Repository python/cpython, pull requests merged in 2018-11, with the labels that each got.

#10270 [3.6] bpo-26558: Fix Py_FatalError() with GIL released (GH-10267)
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge, skip news

#10266 bpo-35081: Add _PyThreadState_GET() internal macro
  Include/internal/pycore_state.h
  Include/pystate.h
  Modules/_testcapimodule.c
  Objects/call.c
  Objects/dictobject.c
  Objects/genobject.c
  Objects/object.c
  Objects/odictobject.c
  Objects/typeobject.c
  Parser/myreadline.c
  Python/_warnings.c
  Python/ceval.c
  Python/context.c
  Python/errors.c
  Python/pylifecycle.c
  Python/pystate.c
  Python/symtable.c
  Python/sysmodule.c
  Python/thread_nt.h
  Python/thread_pthread.h
Labels: CLA signed, awaiting merge, skip news

#10271 bpo-35081: Move accu.h to Include/internal/pycore_accu.h
  Include/internal/pycore_accu.h
  Makefile.pre.in
  Modules/_io/stringio.c
  Modules/_json.c
  Objects/accu.c
  Objects/listobject.c
  Objects/tupleobject.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: CLA signed, awaiting merge, skip news

#10203 [2.7] bpo-32804: Include the context parameter in urlretrieve documentation
  Doc/library/urllib.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#10273 bpo-35081: And pycore_lifecycle.h and pycore_pathconfig.h
  Include/coreconfig.h
  Include/internal/pycore_lifecycle.h
  Include/internal/pycore_pathconfig.h
  Include/internal/pycore_state.h
  Include/pylifecycle.h
  Makefile.pre.in
  Modules/_testcapimodule.c
  Modules/getpath.c
  Modules/main.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Programs/python.c
  Python/coreconfig.c
  Python/import.c
  Python/pathconfig.c
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#10268 bpo-35128: Fix spacing issues in warning.warn messages
  Lib/bz2.py
  Lib/ftplib.py
  Lib/imaplib.py
  Lib/poplib.py
  Lib/smtplib.py
Labels: CLA signed, awaiting changes, needs backport to 3.6, needs backport to 3.7, skip news

#6984 bpo-33578: Add getstate/setstate for CJK codec
  Lib/test/test_io.py
  Lib/test/test_multibytecodec.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-06-08-23-55-34.bpo-33578.7oSsjG.rst
  Modules/cjkcodecs/_codecs_cn.c
  Modules/cjkcodecs/clinic/multibytecodec.c.h
  Modules/cjkcodecs/multibytecodec.c
  Modules/cjkcodecs/multibytecodec.h
Labels: :robot: automerge, CLA signed, awaiting merge

#10280 [3.7] bpo-35128: Fix spacing issues in warning.warn() messages. (GH-10268).
  Lib/ftplib.py
  Lib/imaplib.py
  Lib/poplib.py
  Lib/smtplib.py
Labels: CLA signed, awaiting merge, skip news

#10281 [3.6] bpo-35128: Fix spacing issues in warning.warn() messages. (GH-10268).
  Lib/ftplib.py
  Lib/imaplib.py
  Lib/poplib.py
  Lib/smtplib.py
Labels: CLA signed, awaiting merge, skip news

#10201 bpo-35075: Fix broken url in the pprint documentation
  Doc/library/pprint.rst
  Doc/tools/susp-ignored.csv
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#10283 [3.6] bpo-35075: Fix broken url in the pprint documentation (GH-10201)
  Doc/library/pprint.rst
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting merge, skip news, type-documentation

#10282 [3.7] bpo-35075: Fix broken url in the pprint documentation (GH-10201)
  Doc/library/pprint.rst
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting merge, skip news, type-documentation

#10230 [3.7] Doc: fix asyncio loop.close() description (GH-10229)
  Doc/library/asyncio-eventloop.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10221 [3.7] Include memo in the documented signature of copy.deepcopy() (GH-9456)
  Doc/library/copy.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10222 [3.6] Include memo in the documented signature of copy.deepcopy() (GH-9456)
  Doc/library/copy.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10289 bpo-35139: The `pyexpat` module's macros in `Modules/Setup` now matches `setup.py`
  Misc/NEWS.d/next/Build/2018-11-01-15-01-23.bpo-35139.XZTttb.rst
  Modules/Setup
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#10291 [3.7] closes bpo-35139: The `pyexpat` module's macros in `Modules/Setup` now match `setup.py` (GH-10289)
  Misc/NEWS.d/next/Build/2018-11-01-15-01-23.bpo-35139.XZTttb.rst
  Modules/Setup.dist
Labels: CLA signed, awaiting merge

#10293 [2.7] closes bpo-35139: The `pyexpat` module's macros in `Modules/Setup` now match `setup.py` (GH-10289)
  Misc/NEWS.d/next/Build/2018-11-01-15-01-23.bpo-35139.XZTttb.rst
  Modules/Setup.dist
Labels: CLA signed, awaiting merge

#10290 bpo-33578: Fix getstate/setstate for CJK decoder
  Lib/test/test_multibytecodec.py
  Modules/cjkcodecs/multibytecodec.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#10292 [3.6] closes bpo-35139: The `pyexpat` module's macros in `Modules/Setup` now match `setup.py` (GH-10289)
  Misc/NEWS.d/next/Build/2018-11-01-15-01-23.bpo-35139.XZTttb.rst
  Modules/Setup.dist
Labels: CLA signed, awaiting merge

#10101 bpo-29341: Added path.like object to docstring in posixmodule.c and posixmodule.c.h
  Misc/NEWS.d/next/Core and Builtins/2018-10-25-20-53-32.bpo-29341.jH-AMF.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#10300 bpo-35147: Fix _Py_NO_RETURN for GCC
  Include/pyerrors.h
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-bugfix

#10299 [3.6]bpo-29341: Backport b942707 3.6
  Misc/NEWS.d/next/Core and Builtins/2018-10-25-20-53-32.bpo-29341.jH-AMF.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#10298 [3.7]bpo-29341: Backport b942707 3.7
  Misc/NEWS.d/next/Core and Builtins/2018-10-25-20-53-32.bpo-29341.jH-AMF.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#10301 [3.7] bpo-35147: Fix _Py_NO_RETURN for GCC (GH-10300)
  Include/pyerrors.h
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-bugfix

#10306 Fix a typo about a comma
  Doc/tutorial/errors.rst
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#10309 [3.7] Fix a typo about a comma. (GH-10306)
  Doc/tutorial/errors.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10310 [3.6] Fix a typo about a comma. (GH-10306)
  Doc/tutorial/errors.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10311 [2.7] Fix a typo about a comma. (GH-10306)
  Doc/tutorial/errors.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10303 Doc: -W flag for sphinx-build can be disabled
  Doc/Makefile
Labels: CLA signed, awaiting core review, skip issue, skip news

#6587 bpo-33275: Explain that the orderness of the result is system-dependant
  Doc/library/glob.rst
Labels: CLA signed, awaiting review, skip news

#10319 bpo-35161: Fix stack-use-after-scope in grp.getgr{nam,gid} and pwd.getpw{nam,uid}
  Modules/grpmodule.c
  Modules/pwdmodule.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#10315 [2.7] Docs: fix some wrong words (GH-6987)
  aclocal.m4
  configure
  configure.ac
Labels: CLA signed, awaiting merge, skip issue, skip news

#10316 bpo-35159: Add a link to the devguide in the sidebar of the index (Doc/)
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, skip news

#9423 Doc: Disable smartquotes for zh-tw, fr and ja translations
  Doc/conf.py
  Doc/docutils.conf
Labels: CLA signed, awaiting review, skip issue, skip news

#10325 [3.7] bpo-21263: Skip test_gdb when python has been compiled with LLVM clang (GH-10318)
  Lib/test/test_gdb.py
  Misc/ACKS
  Misc/NEWS.d/next/Tests/2018-11-04-20-17-09.bpo-21263.T3qo9r.rst
Labels: CLA signed, awaiting review

#10326 [3.6] bpo-21263: Skip test_gdb when python has been compiled with LLVM clang (GH-10318)
  Lib/test/test_gdb.py
  Misc/ACKS
  Misc/NEWS.d/next/Tests/2018-11-04-20-17-09.bpo-21263.T3qo9r.rst
Labels: CLA signed, awaiting review

#4268 bpo-31887: Adds documentations for special multipart/signed handling
  Doc/library/email.generator.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#10265 bpo-35118: add indexing details to queue and deque
  Doc/library/collections.rst
  Doc/library/queue.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#4063 bpo-9842: Add cross-reference to the ellipsis object
  Doc/glossary.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#5614 bpo-19675: Terminate processes if construction of a pool is failing.
  Lib/multiprocessing/pool.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2018-02-10-23-41-05.bpo-19675.-dj35-.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#4806 bpo-32285: Add `unicodedata.is_normalized` to check the current norma…
  Doc/library/unicodedata.rst
  Doc/whatsnew/3.8.rst
  Lib/test/test_normalization.py
  Misc/NEWS.d/next/Core and Builtins/2017-12-12-13-43-13.bpo-32285.LzKSwz.rst
  Modules/clinic/unicodedata.c.h
  Modules/unicodedata.c
Labels: CLA signed, awaiting review

#5132 bpo-32512: Add -m option to profile for profiling modules
  Doc/library/profile.rst
  Lib/profile.py
  Lib/test/test_cprofile.py
  Lib/test/test_profile.py
  Misc/NEWS.d/next/Library/2018-01-07-17-43-10.bpo-32512.flC-dE.rst
Labels: CLA signed, awaiting merge

#10284 bpo-35133: Fix mistakes when concatenate string literals on different lines.
  Lib/_pydecimal.py
  Lib/concurrent/futures/thread.py
  Lib/distutils/command/bdist_dumb.py
  Lib/distutils/command/bdist_msi.py
  Lib/distutils/command/bdist_rpm.py
  Lib/distutils/command/bdist_wininst.py
  Lib/distutils/command/build_ext.py
  Lib/email/_header_value_parser.py
  Lib/idlelib/hyperparser.py
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/idle_test/mock_tk.py
  Lib/importlib/abc.py
  Lib/test/test_builtin.py
  Lib/test/test_compile.py
  Lib/test/test_decimal.py
  Lib/test/test_http_cookiejar.py
  Lib/test/test_range.py
  Lib/test/test_smtplib.py
  Lib/test/test_strptime.py
  Lib/trace.py
  Lib/unittest/mock.py
  Modules/_datetimemodule.c
  Modules/_io/textio.c
  Modules/_pickle.c
  Python/import.c
  Tools/scripts/texi2html.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-bugfix

#10334 [3.7] bpo-35133: Fix mistakes when concatenate string literals on different lines. (GH-10284)
  Lib/_pydecimal.py
  Lib/concurrent/futures/thread.py
  Lib/distutils/command/bdist_dumb.py
  Lib/distutils/command/bdist_msi.py
  Lib/distutils/command/bdist_rpm.py
  Lib/distutils/command/bdist_wininst.py
  Lib/distutils/command/build_ext.py
  Lib/email/_header_value_parser.py
  Lib/idlelib/hyperparser.py
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/idle_test/mock_tk.py
  Lib/importlib/abc.py
  Lib/test/test_builtin.py
  Lib/test/test_compile.py
  Lib/test/test_decimal.py
  Lib/test/test_http_cookiejar.py
  Lib/test/test_range.py
  Lib/test/test_smtplib.py
  Lib/test/test_strptime.py
  Lib/trace.py
  Lib/unittest/mock.py
  Modules/_datetimemodule.c
  Modules/_io/textio.c
  Modules/_pickle.c
  Python/import.c
  Tools/scripts/texi2html.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#10335 [3.6] bpo-35133: Fix mistakes when concatenate string literals on different lines. (GH-10284)
  Lib/_pydecimal.py
  Lib/distutils/command/bdist_dumb.py
  Lib/distutils/command/bdist_msi.py
  Lib/distutils/command/bdist_rpm.py
  Lib/distutils/command/bdist_wininst.py
  Lib/distutils/command/build_ext.py
  Lib/email/_header_value_parser.py
  Lib/idlelib/hyperparser.py
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/idle_test/mock_tk.py
  Lib/test/test_compile.py
  Lib/test/test_decimal.py
  Lib/test/test_http_cookiejar.py
  Lib/test/test_range.py
  Lib/test/test_smtplib.py
  Lib/test/test_strptime.py
  Lib/trace.py
  Lib/unittest/mock.py
  Modules/_datetimemodule.c
  Modules/_pickle.c
  Python/import.c
  Tools/scripts/texi2html.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, skip news, type-bugfix

#10332 bpo-35167: Specify program for gzip and json.tool command line options.
  Doc/library/gzip.rst
  Doc/library/json.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#10336 [2.7] bpo-35133: Fix mistakes when concatenate string literals on different lines. (GH-10284) (GH-10335)
  Lib/decimal.py
  Lib/distutils/command/bdist_dumb.py
  Lib/distutils/command/bdist_msi.py
  Lib/distutils/command/bdist_rpm.py
  Lib/distutils/command/bdist_wininst.py
  Lib/distutils/command/build_ext.py
  Lib/idlelib/HyperParser.py
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/idle_test/mock_tk.py
  Lib/test/test_compile.py
  Lib/test/test_decimal.py
  Lib/test/test_strptime.py
  Lib/trace.py
  Python/import.c
  Tools/scripts/texi2html.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#10338 [3.7] bpo-35167: Specify program for json.tool command line options. (GH-10332)
  Doc/library/json.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, skip news, type-documentation

#10339 [3.6] bpo-35167: Specify program for json.tool command line options. (GH-10332) (GH-10338)
  Doc/library/json.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#10118 importlib doc: Fix required Python version of an example
  Doc/library/importlib.rst
Labels: CLA signed, awaiting core review, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#10345 [3.7] [Docs] Fix required version of an example of importlib (GH-10118)
  Doc/library/importlib.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10346 [3.6] [Docs] Fix required version of an example of importlib (GH-10118)
  Doc/library/importlib.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6827 bpo-33462: Add __reversed__ to dict and dict views
  Doc/library/stdtypes.rst
  Doc/whatsnew/3.8.rst
  Include/dictobject.h
  Lib/test/test_collections.py
  Lib/test/test_dict.py
  Lib/test/test_enumerate.py
  Misc/NEWS.d/next/Core and Builtins/2018-05-23-17-18-02.bpo-33462.gurbpbrhe.rst
  Objects/clinic/dictobject.c.h
  Objects/dictobject.c
  Objects/object.c
Labels: CLA signed, awaiting merge

#10323 bpo-35119: Fix RecursionError in example of customizing module attribute access.
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#10348 [3.7] bpo-35119: Fix RecursionError in example of customizing module attribute access. (GH-10323)
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#10350 bpo-35099: Improve the doc about IDLE running user code.
  Doc/library/idle.rst
  Misc/NEWS.d/next/IDLE/2018-11-05-20-43-08.bpo-35099.SVOZXC.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-documentation

#10351 [3.7] bpo-35099: Improve the doc about IDLE running user code. (GH-10350)
  Doc/library/idle.rst
  Misc/NEWS.d/next/IDLE/2018-11-05-20-43-08.bpo-35099.SVOZXC.rst
Labels: CLA signed, awaiting merge, type-documentation

#10352 [3.6] bpo-35099: Improve the doc about IDLE running user code. (GH-10350)
  Doc/library/idle.rst
  Misc/NEWS.d/next/IDLE/2018-11-05-20-43-08.bpo-35099.SVOZXC.rst
Labels: CLA signed, awaiting merge, type-documentation

#10353 bpo-35099: Update idlelib/help.html
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#10354 [3.7] bpo-35099: Update idlelib/help.html (GH-10353)
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, skip news, type-documentation

#10355 [3.6] bpo-35099: Update idlelib/help.html (GH-10353)
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, skip news, type-documentation

#10347 bpo-35171: Fix test_TimeRE_recreation_timezone failure on some systems
  Lib/test/test_strptime.py
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#10357 [3.7] closes bpo-35171: Fix test_TimeRE_recreation_timezone failure on some systems. (GH-10347)
  Lib/test/test_strptime.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#10358 [3.6] closes bpo-35171: Fix test_TimeRE_recreation_timezone failure on some systems. (GH-10347)
  Lib/test/test_strptime.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#10359 [2.7] closes bpo-35171: Fix test_TimeRE_recreation_timezone failure on some systems. (GH-10347)
  Lib/test/test_strptime.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#10362 bpo-35081: Add _PyCoreConfig_AsDict()
  Include/coreconfig.h
  Include/internal/pycore_pathconfig.h
  Modules/_testcapimodule.c
  Python/coreconfig.c
Labels: CLA signed, awaiting merge, skip news

#10356 bpo-23220: Explain how IDLE's Shell displays output
  Doc/library/idle.rst
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2018-11-05-23-23-00.bpo-23220.H3SAWE.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-documentation

#10369 [3.6] bpo-23220: Explain how IDLE's Shell displays output (GH-10356)
  Doc/library/idle.rst
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2018-11-05-23-23-00.bpo-23220.H3SAWE.rst
Labels: CLA signed, awaiting review, type-documentation

#10305 bpo-17560: Too small type for struct.pack/unpack in mutliprocessing.Connection
  Lib/multiprocessing/connection.py
  Misc/NEWS.d/next/Library/2018-11-03-10-12-04.bpo-35152.xpqskp.rst
Labels: CLA signed, awaiting merge

#10371 bpo-35081: Add pycore_fileutils.h
  Include/fileutils.h
  Include/internal/pycore_fileutils.h
  Modules/getpath.c
  Objects/unicodeobject.c
  Python/coreconfig.c
  Python/fileutils.c
  Python/pathconfig.c
Labels: CLA signed, skip news

#10373 bpo-33000: Document that IDLE's shell has no line limit.
  Doc/library/idle.rst
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2018-11-06-23-10-54.bpo-33000.pQasCt.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-documentation

#10374 [3.7] bpo-33000: Document that IDLE's shell has no line limit. (GH-10373)
  Doc/library/idle.rst
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2018-11-06-23-10-54.bpo-33000.pQasCt.rst
Labels: CLA signed, awaiting merge, type-documentation

#10375 [3.6] bpo-33000: Document that IDLE's shell has no line limit. (GH-10373)
  Doc/library/idle.rst
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2018-11-06-23-10-54.bpo-33000.pQasCt.rst
Labels: CLA signed, awaiting merge, type-documentation

#10372 Remove duplicate "Reference Guide" in optparse.rst
  Doc/library/optparse.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#9704 bpo-34898: Add `mtime` argument to `gzip.compress`
  Doc/library/gzip.rst
  Doc/whatsnew/3.8.rst
  Lib/gzip.py
  Lib/test/test_gzip.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-10-04-17-23-43.bpo-34898.Wo2PoJ.rst
Labels: CLA signed, awaiting merge, type-enhancement

#10051 bpo-31553: add --json-lines option to json.tool
  Doc/library/json.rst
  Doc/whatsnew/3.8.rst
  Lib/json/tool.py
  Lib/test/test_json/test_tool.py
  Misc/NEWS.d/next/Library/2018-10-23-14-46-47.bpo-31553.JxRkAW.rst
Labels: CLA signed, awaiting merge

#10219 bpo-34160: Preserves order of minidom of Element attributes
  Doc/library/xml.dom.minidom.rst
  Lib/test/test_minidom.py
  Lib/xml/dom/minidom.py
  Misc/NEWS.d/next/Library/2018-10-27-21-11-42.bpo-34160.UzyPZf.rst
Labels: CLA signed, awaiting merge, type-enhancement

#7253 bpo-2504: Add pgettext() and variants to gettext
  Doc/library/gettext.rst
  Doc/whatsnew/3.8.rst
  Lib/gettext.py
  Lib/test/test_gettext.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-05-30-16-00-06.bpo-2504.BynUvU.rst
  Tools/i18n/msgfmt.py
Labels: CLA signed, awaiting merge, type-enhancement

#10295 bpo-32409 Ensures activate.bat can handle Unicode contents
  Lib/venv/scripts/nt/activate.bat
  Misc/NEWS.d/next/Library/2018-11-02-12-01-00.bpo-32409.MFRX2Q.rst
Labels: CLA signed, awaiting review

#9804 Mark len call as a code snippet in stdtypes.rst
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#9603 Fix markup for xml.sax in 3.8 notes
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8239 Add future_stmt to simple_stmt production list
  Doc/reference/simple_stmts.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#10379 [3.7] Mark -c and -O as command line options in reStructuredText. (GH-10103)
  Doc/reference/executionmodel.rst
  Doc/reference/import.rst
  Doc/reference/simple_stmts.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10380 [3.6] Mark -c and -O as command line options in reStructuredText. (GH-10103)
  Doc/reference/executionmodel.rst
  Doc/reference/import.rst
  Doc/reference/simple_stmts.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10381 [3.7] Mark len call as a code snippet in stdtypes.rst. (GH-9804)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10382 [3.6] Mark len call as a code snippet in stdtypes.rst. (GH-9804)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10383 [3.7] Correct grammar mistakes in string.rst. (GH-9752)
  Doc/library/string.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10384 [3.6] Correct grammar mistakes in string.rst. (GH-9752)
  Doc/library/string.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10385 [2.7] Correct grammar mistakes in string.rst. (GH-9752)
  Doc/library/string.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10386 [3.7] Add future_stmt to simple_stmt production list. (GH-8239)
  Doc/reference/simple_stmts.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10138 Add a reference to the name mangling description in the tutorial to the index
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#10102 glob uses fnmatch.filter instead of fnmatch since 2001
  Doc/library/fnmatch.rst
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#10333 Add link to PEP 525 in Expressions
  Doc/reference/expressions.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#10389 [3.7] Add a reference to the name mangling description in the tutorial to the index. (GH-10138)
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10390 [3.6] Add a reference to the name mangling description in the tutorial to the index. (GH-10138)
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10391 [2.7] Add a reference to the name mangling description in the tutorial to the index. (GH-10138)
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10392 [3.7] glob uses fnmatch.filter instead of fnmatch since 2001. (GH-10102)
  Doc/library/fnmatch.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10393 [3.6] glob uses fnmatch.filter instead of fnmatch since 2001. (GH-10102)
  Doc/library/fnmatch.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10394 [2.7] glob uses fnmatch.filter instead of fnmatch since 2001. (GH-10102)
  Doc/library/fnmatch.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10395 [3.7] Add link to PEP 525 in Expressions. (GH-10333)
  Doc/reference/expressions.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10327 bpo-34726: Fix handling of hash-based pycs in zipimport
  Lib/test/test_cmd_line_script.py
  Lib/zipimport.py
  Misc/NEWS.d/next/Core and Builtins/2018-11-04-18-13-40.bpo-34022.U3btVj.rst
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting merge

#10396 [3.6] Add link to PEP 525 in Expressions. (GH-10333)
  Doc/reference/expressions.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10360 bpo-35015: Doc: Fix internationalisation of the availability directive.
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#10399 [3.7] bpo-35015: Doc: Fix internationalisation of the availability directive. (GH-10360)
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting merge, skip news

#10261 [3.6] bpo-31354: Let configure --with-lto work on all builds
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2017-09-08-11-48-11.bpo-31354.4f-VJK.rst
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#10400 bpo-34011: Fix the construction of subprocess.CalledProcessError in test_venv
  Lib/test/test_venv.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#10401 [3.7] bpo-34011: Fix the construction of subprocess.CalledProcessError in test_venv (GH-10400)
  Lib/test/test_venv.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#10402 [3.6] bpo-34011: Fix the construction of subprocess.CalledProcessError in test_venv (GH-10400)
  Lib/test/test_venv.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#10288 Doc: Make all versions sidebars the same for consistency.
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#10403 bpo-32409: Revert "bpo-32409: Fix regression in activate.bat on international Windows (GH-10295)"
  Lib/venv/scripts/nt/activate.bat
  Misc/NEWS.d/next/Library/2018-11-02-12-01-00.bpo-32409.MFRX2Q.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#10405 [3.7] Revert "bpo-32409: Fix regression in activate.bat on international Windows (GH-10295)" (GH-10403)
  Lib/venv/scripts/nt/activate.bat
  Misc/NEWS.d/next/Library/2018-11-02-12-01-00.bpo-32409.MFRX2Q.rst
Labels: CLA signed, awaiting merge

#10388 [2.7] Add future_stmt to simple_stmt production list. (GH-8239)
  Doc/reference/simple_stmts.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10387 [3.6] Add future_stmt to simple_stmt production list. (GH-8239)
  Doc/reference/simple_stmts.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#9823 bpo-34966: Improve support of method aliases in pydoc.
  Lib/pydoc.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2018-10-12-18-57-52.bpo-34966.WZeBHO.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#10407 [3.7] bpo-34966: Improve support of method aliases in pydoc. (GH-9823)
  Lib/pydoc.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2018-10-12-18-57-52.bpo-34966.WZeBHO.rst
Labels: CLA signed, awaiting merge

#10408 [3.6] bpo-34966: Improve support of method aliases in pydoc. (GH-9823)
  Lib/pydoc.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2018-10-12-18-57-52.bpo-34966.WZeBHO.rst
Labels: CLA signed, awaiting merge

#10409 [3.7] Doc: Make all versions sidebars the same for consistency. (GH-10288)
  Doc/tools/templates/indexsidebar.html
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#10410 [2.7] Doc: Make all versions sidebars the same for consistency. (GH-10288)
  Doc/tools/templates/indexsidebar.html
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#10028 [Skip Issue] Replace dead code with an assertion in winreg.c
  PC/winreg.c
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#10212 bpo-35065: Remove `StreamReaderProtocol._untrack_reader`
  Lib/asyncio/streams.py
  Lib/asyncio/subprocess.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2018-10-29-10-18-31.bpo-35065.CulMN8.rst
Labels: CLA signed, awaiting merge

#10418 bpo-35193: Fix an off by one error in the RETURN_VALUE case.
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2018-11-08-15-00-58.bpo-35193.HzPS6R.rst
  Python/peephole.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#10421 [3.7] bpo-35193: Fix an off by one error in the RETURN_VALUE case. (GH-10418)
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2018-11-08-15-00-58.bpo-35193.HzPS6R.rst
  Python/peephole.c
Labels: CLA signed, awaiting merge, type-bugfix

#9190 bpo-24412: Adds cleanUps for setUpClass and setUpModule.
  Doc/library/unittest.rst
  Doc/whatsnew/3.8.rst
  Lib/unittest/__init__.py
  Lib/unittest/case.py
  Lib/unittest/suite.py
  Lib/unittest/test/test_runner.py
  Misc/NEWS.d/next/Library/2018-09-11-10-51-16.bpo-24412.i-F_E5.rst
Labels: CLA signed, awaiting changes

#10420 bpo-35194: Fix a wrong constant in cp932 codec
  Modules/cjkcodecs/_codecs_jp.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#10422 [3.6] bpo-35193: Fix an off by one error in the RETURN_VALUE case. (GH-10418)
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2018-11-08-23-00-04.bpo-35193.WK2PDg.rst
  Python/peephole.c
Labels: CLA signed, awaiting merge, type-bugfix

#10424 [3.6] bpo-35194: Fix a wrong constant in cp932 codec (GH-10420)
  Modules/cjkcodecs/_codecs_jp.c
Labels: CLA signed, awaiting merge, skip news

#10423 [3.7] bpo-35194: Fix a wrong constant in cp932 codec (GH-10420)
  Modules/cjkcodecs/_codecs_jp.c
Labels: CLA signed, awaiting merge, skip news

#10425 Fixing wording in comment.
  Modules/mathmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10426 Cleanup and improve the regex tokenizer example.
  Doc/library/re.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#10429 Optimize set.pop() to advance a pointer instead of indexing.
  Objects/setobject.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-performance

#10430 Hoist the float conversion out of the inner loop.
  Lib/random.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-performance

#10363 bpo-35081: Internal headers require Py_BUILD_CORE
  Include/internal/pycore_accu.h
  Include/internal/pycore_atomic.h
  Include/internal/pycore_ceval.h
  Include/internal/pycore_condvar.h
  Include/internal/pycore_context.h
  Include/internal/pycore_getopt.h
  Include/internal/pycore_gil.h
  Include/internal/pycore_hamt.h
  Include/internal/pycore_hash.h
  Include/internal/pycore_lifecycle.h
  Include/internal/pycore_mem.h
  Include/internal/pycore_pathconfig.h
  Include/internal/pycore_state.h
  Include/internal/pycore_warnings.h
  Modules/Setup
  setup.py
Labels: CLA signed, skip news

#10434 bpo-35199: Add an internal _PyTuple_ITEMS() macro
  Include/tupleobject.h
  Modules/_functoolsmodule.c
  Modules/_testcapimodule.c
  Objects/call.c
  Objects/codeobject.c
  Objects/descrobject.c
  Objects/funcobject.c
  Python/ceval.c
  Python/getargs.c
Labels: CLA signed, awaiting merge, skip news

#10404 [3.6] Doc: Make all versions sidebars the same for consistency. (GH-10288)
  Doc/tools/templates/indexsidebar.html
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#10397 Correct a typo in the Unittest documentation
  Doc/library/unittest.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#10439 [3.7] Correct a typo in the Unittest documentation (GH-10397)
  Doc/library/unittest.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10440 [3.6] Correct a typo in the Unittest documentation (GH-10397)
  Doc/library/unittest.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10287 Doc: Simplify Copyright line in README
  README.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10445 bpo-35202: Remove unused imports in Lib directory
  Lib/shutil.py
  Lib/trace.py
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip news

#10433 [2.7] bpo-35194: Fix a wrong constant in cp932 codec (GH-10420)
  Modules/cjkcodecs/_codecs_jp.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#10438 bpo-35202: Remove unused imports in idle lib package
  Lib/idlelib/codecontext.py
  Lib/idlelib/filelist.py
  Lib/idlelib/idle_test/test_config.py
  Lib/idlelib/idle_test/test_config_key.py
  Lib/idlelib/idle_test/test_rpc.py
  Lib/idlelib/pyparse.py
  Misc/NEWS.d/next/IDLE/2018-11-10-09-10-54.bpo-35202.TeJJrt.rst
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7

#10447 [3.7] bpo-35202: Remove unused imports in idlelib (GH-10438)
  Lib/idlelib/codecontext.py
  Lib/idlelib/filelist.py
  Lib/idlelib/idle_test/test_config.py
  Lib/idlelib/idle_test/test_config_key.py
  Lib/idlelib/idle_test/test_rpc.py
  Lib/idlelib/pyparse.py
  Misc/NEWS.d/next/IDLE/2018-11-10-09-10-54.bpo-35202.TeJJrt.rst
Labels: CLA signed, awaiting merge

#10448 [3.6] bpo-35202: Remove unused imports in idlelib (GH-10438)
  Lib/idlelib/codecontext.py
  Lib/idlelib/filelist.py
  Lib/idlelib/idle_test/test_config.py
  Lib/idlelib/idle_test/test_config_key.py
  Lib/idlelib/idle_test/test_rpc.py
  Lib/idlelib/pyparse.py
  Misc/NEWS.d/next/IDLE/2018-11-10-09-10-54.bpo-35202.TeJJrt.rst
Labels: CLA signed, awaiting merge

#10457 [3.7] bpo-34864: Document two IDLE on MacOS issues. (GH-10456)
  Doc/library/idle.rst
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2018-11-10-21-27-25.bpo-34864.Ci-G2q.rst
Labels: CLA signed, awaiting merge, type-documentation

#10458 [3.6] bpo-34864: Document two IDLE on MacOS issues. (GH-10456)
  Doc/library/idle.rst
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2018-11-10-21-27-25.bpo-34864.Ci-G2q.rst
Labels: CLA signed, awaiting merge, type-documentation

#10431 dict insertion order is guaranteed since 3.7
  Doc/library/collections.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#10465 [3.7] dict insertion order is guaranteed since 3.7 (GH-10431)
  Doc/library/collections.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#7252 bpo-33699: Describe try's else clause with the rest of the try clause
  Doc/reference/compound_stmts.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#10467 [3.7] bpo-33699: Describe try's else clause with the rest of the try clause (GH-7252)
  Doc/reference/compound_stmts.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation
