Repository python/cpython, pull requests merged in 2018-04, with the labels that each got.

#6322 [2.7] bpo-33132: Fix reference counting issues in the compiler. (GH-6209).
  Python/compile.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#6320 [3.7] bpo-33188: Allow dynamic creation of generic dataclasses (GH-6319)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
Labels: CLA signed, awaiting review, skip news

#6334 bpo-20104: Add os.posix_spawn documentation.
  Doc/library/os.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#6336 [3.7] bpo-20104: Add os.posix_spawn documentation. (GH-6334)
  Doc/library/os.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6339 [2.7] bpo-27212: Modify islice recipe to consume initial values prece…
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
  Misc/NEWS.d/next/Documentation/2018-03-22-19-23-04.bpo-27212.wrE5KR.rst
Labels: awaiting merge, type-documentation

#6344 bpo-33204: IDLE: consistently color invalid string prefixes
  Lib/idlelib/colorizer.py
  Misc/NEWS.d/next/IDLE/2018-04-02-00-28-13.bpo-33204.NBsuIv.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#6345 [3.7] bpo-33204: IDLE: consistently color invalid string prefixes (GH-6344)
  Lib/idlelib/colorizer.py
  Misc/NEWS.d/next/IDLE/2018-04-02-00-28-13.bpo-33204.NBsuIv.rst
Labels: CLA signed, awaiting merge

#6346 [3.6] bpo-33204: IDLE: consistently color invalid string prefixes (GH-6344)
  Lib/idlelib/colorizer.py
  Misc/NEWS.d/next/IDLE/2018-04-02-00-28-13.bpo-33204.NBsuIv.rst
Labels: CLA signed, awaiting merge

#6347 bpo-33204: IDLE - revise and extend colorizer test
  Lib/idlelib/colorizer.py
  Misc/NEWS.d/next/IDLE/2018-04-02-00-28-13.bpo-33204.NBsuIv.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#6348 [3.7] bpo-33204: IDLE - revise and extend colorizer test. (GH-6347)
  Lib/idlelib/colorizer.py
  Misc/NEWS.d/next/IDLE/2018-04-02-00-28-13.bpo-33204.NBsuIv.rst
Labels: CLA signed, awaiting merge

#6349 [3.6] bpo-33204: IDLE - revise and extend colorizer test. (GH-6347)
  Lib/idlelib/colorizer.py
  Misc/NEWS.d/next/IDLE/2018-04-02-00-28-13.bpo-33204.NBsuIv.rst
Labels: CLA signed, awaiting merge

#6352 bpo-29922: Improve error messages in 'async with'
  Lib/test/test_coroutines.py
  Misc/NEWS.d/next/Core and Builtins/2018-04-03-00-30-25.bpo-29922.CdLuMl.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-enhancement

#6341 bpo-33199: Initialize ma_version_tag in PyDict_Copy
  Misc/NEWS.d/next/Core and Builtins/2018-04-02-09-32-40.bpo-33199.TPnxQu.rst
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6335 bpo-33202 fix os.walk mentioning os.listdir instead of os.scandir
  Doc/library/os.rst
Labels: CLA not signed, awaiting review, needs backport to 3.6, needs backport to 3.7, skip news

#6357 [3.7] bpo-33199: Initialize ma_version_tag in PyDict_Copy (GH-6341)
  Misc/NEWS.d/next/Core and Builtins/2018-04-02-09-32-40.bpo-33199.TPnxQu.rst
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#6358 [3.6] bpo-33199: Initialize ma_version_tag in PyDict_Copy (GH-6341)
  Misc/NEWS.d/next/Core and Builtins/2018-04-02-09-32-40.bpo-33199.TPnxQu.rst
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#6359 [3.7] closes bpo-33202: fix os.walk mentioning os.listdir instead of os.scandir (GH-6335)
  Doc/library/os.rst
Labels: CLA not signed, awaiting merge, skip news

#6360 [3.6] closes bpo-33202: fix os.walk mentioning os.listdir instead of os.scandir (GH-6335)
  Doc/library/os.rst
Labels: CLA not signed, awaiting merge, skip news

#5001 bpo-32360: Remove object_pairs_hook=OrderedDict examples
  Doc/library/json.rst
  Lib/json/__init__.py
  Lib/json/decoder.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, skip news, type-documentation

#6361 [3.7] bpo-32360: Remove object_pairs_hook=OrderedDict examples (GH-5001)
  Doc/library/json.rst
  Lib/json/__init__.py
  Lib/json/decoder.py
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6363 bpo-33209: End framing at the end of C implementation of pickle.Pickler.dump().
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2018-04-03-10-37-13.bpo-33209.9sGWE_.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6366 [3.7] bpo-33209: End framing at the end of C implementation of pickle.Pickler.dump(). (GH-6363)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2018-04-03-10-37-13.bpo-33209.9sGWE_.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting review, type-bugfix

#6367 [3.6] bpo-33209: End framing at the end of C implementation of pickle.Pickler.dump(). (GH-6363)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2018-04-03-10-37-13.bpo-33209.9sGWE_.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting merge, type-bugfix

#4973 bpo-32337: Update tutorial and documentation related with dict order.
  Doc/library/stdtypes.rst
  Doc/tutorial/datastructures.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2017-12-22-17-29-37.bpo-32337.eZe-ID.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-documentation

#6329 bpo-33195: Doc: Deprecate Py_UNICODE in c-api/arg
  Doc/c-api/arg.rst
  Misc/NEWS.d/next/Documentation/2018-04-01-14-30-36.bpo-33195.dRS-XX.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-documentation

#6368 [3.7] bpo-32337: Update documentats about dict order (GH-4973)
  Doc/library/stdtypes.rst
  Doc/tutorial/datastructures.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2017-12-22-17-29-37.bpo-32337.eZe-ID.rst
Labels: CLA signed, awaiting merge, type-documentation

#6369 [3.7] bpo-33195: Doc: Deprecate Py_UNICODE in c-api/arg (GH-6329)
  Doc/c-api/arg.rst
  Misc/NEWS.d/next/Documentation/2018-04-01-14-30-36.bpo-33195.dRS-XX.rst
Labels: CLA signed, awaiting merge, type-documentation

#6355 bpo-23403: Bump pickle.DEFAULT_PROTOCOL to 4
  Doc/library/pickle.rst
  Doc/whatsnew/3.8.rst
  Lib/pickle.py
  Misc/NEWS.d/next/Library/2018-04-02-16-10-12.bpo-23403.KG7ADV.rst
  Modules/_pickle.c
  Modules/clinic/_pickle.c.h
Labels: CLA signed, awaiting merge

#6353 [3.7] bpo-29922: Improve error messages in 'async with' (GH-6352)
  Lib/test/test_coroutines.py
  Misc/NEWS.d/next/Core and Builtins/2018-04-03-00-30-25.bpo-29922.CdLuMl.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge, type-enhancement

#6354 [3.6] bpo-29922: Improve error messages in 'async with' (GH-6352)
  Lib/test/test_coroutines.py
  Misc/NEWS.d/next/Core and Builtins/2018-04-03-00-30-25.bpo-29922.CdLuMl.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge, type-enhancement

#6370 bpo-29922: Add more tests for error messages in 'async with'.
  Lib/test/test_coroutines.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-tests

#6356 bpo-33207: Call super in Generic.__init_subclass__
  Lib/test/test_typing.py
  Lib/typing.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#6371 [3.7] bpo-29922: Add more tests for error messages in 'async with'. (GH-6370)
  Lib/test/test_coroutines.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#6372 [3.7] bpo-33207: Call super in Generic.__init_subclass__ (GH-6356)
  Lib/test/test_typing.py
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip news

#6376 bpo-32873: Remove a name hack for generic aliases in typing module
  Lib/test/test_typing.py
  Lib/typing.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#6378 [3.7] bpo-32873: Remove a name hack for generic aliases in typing module (GH-6376)
  Lib/test/test_typing.py
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip news

#6379 Add a Travis webhook for Zulip
  .travis.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#6382 [3.6] bpo-33195: Doc: Deprecate Py_UNICODE in c-api/arg (GH-6329)
  Doc/c-api/arg.rst
  Misc/NEWS.d/next/Documentation/2018-04-01-14-30-36.bpo-33195.dRS-XX.rst
Labels: CLA signed, awaiting merge, type-documentation

#6380 Clean up and enhance frozen dataclass tests.
  Lib/test/test_dataclasses.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#6385 [3.7] Clean up and enhance frozen dataclass tests. (GH-6380)
  Lib/test/test_dataclasses.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#6338 bpo-33203: Ensure random.choice always raises IndexError on empty sequence
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2018-04-05-11-09-45.bpo-33203.Hje9Py.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#6387 [3.7] bpo-33203: Ensure random.choice always raises IndexError on empty sequence (GH-6338)
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2018-04-05-11-09-45.bpo-33203.Hje9Py.rst
Labels: CLA signed, awaiting review

#6388 [3.6] bpo-33203: Ensure random.choice always raises IndexError on empty sequence (GH-6338)
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2018-04-05-11-09-45.bpo-33203.Hje9Py.rst
Labels: CLA signed, awaiting review

#6384 bpo-15817: Expose command documentation to gdb help
  Misc/gdbinit
Labels: CLA signed, awaiting review, skip news

#6390 [3.7] bpo-33224: PEP 479 fix for difflib.mdiff() (GH-6381)
  Lib/difflib.py
  Lib/test/test_difflib.py
  Misc/NEWS.d/next/Library/2018-04-04-23-41-30.bpo-33224.pyR0jB.rst
Labels: CLA signed, awaiting review

#6386 bpo-33231: Fix potential leak in normalizestring()
  Misc/NEWS.d/next/Core and Builtins/2018-04-05-22-20-44.bpo-33231.3Jmo0q.rst
  Python/codecs.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6393 [3.7] bpo-33231: Fix potential leak in normalizestring() (GH-6386)
  Misc/NEWS.d/next/Core and Builtins/2018-04-05-22-20-44.bpo-33231.3Jmo0q.rst
  Python/codecs.c
Labels: CLA signed, awaiting merge, type-bugfix

#6394 [3.6] bpo-33231: Fix potential leak in normalizestring() (GH-6386)
  Misc/NEWS.d/next/Core and Builtins/2018-04-05-22-20-44.bpo-33231.3Jmo0q.rst
  Python/codecs.c
Labels: CLA signed, awaiting merge, type-bugfix

#6396 fixed capitalization of class name
  Doc/library/http.server.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#6399 [3.7] bpo-29673: fix gdb scripts pystack and pystackv (GH-6126)
  Misc/ACKS
  Misc/NEWS.d/next/Tools-Demos/2018-03-16-17-25-05.bpo-29673.m8QtaW.rst
  Misc/gdbinit
  Python/ceval.c
Labels: CLA signed, awaiting review

#6400 [3.6] bpo-29673: fix gdb scripts pystack and pystackv (GH-6126)
  Misc/ACKS
  Misc/NEWS.d/next/Tools-Demos/2018-03-16-17-25-05.bpo-29673.m8QtaW.rst
  Misc/gdbinit
  Python/ceval.c
Labels: CLA signed, awaiting review

#6402 bpo-33169: Remove values of `None` from sys.path_importer_cache when invalidating caches
  Doc/library/importlib.rst
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_importlib/import_/test_path.py
  Lib/test/test_importlib/test_api.py
  Misc/NEWS.d/next/Library/2018-04-06-14-56-26.bpo-33169.ByhDqb.rst
  Python/importlib_external.h
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6403 [3.7] bpo-33169: Remove values of `None` from sys.path_importer_cache when invalidating caches (GH-6402)
  Doc/library/importlib.rst
  Doc/whatsnew/3.7.rst
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_importlib/import_/test_path.py
  Lib/test/test_importlib/test_api.py
  Misc/NEWS.d/next/Library/2018-04-06-14-56-26.bpo-33169.ByhDqb.rst
  Python/importlib_external.h
Labels: CLA signed, awaiting merge

#5179 bpo-8243: Doc patch for curses.window.addstr and curses.window.addch
  Doc/library/curses.rst
  Misc/NEWS.d/next/Documentation/2018-01-13-20-30-53.bpo-8243.s98r28.rst
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-documentation

#6404 [3.7] bpo-8243: Doc patch for curses.window.addstr and curses.window.addch (GH-5179)
  Doc/library/curses.rst
  Misc/NEWS.d/next/Documentation/2018-01-13-20-30-53.bpo-8243.s98r28.rst
Labels: CLA signed, awaiting review, type-documentation

#6406 [3.6] bpo-8243: Doc patch for curses.window.addstr and curses.window.addch (GH-5179)
  Doc/library/curses.rst
  Misc/NEWS.d/next/Documentation/2018-01-13-20-30-53.bpo-8243.s98r28.rst
Labels: CLA signed, awaiting review, type-documentation

#6405 [2.7] bpo-8243: Doc patch for curses.window.addstr and curses.window.addch (GH-5179)
  Doc/library/curses.rst
  Misc/NEWS.d/next/Documentation/2018-01-13-20-30-53.bpo-8243.s98r28.rst
Labels: CLA signed, awaiting review, type-documentation

#6407 bpo-33184: Update macOS installer build to use OpenSSL 1.1.0h.
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2018-04-07-00-51-34.bpo-33184.3j208P.rst
Labels: CLA signed, OS-mac, awaiting merge, needs backport to 3.7

#6409 [3.7] bpo-33184: Update macOS installer build to use OpenSSL 1.1.0h. (GH-6407)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2018-04-07-00-51-34.bpo-33184.3j208P.rst
Labels: CLA signed, awaiting review

#6408 [3.6] bpo-33184: Update macOS installer build to use OpenSSL 1.0.2o.
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2018-04-07-00-58-50.bpo-33184.rMTiqu.rst
Labels: CLA signed, awaiting merge

#6337 bpo-33201: Modernize "Extension types" doc
  Doc/extending/index.rst
  Doc/extending/newtypes.rst
  Doc/extending/newtypes_tutorial.rst
  Doc/includes/custom.c
  Doc/includes/custom2.c
  Doc/includes/custom3.c
  Doc/includes/custom4.c
  Doc/includes/noddy.c
  Doc/includes/noddy2.c
  Doc/includes/noddy3.c
  Doc/includes/noddy4.c
  Doc/includes/shoddy.c
  Doc/includes/sublist.c
  Doc/includes/test.py
  Misc/NEWS.d/next/Documentation/2018-04-01-21-03-41.bpo-33201.aa8Lkl.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#6411 [3.7] bpo-33201: Modernize "Extension types" doc (GH-6337)
  Doc/extending/index.rst
  Doc/extending/newtypes.rst
  Doc/extending/newtypes_tutorial.rst
  Doc/includes/custom.c
  Doc/includes/custom2.c
  Doc/includes/custom3.c
  Doc/includes/custom4.c
  Doc/includes/noddy.c
  Doc/includes/noddy2.c
  Doc/includes/noddy3.c
  Doc/includes/noddy4.c
  Doc/includes/shoddy.c
  Doc/includes/sublist.c
  Doc/includes/test.py
  Misc/NEWS.d/next/Documentation/2018-04-01-21-03-41.bpo-33201.aa8Lkl.rst
Labels: CLA signed, awaiting review

#6412 [3.6] bpo-33201: Modernize "Extension types" doc (GH-6337)
  Doc/extending/index.rst
  Doc/extending/newtypes.rst
  Doc/extending/newtypes_tutorial.rst
  Doc/includes/custom.c
  Doc/includes/custom2.c
  Doc/includes/custom3.c
  Doc/includes/custom4.c
  Doc/includes/noddy.c
  Doc/includes/noddy2.c
  Doc/includes/noddy3.c
  Doc/includes/noddy4.c
  Doc/includes/shoddy.c
  Doc/includes/sublist.c
  Doc/includes/test.py
  Misc/NEWS.d/next/Documentation/2018-04-01-21-03-41.bpo-33201.aa8Lkl.rst
Labels: CLA signed, awaiting merge

#6413 bpo-29613: Added support for SameSite cookies
  Doc/library/http.cookies.rst
  Lib/http/cookies.py
  Lib/test/test_http_cookies.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-04-07-13-49-39.bpo-29613.r6FDnB.rst
Labels: CLA signed, awaiting merge

#6415 Add a prepend() recipe to teach a chain() idiom
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#6421 [3.7] Add a prepend() recipe to teach a chain() idiom (GH-6415)
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#6422 [3.6] Add a prepend() recipe to teach a chain() idiom (GH-6415)
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#6414 Update docstring of tempfile._RandomNameSequence
  Lib/tempfile.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#6425 [3.7] Update docstring of tempfile._RandomNameSequence (GH-6414)
  Lib/tempfile.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6426 [3.6] Update docstring of tempfile._RandomNameSequence (GH-6414)
  Lib/tempfile.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6427 Fix misleading docsting of shelve.open().
  Lib/shelve.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#6423 [3.7] Improve highlighting of some code blocks. (GH-6401)
  Doc/distutils/configfile.rst
  Doc/distutils/packageindex.rst
  Doc/extending/embedding.rst
  Doc/extending/extending.rst
  Doc/extending/newtypes_tutorial.rst
  Doc/faq/library.rst
  Doc/faq/windows.rst
  Doc/howto/argparse.rst
  Doc/howto/clinic.rst
  Doc/howto/instrumentation.rst
  Doc/howto/logging-cookbook.rst
  Doc/howto/logging.rst
  Doc/howto/regex.rst
  Doc/howto/unicode.rst
  Doc/howto/urllib2.rst
  Doc/install/index.rst
  Doc/library/faulthandler.rst
  Doc/library/json.rst
  Doc/library/logging.config.rst
  Doc/library/logging.rst
  Doc/library/site.rst
  Doc/library/timeit.rst
  Doc/library/tokenize.rst
  Doc/library/zipapp.rst
  Doc/tutorial/appendix.rst
  Doc/using/cmdline.rst
  Doc/using/unix.rst
  Doc/using/windows.rst
  Doc/whatsnew/3.6.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6424 [3.6] Improve highlighting of some code blocks. (GH-6401).
  Doc/distutils/configfile.rst
  Doc/distutils/packageindex.rst
  Doc/extending/embedding.rst
  Doc/extending/extending.rst
  Doc/extending/newtypes_tutorial.rst
  Doc/faq/library.rst
  Doc/faq/windows.rst
  Doc/howto/argparse.rst
  Doc/howto/clinic.rst
  Doc/howto/instrumentation.rst
  Doc/howto/logging-cookbook.rst
  Doc/howto/logging.rst
  Doc/howto/regex.rst
  Doc/howto/unicode.rst
  Doc/howto/urllib2.rst
  Doc/install/index.rst
  Doc/library/faulthandler.rst
  Doc/library/json.rst
  Doc/library/logging.config.rst
  Doc/library/logging.rst
  Doc/library/site.rst
  Doc/library/timeit.rst
  Doc/library/tokenize.rst
  Doc/library/zipapp.rst
  Doc/tutorial/appendix.rst
  Doc/using/cmdline.rst
  Doc/using/unix.rst
  Doc/using/windows.rst
  Doc/whatsnew/3.6.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6429 [3.7] Fix misleading docsting of shelve.open(). (GH-6427)
  Lib/shelve.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6430 [3.6] Fix misleading docsting of shelve.open(). (GH-6427)
  Lib/shelve.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#5827 bpo-32759: Free unused arenas in multiprocessing.heap
  Lib/multiprocessing/heap.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2018-02-23-12-21-41.bpo-32759.M-y9GA.rst
Labels: CLA signed, awaiting merge

#6120 bpo-33031: Remove dead code in C implementation of OrderedDict.
  Objects/odictobject.c
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news

#6259 bpo-31920: Fixed handling directories as arguments in the pygettext script.
  Lib/test/test_tools/test_i18n.py
  Misc/ACKS
  Misc/NEWS.d/next/Tools-Demos/2018-03-26-18-54-24.bpo-31920.u_WKsT.rst
  Tools/i18n/pygettext.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6431 [3.7] bpo-31920: Fixed handling directories as arguments in the ``pygettext`` script. (GH-6259)
  Lib/test/test_tools/test_i18n.py
  Misc/ACKS
  Misc/NEWS.d/next/Tools-Demos/2018-03-26-18-54-24.bpo-31920.u_WKsT.rst
  Tools/i18n/pygettext.py
Labels: CLA signed, awaiting merge, type-bugfix

#6432 [3.6] bpo-31920: Fixed handling directories as arguments in the ``pygettext`` script. (GH-6259)
  Lib/test/test_tools/test_i18n.py
  Misc/ACKS
  Misc/NEWS.d/next/Tools-Demos/2018-03-26-18-54-24.bpo-31920.u_WKsT.rst
  Tools/i18n/pygettext.py
Labels: CLA signed, awaiting merge, type-bugfix

#6433 [3.7] bpo-33031: Remove dead code in C implementation of OrderedDict. (GH-6120)
  Objects/odictobject.c
Labels: CLA signed, awaiting merge, skip news

#6417 bpo-31201: Clarify command to re-run failing test(s) with example
  README.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#6437 [3.7] bpo-31201: Clarify command to re-run failing test(s) with example (GH-6417)
  README.rst
Labels: CLA signed, awaiting review, skip news

#6438 [3.6] bpo-31201: Clarify command to re-run failing test(s) with example (GH-6417)
  README.rst
Labels: CLA signed, awaiting review, skip news

#6440 [3.7] bpo-33253: Fix xxsubtype.bench() to accept correct str signature. (GH-6439)
  Modules/xxsubtype.c
Labels: CLA not signed, awaiting merge, skip news, type-bugfix

#6441 [3.6] bpo-33253: Fix xxsubtype.bench() to accept correct str signature. (GH-6439)
  Modules/xxsubtype.c
Labels: CLA not signed, awaiting merge, skip news, type-bugfix

#6436 [2.7] bpo-31920: Fixed handling directories as arguments in the ``pygettext`` script. (GH-6259)
  Misc/ACKS
  Misc/NEWS.d/next/Tools-Demos/2018-03-26-18-54-24.bpo-31920.u_WKsT.rst
  Tools/i18n/pygettext.py
Labels: CLA signed, awaiting merge, type-bugfix

#6445 [3.7] bpo-33097: Fix submit accepting callable after executor shutdown by interpreter exit (GH-6144)
  Lib/concurrent/futures/process.py
  Lib/concurrent/futures/thread.py
  Lib/test/test_concurrent_futures.py
  Misc/NEWS.d/next/Library/2018-03-18-16-48-23.bpo-33097.Yl4gI2.rst
Labels: CLA signed, awaiting review

#6447 bpo-33260: Regenerate token.py after removing ASYNC and AWAIT.
  Doc/reference/expressions.rst
  Lib/token.py
  Lib/tokenize.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-bugfix

#6449 [3.7] bpo-33260: Regenerate token.py after removing ASYNC and AWAIT. (GH-6447)
  Doc/reference/expressions.rst
  Lib/token.py
  Lib/tokenize.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#6435 Fix error messages in argparse examples.
  Doc/library/argparse.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#6451 [3.7] Fix error messages in argparse examples (GH-6435)
  Doc/library/argparse.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6452 [3.6] Fix error messages in argparse examples (GH-6435)
  Doc/library/argparse.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6392 [3.7] bpo-33217: deprecate non-Enum lookups in Enums
  Doc/library/enum.rst
  Doc/whatsnew/3.7.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2018-04-05-13-36-09.bpo-33217.FfOKDI.rst
Labels: CLA signed, awaiting merge

#1280 itemgetter add dict example
  Doc/library/operator.rst
Labels: CLA not signed, awaiting merge, skip issue, skip news

#6463 bpo-33184 Update Windows installer to OpenSSL 1.1.0h
  Misc/NEWS.d/next/Windows/2018-04-13-11-28-55.bpo-33184.7YhqQE.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7, type-security

#6464 bpo-33184 Update Windows installer to OpenSSL 1.0.2o
  Misc/NEWS.d/next/Windows/2018-04-13-11-39-28.bpo-33184.aEohx0.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, OS-windows, awaiting merge, type-security

#6468 [3.7] bpo-33184: Update Windows installer to OpenSSL 1.1.0h (GH-6463)
  Misc/NEWS.d/next/Windows/2018-04-13-11-28-55.bpo-33184.7YhqQE.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting merge, type-security

#6469 [2.7] Backport macOS universal build and installer fixes from 3.6.
  Mac/BuildScript/README.txt
  Mac/BuildScript/build-installer.py
  Mac/BuildScript/issue19373_tk_8_5_15_source.patch
  Mac/BuildScript/openssl_sdk_makedepend.patch
  Mac/BuildScript/resources/Conclusion.rtf
  Mac/BuildScript/resources/ReadMe.rtf
  Mac/BuildScript/resources/Welcome.rtf
  Mac/BuildScript/resources/install_certificates.command
  Mac/BuildScript/scripts/postflight.documentation
  Mac/BuildScript/tk868_on_10_8_10_9.patch
  Mac/IDLE/Makefile.in
  Mac/README
  Misc/NEWS.d/next/macOS/2018-04-14-08-49-40.bpo-11485.oALntE.rst
  Misc/NEWS.d/next/macOS/2018-04-14-08-54-31.bpo-19019.mRkb0w.rst
  Misc/NEWS.d/next/macOS/2018-04-14-08-55-36.bpo-24414.Z5A1cS.rst
  Misc/NEWS.d/next/macOS/2018-04-14-08-56-20.bpo-32726.Mticyn.rst
  configure
  configure.ac
Labels: CLA signed, awaiting merge, skip issue

#6470 [2.7] Fix errant NEWS item: bpo-19019 -> bpo-17128
  Misc/NEWS.d/next/macOS/2018-04-14-08-54-31.bpo-17128.mRkb0w.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#6466 bpo-33176: Add a toreadonly() method to memoryviews.
  Doc/library/stdtypes.rst
  Lib/test/test_buffer.py
  Lib/test/test_memoryview.py
  Misc/NEWS.d/next/Core and Builtins/2018-04-13-22-31-09.bpo-33176.PB9com.rst
  Objects/memoryobject.c
Labels: CLA signed, awaiting merge, type-enhancement

#6419 bpo-33185: Fix regression in pydoc CLI sys.path handling
  Doc/whatsnew/3.7.rst
  Lib/pydoc.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2018-04-08-22-54-07.bpo-33185.Id-Ba9.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6476 [3.7] bpo-33185: Fix regression in pydoc CLI sys.path handling (GH-6419)
  Doc/whatsnew/3.7.rst
  Lib/pydoc.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2018-04-08-22-54-07.bpo-33185.Id-Ba9.rst
Labels: CLA signed, awaiting merge

#6477 bpo-33185: Improve wording and markup
  Doc/whatsnew/3.7.rst
  Lib/pydoc.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2018-04-08-22-54-07.bpo-33185.Id-Ba9.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6478 [3.7] bpo-33185: Improve wording and markup (GH-6477)
  Doc/whatsnew/3.7.rst
  Lib/pydoc.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2018-04-08-22-54-07.bpo-33185.Id-Ba9.rst
Labels: CLA signed, awaiting merge

#6472 bpo-33270: Intern names for all anonymous code objects
  Misc/NEWS.d/next/Core and Builtins/2018-04-14-13-12-50.bpo-33270.UmVV6i.rst
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
Labels: CLA signed, awaiting merge, type-performance

#4288 bpo-31947: names=None case is not handled by EnumMeta._create_ method
  Lib/enum.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-bugfix

#6454 bpo-33264: Remove might-be-deprecated urllib.request.urlretrieve function reference
  Doc/howto/urllib2.rst
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7, skip news

#6486 [3.7] bpo-33264 Remove to-be-deprecated urllib.request.urlretrieve function reference (GH-6454)
  Doc/howto/urllib2.rst
Labels: CLA signed, awaiting merge, skip news

#6484 [3.7] bpo-31947: remove None default for names param in Enum._create_ (GH-4288)
  Lib/enum.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#6457 bpo-33266: Add support for all string literals to lib2to3
  Lib/lib2to3/pgen2/tokenize.py
  Lib/lib2to3/tests/data/py3_test_grammar.py
Labels: CLA not signed, CLA signed, awaiting review, needs backport to 3.7, skip news, type-bugfix

#6488 bpo-33266: [3.7] Add support for all string literals to lib2to3 (GH-6457)
  Lib/lib2to3/pgen2/tokenize.py
  Lib/lib2to3/tests/data/py3_test_grammar.py
Labels: CLA not signed, awaiting review, skip news, type-bugfix

#6492 [3.7] acks += Zsolt Dollenstein (GH-6490)
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-04-16-15-59-21.bpo-33266.w2PAm-.rst
Labels: CLA signed, awaiting review, skip issue

#6491 bpo-23403: [lib2to3] Make grammar pickling faster
  Lib/lib2to3/pgen2/grammar.py
  Misc/NEWS.d/next/Library/2018-04-16-16-21-09.bpo-23403.rxR1Q_.rst
Labels: CLA signed, awaiting merge

#6494 bpo-33251: Revert 725476222a3c1f2f93162d75a540e6bcdeaa36fd
  Doc/library/configparser.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#6495 bpo-33251: [3.7] Revert 725476222a3c1f2f93162d75a540e6bcdeaa36fd (GH-6494)
  Doc/library/configparser.rst
Labels: CLA signed, awaiting review, skip news

#6496 bpo-33251: [3.6] Revert 725476222a3c1f2f93162d75a540e6bcdeaa36fd (GH-6494)
  Doc/library/configparser.rst
Labels: CLA signed, awaiting review, skip news

#6479 bpo-33283: Mention PNG as a supported format by Tcl/Tk
  Doc/library/tkinter.rst
  Lib/tkinter/__init__.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#6475 fix pydoc-topics to work with Sphinx 1.7
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#6500 [3.7] fix pydoc-topics to work with Sphinx 1.7 (GH-6475)
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#6501 [3.6] fix pydoc-topics to work with Sphinx 1.7 (GH-6475)
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#6350 bpo-33205: dict: Change GROWTH_RATE to (used*3)
  Misc/NEWS.d/next/Core and Builtins/2018-04-03-00-58-41.bpo-33205.lk2F3r.rst
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-performance

#6502 [2.7] fix pydoc-topics to work with Sphinx 1.7 (GH-6475)
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#6499 [3.6] bpo-33283: Mention PNG as a supported format by Tcl/Tk. (GH-6479)
  Doc/library/tkinter.rst
  Lib/tkinter/__init__.py
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6443 Typo
  Lib/test/support/__init__.py
Labels: CLA signed, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#6291 bpo-33144: random.Random and subclasses: split _randbelow implementation
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2018-04-10-14-50-30.bpo-33144.iZr4et.rst
Labels: CLA signed, awaiting merge, type-performance

#6504 bpo-33295: Skip test using missing external site
  Lib/test/test_urllib2net.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#6509 [3.7] bpo-33295: Skip test using missing external site (GH-6504)
  Lib/test/test_urllib2net.py
Labels: CLA signed, awaiting review, skip news, type-tests

#6510 [2.7] bpo-33295: Skip test using missing external site (GH-6504)
  Lib/test/test_urllib2net.py
Labels: CLA signed, awaiting review, skip news, type-tests

#6511 [3.6] bpo-33295: Skip test using missing external site (GH-6504)
  Lib/test/test_urllib2net.py
Labels: CLA signed, awaiting review, skip news, type-tests

#6507 [3.7] Fix spelling typo (GH-6443)
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting review, skip issue, skip news

#6508 [3.6] Fix spelling typo (GH-6443)
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting review, skip issue, skip news

#6503 [3.7] bpo-33205: dict: Change GROWTH_RATE to `used*3` (GH-6350)
  Misc/NEWS.d/next/Core and Builtins/2018-04-03-00-58-41.bpo-33205.lk2F3r.rst
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, type-performance

#6483 bpo-11594: Ensure line-endings are respected when using 2to3
  Lib/lib2to3/refactor.py
  Lib/lib2to3/tests/data/crlf.py
  Lib/lib2to3/tests/test_refactor.py
  Misc/NEWS.d/next/Library/2018-04-16-08-42-03.bpo-11594.QLo4vv.rst
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7

#6515 [3.7] bpo-11594: Ensure line-endings are respected when using 2to3 (GH-6483)
  Lib/lib2to3/refactor.py
  Lib/lib2to3/tests/data/crlf.py
  Lib/lib2to3/tests/test_refactor.py
  Misc/NEWS.d/next/Library/2018-04-16-08-42-03.bpo-11594.QLo4vv.rst
Labels: CLA signed, awaiting merge

#6521 [3.7] bpo-33283: Mention PNG as a supported format by Tcl/Tk. (GH-6479)
  Doc/library/tkinter.rst
  Lib/tkinter/__init__.py
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6519 bpo-33308: Fix a crash in the parser module when convert an ST object.
  Lib/test/test_parser.py
  Misc/NEWS.d/next/Library/2018-04-18-19-12-25.bpo-33308.fW75xi.rst
  Modules/parsermodule.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6528 [3.7] bpo-31583: Fix 2to3 for using with --add-suffix option (GH-3758)
  Lib/lib2to3/main.py
  Misc/NEWS.d/next/Tools-Demos/2017-09-26-10-11-21.bpo-31583.TM90_H.rst
Labels: CLA signed, awaiting review

#6524 bpo-33313: Update What's new in 3.7 to reference preadv, pwritev and posix_spawn
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news, type-documentation

#6529 [3.6] bpo-31583: Fix 2to3 for using with --add-suffix option (GH-3758)
  Lib/lib2to3/main.py
  Misc/NEWS.d/next/Tools-Demos/2017-09-26-10-11-21.bpo-31583.TM90_H.rst
Labels: CLA signed, awaiting review

#6526 [3.7] bpo-33308: Fix a crash in the parser module when convert an ST object. (GH-6519)
  Lib/test/test_parser.py
  Misc/NEWS.d/next/Library/2018-04-18-19-12-25.bpo-33308.fW75xi.rst
  Modules/parsermodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#6527 [3.6] bpo-33308: Fix a crash in the parser module when convert an ST object. (GH-6519)
  Lib/test/test_parser.py
  Misc/NEWS.d/next/Library/2018-04-18-19-12-25.bpo-33308.fW75xi.rst
  Modules/parsermodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#6531 [3.7] bpo-33313: Update What's new in 3.7 to reference preadv, pwritev and posix_spawn (GH-6524)
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6513 bpo-33299: Return an object itself for some types in _PyCode_ConstantKey().
  Objects/codeobject.c
  Python/compile.c
Labels: CLA signed, awaiting merge, skip news, type-performance

#6533 [3.7] bpo-33189: pygettext.py now accepts only literal strings (GH-6364)
  Lib/test/test_tools/test_i18n.py
  Misc/NEWS.d/next/Tools-Demos/2018-04-03-18-10-00.bpo-33189.QrXR00.rst
  Tools/i18n/pygettext.py
Labels: CLA signed, awaiting merge, type-bugfix

#6535 [3.6] bpo-33189: pygettext.py now accepts only literal strings (GH-6364)
  Lib/test/test_tools/test_i18n.py
  Misc/NEWS.d/next/Tools-Demos/2018-04-03-18-10-00.bpo-33189.QrXR00.rst
  Tools/i18n/pygettext.py
Labels: CLA signed, awaiting merge, type-bugfix

#6538 bpo-24318: Clean up the readme text around PGO a bit.
  README.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#6539 bpo-24318: [3.7] Clean up the readme text around PGO a bit. (GH-6538)
  README.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#6537 bpo-33312: Fix clang ubsan out of bounds warnings in dict.
  Misc/NEWS.d/next/Core and Builtins/2018-04-19-08-30-07.bpo-33312.mDe2iL.rst
  Objects/dict-common.h
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6542 bpo-33283: Mention PNG as a supported format by Tcl/Tk. (GH-6479)
  Doc/library/tkinter.rst
  Lib/lib-tk/Tkinter.py
Labels: CLA signed, awaiting merge, skip news, type-documentation
