Repository python/cpython, pull requests merged in 2018-05, with the labels that each got.

#4205 bpo-31908: Fix output of cover files for trace module command-line tool
  Lib/test/test_trace.py
  Lib/trace.py
  Misc/NEWS.d/next/Library/2017-10-31.bpo-31908.g4xh8x.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6666 [3.7] bpo-31908: Fix output of cover files for trace module command-line tool. (GH-4205)
  Lib/test/test_trace.py
  Lib/trace.py
  Misc/NEWS.d/next/Library/2017-10-31.bpo-31908.g4xh8x.rst
Labels: CLA signed, awaiting merge, type-bugfix

#6668 [3.6] bpo-31908: Fix output of cover files for trace module command-line tool. (GH-4205)
  Lib/test/test_trace.py
  Lib/trace.py
  Misc/NEWS.d/next/Library/2017-10-31.bpo-31908.g4xh8x.rst
Labels: CLA signed, awaiting merge, type-bugfix

#6645 Add What's New for Korean documentation translation.
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#6644 [3.6] bpo-33378: Add Korean to the language switcher. (GH-6627)
  Doc/tools/static/switchers.js
  Misc/NEWS.d/next/Documentation/2018-04-29-04-02-18.bpo-33378.-anAHN.rst
Labels: CLA signed, awaiting merge

#5469 bpo-20709: os.utime(path_to_directory): wrong documentation for Windows.
  Doc/library/os.rst
  Misc/NEWS.d/next/Documentation/2018-02-01-10-57-24.bpo-20709.1flcnc.rst
Labels: CLA signed, awaiting review

#6332 bpo-20104: Improve error handling and fix a reference leak in os.posix_spawn().
  Doc/library/os.rst
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Library/2018-04-01-19-21-04.bpo-20104.-AKcGa.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting changes, needs backport to 3.7, type-bugfix

#6673 [3.7] bpo-20104: Improve error handling and fix a reference leak in os.posix_spawn(). (GH-6332)
  Doc/library/os.rst
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Library/2018-04-01-19-21-04.bpo-20104.-AKcGa.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#6660 [3.7] bpo-33377: add triplets for mips-r6 and riscv (GH-6655)
  Misc/NEWS.d/next/Build/2018-04-30-16-53-00.bpo-33377.QBh6vP.rst
  configure
  configure.ac
Labels: CLA signed, awaiting review

#6625 bpo-33281: Change some ifs to be elifs so the correct find_library is not later overridden.
  Lib/ctypes/util.py
Labels: CLA signed, awaiting review, needs backport to 3.7, skip news

#6681 bpo-33281: NEWS and ACK
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-05-01-22-35-50.bpo-33281.d4jOt4.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6680 [3.7] bpo-33281: Fix ctypes.util.find_library regression on macOS (GH-6625)
  Lib/ctypes/util.py
Labels: CLA signed, awaiting review, skip news

#6682 [3.7] bpo-33281: NEWS and ACK (GH-6681)
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-05-01-22-35-50.bpo-33281.d4jOt4.rst
Labels: CLA signed, awaiting review

#6683 bpo-33290: Have macOS installer remove "pip" alias
  Mac/BuildScript/scripts/postflight.ensurepip
Labels: CLA signed, awaiting merge, skip news

#6686 Mitigate macOS race condition in installer build
  Mac/BuildScript/build-installer.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#6684 [3.7] bpo-33290: Have macOS installer remove "pip" alias (GH-6683)
  Mac/BuildScript/scripts/postflight.ensurepip
Labels: CLA signed, awaiting review, skip news

#6687 [3.7] Mitigate macOS race condition in installer build (GH-6686)
  Mac/BuildScript/build-installer.py
Labels: CLA signed, awaiting review, skip issue, skip news

#6685 [3.6] bpo-33290: Have macOS installer remove "pip" alias (GH-6683)
  Mac/BuildScript/scripts/postflight.ensurepip
Labels: CLA signed, awaiting review, skip news

#6688 [3.6] Mitigate macOS race condition in installer build (GH-6686)
  Mac/BuildScript/build-installer.py
Labels: CLA signed, awaiting review, skip issue, skip news

#6689 [2.7] Mitigate macOS race condition in installer build (GH-6686)
  Mac/BuildScript/build-installer.py
Labels: CLA signed, awaiting review, skip issue, skip news

#6661 [3.7] bpo-33393: Update config.guess and config.sub files (GH-6658)
  Misc/NEWS.d/next/Build/2018-04-30-17-19-37.bpo-33393.HkVCqI.rst
  config.guess
  config.sub
Labels: CLA signed, awaiting review

#6662 bpo-33394 [3.7] Enable the verbose build for extension modules with GNU make (GH-6659)
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2018-04-30-17-36-46.bpo-33394._Vdi4t.rst
Labels: CLA signed, awaiting review

#6670 bpo-33391: fix leak in set_symmetric_difference
  Misc/NEWS.d/next/Core and Builtins/2018-05-02-08-36-03.bpo-33391.z4a7rb.rst
  Objects/setobject.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#6690 [3.7] bpo-33391: Fix refleak in set_symmetric_difference (GH-6670)
  Misc/NEWS.d/next/Core and Builtins/2018-05-02-08-36-03.bpo-33391.z4a7rb.rst
  Objects/setobject.c
Labels: CLA signed, awaiting merge

#6691 [3.6] bpo-33391: Fix refleak in set_symmetric_difference (GH-6670)
  Misc/NEWS.d/next/Core and Builtins/2018-05-02-08-36-03.bpo-33391.z4a7rb.rst
  Objects/setobject.c
Labels: CLA signed, awaiting merge

#6581 bpo-33332: Add signal.valid_signals()
  Doc/library/signal.rst
  Lib/asyncio/unix_events.py
  Lib/multiprocessing/resource_sharer.py
  Lib/signal.py
  Lib/test/support/__init__.py
  Lib/test/test_asyncio/test_unix_events.py
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Library/2018-04-23-21-41-30.bpo-33332.Y6OZ8Z.rst
  Modules/clinic/signalmodule.c.h
  Modules/signalmodule.c
  aclocal.m4
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting merge, type-enhancement

#6703 [3.6] bpo-33400: Clarified documentation to indicate no strict adherence to ISO 8601. (GH-6702)
  Doc/howto/logging.rst
  Doc/library/logging.config.rst
  Doc/library/logging.rst
  Lib/logging/__init__.py
Labels: CLA signed, awaiting review, skip news

#6646 [2.7] bpo-32362: Fix references to non-existent multiprocessing.Connection() (GH-6223)
  Doc/library/multiprocessing.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6620 [2.7] bpo-32857: Raise error when tkinter after_cancel() is called with None (GH-5701)
  Lib/lib-tk/Tkinter.py
  Lib/lib-tk/test/test_tkinter/test_misc.py
  Misc/NEWS.d/next/Library/2018-02-16-14-37-14.bpo-32857.-XljAx.rst
Labels: CLA signed, awaiting merge, type-bugfix

#6701 bpo-33422: Consider the special case of string/byte literals, and update the lis…
  Lib/pydoc.py
  Misc/NEWS.d/next/Library/2018-05-05-09-53-05.bpo-33422.4FtQ0q.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6709 [3.7] bpo-33422: Fix quotation marks getting deleted when looking up byte/string literals on pydoc. (GH-6701)
  Lib/pydoc.py
  Misc/NEWS.d/next/Library/2018-05-05-09-53-05.bpo-33422.4FtQ0q.rst
Labels: CLA signed, awaiting merge, type-bugfix

#6710 [3.6] bpo-33422: Fix quotation marks getting deleted when looking up byte/string literals on pydoc. (GH-6701)
  Lib/pydoc.py
  Misc/NEWS.d/next/Library/2018-05-05-09-53-05.bpo-33422.4FtQ0q.rst
Labels: CLA signed, awaiting merge, type-bugfix

#6708 bpo-20087: Update locale alias mapping with glibc 2.27 supported locales.
  Lib/locale.py
  Lib/test/test_locale.py
  Misc/NEWS.d/next/Library/2018-05-05-18-02-24.bpo-20087.lJrvXL.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-enhancement

#6717 [2.7] bpo-20087: Update locale alias mapping with glibc 2.27 supported locales. (GH-6708).
  Lib/locale.py
  Lib/test/test_locale.py
  Misc/NEWS.d/next/Library/2018-05-05-18-02-24.bpo-20087.lJrvXL.rst
Labels: CLA signed, awaiting merge, type-enhancement

#6716 Remove mojibake in the locale aliases mapping.
  Lib/locale.py
  Tools/i18n/makelocalealias.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#6712 [2.7] bpo-33422: Fix quotation marks getting deleted when looking up …
  Lib/pydoc.py
  Misc/NEWS.d/next/Library/2018-05-05-09-53-05.bpo-33422.4FtQ0q.rst
Labels: CLA signed, awaiting review, type-bugfix

#6720 bpo-33441: Make the sigset_t converter available in other modules.
  Lib/test/test_signal.py
  Modules/clinic/signalmodule.c.h
  Modules/posixmodule.c
  Modules/posixmodule.h
  Modules/signalmodule.c
Labels: CLA signed, awaiting core review, skip news, type-enhancement

#6724 bpo-33096: Removed unintentionally backported from Python 3 Tkinter files.
  Lib/tkinter/test/test_ttk/test_widgets.py
  Lib/tkinter/ttk.py
  Misc/NEWS.d/next/Library/2018-05-08-08-03-34.bpo-33096.0hsFhL.rst
Labels: CLA signed, awaiting merge, type-bugfix

#6563 bpo-33144: Fix choosing random.Random._randbelow implementation.
  Lib/random.py
  Lib/test/test_random.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#6726 bpo-32717: Document PEP 560
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#6729 [3.7] bpo-32717: Document PEP 560 (GH-6726)
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting merge, skip news

#6674 Fix typo in __mul__ docstring
  Objects/typeobject.c
Labels: CLA not signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-bugfix

#6735 [3.7] bpo-28556: Minor fixes for typing module (GH-6732)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2018-05-08-16-43-42.bpo-28556._xr5mp.rst
Labels: CLA signed, awaiting merge

#6727 bpo-33445: fail properly in test_cprofile()
  Lib/test/test_profile.py
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7, skip news

#6736 [3.7] closes bpo-33445: fail properly in test_cprofile() (GH-6727)
  Lib/test/test_profile.py
Labels: CLA signed, awaiting merge, skip news

#6737 [3.6] closes bpo-33445: fail properly in test_cprofile() (GH-6727)
  Lib/test/test_profile.py
Labels: CLA signed, awaiting merge, skip news

#6733 [3.7] Fix typo in __mul__ and __rmul__ docstring (GH-6674)
  Objects/typeobject.c
Labels: CLA not signed, awaiting merge, skip issue, skip news, type-bugfix

#6734 [3.6] Fix typo in __mul__ and __rmul__ docstring (GH-6674)
  Objects/typeobject.c
Labels: CLA not signed, awaiting merge, skip issue, skip news, type-bugfix

#6728 Fix superfluous if in documentation.
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#6739 [3.7] Fix superfluous if in documentation. (GH-6728)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#6740 [3.6] Fix superfluous if in documentation. (GH-6728)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#6738 bpo-13525: Fix incorrect encoding name in the tutorial example.
  Doc/tutorial/interpreter.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#6742 [3.7] bpo-13525: Fix incorrect encoding name in the tutorial example. (GH-6738)
  Doc/tutorial/interpreter.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6743 [3.6] bpo-13525: Fix incorrect encoding name in the tutorial example. (GH-6738)
  Doc/tutorial/interpreter.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6744 [2.7] bpo-13525: Fix incorrect encoding name in the tutorial example. (GH-6738).
  Doc/tutorial/interpreter.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6677 bpo-33311: Do not display parameters displayed in parentheses for module call
  Lib/cgitb.py
  Misc/NEWS.d/next/Library/2018-05-01-22-33-14.bpo-33311.8YPB-k.rst
Labels: CLA signed, awaiting merge, type-enhancement

#3859 bpo-21983: Fix a crash in ctypes.cast() in case the type argument is a ctypes structured data type.
  Lib/ctypes/test/test_cast.py
  Misc/NEWS.d/next/Core and Builtins/2017-10-02-21-02-14.bpo-21983.UoC319.rst
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6746 [3.6] bpo-21983: Fix a crash in ctypes.cast() when passed a ctypes structured data type (GH-3859)
  Lib/ctypes/test/test_cast.py
  Misc/NEWS.d/next/Core and Builtins/2017-10-02-21-02-14.bpo-21983.UoC319.rst
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge

#4251 bpo-20171: Convert the _curses and _curses_panel modules to Argument Clinic.
  Include/py_curses.h
  Modules/_curses_panel.c
  Modules/_cursesmodule.c
  Modules/clinic/_curses_panel.c.h
  Modules/clinic/_cursesmodule.c.h
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#6741 bpo-26701: Tweak the documentation for special methods in int().
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#6751 [3.7] bpo-26701: Tweak the documentation for special methods in int(). (GH-6741)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6752 [3.6] bpo-26701: Tweak the documentation for special methods in int(). (GH-6741)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6758 bpo-28556: Fix a bug in Generic.__new__
  Lib/test/test_typing.py
  Lib/typing.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#6764 [3.7] Fix a bug in Generic.__new__ (GH-6758)
  Lib/test/test_typing.py
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#6753 bpo-33455: Pass os.environ in test_posix::test_specify_environment
  Lib/test/test_posix.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-tests

#6765 [3.7] bpo-33455: Pass os.environ in test_posix::test_specify_environment. (GH-6753)
  Lib/test/test_posix.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#6123 bpo-28055: fix unaligned accesses in siphash24()
  Misc/NEWS.d/next/Core and Builtins/2018-04-25-20-44-42.bpo-28055.f49kfC.rst
  Python/pyhash.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6777 [3.7] bpo-28055: Fix unaligned accesses in siphash24(). (GH-6123)
  Misc/NEWS.d/next/Core and Builtins/2018-04-25-20-44-42.bpo-28055.f49kfC.rst
  Python/pyhash.c
Labels: CLA signed, awaiting merge, type-bugfix

#6778 [3.6] bpo-28055: Fix unaligned accesses in siphash24(). (GH-6123)
  Misc/NEWS.d/next/Core and Builtins/2018-04-25-20-44-42.bpo-28055.f49kfC.rst
  Python/pyhash.c
Labels: CLA signed, awaiting merge, type-bugfix

#6776 fix error message in ast.c
  Python/ast.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#6786 bpo-33488: Satisfy markdownlint for pull request
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7, skip news

#6787 [3.7] bpo-33488: Satisfy markdownlint for the pull request template. (GH-6786)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CLA signed, awaiting merge, skip news

#5246 bpo-32601: Skip PosixPathTest.test_expanduser if no other user is found
  Lib/test/test_pathlib.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#5711 bpo-32861: urllib.robotparser fix incomplete __str__ methods.
  Lib/test/test_robotparser.py
  Lib/urllib/robotparser.py
  Misc/NEWS.d/next/Library/2018-04-02-20-44-54.bpo-32861.HeBjzN.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6793 [3.6] bpo-32601: Let test_expanduser use the same user if no others found. (GH-5246)
  Lib/test/test_pathlib.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#6609 bpo-22069: Flush is implied also when write contains a carriage return
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#6798 bpo-33494: Change dataclasses.Fields repr to use the repr of member
  Lib/dataclasses.py
  Misc/NEWS.d/next/Library/2018-05-14-10-29-03.bpo-33495.TeGTQJ.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6800 Remove `ifdef` check for an OpenSSL version (0.9.6) we don't support
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#6801 [3.7] bpo-22069: Update TextIO documentation (GH-6609)
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6802 [2.7] bpo-22069: Update TextIO documentation (GH-6609)
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#6803 [3.6] bpo-22069: Update TextIO documentation (GH-6609)
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#5992 [3.4] bpo-33001: Prevent buffer overrun in os.symlink (GH-5989)
  Lib/test/test_os.py
  Misc/NEWS.d/next/Security/2018-03-05-10-09-51.bpo-33001.elj4Aa.rst
  Modules/posixmodule.c
Labels: CLA signed, OS-windows, awaiting merge, type-bugfix, type-security

#6806 [3.7] bpo-33495: Change dataclasses.Fields repr to use the repr of each of its members (GH-6798)
  Lib/dataclasses.py
  Misc/NEWS.d/next/Library/2018-05-14-10-29-03.bpo-33495.TeGTQJ.rst
Labels: CLA signed, awaiting merge

#6807 [3.7] Remove `ifdef` check for an OpenSSL version (0.9.6) we don't support (GH-6800)
  Modules/_ssl.c
Labels: CLA signed, awaiting review, skip issue, skip news

#5991 [3.5] bpo-33001: Prevent buffer overrun in os.symlink (GH-5989)
  Lib/test/test_os.py
  Misc/NEWS.d/next/Security/2018-03-05-10-09-51.bpo-33001.elj4Aa.rst
  Modules/posixmodule.c
Labels: CLA signed, OS-windows, awaiting merge, type-bugfix, type-security

#6722 bpo-33443 Fix typo in Python/import.c (GH-6721)
  Python/import.c
Labels: CLA signed, awaiting merge, skip news

#6810 [3.7] Add versionchanged in create_datagram_endpoint doc (GH-4697)
  Doc/library/asyncio-eventloop.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6811 [3.6] Add versionchanged in create_datagram_endpoint doc (GH-4697)
  Doc/library/asyncio-eventloop.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6816 Fixed an unused variable warning introduced in GH-6800
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#6812 bpo-33502: dataclass._Dataclassparams repr: use repr of each member.
  Lib/dataclasses.py
  f.py
  j.py
  t.py
  x.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#6794 bpo-20104: Remove posix_spawn from 3.7
  Doc/library/os.rst
  Doc/whatsnew/3.7.rst
  Lib/test/test_posix.py
  Misc/NEWS.d/3.7.0b1.rst
  Misc/NEWS.d/next/Core and Builtins/2018-05-14-11-34-55.bpo-20104.kqBNzv.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#6818 [3.6] bpo-32861: urllib.robotparser fix incomplete __str__ methods. (GH-5711) (GH-6795)
  Lib/test/test_robotparser.py
  Lib/urllib/robotparser.py
  Misc/NEWS.d/next/Library/2018-04-02-20-44-54.bpo-32861.HeBjzN.rst
Labels: awaiting review, type-bugfix

#6817 [2.7] bpo-32861: urllib.robotparser fix incomplete __str__ methods. (GH-5711) (GH-6795)
  Lib/robotparser.py
  Lib/test/test_robotparser.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-04-02-20-44-54.bpo-32861.HeBjzN.rst
Labels: CLA signed, awaiting merge, type-bugfix

#6804 bpo-33497: Add errors param to cgi.parse_multipart and make an encoding in FieldStorage use the given errors
  Doc/library/cgi.rst
  Lib/cgi.py
  Lib/test/test_cgi.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#6822 bpo-33421: Add AsyncContextManager to typing module documentation (Python 3.7+).
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2018-05-14-15-15-41.bpo-33421.3GU_QO.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6838 bpo-33497: Add NEWS and ACKS entries.
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-05-14-17-49-34.bpo-33497.wWT6XM.rst
Labels: CLA signed, awaiting merge

#6830 [3.7] Fixed an unused variable warning introduced in GH-6800 (GH-6816)
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#3006 bpo-16865: Support arrays >=2GB in ctypes
  Lib/ctypes/test/test_arrays.py
  Misc/NEWS.d/next/Library/2017-09-29-16-40-38.bpo-16865.l-f6I_.rst
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#6831 [3.7] bpo-33502: dataclass._Dataclassparams repr: use repr of each member. (GH-6812)
  Lib/dataclasses.py
  f.py
  j.py
  t.py
  x.py
Labels: CLA signed, awaiting merge, skip news

#6835 Remove accidentally checked in files.
  f.py
  j.py
  t.py
  x.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#6839 [3.7] bpo-33421: Add AsyncContextManager to typing module documentation. (GH-6822)
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2018-05-14-15-15-41.bpo-33421.3GU_QO.rst
Labels: CLA signed, awaiting merge

#6823 bpo-33421: Add AsyncContextManager to typing module documentation (Python 3.6).
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2018-05-14-15-23-51.bpo-33421.3GU_QO.rst
Labels: CLA signed, awaiting merge

#6780 bpo-33483: more correctly handle finding the C compiler
  Misc/NEWS.d/next/Build/2018-05-13-17-21-54.bpo-33483.WOs-en.rst
  configure.ac
Labels: CLA signed, awaiting review

#6850 run autoreconf
  aclocal.m4
  configure
Labels: CLA signed, awaiting merge, skip issue, skip news

#6842 [3.7] bpo-16865: Support arrays >=2GB in ctypes. (GH-3006)
  Lib/ctypes/test/test_arrays.py
  Misc/NEWS.d/next/Library/2017-09-29-16-40-38.bpo-16865.l-f6I_.rst
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge, type-bugfix

#6843 [3.6] bpo-16865: Support arrays >=2GB in ctypes. (GH-3006)
  Lib/ctypes/test/test_arrays.py
  Misc/NEWS.d/next/Library/2017-09-29-16-40-38.bpo-16865.l-f6I_.rst
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge, type-bugfix

#6844 [3.7] Remove accidentally checked in files. (GH-6835)
  f.py
  j.py
  t.py
  x.py
Labels: CLA signed, awaiting review, skip issue, skip news

#6858 bpo-33517: dataclasses: Add the field type to Field repr
  Lib/dataclasses.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#6859 [3.7] bpo-33517: dataclasses: Add the field type to Field repr (GH-6858)
  Lib/dataclasses.py
Labels: CLA signed, awaiting merge, skip news

#6813 bpo-32604: Remove xid registry.
  Include/internal/pystate.h
  Lib/test/test__xxsubinterpreters.py
  Misc/NEWS.d/3.7.0b1.rst
  Misc/NEWS.d/next/Tests/2018-05-14-13-32-46.bpo-32604.a_z6D_.rst
  Modules/_xxsubinterpretersmodule.c
  PC/config.c
  PCbuild/pythoncore.vcxproj
  Python/pystate.c
  setup.py
Labels: CLA signed, awaiting merge

#6485 [3.6] bpo-31947: remove None default for names param in Enum._create_ (GH-4288)
  Lib/enum.py
Labels: CLA signed, awaiting review, skip news, type-bugfix

#6862 [3.7] bpo-28167: bump platform.linux_distribution removal to 3.8 (GH-6669)
  Doc/library/platform.rst
  Lib/platform.py
  Lib/test/test_platform.py
  Misc/NEWS.d/next/Library/2018-05-02-07-26-29.bpo-28167.7FwDfN.rst
Labels: CLA signed, awaiting review

#6864 [3.6] bpo-28167: bump platform.linux_distribution removal to 3.8 (GH-6862)
  Doc/library/platform.rst
Labels: CLA signed, awaiting merge, skip news

#6833 bpo-33509: Fix _warnings for module_globals=None
  Lib/test/test_warnings/__init__.py
  Misc/NEWS.d/next/Core and Builtins/2018-05-14-17-31-02.bpo-33509.pIUfTd.rst
  Python/_warnings.c
Labels: CLA signed, awaiting merge

#6814 bpo-33503: Fix the broken pypi link in the source and the documentation
  Doc/distributing/index.rst
  Doc/distutils/apiref.rst
  Doc/distutils/packageindex.rst
  Doc/distutils/setupscript.rst
  Doc/faq/general.rst
  Doc/faq/library.rst
  Doc/howto/curses.rst
  Doc/howto/pyporting.rst
  Doc/installing/index.rst
  Doc/library/distribution.rst
  Doc/library/index.rst
  Doc/library/pprint.rst
  Doc/library/re.rst
  Doc/library/ssl.rst
  Doc/library/unittest.mock.rst
  Doc/library/xml.rst
  Doc/tutorial/venv.rst
  Doc/tutorial/whatnow.rst
  Doc/using/windows.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/2.5.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.5.rst
  Misc/NEWS.d/next/Documentation/2018-05-14-20-08-58.bpo-33503.Wvt0qg.rst
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#6867 [3.7] bpo-29706: Test that IDLE colors async/await as keywords. (GH-6846)
  Lib/idlelib/colorizer.py
Labels: CLA signed, awaiting merge, skip news

#5904 bpo-32257: Add ssl.OP_NO_RENEGOTIATION
  Doc/library/ssl.rst
  Misc/NEWS.d/next/Library/2018-02-26-09-08-07.bpo-32257.6ElnUt.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6868 [3.6] bpo-29706: Test that IDLE colors async/await as keywords. (GH-6846)
  Lib/idlelib/colorizer.py
Labels: CLA signed, awaiting merge, skip news

#6870 [3.7] bpo-33509: Fix _warnings for module_globals=None (GH-6833)
  Lib/test/test_warnings/__init__.py
  Misc/NEWS.d/next/Core and Builtins/2018-05-14-17-31-02.bpo-33509.pIUfTd.rst
  Python/_warnings.c
Labels: CLA signed, awaiting merge

#6873 bpo-30928: Update idlelib/NEWS.txt to 2018-05-14.
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#6747 bpo-33454: Fix arguments parsing in _xxsubinterpreters.channel_close().
  Modules/_xxsubinterpretersmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-bugfix

#6879 [3.6] bpo-29706: IDLE now colors async and await as keywords in 3.6.
  Lib/idlelib/colorizer.py
  Misc/NEWS.d/next/IDLE/2018-05-15-17-01-10.bpo-29706.id4H5i.rst
Labels: CLA signed, awaiting merge

#6881 [3.7] bpo-30928: Update idlelib/NEWS.txt to 2018-05-14. (GH-6873)
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting merge, skip news

#6882 [3.6] bpo-30928: Update idlelib/NEWS.txt to 2018-05-14. (GH-6873)
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting merge, skip news

#6768 bpo-33453: Handle string type annotations in dataclasses.
  Lib/dataclasses.py
  Lib/test/dataclass_module_1.py
  Lib/test/dataclass_module_1_str.py
  Lib/test/dataclass_module_2.py
  Lib/test/dataclass_module_2_str.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2018-05-12-06-01-02.bpo-33453.Fj-jMD.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6889 [3.7] bpo-33453: Handle string type annotations in dataclasses. (GH-6768)
  Lib/dataclasses.py
  Lib/test/dataclass_module_1.py
  Lib/test/dataclass_module_1_str.py
  Lib/test/dataclass_module_2.py
  Lib/test/dataclass_module_2_str.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2018-05-12-06-01-02.bpo-33453.Fj-jMD.rst
Labels: CLA signed, awaiting merge

#6847 bpo-33512: use standard for detecting long double
  Misc/NEWS.d/next/Build/2018-05-15-02-07-49.bpo-33512.X4Fy1Q.rst
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting review

#6888 [3.6] bpo-30928: update idlelib/NEWS.txt for 3.6.
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting merge, skip news, type-documentation

#4940 bpo-32384 fix test.test_generators for other implementations
  Lib/test/test_generators.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#6891 [3.7] bpo-32384: Skip test when _testcapi isn't available (GH-4940)
  Lib/test/test_generators.py
Labels: CLA signed, awaiting review, skip news

#6893 Reflow dataclass comments.
  Lib/dataclasses.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#6894 [3.7] bpo-32216: Add documentation for dataclasses (GH-6886)
  Doc/library/dataclasses.rst
  Doc/library/python.rst
Labels: CLA signed, awaiting merge, skip news

#6892 [3.6] bpo-32384: Skip test when _testcapi isn't available (GH-4940)
  Lib/test/test_generators.py
Labels: CLA signed, awaiting review, skip news

#6896 [3.7] Reflow dataclasses comments (GH-6893)
  Lib/dataclasses.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#6899 [3.7] bpo-33534: Remove unneeded test. (GH-6897)
  Lib/dataclasses.py
Labels: CLA signed, awaiting merge, skip news

#6903 Minor tweaks to dataclasses docs.
  Doc/library/dataclasses.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#6904 [3.7] Minor tweaks to dataclasses docs. (GH-6903)
  Doc/library/dataclasses.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6872 [3.7] bpo-33503: Fix the broken pypi link in the source and the documentation (GH-6814)
  Doc/distributing/index.rst
  Doc/distutils/apiref.rst
  Doc/distutils/packageindex.rst
  Doc/distutils/setupscript.rst
  Doc/faq/general.rst
  Doc/faq/library.rst
  Doc/howto/curses.rst
  Doc/howto/pyporting.rst
  Doc/installing/index.rst
  Doc/library/distribution.rst
  Doc/library/index.rst
  Doc/library/pprint.rst
  Doc/library/re.rst
  Doc/library/ssl.rst
  Doc/library/unittest.mock.rst
  Doc/library/xml.rst
  Doc/tutorial/venv.rst
  Doc/tutorial/whatnow.rst
  Doc/using/windows.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/2.5.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.5.rst
  Misc/NEWS.d/next/Documentation/2018-05-14-20-08-58.bpo-33503.Wvt0qg.rst
Labels: CLA signed, awaiting review

#6885 [3.6] bpo-33503: Fix the broken pypi link in the source and the documentation
  Doc/distributing/index.rst
  Doc/distutils/apiref.rst
  Doc/distutils/packageindex.rst
  Doc/faq/general.rst
  Doc/faq/library.rst
  Doc/howto/curses.rst
  Doc/howto/pyporting.rst
  Doc/installing/index.rst
  Doc/library/distribution.rst
  Doc/library/index.rst
  Doc/library/pprint.rst
  Doc/library/re.rst
  Doc/library/ssl.rst
  Doc/library/unittest.mock.rst
  Doc/library/xml.rst
  Doc/tutorial/venv.rst
  Doc/tutorial/whatnow.rst
  Doc/using/windows.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/2.5.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.5.rst
  Misc/NEWS.d/next/Documentation/2018-05-14-20-08-58.bpo-33503.Wvt0qg.rst
Labels: CLA signed, awaiting review

#6883 bpo-21475: Support the Sitemap extension in robotparser
  Doc/library/urllib.robotparser.rst
  Lib/test/test_robotparser.py
  Lib/urllib/robotparser.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-05-15-15-03-48.bpo-28612.E9dz39.rst
Labels: CLA signed, awaiting merge

#6906 bpo-33536: Validate make_dataclass() field names.
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2018-05-16-10-07-40.bpo-33536._s0TE8.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#6863 bpo-24318: Rewrite the README PGO section.
  README.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news, sprint, type-documentation

#6824 Fix ClassVar as string fails when getting type hints
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2018-05-15-18-02-03.bpo-0.pj2Mbb.rst
Labels: CLA not signed, awaiting review, needs backport to 3.7, skip issue

#6908 [3.7] bpo-33536: Validate make_dataclass() field names. (GH-6906)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2018-05-16-10-07-40.bpo-33536._s0TE8.rst
Labels: CLA signed, awaiting merge

#6909 [3.7] bpo-24318: Rewrite the README PGO section. (GH-6863)
  README.rst
Labels: CLA signed, awaiting merge, skip news, sprint, type-documentation

#6887 Remove an unneeded call into OpenSSL
  Modules/_ssl.c
Labels: awaiting core review, skip issue, skip news

#6914 bpo-32604: Improve subinterpreter tests.
  Lib/test/test__xxsubinterpreters.py
  Modules/_xxsubinterpretersmodule.c
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news

#6913 bpo-32216: Update dataclasses documentation
  Doc/library/dataclasses.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#6918 [3.7] bpo-32216: Update dataclasses documentation (GH-6913)
  Doc/library/dataclasses.rst
Labels: CLA signed, awaiting review, skip issue, skip news

#6865 bpo-33522: Enable CI builds on Visual Studio Team Services
  .vsts/docs-release.yml
  .vsts/docs.yml
  .vsts/linux-buildbot.yml
  .vsts/linux-coverage.yml
  .vsts/linux-deps.yml
  .vsts/linux-pr.yml
  .vsts/macos-buildbot.yml
  .vsts/macos-pr.yml
  .vsts/windows-buildbot.yml
  .vsts/windows-pr.yml
  Doc/make.bat
  Lib/tempfile.py
  Lib/test/support/__init__.py
  Lib/test/test_asyncio/test_base_events.py
  Lib/test/test_bdb.py
  Lib/test/test_pathlib.py
  Lib/test/test_poplib.py
  Lib/test/test_selectors.py
  Misc/NEWS.d/next/Build/2018-05-15-12-44-50.bpo-33522.mJoNcA.rst
  Misc/NEWS.d/next/Library/2018-05-16-17-05-48.bpo-33548.xWslmx.rst
  PCbuild/rt.bat
  Tools/ssl/multissltests.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7
