Repository python/cpython, pull requests merged in 2018-07, with the labels that each got.

#8032 bpo-30660: Doc: Optimize PNG files
  Doc/faq/python-video-icon.png
  Doc/howto/logging_flow.png
  Doc/library/hashlib-blake2-tree.png
  Doc/library/pathlib-inheritance.png
  Doc/library/tulip_coro.png
  Doc/library/turtle-star.png
  Doc/using/win_installer.png
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8008 bpo-33978: close resources before deletion of logging handlers
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2018-06-29-12-23-34.bpo-33978.y4csIw.rst
Labels: CLA signed, awaiting merge

#8044 [3.7] bpo-33978: Close existing handlers before logging (re-)configuration. (GH-8008)
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2018-06-29-12-23-34.bpo-33978.y4csIw.rst
Labels: CLA signed, awaiting review

#8045 [3.6] bpo-33978: Close existing handlers before logging (re-)configuration. (GH-8008)
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2018-06-29-12-23-34.bpo-33978.y4csIw.rst
Labels: CLA signed, awaiting review

#7917 bpo-33961: Adjusted docs to correct exceptions raised.
  Doc/library/dataclasses.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#8048 [3.5] bpo-33700: Backport language switcher (GH-2652)
  Doc/Makefile
  Doc/conf.py
  Doc/tools/static/switchers.js
  Doc/tools/static/version_switch.js
  Doc/tools/templates/layout.html
Labels: CLA signed, awaiting merge

#8051 bpo-34006: Set SPHINXOPTS for htmlhelp
  Doc/make.bat
  Misc/NEWS.d/next/Windows/2018-07-02-14-19-32.bpo-34006.7SgBT_.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#8053 [3.7] bpo-34006: Revert line length limit for Windows help docs (GH-8051)
  Doc/make.bat
  Misc/NEWS.d/next/Windows/2018-07-02-14-19-32.bpo-34006.7SgBT_.rst
Labels: CLA signed, awaiting merge

#8054 [3.6] bpo-34006: Revert line length limit for Windows help docs (GH-8051)
  Doc/make.bat
  Misc/NEWS.d/next/Windows/2018-07-02-14-19-32.bpo-34006.7SgBT_.rst
Labels: CLA signed, awaiting merge

#8059 bpo-33735: Fix test_multiprocessing random failure
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news

#8047 bpo-34019: Fix wrong arguments for Opera Browser
  Lib/test/test_webbrowser.py
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2018-07-02-05-59-11.bpo-34019.ZXJIife.rst
Labels: CLA signed, awaiting merge

#8060 [3.7] bpo-33735: Fix test_multiprocessing random failure (GH-8059)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#8061 [2.7] bpo-33735: Fix test_multiprocessing random failure (GH-8059)
  Lib/test/test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#8062 [3.6] bpo-33735: Fix test_multiprocessing random failure (GH-8059)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#8042 bpo-34018: Doc'd that type names of SQLite converters are case-insensitive.
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news

#8064 [3.6] bpo-34019: Fix wrong arguments for Opera Browser (GH-8047)
  Lib/test/test_webbrowser.py
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2018-07-02-05-59-11.bpo-34019.ZXJIife.rst
Labels: CLA signed, awaiting merge

#8063 [3.7] bpo-34019: Fix wrong arguments for Opera Browser (GH-8047)
  Lib/test/test_webbrowser.py
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2018-07-02-05-59-11.bpo-34019.ZXJIife.rst
Labels: CLA signed, awaiting merge

#8065 [3.7] bpo-34018: Doc'd that type names of SQLite converters are case-insensitive. (GH-8042)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#8067 [3.6] bpo-34018: Doc'd that type names of SQLite converters are case-insensitive. (GH-8042)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#8066 [2.7] bpo-34018: Doc'd that type names of SQLite converters are case-insensitive. (GH-8042)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#7918 bpo-24596: Decref module in PyRun_SimpleFileExFlags() on SystemExit
  Lib/test/test_gc.py
  Misc/NEWS.d/next/Core and Builtins/2018-06-25-16-54-05.bpo-24596.Rkwova.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting review

#8070 [3.7] bpo-24596: Decref module in PyRun_SimpleFileExFlags() on SystemExit (GH-7918)
  Lib/test/test_gc.py
  Misc/NEWS.d/next/Core and Builtins/2018-06-25-16-54-05.bpo-24596.Rkwova.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting review

#8069 [3.6] bpo-24596: Decref module in PyRun_SimpleFileExFlags() on SystemExit (GH-7918)
  Lib/test/test_gc.py
  Misc/NEWS.d/next/Core and Builtins/2018-06-25-16-54-05.bpo-24596.Rkwova.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting review

#8058 bpo-33418: Add tp_clear for function object
  Misc/NEWS.d/next/Core and Builtins/2018-07-03-19-00-10.bpo-33418.cfGm3n.rst
  Objects/funcobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#8075 Don't export pending_threadfunc from _testcapi.
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#8076 Make GenericAlias_Type and Generic_Type static.
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#8078 [2.7] Don't export pending_threadfunc from _testcapi. (GH-8075)
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8077 [3.7] Don't export pending_threadfunc from _testcapi. (GH-8075)
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8079 [3.6] Don't export pending_threadfunc from _testcapi. (GH-8075)
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8080 [3.7] Make GenericAlias_Type and Generic_Type static. (GH-8076)
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8020 bpo-34010: Fix tarfile read performance regression
  Lib/tarfile.py
  Misc/NEWS.d/next/Library/2018-07-04-07-36-53.bpo-34010.VNDkde.rst
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7, type-bugfix, type-performance

#8082 [3.7] bpo-34010: Fix tarfile read performance regression (GH-8020)
  Lib/tarfile.py
  Misc/NEWS.d/next/Library/2018-07-04-07-36-53.bpo-34010.VNDkde.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-performance

#8083 [3.6] bpo-34010: Fix tarfile read performance regression (GH-8020)
  Lib/tarfile.py
  Misc/NEWS.d/next/Library/2018-07-04-07-36-53.bpo-34010.VNDkde.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-performance

#8081 bpo-34040, multiprocessing: Fix test_forkserver_sigkill()
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#8084 [3.7] bpo-34040, multiprocessing: Fix test_forkserver_sigkill() (GH-8081)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#8034 bpo-32942: Fix environment dependent test_script_helper
  Lib/test/test_script_helper.py
Labels: CLA signed, awaiting review, skip news

#8085 [3.6] bpo-34040, multiprocessing: Fix test_forkserver_sigkill() (GH-8081)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#8087 [3.7] bpo-32942: Fix environment dependent test_script_helper (GH-8034)
  Lib/test/test_script_helper.py
Labels: CLA signed, awaiting merge, skip news

#8088 [3.6] bpo-32942: Fix environment dependent test_script_helper (GH-8034)
  Lib/test/test_script_helper.py
Labels: CLA signed, awaiting merge, skip news

#7348 bpo-30516: Fix documentation issue with -timedelta in datetime
  Doc/library/datetime.rst
Labels: CLA signed, awaiting change review, skip news

#8094 Minor code refactoring. Compute len() one fewer times on one code path.
  Lib/random.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#8092 [3.6] bpo-30516: Fix documentation issue with -timedelta in datetime (GH-7348)
  Doc/library/datetime.rst
Labels: CLA signed, awaiting review, skip news

#8093 [3.7] bpo-30516: Fix documentation issue with -timedelta in datetime (GH-7348)
  Doc/library/datetime.rst
Labels: CLA signed, awaiting review, skip news

#8072 Doc: Stackless Python wiki moved to github.
  Doc/faq/design.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#7994 Removed unused import in tzinfo_examples.py.
  Doc/includes/tzinfo_examples.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#8101 [3.7] Removed unused import from tzinfo_examples.py. (GH-7994)
  Doc/includes/tzinfo_examples.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#7336 bpo-33720: Improve test for the stack overflow in marshal.loads().
  Lib/test/test_marshal.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#8104 [3.7] bpo-33720: Improve tests for the stack overflow in marshal.loads(). (GH-7336)
  Lib/test/test_marshal.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#8105 [3.6] bpo-33720: Improve tests for the stack overflow in marshal.loads(). (GH-7336)
  Lib/test/test_marshal.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#8106 Fix fuzz testing for marshal.loads().
  Lib/test/test_marshal.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-tests

#8107 [2.7] bpo-33720: Improve tests for the stack overflow in marshal.loads(). (GH-7336).
  Lib/test/test_marshal.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#8109 [3.7] Fix fuzz testing for marshal.loads(). (GH-8106)
  Lib/test/test_marshal.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#8110 [3.6] Fix fuzz testing for marshal.loads(). (GH-8106)
  Lib/test/test_marshal.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#7985 [3.7] bpo-33988: Use DeprecationWarning instead of PendingDeprecationWarning
  Lib/test/test_platform.py
  Lib/test/test_ssl.py
Labels: CLA signed, awaiting review, skip news

#8090 bpo-34044: subprocess.Popen copies startupinfo
  Lib/subprocess.py
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Library/2018-07-04-17-14-26.bpo-34044.KWAu4y.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7

#8121 [3.7] bpo-34044: subprocess.Popen copies startupinfo (GH-8090)
  Lib/subprocess.py
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Library/2018-07-04-17-14-26.bpo-34044.KWAu4y.rst
Labels: CLA signed, awaiting merge

#8102 Fix typo in Lib/dataclasses.py documentation
  Lib/dataclasses.py
Labels: CLA not signed, awaiting review, needs backport to 3.7, skip issue, skip news

#8103 bpo-34049: classify abs() argument type
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8124 Add more detail to Counter.fromkeys() comment
  Lib/collections/__init__.py
Labels: awaiting merge, skip issue, skip news, type-documentation

#8114 versionadded -> versionchanged for all 'X parameter was added' for uniformity.
  Doc/library/logging.rst
  Doc/library/sched.rst
  Doc/library/subprocess.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8089 bpo-34043: Optimize tarfile uncompress performance
  Lib/tarfile.py
  Misc/NEWS.d/next/Library/2018-07-04-21-14-35.bpo-34043.0YJNq9.rst
Labels: CLA signed, awaiting merge, type-performance

#8127 Make TaskStepMethWrapper_Type and TaskWakeupMethWrapper_Type static.
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#8128 [3.7] Make TaskStepMethWrapper_Type and TaskWakeupMethWrapper_Type static. (GH-8127)
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8129 [3.6] Make TaskStepMethWrapper_Type and TaskWakeupMethWrapper_Type static. (GH-8127)
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#7891 bpo-33899: Make tokenize module mirror end-of-file is end-of-line behavior
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Library/2018-06-24-01-57-14.bpo-33899.IaOcAr.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#7618 Fix GCC warning in Python/hamt.c
  Python/hamt.c
Labels: CLA signed, awaiting review, needs backport to 3.7, skip issue, skip news

#8112 Doc: Remove superfluous markup.
  Doc/library/pdb.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#8108 [3.7] Update Stackless Python wiki URL (GH-8072)
  Doc/faq/design.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#8136 [3.7] Doc: Remove superfluous markup. (GH-8112)
  Doc/library/pdb.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#8135 [3.7] Fix GCC warning in Python/hamt.c (GH-7618)
  Python/hamt.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8039 bpo-20180: complete AC conversion of Objects/stringlib/transmogrify.h
  Objects/bytearrayobject.c
  Objects/bytes_methods.c
  Objects/bytesobject.c
  Objects/stringlib/clinic/transmogrify.h.h
  Objects/stringlib/transmogrify.h
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting merge, skip news

#8132 [3.7] bpo-33899: Make tokenize module mirror end-of-file is end-of-li…
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Library/2018-06-24-01-57-14.bpo-33899.IaOcAr.rst
Labels: CLA signed, awaiting review

#8134 [3.6] bpo-33899: Make tokenize module mirror end-of-file is end-of-li…
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Library/2018-06-24-01-57-14.bpo-33899.IaOcAr.rst
Labels: CLA signed, awaiting review

#8040 Fix typos in Objects/odictobject.c documentation
  Objects/odictobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#8118 bpo-34054: multiprocessing uses time.monotonic()
  Lib/multiprocessing/connection.py
  Lib/multiprocessing/managers.py
  Lib/multiprocessing/queues.py
  Lib/multiprocessing/synchronize.py
  Misc/NEWS.d/next/Library/2018-07-05-18-37-05.bpo-34054.nWRS6M.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#8137 [3.7] fix two typos in Objects/odictobject.c comments (GH-8040)
  Objects/odictobject.c
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8139 [3.7] bpo-34054: multiprocessing uses time.monotonic() (GH-8118)
  Lib/multiprocessing/connection.py
  Lib/multiprocessing/managers.py
  Lib/multiprocessing/queues.py
  Lib/multiprocessing/synchronize.py
  Misc/NEWS.d/next/Library/2018-07-05-18-37-05.bpo-34054.nWRS6M.rst
Labels: CLA signed, awaiting merge

#8140 [3.6] bpo-34054: multiprocessing uses time.monotonic() (GH-8118)
  Lib/multiprocessing/connection.py
  Lib/multiprocessing/managers.py
  Lib/multiprocessing/queues.py
  Lib/multiprocessing/synchronize.py
  Misc/NEWS.d/next/Library/2018-07-05-18-37-05.bpo-34054.nWRS6M.rst
Labels: CLA signed, awaiting merge

#8141 Clarify that example in comment is about fromkeys()
  Lib/collections/__init__.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8119 bpo-34042: Fix dict.copy() to maintain correct total refcount
  Misc/NEWS.d/next/Core and Builtins/2018-07-05-15-51-29.bpo-34042.Gr9XUH.rst
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.7

#8143 [3.7] bpo-34042: Fix dict.copy() to maintain correct total refcount (GH-8119)
  Misc/NEWS.d/next/Core and Builtins/2018-07-05-15-51-29.bpo-34042.Gr9XUH.rst
  Objects/dictobject.c
Labels: CLA signed, awaiting merge

#8126 [2.7] bpo-34019: Fix wrong arguments for Opera Browser (GH-8047)
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2018-07-02-05-59-11.bpo-34019.ZXJIife.rst
Labels: CLA signed, awaiting merge

#8131 bpo-23493: json: Change sort_keys in Python encoder same to C
  Lib/json/encoder.py
Labels: CLA signed, awaiting merge, skip news

#8130 bpo-34056: Always return bytes from _HackedGetData.get_data().
  Lib/imp.py
  Lib/test/test_imp.py
  Misc/NEWS.d/next/Library/2018-07-05-22-45-46.bpo-34056.86isrU.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#8146 [3.7] closes bpo-34056: Always return bytes from _HackedGetData.get_data(). (GH-8130)
  Lib/imp.py
  Lib/test/test_imp.py
  Misc/NEWS.d/next/Library/2018-07-05-22-45-46.bpo-34056.86isrU.rst
Labels: CLA signed, awaiting merge

#8147 Make two PyModuleDef_Slot symbols static in _testmultiphase.
  Modules/_testmultiphase.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#8149 [3.6] Make two PyModuleDef_Slot symbols static in _testmultiphase. (GH-8147)
  Modules/_testmultiphase.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8151 Hide some symbols from _xxsubinterpreters.
  Modules/_xxsubinterpretersmodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8153 bpo-34065: Fix wrongly written basicConfig document rst syntax about force
  Doc/library/logging.rst
  Misc/NEWS.d/next/Documentation/2018-07-07-20-38-41.bpo-34065.1snofM.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-documentation

#8142 Fix typo in TypeVar docstring
  Lib/typing.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#8157 [3.7] Fix typo in TypeVar docstring (GH-8142)
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#8155 [3.6] bpo-34065: Improve the markup of logging.basicConfig() arguments (GH-8153)
  Doc/library/logging.rst
  Misc/NEWS.d/next/Documentation/2018-07-07-20-38-41.bpo-34065.1snofM.rst
Labels: CLA signed, awaiting review, type-documentation

#8156 [3.7] bpo-34065: Improve the markup of logging.basicConfig() arguments (GH-8153).
  Doc/library/logging.rst
  Misc/NEWS.d/next/Documentation/2018-07-07-20-38-41.bpo-34065.1snofM.rst
Labels: CLA signed, awaiting review, type-documentation

#8160 Make various internal _testbuffer symbols static.
  Modules/_testbuffer.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#8161 [3.7] Make various internal _testbuffer symbols static. (GH-8160)
  Modules/_testbuffer.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8162 [3.6] Make various internal _testbuffer symbols static. (GH-8160)
  Modules/_testbuffer.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8144 Add missing closing parentheses
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#8117 Fix moduleauthor/sectionauthor directives in Enum
  Doc/library/enum.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#8163 [3.7] Add missing closing parentheses (GH-8144)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8164 [3.6] Fix moduleauthor/sectionauthor directives in Enum (GH-8117)
  Doc/library/enum.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8165 [3.7] Fix moduleauthor/sectionauthor directives in Enum (GH-8117)
  Doc/library/enum.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8166 [3.6] Add missing closing parentheses (GH-8144)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#7510 bpo-33804: Document the default value of the size parameter of io.TextIOBase.read
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#8167 [3.7] bpo-33804: Document that the argument for io.TextIOBase.read() is optional (GH-7510)
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8168 [3.6] bpo-33804: Document that the argument for io.TextIOBase.read() is optional (GH-7510)
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8169 [3.7] bpo-33702: Add some missing links in production lists and do a little polish (GH-7259)
  Doc/reference/compound_stmts.rst
  Doc/reference/expressions.rst
  Doc/reference/simple_stmts.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8170 [3.6] bpo-33702: Add some missing links in production lists and do a little polish (GH-7259)
  Doc/reference/compound_stmts.rst
  Doc/reference/expressions.rst
  Doc/reference/simple_stmts.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8171 [2.7] bpo-33804: Document that the argument for io.TextIOBase.read() …
  Doc/library/io.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#6036 bpo-28626: rearrange discussion of output formatting to encourage f-strings
  Doc/tutorial/inputoutput.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news

#8175 Make PySimpleQueueType static.
  Modules/_queuemodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#8176 [3.7] Make PySimpleQueueType static. (GH-8175)
  Modules/_queuemodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#8177 [3.7] closes bpo-34050: Fix link in SSL docs (GH-8173)
  Doc/library/ssl.rst
  Misc/ACKS
Labels: CLA signed, awaiting merge, skip news

#8179 [2.7] closes bpo-34050: Fix link in SSL docs (GH-8173).
  Doc/library/ssl.rst
  Misc/ACKS
Labels: CLA signed, awaiting merge, skip news

#8178 [3.6] closes bpo-34050: Fix link in SSL docs (GH-8173)
  Doc/library/ssl.rst
  Misc/ACKS
Labels: CLA signed, awaiting merge, skip news

#8181 [2.7] bpo-33888: Use CPython instead of Python in the FAQ (GH-7767)
  Doc/faq/design.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8180 [3.7] bpo-33888: Use CPython instead of Python in the FAQ (GH-7767)
  Doc/faq/design.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8182 [3.6] bpo-33888: Use CPython instead of Python in the FAQ (GH-7767)
  Doc/faq/design.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#8086 bpo-34041: Added *deterministic* parameter to sqlite3.Connection.create_function().
  Doc/library/sqlite3.rst
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2018-07-06-15-06-32.bpo-34041.0zrKLh.rst
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge

#8183 [3.7] bpo-31014: Fix the webbrowser module. (GH-7267)
  Lib/test/test_webbrowser.py
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2018-05-31-06-48-55.bpo-31014.SNY681.rst
Labels: CLA signed, awaiting merge, type-bugfix

#8172 bpo-34061: Add missing docs for NotSupportedError sqlite module
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#8185 [3.6] bpo-34061: Document sqlite3.NotSupportedError (GH-8172).
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news

#8186 [3.7] bpo-34061: Document sqlite3.NotSupportedError (GH-8172)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news

#8188 Fix margin in sentinel and mock_open
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#8189 [3.7] Fix margin in sentinel and mock_open (GH-8188)
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8190 [3.6] Fix margin in sentinel and mock_open (GH-8188)
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#7684 bpo-26544: Fixed implementation of platform.libc_ver().
  Doc/library/platform.rst
  Lib/platform.py
  Lib/test/test_platform.py
  Misc/NEWS.d/next/Library/2018-06-13-20-33-29.bpo-26544.hQ1oMt.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#8193 [3.7] bpo-26544: Fixed implementation of platform.libc_ver(). (GH-7684).
  Doc/library/platform.rst
  Lib/platform.py
  Lib/test/test_platform.py
  Misc/NEWS.d/next/Library/2018-06-13-20-33-29.bpo-26544.hQ1oMt.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, type-bugfix

#8195 [3.6] [3.7] bpo-26544: Fixed implementation of platform.libc_ver(). (GH-7684). (GH-8193)
  Doc/library/platform.rst
  Lib/platform.py
  Lib/test/test_platform.py
  Misc/NEWS.d/next/Library/2018-06-13-20-33-29.bpo-26544.hQ1oMt.rst
Labels: CLA signed, awaiting review, type-bugfix

#8196 [2.7] bpo-26544: Fixed implementation of platform.libc_ver(). (GH-7684). (GH-8193)
  Lib/platform.py
  Lib/test/test_platform.py
  Misc/NEWS.d/next/Library/2018-06-13-20-33-29.bpo-26544.hQ1oMt.rst
Labels: CLA signed, awaiting merge, type-bugfix

#6517 bpo-33305: Improve SyntaxError for invalid numerical literals.
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core and Builtins/2018-04-18-14-17-44.bpo-33305.9z3dDH.rst
  Parser/tokenizer.c
Labels: CLA signed, awaiting merge, type-enhancement

#8159 bpo-34066: Disabled interruption before SETUP_WITH and BEFORE_ASYNC_WITH.
  Misc/NEWS.d/next/Core and Builtins/2018-07-07-20-15-34.bpo-34066.y9vs6s.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#8197 [3.7] bpo-34066: Disabled interruption before SETUP_WITH and BEFORE_ASYNC_WITH. (GH-8159)
  Misc/NEWS.d/next/Core and Builtins/2018-07-07-20-15-34.bpo-34066.y9vs6s.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge, type-bugfix

#8158 bpo-34067: Include a more easily understood example for nullcontext
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting review, needs backport to 3.7, skip news

#8174 [3.7] bpo-28626: rearrange discussion of output formatting to encourage f-strings (GH-6036)
  Doc/tutorial/inputoutput.rst
Labels: CLA signed, awaiting merge, skip news

#8199 [3.7] bpo-34067: Include a more easily understood example for nullcontext (GH-8158)
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting merge, skip news

#8200 [3.7] Fixed several assertTrue() that were intended to be assertEqual(). (GH-8191)
  Lib/ctypes/test/test_as_parameter.py
  Lib/test/test_pkg.py
  Lib/test/test_socket.py
  Lib/test/test_support.py
  Lib/test/test_tokenize.py
  Lib/test/test_warnings/__init__.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#8201 [3.6] Fixed several assertTrue() that were intended to be assertEqual(). (GH-8191)
  Lib/ctypes/test/test_as_parameter.py
  Lib/test/test_pkg.py
  Lib/test/test_socket.py
  Lib/test/test_support.py
  Lib/test/test_tokenize.py
  Lib/test/test_warnings/__init__.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#8198 [3.6] bpo-34066: Disabled interruption before SETUP_WITH and BEFORE_ASYNC_WITH. (GH-8159)
  Misc/NEWS.d/next/Core and Builtins/2018-07-07-20-15-34.bpo-34066.y9vs6s.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge, type-bugfix

#8202 [2.7] Fixed several assertTrue() that were intended to be assertEqual(). (GH-8191)
  Lib/ctypes/test/test_as_parameter.py
  Lib/test/test_pkg.py
  Lib/test/test_test_support.py
  Lib/test/test_warnings.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#8194 bpo-22689: Copy the result of getenv() in sys_breakpointhook().
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-bugfix

#8206 [3.7] bpo-22689: Copy the result of getenv() in sys_breakpointhook(). (GH-8194)
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#4142 bpo-24459: Document missing env variables in python.man
  Misc/python.man
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#8207 [3.7] bpo-24459: Document missing env variables in python.man (GH-4142)
  Misc/python.man
Labels: CLA signed, awaiting merge, skip news

#8208 bpo-11572: Make several minor improvements to copy module
  Lib/copy.py
  Lib/pickle.py
Labels: CLA signed, awaiting merge, skip news

#8209 Move Code_of_Conduct.rst to the root level.
  CODE_OF_CONDUCT.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#8210 [3.7] Move Code_of_Conduct.rst to the root level. (GH-8209)
  CODE_OF_CONDUCT.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#8211 delete some unused pysqlite forward declarations
  Modules/_sqlite/module.h
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#8212 [3.7] delete some unused pysqlite forward declarations (GH-8211)
  Modules/_sqlite/module.h
Labels: CLA signed, awaiting merge, skip issue, skip news

#8213 [3.6] delete some unused pysqlite forward declarations (GH-8211)
  Modules/_sqlite/module.h
Labels: CLA signed, awaiting merge, skip issue, skip news

#8214 [2.7] delete some unused pysqlite forward declarations (GH-8211).
  Modules/_sqlite/module.h
Labels: CLA signed, awaiting merge, skip issue, skip news
