Repository python/cpython, pull requests merged in 2018-10, with the labels that each got.

#9634 Fix name of argument in docs for functools.reduce().
  Doc/library/functools.rst
Labels: CLA not signed, awaiting merge, skip issue, skip news, type-documentation

#9541 bpo-30156: Remove property_descr_get() optimization
  Misc/NEWS.d/next/Core and Builtins/2018-09-24-17-51-15.bpo-30156.pH0j5j.rst
  Objects/descrobject.c
Labels: CLA signed, awaiting merge

#9643 bpo-34476: Document that asyncio.sleep() always suspends.
  Doc/library/asyncio-task.rst
Labels: CLA not signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#9654 [3.7] bpo-34476: Document that asyncio.sleep() always suspends. (GH-9643)
  Doc/library/asyncio-task.rst
Labels: CLA not signed, awaiting merge, skip news, type-documentation

#7617 bpo-30167: Add test for module.__cached__ is None
  Lib/test/test_site.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#9662 bpo-31865: Fix a couple of typos in the html.unescape() docs.
  Doc/library/html.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#9663 [3.7] bpo-31865: Fix a couple of typos in the html.unescape() docs. (GH-9662)
  Doc/library/html.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#9664 [3.6] bpo-31865: Fix a couple of typos in the html.unescape() docs. (GH-9662)
  Doc/library/html.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#9666 bpo-34868: Improve error message with '_' is combined with an invalid type specifier.
  Lib/test/test_long.py
  Python/formatter_unicode.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#9668 [3.7] closes bpo-34868: Improve error message with '_' is combined with an invalid type specifier. (GH-9666)
  Lib/test/test_long.py
  Python/formatter_unicode.c
Labels: CLA signed, awaiting merge, skip news

#9669 [3.6] closes bpo-34868: Improve error message with '_' is combined with an invalid type specifier. (GH-9666)
  Lib/test/test_long.py
  Python/formatter_unicode.c
Labels: CLA signed, awaiting merge, skip news

#9670 Make it clear that the msg argument to assertRaises is keyword-only.
  Doc/library/unittest.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#9671 [3.7] Make it clear that the msg argument to assertRaises is keyword-only. (GH-9670)
  Doc/library/unittest.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#9672 [3.6] Make it clear that the msg argument to assertRaises is keyword-only. (GH-9670)
  Doc/library/unittest.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#9636 bpo-34843: Remove recent from logging cookbook
  Doc/howto/logging-cookbook.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9661 bpo-34728: Fix asyncio tests to run under "-Werror"
  Lib/test/test_asyncgen.py
  Lib/test/test_asyncio/functional.py
  Lib/test/test_asyncio/test_base_events.py
  Lib/test/test_asyncio/test_buffered_proto.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_locks.py
  Lib/test/test_asyncio/test_pep492.py
  Lib/test/test_asyncio/test_queues.py
  Lib/test/test_asyncio/test_selector_events.py
  Lib/test/test_asyncio/test_sslproto.py
  Lib/test/test_asyncio/test_streams.py
  Lib/test/test_asyncio/test_subprocess.py
  Lib/test/test_asyncio/test_tasks.py
  Lib/test/test_asyncio/utils.py
Labels: CLA signed, awaiting merge, skip news

#8450 bpo-34172: multiprocessing.Pool leaks resources after being deleted
  Lib/multiprocessing/pool.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2018-07-26-10-31-52.bpo-34172.8ovLNi.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#9676 [3.7] bpo-34172: multiprocessing.Pool leaks resources after being deleted (GH-8450)
  Lib/multiprocessing/pool.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2018-07-26-10-31-52.bpo-34172.8ovLNi.rst
Labels: CLA signed, awaiting review

#9677 [3.6] bpo-34172: multiprocessing.Pool leaks resources after being deleted (GH-8450)
  Lib/multiprocessing/pool.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2018-07-26-10-31-52.bpo-34172.8ovLNi.rst
Labels: CLA signed, awaiting review

#9680 Make it clear that the msg argument to assertWarns/assertWarnsRegex/assertRaisesRegex is keyword-only.
  Doc/library/unittest.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#9682 [3.6] Make it clear that the msg argument to assertWarns/assertWarnsRegex/assertRaisesRegex is keyword-only. (GH-9680)
  Doc/library/unittest.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#9683 bpo-34879: Fix a possible null pointer dereference in bytesobject.c
  Misc/NEWS.d/next/Core and Builtins/2018-10-02-22-55-11.bpo-34879.7VNH2a.rst
  Objects/bytesobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#9684 [3.7] bpo-34879: Fix a possible null pointer dereference in bytesobject.c (GH-9683)
  Misc/NEWS.d/next/Core and Builtins/2018-10-02-22-55-11.bpo-34879.7VNH2a.rst
  Objects/bytesobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#9685 [3.6] bpo-34879: Fix a possible null pointer dereference in bytesobject.c (GH-9683)
  Misc/NEWS.d/next/Core and Builtins/2018-10-02-22-55-11.bpo-34879.7VNH2a.rst
  Objects/bytesobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#9686 [2.7] bpo-34172: multiprocessing.Pool leaks resources after being deleted (GH-8450)
  Lib/multiprocessing/pool.py
  Lib/test/test_multiprocessing.py
  Misc/NEWS.d/next/Library/2018-07-26-10-31-52.bpo-34172.8ovLNi.rst
Labels: CLA signed, awaiting merge

#9679 bpo-34872: Fix self-cancellation in C implementation of asyncio.Task
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2018-10-02-19-36-34.bpo-34872.yWZRhI.rst
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#9690 [3.6] bpo-34872: Fix self-cancellation in C implementation of asyncio.Task (GH-9679)
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2018-10-02-19-36-34.bpo-34872.yWZRhI.rst
  Modules/_asynciomodule.c
Labels: :robot: automerge, CLA signed, awaiting merge

#9691 [3.7] bpo-34872: Fix self-cancellation in C implementation of asyncio.Task (GH-9679)
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2018-10-02-19-36-34.bpo-34872.yWZRhI.rst
  Modules/_asynciomodule.c
Labels: :robot: automerge, CLA signed, awaiting merge

#9420 bpo-34739: Get rid of tp_getattro in xml.etree.ElementTree.XMLParser.
  Modules/_elementtree.c
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#9421 bpo-34740: Get rid of tp_getattro in ossaudiodev.oss_audio_device.
  Modules/ossaudiodev.c
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#9698 bpo-34871: Fix two typos in test_inspect.py
  Lib/test/test_inspect.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#9696 bpo-34871: inspect: Don't pollute sys.modules
  Lib/inspect.py
  Misc/NEWS.d/next/Library/2018-10-04-18-46-54.bpo-34871.t3X-dB.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#9697 Update ssl.py
  Lib/ssl.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#9710 [3.6] Fix a typo ssl.py docstring (GH-9697)
  Lib/ssl.py
Labels: CLA signed, awaiting review, skip issue, skip news

#9709 [3.7] Fix a typo ssl.py docstring (GH-9697)
  Lib/ssl.py
Labels: CLA signed, awaiting review, skip issue, skip news

#4348 bpo-28441: Ensure `.exe` suffix in `sys.executable` on MinGW and Cygwin
  Misc/NEWS.d/next/Library/2018-10-04-15-53-14.bpo-28441.2sQENe.rst
  Modules/getpath.c
Labels: :robot: automerge, CLA signed, awaiting merge

#9712 bpo-34906: Doc: Fix typos
  Doc/library/dis.rst
  Doc/library/ssl.rst
  Doc/library/zipapp.rst
  Doc/whatsnew/3.6.rst
  Lib/bdb.py
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#9714 [3.7] bpo-34906: Doc: Fix typos (GH-9712)
  Doc/library/dis.rst
  Doc/library/ssl.rst
  Doc/library/zipapp.rst
  Doc/whatsnew/3.6.rst
  Lib/bdb.py
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, skip news

#9717 [3.7] bpo-34825: Add more entries to os to pathlib reference table (GH-9608)
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9718 Simplify flags check in sre_compile.py.
  Lib/sre_compile.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#9719 bpo-34902: Fixes VM image for Azure Pipelines build
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#9721 Use assertEqual() instead of assertEquals().
  Lib/ctypes/test/test_win32.py
  Lib/test/test_grammar.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#9722 Fix a compiler warning added in bpo-34872.
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#9723 [3.7] bpo-34902: Fixes VM image for Azure Pipelines build (GH-9719)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, awaiting merge, skip news

#9724 [3.6] bpo-34902: Fixes VM image for Azure Pipelines build (GH-9719)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, awaiting merge, skip news

#9725 [3.7] Use assertEqual() instead of assertEquals(). (GH-9721)
  Lib/ctypes/test/test_win32.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, skip issue, skip news, type-tests

#9726 [3.7] Fix a compiler warning added in bpo-34872. (GH-9722).
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, skip issue, skip news

#9727 [3.6] Use assertEqual() instead of assertEquals(). (GH-9721) (GH-9725)
  Lib/ctypes/test/test_win32.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#9728 [3.6] [3.7] Fix a compiler warning added in bpo-34872. (GH-9722). (GH-9726)
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#9705 bpo-34899: Fix a possible assertion failure due to int_from_bytes_impl()
  Objects/longobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-bugfix

#9729 [3.7] bpo-34899: Fix a possible assertion failure due to int_from_bytes_impl() (GH-9705)
  Objects/longobject.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#8377 bpo-34158: Documentation UTC offset update
  Doc/library/datetime.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#9065 [3.7] bpo-34565: Change a PC/launcher.c comment to accurately describe valid major versions. (GH-9037)
  PC/launcher.c
Labels: CLA signed, awaiting merge, skip news

#9408 [3.7] Clarify that AsyncExitStack works with coroutine functions (GH-9405)
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#9604 [3.7] Fix markup for xml.sax in 3.7 notes
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#9681 [3.7] Make it clear that the msg argument to assertWarns/assertWarnsRegex/assertRaisesRegex is keyword-only. (GH-9680)
  Doc/library/unittest.rst
Labels: awaiting merge, skip issue, skip news, type-documentation

#9732 [3.7] bpo-34158: Documentation UTC offset update (GH-8377)
  Doc/library/datetime.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#9229 [3.6] bpo-34282: Fix Enum._convert method shadowing members named _convert
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2018-09-02-13-33-35.bpo-34282.ztyXH8.rst
Labels: CLA signed, awaiting review

#9737 bpo-34909: keep searching mixins until base class is found
  Lib/enum.py
  Lib/test/test_enum.py
Labels: CLA signed, awaiting merge, skip news

#9733 bpo-34910: Ensure PyObject_Print() always returns -1 on error
  Misc/NEWS.d/next/C API/2018-10-05-17-06-49.bpo-34910.tSFrls.rst
  Objects/object.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#9740 [3.6] bpo-34910: Ensure that PyObject_Print() always returns -1 on error. (GH-9733)
  Misc/NEWS.d/next/C API/2018-10-05-17-06-49.bpo-34910.tSFrls.rst
  Objects/object.c
Labels: CLA signed, awaiting merge, type-bugfix

#9739 [3.7] bpo-34910: Ensure that PyObject_Print() always returns -1 on error. (GH-9733)
  Misc/NEWS.d/next/C API/2018-10-05-17-06-49.bpo-34910.tSFrls.rst
  Objects/object.c
Labels: CLA signed, awaiting merge, type-bugfix

#9738 [3.7] bpo-34909: keep searching mixins until base class is found (GH-9737)
  Lib/enum.py
  Lib/test/test_enum.py
Labels: CLA signed, awaiting review, skip news

#9735 bpo-34906: Doc: Fix typos (2)
  Doc/whatsnew/3.3.rst
  Doc/whatsnew/3.5.rst
  Doc/whatsnew/3.7.rst
  Lib/idlelib/NEWS.txt
  Misc/HISTORY
  Misc/NEWS.d/3.5.0a1.rst
  Misc/NEWS.d/3.5.0a2.rst
  Misc/NEWS.d/3.5.0a3.rst
  Misc/NEWS.d/3.5.0a4.rst
  Misc/NEWS.d/3.5.1rc1.rst
  Misc/NEWS.d/3.5.2rc1.rst
  Misc/NEWS.d/3.5.3rc1.rst
  Misc/NEWS.d/3.5.4rc1.rst
  Misc/NEWS.d/3.6.0a1.rst
  Misc/NEWS.d/3.6.0a2.rst
  Misc/NEWS.d/3.6.0a3.rst
  Misc/NEWS.d/3.6.0a4.rst
  Misc/NEWS.d/3.6.0b1.rst
  Misc/NEWS.d/3.6.2rc2.rst
  Misc/NEWS.d/3.6.3rc1.rst
  Misc/NEWS.d/3.6.4rc1.rst
  Misc/NEWS.d/3.6.6rc1.rst
  Misc/NEWS.d/3.7.0a1.rst
  Misc/NEWS.d/3.7.0a3.rst
  Misc/NEWS.d/3.7.0b2.rst
  Misc/NEWS.d/3.7.0b3.rst
  Misc/NEWS.d/3.7.0b5.rst
  Misc/NEWS.d/next/Core and Builtins/2018-09-13-12-21-08.bpo-34651.v-bUeV.rst
  Misc/NEWS.d/next/Documentation/2018-01-25-13-58-49.bpo-30607.4dXxiq.rst
  Misc/NEWS.d/next/Documentation/2018-05-13-14-44-30.bpo-33487.iLDzFb.rst
  Misc/NEWS.d/next/Library/2017-12-06-10-10-10.bpo-32221.ideco_.rst
  Misc/NEWS.d/next/Library/2018-03-06-20-30-20.bpo-32999.lgFXWl.rst
  Misc/NEWS.d/next/Library/2018-05-18-21-50-47.bpo-33570.7CZy4t.rst
  Misc/NEWS.d/next/Library/2018-06-29-00-31-36.bpo-14117.3nvDuR.rst
  Misc/NEWS.d/next/Library/2018-09-30-08-08-14.bpo-34849.NXK9Ff.rst
  Misc/NEWS.d/next/Tools-Demos/2018-02-20-12-16-47.bpo-32885.dL5x7C.rst
  Misc/NEWS.d/next/Windows/2018-05-16-11-31-17.bpo-29097.9mqEuI.rst
  Modules/_ctypes/libffi_msvc/win32.c
Labels: CLA signed, awaiting merge, skip news

#9606 bpo-34824: Fix a possible NULL pointer dereference in _ssl.c
  Misc/NEWS.d/next/Core and Builtins/2018-09-27-11-10-02.bpo-34824.VLlCaU.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#9745 Correct grammar mistake in re.rst
  Doc/library/re.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#9746 [3.7] Correct grammar mistake in re.rst. (GH-9745)
  Doc/library/re.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#9581 [3.7] bpo-34334: Don't log traceback twice in QueueHandler (GH-9537)
  Doc/library/logging.handlers.rst
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2018-09-25-08-42-34.bpo-34334.rSPBW9.rst
Labels: CLA signed, awaiting review

#9291 [3.7] bpo-6721: Hold logging locks across fork() (GH-4071)
  Lib/logging/__init__.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2018-09-13-10-09-19.bpo-6721.ZUL_F3.rst
Labels: CLA signed, awaiting review, sprint, type-bugfix

#9708 bpo-34901: add isolated (-I) flag to sys.flags
  Doc/library/sys.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#6088 bpo-33014: Clarify str.isidentifier docstring
  Doc/library/stdtypes.rst
  Objects/clinic/unicodeobject.c.h
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, skip news

#9756 bpo-33014: minor docstring fixup
  Objects/clinic/unicodeobject.c.h
  Objects/unicodeobject.c
Labels: CLA signed, awaiting review, skip issue, skip news

#9753 bpo-34925: Optimize common case for bisect() argument parsing
  Misc/NEWS.d/next/Library/2018-10-07-20-37-02.bpo-34925.KlkZ-Y.rst
  Modules/_bisectmodule.c
Labels: CLA signed, awaiting merge, type-performance

#9754 bpo-34817: Use double quote instead of backtick to clarify Ellipsis constant
  Doc/library/constants.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9617 bpo-34829: Add missing selection_ methods to the Tkinter Spinbox
  Doc/whatsnew/3.8.rst
  Lib/tkinter/__init__.py
  Lib/tkinter/test/test_tkinter/test_widgets.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-10-08-16-04-36.bpo-34829.B7v7D0.rst
Labels: CLA signed, awaiting merge, type-enhancement

#9734 bpo-34911: Added support for secure websocket cookies
  Doc/library/http.cookiejar.rst
  Lib/http/cookiejar.py
  Lib/test/test_http_cookiejar.py
  Misc/NEWS.d/next/Library/2018-10-08-15-22-02.bpo-34911.hCy0Fv.rst
Labels: CLA signed, awaiting merge

#9750 bpo-34921: No return not allowed by get_type_hints; line 133 …
  Lib/typing.py
Labels: CLA not signed, awaiting review, skip news

#3908 bpo-31715 Add mimetype for extension .mjs
  Lib/mimetypes.py
  Misc/NEWS.d/next/Library/2018-08-15-16-22-30.bpo-31715.Iw8jS8.rst
Labels: CLA signed, awaiting merge

#9761 bpo-34937: Extract tests for sock_*() functions into a separate file
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_sock_lowlevel.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#9758 bpo-32174: Let .chm document display non-ASCII characters properly
  Doc/conf.py
  Doc/tools/extensions/escape4chm.py
  Misc/NEWS.d/next/Documentation/2018-10-08-19-15-28.bpo-32174.YO9CYm.rst
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7

#9464 bpo-34758: add .wasm to recognized file extensions in mimetypes module
  Lib/mimetypes.py
  Misc/NEWS.d/next/Library/2018-09-26-14-09-34.bpo-34758.bRBfAi.rst
Labels: CLA signed, awaiting merge

#9757 bpo-34929: Extract sendfile tests into a separate test file
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_sendfile.py
Labels: CLA signed, awaiting merge, expert-asyncio, skip news, type-tests

#5345 bpo-32680 add default "sock" on SMTP objects
  Lib/smtplib.py
  Lib/test/test_smtplib.py
  Misc/NEWS.d/next/Library/2018-10-09-14-25-36.bpo-32680.z2FbOp.rst
Labels: CLA signed, awaiting change review

#9656 bpo-32962: Fix test_gdb failure in debug build with -mcet -fcf-protection -O0
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Tests/2018-05-10-16-59-15.bpo-32962.S-rcIN.rst
Labels: CLA signed, needs backport to 3.6, needs backport to 3.7

#9771 [3.6] bpo-32962: Fix test_gdb failure in debug build with -mcet -fcf-protection -O0 (GH-9656)
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Tests/2018-05-10-16-59-15.bpo-32962.S-rcIN.rst
Labels: CLA signed, awaiting merge, type-tests

#9770 [3.7] bpo-32962: Fix test_gdb failure in debug build with -mcet -fcf-protection -O0 (GH-9656)
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Tests/2018-05-10-16-59-15.bpo-32962.S-rcIN.rst
Labels: CLA signed, awaiting merge, type-tests

#9716 bpo-34769: Thread safety for _asyncgen_finalizer_hook().
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_base_events.py
  Misc/NEWS.d/next/Library/2018-10-09-11-01-16.bpo-34769.cSkkZt.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#9772 [3.7] bpo-34769: Thread safety for _asyncgen_finalizer_hook(). (GH-9716)
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_base_events.py
  Misc/NEWS.d/next/Library/2018-10-09-11-01-16.bpo-34769.cSkkZt.rst
Labels: CLA signed, awaiting merge

#9775 bpo-23596: Add unit tests for the command line for the gzip module
  Lib/test/test_gzip.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#9780 [3.6] bpo-23596: Add unit tests for the command line for the gzip module (GH-9775)
  Lib/test/test_gzip.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#9779 [3.7] bpo-23596: Add unit tests for the command line for the gzip module (GH-9775)
  Lib/test/test_gzip.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#9781 bpo-23596: Use argparse for the command line of gzip
  Lib/gzip.py
  Misc/NEWS.d/next/Tests/2018-10-09-23-51-07.bpo-23596.rdnert.rst
Labels: CLA signed, awaiting merge

#9782 bpo-34913: Document gzip command line interface
  Doc/library/gzip.rst
  Misc/NEWS.d/next/Documentation/2018-10-10-00-34-08.bpo-34913.kVd1Fv.rst
Labels: CLA signed, awaiting core review, type-documentation

#9776 Convert code of conduct to markdown for Github
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.rst
Labels: CLA signed, awaiting review, skip issue, skip news

#9778 bpo-33613: Fix test_semaphore_tracker signal tests when using -Werror
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#9788 [2.7] bpo-32962: Fix test_gdb failure in debug build with -mcet -fcf-protection -O0 (GH-9656)
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Tests/2018-05-10-16-59-15.bpo-32962.S-rcIN.rst
Labels: CLA signed, awaiting merge, type-tests

#9789 [3.7] bpo-34906: Doc: Fix typos (2) (GH-9735)
  Doc/whatsnew/3.3.rst
  Doc/whatsnew/3.5.rst
  Doc/whatsnew/3.7.rst
  Lib/idlelib/NEWS.txt
  Misc/HISTORY
  Misc/NEWS.d/3.5.0a1.rst
  Misc/NEWS.d/3.5.0a2.rst
  Misc/NEWS.d/3.5.0a3.rst
  Misc/NEWS.d/3.5.0a4.rst
  Misc/NEWS.d/3.5.1rc1.rst
  Misc/NEWS.d/3.5.2rc1.rst
  Misc/NEWS.d/3.5.3rc1.rst
  Misc/NEWS.d/3.5.4rc1.rst
  Misc/NEWS.d/3.6.0a1.rst
  Misc/NEWS.d/3.6.0a2.rst
  Misc/NEWS.d/3.6.0a3.rst
  Misc/NEWS.d/3.6.0a4.rst
  Misc/NEWS.d/3.6.0b1.rst
  Misc/NEWS.d/3.6.2rc2.rst
  Misc/NEWS.d/3.6.3rc1.rst
  Misc/NEWS.d/3.6.4rc1.rst
  Misc/NEWS.d/3.6.6rc1.rst
  Misc/NEWS.d/3.7.0a1.rst
  Misc/NEWS.d/3.7.0a3.rst
  Misc/NEWS.d/3.7.0b2.rst
  Misc/NEWS.d/3.7.0b3.rst
  Misc/NEWS.d/3.7.0b5.rst
  Modules/_ctypes/libffi_msvc/win32.c
Labels: CLA signed, awaiting merge, skip news

#9790 [3.6] bpo-34906: Doc: Fix typos (2) (GH-9735)
  Doc/whatsnew/3.3.rst
  Doc/whatsnew/3.5.rst
  Lib/idlelib/NEWS.txt
  Misc/HISTORY
  Misc/NEWS.d/3.5.0a1.rst
  Misc/NEWS.d/3.5.0a2.rst
  Misc/NEWS.d/3.5.0a3.rst
  Misc/NEWS.d/3.5.0a4.rst
  Misc/NEWS.d/3.5.1rc1.rst
  Misc/NEWS.d/3.5.2rc1.rst
  Misc/NEWS.d/3.5.3rc1.rst
  Misc/NEWS.d/3.6.0a1.rst
  Misc/NEWS.d/3.6.0a2.rst
  Misc/NEWS.d/3.6.0a3.rst
  Misc/NEWS.d/3.6.0a4.rst
  Misc/NEWS.d/3.6.0b1.rst
  Misc/NEWS.d/3.6.2rc2.rst
  Misc/NEWS.d/3.6.3rc1.rst
  Misc/NEWS.d/3.6.4rc1.rst
  Misc/NEWS.d/3.6.6rc1.rst
  Modules/_ctypes/libffi_msvc/win32.c
Labels: CLA signed, awaiting review, skip news

#9777 bpo-34926: Make mimetypes.guess_type accept os.PathLike objects
  Doc/library/mimetypes.rst
  Lib/mimetypes.py
  Lib/test/test_mimetypes.py
  Misc/NEWS.d/next/Library/2018-10-10-00-22-57.bpo-34926.CA0rqd.rst
Labels: CLA signed, awaiting merge, type-enhancement

#9607 bpo-34022: Stop forcing of hash-based invalidation with SOURCE_DATE_EPOCH
  Doc/library/compileall.rst
  Doc/library/py_compile.rst
  Lib/compileall.py
  Lib/py_compile.py
  Lib/test/test_compileall.py
  Lib/test/test_importlib/source/test_file_loader.py
  Lib/test/test_py_compile.py
  Misc/NEWS.d/next/Library/2018-09-27-13-14-15.bpo-34022.E2cl0r.rst
Labels: CLA signed, awaiting merge

#9720 bpo-34576 warn users on security for http.server
  Doc/library/http.server.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9794 [3.6] bpo-34576 warn users on security for http.server (GH-9720)
  Doc/library/http.server.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9784 Micro-optimize list index range checks
  Objects/listobject.c
Labels: CLA signed, awaiting merge, skip issue, skip news, type-performance

#9795 [3.7] bpo-34576 warn users on security for http.server (GH-9720)
  Doc/library/http.server.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9751 bpo-34922: Fixed integer overflow in the digest() and hexdigest() methods
  Lib/test/test_hashlib.py
  Misc/NEWS.d/next/Library/2018-10-07-21-18-52.bpo-34922.37IdsA.rst
  Modules/_sha3/sha3module.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#9657 [3.6] bpo-33729: Fix issues with arguments parsing in hashlib. (GH-8346) (GH-8581)
  Doc/library/hashlib.rst
  Lib/hashlib.py
  Lib/test/test_hashlib.py
  Misc/NEWS.d/next/Library/2018-07-20-09-11-05.bpo-33729.sO6iTb.rst
  Modules/_blake2/blake2b_impl.c
  Modules/_blake2/blake2s_impl.c
  Modules/_blake2/clinic/blake2b_impl.c.h
  Modules/_blake2/clinic/blake2s_impl.c.h
  Modules/_hashopenssl.c
  Modules/_sha3/clinic/sha3module.c.h
  Modules/_sha3/sha3module.c
Labels: CLA signed, awaiting merge, type-bugfix

#9786 [Skip Issue] Fix a possible decref of a borrowed reference in symtable.c
  Python/symtable.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#9798 [3.7] bpo-34922: Fix integer overflow in the digest() and hexdigest() methods (GH-9751)
  Lib/test/test_hashlib.py
  Misc/NEWS.d/next/Library/2018-10-07-21-18-52.bpo-34922.37IdsA.rst
  Modules/_sha3/sha3module.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, type-bugfix

#9800 [3.6] Fix a possible decref of a borrowed reference in symtable.c. (GH-9786)
  Python/symtable.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#9801 [3.6] bpo-34922: Fix integer overflow in the digest() and hexdigest() methods (GH-9751) (GH-9798)
  Lib/test/test_hashlib.py
  Misc/NEWS.d/next/Library/2018-10-07-21-18-52.bpo-34922.37IdsA.rst
  Modules/_sha3/sha3module.c
Labels: CLA signed, awaiting review, type-bugfix

#9810 [Skip Issue] Fix an incorrect check in compiler_try_except()
  Python/compile.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-bugfix

#9811 [3.7] Fix an incorrect check in compiler_try_except(). (GH-9810)
  Python/compile.c
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#9812 [3.6] Fix an incorrect check in compiler_try_except(). (GH-9810)
  Python/compile.c
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#9806 bpo-34962: make doctest in Doc now passes, and is enforced in CI
  .travis.yml
  Doc/conf.py
  Doc/distutils/examples.rst
  Doc/library/multiprocessing.rst
  Doc/library/re.rst
  Doc/library/turtle.rst
  Doc/library/unittest.mock-examples.rst
  Doc/library/unittest.mock.rst
  Misc/NEWS.d/next/Tests/2018-10-11-22-34-27.bpo-34962.0PLBi8.rst
Labels: CLA signed, awaiting merge

#9764 bpo-34940: Fix the error handling in _check_for_legacy_statements()
  Objects/exceptions.c
Labels: CLA signed, awaiting merge, skip news

#8052 bpo-31516: Skip test_main_thread_during_shutdown() with COUNT_ALLOCS builds
  Lib/test/test_threading.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#9813 [3.7] bpo-31516: Skip test_main_thread_during_shutdown() with COUNT_ALLOCS builds. (GH-8052)
  Lib/test/test_threading.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#9814 [3.6] bpo-31516: Skip test_main_thread_during_shutdown() with COUNT_ALLOCS builds. (GH-8052)
  Lib/test/test_threading.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#9796 bpo-34203: Faq should connote python3 usage
  Doc/faq/general.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#9707 bpo-34900: Fix subTests to not crash when called from TestCase.debug()
  Lib/unittest/case.py
  Lib/unittest/test/test_case.py
  Misc/NEWS.d/next/Library/2018-10-05-05-55-53.bpo-34900.8RNiFu.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#9818 [3.7] bpo-34900: Make TestCase.debug() work with subtests (GH-9707)
  Lib/unittest/case.py
  Lib/unittest/test/test_case.py
  Misc/NEWS.d/next/Library/2018-10-05-05-55-53.bpo-34900.8RNiFu.rst
Labels: CLA signed, awaiting review

#9819 [3.6] bpo-34900: Make TestCase.debug() work with subtests (GH-9707)
  Lib/unittest/case.py
  Lib/unittest/test/test_case.py
  Misc/NEWS.d/next/Library/2018-10-05-05-55-53.bpo-34900.8RNiFu.rst
Labels: CLA signed, awaiting review

#9815 [3.7] bpo-34203: FAQ now recommends python 3.x over 2.x (GH-9796)
  Doc/faq/general.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9816 [3.6] bpo-34203: FAQ now recommends python 3.x over 2.x (GH-9796)
  Doc/faq/general.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9817 [2.7] bpo-34203: FAQ now recommends python 3.x over 2.x (GH-9796)
  Doc/faq/general.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#9692 bpo-11233: Create availability directive for documentation
  Doc/c-api/exceptions.rst
  Doc/c-api/init.rst
  Doc/library/_thread.rst
  Doc/library/asyncio-eventloop.rst
  Doc/library/asyncio-policy.rst
  Doc/library/asyncio-stream.rst
  Doc/library/asyncore.rst
  Doc/library/codecs.rst
  Doc/library/hashlib.rst
  Doc/library/intro.rst
  Doc/library/mimetypes.rst
  Doc/library/os.path.rst
  Doc/library/os.rst
  Doc/library/resource.rst
  Doc/library/select.rst
  Doc/library/shutil.rst
  Doc/library/signal.rst
  Doc/library/socket.rst
  Doc/library/ssl.rst
  Doc/library/subprocess.rst
  Doc/library/sys.rst
  Doc/library/threading.rst
  Doc/library/time.rst
  Doc/tools/extensions/pyspecific.py
  Doc/tools/rstlint.py
  Doc/using/cmdline.rst
  Misc/NEWS.d/next/Documentation/2018-10-03-20-39-25.bpo-11233.BX6Gen.rst
Labels: CLA signed, awaiting changes

#9822 bpo-34964: Make Tkinter sources more readable by adding blank lines.
  Lib/tkinter/__init__.py
  Lib/tkinter/commondialog.py
  Lib/tkinter/dialog.py
  Lib/tkinter/dnd.py
  Lib/tkinter/filedialog.py
  Lib/tkinter/messagebox.py
  Lib/tkinter/scrolledtext.py
  Lib/tkinter/simpledialog.py
Labels: CLA signed, awaiting merge, skip news

#9768 bpo-23831: Add moveto method to the tkinter.Canvas widget
  Doc/whatsnew/3.8.rst
  Lib/tkinter/__init__.py
  Lib/tkinter/test/test_tkinter/test_widgets.py
  Misc/NEWS.d/next/Library/2018-10-09-15-44-04.bpo-23831.2CL7lL.rst
Labels: CLA signed, awaiting merge

#9831 bpo-34783: Disable test_nonexisting_script for macOS framework builds
  Lib/test/test_cmd_line_script.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-tests

#9832 [3.7] bpo-34783: Disable test_nonexisting_script for macOS framework builds (GH-9831)
  Lib/test/test_cmd_line_script.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#9827 bpo-34967: Sphinx is deprecating add_description_unit, use add_object_type
  Doc/tools/extensions/pyspecific.py
  Misc/NEWS.d/next/Documentation/2018-10-13-07-39-57.bpo-34967.E40tFP.rst
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#9838 [3.7] bpo-16965: 2to3 now rewrites execfile() to open with 'rb'. (GH-8569)
  Lib/lib2to3/fixes/fix_execfile.py
  Lib/lib2to3/tests/test_fixers.py
  Misc/NEWS.d/next/Library/2018-10-12-20-30-42.bpo-16965.xo5LAr.rst
Labels: CLA signed, awaiting merge, type-bugfix

#9839 [3.6] bpo-16965: 2to3 now rewrites execfile() to open with 'rb'. (GH-8569)
  Lib/lib2to3/fixes/fix_execfile.py
  Lib/lib2to3/tests/test_fixers.py
  Misc/NEWS.d/next/Library/2018-10-12-20-30-42.bpo-16965.xo5LAr.rst
Labels: CLA signed, awaiting merge, type-bugfix

#9845 Fixes issues in Windows release upload script
  Tools/msi/uploadrelease.ps1
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#9843 Add new tests for bytes and bytearray constructors.
  Lib/test/test_bytes.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-tests

#9847 [3.7] Add new tests for bytes and bytearray constructors. (GH-9843)
  Lib/test/test_bytes.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#9837 bpo-34970: Protect tasks weak set manipulation in asyncio.all_tasks()
  Lib/asyncio/tasks.py
  Misc/NEWS.d/next/Library/2018-10-13-11-14-13.bpo-34970.SrJTY7.rst
Labels: :robot: automerge, CLA signed, awaiting merge, expert-asyncio, needs backport to 3.7, type-bugfix

#9848 [3.6] Add new tests for bytes and bytearray constructors. (GH-9843)
  Lib/test/test_bytes.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#9858 bpo-33656: Move pyshell ctypes import inside try block.
  Lib/idlelib/pyshell.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#9863 [3.6] bpo-33656: Move pyshell ctypes import inside try block. (GH-9858)
  Lib/idlelib/pyshell.py
Labels: CLA signed, awaiting merge, skip news

#9766 bpo-34941: Fix searching Element subclasses.
  Lib/test/test_xml_etree.py
  Misc/NEWS.d/next/Library/2018-10-09-14-42-16.bpo-34941.1Q5QKv.rst
  Modules/_elementtree.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#9867 [3.7] bpo-34941: Fix searching Element subclasses. (GH-9766)
  Lib/test/test_xml_etree.py
  Misc/NEWS.d/next/Library/2018-10-09-14-42-16.bpo-34941.1Q5QKv.rst
  Modules/_elementtree.c
Labels: CLA signed, awaiting merge, type-bugfix

#9864 Fix grammar and use "coroutine" instead of "async def function" in compound_stmts.rst
  Doc/reference/compound_stmts.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#9869 [3.7] Update compound_stmts.rst (GH-9864)
  Doc/reference/compound_stmts.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#9868 [3.6] bpo-34941: Fix searching Element subclasses. (GH-9766)
  Lib/test/test_xml_etree.py
  Misc/NEWS.d/next/Library/2018-10-09-14-42-16.bpo-34941.1Q5QKv.rst
  Modules/_elementtree.c
Labels: CLA signed, awaiting merge, type-bugfix

#9866 [2.7] Add new tests for bytearray constructor. (GH-9843)
  Lib/test/test_bytes.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#9850 bpo-34521: Add NEWS entry for changes in GH-9613
  Misc/NEWS.d/next/Library/2018-10-13-19-15-23.bpo-34521.YPaiTK.rst
Labels: CLA signed, awaiting merge, type-tests

#9844 bpo-34939: Allow annotated global names in module namespace
  Lib/test/test_symtable.py
  Misc/NEWS.d/next/Core and Builtins/2018-10-13-17-40-15.bpo-34939.0gpxlJ.rst
  Python/symtable.c
Labels: CLA signed, awaiting merge

#9852 bpo-34974: Do not replace unexpected errors in bytes() and bytearray().
  Lib/test/test_bytes.py
  Misc/NEWS.d/next/Core and Builtins/2018-10-13-22-24-19.bpo-34974.7LgTc2.rst
  Objects/bytearrayobject.c
  Objects/bytesobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#9879 [3.6] bpo-34974: Do not replace unexpected errors in bytes() and bytearray(). (GH-9852)
  Lib/test/test_bytes.py
  Misc/NEWS.d/next/Core and Builtins/2018-10-13-22-24-19.bpo-34974.7LgTc2.rst
  Objects/bytearrayobject.c
  Objects/bytesobject.c
Labels: CLA signed, awaiting merge, type-bugfix
