Repository python/cpython, pull requests merged in 2018-06, with the labels that each got.

#7285 bpo-33606: improve logging performance when logger is disabled
  Lib/logging/__init__.py
  Lib/test/test_logging.py
Labels: CLA signed, awaiting merge, skip news

#7293 bpo-33692: pythoninfo detect libedit on Python 3.6
  Lib/test/pythoninfo.py
Labels: CLA signed, awaiting merge, skip news

#7292 bpo-33718: regrtest: enhance "running:" formatting
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/runtest_mp.py
  Lib/test/libregrtest/utils.py
Labels: CLA signed, awaiting merge, skip news

#7296 bpo-32519: Removed misleading sentence from EnvBuilder documentation.
  Doc/library/venv.rst
Labels: CLA signed, awaiting merge, skip news

#7297 bpo-33400: Removed references to RFC3339 and ISO8601 from the logging…
  Doc/library/logging.config.rst
  Doc/library/logging.rst
Labels: CLA signed, awaiting merge, skip news

#7146 bpo-30654: Do not reset SIGINT handler to SIG_DFL in finisignal
  Misc/NEWS.d/next/Core and Builtins/2018-05-28-12-28-53.bpo-30654.9fDJye.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7

#7301 [3.6] bpo-33692: Update pythoninfo from master
  Lib/test/pythoninfo.py
Labels: CLA signed, awaiting merge, skip news

#7298 [3.7] bpo-33692: Update pythoninfo from master
  Lib/test/pythoninfo.py
Labels: CLA signed, awaiting merge, skip news

#7305 [3.7] bpo-33718: regrtest: update from master
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/runtest_mp.py
  Lib/test/libregrtest/utils.py
Labels: CLA signed, awaiting merge, skip news

#7304 [2.7] bpo-33692: Update pythoninfo from master
  Lib/test/pythoninfo.py
Labels: CLA signed, awaiting merge, skip news

#7306 [3.7] bpo-30654: Do not reset SIGINT handler to SIG_DFL in finisignal (GH-7146)
  Misc/NEWS.d/next/Core and Builtins/2018-05-28-12-28-53.bpo-30654.9fDJye.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting review

#7307 [3.6] bpo-30654: Do not reset SIGINT handler to SIG_DFL in finisignal (GH-7146)
  Misc/NEWS.d/next/Core and Builtins/2018-05-28-12-28-53.bpo-30654.9fDJye.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting review

#7308 [3.6] bpo-31009: Move fd_count() to test.support
  Lib/test/libregrtest/refleak.py
  Lib/test/support/__init__.py
  Lib/test/test_regrtest.py
Labels: CLA signed, awaiting merge, skip news

#7309 [3.7] bpo-33540: Fix socketserver.ThreadingMixIn if block_on_close=False
  Lib/socketserver.py
Labels: CLA signed, awaiting merge, skip news

#7310 bpo-33540: Fix socketserver.ThreadingMixIn if block_on_close=False
  Lib/socketserver.py
Labels: CLA signed, awaiting merge, skip news

#7311 [3.6] test.bisect: Update from master, fix typos
  Lib/test/bisect.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#7315 [3.6] bpo-31234: Add test.support.wait_threads_exit() (GH-3578)
  Lib/test/lock_tests.py
  Lib/test/support/__init__.py
  Lib/test/test_socket.py
  Lib/test/test_thread.py
  Lib/test/test_threading.py
  Lib/test/test_threadsignals.py
Labels: CLA signed, awaiting merge, skip news

#7319 bpo-33532: Fix test_multiprocessing_forkserver.test_ignore()
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#7320 [3.7] bpo-33532: Fix test_multiprocessing_forkserver.test_ignore() (GH-7319)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#7323 [2.7] bpo-33532: Fix test_multiprocessing_forkserver.test_ignore()
  Lib/test/test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#7324 [3.6] bpo-31238: pydoc ServerThread.stop() now joins itself (GH-3151)
  Lib/pydoc.py
  Misc/NEWS.d/next/Library/2017-08-21-12-31-53.bpo-31238.Gg0LRH.rst
Labels: CLA signed, awaiting merge, skip news

#7325 [3.6] bpo-33718: Update regrtest from master
  .vsts/linux-coverage.yml
  Lib/test/libregrtest/cmdline.py
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/refleak.py
  Lib/test/libregrtest/runtest.py
  Lib/test/libregrtest/runtest_mp.py
  Lib/test/libregrtest/save_env.py
  Lib/test/libregrtest/utils.py
  Lib/test/support/__init__.py
  Lib/test/test_regrtest.py
Labels: CLA signed, awaiting merge, skip news

#7322 [3.6] bpo-33532: Fix test_multiprocessing_forkserver.test_ignore()
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#7302 [3.7] bpo-33400: Removed references to RFC3339 and ISO8601 from the logging documentation. (GH-7297)
  Doc/library/logging.config.rst
  Doc/library/logging.rst
Labels: CLA signed, awaiting review, skip news

#7303 [3.6] bpo-33400: Removed references to RFC3339 and ISO8601 from the logging documentation. (GH-7297)
  Doc/library/logging.config.rst
  Doc/library/logging.rst
Labels: CLA signed, awaiting review, skip news

#7299 [3.6] bpo-32519: Removed misleading sentence from EnvBuilder documentation. (GH-7296)
  Doc/library/venv.rst
Labels: CLA signed, awaiting review, skip news

#7300 [3.7] bpo-32519: Removed misleading sentence from EnvBuilder documentation. (GH-7296)
  Doc/library/venv.rst
Labels: CLA signed, awaiting review, skip news

#6808 bpo-29235: Make cProfile.Profile a context manager.
  Doc/library/profile.rst
  Lib/cProfile.py
  Lib/test/test_cprofile.py
  Misc/NEWS.d/next/Library/2018-05-14-15-01-55.bpo-29235.47Fzwt.rst
Labels: CLA signed, awaiting merge

#7106 bpo-33642: IDLE: Use variable number of lines in CodeContext.
  Lib/idlelib/codecontext.py
  Lib/idlelib/config-extensions.def
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_codecontext.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2018-05-24-20-42-44.bpo-33642.J0VQbS.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-enhancement

#7332 [3.7] bpo-33642: IDLE: Use variable number of lines in CodeContext. (GH-7106)
  Lib/idlelib/codecontext.py
  Lib/idlelib/config-extensions.def
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_codecontext.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2018-05-24-20-42-44.bpo-33642.J0VQbS.rst
Labels: CLA signed, awaiting merge, type-enhancement

#7333 [3.6] bpo-33642: IDLE: Use variable number of lines in CodeContext. (GH-7106)
  Lib/idlelib/codecontext.py
  Lib/idlelib/config-extensions.def
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_codecontext.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2018-05-24-20-42-44.bpo-33642.J0VQbS.rst
Labels: CLA signed, awaiting merge, type-enhancement

#7251 bpo-33615: avoid extra decref
  Include/internal/pystate.h
  Lib/test/test__xxsubinterpreters.py
  Modules/_xxsubinterpretersmodule.c
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news

#7199 bpo-33679: IDLE: Re-enable color configuration for code context
  Lib/idlelib/codecontext.py
  Lib/idlelib/config-highlight.def
  Lib/idlelib/config.py
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_codecontext.py
  Misc/NEWS.d/next/IDLE/2018-05-29-07-14-37.bpo-33679.MgX_Ui.rst
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7, type-bugfix

#7334 [3.7] bpo-33679: IDLE: Re-enable color configuration for code context (GH-7199)
  Lib/idlelib/codecontext.py
  Lib/idlelib/config-highlight.def
  Lib/idlelib/config.py
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_codecontext.py
  Misc/NEWS.d/next/IDLE/2018-05-29-07-14-37.bpo-33679.MgX_Ui.rst
Labels: CLA signed, awaiting merge, type-bugfix

#7335 [3.6] bpo-33679: IDLE: Re-enable color configuration for code context (GH-7199)
  Lib/idlelib/codecontext.py
  Lib/idlelib/config-highlight.def
  Lib/idlelib/config.py
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_codecontext.py
  Misc/NEWS.d/next/IDLE/2018-05-29-07-14-37.bpo-33679.MgX_Ui.rst
Labels: CLA signed, awaiting merge, type-bugfix

#7328 bpo-33562: Check the global asyncio event loop policy isn't set after any tests
  Lib/test/libregrtest/save_env.py
  Lib/test/support/__init__.py
  Lib/test/test_asyncgen.py
  Lib/test/test_asyncio/test_base_events.py
  Lib/test/test_asyncio/test_buffered_proto.py
  Lib/test/test_asyncio/test_context.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_futures.py
  Lib/test/test_asyncio/test_locks.py
  Lib/test/test_asyncio/test_pep492.py
  Lib/test/test_asyncio/test_proactor_events.py
  Lib/test/test_asyncio/test_queues.py
  Lib/test/test_asyncio/test_selector_events.py
  Lib/test/test_asyncio/test_server.py
  Lib/test/test_asyncio/test_sslproto.py
  Lib/test/test_asyncio/test_streams.py
  Lib/test/test_asyncio/test_subprocess.py
  Lib/test/test_asyncio/test_tasks.py
  Lib/test/test_asyncio/test_unix_events.py
  Lib/test/test_asyncio/test_windows_events.py
  Lib/test/test_asyncio/test_windows_utils.py
  Lib/test/test_contextlib_async.py
  Lib/test/test_coroutines.py
  Lib/test/test_pdb.py
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Tests/2018-06-01-14-25-31.bpo-33562.GutEHf.rst
Labels: CLA signed, awaiting merge, type-tests

#6987 Docs: fix some wrong words
  Lib/bdb.py
  configure.ac
Labels: CLA signed, awaiting merge, skip issue, skip news

#6964 Fix typo in datamodel.rst
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#7338 [3.7] Docs: fix some wrong words (GH-6987)
  Lib/bdb.py
  configure.ac
Labels: CLA signed, awaiting merge, skip issue, skip news

#7339 [3.7] Fix typo in datamodel.rst (GH-6964)
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#7340 [3.6] Fix typo in datamodel.rst (GH-6964)
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#6316 bpo-23495: Correct the documentation for writerows() of csv Writer objects
  Doc/library/csv.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#7341 [3.6] bpo-23495: Correct the documentation for writerows() of csv Writer objects (GH-6316)
  Doc/library/csv.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#7342 [3.7] bpo-23495: Correct the documentation for writerows() of csv Writer objects (GH-6316)
  Doc/library/csv.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#7343 [2.7] bpo-23495: Correct the documentation for writerows() of csv Writer objects (GH-6316)
  Doc/library/csv.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#7070 bpo-27485: Change urlparse tests to use private methods
  Lib/test/test_urlparse.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7354 [2.7] bpo-33744: Fix test_uu. (GH-7350)
  Lib/test/test_uu.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7355 bpo-33750: Reset thread-local context precision in test_round().
  Lib/test/test_decimal.py
Labels: CLA signed, awaiting merge, skip news

#7356 [3.6] bpo-33750: Reset thread-local context precision in test_round(). (GH-7355)
  Lib/test/test_decimal.py
Labels: CLA signed, awaiting review, skip news

#7357 [3.7] bpo-33750: Reset thread-local context precision in test_round(). (GH-7355)
  Lib/test/test_decimal.py
Labels: CLA signed, awaiting review, skip news

#7358 bpo-33761: Fix a file leak in test_iterparse in test_xml_etree.
  Lib/test/test_xml_etree.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#7347 [2.7] bpo-30654: Do not reset SIGINT handler to SIG_DFL in finisignal (GH-7146)
  Misc/NEWS.d/next/Core and Builtins/2018-05-28-12-28-53.bpo-30654.9fDJye.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting merge

#7359 [3.7] bpo-33761: Fix a file leak in test_iterparse in test_xml_etree. (GH-7358)
  Lib/test/test_xml_etree.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7364 bpo-33764: Appveyor fixes
  .github/appveyor.yml
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#7369 [3.7] bpo-33764: Appveyor fixes (GH-7364)
  .github/appveyor.yml
Labels: CLA signed, awaiting review, skip issue, skip news

#7361 bpo-33760: Fix file leaks in test_io.
  Lib/test/test_io.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#7362 bpo-33759: Fix test.test_xmlrpc.ServerProxyTestCase.
  Lib/test/test_xmlrpc.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#7370 [3.7] bpo-33760: Fix file leaks in test_io. (GH-7361)
  Lib/test/test_io.py
Labels: CLA signed, awaiting review, skip news, type-tests

#7371 [3.7] bpo-33759: Fix test.test_xmlrpc.ServerProxyTestCase. (GH-7362)
  Lib/test/test_xmlrpc.py
Labels: CLA signed, awaiting review, skip news, type-tests

#7372 [3.6] bpo-33760: Fix file leaks in test_io. (GH-7361)
  Lib/test/test_io.py
Labels: CLA signed, awaiting review, skip news, type-tests

#7375 [3.6] bpo-33759: Fix test.test_xmlrpc.ServerProxyTestCase. (GH-7362)
  Lib/test/test_xmlrpc.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7374 [2.7] bpo-33759: Fix test.test_xmlrpc.ServerProxyTestCase. (GH-7362)
  Lib/test/test_xmlrpc.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7250 travis: Fix macOS build
  .travis.yml
Labels: CLA signed, OS-mac, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#7379 [3.6] bpo-33764: Appveyor fixes (GH-7364)
  .github/appveyor.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#7380 [2.7] bpo-33764: Appveyor fixes (GH-7364)
  .github/appveyor.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#7365 bpo-33509: Fix test_warnings for python3 -Werror
  Lib/test/test_warnings/__init__.py
Labels: CLA signed, awaiting merge, skip news

#7344 Regenerate configure after changing configure.ac in GH-6987.
  configure
Labels: CLA signed, awaiting merge, skip issue, skip news

#7382 [3.7] Regenerate configure after changing configure.ac in GH-6987. (GH-7344)
  configure
Labels: CLA signed, awaiting review, skip issue, skip news

#7263 bpo-33640: Fix documentation issue with uuid class
  Doc/library/uuid.rst
Labels: CLA signed, awaiting review, skip news

#7295 bpo-27902: Add compatibility note to Profile docs
  Doc/library/profile.rst
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news

#6799 bpo-31849: Fix warning in pyhash.c.
  Misc/NEWS.d/next/Core and Builtins/2018-05-14-11-00-00.bpo-31849.EmHaH4.rst
  Python/pyhash.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#7321 bpo-33734: asyncio/ssl: Fix AttributeError, increase default handshake timeout
  Doc/library/asyncio-eventloop.rst
  Lib/asyncio/base_events.py
  Lib/asyncio/constants.py
  Lib/asyncio/events.py
  Lib/asyncio/sslproto.py
  Lib/test/test_asyncio/test_sslproto.py
  Lib/test/test_asyncio/utils.py
  Misc/NEWS.d/next/Library/2018-06-01-10-55-48.bpo-33734.x1W9x0.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#7351 bpo-33664: Scroll IDLE editor text by lines
  Lib/idlelib/editor.py
  Misc/NEWS.d/next/IDLE/2018-06-03-09-13-28.bpo-33664.PZzQyL.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#7367 bpo-33763: IDLE: Replace label widget with text widget in code context
  Lib/idlelib/codecontext.py
  Lib/idlelib/idle_test/test_codecontext.py
  Misc/NEWS.d/next/IDLE/2018-06-03-20-12-57.bpo-33763.URiFlE.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#7396 [3.7] bpo-33734: asyncio/ssl: a bunch of bugfixes (GH-7321)
  Doc/library/asyncio-eventloop.rst
  Lib/asyncio/base_events.py
  Lib/asyncio/constants.py
  Lib/asyncio/events.py
  Lib/asyncio/sslproto.py
  Lib/test/test_asyncio/test_sslproto.py
  Lib/test/test_asyncio/utils.py
  Misc/NEWS.d/next/Library/2018-06-01-10-55-48.bpo-33734.x1W9x0.rst
Labels: CLA signed, awaiting review

#7398 [3.6] bpo-33664: Scroll IDLE editor text by lines (GH-7351)
  Lib/idlelib/editor.py
  Misc/NEWS.d/next/IDLE/2018-06-03-09-13-28.bpo-33664.PZzQyL.rst
Labels: CLA signed, awaiting merge, type-bugfix

#7400 [3.6] bpo-33763: IDLE: Replace label widget with text widget in code context (GH-7367)
  Lib/idlelib/codecontext.py
  Lib/idlelib/idle_test/test_codecontext.py
  Misc/NEWS.d/next/IDLE/2018-06-03-20-12-57.bpo-33763.URiFlE.rst
Labels: CLA signed, awaiting merge

#7399 [3.7] bpo-33763: IDLE: Replace label widget with text widget in code context (GH-7367)
  Lib/idlelib/codecontext.py
  Lib/idlelib/idle_test/test_codecontext.py
  Misc/NEWS.d/next/IDLE/2018-06-03-20-12-57.bpo-33763.URiFlE.rst
Labels: CLA signed, awaiting merge

#7394 [3.6] bpo-31849: Fix warning in pyhash.c (GH-6799)
  Misc/NEWS.d/next/Core and Builtins/2018-05-14-11-00-00.bpo-31849.EmHaH4.rst
  Python/pyhash.c
Labels: CLA signed, awaiting merge

#7387 [3.7] bpo-33640, uuid.UUID doc: document endian of bytes parameter (GH-7263)
  Doc/library/uuid.rst
Labels: CLA signed, awaiting merge, skip news

#7386 [3.6] bpo-33640, uuid.UUID doc: document endian of bytes parameter (GH-7263)
  Doc/library/uuid.rst
Labels: CLA signed, awaiting merge, skip news

#7363 [3.6] bpo-33761: Fix a file leak in test_iterparse in test_xml_etree. (GH-7358)
  Lib/test/test_xml_etree.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7384 [3.7] bpo-33509: Fix test_warnings for python3 -Werror (GH-7365)
  Lib/test/test_warnings/__init__.py
Labels: CLA signed, awaiting merge, skip news

#7391 [2.7] bpo-27902: Add compatibility note to Profile docs (GH-7295)
  Doc/library/profile.rst
Labels: CLA signed, awaiting merge, skip news

#7392 [3.6] bpo-27902: Add compatibility note to Profile docs (GH-7295)
  Doc/library/profile.rst
Labels: CLA signed, awaiting merge, skip news

#7393 [3.7] bpo-31849: Fix warning in pyhash.c (GH-6799)
  Misc/NEWS.d/next/Core and Builtins/2018-05-14-11-00-00.bpo-31849.EmHaH4.rst
  Python/pyhash.c
Labels: CLA signed, awaiting merge

#6663 [3.6] bpo-33394: Enable the verbose build for extension modules with GNU make (GH-6659)
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2018-04-30-17-36-46.bpo-33394._Vdi4t.rst
Labels: awaiting merge

#7401 bpo-33720: Reduces maximum marshal recursion depth on release builds.
  Lib/test/test_marshal.py
  Misc/NEWS.d/next/Windows/2018-06-04-09-20-53.bpo-33720.VKDXHK.rst
  Python/marshal.c
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7

#7405 [3.7] bpo-33720: Reduces maximum marshal recursion depth on release builds. (GH-7401)
  Lib/test/test_marshal.py
  Misc/NEWS.d/next/Windows/2018-06-04-09-20-53.bpo-33720.VKDXHK.rst
  Python/marshal.c
Labels: CLA signed, awaiting merge

#7406 [2.7] bpo-31234: Join threads explicitly in tests
  Lib/test/support/__init__.py
  Lib/test/test_asyncore.py
  Lib/test/test_hashlib.py
  Lib/test/test_httpservers.py
  Lib/test/test_smtplib.py
  Lib/test/test_thread.py
Labels: CLA signed, awaiting merge, skip news

#7093 bpo-33609: Add document for dict order
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting core review, awaiting merge, needs backport to 3.7, skip news, type-documentation

#7407 [3.7] bpo-33609: Document dict insertion order guarantee as of 3.7 (GH-7093)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#7408 [2.7] bpo-18174: Fix file descriptor leaks in tests
  Lib/test/test_posix.py
  Lib/test/test_tempfile.py
Labels: CLA signed, awaiting merge, skip news

#7377 bpo-33753: Refactor creating temporary files in test_fileinput.
  Lib/test/test_fileinput.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#7417 [3.7] bpo-33753: Refactor creating temporary files in test_fileinput. (GH-7377)
  Lib/test/test_fileinput.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7409 [2.7] bpo-18174: regrtest -R 3:3 now also detects FD leak
  Lib/test/regrtest.py
  Lib/test/support/__init__.py
  Lib/test/test_regrtest.py
Labels: CLA signed, awaiting merge, skip news

#7420 [2.7] bpo-18174: Fix fd_count() on FreeBSD
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting merge, skip news

#7395 bpo-5755: Move -Wstrict-prototypes to CFLAGS_NODIST
  Misc/NEWS.d/next/Build/2018-06-04-21-34-34.bpo-5755.65GmCj.rst
  configure
  configure.ac
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#7289 bpo-32392: Document env kwarg of subprocess.run method
  Doc/library/subprocess.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#7423 [3.7] bpo-32392: Document env keyword argument of subprocess.run() (GH-7289)
  Doc/library/subprocess.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#7381 bpo-33767: Fix improper use of SystemError by mmap.mmap objects
  Lib/test/test_mmap.py
  Misc/NEWS.d/next/Library/2018-06-03-22-41-59.bpo-33767.2e82g3.rst
  Modules/mmapmodule.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#7403 bpo-33769: start_tls:Fix error message; cancel callbacks on error
  Lib/asyncio/base_events.py
  Lib/asyncio/sslproto.py
  Misc/NEWS.d/next/Library/2018-06-04-13-46-39.bpo-33769.D_pxYz.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#7376 bpo-33752: Fix a file leak in test_dbm.
  Lib/test/test_dbm.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#7426 [3.7] bpo-33767: Fix improper use of SystemError by mmap.mmap objects (GH-7381)
  Lib/test/test_mmap.py
  Misc/NEWS.d/next/Library/2018-06-03-22-41-59.bpo-33767.2e82g3.rst
  Modules/mmapmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#7427 [3.6] bpo-33767: Fix improper use of SystemError by mmap.mmap objects (GH-7381)
  Lib/test/test_mmap.py
  Misc/NEWS.d/next/Library/2018-06-03-22-41-59.bpo-33767.2e82g3.rst
  Modules/mmapmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#7429 [3.6] bpo-33752: Fix a file leak in test_dbm. (GH-7376)
  Lib/test/test_dbm.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7430 [3.7] bpo-33752: Fix a file leak in test_dbm. (GH-7376)
  Lib/test/test_dbm.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7346 bpo-31215: Add version changed notes for OpenSSL 1.1.0 compatibility
  Doc/library/ssl.rst
Labels: CLA signed, awaiting review, skip news

#7428 [3.7] bpo-33769: start_tls: Fix error message; cancel callbacks on error (GH-7403)
  Lib/asyncio/base_events.py
  Lib/asyncio/sslproto.py
  Misc/NEWS.d/next/Library/2018-06-04-13-46-39.bpo-33769.D_pxYz.rst
Labels: CLA signed, awaiting review

#7424 bpo-33165: Added stacklevel parameter to logging APIs.
  Doc/library/logging.rst
  Lib/logging/__init__.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2018-06-05-12-43-25.bpo-33165.9TIsVf.rst
Labels: CLA signed, awaiting merge

#7412 bpo-33755: Fix importlib.resources isolation tests
  Lib/test/test_importlib/test_resource.py
  Lib/test/test_importlib/util.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#7431 [3.6] bpo-33753: Refactor creating temporary files in test_fileinput. (GH-7377).
  Lib/test/test_fileinput.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7378 bpo-33751: Fix test_file.
  Lib/test/test_file.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#6957 bpo-12486: Document tokenize.generate_tokens() as public API
  Doc/library/tokenize.rst
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Library/2018-05-17-22-14-58.bpo-12486.HBeh62.rst
Labels: CLA signed, awaiting merge

#7435 [3.7] bpo-33751: Fix test_file. (GH-7378)
  Lib/test/test_file.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7436 [3.6] bpo-33751: Fix test_file. (GH-7378)
  Lib/test/test_file.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#7414 Improve the subprocess restore_signals=True test.
  Lib/test/test_subprocess.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-tests

#7434 [3.7] bpo-33755: Fix importlib.resources isolation tests (GH-7412)
  Lib/test/test_importlib/test_resource.py
  Lib/test/test_importlib/util.py
Labels: CLA signed, awaiting review, skip news

#7281 [2.7] bpo-33600: document that platform.linux_distribution() has been removed
  Doc/library/platform.rst
Labels: CLA signed, awaiting merge, skip news

#6819 bpo-33504: Migrate configparser from OrderedDict to dict.
  Doc/library/configparser.rst
  Lib/configparser.py
  Lib/test/test_configparser.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-05-15-12-11-13.bpo-33504.czsHFg.rst
Labels: CLA signed, awaiting review

#7422 [3.7] bpo-5755: Move -Wstrict-prototypes to CFLAGS_NODIST (GH-7395)
  Misc/NEWS.d/next/Build/2018-06-04-21-34-34.bpo-5755.65GmCj.rst
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#7438 [3.6] bpo-5755: Move -Wstrict-prototypes to CFLAGS_NODIST (GH-7395)
  Misc/NEWS.d/next/Build/2018-06-04-21-34-34.bpo-5755.65GmCj.rst
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#7440 remove hg support from patchcheck
  Tools/scripts/patchcheck.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#7444 [2.7] remove hg support from patchcheck (GH-7440).
  Tools/scripts/patchcheck.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#7442 [3.7] remove hg support from patchcheck (GH-7440)
  Tools/scripts/patchcheck.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#7443 [3.6] remove hg support from patchcheck (GH-7440)
  Tools/scripts/patchcheck.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#7446 [2.7] PC/_subprocess.c: Fix signed/unsigned comparison
  PC/_subprocess.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#7449 bpo-31044, test_posix: Reenable makedev() tests on FreeBSD
  Lib/test/test_posix.py
Labels: CLA signed, awaiting merge, skip news

#7448 test.support.SaveSignals: fix typo
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#7447 bpo-33781: audioop: enhance rounding double as int
  Modules/audioop.c
Labels: CLA signed, awaiting merge, skip news

#7450 [3.7] bpo-33781: audioop: enhance rounding double as int (GH-7447)
  Modules/audioop.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#7452 [2.7] bpo-33781: audioop: enhance rounding double as int (GH-7447)
  Modules/audioop.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#7451 [3.6] bpo-33781: audioop: enhance rounding double as int (GH-7447)
  Modules/audioop.c
Labels: CLA signed, awaiting review, skip news, type-bugfix

#7453 [2.7] bpo-19418: audioop.c: Fix warnings on -0x80000000
  Modules/audioop.c
Labels: CLA signed, awaiting merge, skip news

#7419 bpo-28240: timeit: Update repeat() doc
  Doc/library/timeit.rst
  Lib/timeit.py
Labels: CLA signed, awaiting merge, skip news

#7455 [3.7] bpo-33773: Fix test.support.fd_count() on Linux/FreBSD (GH-7421)
  Lib/test/support/__init__.py
  Lib/test/test_support.py
Labels: CLA signed, awaiting merge, skip news

#7454 [3.6] bpo-33773: Fix test.support.fd_count() on Linux/FreBSD (GH-7421)
  Lib/test/support/__init__.py
  Lib/test/test_support.py
Labels: CLA signed, awaiting merge, skip news

#7456 [2.7] bpo-33773: Fix test.support.fd_count() on Linux/FreBSD (GH-7421)
  Lib/test/support/__init__.py
  Lib/test/test_test_support.py
Labels: CLA signed, awaiting merge, skip news

#7457 [3.7] bpo-28240: timeit: Update repeat() doc (GH-7419)
  Doc/library/timeit.rst
  Lib/timeit.py
Labels: CLA signed, awaiting review, skip news

#7459 [2.7] bpo-31731: test_io hangs with --huntrleaks: exclude it
  Lib/test/regrtest.py
Labels: CLA signed, awaiting merge, skip news

#7460 bpo-33789: test_asyncio: Fix ResourceWarning
  Lib/test/test_asyncio/functional.py
  Lib/test/test_asyncio/test_sslproto.py
Labels: CLA signed, awaiting merge, skip news

#7461 bpo-33789, test_asyncio: Hide PendingDeprecationWarning
  Lib/test/test_asyncio/test_tasks.py
Labels: CLA signed, awaiting merge, skip news

#7462 bpo-32676, test_asyncio: Fix warning in test_error_in_call_soon()
  Lib/test/test_asyncio/test_tasks.py
Labels: CLA signed, awaiting merge, skip news

#7439 update to Unicode 11.0.0 (bpo-33778)
  Doc/library/unicodedata.rst
  Doc/reference/lexical_analysis.rst
  Lib/test/test_unicodedata.py
  Misc/NEWS.d/next/Library/2018-06-05-20-22-30.bpo-33778._tSAS6.rst
  Modules/unicodedata.c
  Modules/unicodedata_db.h
  Modules/unicodename_db.h
  Objects/unicodetype_db.h
  Tools/unicode/makeunicodedata.py
Labels: awaiting core review

#7465 bpo-33274: Compliance with DOM L1: return removed attribute
  Lib/test/test_minidom.py
  Lib/xml/dom/minidom.py
  Misc/NEWS.d/next/Library/2018-06-06-22-01-33.bpo-33274.teYqv8.rst
Labels: CLA signed, awaiting merge

#7385 bpo-30436: Add missing space in importlib.util.find_spec() error message
  Lib/importlib/util.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-bugfix

#7470 [3.7] update to Unicode 11.0.0 (closes bpo-33778) (GH-7439)
  Doc/library/unicodedata.rst
  Doc/reference/lexical_analysis.rst
  Lib/test/test_unicodedata.py
  Misc/NEWS.d/next/Library/2018-06-05-20-22-30.bpo-33778._tSAS6.rst
  Modules/unicodedata.c
  Modules/unicodedata_db.h
  Modules/unicodename_db.h
  Objects/unicodetype_db.h
  Tools/unicode/makeunicodedata.py
Labels: CLA signed, awaiting review

#7331 bpo-29235: Update document for Profiler's context manager
  Doc/library/profile.rst
  Doc/whatsnew/3.8.rst
  Misc/NEWS.d/next/Library/2018-05-14-15-01-55.bpo-29235.47Fzwt.rst
Labels: CLA signed, awaiting changes

#7366 bpo-17909: Document that json.load can accept a binary IO
  Doc/library/json.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#7474 [3.7] bpo-17909: Document that json.load can accept a binary IO (GH-7366)
  Doc/library/json.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation
