Repository python/cpython, pull requests merged in 2018-02, with the labels that each got.

#5593 Fix some warnings produced by different compilers.
  Modules/_decimal/libmpdec/mpdecimal.c
  Modules/socketmodule.c
  Modules/timemodule.c
  Python/context.c
  Python/hamt.c
  Python/pyhash.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-bugfix

#5600 [3.7] Fix some warnings produced by different compilers. (GH-5593)
  Modules/_decimal/libmpdec/mpdecimal.c
  Modules/socketmodule.c
  Modules/timemodule.c
  Python/context.c
  Python/hamt.c
  Python/pyhash.c
Labels: CLA signed, awaiting review, skip issue, skip news, type-bugfix

#5601 bpo-30157: Fix csv.Sniffer.sniff() regex pattern.
  Lib/csv.py
  Lib/test/test_csv.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-02-09-14-44-43.bpo-30157.lEiiAK.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#5602 [3.7] bpo-30157: Fix csv.Sniffer.sniff() regex pattern. (GH-5601)
  Lib/csv.py
  Lib/test/test_csv.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-02-09-14-44-43.bpo-30157.lEiiAK.rst
Labels: CLA signed, awaiting review, type-bugfix

#5603 [3.6] bpo-30157: Fix csv.Sniffer.sniff() regex pattern. (GH-5601)
  Lib/csv.py
  Lib/test/test_csv.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-02-09-14-44-43.bpo-30157.lEiiAK.rst
Labels: CLA signed, awaiting merge, type-bugfix

#5604 [2.7] bpo-30157: Fix csv.Sniffer.sniff() regex pattern. (GH-5601)
  Lib/csv.py
  Lib/test/test_csv.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-02-09-14-44-43.bpo-30157.lEiiAK.rst
Labels: CLA signed, awaiting merge, type-bugfix

#5588 bpo-30688: Support \N{name} escapes in re patterns.
  Doc/library/re.rst
  Doc/whatsnew/3.8.rst
  Lib/sre_parse.py
  Lib/test/test_re.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-02-08-18-59-11.bpo-30688.zBh4TH.rst
Labels: CLA signed, awaiting merge, type-enhancement

#5606 bpo-30688: Import unicodedata only when needed
  Lib/sre_parse.py
Labels: CLA not signed, awaiting merge, skip news, type-bugfix

#5599 travis: Use -O3 option
  .travis.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#5607 [3.7] travis: Use -O3 option (GH-5599)
  .travis.yml
Labels: CLA signed, awaiting review, skip issue, skip news

#5609 bpo-32800: Update link to w3c doc for xml default namespaces
  Doc/library/xml.etree.elementtree.rst
  Misc/NEWS.d/next/Documentation/2018-02-10-15-16-04.bpo-32800.FyrqCk.rst
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#5611 [3.7] bpo-32800: Update link to w3c doc for xml default namespaces (GH-5609)
  Doc/library/xml.etree.elementtree.rst
  Misc/NEWS.d/next/Documentation/2018-02-10-15-16-04.bpo-32800.FyrqCk.rst
Labels: CLA signed, awaiting review

#5612 [3.6] bpo-32800: Update link to w3c doc for xml default namespaces (GH-5609)
  Doc/library/xml.etree.elementtree.rst
  Misc/NEWS.d/next/Documentation/2018-02-10-15-16-04.bpo-32800.FyrqCk.rst
Labels: CLA signed, awaiting review

#5613 [2.7] bpo-32800: Update link to w3c doc for xml default namespaces (GH-5609)
  Doc/library/xml.etree.elementtree.rst
  Misc/NEWS.d/next/Documentation/2018-02-10-15-16-04.bpo-32800.FyrqCk.rst
Labels: CLA signed, awaiting review

#5586 bpo-32792: Preserve mapping order in ChainMap()
  Lib/collections/__init__.py
  Lib/test/test_collections.py
  Misc/NEWS.d/next/Library/2018-02-08-00-47-07.bpo-32792.NtyDb4.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#5617 [3.7] bpo-32792: Preserve mapping order in ChainMap() (GH-5586)
  Lib/collections/__init__.py
  Lib/test/test_collections.py
  Misc/NEWS.d/next/Library/2018-02-08-00-47-07.bpo-32792.NtyDb4.rst
Labels: CLA signed, awaiting review

#5610 bpo-11015: Update test.support documentation
  Doc/library/test.rst
  Misc/NEWS.d/next/Documentation/2018-02-10-12-48-38.bpo-11015.-gUf34.rst
Labels: CLA signed, awaiting review

#5618 Code beautification using f-strings
  Lib/collections/__init__.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#5619 [3.7] bpo-11015: Update test.support documentation (GH-5610)
  Doc/library/test.rst
  Misc/NEWS.d/next/Documentation/2018-02-10-12-48-38.bpo-11015.-gUf34.rst
Labels: CLA signed, awaiting review

#5516 bpo-32604: Make _xxsubinterpreters build on Windows
  PC/config.c
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7, skip news

#5624 [3.7] bpo-32604: Make _xxsubinterpreters build on Windows (GH-5516)
  PC/config.c
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, awaiting review, skip news

#5519 Add short-circuit for doc changes to AppVeyor
  .github/appveyor.yml
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#5626 [3.7] Add short-circuit for doc changes to AppVeyor (GH-5519).
  .github/appveyor.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#5628 [3.6] Add short-circuit for doc changes to AppVeyor (GH-5519)
  .github/appveyor.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#5629 [2.7] Add short-circuit for doc changes to AppVeyor (GH-5519)
  .github/appveyor.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#5622 bpo-32815: Document **text** argument in Popen and run
  Doc/library/subprocess.rst
Labels: CLA signed, awaiting review, needs backport to 3.7, skip news, type-documentation

#5632 Adjust AppVeyor doc short-circuit
  .github/appveyor.yml
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#5633 [3.7] Fix AppVeyor doc short-circuit (GH-5632)
  .github/appveyor.yml
Labels: CLA signed, awaiting review, skip issue, skip news

#5635 [2.7] Fix AppVeyor doc short-circuit (GH-5632)
  .github/appveyor.yml
Labels: CLA signed, awaiting review, skip issue, skip news

#5569 [3.7] Fix typo in Include/objimpl.h, the word "has" was missing (GH-5568)
  Include/objimpl.h
Labels: CLA signed, awaiting merge, skip issue, skip news

#5570 [3.6] Fix typo in Include/objimpl.h, the word "has" was missing (GH-5568)
  Include/objimpl.h
Labels: CLA signed, awaiting merge, skip issue, skip news

#5571 [2.7] Fix typo in Include/objimpl.h, the word "has" was missing (GH-5568)
  Include/objimpl.h
Labels: CLA not signed, awaiting merge, skip issue, skip news

#5547 [3.6] bpo-32720: Fixed the replacement field grammar documentation. (GH-5544)
  Doc/library/string.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#5577 bpo-29248: Fix readlink bug os
  Lib/test/test_os.py
  Misc/NEWS.d/next/Windows/2018-02-07-17-50-48.bpo-29248.Xzwj-6.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#5640 [3.6] bpo-29248: Fix os.readlink() on Windows (GH-5577)
  Lib/test/test_os.py
  Misc/NEWS.d/next/Windows/2018-02-07-17-50-48.bpo-29248.Xzwj-6.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting review

#5637 [2.7] bpo-30109: Fix reindent.py for non-ASCII files.
  Lib/email/utils.py
  Misc/NEWS.d/next/Tools-Demos/2018-02-12-14-27-01.bpo-30109.lIYlaf.rst
  Tools/scripts/reindent.py
Labels: CLA signed, awaiting merge, type-bugfix

#5449 bpo-32221: makeipaddr(): remove interface part + speedup (GH-5449)
  Doc/library/socket.rst
  Lib/test/test_socket.py
  Misc/NEWS.d/next/Library/2017-12-06-10-10-10.bpo-32221.ideco_.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting review, needs backport to 3.7

#5641 [3.7] bpo-32221: makeipaddr(): remove interface part + speedup (GH-5449) (GH-5449)
  Doc/library/socket.rst
  Lib/test/test_socket.py
  Misc/NEWS.d/next/Library/2017-12-06-10-10-10.bpo-32221.ideco_.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting review

#5642 [3.7] bpo-32826: Add "encoding=utf-8" to open() in idle_test/test_help_about. (GH-5639)
  Lib/idlelib/idle_test/test_help_about.py
  Misc/NEWS.d/next/IDLE/2018-02-12-11-05-22.bpo-32826.IxNZrk.rst
Labels: CLA signed, awaiting merge

#5643 [3.6] bpo-32826: Add "encoding=utf-8" to open() in idle_test/test_help_about. (GH-5639)
  Lib/idlelib/idle_test/test_help_about.py
  Misc/NEWS.d/next/IDLE/2018-02-12-11-05-22.bpo-32826.IxNZrk.rst
Labels: CLA signed, awaiting merge

#5644 [3.7] bpo-29248: Fix os.readlink() on Windows (GH-5577)
  Lib/test/test_os.py
  Misc/NEWS.d/next/Windows/2018-02-07-17-50-48.bpo-29248.Xzwj-6.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#5646 bpo-32837: IDLE - require encoding argument for textview.view_file.
  Lib/idlelib/idle_test/test_textview.py
  Lib/idlelib/textview.py
  Misc/NEWS.d/next/IDLE/2018-02-12-17-22-48.bpo-32837.-33QPl.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#5647 [3.7] bpo-32837: IDLE - require encoding argument for textview.view_file. (GH-5646)
  Lib/idlelib/idle_test/test_textview.py
  Lib/idlelib/textview.py
  Misc/NEWS.d/next/IDLE/2018-02-12-17-22-48.bpo-32837.-33QPl.rst
Labels: CLA signed, awaiting merge

#5648 [3.6] bpo-32837: IDLE - require encoding argument for textview.view_file. (GH-5646)
  Lib/idlelib/idle_test/test_textview.py
  Lib/idlelib/textview.py
  Misc/NEWS.d/next/IDLE/2018-02-12-17-22-48.bpo-32837.-33QPl.rst
Labels: CLA signed, awaiting merge

#5636 bpo-32827: Fix usage of _PyUnicodeWriter_Prepare() in decoding errors handler.
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-bugfix

#5608 bpo-32370: Use the correct encoding for ipconfig output in the uuid module
  Lib/uuid.py
  Misc/NEWS.d/next/Windows/2018-02-10-15-38-19.bpo-32370.kcKuct.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#5650 [3.7] bpo-32827: Fix usage of _PyUnicodeWriter_Prepare() in decoding errors handler. (GH-5636)
  Objects/unicodeobject.c
Labels: CLA signed, awaiting review, skip news, type-bugfix

#5653 bpo-30579: Docs for dynamic traceback creation
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#5655 [3.7] bpo-30579: Docs for dynamic traceback creation (GH-5653)
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting merge, skip news

#5652 [3.7] bpo-32370: Use the correct encoding for ipconfig output in the uuid module. (GH-5608)
  Lib/uuid.py
  Misc/NEWS.d/next/Windows/2018-02-10-15-38-19.bpo-32370.kcKuct.rst
Labels: CLA signed, awaiting merge, type-bugfix

#5654 [3.6] bpo-32370: Use the correct encoding for ipconfig output in the uuid module. (GH-5608).
  Lib/uuid.py
  Misc/NEWS.d/next/Windows/2018-02-10-15-38-19.bpo-32370.kcKuct.rst
Labels: CLA signed, awaiting merge, type-bugfix

#5656 [3.6] bpo-32827: Fix usage of _PyUnicodeWriter_Prepare() in decoding errors handler. (GH-5636)
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#3995 bpo-31787: Prevent refleaks when calling __init__() more than once
  Lib/test/test_asyncio/test_tasks.py
  Lib/test/test_bz2.py
  Lib/test/test_descr.py
  Lib/test/test_hashlib.py
  Lib/test/test_lzma.py
  Lib/test/test_property.py
  Misc/NEWS.d/next/Library/2018-02-09-21-41-56.bpo-31787.owSZ2t.rst
  Modules/_asynciomodule.c
  Modules/_bz2module.c
  Modules/_hashopenssl.c
  Modules/_lzmamodule.c
  Objects/descrobject.c
  Objects/funcobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#660 bpo-29803: remove some redandunt ops in unicodeobject.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#5657 [3.7] bpo-31787: Prevent refleaks when calling __init__() more than once (GH-3995)
  Lib/test/test_asyncio/test_tasks.py
  Lib/test/test_bz2.py
  Lib/test/test_descr.py
  Lib/test/test_hashlib.py
  Lib/test/test_lzma.py
  Lib/test/test_property.py
  Misc/NEWS.d/next/Library/2018-02-09-21-41-56.bpo-31787.owSZ2t.rst
  Modules/_asynciomodule.c
  Modules/_bz2module.c
  Modules/_hashopenssl.c
  Modules/_lzmamodule.c
  Objects/descrobject.c
  Objects/funcobject.c
Labels: CLA signed, awaiting merge

#5659 [3.6] bpo-31787: Prevent refleaks when calling __init__() more than once (GH-3995)
  Lib/test/test_asyncio/test_tasks.py
  Lib/test/test_bz2.py
  Lib/test/test_descr.py
  Lib/test/test_hashlib.py
  Lib/test/test_lzma.py
  Lib/test/test_property.py
  Misc/NEWS.d/next/Library/2018-02-09-21-41-56.bpo-31787.owSZ2t.rst
  Modules/_asynciomodule.c
  Modules/_bz2module.c
  Modules/_hashopenssl.c
  Modules/_lzmamodule.c
  Objects/descrobject.c
  Objects/funcobject.c
Labels: CLA signed, awaiting merge

#5660 bpo-31787: Skip refleak check when _hashlib is not available
  Lib/test/test_hashlib.py
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#5661 [3.7] bpo-31787: Skip refleak check when _hashlib is not available (GH-5660)
  Lib/test/test_hashlib.py
Labels: CLA signed, awaiting merge, skip news

#5662 [3.6] bpo-31787: Skip refleak check when _hashlib is not available (GH-5660)
  Lib/test/test_hashlib.py
Labels: CLA signed, awaiting merge, skip news

#5666 bpo-27846: Fix an incorrect note in the base64 documentation
  Doc/library/base64.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#5668 [3.7] bpo-27846: Delete incorrect note in base64 docs (GH-5666)
  Doc/library/base64.rst
Labels: CLA signed, awaiting review, skip news

#5669 [3.6] bpo-27846: Delete incorrect note in base64 docs (GH-5666)
  Doc/library/base64.rst
Labels: CLA signed, awaiting review, skip news

#5558 remove mercurial dot files
  .hgeol
  .hgignore
  .hgtags
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#5605 Fix installation instructions for *nix
  Doc/using/unix.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#5672 [3.7] remove mercurial dot files (GH-5558)
  .hgeol
  .hgignore
  .hgtags
Labels: CLA signed, awaiting merge, skip issue, skip news

#5673 [2.7] remove mercurial dot files (GH-5558).
  .hgeol
  .hgignore
  .hgtags
Labels: CLA signed, awaiting merge, skip issue, skip news

#5676 [3.7] Fix installation instructions for *nix (GH-5605)
  Doc/using/unix.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#5677 [2.7] Fix installation instructions for *nix (GH-5605)
  Doc/using/unix.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#5678 [3.6] Fix installation instructions for *nix (GH-5605)
  Doc/using/unix.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#5674 [3.6] remove mercurial dot files (GH-5558).
  .hgeol
  .hgtags
Labels: CLA signed, awaiting merge, skip issue, skip news

#5665 bpo-32841: Asyncio.Condition prevents cancellation
  Lib/asyncio/locks.py
  Lib/test/test_asyncio/test_locks.py
  Misc/NEWS.d/next/Library/2018-02-14-00-21-24.bpo-32841.bvHDOc.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#5682 [3.7] bpo-32841: Fix cancellation in awaiting asyncio.Condition (GH-5665)
  Lib/asyncio/locks.py
  Lib/test/test_asyncio/test_locks.py
  Misc/NEWS.d/next/Library/2018-02-14-00-21-24.bpo-32841.bvHDOc.rst
Labels: CLA signed, awaiting merge

#5683 [3.6] bpo-32841: Fix cancellation in awaiting asyncio.Condition (GH-5665)
  Lib/asyncio/locks.py
  Lib/test/test_asyncio/test_locks.py
  Misc/NEWS.d/next/Library/2018-02-14-00-21-24.bpo-32841.bvHDOc.rst
Labels: CLA signed, awaiting review

#5681 Fix typo in comment at the end of conditional block
  Modules/posixmodule.c
Labels: CLA not signed, awaiting merge, skip issue, skip news

#5687 [2.7] Update comment in posixmodule.c (GH-5681)
  Modules/posixmodule.c
Labels: CLA not signed, awaiting merge, skip issue, skip news

#5688 [3.7] Update comment in posixmodule.c (GH-5681)
  Modules/posixmodule.c
Labels: CLA not signed, awaiting merge, skip issue, skip news

#5686 [3.6] Update comment in posixmodule.c (GH-5681)
  Modules/posixmodule.c
Labels: CLA not signed, awaiting merge, skip issue, skip news

#5694 Update and sync importlib.resources documentation
  Doc/library/importlib.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#5697 [3.7] Update and sync importlib.resources documentation (GH-5694)
  Doc/library/importlib.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#5696 [3.7] [master] Fix typo in Python3.7 doc
  Doc/whatsnew/3.7.rst
Labels: awaiting merge, needs backport to 3.7, skip issue, skip news

#5685 bpo-32436: Add docs for contextvars
  Doc/library/contextvars.rst
  Doc/library/index.rst
  Doc/whatsnew/3.7.rst
  Misc/NEWS.d/next/Documentation/2018-02-14-11-10-41.bpo-32436.TTJ2jb.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#5699 [3.7] bpo-32436: Add docs for contextvars (GH-5685)
  Doc/library/contextvars.rst
  Doc/library/index.rst
  Doc/whatsnew/3.7.rst
  Misc/NEWS.d/next/Documentation/2018-02-14-11-10-41.bpo-32436.TTJ2jb.rst
Labels: CLA signed, awaiting merge

#5698 [3.7] Correct the code example in Python 3.7's What's New (GH-5696)
  Doc/whatsnew/3.7.rst
Labels: CLA not signed, awaiting merge, skip issue, skip news

#5709 bpo-32604: Clean up created subinterpreters before runtime finalization.
  Include/internal/pystate.h
  Include/pystate.h
  Lib/test/test__xxsubinterpreters.py
  Modules/_xxsubinterpretersmodule.c
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news

#5710 [3.7] bpo-32604: Clean up created subinterpreters before runtime finalization. (gh-5709)
  Include/internal/pystate.h
  Include/pystate.h
  Lib/test/test__xxsubinterpreters.py
  Modules/_xxsubinterpretersmodule.c
  Python/pystate.c
Labels: CLA signed, awaiting review, skip news

#5712 bpo-32860: Fix a missing asterisk in the documentation for glob.iglob()
  Doc/library/glob.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#5706 DOC: fix documentation for copyright and credits
  Doc/library/constants.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#5714 [3.7] bpo-32860: Fix a missing asterisk in the documentation for glob.iglob() (GH-5712)
  Doc/library/glob.rst
Labels: CLA signed, awaiting merge, skip news

#5715 [3.6] bpo-32860: Fix a missing asterisk in the documentation for glob.iglob() (GH-5712)
  Doc/library/glob.rst
Labels: CLA signed, awaiting merge, skip news

#5716 [3.7] DOC: fix documentation for copyright and credits (GH-5706)
  Doc/library/constants.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#5717 [2.7] DOC: fix documentation for copyright and credits (GH-5706)
  Doc/library/constants.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#5718 [3.6] DOC: fix documentation for copyright and credits (GH-5706)
  Doc/library/constants.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#5692 bpo-32852: Fix trace changing sys.argv to tuple
  Lib/test/test_trace.py
  Lib/trace.py
  Misc/NEWS.d/next/Library/2018-02-15-12-04-29.bpo-32852.HDqIxM.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#5719 [3.7] bpo-32852: Fix trace changing sys.argv to tuple. (GH-5692)
  Lib/test/test_trace.py
  Lib/trace.py
  Misc/NEWS.d/next/Library/2018-02-15-12-04-29.bpo-32852.HDqIxM.rst
Labels: CLA signed, awaiting merge, type-bugfix

#5720 [3.6] bpo-32852: Fix trace changing sys.argv to tuple. (GH-5692)
  Lib/test/test_trace.py
  Lib/trace.py
  Misc/NEWS.d/next/Library/2018-02-15-12-04-29.bpo-32852.HDqIxM.rst
Labels: CLA signed, awaiting merge, type-bugfix

#5721 Fix a typo in asyncio docs
  Doc/library/asyncio-eventloop.rst
Labels: CLA signed, awaiting merge, expert-asyncio, needs backport to 3.7, skip issue, skip news

#5722 [3.7] Fix a typo in asyncio docs (GH-5721)
  Doc/library/asyncio-eventloop.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#5671 bpo-30638: Add clinic to `make regen-all`
  .travis.yml
  Makefile.pre.in
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news

#5724 [3.7] bpo-30638: Add clinic to `make regen-all` (GH-5671)
  .travis.yml
  Makefile.pre.in
Labels: CLA signed, awaiting merge, skip news

#5725 [3.6] bpo-30638: Add clinic to `make regen-all` (GH-5671)
  .travis.yml
  Makefile.pre.in
Labels: CLA signed, awaiting merge, skip news

#5728 Improves the ability to build in CI
  Lib/test/support/script_helper.py
  Lib/test/test_cmd_line.py
  PCbuild/find_python.bat
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#5729 [3.7] Improves the ability to build in CI (GH-5728)
  Lib/test/support/script_helper.py
  Lib/test/test_cmd_line.py
  PCbuild/find_python.bat
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, awaiting merge, skip issue, skip news

#5731 Adds missing backslashes to get_externals.bat
  PCbuild/get_externals.bat
Labels: CLA signed, awaiting merge, skip issue, skip news

#5730 [3.6] Improves the ability to build in CI (GH-5728)
  Lib/test/support/script_helper.py
  Lib/test/test_cmd_line.py
  PCbuild/find_python.bat
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, awaiting merge, skip issue, skip news

#5273 bpo-31333: Re-implement ABCMeta in C
  Doc/whatsnew/3.7.rst
  Lib/_py_abc.py
  Lib/abc.py
  Lib/test/libregrtest/refleak.py
  Lib/test/test_abc.py
  Lib/test/test_typing.py
  Misc/NEWS.d/next/Library/2018-02-15-08-18-52.bpo-31333.4fF-gM.rst
  Modules/Setup.dist
  Modules/_abc.c
  Modules/clinic/_abc.c.h
  PC/config.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  setup.py
Labels: CLA signed, awaiting merge

#5727 Clean up Travis config
  .travis.yml
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#5737 [3.7] Clean up Travis config (GH-5727)
  .travis.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#5736 [3.6] Correct venv doc bpo-32540
  Doc/using/venv-create.inc
Labels: CLA signed, awaiting merge, skip news

#5733 [3.7] bpo-31333: Re-implement ABCMeta in C (GH-5273)
  Doc/whatsnew/3.7.rst
  Lib/_py_abc.py
  Lib/abc.py
  Lib/test/libregrtest/refleak.py
  Lib/test/test_abc.py
  Lib/test/test_typing.py
  Misc/NEWS.d/next/Library/2018-02-15-08-18-52.bpo-31333.4fF-gM.rst
  Modules/Setup.dist
  Modules/_abc.c
  Modules/clinic/_abc.c.h
  PC/config.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  setup.py
Labels: CLA signed, awaiting merge

#5734 [3.7] bpo-25988: Emit a warning when use or import ABCs from 'collections'. (GH-5460)
  Lib/collections/__init__.py
  Modules/_decimal/_decimal.c
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#5739 bpo-32869: Fix incorrect dst buffer size for MultiByteToWideChar
  Python/fileutils.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-bugfix

#5743 bpo-25988: add NEWS entry for 3.7.0b2
  Misc/NEWS.d/next/Library/2018-02-18-13-04-59.bpo-25988.ACidKC.rst
Labels: CLA signed, awaiting merge

#5741 [3.7] bpo-32869: Fix incorrect dst buffer size for MultiByteToWideChar (GH-5739)
  Python/fileutils.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#5742 [3.6] bpo-32869: Fix incorrect dst buffer size for MultiByteToWideChar (GH-5739)
  Python/fileutils.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#5738 [3.6] Clean up Travis config (GH-5727)
  .travis.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#5740 [2.7] Clean up Travis config (GH-5727)
  .travis.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#5744 bpo-31333: Fix typo in whatsnew/3.7.rst
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#5745 [3.7] bpo-31333: Fix typo in whatsnew/3.7.rst (GH-5744)
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting merge, skip news

#5726 bpo-21060: improve error message for "setup.py upload" without dist files
  Lib/distutils/command/upload.py
  Misc/NEWS.d/next/Library/2018-02-17-19-20-19.bpo-21060.S1Z-x6.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#5310 bpo-31972: Improve docstrings for pathlib classes
  Lib/pathlib.py
  Misc/NEWS.d/next/Documentation/2018-01-25-14-23-12.bpo-31972.w1m_8r.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6

#5749 [3.6] bpo-31972: Improve docstrings for pathlib classes (GH-5310)
  Lib/pathlib.py
  Misc/NEWS.d/next/Documentation/2018-01-25-14-23-12.bpo-31972.w1m_8r.rst
Labels: CLA signed, awaiting merge

#5750 [3.7] bpo-31972: Improve docstrings for pathlib classes (GH-5310)
  Lib/pathlib.py
  Misc/NEWS.d/next/Documentation/2018-01-25-14-23-12.bpo-31972.w1m_8r.rst
Labels: CLA signed, awaiting merge

#5347 bpo-32682: test_zlib improve version parsing
  Lib/test/test_zlib.py
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-tests

#5748 [2.7] bpo-21060 Improve error message for "setup.py upload" without dist files (GH-5726).
  Lib/distutils/command/upload.py
  Misc/NEWS.d/next/Library/2018-02-17-19-20-19.bpo-21060.S1Z-x6.rst
Labels: CLA signed, awaiting merge

#5746 [3.7] bpo-20160: Improve error message for "setup.py upload" without dist files (GH-5726)
  Lib/distutils/command/upload.py
  Misc/NEWS.d/next/Library/2018-02-17-19-20-19.bpo-21060.S1Z-x6.rst
Labels: CLA signed, awaiting changes

#5751 [3.7] bpo-32682: Improve libz version parsing in test_zilb (GH-5347)
  Lib/test/test_zlib.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#5747 [3.6] bpo-21060 Improve error message for "setup.py upload" without dist files (GH-5726)
  Lib/distutils/command/upload.py
  Misc/NEWS.d/next/Library/2018-02-17-19-20-19.bpo-21060.S1Z-x6.rst
Labels: CLA signed, awaiting merge

#5752 [3.6] bpo-32682: Improve libz version parsing in test_zilb (GH-5347)
  Lib/test/test_zlib.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#5758 bpo-30121: Fix test_subprocess for Windows Debug builds
  Lib/test/test_subprocess.py
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7, skip news

#5760 [3.6] bpo-30121: Fix test_subprocess for Windows Debug builds (GH-5758)
  Lib/test/test_subprocess.py
Labels: CLA signed, awaiting merge, skip news

#5759 [3.7] bpo-30121: Fix test_subprocess for Windows Debug builds (GH-5758)
  Lib/test/test_subprocess.py
Labels: CLA signed, awaiting merge, skip news

#5763 bpo-32870: Fix typo in docs
  Doc/library/collections.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#5757 bpo-32409: Ensures activate.bat can handle Unicode contents
  Lib/test/test_venv.py
  Lib/venv/scripts/nt/activate.bat
  Misc/NEWS.d/next/Windows/2018-02-19-10-00-57.bpo-32409.nocuDg.rst
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-bugfix

#5765 [3.7] bpo-32409: Ensures activate.bat can handle Unicode contents (GH-5757)
  Lib/test/test_venv.py
  Lib/venv/scripts/nt/activate.bat
  Misc/NEWS.d/next/Windows/2018-02-19-10-00-57.bpo-32409.nocuDg.rst
Labels: CLA signed, awaiting review, type-bugfix

#5766 [3.6] bpo-32409: Ensures activate.bat can handle Unicode contents (GH-5757)
  Lib/test/test_venv.py
  Lib/venv/scripts/nt/activate.bat
  Misc/NEWS.d/next/Windows/2018-02-19-10-00-57.bpo-32409.nocuDg.rst
Labels: CLA signed, awaiting review, type-bugfix

#5708 bpo-32859: Don't retry dup3() if it is not available at runtime
  Misc/NEWS.d/next/Library/2018-02-19-17-46-31.bpo-32859.kAT-Xp.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7

#5768 [3.7] closes bpo-32859: Don't retry dup3() if it is not available at runtime (GH-5708)
  Misc/NEWS.d/next/Library/2018-02-19-17-46-31.bpo-32859.kAT-Xp.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting review

#5767 bpo-32500: Correct the documentation for PySequence_Size() and PySequence_Length()
  Doc/c-api/sequence.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#5240 bpo-31848: Fix broken error handling in Aifc_read.initfp() when the SSND chunk is not found
  Lib/aifc.py
  Lib/test/test_aifc.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-01-18-23-34-17.bpo-31848.M2cldy.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix

#5780 [3.7] bpo-31848: Fix broken error handling in Aifc_read.initfp() when the SSND chunk is not found (GH-5240)
  Lib/aifc.py
  Lib/test/test_aifc.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-01-18-23-34-17.bpo-31848.M2cldy.rst
Labels: CLA signed, awaiting merge, type-bugfix

#5782 [3.6] bpo-31848: Fix broken error handling in Aifc_read.initfp() when the SSND chunk is not found (GH-5240)
  Lib/aifc.py
  Lib/test/test_aifc.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-01-18-23-34-17.bpo-31848.M2cldy.rst
Labels: CLA signed, awaiting merge, type-bugfix

#5778 bpo-32604: Swap threads only if the interpreter is different.
  Lib/test/test__xxsubinterpreters.py
  Modules/_xxsubinterpretersmodule.c
  Python/pystate.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#5783 [3.7] bpo-32604: Swap threads only if the interpreter is different. (gh-5778)
  Lib/test/test__xxsubinterpreters.py
  Modules/_xxsubinterpretersmodule.c
  Python/pystate.c
Labels: CLA signed, awaiting review, skip news

#5785 [3.7] bpo-32540: Correct venv doc (GH-5736)
  Doc/using/venv-create.inc
Labels: CLA signed, skip news

#5786 [3.6] bpo-32540: Correct venv doc (GH-5736)
  Doc/using/venv-create.inc
Labels: CLA signed, skip news

#176 bpo-28886: doc: Move deprecated abc decorators to separate section
  Doc/library/abc.rst
Labels: CLA signed, awaiting changes, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#5769 [3.6] closes bpo-32859: Don't retry dup3() if it is not available at runtime (GH-5708)
  Misc/NEWS.d/next/Library/2018-02-19-17-46-31.bpo-32859.kAT-Xp.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting review

#5787 [3.7] bpo-28886: doc: Move deprecated abc decorators to separate section (GH-176)
  Doc/library/abc.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#5788 [3.6] bpo-28886: doc: Move deprecated abc decorators to separate section (GH-176)
  Doc/library/abc.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#5789 bpo-32008: don't use PROTOCOL_TLSv1 in example
  Doc/library/ssl.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip news
