Repository python/cpython, pull requests merged in 2019-02, with the labels that each got.

#11717 Speed-up common cases for deque.__init__()
  Modules/_collectionsmodule.c
Labels: CLA signed, skip issue, skip news, type-performance

#11608 bpo-35537: Add setsid parameter to os.posix_spawn() and os.posix_spawnp().
  Doc/library/os.rst
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Library/2019-01-18-13-44-13.bpo-35537.R1lbTl.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting changes

#11718 bpo-35537: Skip test_start_new_session() of posix_spawn
  Lib/test/test_posix.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#11719 [WIP] bpo-35537: Fix function name in os.posix_spawnp() errors
  Modules/posixmodule.c
Labels: CLA signed, DO-NOT-MERGE, awaiting core review, skip news

#11722 bpo-35861: test_named_expressions raises SyntaxWarning
  Lib/test/test_named_expressions.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#11720 bpo-35864: fix namedtuple._asdict() docstring
  Lib/collections/__init__.py
Labels: CLA not signed, awaiting merge, needs backport to 3.7, skip news, type-bugfix, type-documentation

#11724 bpo-35877: Make parenthesis optional for named expression in while statement
  Grammar/Grammar
  Lib/test/test_parser.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-01-22-38-11.bpo-35877.Jrse8f.rst
  Python/graminit.c
Labels: CLA signed, awaiting merge

#11664 bpo-35813: Added shared_memory submodule of multiprocessing.
  Lib/multiprocessing/shared_memory.py
  Misc/NEWS.d/next/Library/2019-01-23-22-44-37.bpo-35813.Yobj-Y.rst
  Modules/_multiprocessing/posixshmem.c
  setup.py
Labels: CLA signed, awaiting merge

#11734 [2.7] bpo-25592: Improve documentation of distutils data_files (GH-9767)
  Doc/distutils/setupscript.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#4808 bpo-26256: Document algorithm speed for the Decimal module.
  Doc/library/decimal.rst
Labels: CLA signed, awaiting merge, skip news

#11736 [3.7] bpo-26256: Document algorithm speed for the Decimal module. (GH-4808)
  Doc/library/decimal.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#11737 [3.7] bpo-33316: PyThread_release_lock always fails (GH-6541)
  Misc/NEWS.d/next/Windows/2018-04-20-03-24-07.bpo-33316.9IiJ8J.rst
  Python/thread_nt.h
Labels: CLA signed, awaiting merge, type-bugfix

#7789 bpo-33895: Relase GIL while calling functions that acquire Windows loader lock
  Misc/NEWS.d/next/Windows/2018-06-19-11-57-50.bpo-33895.zpblTy.rst
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/callproc.c
  Modules/overlapped.c
  Modules/posixmodule.c
  PC/winreg.c
  Python/dynload_win.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge

#11738 [3.7] bpo-1104: msilib.SummaryInfo.GetProperty() truncates the string by one character (GH-4517)
  Lib/test/test_msilib.py
  Misc/NEWS.d/next/Windows/2017-11-24-12-53-54.bpo-1104.1CWSZp.rst
  PC/_msi.c
Labels: CLA signed, awaiting merge

#11730 bpo-35845: Add order={'C', 'F', 'A'} parameter to memoryview.tobytes().
  Doc/library/stdtypes.rst
  Lib/test/test_buffer.py
  Misc/NEWS.d/next/Library/2019-02-02-00-04-01.bpo-35845.1jx2wk.rst
  Objects/memoryobject.c
Labels: CLA signed, awaiting merge

#9000 bpo-32560: inherit the py launcher's STARTUPINFO
  Misc/NEWS.d/next/Windows/2019-02-02-11-02-44.bpo-32560.I5WAGW.rst
  PC/launcher.c
Labels: :robot: automerge, CLA signed, OS-windows, awaiting merge, needs backport to 3.7

#11739 [3.7] bpo-32560: inherit the py launcher's STARTUPINFO (GH-9000)
  Misc/NEWS.d/next/Windows/2019-02-02-11-02-44.bpo-32560.I5WAGW.rst
  PC/launcher.c
Labels: CLA signed, awaiting merge

#740 bpo-29734: nt._getfinalpathname handle leak
  Lib/test/test_os.py
  Misc/NEWS.d/next/Windows/2019-01-12-16-52-38.bpo-29734.6_OJwI.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting review, needs backport to 3.7

#11741 bpo-34691: Compile _contextvars module into main Python library
  Misc/NEWS.d/next/Build/2019-02-02-13-34-05.bpo-34691.B-Lsj4.rst
  PC/config.c
  PCbuild/_contextvars.vcxproj
  PCbuild/_contextvars.vcxproj.filters
  PCbuild/pcbuild.proj
  Tools/msi/lib/lib_files.wxs
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7

#11743 [3.7] bpo-34691: Compile _contextvars module into main Python library (GH-11741)
  Misc/NEWS.d/next/Build/2019-02-02-13-34-05.bpo-34691.B-Lsj4.rst
  PC/config.c
  PCbuild/_contextvars.vcxproj
  PCbuild/_contextvars.vcxproj.filters
  PCbuild/pcbuild.proj
  Tools/msi/lib/lib_files.wxs
Labels: CLA signed, awaiting merge

#11747 [3.7] bpo-35642: Remove asynciomodule.c from pythoncore.vcxproj (GH-11410)
  Misc/NEWS.d/next/Build/2019-01-02-11-23-33.bpo-35642.pjkhJe.rst
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: CLA signed, awaiting merge

#11748 Update macOS installer Welcome and ReadMe for 3.8
  Mac/BuildScript/resources/ReadMe.rtf
  Mac/BuildScript/resources/Welcome.rtf
Labels: CLA signed, awaiting merge, skip issue, skip news

#11725 bpo-35884: Add variable access benchmarking script
  Doc/whatsnew/3.8.rst
  Misc/NEWS.d/next/Tools-Demos/2019-02-01-12-22-37.bpo-35884.hJkMRD.rst
  Tools/scripts/var_access_benchmark.py
Labels: CLA signed, awaiting core review, type-performance

#11746 bpo-35692: pathlib no longer raises when checking file and directory existence
  Lib/pathlib.py
  Misc/NEWS.d/next/Windows/2019-02-02-16-23-57.bpo-35692.cIiiE9.rst
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7, type-bugfix

#11745 bpo-35872 and bpo-35873: Clears __PYVENV_LAUNCHER__ variable
  Lib/multiprocessing/popen_spawn_win32.py
  Lib/multiprocessing/spawn.py
  Lib/site.py
  Lib/test/test_venv.py
  Lib/venv/__init__.py
  Misc/NEWS.d/next/Windows/2019-02-02-15-56-50.bpo-35873.UW-qS9.rst
  Misc/NEWS.d/next/Windows/2019-02-02-15-57-19.bpo-35872.Bba2n7.rst
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7

#11753 [3.7] bpo-35872 and bpo-35873: Clears __PYVENV_LAUNCHER__ variable (GH-11745)
  Lib/multiprocessing/popen_spawn_win32.py
  Lib/multiprocessing/spawn.py
  Lib/site.py
  Lib/test/test_venv.py
  Lib/venv/__init__.py
  Misc/NEWS.d/next/Windows/2019-02-02-15-56-50.bpo-35873.UW-qS9.rst
  Misc/NEWS.d/next/Windows/2019-02-02-15-57-19.bpo-35872.Bba2n7.rst
Labels: CLA signed, awaiting merge

#10902 bpo-32417: Make timedelta arithmetic respect subclasses
  Lib/datetime.py
  Lib/test/datetimetester.py
  Misc/NEWS.d/next/Library/2018-12-04-13-35-36.bpo-32417._Y9SKM.rst
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting merge

#11732 bpo-35321: Set the spec origin to frozen in frozen modules
  Lib/importlib/_bootstrap.py
  Lib/test/test_imp.py
  Misc/NEWS.d/next/Library/2019-02-02-01-53-36.bpo-35321.1Y4DU4.rst
  Python/importlib.h
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#11744 bpo-35299: Fixes sysconfig and distutils during PGO profiling
  Lib/distutils/command/build_ext.py
  Lib/distutils/sysconfig.py
  Lib/distutils/tests/test_build_ext.py
  Lib/sysconfig.py
  Misc/NEWS.d/next/Windows/2019-02-02-14-47-12.bpo-35299.1rgEzd.rst
  Tools/msi/dev/dev.wixproj
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7

#11758 [3.7] bpo-35299: Fixed sysconfig and distutils during PGO profiling (GH-11744)
  Lib/distutils/command/build_ext.py
  Lib/distutils/sysconfig.py
  Lib/distutils/tests/test_build_ext.py
  Lib/sysconfig.py
  Misc/NEWS.d/next/Windows/2019-02-02-14-47-12.bpo-35299.1rgEzd.rst
  Tools/msi/dev/dev.wixproj
Labels: CLA signed, awaiting merge

#11759 Fix typo (micro->nano)
  Tools/scripts/var_access_benchmark.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#11710 asyncio: Use dict instead of OrderedDict
  Lib/asyncio/base_events.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#11709 email: Use dict instead of OrderedDict
  Lib/email/_header_value_parser.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#11304 bpo-20001: Update pathlib landing image
  Doc/library/pathlib-inheritance.png
  Doc/library/pathlib-inheritance.svg
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news, type-documentation

#11761 [3.7] bpo-20001: update pathlib landing image (GH-11304)
  Doc/library/pathlib-inheritance.png
  Doc/library/pathlib-inheritance.svg
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11775 Fix url to core-mentorship mailing list
  Doc/bugs.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, skip issue, skip news, type-documentation

#11776 [3.7] Fix url to core-mentorship mailing list (GH-11775)
  Doc/bugs.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#11778 [2.7] Fix url to core-mentorship mailing list (GH-11775).
  Doc/bugs.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#11359 bpo-35606: Implement math.prod
  Doc/library/math.rst
  Doc/whatsnew/3.8.rst
  Lib/test/test_math.py
  Misc/NEWS.d/next/Library/2018-12-29-21-59-03.bpo-35606.NjGjou.rst
  Modules/clinic/mathmodule.c.h
  Modules/mathmodule.c
Labels: CLA signed, awaiting merge

#11772 bpo-35917: Test multiprocessing manager classes and shareable types
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2019-02-06-18-06-16.bpo-35917.-Clv1L.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-tests

#11780 [3.7] bpo-35917: Test multiprocessing manager classes and shareable types (GH-11772)
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2019-02-06-18-06-16.bpo-35917.-Clv1L.rst
Labels: CLA signed, awaiting merge, type-tests

#11767 bpo-24209: In http.server script, rely on getaddrinfo to bind to preferred address based on the bind parameter.
  Lib/http/server.py
  Lib/test/test_httpservers.py
  Misc/NEWS.d/next/Library/2019-02-06-01-40-55.bpo-24209.awtwPD.rst
Labels: CLA signed, awaiting merge

#11771 bpo-35911: add cell constructor
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Lib/test/test_funcattrs.py
  Lib/types.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-06-17-50-59.bpo-35911.oiWE8.rst
  Objects/cellobject.c
Labels: CLA signed, awaiting merge, type-enhancement

#11384 bpo-35615: Fix crashes when copying a Weak{Key,Value}Dictionary.
  Lib/test/test_weakref.py
  Lib/weakref.py
  Misc/NEWS.d/next/Library/2018-12-30-20-00-05.bpo-35615.Uz1SVh.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-bugfix

#11785 [3.7] bpo-35615: Fix crashes when copying a Weak{Key,Value}Dictionary. (GH-11384)
  Lib/test/test_weakref.py
  Lib/weakref.py
  Misc/NEWS.d/next/Library/2018-12-30-20-00-05.bpo-35615.Uz1SVh.rst
Labels: CLA signed, awaiting review, type-bugfix

#11790 bpo-32417: Add What's New entry for date subclass behavior
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#11794 Complete and neaten-up namedtuple's replacement of builtin function lookups with derefs
  Lib/collections/__init__.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#11765 bpo-35903: Use autoconfig to probe for shm_open() and shm_unlink().
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed, awaiting merge, skip news

#10161 Rework tuple hash tests.
  Lib/test/support/__init__.py
  Lib/test/test_tuple.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#11795 lru_cache: Add more comments. Fix comment typos. Clarify a comment.
  Modules/_functoolsmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#11798 [3.7] lru_cache: Add more comments. Fix comment typos. Clarify a comment. (GH-11795)
  Modules/_functoolsmodule.c
Labels: :robot: automerge, CLA signed, awaiting review, skip issue, skip news, type-documentation

#11799 bpo-35833: Revise IDLE doc for control codes sent to Shell.
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2019-02-08-22-14-24.bpo-35833.XKFRvF.rst
Labels: awaiting merge, needs backport to 3.7, type-documentation

#11800 [3.7] bpo-35833: Revise IDLE doc for control codes sent to Shell. (GH-11799)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2019-02-08-22-14-24.bpo-35833.XKFRvF.rst
Labels: CLA signed, awaiting merge, type-documentation

#11801 bpo-35940: Do not retain references to processes and managers in TestSyncManagerTypes to avoid dangling processes
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#11802 [3.7] Do not retain references to processes and managers in TestSyncManagerTypes (GH-11801)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#11653 Make sure the BaseManager in test_multiprocessing is cleaned up correctly
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#11803 [3.7] Make sure the BaseManager in test_multiprocessing is cleaned up correctly (GH-11653)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#11805 Fix broken :ref: in asyncio docs
  Doc/library/asyncio-protocol.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#11735 bpo-35878: Fix compiler warnings about end_col_offset and end_lineno
  Python/ast.c
Labels: CLA signed, awaiting core review, skip news

#11808 bpo-35959: Fix division by 0 when checking for overflow
  Lib/test/test_math.py
  Modules/mathmodule.c
Labels: CLA signed, awaiting core review, skip news

#11806 Fix compiler warning about non initialized variable
  Python/ast.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#11810 Doc sidebar: 3.6 has moved to security-fix mode.
  Doc/tools/templates/indexsidebar.html
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news

#11813 [2.7] Doc sidebar: 3.6 has moved to security-fix mode. (GH-11810)
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, skip issue, skip news

#11811 [3.7] Doc sidebar: 3.6 has moved to security-fix mode. (GH-11810)
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, skip issue, skip news

#11812 [3.6] Doc sidebar: 3.6 has moved to security-fix mode. (GH-11810)
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, skip issue, skip news

#8519 bpo-22062: Updated docstring and documentation for pathlib
  Doc/library/pathlib.rst
  Lib/pathlib.py
  Misc/NEWS.d/next/Documentation/2018-07-28-12-41-01.bpo-22062.TaN2hn.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7

#11817 [3.7] bpo-22062: Updated docstring and documentation for pathlib (GH-8519)
  Doc/library/pathlib.rst
  Lib/pathlib.py
  Misc/NEWS.d/next/Documentation/2018-07-28-12-41-01.bpo-22062.TaN2hn.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#11766 bpo-35766 follow-up: Add an error check to new_type_comment()
  Python/ast.c
Labels: CLA signed, awaiting merge, skip news

#11627 bpo-35378: Fix multiprocessing.Pool references
  Lib/multiprocessing/pool.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2019-01-21-02-15-20.bpo-35378.4oF03i.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-tests

#11821 bpo-35963: Complete switch cases in symtable.c
  Python/symtable.c
Labels: CLA signed, awaiting merge, skip news

#11819 bpo-35918: Remove broken has_key method and add test
  Lib/multiprocessing/managers.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2019-02-11-16-23-10.bpo-35918.oGDlpT.rst
Labels: CLA signed, awaiting merge

#11824 [3.7] bpo-35918: Remove broken has_key method and add test (GH-11819)
  Lib/multiprocessing/managers.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2019-02-11-16-23-10.bpo-35918.oGDlpT.rst
Labels: CLA signed, awaiting core review

#11815 bpo-35960: Fix dataclasses.field throwing away empty metadata.
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2019-02-10-20-57-12.bpo-35960.bh-6Ja.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7

#11826 [3.7] bpo-35960: Fix dataclasses.field throwing away empty metadata. (GH-11815)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2019-02-10-20-57-12.bpo-35960.bh-6Ja.rst
Labels: CLA signed, awaiting review

#11822 bpo-35972: _xxsubinterpreters: Fix potential integer truncation in channel_send()
  Lib/test/test__xxsubinterpreters.py
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news

#11823 bpo-35505: Skip test_imap4_host_default_value if localhost listens on IMAP port
  Lib/test/test_imaplib.py
  Misc/NEWS.d/next/Tests/2019-02-12-01-33-08.bpo-35505.N9ba_K.rst
Labels: CLA signed, awaiting merge, type-tests

#11829 [3.7] bpo-35505: Skip test_imap4_host_default_value if localhost listens on IMAP port (GH-11823)
  Lib/test/test_imaplib.py
  Misc/NEWS.d/next/Tests/2019-02-12-01-33-08.bpo-35505.N9ba_K.rst
Labels: CLA signed, awaiting merge, type-tests

#11832 bpo-35973: Fix potential memory leak in parsetok.c
  Parser/parsetok.c
Labels: CLA signed, awaiting merge, skip news

#11556 Remove stray quote in os.replace docstring
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip issue, skip news

#11835 [3.7] Remove stray quote in os.replace docstring.
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#11837 Be consistent about the use of from-imports in random module
  Lib/random.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#11818 bpo-18283: Add support for bytes to shutil.which
  Doc/library/shutil.rst
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2019-02-11-09-24-08.bpo-18283.BT3Jhc.rst
Labels: CLA signed, awaiting merge

#11830 bpo-35961: Fix a crash in slice_richcompare()
  Misc/NEWS.d/next/Core and Builtins/2019-02-12-20-16-34.bpo-35961.7f7Sne.rst
  Objects/sliceobject.c
Labels: CLA signed, awaiting merge

#11839 [3.7] bpo-35961: Fix a crash in slice_richcompare() (GH-11830)
  Misc/NEWS.d/next/Core and Builtins/2019-02-12-20-16-34.bpo-35961.7f7Sne.rst
  Objects/sliceobject.c
Labels: CLA signed, awaiting merge

#11777 bpo-35887: Add make regen-importlib step to importlib docs
  Lib/importlib/_bootstrap.py
Labels: CLA signed, awaiting merge, skip news

#11804 bpo-35500: align expected and actual calls on mock.assert_called_with error message.
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2019-02-10-00-00-13.bpo-35500.1HOMmo.rst
Labels: CLA signed, awaiting merge

#11681 bpo-35826: Fix typo in equivalent code of `async with cond`
  Doc/library/asyncio-sync.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#11849 bpo-35991: Fix a potential double free in Modules/_randommodule.c
  Misc/NEWS.d/next/Core and Builtins/2019-02-14-00-00-30.bpo-35991.xlbfSk.rst
  Modules/_randommodule.c
Labels: CLA signed, awaiting review, needs backport to 3.7

#11851 [3.7] closes bpo-35991: Fix a potential double free in Modules/_randommodule.c. (GH-11849)
  Misc/NEWS.d/next/Core and Builtins/2019-02-14-00-00-30.bpo-35991.xlbfSk.rst
  Modules/_randommodule.c
Labels: CLA signed, awaiting merge

#11825 bpo-35976: Enable Windows projects to build with platform ARM32
  .gitignore
  Misc/NEWS.d/next/Windows/2019-02-11-20-07-43.bpo-35976.toap7O.rst
  PC/pyconfig.h
  PCbuild/_asyncio.vcxproj
  PCbuild/_bz2.vcxproj
  PCbuild/_ctypes.vcxproj
  PCbuild/_ctypes_test.vcxproj
  PCbuild/_decimal.vcxproj
  PCbuild/_elementtree.vcxproj
  PCbuild/_freeze_importlib.vcxproj
  PCbuild/_hashlib.vcxproj
  PCbuild/_lzma.vcxproj
  PCbuild/_msi.vcxproj
  PCbuild/_multiprocessing.vcxproj
  PCbuild/_overlapped.vcxproj
  PCbuild/_queue.vcxproj
  PCbuild/_socket.vcxproj
  PCbuild/_sqlite3.vcxproj
  PCbuild/_ssl.vcxproj
  PCbuild/_testbuffer.vcxproj
  PCbuild/_testcapi.vcxproj
  PCbuild/_testconsole.vcxproj
  PCbuild/_testembed.vcxproj
  PCbuild/_testimportmultiple.vcxproj
  PCbuild/_testmultiphase.vcxproj
  PCbuild/_tkinter.vcxproj
  PCbuild/liblzma.vcxproj
  PCbuild/pcbuild.proj
  PCbuild/pcbuild.sln
  PCbuild/pyexpat.vcxproj
  PCbuild/pylauncher.vcxproj
  PCbuild/pyproject.props
  PCbuild/pyshellext.vcxproj
  PCbuild/python.props
  PCbuild/python.vcxproj
  PCbuild/python3dll.vcxproj
  PCbuild/pythoncore.vcxproj
  PCbuild/pythonw.vcxproj
  PCbuild/pywlauncher.vcxproj
  PCbuild/select.vcxproj
  PCbuild/sqlite3.vcxproj
  PCbuild/unicodedata.vcxproj
  PCbuild/venvlauncher.vcxproj
  PCbuild/venvwlauncher.vcxproj
  PCbuild/winsound.vcxproj
  PCbuild/xxlimited.vcxproj
Labels: CLA signed, awaiting merge

#11424 bpo-35633: test_lockf() fails with "PermissionError: [Errno 13] Permission denied" on AIX
  Lib/test/eintrdata/eintr_tester.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip news

#11858 [3.7] bpo-35633: test_lockf() fails with "PermissionError: [Errno 13] Permission denied" on AIX (GH-11424)
  Lib/test/eintrdata/eintr_tester.py
Labels: CLA signed, awaiting merge, skip news

#10264 bpo-30410: Documentation of sys.stdin/out/err update to reflect change in 3.6
  Doc/library/sys.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#11860 [3.7] bpo-30410: Documentation of sys.stdin/out/err update to reflect change in 3.6 (GH-10264)
  Doc/library/sys.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11853 bpo-35994: add sub dir for sub2_tree in os.walk test if symlink is not supported
  Lib/test/test_os.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip news, type-tests

#11861 [3.7] bpo-35994: add sub dir for sub2_tree in os.walk test if symlink is not supported (GH-11853)
  Lib/test/test_os.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#11863 bpo-35746: Credit Colin Read and Nicolas Edet
  Misc/NEWS.d/3.8.0a1.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11866 [2.7] bpo-35746: Credit Colin Read and Nicolas Edet
  Misc/NEWS.d/next/Security/2019-01-15-18-16-05.bpo-35746.nMSd0j.rst
Labels: CLA signed, awaiting merge

#11864 [3.7] bpo-35746: Credit Colin Read and Nicolas Edet
  Misc/NEWS.d/next/Security/2019-01-15-18-16-05.bpo-35746.nMSd0j.rst
Labels: CLA signed, awaiting merge

#10607 [2.7] bpo-33570: TLS 1.3 ciphers for OpenSSL 1.1.1 (GH-6976) (GH-8760)
  Doc/library/ssl.rst
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2018-05-18-21-50-47.bpo-33570.7CZy4t.rst
  Tools/ssl/multissltests.py
Labels: CLA signed, awaiting review

#10608 [2.7] bpo-28043: improved default settings for SSLContext
  Doc/library/ssl.rst
  Lib/ssl.py
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Security/2018-11-20-16-50-03.bpo-28043.qOoOqW.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting review

#11877 [2.7] bpo-29136: Fix from test_ssl test_default_ecdh_curve
  Lib/test/test_ssl.py
Labels: CLA signed, awaiting review, skip news, type-tests

#11876 [2.7] bpo-32947: Fixes for TLS 1.3 and OpenSSL 1.1.1 (GH-8761)
  Doc/library/ssl.rst
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2018-08-14-08-57-01.bpo-32947.mqStVW.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting review

#11879 [2.7] bpo-33570: Enable OpenSSL 1.1.1 testing within the multissl test file
  Tools/ssl/multissltests.py
Labels: CLA signed, awaiting merge, skip news

#11881 bpo-36006: Fix versionchanged directive alignment in io module documentation
  Doc/library/io.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#11882 [3.7] bpo-36006: Fix versionchanged directive alignment in io module documentation (GH-11881)
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11880 Fix the versionadded info for typing.NoReturn
  Doc/library/typing.rst
Labels: :robot: automerge, CLA not signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#11883 [3.7] Fix the versionadded info for typing.NoReturn (GH-11880)
  Doc/library/typing.rst
Labels: CLA not signed, awaiting merge, skip issue, skip news, type-documentation

#11884 Improve readability of random module examples
  Doc/library/random.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#11885 [3.7] Improve readability of random module examples (GH-11884)
  Doc/library/random.rst
Labels: :robot: automerge, CLA signed, awaiting review, skip issue, skip news, type-documentation

#11782 bpo-35931: Gracefully handle SyntaxError in pdb debug command
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2019-02-07-16-22-50.bpo-35931._63i7B.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7

#11886 [3.7] bpo-35931: Gracefully handle SyntaxError in pdb debug command (GH-11782)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2019-02-07-16-22-50.bpo-35931._63i7B.rst
Labels: CLA signed, awaiting merge

#11845 bpo-35984: _xxsubinterpreters: Fix memory leak in _channel_send()
  Modules/_xxsubinterpretersmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#11887 bpo-36007: Bump minimum sphinx version to 1.8
  Doc/conf.py
  Misc/NEWS.d/next/Documentation/2019-02-15-15-33-41.bpo-36007.OTFrza.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7

#11757 bpo-15248: Emit a compiler warning when missed a comma before tuple or list.
  Doc/whatsnew/3.8.rst
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-04-21-10-17.bpo-15248.2sXSZZ.rst
  Python/compile.c
Labels: CLA signed, awaiting merge

#11639 bpo-35798: Fix duplicate SyntaxWarning: "is" with a literal.
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#11890 [2.7] Update IDLE.app plist copyright date
  Mac/IDLE/Info.plist.in
Labels: CLA signed, awaiting merge, skip issue, skip news

#11865 [3.6] bpo-35746: Credit Colin Read and Nicolas Edet
  Misc/NEWS.d/next/Security/2019-01-15-18-16-05.bpo-35746.nMSd0j.rst
Labels: CLA signed, awaiting merge, type-tests

#11896 bpo-33089: Add math.dist() and math.hypot() to Whatsnew
  Doc/whatsnew/3.8.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#11897 bpo-32492: Add missing whatsnew entries for itemgetter and namedtuple
  Doc/whatsnew/3.8.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#11899 bpo-33234: Add another attribution in Whatsnew
  Doc/whatsnew/3.8.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#11898 bpo-35884: Add missing FIFO queue benchmark
  Tools/scripts/var_access_benchmark.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#11862 bpo-1054041: Exit properly after an uncaught ^C.
  Include/internal/pycore_pylifecycle.h
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-16-00-42-32.bpo-1054051.BL-WLd.rst
  Modules/main.c
  Python/pylifecycle.c
  Python/pythonrun.c
Labels: CLA signed, awaiting merge, type-bugfix, type-enhancement

#11889 Micro-optimization for random.choices(). Convert range() to repeat().
  Lib/random.py
Labels: CLA signed, awaiting core review, skip issue, skip news, type-performance

#11901 [2.7] Add product codes until the end of time
  Tools/msi/uuids.py
Labels: CLA signed, OS-windows, awaiting merge, skip issue, skip news

#11902 bpo-36013: Fix the interactive shell SIGINT test.
  Lib/test/test_signal.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-tests

#9391 bpo-34720: Fix test_importlib.test_bad_traverse for AIX
  Misc/NEWS.d/next/Tests/2018-12-26-12-31-16.bpo-34720.T268vz.rst
  Modules/_testmultiphase.c
Labels: :robot: automerge, CLA signed, awaiting merge

#11857 bpo-35992: Use PySequence_GetItem only if sq_item is not NULL
  Lib/test/test_genericclass.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-14-12-01-44.bpo-35992.nG9e2L.rst
  Objects/abstract.c
Labels: CLA signed, awaiting merge, needs backport to 3.7

#11910 [3.7] bpo-35992: Use PySequence_GetItem only if sq_item is not NULL (GH-11857)
  Lib/test/test_genericclass.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-14-12-01-44.bpo-35992.nG9e2L.rst
  Objects/abstract.c
Labels: CLA signed, awaiting merge

#11831 bpo-35942: Improve the error message if __fspath__ returns invalid types in path_converter
  Lib/test/test_os.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-18-09-30-55.bpo-35942.oLhL2v.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-bugfix

#11500 bpo-35704: Prevent test_shutil fail result when AIX is 32-bit and MAXDATA < 0x20000000
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Tests/2019-01-04-17-44-41.bpo-35633.wHfVop.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#11912 [3.7] bpo-35942: Improve the error message if __fspath__ returns invalid types in path_converter (GH-11831)
  Lib/test/test_os.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-18-09-30-55.bpo-35942.oLhL2v.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#11914 bpo-35704: Include correct NEWS entry
  Misc/NEWS.d/next/Tests/2019-01-04-17-44-41.bpo-35633.wHfVop.rst
  Misc/NEWS.d/next/Tests/2019-01-10-09-14-58.bpo-35704.FLglYo.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#11546 bpo-34294: re module, fix wrong capturing groups in rare cases
  Doc/library/re.rst
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2019-01-14-11-53-10.bpo-34294.3JFdg2.rst
  Modules/_sre.c
  Modules/sre_lib.h
Labels: CLA signed, awaiting merge

#11919 [3.7] bpo-34294: re module, fix wrong capturing groups in rare cases. (GH-11546)
  Doc/library/re.rst
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2019-01-14-11-53-10.bpo-34294.3JFdg2.rst
  Modules/_sre.c
  Modules/sre_lib.h
Labels: CLA signed, awaiting merge, type-bugfix

#9047 bpo-34572: change _pickle unpickling to use import rather than retrieving from sys.modules
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2018-09-05-03-02-32.bpo-34572.ayisd2.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting merge, needs backport to 3.7

#11921 [3.7] bpo-34572: change _pickle unpickling to use import rather than retrieving from sys.modules (GH-9047)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2018-09-05-03-02-32.bpo-34572.ayisd2.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting review

#11749 [2.7] bpo-1104: msilib.SummaryInfo.GetProperty() truncates the string by one character (GH-4517)
  Lib/test/test_msilib.py
  Misc/NEWS.d/next/Windows/2017-11-24-12-53-54.bpo-1104.1CWSZp.rst
  PC/_msi.c
Labels: :robot: automerge, CLA signed, awaiting merge

#11472 bpo-35689: IDLE: Add docstrings and unittests for colorizer.py
  Lib/idlelib/NEWS.txt
  Lib/idlelib/colorizer.py
  Lib/idlelib/idle_test/test_colorizer.py
  Misc/NEWS.d/next/IDLE/2019-01-08-17-51-44.bpo-35689.LlaqR8.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#11925 [3.7] bpo-35689: IDLE: Add docstrings and unittests for colorizer.py (GH-11472)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/colorizer.py
  Lib/idlelib/idle_test/test_colorizer.py
  Misc/NEWS.d/next/IDLE/2019-01-08-17-51-44.bpo-35689.LlaqR8.rst
Labels: CLA signed, awaiting merge

#11895 bpo-35798: Add test.support.check_syntax_warning().
  Doc/library/test.rst
  Lib/test/support/__init__.py
  Lib/test/test_grammar.py
  Lib/test/test_string_literals.py
  Misc/NEWS.d/next/Tests/2019-02-16-15-19-31.bpo-35798.JF16MP.rst
Labels: CLA signed, awaiting merge, type-enhancement

#11911 [2.7] bpo-35126: Fix a mistake in FAQ about converting number to string
  Doc/faq/programming.rst
  Misc/NEWS.d/next/Documentation/2019-02-18-10-01-07.bpo-35126.LWwl8X.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#11932 Fix syntax warnings in tests introduced in bpo-15248.
  Lib/test/test_bytes.py
  Lib/test/test_extcall.py
  Lib/test/test_tuple.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-tests

#11934 Fix syntax warnings in tests introduced in bpo-35942.
  Lib/test/test_os.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#11933 Fix a misnamed test for lists.
  Lib/test/list_tests.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-tests

#11936 [3.7] Fix a misnamed test for lists. (GH-11933)
  Lib/test/list_tests.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#11937 [3.7] Fix syntax warnings in tests introduced in bpo-35942. (GH-11934)
  Lib/test/test_os.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#11641 bpo-31506: Clarify error messages for object.__new__ and object.__init__
  Lib/test/test_class.py
  Misc/NEWS.d/next/Core and Builtins/2019-01-22-02-06-39.bpo-31506.eJ5FpV.rst
  Objects/typeobject.c
Labels: CLA signed, awaiting merge

#11939 [3.7] bpo-31506: Clarify error messages for object.__new__ and object.__init__ (GH-11641)
  Lib/test/test_class.py
  Misc/NEWS.d/next/Core and Builtins/2019-01-22-02-06-39.bpo-31506.eJ5FpV.rst
  Objects/typeobject.c
Labels: CLA signed, awaiting merge

#11315 Doc: Fix typo.
  Doc/library/unittest.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation
