Repository python/cpython, pull requests merged in 2019-01, with the labels that each got.

#11394 bpo-35630: Use code tag for 'python3' in 'README.rst'
  README.rst
Labels: CLA signed, awaiting review, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#11380 bpo-35623: Fix integer overflow when sorting large lists
  Misc/NEWS.d/next/Core and Builtins/2018-12-31-02-37-20.bpo-35623.24AQhY.rst
  Objects/listobject.c
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#11399 [3.7] closes bpo-35630: Use code tag for 'python3' in 'README.rst' (GH-11394)
  README.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11400 [3.6] closes bpo-35630: Use code tag for 'python3' in 'README.rst' (GH-11394)
  README.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11402 bpo-35636: remove redundant check in unicode_hash(PyObject *self)
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, skip news

#11322 bpo-35588: Speed up mod, divmod and floordiv operations for Fraction type
  Lib/fractions.py
  Lib/test/test_fractions.py
  Misc/NEWS.d/next/Library/2018-12-26-10-55-59.bpo-35588.PSR6Ez.rst
Labels: CLA signed, awaiting merge

#11356 Revert "bpo-35603: Escape table header of make_table output that can cause potential XSS"
  Lib/difflib.py
  Lib/test/test_difflib.py
  Misc/NEWS.d/next/Library/2018-12-28-14-53-22.bpo-35603.rVCZAE.rst
Labels: CLA signed, awaiting core review

#11404 Bump copyright years to 2019.
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting core review, skip issue, skip news

#11406 [3.7] Bump copyright years to 2019. (GH-11404).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#11407 [3.6] Bump copyright years to 2019. (GH-11404).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#11408 [2.7] Bump copyright years to 2019. (GH-11404).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  Python/getcopyright.c
  README
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#11409 [2.7] Remove README.rst inadvertandly "backported" from 3.x in 5a89c71580529549e71567abf557c812eb470b2b.
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#11412 [3.7] closes bpo-35643: Fix a SyntaxWarning: invalid escape sequence in Modules/_sha3/cleanup.py (GH-11411)
  Misc/NEWS.d/next/Library/2019-01-02-20-04-49.bpo-35643.DaMiaV.rst
  Modules/_sha3/cleanup.py
Labels: CLA signed, awaiting merge

#11310 bpo-35525: Update the argument name for NNTP.starttls()
  Doc/library/nntplib.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#11416 [3.7] bpo-35525: Correct the argument name for NNTP.starttls() (GH-11310)
  Doc/library/nntplib.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11395 bpo-33987: IDLE - use ttk Frame for ttk widgets
  Lib/idlelib/autocomplete_w.py
  Lib/idlelib/config_key.py
  Lib/idlelib/configdialog.py
  Lib/idlelib/debugger.py
  Lib/idlelib/grep.py
  Lib/idlelib/idle_test/test_searchbase.py
  Lib/idlelib/query.py
  Lib/idlelib/replace.py
  Lib/idlelib/scrolledlist.py
  Lib/idlelib/search.py
  Lib/idlelib/searchbase.py
  Lib/idlelib/tree.py
  Misc/NEWS.d/next/IDLE/2018-12-31-17-04-18.bpo-33987.fD92up.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#11419 [3.7] bpo-33987: IDLE - use ttk Frame for ttk widgets (GH-11395)
  Lib/idlelib/autocomplete_w.py
  Lib/idlelib/config_key.py
  Lib/idlelib/configdialog.py
  Lib/idlelib/debugger.py
  Lib/idlelib/grep.py
  Lib/idlelib/idle_test/test_searchbase.py
  Lib/idlelib/query.py
  Lib/idlelib/replace.py
  Lib/idlelib/scrolledlist.py
  Lib/idlelib/search.py
  Lib/idlelib/searchbase.py
  Lib/idlelib/tree.py
  Misc/NEWS.d/next/IDLE/2018-12-31-17-04-18.bpo-33987.fD92up.rst
Labels: CLA signed, awaiting merge

#11415 bpo-35641: IDLE - calltip not properly formatted if no docstring
  Lib/idlelib/calltip.py
  Lib/idlelib/idle_test/test_calltip.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-01-02-22-15-01.bpo-35641.QEaANl.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-bugfix

#11420 [3.7] bpo-35641: IDLE - format calltip properly when no docstring (GH-11415)
  Lib/idlelib/calltip.py
  Lib/idlelib/idle_test/test_calltip.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-01-02-22-15-01.bpo-35641.QEaANl.rst
Labels: CLA signed, awaiting merge, type-bugfix

#11422 bpo-31450: Remove documentation mentioning that subprocess's child_tr…
  Doc/library/subprocess.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news, type-documentation

#11426 [3.7] bpo-31450: Remove documentation mentioning that subprocess's child_traceback is available with the parent process (GH-11422)
  Doc/library/subprocess.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#11396 bpo-35631: Improve typing docs wrt abstract/concrete collection types
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#11431 [3.7] bpo-35631: Improve typing docs wrt abstract/concrete collection types (GH-11396)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11274 bpo-23057: Use 'raise' to emulate ctrl-c in proactor tests
  Lib/asyncio/windows_events.py
  Lib/test/test_asyncio/test_ctrl_c_in_proactor_loop_helper.py
  Lib/test/test_asyncio/test_windows_events.py
Labels: CLA signed, awaiting merge, expert-asyncio, skip news, type-tests

#11444 bpo-20182: remove doc-string declaration no longer used after AC conversion
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#11171 bpo-35488: Add test for ** glob matching in pathlib
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Tests/2019-01-04-21-34-53.bpo-35488.U7JJzP.rst
Labels: CLA signed, awaiting merge, type-tests

#11434 bpo-35660: Fix imports in idlelib.window
  Lib/idlelib/window.py
  Misc/NEWS.d/next/IDLE/2019-01-04-19-14-29.bpo-35660.hMxI7N.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#11449 [3.7] bpo-35660: Fix imports in idlelib.window (GH-11434)
  Lib/idlelib/window.py
  Misc/NEWS.d/next/IDLE/2019-01-04-19-14-29.bpo-35660.hMxI7N.rst
Labels: CLA signed, awaiting merge

#8049 import sys in test_threading_local.py for line 144
  Lib/test/test_threading_local.py
Labels: CLA signed, awaiting review, skip issue, skip news

#11450 [3.7] test_threading_local: add missing "import sys" (GH-8049)
  Lib/test/test_threading_local.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#11288 bpo-35560: Remove incorrect assert statement that caused segfault in debug builds
  Lib/test/test_float.py
  Misc/NEWS.d/next/Core and Builtins/2018-12-22-22-19-51.bpo-35560.9vMWSP.rst
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-bugfix

#11435 bpo-35664: Optimize operator.itemgetter
  Lib/test/test_operator.py
  Misc/NEWS.d/next/Library/2019-01-04-22-18-25.bpo-35664.Z-Gyyj.rst
  Modules/_operator.c
Labels: CLA signed, awaiting merge, type-performance

#11461 bpo-32710: test_asyncio: test_sendfile reset policy
  Lib/test/test_asyncio/test_sendfile.py
  Misc/NEWS.d/next/Tests/2019-01-07-23-34-41.bpo-32710.Hzo1b8.rst
Labels: CLA signed, awaiting merge, type-tests

#11462 bpo-35682: Fix _ProactorBasePipeTransport._force_close()
  Lib/asyncio/proactor_events.py
  Misc/NEWS.d/next/Library/2019-01-08-01-54-02.bpo-35682.KDM9lk.rst
Labels: CLA signed, awaiting merge

#10763 CI, FIX remove spurious quote in azure script
  .azure-pipelines/posix-steps.yml
Labels: CLA signed, awaiting review, skip issue, skip news

#11463 [3.7] bpo-35682: Fix _ProactorBasePipeTransport._force_close() (GH-11462)
  Lib/asyncio/proactor_events.py
  Misc/NEWS.d/next/Library/2019-01-08-01-54-02.bpo-35682.KDM9lk.rst
Labels: CLA signed, awaiting merge

#10849 bpo-35374: Avoid trailing space in hhc file name if found on PATH.
  Doc/make.bat
Labels: CLA signed, awaiting review, skip news

#11464 [3.7] bpo-35374: Avoid trailing space in hhc file name if found on PATH. (GH-10849)
  Doc/make.bat
Labels: CLA signed, awaiting merge, skip news

#11335 bpo-35568: add 'raise_signal' function
  Doc/library/signal.rst
  Lib/test/test_asyncio/test_windows_events.py
  Lib/test/test_faulthandler.py
  Lib/test/test_posix.py
  Lib/test/test_regrtest.py
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Library/2018-12-27-19-23-00.bpo-35568.PutiOC.rst
  Modules/_testcapimodule.c
  Modules/clinic/signalmodule.c.h
  Modules/signalmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge

#11465 bpo-35596: Use unchecked PYCs for the embeddable distro to avoid zipimport restrictions
  .azure-pipelines/ci.yml
  .azure-pipelines/windows-layout-steps.yml
  Misc/NEWS.d/next/Windows/2019-01-08-13-56-01.bpo-35596.oFvhcm.rst
  PC/layout/main.py
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7

#11467 [3.7] bpo-35596: Use unchecked PYCs for the embeddable distro to avoid zipimport restrictions (GH-11465)
  .azure-pipelines/ci.yml
  .azure-pipelines/windows-layout-steps.yml
  Misc/NEWS.d/next/Windows/2019-01-08-13-56-01.bpo-35596.oFvhcm.rst
  PC/layout/main.py
Labels: CLA signed, awaiting merge

#11469 bpo-32710: Fix leak in Overlapped_WSASend()
  Misc/NEWS.d/next/Library/2019-01-08-14-00-52.bpo-32710.Sn5Ujj.rst
  Modules/overlapped.c
Labels: CLA signed, awaiting merge

#11471 [3.7] bpo-32710: Fix leak in Overlapped_WSASend() (GH-11469)
  Misc/NEWS.d/next/Library/2019-01-08-14-00-52.bpo-32710.Sn5Ujj.rst
  Modules/overlapped.c
Labels: CLA signed, awaiting merge

#10639 bpo-24746: Avoid stripping trailing whitespace in doctest fancy diff
  Lib/doctest.py
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Library/2018-11-22-15-22-56.bpo-24746.eSLKBE.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#11476 [3.7] bpo-24746: Avoid stripping trailing whitespace in doctest fancy diff (GH-10639)
  Lib/doctest.py
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Library/2018-11-22-15-22-56.bpo-24746.eSLKBE.rst
Labels: CLA signed, awaiting merge

#11477 [3.6] bpo-24746: Avoid stripping trailing whitespace in doctest fancy diff (GH-10639)
  Lib/doctest.py
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Library/2018-11-22-15-22-56.bpo-24746.eSLKBE.rst
Labels: CLA signed, awaiting merge

#11479 bpo-35641: Move IDLE blurb to IDLE directory
  Misc/NEWS.d/next/IDLE/2019-01-02-22-15-01.bpo-35641.QEaANl.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#11480 [3.7] bpo-35641: Move IDLE blurb to IDLE directory (GH-11479)
  Misc/NEWS.d/next/IDLE/2019-01-02-22-15-01.bpo-35641.QEaANl.rst
Labels: CLA signed, awaiting merge, skip news

#11482 [2.7] bpo-24746: Avoid stripping trailing whitespace in doctest fancy diff
  Lib/doctest.py
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Library/2018-11-22-15-22-56.bpo-24746.eSLKBE.rst
Labels: CLA signed

#11056 Add example to the documentation for calling unittest.mock.patch with create=True
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#11484 [3.7] Add example to the documentation for calling unittest.mock.patch with create=True (GH-11056)
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10886 bpo-35404: Clarify how to import _structure in email.message doc
  Doc/library/email.message.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#9648 Fix grammar in Dealing with Bugs
  Doc/bugs.rst
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#11485 [3.7] Update bugs.rst (GH-9648)
  Doc/bugs.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#11487 [2.7] Update bugs.rst (GH-9648)
  Doc/bugs.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#11423 Trivial: Distutils must no longer remain compatible with 2.3
  Lib/distutils/README
Labels: CLA signed, awaiting core review, skip issue, skip news

#11177 bpo-34855: Correct Windows-native variables
  .azure-pipelines/windows-appx-test.yml
  .azure-pipelines/windows-steps.yml
  PCbuild/find_python.bat
Labels: CLA signed, OS-windows, awaiting review, needs backport to 3.7, skip news

#11490 [3.7] bpo-34855: Fix EXTERNALS_DIR build variable for Windows (GH-11177)
  .azure-pipelines/windows-appx-test.yml
  .azure-pipelines/windows-steps.yml
  PCbuild/find_python.bat
Labels: CLA signed, awaiting merge, skip news

#11505 [3.7] bpo-24746: Fix doctest failures when running the testsuite with -R (GH-11501)
  Lib/test/test_doctest.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#11128 bpo-35470: Fix a reference counting bug in _PyImport_FindExtensionObjectEx()
  Python/import.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#11506 [3.7] bpo-35470: Fix a reference counting bug in _PyImport_FindExtensionObjectEx(). (GH-11128)
  Python/import.c
Labels: CLA signed, awaiting merge, skip news

#11503 bpo-35702: Add new identifier CLOCK_UPTIME_RAW for Darwin
  Doc/library/time.rst
  Doc/whatsnew/3.8.rst
  Misc/NEWS.d/next/Library/2019-01-10-14-03-12.bpo-35702._ct_0H.rst
  Modules/timemodule.c
Labels: CLA signed, awaiting merge

#5850 bpo-32146: Add documentation about frozen executables on Unix
  Doc/library/multiprocessing.rst
  Misc/NEWS.d/next/Library/2018-02-25-10-17-23.bpo-32146.xOzUFW.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-documentation

#11511 [3.7] bpo-32146: Add documentation about frozen executables on Unix (GH-5850)
  Doc/library/multiprocessing.rst
  Misc/NEWS.d/next/Library/2018-02-25-10-17-23.bpo-32146.xOzUFW.rst
Labels: CLA signed, awaiting merge, type-documentation

#11509 [3.6] - "Revert bpo-24746: Avoid stripping trailing whitespace in doctest fancy diff (GH-10639)"
  Lib/doctest.py
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Library/2018-11-22-15-22-56.bpo-24746.eSLKBE.rst
Labels: CLA signed, awaiting merge

#11512 [2.7] bpo-24746: Fix doctest failures when running the testsuite with -R
  Lib/test/test_doctest.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#11517 bpo-35716: CLOCK_MONOTONIC_RAW available on macOS
  Doc/library/time.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#11518 [3.7] bpo-35716: Update time.CLOCK_MONOTONIC_RAW doc (GH-11517)
  Doc/library/time.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11489 bpo-32710: Fix _overlapped.Overlapped memory leaks
  Misc/NEWS.d/next/Library/2019-01-10-15-55-10.bpo-32710.KwECPu.rst
  Modules/overlapped.c
Labels: CLA signed, awaiting merge, skip news

#11313 bpo-35582: Argument Clinic: inline parsing code for positional parameters.
  Include/modsupport.h
  Lib/test/clinic.test
  Modules/_io/clinic/bufferedio.c.h
  Modules/_io/clinic/bytesio.c.h
  Modules/_io/clinic/fileio.c.h
  Modules/_io/clinic/iobase.c.h
  Modules/_io/clinic/stringio.c.h
  Modules/_io/clinic/textio.c.h
  Modules/_io/clinic/winconsoleio.c.h
  Modules/cjkcodecs/clinic/multibytecodec.c.h
  Modules/clinic/_bz2module.c.h
  Modules/clinic/_codecsmodule.c.h
  Modules/clinic/_collectionsmodule.c.h
  Modules/clinic/_cryptmodule.c.h
  Modules/clinic/_curses_panel.c.h
  Modules/clinic/_cursesmodule.c.h
  Modules/clinic/_dbmmodule.c.h
  Modules/clinic/_elementtree.c.h
  Modules/clinic/_gdbmmodule.c.h
  Modules/clinic/_lzmamodule.c.h
  Modules/clinic/_operator.c.h
  Modules/clinic/_ssl.c.h
  Modules/clinic/_struct.c.h
  Modules/clinic/_tkinter.c.h
  Modules/clinic/_tracemalloc.c.h
  Modules/clinic/_weakref.c.h
  Modules/clinic/arraymodule.c.h
  Modules/clinic/audioop.c.h
  Modules/clinic/binascii.c.h
  Modules/clinic/cmathmodule.c.h
  Modules/clinic/fcntlmodule.c.h
  Modules/clinic/itertoolsmodule.c.h
  Modules/clinic/mathmodule.c.h
  Modules/clinic/posixmodule.c.h
  Modules/clinic/pwdmodule.c.h
  Modules/clinic/pyexpat.c.h
  Modules/clinic/resource.c.h
  Modules/clinic/selectmodule.c.h
  Modules/clinic/signalmodule.c.h
  Modules/clinic/spwdmodule.c.h
  Modules/clinic/symtablemodule.c.h
  Modules/clinic/unicodedata.c.h
  Modules/clinic/zlibmodule.c.h
  Objects/clinic/bytearrayobject.c.h
  Objects/clinic/bytesobject.c.h
  Objects/clinic/floatobject.c.h
  Objects/clinic/listobject.c.h
  Objects/clinic/longobject.c.h
  Objects/clinic/tupleobject.c.h
  Objects/clinic/typeobject.c.h
  Objects/clinic/unicodeobject.c.h
  Objects/stringlib/clinic/transmogrify.h.h
  PC/clinic/msvcrtmodule.c.h
  PC/clinic/winreg.c.h
  Python/clinic/bltinmodule.c.h
  Python/clinic/import.c.h
  Python/clinic/marshal.c.h
  Python/clinic/sysmodule.c.h
  Python/getargs.c
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting merge, skip news, type-performance

#11519 [3.7] bpo-32710: Fix _overlapped.Overlapped memory leaks (GH-11489)
  Misc/NEWS.d/next/Library/2019-01-10-15-55-10.bpo-32710.KwECPu.rst
  Modules/overlapped.c
Labels: CLA signed, awaiting merge, skip news

#11520 bpo-35582: Argument Clinic: Optimize the "all boring objects" case.
  Lib/test/clinic.test
  Modules/_io/clinic/bufferedio.c.h
  Modules/_io/clinic/bytesio.c.h
  Modules/_io/clinic/fileio.c.h
  Modules/_io/clinic/textio.c.h
  Modules/cjkcodecs/clinic/multibytecodec.c.h
  Modules/clinic/_abc.c.h
  Modules/clinic/_cursesmodule.c.h
  Modules/clinic/_elementtree.c.h
  Modules/clinic/_gdbmmodule.c.h
  Modules/clinic/_heapqmodule.c.h
  Modules/clinic/_operator.c.h
  Modules/clinic/_pickle.c.h
  Modules/clinic/_sre.c.h
  Modules/clinic/itertoolsmodule.c.h
  Modules/clinic/mathmodule.c.h
  Modules/clinic/selectmodule.c.h
  Objects/clinic/bytearrayobject.c.h
  Objects/clinic/bytesobject.c.h
  Objects/clinic/dictobject.c.h
  Objects/clinic/enumobject.c.h
  Objects/clinic/floatobject.c.h
  Objects/clinic/listobject.c.h
  Objects/clinic/tupleobject.c.h
  Objects/clinic/unicodeobject.c.h
  Python/clinic/bltinmodule.c.h
  Python/clinic/context.c.h
  Python/clinic/import.c.h
  Python/clinic/sysmodule.c.h
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting merge, skip news, type-performance

#9127 bpo-34569: Fix subinterpreter 32-bit ABI, pystate.c/_new_long_object()
  Misc/NEWS.d/next/Tests/2018-09-09-14-36-59.bpo-34569.okj1Xh.rst
  Python/pystate.c
Labels: CLA signed, awaiting merge, type-tests

#11532 [3.7] bpo-33817: Fix _PyBytes_Resize() for empty bytes object. (GH-11516)
  Lib/test/test_bytes.py
  Lib/test/test_unicode.py
  Misc/NEWS.d/next/C API/2019-01-11-11-16-16.bpo-33817.nJ4yIj.rst
  Objects/bytesobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#11161 bpo-35494: Improve syntax error messages for unbalanced parentheses in f-string.
  Lib/test/test_fstring.py
  Misc/NEWS.d/next/Core and Builtins/2018-12-14-18-02-34.bpo-35494.IWOPtb.rst
  Python/ast.c
Labels: CLA signed, awaiting merge, type-enhancement

#11438 bpo-35634: Raise an error when first passed kwargs contains duplicated keys.
  Lib/test/test_extcall.py
  Misc/NEWS.d/next/Core and Builtins/2019-01-05-18-39-49.bpo-35634.nVP_gs.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge

#11276 bpo-35552: Fix reading past the end in PyUnicode_FromFormat() and PyBytes_FromFormat().
  Misc/NEWS.d/next/Core and Builtins/2018-12-21-13-29-30.bpo-35552.1DzQQc.rst
  Objects/bytesobject.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, type-bugfix

#11533 [3.7] bpo-35552: Fix reading past the end in PyUnicode_FromFormat() and PyBytes_FromFormat(). (GH-11276)
  Misc/NEWS.d/next/Core and Builtins/2018-12-21-13-29-30.bpo-35552.1DzQQc.rst
  Objects/bytesobject.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#11534 [2.7] bpo-35552: Fix reading past the end in PyString_FromFormat(). (GH-11276)
  Misc/NEWS.d/next/Core and Builtins/2018-12-21-13-29-30.bpo-35552.1DzQQc.rst
  Objects/stringobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#8948 bpo-34512: Document platform-specific strftime() behavior for non-ASC…
  Doc/library/datetime.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, skip news, type-documentation

#10021 bpo-16806: Fix `lineno` and `col_offset` for multi-line string tokens.
  Lib/test/test_ast.py
  Lib/test/test_fstring.py
  Lib/test/test_opcodes.py
  Lib/test/test_string_literals.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2018-10-20-18-05-58.bpo-16806.zr3A9N.rst
  Parser/parsetok.c
  Parser/tokenizer.c
  Parser/tokenizer.h
  Python/ast.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting merge

#10454 bpo-35196: optimize Squeezer's write() interception
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Lib/idlelib/idle_test/test_squeezer.py
  Lib/idlelib/pyshell.py
  Lib/idlelib/squeezer.py
  Misc/NEWS.d/next/IDLE/2018-12-27-17-46-42.bpo-35196.9E-xUh.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-performance

#11541 [3.7] bpo-35196: Optimize Squeezer's write() interception (GH-10454)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Lib/idlelib/idle_test/test_squeezer.py
  Lib/idlelib/pyshell.py
  Lib/idlelib/squeezer.py
  Misc/NEWS.d/next/IDLE/2018-12-27-17-46-42.bpo-35196.9E-xUh.rst
Labels: CLA signed, awaiting merge, type-performance

#11543 bpo-35730: Disable IDLE test_reload assertion.
  Lib/idlelib/idle_test/test_squeezer.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-bugfix, type-tests

#11544 [3.7] bpo-35730: Disable IDLE test_reload assertion. (GH-11543)
  Lib/idlelib/idle_test/test_squeezer.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-tests

#10692 bpo-35066
  Lib/test/datetimetester.py
  Misc/NEWS.d/next/Library/2018-11-29-09-38-40.bpo-35066.Nwej2s.rst
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting core review, needs backport to 3.7

#11550 [3.7] bpo-35066: _dateime.datetime.strftime copies trailing '%' (GH-10692)
  Lib/test/datetimetester.py
  Misc/NEWS.d/next/Library/2018-11-29-09-38-40.bpo-35066.Nwej2s.rst
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting merge

#9457 bpo-34756: Simplify the implementation of sys.breakpointhook().
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#11551 [3.7] bpo-34756: Silence only ImportError and AttributeError in sys.breakpointhook(). (GH-9457)
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#11366 bpo-35619: Improve support of custom data descriptors in help() and pydoc.
  Lib/pydoc.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2018-12-30-19-50-36.bpo-35619.ZRXdhy.rst
Labels: CLA signed, awaiting merge, type-enhancement

#11238 bpo-29707: Document that os.path.ismount() is not able to detect bind mounts.
  Doc/library/os.path.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, skip news, type-documentation

#11560 [3.7] bpo-29707: Document that os.path.ismount() is not able to reliable detect bind mounts. (GH-11238)
  Doc/library/os.path.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11555 bpo-34323: Enhance IocpProactor.close() log
  Lib/asyncio/windows_events.py
  Misc/NEWS.d/next/Library/2019-01-14-17-34-36.bpo-34323.CRErrt.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#11562 [3.7] bpo-35738: Update the example for timer.Timer.repeat(). (GH-11559)
  Doc/library/timeit.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11563 bpo-11555: Enhance IocpProactor.close() log again
  Lib/asyncio/windows_events.py
Labels: CLA signed, awaiting merge, skip news

#11564 [3.7] bpo-35742: Fix test_envar_unimportable in test_builtin. (GH-11561)
  Lib/test/test_builtin.py
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#11565 [3.7] bpo-34323: Enhance IocpProactor.close() log
  Lib/asyncio/windows_events.py
  Misc/NEWS.d/next/Library/2019-01-14-17-34-36.bpo-34323.CRErrt.rst
Labels: CLA signed, awaiting merge

#11127 [2.7] bpo-8765: Deprecate writing unicode to binary streams in Py3k mode.
  Lib/test/test_fileio.py
  Misc/NEWS.d/next/Library/2018-12-12-09-59-41.bpo-8765.IFupT2.rst
  Modules/_io/bufferedio.c
  Modules/_io/fileio.c
Labels: CLA signed, awaiting merge, type-enhancement

#11566 bpo-23846: Fix ProactorEventLoop._write_to_self()
  Lib/asyncio/proactor_events.py
  Misc/NEWS.d/next/Library/2019-01-15-13-31-30.bpo-23846.LT_qL8.rst
Labels: CLA signed, awaiting merge

#11567 [3.7] bpo-23846: Fix ProactorEventLoop._write_to_self() (GH-11566)
  Lib/asyncio/proactor_events.py
  Misc/NEWS.d/next/Library/2019-01-15-13-31-30.bpo-23846.LT_qL8.rst
Labels: CLA signed, awaiting merge

#11569 bpo-35746: Fix segfault in ssl's cert parser
  Lib/test/talos-2019-0758.pem
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Security/2019-01-15-18-16-05.bpo-35746.nMSd0j.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-security

#11452 bpo-35537: subprocess uses os.posix_spawn in some cases
  Doc/whatsnew/3.8.rst
  Lib/subprocess.py
  Lib/test/pythoninfo.py
  Misc/NEWS.d/next/Library/2018-12-20-16-24-51.bpo-35537.z4E7aA.rst
Labels: CLA signed, awaiting merge

#11572 [3.7] bpo-35746: Fix segfault in ssl's cert parser (GH-11569)
  Lib/test/talos-2019-0758.pem
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Security/2019-01-15-18-16-05.bpo-35746.nMSd0j.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, type-security

#11574 [2.7] bpo-35746: Fix segfault in ssl's cert parser (GH-11569)
  Lib/test/talos-2019-0758.pem
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Security/2019-01-15-18-16-05.bpo-35746.nMSd0j.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, type-security

#11573 [3.6] bpo-35746: Fix segfault in ssl's cert parser (GH-11569)
  Lib/test/talos-2019-0758.pem
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Security/2019-01-15-18-16-05.bpo-35746.nMSd0j.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, type-security

#11582 Revert "bpo-35537: subprocess can now use os.posix_spawnp (GH-11579)"
  Doc/whatsnew/3.8.rst
  Lib/subprocess.py
  Lib/test/pythoninfo.py
Labels: CLA signed, awaiting merge, skip news

#11540 bpo-35486: Note Py3.6 import system API requirement change
  Doc/library/importlib.rst
  Doc/whatsnew/3.6.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#11587 [3.7] bpo-35486: Note Py3.6 import system API requirement change (GH-11540)
  Doc/library/importlib.rst
  Doc/whatsnew/3.6.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11581 Fixes typo in asyncio.queue doc
  Doc/library/asyncio-queue.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#11589 [3.7] Fixes typo in asyncio.queue doc (GH-11581)
  Doc/library/asyncio-queue.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#11454 bpo-35283: Add a deprecated warning for the threading.Thread.isAlive
  Doc/whatsnew/3.8.rst
  Lib/test/support/__init__.py
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Library/2019-01-07-17-17-16.bpo-35283.WClosC.rst
Labels: CLA signed, awaiting merge

#11570 bpo-35701: Added '__weakref__' to UUID __slots__ list to prevent regression.
  Lib/test/test_uuid.py
  Lib/uuid.py
Labels: CLA signed, awaiting review, skip news

#7282 bpo-33687: uu: fix call to os.chmod
  Lib/test/test_uu.py
  Lib/uu.py
  Misc/NEWS.d/next/Library/2018-06-10-14-08-52.bpo-33687.1zZdnA.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#11592 [3.7] bpo-33687: Fix call to os.chmod() in uu.decode() (GH-7282)
  Lib/test/test_uu.py
  Lib/uu.py
  Misc/NEWS.d/next/Library/2018-06-10-14-08-52.bpo-33687.1zZdnA.rst
Labels: CLA signed, awaiting review

#11597 bpo-34162: Update idlelib/NEWS.txt to 2019 Jan 17
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#11595 bpo-23156: Remove obsolete tix install directions
  Doc/library/tkinter.tix.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#11599 [3.7] bpo-23156: Remove obsolete tix install directions (GH-11595)
  Doc/library/tkinter.tix.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11598 [3.7] bpo-34161: Update idlelib/NEWS.txt to 2019 Jan 17 (GH-11597)
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting review, skip news, type-documentation

#11348 [3.6] bpo-35601: Alleviate race condition when waiting for SIGALRM in test_asyncio (GH-11337)
  Lib/test/test_asyncio/test_events.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#11351 [3.6] Make sure file object is close if socket.create_connection fails (GH-11334)
  Lib/test/test_socket.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#11417 [3.6] bpo-35525: Correct the argument name for NNTP.starttls() (GH-11310)
  Doc/library/nntplib.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11588 [3.6] bpo-35486: Note Py3.6 import system API requirement change (GH-11540)
  Doc/library/importlib.rst
  Doc/whatsnew/3.6.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11601 [3.7] bpo-35730: IDLE - test squeezer reload() by checking load_font() (GH-11585)
  Lib/idlelib/idle_test/test_squeezer.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-tests

#9642 bpo-34850: Emit a warning for "is" and "is not" with a literal.
  Doc/whatsnew/3.8.rst
  Lib/test/test_ast.py
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core and Builtins/2018-09-30-11-19-55.bpo-34850.CbgDwb.rst
  Python/compile.c
Labels: CLA signed, DO-NOT-MERGE, awaiting changes, type-enhancement

#11602 bpo-35769: Change IDLE's new file name from 'Untitled' to 'untitled'
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Misc/NEWS.d/next/IDLE/2019-01-18-01-24-23.bpo-35769.GqsB34.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#11596 bpo-35283: Update the docstring of threading.Thread.join method
  Lib/threading.py
Labels: CLA signed, awaiting core review, skip news

#11604 [3.7] bpo-35283: Add deprecation warning for Thread.isAlive (GH-11454)
  Lib/test/support/__init__.py
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Library/2019-01-07-17-17-16.bpo-35283.WClosC.rst
Labels: CLA signed, awaiting review

#11510 bpo-35045: Accept TLSv1 default in min max test
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2019-01-10-18-35-42.bpo-35045.qdd6d9.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, type-tests

#11443 bpo-21257: document http.client.parse_headers
  Doc/library/http.client.rst
  Misc/NEWS.d/next/Documentation/2019-01-15-21-45-27.bpo-21257.U9LKkx.rst
Labels: CLA signed, awaiting merge, type-documentation

#11614 bpo-35770: IDLE macosx deletes Options => Configure IDLE
  Lib/idlelib/NEWS.txt
  Lib/idlelib/macosx.py
  Misc/NEWS.d/next/IDLE/2019-01-18-13-04-30.bpo-35770.2LxJGu.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-bugfix

#11616 [3.7] bpo-35770: IDLE macosx deletes Options => Configure IDLE. (GH-11614)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/macosx.py
  Misc/NEWS.d/next/IDLE/2019-01-18-13-04-30.bpo-35770.2LxJGu.rst
Labels: CLA signed, awaiting merge, type-bugfix

#11547 bpo-35733: `isinstance(ast.Constant(True), ast.Num)` is `False`
  Lib/ast.py
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2019-01-13-18-42-41.bpo-35733.eFfLiv.rst
Labels: CLA signed, awaiting merge

#11618 bpo-35770: Fix off-by-1 error.
  Lib/idlelib/macosx.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-bugfix

#11495 bpo-35699: fix distuils cannot detect Build Tools 2017 anymore
  Lib/distutils/_msvccompiler.py
  Misc/NEWS.d/next/Library/2019-01-11-07-09-25.bpo-35699.VDiENF.rst
Labels: CLA signed, OS-windows, awaiting review, needs backport to 3.7, type-bugfix

#11626 [3.7] bpo-35699: fix distuils cannot detect Build Tools 2017 anymore (GH-11495)
  Lib/distutils/_msvccompiler.py
  Misc/NEWS.d/next/Library/2019-01-11-07-09-25.bpo-35699.VDiENF.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#11057 bpo-20239: Allow repeated deletion of unittest.mock.Mock attributes
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2018-12-09-21-35-49.bpo-20239.V4mWBL.rst
Labels: CLA signed

#11630 [3.7] bpo-35772: Fix test_tarfile on ppc64 (GH-11606)
  Lib/test/pythoninfo.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Tests/2019-01-18-12-19-19.bpo-35772.sGBbsn.rst
Labels: CLA signed, type-tests

#11635 bpo-35794: Catch PermissionError in test_no_such_executable
  Lib/test/test_posix.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#11620 bpo-35782: Fix error message in randrange
  Lib/random.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip news

#11531 bpo-35758: Fix building on ARM + MSVC
  Include/internal/pycore_atomic.h
  Include/pyport.h
  Misc/NEWS.d/next/Windows/2019-01-21-05-18-14.bpo-35758.8LsY3l.rst
Labels: CLA signed, awaiting merge

#11605 bpo-33416: Add end positions to Python AST
  Doc/library/ast.rst
  Include/Python-ast.h
  Include/node.h
  Lib/ast.py
  Lib/test/test_asdl_parser.py
  Lib/test/test_ast.py
  Lib/test/test_parser.py
  Misc/NEWS.d/next/Core and Builtins/2019-01-19-19-41-53.bpo-33416.VDeOU5.rst
  Modules/parsermodule.c
  Parser/Python.asdl
  Parser/asdl_c.py
  Parser/node.c
  Parser/parser.c
  Parser/parser.h
  Parser/parsetok.c
  Python/Python-ast.c
  Python/ast.c
  Python/ast_opt.c
  Python/compile.c
Labels: CLA signed, awaiting merge

#11528 bpo-35720: Fixing a memory leak in Modules/main.c:pymain_parse_cmdline_impl
  Misc/NEWS.d/next/Core and Builtins/2019-01-12-23-33-04.bpo-35720.LELKQx.rst
  Modules/main.c
Labels: CLA signed, awaiting review

#11647 bpo-35713: Rework Python initialization
  Doc/whatsnew/3.8.rst
  Include/cpython/pylifecycle.h
  Include/internal/pycore_pylifecycle.h
  Misc/NEWS.d/next/C API/2019-01-22-17-04-10.bpo-35713.fmehdG.rst
  Objects/bytearrayobject.c
  Objects/exceptions.c
  Objects/unicodeobject.c
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge

#11648 [3.7] bpo-35720: Fixing a memory leak in pymain_parse_cmdline_impl() (GH-11528)
  Misc/NEWS.d/next/Core and Builtins/2019-01-12-23-33-04.bpo-35720.LELKQx.rst
  Modules/main.c
Labels: CLA signed, awaiting merge

#11493 bpo-35683: Improve Azure Pipelines steps
  .azure-pipelines/ci.yml
  .azure-pipelines/docker-steps.yml
  .azure-pipelines/posix-deps-apt.sh
  .azure-pipelines/posix-steps.yml
  .azure-pipelines/pr.yml
  .azure-pipelines/windows-appx-test.yml
  .azure-pipelines/windows-layout-steps.yml
  .azure-pipelines/windows-steps.yml
  Lib/idlelib/idle_test/test_help_about.py
  Lib/test/libregrtest/main.py
  Lib/test/test_symbol.py
  Misc/NEWS.d/next/Build/2019-01-10-11-37-18.bpo-35683.pf5Oos.rst
  PC/layout/main.py
Labels: CLA signed, OS-windows, awaiting merge

#11650 bpo-35713: Split _Py_InitializeCore into subfunctions
  Include/internal/pycore_pylifecycle.h
  Misc/NEWS.d/next/Core and Builtins/2019-01-22-18-50-21.bpo-35713.bTeUsa.rst
  Objects/exceptions.c
  Objects/fileobject.c
  Objects/floatobject.c
  Objects/longobject.c
  Objects/object.c
  Objects/unicodeobject.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge

#11651 [3.7] bpo-35683: Improve Azure Pipelines steps (GH-11493)
  .azure-pipelines/ci.yml
  .azure-pipelines/docker-steps.yml
  .azure-pipelines/posix-deps-apt.sh
  .azure-pipelines/posix-steps.yml
  .azure-pipelines/pr.yml
  .azure-pipelines/windows-appx-test.yml
  .azure-pipelines/windows-layout-steps.yml
  .azure-pipelines/windows-steps.yml
  Lib/idlelib/idle_test/test_help_about.py
  Lib/test/libregrtest/main.py
  Lib/test/test_symbol.py
  Misc/NEWS.d/next/Build/2019-01-10-11-37-18.bpo-35683.pf5Oos.rst
  PC/layout/main.py
Labels: CLA signed, awaiting merge

#11537 bpo-35726:QueueHandler formatting affects other handlers
  Lib/logging/handlers.py
  Misc/NEWS.d/next/Library/2019-01-13-01-33-00.bpo-35726.dasdas.rst
Labels: CLA signed, awaiting change review

#11525 bpo-35722: Update the documentation for the parameter disable_existing_loggers
  Doc/howto/logging.rst
  Doc/library/logging.config.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11655 [3.7] bpo-35722: Updated the documentation for the 'disable_existing_loggers' parameter (GH-11525)
  Doc/howto/logging.rst
  Doc/library/logging.config.rst
Labels: CLA signed, awaiting review, skip news, type-documentation
