Repository python/cpython, pull requests merged in 2019-08, with the labels that each got.

#14748 bpo-18049: Sync thread stack size to main thread size on macOS
  Lib/test/test_threading.py
  Misc/NEWS.d/next/macOS/2019-07-13-15-58-18.bpo-18049.MklhQQ.rst
  Python/thread_pthread.h
  configure
  configure.ac
Labels: CLA signed, OS-mac, awaiting merge, needs backport to 3.8

#12341 bpo-36302: Sort list of sources
  Lib/distutils/command/build_ext.py
  Misc/NEWS.d/next/Library/2019-03-21-19-23-46.bpo-36302.Yc591g.rst
Labels: CLA signed, awaiting review

#15052 bpo-37726: prefer argparse over getopt
  Doc/tutorial/stdlib.rst
  Misc/NEWS.d/next/Documentation/2019-07-31-11-40-06.bpo-37726.h-3o9a.rst
Labels: CLA signed, awaiting merge, type-documentation

#15070 [3.8] bpo-37726: Prefer argparse over getopt in stdlib tutorial (GH-15052)
  Doc/tutorial/stdlib.rst
  Misc/NEWS.d/next/Documentation/2019-07-31-11-40-06.bpo-37726.h-3o9a.rst
Labels: CLA signed, awaiting review, type-documentation

#15069 [3.7] bpo-37726: Prefer argparse over getopt in stdlib tutorial (GH-15052)
  Doc/tutorial/stdlib.rst
  Misc/NEWS.d/next/Documentation/2019-07-31-11-40-06.bpo-37726.h-3o9a.rst
Labels: CLA signed, awaiting review, type-documentation

#15065 [3.8] bpo-18049: Sync thread stack size to main thread size on macOS (GH-14748)
  Lib/test/test_threading.py
  Misc/NEWS.d/next/macOS/2019-07-13-15-58-18.bpo-18049.MklhQQ.rst
  Python/thread_pthread.h
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#14817 [3.6] bpo-37461: Fix infinite loop in parsing of specially crafted email headers (GH-14794)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Security/2019-07-16-08-11-00.bpo-37461.1Ahz7O.rst
Labels: CLA signed, awaiting review, type-security

#14844 bpo-16970: Adding error message for invalid args
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-07-19-01-46-56.bpo-16970.GEASf5.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#15074 [3.8] bpo-16970: Adding error message for invalid args (GH-14844)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-07-19-01-46-56.bpo-16970.GEASf5.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#15050 bpo-37729: gc: write stats at once
  Modules/gcmodule.c
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-enhancement

#12666 bpo-36487: Make C-API docs clear about what the main interpreter is
  Doc/c-api/init.rst
  Misc/NEWS.d/next/Documentation/2019-04-02-19-23-00.bpo-36487.Jg6-MG.rst
Labels: CLA signed, awaiting merge, type-documentation

#15077 bpo-37742: Return the root logger when logging.getLogger('root') is c…
  Lib/logging/__init__.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2019-08-02-14-01-25.bpo-37742.f4Xn9S.rst
Labels: CLA signed, awaiting core review, type-enhancement

#15080 [3.8] bpo-36487: Make C-API docs clear about what the main interpreter is. (gh-12666)
  Doc/c-api/init.rst
  Misc/NEWS.d/next/Documentation/2019-04-02-19-23-00.bpo-36487.Jg6-MG.rst
Labels: CLA signed, awaiting review, type-documentation

#12767 bpo-36590: Add Bluetooth RFCOMM support for Windows.
  Lib/test/test_socket.py
  Misc/NEWS.d/next/Windows/2019-04-10-21-13-26.bpo-36590.ZTaKcu.rst
  Modules/socketmodule.c
  Modules/socketmodule.h
Labels: CLA signed, awaiting review

#11847 bpo-20523: pdb searches for .pdbrc in ~ instead of $HOME
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-15-20-42-36.bpo-20523.rRLrvr.rst
Labels: CLA signed, awaiting core review

#15084 [3.7] bpo-20523: pdb searches for .pdbrc in ~ instead of $HOME (GH-11847)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-15-20-42-36.bpo-20523.rRLrvr.rst
Labels: CLA signed, awaiting merge

#15085 [3.8] bpo-20523: pdb searches for .pdbrc in ~ instead of $HOME (GH-11847)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-15-20-42-36.bpo-20523.rRLrvr.rst
Labels: CLA signed, awaiting merge

#7337 bpo-30974: fix os.path.samefile docstring with docs
  Lib/genericpath.py
Labels: CLA signed, awaiting core review, skip news

#15086 [3.8] bpo-30974: Change os.path.samefile docstring to match docs (GH-7337)
  Lib/genericpath.py
Labels: CLA signed, awaiting merge, skip news

#15087 [3.7] bpo-30974: Change os.path.samefile docstring to match docs (GH-7337)
  Lib/genericpath.py
Labels: CLA signed, awaiting merge, skip news

#14869 bpo-37444: Update differing exception between builtins and importlib
  Doc/library/importlib.rst
  Doc/whatsnew/3.9.rst
  Lib/importlib/_bootstrap.py
  Lib/importlib/util.py
  Lib/test/test_importlib/import_/test_relative_imports.py
  Lib/test/test_importlib/test_util.py
  Misc/NEWS.d/next/Core and Builtins/2019-07-20-22-34-42.bpo-37444.UOd3Xs.rst
  Python/import.c
  Python/importlib.h
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#15081 bpo-18049: Define THREAD_STACK_SIZE for AIX to pass default recursion limit test
  Misc/NEWS.d/next/Library/2019-08-02-16-44-42.bpo-18049.OA4qBL.rst
  Python/thread_pthread.h
Labels: CLA signed, awaiting merge, needs backport to 3.8

#15078 Fix Typo in Lib/http/__init__.py
  Lib/http/__init__.py
Labels: CLA not signed, awaiting review, skip issue, skip news

#15098 [3.8] Correct description of HTTP status code 308. (GH-15078)
  Lib/http/__init__.py
Labels: CLA not signed, awaiting merge, skip issue, skip news

#15097 [3.7] Correct description of HTTP status code 308. (GH-15078)
  Lib/http/__init__.py
Labels: CLA not signed, awaiting merge, skip issue, skip news

#14996 bpo-37685: Fixed comparisons of datetime.timedelta and datetime.timezone.
  Doc/library/test.rst
  Lib/datetime.py
  Lib/test/datetimetester.py
  Lib/test/support/__init__.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2019-07-28-22-25-25.bpo-37685._3bN9f.rst
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.7, needs backport to 3.8, type-bugfix

#15102 [3.8] bpo-37685: Fixed comparisons of datetime.timedelta and datetime.timezone. (GH-14996)
  Doc/library/test.rst
  Lib/datetime.py
  Lib/test/datetimetester.py
  Lib/test/support/__init__.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2019-07-28-22-25-25.bpo-37685._3bN9f.rst
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#14904 bpo-37648: Fixed minor inconsistency in some __contains__.
  Doc/library/test.rst
  Lib/test/list_tests.py
  Lib/test/seq_tests.py
  Lib/test/support/__init__.py
  Lib/test/test_iter.py
  Misc/NEWS.d/next/Core and Builtins/2019-07-22-11-05-05.bpo-37648.6TY2L-.rst
  Modules/_asynciomodule.c
  Modules/_ssl.c
  Objects/abstract.c
  Objects/dictobject.c
  Objects/listobject.c
  Objects/tupleobject.c
Labels: CLA signed, awaiting merge

#15104 [3.7] bpo-37685: Fixed comparisons of datetime.timedelta and datetime.timezone. (GH-14996)
  Doc/library/test.rst
  Lib/datetime.py
  Lib/test/datetimetester.py
  Lib/test/support/__init__.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2019-07-28-22-25-25.bpo-37685._3bN9f.rst
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting core review, type-bugfix

#15063 [3.8] bpo-37730: Fix usage of NotImplemented instead of NotImplementedError in docs. (GH-15062)
  Doc/library/winreg.rst
  PC/clinic/winreg.c.h
  PC/winreg.c
Labels: CLA signed, awaiting merge, skip news, type-documentation

#15106 [3.7] bpo-37730: Fix usage of NotImplemented instead of NotImplementedError in docs. (GH-15062).
  Doc/library/winreg.rst
  PC/clinic/winreg.c.h
  PC/winreg.c
Labels: CLA signed, awaiting core review, skip news, type-documentation

#15103 bpo-37706: fix sidebar drag tests
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/idle_test/test_sidebar.py
  Lib/idlelib/sidebar.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news

#15107 [3.8] bpo-37706: IDLE - fix sidebar code bug and drag tests (GH-15103)
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/idle_test/test_sidebar.py
  Lib/idlelib/sidebar.py
Labels: CLA signed, awaiting merge, skip news

#15108 [3.7] bpo-37706: IDLE - fix sidebar code bug and drag tests (GH-15103)
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/idle_test/test_sidebar.py
  Lib/idlelib/sidebar.py
Labels: CLA signed, awaiting merge, skip news

#15110 bpo-36324: Update comments to include the target hash sums
  Lib/statistics.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-documentation

#15112 [3.8] bpo-36324: Update comments to include the target hash sums (GH-15110)
  Lib/statistics.py
Labels: CLA signed, awaiting review, skip news, type-documentation

#14834 [3.7] bpo-34621: backwards-compatible pickle UUID with is_safe=unknown
  Lib/uuid.py
  Misc/NEWS.d/next/Library/2019-08-04-22-06-54.bpo-34621.E2EWkw.rst
Labels: CLA signed, awaiting merge, type-bugfix

#15113 bpo-28292: Mark calendar.py helper functions as private.
  Lib/calendar.py
  Misc/NEWS.d/next/Library/2019-08-04-11-47-58.bpo-28292.vkihH5.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8

#15116 [3.8] bpo-28292: Mark calendar.py helper functions as private. (GH-15113)
  Lib/calendar.py
  Misc/NEWS.d/next/Library/2019-08-04-11-47-58.bpo-28292.vkihH5.rst
Labels: CLA signed, awaiting review

#15114 Update itertools docs
  Doc/library/itertools.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip issue, skip news, type-documentation

#15115 bpo-37748: Re-order the Run menu.
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help.html
  Lib/idlelib/mainmenu.py
  Misc/NEWS.d/next/IDLE/2019-08-04-15-27-50.bpo-37748.0vf6pg.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-enhancement

#15118 [3.8] Update itertools docs (GH-15114)
  Doc/library/itertools.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#15119 [3.8] bpo-37748: Re-order the Run menu. (GH-15115)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help.html
  Lib/idlelib/mainmenu.py
  Misc/NEWS.d/next/IDLE/2019-08-04-15-27-50.bpo-37748.0vf6pg.rst
Labels: CLA signed, awaiting merge, type-enhancement

#15120 [3.7] bpo-37748: Re-order the Run menu. (GH-15115)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help.html
  Lib/idlelib/mainmenu.py
  Misc/NEWS.d/next/IDLE/2019-08-04-15-27-50.bpo-37748.0vf6pg.rst
Labels: CLA signed, awaiting merge, type-enhancement

#15101 Adds authors of #11847
  Misc/ACKS
Labels: CLA signed, awaiting review, skip issue, skip news

#15121 bpo-36419: IDLE - Refactor autocompete and improve testing.
  Lib/idlelib/autocomplete.py
  Lib/idlelib/autocomplete_w.py
  Lib/idlelib/idle_test/test_autocomplete.py
  Misc/NEWS.d/next/IDLE/2019-08-04-17-10-01.bpo-36419.TJZqOc.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-enhancement, type-tests

#15123 [3.8] bpo-36419: IDLE - Refactor autocompete and improve testing. (GH-15121)
  Lib/idlelib/autocomplete.py
  Lib/idlelib/autocomplete_w.py
  Lib/idlelib/idle_test/test_autocomplete.py
  Misc/NEWS.d/next/IDLE/2019-08-04-17-10-01.bpo-36419.TJZqOc.rst
Labels: CLA signed, awaiting merge, type-enhancement, type-tests

#15124 [3.7] bpo-36419: IDLE - Refactor autocompete and improve testing. (GH-15121)
  Lib/idlelib/autocomplete.py
  Lib/idlelib/autocomplete_w.py
  Lib/idlelib/idle_test/test_autocomplete.py
  Misc/NEWS.d/next/IDLE/2019-08-04-17-10-01.bpo-36419.TJZqOc.rst
Labels: CLA signed, awaiting merge, type-enhancement, type-tests

#15076 [3.8] bpo-37729: gc: write stats at once (GH-15050)
  Modules/gcmodule.c
Labels: CLA signed, awaiting review, skip news, type-enhancement

#15133 [2.7] bpo-37730: Fix usage of NotImplemented instead of NotImplementedError in docs. (GH-15062).
  Doc/library/_winreg.rst
  PC/_winreg.c
Labels: CLA signed, awaiting merge, skip news, type-documentation

#15127 bpo-37759: Significant edits to Whatsnew 3.8
  Doc/whatsnew/3.8.rst
  Misc/NEWS.d/next/Documentation/2019-08-04-19-20-58.bpo-37759.EHRF4i.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, type-documentation

#15139 [3.8] bpo-37759: First round of major edits to Whatsnew 3.8 (GH-15127)
  Doc/whatsnew/3.8.rst
  Misc/NEWS.d/next/Documentation/2019-08-04-19-20-58.bpo-37759.EHRF4i.rst
Labels: CLA signed, awaiting review, type-documentation

#14274 Improve signal documentation
  Doc/library/signal.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#15151 [3.8] Improve signal documentation (GH-14274)
  Doc/library/signal.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#15152 [3.7] Improve signal documentation (GH-14274)
  Doc/library/signal.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#15153 bpo-37741: Make importlib.metadata a simple module
  Lib/importlib/metadata.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip news

#8904 bpo-34488: Improve performance of BytesIO.writelines() by avoiding creation of unused ints.
  Misc/NEWS.d/next/Library/2019-08-06-21-30-58.bpo-34488.OqxVo8.rst
  Modules/_io/bytesio.c
Labels: CLA signed, awaiting review

#15117 bpo-37646: Document that eval() cannot access nested scopes
  Doc/library/functions.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-documentation

#15155 [3.8] bpo-37646: Document that eval() cannot access nested scopes (GH-15117)
  Doc/library/functions.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#15154 [3.8] bpo-37741: Make importlib.metadata a simple module (GH-15153)
  Lib/importlib/metadata.py
Labels: CLA signed, awaiting review, skip news

#13482 bpo-37004: Documented asymmetry of string arguments in difflib.SequenceMatcher for ratio method
  Doc/library/difflib.rst
  Misc/NEWS.d/next/Documentation/2019-05-22-04-30-07.bpo-37004.BRgxrt.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, type-documentation

#14128 Update pickle.rst
  Doc/library/pickle.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#15157 [3.8] bpo-37004: Documented asymmetry of string arguments in difflib.SequenceMatcher for ratio method (GH-13482)
  Doc/library/difflib.rst
  Misc/NEWS.d/next/Documentation/2019-05-22-04-30-07.bpo-37004.BRgxrt.rst
Labels: CLA signed, awaiting core review, type-documentation

#15158 [3.7] bpo-37004: Documented asymmetry of string arguments in difflib.SequenceMatcher for ratio method (GH-13482)
  Doc/library/difflib.rst
  Misc/NEWS.d/next/Documentation/2019-05-22-04-30-07.bpo-37004.BRgxrt.rst
Labels: CLA signed, awaiting core review, type-documentation

#15146 bpo-37734: Fix use of registry values to launch Python from Microsoft Store app
  Misc/NEWS.d/next/Windows/2019-08-06-09-35-12.bpo-37734.EoJ9Nh.rst
  PC/layout/main.py
  PC/layout/support/appxmanifest.py
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8

#15150 bpo-37778: Fixes the icons used for file associations to the Microsoft Store package
  Misc/NEWS.d/next/Windows/2019-08-06-13-54-12.bpo-37778.AY1XhH.rst
  PC/icons/py.png
  PC/layout/support/appxmanifest.py
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8

#15163 [3.8] bpo-37734: Fix use of registry values to launch Python from Microsoft Store app (GH-15146)
  Misc/NEWS.d/next/Windows/2019-08-06-09-35-12.bpo-37734.EoJ9Nh.rst
  PC/layout/main.py
  PC/layout/support/appxmanifest.py
Labels: CLA signed, awaiting merge

#15164 [3.8] bpo-37778: Fixes the icons used for file associations to the Microsoft Store package (GH-15150)
  Misc/NEWS.d/next/Windows/2019-08-06-13-54-12.bpo-37778.AY1XhH.rst
  PC/icons/py.png
  PC/layout/support/appxmanifest.py
Labels: CLA signed, awaiting merge

#15165 bpo-37734: Remove unnecessary brace escapes in PC/layout script
  PC/layout/support/appxmanifest.py
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, skip news

#15166 [3.8] bpo-37734: Remove unnecessary brace escapes in PC/layout script (GH-15165)
  PC/layout/support/appxmanifest.py
Labels: CLA signed, awaiting merge, skip news

#9509 bpo-34775: Return NotImplemented in PurePath division.
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2018-09-23-03-18-52.bpo-34775.vHeuHk.rst
Labels: CLA signed, awaiting merge

#14952 bpo-37685: Fixed __eq__, __lt__ etc implementations in some classes.
  Lib/asyncio/events.py
  Lib/distutils/tests/test_version.py
  Lib/distutils/version.py
  Lib/email/headerregistry.py
  Lib/importlib/_bootstrap.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_email/test_headerregistry.py
  Lib/test/test_traceback.py
  Lib/test/test_weakref.py
  Lib/test/test_xmlrpc.py
  Lib/tkinter/__init__.py
  Lib/tkinter/font.py
  Lib/tkinter/test/test_tkinter/test_font.py
  Lib/tkinter/test/test_tkinter/test_variables.py
  Lib/traceback.py
  Lib/tracemalloc.py
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Lib/weakref.py
  Lib/xmlrpc/client.py
  Misc/NEWS.d/next/Library/2019-07-26-00-12-29.bpo-37685.TqckMZ.rst
  Python/importlib.h
  Tools/pynche/PyncheWidget.py
Labels: CLA signed, awaiting changes, type-bugfix

#15167 bpo-37685: Use singletons ALWAYS_EQ and NEVER_EQ in more tests.
  Lib/test/support/__init__.py
  Lib/test/test_collections.py
  Lib/test/test_compare.py
  Lib/test/test_contains.py
  Lib/test/test_dict_version.py
  Lib/test/test_enum.py
  Lib/test/test_inspect.py
  Lib/test/test_range.py
  Lib/test/test_urllib2.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#15122 bpo-35892: Add usage note to mode()
  Doc/library/statistics.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-documentation

#15176 [3.8] bpo-35892: Add usage note to mode() (GH-15122)
  Doc/library/statistics.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#15134 bpo-37587: optimize json.loads for large string
  Modules/_json.c
Labels: CLA signed, awaiting core review, skip news, type-performance

#15149 bpo-25172: Raise appropriate ImportError msg when crypt module used on Windows
  Lib/crypt.py
  Misc/NEWS.d/next/Windows/2019-08-06-18-09-18.bpo-25172.Akreij.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8

#15183 bpo-37268: test_parser fails when run with -Werror
  Lib/test/test_parser.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#15184 bpo-37795: Capture DeprecationWarnings in the test suite
  Lib/distutils/tests/test_bdist.py
  Lib/test/test_httplib.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-tests

#15181 bpo-36511 fix failures in Windows Python arm32 buildbot tests
  Lib/test/libregrtest/win_utils.py
  Tools/buildbot/remoteDeploy.bat
Labels: CLA signed, awaiting review, needs backport to 3.8, skip news

#15188 [3.8] bpo-37795: Capture DeprecationWarnings in the test suite (GH-15184)
  Lib/distutils/tests/test_bdist.py
  Lib/test/test_httplib.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#14825 [3.7] bpo-34155: Dont parse domains containing @ (GH-13079)
  Lib/email/_header_value_parser.py
  Lib/email/_parseaddr.py
  Lib/test/test_email/test__header_value_parser.py
  Lib/test/test_email/test_email.py
  Misc/NEWS.d/next/Security/2019-05-04-13-33-37.bpo-34155.MJll68.rst
Labels: CLA signed, awaiting merge, type-security

#14824 [3.8] bpo-34155: Dont parse domains containing @ (GH-13079)
  Lib/email/_header_value_parser.py
  Lib/email/_parseaddr.py
  Lib/test/test_email/test__header_value_parser.py
  Lib/test/test_email/test_email.py
  Misc/NEWS.d/next/Security/2019-05-04-13-33-37.bpo-34155.MJll68.rst
Labels: CLA signed, awaiting merge, type-security

#14878 bpo-37642: Update max and min offset in datetime module
  Lib/datetime.py
  Lib/test/datetimetester.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-07-21-20-59-31.bpo-37642.L61Bvy.rst
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#14826 [3.6] bpo-34155: Dont parse domains containing @ (GH-13079)
  Lib/email/_header_value_parser.py
  Lib/email/_parseaddr.py
  Lib/test/test_email/test__header_value_parser.py
  Lib/test/test_email/test_email.py
  Misc/NEWS.d/next/Security/2019-05-04-13-33-37.bpo-34155.MJll68.rst
Labels: CLA signed, awaiting review, type-security

#15142 [3.8] bpo-32912: Revert warnings for invalid escape sequences.
  Doc/reference/lexical_analysis.rst
  Doc/whatsnew/3.8.rst
  Lib/test/test_fstring.py
  Lib/test/test_string_literals.py
  Misc/NEWS.d/next/Core and Builtins/2019-08-06-14-03-59.bpo-32912.UDwSMJ.rst
  Python/ast.c
Labels: CLA signed, awaiting merge

#15195 bpo-32912: Revert SyntaxWarning on invalid escape sequences.
  Doc/reference/lexical_analysis.rst
  Doc/whatsnew/3.8.rst
  Lib/test/test_fstring.py
  Lib/test/test_string_literals.py
  Misc/NEWS.d/next/Core and Builtins/2019-08-06-14-03-59.bpo-32912.UDwSMJ.rst
  Python/ast.c
Labels: :robot: automerge, CLA signed, awaiting merge

#15174 Delete leftover clinic-generated file for C zipimport.
  Modules/clinic/zipimport.c.h
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip issue, skip news

#15196 [3.8] Delete leftover clinic-generated file for C zipimport. (GH-15174)
  Modules/clinic/zipimport.c.h
Labels: CLA signed, awaiting merge, skip issue, skip news

#15044 bpo-32178: Fix IndexError trying to parse 'To' header starting with ':'.
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Library/2019-07-30-22-41-05.bpo-32178.X-IFLe.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#15213 [3.8] bpo-32178: Fix IndexError trying to parse 'To' header starting with ':'. (GH-15044)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Library/2019-07-30-22-41-05.bpo-32178.X-IFLe.rst
Labels: CLA signed, awaiting merge, type-bugfix

#15214 [3.7] bpo-32178: Fix IndexError trying to parse 'To' header starting with ':'. (GH-15044)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Library/2019-07-30-22-41-05.bpo-32178.X-IFLe.rst
Labels: CLA signed, awaiting merge, type-bugfix

#15212 bpo-37819: Add Fraction.as_integer_ratio()
  Doc/library/fractions.rst
  Lib/fractions.py
  Lib/test/test_fractions.py
  Misc/NEWS.d/next/Library/2019-08-11-10-34-19.bpo-37819.LVJls-.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, type-enhancement

#15215 [3.8] bpo-37819: Add Fraction.as_integer_ratio() (GH-15212)
  Doc/library/fractions.rst
  Lib/fractions.py
  Lib/test/test_fractions.py
  Misc/NEWS.d/next/Library/2019-08-11-10-34-19.bpo-37819.LVJls-.rst
Labels: CLA signed, awaiting review, type-enhancement

#15197 Fix docs for assert_called and assert_called_once
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#15218 [3.7] Fix docs for assert_called and assert_called_once (GH-15197)
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#15219 [3.8] Fix docs for assert_called and assert_called_once (GH-15197)
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#15225 bpo-37804: Remove the deprecated method threading.Thread.isAlive()
  Doc/whatsnew/3.9.rst
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Library/2019-08-12-23-07-47.bpo-37804.Ene6L-.rst
Labels: CLA signed, awaiting review

#14967 bpo-37354: Make Powershell Activate.ps1 script static to allow for signing
  Lib/venv/scripts/common/Activate.ps1
  Misc/NEWS.d/next/Library/2019-07-25-10-28-40.bpo-37354.RT3_3H.rst
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.8, type-enhancement

#15233 [3.8] bpo-37354: Make Powershell Activate.ps1 script static to allow for signing (GH-14967)
  Lib/venv/scripts/common/Activate.ps1
  Misc/NEWS.d/next/Library/2019-07-25-10-28-40.bpo-37354.RT3_3H.rst
Labels: CLA signed, DO-NOT-MERGE, awaiting review, type-enhancement

#15235 bpo-37354: Sign Activate.ps1 for release
  .azure-pipelines/windows-release/msi-steps.yml
  .azure-pipelines/windows-release/stage-build.yml
  .azure-pipelines/windows-release/stage-layout-full.yml
  .azure-pipelines/windows-release/stage-layout-msix.yml
  .azure-pipelines/windows-release/stage-layout-nuget.yml
  .azure-pipelines/windows-release/stage-sign.yml
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, skip news

#15236 [3.8] bpo-37354: Sign Activate.ps1 for release (GH-15235)
  .azure-pipelines/windows-release/msi-steps.yml
  .azure-pipelines/windows-release/stage-build.yml
  .azure-pipelines/windows-release/stage-layout-full.yml
  .azure-pipelines/windows-release/stage-layout-msix.yml
  .azure-pipelines/windows-release/stage-layout-nuget.yml
  .azure-pipelines/windows-release/stage-sign.yml
Labels: CLA signed, awaiting merge, skip news

#15237 Remove versioned executables from non-APPX packages
  PC/layout/main.py
Labels: :robot: automerge, CLA signed, OS-windows, awaiting core review, needs backport to 3.8, skip issue, skip news, type-bugfix

#15238 [3.8] Remove versioned executables from non-APPX packages (GH-15237)
  PC/layout/main.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#15204 bpo-37759: Second round of edits to Whatsnew 3.8
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip news, type-documentation

#15240 [3.8] bpo-37759: Second round of edits to Whatsnew 3.8 (GH-15204)
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-documentation

#15130 bpo-37760: Factor out the basic UCD parsing logic of makeunicodedata.
  Tools/unicode/makeunicodedata.py
Labels: CLA signed, awaiting review, skip news

#15171 bpo-37760: Mark all generated Unicode data headers as generated.
  .gitattributes
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, needs backport to 3.8, skip news

#15126 bpo-37758: Clean out vestigial script-bits from test_unicodedata.
  Lib/test/test_unicodedata.py
Labels: CLA signed, awaiting review, skip news, type-tests

#15129 bpo-37760: Constant-fold some old options in makeunicodedata.
  Tools/unicode/makeunicodedata.py
Labels: CLA signed, awaiting review, skip news

#15253 bpo-37841: Remove python_uwp dependency on msvcp140.dll
  PCbuild/python_uwp.vcxproj
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, skip news, type-bugfix

#14729 bpo-37583: Update support.get_socket_conn_refused_errs()
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting review, needs backport to 3.7, needs backport to 3.8, skip news

#15257 [3.8] bpo-37841: Remove python_uwp dependency on msvcp140.dll (GH-15253)
  PCbuild/python_uwp.vcxproj
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#15258 [3.8] bpo-37583: Add err 113 to support.get_socket_conn_refused_errs() (GH-14729)
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting merge, skip news

#15208 bpo-37814: Document the empty tuple type annotation syntax
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#15261 [3.8] bpo-37814: Document the empty tuple type annotation syntax (GH-15208)
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#15262 [3.7] bpo-37814: Document the empty tuple type annotation syntax (GH-15208)
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#14982 bpo-37689: add Path.is_relative_to() method
  Doc/library/pathlib.rst
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2019-07-27-18-00-43.bpo-37689.glEmZi.rst
Labels: CLA signed, awaiting merge

#15182 [3.8] bpo-25172: Raise appropriate ImportError msg when crypt module used on Windows (GH-15149)
  Lib/crypt.py
  Misc/NEWS.d/next/Windows/2019-08-06-18-09-18.bpo-25172.Akreij.rst
Labels: CLA signed, awaiting merge

#15252 bpo-25172: Add test for crypt ImportError msg for Windows
  Lib/test/test_crypt.py
Labels: CLA signed, awaiting review, needs backport to 3.8, skip news, type-tests

#15263 [3.8] bpo-25172: Add test for crypt ImportError on Windows (GH-15252)
  Lib/test/test_crypt.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#14792 bpo-37256: Wording in Request class docs
  Doc/library/urllib.request.rst
  Misc/NEWS.d/next/Documentation/2019-07-16-14-48-12.bpo-37256.qJTrBb.rst
Labels: CLA signed, awaiting merge, type-documentation

#15248 bpo-37760: Factor out standard range-expanding logic in makeunicodedata.
  Tools/unicode/makeunicodedata.py
Labels: CLA signed, awaiting review, skip news

#14814 bpo-37337: Fix a GCC 9 warning in Objects/descrobject.c
  Objects/descrobject.c
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news

#15096 bpo-37681: no_sanitize_thread supported from gcc 5.1
  Objects/obmalloc.c
Labels: CLA signed, awaiting review, needs backport to 3.7, needs backport to 3.8, skip news

#15259 [3.7] bpo-37583: Update support.get_socket_conn_refused_errs()
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting review, skip news

#15270 [3.8] bpo-37681: no_sanitize_thread support from GCC 5.1 (GH-15096)
  Objects/obmalloc.c
Labels: CLA signed, awaiting merge, skip news

#15271 [3.7] bpo-37681: no_sanitize_thread support from GCC 5.1 (GH-15096)
  Objects/obmalloc.c
Labels: CLA signed, awaiting merge, skip news

#15071 bpo-37738: Fix curses addch(str, color_pair)
  Misc/NEWS.d/next/Library/2019-08-01-17-11-16.bpo-37738.A3WWcT.rst
  Modules/_cursesmodule.c
Labels: CLA signed, needs backport to 3.7, needs backport to 3.8

#15272 [3.8] bpo-37738: Fix curses addch(str, color_pair) (GH-15071)
  Misc/NEWS.d/next/Library/2019-08-01-17-11-16.bpo-37738.A3WWcT.rst
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting merge

#15273 [3.7] bpo-37738: Fix curses addch(str, color_pair) (GH-15071)
  Misc/NEWS.d/next/Library/2019-08-01-17-11-16.bpo-37738.A3WWcT.rst
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting core review

#15019 bpo-36502: Correct documentation of `str.isspace`.
  Doc/library/stdtypes.rst
  Lib/test/test_unicode.py
Labels: CLA signed, awaiting review, needs backport to 3.8, skip news, type-tests

#15072 bpo-37531: Fix regrtest timeout for subprocesses
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/runtest.py
  Lib/test/libregrtest/runtest_mp.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Library/2019-07-09-19-38-26.bpo-37531.GX7s8S.rst
Labels: CLA signed, awaiting core review

#15277 [3.7] bpo-37256: Wording in Request class docs (GH-14792)
  Doc/library/urllib.request.rst
  Misc/NEWS.d/next/Documentation/2019-07-16-14-48-12.bpo-37256.qJTrBb.rst
Labels: CLA signed, awaiting merge, type-documentation

#12052 bpo-36030: Improve performance of some tuple operations
  Objects/tupleobject.c
Labels: CLA signed, awaiting merge, skip news

#15280 [3.7] bpo-37531: Fix regrtest timeout for subprocesses (GH-15072)
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/runtest.py
  Lib/test/libregrtest/runtest_mp.py
  Lib/test/libregrtest/win_utils.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Library/2019-07-09-19-38-26.bpo-37531.GX7s8S.rst
Labels: CLA signed, awaiting core review

#15279 [3.8] bpo-37531: Fix regrtest timeout for subprocesses (GH-15072)
  Lib/test/libregrtest/__init__.py
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/runtest.py
  Lib/test/libregrtest/runtest_mp.py
  Lib/test/libregrtest/win_utils.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Library/2019-07-09-19-38-26.bpo-37531.GX7s8S.rst
Labels: CLA signed, awaiting core review

#15267 bpo-37849: IDLE: fix completion window positioning above line
  Lib/idlelib/NEWS.txt
  Lib/idlelib/autocomplete_w.py
  Misc/NEWS.d/next/IDLE/2019-08-14-09-43-15.bpo-37849.-bcYF3.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-bugfix

#15282 [3.8] bpo-37849: IDLE: fix completion window positioning above line (GH-15267)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/autocomplete_w.py
  Misc/NEWS.d/next/IDLE/2019-08-14-09-43-15.bpo-37849.-bcYF3.rst
Labels: CLA signed, awaiting merge, type-bugfix

#15283 [3.7] bpo-37849: IDLE: fix completion window positioning above line (GH-15267)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/autocomplete_w.py
  Misc/NEWS.d/next/IDLE/2019-08-14-09-43-15.bpo-37849.-bcYF3.rst
Labels: CLA signed, awaiting merge, type-bugfix

#15243 bpo-37826: Document exception chaining in Python tutorial for errors.
  Doc/tutorial/errors.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#15202 bpo-37811: FreeBSD, OSX: fix poll(2) usage in sockets module
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-08-14-21-41-07.bpo-37811.d1xYj7.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting review

#15276 bpo-21131: Fix faulthandler.register(chain=True) stack
  Misc/NEWS.d/next/Library/2019-08-14-15-34-23.bpo-21131.0MMQRi.rst
  Modules/faulthandler.c
Labels: CLA signed, needs backport to 3.7, needs backport to 3.8

#15290 [3.8] bpo-37811: FreeBSD, OSX: fix poll(2) usage in sockets module (GH-15202)
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-08-14-21-41-07.bpo-37811.d1xYj7.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting merge

#15289 [3.7] bpo-37811: FreeBSD, OSX: fix poll(2) usage in sockets module (GH-15202)
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-08-14-21-41-07.bpo-37811.d1xYj7.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting merge

#15291 [3.8] bpo-21131: Fix faulthandler.register(chain=True) stack (GH-15276)
  Misc/NEWS.d/next/Library/2019-08-14-15-34-23.bpo-21131.0MMQRi.rst
  Modules/faulthandler.c
Labels: CLA signed, awaiting merge

#15148 bpo-37775: update docs of compileall
  Doc/library/compileall.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#15292 [3.7] bpo-21131: Fix faulthandler.register(chain=True) stack (GH-15276)
  Misc/NEWS.d/next/Library/2019-08-14-15-34-23.bpo-21131.0MMQRi.rst
  Modules/faulthandler.c
Labels: CLA signed, awaiting merge

#15294 [3.8] bpo-37775: Update compileall doc for invalidation_mode parameter (GH-15148)
  Doc/library/compileall.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#15128 bpo-37760: Avoid cluttering work tree with downloaded Unicode files.
  .gitignore
  Tools/unicode/makeunicodedata.py
Labels: CLA signed, awaiting review, skip news
