Repository python/cpython, pull requests merged in 2019-04, with the labels that each got.

#12637 bpo-36492: Deprecate passing some arguments as keyword arguments.
  Doc/whatsnew/3.8.rst
  Lib/bdb.py
  Lib/cProfile.py
  Lib/concurrent/futures/_base.py
  Lib/concurrent/futures/process.py
  Lib/concurrent/futures/thread.py
  Lib/contextlib.py
  Lib/curses/__init__.py
  Lib/functools.py
  Lib/multiprocessing/managers.py
  Lib/profile.py
  Lib/test/test_concurrent_futures.py
  Lib/test/test_contextlib.py
  Lib/test/test_contextlib_async.py
  Lib/test/test_functools.py
  Lib/test/test_trace.py
  Lib/test/test_weakref.py
  Lib/trace.py
  Lib/unittest/case.py
  Lib/unittest/test/test_runner.py
  Lib/weakref.py
  Misc/NEWS.d/next/Library/2019-03-31-10-21-54.bpo-36492.f7vyUs.rst
Labels: CLA signed, awaiting core review, type-bugfix

#12645 [3.7] bpo-36492: Fix passing special keyword arguments to some functions. (GH-12637)
  Lib/bdb.py
  Lib/cProfile.py
  Lib/concurrent/futures/_base.py
  Lib/concurrent/futures/process.py
  Lib/concurrent/futures/thread.py
  Lib/contextlib.py
  Lib/curses/__init__.py
  Lib/functools.py
  Lib/multiprocessing/managers.py
  Lib/profile.py
  Lib/test/test_concurrent_futures.py
  Lib/test/test_contextlib.py
  Lib/test/test_contextlib_async.py
  Lib/test/test_functools.py
  Lib/test/test_trace.py
  Lib/test/test_weakref.py
  Lib/trace.py
  Lib/unittest/case.py
  Lib/weakref.py
  Misc/NEWS.d/next/Library/2019-03-31-10-21-54.bpo-36492.f7vyUs.rst
Labels: CLA signed, awaiting core review, type-bugfix

#11930 bpo-36026: make descr error message consistent
  Lib/test/test_descr.py
  Objects/descrobject.c
Labels: CLA signed, awaiting merge, skip news

#12616 bpo-20844: open script file with "rb" mode
  Doc/c-api/veryhigh.rst
  Lib/test/test_cmd_line_script.py
  Misc/NEWS.d/next/Core and Builtins/2019-03-29-18-47-50.bpo-20844.ge-7SM.rst
  Modules/main.c
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.7, type-bugfix

#12647 [3.7] bpo-20844: open script file with "rb" mode (GH-12616)
  Doc/c-api/veryhigh.rst
  Lib/test/test_cmd_line_script.py
  Misc/NEWS.d/next/Core and Builtins/2019-03-29-18-47-50.bpo-20844.ge-7SM.rst
  Modules/main.c
Labels: CLA signed, awaiting core review, type-bugfix

#12641 bpo-36495: Fix two out-of-bounds array reads
  Python/ast.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#12238 bpo-36157:Document PyInterpreterState_Main()
  Doc/c-api/init.rst
  Misc/NEWS.d/next/Documentation/2019-03-08-15-39-47.bpo-36157.nF1pP1.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#12650 [3.7] bpo-36157:Document PyInterpreterState_Main() (GH-12238)
  Doc/c-api/init.rst
  Misc/NEWS.d/next/Documentation/2019-03-08-15-39-47.bpo-36157.nF1pP1.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#12651 [3.7] Temporary workaround for an ACL issue on Ubuntu on Azure Pipelines (GH-12649)
  .azure-pipelines/posix-steps.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#12250 bpo-13120: fix typo with test_issue13120() method name
  Lib/test/test_pdb.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip news, type-tests

#12468 bpo-36377: Specify that range() can not be compared
  Doc/tutorial/datastructures.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12653 fix confusing argument name in unicodeobject.c
  Objects/exceptions.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#12652 [3.7] bpo-13120: fix typo with test_issue13120() method name (GH-12250)
  Lib/test/test_pdb.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#12656 bpo-35838: document optionxform must be idempotent
  Doc/library/configparser.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news, type-documentation

#12657 [3.7] bpo-35838: document optionxform must be idempotent (GH-12656)
  Doc/library/configparser.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12619 bpo-36473: add maximum iteration check for dict .values() and .items()
  Lib/test/test_dict.py
  Misc/NEWS.d/next/Core and Builtins/2019-03-27-23-53-00.bpo-36452.xhK2lT.rst
  Objects/dictobject.c
Labels: :robot: automerge, CLA signed, awaiting review

#12660 bpo-36504: Fix signed integer overflow in _ctypes.c's PyCArrayType_new()
  Lib/ctypes/test/test_arrays.py
  Misc/NEWS.d/next/Core and Builtins/2019-04-02-04-10-32.bpo-36504.k_V8Bm.rst
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, type-bugfix

#6448 bpo-33261: guard access to __code__ attribute in inspect
  Lib/inspect.py
  Lib/test/inspect_fodder.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2018-04-11-11-41-52.bpo-33291.-xLGf8.rst
Labels: CLA signed, awaiting merge

#5004 bpo-32413: Add documentation that at the module level, locals(), globals() are the same dictionary
  Doc/library/functions.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip news

#12664 [3.7] bpo-32413: Add documentation that at the module level, locals(), globals() are the same dictionary (GH-5004)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12139 Have UserDict.__init__() implicitly check for updating w/ bool(kwargs) instead of len()
  Lib/collections/__init__.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#12565 bpo-36440: include node names in ParserError messages, instead of numeric IDs
  Lib/test/test_parser.py
  Misc/NEWS.d/next/Core and Builtins/2019-03-25-13-45-19.bpo-36440.gkvzhi.rst
  Modules/parsermodule.c
Labels: CLA signed, awaiting merge

#12676 [3.7] bpo-36504: Fix signed integer overflow in _ctypes.c's PyCArrayType_new(). (GH-12660)
  Lib/ctypes/test/test_arrays.py
  Misc/NEWS.d/next/Core and Builtins/2019-04-02-04-10-32.bpo-36504.k_V8Bm.rst
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge, type-bugfix

#12671 [3.7] bpo-36440: include node names in ParserError messages, instead of numeric IDs (GH-12565)
  Lib/test/test_parser.py
  Misc/NEWS.d/next/Core and Builtins/2019-03-25-13-45-19.bpo-36440.gkvzhi.rst
  Modules/parsermodule.c
Labels: CLA signed, awaiting core review

#12678 [2.7] bpo-36504: Fix signed integer overflow in _ctypes.c's PyCArrayType_new(). (GH-12660)
  Lib/ctypes/test/test_arrays.py
  Misc/NEWS.d/next/Core and Builtins/2019-04-02-04-10-32.bpo-36504.k_V8Bm.rst
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge, type-bugfix

#12681 bpo-36522: Print all values for headers with multiple values
  Lib/http/client.py
  Lib/test/test_httplib.py
  Misc/NEWS.d/next/Library/2019-04-03-20-46-47.bpo-36522.g5x3By.rst
Labels: CLA not signed, awaiting merge, needs backport to 3.7, type-bugfix

#12682 [3.7] bpo-36522: Print all values for headers with multiple values. (GH-12681)
  Lib/http/client.py
  Lib/test/test_httplib.py
  Misc/NEWS.d/next/Library/2019-04-03-20-46-47.bpo-36522.g5x3By.rst
Labels: CLA not signed, awaiting merge, type-bugfix

#12662 Typo: delete duplicated test case
  Lib/test/re_tests.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#12690 Fix a misplaced stderr=
  Tools/importbench/importbench.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#12505 bpo-36404: recommend DeprecationWarning over PendingDeprecationWarning
  Doc/library/exceptions.rst
  Doc/library/warnings.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#12696 [3.7] bpo-36404: recommend DeprecationWarning over PendingDeprecationWarning (GH-12505)
  Doc/library/exceptions.rst
  Doc/library/warnings.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12695 bpo-36301: Fix _PyPreConfig_Read() compiler warning
  Python/preconfig.c
Labels: CLA signed, awaiting core review, skip news

#11900 bpo-29202: improve dict iteration
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, skip news, type-performance

#10406 bpo-25451: Add transparency methods to tkinter.PhotoImage
  Doc/whatsnew/3.8.rst
  Lib/tkinter/__init__.py
  Lib/tkinter/test/test_tkinter/test_images.py
  Misc/NEWS.d/next/Library/2018-11-07-23-44-25.bpo-25451.re_8db.rst
Labels: CLA signed, awaiting merge, type-enhancement

#12598 Fix doc for create_subprocess_exec
  Doc/library/asyncio-subprocess.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#12700 [3.7] Fix doc for create_subprocess_exec (GH-12598)
  Doc/library/asyncio-subprocess.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12688 bpo-36527: silence -Wunused-parameter warnings in object.h
  Include/object.h
Labels: CLA signed, awaiting changes, skip news

#12698 bpo-36050: optimize HTTPResponse.read()
  Lib/http/client.py
  Misc/NEWS.d/next/Library/2019-04-05-21-29-53.bpo-36050.x9DRKE.rst
Labels: CLA signed, awaiting core review, type-performance

#12677 bpo-9883: Remove names from the "unimplemented interfaces" list in the minidom docs that are actually implemented.
  Doc/library/xml.dom.minidom.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#12635 bpo-30661: Improve doc for tarfile pax change and effect on shutil
  Doc/library/shutil.rst
  Doc/library/tarfile.rst
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11659 bpo-35726: Add test for QueueHandler with multiple handlers
  Lib/test/test_logging.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#11787 bpo-35936: Updates to modulefinder
  Lib/modulefinder.py
  Lib/test/test_modulefinder.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-02-13-18-56-22.bpo-17396.oKRkrD.rst
  Misc/NEWS.d/next/Library/2019-02-13-18-56-27.bpo-35376.UFhYLj.rst
  Misc/NEWS.d/next/Library/2019-02-16-22-19-32.bpo-35936.Ay5WtD.rst
Labels: CLA signed, awaiting merge

#12638 bpo-27181: Add statistics.geometric_mean()
  Doc/library/statistics.rst
  Doc/whatsnew/3.8.rst
  Lib/statistics.py
  Lib/test/test_statistics.py
  Misc/NEWS.d/next/Library/2019-03-31-01-18-52.bpo-27181.LVUWcc.rst
Labels: CLA signed, awaiting core review, type-enhancement

#12658 bpo-36503: remove references to 'aix3' and 'aix4'
  Lib/test/test_fcntl.py
  Misc/ACKS
  Misc/NEWS.d/next/Build/2019-04-02-09-25-23.bpo-36503.0xzfkQ.rst
  setup.py
Labels: CLA signed, awaiting merge

#12712 [3.7] bpo-9883: Update list of unimplemented interfaces in minidom. (GH-12677)
  Doc/library/xml.dom.minidom.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#1270 bisect: Removed duplicate code
  Lib/bisect.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#10480 Correct "inplace" with "in-place"
  Doc/c-api/typeobj.rst
  Doc/library/operator.rst
Labels: CLA signed, awaiting core review, needs backport to 3.6, needs backport to 3.7, skip issue, skip news, type-documentation

#12721 [3.7] Correct "inplace" with "in-place" (GH-10480)
  Doc/c-api/typeobj.rst
  Doc/library/operator.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12706 Add a What's New entry for bpo-35459.
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#10918 bpo-35416: Fix potential resource warnings in distutils
  Lib/distutils/command/bdist_rpm.py
  Lib/distutils/command/bdist_wininst.py
  Lib/distutils/command/upload.py
  Misc/NEWS.d/next/Library/2018-12-05-09-55-05.bpo-35416.XALKZG.rst
Labels: CLA signed, awaiting merge

#11784 bpo-35934: Add socket.create_server() utility function
  Doc/library/socket.rst
  Doc/whatsnew/3.8.rst
  Lib/ftplib.py
  Lib/socket.py
  Lib/test/_test_multiprocessing.py
  Lib/test/eintrdata/eintr_tester.py
  Lib/test/test_asyncio/functional.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_streams.py
  Lib/test/test_epoll.py
  Lib/test/test_ftplib.py
  Lib/test/test_httplib.py
  Lib/test/test_kqueue.py
  Lib/test/test_socket.py
  Lib/test/test_ssl.py
  Lib/test/test_support.py
  Misc/NEWS.d/next/Library/2019-02-07-20-25-39.bpo-35934.QmfNmY.rst
Labels: CLA signed, awaiting merge, type-enhancement

#12733 bpo-36565: Fix libregrtest for Python without builtin _abc
  Lib/test/libregrtest/refleak.py
  Misc/NEWS.d/next/Tests/2019-04-08-19-01-21.bpo-36565.2bxgtU.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#12734 [3.7] bpo-36565: Fix libregrtest for Python without builtin _abc (GH-12733)
  Lib/test/libregrtest/refleak.py
  Misc/NEWS.d/next/Tests/2019-04-08-19-01-21.bpo-36565.2bxgtU.rst
Labels: CLA signed, awaiting merge

#12735 BPO-17561: set create_server backlog default to None
  Doc/library/socket.rst
  Lib/socket.py
  Misc/NEWS.d/next/Library/2019-04-09-04-08-46.bpo-17561.hOhVnh.rst
Labels: CLA signed, awaiting core review, skip issue

#11893 bpo-35848: Move all documentation regarding the readinto
  Doc/library/io.rst
  Lib/_pyio.py
Labels: CLA signed, awaiting review, needs backport to 3.7, skip news

#12736 [3.7] closes bpo-35848: Move all documentation regarding the readinto out of IOBase. (GH-11893)
  Doc/library/io.rst
  Lib/_pyio.py
Labels: CLA signed, awaiting merge, skip news

#1249 [2.7] bpo-30134: add an explanation of BytesWarning
  Doc/library/exceptions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12737 fix code styling
  Lib/distutils/command/bdist_wininst.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#12738 [2.7] bpo-30134: add BytesWarning in warnings.rst
  Doc/library/warnings.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#6762 bpo-33461: Emit DeprecationWarning when json.loads(encoding=...) is used
  Doc/library/json.rst
  Lib/json/__init__.py
  Lib/test/test_json/test_decode.py
  Misc/NEWS.d/next/Library/2019-04-09-14-46-28.bpo-33461.SYJM-E.rst
Labels: CLA signed, awaiting review

#6755 bpo-33456: site.py: fix wrong default for key in pyvenv.cfg
  Doc/library/site.rst
Labels: CLA signed, awaiting review, skip news

#8357 bpo-34060: Report system load when running test suite for Windows
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/win_utils.py
  Misc/NEWS.d/next/Windows/2018-07-20-13-09-19.bpo-34060.v-z87j.rst
Labels: CLA signed, awaiting change review

#12744 bpo-36560: Fix reference leak huting in regrtest
  Lib/test/libregrtest/refleak.py
  Lib/test/libregrtest/runtest.py
  Lib/test/libregrtest/setup.py
  Misc/NEWS.d/next/Tests/2019-04-09-14-08-02.bpo-36560._ejeOr.rst
Labels: CLA signed, awaiting core review

#12739 [2.7] bpo-30134: fix BytesWarning doc, docstring and message
  Doc/library/exceptions.rst
  Doc/library/warnings.rst
  Include/code.h
  Objects/bytearrayobject.c
  Objects/exceptions.c
  Python/pythonrun.c
Labels: CLA signed, awaiting core review, skip news

#12708 bpo-36544 : Fix regression introduced in bpo-36146
  Misc/NEWS.d/next/Build/2019-04-06-18-53-03.bpo-36544.hJr2_a.rst
  setup.py
Labels: :robot: automerge, CLA signed, awaiting merge

#12745 [2.7] bpo-36560: Fix reference leak hunting in regrtest (GH-12744)
  Lib/test/regrtest.py
  Misc/NEWS.d/next/Tests/2019-04-09-14-08-02.bpo-36560._ejeOr.rst
Labels: CLA signed, awaiting core review

#12661 bpo-36508: python-config don't export LINKFORSHARED
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2019-04-02-17-01-23.bpo-36508.SN5Y6N.rst
  Misc/python-config.in
  Misc/python-config.sh.in
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.7

#12747 bpo-36560: regrtest: don't collect the GC twice
  Lib/test/libregrtest/refleak.py
Labels: CLA signed, awaiting core review, skip news

#12746 bpo-36577: setup.py reports missing OpenSSL again
  Misc/NEWS.d/next/Build/2019-04-09-17-31-47.bpo-36577.34kuUW.rst
  setup.py
Labels: :robot: automerge, CLA signed, awaiting merge

#12749 [3.7] bpo-36560: regrtest: don't collect the GC twice (GH-12747)
  Lib/test/libregrtest/refleak.py
  Lib/test/libregrtest/runtest.py
  Lib/test/libregrtest/setup.py
  Misc/NEWS.d/next/Tests/2019-04-09-14-08-02.bpo-36560._ejeOr.rst
Labels: CLA signed, awaiting core review, skip news

#12726 bpo-34373: Fix time.mktime() on AIX
  Misc/NEWS.d/next/Library/2019-04-08-14-41-22.bpo-34373.lEAl_-.rst
  Modules/timemodule.c
  Python/pytime.c
Labels: CLA signed, awaiting core review

#12751 [2.7] bpo-36235: Fix distutils test_customize_compiler() on macOS
  Lib/distutils/tests/test_sysconfig.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#3652 bpo-31512: Add non-elevated symlink support for dev mode Windows 10
  Doc/library/os.rst
  Misc/NEWS.d/next/Windows/2017-10-04-12-40-45.bpo-31512.YQeBt2.rst
  Modules/posixmodule.c
  Modules/winreparse.h
Labels: CLA signed, awaiting merge

#12752 Fix typos in compile.c comments
  Python/compile.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#2568 bpo-12910: update and correct quote docstring
  Lib/urllib/parse.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#12754 [3.7] bpo-12910: update and correct quote docstring (GH-2568)
  Lib/urllib/parse.py
Labels: CLA signed, awaiting merge, skip news

#12758 bpo-14826: document that URLopener quotes fullurl.
  Doc/library/urllib.request.rst
Labels: CLA signed, awaiting core review, needs backport to 3.6, needs backport to 3.7, skip news, type-documentation

#12759 [3.7] bpo-14826: document that URLopener quotes fullurl. (GH-12758)
  Doc/library/urllib.request.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#8321 bpo-34144: Fix of venv acvtivate.bat for win 10
  Lib/venv/scripts/nt/activate.bat
  Misc/NEWS.d/next/Windows/2019-04-10-04-35-31.bpo-34144._KzB5z.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#12742 bpo-36559: random module: optimize sha512 import
  Lib/random.py
  Misc/NEWS.d/next/Library/2019-04-09-12-02-35.bpo-36559.LbDRrw.rst
Labels: CLA signed, awaiting core review

#12686 Fix tense build to built
  Doc/extending/building.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip issue, skip news, type-documentation

#12764 bpo-36235: Fix distutils test_customize_compiler() on macOS
  Lib/distutils/tests/test_sysconfig.py
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news, type-tests

#12768 [3.7] bpo-36235: Fix distutils test_customize_compiler() on macOS (GH-12764)
  Lib/distutils/tests/test_sysconfig.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#12724 Fix typo in IncrementalDecoder documentation: encoder -> decoder
  Doc/library/codecs.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip issue, skip news, type-documentation

#12763 better __init__.py explanation in tutorial
  Doc/tutorial/modules.rst
Labels: CLA signed, awaiting changes, needs backport to 3.7, skip issue, skip news, type-documentation

#12773 [3.7] better __init__.py explanation in tutorial (GH-12763)
  Doc/tutorial/modules.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12772 [3.7] Doc: fix typo in IncrementalDecoder.setstate (GH-12724)
  Doc/library/codecs.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12543 bpo-36416: Correct bytes.rpartition documentation
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12775 bpo-36597: Disable Travis CI doctest job
  .travis.yml
Labels: CLA signed, awaiting core review, skip news

#12776 bpo-36597: fix random doctest failure
  .travis.yml
  Doc/library/weakref.rst
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#12770 bpo-36389: _PyObject_IsFreed() now also detects uninitialized memory
  Include/internal/pycore_pymem.h
  Include/pymem.h
  Lib/test/test_capi.py
  Modules/_testcapimodule.c
  Objects/object.c
  Objects/obmalloc.c
Labels: CLA signed, awaiting core review, skip news

#12779 bpo-36597: fix weakref example code
  Doc/library/weakref.rst
Labels: CLA signed, skip news, type-documentation

#8378 bpo-36575: lsprof: Use _PyTime_GetPerfCounter()
  Misc/NEWS.d/next/Library/2019-04-09-22-40-52.bpo-36575.Vg_p92.rst
  Modules/_lsprof.c
Labels: CLA signed, awaiting merge, type-enhancement

#12781 [3.7] bpo-36416: Correct bytes.rpartition documentation (GH-12543)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12778 [3.7] bpo-36597: fix random doctest failure
  Doc/library/weakref.rst
Labels: CLA signed, skip news, type-bugfix, type-documentation

#12782 bpo-36389: Change PyMem_SetupDebugHooks() constants
  Doc/c-api/memory.rst
  Include/internal/pycore_pymem.h
  Lib/test/test_capi.py
  Misc/NEWS.d/next/C API/2019-04-11-12-20-35.bpo-36389.P9QFoP.rst
  Objects/object.c
  Objects/obmalloc.c
Labels: CLA signed, awaiting core review

#12789 bpo-36605: make tags: parse Modules/_io directory
  Misc/NEWS.d/next/Build/2019-04-11-18-50-58.bpo-36605.gk5czf.rst
  configure
  configure.ac
Labels: CLA signed, needs backport to 3.7, skip news

#12788 [3.7] bpo-36389: _PyObject_IsFreed() now also detects uninitialized memory (GH-12770)
  Doc/c-api/memory.rst
  Include/internal/mem.h
  Include/pymem.h
  Lib/test/test_capi.py
  Misc/NEWS.d/next/C API/2019-04-11-12-20-35.bpo-36389.P9QFoP.rst
  Modules/_testcapimodule.c
  Objects/object.c
  Objects/obmalloc.c
Labels: CLA signed, awaiting core review, skip news

#11977 bpo-20582: add link for manpage for flags on getnameinfo()
  Doc/library/socket.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#12793 [3.7] bpo-34839: Add a 'before 3.6' in the section 'warnings' of doctest (GH-9736)
  Doc/library/doctest.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12792 bpo-20180: Use argument clinic for dict.pop() and dict.popitem()
  Misc/NEWS.d/next/Core and Builtins/2019-04-12-15-49-15.bpo-20180.KUqVk7.rst
  Objects/clinic/dictobject.c.h
  Objects/dictobject.c
Labels: CLA signed, awaiting core review

#12797 bpo-36611: Fix test_sys.test_getallocatedblocks()
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Tests/2019-04-12-12-44-42.bpo-36611.UtorXL.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, type-tests

#12801 [3.7] bpo-36611: Fix test_sys.test_getallocatedblocks() (GH-12797)
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Tests/2019-04-12-12-44-42.bpo-36611.UtorXL.rst
Labels: CLA signed, awaiting merge, type-tests

#12787 bpo-36588: For AIX remove major version from sys.platform
  Doc/library/sys.rst
  Doc/whatsnew/3.8.rst
  Misc/NEWS.d/next/Core and Builtins/2019-04-11-14-36-55.bpo-36588.wejLoC.rst
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#12786 bpo-18748: io.IOBase destructor now logs close() errors in dev mode
  Doc/using/cmdline.rst
  Lib/test/test_io.py
  Misc/NEWS.d/next/Library/2019-04-11-16-09-42.bpo-18748.QW7upB.rst
  Modules/_io/iobase.c
Labels: CLA signed, awaiting merge

#12360 bpo-33608: Factor out a private, per-interpreter _Py_AddPendingCall().
  Include/ceval.h
  Include/internal/pycore_ceval.h
  Include/internal/pycore_pystate.h
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2018-09-15-12-13-46.bpo-33608.avmvVP.rst
  Modules/_testcapimodule.c
  Modules/signalmodule.c
  Python/ceval.c
  Python/ceval_gil.h
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting merge

#12804 bpo-36549: str.capitalize now titlecases the first character instead of uppercasing it
  Doc/library/stdtypes.rst
  Lib/test/string_tests.py
  Lib/test/test_unicode.py
  Misc/NEWS.d/next/Core and Builtins/2019-04-11-12-41-31.bpo-36549.QSp8of.rst
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge

#11216 Remove misleading sentence
  Doc/library/io.rst
Labels: CLA signed, awaiting change review, needs backport to 2.7, needs backport to 3.7, skip issue, skip news, type-documentation

#12799 [2.7] bpo-34652: Remove lchmod from the big func checking block. (GH-9247)
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA not signed, awaiting review, skip news

#12761 fix grammar in concurrent/futures/process.py docstring
  Lib/concurrent/futures/process.py
Labels: CLA not signed, awaiting core review, skip issue, skip news

#12806 bpo-33608: Revert "Factor out a private, per-interpreter _Py_AddPendingCall()."
  Include/ceval.h
  Include/internal/pycore_ceval.h
  Include/internal/pycore_pystate.h
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2018-09-15-12-13-46.bpo-33608.avmvVP.rst
  Modules/_testcapimodule.c
  Modules/signalmodule.c
  Python/ceval.c
  Python/ceval_gil.h
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting core review, skip news

#12669 bpo-36513: Enable building cpython nuget package for arm32
  Tools/nuget/build.bat
  Tools/nuget/make_pkg.proj
  Tools/nuget/pythonarm32.nuspec
Labels: CLA signed, awaiting review, skip news

#12663 bpo-36509: Add iot layout for windows iot containers
  Misc/NEWS.d/next/Windows/2019-04-02-10-11-18.bpo-36509.DdaM67.rst
  PC/layout/main.py
  PC/layout/support/options.py
Labels: CLA signed, awaiting review

#12808 Allow builds to fully skip code signing
  Tools/msi/make_cat.ps1
  Tools/msi/sdktools.psm1
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.7, skip issue, skip news

#12810 [3.7] Allow Windows layout builds to fully skip code signing (GH-12808)
  Tools/msi/make_cat.ps1
  Tools/msi/sdktools.psm1
Labels: CLA signed, awaiting merge, skip issue, skip news

#12809 bpo-36618: Add -fmax-type-align=8 flag for clang
  Misc/NEWS.d/next/Build/2019-04-12-19-49-10.bpo-36618.gcI9iq.rst
  configure
  configure.ac
Labels: CLA signed, awaiting core review

#12803 bpo-36389: Add _PyObject_CheckConsistency() function
  Include/cpython/object.h
  Include/internal/pycore_object.h
  Objects/dictobject.c
  Objects/object.c
  Objects/typeobject.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting core review, skip news

#12796 bpo-36611: Disable serialno field of debug memory allocators
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2019-04-12-12-32-39.bpo-36611.zbo9WQ.rst
  Objects/obmalloc.c
Labels: CLA signed, awaiting merge

#12805 bpo-18748: test_io: silence destructor errors
  Lib/test/test_io.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#7849 bpo-33922: Adding documentation for new "-64" suffix of python launcher
  Doc/using/windows.rst
  Misc/ACKS
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news

#12812 [3.7] bpo-33922: Adding documentation for new "-64" suffix of Python launcher (GH-7849)
  Doc/using/windows.rst
  Misc/ACKS
Labels: CLA signed, awaiting merge, skip news

#11312 bpo-35581: Document @typing.type_check_only
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2018-12-25-12-56-57.bpo-35581.aA7r6T.rst
Labels: CLA signed, awaiting merge, type-documentation

#12813 [3.7] bpo-35581: Document @typing.type_check_only (GH-11312)
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2018-12-25-12-56-57.bpo-35581.aA7r6T.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#12811 bpo-36618: Don't add -fmax-type-align flag to old clang
  Misc/NEWS.d/next/Build/2019-04-12-19-49-10.bpo-36618.gcI9iq.rst
  configure
  configure.ac
Labels: CLA signed, awaiting core review

#12815 [2.7] bpo-36605: make tags: parse Modules/_io directory (GH-12789)
  Misc/NEWS.d/next/Build/2019-04-11-18-50-58.bpo-36605.gk5czf.rst
  configure
  configure.ac
Labels: CLA signed, awaiting core review, skip news

#12814 [3.7] bpo-36605: make tags: parse Modules/_io directory (GH-12789)
  Misc/NEWS.d/next/Build/2019-04-11-18-50-58.bpo-36605.gk5czf.rst
  configure
  configure.ac
Labels: CLA signed, awaiting core review, skip news

#12794 Doc: define PY_SSIZE_T_CLEAN always
  Doc/c-api/intro.rst
  Doc/extending/embedding.rst
  Doc/extending/extending.rst
  Doc/faq/extending.rst
  Doc/includes/custom.c
  Doc/includes/custom2.c
  Doc/includes/custom3.c
  Doc/includes/custom4.c
  Doc/includes/run-func.c
  Doc/includes/sublist.c
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip issue, skip news, type-documentation

#12816 [3.7] Doc: define PY_SSIZE_T_CLEAN always (GH-12794)
  Doc/c-api/intro.rst
  Doc/extending/embedding.rst
  Doc/extending/extending.rst
  Doc/faq/extending.rst
  Doc/includes/custom.c
  Doc/includes/custom2.c
  Doc/includes/custom3.c
  Doc/includes/custom4.c
  Doc/includes/run-func.c
  Doc/includes/sublist.c
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#11591 bpo-35734: remove unused methods in ipaddress
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
Labels: CLA signed, awaiting core review, skip news

#11663 bpo-18610: Update wsgiref.validate docstring for wsgi.input read()
  Lib/wsgiref/validate.py
Labels: CLA signed, awaiting review, skip news

#12253 bpo-36623: Clean parser headers and include files
  Doc/whatsnew/3.8.rst
  Include/bitset.h
  Include/grammar.h
  Include/pgenheaders.h
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2019-04-13-02-08-44.bpo-36623.HR_xhB.rst
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Parser/acceler.c
  Parser/grammar1.c
  Parser/listnode.c
  Parser/parser.c
  Parser/parser.h
  Parser/parsetok.c
  Parser/pgen/grammar.py
  Parser/tokenizer.c
  Parser/tokenizer.h
  Python/graminit.c
  Python/strdup.c
Labels: CLA signed, awaiting merge

#12762 bpo-36585: Skip test_preadv_flags if RWF_HIPRI is not supported by the system
  Lib/test/test_posix.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#12541 bpo-36427: Document that PyEval_RestoreThread and PyGILState_Ensure can terminate the calling thread
  Doc/c-api/init.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#12819 [3.7] bpo-36585: Skip test_preadv_flags if RWF_HIPRI is not supported by the system (GH-12762)
  Lib/test/test_posix.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#12790 bpo-36593: Fix isinstance check for Mock objects with spec executed under tracing
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2019-04-11-22-11-24.bpo-36598.hfzDUl.rst
Labels: CLA signed, awaiting merge

#12821 [3.7] bpo-36593: Fix isinstance check for Mock objects with spec executed under tracing (GH-12790)
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2019-04-11-22-11-24.bpo-36598.hfzDUl.rst
Labels: CLA signed, awaiting merge

#12820 [3.7] bpo-36427: Document that PyEval_RestoreThread and PyGILState_Ensure can terminate the calling thread (GH-12541)
  Doc/c-api/init.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#12225 bpo-36227: ElementTree.tostring() default_namespace argument
  Doc/library/xml.etree.elementtree.rst
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2019-03-07-20-02-18.bpo-36227.i2Z1XR.rst
Labels: CLA signed, awaiting merge

#1823 bpo-30485: support a default prefix mapping in ElementPath
  Doc/library/xml.etree.elementtree.rst
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementPath.py
  Misc/NEWS.d/next/Library/2019-04-13-23-42-33.bpo-30485.JHhjJS.rst
Labels: CLA signed, awaiting review, type-enhancement

#8564 bpo-31658: Make xml.sax.parse accepting Path objects
  Doc/library/xml.sax.reader.rst
  Lib/test/test_sax.py
  Lib/xml/sax/saxutils.py
  Misc/NEWS.d/next/Library/2018-07-30-12-00-15.bpo-31658._bx7a_.rst
Labels: CLA signed

#12827 bpo-16079: fix duplicate test method name in test_gzip.
  Lib/test/test_gzip.py
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip news, type-tests

#12828 [3.7] bpo-16079: fix duplicate test method name in test_gzip. (GH-12827)
  Lib/test/test_gzip.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#12830 bpo-30485: Re-allow empty strings in ElementPath namespace mappings
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementPath.py
Labels: CLA signed, skip news

#12832 bpo-27860: ipaddress: use cached_property
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
Labels: CLA signed, awaiting core review, skip news

#12833 bpo-31904: remove _crypt extension for VxWorks RTOS
  Doc/library/crypt.rst
  Misc/NEWS.d/next/Build/2019-04-15-15-01-29.bpo-31904.38fdkg.rst
  setup.py
Labels: CLA signed, awaiting review

#12305 bpo-31904: Add time module support for VxWorks RTOS
  Doc/library/time.rst
  Lib/test/test_time.py
  Misc/NEWS.d/next/Library/2019-03-13-16-48-42.bpo-31904.9sjd38.rst
  Modules/timemodule.c
Labels: CLA signed, awaiting review

#12834 bpo-36629: Add support.get_socket_conn_refused_errs()
  Lib/test/support/__init__.py
  Lib/test/test_imaplib.py
  Lib/test/test_socket.py
  Misc/NEWS.d/next/Tests/2019-04-15-11-57-39.bpo-36629.ySnaL3.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7

#12835 [3.7] bpo-36629: Add support.get_socket_conn_refused_errs() (GH-12834)
  Lib/test/support/__init__.py
  Lib/test/test_imaplib.py
  Lib/test/test_socket.py
  Misc/NEWS.d/next/Tests/2019-04-15-11-57-39.bpo-36629.ySnaL3.rst
Labels: CLA signed, awaiting review

#12822 bpo-36625: Remove obsolete comments from docstrings in fractions module
  Lib/fractions.py
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2019-04-15-12-02-45.bpo-36625.x3LMCF.rst
Labels: CLA signed, awaiting merge

#12837 bpo-36404: update PendingDeprecationWarning explanation
  Doc/library/exceptions.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation
