Repository python/cpython, pull requests merged in 2019-07, with the labels that each got.

#14485 bpo-36168: Lowercase the word "subsequent" in get_value doc
  Doc/library/string.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#14421 bpo-37428: Don't set PHA verify flag on client side
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2019-06-27-13-27-02.bpo-37428._wcwUd.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, needs backport to 3.8, type-bugfix

#14448 bpo-37440: Enable TLS 1.3 post-handshake auth in http.client
  Doc/library/http.client.rst
  Lib/http/client.py
  Lib/test/test_httplib.py
  Misc/NEWS.d/next/Library/2019-06-28-16-40-17.bpo-37440.t3wX-N.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, needs backport to 3.8, type-bugfix

#14493 [3.7] bpo-37428: Don't set PHA verify flag on client side (GH-14421)
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2019-06-27-13-27-02.bpo-37428._wcwUd.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#14495 [3.8] bpo-37440: Enable TLS 1.3 post-handshake auth in http.client (GH-14448)
  Doc/library/http.client.rst
  Lib/http/client.py
  Lib/test/test_httplib.py
  Misc/NEWS.d/next/Library/2019-06-28-16-40-17.bpo-37440.t3wX-N.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#14496 [3.7] bpo-37440: Enable TLS 1.3 post-handshake auth in http.client (GH-14448)
  Doc/library/http.client.rst
  Lib/http/client.py
  Lib/test/test_httplib.py
  Misc/NEWS.d/next/Library/2019-06-28-16-40-17.bpo-37440.t3wX-N.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#14494 [3.8] bpo-37428: Don't set PHA verify flag on client side (GH-14494)
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2019-06-27-13-27-02.bpo-37428._wcwUd.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, type-bugfix

#14501 Minor updates to the macOS installer screens for 3.8.0b2
  Mac/BuildScript/resources/ReadMe.rtf
  Mac/BuildScript/resources/Welcome.rtf
Labels: CLA signed, OS-mac, awaiting core review, skip issue, skip news, type-documentation

#13959 bpo-37221: Add PyCode_NewWithPosOnlyArgs to be used internally and set PyCode_New as a compatibility wrapper
  Doc/c-api/code.rst
  Doc/data/refcounts.dat
  Doc/whatsnew/3.8.rst
  Include/code.h
  Misc/NEWS.d/next/C API/2019-06-11-02-50-38.bpo-37221.4tClQT.rst
  Objects/codeobject.c
  Python/compile.c
  Python/marshal.c
Labels: CLA signed, awaiting merge

#14505 [3.8] bpo-37221: Add PyCode_NewWithPosOnlyArgs to be used internally and set PyCode_New as a compatibility wrapper (GH-13959)
  Doc/c-api/code.rst
  Doc/data/refcounts.dat
  Doc/whatsnew/3.8.rst
  Include/code.h
  Misc/NEWS.d/next/C API/2019-06-11-02-50-38.bpo-37221.4tClQT.rst
  Objects/codeobject.c
  Python/compile.c
  Python/marshal.c
Labels: CLA signed, awaiting review

#14498 bpo-32934: Clarified meaning of 'capacity' for BufferingHandler and M…
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#14508 [3.7] bpo-32934: Clarified meaning of 'capacity' for BufferingHandler and MemoryHandler. (GH-14498)
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14507 [3.8] bpo-32934: Clarified meaning of 'capacity' for BufferingHandler and MemoryHandler. (GH-14498)
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14506 bpo-10945: Drop support for bdist_wininst on non-Windows systems
  Doc/distutils/builtdist.rst
  Lib/distutils/command/bdist_wininst.py
  Misc/NEWS.d/next/Windows/2019-07-01-12-38-48.bpo-10945.s0YBHG.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#14509 [3.7] bpo-10945: Drop support for bdist_wininst on non-Windows systems (GH-14506)
  Doc/distutils/builtdist.rst
  Lib/distutils/command/bdist_wininst.py
  Misc/NEWS.d/next/Windows/2019-07-01-12-38-48.bpo-10945.s0YBHG.rst
Labels: CLA signed, awaiting merge

#14510 [3.8] bpo-10945: Drop support for bdist_wininst on non-Windows systems (GH-14506)
  Doc/distutils/builtdist.rst
  Lib/distutils/command/bdist_wininst.py
  Misc/NEWS.d/next/Windows/2019-07-01-12-38-48.bpo-10945.s0YBHG.rst
Labels: CLA signed, awaiting merge

#14503 bpo-37209: Add pickle entry for 3.8 whatsnew
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip news, type-documentation

#14512 [3.8] bpo-37209: Add pickle entry for 3.8 whatsnew (GH-14503)
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14504 bpo-37467: Fix PyErr_Display() for bytes filename
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2019-07-01-12-22-44.bpo-37467.u-XyEu.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8

#14514 [3.8] bpo-37467: Fix PyErr_Display() for bytes filename (GH-14504)
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2019-07-01-12-22-44.bpo-37467.u-XyEu.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting merge

#14515 [3.7] bpo-37467: Fix PyErr_Display() for bytes filename (GH-14504)
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2019-07-01-12-22-44.bpo-37467.u-XyEu.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting core review

#14518 Remove unused imports
  Lib/test/libregrtest/main.py
  Lib/test/support/__init__.py
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_argparse.py
  Lib/test/test_asynchat.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_pep492.py
  Lib/test/test_asyncio/test_proactor_events.py
  Lib/test/test_asyncio/test_server.py
  Lib/test/test_asyncio/test_sslproto.py
  Lib/test/test_asyncio/test_unix_events.py
  Lib/test/test_asyncio/test_windows_events.py
  Lib/test/test_audit.py
  Lib/test/test_c_locale_coercion.py
  Lib/test/test_capi.py
  Lib/test/test_cgi.py
  Lib/test/test_cmath.py
  Lib/test/test_cmd_line.py
  Lib/test/test_codeccallbacks.py
  Lib/test/test_codecs.py
  Lib/test/test_collections.py
  Lib/test/test_cprofile.py
  Lib/test/test_docxmlrpc.py
  Lib/test/test_email/test_policy.py
  Lib/test/test_embed.py
  Lib/test/test_exceptions.py
  Lib/test/test_faulthandler.py
  Lib/test/test_fork1.py
  Lib/test/test_generators.py
  Lib/test/test_gettext.py
  Lib/test/test_imaplib.py
  Lib/test/test_import/__init__.py
  Lib/test/test_importlib/test_util.py
  Lib/test/test_locale.py
  Lib/test/test_math.py
  Lib/test/test_os.py
  Lib/test/test_peepholer.py
  Lib/test/test_picklebuffer.py
  Lib/test/test_platform.py
  Lib/test/test_posixpath.py
  Lib/test/test_pyclbr.py
  Lib/test/test_pydoc.py
  Lib/test/test_runpy.py
  Lib/test/test_signal.py
  Lib/test/test_smtplib.py
  Lib/test/test_ssl.py
  Lib/test/test_string_literals.py
  Lib/test/test_subprocess.py
  Lib/test/test_sys.py
  Lib/test/test_tabnanny.py
  Lib/test/test_threaded_import.py
  Lib/test/test_threadedtempfile.py
  Lib/test/test_zipfile.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#14519 [3.8] bpo-36168: Lowercase the word "subsequent" in get_value doc (GH-14485)
  Doc/library/string.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14516 bpo-37472: Remove Lib/test/outstanding_bugs.py
  Lib/test/outstanding_bugs.py
  Misc/NEWS.d/next/Tests/2019-07-01-17-19-47.bpo-37472.WzkEAx.rst
  PCbuild/lib.pyproj
Labels: CLA signed, awaiting merge

#14520 [3.8] Remove unused imports in tests (GH-14518)
  Lib/test/libregrtest/main.py
  Lib/test/support/__init__.py
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_argparse.py
  Lib/test/test_asynchat.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_pep492.py
  Lib/test/test_asyncio/test_proactor_events.py
  Lib/test/test_asyncio/test_server.py
  Lib/test/test_asyncio/test_sslproto.py
  Lib/test/test_asyncio/test_unix_events.py
  Lib/test/test_asyncio/test_windows_events.py
  Lib/test/test_audit.py
  Lib/test/test_c_locale_coercion.py
  Lib/test/test_capi.py
  Lib/test/test_cgi.py
  Lib/test/test_cmath.py
  Lib/test/test_cmd_line.py
  Lib/test/test_codeccallbacks.py
  Lib/test/test_codecs.py
  Lib/test/test_collections.py
  Lib/test/test_cprofile.py
  Lib/test/test_docxmlrpc.py
  Lib/test/test_email/test_policy.py
  Lib/test/test_embed.py
  Lib/test/test_exceptions.py
  Lib/test/test_faulthandler.py
  Lib/test/test_fork1.py
  Lib/test/test_generators.py
  Lib/test/test_gettext.py
  Lib/test/test_imaplib.py
  Lib/test/test_import/__init__.py
  Lib/test/test_importlib/test_util.py
  Lib/test/test_locale.py
  Lib/test/test_math.py
  Lib/test/test_os.py
  Lib/test/test_peepholer.py
  Lib/test/test_picklebuffer.py
  Lib/test/test_platform.py
  Lib/test/test_posixpath.py
  Lib/test/test_pyclbr.py
  Lib/test/test_pydoc.py
  Lib/test/test_runpy.py
  Lib/test/test_signal.py
  Lib/test/test_smtplib.py
  Lib/test/test_ssl.py
  Lib/test/test_string_literals.py
  Lib/test/test_subprocess.py
  Lib/test/test_sys.py
  Lib/test/test_tabnanny.py
  Lib/test/test_threaded_import.py
  Lib/test/test_threadedtempfile.py
  Lib/test/test_zipfile.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#14444 bpo-36763: Add PyConfig_SetWideStringList()
  Doc/c-api/init_config.rst
  Include/cpython/initconfig.h
  Misc/NEWS.d/next/C API/2019-06-28-15-49-16.bpo-36763.zrmgki.rst
  Python/initconfig.c
Labels: CLA signed, awaiting core review

#14523 [3.8] bpo-36763: Add PyConfig_SetWideStringList() (GH-14444)
  Doc/c-api/init_config.rst
  Include/cpython/initconfig.h
  Misc/NEWS.d/next/C API/2019-06-28-15-49-16.bpo-36763.zrmgki.rst
  Python/initconfig.c
Labels: CLA signed, awaiting merge

#14521 bpo-37469: Document usability of SimpleQueue with QueueHandler and Qu…
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#14445 bpo-36763: Use PyConfig_Clear()
  Lib/test/test_embed.py
  Modules/main.c
  Programs/_freeze_importlib.c
  Programs/_testembed.c
Labels: CLA signed, awaiting core review, skip news

#14522 [3.7] Remove unused imports in tests (GH-14518)
  Lib/test/libregrtest/main.py
  Lib/test/support/__init__.py
  Lib/test/test_aifc.py
  Lib/test/test_argparse.py
  Lib/test/test_asynchat.py
  Lib/test/test_asyncio/test_pep492.py
  Lib/test/test_asyncio/test_sslproto.py
  Lib/test/test_asyncio/test_unix_events.py
  Lib/test/test_c_locale_coercion.py
  Lib/test/test_capi.py
  Lib/test/test_cmd_line.py
  Lib/test/test_collections.py
  Lib/test/test_contextlib.py
  Lib/test/test_coroutines.py
  Lib/test/test_docxmlrpc.py
  Lib/test/test_email/test_policy.py
  Lib/test/test_exceptions.py
  Lib/test/test_faulthandler.py
  Lib/test/test_fork1.py
  Lib/test/test_frozen.py
  Lib/test/test_gdb.py
  Lib/test/test_generators.py
  Lib/test/test_gettext.py
  Lib/test/test_grammar.py
  Lib/test/test_imaplib.py
  Lib/test/test_import/__init__.py
  Lib/test/test_importlib/test_locks.py
  Lib/test/test_locale.py
  Lib/test/test_netrc.py
  Lib/test/test_os.py
  Lib/test/test_posixpath.py
  Lib/test/test_pyclbr.py
  Lib/test/test_pydoc.py
  Lib/test/test_queue.py
  Lib/test/test_resource.py
  Lib/test/test_runpy.py
  Lib/test/test_sax.py
  Lib/test/test_signal.py
  Lib/test/test_smtplib.py
  Lib/test/test_subprocess.py
  Lib/test/test_thread.py
  Lib/test/test_threaded_import.py
  Lib/test/test_threadedtempfile.py
  Lib/test/test_time.py
  Lib/test/test_tokenize.py
  Lib/test/test_traceback.py
  Lib/test/test_utf8_mode.py
  Lib/test/test_venv.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#14528 [3.8] bpo-36763: Use PyConfig_Clear() (GH-14445)
  Lib/test/test_embed.py
  Modules/main.c
  Programs/_freeze_importlib.c
  Programs/_testembed.c
Labels: CLA signed, awaiting merge, skip news

#14526 [3.7] bpo-37469: Document usability of SimpleQueue with QueueHandler and QueueListener. (GH-14521)
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14525 [3.8] bpo-37469: Document usability of SimpleQueue with QueueHandler and QueueListener. (GH-14521)
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14532 bpo-37470: Document more clearly the error handling for QueueHandler.…
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#14534 [3.7] bpo-37470: Document more clearly the error handling for QueueHandler.emit(). (GH-14532)
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14533 [3.8] bpo-37470: Document more clearly the error handling for QueueHandler.emit(). (GH-14532)
  Doc/library/logging.handlers.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14524 bpo-37363: Add audit events on startup for the run commands
  Doc/library/sys.rst
  Doc/tools/extensions/pyspecific.py
  Doc/using/cmdline.rst
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Security/2019-07-01-10-31-14.bpo-37363.fSjatj.rst
  Modules/main.c
  Programs/_testembed.c
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.8

#14257 [2.7] bpo-19960: Fix building of zlib on macOS without installed headers
  Misc/NEWS.d/next/macOS/2019-06-20-01-16-16.bpo-19960.LpLUPF.rst
  setup.py
Labels: CLA signed, OS-mac, awaiting core review

#14536 [3.8] bpo-37363: Add audit events on startup for the run commands (GH-14524)
  Doc/library/sys.rst
  Doc/tools/extensions/pyspecific.py
  Doc/using/cmdline.rst
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Security/2019-07-01-10-31-14.bpo-37363.fSjatj.rst
  Modules/main.c
  Programs/_testembed.c
Labels: CLA signed, awaiting merge

#14539 Put pyexpatns.h include back. bpo-37437
  Modules/expat/expat_external.h
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, skip news

#14540 [3.8] Put pyexpatns.h include back. bpo-37437 (GH-14539)
  Modules/expat/expat_external.h
Labels: CLA signed, awaiting merge, skip news

#14541 [3.7] Put pyexpatns.h include back. bpo-37437 (GH-14539)
  Modules/expat/expat_external.h
Labels: CLA signed, awaiting merge, skip news

#14544 [2.7] Put pyexpatns.h include back. bpo-37437 (GH-14539)
  Modules/expat/expat_external.h
Labels: CLA signed, awaiting merge, skip news

#14542 [3.6] Put pyexpatns.h include back. bpo-37437 (GH-14539)
  Modules/expat/expat_external.h
Labels: CLA signed, awaiting review, skip news

#14546 bpo-34602: Avoid failures setting macOS stack resource limit
  Lib/test/libregrtest/setup.py
  Misc/NEWS.d/next/macOS/2019-07-02-01-06-47.bpo-34602.10d4wl.rst
  configure
  configure.ac
Labels: CLA signed, OS-mac, awaiting core review, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8

#14547 [3.8] bpo-34602: Avoid failures setting macOS stack resource limit (GH-14546)
  Lib/test/libregrtest/setup.py
  Misc/NEWS.d/next/macOS/2019-07-02-01-06-47.bpo-34602.10d4wl.rst
  configure
  configure.ac
Labels: :robot: automerge, CLA signed, awaiting merge

#14548 [3.7] bpo-34602: Avoid failures setting macOS stack resource limit (GH-14546)
  Lib/test/libregrtest/setup.py
  Misc/NEWS.d/next/macOS/2019-07-02-01-06-47.bpo-34602.10d4wl.rst
  configure
  configure.ac
Labels: :robot: automerge, CLA signed, awaiting merge

#14549 [3.6] bpo-34602: Avoid failures setting macOS stack resource limit (GH-14546)
  Lib/test/libregrtest/setup.py
  Misc/NEWS.d/next/macOS/2019-07-02-01-06-47.bpo-34602.10d4wl.rst
  configure
  configure.ac
Labels: :robot: automerge, CLA signed, awaiting merge

#14517 bpo-36904: Optimize _PyStack_UnpackDict
  Include/cpython/abstract.h
  Objects/call.c
Labels: CLA signed, awaiting merge, skip news

#14449 [3.7] bpo-37335: Fix unexpected ASCII aliases in locale coercion tests
  Lib/test/test_c_locale_coercion.py
  Misc/NEWS.d/next/Tests/2019-06-28-16-54-46.bpo-37335.LLzOx8.rst
Labels: CLA signed, awaiting review, type-tests

#14447 bpo-37335: Remove unnecessary code from c locale coercion tests
  Lib/test/test_c_locale_coercion.py
  Misc/NEWS.d/next/Tests/2019-06-28-16-37-52.bpo-37335.o5S2hY.rst
Labels: CLA signed, awaiting review, type-tests

#14552 [3.8] bpo-37335, test_c_locale_coercion: Remove unnecessary code (GH-14447)
  Lib/test/test_c_locale_coercion.py
  Misc/NEWS.d/next/Tests/2019-06-28-16-37-52.bpo-37335.o5S2hY.rst
Labels: CLA signed, awaiting merge, type-tests

#14527 bpo-37421: _test_multiprocessing calls _run_finalizers()
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2019-07-01-19-57-26.bpo-37421.NFH1f0.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8

#13935 [3.8] bpo-37206: fix docstring of dict.pop()
  Objects/clinic/dictobject.c.h
  Objects/dictobject.c
Labels: CLA signed, awaiting core review, skip news

#14554 [3.8] bpo-37421: multiprocessing tests call _run_finalizers() (GH-14527)
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2019-07-01-19-57-26.bpo-37421.NFH1f0.rst
Labels: CLA signed, awaiting merge

#14555 [3.7] Revert "[3.7] Remove unused imports in tests (GH-14518)"
  Lib/test/libregrtest/main.py
  Lib/test/support/__init__.py
  Lib/test/test_aifc.py
  Lib/test/test_argparse.py
  Lib/test/test_asynchat.py
  Lib/test/test_asyncio/test_pep492.py
  Lib/test/test_asyncio/test_sslproto.py
  Lib/test/test_asyncio/test_unix_events.py
  Lib/test/test_c_locale_coercion.py
  Lib/test/test_capi.py
  Lib/test/test_cmd_line.py
  Lib/test/test_collections.py
  Lib/test/test_contextlib.py
  Lib/test/test_coroutines.py
  Lib/test/test_docxmlrpc.py
  Lib/test/test_email/test_policy.py
  Lib/test/test_exceptions.py
  Lib/test/test_faulthandler.py
  Lib/test/test_fork1.py
  Lib/test/test_frozen.py
  Lib/test/test_gdb.py
  Lib/test/test_generators.py
  Lib/test/test_gettext.py
  Lib/test/test_grammar.py
  Lib/test/test_imaplib.py
  Lib/test/test_import/__init__.py
  Lib/test/test_importlib/test_locks.py
  Lib/test/test_locale.py
  Lib/test/test_netrc.py
  Lib/test/test_os.py
  Lib/test/test_posixpath.py
  Lib/test/test_pyclbr.py
  Lib/test/test_pydoc.py
  Lib/test/test_queue.py
  Lib/test/test_resource.py
  Lib/test/test_runpy.py
  Lib/test/test_sax.py
  Lib/test/test_signal.py
  Lib/test/test_smtplib.py
  Lib/test/test_subprocess.py
  Lib/test/test_thread.py
  Lib/test/test_threaded_import.py
  Lib/test/test_threadedtempfile.py
  Lib/test/test_time.py
  Lib/test/test_tokenize.py
  Lib/test/test_traceback.py
  Lib/test/test_utf8_mode.py
  Lib/test/test_venv.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#14529 bpo-37421: test_urllib calls urlcleanup()
  Lib/test/libregrtest/save_env.py
  Lib/test/test_robotparser.py
  Lib/test/test_sax.py
  Lib/test/test_urllib.py
  Lib/test/test_urllib2.py
  Lib/test/test_urllib2_localnet.py
  Lib/test/test_urllib2net.py
  Lib/test/test_urllibnet.py
  Misc/NEWS.d/next/Tests/2019-07-01-19-56-17.bpo-37421.bOe350.rst
Labels: CLA signed, awaiting merge, type-tests

#14499 bpo-37463: match_hostname requires quad-dotted IPv4
  Lib/ssl.py
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Security/2019-07-01-08-46-14.bpo-37463.1CHwjE.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-security

#14559 [3.8] bpo-37463: match_hostname requires quad-dotted IPv4 (GH-14499)
  Lib/ssl.py
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Security/2019-07-01-08-46-14.bpo-37463.1CHwjE.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-security

#14560 [3.7] bpo-37463: match_hostname requires quad-dotted IPv4 (GH-14499)
  Lib/ssl.py
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Security/2019-07-01-08-46-14.bpo-37463.1CHwjE.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-security

#14453 bpo-37441: Fix a param error in exceptions.rst
  Doc/c-api/exceptions.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#14566 [3.7] bpo-37441: Fix wrong PyErr_SetImportErrorSubclass signature in doc (GH-14453)
  Doc/c-api/exceptions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14565 [3.8] bpo-37441: Fix wrong PyErr_SetImportErrorSubclass signature in doc (GH-14453)
  Doc/c-api/exceptions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14567 Doc: fix typo from Pyton to Python GH-14567
  Doc/whatsnew/3.9.rst
Labels: CLA not signed, awaiting merge, skip issue, skip news, type-documentation

#14562 bpo-37421: test_winconsoleio doesn't leak temp file anymore
  Lib/test/test_winconsoleio.py
  Misc/NEWS.d/next/Tests/2019-07-02-23-20-35.bpo-37421.HCkKWz.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, type-tests

#14563 bpo-37421: test_concurrent_futures cleans up multiprocessing
  Lib/test/test_concurrent_futures.py
  Misc/NEWS.d/next/Tests/2019-07-02-23-29-06.bpo-37421.WEfc5A.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, type-tests

#14564 bpo-37421: Fix test_distutils.test_build_ext()
  Lib/distutils/tests/support.py
  Lib/distutils/tests/test_build_ext.py
  Misc/NEWS.d/next/Tests/2019-07-03-00-05-28.bpo-37421.ORGRSG.rst
Labels: CLA signed, awaiting merge

#14569 [3.8] bpo-37421: test_winconsoleio doesn't leak temp file anymore (GH-14562)
  Lib/test/test_winconsoleio.py
  Misc/NEWS.d/next/Tests/2019-07-02-23-20-35.bpo-37421.HCkKWz.rst
Labels: CLA signed, awaiting merge, type-tests

#14570 [3.8] bpo-37421: test_concurrent_futures cleans up multiprocessing (GH-14563)
  Lib/test/test_concurrent_futures.py
  Misc/NEWS.d/next/Tests/2019-07-02-23-29-06.bpo-37421.WEfc5A.rst
Labels: CLA signed, awaiting merge, type-tests

#14571 [3.8] bpo-37421: Fix test_distutils.test_build_ext() (GH-14564)
  Lib/distutils/tests/support.py
  Lib/distutils/tests/test_build_ext.py
  Misc/NEWS.d/next/Tests/2019-07-03-00-05-28.bpo-37421.ORGRSG.rst
Labels: CLA signed, awaiting merge

#14557 bpo-37484: Optimize __exit__
  Python/ceval.c
Labels: CLA signed, awaiting review, skip news

#14550 bpo-37233: optimize case totalargs == 0 in method_vectorcall
  Objects/classobject.c
Labels: CLA signed, awaiting review, needs backport to 3.8, skip news

#14573 [3.8] bpo-37233: use _PY_FASTCALL_SMALL_STACK in method_vectorcall (GH-13974)
  Objects/classobject.c
Labels: CLA signed, awaiting core review, skip news

#14574 [3.8] bpo-37233: optimize method_vectorcall in case of totalargs == 0 (GH-14550)
  Objects/classobject.c
Labels: CLA signed, awaiting merge, skip news

#14466 bpo-19696: Replace deprecated method in "test_import_pkg.py"
  Lib/test/test_importlib/test_pkg_import.py
  Misc/ACKS
  Misc/NEWS.d/next/Tests/2019-06-29-16-02-21.bpo-19696.05ijhN.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#14576 [3.6] bpo-35605: Fix documentation build for sphinx<1.6
  Doc/tools/extensions/suspicious.py
Labels: CLA signed, awaiting merge, skip news

#14568 bpo-37459: importlib docs improperly reference get_resource_loader()
  Doc/library/importlib.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#14580 [3.8] bpo-37459: importlib docs improperly reference get_resource_loader() (GH-14568)
  Doc/library/importlib.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14581 [3.7] bpo-37459: importlib docs improperly reference get_resource_loader() (GH-14568)
  Doc/library/importlib.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#14572 bpo-37421: Fix multiprocessing get_temp_dir() finalizer
  Lib/multiprocessing/util.py
  Misc/NEWS.d/next/Library/2019-07-03-12-47-52.bpo-37421.gR5hC8.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8

#14558 bpo-37483: add _PyObject_CallOneArg() function
  Doc/c-api/object.rst
  Include/cpython/abstract.h
  Misc/NEWS.d/next/C API/2019-07-02-15-42-37.bpo-37483.vftT4f.rst
  Modules/_asynciomodule.c
  Modules/_collectionsmodule.c
  Modules/_csv.c
  Modules/_ctypes/callproc.c
  Modules/_elementtree.c
  Modules/_io/iobase.c
  Modules/_json.c
  Modules/_pickle.c
  Modules/_sqlite/cache.c
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/microprotocols.c
  Modules/_sre.c
  Modules/_struct.c
  Modules/_xxtestfuzz/fuzzer.c
  Modules/cjkcodecs/cjkcodecs.h
  Modules/cjkcodecs/multibytecodec.c
  Modules/gcmodule.c
  Modules/itertoolsmodule.c
  Modules/pyexpat.c
  Objects/abstract.c
  Objects/bytearrayobject.c
  Objects/bytesobject.c
  Objects/descrobject.c
  Objects/dictobject.c
  Objects/fileobject.c
  Objects/floatobject.c
  Objects/genobject.c
  Objects/listobject.c
  Objects/longobject.c
  Objects/memoryobject.c
  Objects/moduleobject.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Objects/weakrefobject.c
  Python/_warnings.c
  Python/bltinmodule.c
  Python/ceval.c
  Python/codecs.c
  Python/errors.c
  Python/import.c
Labels: CLA signed, awaiting merge

#14575 bpo-37493: use _PyObject_CallNoArg in more places
  Doc/extending/newtypes.rst
  Modules/_collectionsmodule.c
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/cfield.c
  Modules/_testcapimodule.c
  Modules/posixmodule.c
Labels: CLA signed, awaiting change review, skip news

#14586 [3.7] bpo-37421: Fix multiprocessing get_temp_dir() finalizer (GH-14572)
  Lib/multiprocessing/util.py
  Misc/NEWS.d/next/Library/2019-07-03-12-47-52.bpo-37421.gR5hC8.rst
Labels: CLA signed, awaiting merge

#14585 [3.8] bpo-37421: Fix multiprocessing get_temp_dir() finalizer (GH-14572)
  Lib/multiprocessing/util.py
  Misc/NEWS.d/next/Library/2019-07-03-12-47-52.bpo-37421.gR5hC8.rst
Labels: CLA signed, awaiting merge

#14590 [3.8] Minor updates to the macOS installer screens for 3.8.0b2 (GH-14501)
  Mac/BuildScript/resources/ReadMe.rtf
  Mac/BuildScript/resources/Welcome.rtf
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#14584 bpo-37266: Add bpo number to the What's New entry
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#14545 bpo-37479: on Enum subclasses with mixins, __format__ uses overridden __str__
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-07-02-12-43-57.bpo-37479.O53a5S.rst
Labels: CLA signed, awaiting merge

#14262 bpo-37346: Use OSError subclasses in os documentation
  Doc/library/os.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#14553 bpo-37481: Deprecate distutils bdist_wininst command
  Doc/distutils/apiref.rst
  Doc/distutils/builtdist.rst
  Doc/whatsnew/3.8.rst
  Lib/distutils/command/bdist_wininst.py
  Lib/distutils/tests/test_bdist_wininst.py
  Misc/NEWS.d/next/Library/2019-07-02-13-08-30.bpo-37481.hd5k09.rst
Labels: CLA signed, awaiting core review

#14597 [3.7] bpo-37346: Use OSError subclasses in os documentation (GH-14262)
  Doc/library/os.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14596 [3.8] bpo-37346: Use OSError subclasses in os documentation (GH-14262)
  Doc/library/os.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14598 [3.8] bpo-37481: Deprecate distutils bdist_wininst command (GH-14553)
  Doc/distutils/apiref.rst
  Doc/distutils/builtdist.rst
  Doc/whatsnew/3.8.rst
  Lib/distutils/command/bdist_wininst.py
  Lib/distutils/tests/test_bdist_wininst.py
  Misc/NEWS.d/next/Library/2019-07-02-13-08-30.bpo-37481.hd5k09.rst
Labels: CLA signed, awaiting merge

#14600 bpo-37483: fix reference leak in _PyCodec_Lookup
  Python/codecs.c
Labels: CLA signed, awaiting review, skip news, type-bugfix

#13781 bpo-36974: separate vectorcall functions for each calling convention
  Include/descrobject.h
  Include/methodobject.h
  Lib/test/test_call.py
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Core and Builtins/2019-06-11-12-59-38.bpo-36974.bVYmSA.rst
  Objects/call.c
  Objects/descrobject.c
  Objects/methodobject.c
  Python/ceval.c
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting review

#14601 bpo-37421: multiprocessing tests now stop ForkServer
  Lib/multiprocessing/forkserver.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2019-07-05-14-47-55.bpo-37421.n8o2to.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8

#14602 [3.8] bpo-37421: multiprocessing tests now stop ForkServer (GH-14601)
  Lib/multiprocessing/forkserver.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2019-07-05-14-47-55.bpo-37421.n8o2to.rst
Labels: CLA signed, awaiting merge

#14603 bpo-37151: remove _PyMethodDef_RawFastCall* functions
  Include/methodobject.h
  Objects/call.c
Labels: CLA signed, awaiting review, skip news

#14605 [3.7] bpo-37500: Revert commit 85ed1712e428f93408f56fc684816f9a85b0ebc0
  Lib/test/test_syntax.py
  Python/compile.c
  Python/peephole.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#14582 bpo-19696: Move test_threaded_import.py to test_importlib/
  Lib/test/test_importlib/test_threaded_import.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#14556 Typo fix in file Include/object.h
  Include/object.h
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, skip issue, skip news, type-bugfix

#14435 Fix typo
  Misc/NEWS.d/3.8.0a1.rst
  Misc/NEWS.d/3.8.0a3.rst
  Misc/NEWS.d/3.8.0b1.rst
  Modules/_abc.c
  Modules/mathmodule.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#14610 [3.8] Fix some typos (GH-14435)
  Misc/NEWS.d/3.8.0a1.rst
  Misc/NEWS.d/3.8.0a3.rst
  Misc/NEWS.d/3.8.0b1.rst
  Modules/_abc.c
  Modules/mathmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#14604 bpo-37508: Return a bytes object in memory.rst
  Doc/c-api/memory.rst
Labels: CLA signed, awaiting review, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#14614 [3.7] closes bpo-37508: Fix name of type in memory.rst. (GH-14604)
  Doc/c-api/memory.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14613 [3.8] closes bpo-37508: Fix name of type in memory.rst. (GH-14604)
  Doc/c-api/memory.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14616 bpo-37149: Replace dead link for online Tkinter reference
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-02-19-02.bpo-37149.NumHn3.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-documentation

#14618 [3.7] bpo-37149: Replace dead link for online Tkinter reference (GH-14616)
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-02-19-02.bpo-37149.NumHn3.rst
Labels: CLA signed, awaiting merge, type-documentation

#14617 [3.8] bpo-37149: Replace dead link for online Tkinter reference (GH-14616)
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-02-19-02.bpo-37149.NumHn3.rst
Labels: CLA signed, awaiting merge, type-documentation

#14620 [2.7] bpo-37149: Replace dead link for online Tkinter reference (GH-14616)
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-02-19-02.bpo-37149.NumHn3.rst
Labels: CLA signed, awaiting merge, type-documentation

#13944 bpo-26806: add 30 to the recursion limit in IDLE's shell
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help.html
  Lib/idlelib/idle_test/test_run.py
  Lib/idlelib/run.py
  Misc/NEWS.d/next/IDLE/2019-06-10-22-48-50.bpo-26806.Zltkum.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-bugfix

#14621 [3.8] bpo-26806: add 30 to the recursion limit in IDLE's shell (GH-13944)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help.html
  Lib/idlelib/idle_test/test_run.py
  Lib/idlelib/run.py
  Misc/NEWS.d/next/IDLE/2019-06-10-22-48-50.bpo-26806.Zltkum.rst
Labels: CLA signed, awaiting merge, type-bugfix

#14622 [3.7] bpo-26806: add 30 to the recursion limit in IDLE's shell (GH-13944)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help.html
  Lib/idlelib/idle_test/test_run.py
  Lib/idlelib/run.py
  Misc/NEWS.d/next/IDLE/2019-06-10-22-48-50.bpo-26806.Zltkum.rst
Labels: CLA signed, awaiting merge, type-bugfix

#14623 bpo-37487: Fix PyList_GetItem index description.
  Doc/c-api/list.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-17-19-26.bpo-37487.QagfZ5.rst
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.7, needs backport to 3.8, type-documentation

#14624 [3.8] bpo-37487: Fix PyList_GetItem index description. (GH-14623)
  Doc/c-api/list.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-17-19-26.bpo-37487.QagfZ5.rst
Labels: CLA signed, awaiting review, type-documentation

#14625 [3.7] bpo-37487: Fix PyList_GetItem index description. (GH-14623)
  Doc/c-api/list.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-17-19-26.bpo-37487.QagfZ5.rst
Labels: CLA signed, awaiting review, type-documentation

#14626 [2.7] bpo-37487: Fix PyList_GetItem index description. (GH-14623)
  Doc/c-api/list.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-17-19-26.bpo-37487.QagfZ5.rst
Labels: CLA signed, awaiting review, type-documentation

#14627 bpo-37456: Slash ('/') is now part of syntax
  Doc/faq/programming.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-17-51-36.bpo-37456.lgAQHn.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, type-documentation

#14628 [3.8] bpo-37456: Slash ('/') is now part of syntax. (GH-14627)
  Doc/faq/programming.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-17-51-36.bpo-37456.lgAQHn.rst
Labels: CLA signed, awaiting review, type-documentation

#14611 bpo-37478: Specify possible exceptions for os.chdir()
  Doc/library/os.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-00-57-27.bpo-37478.B0ioLw.rst
Labels: CLA signed, awaiting review, needs backport to 3.7, needs backport to 3.8, type-documentation

#14629 [3.8] bpo-37478: Specify possible exceptions for os.chdir() (GH-14611)
  Doc/library/os.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-00-57-27.bpo-37478.B0ioLw.rst
Labels: CLA signed, awaiting review, type-documentation

#14630 [3.7] bpo-37478: Specify possible exceptions for os.chdir() (GH-14611)
  Doc/library/os.rst
  Misc/NEWS.d/next/Documentation/2019-07-06-00-57-27.bpo-37478.B0ioLw.rst
Labels: CLA signed, awaiting review, type-documentation

#14631 bpo-37478: Add missing 'and'.
  Doc/library/os.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#14633 [3.7] bpo-37478: Add missing 'and'. (GH-14631)
  Doc/library/os.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14632 [3.8] bpo-37478: Add missing 'and'. (GH-14631)
  Doc/library/os.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14615 bpo-37513: Fix a type error in ctypes.rst
  Doc/library/ctypes.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#14636 [3.7] bpo-37513: Change ValueError to TypeError in an example in ctypes doc (GH-14615)
  Doc/library/ctypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14635 [3.8] bpo-37513: Change ValueError to TypeError in an example in ctypes doc (GH-14615)
  Doc/library/ctypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14637 [2.7] bpo-37513: Change ValueError to TypeError in an example in ctypes doc (GH-14615)
  Doc/library/ctypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14638 bpo-37520: Correct behavior for zipfile.Path.parent
  Lib/test/test_zipfile.py
  Lib/zipfile.py
  Misc/NEWS.d/next/Library/2019-07-07-21-09-08.bpo-37520.Gg0KD6.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8

#14641 [3.8] bpo-37520: Correct behavior for zipfile.Path.parent (GH-14638)
  Lib/test/test_zipfile.py
  Lib/zipfile.py
  Misc/NEWS.d/next/Library/2019-07-07-21-09-08.bpo-37520.Gg0KD6.rst
Labels: CLA signed, awaiting review

#14267 bpo-37337: Add _PyObject_CallMethodNoArgs()
  Doc/c-api/object.rst
  Include/cpython/abstract.h
  Misc/NEWS.d/next/C API/2019-06-19-12-06-31.bpo-37337.gXIGyU.rst
  Modules/_asynciomodule.c
  Modules/_collectionsmodule.c
  Modules/_ctypes/_ctypes.c
  Modules/_cursesmodule.c
  Modules/_datetimemodule.c
  Modules/_dbmmodule.c
  Modules/_gdbmmodule.c
  Modules/_io/_iomodule.c
  Modules/_io/bufferedio.c
  Modules/_io/iobase.c
  Modules/_io/stringio.c
  Modules/_io/textio.c
  Modules/_pickle.c
  Modules/_posixsubprocess.c
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/module.c
  Modules/_threadmodule.c
  Modules/faulthandler.c
  Modules/mmapmodule.c
  Modules/ossaudiodev.c
  Modules/selectmodule.c
  Objects/abstract.c
  Objects/descrobject.c
  Objects/fileobject.c
  Objects/odictobject.c
  Objects/typeobject.c
  Objects/weakrefobject.c
  Python/bltinmodule.c
  Python/errors.c
  Python/import.c
  Python/pylifecycle.c
  Python/pythonrun.c
  Python/traceback.c
Labels: CLA signed, awaiting merge

#14643 bpo-37421: test_concurrent_futures stop ForkServer
  Lib/test/test_concurrent_futures.py
  Misc/NEWS.d/next/Tests/2019-07-08-10-11-36.bpo-37421.OY77go.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, type-tests

#14645 [3.8] bpo-37421: test_concurrent_futures stops ForkServer (GH-14643)
  Lib/test/test_concurrent_futures.py
  Misc/NEWS.d/next/Tests/2019-07-08-10-11-36.bpo-37421.OY77go.rst
Labels: CLA signed, awaiting review, type-tests

#14644 Doc: Fix: Proper UpperCamelCase and lowercase.
  Doc/tutorial/controlflow.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#14639 Doc: Fix example title.
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#14649 [3.8] Doc: Fix: Proper UpperCamelCase and lowercase. (GH-14644)
  Doc/tutorial/controlflow.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#14650 [3.7] Doc: Fix: Proper UpperCamelCase and lowercase. (GH-14644)
  Doc/tutorial/controlflow.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#14651 [3.8] Doc: Fix example title. (GH-14639)
  Doc/library/stdtypes.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#14607 bpo-18374: fix wrong col_offset of some ast.BinOp instances
  Lib/test/test_ast.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-07-05-21-46-45.bpo-18374.qgE0H3.rst
  Python/ast.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#14652 [3.7] Doc: Fix example title. (GH-14639)
  Doc/library/stdtypes.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#14653 [3.8] bpo-18374: fix wrong col_offset of some ast.BinOp instances (GH-14607)
  Lib/test/test_ast.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-07-05-21-46-45.bpo-18374.qgE0H3.rst
  Python/ast.c
Labels: :robot: automerge, CLA signed, awaiting merge

#14662 bpo-37322: Fix test_ssl.test_pha_required_nocert() ResourceWarning
  Lib/test/test_ssl.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-tests

#14664 bpo-37526: Add support.catch_threading_exception()
  Doc/library/test.rst
  Lib/test/support/__init__.py
  Misc/NEWS.d/next/Tests/2019-07-09-12-33-18.bpo-37526.vmm5y7.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8

#14668 bpo-37120: Fix _ssl get_num_tickets()
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, skip news

#14669 Revert "bpo-37322: Fix test_ssl.test_pha_required_nocert() ResourceWarning (GH-14662)"
  Lib/test/test_ssl.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#14666 [3.8] bpo-37526: Add support.catch_threading_exception() (GH-14664)
  Doc/library/test.rst
  Lib/test/support/__init__.py
  Misc/NEWS.d/next/Tests/2019-07-09-12-33-18.bpo-37526.vmm5y7.rst
Labels: CLA signed, awaiting review

#14659 bpo-18374: fix tests to check the correct thing about line numbers
  Lib/test/test_ast.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip news, type-tests

#14670 bpo-37322: ssl test_pha_required_nocert() ignores expected SSLError
  Lib/test/test_ssl.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-tests

#14671 [3.8] bpo-37120: Fix _ssl get_num_tickets() (GH-14668)
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, skip news

#14673 [3.8] bpo-37322: ssl test_pha_required_nocert() ignores expected SSLError (GH-14670)
  Lib/test/test_ssl.py
Labels: CLA signed, awaiting merge, skip news, type-tests
