Repository python/cpython, pull requests merged in 2019-05, with the labels that each got.

#13030 bpo-36763: Add _PyCoreConfig_SetArgv
  Include/internal/pycore_coreconfig.h
  Lib/test/pythoninfo.py
  Python/coreconfig.c
  Python/pathconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#12755 bpo-30458: Disallow control chars in http URLs.
  Lib/http/client.py
  Lib/test/test_urllib.py
  Lib/test/test_xmlrpc.py
  Misc/NEWS.d/next/Security/2019-04-10-08-53-30.bpo-36276.51E-DA.rst
Labels: CLA signed, awaiting change review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, type-bugfix, type-security

#13031 bpo-36763: Rework _PyInitError API
  Include/cpython/coreconfig.h
  Modules/getpath.c
  Modules/main.c
  Python/bootstrap_hash.c
  Python/coreconfig.c
  Python/frozenmain.c
  Python/preconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#13033 remove jython support from unittest.mock
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Lib/unittest/test/testmock/testpatch.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#13032 bpo-30458: Disable https related urllib tests on a build without ssl
  Lib/test/test_urllib.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#13035 bpo-36763: Add _PyCoreConfig_SetString()
  Include/internal/pycore_coreconfig.h
  Python/coreconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#13025 [2.7] bpo-36742: Fixes handling of pre-normalization characters in urlsplit() (GH-13017)
  Lib/test/test_urlparse.py
  Lib/urlparse.py
  Misc/NEWS.d/next/Security/2019-04-29-15-34-59.bpo-36742.QCUY0i.rst
Labels: :robot: automerge, CLA signed, awaiting core review

#13029 MNT: set stacklevel in the getfullargspec deprecation warning to 2
  Lib/inspect.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#9713 bpo-27682: Handle client connection terminations in wsgiref.
  Lib/test/test_wsgiref.py
  Lib/wsgiref/handlers.py
  Misc/NEWS.d/next/Library/2018-10-05-16-01-00.bpo-34547.abbaa.rst
Labels: awaiting merge, needs backport to 3.7

#13043 [3.7] bpo-27682: Handle client connection terminations in wsgiref (GH-9713)
  Lib/test/test_wsgiref.py
  Lib/wsgiref/handlers.py
  Misc/NEWS.d/next/Library/2018-10-05-16-01-00.bpo-34547.abbaa.rst
Labels: CLA signed, awaiting review

#12883 bpo-36673: Implement comment/PI parsing support for the TreeBuilder in ElementTree.
  Doc/library/xml.etree.elementtree.rst
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2019-04-20-09-50-32.bpo-36673.XF4Egb.rst
  Modules/_elementtree.c
  Modules/clinic/_elementtree.c.h
Labels: CLA signed, awaiting core review

#12885 bpo-36676: Namespace prefix aware parsing support for the ET.XMLParser target
  Doc/library/xml.etree.elementtree.rst
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2019-04-20-13-10-34.bpo-36676.XF4Egb.rst
  Modules/_elementtree.c
Labels: CLA signed, awaiting core review

#10376 bpo-35181: Correct an assumption about the namespace package loader attribute
  Doc/reference/import.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12966 bpo-13611: C14N 2.0 implementation for ElementTree
  Doc/library/xml.etree.elementtree.rst
  Doc/whatsnew/3.8.rst
  Lib/test/test_xml_etree.py
  Lib/test/xmltestdata/c14n-20/c14nComment.xml
  Lib/test/xmltestdata/c14n-20/c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/c14nPrefix.xml
  Lib/test/xmltestdata/c14n-20/c14nPrefixQname.xml
  Lib/test/xmltestdata/c14n-20/c14nPrefixQnameXpathElem.xml
  Lib/test/xmltestdata/c14n-20/c14nQname.xml
  Lib/test/xmltestdata/c14n-20/c14nQnameElem.xml
  Lib/test/xmltestdata/c14n-20/c14nQnameXpathElem.xml
  Lib/test/xmltestdata/c14n-20/c14nTrim.xml
  Lib/test/xmltestdata/c14n-20/doc.dtd
  Lib/test/xmltestdata/c14n-20/doc.xsl
  Lib/test/xmltestdata/c14n-20/inC14N1.xml
  Lib/test/xmltestdata/c14n-20/inC14N2.xml
  Lib/test/xmltestdata/c14n-20/inC14N3.xml
  Lib/test/xmltestdata/c14n-20/inC14N4.xml
  Lib/test/xmltestdata/c14n-20/inC14N5.xml
  Lib/test/xmltestdata/c14n-20/inC14N6.xml
  Lib/test/xmltestdata/c14n-20/inNsContent.xml
  Lib/test/xmltestdata/c14n-20/inNsDefault.xml
  Lib/test/xmltestdata/c14n-20/inNsPushdown.xml
  Lib/test/xmltestdata/c14n-20/inNsRedecl.xml
  Lib/test/xmltestdata/c14n-20/inNsSort.xml
  Lib/test/xmltestdata/c14n-20/inNsSuperfluous.xml
  Lib/test/xmltestdata/c14n-20/inNsXml.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N1_c14nComment.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N1_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N2_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N2_c14nTrim.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N3_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N3_c14nPrefix.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N3_c14nTrim.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N4_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N4_c14nTrim.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N5_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N5_c14nTrim.xml
  Lib/test/xmltestdata/c14n-20/out_inC14N6_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inNsContent_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inNsContent_c14nPrefixQnameXpathElem.xml
  Lib/test/xmltestdata/c14n-20/out_inNsContent_c14nQnameElem.xml
  Lib/test/xmltestdata/c14n-20/out_inNsContent_c14nQnameXpathElem.xml
  Lib/test/xmltestdata/c14n-20/out_inNsDefault_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inNsDefault_c14nPrefix.xml
  Lib/test/xmltestdata/c14n-20/out_inNsPushdown_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inNsPushdown_c14nPrefix.xml
  Lib/test/xmltestdata/c14n-20/out_inNsRedecl_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inNsRedecl_c14nPrefix.xml
  Lib/test/xmltestdata/c14n-20/out_inNsSort_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inNsSort_c14nPrefix.xml
  Lib/test/xmltestdata/c14n-20/out_inNsSuperfluous_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inNsSuperfluous_c14nPrefix.xml
  Lib/test/xmltestdata/c14n-20/out_inNsXml_c14nDefault.xml
  Lib/test/xmltestdata/c14n-20/out_inNsXml_c14nPrefix.xml
  Lib/test/xmltestdata/c14n-20/out_inNsXml_c14nPrefixQname.xml
  Lib/test/xmltestdata/c14n-20/out_inNsXml_c14nQname.xml
  Lib/test/xmltestdata/c14n-20/world.txt
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2019-04-26-10-10-34.bpo-13611.XEF4bg.rst
Labels: CLA signed, awaiting core review

#13045 Mock 100% coverage
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/support.py
  Lib/unittest/test/testmock/testcallable.py
  Lib/unittest/test/testmock/testhelpers.py
  Lib/unittest/test/testmock/testmagicmethods.py
  Lib/unittest/test/testmock/testmock.py
  Lib/unittest/test/testmock/testpatch.py
  Lib/unittest/test/testmock/testsealable.py
  Lib/unittest/test/testmock/testwith.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#13046 bpo-35864: Move dangling bullet points into named subsections
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#13047 bpo-36018: Update example to show mean and stdev properties
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#13040 bpo-29512: Change bisect to bisect_cmd in docstring
  Lib/test/bisect_cmd.py
Labels: CLA signed, awaiting core review, skip news

#13050 [2.7] bpo-29512: Change bisect to bisect_cmd in docstring (GH-13040)
  Lib/test/bisect_cmd.py
Labels: CLA signed, awaiting merge, skip news

#13051 [3.7] bpo-29512: Change bisect to bisect_cmd in docstring (GH-13040)
  Lib/test/bisect_cmd.py
Labels: CLA signed, skip news

#13052 bpo-36763: Make _PyCoreConfig.check_hash_pycs_mode public
  Include/cpython/coreconfig.h
  Lib/test/test_embed.py
  Programs/_testembed.c
  Python/coreconfig.c
  Python/import.c
Labels: CLA signed, awaiting core review, skip news

#13020 regarding to grammar and spell check
  README.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#13049 Fix tiny tiny typo in 3.8 what's new
  Doc/whatsnew/3.8.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#13053 bpo-13611: Include C14N 2.0 test data in installation
  Lib/test/xmltestdata/c14n-20/README
  Makefile.pre.in
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#13026 bpo-14546: Fix the argument handling in Tools/scripts/lll.py
  Lib/test/test_tools/test_lll.py
  Misc/NEWS.d/next/Tools-Demos/2019-04-30-14-30-29.bpo-14546.r38Y-6.rst
  Tools/scripts/lll.py
Labels: CLA signed, awaiting merge

#13056 bpo-36775: Add _Py_FORCE_UTF8_FS_ENCODING macro
  Include/pyport.h
  Objects/unicodeobject.c
  Python/coreconfig.c
  Python/fileutils.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#13057 bpo-36775: Add _PyUnicode_InitEncodings()
  Include/internal/pycore_pylifecycle.h
  Objects/unicodeobject.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#12910 [3.6] bpo-9194: Fix the bounds checking in winreg.c's fixupMultiSZ() (GH-12687)
  PC/winreg.c
Labels: CLA signed, awaiting merge, skip news

#13024 [3.6] bpo-36742: Fixes handling of pre-normalization characters in urlsplit() (GH-13017)
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2019-04-29-15-34-59.bpo-36742.QCUY0i.rst
Labels: CLA signed, awaiting merge

#12716 [3.7] bpo-35726: Prevented QueueHandler formatting from affecting other handlers (GH-11537)
  Lib/logging/handlers.py
  Misc/NEWS.d/next/Library/2019-01-13-01-33-00.bpo-35726.dasdas.rst
Labels: CLA signed, awaiting review

#13061 [3.7] bpo-35726: Add test for QueueHandler with multiple handlers (GH-11659)
  Lib/test/test_logging.py
Labels: CLA signed, awaiting review, skip news, type-tests

#13001 bpo-36546: Fix typo quaatile to quantile
  Lib/test/test_statistics.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#13065 bpo-36763: Add _PyCoreConfig._config_version
  Include/cpython/coreconfig.h
Labels: CLA signed, awaiting core review, skip news

#13058 bpo-36776: Add @support.skip_unless_symlink to test_lll.py
  Lib/test/test_tools/test_lll.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#13062 bpo-36775: _PyCoreConfig only uses wchar_t*
  Include/cpython/coreconfig.h
  Include/internal/pycore_coreconfig.h
  Include/internal/pycore_pylifecycle.h
  Include/internal/pycore_pystate.h
  Objects/stringlib/codecs.h
  Objects/unicodeobject.c
  Programs/_testembed.c
  Python/coreconfig.c
  Python/preconfig.c
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review, skip news

#13037 bpo-36763: _PyCoreConfig_SetPyArgv() preinitializes Python
  Include/internal/pycore_pylifecycle.h
  Modules/main.c
  Python/coreconfig.c
  Python/pylifecycle.c
Labels: CLA signed, skip news

#13060 [3.7] bpo-14546: Fix the argument handling in Tools/scripts/lll.py (GH-13026)
  Lib/test/test_tools/test_lll.py
  Misc/NEWS.d/next/Tools-Demos/2019-04-30-14-30-29.bpo-14546.r38Y-6.rst
  Tools/scripts/lll.py
Labels: CLA signed, awaiting merge

#13063 [2.7] bpo-14546: Fix the argument handling in Tools/scripts/lll.py (GH-13026)
  Lib/test/test_tools.py
  Misc/NEWS.d/next/Tools-Demos/2019-04-30-14-30-29.bpo-14546.r38Y-6.rst
  Tools/scripts/lll.py
Labels: CLA signed, awaiting review

#13066 bpo-36763: Remove _PyCoreConfig._init_main
  Include/cpython/coreconfig.h
  Lib/test/test_embed.py
  Programs/_freeze_importlib.c
  Programs/_testembed.c
  Python/coreconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#13067 [3.7] bpo-34162: Fix idlelib/NEWS.text for 3.7.4
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting core review, skip news, type-documentation

#13055 bpo-13611: Add correct license for C14N test suite to license docs.
  Doc/license.rst
  Lib/test/xmltestdata/c14n-20/README
Labels: CLA signed, awaiting core review, skip news

#9877 bpo-34848 : Correct a method signature in docstring for range(..).index method
  Objects/rangeobject.c
Labels: CLA signed, awaiting merge, skip news

#13075 [3.7] bpo-34848 : Correct an incorrect docstring for range().index method (GH-9877)
  Objects/rangeobject.c
Labels: CLA signed, awaiting merge, skip news

#12996 Don't use the LHS/RHS acronym in Simple statements
  Doc/reference/simple_stmts.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12379 Improve grammar on async context managers and shorten text
  Doc/reference/datamodel.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12399 bpo-36341: Fix tests calling bind() on AF_UNIX sockets
  Lib/test/test_asyncio/test_server.py
  Lib/test/test_socket.py
  Lib/test/test_stat.py
  Misc/NEWS.d/next/Tests/2019-03-18-10-47-45.bpo-36341.UXlY0P.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-tests

#12800 bpo-36613: call remove_done_callback if exception
  Lib/asyncio/tasks.py
  Misc/NEWS.d/next/Library/2019-04-12-13-52-15.bpo-36613.hqT1qn.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7

#11522 Fixed typo
  Doc/library/asyncio-eventloop.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12848 bpo-24638: Improve the error message in asyncio.ensure_future()
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_tasks.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#13076 [3.7] bpo-36613: call remove_done_callback if exception (GH-12800)
  Lib/asyncio/tasks.py
  Misc/NEWS.d/next/Library/2019-04-12-13-52-15.bpo-36613.hqT1qn.rst
Labels: CLA signed, awaiting merge

#7759 bpo-33882: Mention breakpoint() in debugger-related FAQ
  Doc/faq/programming.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#12997 bpo-28238: Implement "{*}tag" and "{ns}*" wildcard tag selection support for ElementPath
  Doc/library/xml.etree.elementtree.rst
  Doc/whatsnew/3.8.rst
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementPath.py
  Misc/NEWS.d/next/Library/2019-04-28-15-01-29.bpo-28238.gdk38f.rst
  Modules/_elementtree.c
Labels: CLA signed, awaiting core review

#12384 Add explicit check to silence warning on MacOS
  Modules/posixmodule.c
Labels: CLA signed, awaiting review, skip issue, skip news

#12990 bpo-26978: Implement pathlib.Path.link_to (Using os.link)
  Doc/library/pathlib.rst
  Doc/whatsnew/3.8.rst
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2019-04-28-01-52-39.bpo-26978.Lpm-SI.rst
Labels: CLA signed, awaiting merge

#13068 bpo-36475: Make PyThread_exit_thread with _Py_NO_RETURN
  Include/pyerrors.h
  Include/pyport.h
  Include/pythread.h
  Python/ceval.c
  Python/thread_nt.h
  Python/thread_pthread.h
Labels: CLA signed, awaiting merge, skip news

#13089 bpo-36166: Change to rst datamodel file.
  Doc/reference/datamodel.rst
Labels: CLA not signed, awaiting merge, skip news, type-documentation

#13090 bpo-36189: Fixing typo in tutorial introduction
  Doc/tutorial/introduction.rst
Labels: CLA not signed, awaiting review, skip news, type-documentation

#13094 [3.7] bpo-36166: Change to rst datamodel file. (GH-13089)
  Doc/reference/datamodel.rst
Labels: CLA not signed, awaiting merge, skip news, type-documentation

#13093 [3.7] bpo-36189: Fixing typo in tutorial introduction (GH-13090)
  Doc/tutorial/introduction.rst
Labels: CLA not signed, awaiting merge, skip news, type-documentation

#13096 simplify StartupImportTests
  Lib/test/test_site.py
Labels: CLA signed, OS-mac, awaiting core review, needs backport to 3.7, skip issue, skip news, type-tests

#13097 [3.7] simplify StartupImportTests (GH-13096)
  Lib/test/test_site.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#7237 bpo-33530: Implement Happy Eyeballs in asyncio, v2
  Doc/library/asyncio-eventloop.rst
  Lib/asyncio/base_events.py
  Lib/asyncio/events.py
  Lib/asyncio/staggered.py
  Misc/NEWS.d/next/Library/2018-05-29-18-34-53.bpo-33530._4Q_bi.rst
Labels: :robot: automerge, CLA signed, awaiting merge, expert-asyncio

#13080 bpo-36791: Safer detection of integer overflow in sum().
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-bugfix

#5505 bpo-16024: Doc cleanup regarding path_fd, dir_fd, follow_symlinks
  Doc/library/os.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#12691 bpo-36531: Only count number of members once in PyType_FromSpec
  Objects/typeobject.c
Labels: CLA signed, awaiting review, skip news

#13109 bpo-36811: Fix a C compiler warning.
  Modules/_elementtree.c
Labels: CLA signed, awaiting core review, skip news

#12091 Doc/c-api/exceptions.rst: fix grammar
  Doc/c-api/exceptions.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#10488 Remove outdated reference to PEP 333
  Doc/library/wsgiref.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#13107 bpo-36798: Updating f-string docs for := use case.
  Doc/reference/lexical_analysis.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#12769 bpo-36594: Fix incorrect use of %p in format strings
  Misc/NEWS.d/next/Core and Builtins/2019-04-10-18-12-11.bpo-36594.fbnJAc.rst
  Modules/_ctypes/_ctypes_test.c
  Modules/_ctypes/callproc.c
  Modules/_xxsubinterpretersmodule.c
  Modules/hashtable.c
  Objects/object.c
  Objects/obmalloc.c
  Objects/unicodeobject.c
  Programs/_freeze_importlib.c
  Python/sysmodule.c
  Python/thread_pthread.h
Labels: CLA signed, awaiting merge

#13118 Unroll import-team in CODEOWNERS
  .github/CODEOWNERS
Labels: CLA signed, awaiting core review, skip issue, skip news

#13115 bpo-30668: add missing word in license.rst
  Doc/license.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#13122 Clarify the download unit in the download section
  Doc/tools/templates/download.html
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#13114 bpo-36275: enhance documentation for venv.create()
  Doc/library/venv.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#13116 bpo-36766: Typos in docs and code comments
  Doc/library/email.generator.rst
  Doc/library/pyclbr.rst
  Lib/idlelib/configdialog.py
  Lib/idlelib/help.html
  Lib/idlelib/help.py
  Lib/idlelib/idle_test/test_config.py
  Lib/lib2to3/pgen2/tokenize.py
  Lib/multiprocessing/resource_sharer.py
  Lib/pathlib.py
  Lib/platform.py
  Lib/pstats.py
  Lib/test/datetimetester.py
  Lib/test/pickletester.py
  Lib/test/support/__init__.py
  Lib/test/test_dataclasses.py
  Lib/test/test_importlib/test_lazy.py
  Lib/test/test_random.py
  Lib/test/test_ssl.py
  Lib/test/test_tools/test_i18n.py
  Lib/tokenize.py
  Lib/turtle.py
  Objects/object.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#13126 [3.7] bpo-30668: add missing word in license.rst (GH-13115)
  Doc/license.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#13131 [3.7] bpo-36275: enhance documentation for venv.create() (GH-13114)
  Doc/library/venv.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#13081 bpo-36793: Remove unneeded __str__ definitions.
  Doc/whatsnew/3.8.rst
  Lib/_pydecimal.py
  Lib/asyncore.py
  Lib/doctest.py
  Lib/email/charset.py
  Lib/http/client.py
  Lib/json/encoder.py
  Lib/logging/__init__.py
  Lib/sre_constants.py
  Lib/subprocess.py
  Lib/xmlrpc/client.py
  Misc/NEWS.d/next/Core and Builtins/2019-05-04-16-15-33.bpo-36793.Izog4Z.rst
  Modules/_decimal/_decimal.c
  Modules/_json.c
  Objects/boolobject.c
  Objects/complexobject.c
  Objects/floatobject.c
  Objects/longobject.c
Labels: CLA signed, awaiting merge, type-enhancement

#13130 [3.7] Clarify the download unit in the download section (GH-13122)
  Doc/tools/templates/download.html
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#12705 bpo-36542: Allow to overwrite the signature for Python functions.
  Lib/bdb.py
  Lib/cProfile.py
  Lib/collections/__init__.py
  Lib/concurrent/futures/_base.py
  Lib/concurrent/futures/process.py
  Lib/concurrent/futures/thread.py
  Lib/contextlib.py
  Lib/curses/__init__.py
  Lib/functools.py
  Lib/inspect.py
  Lib/multiprocessing/managers.py
  Lib/profile.py
  Lib/test/test_inspect.py
  Lib/trace.py
  Lib/unittest/case.py
  Lib/weakref.py
  Misc/NEWS.d/next/Library/2019-04-06-12-36-09.bpo-36542.Q0qyYV.rst
Labels: CLA signed, awaiting core review, type-enhancement

#13133 bpo-36165 Fix rst formatting for several links in ssl documentation
  Doc/library/ssl.rst
Labels: CLA signed, skip news, type-documentation

#13136 [3.7] bpo-36766: Typos in docs and code comments (GH-13116).
  Doc/library/email.generator.rst
  Doc/library/pyclbr.rst
  Lib/idlelib/configdialog.py
  Lib/idlelib/help.html
  Lib/idlelib/help.py
  Lib/idlelib/idle_test/test_config.py
  Lib/lib2to3/pgen2/tokenize.py
  Lib/multiprocessing/resource_sharer.py
  Lib/pathlib.py
  Lib/platform.py
  Lib/pstats.py
  Lib/test/datetimetester.py
  Lib/test/pickletester.py
  Lib/test/support/__init__.py
  Lib/test/test_dataclasses.py
  Lib/test/test_importlib/test_lazy.py
  Lib/test/test_random.py
  Lib/test/test_ssl.py
  Lib/test/test_tools/test_i18n.py
  Lib/tokenize.py
  Lib/turtle.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#13124 bpo-35925: Skip SSL tests that fail due to weak external certs.
  Lib/test/test_httplib.py
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Tests/2019-05-06-18-29-54.bpo-35925.gwQPuC.rst
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, sprint, type-tests

#13101 bpo-36806: Forbid stream objects creation outside of asyncio
  Lib/asyncio/streams.py
  Lib/asyncio/subprocess.py
  Lib/test/test_asyncio/test_streams.py
  Lib/test/test_asyncio/test_subprocess.py
  Misc/NEWS.d/next/Library/2019-05-05-16-14-38.bpo-36806.rAzF-x.rst
Labels: CLA signed, awaiting merge

#13139 [3.7] bpo-35925: Skip SSL tests that fail due to weak external certs. (GH-13124)
  Lib/test/test_httplib.py
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Tests/2019-05-06-18-29-54.bpo-35925.gwQPuC.rst
Labels: CLA signed, awaiting merge, sprint, type-tests

#11521 bpo-31855: unittest.mock.mock_open() results now respects the argument of read([size])
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testwith.py
  Misc/NEWS.d/next/Library/2019-01-11-17-09-15.bpo-31855.PlhfsX.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7

#13152 [3.7] bpo-31855: unittest.mock.mock_open() results now respects the argument of read([size]) (GH-11521)
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testwith.py
  Misc/NEWS.d/next/Library/2019-01-11-17-09-15.bpo-31855.PlhfsX.rst
Labels: CLA signed, awaiting review

#13147 bpo-36783: Added C API Documentation for Time_FromTimeAndFold and PyDateTime_FromDateAndTimeAndFold
  Doc/c-api/datetime.rst
  Misc/NEWS.d/next/Documentation/2019-05-07-02-30-51.bpo-36783.gpC8E2.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-documentation

#13156 [3.7] bpo-36783: Added C API Documentation for Time_FromTimeAndFold and PyDateTime_FromDateAndTimeAndFold (GH-13147)
  Doc/c-api/datetime.rst
  Misc/NEWS.d/next/Documentation/2019-05-07-02-30-51.bpo-36783.gpC8E2.rst
Labels: CLA signed, awaiting merge, type-documentation

#13121 bpo-28795: Signal documentation: Fix misleading statement.
  Doc/library/signal.rst
Labels: CLA signed, needs backport to 3.7, skip news

#13154 [3.7] bpo-30458: Disallow control chars in http URLs. (GH-12755)
  Lib/http/client.py
  Lib/test/test_urllib.py
  Lib/test/test_xmlrpc.py
  Misc/NEWS.d/next/Security/2019-04-10-08-53-30.bpo-30458.51E-DA.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-security

#13158 [3.7] bpo-28795: Signal documentation: Fix misleading statement. (GH-13121)
  Doc/library/signal.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#12704 bpo-36533: Reinit logging.Handler locks on fork().
  Lib/logging/__init__.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2019-04-06-00-55-09.bpo-36533.kzMyRH.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7

#13086 bpo-11001: updated cookie docs
  Doc/library/http.cookies.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#423 bpo-31922: Do not connect UDP sockets when broadcast is allowed
  Lib/asyncio/base_events.py
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_base_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Misc/NEWS.d/next/Library/2018-05-30-01-05-50.bpo-31922.fobsXJ.rst
Labels: :robot: automerge, CLA signed, awaiting merge, expert-asyncio, needs backport to 3.7

#13112 Don't import `wait` from connection
  Lib/concurrent/futures/process.py
Labels: CLA signed, awaiting review, skip issue, skip news, sprint

#13161 [3.7] bpo-11001: updated cookie docs (GH-13086)
  Doc/library/http.cookies.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#13162 [3.7] bpo-31922: Do not connect UDP sockets when broadcast is allowed (GH-423)
  Lib/asyncio/base_events.py
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_base_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Misc/NEWS.d/next/Library/2018-05-30-01-05-50.bpo-31922.fobsXJ.rst
Labels: CLA signed, awaiting merge

#10340 bpo-35125: remove inner callback on outer cancellation in asyncio shield
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2019-02-15-17-18-50.bpo-35125.h0xk0f.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7

#13167 [3.7] bpo-35125: remove inner callback on outer cancellation in asyncio shield (GH-10340)
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2019-02-15-17-18-50.bpo-35125.h0xk0f.rst
Labels: CLA signed, awaiting merge

#13103 Add a footnote about Cheese Shop in Doc/tutorial
  Doc/tutorial/whatnow.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, skip issue, skip news, type-documentation

#13170 [3.7] bpo-36533: Reinit logging.Handler locks on fork(). (GH-12704)
  Lib/logging/__init__.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2019-04-06-00-55-09.bpo-36533.kzMyRH.rst
Labels: CLA signed, awaiting core review, sprint, type-bugfix

#13098 bpo-36801: Fix waiting in StreamWriter.drain for closing SSL transport
  Lib/asyncio/streams.py
  Lib/asyncio/subprocess.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2019-05-05-09-45-44.bpo-36801.XrlFFs.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7

#13174 [3.7] Add a footnote about Cheese Shop in Doc/tutorial (GH-13103)
  Doc/tutorial/whatnow.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#13173 bpo-36838: Suggest 'make venv' when missing Doc/ tools.
  Doc/Makefile
Labels: CLA signed, skip news, sprint, type-documentation, type-enhancement

#11908 bpo-36015: logging: handle StreamHandler representaton of stream with int name
  Lib/logging/__init__.py
  Lib/test/test_logging.py
Labels: CLA signed, awaiting merge, skip news

#13169 bpo-27639: Correct return type for UserList slicing operation
  Lib/collections/__init__.py
  Lib/test/test_userlist.py
  Misc/NEWS.d/next/Core and Builtins/2019-05-07-15-49-17.bpo-27639.b1Ah87.rst
Labels: CLA signed, awaiting review, needs backport to 3.7, type-bugfix

#13176 [3.7] bpo-36801: Fix waiting in StreamWriter.drain for closing SSL transport (GH-13098)
  Lib/asyncio/streams.py
  Lib/asyncio/subprocess.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2019-05-05-09-45-44.bpo-36801.XrlFFs.rst
Labels: CLA signed, awaiting merge

#11316 Doc: Be explicit that Pathlib resolve was strict before 3.6.
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#13190 [3.7] Doc: Be explicit that Pathlib resolve was strict before 3.6. (GH-11316)
  Doc/library/pathlib.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#4125 bpo-31873: Change 12 instances of 'unicode' to 'Unicode'
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting merge, skip news

#13005 bpo-24048: Save the live exception during import.c's remove_module()
  Misc/NEWS.d/next/Core and Builtins/2019-04-29-03-27-22.bpo-24048.vXxUDQ.rst
  Python/import.c
Labels: CLA signed

#13155 [3.6] bpo-30458: Disallow control chars in http URLs. (GH-12755)
  Lib/http/client.py
  Lib/test/test_urllib.py
  Lib/test/test_xmlrpc.py
  Misc/NEWS.d/next/Security/2019-04-10-08-53-30.bpo-30458.51E-DA.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-security

#13194 [3.7] bpo-31873: Update unicode.rst - 'unicode' capitalization (GH-4125)
  Doc/c-api/unicode.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#13192 bpo-36816: Update the self-signed.pythontest.net cert
  Lib/test/selfsigned_pythontestdotnet.pem
  Misc/NEWS.d/next/Tests/2019-05-08-15-55-46.bpo-36816.WBKRGZ.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, sprint, type-tests

#12991 bpo-24758: Improve the error msg for unittest.mock.Mock()'s unsafe mode
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
Labels: CLA signed, awaiting merge, skip news

#13132 bpo-26903: Limit ProcessPoolExecutor to 61 workers on Windows
  Doc/library/concurrent.futures.rst
  Lib/concurrent/futures/process.py
  Lib/test/test_concurrent_futures.py
  Misc/NEWS.d/next/Library/2019-05-06-19-17-04.bpo-26903.4payXb.rst
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7

#13198 [3.6] bpo-36816: Update the self-signed.pythontest.net cert (GH-13192)
  Lib/test/selfsigned_pythontestdotnet.pem
  Misc/NEWS.d/next/Tests/2019-05-08-15-55-46.bpo-36816.WBKRGZ.rst
Labels: :robot: automerge, CLA signed, awaiting core review, sprint, type-tests

#12588 bpo-35900: Add a state_setter arg to save_reduce
  Doc/library/pickle.rst
  Lib/pickle.py
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2019-03-27-15-09-00.bpo-35900.fh56UU.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting merge

#12499 bpo-35900: Enable custom reduction callback registration in _pickle
  Doc/library/pickle.rst
  Lib/pickle.py
  Lib/test/pickletester.py
  Lib/test/test_pickle.py
  Misc/NEWS.d/next/Library/2019-03-22-22-40-00.bpo-35900.oiee0o.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting merge

#13197 [3.7] bpo-36816: Update the self-signed.pythontest.net cert (GH-13192)
  Lib/test/selfsigned_pythontestdotnet.pem
  Misc/NEWS.d/next/Tests/2019-05-08-15-55-46.bpo-36816.WBKRGZ.rst
Labels: :robot: automerge, CLA signed, awaiting merge, sprint, type-tests

#13214 closes bpo-36861: Update Unicode database to 12.1.0.
  Doc/library/stdtypes.rst
  Doc/library/unicodedata.rst
  Doc/reference/lexical_analysis.rst
  Doc/whatsnew/3.8.rst
  Lib/test/test_unicodedata.py
  Misc/NEWS.d/next/Core and Builtins/2019-05-08-20-42-40.bpo-36861.72mvZM.rst
  Modules/unicodedata_db.h
  Modules/unicodename_db.h
  Objects/unicodetype_db.h
  Tools/unicode/makeunicodedata.py
Labels: CLA signed, awaiting core review

#13201 bpo-36831: Do not apply default namespace to unprefixed attributes in ElementPath
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementPath.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#12255 bpo-36239: Skip comments in gettext infos
  Lib/gettext.py
  Lib/test/test_gettext.py
  Misc/NEWS.d/next/Library/2019-03-09-23-51-27.bpo-36239.BHJ3Ln.rst
Labels: CLA signed, awaiting merge

#13213 bpo-36832: Add support for .parent and .joinpath in zipfile.Path
  Lib/test/test_zipfile.py
  Lib/zipfile.py
Labels: CLA signed, awaiting merge, skip news

#13191 bpo-36851: Clean the frame stack if the execution ends with a return and the stack is not empty
  Lib/test/test_code.py
  Misc/NEWS.d/next/Core and Builtins/2019-05-08-11-42-06.bpo-36851.J7DiCW.rst
  Python/ceval.c
Labels: CLA signed, awaiting core review, sprint

#1440 bpo-30262: Don't expose sqlite Cache and Statement
  Doc/whatsnew/3.8.rst
  Misc/NEWS.d/next/Library/2019-05-09-12-38-40.bpo-30262.Tu74ak.rst
  Modules/_sqlite/module.c
Labels: CLA signed, awaiting merge

#10304 [Skip Issue] Fix a possible crash due to PyType_FromSpecWithBases()
  Objects/typeobject.c
Labels: CLA signed, awaiting review, needs backport to 2.7, needs backport to 3.7, skip issue, skip news

#13160 fix broken link in unicode docs
  Doc/howto/unicode.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#13099 bpo-36802: Drop awrite()/aclose(), support await write() and await close() instead
  Doc/library/asyncio-stream.rst
  Lib/asyncio/streams.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2019-05-05-10-12-23.bpo-36802.HYMc8P.rst
Labels: CLA signed, awaiting merge

#8154 bpo-32523: Simplifying news entries with multiple paragraphs.
  Misc/NEWS.d/3.5.0a2.rst
  Misc/NEWS.d/3.5.2rc1.rst
  Misc/NEWS.d/3.5.3rc1.rst
  Misc/NEWS.d/3.5.4rc1.rst
  Misc/NEWS.d/3.5.5rc1.rst
  Misc/NEWS.d/3.6.0a1.rst
  Misc/NEWS.d/3.6.0b2.rst
  Misc/NEWS.d/3.6.2rc1.rst
  Misc/NEWS.d/3.6.3rc1.rst
  Misc/NEWS.d/3.6.4rc1.rst
  Misc/NEWS.d/3.6.5rc1.rst
  Misc/NEWS.d/3.7.0a1.rst
  Misc/NEWS.d/3.7.0a2.rst
  Misc/NEWS.d/3.7.0a3.rst
  Misc/NEWS.d/3.7.0a4.rst
  Misc/NEWS.d/3.7.0b1.rst
  Misc/NEWS.d/3.7.0b2.rst
  Misc/NEWS.d/3.7.0b4.rst
Labels: CLA signed, awaiting merge, skip news

#13224 [3.7] bpo-10536: Enhancements to gettext docs (GH-10324)
  Doc/library/gettext.rst
  Misc/NEWS.d/next/Documentation/2018-11-04-22-03-56.bpo-10536.a0IsfE.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#13230 bpo-36778: cp65001 encoding becomes an alias to utf_8
  Doc/library/codecs.rst
  Lib/encodings/aliases.py
  Lib/encodings/cp65001.py
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Library/2019-05-10-01-06-36.bpo-36778.GRqeiS.rst
Labels: CLA signed, awaiting merge

#12784 bpo-36601: clarify signal handler comment and remove unnecessary pid check.
  Misc/NEWS.d/next/Core and Builtins/2019-04-13-16-14-16.bpo-36601.mIgS7t.rst
  Modules/signalmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge

#12306 bpo-27497: Add return value to csv.DictWriter.writeheader
  Doc/library/csv.rst
  Lib/csv.py
  Lib/test/test_csv.py
  Misc/NEWS.d/next/Library/2019-03-13-10-57-41.bpo-27497.JDmIe_.rst
Labels: CLA signed, awaiting merge

#13144 bpo-36814: ensure os.posix_spawnp handles Py_None
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Library/2019-05-06-23-13-26.bpo-36814.dSeMz_.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting change review

#13212 bpo-24538: Fix bug in shutil involving the copying of xattrs to read-only files.
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-05-09-08-35-18.bpo-24538.WK8Y-k.rst
Labels: CLA signed, awaiting merge

#13226 bpo-36676: Update "what's new" document.
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#13087 bpo-33071: remove outdated PyPI docs
  Doc/distutils/packageindex.rst
  Doc/distutils/setupscript.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#13235 [3.7] bpo-33071: remove outdated PyPI docs (GH-13087)
  Doc/distutils/packageindex.rst
  Doc/distutils/setupscript.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#13182 bpo-36869: Avoid warning of unused variables
  Objects/dictobject.c
Labels: CLA signed, awaiting review, skip news

#11841 bpo-35983: skip trashcan for subclasses
  Include/object.h
  Lib/test/test_capi.py
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-13-16-47-19.bpo-35983.bNxsXv.rst
  Modules/_elementtree.c
  Modules/_testcapimodule.c
  Objects/descrobject.c
  Objects/dictobject.c
  Objects/listobject.c
  Objects/odictobject.c
  Objects/setobject.c
  Objects/tupleobject.c
  Objects/typeobject.c
  Python/hamt.c
  Python/traceback.c
Labels: CLA signed, DO-NOT-MERGE, awaiting merge

#13159 bpo-36737: Use the module state C-API for warnings.
  Include/internal/pycore_pylifecycle.h
  Include/internal/pycore_pystate.h
  Misc/NEWS.d/next/Core and Builtins/2019-05-07-12-18-11.bpo-36737.XAo6LY.rst
  Python/_warnings.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting merge

#12483 bpo-36368: Ignore SIGINT in SharedMemoryManager servers.
  Lib/multiprocessing/managers.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2019-03-21-16-00-00.bpo-36368.zsRT1.rst
Labels: CLA signed, awaiting merge, type-bugfix

#13237 [3.7] bpo-34408: Prevent a null pointer dereference and resource leakage in `PyInterpreterState_New()` (GH-8767)
  Misc/NEWS.d/next/Core and Builtins/2018-08-14-22-35-19.bpo-34408.aomWYW.rst
  Python/pystate.c
Labels: CLA signed, awaiting core review

#13222 bpo-36867: Make semaphore_tracker track other system resources.
  Lib/multiprocessing/forkserver.py
  Lib/multiprocessing/popen_spawn_posix.py
  Lib/multiprocessing/resource_tracker.py
  Lib/multiprocessing/shared_memory.py
  Lib/multiprocessing/spawn.py
  Lib/multiprocessing/synchronize.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2019-05-09-18-12-55.bpo-36867.FuwVTi.rst
  PCbuild/lib.pyproj
Labels: CLA signed, awaiting merge

#12934 bpo-36710: Add 'ceval' local variable to ceval.c
  Include/ceval.h
  Include/internal/pycore_ceval.h
  Include/internal/pycore_pystate.h
  Modules/signalmodule.c
  Python/ceval.c
  Python/ceval_gil.h
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting core review, skip news

#13236 Fix sphinx deprecation warning about env.note_versionchange()
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#13242 bpo-21536: Fix What's New in Python 3.8 entry
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#6695 Docs: shutil: Hide module name from local (anchor) links
  Doc/library/shutil.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news
