Repository python/cpython, pull requests merged in 2019-03, with the labels that each got.

#12111 bpo-36142: Exclude coreconfig.h from Py_LIMITED_API
  Include/Python.h
  Include/cpython/coreconfig.h
  Include/cpython/pystate.h
  Include/internal/pycore_coreconfig.h
  Include/pystate.h
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2019-03-01-03-23-48.bpo-36142.7F6wJd.rst
  Modules/main.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/coreconfig.c
  Python/pathconfig.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting merge

#12114 bpo-36018: Add documentation link to "random variable"
  Doc/library/statistics.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#10994 [3.5] bpo-33127: Compatibility patch for LibreSSL 2.7.0 (GH-6210)
  Misc/NEWS.d/next/Library/2018-03-24-15-08-24.bpo-33127.olJmHv.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, type-bugfix

#12116 bpo-36155: Check for identity on test_gc.test_get_objects
  Lib/test/test_gc.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#12109 bpo-36152: IDLE: Remove unused parameter from colorizer
  Lib/idlelib/colorizer.py
  Lib/idlelib/editor.py
  Misc/NEWS.d/next/IDLE/2019-02-28-18-52-40.bpo-36152.9pkHIU.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7

#12119 [3.7] bpo-36152: IDLE: Remove unused parameter from colorizer (GH-12109)
  Lib/idlelib/colorizer.py
  Lib/idlelib/editor.py
  Misc/NEWS.d/next/IDLE/2019-02-28-18-52-40.bpo-36152.9pkHIU.rst
Labels: CLA signed, awaiting merge

#12113 bpo-36142: Rework error reporting in pymain_main()
  Include/cpython/coreconfig.h
  Include/cpython/pylifecycle.h
  Modules/main.c
  Programs/_freeze_importlib.c
  Programs/_testembed.c
  Python/frozenmain.c
  Python/pathconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge, skip news

#12120 bpo-36142: Remove _PyMain structure
  Include/cpython/coreconfig.h
  Lib/test/test_embed.py
  Modules/main.c
  Python/coreconfig.c
Labels: awaiting merge, skip news

#12098 bpo-36146: Fix inc_dirs in setup.py on macOS
  Misc/NEWS.d/next/Build/2019-02-28-18-09-01.bpo-36146.IwPJVT.rst
  setup.py
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.7

#12097 bpo-36146: Refactor setup.py: add add_ext() method
  setup.py
Labels: CLA signed, awaiting core review, skip news

#12124 bpo-36146: Refactor setup.py: Add PyBuildExt.srcdir
  setup.py
Labels: CLA signed, awaiting merge, skip news

#12123 bpo-36142: Move command line parsing to coreconfig.c
  Include/cpython/coreconfig.h
  Include/internal/pycore_coreconfig.h
  Include/internal/pycore_pathconfig.h
  Modules/main.c
  Python/coreconfig.c
Labels: CLA signed, awaiting merge, skip news

#12125 bpo-36146: Split setup.py into subfunctions
  setup.py
Labels: CLA signed, awaiting merge, skip news

#12127 bpo-36146: Don't run code at setup.py top level
  setup.py
Labels: CLA signed, awaiting merge, skip news

#12128 bpo-36142: Add preconfig.c
  Include/cpython/coreconfig.h
  Include/internal/pycore_coreconfig.h
  Include/internal/pycore_fileutils.h
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/coreconfig.c
  Python/preconfig.c
Labels: CLA signed, awaiting merge, skip news

#12033 bpo-35178: Ensure custom formatwarning function can receive line as positional argument
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2019-02-25-23-04-00.bpo-35178.NA_rXa.rst
Labels: CLA signed, awaiting merge

#12129 bpo-36146: Add TEST_EXTENSIONS to setup.py
  Misc/NEWS.d/next/Build/2019-03-01-17-49-22.bpo-36146.VeoyG7.rst
  setup.py
Labels: CLA signed, awaiting merge

#12130 [3.7] bpo-35178: Fix warnings._formatwarnmsg() (GH-12033)
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2019-02-25-23-04-00.bpo-35178.NA_rXa.rst
Labels: CLA signed, awaiting merge

#12024 bpo-33608: Use _Py_AddPendingCall() in _PyCrossInterpreterData_Release().
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news

#12062 bpo-33608: Simplify DISPATCH by hoisting eval_breaker ahead of time.
  Include/internal/pycore_atomic.h
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#11945 bpo-36043: FileCookieJar supports os.PathLike
  Doc/library/http.cookiejar.rst
  Lib/http/cookiejar.py
  Lib/test/test_http_cookiejar.py
  Misc/NEWS.d/next/Library/2019-02-19-19-53-46.bpo-36043.l867v0.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#12031 bpo-32129: Avoid blurry IDLE application icon on macOS with Tk 8.6.
  Lib/idlelib/pyshell.py
  Misc/NEWS.d/next/IDLE/2019-02-25-11-40-14.bpo-32129.4qVCzD.rst
Labels: CLA signed, OS-mac, awaiting merge, needs backport to 3.7

#12034 [2.7] bpo-32129: Avoid blurry IDLE application icon on macOS with Tk 8.6.
  Lib/idlelib/PyShell.py
  Misc/NEWS.d/next/IDLE/2019-02-25-12-59-24.bpo-32129.4qVCzD.rst
Labels: CLA signed, OS-mac, awaiting merge

#12133 [3.7] bpo-32129: Avoid blurry IDLE application icon on macOS with Tk 8.6. (GH-12031)
  Lib/idlelib/pyshell.py
  Misc/NEWS.d/next/IDLE/2019-02-25-11-40-14.bpo-32129.4qVCzD.rst
Labels: CLA signed, awaiting merge

#11814 bpo-35808: Retire pgen and use pgen2 to generate the parser
  .gitignore
  Include/metagrammar.h
  Include/parsetok.h
  Include/pgen.h
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2019-02-11-00-50-03.bpo-11814.M12CMH.rst
  Misc/coverity_model.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Parser/bitset.c
  Parser/firstsets.c
  Parser/grammar.c
  Parser/metagrammar.c
  Parser/parsetok.c
  Parser/parsetok_pgen.c
  Parser/pgen.c
  Parser/pgen/__init__.py
  Parser/pgen/__main__.py
  Parser/pgen/grammar.py
  Parser/pgen/pgen.py
  Parser/pgen/token.py
  Parser/pgenmain.c
  Parser/printgrammar.c
  Parser/tokenizer.c
  Parser/tokenizer.h
  Parser/tokenizer_pgen.c
  Python/graminit.c
Labels: CLA signed, awaiting merge

#12003 bpo-36097: Use only public C-API in the_xxsubinterpreters module (adding as necessary).
  Include/cpython/interpreteridobject.h
  Include/cpython/pystate.h
  Include/internal/pycore_pystate.h
  Include/interpreteridobject.h
  Makefile.pre.in
  Modules/_xxsubinterpretersmodule.c
  Objects/interpreteridobject.c
  Objects/object.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/pystate.c
  setup.py
Labels: CLA signed, awaiting merge, skip news

#12115 bpo-36103: change default buffer size of shutil.copyfileobj()
  Doc/library/shutil.rst
  Lib/shutil.py
  Misc/NEWS.d/next/Library/2019-03-01-16-10-01.bpo-36103.n6VgXL.rst
Labels: CLA signed, awaiting merge

#12136 Remove some code which has been dead since 1994
  Parser/grammar1.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#12057 Use symbolic names for `SEEK_SET`, etc, instead of hardcoding them
  Lib/_pyio.py
  Modules/_io/textio.c
Labels: CLA signed, awaiting review, skip issue, skip news

#11996 bpo-36091: remove reference to async generator in Lib/types.py
  Lib/types.py
  Misc/NEWS.d/next/Library/2019-02-23-06-49-06.bpo-36091.26o4Lc.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-bugfix

#12146 [3.7] bpo-36091: Remove reference to async generator in Lib/types.py. (GH-11996)
  Lib/types.py
  Misc/NEWS.d/next/Library/2019-02-23-06-49-06.bpo-36091.26o4Lc.rst
Labels: CLA signed, awaiting merge, type-bugfix

#12140 Duplicate test function in test_site
  Lib/test/test_site.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#12147 add missing break statement
  Modules/_io/textio.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#12039 [3.7] bpo-21478 - Autospec functions should propagate mock calls to parent GH-11273
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2018-12-21-09-54-30.bpo-21478.5gsXtc.rst
Labels: CLA signed, awaiting core review

#12143 bpo-36170: posix_spawn doesn't exist on 3.7
  Doc/library/os.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#11891 bpo-35899: Fix Enum handling of empty and weird strings
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2019-02-16-07-11-02.bpo-35899.cjfn5a.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7

#12152 [3.7] fixed duplicated method name of test_getuserbase() (GH-12140)
  Lib/test/test_site.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#12144 [3.5] bpo-33329: Fix multiprocessing regression on newer glibcs (GH-6…
  Misc/NEWS.d/next/Library/2018-04-23-13-21-39.bpo-33329.lQ-Eod.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#12145 [3.4] bpo-33329: Fix multiprocessing regression on newer glibcs (GH-6…
  Misc/NEWS.d/next/Library/2018-04-23-13-21-39.bpo-33329.lQ-Eod.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#12154 Fix typo in configparser doc
  Lib/configparser.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#8394 bpo-20906: Various revisions to the Unicode howto
  Doc/howto/unicode.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#12156 Clean implementation of Parser/pgen and fix pep8
  Parser/pgen/__main__.py
  Parser/pgen/grammar.py
  Parser/pgen/pgen.py
  Parser/pgen/token.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#12051 bpo-31904: Add encoding support for VxWorks RTOS
  Doc/c-api/sys.rst
  Doc/c-api/unicode.rst
  Doc/library/sys.rst
  Include/cpython/coreconfig.h
  Misc/NEWS.d/next/Core and Builtins/2019-02-26-17-34-49.bpo-31904.R4KSj6.rst
  Python/coreconfig.c
  Python/fileutils.c
Labels: CLA signed, awaiting review

#12155 [3.7] bpo-20906: Various revisions to the Unicode howto (GH-8394)
  Doc/howto/unicode.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12159 Revert: bpo-33608: Factor out a private, per-interpreter _Py_AddPendingCall(). (GH-11617)
  Include/ceval.h
  Include/cpython/interpreteridobject.h
  Include/cpython/pystate.h
  Include/internal/pycore_atomic.h
  Include/internal/pycore_ceval.h
  Include/internal/pycore_pystate.h
  Include/interpreteridobject.h
  Makefile.pre.in
  Modules/_testcapimodule.c
  Modules/_xxsubinterpretersmodule.c
  Modules/signalmodule.c
  Objects/interpreteridobject.c
  Objects/object.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/ceval.c
  Python/ceval_gil.h
  Python/pylifecycle.c
  Python/pystate.c
  setup.py
Labels: CLA signed, awaiting merge, skip news

#10437 bpo-35198 Fix C++ extension compilation on AIX
  Lib/distutils/unixccompiler.py
  Misc/NEWS.d/next/Library/2018-11-09-12-45-28.bpo-35198.EJ8keW.rst
Labels: CLA signed, awaiting review, needs backport to 3.7

#12162 [3.7] bpo-35198 Fix C++ extension compilation on AIX (GH-10437)
  Lib/distutils/unixccompiler.py
  Misc/NEWS.d/next/Library/2018-11-09-12-45-28.bpo-35198.EJ8keW.rst
Labels: CLA signed, awaiting merge

#12100 [2.7] bpo-13096: Fix partial backport of issue 13096.
  Misc/NEWS.d/next/Library/2019-03-04-16-13-01.bpo-13096.SGPt_n.rst
  Modules/_ctypes/callproc.c
Labels: CLA signed, awaiting merge

#12158 bpo-36179: Fix ref leaks in _hashopenssl
  Misc/NEWS.d/next/Library/2019-03-04-10-42-46.bpo-36179.jEyuI-.rst
  Modules/_hashopenssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7

#12164 [3.7] bpo-36179: Fix ref leaks in _hashopenssl (GH-12158)
  Misc/NEWS.d/next/Library/2019-03-04-10-42-46.bpo-36179.jEyuI-.rst
  Modules/_hashopenssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#12166 [2.7] bpo-36179: Fix ref leaks in _hashopenssl (GH-12158)
  Misc/NEWS.d/next/Library/2019-03-04-10-42-46.bpo-36179.jEyuI-.rst
  Modules/_hashopenssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#12170 Fixed a missing . and a missing capital letter
  Doc/library/subprocess.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#12105 [2.7] bpo-36149 Fix potential use of uninitialized memory in cPickle
  Misc/NEWS.d/next/Core and Builtins/2019-02-28-13-52-18.bpo-36149.GJdnh4.rst
  Modules/cPickle.c
Labels: CLA signed, awaiting merge

#12171 [3.7] Fixed a missing . and a missing capital letter. (GH-12170)
  Doc/library/subprocess.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12172 bpo-36142: Add _PyPreConfig structure
  Include/cpython/coreconfig.h
  Include/internal/pycore_coreconfig.h
  Modules/main.c
  Programs/_freeze_importlib.c
  Programs/_testembed.c
  Python/coreconfig.c
  Python/pathconfig.c
  Python/preconfig.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#12173 bpo-36142: Add _PyPreConfig_ReadFromArgv()
  Include/internal/pycore_coreconfig.h
  Include/internal/pycore_getopt.h
  Modules/main.c
  Python/coreconfig.c
  Python/getopt.c
  Python/pathconfig.c
  Python/preconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge, skip news

#12142 In compileall documentation, use `option` word for command line interface.
  Doc/library/compileall.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#12175 [3.7] Doc: Use `option` word for command line interface. (GH-12142)
  Doc/library/compileall.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12169 bpo-36188: Clean up 'unbound' method left-overs
  Doc/reference/datamodel.rst
  Misc/NEWS.d/next/Core and Builtins/2019-03-04-18-05-31.bpo-36188.EuUZNz.rst
  Objects/classobject.c
Labels: CLA signed, awaiting review

#10928 bpo-22831: Use "with" to avoid possible fd leaks in tests (part 1).
  Lib/test/test_dbm_dumb.py
  Lib/test/test_mmap.py
  Lib/test/test_socket.py
  Lib/test/test_tarfile.py
  Lib/test/test_zipfile64.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#10929 bpo-22831: Use "with" to avoid possible fd leaks in tests (part 2).
  Lib/test/support/__init__.py
  Lib/test/support/script_helper.py
  Lib/test/test_argparse.py
  Lib/test/test_binhex.py
  Lib/test/test_bool.py
  Lib/test/test_codecs.py
  Lib/test/test_epoll.py
  Lib/test/test_float.py
  Lib/test/test_ioctl.py
  Lib/test/test_os.py
  Lib/test/test_pipes.py
  Lib/test/test_poll.py
  Lib/test/test_random.py
  Lib/test/test_runpy.py
  Lib/test/test_select.py
  Lib/test/test_shelve.py
  Lib/test/test_site.py
  Lib/test/test_socketserver.py
  Lib/test/test_tempfile.py
  Lib/test/test_threading.py
  Lib/test/test_urllib2.py
  Lib/test/test_urllib2_localnet.py
  Lib/test/test_xmlrpc.py
  Lib/test/test_zipimport.py
  Lib/test/test_zipimport_support.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#12174 bpo-36142: Add _PyPreConfig.utf8_mode
  Include/cpython/coreconfig.h
  Include/internal/pycore_coreconfig.h
  Programs/_testembed.c
  Python/coreconfig.c
  Python/preconfig.c
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#12177 [2.7] bpo-36019: Use pythontest.net instead of example.com in network tests (GH-11941)
  Doc/library/test.rst
  Lib/test/support/__init__.py
  Lib/test/test_urllib2net.py
  Lib/test/test_urllibnet.py
  Misc/NEWS.d/next/Tests/2019-03-05-13-27-36.bpo-36019.ebUjCm.rst
Labels: CLA signed, awaiting merge, type-tests

#12179 bpo-33012: Fix compilation warnings for memoryview.tobytes and _collections._tuplegetter.__reduce__
  Modules/_collectionsmodule.c
  Objects/memoryobject.c
Labels: CLA signed, awaiting review, skip news

#12178 [3.7] bpo-29571: Fix test_re.test_locale_flag()
  Lib/test/test_re.py
  Misc/NEWS.d/next/Tests/2019-03-05-13-48-39.bpo-29571.ecGuKR.rst
Labels: CLA signed, awaiting merge, type-tests

#12181 bpo-36142: Add _PyPreConfig.allocator
  Include/cpython/coreconfig.h
  Lib/test/test_embed.py
  Programs/_testembed.c
  Python/coreconfig.c
  Python/preconfig.c
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#12180 Fix the C function signature for _collections._tuplegetter.__reduce__.
  Modules/_collectionsmodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#12167 bpo-36187: Remove NamedStore.
  Include/Python-ast.h
  Lib/test/test_syntax.py
  Parser/Python.asdl
  Python/Python-ast.c
  Python/ast.c
  Python/compile.c
  Python/symtable.c
Labels: CLA signed, awaiting merge, skip news

#12185 bpo-36142: Add _PyMem_GetDebugAllocatorsName()
  Include/internal/pycore_pymem.h
  Lib/test/test_embed.py
  Objects/obmalloc.c
  Programs/_testembed.c
  Python/preconfig.c
Labels: CLA signed, skip news

#12186 bpo-36142: _PyPreConfig_Write() sets the allocator
  Include/internal/pycore_coreconfig.h
  Modules/main.c
  Python/preconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge, skip news

#12187 bpo-36142: Add _PyPreConfig_SetAllocator()
  Include/internal/pycore_coreconfig.h
  Include/internal/pycore_pymem.h
  Lib/test/test_embed.py
  Modules/main.c
  Objects/obmalloc.c
  Python/preconfig.c
  Python/pylifecycle.c
Labels: CLA signed, skip news

#12188 bpo-36142: _PyPreConfig_Read() sets LC_CTYPE
  Include/internal/pycore_coreconfig.h
  Python/coreconfig.c
  Python/preconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge, skip news

#12190 Add more tests for pdf() and cdf()
  Lib/test/test_statistics.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-tests

#12191 bpo-36142: PYTHONMALLOC overrides PYTHONDEV
  Lib/test/test_embed.py
  Programs/_testembed.c
  Python/preconfig.c
Labels: CLA signed, awaiting merge, skip news

#12163 [2.7] bpo-36186: Fix leak of handle in linuxaudiodev
  Misc/NEWS.d/next/Library/2019-03-04-16-39-16.bpo-36186.Hqw1A_.rst
  Modules/linuxaudiodev.c
Labels: CLA signed

#12194 bpo-36209: Fix Typo on hashlib
  Modules/_hashopenssl.c
Labels: CLA signed, skip news

#12196 [3.7] bpo-36209: Fix typo on hashlib error message (GH-12194)
  Modules/_hashopenssl.c
Labels: CLA signed, awaiting merge, skip news

#12073 bpo-36139: release GIL around munmap()
  Misc/NEWS.d/next/Library/2019-03-06-13-07-29.bpo-36139.6kedum.rst
  Modules/mmapmodule.c
Labels: CLA signed, awaiting review

#11010 bpo-32805: Fix compiler warnings in gcmodule.c
  Include/pydtrace.h
Labels: CLA signed, awaiting merge, skip news

#12199 bpo-36139: release GIL around munmap()
  Modules/mmapmodule.c
Labels: CLA signed, awaiting merge, skip news

#12204 bpo-36185: typo: Doc/c-api/objbuffer.rst
  Doc/c-api/objbuffer.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12176 Remove 's' mention as there's no argument for set.copy()
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, needs backport to 2.7, needs backport to 3.7, skip issue, skip news, type-documentation

#12205 [3.7] bpo-36185: Fix typo in Doc/c-api/objbuffer.rst. (GH-12204)
  Doc/c-api/objbuffer.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#12207 [2.7] Fix the documentation for set.copy() (GH-12176)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12206 [3.7] Fix the documentation for set.copy() (GH-12176)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12149 bpo-36169 : Add overlap() method to statistics.NormalDist
  Doc/library/statistics.rst
  Lib/statistics.py
  Lib/test/test_statistics.py
  Misc/NEWS.d/next/Library/2019-03-03-11-37-09.bpo-36169.8nWJy7.rst
Labels: CLA signed, awaiting merge

#12208 Refine statistics.NormalDist documentation and improve test coverage
  Doc/library/statistics.rst
  Lib/test/test_statistics.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation, type-tests

#12201 bpo-36216: Add check for characters in netloc that normalize to separators
  Doc/library/urllib.parse.rst
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2019-03-06-09-38-40.bpo-36216.6q1m4a.rst
Labels: CLA signed, awaiting merge, type-security

#12218 NormalDist.overlap() only needs one example
  Doc/library/statistics.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12213 [3.7] bpo-36216: Add check for characters in netloc that normalize to separators (GH-12201)
  Doc/library/urllib.parse.rst
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2019-03-06-09-38-40.bpo-36216.6q1m4a.rst
Labels: CLA signed, awaiting merge, type-security

#12216 [2.7] bpo-36216: Add check for characters in netloc that normalize to separators (GH-12201)
  Doc/library/urlparse.rst
  Lib/test/test_urlparse.py
  Lib/urlparse.py
  Misc/NEWS.d/next/Security/2019-03-06-09-38-40.bpo-36216.6q1m4a.rst
Labels: CLA signed, awaiting merge, type-security

#12217 bpo-36108: Avoid failing the build on race condition in clean
  PCbuild/openssl.props
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.7, skip news

#12219 [3.7] bpo-36108: Avoid failing the build on race condition in clean (GH-12217)
  PCbuild/openssl.props
Labels: CLA signed, awaiting merge, skip news

#12074 bpo-36140: Fix an incorrect check in msidb_getsummaryinformation()
  PC/_msi.c
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.7, skip news

#12221 [3.7] bpo-36140: Fix an incorrect check in msidb_getsummaryinformation() (GH-12074)
  PC/_msi.c
Labels: CLA signed, awaiting merge, skip news

#12222 [2.7] bpo-36140: Fix an incorrect check in msidb_getsummaryinformation() (GH-12074)
  PC/_msi.c
Labels: CLA signed, awaiting merge, skip news

#12086 bpo-35975: Support parsing earlier minor versions of Python 3
  Doc/library/ast.rst
  Doc/library/token-list.inc
  Doc/library/token.rst
  Grammar/Grammar
  Grammar/Tokens
  Include/Python-ast.h
  Include/compile.h
  Include/parsetok.h
  Include/token.h
  Lib/ast.py
  Lib/keyword.py
  Lib/test/test_parser.py
  Lib/test/test_type_comments.py
  Lib/token.py
  Misc/NEWS.d/next/Core and Builtins/2019-02-27-16-49-08.bpo-35975.IescLY.rst
  Modules/main.c
  Modules/parsermodule.c
  Parser/asdl_c.py
  Parser/parsetok.c
  Parser/token.c
  Parser/tokenizer.c
  Parser/tokenizer.h
  Python/Python-ast.c
  Python/ast.c
  Python/bltinmodule.c
  Python/clinic/bltinmodule.c.h
  Python/compile.c
  Python/graminit.c
  Python/pythonrun.c
Labels: :robot: automerge, CLA signed, awaiting merge

#12227 Fix typo (double 'the') in CODEOWNERS
  .github/CODEOWNERS
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#12229 [3.7] Fix typo (double 'the') in CODEOWNERS (GH-12227)
  .github/CODEOWNERS
Labels: CLA signed, awaiting merge, skip issue, skip news

#12231 [2.7] IDLE: Fix typo in keybindingDialog.py (GH-2322)
  Lib/idlelib/keybindingDialog.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#12232 bpo-34162: Add entries for idlelib/NEWS.txt
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting merge, needs backport to 3.7, skip news, type-documentation

#12233 [3.7] bpo-34162: Add entries for idlelib/NEWS.txt (GH-12232)
  Lib/idlelib/NEWS.txt
Labels: CLA signed, awaiting merge, skip news, type-documentation

#11690 bpo-35843: Implement __getitem__ for _NamespacePath
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_importlib/test_namespace_pkgs.py
  Misc/NEWS.d/next/Library/2019-01-28-10-19-40.bpo-35843.7rXGQE.rst
  Python/importlib_external.h
Labels: :robot: automerge, CLA signed, awaiting merge

#12240 bpo-33608: Fix the Py_atomic_* macros.
  Include/internal/pycore_atomic.h
Labels: CLA signed, awaiting merge, skip news

#12150 [3.7] bpo-35899: Fix Enum handling of empty and weird strings (GH-11891)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2019-02-16-07-11-02.bpo-35899.cjfn5a.rst
Labels: CLA signed, awaiting merge

#11440 bpo-35661: Store the venv prompt in pyvenv.cfg
  Lib/test/test_venv.py
  Lib/venv/__init__.py
  Misc/NEWS.d/next/Library/2019-01-05-16-16-20.bpo-35661.H_UOXc.rst
Labels: CLA signed, awaiting merge

#12243 bpo-33608: Simplify DISPATCH by hoisting eval_breaker ahead of time.
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#12247 bpo-33608: Minor cleanup related to pending calls.
  Include/internal/pycore_ceval.h
  Include/internal/pycore_pystate.h
  Python/ceval.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news

#12245 bpo-33608: Make sure locks in the runtime are properly re-created.
  Include/internal/pycore_pystate.h
  Modules/posixmodule.c
  Python/ceval.c
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news

#12249 Make a documentation link target more specific
  Doc/library/statistics.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12212 d_initial is not used by the parser, so no point generating it
  Include/grammar.h
  Modules/parsermodule.c
  Parser/pgen/grammar.py
  Python/graminit.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#12210 Fix typos and improve grammar in threading.Barrier docstrings
  Lib/threading.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news

#12254 [3.7] Fix typos and improve grammar in threading.Barrier docstrings (GH-12210)
  Lib/threading.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#11809 bpo-35959: Rework integer overflow path in math.prod and add more tests
  Lib/test/test_math.py
  Modules/mathmodule.c
Labels: CLA signed, awaiting core review, skip news

#12256 closes bpo-33376: Update to Unicode 12.0.0.
  Doc/library/stdtypes.rst
  Doc/library/unicodedata.rst
  Doc/reference/lexical_analysis.rst
  Doc/whatsnew/3.8.rst
  Lib/test/test_unicodedata.py
  Misc/NEWS.d/next/Core and Builtins/2019-03-09-15-47-05.bpo-36252.sCQFKq.rst
  Modules/unicodedata_db.h
  Modules/unicodename_db.h
  Objects/unicodetype_db.h
  Tools/unicode/makeunicodedata.py
Labels: CLA signed, awaiting merge

#10258 bpo-35121: prefix dot in domain for proper subdomain validation
  Lib/http/cookiejar.py
  Lib/test/test_http_cookiejar.py
  Misc/NEWS.d/next/Security/2018-10-31-15-39-17.bpo-35121.EgHv9k.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-security

#12261 [3.7] bpo-35121: prefix dot in domain for proper subdomain validation (GH-10258)
  Lib/http/cookiejar.py
  Lib/test/test_http_cookiejar.py
  Misc/NEWS.d/next/Security/2018-10-31-15-39-17.bpo-35121.EgHv9k.rst
Labels: CLA signed, awaiting review, type-security

#12260 [3.6] bpo-35121: prefix dot in domain for proper subdomain validation (GH-10258)
  Lib/http/cookiejar.py
  Lib/test/test_http_cookiejar.py
  Misc/NEWS.d/next/Security/2018-10-31-15-39-17.bpo-35121.EgHv9k.rst
Labels: CLA signed, awaiting review, type-security

#12252 bpo-36251: Fix format strings used in match_repr() and stdprinter_repr()
  Misc/NEWS.d/next/Library/2019-03-09-18-01-24.bpo-36251.zOp9l0.rst
  Modules/_sre.c
  Objects/fileobject.c
Labels: CLA signed, awaiting merge

#12263 [3.7] bpo-36251: Fix format strings used in match_repr() and stdprinter_repr(). (GH-12252)
  Misc/NEWS.d/next/Library/2019-03-09-18-01-24.bpo-36251.zOp9l0.rst
  Modules/_sre.c
  Objects/fileobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#12258 Fix padding on asyncio.IncompleteReadError docs
  Doc/library/asyncio-exceptions.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, skip issue, skip news, type-documentation

#12265 [3.7] Fix padding on asyncio.IncompleteReadError docs (GH-12258)
  Doc/library/asyncio-exceptions.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#10641 bpo-21314: Add a FAQ entry about positional only parameters
  Doc/faq/programming.rst
  Doc/library/functions.rst
  Doc/library/inspect.rst
  Misc/NEWS.d/next/Documentation/2018-11-21-23-01-37.bpo-21314.PG33VT.rst
Labels: CLA signed, awaiting review, needs backport to 3.7, type-documentation

#12266 [3.7] bpo-21314: Add a FAQ entry about positional only parameters (GH-10641)
  Doc/faq/programming.rst
  Doc/library/functions.rst
  Doc/library/inspect.rst
  Misc/NEWS.d/next/Documentation/2018-11-21-23-01-37.bpo-21314.PG33VT.rst
Labels: CLA signed, awaiting merge, type-documentation

#11436 bpo-35647: Fix path check in cookiejar
  Lib/http/cookiejar.py
  Lib/test/test_http_cookiejar.py
  Misc/NEWS.d/next/Library/2018-12-30-14-35-19.bpo-35121.oWmiGU.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, type-security

#12267 [3.7] bpo-35647: Fix path check in cookiejar (GH-11436)
  Lib/http/cookiejar.py
  Lib/test/test_http_cookiejar.py
  Misc/NEWS.d/next/Library/2018-12-30-14-35-19.bpo-35121.oWmiGU.rst
Labels: CLA signed, awaiting merge, type-security

#12262 bpo-36176: Fix IDLE autocomplete & calltip popup colors.
  Lib/idlelib/NEWS.txt
  Lib/idlelib/autocomplete_w.py
  Lib/idlelib/calltip_w.py
  Misc/NEWS.d/next/IDLE/2019-03-10-00-07-46.bpo-36176.jk_vv6.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-bugfix

#12269 [3.7] bpo-36176: Fix IDLE autocomplete & calltip popup colors. (GH-12262)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/autocomplete_w.py
  Lib/idlelib/calltip_w.py
  Misc/NEWS.d/next/IDLE/2019-03-10-00-07-46.bpo-36176.jk_vv6.rst
Labels: CLA signed, awaiting merge, type-bugfix

#12224 [3.4] bpo-36216: Add check for characters in netloc that normalize to separators (GH-12201)
  Doc/library/urllib.parse.rst
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2019-03-06-09-38-40.bpo-36216.6q1m4a.rst
Labels: CLA signed, awaiting merge, type-security

#12223 [3.5] bpo-36216: Add check for characters in netloc that normalize to separators (GH-12201)
  Doc/library/urllib.parse.rst
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2019-03-06-09-38-40.bpo-36216.6q1m4a.rst
Labels: CLA signed, awaiting merge, type-security

#12272 Various refinements to the NormalDist examples and recipes
  Doc/library/statistics.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#12234 bpo-36234: Add more tests to PosixUidGidTests
  Lib/test/test_os.py
  Misc/NEWS.d/next/Tests/2019-03-08-12-53-37.bpo-36234.NRVK6W.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, type-tests

#12235 [2.7] bpo-36234: test_os: check TypeError for invalid uid type
  Lib/test/test_os.py
  Misc/NEWS.d/next/Tests/2019-03-08-12-53-37.bpo-36234.NRVK6W.rst
Labels: CLA signed, awaiting merge, type-tests

#12274 [3.7] bpo-36234: Add more tests to PosixUidGidTests (GH-12234)
  Lib/test/test_os.py
  Misc/NEWS.d/next/Tests/2019-03-08-12-53-37.bpo-36234.NRVK6W.rst
Labels: CLA signed, awaiting merge, type-tests

#12273 Multiprocessing port inconsistency
  Doc/library/multiprocessing.rst
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.7, skip issue, skip news

#12275 [3.7] Doc: Fix inconsistency in multiprocessing (GH-12273)
  Doc/library/multiprocessing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#11848 bpo-35132: Fixes missing target in gdb pep0393 check.
  Misc/NEWS.d/next/Tools-Demos/2019-03-04-02-09-09.bpo-35132.1R_pnL.rst
  Tools/gdb/libpython.py
Labels: CLA signed, needs backport to 3.7

#12103 bpo-35931: Gracefully handle any exception in pdb debug command
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2019-03-11-22-06-36.bpo-35931.Qp_Tbe.rst
Labels: :robot: automerge, CLA signed, needs backport to 3.7

#12285 [3.7] bpo-35931: Gracefully handle any exception in pdb debug command (GH-12103)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2019-02-07-16-22-50.bpo-35931._63i7B.rst
  Misc/NEWS.d/next/Library/2019-03-11-22-06-36.bpo-35931.Qp_Tbe.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#12268 [3.6] bpo-35647: Fix path check in cookiejar (GH-11436)
  Lib/http/cookiejar.py
  Lib/test/test_http_cookiejar.py
  Misc/NEWS.d/next/Library/2018-12-30-14-35-19.bpo-35121.oWmiGU.rst
Labels: CLA signed, type-security

#12215 [3.6] bpo-36216: Add check for characters in netloc that normalize to separators (GH-12201)
  Doc/library/urllib.parse.rst
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2019-03-06-09-38-40.bpo-36216.6q1m4a.rst
Labels: CLA signed, awaiting merge, type-security

#12089 bpo-35892: Fix mode() and add multimode()
  Doc/library/statistics.rst
  Doc/whatsnew/3.8.rst
  Lib/statistics.py
  Lib/test/test_statistics.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-enhancement

#1080 bpo-30040: New empty dict uses key-sharing dict.
  Lib/test/test_descr.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2019-03-11-22-30-56.bpo-30040.W9z8X7.rst
  Objects/dictobject.c
Labels: CLA signed, type-enhancement

#12286 canonicalize "Inada Naoki" in Misc/ACKS and 3.8 news.
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-03-01-16-10-01.bpo-36103.n6VgXL.rst
Labels: CLA signed, skip issue, skip news

#12284 [3.7] bpo-35132: Fixes missing target in gdb pep0393 check. (GH-11848)
  Misc/NEWS.d/next/Tools-Demos/2019-03-04-02-09-09.bpo-35132.1R_pnL.rst
  Tools/gdb/libpython.py
Labels: CLA signed

#12282 bpo-36264: Don't honor POSIX `HOME` in `os.path.expanduser` on windows
  Lib/distutils/tests/test_config.py
  Lib/distutils/tests/test_dist.py
  Lib/ntpath.py
  Lib/test/test_netrc.py
  Lib/test/test_ntpath.py
  Misc/NEWS.d/next/Windows/2019-03-11-09-33-47.bpo-36264.rTzWce.rst
Labels: CLA signed, awaiting review

#12292 [3.7] Minor edits to news entries for 3.7.3
  Misc/NEWS.d/next/Core and Builtins/2019-02-18-09-30-55.bpo-35942.oLhL2v.rst
  Misc/NEWS.d/next/IDLE/2018-12-21-18-44-30.bpo-35555.M58_K3.rst
  Misc/NEWS.d/next/macOS/2018-12-21-18-44-30.bpo-35555.M58_K3.rst
Labels: awaiting merge, skip issue, skip news, type-documentation

#12293 Minor edits to news entries (ported from 3.7)
  Misc/NEWS.d/3.8.0a1.rst
  Misc/NEWS.d/3.8.0a2.rst
Labels: skip issue, skip news, type-documentation

#12291 [2.7] bpo-36216: Only print test messages when verbose (GH-12291)
  Lib/test/test_urlparse.py
Labels: awaiting merge, skip news, type-bugfix, type-tests

#12294 bpo-36264: Updates documentation for change to expanduser on Windows
  Doc/library/os.path.rst
  Doc/whatsnew/3.8.rst
Labels: CLA signed, OS-windows, awaiting core review, skip news, type-documentation
