Repository python/cpython, pull requests merged in 2020-07, with the labels that each got.

#21198 Doc: Minor fix to C API documentation
  Doc/c-api/init_config.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21255 [3.9] Doc: Minor fix to init config C API documentation (GH-21198)
  Doc/c-api/init_config.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21254 [3.8] Doc: Minor fix to init config C API documentation (GH-21198)
  Doc/c-api/init_config.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21252 Add lysnikolaou to CODEOWNERS for the new parser
  .github/CODEOWNERS
Labels: CLA signed, awaiting merge, skip issue, skip news

#21253 [3.9] Add lysnikolaou to CODEOWNERS for the new parser
  .github/CODEOWNERS
Labels: CLA signed, awaiting merge, skip issue, skip news

#21260 [3.9] bpo-41158: IDLE: rewrite the code for handling file encoding (GH-21215)
  Lib/idlelib/iomenu.py
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#21267 [3.8] bpo-41158: IDLE: rewrite the code for handling file encoding (GH-21215)
  Lib/idlelib/iomenu.py
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#21264 bpo-41187: Convert the _msi module to Argument Clinic
  PC/_msi.c
  PC/clinic/_msi.c.h
Labels: CLA signed, awaiting core review, skip news, type-enhancement

#18067 bpo-39385: Add an assertNoLogs context manager to unittest.TestCase (GH-18067)
  Doc/library/unittest.rst
  Lib/unittest/_log.py
  Lib/unittest/case.py
  Lib/unittest/test/test_case.py
  Misc/NEWS.d/next/Library/2020-04-23-18-21-19.bpo-39385.MIAyS7.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#21265 bpo-40521: Cleanup finalize_interp_types()
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#21269 bpo-1635741: Release Unicode interned strings at exit
  Include/internal/pycore_pylifecycle.h
  Objects/unicodeobject.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#20874 bpo-40967: Remove deprecated asyncio.Task.current_task() and asyncio.Task.all_tasks()
  Doc/library/asyncio-task.rst
  Doc/whatsnew/3.9.rst
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2020-06-15-00-13-57.bpo-40967._dx3OO.rst
  Modules/_asynciomodule.c
  Modules/clinic/_asynciomodule.c.h
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9

#21272 [3.9] bpo-40967: Remove deprecated asyncio.Task.current_task() and asyncio.Task.all_tasks() (GH-20874)
  Doc/library/asyncio-task.rst
  Doc/whatsnew/3.9.rst
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2020-06-15-00-13-57.bpo-40967._dx3OO.rst
  Modules/_asynciomodule.c
  Modules/clinic/_asynciomodule.c.h
Labels: CLA signed, awaiting merge

#21274 [3.8] 3.8.3 -> 3.8.4 in macOS installer ReadMe
  Mac/BuildScript/resources/ReadMe.rtf
Labels: CLA signed, awaiting core review, skip issue, skip news

#21275 [3.9] bpo-41043: Escape literal part of the path for glob(). (GH-20994).
  Lib/distutils/command/build_py.py
  Lib/idlelib/tree.py
  Lib/imghdr.py
  Lib/pdb.py
  Lib/sndhdr.py
  Lib/test/_test_multiprocessing.py
  Lib/test/libregrtest/main.py
  Lib/test/support/__init__.py
  Lib/test/test_bz2.py
  Lib/test/test_crashers.py
  Lib/test/test_dbm.py
  Lib/test/test_import/__init__.py
  Lib/test/test_mailbox.py
  Lib/test/test_regrtest.py
  Lib/test/test_site.py
  Lib/test/test_tokenize.py
  Lib/test/test_unicode_file.py
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2020-06-20-00-19-30.bpo-41043.p-Pk-H.rst
  Tools/c-analyzer/c_analyzer/common/files.py
  Tools/c-analyzer/check-c-globals.py
  Tools/peg_generator/scripts/test_parse_directory.py
  Tools/ssl/make_ssl_data.py
  setup.py
Labels: CLA signed, awaiting core review, type-bugfix

#21277 [3.8] bpo-41043: Escape literal part of the path for glob(). (GH-20994).
  Lib/distutils/command/build_py.py
  Lib/idlelib/tree.py
  Lib/imghdr.py
  Lib/pdb.py
  Lib/sndhdr.py
  Lib/test/_test_multiprocessing.py
  Lib/test/libregrtest/main.py
  Lib/test/support/__init__.py
  Lib/test/test_bz2.py
  Lib/test/test_crashers.py
  Lib/test/test_dbm.py
  Lib/test/test_import/__init__.py
  Lib/test/test_mailbox.py
  Lib/test/test_regrtest.py
  Lib/test/test_site.py
  Lib/test/test_tokenize.py
  Lib/test/test_unicode_file.py
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2020-06-20-00-19-30.bpo-41043.p-Pk-H.rst
  Tools/c-globals/check-c-globals.py
  Tools/ssl/make_ssl_data.py
  setup.py
Labels: CLA signed, awaiting core review, type-bugfix

#21258 [3.5] bpo-41183: Update test certs and keys
  Lib/test/allsans.pem
  Lib/test/keycert.passwd.pem
  Lib/test/keycert.pem
  Lib/test/keycert2.pem
  Lib/test/keycert3.pem
  Lib/test/keycert4.pem
  Lib/test/make_ssl_certs.py
  Lib/test/pycacert.pem
  Lib/test/pycakey.pem
  Lib/test/revocation.crl
  Lib/test/ssl_cert.pem
  Lib/test/ssl_key.passwd.pem
  Lib/test/ssl_key.pem
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2020-07-01-16-59-46.bpo-41183.9stVAW.rst
Labels: CLA signed, awaiting core review

#21279 bpo-41193: Ignore OSError in readline write_history()
  Lib/site.py
  Misc/NEWS.d/next/Library/2020-07-02-11-53-45.bpo-41193.8-Tnql.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9

#21281 [3.8] bpo-41193: Ignore OSError in readline write_history() (GH-21279)
  Lib/site.py
  Misc/NEWS.d/next/Library/2020-07-02-11-53-45.bpo-41193.8-Tnql.rst
Labels: CLA signed, awaiting merge

#21280 [3.9] bpo-41193: Ignore OSError in readline write_history() (GH-21279)
  Lib/site.py
  Misc/NEWS.d/next/Library/2020-07-02-11-53-45.bpo-41193.8-Tnql.rst
Labels: CLA signed, awaiting merge

#21278 [3.5] bpo-41183: Update finite DH params to 3072 bits
  Lib/test/dh1024.pem
  Lib/test/ffdh3072.pem
  Lib/test/test_ssl.py
Labels: CLA signed, awaiting core review, skip news

#21286 Remove extraneous file from the Docs folder
  Doc/myfile.bz2
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news

#21287 [3.9] Remove extraneous file from the Docs folder (GH-21286)
  Doc/myfile.bz2
Labels: CLA signed, awaiting merge, skip issue, skip news

#21092 bpo-39960: Allow heap types in the "Carlo Verre" hack check that override "tp_setattro()"
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2020-06-23-18-32-41.bpo-39960.Kez3fP.rst
  Modules/_testcapimodule.c
  Objects/typeobject.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21288 [3.9] bpo-39960: Allow heap types in the "Carlo Verre" hack check that override "tp_setattro()" (GH-21092)
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2020-06-23-18-32-41.bpo-39960.Kez3fP.rst
  Modules/_testcapimodule.c
  Objects/typeobject.c
Labels: CLA signed, awaiting merge

#21163 [3.9] Improve code organization for the random module (GH-21161)
  Lib/random.py
Labels: CLA signed, awaiting review, skip issue, skip news

#21189 bpo-1635741: Port sha256 module to multiphase init (PEP 489)
  Misc/NEWS.d/next/Core and Builtins/2020-07-01-20-17-38.bpo-1635741.-AtPYu.rst
  Modules/sha256module.c
Labels: CLA signed, awaiting merge

#21284 bpo-41194: Pass module state in Python-ast.c
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting core review, skip news

#21290 bpo-41194: The _ast module cannot be loaded more than once
  Misc/NEWS.d/next/Library/2020-07-03-13-15-08.bpo-41194.djrKjs.rst
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting core review

#21292 [3.9] bpo-41194: The _ast module cannot be loaded more than once (GH-21290)
  Misc/NEWS.d/next/Library/2020-07-03-13-15-08.bpo-41194.djrKjs.rst
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting core review

#21270 bpo-1635741: Fix unicode_dealloc() for mortal interned string
  Objects/unicodeobject.c
Labels: CLA signed, awaiting core review, skip news

#21294 bpo-1635741: Port faulthandler module to multiphase initialization
  Misc/NEWS.d/next/Core and Builtins/2020-07-03-23-10-02.bpo-1635741.F5coWe.rst
  Modules/faulthandler.c
Labels: CLA signed, awaiting merge

#21293 bpo-41194: Convert _ast extension to PEP 489
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting merge, skip news

#21271 bpo-41180: Audit code.__new__ when unmarshalling
  Python/marshal.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news

#21222 bpo-41162: Clear audit hooks after destructors
  Lib/test/audit-tests.py
  Lib/test/test_audit.py
  Misc/NEWS.d/next/Security/2020-07-03-20-41-29.bpo-41162.tb8pVj.rst
  Programs/_testembed.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9

#21300 [3.8] bpo-41180: Audit code.__new__ when unmarshalling (GH-21271)
  Python/marshal.c
Labels: CLA signed, awaiting merge, skip news

#21301 [3.9] bpo-41180: Audit code.__new__ when unmarshalling (GH-21271)
  Python/marshal.c
Labels: CLA signed, awaiting merge, skip news

#21302 [3.9] bpo-41162: Clear audit hooks later during finalization (GH-21222)
  Lib/test/audit-tests.py
  Lib/test/test_audit.py
  Misc/NEWS.d/next/Security/2020-07-03-20-41-29.bpo-41162.tb8pVj.rst
  Programs/_testembed.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, needs backport to 3.8

#21304 [3.9] bpo-41162: Fix improperly merged change so that final hooks are called before types are cleared
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#21303 [3.8] bpo-41162: Clear audit hooks later during finalization (GH-21222)
  Lib/test/audit-tests.py
  Lib/test/test_audit.py
  Misc/NEWS.d/next/Security/2020-07-03-20-41-29.bpo-41162.tb8pVj.rst
  Programs/_testembed.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review

#21311 bpo-33864: Clarify the docs for typing.ByteString
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21312 [3.9] bpo-33864: Clarify the docs for typing.ByteString (GH-21311)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21313 [3.8] bpo-33864: Clarify the docs for typing.ByteString (GH-21311)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21307 bpo-41204: Fix compiler warning in ast_type_init()
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#21318 Uncomment Py_DEPRECATED for Py_UNICODE APIs
  Include/cpython/unicodeobject.h
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news

#21323 [3.9] Uncomment Py_DEPRECATED for Py_UNICODE APIs (GH-21318)
  Include/cpython/unicodeobject.h
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#21325 bpo-41211: Doc: Fix PyLong_FromUnicodeObject
  Doc/c-api/long.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-bugfix, type-documentation

#21328 [3.9] bpo-41211: Doc: Fix PyLong_FromUnicodeObject (GH-21325)
  Doc/c-api/long.rst
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-documentation

#21329 [3.8] bpo-41211: Doc: Fix PyLong_FromUnicodeObject (GH-21325)
  Doc/c-api/long.rst
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-documentation

#21327 bpo-39168: Remove the __new__ method of typing.Generic
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2020-07-04-21-56-46.bpo-39168.DQWsXj.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#21331 [3.9] bpo-41211: Doc: Fix PyLong_FromUnicode
  Doc/c-api/long.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-bugfix, type-documentation

#21332 [3.8] bpo-41211: Doc: Fix PyLong_FromUnicode (GH-21331)
  Doc/c-api/long.rst
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-documentation

#21336 bpo-36346: Undeprecate private function _PyUnicode_AsUnicode().
  Include/cpython/unicodeobject.h
  Misc/NEWS.d/next/C API/2020-06-17-11-24-00.bpo-36346.fTMr3S.rst
  Modules/clinic/posixmodule.c.h
  Objects/unicodeobject.c
  PC/_msi.c
  PC/clinic/_msi.c.h
  PC/clinic/winreg.c.h
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting core review

#21335 [3.9] bpo-39168: Remove the __new__ method of typing.Generic (GH-21327)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2020-07-04-21-56-46.bpo-39168.DQWsXj.rst
Labels: CLA signed, awaiting merge

#21339 [3.8] bpo-39960: Allow heap types in the "Carlo Verre" hack check that override "tp_setattro()" (GH-21092)
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2020-06-23-18-32-41.bpo-39960.Kez3fP.rst
  Modules/_testcapimodule.c
  Objects/typeobject.c
Labels: CLA signed, awaiting core review

#21338 bpo-29727: Register array.array as a MutableSequence
  Lib/test/test_array.py
  Misc/NEWS.d/next/Library/2020-07-05-19-16-02.bpo-29727.Q6Z2rg.rst
  Modules/arraymodule.c
Labels: CLA signed, awaiting core review

#21324 bpo-26205: Specify the number of nested scopes
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21340 bpo-28681: Clarify multiple function names in the tutorial
  Doc/tutorial/controlflow.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21342 [3.8] bpo-26205: Specify the number of nested scopes (GH-21324)
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#21341 [3.9] bpo-26205: Specify the number of nested scopes (GH-21324)
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#21343 [3.9] bpo-28681: Clarify multiple function names in the tutorial (GH-21340)
  Doc/tutorial/controlflow.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#21344 [3.8] bpo-28681: Clarify multiple function names in the tutorial (GH-21340)
  Doc/tutorial/controlflow.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#21309 bpo-41165: Deprecate PyEval_ReleaseLock()
  Include/ceval.h
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news

#21345 [3.9] bpo-41165: Deprecate PyEval_ReleaseLock() (GH-21309)
  Include/ceval.h
Labels: CLA signed, awaiting merge, skip news

#21314 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/pickletester.py
  Lib/test/test_binhex.py
  Lib/test/test_bufio.py
  Lib/test/test_capi.py
  Lib/test/test_compileall.py
  Lib/test/test_fileio.py
  Lib/test/test_heapq.py
  Lib/test/test_httplib.py
  Lib/test/test_importlib/util.py
  Lib/test/test_io.py
  Lib/test/test_json/__init__.py
  Lib/test/test_json/test_tool.py
  Lib/test/test_netrc.py
  Lib/test/test_nis.py
  Lib/test/test_pickle.py
  Lib/test/test_py_compile.py
  Lib/test/test_sqlite.py
  Lib/test/test_univnewlines.py
  Lib/test/test_uuid.py
Labels: CLA signed, awaiting review, skip news

#21315 bpo-40275: Use new test.support helper submodules in tests
  Lib/ctypes/test/__init__.py
  Lib/ctypes/test/test_find.py
  Lib/test/test_bytes.py
  Lib/test/test_cgitb.py
  Lib/test/test_ctypes.py
  Lib/test/test_dbm.py
  Lib/test/test_fcntl.py
  Lib/test/test_file.py
  Lib/test/test_fstring.py
  Lib/test/test_httpservers.py
  Lib/test/test_linecache.py
  Lib/test/test_msilib.py
  Lib/test/test_picklebuffer.py
  Lib/test/test_profile.py
  Lib/test/test_pty.py
  Lib/test/test_reprlib.py
  Lib/test/test_shelve.py
  Lib/test/test_tk.py
  Lib/test/test_wsgiref.py
  Lib/test/test_zlib.py
Labels: CLA signed, awaiting review, skip news

#21337 bpo-37207: Update whatsnews for 3.9
  Doc/whatsnew/3.9.rst
Labels: CLA signed, needs backport to 3.9, skip news, type-documentation

#21317 bpo-40275: Use new test.support helper submodules in tests
  Lib/distutils/tests/support.py
  Lib/distutils/tests/test_build_ext.py
  Lib/distutils/tests/test_filelist.py
  Lib/distutils/tests/test_spawn.py
  Lib/test/test_dbm_gnu.py
  Lib/test/test_eof.py
  Lib/test/test_hashlib.py
  Lib/test/test_idle.py
  Lib/test/test_imaplib.py
  Lib/test/test_marshal.py
  Lib/test/test_py_compile.py
  Lib/test/test_set.py
  Lib/test/test_socket.py
  Lib/test/test_sysconfig.py
  Lib/test/test_traceback.py
  Lib/test/test_unicode.py
  Lib/test/test_xml_etree.py
  Lib/test/test_zipfile.py
Labels: CLA signed, awaiting merge, skip news

#21350 [3.9] bpo-37207: Update whatsnews for 3.9 (GH-21337)
  Doc/whatsnew/3.9.rst
Labels: :robot: automerge, CLA signed, skip news, type-documentation

#21297 bpo-29778: Ensure python3.dll is loaded from correct locations when Python is embedded
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Security/2020-07-03-17-21-37.bpo-29778.cR_fGS.rst
  Modules/_testinternalcapi.c
  PC/getpathp.c
  PCbuild/pyproject.props
  PCbuild/python.props
  Python/dynload_win.c
  Python/pathconfig.c
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-bugfix, type-security

#21351 [3.9] bpo-29778: Ensure python3.dll is loaded from correct locations when Python is embedded (GH-21297)
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Security/2020-07-03-17-21-37.bpo-29778.cR_fGS.rst
  Modules/_testinternalcapi.c
  PC/getpathp.c
  PCbuild/pyproject.props
  PCbuild/python.props
  Python/dynload_win.c
  Python/pathconfig.c
Labels: CLA signed, awaiting merge, type-bugfix, type-security

#21352 [3.8] bpo-29778: Ensure python3.dll is loaded from correct locations when Python is embedded (GH-21297)
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Security/2020-07-03-17-21-37.bpo-29778.cR_fGS.rst
  Modules/_testinternalcapi.c
  PC/getpathp.c
  PCbuild/pyproject.props
  PCbuild/python.props
  Python/dynload_win.c
  Python/pathconfig.c
Labels: CLA signed, awaiting review, type-bugfix, type-security

#21298 [3.7] bpo-29778: Ensure python3.dll is loaded from correct locations when Python is embedded (GH-21297)
  Misc/NEWS.d/next/Security/2020-07-03-17-21-37.bpo-29778.cR_fGS.rst
  PC/getpathp.c
  PCbuild/pyproject.props
  PCbuild/python.props
  Python/dynload_win.c
Labels: CLA signed, DO-NOT-MERGE, awaiting core review, needs backport to 3.6, type-bugfix, type-security

#21354 [3.6] bpo-29778: Ensure python3.dll is loaded from correct locations when Python is embedded (GH-21298)
  Misc/NEWS.d/next/Security/2020-07-03-17-21-37.bpo-29778.cR_fGS.rst
  PC/getpathp.c
  PCbuild/pyproject.props
  PCbuild/python.props
  Python/dynload_win.c
Labels: CLA signed, awaiting core review, type-bugfix, type-security

#21356 [3.9] bpo-41215: Don't use NULL by default in the PEG parser keyword list (GH-21355)
  Misc/NEWS.d/next/Core and Builtins/2020-07-06-18-36-33.bpo-41215.vFGFIz.rst
  Parser/pegen/parse.c
  Parser/pegen/pegen.c
  Tools/peg_generator/pegen/c_generator.py
Labels: :robot: automerge, CLA signed, awaiting merge

#21355 bpo-41215: Don't use NULL by default in the PEG parser keyword list
  Misc/NEWS.d/next/Core and Builtins/2020-07-06-18-36-33.bpo-41215.vFGFIz.rst
  Parser/parser.c
  Parser/pegen.c
  Tools/peg_generator/pegen/c_generator.py
Labels: :robot: automerge, CLA signed, awaiting merge

#21237 bpo-40742: Doc: fix parallel build.
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting core review, skip news

#21357 bpo-41218: Only mark async code with CO_COROUTINE.
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2020-07-06-13-35-17.bpo-41218.oKnSr2.rst
  Python/compile.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21361 [3.8] bpo-41218: Only mark async code with CO_COROUTINE. (GH-21357)
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2020-07-06-13-35-17.bpo-41218.oKnSr2.rst
  Python/compile.c
Labels: CLA signed, awaiting merge

#21363 bpo-41218: Improve the test cases for test_compile_top_level_await_nocoro
  Lib/test/test_builtin.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-tests

#21362 [3.9] bpo-41218: Only mark async code with CO_COROUTINE. (GH-21357)
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2020-07-06-13-35-17.bpo-41218.oKnSr2.rst
  Python/compile.c
Labels: CLA signed, awaiting core review

#21364 bpo-41215: Make assertion in the new parser more strict
  Parser/pegen.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#21366 [3.8] bpo-41218: Improve the test cases for test_compile_top_level_await_no_coro (GH-21363)
  Lib/test/test_builtin.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#21367 [3.9] bpo-41215: Make assertion in the new parser more strict (GH-21364)
  Parser/pegen/pegen.c
Labels: CLA signed, awaiting merge, skip news

#21359 bpo-41207 In distutils.spawn, rewrite FileNotFound
  Lib/distutils/spawn.py
  Lib/distutils/tests/test_spawn.py
  Misc/NEWS.d/next/Library/2020-07-06-16-58-53.bpo-41207.Emw7Nk.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, type-bugfix, type-tests

#21373 [3.9] bpo-41207 In distutils.spawn, rewrite FileNotFound (GH-21359)
  Lib/distutils/spawn.py
  Lib/distutils/tests/test_spawn.py
  Misc/NEWS.d/next/Library/2020-07-06-16-58-53.bpo-41207.Emw7Nk.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix, type-tests

#21306 bpo-29778: test_embed tests the path configuration
  Include/internal/pycore_pathconfig.h
  Lib/test/test_embed.py
  Modules/_testinternalcapi.c
  Python/initconfig.c
  Python/pathconfig.c
Labels: CLA signed, awaiting merge, skip news

#21369 bpo-41224: Document is_annotated() in symtable module and update doc strings
  Doc/library/symtable.rst
  Lib/symtable.py
Labels: CLA signed, awaiting merge, skip news

#21305 bpo-41173: Copy test results file from ARM worker before uploading
  Tools/buildbot/test.bat
Labels: CLA signed, OS-windows, awaiting core review, skip news

#21382 [3.9] bpo-41173: Copy test results file from ARM worker before uploading (GH-21305)
  Tools/buildbot/test.bat
Labels: CLA signed, awaiting merge, skip news

#21383 [3.8] bpo-39417: Fix broken link to guide to building venvs (GH-18432)
  Doc/library/venv.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21370 bpo-41225: Add a test for get_id() in the symtable module
  Lib/test/test_symtable.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#21385 bpo-41235: Fix the error handling in SSLContext.load_dh_params()
  Misc/NEWS.d/next/Library/2020-07-07-21-56-26.bpo-41235.H2csMU.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting review, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9

#21388 [3.8] closes bpo-41235: Fix the error handling in SSLContext.load_dh_params() (GH-21385)
  Misc/NEWS.d/next/Library/2020-07-07-21-56-26.bpo-41235.H2csMU.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting merge

#21387 [3.9] closes bpo-41235: Fix the error handling in SSLContext.load_dh_params() (GH-21385)
  Misc/NEWS.d/next/Library/2020-07-07-21-56-26.bpo-41235.H2csMU.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting merge

#21389 [3.7] closes bpo-41235: Fix the error handling in SSLContext.load_dh_params() (GH-21385)
  Misc/NEWS.d/next/Library/2020-07-07-21-56-26.bpo-41235.H2csMU.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting merge

#21390 Revert "bpo-40170: PyType_HasFeature() now always calls PyType_GetFlags() (GH-19378)"
  Include/object.h
  Misc/NEWS.d/next/C API/2020-07-08-10-14-52.bpo-40170.N6Qx1i.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9

#21391 [3.9] Revert "bpo-40170: PyType_HasFeature() now always calls PyType_GetFlags() (GH-19378)" (GH-21390)
  Include/object.h
  Misc/NEWS.d/next/C API/2020-07-08-10-14-52.bpo-40170.N6Qx1i.rst
Labels: CLA signed, awaiting merge

#21401 bpo-41247: asyncio.set_running_loop() cache running loop holder
  Misc/NEWS.d/next/Core and Builtins/2020-07-08-22-03-54.bpo-41247.PndYIk.rst
  Modules/_asynciomodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21402 [3.9] bpo-41247: asyncio.set_running_loop() cache running loop holder (GH-21401)
  Misc/NEWS.d/next/Core and Builtins/2020-07-08-22-03-54.bpo-41247.PndYIk.rst
  Modules/_asynciomodule.c
Labels: :robot: automerge, CLA signed, awaiting merge

#21240 bpo-41175: Guard against a possible NULL pointer dereference within bytearrayobject
  Misc/NEWS.d/next/Core and Builtins/2020-06-30-20-17-31.bpo-41175.acJoXB.rst
  Objects/bytearrayobject.c
Labels: CLA signed, awaiting merge

#20542 bpo-40597: Allow email.contextmanager set_content() to set a null string.
  Lib/email/contentmanager.py
  Lib/test/test_email/test_contentmanager.py
  Misc/NEWS.d/next/Library/2020-05-30-12-44-29.bpo-39384.Iqxy3q.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21405 [3.8] bpo-40597: Allow email.contextmanager set_content() to set a null string. (GH-20542)
  Lib/email/contentmanager.py
  Lib/test/test_email/test_contentmanager.py
  Misc/NEWS.d/next/Library/2020-05-30-12-44-29.bpo-39384.Iqxy3q.rst
Labels: CLA signed, awaiting merge

#21404 [3.9] bpo-40597: Allow email.contextmanager set_content() to set a null string. (GH-20542)
  Lib/email/contentmanager.py
  Lib/test/test_email/test_contentmanager.py
  Misc/NEWS.d/next/Library/2020-05-30-12-44-29.bpo-39384.Iqxy3q.rst
Labels: CLA signed, awaiting merge

#21376 Doc: Builtins functions: faster jump table
  Doc/library/functions.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#21407 bpo-41252: Fix incorrect refcounting in _ssl.c's _servername_callback()
  Misc/NEWS.d/next/Core and Builtins/2020-07-08-21-55-23.bpo-41252.nBWL-Y.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21411 [3.8] bpo-41252: Fix incorrect refcounting in _ssl.c's _servername_callback() (GH-21407)
  Misc/NEWS.d/next/Core and Builtins/2020-07-08-21-55-23.bpo-41252.nBWL-Y.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#21410 [3.9] bpo-41252: Fix incorrect refcounting in _ssl.c's _servername_callback() (GH-21407)
  Misc/NEWS.d/next/Core and Builtins/2020-07-08-21-55-23.bpo-41252.nBWL-Y.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#21413 bpo-41199: Docstring convention not followed for dataclasses documentation page
  Doc/library/dataclasses.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21414 [3.9] bpo-41199: Docstring convention not followed for dataclasses documentation page (GH-21413)
  Doc/library/dataclasses.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#21415 [3.8] bpo-41199: Docstring convention not followed for dataclasses documentation page (GH-21413)
  Doc/library/dataclasses.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#21412 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/test_cmd_line_script.py
  Lib/test/test_codeop.py
  Lib/test/test_contextlib.py
  Lib/test/test_dbm_ndbm.py
  Lib/test/test_getargs2.py
  Lib/test/test_gettext.py
  Lib/test/test_glob.py
  Lib/test/test_import/__init__.py
  Lib/test/test_locale.py
  Lib/test/test_mailbox.py
  Lib/test/test_multiprocessing_main_handling.py
  Lib/test/test_osx_env.py
  Lib/test/test_pkgutil.py
  Lib/test/test_plistlib.py
  Lib/test/test_ttk_guionly.py
  Lib/test/test_turtle.py
  Lib/test/test_xxtestfuzz.py
  Lib/test/test_zipimport.py
Labels: CLA signed, awaiting review, skip news

#19896 bpo-29590: fix stack trace for gen.throw() with yield from
  Lib/test/test_generators.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-03-22-26-00.bpo-29590.aRz3l7.rst
  Objects/genobject.c
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9

#21406 [3.8] bpo-41247: asyncio.set_running_loop() cache running loop holder
  Misc/NEWS.d/next/Core and Builtins/2020-07-08-22-03-54.bpo-41247.PndYIk.rst
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge

#21400 bpo-41172: Fix check for compiler in test suite
  Lib/test/support/__init__.py
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.9, skip issue, skip news, type-tests

#21419 [3.9] bpo-41172: Fix check for compiler in test suite (GH-21400)
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#21358 Remove trailing >>> in enum docs
  Doc/library/enum.rst
  Misc/ACKS
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#15138 bpo-37765: Add keywords to IDLE tab completions
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/autocomplete.py
  Lib/idlelib/help.html
  Lib/idlelib/idle_test/test_autocomplete.py
  Misc/NEWS.d/next/IDLE/2020-07-07-18-44-30.bpo-37765.umc1o8.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21423 [3.9] bpo-37765: Add keywords to IDLE tab completions (GH-15138)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/autocomplete.py
  Lib/idlelib/help.html
  Lib/idlelib/idle_test/test_autocomplete.py
  Misc/NEWS.d/next/IDLE/2020-07-07-18-44-30.bpo-37765.umc1o8.rst
Labels: CLA signed, awaiting merge

#21424 [3.8] bpo-37765: Add keywords to IDLE tab completions (GH-15138)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/autocomplete.py
  Lib/idlelib/help.html
  Lib/idlelib/idle_test/test_autocomplete.py
  Misc/NEWS.d/next/IDLE/2020-07-07-18-44-30.bpo-37765.umc1o8.rst
Labels: CLA signed, awaiting merge

#21326 bpo-23802: patch: __deepcopy__ memo dict argument usage
  Doc/library/copy.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#21426 bpo-41263: Convert code.__new__ to Argument Clinic
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
Labels: CLA signed, awaiting core review, skip news

#21429 bpo-36346: Do not use legacy Unicode C API in ctypes.
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/cfield.c
Labels: CLA signed, awaiting merge, skip news

#21432 [3.8] bpo-41175: Guard against a NULL pointer dereference within bytearrayobject (GH-21240)
  Misc/NEWS.d/next/Core and Builtins/2020-06-30-20-17-31.bpo-41175.acJoXB.rst
  Objects/bytearrayobject.c
Labels: CLA signed, awaiting merge

#21431 [3.9] bpo-41175: Guard against a NULL pointer dereference within bytearrayobject (GH-21240)
  Misc/NEWS.d/next/Core and Builtins/2020-06-30-20-17-31.bpo-41175.acJoXB.rst
  Objects/bytearrayobject.c
Labels: CLA signed, awaiting merge

#21433 bpo-39573: Use the Py_TYPE() macro
  Modules/_elementtree.c
  Objects/abstract.c
  Objects/genericaliasobject.c
  Objects/unicodeobject.c
  PC/_msi.c
  PC/winreg.c
  Tools/scripts/combinerefs.py
Labels: CLA signed, awaiting core review, skip news

#21384 bpo-41227: Minor typo in asyncio transport protocol
  Doc/library/asyncio-protocol.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21435 [3.9] bpo-41227: Fix typo in docs: 'created by th' -> 'created by the' (GH-21384)
  Doc/library/asyncio-protocol.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21436 [3.8] bpo-41227: Fix typo in docs: 'created by th' -> 'created by the' (GH-21384)
  Doc/library/asyncio-protocol.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#14275 bpo-20179: Convert the _overlapped module to the Argument Clinic
  Modules/clinic/overlapped.c.h
  Modules/overlapped.c
Labels: CLA signed, awaiting merge, skip news

#21437 bpo-36346: Make using the legacy Unicode C API optional
  Include/cpython/unicodeobject.h
  Lib/test/support/__init__.py
  Lib/test/test_csv.py
  Lib/test/test_decimal.py
  Lib/test/test_getargs2.py
  Lib/test/test_unicode.py
  Modules/_io/fileio.c
  Modules/_testcapimodule.c
  Modules/_winapi.c
  Modules/clinic/_winapi.c.h
  Modules/overlapped.c
  Modules/posixmodule.c
  Objects/unicodeobject.c
  PC/clinic/winreg.c.h
  PC/winreg.c
  Python/dynload_win.c
  Python/fileutils.c
Labels: CLA signed, awaiting core review, skip news

#21372 bpo-41228: Fix a typo in the description of monthcalendar()
  Doc/library/calendar.rst
Labels: CLA signed, awaiting change review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21440 [3.9] bpo-41228: Fix /a/are/ in monthcalendar() descripton (GH-21372)
  Doc/library/calendar.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21441 [3.8] bpo-41228: Fix /a/are/ in monthcalendar() descripton (GH-21372)
  Doc/library/calendar.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21422 Fix error in docstrings in bisect module
  Lib/bisect.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#14326 bpo-20181: Convert the readline module to the Argument Clinic
  Modules/clinic/readline.c.h
  Modules/readline.c
Labels: CLA signed, awaiting merge, skip news

#14245 bpo-20175: Convert Modules/_multiprocessing to the Argument Clinic
  Modules/_multiprocessing/clinic/multiprocessing.c.h
  Modules/_multiprocessing/clinic/semaphore.c.h
  Modules/_multiprocessing/multiprocessing.c
  Modules/_multiprocessing/multiprocessing.h
  Modules/_multiprocessing/semaphore.c
Labels: CLA signed, awaiting merge, skip news

#21197 bpo-41146: Convert signal.default_int_handler() to Argument Clinic
  Modules/clinic/signalmodule.c.h
  Modules/signalmodule.c
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#21458 bpo-41288: Fix a crash in unpickling invalid NEWOBJ_EX.
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2020-07-13-15-06-35.bpo-41288.8mn5P-.rst
  Modules/_pickle.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21460 [3.8] bpo-41288: Fix a crash in unpickling invalid NEWOBJ_EX. (GH-21458)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2020-07-13-15-06-35.bpo-41288.8mn5P-.rst
  Modules/_pickle.c
Labels: :robot: automerge, CLA signed, awaiting merge

#21459 [3.9] bpo-41288: Fix a crash in unpickling invalid NEWOBJ_EX. (GH-21458)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2020-07-13-15-06-35.bpo-41288.8mn5P-.rst
  Modules/_pickle.c
Labels: :robot: automerge, CLA signed, awaiting merge

#21461 [3.7] bpo-41288: Fix a crash in unpickling invalid NEWOBJ_EX. (GH-21458)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2020-07-13-15-06-35.bpo-41288.8mn5P-.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting merge

#21462 [3.6] bpo-41288: Fix a crash in unpickling invalid NEWOBJ_EX. (GH-21458)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2020-07-13-15-06-35.bpo-41288.8mn5P-.rst
  Modules/_pickle.c
Labels: CLA signed, awaiting merge

#21330 bpo-32192: A basic lazy importer example
  Doc/library/importlib.rst
Labels: CLA signed, awaiting changes, skip news, type-documentation

#21455 Fix repeated words in Classes tutorial
  Doc/tutorial/classes.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21469 [3.8] Fix repeated words in Classes tutorial (GH-21455)
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21468 [3.9] Fix repeated words in Classes tutorial (GH-21455)
  Doc/tutorial/classes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21474 bpo-32528: Document the change in inheritance of asyncio.CancelledError
  Doc/whatsnew/3.8.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21442 bpo-41273: asyncio's proactor read transport's better performance by using recv_into instead of recv
  Lib/asyncio/proactor_events.py
  Lib/test/test_asyncio/test_proactor_events.py
  Misc/NEWS.d/next/Library/2020-07-11-00-15-01.bpo-41273.SVrsJh.rst
Labels: CLA signed, awaiting merge

#14201 bpo-20183: Convert _locale to the Argument Clinic
  Modules/_localemodule.c
  Modules/clinic/_localemodule.c.h
Labels: CLA signed, awaiting merge, skip news
