Repository python/cpython, pull requests merged in 2020-10, with the labels that each got.

#22462 bpo-41870: Avoid the test when nargs=0
  Objects/boolobject.c
Labels: CLA signed, awaiting merge, skip news

#22444 bpo-41861: Convert _sqlite3 RowType and StatementType to heap types
  Modules/_sqlite/cache.c
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/module.c
  Modules/_sqlite/prepare_protocol.c
  Modules/_sqlite/row.c
  Modules/_sqlite/row.h
  Modules/_sqlite/statement.c
  Modules/_sqlite/statement.h
Labels: CLA signed, awaiting merge, skip news

#22478 bpo-41861: Convert _sqlite3 CursorType and ConnectionType to heap types
  Modules/_sqlite/connection.c
  Modules/_sqlite/connection.h
  Modules/_sqlite/cursor.c
  Modules/_sqlite/cursor.h
  Modules/_sqlite/module.c
  Modules/_sqlite/row.c
Labels: CLA signed, awaiting review, skip news

#6121 bpo-26680: Incorporate is_integer in all built-in and standard library numeric types
  Doc/library/decimal.rst
  Doc/library/numbers.rst
  Doc/library/stdtypes.rst
  Lib/_pydecimal.py
  Lib/numbers.py
  Lib/test/decimaltestdata/extra.decTest
  Lib/test/test_bool.py
  Lib/test/test_decimal.py
  Lib/test/test_fractions.py
  Lib/test/test_long.py
  Lib/test/test_numeric_tower.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2018-03-15-11-51-36.bpo-26680.wOWYps.rst
  Misc/NEWS.d/next/Library/2018-03-15-11-55-04.bpo-26680.eKAi85.rst
  Misc/NEWS.d/next/Library/2018-03-15-11-56-48.bpo-26680.Udkhn4.rst
  Modules/_decimal/_decimal.c
  Modules/_decimal/docstrings.h
  Objects/clinic/longobject.c.h
  Objects/longobject.c
Labels: CLA signed, awaiting merge

#22481 bpo-21955: Change my nickname in BINARY_ADD comment
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#22458 [doc] Update references to NumPy
  Doc/faq/programming.rst
  Doc/library/array.rst
  Doc/library/functions.rst
  Doc/tutorial/floatingpoint.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22488 Update link to supporting references
  Modules/mathmodule.c
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#22486 bpo-41692: Deprecate PyUnicode_InternImmortal()
  Doc/whatsnew/3.10.rst
  Include/unicodeobject.h
  Misc/NEWS.d/next/C API/2020-10-02-00-57-34.bpo-41692.fDScsF.rst
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge

#22291 bpo-41802: Document 'PyDict_DelItem' can raise a 'KeyError'
  Doc/c-api/dict.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22494 [3.8] bpo-41802: Document 'PyDict_DelItem' can raise a 'KeyError' (GH-22291)
  Doc/c-api/dict.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22493 [3.9] bpo-41802: Document 'PyDict_DelItem' can raise a 'KeyError' (GH-22291)
  Doc/c-api/dict.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22498 Typo fix - "mesasge" should be "message"
  Lib/email/message.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#22499 [3.9] Typo fix - "mesasge" should be "message" (GH-22498)
  Lib/email/message.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#22500 [3.8] Typo fix - "mesasge" should be "message" (GH-22498)
  Lib/email/message.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#22501 [doc] Fix is_typeddict example markup
  Doc/library/typing.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#22502 [doc] Fix link to abc.collections.Iterable
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22503 [3.9] [doc] Fix link to abc.collections.Iterable (GH-22502)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip issue, skip news, type-documentation

#22474 bpo-41900: C14N 2.0 serialisation failed for unprefixed attributes when a default namespace was defined.
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2020-10-01-10-50-12.bpo-41900.Cho7oh.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9

#22507 [3.9] bpo-41900: C14N 2.0 serialisation failed for unprefixed attributes when a default namespace was defined. (GH-22474)
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2020-10-01-10-50-12.bpo-41900.Cho7oh.rst
Labels: CLA signed, awaiting review

#22508 [3.8] bpo-41900: C14N 2.0 serialisation failed for unprefixed attributes when a default namespace was defined. (GH-22474)
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2020-10-01-10-50-12.bpo-41900.Cho7oh.rst
Labels: CLA signed, awaiting review

#20554 bpo-40833: Clarify docstring of Path.rename
  Doc/library/pathlib.rst
  Lib/pathlib.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22515 [3.8] bpo-40833: Clarify Path.rename doc-string regarding relative paths (GH-20554)
  Doc/library/pathlib.rst
  Lib/pathlib.py
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22418 bpo-41867: Include options for timespec in docstrings of isoformat methods
  Lib/datetime.py
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22516 [3.9] bpo-40833: Clarify Path.rename doc-string regarding relative paths (GH-20554)
  Doc/library/pathlib.rst
  Lib/pathlib.py
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22519 [3.8] bpo-41867: List options for timespec in docstrings of isoformat methods (GH-22418)
  Lib/datetime.py
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22518 [3.9] bpo-41867: List options for timespec in docstrings of isoformat methods (GH-22418)
  Lib/datetime.py
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22455 bpo-41826: Fix compiler warnings in test_peg_generator
  Lib/test/test_peg_generator/test_c_parser.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22371 bpo-40564: Avoid copying state from extant ZipFile.
  Lib/test/test_zipfile.py
  Lib/zipfile.py
  Misc/NEWS.d/next/Library/2020-09-23-03-33-37.bpo-40564.iXQqMq.rst
Labels: CLA signed, awaiting core review

#22520 [doc] Fix link to abc.collections.Iterable
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22521 [3.8] [doc] Fix link to abc.collections.Iterable (GH-22520)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22522 [3.9] [doc] Fix link to abc.collections.Iterable (GH-22520)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22523 bpo-41922: Use PEP 590 vectorcall to speed up reversed()
  Misc/NEWS.d/next/Core and Builtins/2020-10-04-01-02-58.bpo-41922.kHGT8I.rst
  Objects/enumobject.c
Labels: CLA signed, awaiting merge

#22391 bpo-41840: Report module-level globals as both local and global in the symtable module
  Lib/symtable.py
  Lib/test/test_symtable.py
  Misc/NEWS.d/next/Library/2020-09-23-23-17-59.bpo-41840.QRFr4L.rst
Labels: CLA signed, needs backport to 3.8, needs backport to 3.9

#22528 [3.9] bpo-41840: Report module-level globals as both local and global in the symtable module (GH-22391)
  Lib/symtable.py
  Lib/test/test_symtable.py
  Misc/NEWS.d/next/Library/2020-09-23-23-17-59.bpo-41840.QRFr4L.rst
Labels: CLA signed, awaiting core review

#22529 [3.8] bpo-41840: Report module-level globals as both local and global in the symtable module (GH-22391)
  Lib/symtable.py
  Lib/test/test_symtable.py
  Misc/NEWS.d/next/Library/2020-09-23-23-17-59.bpo-41840.QRFr4L.rst
Labels: CLA signed

#22524 [doc] Use list[int] instead of List[int] (etc.) in a few more places
  Doc/library/dataclasses.rst
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news, type-documentation

#22531 [3.9] [doc] Use list[int] instead of List[int] (etc.) in a few more places (GH-22524)
  Doc/library/dataclasses.rst
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22469 bpo-41887: omit leading whitespaces on ast.literal_eval
  Doc/library/ast.rst
  Doc/library/functions.rst
  Lib/ast.py
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2020-09-30-23-49-42.bpo-41887.-ee2S-.rst
Labels: CLA signed, awaiting merge

#22526 bpo-41898: add caveat on root logger seeing all messages
  Doc/library/unittest.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22537 [3.8] bpo-41898: add caveat on root logger seeing all messages in assertLogs doc (GH-22526)
  Doc/library/unittest.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#22540 [3.9] bpo-41898: add caveat on root logger seeing all messages in assertLogs doc (GH-22526)
  Doc/library/unittest.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#22530 Delete extra 'the' from `Formatter` class docstring
  Lib/logging/__init__.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#22542 [3.9] Delete extra 'the' from `Formatter` class docstring (GH-22530)
  Lib/logging/__init__.py
Labels: CLA signed, awaiting review, skip issue, skip news

#22543 [3.8] Delete extra 'the' from `Formatter` class docstring (GH-22530)
  Lib/logging/__init__.py
Labels: CLA signed, awaiting review, skip issue, skip news

#22544 [3.9] bpo-41490: Bump vendored pip to version 20.2.3 (GH-22527).
  Lib/ensurepip/__init__.py
  Lib/ensurepip/_bundled/pip-20.2.3-py2.py3-none-any.whl
Labels: CLA signed, awaiting core review, skip news

#22545 [3.8] bpo-41490: Bump vendored pip to version 20.2.3 (GH-22527).
  Lib/ensurepip/__init__.py
  Lib/ensurepip/_bundled/pip-20.2.3-py2.py3-none-any.whl
Labels: CLA signed, awaiting core review, skip news

#22496 Typo fix
  setup.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news

#22548 [3.9] Typo fix (GH-22496)
  setup.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#22536 bpo-41909: Enable previously disabled recursion checks.
  Lib/test/test_isinstance.py
  Misc/NEWS.d/next/Core and Builtins/2020-10-04-10-55-12.bpo-41909.BqHPcm.rst
  Objects/abstract.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#22550 [3.9] bpo-41909: Enable previously disabled recursion checks. (GH-22536)
  Lib/test/test_isinstance.py
  Misc/NEWS.d/next/Core and Builtins/2020-10-04-10-55-12.bpo-41909.BqHPcm.rst
  Objects/abstract.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting core review, type-bugfix

#22551 [3.8] bpo-41909: Enable previously disabled recursion checks. (GH-22536)
  Lib/test/test_isinstance.py
  Misc/NEWS.d/next/Core and Builtins/2020-10-04-10-55-12.bpo-41909.BqHPcm.rst
  Objects/abstract.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting core review, type-bugfix

#22464 bpo-41892: Clarify an example in the ElementTree docs
  Doc/library/xml.etree.elementtree.rst
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22553 [3.8] bpo-41892: Clarify that an example in the ElementTree docs explicitly avoids modifying an XML tree while iterating over it. (GH-22464)
  Doc/library/xml.etree.elementtree.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22554 [3.9] bpo-41892: Clarify that an example in the ElementTree docs explicitly avoids modifying an XML tree while iterating over it. (GH-22464)
  Doc/library/xml.etree.elementtree.rst
Labels: awaiting merge, skip news, type-documentation

#22517 bpo-41428: Documentation for PEP 604
  Doc/library/stdtypes.rst
  Doc/library/types.rst
  Doc/library/typing.rst
  Doc/whatsnew/3.10.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2020-10-03-18-20-46.bpo-41428._ju1NE.rst
Labels: CLA signed, awaiting merge, type-documentation

#21959 bpo-41557: Update macOS installer to use SQLite 3.33.0
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2020-08-26-09-31-37.bpo-41557.mcQ75z.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#22561 [3.8] bpo-41557: Update macOS installer to use SQLite 3.33.0 (GH-21959)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2020-08-26-09-31-37.bpo-41557.mcQ75z.rst
Labels: CLA signed, awaiting merge

#22560 [3.9] bpo-41557: Update macOS installer to use SQLite 3.33.0 (GH-21959)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2020-08-26-09-31-37.bpo-41557.mcQ75z.rst
Labels: CLA signed, awaiting merge

#22552 bpo-41936. Remove macros Py_ALLOW_RECURSION/Py_END_ALLOW_RECURSION
  Doc/whatsnew/3.10.rst
  Include/ceval.h
  Include/cpython/pystate.h
  Misc/NEWS.d/next/C API/2020-10-05-01-25-23.bpo-41936.1gb5ra.rst
  Python/ceval.c
  Python/pystate.c
Labels: CLA signed, awaiting merge, type-enhancement

#22562 bpo-41774: Tweak new programming FAQ entry
  Doc/faq/programming.rst
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22564 [3.8] bpo-41774: Tweak new programming FAQ entry (GH-22562)
  Doc/faq/programming.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22563 [3.9] bpo-41774: Tweak new programming FAQ entry (GH-22562)
  Doc/faq/programming.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22559 bpo-41939: Fix test_site.test_license_exists_at_url()
  Lib/test/test_site.py
  Misc/NEWS.d/next/Tests/2020-10-05-09-37-43.bpo-41939.P4OlbA.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, type-tests

#22505 bpo-41584: clarify when the reflected method of a binary arithemtic operator is called
  Doc/reference/datamodel.rst
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22567 [3.9] bpo-41939: Fix test_site.test_license_exists_at_url() (GH-22559)
  Lib/test/test_site.py
  Misc/NEWS.d/next/Tests/2020-10-05-09-37-43.bpo-41939.P4OlbA.rst
Labels: CLA signed, awaiting review, type-tests

#22569 [3.8] bpo-41584: clarify when the reflected method of a binary arithemtic operator is called (GH-22505)
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22568 [3.9] bpo-41584: clarify when the reflected method of a binary arithemtic operator is called (GH-22505)
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22574 [3.8] bpo-41939: Fix test_site.test_license_exists_at_url() (GH-22559)
  Lib/test/test_site.py
  Misc/NEWS.d/next/Tests/2020-10-05-09-37-43.bpo-41939.P4OlbA.rst
Labels: CLA signed, awaiting merge, type-tests

#22566 bpo-41944: No longer call eval() on content received via HTTP in the CJK codec tests
  Lib/test/multibytecodec_support.py
  Misc/NEWS.d/next/Tests/2020-10-05-17-43-46.bpo-41944.rf1dYb.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-security, type-tests

#22576 [3.9] bpo-41944: No longer call eval() on content received via HTTP in the CJK codec tests (GH-22566)
  Lib/test/multibytecodec_support.py
  Misc/NEWS.d/next/Tests/2020-10-05-17-43-46.bpo-41944.rf1dYb.rst
Labels: CLA signed, awaiting merge, type-security, type-tests

#22577 [3.8] bpo-41944: No longer call eval() on content received via HTTP in the CJK codec tests (GH-22566)
  Lib/test/multibytecodec_support.py
  Misc/NEWS.d/next/Tests/2020-10-05-17-43-46.bpo-41944.rf1dYb.rst
Labels: CLA signed, awaiting review, type-security, type-tests

#22575 bpo-41944: No longer call eval() on content received via HTTP in the UnicodeNames tests
  Lib/test/test_ucn.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22485 bpo-41905: added abc.update_abstractmethods
  Doc/library/abc.rst
  Doc/library/functools.rst
  Lib/abc.py
  Lib/dataclasses.py
  Lib/test/test_abc.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2020-10-01-21-11-03.bpo-41905._JpjR4.rst
Labels: CLA signed, awaiting merge

#20434 bpo-38605: Make postponed evaluation of annotations default
  Doc/reference/compound_stmts.rst
  Doc/whatsnew/3.10.rst
  Lib/dataclasses.py
  Lib/inspect.py
  Lib/test/dataclass_module_1.py
  Lib/test/dataclass_module_1_str.py
  Lib/test/dataclass_module_2.py
  Lib/test/dataclass_module_2_str.py
  Lib/test/dataclass_textanno.py
  Lib/test/test_annotations.py
  Lib/test/test_coroutines.py
  Lib/test/test_dataclasses.py
  Lib/test/test_dis.py
  Lib/test/test_functools.py
  Lib/test/test_grammar.py
  Lib/test/test_inspect.py
  Lib/test/test_opcodes.py
  Lib/test/test_positional_only_arg.py
  Lib/test/test_pydoc.py
  Lib/test/test_syntax.py
  Lib/test/test_types.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-27-16-08-16.bpo-38605.rcs2uK.rst
  Python/ast_opt.c
  Python/compile.c
  Python/future.c
Labels: CLA signed, awaiting merge

#22343 Fix comment about PyObject_IsTrue
  Objects/object.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#22532 bpo-41923: PEP 613: Add TypeAlias to typing module
  Doc/library/typing.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2020-10-03-23-14-50.bpo-41923.Buonw9.rst
Labels: CLA signed, awaiting merge

#22584 Revert "bpo-26680: Incorporate is_integer in all built-in and standard library numeric types"
  Doc/library/decimal.rst
  Doc/library/numbers.rst
  Doc/library/stdtypes.rst
  Lib/_pydecimal.py
  Lib/numbers.py
  Lib/test/decimaltestdata/extra.decTest
  Lib/test/test_bool.py
  Lib/test/test_decimal.py
  Lib/test/test_fractions.py
  Lib/test/test_long.py
  Lib/test/test_numeric_tower.py
  Misc/ACKS
  Modules/_decimal/_decimal.c
  Modules/_decimal/docstrings.h
  Objects/clinic/longobject.c.h
  Objects/longobject.c
Labels: CLA signed, awaiting core review, skip news

#21602 bpo-41376: Correct the documentation on ``site.getusersitepackages()`` regarding respecting PYTHONNOUSERSITE
  Doc/library/site.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22591 [3.9] bpo-41376: Fix the documentation of `site.getusersitepackages()` (GH-21602)
  Doc/library/site.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22595 bpo-41970: Avoid test failure in test_lib2to3 if the module is already imported
  Lib/test/test_lib2to3.py
  Misc/NEWS.d/next/Tests/2020-10-08-14-00-17.bpo-41970.aZ8QFf.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9

#21715 bpo-41306: Allow scale value to not be rounded
  Lib/tkinter/test/test_tkinter/test_widgets.py
  Misc/NEWS.d/next/Tests/2020-08-03-13-44-37.bpo-41306.VDoWXI.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#22596 [3.8] bpo-41306: Allow scale value to not be rounded (GH-21715)
  Lib/tkinter/test/test_tkinter/test_widgets.py
  Misc/NEWS.d/next/Tests/2020-08-03-13-44-37.bpo-41306.VDoWXI.rst
Labels: CLA signed, awaiting merge, type-tests

#22597 [3.9] bpo-41306: Allow scale value to not be rounded (GH-21715)
  Lib/tkinter/test/test_tkinter/test_widgets.py
  Misc/NEWS.d/next/Tests/2020-08-03-13-44-37.bpo-41306.VDoWXI.rst
Labels: CLA signed, awaiting merge, type-tests

#22598 bpo-41976: Fix the fallback to gcc of ctypes.util.find_library when using gcc>9
  Lib/ctypes/test/test_find.py
  Lib/ctypes/util.py
  Misc/NEWS.d/next/Library/2020-10-08-18-22-28.bpo-41976.Svm0wb.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9

#21960 bpo-41557: Update Windows installer to use SQLite 3.33.0
  Misc/NEWS.d/next/Windows/2020-08-26-09-35-06.bpo-41557.vt00cQ.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, OS-windows, awaiting review, needs backport to 3.8, needs backport to 3.9

#22600 [3.8] bpo-41976: Fix the fallback to gcc of ctypes.util.find_library when using gcc>9 (GH-22598)
  Lib/ctypes/test/test_find.py
  Lib/ctypes/util.py
  Misc/NEWS.d/next/Library/2020-10-08-18-22-28.bpo-41976.Svm0wb.rst
Labels: CLA signed, awaiting core review

#22601 [3.7] bpo-41976: Fix the fallback to gcc of ctypes.util.find_library when using gcc>9 (GH-22598)
  Lib/ctypes/test/test_find.py
  Lib/ctypes/util.py
  Misc/NEWS.d/next/Library/2020-10-08-18-22-28.bpo-41976.Svm0wb.rst
Labels: CLA signed, awaiting core review

#22599 [3.9] bpo-41976: Fix the fallback to gcc of ctypes.util.find_library when using gcc>9 (GH-22598)
  Lib/ctypes/test/test_find.py
  Lib/ctypes/util.py
  Misc/NEWS.d/next/Library/2020-10-08-18-22-28.bpo-41976.Svm0wb.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#22603 [3.8] bpo-41557: Update Windows installer to use SQLite 3.33.0 (GH-21960)
  Misc/NEWS.d/next/Windows/2020-08-26-09-35-06.bpo-41557.vt00cQ.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting merge

#22602 [3.9] bpo-41557: Update Windows installer to use SQLite 3.33.0 (GH-21960)
  Misc/NEWS.d/next/Windows/2020-08-26-09-35-06.bpo-41557.vt00cQ.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting merge

#19069 bpo-39337: Add a test case for normalizing of codec names
  Lib/test/test_codecs.py
Labels: CLA signed, awaiting changes, skip news, type-tests

#22594 Fix the attribute names in the docstring of GenericAlias
  Objects/genericaliasobject.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news

#22606 [3.9] Fix the attribute names in the docstring of GenericAlias (GH-22594)
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#22605 Updated README for python 3.10
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22611 bpo-41979: Accept star-unpacking on with-item targets
  Grammar/python.gram
  Lib/test/test_with.py
  Misc/NEWS.d/next/Core and Builtins/2020-10-09-10-55-50.bpo-41979.ImXIk2.rst
  Parser/parser.c
Labels: CLA signed, awaiting merge, needs backport to 3.9

#22609 [3.9] bpo-41970: Avoid test failure in test_lib2to3 if the module is already imported (GH-22595)
  Lib/test/test_lib2to3.py
  Misc/NEWS.d/next/Tests/2020-10-08-14-00-17.bpo-41970.aZ8QFf.rst
Labels: CLA signed, awaiting merge, type-tests

#22612 [3.9] bpo-41979: Accept star-unpacking on with-item targets (GH-22611)
  Grammar/python.gram
  Lib/test/test_with.py
  Misc/NEWS.d/next/Core and Builtins/2020-10-09-10-55-50.bpo-41979.ImXIk2.rst
  Parser/pegen/parse.c
Labels: :robot: automerge, CLA signed, awaiting merge

#22593 bpo-41974: Remove complex.__float__, complex.__floordiv__, etc
  Doc/whatsnew/3.10.rst
  Lib/test/test_complex.py
  Misc/NEWS.d/next/Core and Builtins/2020-10-08-09-58-19.bpo-41974.8B-q8O.rst
  Objects/abstract.c
  Objects/bytesobject.c
  Objects/complexobject.c
  Objects/floatobject.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge

#22354 bpo-41831: Add tests for tkinter.Event.__repr__
  Lib/tkinter/test/test_tkinter/test_misc.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-tests

#22616 [3.8] bpo-41831: Add tests for tkinter.Event.__repr__ (GH-22354)
  Lib/tkinter/test/test_tkinter/test_misc.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22617 [3.9] bpo-41831: Add tests for tkinter.Event.__repr__ (GH-22354)
  Lib/tkinter/test/test_tkinter/test_misc.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22355 bpo-41831: Restore str implementation of __str__ in tkinter.EventType
  Lib/tkinter/__init__.py
  Misc/NEWS.d/next/Library/2020-09-22-11-07-50.bpo-41831.k-Eop_.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-bugfix

#22619 bpo-39481: Fix duplicate SimpleQueue type in test_genericalias.py
  Lib/test/test_genericalias.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip news, type-tests

#22620 bpo-41985: Add _PyLong_FileDescriptor_Converter and AC converter for "fildes".
  Include/cpython/fileobject.h
  Modules/clinic/fcntlmodule.c.h
  Modules/clinic/posixmodule.c.h
  Modules/clinic/selectmodule.c.h
  Modules/fcntlmodule.c
  Modules/posixmodule.c
  Modules/selectmodule.c
  Modules/termios.c
  Objects/fileobject.c
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting core review, skip news, type-enhancement

#22622 [3.9] bpo-41831: Restore str implementation of __str__ in tkinter.EventType (GH-22355)
  Lib/tkinter/__init__.py
  Misc/NEWS.d/next/Library/2020-09-22-11-07-50.bpo-41831.k-Eop_.rst
Labels: CLA signed, awaiting merge, type-bugfix

#22623 [3.8] bpo-41831: Restore str implementation of __str__ in tkinter.EventType (GH-22355)
  Lib/tkinter/__init__.py
  Misc/NEWS.d/next/Library/2020-09-22-11-07-50.bpo-41831.k-Eop_.rst
Labels: CLA signed, awaiting merge, type-bugfix

#22443 bpo-41756: Add PyIter_Send function to allow sending value into generators/coroutines/iterators
  Doc/c-api/gen.rst
  Doc/c-api/iter.rst
  Doc/data/refcounts.dat
  Doc/whatsnew/3.10.rst
  Include/abstract.h
  Include/genobject.h
  Misc/NEWS.d/next/C API/2020-09-28-14-31-07.bpo-41756.ZZ5wJG.rst
  Modules/_asynciomodule.c
  Modules/_testcapimodule.c
  Objects/abstract.c
  Objects/genobject.c
  Python/ceval.c
Labels: CLA signed, awaiting merge

#22613 Fix incorrect parameter name
  Doc/library/shutil.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22039 [3.9] bpo-41371: Handle lzma lib import error in test_zoneinfo.py (GH-21734)
  Lib/test/test_zoneinfo/test_zoneinfo.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22627 [3.8] Fix incorrect parameter name (GH-22613)
  Doc/library/shutil.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22621 bpo-41986: Add Py_FileSystemDefaultEncodeErrors and Py_UTF8Mode back to limited API
  Include/cpython/fileobject.h
  Include/fileobject.h
  Misc/NEWS.d/next/C API/2020-10-09-22-50-46.bpo-41986.JUPE59.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#22638 [3.8] bpo-41986: Add Py_FileSystemDefaultEncodeErrors and Py_UTF8Mode back to limited API (GH-22621)
  Include/cpython/fileobject.h
  Include/fileobject.h
  Misc/NEWS.d/next/C API/2020-10-09-22-50-46.bpo-41986.JUPE59.rst
Labels: CLA signed, awaiting merge, type-bugfix

#22637 [3.9] bpo-41986: Add Py_FileSystemDefaultEncodeErrors and Py_UTF8Mode back to limited API (GH-22621)
  Include/cpython/fileobject.h
  Include/fileobject.h
  Misc/NEWS.d/next/C API/2020-10-09-22-50-46.bpo-41986.JUPE59.rst
Labels: CLA signed, awaiting merge, type-bugfix

#22641 bpo-42000: Cleanup the AST related C-code
  Parser/asdl_c.py
  Parser/pegen.c
  Python/ast.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#22629 bpo-41991: Remove _PyObject_HasAttrId
  Include/cpython/object.h
  Objects/object.c
  Objects/unionobject.c
  Python/errors.c
  Python/pythonrun.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#22630 bpo-38605: bump the magic number for 'annotations' future
  Lib/importlib/_bootstrap_external.py
  Python/importlib_external.h
Labels: CLA signed, awaiting merge, skip news

#22625 Fix typo in typing.rst
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news, type-documentation

#22644 [3.9] Fix typo in typing.rst (GH-22625)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22642 bpo-42002: Clean up initialization of the sys module.
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#22631 bpo-41993: Fix possible issues in remove_module()
  Misc/NEWS.d/next/Core and Builtins/2020-10-10-13-53-52.bpo-41993.YMzixQ.rst
  Python/import.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#22504 [3.8] [doc] Fix link to abc.collections.Iterable (GH-22502)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22582 Fix typo
  Doc/library/math.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22592 [3.8] bpo-41376: Fix the documentation of `site.getusersitepackages()` (GH-21602)
  Doc/library/site.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22588 Fix typo in listobject.h
  Include/cpython/listobject.h
Labels: CLA not signed, awaiting merge, skip issue, skip news

#22571 Fix .. code-block :: directives in decimal.rst
  Doc/c-api/decimal.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#19754 bpo-40422: create a common _Py_closerange API
  Misc/NEWS.d/next/C API/2020-10-10-14-05-24.bpo-40422.sh8IDY.rst
  Modules/_posixsubprocess.c
  Modules/posixmodule.c
  Modules/posixmodule.h
Labels: :robot: automerge, CLA signed, awaiting merge

#22651 bpo-40423: Optimization: use close_range(2) if available
  Misc/NEWS.d/next/C API/2020-10-11-19-17-44.bpo-40423.GsmgEj.rst
  Modules/posixmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: :robot: automerge, CLA signed, awaiting merge, type-enhancement

#22652 bpo-41971: Fix test failure in test.test_tools.test_c_analyzer when mutating global state
  Tools/c-analyzer/c_analyzer/common/files.py
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news

#22653 [3.9] bpo-41971: Fix test failure in test.test_tools.test_c_analyzer when mutating global state (GH-22652)
  Tools/c-analyzer/c_analyzer/common/files.py
Labels: CLA signed, awaiting merge, skip news

#22655 bpo-41739: Fix test_logging.test_race_between_set_target_and_flush()
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Tests/2020-10-12-00-11-47.bpo-41739.wSCc4K.rst
Labels: CLA signed, awaiting merge, type-tests

#22656 [3.9] bpo-41739: Fix test_logging.test_race_between_set_target_and_flush() (GH-22655)
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Tests/2020-10-12-00-11-47.bpo-41739.wSCc4K.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, type-tests

#22662 [3.8] bpo-41739: Fix test_logging.test_race_between_set_target_and_flush() (GH-22655) (GH-22656)
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Tests/2020-10-12-00-11-47.bpo-41739.wSCc4K.rst
Labels: CLA signed, awaiting review, type-tests

#22144 [doc] Remove mention of async and await as soft keywords
  Doc/reference/compound_stmts.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22650 [3.9] Fix typo (GH-22582)
  Doc/library/math.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22661 [doc] Fix typo in the graphlib docs
  Lib/graphlib.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news

#22663 bpo-41756: Delete PyGen_Send function
  Doc/c-api/gen.rst
  Doc/data/refcounts.dat
  Doc/whatsnew/3.10.rst
  Include/genobject.h
  Misc/NEWS.d/3.10.0a1.rst
  Objects/abstract.c
  Objects/genobject.c
Labels: CLA signed, awaiting merge, skip news

#22669 [3.9] [doc] Fix typo in the graphlib docs (GH-22661)
  Lib/graphlib.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#22670 bpo-42015: Reorder dereferencing calls in meth_dealloc, to make sure m_self is kept alive long enough
  Misc/NEWS.d/next/C API/2020-10-12-20-13-58.bpo-42015.X4H2_V.rst
  Objects/methodobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, type-bugfix

#22674 [3.9] bpo-42015: Reorder dereferencing calls in meth_dealloc, to make sure m_self is kept alive long enough (GH-22670)
  Misc/NEWS.d/next/C API/2020-10-12-20-13-58.bpo-42015.X4H2_V.rst
  Objects/methodobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#22676 Fix typo in "Context manager types" section in typing.rst
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22624 [3.9] bpo-39481: Fix duplicate SimpleQueue type in test_genericalias.py (GH-22619)
  Lib/test/test_genericalias.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22672 bpo-40422: Move _Py_*_SUPPRESS_IPH bits into _Py_closerange
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge, skip news

#22678 [3.9] Fix typo in "Context manager types" section in typing.rst (GH-22676)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22660 bpo-41995: Fix a null pointer dereference in _tracemalloc.c
  Modules/_tracemalloc.c
Labels: CLA signed, awaiting review, needs backport to 3.9, skip news

#22681 [3.9] bpo-41995: Fix null ptr deref in tracemalloc_copy_trace() (GH-22660)
  Modules/_tracemalloc.c
Labels: CLA signed, awaiting merge, skip news

#22683 [3.8] bpo-32793: Fix a duplicate debug message in smtplib (GH-15341)
  Lib/smtplib.py
  Misc/NEWS.d/next/Library/2019-08-20-05-17-32.bpo-32793.cgpXl6.rst
Labels: CLA signed, awaiting core review

#22677 bpo-41756: Export PyGen_Send and wrap it in if-defs
  Doc/c-api/iter.rst
  Include/abstract.h
  PC/python3dll.c
Labels: CLA signed, awaiting merge, skip news

#22664 Add recipe for a version of random() with a larger population
  Doc/library/random.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news, type-documentation

#22684 [3.9] Add recipe for a version of random() with a larger population (GH-22664)
  Doc/library/random.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#22680 bpo-40422: move _Py_closerange to core
  Include/internal/pycore_fileutils.h
  Modules/Setup
  Modules/_posixsubprocess.c
  Modules/posixmodule.c
  Modules/posixmodule.h
  Python/fileutils.c
  setup.py
Labels: CLA signed, awaiting merge, skip news
