Repository python/cpython, pull requests merged in 2020-12, with the labels that each got.

#23531 bpo-42482: remove reference to exc_traceback from TracebackException
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2020-11-27-16-46-58.bpo-42482.EJC3sd.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#23579 [3.8] bpo-42482: remove reference to exc_traceback from TracebackException (GH-23531)
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2020-11-27-16-46-58.bpo-42482.EJC3sd.rst
Labels: CLA signed, awaiting merge

#23549 bpo-38200: Add itertools.pairwise()
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
  Misc/NEWS.d/next/Library/2020-11-28-22-52-57.bpo-38200.DuWGlW.rst
  Modules/clinic/itertoolsmodule.c.h
  Modules/itertoolsmodule.c
Labels: CLA signed, awaiting core review

#23380 [3.9] [doc] Fix smtplib and xml.dom.minidom mark-up (GH-22769)
  Doc/library/smtplib.rst
  Doc/library/xml.dom.minidom.rst
Labels: :robot: automerge, CLA signed, awaiting core review, skip issue, skip news, type-documentation

#20254 bpo-31904: fix fifo test cases for VxWorks RTOS
  Lib/test/test_posix.py
  Lib/test/test_stat.py
  Misc/NEWS.d/next/Tests/2020-05-20-14-28-48.bpo-31904.yJik6k.rst
Labels: CLA signed, awaiting merge, type-tests

#23586 bpo-42519: Replace PyMem_MALLOC() with PyMem_Malloc()
  Include/objimpl.h
  Include/pymem.h
  Modules/_localemodule.c
  Modules/_pickle.c
  Modules/_sre.c
  Modules/_ssl.c
  Modules/_struct.c
  Modules/_testcapimodule.c
  Modules/_threadmodule.c
  Modules/_tkinter.c
  Modules/arraymodule.c
  Modules/cjkcodecs/multibytecodec.c
  Modules/posixmodule.c
  Modules/selectmodule.c
  Objects/capsule.c
  Objects/codeobject.c
  Objects/dictobject.c
  Objects/listobject.c
  Objects/moduleobject.c
  Objects/odictobject.c
  Objects/setobject.c
  Objects/stringlib/join.h
  Objects/structseq.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  PC/winreg.c
  Parser/string_parser.c
  Parser/tokenizer.c
  Python/bltinmodule.c
  Python/getargs.c
  Python/marshal.c
  Python/pystrtod.c
  Python/traceback.c
Labels: CLA signed, awaiting core review, skip news

#23587 bpo-42519: Replace PyObject_MALLOC() with PyObject_Malloc()
  Include/objimpl.h
  Include/pymem.h
  Modules/_blake2/blake2b_impl.c
  Modules/_blake2/blake2s_impl.c
  Modules/_ctypes/callproc.c
  Modules/_curses_panel.c
  Modules/_cursesmodule.c
  Modules/_decimal/_decimal.c
  Modules/_functoolsmodule.c
  Modules/_hashopenssl.c
  Modules/_multiprocessing/semaphore.c
  Modules/_pickle.c
  Modules/_sha3/sha3module.c
  Modules/_sre.c
  Modules/_ssl.c
  Modules/_testbuffer.c
  Modules/_testcapimodule.c
  Modules/_threadmodule.c
  Modules/_tkinter.c
  Modules/cjkcodecs/multibytecodec.c
  Modules/gcmodule.c
  Modules/md5module.c
  Modules/ossaudiodev.c
  Modules/overlapped.c
  Modules/selectmodule.c
  Modules/sha1module.c
  Modules/sha256module.c
  Modules/sha512module.c
  Modules/sre_lib.h
  Modules/unicodedata.c
  Modules/xxmodule.c
  Modules/zlibmodule.c
  Objects/bytesobject.c
  Objects/capsule.c
  Objects/codeobject.c
  Objects/complexobject.c
  Objects/dictobject.c
  Objects/floatobject.c
  Objects/longobject.c
  Objects/object.c
  Objects/odictobject.c
  Objects/rangeobject.c
  Objects/stringlib/unicode_format.h
  Objects/typeobject.c
  Objects/unicodeobject.c
  PC/_msi.c
  PC/winreg.c
  Python/symtable.c
Labels: CLA signed, awaiting core review, skip news

#23580 [doc] Fix bz2 examples markup
  Doc/library/bz2.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#23576 [doc] Fix abc.update_abstractmethods markup
  Doc/library/abc.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23589 [3.8] Fix bz2 examples markup (GH-23580)
  Doc/library/bz2.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23588 [3.9] Fix bz2 examples markup (GH-23580)
  Doc/library/bz2.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23527 [3.9] bpo-17852: Doc: Fix the tutorial about closing files (GH-23135)
  Doc/tutorial/inputoutput.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#23596 [3.7] Bumps [actions/cache](https://github.com/actions/cache) from v1 to v2.1.3.
  .github/workflows/build.yml
  .github/workflows/coverage.yml
Labels: CLA signed, awaiting core review, skip issue, skip news

#23590 [3.9] Add GCC pragmas to silence compiler warning about ffi_prep_closure (GH-23327)
  Modules/_ctypes/callbacks.c
Labels: CLA signed, awaiting review, skip issue, skip news

#23594 [3.8] build(deps): bump actions/upload-artifact from v2.2.0 to v2.2.1 (GH-23583)
  .github/workflows/doc.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#23593 [3.8] build(deps): bump actions/cache from v2.1.2 to v2.1.3 (23582)
  .github/workflows/build.yml
  .github/workflows/coverage.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#23595 bpo-37221: PyCode_New() didn't change in Python 3.8
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#23592 [3.9] build(deps): bump actions/cache from v2.1.2 to v2.1.3 (23582)
  .github/workflows/build.yml
  .github/workflows/coverage.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#23597 [3.9] build(deps): bump actions/upload-artifact from v2.2.0 to v2.2.1
  .github/workflows/doc.yml
Labels: CLA signed, awaiting core review, skip issue, skip news

#23599 [3.8] bpo-37221: PyCode_New() didn't change in Python 3.8 (GH-23595)
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23600 [3.9] bpo-37221: PyCode_New() didn't change in Python 3.8 (GH-23595)
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21675 bpo-31904: Fix test_netrc for VxWorks RTOS
  Lib/test/test_netrc.py
  Misc/NEWS.d/next/Tests/2020-12-01-15-51-19.bpo-31904.iwetj4.rst
Labels: CLA signed, awaiting review, type-tests

#23606 bpo-40939: Restore some stable API functions incorrectly deleted
  Python/pythonrun.c
Labels: CLA signed, awaiting merge, skip news

#23609 Correct return type in Modules/_ssl.c::sslmodule_legacy
  Modules/_ssl.c
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#23568 bpo-42500: Fix recursion in or after except
  Include/cpython/pystate.h
  Include/internal/pycore_ceval.h
  Lib/test/test_exceptions.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2020-11-30-14-27-29.bpo-42500.excVKU.rst
  Python/ceval.c
  Python/errors.c
  Python/pystate.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review

#23495 bpo-42246: Make sure that line number is correct after a return, as required by PEP 626
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2020-11-24-14-01-43.bpo-42246.c9k9hj.rst
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting merge

#23607 bpo-42521: Add note about 'Python -d' only working on debug builds
  Python/initconfig.c
Labels: CLA signed, awaiting merge, skip news

#23608 bpo-41625: Do not add os.splice on AIX due to compatibility issues
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting core review, skip news

#23615 [3.9] bpo-42521: Add note about 'Python -d' only working on debug builds (GH-23607)
  Python/initconfig.c
Labels: CLA signed, awaiting merge, skip news

#23556 bpo-42504: fix for MACOSX_DEPLOYMENT_TARGET=11
  Lib/distutils/spawn.py
  Lib/distutils/tests/test_build_ext.py
  Lib/test/test_posix.py
  Misc/NEWS.d/next/macOS/2020-12-02-15-48-40.bpo-42504.RQmMOR.rst
  setup.py
Labels: CLA signed, awaiting merge

#23622 [3.9] bpo-42504: fix for MACOSX_DEPLOYMENT_TARGET=11 (GH-23556)
  Lib/distutils/spawn.py
  Lib/distutils/tests/test_build_ext.py
  Lib/test/test_posix.py
  Misc/NEWS.d/next/macOS/2020-12-02-15-48-40.bpo-42504.RQmMOR.rst
  setup.py
Labels: :robot: automerge, CLA signed, awaiting merge

#23604 bpo-10486 - Remove the conditional for setting query.
  Lib/http/server.py
Labels: CLA signed, awaiting core review, skip news

#23612 bpo-42328: Skip some tests with themes vista and xpnative on Windows 7
  Lib/tkinter/test/test_ttk/test_style.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-tests

#23625 [3.8] bpo-42328: Skip some tests with themes vista and xpnative on Windows 7 (GH-23612)
  Lib/tkinter/test/test_ttk/test_style.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#23624 [3.9] bpo-42328: Skip some tests with themes vista and xpnative on Windows 7 (GH-23612)
  Lib/tkinter/test/test_ttk/test_style.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#23458 bpo-42431: Fix outdated bytes comments
  Include/bytesobject.h
  Include/cpython/bytesobject.h
  Include/internal/pycore_format.h
  Makefile.pre.in
  Objects/bytearrayobject.c
  Objects/bytesobject.c
  Objects/clinic/bytearrayobject.c.h
  Objects/clinic/bytesobject.c.h
  Objects/unicodeobject.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: CLA signed, awaiting core review, skip news

#23627 bpo-42553: Fix test_asyncio.test_call_later()
  Lib/test/test_asyncio/test_events.py
  Misc/NEWS.d/next/Tests/2020-12-03-13-32-44.bpo-42553.2TRE2N.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-tests

#23626 bpo-42262: Py_NewRef() casts its argument to PyObject*
  Include/object.h
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting core review, skip news

#23629 [3.8] bpo-42553: Fix test_asyncio.test_call_later() (GH-23627)
  Lib/test/test_asyncio/test_events.py
  Misc/NEWS.d/next/Tests/2020-12-03-13-32-44.bpo-42553.2TRE2N.rst
Labels: CLA signed, awaiting merge, type-tests

#23628 [3.9] bpo-42553: Fix test_asyncio.test_call_later() (GH-23627)
  Lib/test/test_asyncio/test_events.py
  Misc/NEWS.d/next/Tests/2020-12-03-13-32-44.bpo-42553.2TRE2N.rst
Labels: CLA signed, awaiting merge, type-tests

#23603 bpo-42523: Fix supported versions in "Using Python on Windows"
  Doc/using/windows.rst
Labels: CLA signed, awaiting review, needs backport to 3.9, skip news, type-documentation

#23631 [3.9] bpo-42523: Fix supported versions in "Using Python on Windows" (GH-23603)
  Doc/using/windows.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23632 bpo-42562: Fix issue when dis failed to parse function that has no line numbers
  Lib/dis.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Library/2020-12-03-22-42-03.bpo-42562.2hPmhi.rst
Labels: CLA signed, awaiting change review

#23636 bpo-42246: Don't forget the entry block when ensuring that all exits have a line number
  Lib/test/test_compile.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
Labels: CLA signed, awaiting core review, skip news

#23637 bpo-41473: Reenable test_gdb on gdb 9.2 and newer
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Tests/2020-12-04-11-47-09.bpo-41473.W_updK.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-tests

#23641 [3.8] bpo-41473: Reenable test_gdb on gdb 9.2 and newer (GH-23637)
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Tests/2020-12-04-11-47-09.bpo-41473.W_updK.rst
Labels: CLA signed, awaiting merge, type-tests

#23640 [3.9] bpo-41473: Reenable test_gdb on gdb 9.2 and newer (GH-23637)
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Tests/2020-12-04-11-47-09.bpo-41473.W_updK.rst
Labels: CLA signed, awaiting merge, type-tests

#23630 bpo-42116: Fix inspect.getsource handling of trailing comments
  Lib/inspect.py
  Lib/test/inspect_fodder.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2020-12-03-15-42-32.bpo-42116.yIwroP.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#23419 bpo-31904: fix test_doctest.py failures for VxWorks
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Tests/2020-11-20-15-07-18.bpo-31904.EBJXjJ.rst
Labels: CLA signed, awaiting merge, type-tests

#23643 [3.9] bpo-42116: Fix inspect.getsource handling of trailing comments (GH-23630)
  Lib/inspect.py
  Lib/test/inspect_fodder.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2020-12-03-15-42-32.bpo-42116.yIwroP.rst
Labels: CLA signed, awaiting merge, type-bugfix

#23644 [3.8] bpo-42116: Fix inspect.getsource handling of trailing comments (GH-23630)
  Lib/inspect.py
  Lib/test/inspect_fodder.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2020-12-03-15-42-32.bpo-42116.yIwroP.rst
Labels: CLA signed, awaiting merge, type-bugfix

#23578 [3.9] bpo-42482: remove reference to exc_traceback from TracebackException (GH-23531)
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2020-11-27-16-46-58.bpo-42482.EJC3sd.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23633 bpo-17735: make inspect.findsource raise OsError instead of IndexError wh…
  Lib/inspect.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2020-12-03-22-22-24.bpo-17735.Qsaaue.rst
Labels: CLA signed, awaiting merge

#23616 bpo-42545: Check that all symbols in the limited ABI are exported
  .github/workflows/build.yml
  .travis.yml
  Doc/data/stable_abi.dat
  Makefile.pre.in
  Tools/scripts/stable_abi.py
Labels: CLA signed, skip news

#23646 [3.9] bpo-17735: inspect.findsource now raises OSError when co_lineno is out of range (GH-23633)
  Lib/inspect.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2020-12-03-22-22-24.bpo-17735.Qsaaue.rst
Labels: CLA signed, awaiting merge, type-bugfix

#23648 bpo-42545: Improve the error message in the stable API script
  Tools/scripts/stable_abi.py
Labels: CLA signed, awaiting core review, skip news

#23469 bpo-26131: Deprecate usage of load_module()
  Doc/whatsnew/3.10.rst
  Lib/importlib/_abc.py
  Lib/importlib/_bootstrap.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_importlib/builtin/test_loader.py
  Lib/test/test_importlib/extension/test_loader.py
  Lib/test/test_importlib/frozen/test_loader.py
  Lib/test/test_importlib/import_/test___loader__.py
  Lib/test/test_importlib/import_/test___package__.py
  Lib/test/test_importlib/import_/test_api.py
  Lib/test/test_importlib/import_/test_caching.py
  Lib/test/test_importlib/import_/test_fromlist.py
  Lib/test/test_importlib/import_/test_meta_path.py
  Lib/test/test_importlib/test_abc.py
  Lib/test/test_importlib/test_api.py
  Lib/test/test_importlib/test_spec.py
  Lib/test/test_venv.py
  Lib/test/test_zipimport.py
  Lib/zipimport.py
  Misc/NEWS.d/next/Core and Builtins/2020-10-22-17-27-08.bpo-26131.B-Veg7.rst
  Misc/NEWS.d/next/Library/2020-10-22-17-26-35.bpo-26131.CAsI3O.rst
  Misc/NEWS.d/next/Library/2020-11-22-12-30-26.bpo-26131.-HsFPG.rst
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: :robot: automerge, CLA signed, awaiting core review

#23623 bpo-42536: GC track recycled tuples
  Lib/test/test_builtin.py
  Lib/test/test_dict.py
  Lib/test/test_enumerate.py
  Lib/test/test_itertools.py
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-02-20-23-31.bpo-42536.Kx3ZOu.rst
  Modules/_functoolsmodule.c
  Modules/itertoolsmodule.c
  Objects/dictobject.c
  Objects/enumobject.c
  Objects/odictobject.c
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#23649 bpo-41116: Fix setup.py test for macOS Tcl/Tk frameworks
  setup.py
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news

#23650 [3.9] bpo-41116: Fix setup.py test for macOS Tcl/Tk frameworks (GH-23649)
  Misc/NEWS.d/next/macOS/2020-12-04-23-09-11.bpo-41116.mSbXyV.rst
  setup.py
Labels: CLA signed, awaiting review, skip news

#19975 bpo-30459: Cast the result of PyList_SET_ITEM() to void
  Include/cpython/listobject.h
  Include/cpython/tupleobject.h
  Misc/NEWS.d/next/C API/2020-05-06-23-54-57.bpo-30459.N9_Jai.rst
Labels: CLA signed, awaiting merge

#23638 bpo-5054: CGIHTTPRequestHandler.run_cgi() HTTP_ACCEPT improperly parsed
  Lib/http/server.py
  Lib/test/test_httpservers.py
  Misc/NEWS.d/next/Library/2020-12-04-03-51-12.bpo-5054.53StYZ.rst
Labels: CLA signed, awaiting core review

#23657 [3.9] bpo-5054: CGIHTTPRequestHandler.run_cgi() HTTP_ACCEPT improperly parsed (GH-23638)
  Lib/http/server.py
  Lib/test/test_httpservers.py
  Misc/NEWS.d/next/Library/2020-12-04-03-51-12.bpo-5054.53StYZ.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23656 bpo-42576: Raise TypeError when passing in keyword arguments to GenericAlias
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-05-22-34-47.bpo-42576.lEeEl7.rst
  Objects/genericaliasobject.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9

#23659 [3.9] bpo-42576: Raise TypeError when passing in keyword arguments to GenericAlias (GH-23656)
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-05-22-34-47.bpo-42576.lEeEl7.rst
  Objects/genericaliasobject.c
Labels: :robot: automerge, CLA signed, awaiting merge

#23613 bpo-42532: Check if NonCallableMock's spec_arg is not None instead of call its __bool__ function
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2020-12-02-07-37-59.bpo-42532.ObNep_.rst
Labels: CLA signed, awaiting merge

#23663 bpo-42576: Clarify only debug builds are affected in news
  Misc/NEWS.d/next/Core and Builtins/2020-12-05-22-34-47.bpo-42576.lEeEl7.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9

#23664 bpo-42582: Remove asyncio._all_tasks_compat().
  Lib/asyncio/__init__.py
  Lib/asyncio/tasks.py
Labels: CLA signed, awaiting merge, skip news

#23666 [3.9] bpo-42576: Clarify only debug builds are affected in news (GH-23663)
  Misc/NEWS.d/next/Core and Builtins/2020-12-05-22-34-47.bpo-42576.lEeEl7.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23653 bpo-38843: Document behavior of default when attribute is already set
  Doc/library/argparse.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news, type-documentation

#23577 bpo-42508: Keep IDLE running on macOS
  Lib/idlelib/NEWS.txt
  Lib/idlelib/runscript.py
  Misc/NEWS.d/next/IDLE/2020-11-30-19-46-05.bpo-42508.fE7w4M.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#23669 [3.9] bpo-42508: Keep IDLE running on macOS (GH-23577)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/runscript.py
  Misc/NEWS.d/next/IDLE/2020-11-30-19-46-05.bpo-42508.fE7w4M.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#23671 Update macos installer ReadMe for 3.10.0a3
  Mac/BuildScript/resources/ReadMe.rtf
Labels: CLA signed, OS-mac, awaiting core review, skip issue, skip news

#23668 [3.9] bpo-38843: Document behavior of default when the attribute is already set (GH-23653)
  Doc/library/argparse.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#22487 bpo-41889: enum: fix multiple-inheritance regression
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-10-01-16-17-11.bpo-41889.qLkNh8.rst
Labels: CLA signed, awaiting merge

#23654 bpo-30459: Cast the result of PyCell_SET to void
  Doc/whatsnew/3.10.rst
  Include/cellobject.h
  Misc/NEWS.d/next/C API/2020-05-06-23-54-57.bpo-30459.N9_Jai.rst
Labels: CLA signed, awaiting merge

#22088 bpo-39825: fix sysconfig.get_config_var('EXT_SUFFIX') on windows
  Lib/sysconfig.py
  Lib/test/test_sysconfig.py
  Misc/NEWS.d/next/Library/2020-10-20-08-28-26.bpo-39825.n6KnG0.rst
Labels: CLA signed, OS-windows, awaiting review, needs backport to 3.8, needs backport to 3.9

#23682 [3.8] bpo-39825: Fixes sysconfig.get_config_var('EXT_SUFFIX') on Windows to match distutils (GH-22088)
  Lib/sysconfig.py
  Lib/test/test_sysconfig.py
  Misc/NEWS.d/next/Library/2020-10-20-08-28-26.bpo-39825.n6KnG0.rst
Labels: CLA signed, awaiting merge

#23681 [3.9] bpo-39825: Fixes sysconfig.get_config_var('EXT_SUFFIX') on Windows to match distutils (GH-22088)
  Lib/sysconfig.py
  Lib/test/test_sysconfig.py
  Misc/NEWS.d/next/Library/2020-10-20-08-28-26.bpo-39825.n6KnG0.rst
Labels: CLA signed, awaiting merge

#23662 bpo-42579: Make workaround for various versions of Sphinx more robust
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting merge, skip news

#23651 [3.9] bpo-42536: GC track recycled tuples (GH-23623)
  Lib/test/test_builtin.py
  Lib/test/test_dict.py
  Lib/test/test_enumerate.py
  Lib/test/test_itertools.py
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-02-20-23-31.bpo-42536.Kx3ZOu.rst
  Modules/_functoolsmodule.c
  Modules/itertoolsmodule.c
  Objects/dictobject.c
  Objects/enumobject.c
  Objects/odictobject.c
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#23652 [3.8] bpo-42536: GC track recycled tuples (GH-23623)
  Lib/test/test_builtin.py
  Lib/test/test_dict.py
  Lib/test/test_enumerate.py
  Lib/test/test_itertools.py
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-02-20-23-31.bpo-42536.Kx3ZOu.rst
  Modules/_functoolsmodule.c
  Modules/itertoolsmodule.c
  Objects/dictobject.c
  Objects/enumobject.c
  Objects/odictobject.c
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#21713 bpo-41462: add os.set_blocking() support for VxWorks RTOS
  Misc/NEWS.d/next/Library/2020-08-03-17-54-32.bpo-41462.ek38d_.rst
  Python/fileutils.c
Labels: CLA signed, awaiting review

#23685 [3.8] bpo-42574: Use format() instead of f-string in Tools/clinic/clinic.py to allow using older Python versions
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting merge, skip news

#23672 [3.8] bpo-41889: [Enum] fix multiple-inheritance regression (GH-22487)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-10-01-16-17-11.bpo-41889.qLkNh8.rst
Labels: CLA signed, awaiting review

#23673 [3.9] bpo-41889: [Enum] fix multiple-inheritance regression (GH-22487)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-10-01-16-17-11.bpo-41889.qLkNh8.rst
Labels: CLA signed, awaiting review

#23642 bpo-32381: Fix PyRun_SimpleFileExFlags() encoding
  Misc/NEWS.d/next/Core and Builtins/2020-12-04-17-17-44.bpo-32381.NY5t2S.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting core review

#23691 bpo-42599: Remove PyModule_GetWarningsModule() of pylifecycle.c
  Doc/whatsnew/3.10.rst
  Python/errors.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting review, skip news

#23692 [3.9] bpo-32381: Fix PyRun_SimpleFileExFlags() encoding (GH-23642)
  Misc/NEWS.d/next/Core and Builtins/2020-12-04-17-17-44.bpo-32381.NY5t2S.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting core review

#23695 bpo-41910: move news entry
  Misc/NEWS.d/3.10.0a2.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#23696 [3.8] bpo-32381: Fix PyRun_SimpleFileExFlags() encoding (GH-23642) (GH-23692)
  Misc/NEWS.d/next/Core and Builtins/2020-12-04-17-17-44.bpo-32381.NY5t2S.rst
  Python/pythonrun.c
Labels: CLA signed, awaiting core review

#23698 [3.8] bpo-41910: move news entry (GH-23695)
  Misc/NEWS.d/3.8.7rc1.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#23697 [3.9] bpo-41910: move news entry (GH-23695)
  Misc/NEWS.d/3.9.1rc1.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#22497 bpo-41907: fix format() behavior for IntFlag
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-10-02-10-19-49.bpo-41907.wiIEsz.rst
Labels: CLA signed, awaiting core review

#23703 [3.9] bpo-41907: [Enum] fix format() behavior for IntFlag (GH-22497)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-10-02-10-19-49.bpo-41907.wiIEsz.rst
Labels: CLA signed, awaiting review

#23704 [3.8] bpo-41907: [Enum] fix format() behavior for IntFlag (GH-22497)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-10-02-10-19-49.bpo-41907.wiIEsz.rst
Labels: CLA signed, awaiting review

#23705 [Enum] reformat and add doc strings
  Lib/enum.py
  Lib/test/test_enum.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#23706 [3.8] [Enum] reformat and add doc strings (GH-23705).
  Lib/enum.py
  Lib/test/test_enum.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#23707 [3.9] [Enum] reformat and add doc strings (GH-23705).
  Lib/enum.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#23700 bpo-32381: Rewrite PyErr_ProgramText()
  Python/errors.c
Labels: CLA signed, awaiting core review, skip news

#23701 bpo-35134: Add Include/cpython/pythonrun.h file
  Include/cpython/pythonrun.h
  Include/pythonrun.h
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: CLA signed, skip news

#21688 bpo-41443: Add more attribute checking for some test in test_posix.py
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Tests/2020-07-30-18-43-05.bpo-41443.834gyg.rst
Labels: CLA signed, awaiting review, type-tests

#21684 bpo-41439: skip test_random_fork() and testIssue8621() if os.fork() is not supported
  Lib/test/test_ssl.py
  Lib/test/test_uuid.py
  Misc/NEWS.d/next/Tests/2020-07-30-14-08-58.bpo-41439.yhteoi.rst
Labels: CLA signed, awaiting review, type-tests

#23709 bpo-32381: Add _PyRun_SimpleFileObject()
  Include/cpython/pythonrun.h
  Modules/main.c
  Python/pythonrun.c
Labels: CLA signed, awaiting core review, skip news

#22853 [3.8] bpo-40084: Enum - dir() includes member attributes (GH-19219)
  Lib/enum.py
  Lib/test/test_enum.py
  Lib/test/test_httplib.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2020-03-29-21-32-00.bpo-40084.MCYwcv.rst
Labels: CLA signed, awaiting review

#23711 bpo-32381: Remove unused _Py_fopen() function
  Include/cpython/fileutils.h
  Misc/NEWS.d/next/C API/2020-12-09-00-35-25.bpo-32381.Je08Ny.rst
  Python/fileutils.c
Labels: CLA signed, awaiting core review

#23723 bpo-32381: Add _PyRun_AnyFileObject()
  Include/cpython/pylifecycle.h
  Include/cpython/pythonrun.h
  Modules/main.c
  Python/pylifecycle.c
  Python/pythonrun.c
Labels: CLA signed, awaiting core review, skip news

#23718 bpo-31904: Define THREAD_STACK_SIZE for VxWorks
  Misc/NEWS.d/next/Library/2020-12-09-15-23-28.bpo-31904.g3k5k3.rst
  Python/thread_pthread.h
Labels: CLA signed, awaiting review

#23710 [doc] Document logging.basicConfig default format
  Doc/library/logging.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23726 [doc] Link to issue regarding logging.disable level param default value
  Doc/library/logging.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#23714 bpo-42567: [Enum] call __init_subclass__ after members are added
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-12-08-22-43-35.bpo-42678.ba9ktU.rst
Labels: CLA signed, awaiting core review

#23722 bpo-42517: [Enum] do not convert private names into members
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-12-09-10-59-16.bpo-42517.FKEVcZ.rst
Labels: CLA signed, awaiting core review

#23731 [3.8] [doc] Link to issue regarding logging.disable level param defau…
  Doc/library/logging.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23732 [3.9] [doc] Link to issue regarding logging.disable level param defau…
  Doc/library/logging.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23730 bpo-42591: Export missing Py_FrozenMain() symbol
  Include/pylifecycle.h
  Misc/NEWS.d/next/C API/2020-12-10-10-43-03.bpo-42591.CXNY8G.rst
  PC/python3dll.c
Labels: CLA signed, awaiting core review, needs backport to 3.9

#23729 bpo-41877: Improve docs for assert misspellings check in mock
  Doc/library/unittest.mock.rst
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2020-12-10-09-24-44.bpo-41877.iJSCvM.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#23735 bpo-42385: [Enum] add `_generate_next_value_` to StrEnum
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-12-09-19-45-32.bpo-42385.boGbjo.rst
Labels: CLA signed, awaiting core review

#23725 bpo-34750: [Enum] add `_EnumDict.update()` support
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-12-09-14-15-48.bpo-34750.x8TASR.rst
Labels: CLA signed, awaiting core review

#22736 bpo-42059: Fixed required/optional keys with old-style TypedDict
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2020-10-17-12-42-08.bpo-42059.ZGMZ3D.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#23548 bpo-41879: Doc: Fix description of async for statement
  Doc/reference/compound_stmts.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#23739 bpo-39717: [tarfile] update nested exception raising
  Lib/tarfile.py
  Misc/NEWS.d/next/Library/2020-12-10-18-36-52.bpo-39717.sK2u0w.rst
Labels: CLA signed, awaiting merge

#23749 [3.9] bpo-41879: Doc: Fix description of async for statement (GH-23548)
  Doc/reference/compound_stmts.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#23719 Add two spaces around equal sign in documentation
  Doc/library/subprocess.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#23753 bpo-30858: Improve error location for expressions with assignments
  Grammar/python.gram
  Lib/test/test_exceptions.py
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-13-15-23-09.bpo-30858.-f9G4z.rst
  Parser/parser.c
Labels: CLA signed, awaiting merge

#23060 bpo-42195: Ensure consistency of Callable's __args__ in collections.abc and typing
  Lib/_collections_abc.py
  Lib/collections/abc.py
  Lib/test/test_genericalias.py
  Lib/test/test_types.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2020-11-20-00-57-47.bpo-42195.HeqcpS.rst
  Objects/genericaliasobject.c
  Objects/unionobject.c
Labels: CLA signed, awaiting merge

#23690 bpo-42598: Fix implicit function declarations in configure
  Misc/NEWS.d/next/Build/2020-12-13-14-43-10.bpo-42598.7ipr5H.rst
  configure
  configure.ac
Labels: awaiting merge

#23756 [3.9] bpo-42598: Fix implicit function declarations in configure (GH-23690)
  Misc/NEWS.d/next/Build/2020-12-13-14-43-10.bpo-42598.7ipr5H.rst
  configure
  configure.ac
Labels: CLA signed, awaiting review

#23757 [3.8] bpo-42598: Fix implicit function declarations in configure (GH-23690)
  Misc/NEWS.d/next/Build/2020-12-13-14-43-10.bpo-42598.7ipr5H.rst
  configure
  configure.ac
Labels: CLA signed, awaiting review

#23676 [3.9] bpo-42532: Check if NonCallableMock's spec_arg is not None instead of call its __bool__ function (GH-23613)
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2020-12-02-07-37-59.bpo-42532.ObNep_.rst
Labels: CLA signed, awaiting merge

#23760 bpo-42634: Don't generate spurious line number in try-except-finally.
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting core review, skip news

#23761 bpo-42635: Make JUMP_ABSOLUTE at end of 'for' loop as artificial to avoid spurious line events.
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
Labels: CLA signed, awaiting core review, skip news

#23765 [3.9] bpo-42195: Ensure consistency of Callable's __args__ in collections.abc and typing (GH-23060)
  Lib/_collections_abc.py
  Lib/collections/abc.py
  Lib/test/test_genericalias.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2020-11-20-00-57-47.bpo-42195.HeqcpS.rst
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge

#23767 [3.6] bpo-40791: Make compare_digest more constant-time. (GH-23438)
  Misc/NEWS.d/next/Security/2020-05-28-06-06-47.bpo-40791.QGZClX.rst
  Modules/_operator.c
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix, type-security

#23759 bpo-36541: Add lib2to3 grammar PEP-570 pos-only arg parsing
  Lib/lib2to3/Grammar.txt
  Lib/lib2to3/tests/test_parser.py
  Misc/NEWS.d/next/Library/2020-12-14-08-23-57.bpo-36541.qdEtZv.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix, type-tests

#23769 [3.8] bpo-36541: Add lib2to3 grammar PEP-570 pos-only arg parsing (GH-23759)
  Lib/lib2to3/Grammar.txt
  Lib/lib2to3/tests/test_parser.py
  Misc/NEWS.d/next/Library/2020-12-14-08-23-57.bpo-36541.qdEtZv.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix, type-tests

#23768 [3.9] bpo-36541: Add lib2to3 grammar PEP-570 pos-only arg parsing (GH-23759)
  Lib/lib2to3/Grammar.txt
  Lib/lib2to3/tests/test_parser.py
  Misc/NEWS.d/next/Library/2020-12-14-08-23-57.bpo-36541.qdEtZv.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix, type-tests

#23737 bpo-41877: Check for misspelled speccing arguments
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2020-12-10-19-49-52.bpo-41877.wiVlPc.rst
Labels: CLA signed, awaiting review, type-enhancement, type-tests

#23770 bpo-42639: Cleanup atexitmodule.c
  Include/cpython/pylifecycle.h
  Include/internal/pycore_interp.h
  Lib/test/test_atexit.py
  Modules/atexitmodule.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#23771 bpo-42639: atexit now logs callbacks exceptions
  Doc/whatsnew/3.10.rst
  Include/internal/pycore_interp.h
  Include/internal/pycore_pylifecycle.h
  Lib/test/test_threading.py
  Misc/NEWS.d/next/Library/2020-12-14-22-31-22.bpo-42639.5Z3iWX.rst
  Modules/atexitmodule.c
  Python/pylifecycle.c
  setup.py
Labels: CLA signed, awaiting core review

#23741 bpo-31904: Enable libpython3.so share library for VxWorks
  Misc/NEWS.d/next/Build/2020-12-11-18-04-38.bpo-31904.j3j6d8.rst
  configure
  configure.ac
Labels: CLA signed, awaiting review

#23747 [3.9] bpo-42059: Fix required/optional keys for TypedDict(..., total=False) (GH-22736)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2020-10-17-12-42-08.bpo-42059.ZGMZ3D.rst
Labels: CLA signed, awaiting review

#23746 [3.9] bpo-40084: Enum - dir() includes member attributes (GH-19219)
  Lib/enum.py
  Lib/test/test_enum.py
  Lib/test/test_httplib.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2020-03-29-21-32-00.bpo-40084.MCYwcv.rst
Labels: CLA signed, awaiting merge

#23734 [3.9] bpo-42591: Export missing Py_FrozenMain() symbol (GH-23730)
  Include/pylifecycle.h
  Misc/NEWS.d/next/C API/2020-12-10-10-43-03.bpo-42591.CXNY8G.rst
Labels: CLA signed, awaiting core review

#23748 [3.9] bpo-42517: [Enum] do not convert private names into members (GH-23722)
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-12-09-10-59-16.bpo-42517.FKEVcZ.rst
Labels: CLA signed, awaiting merge

#23772 [3.9] bpo-42567: [Enum] call __init_subclass__ after members are added (GH-23714)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2020-12-08-22-43-35.bpo-42678.ba9ktU.rst
Labels: CLA signed, awaiting core review

#23773 bpo-33610: Edit idlelib.codecontext
  Lib/idlelib/codecontext.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news

#23774 [3.8] bpo-33610: Edit idlelib.codecontext (GH-23773)
  Lib/idlelib/codecontext.py
Labels: CLA signed, awaiting merge, skip news

#23743 bpo-42246: Remove DO_NOT_EMIT_BYTECODE macros, so that while loops and if statements conform to PEP 626.
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Lib/test/test_peepholer.py
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: skip news

#23775 [3.9] bpo-33610: Edit idlelib.codecontext (GH-23773)
  Lib/idlelib/codecontext.py
Labels: CLA signed, awaiting merge, skip news

#23763 bpo-42639: Move atexit state to PyInterpreterState
  Include/internal/pycore_interp.h
  Include/internal/pycore_pylifecycle.h
  Lib/test/test_atexit.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-09-01-55-10.bpo-42639.5pI5HG.rst
  Modules/atexitmodule.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting merge
