Repository python/cpython, pull requests merged in 2020-08, with the labels that each got.

#21695 bpo-41421: Algebraic simplification for random.paretovariate()
  Lib/random.py
  Misc/NEWS.d/next/Library/2020-08-01-00-51-15.bpo-41421.dHKRVB.rst
Labels: CLA signed, awaiting merge

#21700 Convert a "while 1" to "while True"
  Lib/random.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#21574 bpo-40979: refactored typing.rst; same content, new sub-sections and ordering
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2020-07-21-15-23-30.bpo-40979.pLA8rO.rst
Labels: CLA signed, awaiting merge

#21707 bpo-41424 Corrected grammatical error in Tkinter-Packer documentation
  Doc/library/tkinter.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-bugfix, type-documentation

#21708 [3.9] bpo-41424: Remove extra words in Tkinter-Packer documentation (GH-21707)
  Doc/library/tkinter.rst
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-documentation

#21709 [3.8] bpo-41424: Remove extra words in Tkinter-Packer documentation (GH-21707)
  Doc/library/tkinter.rst
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-documentation

#21706 bpo-41425: Make tkinter doc example runnable
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Library/2020-08-03-01-59-48.bpo-41425.KJo6zF.rst
Labels: CLA not signed, awaiting review, type-documentation

#21711 [3.8] bpo-41425: Make tkinter doc example runnable (GH-21706)
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Library/2020-08-03-01-59-48.bpo-41425.KJo6zF.rst
Labels: CLA not signed, awaiting merge, type-documentation

#21710 [3.9] bpo-41425: Make tkinter doc example runnable (GH-21706)
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Library/2020-08-03-01-59-48.bpo-41425.KJo6zF.rst
Labels: CLA not signed, awaiting merge, type-documentation

#21705 A (very) slight speed improvement for iterating over bytes
  Objects/bytesobject.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#21449 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/test__opcode.py
  Lib/test/test_asyncore.py
  Lib/test/test_binascii.py
  Lib/test/test_bisect.py
  Lib/test/test_builtin.py
  Lib/test/test_concurrent_futures.py
  Lib/test/test_configparser.py
  Lib/test/test_coroutines.py
  Lib/test/test_curses.py
  Lib/test/test_datetime.py
  Lib/test/test_mmap.py
  Lib/test/test_signal.py
  Lib/test/test_ssl.py
  Lib/test/test_tarfile.py
  Lib/test/test_threading.py
  Lib/test/test_trace.py
  Lib/test/test_tracemalloc.py
  Lib/test/test_xml_etree_c.py
  Lib/unittest/test/test_discovery.py
  Lib/unittest/test/test_result.py
Labels: CLA signed, awaiting review, skip news, type-tests

#21451 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/test_bdb.py
  Lib/test/test_code_module.py
  Lib/test/test_embed.py
  Lib/test/test_gzip.py
  Lib/test/test_largefile.py
  Lib/test/test_lltrace.py
  Lib/test/test_ordered_dict.py
  Lib/test/test_pathlib.py
  Lib/test/test_pipes.py
  Lib/test/test_posix.py
  Lib/test/test_pydoc.py
  Lib/test/test_resource.py
  Lib/test/test_runpy.py
  Lib/test/test_sax.py
  Lib/test/test_sys.py
  Lib/test/test_syslog.py
  Lib/test/test_ttk_textonly.py
  Lib/test/test_unicode_file_functions.py
  Lib/test/test_urllib2.py
  Lib/test/test_venv.py
Labels: CLA signed, awaiting review, skip news, type-tests

#21448 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/test_argparse.py
  Lib/test/test_asyncgen.py
  Lib/test/test_clinic.py
  Lib/test/test_codecs.py
  Lib/test/test_doctest.py
  Lib/test/test_exceptions.py
  Lib/test/test_ftplib.py
  Lib/test/test_gc.py
  Lib/test/test_genericpath.py
  Lib/test/test_imghdr.py
  Lib/test/test_mimetypes.py
  Lib/test/test_ntpath.py
  Lib/test/test_operator.py
  Lib/test/test_optparse.py
  Lib/test/test_peg_generator/test_c_parser.py
  Lib/test/test_queue.py
  Lib/test/test_spwd.py
  Lib/test/test_stat.py
  Lib/test/test_tokenize.py
  Lib/test/test_webbrowser.py
Labels: CLA signed, awaiting review, skip news, type-tests

#21718 bpo-38912: regrtest logs unraisable exception into sys.__stderr__
  Lib/test/libregrtest/utils.py
  Lib/test/test_regrtest.py
Labels: CLA signed, awaiting core review, skip news

#21721 bpo-38156: Fix compiler warning in PyOS_StdioReadline()
  Parser/myreadline.c
Labels: CLA signed, awaiting core review, skip news

#21720 bpo-41467: Fix asyncio recv_into() on Windows
  Lib/asyncio/windows_events.py
  Misc/NEWS.d/next/Library/2020-08-04-00-20-30.bpo-41467.Z8DgTL.rst
Labels: CLA signed, awaiting core review

#21723 [3.9] bpo-38156: Fix compiler warning in PyOS_StdioReadline() (GH-21721)
  Parser/myreadline.c
Labels: CLA signed, awaiting merge, skip news

#21726 [3.8] bpo-41467: Fix asyncio recv_into() on Windows (GH-21720)
  Lib/asyncio/windows_events.py
  Misc/NEWS.d/next/Library/2020-08-04-00-20-30.bpo-41467.Z8DgTL.rst
Labels: CLA signed, awaiting merge

#21725 [3.8] bpo-38156: Fix compiler warning in PyOS_StdioReadline() (GH-21721)
  Parser/myreadline.c
Labels: CLA signed, awaiting merge, skip news

#21724 [3.9] bpo-41467: Fix asyncio recv_into() on Windows (GH-21720)
  Lib/asyncio/windows_events.py
  Misc/NEWS.d/next/Library/2020-08-04-00-20-30.bpo-41467.Z8DgTL.rst
Labels: CLA signed, awaiting merge

#21674 bpo-41431: Optimize dict_merge for copy
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-02-15-53-12.bpo-41431.TblUBT.rst
  Objects/dictobject.c
Labels: CLA signed, awaiting core review

#21377 [3.5] bpo-29778: Ensure python3.dll is loaded from correct locations when Python is embedded (GH-21297)
  Misc/NEWS.d/next/Security/2020-07-03-17-21-37.bpo-29778.cR_fGS.rst
  PC/getpathp.c
  PCbuild/pyproject.props
  PCbuild/python.props
  Python/dynload_win.c
Labels: CLA signed, OS-windows, awaiting core review, type-bugfix, type-security

#21233 [3.5] bpo-41004: Resolve hash collisions for IPv4Interface and IPv6In…
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Security/2020-06-29-16-02-29.bpo-41004.ovF0KZ.rst
Labels: CLA signed, awaiting merge, type-security

#17536 bpo-36982: Add support for extended color functions in ncurses 6.1
  Doc/library/curses.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_curses.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2019-05-25-05-27-39.bpo-36982.0UHgfB.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: CLA signed, awaiting merge

#21452 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/eintrdata/eintr_tester.py
  Lib/test/test_email/test_email.py
  Lib/test/test_multibytecodec.py
  Lib/test/test_pdb.py
  Lib/test/test_urllib2_localnet.py
  Lib/test/test_warnings/__init__.py
Labels: CLA signed, awaiting review, skip news

#21727 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/test_importlib/fixtures.py
  Lib/test/test_importlib/import_/test_packages.py
  Lib/test/test_importlib/source/test_file_loader.py
  Lib/test/test_importlib/source/test_finder.py
  Lib/test/test_importlib/test_abc.py
  Lib/test/test_importlib/test_api.py
  Lib/test/test_importlib/test_pkg_import.py
  Lib/test/test_importlib/test_spec.py
  Lib/test/test_importlib/test_threaded_import.py
  Lib/test/test_importlib/test_windows.py
  Lib/test/test_importlib/util.py
  Lib/test/test_inspect.py
  Lib/test/test_site.py
  Lib/test/test_tools/test_fixcid.py
  Lib/test/test_tools/test_i18n.py
  Lib/test/test_tools/test_lll.py
  Lib/test/test_tools/test_pathfix.py
  Lib/test/test_tools/test_pindent.py
  Lib/test/test_tools/test_sundry.py
Labels: CLA signed, awaiting review, skip news

#21714 bpo-41463: Generate information about jumps from 'opcode.py' rather than duplicating it in 'compile.c'
  Include/opcode.h
  Python/compile.c
  Tools/scripts/generate_opcode_h.py
Labels: CLA signed, awaiting merge, skip news

#21479 bpo-36346: Doc: Update removal schedule of legacy Unicode
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21738 [3.9] bpo-36346: Doc: Update removal schedule of legacy Unicode (GH-21479)
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21739 [3.8] bpo-36346: Doc: Update removal schedule of legacy Unicode (GH-21479)
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#20312 bpo-40726: handle uninitalized end_lineno on ast.increment_lineno
  Lib/ast.py
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2020-05-22-12-45-58.bpo-40726.7oBdMw.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21741 [3.9] bpo-40726: handle uninitalized end_lineno on ast.increment_lineno (GH-20312)
  Lib/ast.py
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2020-05-22-12-45-58.bpo-40726.7oBdMw.rst
Labels: CLA signed, awaiting merge

#21722 bpo-40989: Fix compiler warning in winreg.c
  PC/winreg.c
Labels: CLA signed, awaiting core review, skip news

#21745 [3.8] bpo-40726: handle uninitalized end_lineno on ast.increment_lineno
  Lib/ast.py
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2020-05-22-12-45-58.bpo-40726.7oBdMw.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#21736 bpo-41482: Fix error in ipaddress.IPv4Network docstring
  Lib/ipaddress.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news

#21746 [3.8] bpo-41482: Fix error in ipaddress.IPv4Network docstring (GH-21736)
  Lib/ipaddress.py
Labels: CLA signed, awaiting merge, skip news

#21747 [3.9] bpo-41482: Fix error in ipaddress.IPv4Network docstring (GH-21736)
  Lib/ipaddress.py
Labels: CLA signed, awaiting merge, skip news

#21743 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/test_dbm_gnu.py
  Lib/test/test_faulthandler.py
  Lib/test/test_grp.py
  Lib/test/test_http_cookiejar.py
  Lib/test/test_httpservers.py
  Lib/test/test_import/__init__.py
  Lib/test/test_ntpath.py
  Lib/test/test_site.py
  Lib/test/test_socketserver.py
  Lib/test/test_statistics.py
  Lib/test/test_tabnanny.py
  Lib/test/test_tcl.py
  Lib/test/test_tools/test_md5sum.py
  Lib/test/test_turtle.py
  Lib/test/test_urllib2net.py
  Lib/test/test_urllibnet.py
  Lib/test/test_webbrowser.py
  Lib/test/test_winsound.py
  Lib/tkinter/test/test_tkinter/test_images.py
  Lib/tkinter/test/test_tkinter/test_loadtk.py
Labels: CLA signed, awaiting review, skip news

#21754 bpo-41492: Fixes the description appearing in UAC prompts
  .azure-pipelines/windows-release/msi-steps.yml
  .azure-pipelines/windows-release/stage-pack-msix.yml
  .azure-pipelines/windows-release/stage-sign.yml
  Misc/NEWS.d/next/Windows/2020-08-06-16-59-10.bpo-41492.2FQ9cM.rst
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-bugfix

#21756 [3.8] bpo-41492: Fixes the description appearing in UAC prompts on Windows (GH-21754)
  .azure-pipelines/windows-release/msi-steps.yml
  .azure-pipelines/windows-release/stage-pack-msix.yml
  .azure-pipelines/windows-release/stage-sign.yml
  Misc/NEWS.d/next/Windows/2020-08-06-16-59-10.bpo-41492.2FQ9cM.rst
Labels: CLA signed, awaiting merge, type-bugfix

#21755 [3.9] bpo-41492: Fixes the description appearing in UAC prompts on Windows (GH-21754)
  .azure-pipelines/windows-release/msi-steps.yml
  .azure-pipelines/windows-release/stage-pack-msix.yml
  .azure-pipelines/windows-release/stage-sign.yml
  Misc/NEWS.d/next/Windows/2020-08-06-16-59-10.bpo-41492.2FQ9cM.rst
Labels: CLA signed, awaiting merge, type-bugfix

#21734 bpo-41371: Handle lzma lib import error in test_zoneinfo.py
  Lib/test/test_zoneinfo/test_zoneinfo.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip news, type-tests

#21751 bpo-41493: Refactoring dictresize
  Objects/dictobject.c
Labels: CLA signed, awaiting core review, skip news

#21685 bpo-41440: add os.cpu_count() support for VxWorks RTOS
  Doc/whatsnew/3.10.rst
  Misc/NEWS.d/next/Library/2020-07-30-14-56-58.bpo-41440.rju34k.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#21749 bpo-39871: Fix an error in a news entry
  Misc/NEWS.d/3.9.0a5.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#21760 [3.9] bpo-39871: Fix an error in a news entry (GH-21749)
  Misc/NEWS.d/3.9.0a5.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21162 bpo-41098: Doc: Add missing deprecated directives
  Doc/c-api/exceptions.rst
  Include/cpython/pyerrors.h
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21762 [3.8] bpo-41098: Doc: Add missing deprecated directives (GH-21162)
  Doc/c-api/exceptions.rst
  Include/cpython/pyerrors.h
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21761 [3.9] bpo-41098: Doc: Add missing deprecated directives (GH-21162)
  Doc/c-api/exceptions.rst
  Include/cpython/pyerrors.h
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21764 bpo-40275: Use new test.support helper submodules in tests
  Lib/ctypes/test/test_loading.py
  Lib/sqlite3/test/hooks.py
  Lib/test/_test_multiprocessing.py
  Lib/test/test___all__.py
  Lib/test/test_asyncio/test_proactor_events.py
  Lib/test/test_ntpath.py
  Lib/test/test_ossaudiodev.py
  Lib/test/test_platform.py
  Lib/test/test_posixpath.py
  Lib/test/test_py_compile.py
  Lib/test/test_source_encoding.py
  Lib/test/test_startfile.py
  Lib/test/test_sundry.py
  Lib/test/test_winconsoleio.py
  Lib/test/test_zoneinfo/_support.py
Labels: CLA signed, awaiting merge, skip news

#21766 bpo-41477: Make ctypes optional in test_genericalias
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Tests/2020-08-07-17-28-49.bpo-41477.GrFexU.rst
Labels: CLA signed, awaiting core review, type-tests

#21768 bpo-41473: Skip test_gdb with gdb 9.2 to work around gdb bug
  Lib/test/test_gdb.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#21770 [3.8] bpo-41473: Skip test_gdb with gdb 9.2 to work around gdb bug (GH-21768)
  Lib/test/test_gdb.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#21769 [3.9] bpo-41473: Skip test_gdb with gdb 9.2 to work around gdb bug (GH-21768)
  Lib/test/test_gdb.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#21772 bpo-40275: Use new test.support helper submodules in tests
  Lib/sqlite3/test/dbapi.py
  Lib/test/libregrtest/refleak.py
  Lib/test/libregrtest/win_utils.py
  Lib/test/test_audit.py
  Lib/test/test_bytes.py
  Lib/test/test_dbm_ndbm.py
  Lib/test/test_descr.py
  Lib/test/test_xml_etree.py
Labels: CLA signed, awaiting review, skip news

#21776 Update Azure Pipelines build to use Ubuntu 18.04 and move triggers into YAML files
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#21778 [3.8] Update Azure Pipelines build to use Ubuntu 18.04 and move triggers into YAML files (GH-21776)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#21777 [3.9] Update Azure Pipelines build to use Ubuntu 18.04 and move triggers into YAML files (GH-21776)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#21737 Update `open()` docs with link to File Tutorial
  Doc/library/functions.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#21757 bpo-41497: Fix potential UnicodeDecodeError in dis
  Lib/dis.py
  Misc/NEWS.d/next/Library/2020-08-07-06-06-29.bpo-41497.aBtsWz.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, type-bugfix

#21780 [3.9] Doc: Add a link to tutorial page from `open()` doc (GH-21737)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21781 [3.8] Doc: Add a link to tutorial page from `open()` doc (GH-21737)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21783 [3.8] bpo-41497: Fix potential UnicodeDecodeError in dis CLI (GH-21757)
  Lib/dis.py
  Misc/NEWS.d/next/Library/2020-08-07-06-06-29.bpo-41497.aBtsWz.rst
Labels: CLA signed, awaiting merge, type-bugfix

#21782 [3.9] bpo-41497: Fix potential UnicodeDecodeError in dis CLI (GH-21757)
  Lib/dis.py
  Misc/NEWS.d/next/Library/2020-08-07-06-06-29.bpo-41497.aBtsWz.rst
Labels: CLA signed, awaiting merge, type-bugfix

#21771 bpo-40275: Remove test helpers import in test.support
  Lib/ctypes/test/test_loading.py
  Lib/test/support/__init__.py
  Lib/test/test_os.py
  Lib/test/test_posixpath.py
Labels: CLA signed, awaiting review, skip news

#21785 bpo-40275: Use new test.support helper submodules in tests
  Lib/test/libregrtest/save_env.py
  Lib/test/test__osx_support.py
  Lib/test/test_dbm_ndbm.py
  Lib/test/test_zipfile64.py
Labels: CLA signed, awaiting review, skip news, type-tests

#21703 bpo-41455: Fix docs according to sources and devguide
  Doc/library/gc.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21786 [3.9] bpo-41455: Provide a link to how the third generation is collected in the GC docs (GH-21703)
  Doc/library/gc.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21787 [3.8] bpo-41455: Provide a link to how the third generation is collected in the GC docs (GH-21703)
  Doc/library/gc.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21346 Doc: Add output to example code in programming FAQ
  Doc/faq/programming.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#20958 bpo-35018: Sax parser provides no user access to lexical handlers
  Doc/library/xml.sax.handler.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_sax.py
  Lib/xml/sax/handler.py
  Misc/NEWS.d/next/Library/2020-06-17-23-49-45.bpo-35018.NP5_Qk.rst
Labels: CLA signed, awaiting changes

#21794 Improve renamed test_run.RecursionLimitTest
  Lib/idlelib/idle_test/test_run.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-tests

#21795 [3.9] Improve renamed test_run.RecursionLimitTest (GH-21794)
  Lib/idlelib/idle_test/test_run.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#21796 [3.8] Improve renamed test_run.RecursionLimitTest (GH-21794)
  Lib/idlelib/idle_test/test_run.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#21790 [3.9] Doc: Add output to example code in programming FAQ (GH-21346)
  Doc/faq/programming.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21791 [3.8] Doc: Add output to example code in programming FAQ (GH-21346)
  Doc/faq/programming.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21798 bpo-41468: Improve and test IDLE run error exit
  Lib/idlelib/NEWS.txt
  Lib/idlelib/idle_test/test_run.py
  Lib/idlelib/run.py
  Misc/NEWS.d/next/IDLE/2020-08-09-13-42-55.bpo-41468.zkP0_Y.rst
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9

#21800 [3.9] bpo-41468: Improve and test IDLE run error exit (GH-21798)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/idle_test/test_run.py
  Lib/idlelib/run.py
  Misc/NEWS.d/next/IDLE/2020-08-09-13-42-55.bpo-41468.zkP0_Y.rst
Labels: CLA signed, awaiting merge

#21801 [3.8] bpo-41468: Improve and test IDLE run error exit (GH-21798)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/idle_test/test_run.py
  Lib/idlelib/run.py
  Misc/NEWS.d/next/IDLE/2020-08-09-13-42-55.bpo-41468.zkP0_Y.rst
Labels: CLA signed, awaiting merge

#21804 [3.9] Update macOS installer welcome files for 3.9.0rc.
  Mac/BuildScript/resources/ReadMe.rtf
  Mac/BuildScript/resources/Welcome.rtf
Labels: CLA signed, OS-mac, awaiting core review, skip issue, skip news

#21808 bpo-41514: Fix buggy IDLE test
  Lib/idlelib/idle_test/test_run.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-bugfix, type-tests

#21807 [3.9] bpo-41194: Convert _ast extension to PEP 489
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting core review, skip news

#21810 [3.8] bpo-41514: Fix buggy IDLE test (GH-21808)
  Lib/idlelib/idle_test/test_run.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-tests

#21809 [3.9] bpo-41514: Fix buggy IDLE test (GH-21808)
  Lib/idlelib/idle_test/test_run.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix, type-tests

#21519 bpo-41324 Add a minimal decimal capsule API
  Doc/c-api/concrete.rst
  Doc/c-api/decimal.rst
  Include/pydecimal.h
  Lib/test/test_decimal.py
  Misc/NEWS.d/next/C API/2020-08-10-16-05-08.bpo-41324.waZD35.rst
  Modules/_decimal/_decimal.c
  Modules/_decimal/tests/deccheck.py
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting core review

#20441 bpo-16995: add support for base32 extended hex (base32hex)
  Doc/library/base64.rst
  Doc/whatsnew/3.10.rst
  Lib/base64.py
  Lib/test/test_base64.py
  Misc/NEWS.d/next/Library/2020-05-27-00-09-52.bpo-16995.4niOT7.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#21806 bpo-40548: Fix "Check for source changes (pull_request)" GH Action job
  .github/workflows/build.yml
Labels: CLA signed, awaiting merge, skip news

#21813 [3.8] bpo-40548: Fix "Check for source changes (pull_request)" GH Action job (GH-21806)
  .github/workflows/build.yml
Labels: CLA signed, awaiting merge, skip news

#21814 [3.9] bpo-40548: Fix "Check for source changes (pull_request)" GH Action job (GH-21806)
  .github/workflows/build.yml
Labels: CLA signed, awaiting merge, skip news

#21815 Replace import_fresh_module.
  Modules/_decimal/tests/bench.py
  Modules/_decimal/tests/deccheck.py
  Modules/_decimal/tests/formathelper.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#21817 MSVC: The ARM command line should not define MASM
  PCbuild/_decimal.vcxproj
Labels: CLA signed, awaiting core review, skip issue, skip news

#21811 bpo-40275: Fix failed test cases by using test helpers
  Lib/test/test__osx_support.py
  Lib/test/test_importlib/extension/test_case_sensitivity.py
  Lib/test/test_importlib/source/test_case_sensitivity.py
  Lib/test/test_selectors.py
Labels: CLA signed, awaiting review, skip news, type-tests

#21378 bpo-1635741: port multiprocessing to multiphase init
  Misc/NEWS.d/next/Core and Builtins/2020-07-07-16-10-52.bpo-1635741.zU-H_n.rst
  Modules/_multiprocessing/multiprocessing.c
Labels: CLA signed, awaiting merge

#21822 bpo-41521: Replace whitelist/blacklist with allowlist/denylist
  Doc/library/http.cookiejar.rst
  Doc/library/urllib.parse.rst
  Lib/codecs.py
  Lib/ipaddress.py
  Lib/test/test___all__.py
  Lib/test/test_httplib.py
  Lib/test/test_httpservers.py
  Lib/test/test_nntplib.py
  Lib/test/test_tools/test_sundry.py
  Lib/test/test_traceback.py
  Objects/typeobject.c
  Tools/clinic/clinic.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#21823 bpo-41521: Replace whitelist/blacklist with allowlist/denylist
  Lib/test/test_codecs.py
  Lib/test/test_typing.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#21773 bpo-41504: Add links to asttokens, leoAst, LibCST and parso
  Doc/library/ast.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21829 [3.8] bpo-41504: Add links to asttokens, leoAst, LibCST and parso to ast docs (GH-21773)
  Doc/library/ast.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#21827 [3.9] bpo-38912: regrtest logs unraisable exception into sys.__stderr__ (GH-21718)
  Lib/test/libregrtest/utils.py
  Lib/test/test_regrtest.py
Labels: CLA signed, awaiting core review, skip news

#21374 bpo-41191: Add PEP 573 additions to What's New
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news, type-documentation

#21733 bpo-41475: Fix note in "What's new in 3.7"
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21831 [3.9] bpo-41191: Add PEP 573 additions to What's New (GH-21374)
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#21832 [3.9] bpo-41475: Fix note in "What's new in 3.7" (GH-21733)
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#21834 Call randseed() before other imports in deccheck.py.
  Modules/_decimal/tests/deccheck.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#21830 [3.9] bpo-41504: Add links to asttokens, leoAst, LibCST and parso to ast docs (GH-21773)
  Doc/library/ast.rst
Labels: CLA signed, skip issue, skip news

#21820 Fix documentation typo
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#21825 bpo-41521, typing: Rename _PROTO_WHITELIST to _PROTO_ALLOWLIST
  Lib/typing.py
Labels: CLA signed, awaiting core review, skip news

#21835 [3.7] bpo-41475: Fix note in "What's new in 3.7" (GH-21733)
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#21833 [3.8] bpo-41475: Fix note in "What's new in 3.7" (GH-21733)
  Doc/whatsnew/3.7.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#21788 [3.7] bpo-41455: Provide a link to how the third generation is collected in the GC docs (GH-21703)
  Doc/library/gc.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#21838 bpo-41520: codeop no longer ignores SyntaxWarning
  Lib/codeop.py
  Lib/test/test_codeop.py
  Misc/NEWS.d/next/Library/2020-08-12-13-25-16.bpo-41520.BEUWa4.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21841 [3.8] bpo-41520: codeop no longer ignores SyntaxWarning (GH-21838)
  Lib/codeop.py
  Lib/test/test_codeop.py
  Misc/NEWS.d/next/Library/2020-08-12-13-25-16.bpo-41520.BEUWa4.rst
Labels: CLA signed, awaiting merge

#21840 [3.9] bpo-41520: codeop no longer ignores SyntaxWarning (GH-21838)
  Lib/codeop.py
  Lib/test/test_codeop.py
  Misc/NEWS.d/next/Library/2020-08-12-13-25-16.bpo-41520.BEUWa4.rst
Labels: CLA signed, awaiting merge

#21842 Catch all skip_handler cases.
  Modules/_decimal/tests/deccheck.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#21843 [3.9] bpo-40979: refactored typing.rst; (mostly) same content, new sub-sections and ordering (GH-21574)
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2020-07-21-15-23-30.bpo-40979.pLA8rO.rst
Labels: :robot: automerge, CLA signed, awaiting core review, type-documentation

#21844 bpo-40204: Allow pre-Sphinx 3 syntax in the doc
  Doc/conf.py
  Misc/NEWS.d/next/Documentation/2020-08-12-18-35-40.bpo-40204.C8A_pe.rst
Labels: CLA signed, awaiting merge

#21605 bpo-1635741: Clean sysdict and builtins of interpreter
  Python/pystate.c
Labels: awaiting merge, skip news

#21850 bpo-41531: Fix compilation of dict literals with more than 0xFFFF elements
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-12-19-32-15.bpo-41531.WgPzjT.rst
  Python/compile.c
Labels: CLA signed, needs backport to 3.9

#21371 bpo-1635741: port winapi to multi-stage init
  Misc/NEWS.d/next/Core and Builtins/2020-07-06-20-43-19.bpo-1635741.LYhsni.rst
  Modules/_winapi.c
Labels: CLA signed, awaiting core review

#21858 bpo-40204: Fix Sphinx sytanx in howto/instrumentation.rst
  Doc/howto/instrumentation.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#21857 bpo-40204: Fix duplicates in the documentation
  Doc/c-api/buffer.rst
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting core review, skip news

#21848 bpo-41520: Fix second codeop regression
  Lib/codeop.py
  Lib/test/test_codeop.py
  Misc/NEWS.d/next/Library/2020-08-12-13-25-16.bpo-41520.BEUWa4.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-bugfix

#21826 bpo-41521: Replace denylist with blocklist is http.cookiejar doc
  Doc/library/http.cookiejar.rst
  Lib/test/test___all__.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#21860 [3.9] bpo-41520: Fix second codeop regression (GH-21848)
  Lib/codeop.py
  Lib/test/test_codeop.py
  Misc/NEWS.d/next/Library/2020-08-12-13-25-16.bpo-41520.BEUWa4.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, type-bugfix

#21862 [3.8] [3.9] bpo-41520: Fix second codeop regression (GH-21848)
  Lib/codeop.py
  Lib/test/test_codeop.py
  Misc/NEWS.d/next/Library/2020-08-12-13-25-16.bpo-41520.BEUWa4.rst
Labels: CLA signed, awaiting merge, type-bugfix

#21859 bpo-40204: Add :noindex: in the documentation
  Doc/library/aifc.rst
  Doc/library/configparser.rst
  Doc/library/difflib.rst
  Doc/library/enum.rst
  Doc/library/socket.rst
  Doc/library/tarfile.rst
  Doc/library/token.rst
  Doc/library/turtle.rst
  Doc/library/urllib.request.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#21261 bpo-41066: Update the comparison section for os vs pathlib
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#21863 [3.9] bpo-41066: Update the comparison section for os vs pathlib (GH-21261)
  Doc/library/pathlib.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#21864 [3.8] bpo-41066: Update the comparison section for os vs pathlib (GH-21261)
  Doc/library/pathlib.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#21846 bpo-40204, doc: Fix syntax of C variables
  Doc/c-api/arg.rst
  Doc/c-api/buffer.rst
  Doc/c-api/call.rst
  Doc/c-api/capsule.rst
  Doc/c-api/dict.rst
  Doc/c-api/exceptions.rst
  Doc/c-api/file.rst
  Doc/c-api/init.rst
  Doc/c-api/intro.rst
  Doc/c-api/marshal.rst
  Doc/c-api/memory.rst
  Doc/c-api/module.rst
  Doc/c-api/object.rst
  Doc/c-api/structures.rst
  Doc/c-api/tuple.rst
  Doc/c-api/typeobj.rst
  Doc/c-api/unicode.rst
  Doc/c-api/veryhigh.rst
  Doc/whatsnew/3.3.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#21851 Fixed comment about pathlib.link_to: it was added in 3.8, not changed.
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#21866 [3.8] Fixed comment about pathlib.link_to: it was added in 3.8, not changed. (GH-21851)
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#21867 [3.9] Fixed comment about pathlib.link_to: it was added in 3.8, not changed. (GH-21851)
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21871 bpo-41526: Fixed layout of final page of the installer
  Misc/NEWS.d/next/Windows/2020-08-13-22-40-58.bpo-41526.-i2bwb.rst
  Tools/msi/bundle/Default.thm
  Tools/msi/bundle/Default.wxl
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.9

#21872 [3.9] bpo-41526: Fixed layout of final page of the installer (GH-21871)
  Misc/NEWS.d/next/Windows/2020-08-13-22-40-58.bpo-41526.-i2bwb.rst
  Tools/msi/bundle/Default.thm
  Tools/msi/bundle/Default.wxl
Labels: CLA signed, awaiting merge

#21701 bpo-41410: Fix outdated info in mkstemp docs
  Doc/library/tempfile.rst
  Lib/tempfile.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, skip news

#21874 [3.8] bpo-41410: Fix outdated info in mkstemp docs (GH-21701)
  Doc/library/tempfile.rst
  Lib/tempfile.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#21873 [3.9] bpo-41410: Fix outdated info in mkstemp docs (GH-21701)
  Doc/library/tempfile.rst
  Lib/tempfile.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#20965 bpo-41025: Fix subclassing for zoneinfo.ZoneInfo
  Lib/test/test_zoneinfo/test_zoneinfo.py
  Misc/NEWS.d/next/Library/2020-06-18-10-34-59.bpo-41025.elf_nz.rst
  Modules/_zoneinfo.c
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.9

#21878 [3.7] bpo-33786: Fix asynchronous generators to handle GeneratorExit in athrow() (GH-7467)
  Lib/contextlib.py
  Lib/test/test_asyncgen.py
  Lib/test/test_contextlib_async.py
  Misc/NEWS.d/next/Core and Builtins/2018-06-06-23-24-40.bpo-33786.lBvT8z.rst
  Objects/genobject.c
Labels: CLA signed, awaiting merge

#21876 [3.9] bpo-41025: Fix subclassing for zoneinfo.ZoneInfo (GH-20965)
  Lib/test/test_zoneinfo/test_zoneinfo.py
  Misc/NEWS.d/next/Library/2020-06-18-10-34-59.bpo-41025.elf_nz.rst
  Modules/_zoneinfo.c
Labels: awaiting merge

#21879 Fix typo in typing doc
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#21884 [3.8] Fix typo in typing doc (GH-21879)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21883 [3.9] Fix typo in typing doc (GH-21879)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21887 bpo-40878: xlc cannot handle C99 extern inline
  Modules/_decimal/libmpdec/mpdecimal.c
Labels: CLA signed, awaiting core review, skip news

#18772 bpo-31122: ssl.wrap_socket() now raises ssl.SSLEOFError rather than OSError when peer closes connection during TLS negotiation
  Misc/NEWS.d/next/Library/2020-03-11-07-44-06.bpo-31122.zIQ80l.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#21889 [3.8] bpo-31122: ssl.wrap_socket() now raises ssl.SSLEOFError rather than OSError when peer closes connection during TLS negotiation (GH-18772)
  Misc/NEWS.d/next/Library/2020-03-11-07-44-06.bpo-31122.zIQ80l.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#21888 [3.9] bpo-31122: ssl.wrap_socket() now raises ssl.SSLEOFError rather than OSError when peer closes connection during TLS negotiation (GH-18772)
  Misc/NEWS.d/next/Library/2020-03-11-07-44-06.bpo-31122.zIQ80l.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#21890 bpo-41540: AIX: skip test that is flaky with a default ulimit
  Lib/test/test_decimal.py
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news, type-tests

#21891 [3.9] bpo-40878: xlc cannot handle C99 extern inline. (GH-21887)
  Modules/_decimal/libmpdec/mpdecimal.c
Labels: CLA signed, awaiting review, skip news

#21893 [3.9] bpo-41540: AIX: skip test that is flaky with a default ulimit. (GH-21890)
  Lib/test/test_decimal.py
Labels: CLA signed, awaiting review, skip news, type-tests
