Repository python/cpython, pull requests merged in 2020-03, with the labels that each got.

#18718 [3.8] bpo-39769: Fix compileall ddir for subpkgs. (GH-18676)
  Lib/compileall.py
  Lib/test/test_compileall.py
  Lib/test/test_importlib/util.py
  Misc/NEWS.d/next/Library/2020-02-29-13-20-33.bpo-39769.hJmxu4.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, type-bugfix

#18725 [3.7] bpo-39769: Fix compileall ddir for subpkgs. (GH-18676) (GH-18718)
  Lib/compileall.py
  Lib/test/test_compileall.py
  Lib/test/test_importlib/util.py
  Misc/NEWS.d/next/Library/2020-02-29-13-20-33.bpo-39769.hJmxu4.rst
Labels: :robot: automerge, CLA signed, awaiting core review, type-bugfix

#16994 bpo-38641: Add support of starred expressions in return/yield to lib2to3
  Lib/lib2to3/Grammar.txt
  Lib/lib2to3/tests/data/py3_test_grammar.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-10-30-15-31-09.bpo-38641.HrTL9k.rst
Labels: CLA signed, awaiting merge

#18304 bpo-39520: Fix unparsing of ext slices with no dimentions
  Lib/test/test_future.py
  Misc/NEWS.d/next/Core and Builtins/2020-02-02-00-12-07.bpo-39520.uicBq6.rst
  Python/ast_unparse.c
Labels: CLA signed, awaiting merge, type-bugfix

#17377 bpo-38870: Implement Simple Preceding to AST Unparser
  Lib/ast.py
  Lib/test/test_ast.py
  Lib/test/test_unparse.py
Labels: CLA signed, awaiting merge, skip news

#18551 bpo-39678 RFC refactor queue manager thread
  Lib/concurrent/futures/process.py
  Lib/test/test_concurrent_futures.py
  Misc/NEWS.d/next/Library/2020-02-28-12-59-30.bpo-39678.3idfxM.rst
Labels: CLA signed, awaiting merge, type-enhancement

#18726 bpo-39815: add cached_property to all
  Lib/functools.py
  Misc/ACKS
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, skip news

#18709 bpo-39803: Remove unused str from _PyLong_FormatAdvancedWriter
  Python/formatter_unicode.c
Labels: CLA signed, awaiting review, needs backport to 3.8, skip news

#18728 [3.8] bpo-39815: add cached_property to all (GH-18726)
  Lib/functools.py
  Misc/ACKS
Labels: CLA signed, awaiting core review, skip news

#17812 bpo-39199: Add descriptions of non-deprecated AST nodes to the AST module documentation
  Doc/library/ast.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#18046 bpo-39378: partial of PickleState struct should be traversed.
  Modules/_pickle.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news

#18275 bpo-39495: Remove default value from C impl of TreeBuilder.start
  Lib/test/test_xml_etree.py
  Misc/NEWS.d/next/Library/2020-01-30-07-02-02.bpo-39495.8LsIRN.rst
  Modules/_elementtree.c
  Modules/clinic/_elementtree.c.h
Labels: CLA signed, awaiting merge

#17666 bpo-38971: open file in codecs.open() closes if exception raised
  Lib/codecs.py
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Library/2019-12-20-16-06-28.bpo-38971.fKRYlF.rst
Labels: CLA signed, awaiting merge

#18656 bpo-38913: Fix segfault in Py_BuildValue("(s#O)", ...) if entered with exception raised.
  Misc/NEWS.d/next/C API/2020-02-25-20-10-34.bpo-38913.siF1lS.rst
  Modules/_testcapimodule.c
  Python/modsupport.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, type-bugfix

#18731 [3.7] bpo-39378: partial of PickleState struct should be traversed. (GH-18046)
  Modules/_pickle.c
Labels: CLA signed, awaiting merge, skip news

#18730 [3.8] bpo-39378: partial of PickleState struct should be traversed. (GH-18046)
  Modules/_pickle.c
Labels: CLA signed, awaiting merge, skip news

#18732 [3.8] bpo-38913: Fix segfault in Py_BuildValue("(sGH-O)", ...) if entered with exception raised. (GH-18656).
  Misc/NEWS.d/next/C API/2020-02-25-20-10-34.bpo-38913.siF1lS.rst
  Modules/_testcapimodule.c
  Python/modsupport.c
Labels: CLA signed, awaiting core review, type-bugfix

#18658 [3.8] bpo-38410: Properly handle PySys_Audit() failures
  Misc/NEWS.d/next/Library/2019-10-09-08-14-25.bpo-38410._YyoMV.rst
  Python/ceval.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge

#18733 [3.7] bpo-38971: Open file in codecs.open() closes if exception raised. (GH-17666)
  Lib/codecs.py
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Library/2019-12-20-16-06-28.bpo-38971.fKRYlF.rst
Labels: CLA signed, awaiting merge, type-bugfix

#18734 [3.8] bpo-38971: Open file in codecs.open() closes if exception raised. (GH-17666)
  Lib/codecs.py
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Library/2019-12-20-16-06-28.bpo-38971.fKRYlF.rst
Labels: CLA signed, awaiting merge, type-bugfix

#18615 bpo-39530: Fix misleading statement about mixed-type numeric comparisons
  Doc/library/stdtypes.rst
  Misc/NEWS.d/next/Documentation/2020-02-23-13-26-40.bpo-39530._bCvzQ.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-documentation

#18684 bpo-39775: inspect: Change Signature.parameters back to OrderedDict.
  Doc/library/inspect.rst
  Doc/whatsnew/3.9.rst
  Lib/inspect.py
  Misc/NEWS.d/next/Library/2020-02-28-16-42-16.bpo-39775.IuSvVb.rst
Labels: CLA signed, awaiting core review

#18678 bpo-38380: Update macOS & Windows builds to SQLite v3.31.1
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/Windows/2020-02-28-23-51-27.bpo-38380.TpOBCj.rst
  Misc/NEWS.d/next/macOS/2020-02-28-23-51-47.bpo-38380.u-ySyA.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#18669 bpo-39764: Make Task.get_stack accept ag_frame
  Lib/asyncio/base_tasks.py
  Lib/test/test_asyncgen.py
  Misc/NEWS.d/next/Library/2020-02-27-18-21-07.bpo-39764.wqPk68.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8

#18742 [3.8] bpo-39764: Make Task.get_stack accept ag_frame (GH-18669)
  Lib/asyncio/base_tasks.py
  Lib/test/test_asyncgen.py
  Misc/NEWS.d/next/Library/2020-02-27-18-21-07.bpo-39764.wqPk68.rst
Labels: CLA signed, awaiting merge

#18739 bpo-39796: Fix _warnings module initialization
  Include/internal/pycore_warnings.h
  Python/_warnings.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#18740 [3.8] bpo-38380: Update macOS & Windows builds to SQLite v3.31.1 (GH-18678)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/Windows/2020-02-28-23-51-27.bpo-38380.TpOBCj.rst
  Misc/NEWS.d/next/macOS/2020-02-28-23-51-47.bpo-38380.u-ySyA.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting merge

#18741 [3.7] bpo-38380: Update macOS & Windows builds to SQLite v3.31.1 (GH-18678)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/Windows/2020-02-28-23-51-27.bpo-38380.TpOBCj.rst
  Misc/NEWS.d/next/macOS/2020-02-28-23-51-47.bpo-38380.u-ySyA.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting merge

#17760 bpo-38870: Docstring support for function/class/module nodes
  Lib/ast.py
  Lib/test/test_unparse.py
Labels: CLA signed, awaiting merge, skip news

#18750 bpo-39831: Fix a reference leak in PyErr_WarnEx().
  Python/_warnings.c
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip news, type-bugfix

#18746 bpo-39776: Lock ++interp->tstate_next_unique_id. (GH-18746)
  Misc/NEWS.d/next/Core and Builtins/2020-03-02-20-12-33.bpo-39776.fNaxi_.rst
  Python/pystate.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#18749 bpo-39778: Don't traverse weak-reference lists OrderedDict's tp_traverse and tp_clear
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Core and Builtins/2020-03-02-19-21-21.bpo-39778._YGLEc.rst
  Objects/odictobject.c
Labels: CLA signed, awaiting merge

#18755 [3.7] bpo-39778: Don't traverse weak-reference lists OrderedDict's tp_traverse and tp_clear (GH-18749)
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Core and Builtins/2020-03-02-19-21-21.bpo-39778._YGLEc.rst
  Objects/odictobject.c
Labels: CLA signed, awaiting merge

#18756 [3.8] bpo-39778: Don't traverse weak-reference lists OrderedDict's tp_traverse and tp_clear (GH-18749)
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Core and Builtins/2020-03-02-19-21-21.bpo-39778._YGLEc.rst
  Objects/odictobject.c
Labels: CLA signed, awaiting core review

#18724 bpo-38597: Never statically link extension initialization code on Windows
  Lib/distutils/_msvccompiler.py
  Lib/distutils/tests/test_msvccompiler.py
  Misc/NEWS.d/next/Windows/2020-03-01-15-04-54.bpo-38597.MnHdYl.rst
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-bugfix

#18759 [3.7] bpo-38597: Never statically link extension initialization code on Windows (GH-18724)
  Lib/distutils/_msvccompiler.py
  Lib/distutils/tests/test_msvccompiler.py
  Misc/NEWS.d/next/Windows/2020-03-01-15-04-54.bpo-38597.MnHdYl.rst
  PCbuild/pythoncore.vcxproj
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#18758 [3.8] bpo-38597: Never statically link extension initialization code on Windows (GH-18724)
  Lib/distutils/_msvccompiler.py
  Lib/distutils/tests/test_msvccompiler.py
  Misc/NEWS.d/next/Windows/2020-03-01-15-04-54.bpo-38597.MnHdYl.rst
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, awaiting merge, type-bugfix

#18761 [3.8] bpo-39831: Fix a reference leak in PyErr_WarnEx(). (GH-18750)
  Python/_warnings.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#18760 [3.7] bpo-39831: Fix a reference leak in PyErr_WarnEx(). (GH-18750).
  Python/_warnings.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#17518 bpo-38091: Import deadlock detection causes deadlock
  Lib/importlib/_bootstrap.py
  Lib/test/test_import/__init__.py
  Misc/NEWS.d/next/Core and Builtins/2020-02-14-23-10-07.bpo-38091.pwR0K7.rst
  Python/importlib.h
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#18705 bpo-39802: Only implement set_escdelay and set_tabsize when curses extensions are activated
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news

#18754 bpo-39778: Add clarification about tp_traverse and ownership
  Doc/c-api/typeobj.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news

#18763 [3.7] bpo-39778: Add clarification about tp_traverse and ownership (GH-18754)
  Doc/c-api/typeobj.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#18762 [3.8] bpo-39778: Add clarification about tp_traverse and ownership (GH-18754)
  Doc/c-api/typeobj.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#18752 [3.8] bpo-39776: Lock ++interp->tstate_next_unique_id. (GH-18746)
  Misc/NEWS.d/next/Core and Builtins/2020-03-02-20-12-33.bpo-39776.fNaxi_.rst
  Python/pystate.c
Labels: CLA signed, awaiting core review

#18753 [3.7] bpo-39776: Lock ++interp->tstate_next_unique_id (GH-18746)
  Misc/NEWS.d/next/Core and Builtins/2020-03-02-20-12-33.bpo-39776.fNaxi_.rst
  Python/pystate.c
Labels: CLA signed, awaiting core review

#18720 bpo-12915: Fix test to recognize when filesystem encoding cannot encode Unicode string
  Lib/test/test_pkgutil.py
Labels: CLA signed, awaiting review, skip news, type-tests

#18737 [3.7] bpo-39530 Fix misleading statement about mixed-type numeric comparisons (GH-18615)
  Doc/library/stdtypes.rst
  Misc/NEWS.d/next/Documentation/2020-02-23-13-26-40.bpo-39530._bCvzQ.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#18747 bpo-39674: Update collections ABC doc
  Doc/library/collections.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#18748 [3.8] bpo-39674: Update collections ABC deprecation doc
  Doc/library/collections.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#18764 bpo-39831: Remove outdated comment.
  Python/_warnings.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip news

#18770 [3.8] bpo-39831: Remove outdated comment. (GH-18764)
  Python/_warnings.c
Labels: CLA signed, awaiting merge, skip news

#13195 bpo-35712: Make using NotImplemented in a boolean context issue a dep…
  Doc/library/constants.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.9.rst
  Lib/functools.py
  Lib/ipaddress.py
  Lib/test/test_buffer.py
  Lib/test/test_builtin.py
  Lib/test/test_descr.py
  Misc/NEWS.d/next/Core and Builtins/2019-05-08-11-11-45.bpo-35712.KJthus.rst
  Objects/object.c
Labels: CLA signed, awaiting merge

#18552 bpo-39674: Suggest to test with DeprecationWarning
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#18570 bpo-39702: Relax grammar restrictions on decorators (PEP 614).
  Grammar/Grammar
  Include/node.h
  Lib/test/test_decorators.py
  Lib/test/test_grammar.py
  Lib/test/test_parser.py
  Misc/NEWS.d/next/Core and Builtins/2020-02-20-08-12-52.bpo-39702.4_AmyF.rst
  Python/ast.c
  Python/graminit.c
Labels: CLA signed, awaiting merge, type-enhancement

#18751 [3.7] bpo-37953: Fix ForwardRef hash and equality checks (GH-15400)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2019-09-06-17-40-34.bpo-37953.db5FQq.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-enhancement

#18101 [3.7] bpo-39389: gzip: fix compression level metadata (GH-18077)
  Lib/gzip.py
  Lib/test/test_gzip.py
  Misc/NEWS.d/next/Library/2020-01-20-00-56-01.bpo-39389.fEirIS.rst
Labels: CLA signed, awaiting merge

#18745 bpo-39826: add getConnection() hook to logging HTTPHandler
  Lib/logging/handlers.py
  Misc/NEWS.d/next/Library/2020-03-02-15-15-01.bpo-39826.DglHk7.rst
Labels: CLA signed, awaiting merge

#18773 [3.8] (bpo-39530) Fix misleading statement about mixed-type numeric comparisons (GH-18615)
  Doc/library/stdtypes.rst
  Misc/NEWS.d/next/Documentation/2020-02-23-13-26-40.bpo-39530._bCvzQ.rst
Labels: CLA signed, awaiting review, type-documentation

#18601 bpo-39573: Finish converting to new Py_IS_TYPE macro.
  Include/py_curses.h
  Modules/_asynciomodule.c
  Modules/_collectionsmodule.c
  Modules/_elementtree.c
  Modules/_io/bufferedio.c
  Modules/_io/stringio.c
  Modules/_io/textio.c
  Modules/_pickle.c
  Modules/_threadmodule.c
  Modules/cjkcodecs/multibytecodec.h
  Modules/itertoolsmodule.c
  Objects/abstract.c
  Objects/descrobject.c
  Objects/exceptions.c
  Objects/genobject.c
  Objects/listobject.c
  Objects/namespaceobject.c
  Objects/tupleobject.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Python/ceval.c
  Python/errors.c
  Python/importdl.c
Labels: CLA signed, awaiting review, skip news

#18743 bpo-39763: distutils.spawn now uses subprocess
  Lib/distutils/spawn.py
  Lib/distutils/tests/test_spawn.py
  Misc/NEWS.d/next/Build/2020-03-02-14-44-09.bpo-39763.GGEwhH.rst
  Misc/NEWS.d/next/Library/2020-03-02-14-43-19.bpo-39763.5a822c.rst
  setup.py
Labels: CLA signed, awaiting merge

#18776 bpo-39674: Fix typo in What's New In Python 3.9
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#18675 bpo-39770: Remove unnecessary descriptor counting
  Modules/arraymodule.c
Labels: CLA signed, awaiting core review, skip news

#18513 bpo-39639: remove suite node
  Doc/whatsnew/3.9.rst
  Include/Python-ast.h
  Lib/test/test_asdl_parser.py
  Misc/NEWS.d/next/Core and Builtins/2020-02-15-15-29-34.bpo-39639.3mqJjm.rst
  Parser/Python.asdl
  Python/Python-ast.c
  Python/ast.c
  Python/ast_opt.c
  Python/compile.c
  Python/symtable.c
Labels: CLA signed, awaiting merge

#18775 [3.7] Update macOS installer ReadMe for 3.7.7.
  Mac/BuildScript/resources/ReadMe.rtf
Labels: CLA signed, awaiting core review, skip issue, skip news

#18778 bpo-39763: Refactor setup.py
  setup.py
Labels: CLA signed, skip news

#18767 bpo-39674: Revert "bpo-37330: open() no longer accept 'U' in file mode (GH-16959)"
  Doc/library/codecs.rst
  Doc/library/fileinput.rst
  Doc/library/functions.rst
  Doc/whatsnew/3.9.rst
  Lib/_pyio.py
  Lib/fileinput.py
  Lib/imp.py
  Lib/test/test_codecs.py
  Lib/test/test_fileinput.py
  Lib/test/test_io.py
  Misc/NEWS.d/next/Library/2020-03-03-16-21-41.bpo-39674.HJVkD5.rst
  Modules/_io/_iomodule.c
  Modules/_io/clinic/_iomodule.c.h
Labels: CLA signed, awaiting merge

#18777 [3.7] Allow python_uwp.vcxproj to build with toolset v142 if present
  PCbuild/python_uwp.vcxproj
  PCbuild/pythonw_uwp.vcxproj
Labels: CLA signed, OS-windows, awaiting core review, skip issue, skip news, type-bugfix

#18719 bpo-39808: Improve docs for pathlib.Path.stat()
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#18782 [3.7] bpo-39808: Improve docs for pathlib.Path.stat() (GH-18719)
  Doc/library/pathlib.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#18784 Add a missing space after a period in 'typing.TypedDict' documentation
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, skip issue, skip news, type-documentation

#18785 [3.8] Add a missing space after a period in 'typing.TypedDict' documentation (GH-18784)
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#18786 bpo-13487: Use sys.modules.copy() in inspect for thread safety
  Lib/inspect.py
  Misc/NEWS.d/next/Library/2020-03-04-16-10-59.bpo-13487.gqe4Fb.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-bugfix

#18788 [3.7] bpo-13487: Use sys.modules.copy() in inspect.getmodule() for thread safety. (GH-18786)
  Lib/inspect.py
  Misc/NEWS.d/next/Library/2020-03-04-16-10-59.bpo-13487.gqe4Fb.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#18787 [3.8] bpo-13487: Use sys.modules.copy() in inspect.getmodule() for thread safety. (GH-18786)
  Lib/inspect.py
  Misc/NEWS.d/next/Library/2020-03-04-16-10-59.bpo-13487.gqe4Fb.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#18781 bpo-39855: Fix test_subprocess if nobody user doesn't exist
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Tests/2020-03-04-23-03-01.bpo-39855.Ql5xv8.rst
Labels: CLA signed, awaiting core review, type-tests

#18792 bpo-35537: Add a comment to _Py_RestoreSignals()
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#18783 [3.8] bpo-39808: Improve docs for pathlib.Path.stat() (GH-18719)
  Doc/library/pathlib.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#18771 IDLE doc: improve Startup failure subsection.
  Doc/library/idle.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#18795 [3.7] IDLE doc: improve Startup failure subsection. (GH-18771)
  Doc/library/idle.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#18794 [3.8] IDLE doc: improve Startup failure subsection. (GH-18771)
  Doc/library/idle.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#18796 bpo-39870: Remove unused arg from sys_displayhook_unencodable.
  Python/sysmodule.c
Labels: CLA signed, awaiting review, skip news

#18790 closes bpo-39859: Do not downcast result of hstrerror
  Modules/socketmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#18793 bpo-39868: Update Language Reference for PEP 572.
  Doc/reference/compound_stmts.rst
  Doc/reference/expressions.rst
  Misc/NEWS.d/next/Documentation/2020-03-05-16-29-03.bpo-39868.JQoHhO.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, type-documentation

#18797 [3.8] bpo-39868: Update Language Reference for PEP 572. (GH-18793)
  Doc/reference/compound_stmts.rst
  Doc/reference/expressions.rst
  Misc/NEWS.d/next/Documentation/2020-03-05-16-29-03.bpo-39868.JQoHhO.rst
Labels: CLA signed, awaiting merge, type-documentation

#18799 bpo-39573: Make Py_IS_TYPE take const args. Add _PyObject_CAST_CONST.
  Include/object.h
Labels: CLA signed, awaiting merge, skip news

#18774 Removes notion on PyPy supporting py3
  Doc/howto/logging.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#18804 bpo-39873: PyObject_Init() uses PyObject_INIT()
  Objects/object.c
Labels: CLA signed, awaiting core review, skip news

#18800 bpo-39872: Remove unused args from symtable_exit_block and symtable_visit_annota…
  Python/symtable.c
Labels: CLA signed, awaiting review, skip news

#18729 bpo-36144: Implement defaultdict union.
  Doc/library/collections.rst
  Lib/test/test_defaultdict.py
  Misc/NEWS.d/next/Library/2020-02-29-15-54-08.bpo-36144.4GgTZs.rst
  Modules/_collectionsmodule.c
Labels: CLA signed, awaiting merge, type-enhancement

#18807 bpo-39873: Cleanup _PyObject_CheckConsistency()
  Objects/object.c
Labels: CLA signed, awaiting core review, skip news

#18682 bpo-17422: slightly more precise language
  Doc/reference/datamodel.rst
  Misc/NEWS.d/next/Documentation/2020-02-27-17-35-27.bpo-17422.eS1hVh.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-documentation

#18813 [3.7] bpo-17422: slightly more precise language (GH-18682)
  Doc/reference/datamodel.rst
  Misc/NEWS.d/next/Documentation/2020-02-27-17-35-27.bpo-17422.eS1hVh.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#18812 [3.8] bpo-17422: slightly more precise language (GH-18682)
  Doc/reference/datamodel.rst
  Misc/NEWS.d/next/Documentation/2020-02-27-17-35-27.bpo-17422.eS1hVh.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#18809 bpo-39573: Use Py_IS_TYPE to check for types
  Modules/_functoolsmodule.c
  Modules/_threadmodule.c
  Modules/itertoolsmodule.c
  Modules/posixmodule.c
  Objects/abstract.c
  Objects/object.c
  Objects/setobject.c
  Objects/tupleobject.c
  Objects/typeobject.c
  Python/errors.c
Labels: CLA signed, awaiting merge, skip news

#18816 bpo-39877: _PyRuntimeState.finalizing becomes atomic
  Include/internal/pycore_pystate.h
  Python/ceval.c
  Python/pylifecycle.c
  Python/pystate.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, skip news

#18819 bpo-39882: Py_FatalError() logs the function name
  Doc/c-api/sys.rst
  Include/cpython/pyerrors.h
  Include/pyerrors.h
  Lib/test/test_capi.py
  Lib/test/test_exceptions.py
  Lib/test/test_faulthandler.py
  Lib/test/test_io.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/C API/2020-03-06-23-56-04.bpo-39882.Iqhcqm.rst
  Objects/obmalloc.c
  Parser/parser.c
  Parser/tokenizer.c
  Python/ceval.c
  Python/import.c
  Python/pathconfig.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting core review

#18818 bpo-39837: Disable macOS tests on Azure Pipelines
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip news

#18821 [3.7] bpo-39837: Disable macOS tests on Azure Pipelines (GH-18818)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, awaiting merge, skip news

#18820 [3.8] bpo-39837: Disable macOS tests on Azure Pipelines (GH-18818)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
Labels: CLA signed, awaiting merge, skip news

#18824 bpo-39889: Fix ast.unparse() for subscript.
  Lib/ast.py
  Lib/test/test_unparse.py
  Misc/NEWS.d/next/Library/2020-03-07-16-44-51.bpo-39889.3RYqeX.rst
Labels: CLA signed, awaiting core review, type-bugfix

#18826 [3.8] bpo-39889: Fix unparse.py for subscript. (GH-18824).
  Lib/test/test_tools/test_unparse.py
  Misc/NEWS.d/next/Tools-Demos/2020-03-07-18-01-30.bpo-39889.l1czT6.rst
  Tools/parser/unparse.py
Labels: CLA signed, awaiting core review, needs backport to 3.7, type-bugfix

#18827 [3.7] [3.8] bpo-39889: Fix unparse.py for subscript. (GH-18824). (GH-18826)
  Lib/test/test_tools/test_unparse.py
  Misc/NEWS.d/next/Tools-Demos/2020-03-07-18-01-30.bpo-39889.l1czT6.rst
  Tools/parser/unparse.py
Labels: CLA signed, awaiting merge, type-bugfix

#18822 bpo-39878: Remove unused arguments from static functions
  Python/formatter_unicode.c
Labels: CLA signed, awaiting review, skip news

#18823 bpo-39886: Remove unused arg from config_get_stdio_errors
  Python/initconfig.c
Labels: CLA signed, awaiting review, skip news

#18815 bpo-38894: Fix pathlib.Path.glob in the presence of symlinks and insufficient permissions
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Core and Builtins/2020-03-06-21-04-39.bpo-38894.nfcGKv.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8

#18831 [3.7] bpo-38894: Fix pathlib.Path.glob in the presence of symlinks and insufficient permissions (GH-18815)
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Core and Builtins/2020-03-06-21-04-39.bpo-38894.nfcGKv.rst
Labels: CLA signed, awaiting merge

#18830 [3.8] bpo-38894: Fix pathlib.Path.glob in the presence of symlinks and insufficient permissions (GH-18815)
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Core and Builtins/2020-03-06-21-04-39.bpo-38894.nfcGKv.rst
Labels: CLA signed, awaiting merge

#18828 bpo-39199: Use 'eval' mode for the examples with expression nodes
  Doc/library/ast.rst
Labels: CLA signed, awaiting merge, skip news

#18802 bpo-39702: Update the Language Reference (PEP 614).
  Doc/reference/compound_stmts.rst
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#18814 bpo-36144: Update MappingProxyType with PEP 584's operators
  Doc/library/types.rst
  Lib/test/test_types.py
  Misc/NEWS.d/next/Library/2020-02-25-09-28-06.bpo-36144.Rbvvi7.rst
  Objects/descrobject.c
Labels: CLA signed, awaiting merge, type-enhancement

#18833 bpo-39890: Don't mangle the AST when compiling starred assignments
  Python/compile.c
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#18811 bpo-39877: Fix PyEval_RestoreThread() for daemon threads
  Misc/NEWS.d/next/Core and Builtins/2020-03-06-18-30-00.bpo-39877.bzd1y0.rst
  Python/ceval.c
  Python/ceval_gil.h
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge

#18499 bpo-39567: Document audit for os.walk, os.fwalk, Path.glob and Path.rglob.
  Doc/library/os.rst
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#18765 [3.7] bpo-39831: Fix a reference leak in PyErr_WarnEx(). (GH-18750).
  Python/_warnings.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#18840 bpo-39898: Remove unused arg from append_formattedvalue
  Python/ast_unparse.c
Labels: CLA signed, awaiting review, skip news

#18853 fix typo: add space
  Doc/using/cmdline.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#18856 [3.7] fix typo: add space (GH-18853)
  Doc/using/cmdline.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#18855 [3.8] fix typo: add space (GH-18853)
  Doc/using/cmdline.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#18801 bpo-39852: IDLE 'Go to line' deletes selection, updates status
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2020-03-06-01-55-14.bpo-39852.QjA1qF.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-bugfix

#18857 [3.8] bpo-39852: IDLE 'Go to line' deletes selection, updates status (GH-18801)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2020-03-06-01-55-14.bpo-39852.QjA1qF.rst
Labels: CLA signed, awaiting merge, type-bugfix

#18858 [3.7] bpo-39852: IDLE 'Go to line' deletes selection, updates status (GH-18801)
  Doc/library/idle.rst
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Lib/idlelib/help.html
  Misc/NEWS.d/next/IDLE/2020-03-06-01-55-14.bpo-39852.QjA1qF.rst
Labels: CLA signed, awaiting merge, type-bugfix

#18859 bpo-39885: IDLE context menu clears selection
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Misc/NEWS.d/next/IDLE/2020-03-08-14-27-36.bpo-39885.29ERiR.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-bugfix

#18861 [3.7] bpo-39885: IDLE context menu clears selection (GH-18859)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Misc/NEWS.d/next/IDLE/2020-03-08-14-27-36.bpo-39885.29ERiR.rst
Labels: CLA signed, awaiting merge, type-bugfix

#18860 [3.8] bpo-39885: IDLE context menu clears selection (GH-18859)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Misc/NEWS.d/next/IDLE/2020-03-08-14-27-36.bpo-39885.29ERiR.rst
Labels: CLA signed, awaiting merge, type-bugfix

#18699 bpo-39517: fix runpy.run_path() when using pathlike objects
  Lib/runpy.py
  Lib/test/test_runpy.py
  Misc/NEWS.d/next/Library/2020-02-29-11-20-50.bpo-39517.voQZb8.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8

#18862 [3.8] bpo-39517: Allow runpy.run_path() to accept path-like objects (GH-18699)
  Lib/runpy.py
  Lib/test/test_runpy.py
  Misc/NEWS.d/next/Library/2020-02-29-11-20-50.bpo-39517.voQZb8.rst
Labels: CLA signed, awaiting merge

#18603 Fix typo 'Calculate'
  Parser/pgen/automata.py
Labels: CLA not signed, awaiting merge, skip issue, skip news, type-documentation

#18868 bpo-27115: Move IDLE Query error blanking
  Lib/idlelib/query.py
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip news

#18870 [3.7] bpo-27115: Move IDLE Query error blanking (GH-18868)
  Lib/idlelib/query.py
Labels: CLA signed, awaiting merge, skip news

#18869 [3.8] bpo-27115: Move IDLE Query error blanking (GH-18868)
  Lib/idlelib/query.py
Labels: CLA signed, awaiting merge, skip news

#18627 bpo-38691: Ignore pythoncaseok tests
  Doc/library/functions.rst
  Doc/whatsnew/3.9.rst
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_importlib/extension/test_case_sensitivity.py
  Lib/test/test_importlib/source/test_case_sensitivity.py
  Misc/NEWS.d/next/Library/2020-02-23-02-09-03.bpo-38691.oND8Sk.rst
  Python/importlib_external.h
Labels: CLA signed, awaiting review

#18850 bpo-39903: Fix double decref in _elementtree.Element.__getstate__
  Modules/_elementtree.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-bugfix

#18875 [3.7] bpo-39903: Fix double decref in _elementtree.Element.__getstate__ (GH-18850)
  Modules/_elementtree.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#18874 [3.8] bpo-39903: Fix double decref in _elementtree.Element.__getstate__ (GH-18850)
  Modules/_elementtree.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#18735 bpo-39822: Use NULL instead of None for empty attrib in Element.
  Modules/_elementtree.c
  Modules/clinic/_elementtree.c.h
Labels: CLA signed, awaiting merge, skip news

#18866 bpo-39850: Add support for abstract sockets in multiprocessing
  Lib/multiprocessing/connection.py
  Lib/multiprocessing/forkserver.py
  Lib/multiprocessing/managers.py
  Lib/multiprocessing/util.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2020-03-09-01-45-06.bpo-39850.eaJNIE.rst
Labels: CLA signed, awaiting merge

#18877 [3.7]bpo-39850: Add support for abstract sockets in multiprocessing (GH-18866)
  Lib/multiprocessing/connection.py
  Lib/multiprocessing/forkserver.py
  Lib/multiprocessing/util.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2020-03-09-01-45-06.bpo-39850.eaJNIE.rst
Labels: CLA signed, awaiting core review

#18876 [3.8] bpo-39850: Add support for abstract sockets in multiprocessing (GH-18866)
  Lib/multiprocessing/connection.py
  Lib/multiprocessing/forkserver.py
  Lib/multiprocessing/managers.py
  Lib/multiprocessing/util.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2020-03-09-01-45-06.bpo-39850.eaJNIE.rst
Labels: CLA signed, awaiting core review

#18852 bpo-39904: Move handling of one-argument call of type() from type.__new__() to type.__call__().
  Objects/typeobject.c
Labels: CLA signed, awaiting merge, skip news

#18863 bpo-38643: Raise SystemError instead of crashing when PyNumber_ToBase is called with invalid base.
  Lib/test/test_capi.py
  Misc/NEWS.d/next/C API/2020-03-08-22-56-22.bpo-38643.k2ixx6.rst
  Modules/_testcapimodule.c
  Objects/abstract.c
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8

#18873 bpo-36184: Port python-gdb.py to FreeBSD
  Misc/NEWS.d/next/Tools-Demos/2020-03-09-13-28-13.bpo-36184.BMPJ0D.rst
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8

#16329 bpo-38249: Expand Py_UNREACHABLE() to __builtin_unreachable() in the release mode.
  Doc/c-api/intro.rst
  Include/pymacro.h
  Misc/NEWS.d/next/C API/2020-03-09-20-27-19.bpo-38249.IxYbQy.rst
  Modules/_tracemalloc.c
  Objects/stringlib/eq.h
  Python/formatter_unicode.c
  Python/peephole.c
  Python/pytime.c
Labels: CLA signed, awaiting merge, type-performance

#18882 [3.7] bpo-36184: Port python-gdb.py to FreeBSD (GH-18873)
  Misc/NEWS.d/next/Tools-Demos/2020-03-09-13-28-13.bpo-36184.BMPJ0D.rst
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting merge

#18881 [3.8] bpo-36184: Port python-gdb.py to FreeBSD (GH-18873)
  Misc/NEWS.d/next/Tools-Demos/2020-03-09-13-28-13.bpo-36184.BMPJ0D.rst
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting merge

#18883 bpo-39877: Remove useless PyEval_InitThreads() calls
  Include/ceval.h
  Lib/test/test_embed.py
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/callbacks.c
  Modules/_testcapimodule.c
  Modules/_threadmodule.c
  Programs/_testembed.c
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#18884 bpo-39877: Py_Initialize() pass tstate to PyEval_InitThreads()
  Include/internal/pycore_ceval.h
  Python/ceval.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#17892 bpo-38870: Simplify tuple like interleaves, roundtrip extslice properly
  Lib/ast.py
  Lib/test/test_unparse.py
Labels: CLA signed, awaiting merge, skip news

#18871 bpo-27115: Use Query subclass for IDLE editor Goto
  Lib/idlelib/NEWS.txt
  Lib/idlelib/editor.py
  Lib/idlelib/idle_test/test_query.py
  Lib/idlelib/query.py
  Misc/NEWS.d/next/IDLE/2020-03-09-02-45-12.bpo-27115.8hSHMo.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-enhancement

#18885 bpo-39877: Refactor take_gil() function
  Python/ceval.c
  Python/ceval_gil.h
Labels: CLA signed, skip news
