Repository python/cpython, pull requests merged in 2020-05, with the labels that each got.

#19826 Remove dead code in test__xxsubinterpreters
  Lib/test/test__xxsubinterpreters.py
Labels: CLA signed, awaiting core review, skip issue, skip news, type-tests

#19825 bpo-40275: Fix name error in support.socket_helper
  Lib/test/support/socket_helper.py
Labels: CLA signed, awaiting core review, skip news

#19815 bpo-40443: Remove unused imports in stdlib
  Lib/importlib/resources.py
  Lib/multiprocessing/pool.py
  Lib/ssl.py
Labels: CLA signed, awaiting core review, skip news

#19827 bpo-40334: Add support for feature_version in new PEG parser
  Grammar/python.gram
  Lib/test/test_type_comments.py
  Parser/pegen/parse.c
  Parser/pegen/parse_string.c
  Parser/pegen/pegen.c
  Parser/pegen/pegen.h
Labels: CLA signed, awaiting merge, skip news

#19767 Change 'exception happened' to 'exception occurred' in two places
  Doc/tutorial/errors.rst
  Lib/socketserver.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#19820 bpo-40453: Add PyConfig._isolated_subinterpreter
  Doc/c-api/init_config.rst
  Include/cpython/initconfig.h
  Include/cpython/pylifecycle.h
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Library/2020-04-30-22-04-58.bpo-40453.ggz7sl.rst
  Modules/_posixsubprocess.c
  Modules/_threadmodule.c
  Modules/_winapi.c
  Modules/_xxsubinterpretersmodule.c
  Modules/posixmodule.c
  Programs/_testembed.c
  Python/initconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge

#19818 bpo-40334: Simplify type handling in the PEG c_generator
  Parser/pegen/parse.c
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/parser_generator.py
Labels: awaiting merge, skip news

#19814 bpo-32494: Use gdbm_count for dbm_length if possible
  Misc/NEWS.d/next/Library/2020-04-30-22-25-08.bpo-32494.1xaU5l.rst
  Modules/_gdbmmodule.c
Labels: CLA signed, awaiting merge

#19832 bpo-40462: fix variable and function names
  Lib/test/mock_socket.py
  Lib/test/test_frame.py
  Lib/unittest/test/test_program.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#19782 bpo-40334: Improve column offsets for thrown syntax errors by Pegen
  Grammar/python.gram
  Lib/test/test_cmd_line_script.py
  Lib/test/test_exceptions.py
  Parser/pegen/parse.c
  Parser/pegen/pegen.c
  Parser/pegen/pegen.h
Labels: CLA signed, awaiting merge, skip news

#19835 [3.8] bpo-39562: Prevent collision of future and compiler flags (GH-19230)
  Doc/whatsnew/3.8.rst
  Include/code.h
  Include/compile.h
  Lib/__future__.py
  Lib/test/test_future.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-01-14-58-16.bpo-39562.KCsX8n.rst
  Python/bltinmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#19837 bpo-40334: unskip test_function_type in test_unparse with the new parser
  Lib/test/test_unparse.py
Labels: CLA signed, awaiting merge, skip news

#19833 bpo-40334: Correct return value of func_type_comment
  Grammar/python.gram
  Parser/pegen/parse.c
Labels: CLA signed, awaiting merge, skip news

#19838 [3.8] bpo-39562: Correctly updated the version section in the what's new document
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#19830 bpo-40334: Refactor lambda_parameters similar to parameters
  Grammar/python.gram
  Parser/pegen/parse.c
Labels: CLA signed, awaiting merge, skip news

#19828 bpo-40334: Ensure that tok->type_comments is set on every path
  Parser/pegen/pegen.c
Labels: CLA signed, awaiting merge, skip news

#19839 bpo-40334: Make the PyPegen* and PyParser* APIs more consistent
  Include/internal/pegen_interface.h
  Modules/_peg_parser.c
  Parser/pegen/peg_api.c
Labels: CLA signed, awaiting review, skip news

#19831 Simplify choice()'s interaction with the private _randbelow() method
  Lib/random.py
  Lib/test/test_random.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#19824 bpo-39691: Clarify io.open_code behavior
  Doc/library/io.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, skip news, type-documentation

#19840 [3.8] bpo-39691: Clarify io.open_code behavior (GH-19824)
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#19746 bpo-40412: Nullify inittab_copy during finalization
  Misc/NEWS.d/next/C API/2020-05-01-17-28-04.bpo-40412.dE0D8N.rst
  Python/import.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8

#18160 bpo-39435: Fix docs for pickle.loads
  Doc/library/pickle.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2020-01-24-05-42-57.bpo-39435.EFcdFU.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-documentation

#19844 [3.7] bpo-39435: Fix docs for pickle.loads (GH-18160).
  Doc/library/pickle.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2020-01-24-05-42-57.bpo-39435.EFcdFU.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#19843 [3.8] bpo-39435: Fix docs for pickle.loads (GH-18160)
  Doc/library/pickle.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2020-01-24-05-42-57.bpo-39435.EFcdFU.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#19848 Fix the Tools/peg_generator/scripts/benchmark.py script
  Tools/peg_generator/pegen/build.py
  Tools/peg_generator/scripts/benchmark.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#19849 bpo-40334: use the TOKENS file when checking dangling rules
  Tools/peg_generator/pegen/build.py
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/parser_generator.py
  Tools/peg_generator/pegen/python_generator.py
  Tools/peg_generator/pegen/testutil.py
Labels: CLA signed, awaiting merge, skip news

#19841 [3.8] bpo-40412: Nullify inittab_copy during finalization (GH-19746)
  Misc/NEWS.d/next/C API/2020-05-01-17-28-04.bpo-40412.dE0D8N.rst
  Python/import.c
Labels: CLA signed, awaiting merge

#19750 bpo-40417: Fix deprecation warning in PyImport_ReloadModule
  Misc/NEWS.d/next/Core and Builtins/2020-05-01-19-04-52.bpo-40417.Sti2lJ.rst
  Python/import.c
Labels: :robot: automerge, CLA signed, awaiting merge

#19823 bpo-29587: Enable implicit exception chaining with gen.throw()
  Lib/test/test_generators.py
  Misc/NEWS.d/next/Core and Builtins/2020-04-30-00-50-25.bpo-29587.oEwSq.rst
  Objects/genobject.c
Labels: CLA signed, awaiting merge

#19853 Fix some scripts in the peg generator folder
  Lib/test/test_peg_generator/test_c_parser.py
  Tools/peg_generator/data/cprog.py
  Tools/peg_generator/data/top-pypi-packages-365-days.json
  Tools/peg_generator/peg_extension/__init__.py
  Tools/peg_generator/pegen/ast_dump.py
  Tools/peg_generator/pegen/build.py
  Tools/peg_generator/scripts/benchmark.py
  Tools/peg_generator/scripts/show_parse.py
  Tools/peg_generator/scripts/test_parse_directory.py
  Tools/peg_generator/scripts/test_pypi_packages.py
Labels: CLA signed, skip issue, skip news

#19854 bpo-40334: regenerate metaparser as part of regen-all
  Makefile.pre.in
  Tools/peg_generator/pegen/grammar_parser.py
Labels: CLA signed, awaiting merge, skip news

#19846 bpo-39435: Make the first argument of pickle.loads() positional-only.
  Doc/library/pickle.rst
  Lib/pickle.py
  Misc/NEWS.d/next/Library/2020-05-01-23-24-25.bpo-39435.mgb6ib.rst
  Modules/_pickle.c
  Modules/clinic/_pickle.c.h
Labels: CLA signed, awaiting merge, type-enhancement

#19857 [3.8] bpo-40398: Fix typing.get_args() for special generic aliases. (GH-19720)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2020-04-26-22-25-36.bpo-40398.OdXnR3.rst
Labels: CLA signed, awaiting core review, type-bugfix

#19861 Call mkdir before regenerating the peg metaparser
  Makefile.pre.in
Labels: CLA signed, awaiting core review, skip issue, skip news

#19752 bpo-40419: timeit CLI docs now mention 1,2,5,10,... trials instead of powers of 10
  Doc/library/timeit.rst
  Lib/timeit.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#19864 [3.7] bpo-40419: timeit CLI docs now mention 1,2,5,10,... trials instead of powers of 10 (GH-19752)
  Doc/library/timeit.rst
  Lib/timeit.py
Labels: CLA signed, awaiting merge, skip news, type-documentation

#19863 [3.8] bpo-40419: timeit CLI docs now mention 1,2,5,10,... trials instead of powers of 10 (GH-19752)
  Doc/library/timeit.rst
  Lib/timeit.py
Labels: CLA signed, awaiting merge, skip news, type-documentation

#19867 bpo-40465: Deprecate the optional argument to random.shuffle().
  Doc/library/random.rst
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2020-05-02-12-00-28.bpo-40465.qfCjOD.rst
Labels: CLA signed, awaiting core review

#19866 documentation: missing space between Mersenne and Tiwster
  Doc/library/random.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip issue, skip news, type-documentation

#19872 [3.8] Fix missing space in docs(GH-19866)
  Doc/library/random.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#19873 Minor code cleanups for statistics
  Lib/statistics.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#19877 bpo-29587: Remove the exc_value NULL check in _gen_throw()
  Lib/test/test_generators.py
  Objects/genobject.c
Labels: CLA signed, awaiting merge, skip news

#19881 Simplify set entry insertion logic.
  Objects/setobject.c
Labels: CLA signed, awaiting core review, skip issue, skip news, type-performance

#19636 bpo-38870: Don't start generated output with newlines
  Lib/ast.py
  Lib/test/test_unparse.py
Labels: CLA signed, awaiting merge, skip news

#19886 Remove out-of-date comment
  Objects/setobject.c
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#19889 Remove outdated and confusing advice about setting maxsize
  Doc/library/functools.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip issue, skip news, type-documentation

#19890 [3.8] Remove outdated and confusing advice about setting maxsize (GH-19889)
  Doc/library/functools.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#19887 bpo-40334: Set error_indicator in _PyPegen_raise_error
  Parser/pegen/pegen.c
Labels: CLA signed, awaiting merge, skip news

#19891 bpo-40490 Clean up unused imports for pegen module
  Tools/peg_generator/pegen/build.py
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/first_sets.py
  Tools/peg_generator/pegen/grammar.py
  Tools/peg_generator/pegen/grammar_visualizer.py
  Tools/peg_generator/scripts/ast_timings.py
  Tools/peg_generator/scripts/benchmark.py
  Tools/peg_generator/scripts/find_max_nesting.py
  Tools/peg_generator/scripts/test_parse_directory.py
Labels: CLA signed, awaiting review, skip news

#19894 bpo-40493: fix function type comment parsing
  Grammar/python.gram
  Lib/test/test_type_comments.py
  Parser/pegen/parse.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#19836 bpo-40408: Fix support of nested type variables in GenericAlias.
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-01-15-36-14.bpo-40408.XzQI59.rst
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#19893 bpo-40491: fix typo in syntax error for numeric literals
  Parser/pegen/pegen.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#19865 bpo-40334: Spacialized error message for invalid args after bare '*'
  Grammar/python.gram
  Lib/test/test_exceptions.py
  Lib/test/test_peg_parser.py
  Lib/test/test_syntax.py
  Parser/pegen/parse.c
Labels: CLA signed, awaiting merge, skip news

#19888 bpo-40246: Revert reporting of invalid string prefixes
  Include/errcode.h
  Lib/test/test_fstring.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-03-23-28-11.bpo-40246.c1D7x8.rst
  Parser/pegen/pegen.c
  Parser/tokenizer.c
  Python/pythonrun.c
Labels: CLA signed, awaiting merge

#19882 bpo-39573: Use Py_IS_TYPE to check for types
  Objects/genericaliasobject.c
  Objects/typeobject.c
Labels: CLA signed, awaiting merge, skip news

#19852 bpo-40455: Remove gcc10 warning about x_digits
  Objects/longobject.c
Labels: CLA signed, awaiting merge, skip news

#19892 bpo-40135: don't define shared memory block's name in test_shared_memory_across_…
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting review, skip news

#19903 [3.8] bpo-40135: Fix multiprocessing test_shared_memory_across_processes() (GH-19892)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, awaiting merge, skip news

#19906 bpo-40489: Add test case for dict contain use after free
  Lib/test/test_dict.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#19761 bpo-40275: Remove duplicate import of locale module
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting changes, skip news

#19898 bpo-40360: Add a What's new entry for lib2to3 pending deprecation
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#18216 bpo-39470: Indicate that ``os.makedirs`` is equivalent to ``Path.mkdir``
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#19900 bpo-40499: Mention that asyncio.wait() needs a non-empty aws set
  Doc/library/asyncio-task.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2020-05-04-14-20-02.bpo-40499.tjLSo8.rst
Labels: CLA signed, awaiting merge

#19907 bpo-1635741: Port syslog module to multiphase initialization
  Misc/NEWS.d/next/Core and Builtins/2020-05-05-03-36-27.bpo-1635741.ARv1YV.rst
  Modules/syslogmodule.c
Labels: CLA signed, awaiting merge

#19855 bpo-40459: Fix NameError in platform.py
  Lib/platform.py
  Misc/NEWS.d/next/Library/2020-05-02-04-29-31.bpo-40459.fSAYVD.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#19913 [3.7] bpo-40459: Fix NameError in platform.py (GH-19855)
  Lib/platform.py
  Misc/NEWS.d/next/Library/2020-05-02-04-29-31.bpo-40459.fSAYVD.rst
Labels: CLA signed, awaiting merge

#19912 [3.8] bpo-40459: Fix NameError in platform.py (GH-19855)
  Lib/platform.py
  Misc/NEWS.d/next/Library/2020-05-02-04-29-31.bpo-40459.fSAYVD.rst
Labels: CLA signed, awaiting merge

#19870 bpo-40286: Put methods in correct sections. Add security notice
  Doc/library/random.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#19922 Update docs.
  Doc/library/xml.etree.elementtree.rst
  Doc/whatsnew/3.9.rst
  Misc/NEWS.d/3.9.0a1.rst
Labels: CLA signed, awaiting core review, type-documentation

#19924 bpo-40513: Per-interpreter signals pending
  Include/internal/pycore_interp.h
  Include/internal/pycore_runtime.h
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#19927 bpo-40513: Per-interpreter gil_drop_request
  Include/internal/pycore_interp.h
  Include/internal/pycore_runtime.h
  Python/ceval.c
  Python/ceval_gil.h
Labels: CLA signed, awaiting core review, skip news

#19926 bpo-40514: Add --with-experimental-isolated-subinterpreters
  Misc/NEWS.d/next/Build/2020-05-05-15-39-11.bpo-40514.bZZmuS.rst
  Python/preconfig.c
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting merge

#19737 bpo-32117: Updated Simpsons names in docs
  Doc/whatsnew/3.8.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#19929 bpo-40513: Per-interpreter recursion_limit
  Include/internal/pycore_ceval.h
  Include/internal/pycore_interp.h
  Include/internal/pycore_runtime.h
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#19902 bpo-29587: PyErr_SetObject() rejects exception=None
  Lib/test/test_generators.py
  Objects/exceptions.c
  Objects/genobject.c
  Python/errors.c
Labels: CLA signed, awaiting merge, skip news

#19931 bpo-40520: Remove redundant comment in pydebug.h
  Include/pydebug.h
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#19932 Revert "bpo-40513: Per-interpreter signals pending (GH-19924)"
  Include/internal/pycore_interp.h
  Include/internal/pycore_runtime.h
  Python/ceval.c
  Python/ceval_gil.h
Labels: CLA signed, awaiting merge, skip news

#19933 bpo-40521: Disable Unicode caches in isolated subinterpreters
  Objects/typeobject.c
  Objects/unicodeobject.c
Labels: CLA signed, awaiting core review, skip news

#19845 bpo-40458: Increase reserved stack space to prevent overflow crash on Windows
  Misc/NEWS.d/next/Windows/2020-05-01-20-57-57.bpo-40458.Eb0ueI.rst
  PCbuild/python_uwp.vcxproj
  PCbuild/pythonw_uwp.vcxproj
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, type-bugfix

#19937 bpo-40521: Disable free lists in subinterpreters
  Objects/dictobject.c
  Objects/frameobject.c
  Objects/tupleobject.c
Labels: CLA signed, awaiting core review, skip news

#19939 bpo-40522: _PyThreadState_Swap() sets autoTSSkey
  Include/internal/pycore_pystate.h
  Python/ceval.c
  Python/pystate.c
Labels: CLA signed, awaiting core review, skip news

#19941 [3.8] bpo-40458: Increase reserved stack space to prevent overflow crash on Windows (GH-19845)
  Misc/NEWS.d/next/Windows/2020-05-01-20-57-57.bpo-40458.Eb0ueI.rst
  PCbuild/python_uwp.vcxproj
  PCbuild/pythonw_uwp.vcxproj
Labels: CLA signed, awaiting merge, type-bugfix

#19942 bpo-40513: new_interpreter() init GIL earlier
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#19943 bpo-40513: Per-interpreter GIL
  Include/internal/pycore_ceval.h
  Include/internal/pycore_interp.h
  Include/internal/pycore_runtime.h
  Python/ceval.c
  Python/ceval_gil.h
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#19944 bpo-40513: _xxsubinterpreters.run_string() releases the GIL
  Modules/_xxsubinterpretersmodule.c
Labels: CLA signed, awaiting core review, skip news

#19868 bpo-40355: ast.literal_eval rejects malformed Dict nodes
  Lib/ast.py
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2020-05-02-14-24-48.bpo-40355.xTujaB.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-bugfix

#19938 bpo-40504: Allow weakrefs to lru_cache objects
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Library/2020-05-05-17-12-47.bpo-40504.EX6wPn.rst
  Modules/_functoolsmodule.c
Labels: CLA signed, awaiting merge

#19946 bpo-40523: Add pass-throughs for hash() and reversed() to weakref.proxy objects
  Lib/test/test_weakref.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-05-20-36-15.bpo-40523.hKZVTB.rst
  Objects/weakrefobject.c
Labels: CLA signed, awaiting merge

#19934 [3.8] bpo-40417: Fix deprecation warning in PyImport_ReloadModule (GH-19750)
  Misc/NEWS.d/next/Core and Builtins/2020-05-01-19-04-52.bpo-40417.Sti2lJ.rst
  Python/import.c
Labels: :robot: automerge, CLA signed, awaiting merge

#19935 [3.7] bpo-40417: Fix deprecation warning in PyImport_ReloadModule (GH-19750)
  Misc/NEWS.d/next/Core and Builtins/2020-05-01-19-04-52.bpo-40417.Sti2lJ.rst
  Python/import.c
Labels: :robot: automerge, CLA signed, awaiting merge

#19908 bpo-40480 "fnmatch" exponential execution time
  Lib/fnmatch.py
  Lib/test/test_fnmatch.py
  Misc/NEWS.d/next/Library/2020-05-04-21-21-43.bpo-40480.mjldWa.rst
Labels: CLA signed, awaiting core review

#19928 bpo-40517: Implement syntax highlighting support for ASDL
  Doc/conf.py
  Doc/library/ast.rst
  Doc/tools/extensions/asdl_highlight.py
Labels: CLA signed, awaiting review, skip news

#19950 Revert "bpo-40517: Implement syntax highlighting support for ASDL"
  Doc/conf.py
  Doc/library/ast.rst
  Doc/tools/extensions/asdl_highlight.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#19955 bpo-40527: Fix command line argument parsing
  Lib/test/test_cmd_line.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-06-14-52-35.bpo-40527.gTNKuy.rst
  Python/getopt.c
Labels: CLA signed, awaiting merge, needs backport to 3.8

#19956 [3.8] bpo-40527: Fix command line argument parsing (GH-19955)
  Lib/test/test_cmd_line.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-06-14-52-35.bpo-40527.gTNKuy.rst
  Python/getopt.c
Labels: CLA signed, awaiting merge

#19960 bpo-40521: Disable method cache in subinterpreters
  Objects/typeobject.c
Labels: CLA signed, awaiting core review, skip news

#19961 bpo-40533: Disable GC in subinterpreters
  Modules/gcmodule.c
Labels: CLA signed, awaiting merge, skip news

#19959 bpo-40521: Disable list free list in subinterpreters
  Objects/listobject.c
Labels: awaiting core review, skip news

#19963 bpo-40334: Add type to the assignment rule in the grammar file
  Grammar/python.gram
  Parser/pegen/parse.c
Labels: CLA signed, awaiting merge, skip news

#19965 bpo-40537 : Fix typo in sqlite3 documentation
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#19964 bpo-40334: Allow trailing comma in parenthesized context managers
  Grammar/python.gram
  Lib/test/test_grammar.py
  Parser/pegen/parse.c
Labels: CLA signed, awaiting merge, skip news

#19966 bpo-40334: Generate comments in the parser code to improve debugging
  Parser/pegen/parse.c
  Tools/peg_generator/pegen/c_generator.py
Labels: CLA signed, awaiting merge, skip news

#19719 bpo-40397: Refactor typing._GenericAlias
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#19923 bpo-1635741: Port errno module to multiphase initialization
  Misc/NEWS.d/next/Core and Builtins/2020-05-05-21-11-35.bpo-1635741.ggwD3C.rst
  Modules/errnomodule.c
Labels: CLA signed, awaiting merge

#19962 bpo-40334: Fix error location upon parsing an invalid string literal
  Lib/test/test_cmd_line_script.py
  Lib/test/test_string_literals.py
  Parser/pegen/parse_string.c
  Parser/pegen/parse_string.h
  Parser/pegen/pegen.c
  Parser/pegen/pegen.h
Labels: CLA signed, awaiting merge, skip news

#19973 bpo-40334: Error message for invalid default args in function call
  Grammar/python.gram
  Lib/test/test_exceptions.py
  Lib/test/test_peg_parser.py
  Parser/pegen/parse.c
Labels: CLA signed, awaiting merge, skip news

#19936 bpo-38787: C API for module state access from extension methods (PEP 573)
  Doc/c-api/structures.rst
  Doc/c-api/type.rst
  Include/cpython/methodobject.h
  Include/cpython/object.h
  Include/methodobject.h
  Include/object.h
  Lib/test/test_capi.py
  Lib/test/test_sys.py
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2020-01-22-12-38-59.bpo-38787.HUH6hd.rst
  Modules/_testmultiphase.c
  Modules/clinic/_testmultiphase.c.h
  Objects/descrobject.c
  Objects/methodobject.c
  Objects/object.c
  Objects/typeobject.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting merge

#19978 bpo-40545: Export _PyErr_GetTopmostException() function
  Include/cpython/pyerrors.h
  Misc/NEWS.d/next/C API/2020-05-07-11-41-13.bpo-40545.51DzF1.rst
Labels: CLA signed, awaiting core review

#19768 bpo-32604: [_xxsubinterpreters] Propagate exceptions.
  Lib/test/test__xxsubinterpreters.py
  Modules/_xxsubinterpretersmodule.c
Labels: awaiting core review, skip news

#19980 bpo-38787: update docs of structures.rst and code style of _testmultiphase.c
  Doc/c-api/structures.rst
  Modules/_testmultiphase.c
Labels: CLA signed, awaiting merge, skip news

#19981 bpo-40548: Always run GitHub action, even on doc PRs
  .github/workflows/build.yml
Labels: CLA signed, awaiting core review, skip news

#19967 bpo-40517: Implement syntax highlighting support for ASDL
  Doc/conf.py
  Doc/library/ast.rst
  Doc/tools/extensions/asdl_highlight.py
Labels: CLA signed, awaiting review, skip news

#19986 bpo-40555: Check for p->error_indicator in loop rules after the main loop is done
  Lib/test/test_eof.py
  Parser/pegen/parse.c
  Tools/peg_generator/pegen/c_generator.py
Labels: CLA signed, awaiting core review, skip news

#19513 bpo-40273: Reversible mappingproxy
  Doc/library/types.rst
  Lib/test/test_types.py
  Misc/NEWS.d/next/Library/2020-04-14-09-54-35.bpo-40273.IN73Ks.rst
  Objects/descrobject.c
Labels: CLA signed, awaiting core review, type-enhancement

#19990 bpo-40559: Add Py_DECREF to _asynciomodule.c:task_step_impl()
  Misc/NEWS.d/next/Library/2020-05-05-08-12-51.bpo-40559.112wwa.rst
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-bugfix

#19995 [3.8] bpo-40559: Add Py_DECREF to _asynciomodule.c:task_step_impl() (GH-19990)
  Misc/NEWS.d/next/Library/2020-05-05-08-12-51.bpo-40559.112wwa.rst
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting review, type-bugfix

#19996 [3.7] bpo-40559: Add Py_DECREF to _asynciomodule.c:task_step_impl() (GH-19990)
  Misc/NEWS.d/next/Library/2020-05-05-08-12-51.bpo-40559.112wwa.rst
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting review, type-bugfix

#19994 Make the first dataclass example more useful
  Doc/library/dataclasses.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#19997 [3.8] Make the first dataclass example more useful (GH-19994)
  Doc/library/dataclasses.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#19998 [3.7] Make the first dataclass example more useful (GH-19994)
  Doc/library/dataclasses.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#19970 bpo-40541: Add optional *counts* parameter to random.sample()
  Doc/library/random.rst
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2020-05-06-15-36-47.bpo-40541.LlYghL.rst
Labels: CLA signed, awaiting merge, type-enhancement

#19988 bpo-40502: Initialize n->n_col_offset
  Misc/NEWS.d/next/Core and Builtins/2020-05-08-03-25-26.bpo-40502.e-VCyL.rst
  Parser/node.c
Labels: CLA signed, awaiting merge

#19722 bpo-39791: Add files() to importlib.resources
  Doc/library/importlib.rst
  Lib/importlib/_common.py
  Lib/importlib/abc.py
  Lib/importlib/resources.py
  Lib/test/test_importlib/test_files.py
  Lib/test/test_importlib/test_path.py
  Misc/NEWS.d/next/Library/2020-04-27-00-51-40.bpo-39791.wv8Dxn.rst
Labels: CLA signed, awaiting core review

#20005 bpo-40566: Apply PEP 573 to abc module
  Misc/NEWS.d/next/Core and Builtins/2020-05-09-01-39-16.bpo-40566.wlcjW_.rst
  Modules/_abc.c
Labels: :robot: automerge, CLA signed, awaiting merge

#20015 bpo-40570: Improve compatibility of uname_result with late-bound .platform
  Lib/platform.py
  Lib/test/test_platform.py
Labels: :robot: automerge, CLA signed, awaiting core review, skip news

#19987 bpo-40334: Avoid collisions between parser variables and grammar variables
  Lib/test/test_peg_generator/test_pegen.py
  Parser/pegen/parse.c
  Parser/pegen/pegen.h
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/parser_generator.py
Labels: CLA signed, awaiting merge, skip news

#19884 [doc] Add link to Enum class
  Doc/library/types.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#19984 bpo-40397: Remove __args__ and __parameters__ from _SpecialGenericAlias
  Lib/typing.py
  Misc/NEWS.d/next/Library/2020-05-07-21-22-04.bpo-40397.PVWFAn.rst
Labels: CLA signed, awaiting merge

#19982 bpo-40549: Convert posixmodule.c to multiphase init
  Misc/NEWS.d/next/Library/2020-05-07-20-11-51.bpo-40549.6FiRSV.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#15611 bpo-37986: Improve perfomance of PyLong_FromDouble()
  Misc/NEWS.d/next/Core and Builtins/2019-11-20-09-50-58.bpo-37986.o0lmA7.rst
  Objects/floatobject.c
  Objects/longobject.c
Labels: CLA signed, awaiting merge

#20021 bpo-40397: Fix subscription of nested generic alias without parameters.
  Lib/test/test_typing.py
  Lib/typing.py
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#20022 bpo-40257: Tweak docstrings for special generic aliases.
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip news, type-documentation, type-enhancement

#20028 Improve code clarity for the set lookup logic
  Objects/setobject.c
Labels: :robot: automerge, CLA signed, awaiting core review, skip issue, skip news

#20030 bpo-40585: Normalize errors messages in codeop when comparing them
  Lib/test/test_codeop.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-11-00-19-42.bpo-40585.yusknY.rst
  Parser/pegen/pegen.c
Labels: CLA signed, awaiting merge

#20018 bpo-40575: Avoid unnecessary overhead in _PyDict_GetItemIdWithError()
  Objects/dictobject.c
Labels: CLA signed, awaiting core review, skip news

#19653 bpo-36346: array: Don't use deprecated APIs
  Doc/library/array.rst
  Doc/whatsnew/3.9.rst
  Modules/arraymodule.c
  Modules/clinic/arraymodule.c.h
Labels: CLA signed, awaiting changes, skip news

#19999 bpo-40561: Provide docstrings for public-facing webbrowser functions
  Lib/webbrowser.py
  Misc/NEWS.d/next/Documentation/2020-05-08-08-39-40.bpo-40561.ZMB_2i.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#20037 [3.7] bpo-40561: Add docstrings for webbrowser open functions (GH-19999)
  Lib/webbrowser.py
  Misc/NEWS.d/next/Documentation/2020-05-08-08-39-40.bpo-40561.ZMB_2i.rst
Labels: CLA signed, awaiting merge

#20036 [3.8] bpo-40561: Add docstrings for webbrowser open functions (GH-19999)
  Lib/webbrowser.py
  Misc/NEWS.d/next/Documentation/2020-05-08-08-39-40.bpo-40561.ZMB_2i.rst
Labels: CLA signed, awaiting merge

#20026 bpo-40584: Update PyType_FromModuleAndSpec to process tp_vectorcall_offset
  Doc/c-api/structures.rst
  Doc/c-api/type.rst
  Objects/typeobject.c
Labels: CLA signed, awaiting review, skip news

#19911 bpo-40334: produce specialised errors for del
  Grammar/python.gram
  Lib/test/test_grammar.py
  Lib/test/test_syntax.py
  Parser/pegen/parse.c
Labels: CLA signed, awaiting merge, skip news

#20043 bpo-39465: Don't access directly _Py_Identifier members
  Modules/_cursesmodule.c
  Objects/abstract.c
  Objects/typeobject.c
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#20019 bpo-40571: Make lru_cache(maxsize=None) more discoverable
  Doc/library/functools.rst
  Lib/functools.py
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Library/2020-05-09-15-38-25.bpo-40571.kOXZGC.rst
Labels: CLA signed, awaiting core review, type-enhancement

#20044 bpo-40602: Rename hashtable.h to pycore_hashtable.h
  Include/internal/pycore_hashtable.h
  Makefile.pre.in
  Modules/Setup
  Modules/_tracemalloc.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/hashtable.c
  Python/marshal.c
Labels: CLA signed, awaiting core review, skip news

#20046 bpo-40602: _Py_hashtable_new() uses PyMem_Malloc()
  Python/hashtable.c
Labels: CLA signed, awaiting core review, skip news

#20049 bpo-40480: restore ability to join fnmatch.translate() results
  Lib/fnmatch.py
  Lib/test/test_fnmatch.py
Labels: CLA signed, awaiting core review, skip news

#20045 bpo-39481: remove generic classes from ipaddress/mmap
  Lib/ipaddress.py
  Lib/test/test_genericalias.py
  Modules/mmapmodule.c
Labels: CLA signed, awaiting merge, skip news

#20033 bpo-40593: Improve syntax errors for invalid characters in source code.
  Include/cpython/unicodeobject.h
  Include/errcode.h
  Lib/test/test_fstring.py
  Lib/test/test_source_encoding.py
  Lib/test/test_unicode_identifiers.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-11-13-50-52.bpo-40593.yuOXj3.rst
  Objects/unicodeobject.c
  Parser/pegen/pegen.c
  Parser/tokenizer.c
  Python/pythonrun.c
Labels: CLA signed, awaiting core review, type-enhancement

#20051 bpo-40602: Optimize _Py_hashtable for pointer keys
  Include/internal/pycore_hashtable.h
  Python/hashtable.c
Labels: CLA signed, awaiting core review, skip news

#20053 bpo-40596: Fix str.isidentifier() for non-canonicalized strings containing non-BMP characters on Windows.
  Lib/test/test_unicode.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-11-20-53-52.bpo-40596.dwOH_X.rst
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, type-bugfix
