Repository python/cpython, pull requests merged in 2020-09, with the labels that each got.

#21970 [doc] Document VIRTUAL_ENV environment variable (GH-21970)
  Doc/using/venv-create.inc
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22038 bpo-41685: Temporarily pin setuptools to 49.2.1 in Docs venv.
  Doc/Makefile
Labels: CLA signed, awaiting merge, skip issue, skip news

#21940 [doc] Add link to FileHandler in logging (GH-21940)
  Doc/library/logging.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22041 [3.9] bpo-41681: Fix for `f-string/str.format` error description when using 2 `,` in format specifier (GH-22036)
  Lib/test/test_format.py
  Lib/test/test_fstring.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-31-17-49-02.bpo-41681.3-VJiH.rst
  Python/formatter_unicode.c
Labels: :robot: automerge, CLA signed, awaiting merge

#22042 bpo-41617: Fix pycore_bitutils.h to support clang 3.0
  Include/internal/pycore_bitutils.h
  Misc/NEWS.d/next/Build/2020-08-24-18-34-01.bpo-41617.sKKXz7.rst
Labels: CLA signed, awaiting core review

#21837 bpo-41528 Use math module in turtle
  Lib/turtle.py
  Misc/NEWS.d/next/Library/2020-08-12-07-43-31.bpo-41528.bu83oD.rst
Labels: CLA signed, awaiting merge

#22020 bpo-41654: Fix deallocator of MemoryError to account for subclasses
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-30-20-38-33.bpo-41654.HtnhAM.rst
  Objects/exceptions.c
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9

#22044 [3.9] bpo-41617: Fix pycore_byteswap.h to support clang 3.0 (GH-22042)
  Include/internal/pycore_byteswap.h
  Misc/NEWS.d/next/Build/2020-08-24-18-34-01.bpo-41617.sKKXz7.rst
Labels: CLA signed, awaiting core review

#22046 [3.8] bpo-41654: Fix deallocator of MemoryError to account for subclasses (GH-22020)
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-30-20-38-33.bpo-41654.HtnhAM.rst
  Objects/exceptions.c
Labels: CLA signed, awaiting core review

#22045 [3.9] bpo-41654: Fix deallocator of MemoryError to account for subclasses (GH-22020)
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-30-20-38-33.bpo-41654.HtnhAM.rst
  Objects/exceptions.c
Labels: CLA signed, awaiting core review

#22023 bpo-39349: Add cancel_futures to Executor.shutdown base class
  Lib/concurrent/futures/_base.py
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#22031 Note the buffer slots can be set with PyType_Spec with the unlimited …
  Doc/c-api/type.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news, type-documentation

#22052 [3.9] Note the buffer slots can be set with PyType_Spec with the unlimited API. (GH-22031)
  Doc/c-api/type.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22011 [doc] Remove references to PyChecker
  Doc/faq/design.rst
  Doc/faq/programming.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22012 [doc] Remove reference to Boa Constructor
  Doc/faq/programming.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22032 bpo-41513: Improve hypot() accuracy with three separate accumulators
  Modules/mathmodule.c
Labels: CLA signed, awaiting core review, skip news

#22059 bpo-41681 Fixed mistake in test for `f-string/str.format` error description (GH-22036)
  Lib/test/test_format.py
  Lib/test/test_fstring.py
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-tests

#21856 bpo-1635741: port blake2 module to multi-phase init
  Misc/NEWS.d/next/Core and Builtins/2020-08-13-07-18-05.bpo-1635741.FC13e7.rst
  Modules/_blake2/blake2b_impl.c
  Modules/_blake2/blake2module.c
  Modules/_blake2/blake2s_impl.c
Labels: CLA signed, awaiting merge

#21855 bpo-1635741: port sha3 module to multi-phase init
  Misc/NEWS.d/next/Core and Builtins/2020-08-13-07-19-21.bpo-1653741.fubBkb.rst
  Modules/_sha3/sha3module.c
Labels: CLA signed, awaiting merge

#22043 bpo-40204: Update Sphinx to version 3.2.1 in Doc/Makefile
  Doc/Makefile
Labels: CLA signed, awaiting core review, skip news

#22062 bpo-41685: Don't pin setuptools version in Doc/Makefile
  Doc/Makefile
Labels: CLA signed, awaiting core review, skip news

#22060 [3.9] Fixed mistake in test for f-string error description (GH-22036) (GH-22059)
  Lib/test/test_format.py
  Lib/test/test_fstring.py
Labels: CLA signed, awaiting review, skip issue, skip news, type-tests

#22057 [3.8] Remove reference to Boa Constructor. (GH-22012)
  Doc/faq/programming.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22056 [3.9] Remove reference to Boa Constructor. (GH-22012)
  Doc/faq/programming.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22054 [3.9] [doc] Remove references to PyChecker. (GH-22011)
  Doc/faq/design.rst
  Doc/faq/programming.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22055 [3.8] [doc] Remove references to PyChecker. (GH-22011)
  Doc/faq/design.rst
  Doc/faq/programming.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22028 bpo-41675: Modernize siginterrupt calls
  Misc/NEWS.d/next/Core and Builtins/2020-08-31-14-53-17.bpo-41675.VSoqWU.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting merge

#22047 bpo-41679: Fix invalid escape sequences in the peg_highlight Sphinx extension
  Doc/tools/extensions/peg_highlight.py
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#22058 closes bpo-41689: Preserve text signature from tp_doc in C heap type creation.
  Lib/test/test_capi.py
  Misc/NEWS.d/next/C API/2020-09-01-23-39-45.bpo-41689.zxHbLB.rst
  Modules/_testcapimodule.c
  Objects/typeobject.c
Labels: CLA signed, awaiting core review

#22065 [3.9] bpo-41679: Fix invalid escape sequences in the peg_highlight Sphinx extension (GH-22047)
  Doc/tools/extensions/peg_highlight.py
Labels: CLA signed, awaiting merge, skip news

#22053 bpo-41690: Use a loop to collect args in the parser instead of recursion
  Grammar/python.gram
  Misc/NEWS.d/next/Core and Builtins/2020-09-02-12-00-57.bpo-41690.Ny-Sfy.rst
  Parser/parser.c
  Parser/pegen.c
  Parser/pegen.h
Labels: CLA signed, awaiting merge, needs backport to 3.9

#22048 [3.9] bpo-39349: Add cancel_futures to Executor.shutdown base class (GH-22023)
  Lib/concurrent/futures/_base.py
Labels: CLA signed, awaiting merge, skip news

#22067 [3.9] bpo-41690: Use a loop to collect args in the parser instead of recursion (GH-22053)
  Grammar/python.gram
  Misc/NEWS.d/next/Core and Builtins/2020-09-02-12-00-57.bpo-41690.Ny-Sfy.rst
  Parser/pegen/parse.c
  Parser/pegen/pegen.c
  Parser/pegen/pegen.h
Labels: CLA signed, awaiting core review

#22069 bpo-41696: Fix handling of debug mode in asyncio.run
  Lib/asyncio/runners.py
  Lib/test/test_asyncio/test_runners.py
  Misc/NEWS.d/next/Library/2020-09-03-01-35-32.bpo-41696.zkYGre.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#22066 bpo-39010: Improve test shutdown
  Lib/test/test_asyncio/test_windows_events.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-tests

#17635 bpo-39883: Use BSD0 license for code in docs
  Doc/license.rst
  LICENSE
  Misc/NEWS.d/next/Documentation/2020-03-07-03-53-39.bpo-39883.1tnb4-.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#22049 bpo-1635741 port signalmodule to multi-phase init (PEP 489)
  Misc/NEWS.d/next/Core and Builtins/2020-09-01-17-07-20.bpo-1635741.7wSuCc.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting review

#22030 [doc] Fix a typo in the graphlib docs
  Doc/library/graphlib.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news, type-documentation

#22077 bpo-41697: Correctly handle KeywordOrStarred when parsing arguments in the parser
  Grammar/python.gram
  Parser/parser.c
  Parser/pegen.c
  Parser/pegen.h
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#22021 bpo-41667: Fix 'gather' rules in the python parser generator
  Lib/test/test_peg_generator/test_pegen.py
  Tools/peg_generator/pegen/python_generator.py
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#22073 [3.9] bpo-39883: Use BSD0 license for code in docs (GH-17635)
  Doc/license.rst
  LICENSE
  Misc/NEWS.d/next/Documentation/2020-03-07-03-53-39.bpo-39883.1tnb4-.rst
Labels: CLA signed, awaiting merge

#22074 [3.8] bpo-39883: Use BSD0 license for code in docs (GH-17635)
  Doc/license.rst
  LICENSE
  Misc/NEWS.d/next/Documentation/2020-03-07-03-53-39.bpo-39883.1tnb4-.rst
Labels: CLA signed, awaiting merge

#22079 [3.9] bpo-41697: Correctly handle KeywordOrStarred when parsing arguments in the parser (GH-22077).
  Grammar/python.gram
  Parser/pegen/parse.c
  Parser/pegen/pegen.c
  Parser/pegen/pegen.h
Labels: CLA signed, awaiting core review, skip news

#22080 [3.9] Fix 'gather' rules in the python parser generator (GH-22021)
  Lib/test/test_peg_generator/test_pegen.py
  Tools/peg_generator/pegen/python_generator.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#22075 [doc] Update documentation on logging optimization. (GH-22075)
  Doc/howto/logging.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#22034 [3.9] bpo-39010: Fix errors logged on proactor loop restart (GH-22017)
  Lib/asyncio/proactor_events.py
  Lib/asyncio/windows_events.py
  Lib/test/test_asyncio/test_proactor_events.py
  Lib/test/test_asyncio/test_windows_events.py
  Misc/NEWS.d/next/Library/2020-08-30-10-24-26.bpo-39010._mzXJW.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#22035 [3.8] bpo-39010: Fix errors logged on proactor loop restart (GH-22017)
  Lib/asyncio/proactor_events.py
  Lib/asyncio/windows_events.py
  Lib/test/test_asyncio/test_proactor_events.py
  Lib/test/test_asyncio/test_windows_events.py
  Misc/NEWS.d/next/Library/2020-08-30-10-24-26.bpo-39010._mzXJW.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#22072 [3.8] bpo-41696: Fix handling of debug mode in asyncio.run (GH-22069)
  Lib/asyncio/runners.py
  Lib/test/test_asyncio/test_runners.py
  Misc/NEWS.d/next/Library/2020-09-03-01-35-32.bpo-41696.zkYGre.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#22071 [3.9] bpo-41696: Fix handling of debug mode in asyncio.run (GH-22069)
  Lib/asyncio/runners.py
  Lib/test/test_asyncio/test_runners.py
  Misc/NEWS.d/next/Library/2020-09-03-01-35-32.bpo-41696.zkYGre.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#22083 [3.8] bpo-39010: Improve test shutdown (GH-22066)
  Lib/test/test_asyncio/test_windows_events.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#22082 [3.9] bpo-39010: Improve test shutdown (GH-22066)
  Lib/test/test_asyncio/test_windows_events.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#21946 [3.5] bpo-39603: Prevent header injection in http methods (GH-18485)
  Lib/http/client.py
  Lib/test/test_httplib.py
  Misc/NEWS.d/next/Security/2020-02-12-14-17-39.bpo-39603.Gt3RSg.rst
Labels: CLA signed, awaiting merge

#22081 bpo-41700: Skip test if the locale is not supported
  Lib/test/test_c_locale_coercion.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news

#22085 [3.9] bpo-41700: Skip test if the locale is not supported (GH-22081)
  Lib/test/test_c_locale_coercion.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22086 [3.8] bpo-41700: Skip test if the locale is not supported (GH-22081)
  Lib/test/test_c_locale_coercion.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22087 bpo-41713: _signal doesn't use multi-phase init
  Misc/NEWS.d/next/Core and Builtins/2020-09-01-17-07-20.bpo-1635741.7wSuCc.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting core review

#21999 bpo-41638: Improve ProgrammingError message for absent parameter.
  Misc/NEWS.d/next/Library/2020-08-29-16-45-12.bpo-41638.iZfW5N.rst
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting core review, type-enhancement

#22025 bpo-40486: Specify what happens if directory content change diring iteration
  Doc/library/glob.rst
  Doc/library/os.rst
  Doc/library/pathlib.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22096 bpo-41721 Add xlc options
  configure
  configure.ac
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news

#22095 bpo-38585: Remove references to defusedexpat
  Doc/library/xml.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#22097 [3.9] bpo-41721: Add xlc options (GH-22096)
  configure
  configure.ac
Labels: CLA signed, awaiting review, skip news

#22100 [3.9] bpo-38585: Remove references to defusedexpat (GH-22095)
  Doc/library/xml.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22099 [3.8] bpo-38585: Remove references to defusedexpat (GH-22095)
  Doc/library/xml.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22076 [3.9] [doc] Fix a typo in the graphlib docs (GH-22030)
  Doc/library/graphlib.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21990 [3.8] Fix error in argparse documentation example (GH-17399)
  Doc/library/argparse.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21992 [3.9] Fix error in argparse documentation example (GH-17399)
  Doc/library/argparse.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22093 [3.9] bpo-40486: Specify what happens if directory content change diring iteration (GH-22025)
  Doc/library/glob.rst
  Doc/library/os.rst
  Doc/library/pathlib.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#22010 [3.8] Improve asyncio-dev 'Concurrency and Multithreading' docs (GH-20882)
  Doc/library/asyncio-dev.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22009 [3.9] Improve asyncio-dev 'Concurrency and Multithreading' docs (GH-20882)
  Doc/library/asyncio-dev.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21984 [3.9] bpo-38787: Clarify docs for PyType_GetModule and warn against common mistake (GH-20215)
  Doc/c-api/type.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#22104 [3.9] Fix typo in message from assert statement (GH-21283)
  Lib/multiprocessing/synchronize.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#22103 [3.9] closes bpo-41533: Fix a potential memory leak when allocating a stack (GH-21847)
  Misc/NEWS.d/next/Core and Builtins/2020-08-12-20-29-57.bpo-41533.4pcVAc.rst
  Python/modsupport.c
Labels: CLA signed, awaiting merge

#22106 [3.9] bpo-29590: fix stack trace for gen.throw() with yield from (GH-19896)
  Lib/test/test_generators.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-03-22-26-00.bpo-29590.aRz3l7.rst
  Objects/genobject.c
Labels: CLA signed, awaiting merge

#22108 [3.9] On path with known exact float, extract the double with the fast macro. (GH-21072)
  Modules/mathmodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news, type-performance

#22107 [3.9] bpo-41531: Fix compilation of dict literals with more than 0xFFFF elements (GH-21850)
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-12-19-32-15.bpo-41531.WgPzjT.rst
  Python/compile.c
Labels: CLA signed, awaiting merge

#22101 [3.9] Remove unnecessary grammar decorations and change header (GH-20819)
  Grammar/python.gram
Labels: CLA signed, awaiting merge, skip issue, skip news

#22098 bpo-41627: Distinguish 32 and 64-bit user site packages on Windows
  Lib/site.py
  Lib/sysconfig.py
  Misc/NEWS.d/next/Windows/2020-09-04-21-35-28.bpo-41627.sx2KN1.rst
Labels: CLA signed, OS-windows, awaiting core review

#22109 [3.9] bpo-41218: Improve the test cases for test_compile_top_level_await_no_coro (GH-21363)
  Lib/test/test_builtin.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#22102 [3.8] bpo-41654: Explicitly cast PyExc_MemoryError to PyTypeObject to avoid warning
  Objects/exceptions.c
Labels: CLA signed, awaiting core review, skip news

#22040 bpo-41687: Fix sendfile implementation to work with Solaris
  Lib/test/test_asyncio/test_sendfile.py
  Misc/NEWS.d/next/Library/2020-09-01-15-57-51.bpo-41687.m1b1KA.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#19581 bpo-40318: Migrate to SQLite3 trace v2 API
  Misc/NEWS.d/next/Library/2020-04-18-14-16-02.bpo-40318.K2UdRx.rst
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge

#22113 Fix documented Python version for venv --upgrade-deps
  Doc/using/venv-create.inc
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#22114 [doc] Fix padding in some typing definitions
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22115 [3.9] [doc] Fix padding in some typing definitions (GH-22114)
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22110 bpo-41723: Fix an error in the py_compile documentation
  Doc/library/py_compile.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#22117 [3.8] closes bpo-41723: Fix an error in the py_compile documentation. (GH-22110)
  Doc/library/py_compile.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22118 [3.9] closes bpo-41723: Fix an error in the py_compile documentation (GH-22110).
  Doc/library/py_compile.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#21818 bpo-1635741: Port hashlib modules to multiphase init (PEP 489)
  Misc/NEWS.d/next/Core and Builtins/2020-08-10-16-11-32.bpo-1635741.O0d3ym.rst
  Modules/clinic/md5module.c.h
  Modules/clinic/sha1module.c.h
  Modules/clinic/sha512module.c.h
  Modules/md5module.c
  Modules/sha1module.c
  Modules/sha512module.c
Labels: CLA signed, awaiting merge

#22123 bpo-41513: Expand comments
  Modules/mathmodule.c
Labels: CLA signed, awaiting core review, skip news, type-documentation

#22125 [doc] Add link to Generic in typing
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#21995 bpo-1635741 port zlib module to multi-phase init
  Misc/NEWS.d/next/Core and Builtins/2020-08-28-20-54-04.bpo-1635741.7ijlcI.rst
  Modules/clinic/zlibmodule.c.h
  Modules/zlibmodule.c
Labels: CLA signed, awaiting review

#22050 bpo-1635741: port opcode module to multi-phase init (PEP 489)
  Misc/NEWS.d/next/Core and Builtins/2020-09-01-17-06-02.bpo-1635741.5jZymK.rst
  Modules/_opcode.c
Labels: CLA signed, awaiting review

#22051 bpo-1635741: - port overlapped to multi-phase
  Misc/NEWS.d/next/Core and Builtins/2020-09-01-17-22-35.bpo-1635741.CnRME3.rst
  Modules/overlapped.c
Labels: CLA signed, awaiting merge

#22133 [3.9] bpo-41401: Fix test_fspath_support in test_io. (GH-21640)
  Lib/test/test_io.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-tests

#21986 bpo-1635741 port _curses_panel to multi-phase init (PEP 489)
  Misc/NEWS.d/next/Core and Builtins/2020-09-01-17-08-07.bpo-1635741.X9CZgo.rst
  Modules/_curses_panel.c
  Modules/clinic/_curses_panel.c.h
Labels: CLA signed, awaiting merge

#22135 [3.8] bpo-41401: Fix test_fspath_support in test_io. (GH-21640) (GH-22133)
  Lib/test/test_io.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#22092 bpo-41720: Add "return NotImplemented" in turtle.Vec2D.__rmul__().
  Lib/test/test_turtle.py
  Lib/turtle.py
  Misc/NEWS.d/next/Library/2020-09-04-20-45-38.bpo-41720.PW9MzZ.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-bugfix

#22138 [3.8] bpo-41720: Add "return NotImplemented" in turtle.Vec2D.__rmul__(). (GH-22092)
  Lib/test/test_turtle.py
  Lib/turtle.py
  Misc/NEWS.d/next/Library/2020-09-04-20-45-38.bpo-41720.PW9MzZ.rst
Labels: CLA signed, awaiting merge, type-bugfix

#22137 [3.9] bpo-41720: Add "return NotImplemented" in turtle.Vec2D.__rmul__(). (GH-22092)
  Lib/test/test_turtle.py
  Lib/turtle.py
  Misc/NEWS.d/next/Library/2020-09-04-20-45-38.bpo-41720.PW9MzZ.rst
Labels: CLA signed, awaiting merge, type-bugfix

#21511 bpo-41316: Make tarfile follow specs for FNAME
  Lib/tarfile.py
  Lib/test/test_tarfile.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2020-07-28-12-08-58.bpo-41316.bSCbK4.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#20909 bpo-40744: Drop support for SQLite pre 3.7.3
  Doc/library/sqlite3.rst
  Doc/whatsnew/3.10.rst
  Lib/sqlite3/test/backup.py
  Lib/sqlite3/test/dbapi.py
  Lib/sqlite3/test/hooks.py
  Lib/sqlite3/test/regression.py
  Lib/sqlite3/test/transactions.py
  Lib/sqlite3/test/types.py
  Misc/NEWS.d/next/Library/2020-05-30-08-10-23.bpo-40744.jKURVV.rst
  Modules/_sqlite/connection.c
  Modules/_sqlite/module.c
  setup.py
Labels: CLA signed, awaiting merge

#22119 bpo-41732: add iterator to memoryview
  Misc/NEWS.d/next/Library/2020-09-06-20-27-10.bpo-41732.1SKv26.rst
  Objects/memoryobject.c
Labels: CLA not signed, awaiting merge

#22139 bpo-1635741: Port the termios to multi-phase init (PEP 489)
  Misc/NEWS.d/next/Core and Builtins/2020-09-07-11-35-02.bpo-1635741.rvIexb.rst
  Modules/termios.c
Labels: CLA signed, awaiting review

#22134 bpo-1635741: sha256 heap types
  Misc/NEWS.d/next/Core and Builtins/2020-09-07-09-45-47.bpo-1635741.QuDIut.rst
  Modules/clinic/sha256module.c.h
  Modules/sha256module.c
Labels: CLA signed, awaiting merge

#22148 bpo-1635741: Port _string module to multi-phase init
  Misc/NEWS.d/next/Library/2020-09-08-13-51-16.bpo-1635741.wkPeoT.rst
  Objects/unicodeobject.c
Labels: CLA signed, awaiting core review

#22149 bpo-1635741: Port mashal module to multi-phase init
  Misc/NEWS.d/next/Library/2020-09-08-13-55-34.bpo-1635741.56MLP-.rst
  Python/marshal.c
Labels: CLA signed, awaiting core review

#22151 bpo-41703: Fix incorrect bpo number in change notes.
  Misc/NEWS.d/3.9.0a2.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#22142 bpo-38762: Extend logging.test_multiprocessing to cover missing cases.
  Lib/test/test_logging.py
Labels: CLA signed, awaiting review, skip news, type-tests

#22121 Fix typo in typing.py
  Lib/typing.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#22158 [3.8] Fix typo in typing.py (GH-22121)
  Lib/typing.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#22156 [3.9] Fix typo in typing.py (GH-22121)
  Lib/typing.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#22152 [doc] Fix padding in timeit
  Doc/library/timeit.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22160 [3.9] [doc] Fix padding in timeit (GH-22152)
  Doc/library/timeit.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22159 [3.8] [doc] Fix padding in timeit (GH-22152)
  Doc/library/timeit.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#21836 bpo-41525: Make the Python program help ASCII-only
  Lib/test/test_cmd_line.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-12-07-35-07.bpo-41525.d9q3XL.rst
  Misc/python.man
  Python/initconfig.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#22163 [3.8] bpo-41525: Make the Python program help ASCII-only (GH-21836)
  Lib/test/test_cmd_line.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-12-07-35-07.bpo-41525.d9q3XL.rst
  Misc/python.man
  Python/initconfig.c
Labels: CLA signed, awaiting merge, type-bugfix

#22162 [3.9] bpo-41525: Make the Python program help ASCII-only (GH-21836)
  Lib/test/test_cmd_line.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-12-07-35-07.bpo-41525.d9q3XL.rst
  Misc/python.man
  Python/initconfig.c
Labels: CLA signed, awaiting merge, type-bugfix

#22164 bpo-1635741: port scproxy to multi-phase init
  Misc/NEWS.d/next/Core and Builtins/2020-09-08-20-39-43.bpo-1635741.jiXmyT.rst
  Modules/_scproxy.c
Labels: CLA signed, awaiting merge

#22112 bpo-41726: Update the refcounts info of PyType_FromModuleAndSpec in refcounts.dat
  Doc/data/refcounts.dat
  Misc/NEWS.d/next/Documentation/2020-09-08-16-57-09.bpo-41726.g0UXrn.rst
Labels: CLA signed, awaiting review

#22150 Fix compiler warnings in init_dump_ascii_wstr()
  Python/initconfig.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#22167 [doc] Add minor clarification in logging documentation.
  Doc/library/logging.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#22169 [3.8] Fix compiler warnings in init_dump_ascii_wstr() (GH-22150)
  Python/initconfig.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#22168 [3.9] Fix compiler warnings in init_dump_ascii_wstr() (GH-22150)
  Python/initconfig.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#22171 [3.8] Fixes dead links to Django's logging config docs (GH-20823)
  Doc/howto/logging-cookbook.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#22170 [3.9] Fixes dead links to Django's logging config docs (GH-20823)
  Doc/howto/logging-cookbook.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#22174 [3.9] bpo-41703: Fix incorrect bpo number in change notes. (GH-22151)
  Misc/NEWS.d/3.9.0a2.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#22172 [3.9] bpo-41688: Document bug in **= dispatching in the language data…
  Doc/reference/datamodel.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, skip news, type-documentation

#22175 [3.8] [3.9] bpo-41688: Document bug in **= dispatching in the language data… (GH-22172)
  Doc/reference/datamodel.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#22128 bpo-41687: Fix error handling in Solaris sendfile implementation
  Modules/posixmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#21515 bpo-41428: Implementation for PEP 604
  Include/internal/pycore_unionobject.h
  Lib/test/test_isinstance.py
  Lib/test/test_types.py
  Lib/test/test_typing.py
  Lib/types.py
  Lib/typing.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2020-07-28-22-43-27.bpo-41428.FM6xsI.rst
  Objects/abstract.c
  Objects/typeobject.c
  Objects/unionobject.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: CLA signed, awaiting merge

#22007 [doc] Fix markup in IDLE
  Doc/library/idle.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22179 [3.9] Add missing colon to IDLE doc markup (GH-22007)
  Doc/library/idle.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22180 [3.8] Add missing colon to IDLE doc markup (GH-22007)
  Doc/library/idle.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22181 Update idlelib/help.html to current IDLE doc
  Lib/idlelib/help.html
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22183 [3.8] Update idlelib/help.html to current IDLE doc (GH-22181)
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22182 [3.9] Update idlelib/help.html to current IDLE doc (GH-22181)
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22006 [doc] Remove superfluous comment about equal in f-strings
  Doc/reference/lexical_analysis.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22185 [3.8] [doc] Remove superfluous comment about equal in f-strings (GH-22006)
  Doc/reference/lexical_analysis.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22184 [3.9] [doc] Remove superfluous comment about equal in f-strings (GH-22006)
  Doc/reference/lexical_analysis.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22173 [doc] Documentation typo @ logging.Formatter
  Doc/library/logging.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#22165 bpo-1635741 port cmath to multi-phase init (pep 489)
  Misc/NEWS.d/next/Core and Builtins/2020-09-08-21-58-47.bpo-1635741.vdjSLH.rst
  Modules/cmathmodule.c
Labels: CLA signed, awaiting merge

#22188 bpo-37149: Change Shipman tkinter link from archive.org to TkDocs
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Documentation/2020-09-10-07-48-02.bpo-37149.VD0rCv.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-documentation

#22192 [3.9] bpo-37149: Change Shipman tkinter link from archive.org to TkDocs (GH-22188)
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Documentation/2020-09-10-07-48-02.bpo-37149.VD0rCv.rst
Labels: CLA signed, awaiting merge, type-documentation

#22193 [3.8] bpo-37149: Change Shipman tkinter link from archive.org to TkDocs (GH-22188)
  Doc/library/tkinter.rst
  Misc/NEWS.d/next/Documentation/2020-09-10-07-48-02.bpo-37149.VD0rCv.rst
Labels: CLA signed, awaiting merge, type-documentation

#22194 Doc: Fix alphabetical ordering of removeprefix/suffix.
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news, type-documentation

#22195 [3.9] Doc: Fix alphabetical ordering of removeprefix/suffix. (GH-22194)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22201 [doc] struct: update note about network byte order form to be more helpful
  Doc/library/struct.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22203 [3.8] [doc] struct: update note about network byte order form to be more helpful (GH-22201)
  Doc/library/struct.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22202 [3.9] [doc] struct: update note about network byte order form to be more helpful (GH-22201)
  Doc/library/struct.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#22146 bpo-41729: Fix test_winconsole failures (3) and hang.
  PC/_testconsole.c
Labels: CLA signed, DO-NOT-MERGE, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news
