Repository python/cpython, pull requests merged in 2020-01, with the labels that each got.

#17777 bpo-39176: Fix wrong term 'named assignment'
  Lib/test/test_named_expressions.py
  Lib/test/test_syntax.py
  Python/ast.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip news

#17778 [3.8] bpo-39176: Improve error message for 'named assignment' (GH-17777)
  Lib/test/test_named_expressions.py
  Lib/test/test_syntax.py
  Python/ast.c
Labels: CLA signed, awaiting review, skip news

#17776 bpo-37032: Document CodeType.replace (new in python 3.8)
  Doc/library/types.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip news, type-documentation

#17779 [3.8] bpo-37032: Document CodeType.replace (GH-17776)
  Doc/library/types.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
Labels: CLA signed, awaiting merge, skip news, type-documentation

#17773 bpo-39142: Avoid converting namedtuple instances to ConvertingTuple.
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2019-12-31-19-27-23.bpo-39142.oqU5iD.rst
Labels: CLA signed, awaiting core review, type-bugfix

#17785 [3.8] bpo-39142: Avoid converting namedtuple instances to ConvertingTuple. (GH-17773)
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2019-12-31-19-27-23.bpo-39142.oqU5iD.rst
Labels: CLA signed, awaiting review, type-bugfix

#17786 [3.7] bpo-39142: Avoid converting namedtuple instances to ConvertingTuple. (GH-17773)
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2019-12-31-19-27-23.bpo-39142.oqU5iD.rst
Labels: CLA signed, awaiting review, type-bugfix

#17646 bpo-13601: always use line-buffering for sys.stderr
  Doc/library/sys.rst
  Lib/test/test_cmd_line.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2019-12-17-22-32-11.bpo-13601.vNP4LC.rst
  Python/pylifecycle.c
Labels: CLA signed, awaiting merge

#17787 bpo-39183: Fix formatting in library/ensurepip
  Doc/library/ensurepip.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#17789 [3.7] bpo-39183: Fix formatting in library/ensurepip (GH-17787)
  Doc/library/ensurepip.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#17788 [3.8] bpo-39183: Fix formatting in library/ensurepip (GH-17787)
  Doc/library/ensurepip.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#17769 bpo-39114: Fix tracing of except handlers with name binding
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2019-12-31-18-25-45.bpo-39114.WG9alt.rst
  Python/ceval.c
Labels: CLA signed, awaiting core review

#17792 bpo-39186 Update windows installer instructions for git
  Tools/msi/README.txt
Labels: CLA signed, awaiting merge, skip news

#17798 bpo-38870: Throw ValueError on invalid yield from usage
  Lib/ast.py
  Lib/test/test_unparse.py
Labels: CLA signed, awaiting merge, skip news

#17801 Bring Python into the next decade.
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, skip issue, skip news

#17805 [2.7] Bring Python into the next decade. (GH-17801).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Python/getcopyright.c
  README
Labels: CLA signed, awaiting core review, skip issue, skip news

#17804 [3.6] Bring Python into the next decade. (GH-17801).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting core review, skip issue, skip news

#17802 [3.8] Bring Python into the next decade. (GH-17801)
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#17806 Update copyright year in macOS installer license copy
  Mac/BuildScript/resources/License.rtf
Labels: CLA signed, OS-mac, awaiting core review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, skip issue, skip news

#17803 [3.7] Bring Python into the next decade. (GH-17801).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#17809 [2.7] Update copyright year in macOS installer license copy (GH-17806)
  Mac/BuildScript/resources/License.rtf
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#17807 [3.7] Update copyright year in macOS installer license copy (GH-17806)
  Mac/BuildScript/resources/License.rtf
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#17808 [3.8] Update copyright year in macOS installer license copy (GH-17806)
  Mac/BuildScript/resources/License.rtf
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#17810 [3.6] Update copyright year in macOS installer license copy (GH-17806)
  Mac/BuildScript/resources/License.rtf
Labels: CLA signed, awaiting core review, skip issue, skip news

#17742 bpo-39158: ast.literal_eval() doesn't support empty sets
  Doc/library/ast.rst
  Lib/ast.py
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2019-12-29-15-44-38.bpo-39158.cxVoOR.rst
Labels: CLA signed, awaiting core review

#17156 Added link to zlib v1.1.3 vulnerability
  Doc/library/zlib.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#16857 bpo-38532: Add missing decrefs in PyCFuncPtr_FromDll()
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#17811 [3.8] bpo-38532: Add missing decrefs in PyCFuncPtr_FromDll() (GH-16857)
  Modules/_ctypes/_ctypes.c
Labels: :robot: automerge, CLA signed, awaiting review, skip news, type-bugfix

#17774 [2.7] bpo-27973 - urlretrive fails on second ftp transfer.
  Lib/test/test_urllibnet.py
Labels: CLA signed, OS-windows, awaiting merge, skip news, type-tests

#17796 bpo-39191: Don't spawn a task before failing with already running loop
  Lib/asyncio/base_events.py
  Misc/NEWS.d/next/Library/2020-01-02-17-28-03.bpo-39191.ur_scy.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8

#17820 [3.8] bpo-39191: Don't spawn a task before failing (GH-17796).
  Lib/asyncio/base_events.py
  Misc/NEWS.d/next/Library/2020-01-02-17-28-03.bpo-39191.ur_scy.rst
Labels: CLA signed, awaiting core review

#17821 [3.7] bpo-39191: Don't spawn a task before failing (GH-17796).
  Lib/asyncio/base_events.py
  Misc/NEWS.d/next/Library/2020-01-02-17-28-03.bpo-39191.ur_scy.rst
Labels: CLA signed, awaiting core review

#13142 bpo-28367: Add additional baud rates for termios
  Misc/NEWS.d/next/Library/2019-05-06-22-38-47.bpo-28367.2AKen5.rst
  Modules/termios.c
Labels: CLA signed, awaiting review

#17826 bpo-39215: Fix SystemError when nested function has annotation on positional-only argument
  Lib/test/test_positional_only_arg.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-04-17-25-34.bpo-39215.xiqiIz.rst
  Python/symtable.c
Labels: CLA signed, awaiting merge, needs backport to 3.8

#17827 [3.8] bpo-39215: Fix SystemError when nested function has annotation on positional-only argument (GH-17826)
  Lib/test/test_positional_only_arg.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-04-17-25-34.bpo-39215.xiqiIz.rst
  Python/symtable.c
Labels: CLA signed, awaiting merge

#17619 bpo-39057: Fix urllib.request.proxy_bypass_environment().
  Lib/test/test_urllib.py
  Lib/urllib/parse.py
  Lib/urllib/request.py
  Misc/NEWS.d/next/Library/2019-12-15-21-47-54.bpo-39057.FOxn-w.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-bugfix

#17618 bpo-39056: Fix handling invalid warning category in the -W option.
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2019-12-15-21-05-16.bpo-39056.nEfUM9.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-bugfix, type-performance

#17616 bpo-39055: Reject a trailing \n in base64.b64decode() with validate=True.
  Lib/base64.py
  Lib/test/test_base64.py
  Misc/NEWS.d/next/Library/2019-12-15-19-23-23.bpo-39055.FmN3un.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, type-bugfix

#17830 [3.7] bpo-39057: Fix urllib.request.proxy_bypass_environment(). (GH-17619)
  Lib/test/test_urllib.py
  Lib/urllib/parse.py
  Lib/urllib/request.py
  Misc/NEWS.d/next/Library/2019-12-15-21-47-54.bpo-39057.FOxn-w.rst
Labels: CLA signed, awaiting merge, type-bugfix

#17829 [3.8] bpo-39057: Fix urllib.request.proxy_bypass_environment(). (GH-17619)
  Lib/test/test_urllib.py
  Lib/urllib/parse.py
  Lib/urllib/request.py
  Misc/NEWS.d/next/Library/2019-12-15-21-47-54.bpo-39057.FOxn-w.rst
Labels: CLA signed, awaiting merge, type-bugfix

#17834 [3.7] bpo-39055: Reject a trailing \n in base64.b64decode() with validate=True. (GH-17616)
  Lib/base64.py
  Lib/test/test_base64.py
  Misc/NEWS.d/next/Library/2019-12-15-19-23-23.bpo-39055.FmN3un.rst
Labels: CLA signed, awaiting merge, type-bugfix

#17831 [3.8] bpo-39056: Fix handling invalid warning category in the -W option. (GH-17618)
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2019-12-15-21-05-16.bpo-39056.nEfUM9.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-performance

#17832 [3.7] bpo-39056: Fix handling invalid warning category in the -W option. (GH-17618)
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2019-12-15-21-05-16.bpo-39056.nEfUM9.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-performance

#17833 [3.8] bpo-39055: Reject a trailing \n in base64.b64decode() with validate=True. (GH-17616)
  Lib/base64.py
  Lib/test/test_base64.py
  Misc/NEWS.d/next/Library/2019-12-15-19-23-23.bpo-39055.FmN3un.rst
Labels: CLA signed, awaiting merge, type-bugfix

#17815 bpo-39152: add missing ttk.Scale.configure return value
  Lib/tkinter/test/widget_tests.py
  Lib/tkinter/ttk.py
  Misc/NEWS.d/next/Library/2020-01-03-18-02-50.bpo-39152.JgPjCC.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-bugfix

#17839 [3.7] bpo-39152: add missing ttk.Scale.configure return value (GH-17815)
  Lib/tkinter/test/widget_tests.py
  Lib/tkinter/ttk.py
  Misc/NEWS.d/next/Library/2020-01-03-18-02-50.bpo-39152.JgPjCC.rst
Labels: CLA signed, awaiting merge, type-bugfix

#17837 bpo-39216: Fix constant folding optimization for positional only arguments
  Lib/test/test_positional_only_arg.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-05-06-55-52.bpo-39216.74jLh9.rst
  Python/ast_opt.c
Labels: CLA signed, awaiting merge, needs backport to 3.8

#17840 [3.8] bpo-39152: add missing ttk.Scale.configure return value (GH-17815)
  Lib/tkinter/test/widget_tests.py
  Lib/tkinter/ttk.py
  Misc/NEWS.d/next/Library/2020-01-03-18-02-50.bpo-39152.JgPjCC.rst
Labels: CLA signed, awaiting merge, type-bugfix

#17841 [3.8] bpo-39216: Fix constant folding optimization for positional only arguments (GH-17837)
  Lib/test/test_positional_only_arg.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-05-06-55-52.bpo-39216.74jLh9.rst
  Python/ast_opt.c
Labels: CLA signed, awaiting merge

#17813 bpo-39200: Correct the error message for range() empty constructor
  Lib/test/test_range.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-03-14-50-14.bpo-39200.Ip2_iI.rst
  Objects/rangeobject.c
Labels: CLA signed, awaiting merge

#17842 Organise and clean test_positional_only_arg and add more tests
  Lib/test/test_positional_only_arg.py
Labels: CLA signed, awaiting core review, skip issue, skip news, type-tests

#17781 replace links in howto/pyporting.rst with sphinx references
  Doc/howto/pyporting.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#17845 [3.7] Replace links in howto/pyporting.rst with sphinx references (GH-17781)
  Doc/howto/pyporting.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#17844 [3.8] Replace links in howto/pyporting.rst with sphinx references (GH-17781)
  Doc/howto/pyporting.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#16477 Doc: Fixed the parameter list of object. _rpow_ in the document
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#17847 [3.7] Fix the parameter list of object. _rpow_ (GH-GH-16477)
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#17846 [3.8] Fix the parameter list of object. _rpow_ (GH-GH-16477)
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#17694 bpo-39130: Dict reversed was added in v3.8 so should say in the doc as well
  Doc/library/stdtypes.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, skip news, type-documentation

#17848 [3.8] bpo-39130: Dict reversed was added in v3.8 so should say in the doc as well (GH-17694)
  Doc/library/stdtypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#17165 minor formatting improvements and fixes to idle.rst
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip issue, skip news

#17849 [3.8] Minor formatting improvements and fixes to idle.rst (GH-17165)
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, skip issue, skip news

#17851 bpo-38907: In http.server script, restore binding to IPv4 on Windows.
  Lib/http/server.py
  Misc/NEWS.d/next/Library/2020-01-06-02-14-38.bpo-38907.F1RkCR.rst
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8

#17859 [3.7] Minor formatting improvements and fixes to idle.rst (GH-17165)
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, skip issue, skip news

#17852 clinic: Fix clinic anti-pattern
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip issue, skip news

#17854 [3.8] bpo-38907: In http.server script, restore binding to IPv4 on Windows. (GH-17851)
  Lib/http/server.py
  Misc/NEWS.d/next/Library/2020-01-06-02-14-38.bpo-38907.F1RkCR.rst
Labels: CLA signed, awaiting review

#17864 bpo-38907: Suppress any exception when attempting to set V6ONLY.
  Lib/http/server.py
Labels: CLA signed, needs backport to 3.8, skip news

#17865 [3.8] bpo-38907: Suppress any exception when attempting to set V6ONLY. (GH-17864)
  Lib/http/server.py
Labels: CLA signed, awaiting review, skip news

#17692 Fix link to bpo issue in Changelog
  Misc/NEWS.d/3.9.0a2.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#17860 bpo-39209: Manage correctly multi-line tokens in interactive mode
  Lib/test/test_repl.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-06-10-29-16.bpo-39209.QHAONe.rst
  Parser/tokenizer.c
Labels: CLA signed, awaiting core review, needs backport to 3.8

#17867 [3.8] bpo-39209: Manage correctly multi-line tokens in interactive mode (GH-17860)
  Lib/test/test_repl.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-06-10-29-16.bpo-39209.QHAONe.rst
  Parser/tokenizer.c
Labels: CLA signed, awaiting merge

#17868 [3.8] bpo-39041: Add GitHub Actions support (GH-17594)
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/doc.yml
  .github/workflows/posix-deps-apt.sh
  Doc/make.bat
Labels: CLA signed, awaiting review, skip news

#17869 [3.7] bpo-39041: Add GitHub Actions support (GH-17594)
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/doc.yml
  .github/workflows/posix-deps-apt.sh
  Doc/make.bat
Labels: CLA signed, awaiting review, skip news

#17818 bpo-29778: Fix incorrect NULL check
  Python/pathconfig.c
Labels: CLA signed, OS-windows, awaiting review, needs backport to 3.8, skip news, type-bugfix

#17871 [3.8] bpo-29778: Fix incorrect NULL check in _PyPathConfig_InitDLLPath() (GH-17818)
  Python/pathconfig.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#17872 bpo-39234: Doc: `enum.auto()` incrementation value not specified.
  Doc/library/enum.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#17873 bpo-39041: Fix coverage upload command for GitHub Actions
  .github/workflows/coverage.yml
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news

#17879 [3.8] bpo-39041: Fix coverage upload command for GitHub Actions (GH-17873)
  .github/workflows/coverage.yml
Labels: CLA signed, awaiting merge, skip news

#17880 [3.7] bpo-39041: Fix coverage upload command for GitHub Actions (GH-17873)
  .github/workflows/coverage.yml
Labels: CLA signed, awaiting merge, skip news

#17878 bpo-39234: `enum.auto()` default initial value as 1
  Doc/library/enum.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#17885 Doc: Change Python 2 status to EOL.
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting core review, needs backport to 2.7, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-documentation

#17888 [2.7] Doc: Change Python 2 status to EOL. (GH-17885)
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#17886 [3.7] Doc: Change Python 2 status to EOL. (GH-17885)
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#17889 [3.8] Doc: Change Python 2 status to EOL. (GH-17885)
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#17858 bpo-38623: Doc: Add section for site module CLI.
  Doc/library/site.rst
Labels: CLA signed, needs backport to 3.7, needs backport to 3.8, skip news, type-documentation

#17891 [3.7] bpo-38623: Doc: Add section for site module CLI. (GH-17858)
  Doc/library/site.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#17890 [3.8] bpo-38623: Doc: Add section for site module CLI. (GH-17858)
  Doc/library/site.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#17863 bpo-39191: Fix RuntimeWarning in asyncio test
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_events.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, skip news, type-tests

#17882 bpo-39239: epoll.unregister() no longer ignores EBADF
  Doc/library/select.rst
  Doc/whatsnew/3.9.rst
  Lib/test/test_epoll.py
  Misc/NEWS.d/next/Library/2020-01-07-01-02-44.bpo-39239.r7vecs.rst
  Modules/selectmodule.c
Labels: CLA signed, awaiting merge

#17894 [3.8] bpo-39191: Fix RuntimeWarning in asyncio test (GH-17863)
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_events.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#17689 bpo-39198: Ensure logging global lock is released on exception in isEnabledFor
  Lib/logging/__init__.py
  Misc/NEWS.d/next/Library/2020-01-02-20-21-03.bpo-39198.nzwGyG.rst
Labels: CLA signed, awaiting merge

#17897 [3.8] bpo-39198: Ensure logging global lock is released on exception in isEnabledFor (GH-17689)
  Lib/logging/__init__.py
  Misc/NEWS.d/next/Library/2020-01-02-20-21-03.bpo-39198.nzwGyG.rst
Labels: CLA signed, awaiting review

#17898 [3.7] bpo-39198: Ensure logging global lock is released on exception in isEnabledFor (GH-17689)
  Lib/logging/__init__.py
  Misc/NEWS.d/next/Library/2020-01-02-20-21-03.bpo-39198.nzwGyG.rst
Labels: CLA signed, awaiting review

#17203 bpo-38615: Add timeout parameter for IMAP4 and IMAP4_SSL constructor
  Doc/library/imaplib.rst
  Doc/whatsnew/3.9.rst
  Lib/imaplib.py
  Lib/test/test_imaplib.py
  Misc/NEWS.d/next/Library/2019-11-17-17-32-35.bpo-38615.OVyaNX.rst
Labels: CLA signed, awaiting change review

#17780 bpo-38871: Fix lib2to3 to be able to use in edge cases of filter
  Lib/lib2to3/fixes/fix_filter.py
  Lib/lib2to3/tests/test_fixers.py
  Misc/NEWS.d/next/Library/2020-01-01-18-44-52.bpo-38871.3EEOLg.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8

#17900 [3.7] bpo-38871: Fix lib2to3 for filter-based statements that contain lambda (GH-17780)
  Lib/lib2to3/fixes/fix_filter.py
  Lib/lib2to3/tests/test_fixers.py
  Misc/NEWS.d/next/Library/2020-01-01-18-44-52.bpo-38871.3EEOLg.rst
Labels: CLA signed, awaiting merge

#17899 [3.8] bpo-38871: Fix lib2to3 for filter-based statements that contain lambda (GH-17780)
  Lib/lib2to3/fixes/fix_filter.py
  Lib/lib2to3/tests/test_fixers.py
  Misc/NEWS.d/next/Library/2020-01-01-18-44-52.bpo-38871.3EEOLg.rst
Labels: CLA signed, awaiting merge

#17887 [3.6] Doc: Change Python 2 status to EOL. (GH-17885)
  Doc/tools/templates/indexsidebar.html
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#17877 bpo-39237: Remove redundant call to round from delta_new
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting review, skip news

#17874 bpo-39233: Update positional-only section in the glossary
  Doc/glossary.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, skip news, type-documentation

#17903 bpo-39242: Updated the Gmane domain into news.gmane.io
  Doc/library/nntplib.rst
  Lib/nntplib.py
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Library/2020-01-08-23-25-27.bpo-39242.bnL65N.rst
Labels: CLA signed, awaiting review, needs backport to 3.7, needs backport to 3.8

#17905 [3.7] bpo-39242: Updated the Gmane domain into news.gmane.io (GH-17903)
  Doc/library/nntplib.rst
  Lib/nntplib.py
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Library/2020-01-08-23-25-27.bpo-39242.bnL65N.rst
Labels: CLA signed, awaiting merge

#17904 [3.8] bpo-39242: Updated the Gmane domain into news.gmane.io (GH-17903)
  Doc/library/nntplib.rst
  Lib/nntplib.py
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Library/2020-01-08-23-25-27.bpo-39242.bnL65N.rst
Labels: CLA signed, awaiting merge

#17822 bpo-35292: Avoid call mimetypes.init when http.server is imported
  Doc/library/http.server.rst
  Lib/http/server.py
  Misc/NEWS.d/next/Library/2020-01-08-14-39-19.bpo-35292.ihRT1z.rst
Labels: CLA signed, awaiting review

#17870 Py_DECREF: only pass filename if Py_REF_DEBUG is defined
  Include/object.h
Labels: CLA signed, awaiting merge, skip issue, skip news

#17907 bpo-39261: Remove dead assignment from pyinit_config
  Python/pylifecycle.c
Labels: CLA signed, awaiting review, skip news

#17908 bpo-39262: Use specific out-of-memory message in _sharedexception_bind
  Modules/_xxsubinterpretersmodule.c
Labels: CLA signed, awaiting review, needs backport to 3.8, skip news

#17913 [3.8] closes bpo-39262: Use specific out-of-memory message in _sharedexception_bind. (GH-17908)
  Modules/_xxsubinterpretersmodule.c
Labels: CLA signed, awaiting merge, skip news

#17915 bpo-39271: Remove dead assignment from pattern_subx
  Modules/_sre.c
Labels: CLA signed, awaiting merge, skip news

#17916 bpo-39272: Remove dead assignment from _ssl__SSLContext_load_verify_l…
  Modules/_ssl.c
Labels: CLA signed, awaiting merge, skip news

#17914 bpo-39270: Remove dead assignment from config_init_module_search_paths.
  Python/pathconfig.c
Labels: CLA signed, awaiting merge, skip news

#17896 bpo-39161: Document multi-phase init modules under Py_NewInterpreter()
  Doc/c-api/init.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, skip news, type-documentation

#17918 [3.8] bpo-39161: Document multi-phase init modules under Py_NewInterpreter() (GH-17896)
  Doc/c-api/init.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#17909 Add test cases for dataclasses.
  Lib/test/test_dataclasses.py
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, skip issue, skip news, type-tests

#17881 bpo-25172: Reduce scope of crypt import tests
  Lib/test/test_crypt.py
Labels: CLA signed, needs backport to 3.8, skip news, type-tests

#17856 minor: fix typo in test doc, fix flake8 issues
  Lib/test/test_eof.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip issue, skip news, type-tests

#17922 [3.8] bpo-25172: Reduce scope of crypt import tests (GH-17881)
  Lib/test/test_crypt.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#17923 [3.8] Fix typo in test's docstring (GH-17856)
  Lib/test/test_eof.py
Labels: CLA signed, awaiting review, skip issue, skip news, type-tests

#17925 bpo-39235: Fix end location for genexp in call args
  Misc/NEWS.d/next/Core and Builtins/2020-01-09-10-01-18.bpo-39235.RYwjoc.rst
  Python/ast.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, type-bugfix

#17927 [3.8] bpo-39235: Fix end location for genexp in call args (GH-17925)
  Misc/NEWS.d/next/Core and Builtins/2020-01-09-10-01-18.bpo-39235.RYwjoc.rst
  Python/ast.c
Labels: CLA signed, awaiting merge, type-bugfix

#17926 bpo-39235: Check end_lineno and end_col_offset of AST nodes.
  Lib/test/test_ast.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#17800 bpo-39166: Fix trace of last iteration of async for loops
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-02-22-22-03.bpo-39166.Qt-UeD.rst
  Python/ceval.c
Labels: CLA signed, awaiting core review

#17919 [3.8] Add test cases for dataclasses. (GH-17909)
  Lib/test/test_dataclasses.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-tests

#17920 [3.7] Add test cases for dataclasses. (GH-17909)
  Lib/test/test_dataclasses.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-tests

#17912 bpo-39259: poplib.POP3/POP3_SSL now reject timeout = 0
  Doc/library/poplib.rst
  Doc/whatsnew/3.9.rst
  Lib/poplib.py
  Lib/test/test_poplib.py
  Misc/NEWS.d/next/Library/2020-01-09-10-58-58.bpo-39259.RmDgCC.rst
Labels: CLA signed, awaiting change review

#17814 bpo-39200: Correct the error message for min/max builtin function
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2020-01-04-01-14-32.bpo-39200.8Z9DYp.rst
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge, type-bugfix, type-enhancement

#17945 bpo-39292: Add missing syslog facility codes to logging.handlers.SysLogHandler.
  Lib/logging/handlers.py
Labels: CLA signed, awaiting core review, skip news, type-enhancement

#17706 Fix host datatype in addr of socket.create_server example.
  Lib/socket.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, skip issue, skip news

#17948 [3.8] Fix host in address of socket.create_server example. (GH-17706)
  Lib/socket.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#17939 bpo-39259: nntplib.NNTP/NNTP_SSL refactoring
  Lib/nntplib.py
Labels: CLA signed, awaiting changes, skip news

#17947 bpo-39297: Update for importlib_metadata 1.4.
  Lib/importlib/metadata.py
  Misc/NEWS.d/next/Library/2020-01-11-01-15-37.bpo-39297.y98Z6Q.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8

#17952 [3.8] bpo-39297: Update for importlib_metadata 1.4. (GH-17947)
  Lib/importlib/metadata.py
  Misc/NEWS.d/next/Library/2020-01-11-01-15-37.bpo-39297.y98Z6Q.rst
Labels: CLA signed, awaiting review

#17936 bpo-39259: nntplib.NNTP/NNTP_SSL now reject timeout = 0
  Doc/library/nntplib.rst
  Doc/whatsnew/3.9.rst
  Lib/nntplib.py
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Library/2020-01-11-00-32-45.bpo-39259._S5VjC.rst
Labels: CLA signed, awaiting changes

#17937 bpo-39288: Add math.nextafter(x, y)
  Doc/library/math.rst
  Doc/whatsnew/3.9.rst
  Lib/test/test_math.py
  Misc/NEWS.d/next/Library/2020-01-10-16-52-09.bpo-39288.IB-aQX.rst
  Modules/clinic/mathmodule.c.h
  Modules/mathmodule.c
Labels: CLA signed, awaiting merge

#17960 bpo-16575: Disabled checks for union types being passed by value.
  Lib/ctypes/test/test_structures.py
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#17934 bpo-12159: document sys.maxsize limit in len() function reference
  Doc/library/functions.rst
Labels: CLA signed, awaiting change review, skip news, type-documentation

#16552 bpo-38356: Fix ThreadedChildWatcher thread leak in test_asyncio
  Lib/asyncio/unix_events.py
Labels: :robot: automerge, CLA signed, awaiting merge, expert-asyncio, needs backport to 3.8, skip news, type-bugfix

#17902 [3.8] bpo-39233: Update positional-only section in the glossary (GH-17874)
  Doc/glossary.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#17963 [3.8] bpo-38356: Fix ThreadedChildWatcher thread leak in test_asyncio (GH-16552)
  Lib/asyncio/unix_events.py
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#17964 [3.8] bpo-16575: Disabled checks for union types being passed by value. (GH-17960)
  Lib/ctypes/test/test_structures.py
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting review, skip news, type-bugfix

#17962 bpo-39288: Add examples to math.nextafter() documentation
  Doc/library/math.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#16438 bpo-38293: Allow shallow and deep copying of property objects
  Lib/copy.py
  Lib/test/test_copy.py
  Misc/NEWS.d/next/Library/2019-09-29-08-17-03.bpo-38293.wls5s3.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-enhancement

#17968 [3.7] bpo-38293: Allow shallow and deep copying of property objects (GH-16438)
  Lib/copy.py
  Lib/test/test_copy.py
  Misc/NEWS.d/next/Library/2019-09-29-08-17-03.bpo-38293.wls5s3.rst
Labels: CLA signed, awaiting merge, type-enhancement

#17969 [3.8] bpo-38293: Allow shallow and deep copying of property objects (GH-16438)
  Lib/copy.py
  Lib/test/test_copy.py
  Misc/NEWS.d/next/Library/2019-09-29-08-17-03.bpo-38293.wls5s3.rst
Labels: CLA signed, awaiting merge, type-enhancement

#17172 bpo-3530: Use fix_missing_locations when node transformer adds nodes
  Doc/library/ast.rst
  Misc/NEWS.d/next/Documentation/2019-11-17-11-53-10.bpo-3530.8zFUMc.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, type-documentation

#17973 [3.7] bpo-3530: Add advice on when to correctly use fix_missing_locations in the AST docs (GH-17172)
  Doc/library/ast.rst
  Misc/NEWS.d/next/Documentation/2019-11-17-11-53-10.bpo-3530.8zFUMc.rst
Labels: CLA signed, awaiting merge, type-documentation

#17972 [3.8] bpo-3530: Add advice on when to correctly use fix_missing_locations in the AST docs (GH-17172)
  Doc/library/ast.rst
  Misc/NEWS.d/next/Documentation/2019-11-17-11-53-10.bpo-3530.8zFUMc.rst
Labels: CLA signed, awaiting merge, type-documentation

#17929 Fix outdated comment in _strptime.py
  Lib/_strptime.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#17970 [3.7] bpo-16575: Disabled checks for union types being passed by value. (GH-17960)
  Lib/ctypes/test/test_structures.py
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#17967 bpo-39313: Add an option to RefactoringTool for using exec as a function
  Doc/library/2to3.rst
  Lib/lib2to3/main.py
  Lib/lib2to3/refactor.py
  Lib/lib2to3/tests/test_refactor.py
  Misc/NEWS.d/next/Library/2020-01-12-18-17-00.bpo-39313.DCTsnm.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#12200 bpo-32021: Support brotli .br encoding in mimetypes
  Lib/mimetypes.py
  Misc/NEWS.d/next/Core and Builtins/2019-03-11-13-30-40.bpo-32021.dpbtkP.rst
Labels: CLA signed, awaiting merge, type-enhancement
