Repository python/cpython, pull requests merged in 2020-11, with the labels that each got.

#22970 bpo-42146: Unify cleanup in subprocess_fork_exec()
  Modules/_posixsubprocess.c
Labels: CLA signed, awaiting merge, skip news

#23059 bpo-29566: binhex.binhex now consitently writes MacOS 9 line endings.
  Lib/binhex.py
  Lib/test/test_binhex.py
  Misc/NEWS.d/next/Library/2020-10-31-13-28-36.bpo-29566.6aDbty.rst
Labels: :robot: automerge, CLA signed, OS-mac, awaiting merge, needs backport to 3.8, needs backport to 3.9

#23070 [3.8] bpo-29566: binhex.binhex now consitently writes MacOS 9 line endings. (GH-23059)
  Lib/binhex.py
  Lib/test/test_binhex.py
  Misc/NEWS.d/next/Library/2020-10-31-13-28-36.bpo-29566.6aDbty.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23071 [3.9] bpo-29566: binhex.binhex now consitently writes MacOS 9 line endings. (GH-23059)
  Lib/binhex.py
  Lib/test/test_binhex.py
  Misc/NEWS.d/next/Library/2020-10-31-13-28-36.bpo-29566.6aDbty.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23068 bpo-42160: tempfile: Use choises() instead of choise()
  Lib/tempfile.py
  Lib/test/test_tempfile.py
Labels: awaiting core review, skip news

#23062 bpo-37483: Add PyObject_CallOneArg() in the What's New in Python 3.9
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#23074 [3.9] bpo-37483: Add PyObject_CallOneArg() in the What's New in Python 3.9 (GH-23062)
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23078 Expand and clarify the "Invoking Descriptors" section of the Descriptor HowTo
  Doc/howto/descriptor.rst
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news, type-documentation

#23080 [3.9] Expand and clarify the "Invoking Descriptors" section of the Descriptor HowTo (GH-23078)
  Doc/howto/descriptor.rst
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#23081 bpo-42233: Correctly repr GenericAlias when used with typing module
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2020-11-02-01-31-15.bpo-42233.YxRj-h.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9

#23083 bpo-42236: Enhance _locale._get_locale_encoding()
  Include/internal/pycore_fileutils.h
  Modules/_io/textio.c
  Modules/_localemodule.c
  Python/fileutils.c
  Python/initconfig.c
Labels: CLA signed, awaiting core review, skip news

#23086 bpo-42236: Use UTF-8 encoding if nl_langinfo(CODESET) fails
  Doc/c-api/init_config.rst
  Doc/library/sys.rst
  Include/cpython/initconfig.h
  Include/internal/pycore_fileutils.h
  Include/pyport.h
  Misc/NEWS.d/next/Core and Builtins/2020-11-01-21-21-38.bpo-42236.MPx-NK.rst
  Python/fileutils.c
  Python/initconfig.c
Labels: CLA signed, awaiting core review

#13893 bpo-37193: remove thread objects which finished process its request
  Lib/socketserver.py
  Lib/test/test_socketserver.py
  Misc/NEWS.d/next/Library/2020-06-12-21-23-20.bpo-37193.wJximU.rst
Labels: CLA signed, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9

#23084 Add member objects to the descriptor howto guide
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news, type-documentation

#23090 [3.9] Add member objects to the descriptor howto guide (GH-23084)
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#20910 bpo-40511: fix unnecessary flashing of calltips
  Lib/idlelib/calltip.py
  Lib/idlelib/idle_test/mock_tk.py
  Lib/idlelib/idle_test/test_calltip.py
  Misc/NEWS.d/next/IDLE/2020-06-16-12-16-13.bpo-40511.XkihpM.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#23092 Minor formatting edits to the descriptor howto guide
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news, type-documentation

#23093 [3.9] bpo-40511: Stop unwanted flashing of IDLE calltips (GH-20910)
  Lib/idlelib/calltip.py
  Lib/idlelib/idle_test/mock_tk.py
  Lib/idlelib/idle_test/test_calltip.py
  Misc/NEWS.d/next/IDLE/2020-06-16-12-16-13.bpo-40511.XkihpM.rst
Labels: CLA signed, awaiting merge, type-bugfix

#23094 [3.8] bpo-40511: Stop unwanted flashing of IDLE calltips (GH-20910)
  Lib/idlelib/calltip.py
  Lib/idlelib/idle_test/mock_tk.py
  Lib/idlelib/idle_test/test_calltip.py
  Misc/NEWS.d/next/IDLE/2020-06-16-12-16-13.bpo-40511.XkihpM.rst
Labels: CLA signed, awaiting merge, type-bugfix

#23095 [3.9] Minor formatting edits to the descriptor howto guide (GH-23092)
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#21545 bpo-41229: Update docs for explicit aclose()-required cases and add contextlib.aclosing() method
  Doc/library/contextlib.rst
  Doc/reference/expressions.rst
  Lib/contextlib.py
  Lib/test/test_contextlib_async.py
  Misc/NEWS.d/next/Library/2020-07-19-20-10-41.bpo-41229.p8rJa2.rst
Labels: :robot: automerge, CLA signed, awaiting merge, expert-asyncio, type-enhancement

#23073 bpo-42230: Improve asyncio documentation regarding accepting sets vs iterables
  Doc/library/asyncio-task.rst
  Lib/asyncio/tasks.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news

#23104 [3.9] bpo-42230: Improve asyncio documentation regarding accepting sets vs iterables (GH-23073)
  Doc/library/asyncio-task.rst
  Lib/asyncio/tasks.py
Labels: CLA signed, awaiting merge, skip news

#23105 [3.8] bpo-42230: Improve asyncio documentation regarding accepting sets vs iterables (GH-23073)
  Doc/library/asyncio-task.rst
  Lib/asyncio/tasks.py
Labels: CLA signed, awaiting merge, skip news

#21689 bpo-41435: Add sys._current_exceptions() function
  Doc/library/sys.rst
  Include/cpython/pystate.h
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2020-08-07-13-42-48.bpo-41435.qPWjJA.rst
  Python/clinic/sysmodule.c.h
  Python/pystate.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge

#23067 bpo-42224: Fix test_format when locale does not expect number grouping
  Lib/test/test_format.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-tests

#23110 [3.8] bpo-42224: Fix test_format when locale does not expect number grouping (GH-23067)
  Lib/test/test_format.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-tests

#23109 bpo-42236: Enhance init and encoding documentation
  Doc/c-api/exceptions.rst
  Doc/c-api/init.rst
  Doc/c-api/init_config.rst
  Doc/c-api/sys.rst
  Doc/c-api/unicode.rst
  Doc/c-api/veryhigh.rst
  Doc/glossary.rst
  Doc/howto/unicode.rst
  Doc/library/devmode.rst
  Doc/library/exceptions.rst
  Doc/library/locale.rst
  Doc/library/os.rst
  Doc/library/sys.rst
  Doc/using/cmdline.rst
  Doc/using/windows.rst
  Doc/whatsnew/3.7.rst
  Include/cpython/initconfig.h
  Python/initconfig.c
  Python/preconfig.c
Labels: awaiting core review, skip news

#23111 [3.9] bpo-42224: Fix test_format when locale does not expect number grouping (GH-23067)
  Lib/test/test_format.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#23107 bpo-37193: Revert "remove thread objects which finished process its request"
  Lib/socketserver.py
  Lib/test/test_socketserver.py
  Misc/NEWS.d/next/Library/2020-06-12-21-23-20.bpo-37193.wJximU.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#22565 bpo-41943: Fix bug where assertLogs doesn't correctly filter messages…
  Lib/unittest/_log.py
  Lib/unittest/test/test_case.py
  Misc/NEWS.d/next/Library/2020-10-07-18-36-03.bpo-41943.Pt55fT.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#22882 bpo-42103: Improve validation of Plist files.
  Lib/plistlib.py
  Lib/test/test_plistlib.py
  Misc/NEWS.d/next/Library/2020-10-23-19-20-14.bpo-42103.C5obK2.rst
  Misc/NEWS.d/next/Security/2020-10-23-19-19-30.bpo-42103.cILT66.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, type-bugfix, type-security

#23024 bpo-41796: Make _ast module state per interpreter
  Include/Python-ast.h
  Include/internal/pycore_ast.h
  Include/internal/pycore_interp.h
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2020-10-29-12-49-08.bpo-41796.tkGdHq.rst
  PCbuild/regen.vcxproj
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting core review

#23115 [3.9] bpo-42103: Improve validation of Plist files. (GH-22882)
  Lib/plistlib.py
  Lib/test/test_plistlib.py
  Misc/NEWS.d/next/Library/2020-10-23-19-20-14.bpo-42103.C5obK2.rst
  Misc/NEWS.d/next/Security/2020-10-23-19-19-30.bpo-42103.cILT66.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-security

#23053 bpo-26789: Fix logging.FileHandler._open() at exit
  Lib/logging/__init__.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2020-10-31-01-16-49.bpo-26789.9BdNAt.rst
  Python/_warnings.c
Labels: CLA signed, awaiting merge

#11118 bpo-35455: Fix thread_time for Solaris OS
  Misc/NEWS.d/next/Library/2020-11-02-14-10-48.bpo-35455.Q1xTIo.rst
  Modules/timemodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#23114 [3.9] bpo-42180: fix plural in arguments and control (GH-23015)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23116 [3.8] bpo-42103: Improve validation of Plist files. (GH-22882)
  Lib/plistlib.py
  Lib/test/test_plistlib.py
  Misc/NEWS.d/next/Library/2020-10-23-19-20-14.bpo-42103.C5obK2.rst
  Misc/NEWS.d/next/Security/2020-10-23-19-19-30.bpo-42103.cILT66.rst
Labels: CLA signed, awaiting core review, type-bugfix, type-security

#23108 bpo-40077: Convert mmap to use heap types
  Misc/NEWS.d/next/Core and Builtins/2020-11-02-14-39-48.bpo-40077.grY9TG.rst
  Modules/mmapmodule.c
Labels: CLA signed, awaiting merge

#23121 bpo-42249: Fix writing binary Plist files larger than 4 GiB.
  Lib/plistlib.py
  Misc/NEWS.d/next/Library/2020-11-03-09-22-56.bpo-42249.vfNO2u.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#23128 [3.8] bpo-42249: Fix writing binary Plist files larger than 4 GiB. (GH-23121)
  Lib/plistlib.py
  Misc/NEWS.d/next/Library/2020-11-03-09-22-56.bpo-42249.vfNO2u.rst
Labels: CLA signed, awaiting merge, type-bugfix

#23131 bpo-41796: Call _PyAST_Fini() earlier to fix a leak
  Include/internal/pycore_pylifecycle.h
  Parser/asdl_c.py
  Python/Python-ast.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting core review, skip news

#22835 bpo-42100: Add _PyType_GetModuleByDef
  Include/cpython/object.h
  Modules/_testmultiphase.c
  Modules/clinic/_testmultiphase.c.h
  Objects/typeobject.c
Labels: CLA signed, awaiting core review, skip news

#23017 Fix incorrect attr links in ast docs
  Doc/library/ast.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23129 [3.9] bpo-42249: Fix writing binary Plist files larger than 4 GiB. (GH-23121)
  Lib/plistlib.py
  Misc/NEWS.d/next/Library/2020-11-03-09-22-56.bpo-42249.vfNO2u.rst
Labels: CLA signed, awaiting merge, type-bugfix

#23132 Enable signing of nuget.org packages and update to supported timestamp server
  .azure-pipelines/windows-release/stage-pack-msix.yml
  .azure-pipelines/windows-release/stage-pack-nuget.yml
  .azure-pipelines/windows-release/stage-sign.yml
  PCbuild/pyproject.props
  Tools/msi/sdktools.psm1
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#23137 [3.9] Enable signing of nuget.org packages and update to supported timestamp server (GH-23132)
  .azure-pipelines/windows-release/stage-pack-msix.yml
  .azure-pipelines/windows-release/stage-pack-nuget.yml
  .azure-pipelines/windows-release/stage-sign.yml
  PCbuild/pyproject.props
  Tools/msi/sdktools.psm1
Labels: CLA signed, awaiting merge, skip issue, skip news

#23138 [3.8] Enable signing of nuget.org packages and update to supported timestamp server (GH-23132)
  .azure-pipelines/windows-release/stage-pack-msix.yml
  .azure-pipelines/windows-release/stage-pack-nuget.yml
  .azure-pipelines/windows-release/stage-sign.yml
  PCbuild/pyproject.props
  Tools/msi/sdktools.psm1
Labels: CLA signed, awaiting merge, skip issue, skip news

#23125 bpo-42251: Add gettrace and getprofile to threading
  Doc/library/threading.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Library/2020-11-03-14-15-35.bpo-42251.6TC32V.rst
Labels: CLA signed, awaiting merge

#23119 bpo-42236: os.device_encoding() respects UTF-8 Mode
  Doc/library/os.rst
  Lib/test/test_utf8_mode.py
  Misc/NEWS.d/next/Library/2020-11-02-23-05-17.bpo-42236.aJ6ZBR.rst
  Python/fileutils.c
  Python/initconfig.c
Labels: CLA signed, awaiting merge

#23122 bpo-1635741: Add PyModule_AddObjectRef() function
  Doc/c-api/module.rst
  Doc/whatsnew/3.10.rst
  Include/modsupport.h
  Misc/NEWS.d/next/C API/2020-11-03-11-52-27.bpo-1635741.aDYJKB.rst
  Python/modsupport.c
Labels: CLA signed, awaiting core review

#23130 [3.9] bpo-35455: Fix thread_time for Solaris OS (GH-11118)
  Misc/NEWS.d/next/Library/2020-11-02-14-10-48.bpo-35455.Q1xTIo.rst
  Modules/timemodule.c
Labels: CLA signed, awaiting review

#23145 [3.8] bpo-35455: Fix thread_time for Solaris OS (GH-11118).
  Misc/NEWS.d/next/Library/2020-11-02-14-10-48.bpo-35455.Q1xTIo.rst
  Modules/timemodule.c
Labels: CLA signed, awaiting merge

#23149 bpo-42260: Reorganize PyConfig
  Include/cpython/initconfig.h
Labels: CLA signed, awaiting core review, skip news

#23147 bpo-1635741: _contextvars uses PyModule_AddType()
  Modules/_contextvarsmodule.c
  Python/context.c
Labels: CLA signed, awaiting core review, skip news

#23146 bpo-1635741: _ast uses PyModule_AddObjectRef()
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting core review, skip news

#23151 bpo-1635741: _warnings uses PyModule_AddObjectRef()
  Python/_warnings.c
  Python/importdl.c
Labels: CLA signed, awaiting core review, skip news

#23150 bpo-42260: Main init modify sys.flags in-place
  Include/internal/pycore_pylifecycle.h
  Misc/NEWS.d/next/C API/2020-11-04-16-31-55.bpo-42260.CmgHtF.rst
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review, skip news

#22489 bpo-1635741: pyexpat error handling
  Modules/pyexpat.c
Labels: CLA signed, awaiting merge, skip news

#23148 bpo-1635741: _sqlite3 uses PyModule_AddObjectRef
  Modules/_sqlite/microprotocols.c
  Modules/_sqlite/module.c
Labels: CLA signed, awaiting merge, skip news

#23141 bpo-42207: Disable peg generator tests when building with PGO
  Lib/test/test_peg_generator/test_c_parser.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#23155 [3.9] bpo-42207 :Disable peg generator tests when building with PGO (GH-23141)
  Lib/test/test_peg_generator/test_c_parser.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#23158 bpo-42260: Add _PyInterpreterState_SetConfig()
  Doc/c-api/init_config.rst
  Include/cpython/pystate.h
  Include/internal/pycore_initconfig.h
  Include/internal/pycore_interp.h
  Lib/test/test_embed.py
  Programs/_testembed.c
  Python/initconfig.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting core review, skip news

#20516 bpo-40816 Add AsyncContextDecorator class
  Doc/library/contextlib.rst
  Lib/contextlib.py
  Lib/test/test_contextlib_async.py
  Misc/NEWS.d/next/Library/2020-05-29-15-25-41.bpo-40816.w61Pob.rst
Labels: CLA signed, awaiting merge

#23157 bpo-42266: Handle monkey-patching descriptors in LOAD_ATTR cache
  Lib/test/test_opcache.py
  Misc/NEWS.d/next/Core and Builtins/2020-11-04-23-03-25.bpo-42266.G4hGDe.rst
  PCbuild/lib.pyproj
  Python/ceval.c
Labels: CLA signed, awaiting merge

#23152 bpo-42262: Add Py_NewRef() function
  Doc/c-api/refcounting.rst
  Doc/whatsnew/3.10.rst
  Include/boolobject.h
  Include/object.h
  Misc/NEWS.d/next/C API/2020-11-04-17-22-36.bpo-42262.fCWzBb.rst
  Objects/object.c
  PC/python3dll.c
Labels: CLA signed, awaiting merge

#23164 bpo-40816: [docs] Fix wrongly named AsyncContextManager
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23165 bpo-41877 Check for asert, aseert, assrt in mocks
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2020-11-05-16-00-03.bpo-41877.FHbngM.rst
Labels: CLA signed, awaiting merge

#23167 bpo-42260: Add _PyConfig_FromDict()
  Include/internal/pycore_initconfig.h
  Lib/test/_test_embed_set_config.py
  Lib/test/test_embed.py
  Modules/_testinternalcapi.c
  Python/initconfig.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review, skip news

#23168 bpo-42260: PyConfig_Read() only parses argv once
  Doc/c-api/init_config.rst
  Lib/test/_test_embed_set_config.py
  Lib/test/test_embed.py
  Misc/NEWS.d/next/C API/2020-11-05-18-02-07.bpo-42260.pAeaNR.rst
  Modules/_testinternalcapi.c
  Python/initconfig.c
Labels: CLA signed, awaiting core review

#22610 bpo-26389: Allow passing an exception object in the traceback module
  Doc/library/traceback.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2020-10-08-23-51-55.bpo-26389.uga44e.rst
Labels: CLA signed, awaiting merge

#23162 bpo-42179: Doc/tutorial: Remove mention of __cause__
  Doc/tutorial/errors.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#23173 [3.9] bpo-42179: Doc/tutorial: Remove mention of __cause__ (GH-23162)
  Doc/tutorial/errors.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23175 Minor grammar edits for the descriptor howto guide
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news, type-documentation

#23123 bpo-41832: PyType_FromModuleAndSpec() can accept the NULL tp_doc slot.
  Doc/c-api/type.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_capi.py
  Misc/NEWS.d/next/C API/2020-11-03-19-47-06.bpo-41832.dL1VJJ.rst
  Modules/_lsprof.c
  Modules/_testcapimodule.c
  Objects/typeobject.c
Labels: CLA signed, awaiting merge

#22005 [doc] Remove no longer valid note on platform.win32_ver
  Doc/library/platform.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#23183 [3.9] Remove outdated reference to pywin32 from platform module (GH-22005)
  Doc/library/platform.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23186 [3.9] Minor grammar edits for the descriptor howto guide (GH-23175)
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#22929 bpo-42133: update parts of the stdlib to fall back to `__spec__.parent` when `__loader__` is missing
  Doc/whatsnew/3.10.rst
  Lib/doctest.py
  Lib/inspect.py
  Lib/linecache.py
  Lib/site.py
  Misc/NEWS.d/next/Library/2020-10-23-15-47-47.bpo-42133.BzizYV.rst
Labels: CLA signed, awaiting core review

#20969 bpo-41028: Doc: Move switchers to docsbuild-scripts.
  Doc/Makefile
  Doc/tools/static/switchers.js
  Doc/tools/templates/dummy.html
  Doc/tools/templates/indexsidebar.html
  Doc/tools/templates/layout.html
  Misc/NEWS.d/next/Documentation/2020-06-18-23-37-03.bpo-41028.vM8bC8.rst
Labels: CLA signed, awaiting merge, type-documentation

#23190 bpo-42282: Fold constants inside named expressions
  Misc/NEWS.d/next/Core and Builtins/2020-11-07-21-02-05.bpo-42282.M1W4Wj.rst
  Python/ast_opt.c
Labels: CLA signed, awaiting merge

#23082 [3.9] bpo-42233: Correctly repr GenericAlias when used with typing module (GH-23081)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2020-11-02-01-31-15.bpo-42233.YxRj-h.rst
Labels: CLA signed, awaiting merge

#23136 bpo-40077: Convert _queuemodule to use heap types
  Misc/NEWS.d/next/Core and Builtins/2020-11-03-21-58-27.bpo-40077.a9qM1j.rst
  Modules/_queuemodule.c
  Modules/clinic/_queuemodule.c.h
Labels: :robot: automerge, CLA signed, awaiting merge

#23194 Minor wording change in concurrent.futures.
  Doc/library/concurrent.futures.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#22855 bpo-41100: Support macOS 11 and Apple Silicon
  Lib/_osx_support.py
  Lib/ctypes/macholib/dyld.py
  Lib/ctypes/test/test_macholib.py
  Lib/distutils/tests/test_build_ext.py
  Lib/test/test_bytes.py
  Lib/test/test_platform.py
  Lib/test/test_posix.py
  Lib/test/test_time.py
  Lib/test/test_unicode.py
  Mac/BuildScript/build-installer.py
  Mac/BuildScript/openssl-mac-arm64.patch
  Mac/README.rst
  Mac/Tools/pythonw.c
  Misc/NEWS.d/next/macOS/2020-11-01-16-40-23.bpo-41100.BApztP.rst
  Modules/_ctypes/callbacks.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/ctypes.h
  Modules/_ctypes/malloc_closure.c
  Modules/getpath.c
  Modules/posixmodule.c
  Modules/timemodule.c
  Python/bootstrap_hash.c
  Python/pytime.c
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed

#23196 [3.8] Minor wording change in concurrent.futures. (GH-23194)
  Doc/library/concurrent.futures.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23195 [3.9] Minor wording change in concurrent.futures. (GH-23194)
  Doc/library/concurrent.futures.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#23075 bpo-41754: Ignore NotADirectoryError in invocation of xdg-settings
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2020-11-01-15-07-20.bpo-41754.DraSZh.rst
Labels: :robot: automerge, CLA signed, OS-mac, awaiting core review, needs backport to 3.8, needs backport to 3.9

#23197 [3.9] bpo-41754: Ignore NotADirectoryError in invocation of xdg-settings (GH-23075)
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2020-11-01-15-07-20.bpo-41754.DraSZh.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23198 [3.8] bpo-41754: Ignore NotADirectoryError in invocation of xdg-settings (GH-23075)
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2020-11-01-15-07-20.bpo-41754.DraSZh.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23077 bpo-42233: Add union type expression support for GenericAlias and fix de-duplicating of GenericAlias
  Include/internal/pycore_unionobject.h
  Lib/test/test_types.py
  Misc/NEWS.d/next/Core and Builtins/2020-11-01-23-34-56.bpo-42233.zOSzja.rst
  Objects/genericaliasobject.c
  Objects/typeobject.c
  Objects/unionobject.c
Labels: CLA signed, awaiting review

#22147 bpo-40624: Add support for the XPath != operator in xml.etree
  Doc/library/xml.etree.elementtree.rst
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementPath.py
  Misc/NEWS.d/next/Library/2020-09-08-03-19-04.bpo-40624.0-gYfx.rst
Labels: CLA signed, awaiting merge

#21870 bpo-41543: contextlib.nullcontext can fill in for an async context manager
  Doc/library/contextlib.rst
  Lib/contextlib.py
  Lib/test/test_contextlib_async.py
  Misc/NEWS.d/next/Library/2020-08-14-00-39-04.bpo-41543.RpcRjb.rst
Labels: CLA signed, awaiting merge

#23206 bpo-42294: Add borrowed/strong reference to doc glossary
  Doc/c-api/arg.rst
  Doc/c-api/init.rst
  Doc/c-api/intro.rst
  Doc/c-api/refcounting.rst
  Doc/c-api/reflection.rst
  Doc/c-api/structures.rst
  Doc/c-api/typeobj.rst
  Doc/c-api/weakref.rst
  Doc/data/refcounts.dat
  Doc/glossary.rst
  Include/object.h
Labels: CLA signed, awaiting core review, skip news

#23166 bpo-41712: Vulnerable regex changed
  Tools/msi/purge.py
Labels: CLA signed, awaiting core review, skip news

#19875 bpo-36310: Allow ``pygettext.py`` to detect calls to ``gettext`` in f-strings.
  Lib/test/test_tools/test_i18n.py
  Misc/ACKS
  Misc/NEWS.d/next/Tools-Demos/2020-05-03-01-30-46.bpo-36310.xDxxwY.rst
  Tools/i18n/pygettext.py
Labels: CLA signed, awaiting core review

#23180 Fix typo in unicodeobject.c
  Objects/unicodeobject.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news

#23215 [3.9] Fix typo in unicodeobject.c (GH-23180)
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#23211 bpo-42260: Compute the path config in the main init
  Include/internal/pycore_initconfig.h
  Lib/test/_test_embed_set_config.py
  Programs/_testembed.c
  Python/initconfig.c
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review, skip news

#23189 Fix typo in test_array.py
  Lib/test/test_array.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#23009 bpo-42171: Add PEP573-related items to the limited API
  Doc/c-api/structures.rst
  Include/methodobject.h
  Misc/NEWS.d/next/C API/2020-10-27-21-10-14.bpo-42171.S3FWTP.rst
  PC/python3dll.c
Labels: :robot: automerge, CLA signed, awaiting merge

#23020 bpo-42183: Fix a stack overflow error for asyncio Task or Future repr()
  Lib/asyncio/base_futures.py
  Lib/test/test_asyncio/test_futures2.py
  Misc/NEWS.d/next/Library/2020-10-29-11-17-35.bpo-42183.50ZcIi.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9

#23221 [3.9] bpo-42183: Fix a stack overflow error for asyncio Task or Future repr() (GH-23020)
  Lib/asyncio/base_futures.py
  Lib/test/test_asyncio/test_futures2.py
  Misc/NEWS.d/next/Library/2020-10-29-11-17-35.bpo-42183.50ZcIi.rst
Labels: CLA signed, awaiting merge

#23222 [3.8] bpo-42183: Fix a stack overflow error for asyncio Task or Future repr() (GH-23020)
  Lib/asyncio/base_futures.py
  Lib/test/test_asyncio/test_futures2.py
  Misc/NEWS.d/next/Library/2020-10-29-11-17-35.bpo-42183.50ZcIi.rst
Labels: CLA signed, awaiting merge

#23217 bpo-41229: Add a whatsnew entry about contextlib.aclosing
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#22585 bpo-42014: shutil.rmtree: call onerror with correct function
  Lib/shutil.py
  Misc/NEWS.d/next/Library/2020-11-10-15-40-56.bpo-42014.ShM37l.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#23229 [3.8] bpo-42014: shutil.rmtree: call onerror with correct function (GH-22585)
  Lib/shutil.py
  Misc/NEWS.d/next/Library/2020-11-10-15-40-56.bpo-42014.ShM37l.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23228 [3.9] bpo-42014: shutil.rmtree: call onerror with correct function (GH-22585)
  Lib/shutil.py
  Misc/NEWS.d/next/Library/2020-11-10-15-40-56.bpo-42014.ShM37l.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23117 [3.7] bpo-42103: Improve validation of Plist files. (GH-22882)
  Lib/plistlib.py
  Lib/test/test_plistlib.py
  Misc/NEWS.d/next/Library/2020-10-23-19-20-14.bpo-42103.C5obK2.rst
  Misc/NEWS.d/next/Security/2020-10-23-19-19-30.bpo-42103.cILT66.rst
Labels: CLA signed, awaiting core review, type-bugfix, type-security

#23118 [3.6] bpo-42103: Improve validation of Plist files. (GH-22882)
  Lib/plistlib.py
  Lib/test/test_plistlib.py
  Misc/NEWS.d/next/Library/2020-10-23-19-20-14.bpo-42103.C5obK2.rst
  Misc/NEWS.d/next/Security/2020-10-23-19-19-30.bpo-42103.cILT66.rst
Labels: CLA signed, awaiting core review, type-bugfix, type-security

#23231 [3.6] bpo-35560: Remove assertion from format(float, "n") (GH-11288)
  Lib/test/test_float.py
  Misc/NEWS.d/next/Core and Builtins/2018-12-22-22-19-51.bpo-35560.9vMWSP.rst
  Objects/unicodeobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#22780 bpo-42085: Introduce dedicated entry in PyAsyncMethods for sending values
  Doc/c-api/typeobj.rst
  Include/abstract.h
  Include/cpython/object.h
  Include/object.h
  Include/typeslots.h
  Lib/test/test_sys.py
  Misc/NEWS.d/next/C API/2020-10-19-15-58-16.bpo-42085.NhEf3W.rst
  Modules/_asynciomodule.c
  Modules/_testcapimodule.c
  Objects/abstract.c
  Objects/genobject.c
  Objects/typeobject.c
  Objects/typeslots.inc
Labels: CLA signed, awaiting merge

#23220 bpo-42260: Fix _PyConfig_Read() if compute_path_config=0
  Doc/c-api/init.rst
  Doc/c-api/init_config.rst
  Doc/whatsnew/3.10.rst
  Include/internal/pycore_initconfig.h
  Misc/NEWS.d/next/C API/2020-11-10-14-27-39.bpo-42260.-Br3Co.rst
  Python/initconfig.c
  Python/pathconfig.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review

#21931 bpo-41073: PyType_GetSlot() can now accept static types.
  Doc/c-api/type.rst
  Doc/whatsnew/3.10.rst
  Misc/NEWS.d/next/C API/2020-07-08-21-01-49.bpo-41073.VqQZON.rst
  Modules/_testcapimodule.c
  Objects/typeobject.c
  Objects/typeslots.inc
  Objects/typeslots.py
Labels: :robot: automerge, CLA signed, awaiting merge

#22938 bpo-42140: Improve asyncio.wait function
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2020-10-24-04-02-36.bpo-42140.miLqvb.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#23232 [3.9] bpo-4bpo-42314: Fix the documentation for venv --upgrade-deps (GH-22113) (GH-23232)
  Doc/using/venv-create.inc
Labels: CLA signed, awaiting merge, skip issue, skip news

#23233 [3.9] bpo-42140: Improve asyncio.wait function (GH-22938)
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2020-10-24-04-02-36.bpo-42140.miLqvb.rst
Labels: CLA signed, awaiting merge

#23227 bpo-42294: Grammar fixes in glossary strong/weak references
  Doc/c-api/weakref.rst
  Doc/glossary.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#23234 bpo-1635741: Fix typo in PyModule_AddObjectRef() doc
  Doc/whatsnew/3.10.rst
  Misc/NEWS.d/next/C API/2020-11-03-11-52-27.bpo-1635741.aDYJKB.rst
Labels: CLA signed, awaiting core review, type-documentation

#18103 bpo-39411: pyclbr rewrite on AST
  Doc/library/pyclbr.rst
  Lib/pyclbr.py
  Lib/test/test_pyclbr.py
  Misc/NEWS.d/next/Library/2020-01-21-16-38-25.bpo-39411.9uHFqT.rst
Labels: CLA signed, awaiting merge

#21502 bpo-40932: Note security caveat of shlex.quote on Windows
  Doc/library/shlex.rst
  Doc/library/subprocess.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#23236 bpo-40170: Fix PyType_Ready() refleak on static type
  Include/cpython/object.h
  Objects/typeobject.c
Labels: CLA signed, awaiting core review, skip news

#23237 bpo-42085: Fix memory leak introduced by GH-22780
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, skip news

#23113 bpo-42246: Partial implementation of PEP 626.
  Include/cpython/code.h
  Lib/dis.py
  Lib/test/test_code.py
  Lib/test/test_compile.py
  Lib/test/test_opcodes.py
  Lib/test/test_pdb.py
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2020-11-02-15-48-17.bpo-42246.3CNQEX.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Objects/frameobject.c
  Objects/lnotab_notes.txt
  Python/ceval.c
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
  Python/marshal.c
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review

#23154 bpo-42237: Fix os.sendfile() on illumos
  Misc/NEWS.d/next/Library/2020-11-10-14-27-49.bpo-42237.F363jO.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#23244 [3.9] bpo-42237: Fix os.sendfile() on illumos (GH-23154)
  Misc/NEWS.d/next/Library/2020-11-10-14-27-49.bpo-42237.F363jO.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#23245 bpo-42246: Bump magic number.
  Lib/importlib/_bootstrap_external.py
  PC/launcher.c
  Python/importlib_external.h
Labels: CLA signed, awaiting core review, skip news

#23246 [3.8] bpo-42237: Fix os.sendfile() on illumos (GH-23154).
  Misc/NEWS.d/next/Library/2020-11-10-14-27-49.bpo-42237.F363jO.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#23247 bpo-38823: Fix refleaks in _ctypes extension init
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/callproc.c
Labels: CLA signed, awaiting core review, skip news

#23249 bpo-42260: Initialize warnings and time early at startup
  Include/internal/pycore_interp.h
  Include/internal/pycore_pylifecycle.h
  Include/internal/pycore_warnings.h
  Python/_warnings.c
  Python/import.c
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review, skip news

#23248 bpo-38823: Always build _ctypes with wchar_t
  Misc/NEWS.d/next/Build/2020-11-12-13-45-15.bpo-38823.C0z_Fe.rst
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/cfield.c
  Modules/_ctypes/ctypes.h
  Modules/_ctypes/stgdict.c
Labels: CLA signed, awaiting core review

#23218 bpo-42308: Add `threading.__excepthook__`
  Doc/library/threading.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Library/2020-11-10-12-09-13.bpo-42308.yaJHH9.rst
Labels: CLA signed, awaiting merge

#23251 bpo-42246: Eliminate jumps to exit blocks by copying those blocks.
  Lib/test/test_dis.py
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting core review, skip news

#22897 [3.9] bpo-42086: Document AST operator nodes acts as a singleton (GH-22896)
  Doc/library/ast.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#23256 bpo-42246: Fix memory leak in compiler
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#23258 bpo-38823: Fix compiler warning in _ctypes on Windows
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting core review, skip news

#23257 bpo-42296: On Windows, fix CTRL+C regression
  Misc/NEWS.d/next/Core and Builtins/2020-11-13-13-53-11.bpo-42296.DuGrLJ.rst
  Python/ceval.c
Labels: CLA signed, awaiting core review

#23259 [3.9] bpo-42296: On Windows, fix CTRL+C regression (GH-23257)
  Misc/NEWS.d/next/Core and Builtins/2020-11-13-13-53-11.bpo-42296.DuGrLJ.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge

#23260 bpo-41617: Add _Py__has_builtin() macro
  Include/internal/pycore_bitutils.h
  Include/pyport.h
  Misc/NEWS.d/next/Build/2020-11-13-15-04-53.bpo-41617.98_oaE.rst
Labels: CLA signed, awaiting merge

#22739 bpo-42042: Use ids attribute instead of names attribute
  Doc/tools/extensions/c_annotations.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news

#20959 bpo-40968: Send http/1.1 ALPN extension
  Doc/library/http.client.rst
  Doc/library/urllib.request.rst
  Lib/http/client.py
  Lib/urllib/request.py
  Misc/NEWS.d/next/Library/2020-06-18-11-35-16.bpo-40968.R8Edbv.rst
Labels: CLA signed, awaiting core review, type-enhancement

#23262 [3.9] bpo-41617: Add _Py__has_builtin() macro (GH-23260)
  Include/internal/pycore_byteswap.h
  Include/pyport.h
  Misc/NEWS.d/next/Build/2020-11-13-15-04-53.bpo-41617.98_oaE.rst
Labels: CLA signed, awaiting core review

#23265 [3.9] bpo-42042: Use ids attribute instead of names attribute (GH-22739)
  Doc/tools/extensions/c_annotations.py
Labels: CLA signed, awaiting core review, skip news

#23264 bpo-42344: Improve pseudo implementation for SimpleNamespace
  Doc/library/types.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23270 [3.9] bpo-42344: Improve pseudo implementation for SimpleNamespace (GH-23264)
  Doc/library/types.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#20930 bpo-41001: Add os.eventfd()
  Doc/library/os.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_os.py
  Misc/NEWS.d/next/Library/2020-06-17-12-24-26.bpo-41001.5mi7b0.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting merge, type-enhancement

#23271 bpo-40754: Adds _testinternalcapi to Windows installer for test suite
  Misc/NEWS.d/next/Tests/2020-11-13-21-51-34.bpo-40754.Ekoxkg.rst
  Tools/msi/test/test_files.wxs
Labels: CLA signed, OS-windows, needs backport to 3.8, needs backport to 3.9, type-tests

#23274 [3.8] bpo-40754: Adds _testinternalcapi to Windows installer for test suite (GH-23271)
  Misc/NEWS.d/next/Tests/2020-11-13-21-51-34.bpo-40754.Ekoxkg.rst
  Tools/msi/test/test_files.wxs
Labels: CLA signed, awaiting merge, type-tests

#23273 [3.9] bpo-40754: Adds _testinternalcapi to Windows installer for test suite (GH-23271)
  Misc/NEWS.d/next/Tests/2020-11-13-21-51-34.bpo-40754.Ekoxkg.rst
  Tools/msi/test/test_files.wxs
Labels: CLA signed, awaiting merge, type-tests

#23187 bpo-42131: Add PEP 451-related methods to zipimport
  Doc/library/zipimport.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_zipimport.py
  Lib/zipimport.py
  Misc/NEWS.d/next/Library/2020-11-06-18-20-47.bpo-42131.l2rjjG.rst
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting merge
