Repository python/cpython, pull requests merged in 2021-08, with the labels that each got.

#27521 bpo-34013: Don't consider a grouped expression when reporting legacy print syntax errors
  Grammar/python.gram
  Lib/test/test_exceptions.py
  Parser/parser.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news

#27522 [3.10] bpo-34013: Don't consider a grouped expression when reporting legacy print syntax errors (GH-27521)
  Grammar/python.gram
  Lib/test/test_exceptions.py
  Parser/parser.c
Labels: CLA signed, awaiting merge, skip news

#27510 [3.10] bpo-44784: Apply changes from importlib_metadata 4.6.3 (GH-27508)
  Lib/test/test_importlib/test_metadata_api.py
  Misc/NEWS.d/next/Library/2021-07-31-08-45-31.bpo-44784.fIMIDS.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-tests

#27531 [3.10] Remove beta release note from macOS installer displays
  Mac/BuildScript/resources/ReadMe.rtf
  Mac/BuildScript/resources/Welcome.rtf
Labels: CLA signed, OS-mac, awaiting core review, skip issue, skip news

#27515 bpo-44793: Fix checking the number of arguments when subscribe a gene…
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-07-31-20-28-20.bpo-44793.woaQSg.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, type-bugfix

#27537 [3.10] bpo-44793: Fix checking the number of arguments when subscribe a generic type with ParamSpec parameter. (GH-27515)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-07-31-20-28-20.bpo-44793.woaQSg.rst
Labels: CLA signed, awaiting merge, type-bugfix

#27485 bpo-44781: make distutils test suppress deprecation warning from impo…
  Lib/distutils/tests/test_bdist.py
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news, type-tests

#27534 DOC: "Mac OS " -> "macOS"
  Doc/library/platform.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9, skip issue, skip news, type-documentation

#27535 DOC: "Mac OS X" -> "macOS"
  Doc/library/othergui.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9, skip issue, skip news, type-documentation

#27500 [3.10] bpo-44667: Treat correctly lines ending with comments and no newlines in the Python tokenizer (GH-27499)
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Library/2021-07-30-23-27-30.bpo-44667.tu0Xrv.rst
Labels: CLA signed, awaiting merge

#27501 [3.9] bpo-44667: Treat correctly lines ending with comments and no newlines in the Python tokenizer (GH-27499)
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Library/2021-07-30-23-27-30.bpo-44667.tu0Xrv.rst
Labels: CLA signed, awaiting merge

#27540 [3.10] bpo-44781: make distutils test suppress deprecation warning from import distutils (GH-27485)
  Lib/distutils/tests/test_bdist.py
Labels: CLA signed, awaiting review, skip news, type-tests

#27544 bpo-44808: Fix test_inspect in refleak mode
  Lib/test/test_inspect.py
Labels: CLA signed, needs backport to 3.10, skip news

#27547 [3.9] doc: "Mac OS X" -> "macOS" (GH-27535)
  Doc/library/othergui.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#27548 [3.10] doc: "Mac OS X" -> "macOS" (GH-27535)
  Doc/library/othergui.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#27546 [3.10] bpo-44808: Fix test_inspect in refleak mode (GH-27544)
  Lib/test/test_inspect.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#27542 bpo-44206: Make sure that dict-keys's version is set to zero when value is popped.
  Lib/test/test_module.py
  Objects/dictobject.c
Labels: CLA signed, awaiting merge, skip news

#27538 bpo-44785: Silence deprecation warnings in test_pickle
  Lib/test/test_pickle.py
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9, skip news, type-tests

#27545 bpo-44806: Fix __init__ in subclasses of protocols
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-08-02-14-37-32.bpo-44806.wOW_Qn.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9, type-bugfix

#27555 bpo-44812: Document PyMember_GetOne and PyMember_SetOne
  Doc/c-api/structures.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#27554 [3.10] doc: "Mac OS " -> "macOS" (GH-27534)
  Doc/library/platform.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#27557 [3.9] bpo-44785: Silence deprecation warnings in test_pickle (GH-27538)
  Lib/test/test_pickle.py
Labels: CLA signed, awaiting review, skip news, type-tests

#27559 [3.9] bpo-44806: Fix __init__ in subclasses of protocols (GH-27545)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-08-02-14-37-32.bpo-44806.wOW_Qn.rst
Labels: CLA signed, awaiting review, type-bugfix

#27561 [3.9] bpo-44812: Document PyMember_GetOne and PyMember_SetOne (GH-27555)
  Doc/c-api/structures.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27286 bpo-35183: Add typical examples to os.path.splitext docs
  Doc/library/os.path.rst
  Misc/NEWS.d/next/Documentation/2021-07-22-08-28-03.bpo-35183.p9BWTB.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9, type-documentation

#27560 [3.10] bpo-44812: Document PyMember_GetOne and PyMember_SetOne (GH-27555)
  Doc/c-api/structures.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27558 [3.10] bpo-44806: Fix __init__ in subclasses of protocols (GH-27545)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-08-02-14-37-32.bpo-44806.wOW_Qn.rst
Labels: CLA signed, awaiting merge, type-bugfix

#27556 [3.10] bpo-44785: Silence deprecation warnings in test_pickle (GH-27538)
  Lib/test/test_pickle.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#27564 [3.9] bpo-35183: Add typical examples to os.path.splitext docs (GH-27286)
  Doc/library/os.path.rst
  Misc/NEWS.d/next/Documentation/2021-07-22-08-28-03.bpo-35183.p9BWTB.rst
Labels: CLA signed, awaiting review, type-documentation

#27563 [3.10] bpo-35183: Add typical examples to os.path.splitext docs (GH-27286)
  Doc/library/os.path.rst
  Misc/NEWS.d/next/Documentation/2021-07-22-08-28-03.bpo-35183.p9BWTB.rst
Labels: CLA signed, awaiting merge, type-documentation

#27536 bpo-44782: Improve OrderedDict recipe for LRU cache variants
  Doc/library/collections.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#27567 [3.9] bpo-44782: Improve OrderedDict recipe for LRU cache variants (GH-27536)
  Doc/library/collections.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27566 [3.10] bpo-44782: Improve OrderedDict recipe for LRU cache variants (GH-27536)
  Doc/library/collections.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27565 [3.10] bpo-44792: Improve syntax errors for if expressions (GH-27506)
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2021-07-31-12-12-57.bpo-44792.mOReTW.rst
  Parser/parser.c
Labels: CLA signed, awaiting merge

#17658 bpo-39091: Fix segfault when Exception constructor returns non-exception for gen.throw
  Lib/test/test_generators.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2019-12-21-14-18-32.bpo-39091.dOexgQ.rst
  Python/errors.c
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.8, needs backport to 3.9

#27572 [3.10] closes bpo-39091: Fix segfault when Exception constructor returns non-exception for gen.throw. (GH-17658)
  Lib/test/test_generators.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2019-12-21-14-18-32.bpo-39091.dOexgQ.rst
  Python/errors.c
Labels: CLA signed, awaiting merge

#27573 [3.9] closes bpo-39091: Fix segfault when Exception constructor returns non-exception for gen.throw. (GH-17658)
  Lib/test/test_generators.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2019-12-21-14-18-32.bpo-39091.dOexgQ.rst
  Python/errors.c
Labels: CLA signed, awaiting merge

#27530 bpo-27275: Change popitem() and pop() methods of collections.OrderedDict
  Lib/collections/__init__.py
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Library/2021-08-01-19-49-09.bpo-27275.QsvE0k.rst
  Objects/odictobject.c
Labels: CLA signed, awaiting core review, type-bugfix

#27471 bpo-41737: expand doc for NotADirectoryError
  Doc/library/exceptions.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#27577 [3.9] bpo-41737: expand doc for NotADirectoryError (GH-27471)
  Doc/library/exceptions.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27576 [3.10] bpo-41737: expand doc for NotADirectoryError (GH-27471)
  Doc/library/exceptions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27571 bpo-44808: fixes test for interactive inspect getsource of a class
  Lib/test/test_inspect.py
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news, type-tests

#27578 [3.10] bpo-44808: fixes test for interactive inspect getsource of a class (GH-27571)
  Lib/test/test_inspect.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#27580 Ensure LICENSE file is regenerated even in PGO builds
  PCbuild/regen.targets
Labels: CLA signed, OS-windows, awaiting merge, needs backport to 3.10, skip issue, skip news, type-bugfix

#27582 [3.10] Ensure LICENSE.txt file is generated even in PGO builds (GH-27580)
  PCbuild/regen.targets
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix

#22454 bpo-41886: Fix documented type of PyType_Type
  Doc/c-api/type.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news, type-documentation

#27583 [3.9] bpo-41886: Fix documented type of PyType_Type (GH-22454)
  Doc/c-api/type.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27584 [3.10] bpo-41886: Fix documented type of PyType_Type (GH-22454)
  Doc/c-api/type.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27575 Add option to write specialization stats to files and script to summarize.
  Include/internal/pycore_code.h
  Python/ceval.c
  Python/specialize.c
  Tools/scripts/summarize_specialization_stats.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#27589 bpo-44821: Eagerly assign __dict__ for new objects.
  Include/internal/pycore_object.h
  Lib/test/test_capi.py
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-04-11-37-38.bpo-44821.67YHGI.rst
  Objects/dictobject.c
  Objects/typeobject.c
Labels: CLA signed, awaiting core review

#27593 bpo-41117: Cleanup subtract_refs()
  Modules/gcmodule.c
Labels: CLA signed, awaiting core review, skip news

#27592 bpo-44760: Fix hyperlink conflict in turtle docs
  Doc/library/turtle.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27581 bpo-44301: Docs: Note that tp_clear and m_clear are not always called
  Doc/c-api/module.rst
  Doc/c-api/typeobj.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#27585 bpo-44801: Check arguments in substitution of ParamSpec in Callable
  Lib/_collections_abc.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-08-03-20-37-45.bpo-44801.i49Aug.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, type-bugfix

#27594 [3.10] bpo-44760: Fix hyperlink conflict in turtle docs (GH-27592)
  Doc/library/turtle.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27596 [3.10] bpo-44301: Note that tp_clear and m_clear are not always called (GH-27581)
  Doc/c-api/module.rst
  Doc/c-api/typeobj.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27597 [3.9] bpo-44301: Note that tp_clear and m_clear are not always called (GH-27581)
  Doc/c-api/module.rst
  Doc/c-api/typeobj.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27320 Fix 404 link to the pyporting mailing list
  Doc/howto/pyporting.rst
Labels: CLA signed, awaiting change review, needs backport to 3.10, needs backport to 3.9, skip issue, skip news, type-documentation

#27600 [3.10] Fix 404 link to the pyporting mailing list (GH-27320)
  Doc/howto/pyporting.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#27601 [3.9] Fix 404 link to the pyporting mailing list (GH-27320)
  Doc/howto/pyporting.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#27602 Fix typo in 'xml.dom.minidom' documentation
  Doc/library/xml.dom.minidom.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9, skip issue, skip news, type-documentation

#26899 [doc] bpo-43066: Zipfile - add note on leading slash in the filename arg
  Doc/library/zipfile.rst
  Misc/NEWS.d/next/Documentation/2021-06-24-14-37-16.bpo-43066.Ti7ahX.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9, type-documentation

#27166 bpo-42958: Update filecmp.cmp docs
  Doc/library/filecmp.rst
  Lib/filecmp.py
  Misc/NEWS.d/next/Documentation/2021-07-15-11-19-03.bpo-42958.gC5IHM.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9

#27603 [3.10] Fix typo in 'xml.dom.minidom' documentation (GH-27602)
  Doc/library/xml.dom.minidom.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#27605 [3.10] [doc] bpo-43066: zipfile - add note on leading slash in the filename arg (GH-26899)
  Doc/library/zipfile.rst
  Misc/NEWS.d/next/Documentation/2021-06-24-14-37-16.bpo-43066.Ti7ahX.rst
Labels: CLA signed, awaiting merge, type-documentation

#27606 [3.9] [doc] bpo-43066: zipfile - add note on leading slash in the filename arg (GH-26899)
  Doc/library/zipfile.rst
  Misc/NEWS.d/next/Documentation/2021-06-24-14-37-16.bpo-43066.Ti7ahX.rst
Labels: CLA signed, awaiting core review, type-documentation

#27607 [3.10] bpo-42958: Improve description of shallow= in filecmp.cmp docs (GH-27166)
  Doc/library/filecmp.rst
  Lib/filecmp.py
  Misc/NEWS.d/next/Documentation/2021-07-15-11-19-03.bpo-42958.gC5IHM.rst
Labels: CLA signed, awaiting merge

#27608 [3.9] bpo-42958: Improve description of shallow= in filecmp.cmp docs (GH-27166)
  Doc/library/filecmp.rst
  Lib/filecmp.py
  Misc/NEWS.d/next/Documentation/2021-07-15-11-19-03.bpo-42958.gC5IHM.rst
Labels: CLA signed, awaiting review

#27598 [3.10] bpo-44801: Check arguments in substitution of ParamSpec in Callable (GH-27585)
  Lib/_collections_abc.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-08-03-20-37-45.bpo-44801.i49Aug.rst
Labels: CLA signed, awaiting merge, type-bugfix

#27610 platform: Import subprocess in function.
  Lib/platform.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#27588 bpo-44822: Don't truncate `str`s with embedded NULL chars returned by `sqlite3` UDF callbacks
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-08-04-12-29-00.bpo-44822.zePNXA.rst
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, type-bugfix

#26490 bpo-44291: Fix reconnection in logging.handlers.SysLogHandler (GH-26490)
  Lib/logging/handlers.py
  Lib/test/test_logging.py
Labels: CLA signed, awaiting review, skip news

#27615 bpo-44838: Refine the custom syntax errors for invalid 'if' expressions
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-05-17-42-03.bpo-44838.r_Lkj_.rst
  Parser/parser.c
Labels: CLA signed, awaiting merge, needs backport to 3.10

#27616 [3.10] bpo-44838: Refine the custom syntax errors for invalid 'if' expressions (GH-27615).
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-05-17-42-03.bpo-44838.r_Lkj_.rst
  Parser/parser.c
Labels: CLA signed, awaiting merge, :robot: automerge

#27618 bpo-44679: [doc] fix typo in unittest.mock.rst
  Doc/library/unittest.mock.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#27620 [3.10] bpo-44679: [doc] fix typo in unittest.mock.rst (GH-27618)
  Doc/library/unittest.mock.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#27065 bpo-44584: Deprecate PYTHONTHREADDEBUG env var
  Doc/using/cmdline.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_threading.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-08-12-18-56.bpo-44584.qKnSqV.rst
  Misc/python.man
  Python/pylifecycle.c
  Python/thread.c
Labels: CLA signed, awaiting core review, needs backport to 3.10

#27624 [3.10] bpo-44584: Deprecate PYTHONTHREADDEBUG env var (GH-27065)
  Doc/using/cmdline.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_threading.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-08-12-18-56.bpo-44584.qKnSqV.rst
  Misc/python.man
  Python/pylifecycle.c
  Python/thread.c
Labels: CLA signed, awaiting merge

#26783 bpo-40928: notify users of osx malloc warnings
  Lib/test/support/__init__.py
  Lib/test/test_decimal.py
  Misc/NEWS.d/next/Tests/2021-08-06-00-07-15.bpo-40928.aIwb6G.rst
Labels: CLA signed, awaiting change review

#27623 bpo-44849: Fix os.set_inheritable() on FreeBSD 14 with O_PATH
  Misc/NEWS.d/next/Library/2021-08-06-13-00-28.bpo-44849.O78F_f.rst
  Python/fileutils.c
Labels: CLA signed, awaiting merge

#27629 [3.9] bpo-40928: notify users running test_decimal on macOS of malloc warnings (GH-26783)
  Lib/test/support/__init__.py
  Lib/test/test_decimal.py
  Misc/NEWS.d/next/Tests/2021-08-06-00-07-15.bpo-40928.aIwb6G.rst
Labels: CLA signed, awaiting core review

#27614 bpo-44524: Fix an issue wherein `_GenericAlias._name` was not properly set for specialforms
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-08-05-18-20-17.bpo-44524.9T1tfe.rst
Labels: type-bugfix, CLA signed, awaiting core review, needs backport to 3.10

#27631 [3.10] bpo-44849: Fix os.set_inheritable() on FreeBSD 14 with O_PATH (GH-27623)
  Misc/NEWS.d/next/Library/2021-08-06-13-00-28.bpo-44849.O78F_f.rst
  Python/fileutils.c
Labels: CLA signed, awaiting merge

#27630 [3.9] bpo-44849: Fix os.set_inheritable() on FreeBSD 14 with O_PATH (GH-27623)
  Misc/NEWS.d/next/Library/2021-08-06-13-00-28.bpo-44849.O78F_f.rst
  Python/fileutils.c
Labels: CLA signed, awaiting merge

#27619 [3.9] bpo-44679: [doc] fix typo in unittest.mock.rst (GH-27618)
  Doc/library/unittest.mock.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#27632 [3.10] bpo-44524: Fix an issue wherein `_GenericAlias._name` was not properly set for specialforms (GH-27614)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-08-05-18-20-17.bpo-44524.9T1tfe.rst
Labels: type-bugfix, CLA signed, awaiting merge

#27628 [3.10] bpo-40928: notify users running test_decimal on macOS of malloc warnings (GH-26783)
  Lib/test/support/__init__.py
  Lib/test/test_decimal.py
  Misc/NEWS.d/next/Tests/2021-08-06-00-07-15.bpo-40928.aIwb6G.rst
Labels: CLA signed, awaiting merge

#27627 [3.9] bpo-43853: Handle sqlite3_value_text() errors (GH-25422).
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-04-15-12-02-17.bpo-43853.XXCVAp.rst
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge

#27611 [3.10] bpo-44822: Don't truncate `str`s with embedded NULL chars returned by `sqlite3` UDF callbacks (GH-27588)
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-08-04-12-29-00.bpo-44822.zePNXA.rst
  Modules/_sqlite/connection.c
Labels: type-bugfix, CLA signed, awaiting merge

#27635 bpo-44756: [docs] revert automated virtual environment creation on `make html`
  Doc/Makefile
  Doc/README.rst
  Misc/NEWS.d/next/Documentation/2021-08-06-19-36-21.bpo-44756.1Ngzon.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27613 bpo-44839: Raise more specific errors in sqlite3
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-08-05-14-59-39.bpo-44839.MURNL9.rst
  Modules/_sqlite/connection.c
Labels: type-enhancement, CLA signed, awaiting core review

#27636 [3.9] bpo-44756: [docs] revert automated virtual environment creation on `make html` (GH-27635)
  Doc/Makefile
  Doc/README.rst
  Misc/NEWS.d/next/Documentation/2021-08-06-19-36-21.bpo-44756.1Ngzon.rst
Labels: CLA signed, awaiting review

#27637 [3.10] bpo-44756: [docs] revert automated virtual environment creation on `make html` (GH-27635)
  Doc/Makefile
  Doc/README.rst
  Misc/NEWS.d/next/Documentation/2021-08-06-19-36-21.bpo-44756.1Ngzon.rst
Labels: CLA signed, awaiting merge

#27633 bpo-44605: Teach @total_ordering() to work with metaclasses
  Lib/functools.py
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Library/2021-08-06-09-43-50.bpo-44605.q4YSBZ.rst
Labels: type-bugfix, CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27641 [3.9] bpo-44605: Teach @total_ordering() to work with metaclasses (GH-27633)
  Lib/functools.py
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Library/2021-08-06-09-43-50.bpo-44605.q4YSBZ.rst
Labels: type-bugfix, CLA signed, awaiting review

#26795 bpo-27752: improve documentation of csv.Dialect
  Doc/library/csv.rst
  Misc/NEWS.d/next/Documentation/2021-06-18-18-04-53.bpo-27752.NEByNk.rst
Labels: CLA signed, type-documentation, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27640 [3.10] bpo-44605: Teach @total_ordering() to work with metaclasses (GH-27633)
  Lib/functools.py
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Library/2021-08-06-09-43-50.bpo-44605.q4YSBZ.rst
Labels: type-bugfix, CLA signed, awaiting merge

#27643 [3.10] bpo-27752: improve documentation of csv.Dialect (GH-26795)
  Doc/library/csv.rst
  Misc/NEWS.d/next/Documentation/2021-06-18-18-04-53.bpo-27752.NEByNk.rst
Labels: CLA signed, type-documentation, awaiting merge

#27644 [3.9] bpo-27752: improve documentation of csv.Dialect (GH-26795)
  Doc/library/csv.rst
  Misc/NEWS.d/next/Documentation/2021-06-18-18-04-53.bpo-27752.NEByNk.rst
Labels: CLA signed, type-documentation, awaiting review

#21917 bpo-41576: document BaseException in favor of bare except
  Doc/tutorial/errors.rst
  Misc/NEWS.d/next/Documentation/2020-08-21-22-59-37.bpo-41576.7a6CQR.rst
Labels: CLA signed, type-documentation, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27639 [3.9] bpo-44822: Don't truncate `str`s with embedded NULL chars returned by `sqlite3` UDF callbacks (GH-27588)
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-08-04-12-29-00.bpo-44822.zePNXA.rst
  Modules/_sqlite/connection.c
Labels: type-bugfix, CLA signed, awaiting merge

#27646 [3.10] bpo-41576: document BaseException in favor of bare except (GH-21917)
  Doc/tutorial/errors.rst
  Misc/NEWS.d/next/Documentation/2020-08-21-22-59-37.bpo-41576.7a6CQR.rst
Labels: CLA signed, type-documentation, awaiting merge

#24419 bpo-42971: Add errno.EQFULL (macOS)
  Doc/library/errno.rst
  Misc/NEWS.d/next/Library/2021-02-02-20-11-14.bpo-42971.OpVoFu.rst
  Modules/errnomodule.c
Labels: CLA signed, OS-mac, awaiting merge, stale

#27647 bpo-44856: Possible reference leak in error paths of update_bases() and __build_class__
  Misc/NEWS.d/next/Core and Builtins/2021-08-07-01-26-12.bpo-44856.9rk3li.rst
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10

#27652 [3.8] bpo-44856: Possible reference leak in error paths of update_bases() and __build_class__ (GH-27647)
  Misc/NEWS.d/next/Core and Builtins/2021-08-07-01-26-12.bpo-44856.9rk3li.rst
  Python/bltinmodule.c
Labels: CLA signed, awaiting review

#27651 [3.9] bpo-44856: Possible reference leak in error paths of update_bases() and __build_class__ (GH-27647)
  Misc/NEWS.d/next/Core and Builtins/2021-08-07-01-26-12.bpo-44856.9rk3li.rst
  Python/bltinmodule.c
Labels: CLA signed, awaiting review

#27653 [3.10] bpo-44856: Possible reference leak in error paths of update_bases() and __build_class__ (GH-27647)
  Misc/NEWS.d/next/Core and Builtins/2021-08-07-01-26-12.bpo-44856.9rk3li.rst
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge

#27664 bpo-44830 - Remove the broken Broken Mozilla devguide link.
  Doc/bugs.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#27665 [3.9] bpo-44830 - Remove the broken Broken Mozilla devguide link. (GH-27664)
  Doc/bugs.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#27654 bpo-44859: Improve error handling in sqlite3 and change some errors
  Lib/sqlite3/test/dbapi.py
  Lib/sqlite3/test/hooks.py
  Lib/sqlite3/test/regression.py
  Lib/sqlite3/test/types.py
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-08-07-17-28-56.bpo-44859.CCopjk.rst
  Modules/_sqlite/clinic/cursor.c.h
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/statement.c
Labels: type-bugfix, CLA signed, type-tests, awaiting core review

#27669 bpo-42053: Remove misleading check in os.fwalk()
  Lib/os.py
Labels: CLA signed, awaiting core review, skip news

#27656 bpo-44840: Compiler: Move duplication of exit blocks with no line numbers to after CFG optimization.
  Lib/test/test_dis.py
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting core review, skip news, needs backport to 3.10

#27590 bpo-44826: Specialize STORE_ATTR
  Include/internal/pycore_code.h
  Include/internal/pycore_dict.h
  Include/opcode.h
  Lib/opcode.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-05-17-49-55.bpo-44826.zQsyK5.rst
  Objects/dictobject.c
  Python/ceval.c
  Python/opcode_targets.h
  Python/specialize.c
Labels: CLA signed, awaiting core review

#27673 [3.10] bpo-44840: Compiler: Move duplication of exit blocks with no line numbers to after CFG optimization. (GH-27656)
  Lib/test/test_dis.py
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting merge, skip news

#21470 bpo-32695: Docs and tests for compresslevel and preset kwargs in tarfile
  Doc/library/tarfile.rst
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Library/2020-07-13-23-46-59.bpo-32695.tTqqXe.rst
Labels: CLA signed, type-tests, type-documentation, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27674 [3.9] bpo-32695: Docs and tests for compresslevel and preset kwargs in tarfile (GH-21470)
  Doc/library/tarfile.rst
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Library/2020-07-13-23-46-59.bpo-32695.tTqqXe.rst
Labels: CLA signed, type-tests, type-documentation, awaiting review

#27675 [3.10] bpo-32695: Docs and tests for compresslevel and preset kwargs in tarfile (GH-21470)
  Doc/library/tarfile.rst
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Library/2020-07-13-23-46-59.bpo-32695.tTqqXe.rst
Labels: CLA signed, type-tests, type-documentation, awaiting merge

#27676 bpo-44702: Remove ambiguity in sentence
  Doc/library/weakref.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, :robot: automerge

#27677 Remove unused variable.
  Python/compile.c
Labels: CLA signed, skip issue, awaiting core review, skip news

#27650 bpo-44522: Fix inaccurate information in open() function
  Doc/library/functions.rst
Labels: CLA signed, type-documentation, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#27680 [3.10] Remove unused variable. (GH-27677)
  Python/compile.c
Labels: CLA signed, skip issue, awaiting merge, skip news

#27681 [3.10] bpo-44522: Fix inaccurate information in open() function (GH-27650)
  Doc/library/functions.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#27682 [3.9] bpo-44522: Fix inaccurate information in open() function (GH-27650)
  Doc/library/functions.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#18034 bpo-38840: Incorrect __all__ in multiprocessing.managers
  Lib/multiprocessing/managers.py
  Misc/NEWS.d/next/Library/2020-01-16-23-41-16.bpo-38840.VzzYZz.rst
Labels: CLA signed, awaiting core review

#21631 bpo-41402: Fix email ContentManager calling .encode() on bytes
  Lib/email/contentmanager.py
  Lib/test/test_email/test_contentmanager.py
  Misc/NEWS.d/next/Library/2020-07-26-18-17-30.bpo-41402.YRkVkp.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27683 bpo-44872: use new trashcan macros in framobject.c
  Misc/NEWS.d/next/Core and Builtins/2021-08-09-16-16-03.bpo-44872.OKRlhK.rst
  Objects/frameobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10

#27684 [3.9] bpo-38840: Incorrect __all__ in multiprocessing.managers (GH-18034)
  Lib/multiprocessing/managers.py
  Misc/NEWS.d/next/Library/2020-01-16-23-41-16.bpo-38840.VzzYZz.rst
Labels: CLA signed, awaiting review

#27685 [3.10] bpo-38840: Incorrect __all__ in multiprocessing.managers (GH-18034)
  Lib/multiprocessing/managers.py
  Misc/NEWS.d/next/Library/2020-01-16-23-41-16.bpo-38840.VzzYZz.rst
Labels: CLA signed, awaiting merge

#27689 bpo-44854: Remove trailing whitespaces
  .github/SECURITY.md
  .github/problem-matchers/sphinx.json
  Doc/tools/templates/search.html
  Modules/_bisectmodule.c
  Modules/_ctypes/_ctypes_test.c
  Modules/_json.c
  Modules/termios.c
  Objects/exceptions.c
  Objects/genericaliasobject.c
  Parser/tokenizer.h
  Python/adaptive.md
  Tools/c-analyzer/c_parser/_state_machine.py
  Tools/c-analyzer/c_parser/preprocessor/__init__.py
Labels: CLA signed, awaiting merge, skip news

#27687 [3.9] bpo-41402: Fix email ContentManager calling .encode() on bytes (GH-21631)
  Lib/email/contentmanager.py
  Lib/test/test_email/test_contentmanager.py
  Misc/NEWS.d/next/Library/2020-07-26-18-17-30.bpo-41402.YRkVkp.rst
Labels: CLA signed, awaiting review

#18272 bpo-39498 Start linking the security warnings in the stdlib modules
  Doc/library/hashlib.rst
  Doc/library/index.rst
  Doc/library/logging.config.rst
  Doc/library/multiprocessing.rst
  Doc/library/security_warnings.rst
  Doc/library/shelve.rst
  Doc/library/subprocess.rst
  Doc/library/tempfile.rst
  Doc/library/zipfile.rst
  Misc/NEWS.d/next/Documentation/2020-01-30-05-18-48.bpo-39498.Nu3sFL.rst
Labels: CLA signed, type-documentation, awaiting core review

#27694 bpo-14853: add back the stdin test, skip if stdin is redirected
  Lib/test/test_file.py
Labels: CLA signed, type-tests, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#27686 [3.10] bpo-41402: Fix email ContentManager calling .encode() on bytes (GH-21631)
  Lib/email/contentmanager.py
  Lib/test/test_email/test_contentmanager.py
  Misc/NEWS.d/next/Library/2020-07-26-18-17-30.bpo-41402.YRkVkp.rst
Labels: CLA signed, awaiting merge

#27696 [3.10] bpo-39498 Start linking the security warnings in the stdlib modules (GH-18272)
  Doc/library/hashlib.rst
  Doc/library/index.rst
  Doc/library/logging.config.rst
  Doc/library/multiprocessing.rst
  Doc/library/security_warnings.rst
  Doc/library/shelve.rst
  Doc/library/subprocess.rst
  Doc/library/tempfile.rst
  Doc/library/zipfile.rst
  Misc/NEWS.d/next/Documentation/2020-01-30-05-18-48.bpo-39498.Nu3sFL.rst
Labels: CLA signed, type-documentation, awaiting merge

#27699 [3.9] bpo-39498 Start linking the security warnings in the stdlib modules (GH-18272)
  Doc/library/hashlib.rst
  Doc/library/index.rst
  Doc/library/logging.config.rst
  Doc/library/multiprocessing.rst
  Doc/library/security_warnings.rst
  Doc/library/shelve.rst
  Doc/library/subprocess.rst
  Doc/library/tempfile.rst
  Doc/library/zipfile.rst
  Misc/NEWS.d/next/Documentation/2020-01-30-05-18-48.bpo-39498.Nu3sFL.rst
Labels: CLA signed, type-documentation, awaiting review

#27691 [3.9] bpo-44872: use new trashcan macros in framobject.c (GH-27683)
  Misc/NEWS.d/next/Core and Builtins/2021-08-09-16-16-03.bpo-44872.OKRlhK.rst
  Objects/frameobject.c
Labels: CLA signed, awaiting core review

#27692 [3.8] bpo-44872: use new trashcan macros in framobject.c (GH-27683)
  Misc/NEWS.d/next/Core and Builtins/2021-08-09-16-16-03.bpo-44872.OKRlhK.rst
  Objects/frameobject.c
Labels: CLA signed, awaiting core review

#27690 [3.10] bpo-44872: use new trashcan macros in framobject.c (GH-27683)
  Misc/NEWS.d/next/Core and Builtins/2021-08-09-16-16-03.bpo-44872.OKRlhK.rst
  Objects/frameobject.c
Labels: CLA signed, awaiting merge

#6990 bpo-33479: Remove unqualified tkinter threadsafe claim.
  Doc/library/tk.rst
  Misc/NEWS.d/next/Documentation/2018-05-19-15-59-29.bpo-33479.4cLlxo.rst
Labels: CLA signed, type-documentation, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27626 bpo-25782: avoid hang in PyErr_SetObject when current exception has a…
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-07-21-39-19.bpo-25782.B22lMx.rst
  Python/errors.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27704 [3.10] bpo-33479: Remove unqualified tkinter threadsafe claim. (GH-6990)
  Doc/library/tk.rst
  Misc/NEWS.d/next/Documentation/2018-05-19-15-59-29.bpo-33479.4cLlxo.rst
Labels: CLA signed, type-documentation, awaiting merge

#27703 [3.9] bpo-33349: make lib2to3 parse async generators everywhere (GH-6588)
  Lib/lib2to3/pgen2/tokenize.py
  Lib/lib2to3/tests/test_parser.py
  Misc/NEWS.d/next/Library/2018-04-24-14-25-07.bpo-33349.Y_0LIr.rst
Labels: CLA signed, awaiting review

#27705 [3.9] bpo-33479: Remove unqualified tkinter threadsafe claim. (GH-6990)
  Doc/library/tk.rst
  Misc/NEWS.d/next/Documentation/2018-05-19-15-59-29.bpo-33479.4cLlxo.rst
Labels: CLA signed, type-documentation, awaiting review

#27708 bpo-44826: Fix stats for STORE_ATTR specialization.
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#27707 [3.9] bpo-25782: avoid hang in PyErr_SetObject when current exception has a cycle in its context chain (GH-27626)
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-07-21-39-19.bpo-25782.B22lMx.rst
  Python/errors.c
Labels: CLA signed, awaiting review

#27698 [3.9] bpo-14853: add back the stdin test, skip if stdin is redirected (GH-27694)
  Lib/test/test_file.py
Labels: CLA signed, type-tests, awaiting review, skip news

#27702 [3.10] bpo-33349: make lib2to3 parse async generators everywhere (GH-6588)
  Lib/lib2to3/pgen2/tokenize.py
  Lib/lib2to3/tests/test_parser.py
  Misc/NEWS.d/next/Library/2018-04-24-14-25-07.bpo-33349.Y_0LIr.rst
Labels: CLA signed, awaiting merge

#27706 [3.10] bpo-25782: avoid hang in PyErr_SetObject when current exception has a cycle in its context chain (GH-27626)
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-07-21-39-19.bpo-25782.B22lMx.rst
  Python/errors.c
Labels: CLA signed, awaiting merge

#27701 Classify specialization failures. Provides more useful stats, with lower overhead.
  Include/internal/pycore_code.h
  Lib/test/test__opcode.py
  Python/specialize.c
  Tools/scripts/summarize_specialization_stats.py
Labels: CLA signed, skip issue, awaiting merge, skip news

#27638 bpo-44854: Add .editorconfig file to help enforce `make patchcheck`
  .editorconfig
Labels: CLA signed, awaiting merge, skip news, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10
