Repository python/cpython, pull requests merged in 2021-02, with the labels that each got.

#24341 bpo-42504: Ensure that get_config_var('MACOSX_DEPLOYMENT_TARGET') is a string
  Lib/distutils/spawn.py
  Lib/distutils/tests/test_build_ext.py
  Lib/sysconfig.py
  Lib/test/test_posix.py
  Misc/NEWS.d/next/macOS/2021-01-26-14-36-11.bpo-42504.ZxWt71.rst
  setup.py
Labels: CLA signed, OS-mac, awaiting merge, needs backport to 3.9

#24410 [3.9] bpo-42504: Ensure that get_config_var('MACOSX_DEPLOYMENT_TARGET') is a string (GH-24341)
  Lib/distutils/spawn.py
  Lib/distutils/tests/test_build_ext.py
  Lib/sysconfig.py
  Lib/test/test_posix.py
  Misc/NEWS.d/next/macOS/2021-01-26-14-36-11.bpo-42504.ZxWt71.rst
  setup.py
Labels: CLA signed, awaiting review

#23888 [3.9] bpo-42688: Fix ffi alloc/free when using external libffi on macos (GH-23868)
  Modules/_ctypes/malloc_closure.c
Labels: CLA signed, awaiting review, skip news

#24408 [3.8] bpo-43016: Fix test_curses on platform without cursesw (GH-24405)
  Lib/test/test_curses.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#24407 [3.9] bpo-43016: Fix test_curses on platform without cursesw (GH-24405)
  Lib/test/test_curses.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#24368 bpo-42990: Further refactoring of PyEval_ functions.
  Include/cpython/frameobject.h
  Include/eval.h
  Include/internal/pycore_ceval.h
  Misc/NEWS.d/next/Core and Builtins/2021-01-30-11-31-44.bpo-42990.69h_zK.rst
  Objects/call.c
  Objects/frameobject.c
  Objects/funcobject.c
  Python/bltinmodule.c
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#24309 Fix typo in Lib/trace.py
  Lib/trace.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#24121 bpo-42834: Make static cache variables in _json.c compatible with subinterpreters
  Misc/NEWS.d/next/Library/2021-01-05-23-55-24.bpo-42834.LxRnZC.rst
  Modules/_json.c
Labels: CLA signed, awaiting review

#24348 bpo-38307: Add end_lineno attribute to pyclbr _Objects
  Doc/whatsnew/3.10.rst
  Lib/idlelib/idle_test/test_browser.py
  Lib/pyclbr.py
  Lib/test/test_pyclbr.py
  Misc/NEWS.d/next/Library/2020-03-16-03-03-21.bpo-38307.2cmw2i.rst
Labels: CLA signed, awaiting review, type-enhancement

#24072 bpo-41748: Handles unquoted attributes with commas
  Lib/html/parser.py
  Lib/test/test_htmlparser.py
  Misc/NEWS.d/next/Library/2021-01-05-21-26-29.bpo-41748.KdC0w3.rst
Labels: :robot: automerge, CLA signed, awaiting change review, needs backport to 3.8, needs backport to 3.9, type-bugfix

#24416 [3.8] bpo-41748: Handles unquoted attributes with commas (GH-24072)
  Lib/html/parser.py
  Lib/test/test_htmlparser.py
  Misc/NEWS.d/next/Library/2021-01-05-21-26-29.bpo-41748.KdC0w3.rst
Labels: CLA signed, awaiting merge, type-bugfix

#24415 [3.9] bpo-41748: Handles unquoted attributes with commas (GH-24072)
  Lib/html/parser.py
  Lib/test/test_htmlparser.py
  Misc/NEWS.d/next/Library/2021-01-05-21-26-29.bpo-41748.KdC0w3.rst
Labels: CLA signed, awaiting merge, type-bugfix

#24417 bpo-42899: Only eliminate jumps to successor block if jump is unconditional.
  Lib/test/test_bool.py
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#24292 bpo-42997: Improve error message for missing : before suites
  Doc/tools/extensions/peg_highlight.py
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-01-24-20-19-55.bpo-42997.QUOPgP.rst
  Parser/parser.c
  Parser/pegen.c
  Parser/pegen.h
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/grammar.py
  Tools/peg_generator/pegen/grammar_parser.py
  Tools/peg_generator/pegen/metagrammar.gram
Labels: CLA signed, awaiting merge

#21201 bpo-41149 Fix a bug in threading that causes threads to fail to start.
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Library/2020-06-28-16-13-02.bpo-41149.jiZWtJ.rst
Labels: CLA signed, awaiting merge

#24420 bpo-43108: Fix a reference leak in the curses module
  Misc/NEWS.d/next/Library/2021-02-02-20-23-31.bpo-43108.lqcCZ6.rst
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting core review

#23513 bpo-8264: Document hasattr and getattr behavior for private attributes
  Doc/library/functions.rst
  Doc/reference/expressions.rst
Labels: CLA signed, awaiting merge, skip news, stale, type-documentation

#24422 Add link to Microsoft docs for limitations in Windows Store package
  Doc/using/windows.rst
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#24425 [3.8] Add link to Microsoft docs for limitations in Windows Store package (GH-24422)
  Doc/using/windows.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24424 [3.9] Add link to Microsoft docs for limitations in Windows Store package (GH-24422)
  Doc/using/windows.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24394 bpo-43082: Remove redundant 'the' in Descriptor howto
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#24427 [3.9] bpo-43082: Remove redundant 'the' in Descriptor howto (GH-24394)
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24430 [3.9] bpo-43108: Fix a reference leak in the curses module (GH-24420)
  Misc/NEWS.d/next/Library/2021-02-02-20-23-31.bpo-43108.lqcCZ6.rst
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting merge

#23019 Fix typo
  Lib/datetime.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#24434 [3.8] Fix typo (GH-23019)
  Lib/datetime.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#24435 [3.9] Fix typo (GH-23019)
  Lib/datetime.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#24436 bpo-43121: Fix incorrect SyntaxError message for missing comma
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-02-03-22-33-05.bpo-43121.jqcViq.rst
  Parser/parser.c
Labels: CLA signed, awaiting core review

#24428 bpo-43106: Add os.O_EVTONLY/O_FSYNC/O_SYMLINK/O_NOFOLLOW_ANY
  Doc/library/os.rst
  Doc/whatsnew/3.10.rst
  Misc/NEWS.d/next/Library/2021-02-03-17-06-38.bpo-43106.SwcSuU.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#24437 [3.8] bpo-42773: fix tests not being run on pushes (GH-24004)
  .github/workflows/build.yml
Labels: CLA signed, awaiting merge, skip news

#24438 [3.9] bpo-42773: fix tests not being run on pushes (GH-24004)
  .github/workflows/build.yml
Labels: CLA signed, awaiting merge, skip news

#24445 [3.8] build(deps): bump actions/upload-artifact from v2.2.1 to v2.2.2 (GH-24411)
  .github/workflows/doc.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#24444 [3.9] build(deps): bump actions/upload-artifact from v2.2.1 to v2.2.2 (GH-24411)
  .github/workflows/doc.yml
Labels: CLA signed, awaiting merge, skip issue, skip news

#24443 Fix dependabot.yml file
  .github/dependabot.yml
Labels: CLA signed, awaiting core review, skip issue, skip news

#24441 Fix compiler warnings in MSVC for winreg.c
  PC/winreg.c
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#24440 bpo-42882: Fix compiler warnings in MSVC
  Python/pystate.c
Labels: CLA signed, awaiting review, skip news

#24439 bpo-43102: Set namedtuple __new__'s internal builtins to a dict.
  Lib/collections/__init__.py
  Lib/test/test_collections.py
  Misc/NEWS.d/next/Library/2021-02-03-22-55-27.bpo-43102.TSlZ6J.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, type-bugfix

#24452 [3.9] bpo-43102: Set namedtuple __new__'s internal builtins to a dict. (GH-24439)
  Lib/collections/__init__.py
  Lib/test/test_collections.py
  Misc/NEWS.d/next/Library/2021-02-03-22-55-27.bpo-43102.TSlZ6J.rst
Labels: CLA signed, awaiting review, type-bugfix

#24453 bpo-35295: Remove outdated comment.
  Include/cpython/unicodeobject.h
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#24454 [3.9] bpo-35295: Remove outdated comment. (GH-24453)
  Include/cpython/unicodeobject.h
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#24455 Reduce overhead on random timings
  Lib/random.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#24456 Minor readability improvements. Also note performance impact of __slots__.
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#24450 bpo-43132: Fix incorrect handling of PyObject_RichCompareBool() in _zoneinfo
  Modules/_zoneinfo.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-bugfix

#24423 Fix a typo in a deprecation warning
  Lib/distutils/__init__.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#24457 [3.9] bpo-43132: Fix incorrect handling of PyObject_RichCompareBool() in _zoneinfo (GH-24450)
  Modules/_zoneinfo.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#24448 Simple typo fix
  Doc/howto/urllib2.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#24458 [3.9] Simple typo fix (GH-24448)
  Doc/howto/urllib2.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24459 [3.8] Simple typo fix (GH-24448)
  Doc/howto/urllib2.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24469 bpo-16781: In 'exec' doc, add 'nonlocal' to 'yield' and 'return'
  Doc/library/functions.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24471 [3.8] bpo-16781: In 'exec' doc, add 'nonlocal' to 'yield' and 'return' (GH-2446)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24470 [3.9] bpo-16781: In 'exec' doc, add 'nonlocal' to 'yield' and 'return' (GH-2446)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24467 bpo-43149: Improve error message for exception group without parentheses
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-02-07-03-27-14.bpo-43149.0umPKD.rst
  Parser/parser.c
Labels: CLA signed, awaiting merge

#24462 bpo-43147: Remove archaic terminology.
  Doc/library/statistics.rst
  Lib/statistics.py
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#20239 bpo-40692: Run more test_concurrent_futures tests
  Lib/compileall.py
  Lib/concurrent/futures/process.py
  Lib/multiprocessing/resource_tracker.py
  Lib/test/test_compileall.py
  Lib/test/test_concurrent_futures.py
  Misc/NEWS.d/next/Core and Builtins/2020-05-19-22-10-05.bpo-40692.ajEhrR.rst
Labels: CLA signed, awaiting merge

#24189 bpo-13501: allow choosing between readline and libedit
  Misc/NEWS.d/next/Build/2021-01-10-22-25-23.bpo-13501.g4L-6R.rst
  Modules/readline.c
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed, awaiting merge

#24486 bpo-43162: [Enum] deprecate enum member.member access
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-02-08-16-27-00.bpo-43162.t-W7h3.rst
Labels: CLA signed, awaiting core review

#24301 Improve docs of PEP 604 Union
  Doc/library/functions.rst
  Doc/library/stdtypes.rst
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24224 bpo-41824: Add versionadded for typing.ForwardRef docs
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24493 [3.9] bpo-41824: Add versionadded for typing.ForwardRef docs (GH-24224)
  Doc/library/typing.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#24494 [3.8] bpo-41824: Add versionadded for typing.ForwardRef docs (GH-24224)
  Doc/library/typing.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#24495 [3.8] bpo-41824: Fix indentation issue in ForwardRef docs
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24485 bpo-43166 Disable ceval.c optimisations for Windows debug builds
  Include/pyport.h
Labels: CLA signed, OS-windows, awaiting merge, skip news

#24483 bpo-43163: Handle unclosed parentheses in codeop
  Lib/codeop.py
  Lib/test/test_codeop.py
  Misc/NEWS.d/next/Library/2021-02-08-21-13-51.bpo-43163.E2MgzH.rst
Labels: CLA signed, awaiting merge

#23056 bpo-42217: compiler: merge same co_code and co_linetable objects
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2020-10-31-16-54-00.bpo-42217.GdcHe5.rst
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
Labels: CLA signed, awaiting core review

#24496 Fix link to sqlite3 enable_shared_cache documentation
  Doc/whatsnew/3.10.rst
Labels: CLA not signed, awaiting merge, skip issue, skip news, type-documentation

#24503 bpo-40956: [regression] first argument in sqlite3.Connection.backup is mandatory
  Lib/sqlite3/test/backup.py
  Misc/NEWS.d/next/Library/2021-02-10-23-29-50.bpo-40956.LcAbwG.rst
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge

#24498 bpo-43174: Windows: Use /utf-8 compiler option.
  Misc/NEWS.d/next/Build/2021-02-10-14-11-53.bpo-43174.F9zwXQ.rst
  PCbuild/pyproject.props
Labels: CLA signed, OS-windows, awaiting merge

#24508 bpo-43202: Immediately return code object in codeop._maybe_compile
  Lib/codeop.py
Labels: CLA signed, awaiting merge, skip news, type-enhancement

#24513 [3.9] bpo-43174: Windows: Use /utf-8 compiler option. (GH-24498)
  Misc/NEWS.d/next/Build/2021-02-10-14-11-53.bpo-43174.F9zwXQ.rst
  PCbuild/pyproject.props
Labels: CLA signed, awaiting merge

#24507 bpo-43204: Fix LibTomCrypt URL in md5module.c and sha*module.c comments
  Modules/md5module.c
  Modules/sha1module.c
  Modules/sha256module.c
  Modules/sha512module.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news

#24515 [3.9] bpo-43204: Fix LibTomCrypt URL in md5module.c and sha*module.c comments (GH-24507)
  Modules/md5module.c
  Modules/sha1module.c
  Modules/sha256module.c
  Modules/sha512module.c
Labels: CLA signed, awaiting merge, skip news

#24499 bpo-43172: readline now passes its tests when built against libedit
  Doc/library/readline.rst
  Lib/test/test_readline.py
  Misc/NEWS.d/next/Library/2021-02-10-06-00-53.bpo-43172.ZMCJni.rst
  Modules/clinic/readline.c.h
  Modules/readline.c
Labels: CLA signed, awaiting core review, type-bugfix, type-tests

#24505 bpo-43200: Fix a link to shutil.copy() in the shutil module docs
  Doc/library/shutil.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24524 [3.8] bpo-43200: Fix link to shutil.copy() in the shutil doc (GH-24505)
  Doc/library/shutil.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24523 [3.9] bpo-43200: Fix link to shutil.copy() in the shutil doc (GH-24505)
  Doc/library/shutil.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24512 bpo-43202: More codeop._maybe_compile clean-ups
  Lib/codeop.py
Labels: CLA signed, awaiting merge, skip news, type-performance

#24473 bpo-43152: Update assert statement to remove unused warning
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#24518 bpo-43210: Fix byteswap comment in sha512module.c
  Modules/sha512module.c
Labels: CLA signed, awaiting merge, skip news

#24516 [3.8] bpo-43204: Fix LibTomCrypt URL in md5module.c and sha*module.c comments (GH-24507)
  Modules/md5module.c
  Modules/sha1module.c
  Modules/sha256module.c
  Modules/sha512module.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#24297 bpo-42967: only use '&' as a query string separator
  Doc/library/cgi.rst
  Doc/library/urllib.parse.rst
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.6.rst
  Doc/whatsnew/3.7.rst
  Doc/whatsnew/3.8.rst
  Doc/whatsnew/3.9.rst
  Lib/cgi.py
  Lib/test/test_cgi.py
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2021-02-14-15-59-16.bpo-42967.YApqDS.rst
Labels: CLA signed, awaiting merge

#24533 bpo-43181: Make PyObject_TypeCheck a static inline function
  Doc/c-api/object.rst
  Include/object.h
  Misc/NEWS.d/next/Core and Builtins/2021-02-11-11-37-14.bpo-43181.ydv33S.rst
Labels: CLA signed, awaiting review

#24536 bpo-42967: Fix urllib.parse docs and make logic clearer
  Doc/library/urllib.parse.rst
  Doc/whatsnew/3.6.rst
  Doc/whatsnew/3.8.rst
  Doc/whatsnew/3.9.rst
  Lib/urllib/parse.py
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24528 [3.9] bpo-42967: only use '&' as a query string separator (GH-24297)
  Doc/library/cgi.rst
  Doc/library/urllib.parse.rst
  Doc/whatsnew/3.6.rst
  Doc/whatsnew/3.7.rst
  Doc/whatsnew/3.8.rst
  Doc/whatsnew/3.9.rst
  Lib/cgi.py
  Lib/test/test_cgi.py
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2021-02-14-15-59-16.bpo-42967.YApqDS.rst
Labels: CLA signed, awaiting core review

#24529 [3.8] bpo-42967: only use '&' as a query string separator (GH-24297)
  Doc/library/cgi.rst
  Doc/library/urllib.parse.rst
  Doc/whatsnew/3.6.rst
  Doc/whatsnew/3.7.rst
  Doc/whatsnew/3.8.rst
  Lib/cgi.py
  Lib/test/test_cgi.py
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2021-02-14-15-59-16.bpo-42967.YApqDS.rst
Labels: CLA signed, awaiting core review

#24531 [3.7] bpo-42967: only use '&' as a query string separator (GH-24297)
  Doc/library/cgi.rst
  Doc/library/urllib.parse.rst
  Doc/whatsnew/3.6.rst
  Doc/whatsnew/3.7.rst
  Lib/cgi.py
  Lib/test/test_cgi.py
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2021-02-14-15-59-16.bpo-42967.YApqDS.rst
Labels: CLA signed, awaiting core review

#24429 [3.8] bpo-43108: Fix a reference leak in the curses module (GH-24420)
  Misc/NEWS.d/next/Library/2021-02-02-20-23-31.bpo-43108.lqcCZ6.rst
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting merge

#24532 [3.6] bpo-42967: only use '&' as a query string separator (GH-24297)
  Doc/library/cgi.rst
  Doc/library/urllib.parse.rst
  Doc/whatsnew/3.6.rst
  Lib/cgi.py
  Lib/test/test_cgi.py
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2021-02-14-15-59-16.bpo-42967.YApqDS.rst
Labels: CLA signed, awaiting core review

#24539 bpo-43231: Fix test.test_curses.TestCurses.test_init_pair when running under -R
  Lib/test/test_curses.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#24541 bpo-43231: Correctly calculate the curses color pair limit when checking for it
  Lib/test/test_curses.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#24520 [3.9] Minor improvements to the convolve() recipe (GH-24012)
  Doc/library/itertools.rst
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#24511 Add a warning block around the get_referrers() documentation
  Doc/library/gc.rst
Labels: CLA signed, awaiting core review, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#24543 [3.8] Add a warning block around the get_referrers() documentation (GH-24511)
  Doc/library/gc.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24108 bpo-42819: disable Readline bracketed paste
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2021-01-04-23-54-34.bpo-42819.4KO6wU.rst
  Modules/readline.c
Labels: CLA signed, awaiting merge

#24546 [3.8] bpo-42819, readline: Disable bracketed paste (GH-24108)
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2021-01-04-23-54-34.bpo-42819.4KO6wU.rst
  Modules/readline.c
Labels: CLA signed, awaiting merge

#24500 bpo-43155: Add PyCMethod_New to PC/python3dll.c
  Misc/NEWS.d/next/Windows/2021-02-10-04-16-51.bpo-43155.O1tURk.rst
  PC/python3dll.c
Labels: CLA signed, awaiting merge

#24545 [3.9] bpo-42819, readline: Disable bracketed paste (GH-24108)
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2021-01-04-23-54-34.bpo-42819.4KO6wU.rst
  Modules/readline.c
Labels: CLA signed, awaiting merge

#24544 [3.7] Add a warning block around the get_referrers() documentation (GH-24511)
  Doc/library/gc.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24535 bpo-40170: Convert PyDescr_IsData macro to C function
  Doc/c-api/descriptor.rst
  Include/descrobject.h
  Misc/NEWS.d/next/Core and Builtins/2021-02-15-13-41-14.bpo-40170.r2FAtl.rst
  Objects/descrobject.c
Labels: CLA signed, awaiting merge

#23988 bpo-35134: Add Include/cpython/pytime.h file
  Include/Python.h
  Include/cpython/pytime.h
  Makefile.pre.in
  Modules/gcmodule.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: CLA signed, awaiting review, skip news

#24548 bpo-40170: Convert PyIter_Check macro to a function
  Doc/c-api/iter.rst
  Include/abstract.h
  Include/cpython/abstract.h
  Misc/NEWS.d/next/Core and Builtins/2021-02-15-15-06-43.bpo-40170.ZYeSii.rst
  Objects/abstract.c
Labels: CLA signed, awaiting review

#24418 bpo-43103: Add configure --without-static-libpython
  Doc/whatsnew/3.10.rst
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2021-02-02-16-26-44.bpo-43103.VWeyP_.rst
  Tools/scripts/smelly.py
  Tools/scripts/stable_abi.py
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#24553 bpo-40170: Always define PyExceptionClass_Name as a function
  Include/cpython/pyerrors.h
  Misc/NEWS.d/next/C API/2021-02-16-22-29-39.bpo-40170.ahHmOo.rst
  Objects/exceptions.c
Labels: CLA signed, awaiting review

#24554 [3.9] bpo-43155: Add PyCMethod_New to PC/python3dll.c (GH-24500)
  Misc/NEWS.d/next/Windows/2021-02-10-04-16-51.bpo-43155.O1tURk.rst
  PC/python3.def
Labels: CLA signed, awaiting review

#24555 bpo-40170: Move 3 NEWS entries to the C API section
  Misc/NEWS.d/next/C API/2021-02-11-11-37-14.bpo-43181.ydv33S.rst
  Misc/NEWS.d/next/C API/2021-02-15-13-41-14.bpo-40170.r2FAtl.rst
  Misc/NEWS.d/next/C API/2021-02-15-15-06-43.bpo-40170.ZYeSii.rst
Labels: CLA signed, awaiting review, skip news

#24550 bpo-35134: Move Include/{pyarena.h,pyctype.h} to Include/cpython
  Include/Python.h
  Include/cpython/pyarena.h
  Include/cpython/pyctype.h
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2021-02-17-18-51-26.bpo-35134.YoQdk8.rst
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Parser/pegen.h
  Tools/scripts/stable_abi.py
Labels: CLA signed, awaiting review

#24559 bpo-42990: Add __builtins__ attribute to functions
  Doc/library/inspect.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_collections.py
  Lib/test/test_funcattrs.py
  Misc/NEWS.d/next/Core and Builtins/2021-02-17-19-02-21.bpo-42990.SKXHiI.rst
  Objects/funcobject.c
Labels: CLA signed, awaiting core review

#24251 bpo-42960: resources module, adding RLIMIT_KQUEUES constant from FreeBSD
  Doc/library/resource.rst
  Misc/NEWS.d/next/Library/2021-01-18-21-07-20.bpo-42960.a7Dote.rst
  Modules/resource.c
Labels: CLA signed, awaiting merge, stale

#24562 bpo-43249: sqlite3_column_bytes() must follow sqlite_column_blob()
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting merge, skip news

#24565 bpo-43249: Improve scoping
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting merge, skip news

#24566 bpo-42990: Refactor _PyFrame_New_NoTrack()
  Doc/c-api/function.rst
  Include/cpython/frameobject.h
  Include/internal/pycore_ceval.h
  Objects/frameobject.c
  Objects/funcobject.c
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#24552 Remove all links to mingw.org
  Doc/install/index.rst
  Doc/using/windows.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#24568 [3.8] Remove all links to mingw.org (GH-24552)
  Doc/install/index.rst
  Doc/using/windows.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24567 [3.9] Remove all links to mingw.org (GH-24552)
  Doc/install/index.rst
  Doc/using/windows.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#18174 bpo-39448: Add regen-frozen makefile target.
  Lib/ctypes/test/test_values.py
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2020-01-24-12-54-22.bpo-39448.k4pv14.rst
  Python/frozen.c
  Python/frozen_hello.h
  Tools/freeze/regen_frozen.py
Labels: CLA signed, awaiting merge

#24563 bpo-43254: Fix broken *snprintf() man page links
  Doc/c-api/conversion.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24572 [3.8] closes bpo-43254: Fix *snprintf() man page refs. (GH-24563)
  Doc/c-api/conversion.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24571 [3.9] closes bpo-43254: Fix *snprintf() man page refs. (GH-24563)
  Doc/c-api/conversion.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24569 bpo-43258: Prevent needless allocation of sqlite3 aggregate context for empty queries
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-02-18-23-30-52.bpo-43258.LeU-q8.rst
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge

#24574 bpo-43258: Fix sqlite3 UDF callback scoping
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge, skip news

#24576 bpo-43268: Replace _PyThreadState_GET() with _PyInterpreterState_GET()
  Include/internal/pycore_long.h
  Include/internal/pycore_object.h
  Modules/faulthandler.c
Labels: CLA signed, awaiting core review, skip news

#24575 bpo-40522: Replace PyThreadState_GET() with PyThreadState_Get()
  Include/cpython/abstract.h
  Include/cpython/object.h
Labels: CLA signed, awaiting core review, skip news

#24577 bpo-43268: _Py_IsMainInterpreter() now expects interp
  Include/internal/pycore_pystate.h
  Objects/longobject.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Python/ceval.c
  Python/context.c
  Python/import.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: CLA signed, awaiting core review, skip news

#24581 bpo-43268: Remove abuse usage of tstate in sysmodule.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review, skip news

#24579 bpo-43270: Remove private _PyErr_OCCURRED() macro
  Include/pyerrors.h
  Misc/NEWS.d/next/C API/2021-02-19-14-28-26.bpo-43270.UKx4XN.rst
  Python/ceval.c
Labels: CLA signed, awaiting core review

#24580 bpo-43268: Pass interp rather than tstate
  Include/internal/pycore_ceval.h
  Include/internal/pycore_context.h
  Include/internal/pycore_gc.h
  Include/internal/pycore_pylifecycle.h
  Include/internal/pycore_warnings.h
  Modules/atexitmodule.c
  Modules/gcmodule.c
  Objects/bytesobject.c
  Objects/dictobject.c
  Objects/exceptions.c
  Objects/floatobject.c
  Objects/frameobject.c
  Objects/genobject.c
  Objects/listobject.c
  Objects/longobject.c
  Objects/sliceobject.c
  Objects/tupleobject.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Python/_warnings.c
  Python/bltinmodule.c
  Python/ceval.c
  Python/ceval_gil.h
  Python/context.c
  Python/import.c
  Python/initconfig.c
  Python/pylifecycle.c
  Python/pystate.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review, skip news

#24583 bpo-43268: local_clear() uses _PyInterpreterState_GET()
  Modules/_threadmodule.c
Labels: CLA signed, awaiting core review, skip news

#24561 bpo-35134: Move non-limited C API files to Include/cpython/
  Doc/whatsnew/3.10.rst
  Include/Python.h
  Include/cpython/odictobject.h
  Include/cpython/parser_interface.h
  Include/cpython/picklebufobject.h
  Include/cpython/pydebug.h
  Include/cpython/pyfpe.h
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2021-02-18-18-46-42.bpo-35134.dFpEDT.rst
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Parser/peg_api.c
  Python/pythonrun.c
  Tools/scripts/stable_abi.py
Labels: CLA signed, awaiting review

#24573 bpo-43266: Improve "String conversion and formatting" formatting
  Doc/c-api/conversion.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24584 [3.9] closes bpo-43266: Improve array formatting. (GH-24573)
  Doc/c-api/conversion.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24098 bpo-42825: Enable /OPT:REF
  PCbuild/pyproject.props
Labels: CLA signed, awaiting review, skip news, stale

#24514 bpo-43042: Augment tutorial sentence
  Doc/tutorial/controlflow.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24590 [3.8] bpo-43042: Augment tutorial sentence (GH-24514)
  Doc/tutorial/controlflow.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24589 [3.9] bpo-43042: Augment tutorial sentence (GH-24514)
  Doc/tutorial/controlflow.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24591 [3.9] bpo-43272: Fix old parser test failures for backported grammar constructs
  Lib/test/test_fstring.py
  Lib/test/test_named_expressions.py
  Lib/test/test_unpack_ex.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#24509 Fix typo in dis lib doc
  Doc/library/dis.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#24594 [3.8] Fix typo in dis module doc (GH-24509)
  Doc/library/dis.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24593 [3.9] Fix typo in dis module doc (GH-24509)
  Doc/library/dis.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24497 Fix typo in launcher.c
  PC/launcher.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#24564 bpo-42990: Functions inherit current builtins
  Doc/whatsnew/3.10.rst
  Include/internal/pycore_ceval.h
  Lib/test/test_funcattrs.py
  Misc/NEWS.d/next/Core and Builtins/2021-02-18-15-12-30.bpo-42990.toAqBH.rst
  Objects/frameobject.c
  Objects/funcobject.c
  Python/ceval.c
Labels: CLA signed, awaiting core review

#24598 bpo-43277: Add PySet_CheckExact to the C-API
  Doc/c-api/set.rst
  Doc/whatsnew/3.10.rst
  Include/setobject.h
  Misc/NEWS.d/next/Core and Builtins/2021-02-20-16-50-22.bpo-43277.FXkRXk.rst
  Objects/dictobject.c
  Objects/setobject.c
Labels: :robot: automerge, CLA signed, awaiting merge

#24578 bpo-43269: Clean up sqlite3 file scope
  Modules/_sqlite/cache.c
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/prepare_protocol.c
  Modules/_sqlite/row.c
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting merge, skip news

#24595 bpo-27646: Say that 'yield from' expression can be any iterable
  Doc/reference/expressions.rst
  Misc/NEWS.d/next/Documentation/2021-02-20-00-09-13.bpo-27646.HRsmo-.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-documentation

#24603 [3.8] bpo-27646: Say that 'yield from' expression can be any iterable (GH-24595)
  Doc/reference/expressions.rst
  Misc/NEWS.d/next/Documentation/2021-02-20-00-09-13.bpo-27646.HRsmo-.rst
Labels: CLA signed, awaiting merge, type-documentation

#24602 [3.9] bpo-27646: Say that 'yield from' expression can be any iterable (GH-24595)
  Doc/reference/expressions.rst
  Misc/NEWS.d/next/Documentation/2021-02-20-00-09-13.bpo-27646.HRsmo-.rst
Labels: CLA signed, awaiting merge, type-documentation

#24604 bpo-43283: Rearrange some IDLE doc paragraphs.
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24608 [3.8] bpo-43283: Rearrange some IDLE doc paragraphs. (GH-24604)
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24607 [3.9] bpo-43283: Rearrange some IDLE doc paragraphs. (GH-24604)
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24605 bpo-43269: Remove redundant extern keywords
  Modules/_sqlite/cache.c
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/prepare_protocol.c
  Modules/_sqlite/row.c
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting merge, skip news

#24582 bpo-42093: Cleanup _PyDict_GetItemHint()
  Objects/dictobject.c
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#24612 bpo-43288: Fix test_importlib test to correctly skip
  Lib/test/test_importlib/fixtures.py
  Misc/NEWS.d/next/Tests/2021-02-21-11-11-53.bpo-43288.LfTvL-.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news

#24614 Fix failed merge of bpo-43288.
  Lib/test/test_importlib/fixtures.py
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news, type-tests
