Repository python/cpython, pull requests merged in 2021-10, with the labels that each got.

#28664 bpo-45020: Add more test cases for frozen modules.
  Lib/__phello__.foo.py
  Lib/__phello__/__init__.py
  Lib/__phello__/ham/__init__.py
  Lib/__phello__/ham/eggs.py
  Lib/__phello__/spam.py
  Lib/test/test_frozen.py
  Lib/test/test_importlib/frozen/test_finder.py
  Makefile.pre.in
  PCbuild/_freeze_module.vcxproj
  PCbuild/_freeze_module.vcxproj.filters
  Python/frozen.c
  Tools/scripts/freeze_modules.py
  Tools/scripts/generate_stdlib_module_names.py
Labels: CLA signed, awaiting core review, skip news

#28665 Also install __phello__, in addition to __hello__.
  Makefile.pre.in
Labels: CLA signed, skip issue, awaiting core review, skip news

#28668 [3.10] bpo-45229: Make datetime tests discoverable (GH-28615)
  Lib/test/test_datetime.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#28662 bpo-41710: PyThread_acquire_lock_timed() uses sem_clockwait()
  Doc/whatsnew/3.11.rst
  Misc/NEWS.d/next/Library/2021-09-30-23-00-18.bpo-41710.svuloZ.rst
  Python/thread_pthread.h
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting merge

#28661 bpo-45310: Fix parrallel shared memory tests
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, type-tests, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28667 Revert "bpo-45229: Revert "Make datetime tests discoverable""
  Lib/test/test_datetime.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#28666 [3.9] Revert "[3.9] Revert "[3.9] bpo-45229: Make datetime tests discoverable (GH-28615) (GH-28645)""
  Lib/test/test_datetime.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#28670 [3.9] bpo-45310: Fix parrallel shared memory tests (GH-28661)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#28669 [3.10] bpo-45310: Fix parrallel shared memory tests (GH-28661)
  Lib/test/_test_multiprocessing.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#28294 bpo-45125: Improves pickling docs and tests for `shared_memory`
  Doc/library/multiprocessing.shared_memory.rst
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2021-09-11-22-08-18.bpo-45125.FVSzs2.rst
Labels: CLA signed, type-tests, awaiting merge, needs backport to 3.9, needs backport to 3.10

#28673 bpo-41710: Fix PY_TIMEOUT_MAX on Windows
  Include/pythread.h
  Misc/NEWS.d/next/Library/2021-09-30-08-57-50.bpo-41710.JMsPAW.rst
  Python/thread_nt.h
Labels: CLA signed, awaiting merge

#28676 bpo-41710: gc_collect_main() uses _PyTime_GetPerfCounter()
  Modules/gcmodule.c
Labels: CLA signed, awaiting core review, skip news

#28674 bpo-41710: Add private _PyDeadline_Get() function
  Include/cpython/pytime.h
  Modules/_queuemodule.c
  Modules/_ssl.c
  Modules/_threadmodule.c
  Modules/clinic/_queuemodule.c.h
  Modules/selectmodule.c
  Modules/signalmodule.c
  Modules/socketmodule.c
  Python/pytime.c
  Python/thread_nt.h
  Python/thread_pthread.h
Labels: CLA signed, awaiting core review, skip news

#28653 hashlib: Fix old message about unicode objects.
  Modules/hashlib.h
Labels: CLA signed, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#28678 [3.10] hashlib: Fix old message about unicode objects. (GH-28653)
  Modules/hashlib.h
Labels: CLA signed, skip issue, awaiting merge, skip news

#28675 [3.10] bpo-45125: Improves pickling docs and tests for `shared_memory` (GH-28294)
  Doc/library/multiprocessing.shared_memory.rst
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2021-09-11-22-08-18.bpo-45125.FVSzs2.rst
Labels: CLA signed, type-tests, awaiting merge

#28679 [3.9] hashlib: Fix old message about unicode objects. (GH-28653)
  Modules/hashlib.h
Labels: CLA signed, skip issue, awaiting merge, skip news, :robot: automerge

#28680 bpo-45332: Fix broken Decimal test and benchmark
  Modules/_decimal/tests/bench.py
  Modules/_decimal/tests/deccheck.py
  Modules/_decimal/tests/formathelper.py
Labels: type-bugfix, CLA signed, awaiting merge, skip news, needs backport to 3.10

#28681 [3.10] bpo-45332: Fix broken Decimal test and benchmark (GH-28680)
  Modules/_decimal/tests/bench.py
  Modules/_decimal/tests/deccheck.py
  Modules/_decimal/tests/formathelper.py
Labels: type-bugfix, CLA signed, awaiting merge, skip news

#28677 Fix a couple of compiler warnings.
  Python/ceval.c
Labels: CLA signed, skip issue, awaiting merge, skip news

#28671 [3.10] bpo-41710: PyThread_acquire_lock_timed() uses sem_clockwait()
  Misc/NEWS.d/next/Library/2021-09-30-23-00-18.bpo-41710.svuloZ.rst
  Python/thread_pthread.h
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting merge

#28683 [3.9] bpo-41710: PyThread_acquire_lock_timed() uses sem_clockwait() (GH-28671)
  Misc/NEWS.d/next/Library/2021-09-30-23-00-18.bpo-41710.svuloZ.rst
  Python/thread_pthread.h
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting merge

#28457 bpo-44687: Fix unintended closing file error when peeking a BufferedReader object
  Misc/NEWS.d/next/C API/2021-09-19-17-18-25.bpo-44687.3fqDRC.rst
  Modules/_io/bufferedio.c
Labels: CLA signed, awaiting review, needs backport to 3.9, needs backport to 3.10

#28685 [3.10] bpo-44687: Ensure BufferedReader objects with unread buffers can peek even when the underlying file is closed (GH-28457)
  Misc/NEWS.d/next/C API/2021-09-19-17-18-25.bpo-44687.3fqDRC.rst
  Modules/_io/bufferedio.c
Labels: CLA signed, awaiting merge

#28686 [3.9] bpo-44687: Ensure BufferedReader objects with unread buffers can peek even when the underlying file is closed (GH-28457)
  Misc/NEWS.d/next/C API/2021-09-19-17-18-25.bpo-44687.3fqDRC.rst
  Modules/_io/bufferedio.c
Labels: CLA signed, awaiting merge

#28687 bpo-45341: Replace 'Packaging' with 'Package' in "Python P... Index"
  Doc/distributing/index.rst
  Doc/installing/index.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28688 [3.10] bpo-45341: Replace 'Packaging' with 'Package' in "Python P... Index" (GH-28687)
  Doc/distributing/index.rst
  Doc/installing/index.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28659 Makefile: Fix missing slashes
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2021-10-01-12-20-05.bpo-0.2ykYK2.rst
Labels: type-bugfix, CLA signed, skip issue, awaiting merge, needs backport to 3.9, needs backport to 3.10

#28649 bpo-45329: Fix freed memory access in pyexpat.c
  Misc/NEWS.d/next/Library/2021-10-01-13-09-53.bpo-45329.9iMYaO.rst
  Modules/pyexpat.c
Labels: type-bugfix, CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#28692 [3.10] bpo-45329: Fix freed memory access in pyexpat.c (GH-28649)
  Misc/NEWS.d/next/Library/2021-10-01-13-09-53.bpo-45329.9iMYaO.rst
  Modules/pyexpat.c
Labels: type-bugfix, CLA signed, awaiting merge

#28689 [3.9] bpo-45341: Replace 'Packaging' with 'Package' in "Python P... Index" (GH-28687)
  Doc/distributing/index.rst
  Doc/installing/index.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28697 bpo-45346 Keep docs consistent regarding true and false values
  Doc/library/ast.rst
  Doc/reference/compound_stmts.rst
  Lib/test/test_builtin.py
Labels: CLA signed, type-documentation, awaiting core review, skip news, needs backport to 3.10

#28696 Fix spelling error in comment
  Objects/setobject.c
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news, needs backport to 3.10

#28698 [3.10] bpo-45346: Keep docs consistent regarding true and false values (GH-28697)
  Doc/library/ast.rst
  Doc/reference/compound_stmts.rst
  Lib/test/test_builtin.py
Labels: CLA signed, type-tests, type-documentation, awaiting review, skip news

#28699 [3.10] Fix spelling error in comment (GH-28696)
  Objects/setobject.c
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#28706 Remove trailing spaces.
  Lib/test/test_syntax.py
  Lib/test/test_tokenize.py
  Modules/termios.c
  Python/Python-tokenize.c
  Python/bltinmodule.c
Labels: CLA signed, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28703 Remove news entry without bpo issue number.
  Misc/NEWS.d/next/Build/2021-10-01-12-20-05.bpo-0.2ykYK2.rst
Labels: CLA signed, skip issue, awaiting merge, skip news, :robot: automerge

#28709 [3.10] Remove trailing spaces
  Include/internal/pycore_code.h
  Lib/test/test_syntax.py
  Lib/test/test_time.py
  Lib/typing.py
  Modules/_bisectmodule.c
  Modules/_ctypes/_ctypes_test.c
  Modules/_json.c
  Modules/termios.c
  Objects/exceptions.c
  Objects/genericaliasobject.c
  Objects/obmalloc.c
  Parser/tokenizer.h
  Python/bootstrap_hash.c
  Tools/c-analyzer/c_parser/_state_machine.py
  Tools/c-analyzer/c_parser/preprocessor/__init__.py
Labels: CLA signed, skip issue, awaiting merge, skip news

#28710 [3.9] Remove trailing spaces
  Include/internal/pycore_code.h
  Lib/_osx_support.py
  Modules/_ctypes/_ctypes_test.c
  Modules/_ctypes/callproc.c
  Modules/timemodule.c
  Objects/genericaliasobject.c
  Python/bootstrap_hash.c
  Python/pytime.c
Labels: CLA signed, skip issue, awaiting core review, skip news

#28711 bpo-45355: Use sizeof(_Py_CODEUNIT) instead of literal 2 for the size…
  Modules/_tracemalloc.c
  Objects/frameobject.c
  Objects/genobject.c
  Python/ceval.c
  Python/traceback.c
Labels: CLA signed, awaiting core review, skip news, needs backport to 3.10

#28707 [3.10] bpo-45350: Rerun autoreconf with the pkg-config macros
  .github/workflows/build.yml
  aclocal.m4
  configure
Labels: CLA signed, awaiting core review, skip news

#28708 bpo-45350: Rerun autoreconf with the pkg-config macros
  .github/workflows/build.yml
  aclocal.m4
  configure
Labels: CLA signed, awaiting core review, skip news

#27089 bpo-44594: fix (Async)ExitStack handling of __context__
  Lib/contextlib.py
  Lib/test/test_contextlib.py
  Lib/test/test_contextlib_async.py
  Misc/NEWS.d/next/Library/2021-07-12-10-32-48.bpo-44594.eEa5zi.rst
Labels: CLA signed, awaiting review, needs backport to 3.9, needs backport to 3.10

#28628 bpo-28206: Document signals Handlers, Sigmasks and Signals enums
  Doc/library/signal.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28720 bpo-45355: More use of sizeof(_Py_CODEUNIT)
  Objects/codeobject.c
  Objects/frameobject.c
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news, needs backport to 3.10

#28716 Fix compiler warning in ceval.c regarding signed comparison
  Python/ceval.c
Labels: CLA signed, skip issue, awaiting merge, skip news

#28721 [3.10] bpo-45355: More use of sizeof(_Py_CODEUNIT) (GH-28720).
  Objects/frameobject.c
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#28730 [3.10] bpo-44594: fix (Async)ExitStack handling of __context__ (gh-27089)
  Lib/contextlib.py
  Lib/test/test_contextlib.py
  Lib/test/test_contextlib_async.py
  Misc/NEWS.d/next/Library/2021-07-12-10-32-48.bpo-44594.eEa5zi.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#28731 [3.9] bpo-44594: fix (Async)ExitStack handling of __context__ (gh-27089)
  Lib/contextlib.py
  Lib/test/test_contextlib.py
  Lib/test/test_contextlib_async.py
  Misc/NEWS.d/next/Library/2021-07-12-10-32-48.bpo-44594.eEa5zi.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#28732 bpo-45371: Fix distutils' rpath support for clang
  Lib/distutils/unixccompiler.py
  Misc/NEWS.d/next/Library/2021-10-05-11-03-48.bpo-45371.NOwcDJ.rst
Labels: CLA signed, awaiting merge, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#28723 bpo-43760: Check for tracing using 'bitwise or' instead of branch in dispatch.
  Include/opcode.h
  Misc/NEWS.d/next/Core and Builtins/2021-10-04-16-11-50.bpo-43760.R9QoUv.rst
  Python/ceval.c
  Python/makeopcodetargets.py
  Python/opcode_targets.h
  Python/sysmodule.c
  Tools/scripts/generate_opcode_h.py
Labels: CLA signed, awaiting core review

#28729 bpo-45163: Restrict added libnetwork check to builds on Haiku.
  configure
  configure.ac
Labels: CLA signed, awaiting merge, skip news

#28733 [3.10] bpo-45371: Fix distutils' rpath support for clang (GH-28732)
  Lib/distutils/unixccompiler.py
  Misc/NEWS.d/next/Library/2021-10-05-11-03-48.bpo-45371.NOwcDJ.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#28734 [3.9] bpo-45371: Fix distutils' rpath support for clang (GH-28732)
  Lib/distutils/unixccompiler.py
  Misc/NEWS.d/next/Library/2021-10-05-11-03-48.bpo-45371.NOwcDJ.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#28712 bpo-45354: Skip obsolete device name tests on Windows 11
  Lib/test/test_winconsoleio.py
Labels: CLA signed, type-tests, awaiting review, skip news

#28735 bpo-45375: Fix assertion failure due to searching for stdlib in unnormalised paths
  Misc/NEWS.d/next/Windows/2021-10-05-12-41-53.bpo-45375.CohPP-.rst
  PC/getpathp.c
  PCbuild/regen.targets
Labels: CLA signed, OS-windows, awaiting merge

#28737 [3.10] bpo-45354: Skip obsolete device name tests on Windows 11 (GH-28712)
  Lib/test/test_winconsoleio.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#28736 [3.9] bpo-45354: Skip obsolete device name tests on Windows 11 (GH-28712)
  Lib/test/test_winconsoleio.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#27794 bpo-44050: Extension modules can share state when they don't support sub-interpreters.
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-08-00-30-09.bpo-44050.mFI15u.rst
  Modules/_testmultiphase.c
  Python/import.c
Labels: CLA signed, awaiting merge, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#28738 [3.10] bpo-44050: Extension modules can share state when they don't support sub-interpreters. (GH-27794)
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-08-00-30-09.bpo-44050.mFI15u.rst
  Modules/_testmultiphase.c
  Python/import.c
Labels: CLA signed, awaiting review

#28740 bpo-45324: Rearrange some of the FrozenImporter finder tests.
  Lib/test/test_importlib/frozen/test_finder.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#28701 [3.9] Update macOS installer ReadMe for 3.9.8.
  Mac/BuildScript/resources/ReadMe.rtf
Labels: CLA signed, OS-mac, skip issue, awaiting core review, skip news

#28700 [doc] Fix copy & paste mistake in gethostbyname_ex
  Doc/library/socket.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#28742 [3.10] [doc] Fix gethostbyname_ex description (GH-28700)
  Doc/library/socket.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#28743 [3.9] [doc] Fix gethostbyname_ex description (GH-28700)
  Doc/library/socket.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#28655 bpo-45020: Identify which frozen modules are actually aliases.
  Include/internal/pycore_import.h
  Lib/importlib/_bootstrap.py
  Lib/test/test_importlib/frozen/test_finder.py
  Lib/test/test_importlib/frozen/test_loader.py
  Misc/NEWS.d/next/Core and Builtins/2021-10-01-09-06-54.bpo-45020.Cj5VQN.rst
  Programs/_freeze_module.c
  Python/clinic/import.c.h
  Python/frozen.c
  Python/import.c
  Tools/scripts/freeze_modules.py
Labels: CLA signed, awaiting core review

#28694 [3.10] sqlite3: Modernize documentation around unicode and bytes. (GH-28652)
  Doc/includes/sqlite3/text_factory.py
  Doc/library/sqlite3.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#28739 Fix typo in parser.py
  Tools/peg_generator/pegen/parser.py
Labels: CLA signed, skip issue, awaiting merge, skip news

#28744 Fix typos in the Doc directory
  Doc/c-api/call.rst
  Doc/c-api/init_config.rst
  Doc/faq/design.rst
  Doc/library/ast.rst
  Doc/library/base64.rst
  Doc/library/dis.rst
  Doc/library/enum.rst
  Doc/library/fileinput.rst
  Doc/library/importlib.metadata.rst
  Doc/library/test.rst
  Doc/library/types.rst
  Doc/reference/import.rst
  Doc/tools/rstlint.py
  Doc/using/cmdline.rst
  Doc/using/configure.rst
  Doc/whatsnew/3.10.rst
Labels: CLA signed, skip issue, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#19588 bpo-40321: Support HTTP response status code 308 in urllib.request
  Doc/library/urllib.request.rst
  Lib/urllib/request.py
  Misc/NEWS.d/next/Library/2021-07-22-21-25-56.bpo-40321.gBlFmw.rst
Labels: CLA signed, awaiting merge

#28755 bpo-45388: Normalize jumps in compiler.
  Lib/test/test_dis.py
  Python/ceval.c
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#28520 bpo-40116: Add insertion order bit-vector to dict values to allow dicts to share keys more freely.
  Include/cpython/dictobject.h
  Include/internal/pycore_dict.h
  Lib/test/test_dict.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-23-14-00-05.bpo-40116.KaoeFs.rst
  Modules/_testcapimodule.c
  Objects/dictobject.c
  Python/ceval.c
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review

#28749 [3.9] [doc] Update references to NumPy (GH-22458)
  Doc/faq/programming.rst
  Doc/library/array.rst
  Doc/library/functions.rst
  Doc/tutorial/floatingpoint.rst
Labels: type-documentation, skip issue, awaiting review, skip news

#28758 [3.10] Fix typos in the Doc directory #28744
  Doc/c-api/call.rst
  Doc/c-api/init_config.rst
  Doc/faq/design.rst
  Doc/library/ast.rst
  Doc/library/base64.rst
  Doc/library/fileinput.rst
  Doc/library/importlib.metadata.rst
  Doc/library/test.rst
  Doc/library/types.rst
  Doc/tools/rstlint.py
  Doc/using/configure.rst
  Doc/whatsnew/3.10.rst
Labels: CLA signed, skip issue, awaiting review, skip news

#28759 [3.9] Fix typos in the Doc directory #28744
  Doc/c-api/call.rst
  Doc/faq/design.rst
  Doc/library/ast.rst
  Doc/library/test.rst
  Doc/library/types.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#27989 bpo-34804: [doc] Rephrase section on side effects in functional.rst for clarity
  Doc/howto/functional.rst
Labels: CLA signed, type-documentation, awaiting review, skip news, stale, needs backport to 3.9, needs backport to 3.10

#28754 Remove test_nntplib from quicktest
  Makefile.pre.in
Labels: CLA signed, skip issue, awaiting core review, skip news

#28762 [3.10] bpo-34804: [doc] Rephrase section on side effects in functional.rst for clarity (GH-27989)
  Doc/howto/functional.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28763 [3.9] bpo-34804: [doc] Rephrase section on side effects in functional.rst for clarity (GH-27989)
  Doc/howto/functional.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28760 bpo-40321: Add missing test, slightly expand documentation
  Doc/library/urllib.request.rst
  Lib/test/test_urllib2.py
  Lib/urllib/request.py
  Misc/NEWS.d/next/Library/2021-07-22-21-25-56.bpo-40321.gBlFmw.rst
Labels: CLA signed, awaiting merge

#28646 bpo-45328: Avoid failure in OSs without TCP_NODELAY support
  Lib/http/client.py
  Misc/NEWS.d/next/Library/2021-09-30-08-22-44.bpo-45328.8Z-Q0B.rst
Labels: CLA signed, awaiting review, needs backport to 3.9, needs backport to 3.10

#28770 [3.9] bpo-45328: Avoid failure in OSs without TCP_NODELAY support (GH-28646)
  Lib/http/client.py
  Misc/NEWS.d/next/Library/2021-09-30-08-22-44.bpo-45328.8Z-Q0B.rst
Labels: CLA signed, awaiting review

#28772 [3.10] [doc] Mention __slots__ behavior in weakref.rst (GH-21061)
  Doc/library/weakref.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#28764 bpo-45375: Fix off by one error in buffer allocation
  PC/getpathp.c
Labels: CLA signed, awaiting core review, skip news

#28766 Fix typos in the Objects directory
  Objects/exception_handling_notes.txt
  Objects/exceptions.c
  Objects/floatobject.c
  Objects/frameobject.c
  Objects/listobject.c
  Objects/listsort.txt
  Objects/obmalloc.c
  Objects/setobject.c
  Objects/unicodeobject.c
  PC/getpathp.c
  Parser/tokenizer.h
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#28719 bpo-45385: Fix reference leak from descr_check
  Misc/NEWS.d/next/Core and Builtins/2021-10-06-21-20-11.bpo-45385.CTUT8s.rst
  Objects/descrobject.c
Labels: CLA signed, awaiting merge, skip news, needs backport to 3.10

#28774 bpo-35970: Add help flag to base64 module
  Lib/base64.py
  Lib/test/test_base64.py
  Misc/NEWS.d/next/Library/2019-02-11-19-06-10.bpo-35970.ZRvh51.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#28789 [3.10] Fix typos in the Include directory (GH-28745)
  Include/abstract.h
  Include/cpython/dictobject.h
  Include/cpython/pystate.h
  Include/cpython/pytime.h
  Include/internal/pycore_traceback.h
  Include/object.h
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news, :robot: automerge

#28806 Remove draft notice on the 3.10 What's new document
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news, :robot: automerge, needs backport to 3.10

#28786 bpo-45402: Fix test_tools.test_sundry()
  Misc/NEWS.d/next/Tests/2021-10-07-13-43-01.bpo-45402.jlQvep.rst
  Tools/scripts/freeze_modules.py
Labels: CLA signed, awaiting merge

#28663 bpo-45337: Use the realpath of the new executable when creating a venv on Windows
  Lib/test/test_venv.py
  Lib/venv/__init__.py
  Misc/NEWS.d/next/Windows/2021-09-30-23-17-27.bpo-45337.qg7U_h.rst
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.9, needs backport to 3.10

#28815 [3.9] bpo-45262, asyncio: Fix cache of the running loop holder (GH-28796)
  Misc/NEWS.d/next/Library/2021-10-07-14-04-10.bpo-45262.HqF71Z.rst
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge

#28805 bpo-45407: Remove outdated XXX comment from Struct___init___impl
  Modules/_struct.c
Labels: CLA signed, skip issue, awaiting merge, skip news

#28819 bpo-45410: libregrtest -jN writes stderr into stdout
  Lib/test/libregrtest/runtest_mp.py
  Misc/NEWS.d/next/Tests/2021-10-08-14-03-20.bpo-45410.Ex9xe2.rst
Labels: CLA signed, awaiting core review

#29200 bpo-45335: Add note to `sqlite3` docs about "timestamp" converter
  Doc/library/sqlite3.rst
Labels: CLA signed, type-documentation, awaiting change review, skip news, needs backport to 3.9, needs backport to 3.10

#29204 bpo-45600: Enhanced / clarified the docs for os.environ and os.environb
  Doc/library/os.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29171 bpo-45581: Raise `MemoryError` in `sqlite3.connect` if SQLite signals memory error
  Misc/NEWS.d/next/Library/2021-10-22-21-57-02.bpo-45581.rlH6ay.rst
  Modules/_sqlite/connection.c
Labels: type-bugfix, CLA signed, awaiting review, needs backport to 3.9, needs backport to 3.10

#29319 [3.10] bpo-45335: Add note to `sqlite3` docs about "timestamp" converter (GH-29200)
  Doc/library/sqlite3.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29320 [3.9] bpo-45335: Add note to `sqlite3` docs about "timestamp" converter (GH-29200)
  Doc/library/sqlite3.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29322 [3.10] bpo-45600: Enhanced / clarified the docs for os.environ and os.environb (GH-29204)
  Doc/library/os.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29321 [3.9] bpo-45600: Enhanced / clarified the docs for os.environ and os.environb (GH-29204)
  Doc/library/os.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29323 [3.10] bpo-45581: Raise `MemoryError` in `sqlite3.connect` if SQLite signals memory error (GH-29171)
  Misc/NEWS.d/next/Library/2021-10-22-21-57-02.bpo-45581.rlH6ay.rst
  Modules/_sqlite/connection.c
Labels: type-bugfix, CLA signed, awaiting core review

#29189 bpo-45379: clarify FROZEN_EXCLUDED and FROZEN_INVALID documentation
  Python/import.c
Labels: CLA signed, awaiting review, skip news

#29324 [3.9] bpo-45581: Raise `MemoryError` in `sqlite3.connect` if SQLite signals memory error (GH-29171)
  Misc/NEWS.d/next/Library/2021-10-22-21-57-02.bpo-45581.rlH6ay.rst
  Modules/_sqlite/connection.c
Labels: type-bugfix, CLA signed, awaiting core review

#29304 bpo-10572: Move `sqlite3` tests to `Lib/test`
  Lib/sqlite3/test/__init__.py
  Lib/test/test_sqlite.py
  Lib/test/test_sqlite3/__init__.py
  Lib/test/test_sqlite3/__main__.py
  Lib/test/test_sqlite3/test_backup.py
  Lib/test/test_sqlite3/test_dbapi.py
  Lib/test/test_sqlite3/test_dump.py
  Lib/test/test_sqlite3/test_factory.py
  Lib/test/test_sqlite3/test_hooks.py
  Lib/test/test_sqlite3/test_regression.py
  Lib/test/test_sqlite3/test_transactions.py
  Lib/test/test_sqlite3/test_types.py
  Lib/test/test_sqlite3/test_userfunctions.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2021-01-07-01-25-38.bpo-10572.gEEZ9z.rst
  PCbuild/lib.pyproj
Labels: CLA signed, awaiting merge, :robot: automerge

#29025 Fix docs source link for importlib.metadata
  Doc/library/importlib.metadata.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news, :robot: automerge, needs backport to 3.10

#29330 [3.10] Fix docs source link for importlib.metadata (GH-29025)
  Doc/library/importlib.metadata.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news, :robot: automerge

#29307 bpo-45666: fixes warning with `swprintf` and `%s`
  Misc/NEWS.d/next/Build/2021-10-29-12-54-53.bpo-45666.w2G63u.rst
  Programs/_testembed.c
Labels: CLA signed, awaiting merge

#29334 bpo-45679: Fix caching of multi-value typing.Literal
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-10-30-21-11-37.bpo-45679.Dq8Cpu.rst
Labels: type-bugfix, CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#29340 [3.10] bpo-45679: Fix caching of multi-value typing.Literal (GH-29334)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-10-30-21-11-37.bpo-45679.Dq8Cpu.rst
Labels: type-bugfix, CLA signed, awaiting merge

#29251 bpo-45634: Don't combine error checks when adding `sqlite3` int constants
  Modules/_sqlite/module.c
Labels: CLA signed, awaiting merge, skip news, needs backport to 3.10

#29343 [3.10] bpo-45634: Don't combine error checks when adding `sqlite3` int constants (GH-29251)
  Modules/_sqlite/module.c
Labels: CLA signed, awaiting merge, skip news

#29194 bpo-45516: fix Traversable.name documentation
  Doc/library/importlib.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, :robot: automerge

#29344 Move field width to the right field
  Doc/library/logging.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news, :robot: automerge

#29349 [3.10] bpo-45516: add protocol description to the Traversable documentation (GH-29039)
  Doc/library/importlib.rst
  Misc/NEWS.d/next/Documentation/2021-10-18-20-12-18.bpo-45516.EJh4K8.rst
Labels: CLA signed, type-documentation, awaiting merge

#29348 [3.9] bpo-45516: add protocol description to the Traversable documentation (GH-29039)
  Doc/library/importlib.rst
  Misc/NEWS.d/next/Documentation/2021-10-18-20-12-18.bpo-45516.EJh4K8.rst
Labels: CLA signed, type-documentation, awaiting merge

#29338 Updated README for Python 3.11
  README.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#29350 [3.9] Move field width to the right field (GH-29344) (GH-29350)
  Doc/library/logging.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news, :robot: automerge

#29351 [3.10] Move field width to the right field (GH-29344) (GH-29351)
  Doc/library/logging.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news, :robot: automerge

#29256 bpo-45618: Update Sphinx version used to build the documentation to 4.2.0
  Doc/requirements.txt
  Misc/NEWS.d/next/Documentation/2021-10-31-20-35-06.bpo-45618.RTcNXF.rst
Labels: CLA signed, awaiting merge, :robot: automerge
