Repository python/cpython, pull requests merged in 2021-09, with the labels that each got.

#28103 [3.9] bpo-45057: Simplify RegressionTestResult (GH-28081)
  Lib/test/support/testresult.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#28101 [3.10] bpo-45057: Simplify RegressionTestResult (GH-28081)
  Lib/test/support/testresult.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#28093 [3.9] bpo-45060: Get rid of few uses of the equality operators with None (GH-28087).
  Doc/library/dbm.rst
  Lib/ctypes/_aix.py
  Lib/email/contentmanager.py
  Lib/test/datetimetester.py
  Modules/_gdbmmodule.c
  Modules/clinic/_gdbmmodule.c.h
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting core review, skip news

#28113 bpo-44895: libregrtest: refleak check clears types later
  Lib/test/libregrtest/refleak.py
  Lib/test/libregrtest/runtest.py
  Lib/test/libregrtest/utils.py
  Misc/NEWS.d/next/Tests/2021-09-01-17-17-44.bpo-44895.kV7H77.rst
Labels: CLA signed, awaiting merge

#28116 bpo-40360: Deprecate the lib2to3 package
  Doc/whatsnew/3.11.rst
  Lib/lib2to3/__init__.py
  Lib/test/test_lib2to3.py
  Misc/NEWS.d/next/Library/2021-09-02-00-18-32.bpo-40360.9nmMtB.rst
Labels: CLA signed, awaiting merge

#28117 bpo-45085: Remove the binhex module
  Doc/library/binascii.rst
  Doc/library/binhex.rst
  Doc/library/netdata.rst
  Doc/whatsnew/3.11.rst
  Lib/binhex.py
  Lib/test/test_binascii.py
  Lib/test/test_binhex.py
  Misc/NEWS.d/next/Library/2021-09-02-00-47-14.bpo-45085.mMnaDv.rst
  Modules/binascii.c
  Modules/clinic/binascii.c.h
  PCbuild/lib.pyproj
  Python/stdlib_module_names.h
Labels: CLA signed, awaiting core review

#28118 bpo-37330: open() no longer accept 'U' in file mode
  Doc/library/codecs.rst
  Doc/library/fileinput.rst
  Doc/library/functions.rst
  Doc/whatsnew/3.11.rst
  Lib/_pyio.py
  Lib/fileinput.py
  Lib/imp.py
  Lib/test/test_codecs.py
  Lib/test/test_fileinput.py
  Lib/test/test_io.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-02-01-28-01.bpo-37330.QDjM_l.rst
  Modules/_io/_iomodule.c
  Modules/_io/clinic/_iomodule.c.h
Labels: CLA signed, awaiting core review

#28109 bpo-45056: Remove trailing unused constants from co_consts
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-01-16-55-43.bpo-45056.7AK2d9.rst
  Python/compile.c
  Python/frozen_modules/importlib__bootstrap.h
  Python/frozen_modules/importlib__bootstrap_external.h
  Python/frozen_modules/zipimport.h
Labels: CLA signed, awaiting merge, needs backport to 3.10

#28123 [doc] Link to deprecation policy PEP from the DeprecationWarning documentation
  Doc/library/exceptions.rst
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#27941 bpo-43613: Faster implementation of gzip.compress and gzip.decompress
  Doc/library/gzip.rst
  Doc/library/zlib.rst
  Lib/gzip.py
  Lib/test/test_zlib.py
  Misc/NEWS.d/next/Library/2021-03-24-09-40-02.bpo-43612.vMGZ4y.rst
  Misc/NEWS.d/next/Library/2021-08-25-10-28-49.bpo-43613.WkYmI0.rst
  Modules/clinic/zlibmodule.c.h
  Modules/zlibmodule.c
Labels: CLA signed, awaiting review

#28122 bpo-40360: [doc] Rephrase deprecation note about lib2to3
  Doc/library/2to3.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, needs backport to 3.10

#28124 [3.9] [doc] Link to deprecation policy PEP from the DeprecationWarning documentation (GH-28123)
  Doc/library/exceptions.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#28127 [3.10] bpo-40360: [doc] Rephrase deprecation note about lib2to3 (GH-28122)
  Doc/library/2to3.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#27792 Add missing sentinel obj reference to dataclasses documentation
  Doc/library/dataclasses.rst
Labels: CLA signed, type-documentation, skip issue, awaiting changes, skip news, needs backport to 3.10

#28121 bpo-45081: Fix __init__ method generation when inheriting from Protocol
  Lib/test/test_dataclasses.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-09-02-12-42-25.bpo-45081.tOjJ1k.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#28126 [3.10] [doc] Link to deprecation policy PEP from the DeprecationWarning documentation (GH-28123)
  Doc/library/exceptions.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#28130 [3.10] [doc] Reword sentinel object summary in dataclasses (GH-27792)
  Doc/library/dataclasses.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#28132 [3.9] bpo-45081: Fix __init__ method generation when inheriting from Protocol (GH-28121)
  Lib/test/test_dataclasses.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-09-02-12-42-25.bpo-45081.tOjJ1k.rst
Labels: CLA signed, awaiting review

#28129 bpo-45082: Cleanup ctypes.c_buffer alias
  Doc/library/ctypes.rst
  Lib/ctypes/__init__.py
  Lib/ctypes/test/test_strings.py
  Modules/_ctypes/callproc.c
Labels: CLA signed, awaiting core review, skip news

#28131 [3.10] bpo-45081: Fix __init__ method generation when inheriting from Protocol (GH-28121)
  Lib/test/test_dataclasses.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-09-02-12-42-25.bpo-45081.tOjJ1k.rst
Labels: CLA signed, awaiting merge

#28119 bpo-45083: Include the exception class qualname when formatting an ex…
  Lib/test/test_sys.py
  Lib/test/test_traceback.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-01-23-55-49.bpo-45083.cLi9G3.rst
  Python/errors.c
  Python/pythonrun.c
Labels: CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#27309 bpo-34602: Quadruple stack size on macOS when compiling with UBSAN
  Misc/NEWS.d/next/macOS/2021-08-27-16-55-10.bpo-34602.ZjHsYJ.rst
  Python/thread_pthread.h
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, OS-mac, awaiting change review, needs backport to 3.10

#28140 bpo-45094: Add Py_NO_INLINE macro
  Doc/c-api/intro.rst
  Include/pymath.h
  Include/pyport.h
  Misc/NEWS.d/next/C API/2021-09-03-15-53-43.bpo-45094.tinXwL.rst
  Modules/_functoolsmodule.c
  Modules/_io/bytesio.c
  Modules/_posixsubprocess.c
  Python/marshal.c
Labels: CLA signed, awaiting core review

#28142 bpo-43950: support positions for dis.Instructions created through dis.Bytecode
  Lib/dis.py
  Lib/test/test_dis.py
Labels: CLA signed, awaiting merge, skip news

#27837 bpo-42255: Deprecate webbrowser.MacOSX from Python 3.11
  Doc/library/webbrowser.rst
  Doc/whatsnew/3.11.rst
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2021-08-19-23-49-10.bpo-42255.ofe3ms.rst
Labels: CLA signed, awaiting change review

#28001 [3.8] bpo-45022: Pin current libffi build to fixed version in preparation for upcoming update (GH-27982)
  PCbuild/get_externals.bat
  PCbuild/prepare_libffi.bat
  PCbuild/python.props
Labels: CLA signed, awaiting core review, skip news

#28135 [3.9] bpo-45083: Include the exception class qualname when formatting an exception (GH-28119)
  Include/internal/pycore_object.h
  Lib/test/test_sys.py
  Lib/test/test_traceback.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-01-23-55-49.bpo-45083.cLi9G3.rst
  Objects/typeobject.c
  Python/errors.c
  Python/pythonrun.c
Labels: CLA signed, awaiting review

#28145 [3.9] bpo-42255: Update webbrowser doc
  Doc/library/webbrowser.rst
Labels: CLA signed, skip news

#28144 [3.10] bpo-42255: Update webbrowser doc
  Doc/library/webbrowser.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28146 bpo-45022: Update libffi to 3.4.2 in Windows build
  Misc/NEWS.d/next/Windows/2021-09-03-18-05-21.bpo-45022.bgpD_r.rst
  PCbuild/get_externals.bat
  PCbuild/libffi.props
  PCbuild/python.props
Labels: CLA signed, awaiting core review

#28112 bpo-45075: distinguish between frame and FrameSummary in traceback mo…
  Doc/library/traceback.rst
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2021-09-01-15-27-00.bpo-45075.9xUpvt.rst
Labels: CLA signed, awaiting merge

#28092 [3.10] bpo-45060: Get rid of few uses of the equality operators with None (GH-28087).
  Doc/library/dbm.rst
  Lib/ctypes/_aix.py
  Lib/email/contentmanager.py
  Lib/test/datetimetester.py
  Lib/test/test_pty.py
  Lib/test/test_type_annotations.py
  Modules/_gdbmmodule.c
  Modules/clinic/_gdbmmodule.c.h
  Tools/clinic/clinic.py
Labels: CLA signed, awaiting merge, skip news

#28147 bpo-37596: Update `test_deterministic_sets` to correctly handle different string hash algorithms
  Lib/test/test_marshal.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#28152 Check that 'configure' is generated by GNU Autoconf 2.69
  .github/workflows/build.yml
Labels: CLA signed, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28151 [3.10] Regenerate autoconf files with version 2.69
  configure
Labels: CLA signed, skip issue, awaiting core review, skip news

#28153 [3.9] bpo-45097: Remove incorrect deprecation warnings in asyncio.
  Lib/asyncio/base_events.py
  Lib/asyncio/runners.py
  Lib/asyncio/subprocess.py
  Lib/asyncio/tasks.py
  Lib/asyncio/unix_events.py
  Lib/test/test_asyncgen.py
  Lib/test/test_asyncio/__init__.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_queues.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2021-09-04-13-10-25.bpo-45097.5J4IC-.rst
Labels: type-bugfix, CLA signed, awaiting merge

#28154 bpo-45097: Add more tests for shutdown_asyncgens()
  Lib/test/test_asyncgen.py
Labels: CLA signed, type-tests, awaiting core review, skip news, needs backport to 3.10

#28000 bpo-45030: Fix integer overflow in __reduce__ of the range iterator
  Lib/test/test_range.py
  Misc/NEWS.d/next/Library/2021-08-27-19-01-23.bpo-45030.tAmBbY.rst
  Objects/rangeobject.c
Labels: type-bugfix, CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#28158 Add What's New for dataclass keyword-only parameters.
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news, needs backport to 3.10

#28163 [3.10] Add What's New for dataclass keyword-only parameters. (GH-28158)
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#28159 [3.10] bpo-45097: Add more tests for shutdown_asyncgens() (GH-28154)
  Lib/test/test_asyncgen.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#28160 [3.10] bpo-45030: Fix integer overflow in __reduce__ of the range iterator (GH-28000)
  Lib/test/test_range.py
  Misc/NEWS.d/next/Library/2021-08-27-19-01-23.bpo-45030.tAmBbY.rst
  Objects/rangeobject.c
Labels: type-bugfix, CLA signed, awaiting merge

#28161 [3.9] bpo-45030: Fix integer overflow in __reduce__ of the range iterator (GH-28000)
  Lib/test/test_range.py
  Misc/NEWS.d/next/Library/2021-08-27-19-01-23.bpo-45030.tAmBbY.rst
  Objects/rangeobject.c
Labels: type-bugfix, CLA signed, awaiting merge

#28060 bpo-45042: Now test classes decorated with `requires_hashdigest` are not skipped
  Lib/test/_test_multiprocessing.py
  Lib/test/support/hashlib_helper.py
  Lib/test/test_tools/test_md5sum.py
  Misc/NEWS.d/next/Tests/2021-08-30-11-54-14.bpo-45042.QMz3X8.rst
Labels: CLA signed, type-tests, awaiting merge, needs backport to 3.9, needs backport to 3.10

#28168 [3.10] bpo-45042: Now test classes decorated with `requires_hashdigest` are not skipped (GH-28060)
  Lib/test/_test_multiprocessing.py
  Lib/test/support/hashlib_helper.py
  Lib/test/test_tools/test_md5sum.py
  Misc/NEWS.d/next/Tests/2021-08-30-11-54-14.bpo-45042.QMz3X8.rst
Labels: CLA signed, type-tests, awaiting merge

#28171 Remove unused macros from `Modules/_sqlite/microprotocols.h`
  Modules/_sqlite/microprotocols.h
Labels: CLA signed, skip issue, awaiting merge, skip news

#28167 bpo-44571: Add itertool recipe for a variant of takewhile()
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
Labels: CLA signed, type-documentation, awaiting merge, skip news, needs backport to 3.10

#28173 [3.10] bpo-44571: Add itertool recipe for a variant of takewhile() (GH-28167)
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28169 [3.9] bpo-45042: Now test classes decorated with `requires_hashdigest…
  Lib/test/_test_multiprocessing.py
  Lib/test/support/hashlib_helper.py
  Lib/test/test_tools/test_md5sum.py
  Misc/NEWS.d/next/Tests/2021-08-30-11-54-14.bpo-45042.QMz3X8.rst
Labels: CLA signed, type-tests, awaiting core review

#28166 bpo-45102: unittest: add tests for skipping and errors in cleanup
  Lib/unittest/test/test_skipping.py
Labels: CLA signed, type-tests, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28174 [3.10] bpo-45102: unittest: add tests for skipping and errors in cleanup (GH-28166)
  Lib/unittest/test/test_skipping.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#28175 [3.9] bpo-45102: unittest: add tests for skipping and errors in cleanup (GH-28166)
  Lib/unittest/test/test_skipping.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#28172 Extract visitors from the grammar nodes and call makers in the peg generator
  Lib/test/test_peg_generator/test_pegen.py
  Parser/parser.c
  Tools/peg_generator/pegen/__main__.py
  Tools/peg_generator/pegen/build.py
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/first_sets.py
  Tools/peg_generator/pegen/grammar.py
  Tools/peg_generator/pegen/grammar_visualizer.py
  Tools/peg_generator/pegen/keywordgen.py
  Tools/peg_generator/pegen/parser_generator.py
  Tools/peg_generator/pegen/python_generator.py
  Tools/peg_generator/pegen/testutil.py
  Tools/peg_generator/pegen/validator.py
Labels: CLA signed, skip issue, awaiting core review, skip news

#28155 [3.10] Check that 'configure' is generated by GNU Autoconf 2.69 (GH-28152)
  .github/workflows/build.yml
Labels: CLA signed, skip issue, awaiting review, skip news

#28139 bpo-41031: Match C and Python code formatting of unprintable exceptio…
  Lib/test/test_sys.py
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-03-12-35-17.bpo-41031.yPSJEs.rst
  Python/errors.c
  Python/pythonrun.c
Labels: CLA signed, awaiting merge

#28164 More useful OrderedDict LRU recipes
  Doc/library/collections.rst
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news, needs backport to 3.10

#28179 [3.10] More useful OrderedDict LRU recipes (GH-28164)
  Doc/library/collections.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#27621 bpo-44848: Update macOS installer to use SQLite 3.36.0
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2021-08-06-10-08-41.bpo-44848.0uYXsE.rst
Labels: CLA signed, awaiting merge

#28137 bpo-42238: [doc] remove unused, and deduplicate, suspicious ignore rules.
  Doc/tools/extensions/suspicious.py
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting core review, skip news

#28182 bpo-45052: Unskips a failing `test_shared_memory_basics` test
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2021-09-06-19-00-29.bpo-45052.yrOK3J.rst
Labels: CLA signed, awaiting review, needs backport to 3.9, needs backport to 3.10

#28185 [3.10] bpo-45052: Unskips a failing `test_shared_memory_basics` test (GH-28182)
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2021-09-06-19-00-29.bpo-45052.yrOK3J.rst
Labels: CLA signed, awaiting merge

#28108 bpo-34561: Switch to Munro & Wild "powersort" merge strategy.
  Misc/NEWS.d/next/Core and Builtins/2021-09-01-19-21-48.bpo-34561.uMAVA-.rst
  Objects/listobject.c
  Objects/listsort.txt
Labels: CLA signed, awaiting core review

#27997 [3.10] Fix typo in a comment in Modules/_ssl.c: s/validata/validate/ (GH-27993)
  Modules/_ssl.c
Labels: CLA not signed, skip issue, awaiting merge, skip news

#28191 Update idlelib/help.html to include idle.rst spelling fix
  Lib/idlelib/help.html
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28192 [3.10] Update idlelib/help.html to include idle.rst spelling fix (GH-28191)
  Lib/idlelib/help.html
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#28193 [3.9] Update idlelib/help.html to include idle.rst spelling fix (GH-28191)
  Lib/idlelib/help.html
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#27655 bpo-44860: Make sysconfig posix_user not depend on platlibdir
  Lib/sysconfig.py
  Misc/NEWS.d/next/Library/2021-08-07-22-51-32.bpo-44860.PTvRrU.rst
Labels: CLA signed, awaiting merge

#28011 bpo-45035: Make sysconfig posix_home depend on platlibdir
  Lib/sysconfig.py
  Misc/NEWS.d/next/Library/2021-08-28-14-52-27.bpo-45035.O9mNam.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10

#27955 bpo-44963: Implement send() and throw() methods for anext_awaitable objects
  Lib/test/test_asyncgen.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-25-23-07-10.bpo-44963.5EET8y.rst
  Objects/iterobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.10

#28195 bpo-45124: Remove the bdist_msi command
  Doc/distutils/apiref.rst
  Doc/distutils/builtdist.rst
  Doc/library/msilib.rst
  Doc/whatsnew/3.11.rst
  Lib/distutils/command/bdist.py
  Lib/distutils/command/bdist_msi.py
  Lib/distutils/tests/test_bdist.py
  Lib/distutils/tests/test_bdist_msi.py
  Lib/test/test_sundry.py
  Misc/NEWS.d/next/Library/2021-09-07-09-13-27.bpo-45124.Kw5AUs.rst
  PCbuild/lib.pyproj
Labels: CLA signed, awaiting review

#28194 bpo-45123: PyAiter_Check and PyObject_GetAiter fix & rename.
  Doc/c-api/iter.rst
  Doc/c-api/object.rst
  Doc/data/refcounts.dat
  Doc/data/stable_abi.dat
  Include/abstract.h
  Misc/NEWS.d/next/Core and Builtins/2021-09-06-21-52-45.bpo-45123.8Eh9iI.rst
  Misc/stable_abi.txt
  Objects/abstract.c
  PC/python3dll.c
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge, :robot: automerge, needs backport to 3.10

#28198 [3.10] bpo-44963: Implement send() and throw() methods for anext_awaitable objects (GH-27955)
  Lib/test/test_asyncgen.py
  Misc/NEWS.d/next/Core and Builtins/2021-08-25-23-07-10.bpo-44963.5EET8y.rst
  Objects/iterobject.c
Labels: CLA signed, awaiting merge

#28200 bpo-44964: Add a note explaining the new semantics of f_last_i in frame objects
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news, needs backport to 3.10

#28197 [3.10] bpo-44860: Make sysconfig posix_user not depend on platlibdir (GH-27655)
  Lib/sysconfig.py
  Misc/NEWS.d/next/Library/2021-08-07-22-51-32.bpo-44860.PTvRrU.rst
Labels: CLA signed, awaiting merge

#28202 [3.10] bpo-44964: Add a note explaining the new semantics of f_last_i in frame objects (GH-28200)
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28199 [3.10] bpo-45123: PyAiter_Check and PyObject_GetAiter fix & rename. (GH-28194)
  Doc/c-api/iter.rst
  Doc/c-api/object.rst
  Doc/data/python3.10.abi
  Doc/data/refcounts.dat
  Doc/data/stable_abi.dat
  Include/abstract.h
  Misc/NEWS.d/next/Core and Builtins/2021-09-06-21-52-45.bpo-45123.8Eh9iI.rst
  Misc/stable_abi.txt
  Objects/abstract.c
  PC/python3dll.c
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge

#28088 bpo-44991: Normalise `sqlite3` callback naming
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting review, skip news

#28201 bpo-45035: Revert "Make sysconfig posix_home depend on platlibdir"
  Lib/sysconfig.py
  Misc/NEWS.d/next/Library/2021-08-28-14-52-27.bpo-45035.O9mNam.rst
Labels: CLA signed, awaiting core review

#28178 bpo-45034: Fixes how upper limit is formatted for `struct.pack("H", ...)`
  Lib/test/test_struct.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2021-09-05-20-33-25.bpo-45034.62NLD5.rst
  Modules/_struct.c
Labels: CLA signed, awaiting merge

#27940 bpo-42064: Pass module state to trace, progress, and authorizer callbacks
  Modules/_sqlite/connection.c
  Modules/_sqlite/connection.h
Labels: CLA signed, awaiting merge, skip news

#28190 bpo-44348: BaseException deallocator uses trashcan
  Misc/NEWS.d/next/Core and Builtins/2021-09-07-00-21-04.bpo-44348.f8w_Td.rst
  Objects/exceptions.c
Labels: CLA signed, awaiting merge

#28210 bpo-45104: Clarify when __init__ is called.
  Doc/reference/datamodel.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10

#28183 bpo-45118: Fix regrtest second summary for re-run tests
  Lib/test/libregrtest/main.py
Labels: CLA signed, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28213 [3.8] bpo-45104: Clarify when __init__ is called (GH-28210)
  Doc/reference/datamodel.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28211 [3.10] bpo-45104: Clarify when __init__ is called (GH-28210)
  Doc/reference/datamodel.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28212 [3.9] bpo-45104: Clarify when __init__ is called (GH-28210)
  Doc/reference/datamodel.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28205 bpo-38820: Test with OpenSSL 3.0.0 final
  .github/workflows/build.yml
  Tools/ssl/multissltests.py
Labels: CLA signed, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28215 [3.9] bpo-45118: Fix regrtest second summary for re-run tests (GH-28183)
  Lib/test/libregrtest/main.py
Labels: CLA signed, awaiting review, skip news

#28165 Add more itertool recipes
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news, needs backport to 3.10

#28156 [3.9] Check that 'configure' is generated by GNU Autoconf 2.69
  .github/workflows/build.yml
Labels: CLA signed, skip issue, awaiting core review, skip news

#28219 [3.10] Add more itertool recipes (GH-28165)
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#28085 bpo-45012 Release GIL around stat in os.scandir
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2021-08-31-11-09-52.bpo-45012.ueeOcx.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#28029 DOC: remove documentation for non-existing socket class attributes
  Modules/socketmodule.c
Labels: CLA signed, skip issue, awaiting review, skip news

#28018 bpo-24888: Clarify subprocess.check_call propagates exceptions if unable to start process
  Doc/library/subprocess.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28223 [3.9] bpo-24888: Clarify subprocess.check_call propagates exceptions if unable to start process (GH-28018)
  Doc/library/subprocess.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28224 [3.10] bpo-24888: Clarify subprocess.check_call propagates exceptions if unable to start process (GH-28018)
  Doc/library/subprocess.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28221 [3.9] Remove documentation for non-existing socket class attributes (GH-28029)
  Modules/socketmodule.c
Labels: CLA signed, skip issue, awaiting review, skip news

#28222 [3.10] Remove documentation for non-existing socket class attributes (GH-28029)
  Modules/socketmodule.c
Labels: CLA signed, skip issue, awaiting merge, skip news

#28203 [skip issue] [skip news] Update libffi dll name to libffi-8
  Tools/msi/lib/lib_files.wxs
Labels: CLA signed, skip issue, awaiting review, skip news

#28216 [3.10] bpo-38820: Test with OpenSSL 3.0.0 final (GH-28205)
  .github/workflows/build.yml
  Tools/ssl/multissltests.py
Labels: CLA signed, awaiting merge, skip news

#28128 bpo-39573: Py_TYPE becomes a static inline function
  Doc/c-api/structures.rst
  Doc/whatsnew/3.11.rst
  Include/object.h
  Misc/NEWS.d/next/C API/2021-06-03-00-59-48.bpo-39573.-elHTJ.rst
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting core review

#28225 bpo-45132 Remove deprecated __getitem__ methods
  Doc/library/fileinput.rst
  Doc/library/wsgiref.rst
  Doc/library/xml.dom.pulldom.rst
  Doc/whatsnew/3.11.rst
  Lib/fileinput.py
  Lib/test/test_fileinput.py
  Lib/test/test_pulldom.py
  Lib/test/test_wsgiref.py
  Lib/wsgiref/util.py
  Lib/xml/dom/pulldom.py
  Misc/NEWS.d/next/Library/2021-09-07-16-33-51.bpo-45132.WI9zQY.rst
Labels: type-enhancement, CLA signed, awaiting merge

#28206 bpo-45121: Fix issue when Protocol.__init__ raise RecursionError
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-07-17-10-16.bpo-45121.iG-Hsf.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#27857 bpo-44959: Added fallback to extension modules with '.sl' suffix on HP-UX
  Misc/NEWS.d/next/Core and Builtins/2021-09-08-08-29-41.bpo-44959.OSwwPf.rst
  Python/dynload_hpux.c
Labels: CLA signed, awaiting merge

#28233 [3.9] bpo-45121: Fix RecursionError when calling Protocol.__init__ from a subclass' __init__ (GH-28206)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-07-17-10-16.bpo-45121.iG-Hsf.rst
Labels: CLA signed, awaiting core review

#28232 [3.10] bpo-45121: Fix RecursionError when calling Protocol.__init__ from a subclass' __init__ (GH-28206)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-07-17-10-16.bpo-45121.iG-Hsf.rst
Labels: CLA signed, awaiting review

#28027 [3.10] bpo-25130: Add calls of gc.collect() in tests to support PyPy (GH-28005).
  Lib/test/_test_multiprocessing.py
  Lib/test/lock_tests.py
  Lib/test/test_array.py
  Lib/test/test_asyncgen.py
  Lib/test/test_asyncio/test_tasks.py
  Lib/test/test_code.py
  Lib/test/test_concurrent_futures.py
  Lib/test/test_copy.py
  Lib/test/test_deque.py
  Lib/test/test_exceptions.py
  Lib/test/test_file.py
  Lib/test/test_fileio.py
  Lib/test/test_functools.py
  Lib/test/test_generators.py
  Lib/test/test_io.py
  Lib/test/test_itertools.py
  Lib/test/test_queue.py
  Lib/test/test_raise.py
  Lib/test/test_scope.py
  Lib/test/test_set.py
  Lib/test/test_socket.py
  Lib/test/test_subprocess.py
  Lib/test/test_tempfile.py
  Lib/test/test_thread.py
  Lib/test/test_threading_local.py
  Lib/test/test_weakref.py
  Lib/test/test_weakset.py
  Lib/test/test_xml_etree.py
  Lib/tkinter/test/test_tkinter/test_images.py
  Lib/tkinter/test/test_tkinter/test_variables.py
  Lib/tkinter/test/test_ttk/test_extensions.py
  Lib/tkinter/test/test_ttk/test_widgets.py
  Lib/unittest/test/test_assertions.py
  Lib/unittest/test/test_case.py
  Misc/NEWS.d/next/Tests/2021-08-27-22-37-19.bpo-25130.ig4oJe.rst
Labels: CLA signed, type-tests, awaiting core review

#28214 [3.10] bpo-45118: Fix regrtest second summary for re-run tests (GH-28183)
  Lib/test/libregrtest/main.py
Labels: CLA signed, awaiting review, skip news

#28008 bpo-19113: remove unused test_errors
  Lib/ctypes/test/test_functions.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#28236 [3.9] bpo-45097: Fix deprecation warnings in test_asyncio
  Lib/test/test_asyncio/test_tasks.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#28125 [3.10] bpo-45056: Remove trailing unused constants from co_consts (GH-28109)
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-01-16-55-43.bpo-45056.7AK2d9.rst
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting core review

#28134 [3.10] bpo-45083: Include the exception class qualname when formatting an exception (GH-28119)
  Include/internal/pycore_object.h
  Lib/test/test_sys.py
  Lib/test/test_traceback.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-01-23-55-49.bpo-45083.cLi9G3.rst
  Objects/typeobject.c
  Python/errors.c
  Python/pythonrun.c
Labels: CLA signed, awaiting review

#28207 bpo-45129 Remove deprecated reuse_address
  Doc/library/asyncio-eventloop.rst
  Doc/whatsnew/3.11.rst
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_base_events.py
  Misc/NEWS.d/next/Library/2021-09-07-14-27-39.bpo-45129.vXH0gw.rst
Labels: CLA signed, awaiting change review

#28217 [3.9] bpo-38820: Test with OpenSSL 3.0.0 final (GH-28205)
  .github/workflows/build.yml
  Tools/ssl/multissltests.py
Labels: CLA signed, awaiting core review, skip news

#28186 [3.9] bpo-41082: Add note on errors that may be raised by home() and expanduser()
  Doc/library/pathlib.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#28229 bpo-44340: Update whatsnews for ThinLTO
  Doc/whatsnew/3.11.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news

#28237 bpo-38371: Remove deprecated `tkinter` split() method
  Doc/whatsnew/3.11.rst
  Lib/test/test_tcl.py
  Misc/NEWS.d/next/Library/2021-09-08-13-19-29.bpo-38371.y1kEfP.rst
  Modules/_tkinter.c
  Modules/clinic/_tkinter.c.h
Labels: type-enhancement, CLA signed, awaiting merge

#28230 bpo-20499: Rounding error in statistics.pvariance
  Lib/statistics.py
  Lib/test/test_statistics.py
  Misc/NEWS.d/next/Library/2021-09-08-01-19-31.bpo-20499.tSxx8Y.rst
Labels: type-bugfix, CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#28248 [3.10] bpo-20499: Rounding error in statistics.pvariance (GH-28230)
  Lib/statistics.py
  Lib/test/test_statistics.py
  Misc/NEWS.d/next/Library/2021-09-08-01-19-31.bpo-20499.tSxx8Y.rst
Labels: type-bugfix, CLA signed, awaiting core review, needs backport to 3.9

#28241 Fix small mistake in fileinput documentation
  Doc/library/fileinput.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#28249 [3.10] Fix small mistake in fileinput documentation (GH-28241)
  Doc/library/fileinput.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#27936 specify default order in memoryview.tobytes() docs
  Doc/library/stdtypes.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#28235 bpo-44860: Update test_sysconfig for posix_user platlib
  Lib/test/pythoninfo.py
  Lib/test/test_sysconfig.py
  Misc/NEWS.d/next/Tests/2021-09-08-13-01-37.bpo-44860.qXd0kx.rst
Labels: CLA signed, type-tests, awaiting core review, needs backport to 3.10

#28251 [3.10] bpo-44860: Update test_sysconfig for posix_user platlib (GH-28235)
  Lib/test/pythoninfo.py
  Lib/test/test_sysconfig.py
  Misc/NEWS.d/next/Tests/2021-09-08-13-01-37.bpo-44860.qXd0kx.rst
Labels: CLA signed, type-tests, awaiting merge

#28246 bpo-45017: move opcode-related logic from modulefinder to dis
  Lib/dis.py
  Lib/modulefinder.py
  Lib/test/test_dis.py
Labels: CLA signed, awaiting merge, skip news

#28256 [3.9] bpo-44219: Release the GIL during isatty syscalls (GH-28250)
  Misc/NEWS.d/next/Core and Builtins/2021-09-09-10-32-33.bpo-44219.WiYyjz.rst
  Modules/posixmodule.c
  Python/fileutils.c
Labels: type-bugfix, CLA signed, awaiting merge

#28253 bpo-45147: Edit typo in documentation Update 3.10.rst
  Doc/whatsnew/3.10.rst
Labels: CLA not signed, type-documentation, awaiting merge, skip news, :robot: automerge, needs backport to 3.10

#28255 [3.10] bpo-44219: Release the GIL during isatty syscalls (GH-28250)
  Misc/NEWS.d/next/Core and Builtins/2021-09-09-10-32-33.bpo-44219.WiYyjz.rst
  Modules/posixmodule.c
  Python/fileutils.c
Labels: type-bugfix, CLA signed, awaiting merge

#28259 [3.10] bpo-45147: Fix minor typo in 3.10.rst (GH-28253)
  Doc/whatsnew/3.10.rst
Labels: CLA not signed, type-documentation, awaiting review, skip news

#28260 bpo-45067 - Verify the version of ncurses for extended color support feature usage.
  Misc/NEWS.d/next/Build/2021-09-09-16-45-26.bpo-45067.mFmY92.rst
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting merge

#28263 [3.10] bpo-45067 - Verify the version of ncurses for extended color support feature usage. (GH-28260)
  Misc/NEWS.d/next/Build/2021-09-09-16-45-26.bpo-45067.mFmY92.rst
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting merge

#28218 bpo-45024 and bpo-23864: Document how interface testing works with the collections ABCs
  Doc/library/collections.abc.rst
  Misc/NEWS.d/next/Documentation/2021-09-08-17-20-19.bpo-45024.dkNPNi.rst
Labels: CLA signed, type-documentation, awaiting core review, needs backport to 3.10

#28266 [3.10] bpo-45024 and bpo-23864: Document how interface testing works with the collections ABCs (GH-28218)
  Doc/library/collections.abc.rst
  Misc/NEWS.d/next/Documentation/2021-09-08-17-20-19.bpo-45024.dkNPNi.rst
Labels: CLA signed, type-documentation, awaiting review

#21849 bpo-40563: Support pathlike objects on dbm/shelve
  Doc/library/dbm.rst
  Doc/library/shelve.rst
  Lib/dbm/__init__.py
  Lib/dbm/dumb.py
  Lib/test/test_dbm.py
  Lib/test/test_dbm_dumb.py
  Lib/test/test_dbm_gnu.py
  Lib/test/test_dbm_ndbm.py
  Lib/test/test_shelve.py
  Misc/NEWS.d/next/Library/2020-05-21-01-42-32.bpo-40563.fDn5bP.rst
  Modules/_dbmmodule.c
  Modules/_gdbmmodule.c
  Modules/clinic/_dbmmodule.c.h
  Modules/clinic/_gdbmmodule.c.h
Labels: type-enhancement, CLA signed, awaiting merge

#28270 bpo-45132: Fix the reStructuredText markup
  Doc/library/wsgiref.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news

#28220 Fix typo in pep384_macrocheck.py
  Tools/scripts/pep384_macrocheck.py
Labels: CLA signed, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#28272 [3.10] Fix typos in pep384_macrocheck.py (GH-28220)
  Tools/scripts/pep384_macrocheck.py
Labels: CLA signed, skip issue, awaiting merge, skip news, :robot: automerge

#28273 [3.9] Fix typos in pep384_macrocheck.py (GH-28220)
  Tools/scripts/pep384_macrocheck.py
Labels: CLA signed, skip issue, awaiting merge, skip news, :robot: automerge

#28261 bpo-44219: Mention GH-28250 is a deadlock bugfix
  Misc/NEWS.d/next/Core and Builtins/2021-09-09-10-32-33.bpo-44219.WiYyjz.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#28208 bpo-44964: Correct the note about the f_lasti field
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news, :robot: automerge, needs backport to 3.10

#28082 bpo-25894: Always report skipped and failed subtests separately
  Lib/unittest/runner.py
  Lib/unittest/test/test_result.py
  Misc/NEWS.d/next/Library/2021-09-05-13-15-08.bpo-25894.zjbi2f.rst
Labels: CLA signed, awaiting core review

#28274 [3.10] bpo-44219: Mention GH-28250 is a deadlock bugfix (GH-28261)
  Misc/NEWS.d/next/Core and Builtins/2021-09-09-10-32-33.bpo-44219.WiYyjz.rst
Labels: CLA signed, awaiting review

#28276 [3.10] bpo-44964: Correct the note about the f_lasti field (GH-28208)
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28275 [3.9] bpo-44219: Mention GH-28250 is a deadlock bugfix (GH-28261)
  Misc/NEWS.d/next/Core and Builtins/2021-09-09-10-32-33.bpo-44219.WiYyjz.rst
Labels: CLA signed, awaiting review

#28264 bpo-9811: [doc] strftime handling of unsupported format specifiers is…
  Doc/library/datetime.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#28247 bpo-45144: use subTests in test_peepholer
  Lib/test/test_peepholer.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#28277 [3.10] bpo-9811: [doc] strftime handling of unsupported format specifiers is platform dependent (GH-28264)
  Doc/library/datetime.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28278 [3.9] bpo-9811: [doc] strftime handling of unsupported format specifiers is platform dependent (GH-28264)
  Doc/library/datetime.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#28228 IDLE: adjust Python version in doc url for 3.10+
  Lib/idlelib/help_about.py
Labels: CLA signed, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#28281 [3.10] IDLE: adjust Python version in doc url for 3.10+ (GH-28228)
  Lib/idlelib/help_about.py
Labels: CLA signed, skip issue, awaiting merge, skip news
