Repository python/cpython, pull requests merged in 2021-07, with the labels that each got.

#26947 bpo-44531: Add _PyType_AllocNoTrack() function
  Include/internal/pycore_object.h
  Objects/dictobject.c
  Objects/tupleobject.c
  Objects/typeobject.c
Labels: CLA signed, awaiting merge, skip news

#26968 bpo-43425: Update _osx_support not to use distutils.log
  Lib/_osx_support.py
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news

#26946 bpo-43770: Cleanup _PyObject_GetMethod()
  Objects/object.c
Labels: CLA signed, awaiting core review, skip news

#26978 [3.10] bpo-43425: Update _osx_support not to use distutils.log (GH-26968)
  Lib/_osx_support.py
Labels: CLA signed, awaiting merge, skip news

#26954 Add file describing how to add or modify specialized families of instructions.
  Python/adaptive.md
  Python/specialize.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#26369 bpo-43216: Remove @asyncio.coroutine
  Doc/library/asyncio-task.rst
  Doc/library/collections.abc.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.11.rst
  Lib/asyncio/coroutines.py
  Lib/test/test_asyncio/test_base_events.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_locks.py
  Lib/test/test_asyncio/test_pep492.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2021-05-25-23-26-38.bpo-43216.xTUyyX.rst
Labels: CLA signed, awaiting merge, stale

#24540 bpo-43234: Prohibit non-ThreadPoolExecutor in loop.set_default_executor
  Doc/library/asyncio-eventloop.rst
  Doc/whatsnew/3.11.rst
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_base_events.py
  Misc/NEWS.d/next/Library/2021-02-15-22-14-31.bpo-43234.F-vKAT.rst
Labels: CLA signed, awaiting merge

#26983 bpo-44313: bump up the magic number after compiler changes
  Lib/importlib/_bootstrap_external.py
  Python/importlib_external.h
Labels: CLA signed, awaiting core review, skip news

#26969 bpo-43425: Update setup.py not to use distutils.log
  setup.py
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news

#26986 [3.10] bpo-43425: Update setup.py not to use distutils.log (GH-26969)
  setup.py
Labels: CLA signed, awaiting merge, skip news

#16341 bpo-30256: Add test for nested queues
  Lib/multiprocessing/managers.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2019-09-25-13-54-41.bpo-30256.wBkzox.rst
  Misc/NEWS.d/next/Tests/2019-09-25-18-10-10.bpo-30256.A5i76Q.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, type-tests

#26987 [3.10] bpo-30256: Add manager_owned keyword arg to AutoProxy (GH-16341)
  Lib/multiprocessing/managers.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2019-09-25-13-54-41.bpo-30256.wBkzox.rst
  Misc/NEWS.d/next/Tests/2019-09-25-18-10-10.bpo-30256.A5i76Q.rst
Labels: CLA signed, awaiting merge, type-tests

#26989 [3.9] bpo-30256: Add manager_owned keyword arg to AutoProxy (GH-16341)
  Lib/multiprocessing/managers.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2019-09-25-13-54-41.bpo-30256.wBkzox.rst
  Misc/NEWS.d/next/Tests/2019-09-25-18-10-10.bpo-30256.A5i76Q.rst
Labels: CLA signed, awaiting merge, type-tests

#26967 bpo-34798: [doc] clearer presentation of pprint.PrettyPrinter constru…
  Doc/library/pprint.rst
  Misc/NEWS.d/next/Library/2021-06-30-13-29-49.bpo-34798.t7FCa0.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9, type-documentation

#26990 [3.10] bpo-34798: [doc] clearer presentation of pprint.PrettyPrinter constru… (GH-26967)
  Doc/library/pprint.rst
  Misc/NEWS.d/next/Library/2021-06-30-13-29-49.bpo-34798.t7FCa0.rst
Labels: CLA signed, awaiting review, type-documentation

#26955 bpo-43950: Initial base implementation for PEP 657
  Include/cpython/code.h
  Include/internal/pycore_code.h
  Lib/ctypes/test/test_values.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_code.py
  Lib/test/test_compile.py
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Programs/test_frozenmain.h
  Python/compile.c
  Python/frozen_hello.h
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
  Python/marshal.c
Labels: CLA signed, awaiting merge, skip news

#26994 bpo-30256: Fix rst in news
  Misc/NEWS.d/next/Library/2019-09-25-13-54-41.bpo-30256.wBkzox.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#26996 [3.9] bpo-30256: [doc] Fix formatting error in news (GH-26994)
  Misc/NEWS.d/next/Library/2019-09-25-13-54-41.bpo-30256.wBkzox.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#26998 [3.10] bpo-30256: [doc] Fix formatting error in news (GH-26994)
  Misc/NEWS.d/next/Library/2019-09-25-13-54-41.bpo-30256.wBkzox.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#26997 bpo-43950: optimize column table assembling with pre-sizing object
  Python/compile.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#26663 bpo-44388: Update venv EnvBuilder.ensure_directories() docs.
  Doc/library/venv.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#26966 bpo-42238: rstlint: Add two new checks.
  Doc/tools/rstlint.py
Labels: CLA signed, awaiting core review, skip news

#26993 bpo-44553 : Implement GC methods for types.Union
  Lib/test/test_types.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-02-22-54-41.bpo-44553.l9YqGg.rst
  Objects/unionobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, type-bugfix

#27002 [3.10] bpo-44553 : Implement GC methods for types.Union (GH-26993)
  Lib/test/test_types.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-02-22-54-41.bpo-44553.l9YqGg.rst
  Objects/unionobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#26991 [doc] Fix typo
  Doc/c-api/memory.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip issue, skip news, type-documentation

#26118 bpo-44129: Add descriptive global variables for general purpose bit f…
  Lib/test/test_zipfile.py
  Lib/zipfile.py
Labels: CLA signed, awaiting merge, skip news

#26656 bpo-34266: [pdb] handle ValueError from shlex.split()
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2021-06-10-21-53-46.bpo-34266.k3fxnm.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, type-bugfix

#27005 [3.9] bpo-34266: [pdb] handle ValueError from shlex.split() (GH-26656)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2021-06-10-21-53-46.bpo-34266.k3fxnm.rst
Labels: CLA signed, awaiting review, type-bugfix

#27006 [3.10] bpo-34266: [pdb] handle ValueError from shlex.split() (GH-26656)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2021-06-10-21-53-46.bpo-34266.k3fxnm.rst
Labels: CLA signed, awaiting core review, type-bugfix

#27003 [3.10] Fix a small typo in the docs (GH-26991)
  Doc/c-api/memory.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#27008 bpo-44553: Correct failure in tp_new for the union object
  Objects/unionobject.c
Labels: CLA signed, awaiting core review, needs backport to 3.10, skip news

#27009 [3.10] bpo-44553: Correct failure in tp_new for the union object (GH-27008)
  Objects/unionobject.c
Labels: CLA signed, awaiting merge, skip news

#27010 [3.10] bpo-44559: [Enum] revert str repr
  Doc/howto/enum.rst
  Doc/howto/index.rst
  Doc/library/enum.rst
  Doc/library/http.rst
  Doc/library/socket.rst
  Doc/library/ssl.rst
  Doc/whatsnew/3.10.rst
  Lib/ast.py
  Lib/enum.py
  Lib/http/__init__.py
  Lib/inspect.py
  Lib/plistlib.py
  Lib/pstats.py
  Lib/re.py
  Lib/ssl.py
  Lib/test/test_ast.py
  Lib/test/test_enum.py
  Lib/test/test_httplib.py
  Lib/test/test_pstats.py
  Lib/test/test_pydoc.py
  Lib/test/test_re.py
  Lib/test/test_signal.py
  Lib/test/test_socket.py
  Lib/test/test_ssl.py
  Lib/test/test_unicode.py
  Lib/test/test_uuid.py
  Lib/tkinter/__init__.py
  Lib/tkinter/test/test_tkinter/test_misc.py
  Lib/uuid.py
Labels: CLA signed, awaiting core review, skip news

#27016 bpo-44562: Remove invalid PyObject_GC_Del from error path of types.GenericAlias …
  Misc/NEWS.d/next/Core and Builtins/2021-07-04-23-38-51.bpo-44562.QdeRQo.rst
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge

#27019 [3.10] bpo-44562: Remove invalid PyObject_GC_Del from error path of types.GenericAlias … (GH-27016)
  Misc/NEWS.d/next/Core and Builtins/2021-07-04-23-38-51.bpo-44562.QdeRQo.rst
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge

#27018 [3.9] bpo-44562: Remove invalid PyObject_GC_Del from error path of types.GenericAlias … (GH-27016)
  Misc/NEWS.d/next/Core and Builtins/2021-07-04-23-38-51.bpo-44562.QdeRQo.rst
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge

#27011 bpo-43950: use 0-indexed column offsets for bytecode positions
  Lib/test/test_code.py
  Lib/test/test_compile.py
  Objects/codeobject.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#27015 bpo-43950: include position in dis.Instruction
  Lib/dis.py
  Lib/test/test_dis.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#27022 [3.9] bpo-44562: Revert "Remove invalid PyObject_GC_Del from error path of types.GenericAlias … (GH-27016)"
  Misc/NEWS.d/next/Core and Builtins/2021-07-04-23-38-51.bpo-44562.QdeRQo.rst
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting core review

#26958 bpo-43950: Print columns in tracebacks (PEP 657)
  Doc/library/traceback.rst
  Include/cpython/traceback.h
  Lib/idlelib/idle_test/test_run.py
  Lib/test/test_cmd_line_script.py
  Lib/test/test_doctest.py
  Lib/test/test_traceback.py
  Lib/test/test_zipimport.py
  Lib/traceback.py
  Parser/pegen.c
  Parser/pegen.h
  Python/_warnings.c
  Python/traceback.c
Labels: CLA signed, awaiting merge, skip news

#26143 bpo-41486: zlib uses an UINT32_MAX sliding window for the output buffer
  Misc/NEWS.d/next/Core and Builtins/2021-07-04-17-41-47.bpo-41486.DiM24a.rst
  Modules/zlibmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, stale, type-bugfix, type-performance

#27025 [3.10] bpo-41486: zlib uses an UINT32_MAX sliding window for the output buffer (GH-26143)
  Misc/NEWS.d/next/Core and Builtins/2021-07-04-17-41-47.bpo-41486.DiM24a.rst
  Modules/zlibmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix, type-performance

#27000 bpo-44534: fix wording and docstring sync in unittest.Mock
  Doc/library/unittest.mock.rst
  Lib/unittest/mock.py
Labels: CLA signed, awaiting merge, skip news

#27012 bpo-44558: Make the implementation consistency of operator.indexOf
  Lib/operator.py
  Lib/test/test_operator.py
  Misc/NEWS.d/next/Library/2021-07-04-21-16-53.bpo-44558.cm7Slv.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9

#27029 [3.10] bpo-44558: Make the implementation consistency of operator.indexOf (GH-27012)
  Lib/operator.py
  Lib/test/test_operator.py
  Misc/NEWS.d/next/Library/2021-07-04-21-16-53.bpo-44558.cm7Slv.rst
Labels: CLA signed, awaiting merge

#27030 [3.9] bpo-44558: Make the implementation consistency of operator.indexOf (GH-27012)
  Lib/operator.py
  Lib/test/test_operator.py
  Misc/NEWS.d/next/Library/2021-07-04-21-16-53.bpo-44558.cm7Slv.rst
Labels: CLA signed, awaiting merge

#27021 bpo-44562: Use PyType_GenericAlloc in Py_GenericAlias
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news

#27031 [3.10] bpo-44562: Use PyType_GenericAlloc in Py_GenericAlias (GH-27021)
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge, skip news

#27033 bpo-44022: Fix Sphinx role in NEWS entry
  Misc/NEWS.d/next/Security/2021-05-05-17-37-04.bpo-44022.bS3XJ9.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#26984 bpo-44479: Regenerate test_frozenmain.h and frozen_hello.h on Windows
  PCbuild/_freeze_importlib.vcxproj
  PCbuild/python.vcxproj
  PCbuild/regen.targets
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.10, needs backport to 3.9, skip news

#27028 [3.9] bpo-44562: Remove invalid PyObject_GC_Del from error path of types.GenericAlias … (GH-27016)
  Misc/NEWS.d/next/Core and Builtins/2021-07-04-23-38-51.bpo-44562.QdeRQo.rst
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting merge

#27013 bpo-43453: Update and re-add example to typing runtime_checkable
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27035 [3.10] bpo-44479: Regenerate test_frozenmain.h and frozen_hello.h during build on Windows (GH-26984)
  PCbuild/_freeze_importlib.vcxproj
  PCbuild/python.vcxproj
  PCbuild/regen.targets
Labels: CLA signed, awaiting core review, skip news

#27036 [3.10] bpo-43453: Update and re-add example to typing runtime_checkable (GH-27013)
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27020 bpo-44563: Fix error handling in tee.fromiterable()
  Modules/itertoolsmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news, type-bugfix

#27042 [3.9] bpo-44563: Fix error handling in tee.fromiterable() (GH-27020)
  Modules/itertoolsmodule.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#27041 [3.10] bpo-44563: Fix error handling in tee.fromiterable() (GH-27020)
  Modules/itertoolsmodule.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#27039 bpo-38291: Fix a spurious warning when using help(object)
  Lib/typing.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#26980 bpo-44490: Add __parameters__ and __getitem__ to types.Union
  Include/genericaliasobject.h
  Lib/test/test_types.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-01-11-59-34.bpo-44490.xY80VR.rst
  Objects/genericaliasobject.c
  Objects/unionobject.c
Labels: CLA signed, awaiting merge

#26560 Doc: Fix link in multiprocessing.starmap pointing to builtin map.
  Doc/library/multiprocessing.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, stale, type-documentation

#26941 bpo-44530: Add co_qualname field to PyCodeObject
  Doc/c-api/function.rst
  Include/cpython/code.h
  Include/internal/pycore_code.h
  Lib/ctypes/test/test_values.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_code.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/C API/2021-06-28-23-44-47.bpo-44530.qij7YC.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Objects/funcobject.c
  Objects/genobject.c
  Programs/test_frozenmain.h
  Python/ceval.c
  Python/compile.c
  Python/frozen_hello.h
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
  Python/marshal.c
Labels: CLA signed, awaiting merge

#27052 bpo-44530: Document the new CodeObject.co_qualname attribute
  Doc/library/inspect.rst
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#27007 bpo-44558: Match countOf `is`/`==` treatment to c
  Lib/operator.py
  Lib/test/test_operator.py
  Misc/NEWS.d/next/Documentation/2021-07-03-18-25-17.bpo-44558.0pTknl.rst
  Modules/_operator.c
  Modules/clinic/_operator.c.h
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9

#27053 [3.10] bpo-44558: Match countOf `is`/`==` treatment to c (GH-27007)
  Lib/operator.py
  Lib/test/test_operator.py
  Misc/NEWS.d/next/Documentation/2021-07-03-18-25-17.bpo-44558.0pTknl.rst
  Modules/_operator.c
  Modules/clinic/_operator.c.h
Labels: CLA signed, awaiting merge

#27055 [3.9] bpo-44558: Match countOf `is`/`==` treatment to c (GH-27007).
  Lib/operator.py
  Lib/test/test_operator.py
  Misc/NEWS.d/next/Documentation/2021-07-03-18-25-17.bpo-44558.0pTknl.rst
  Modules/_operator.c
  Modules/clinic/_operator.c.h
Labels: CLA signed, awaiting core review

#27056 bpo-44479: Simplified LICENSE.txt regeneration in Windows build
  PCbuild/regen.targets
Labels: CLA signed, awaiting core review, needs backport to 3.10, skip news, type-bugfix

#27058 [3.10] bpo-44479: Simplified LICENSE.txt regeneration in Windows build (GH-27056)
  PCbuild/regen.targets
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#27023 bpo-43950: Add option to opt-out of PEP-657
  Doc/c-api/init_config.rst
  Doc/using/cmdline.rst
  Include/cpython/initconfig.h
  Lib/idlelib/idle_test/test_run.py
  Lib/test/_test_embed_set_config.py
  Lib/test/support/__init__.py
  Lib/test/test_code.py
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Lib/test/test_doctest.py
  Lib/test/test_embed.py
  Lib/test/test_marshal.py
  Lib/test/test_traceback.py
  Lib/test/test_zipimport.py
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Programs/_testembed.c
  Python/initconfig.c
Labels: CLA signed, awaiting merge, skip news

#27060 Remove __cleanenv from PEP-657 tests
  Lib/test/test_code.py
  Lib/test/test_marshal.py
  Lib/test/test_traceback.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-tests

#25487 bpo-43895: Remove an unnecessary cache of shared object handles
  Misc/NEWS.d/next/Core and Builtins/2021-07-07-16-05-35.bpo-43895.JFjR0-.rst
  Python/dynload_shlib.c
Labels: CLA signed, awaiting merge, stale

#21263 bpo-41137: Use utf-8 encoding while reading .pdbrc files
  Doc/library/pdb.rst
  Doc/whatsnew/3.11.rst
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2020-07-01-17-42-41.bpo-41137.AnqbP-.rst
Labels: CLA signed, awaiting core review

#26572 Doc: Fix wrong exception used in example.
  Doc/library/asyncio-task.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, skip issue, skip news, stale, type-documentation

#27001 bpo-43908: Types with `Py_TPFLAGS_IMMUTABLETYPE ` can now inherit the vectorcall protocol
  Doc/c-api/typeobj.rst
  Doc/whatsnew/3.11.rst
  Lib/test/test_call.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-03-00-20-39.bpo-43908.YHuV_s.rst
  Objects/typeobject.c
Labels: CLA signed, awaiting merge

#27064 bpo-44581: Dont execute quickened instructions if tracing
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#26849 docs: add the word 'official'
  Doc/tools/templates/indexcontent.html
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip issue, skip news

#27070 [3.9] docs: add the word 'official' (GH-26849)
  Doc/tools/templates/indexcontent.html
Labels: CLA signed, awaiting merge, skip issue, skip news

#27069 [3.10] docs: add the word 'official' (GH-26849)
  Doc/tools/templates/indexcontent.html
Labels: CLA signed, awaiting merge, skip issue, skip news

#27059 bpo-44582: Accelerate mimetypes.init on Windows with a native accelerator
  Lib/mimetypes.py
  Lib/test/test_mimetypes.py
  Misc/NEWS.d/next/Windows/2021-07-07-21-07-18.bpo-44582.4Mm6Hh.rst
  Modules/_winapi.c
  Modules/clinic/_winapi.c.h
Labels: CLA signed, OS-windows, needs backport to 3.10, needs backport to 3.9

#27071 [3.10] bpo-44582: Accelerate mimetypes.init on Windows with a native accelerator (GH-27059)
  Lib/mimetypes.py
  Lib/test/test_mimetypes.py
  Misc/NEWS.d/next/Windows/2021-07-07-21-07-18.bpo-44582.4Mm6Hh.rst
  Modules/_winapi.c
  Modules/clinic/_winapi.c.h
Labels: CLA signed, awaiting merge

#26781 bpo-44446: support lineno being None in traceback.FrameSummary
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2021-06-17-22-39-34.bpo-44446.qwdRic.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10

#27072 [3.10] bpo-44446: support lineno being None in traceback.FrameSummary (GH-26781)
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2021-06-17-22-39-34.bpo-44446.qwdRic.rst
Labels: CLA signed, awaiting core review

#27068 bpo-44570: Fix line tracing for forwards jumps to duplicated tails
  Lib/test/test_sys_settrace.py
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#27067 [3.10] bpo-44570: Fix line tracing for forward jumps to duplicated tails
  Lib/test/test_pdb.py
  Lib/test/test_sys_settrace.py
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#27062 [3.10] Doc: Fix wrong exception used in example. (GH-26572)
  Doc/library/asyncio-task.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#27044 Remove irrelevant comment
  Modules/unicodedata.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#27074 [3.10] bpo-43897: ast validation for pattern matching nodes
  Lib/test/test_ast.py
  Python/ast.c
Labels: CLA signed, awaiting merge, skip news

#26555 bpo-44317: Improve tokenizer errors with more informative locations
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-06-00-29-14.bpo-44317.xPPhcZ.rst
  Parser/tokenizer.c
Labels: CLA signed, awaiting core review, stale

#27079 [3.10] bpo-44317: Improve tokenizer errors with more informative locations (GH-26555)
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-06-00-29-14.bpo-44317.xPPhcZ.rst
  Parser/tokenizer.c
Labels: CLA signed, awaiting review

#27049 bpo-43219: shutil.copyfile, raise a less confusing exception instead of IsADirectoryError
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2021-07-09-07-14-37.bpo-41928.Q1jMrr.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, type-bugfix

#27081 [3.10] bpo-43219: shutil.copyfile, raise a less confusing exception instead of IsADirectoryError (GH-27049)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2021-07-09-07-14-37.bpo-41928.Q1jMrr.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#27082 [3.9] bpo-43219: shutil.copyfile, raise a less confusing exception instead of IsADirectoryError (GH-27049)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2021-07-09-07-14-37.bpo-41928.Q1jMrr.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#27085 bpo-29753: revert 0d7ad9f (GH-19850)
  Lib/ctypes/test/test_bitfields.py
  Modules/_ctypes/cfield.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news

#27086 [3.10] bpo-29753: revert 0d7ad9f (GH-19850) (GH-27085)
  Lib/ctypes/test/test_bitfields.py
  Modules/_ctypes/cfield.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#27078 bpo-44207: Add an internal version number to function objects.
  Include/funcobject.h
  Lib/test/test_sys.py
  Objects/funcobject.c
Labels: CLA signed, awaiting core review, skip news

#20138 bpo-26329: update os.path.normpath documentation
  Doc/library/os.path.rst
  Lib/posixpath.py
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news

#27094 [3.10] bpo-26329: update os.path.normpath documentation (GH-20138)
  Doc/library/os.path.rst
  Lib/posixpath.py
Labels: CLA signed, awaiting review, skip news

#26506 [3.8] bpo-44022: Improve the regression test. (GH-26503)
  Lib/test/test_httplib.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-security, type-tests

#26831 [3.9] bpo-44472: Fix ltrace functionality when exceptions are raised (GH-26822)
  Misc/NEWS.d/next/Core and Builtins/2021-06-21-11-19-54.bpo-44472.Vvm1yn.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge

#26803 [3.9] bpo-43298: Improved error message when building without the Windows SDK installed (GH-26800)
  Misc/NEWS.d/next/Build/2021-06-19-11-50-03.bpo-43298.9ircMb.rst
  PCbuild/python.props
Labels: CLA signed, awaiting merge

#26322 [3.9] bpo-43207: InspectLoader.is_package is not an abstract method (GH-24517)
  Doc/library/importlib.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, stale, type-documentation

#25944 [3.9] bpo-38820: Test with OpenSSL 3.0.0-alpha16 (GH-25942)
  .github/workflows/build.yml
  Tools/ssl/multissltests.py
Labels: CLA signed, awaiting core review, skip news, stale, type-tests

#23026 bpo-42194: Add "New in version: 3.9" to argparse.BooleanOptionalAction
  Doc/library/argparse.rst
Labels: CLA not signed, awaiting review, needs backport to 3.10, needs backport to 3.9, skip news, stale, type-documentation

#27095 [3.9] bpo-26329: update os.path.normpath documentation (GH-20138)
  Doc/library/os.path.rst
  Lib/posixpath.py
Labels: CLA signed

#27097 [3.10] bpo-42194: Add "New in version: 3.9" to argparse.BooleanOptionalAction (GH-23026)
  Doc/library/argparse.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24460 [3.9] bpo-43048: RecursionError traceback RecursionError bugfix for cpy3.9 (GH-24460)
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2021-02-06-05-34-01.bpo-43048.yCPUmo.rst
Labels: CLA signed, awaiting core review, stale

#27098 [3.9] bpo-42194: Add "New in version: 3.9" to argparse.BooleanOptionalAction (GH-23026)
  Doc/library/argparse.rst
Labels: CLA signed

#27099 [3.10] bpo-44559: [Enum] add news entry for enum module reversion
  Misc/NEWS.d/next/Library/2021-07-12-10-43-31.bpo-44559.YunVKY.rst
Labels: CLA signed, awaiting core review

#27037 bpo-43950: Specialize tracebacks for subscripts/binary ops
  Doc/library/traceback.rst
  Lib/test/test_traceback.py
  Lib/traceback.py
  Python/traceback.c
Labels: CLA signed, awaiting merge, skip news

#27101 bpo-44613: Make importlib.metadata non-provisional
  Doc/library/importlib.metadata.rst
  Misc/NEWS.d/next/Documentation/2021-07-12-11-39-20.bpo-44613.DIXNzc.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, type-documentation

#27047 bpo-43950: Add documentation for PEP-657
  Doc/c-api/code.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.11.rst
  Misc/NEWS.d/next/Core and Builtins/2021-07-06-15-27-11.bpo-43950.LhL2-q.rst
Labels: CLA signed, awaiting merge, type-documentation

#27106 [3.10] bpo-44613: Make importlib.metadata non-provisional (GH-27101)
  Doc/library/importlib.metadata.rst
  Misc/NEWS.d/next/Documentation/2021-07-12-11-39-20.bpo-44613.DIXNzc.rst
Labels: CLA signed, awaiting review, type-documentation

#26830 [3.10] bpo-44472: Fix ltrace functionality when exceptions are raised (GH-26822)
  Misc/NEWS.d/next/Core and Builtins/2021-06-21-11-19-54.bpo-44472.Vvm1yn.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge

#27103 Remove unnecessary pass statements
  Lib/lib2to3/btm_utils.py
  Lib/multiprocessing/managers.py
  Lib/telnetlib.py
Labels: CLA signed, awaiting review, skip issue, skip news

#27073 bpo-35113: inspect: clean up a duplicate import and comment
  Lib/inspect.py
Labels: CLA signed, awaiting review, skip news

#26909 bpo-44514: Add doctest testcleanup for configparser and bz2
  Doc/library/bz2.rst
  Doc/library/configparser.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27061 bpo-43126: Expand docs on io.IOBase.readlines() method
  Doc/library/io.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#27111 [3.9] bpo-44514: Add doctest testcleanup for configparser and bz2 (GH-26909)
  Doc/library/bz2.rst
  Doc/library/configparser.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27112 [3.10] bpo-44514: Add doctest testcleanup for configparser and bz2 (GH-26909)
  Doc/library/bz2.rst
  Doc/library/configparser.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27110 [3.10] bpo-38741: Definition of multiple ']' in header configparser (GH-17129)
  Lib/configparser.py
  Lib/test/test_configparser.py
  Misc/NEWS.d/next/Library/2019-11-12-18-59-33.bpo-38741.W7IYkq.rst
Labels: CLA signed, awaiting review, type-bugfix

#27113 [3.10] bpo-43126: Expand docs on io.IOBase.readlines() method (GH-27061)
  Doc/library/io.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27114 [3.9] bpo-43126: Expand docs on io.IOBase.readlines() method (GH-27061)
  Doc/library/io.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#27108 Fix typos in Mac/README.rst
  Mac/README.rst
Labels: CLA not signed, awaiting review, skip issue, skip news, type-documentation

#27092 bpo-44572: On Windows platform disconnect STDIN in platform._syscmd_ver() to prevent erroneous STDIN consumption
  Lib/platform.py
  Misc/NEWS.d/next/Windows/2021-07-13-15-32-49.bpo-44572.gXvhDc.rst
Labels: CLA signed, awaiting review

#27124 [3.10] bpo-44572: On Windows, disconnect STDIN in platform._syscmd_ver() to prevent erroneous STDIN consumption (GH-27092)
  Lib/platform.py
  Misc/NEWS.d/next/Windows/2021-07-13-15-32-49.bpo-44572.gXvhDc.rst
Labels: CLA signed, awaiting merge

#6766 bpo-33346: Allow async comprehensions inside implicit async comprehensions.
  Doc/reference/expressions.rst
  Doc/whatsnew/3.11.rst
  Lib/test/test_coroutines.py
  Misc/NEWS.d/next/Core and Builtins/2018-05-11-12-44-03.bpo-33346.ZgBkvB.rst
  Python/compile.c
  Python/symtable.c
Labels: CLA signed, awaiting merge

#27127 bpo-44630: Fix assertion errors in csv module
  Lib/test/test_csv.py
  Modules/_csv.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news, type-bugfix

#27129 [3.10] bpo-44630: Fix assertion errors in csv module (GH-27127)
  Lib/test/test_csv.py
  Modules/_csv.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-bugfix

#27130 [3.9] bpo-44630: Fix assertion errors in csv module (GH-27127)
  Lib/test/test_csv.py
  Modules/_csv.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-bugfix

#27120 bpo-44606: Fix __instancecheck__ and __subclasscheck__ for the union type.
  Lib/test/test_types.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-13-20-22-12.bpo-44606.S3Bv2w.rst
  Objects/unionobject.c
Labels: CLA signed, awaiting core review, needs backport to 3.10, type-bugfix

#27132 [3.10] bpo-44606: Fix __instancecheck__ and __subclasscheck__ for the union type. (GH-27120)
  Lib/test/test_types.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-13-20-22-12.bpo-44606.S3Bv2w.rst
  Objects/unionobject.c
Labels: CLA signed, awaiting merge, type-bugfix

#27133 [3.10] bpo-44608: Fix memory leak in _tkinter._flatten() (GH-27107)
  Lib/test/test_tcl.py
  Misc/NEWS.d/next/Library/2021-07-13-09-01-33.bpo-44608.R3IcM1.rst
  Modules/_tkinter.c
Labels: CLA signed, awaiting merge, type-bugfix

#27134 [3.9] bpo-44608: Fix memory leak in _tkinter._flatten() (GH-27107)
  Lib/test/test_tcl.py
  Misc/NEWS.d/next/Library/2021-07-13-09-01-33.bpo-44608.R3IcM1.rst
  Modules/_tkinter.c
Labels: CLA signed, awaiting merge, type-bugfix

#27109 bpo-44616: Mark all clean up instructions at end of named exception block as artificial
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news

#27135 [3.10] bpo-44616: Mark all clean up instructions at end of named exception block as artificial
  Lib/test/test_sys_settrace.py
  Python/compile.c
Labels: CLA signed, awaiting merge, skip news

#26884 bpo-42064: Move `sqlite3` exceptions to global state, part 2 of 2
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/microprotocols.c
  Modules/_sqlite/module.c
  Modules/_sqlite/module.h
  Modules/_sqlite/statement.c
  Modules/_sqlite/util.c
  Tools/c-analyzer/cpython/ignored.tsv
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#27125 [3.9] bpo-44572: On Windows, disconnect STDIN in platform._syscmd_ver() to prevent erroneous STDIN consumption (GH-27092)
  Lib/platform.py
  Misc/NEWS.d/next/Windows/2021-07-13-15-32-49.bpo-44572.gXvhDc.rst
Labels: CLA signed, awaiting merge

#27136 bpo-44635: Convert None to NoneType in the union type constructor
  Lib/test/test_types.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-14-13-54-07.bpo-44635.7ZMAdB.rst
  Objects/unionobject.c
Labels: CLA signed, awaiting core review, needs backport to 3.10

#27139 bpo-44632: Fix support of TypeVar in the union type
  Lib/test/test_types.py
  Objects/unionobject.c
Labels: CLA signed, awaiting core review, needs backport to 3.10, skip news, type-bugfix

#27145 bpo-44639: fix typo in sqlite.rst (transation => transaction)
  Doc/library/sqlite3.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#27147 Fix docstring typo in sqlite3.Connection.executescript/sqlite3.Cursor.executescript
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/clinic/cursor.c.h
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.10, skip issue, skip news

#27150 Add release highlights for the 3.10 what's new document
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#27152 [3.10] Add release highlights for the 3.10 what's new document (GH-27150)
  Doc/whatsnew/3.10.rst
Labels: awaiting core review, skip issue, skip news, type-documentation

#27148 [3.10] bpo-44639: fix typo in sqlite.rst (transation => transaction) (GH-27145)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#27149 [3.9] bpo-44639: fix typo in sqlite.rst (transation => transaction) (GH-27145)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25079 bpo-34932: Add socket.TCP_KEEPALIVE for macOS
  Doc/library/socket.rst
  Lib/test/test_socket.py
  Misc/NEWS.d/next/macOS/2021-03-29-21-11-23.bpo-34932.f3Hdyd.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.10

#27151 [3.10] Fix docstring typo in sqlite3.Connection.executescript/sqlite3.Cursor.executescript (GH-27147)
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/clinic/cursor.c.h
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting review, skip issue, skip news

#27153 [3.10] bpo-34932: Add socket.TCP_KEEPALIVE for macOS (GH-25079)
  Doc/library/socket.rst
  Lib/test/test_socket.py
  Misc/NEWS.d/next/macOS/2021-03-29-21-11-23.bpo-34932.f3Hdyd.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting merge

#27140 bpo-44473: Update docstring and documentation for QueueHandler.prepar…
  Doc/library/logging.handlers.rst
  Lib/logging/handlers.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#27131 bpo-44589: raise SyntaxError when mapping pattern has duplicate key
  Doc/reference/compound_stmts.rst
  Lib/test/test_patma.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-13-23-19-41.bpo-44589.59OH8T.rst
  Python/compile.c
Labels: CLA signed, awaiting change review, needs backport to 3.10

#27157 [3.10] bpo-44589: raise a SyntaxError when mapping patterns have duplicate literal keys (GH-27131)
  Doc/reference/compound_stmts.rst
  Lib/test/test_patma.py
  Misc/NEWS.d/next/Core and Builtins/2021-07-13-23-19-41.bpo-44589.59OH8T.rst
  Python/compile.c
Labels: :robot: automerge, CLA signed, awaiting merge
