Repository python/cpython, pull requests merged in 2021-11, with the labels that each got.

#29327 bpo-10572: Add sqlite3 test back in PGO test suite
  Lib/test/libregrtest/pgo.py
Labels: CLA signed, awaiting merge, skip news

#29315 bpo-45668: Fix PGO tests without test extensions (GH-29315)
  Lib/test/datetimetester.py
  Lib/test/string_tests.py
  Lib/test/support/__init__.py
  Lib/test/test_array.py
  Lib/test/test_bytes.py
  Lib/test/test_cmath.py
  Lib/test/test_codecs.py
  Lib/test/test_dict.py
  Lib/test/test_embed.py
  Lib/test/test_float.py
  Lib/test/test_struct.py
  Lib/test/test_unicode.py
  Misc/NEWS.d/next/Tests/2021-10-29-17-18-56.bpo-45668.MfAw4i.rst
Labels: CLA signed, type-tests, awaiting merge

#29341 bpo-45666: Use `%S` for MSVC and `%s` elsewhere for `swprintf` in `_testembed.c`
  Programs/_testembed.c
Labels: CLA signed, awaiting merge, skip news

#29354 Update macOS installer to use Tk 8.6.12rc1 pre-release for 3.11.0a2.
  Mac/BuildScript/bpo-44828-filedialog-crash-monterey.patch
  Mac/BuildScript/build-installer.py
  Mac/BuildScript/resources/ReadMe.rtf
  Mac/BuildScript/resources/Welcome.rtf
Labels: CLA signed, OS-mac, skip issue, awaiting core review, skip news

#28463 bpo-45243: Add support for setting/getting `sqlite3` connection limits
  Doc/library/sqlite3.rst
  Doc/whatsnew/3.11.rst
  Lib/test/test_sqlite3/test_dbapi.py
  Misc/NEWS.d/next/Library/2021-09-20-01-25-09.bpo-45243.0pJf0U.rst
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/connection.c
  Modules/_sqlite/module.c
Labels: CLA signed, awaiting merge

#29358 bpo-45688: Add _scproxy to sys.stdlib_module_names (GH-29358)
  Misc/NEWS.d/next/Core and Builtins/2021-11-02-09-27-46.bpo-45688.v5Der1.rst
  Python/stdlib_module_names.h
  Tools/scripts/generate_stdlib_module_names.py
Labels: CLA signed, awaiting core review, needs backport to 3.10

#29353 bpo-43158: Use configure values for building _uuid extension (GH-29353)
  Misc/NEWS.d/next/Build/2021-11-01-12-51-46.bpo-43158.fghS6w.rst
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#29361 [3.10] bpo-45688: Add _scproxy to sys.stdlib_module_names (GH-29358) (GH-29361)
  Misc/NEWS.d/next/Core and Builtins/2021-11-02-09-27-46.bpo-45688.v5Der1.rst
  Python/stdlib_module_names.h
  Tools/scripts/generate_stdlib_module_names.py
Labels: CLA signed, :robot: automerge

#29362 [3.10] bpo-43158: Use configure values for building _uuid extension (GH-29353) (GH-29362)
  Misc/NEWS.d/next/Build/2021-11-01-12-51-46.bpo-43158.fghS6w.rst
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed, awaiting merge, :robot: automerge

#29363 [3.9] bpo-43158: Use configure values for building _uuid extension (GH-29353) (GH-29363)
  Misc/NEWS.d/next/Build/2021-11-01-12-51-46.bpo-43158.fghS6w.rst
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed, awaiting merge, :robot: automerge

#29318 bpo-45633 Fix typo in extending/newtypes documentation
  Doc/extending/newtypes.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#29234 bpo-42064: Adapt `sqlite3` to multi-phase init (PEP 489)
  Misc/NEWS.d/next/Library/2021-10-27-13-28-52.bpo-42064.UK4jgV.rst
  Modules/_sqlite/module.c
Labels: CLA signed, awaiting review

#29325 makefile: remove unused SGI_ABI variable
  Makefile.pre.in
Labels: CLA signed, skip issue, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#29368 [3.10] makefile: remove unused SGI_ABI variable (GH-29325)
  Makefile.pre.in
Labels: CLA signed, skip issue, awaiting review, skip news

#29367 bpo-44828: macOS installer: avoid leaving a zombie Save panel in Tk 8.6.12rc1
  Mac/BuildScript/bpo-44828-filedialog-crash-monterey-8612rc1.patch
  Mac/BuildScript/build-installer.py
Labels: CLA signed, OS-mac, skip issue, awaiting core review, skip news

#29370 [3.9] makefile: remove unused SGI_ABI variable (GH-29325)
  Makefile.pre.in
Labels: CLA signed, skip issue, awaiting review, skip news

#29369 [3.10] bpo-44828: Avoid leaving a zombie Save panel.
  Mac/BuildScript/bpo-44828-filedialog-crash-monterey.patch
Labels: CLA signed, OS-mac, awaiting core review, skip news

#29371 [3.9] bpo-44828: Avoid leaving a zombie Save panel.
  Mac/BuildScript/bpo-44828-filedialog-crash-monterey.patch
Labels: CLA signed, OS-mac, awaiting core review, skip news

#28947 bpo-45457: Minor fix to documentation for SSLContext.load_default_certs.
  Doc/library/ssl.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#28941 [doc] Link to section File input in Functions
  Doc/library/functions.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#29373 [3.10] bpo-45457: Minor fix to documentation for SSLContext.load_default_certs. (GH-28947)
  Doc/library/ssl.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29374 [3.9] bpo-45457: Minor fix to documentation for SSLContext.load_default_certs. (GH-28947)
  Doc/library/ssl.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29375 [3.10] [doc] Link to section File input (GH-28941)
  Doc/library/functions.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#28824 bpo-45406: make inspect.getmodule() return None when getabsfile() rai…
  Lib/inspect.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2021-10-08-19-24-48.bpo-45406.Qh_Mz4.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#29376 [3.9] [doc] Link to section File input (GH-28941)
  Doc/library/functions.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#29377 [3.10] bpo-45406: make inspect.getmodule() return None when getabsfile() raises FileNotFoundError (GH-28824)
  Lib/inspect.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2021-10-08-19-24-48.bpo-45406.Qh_Mz4.rst
Labels: CLA signed, awaiting merge

#29378 [3.9] bpo-45406: make inspect.getmodule() return None when getabsfile() raises FileNotFoundError (GH-28824)
  Lib/inspect.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2021-10-08-19-24-48.bpo-45406.Qh_Mz4.rst
Labels: CLA signed, awaiting merge

#28076 bpo-24139: Add support for SQLite extended result codes
  Doc/whatsnew/3.11.rst
  Lib/test/test_sqlite3/test_dbapi.py
  Misc/NEWS.d/next/Library/2021-08-30-23-10-48.bpo-24139.e38czf.rst
  Modules/_sqlite/module.c
  Modules/_sqlite/util.c
Labels: CLA signed, awaiting merge

#29342 [3.9] bpo-45679: Fix caching of multi-value typing.Literal (GH-29334)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-10-30-21-11-37.bpo-45679.Dq8Cpu.rst
Labels: type-bugfix, CLA signed, awaiting merge

#29364 [3.10] bpo-45633: Fix newtypes doc typo (GH-29318)
  Doc/extending/newtypes.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#29365 [3.9] bpo-45633: Fix newtypes doc typo (GH-29318)
  Doc/extending/newtypes.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29382 bpo-24139: Fix sqlite3 test suite on s390x RHEL buildbots
  Lib/test/test_sqlite3/test_dbapi.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#29332 bpo-45578: add tests for `dis.distb`
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Tests/2021-10-30-19-00-25.bpo-45578.bvu6X2.rst
Labels: CLA signed, type-tests, awaiting review, needs backport to 3.9, needs backport to 3.10

#29385 [3.10] bpo-45578: add tests for `dis.distb` (GH-29332)
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Tests/2021-10-30-19-00-25.bpo-45578.bvu6X2.rst
Labels: CLA signed, type-tests, awaiting core review

#29328 bpo-45678: Add ``functools.singledispatchmethod`` tests
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Tests/2021-10-30-13-12-20.bpo-45678.bKrYeS.rst
Labels: CLA signed, type-tests, awaiting review, needs backport to 3.9, needs backport to 3.10

#29366 bpo-45691: Make array of small ints static to fix use-after-free error.
  Include/internal/pycore_interp.h
  Include/internal/pycore_long.h
  Include/internal/pycore_runtime.h
  Objects/longobject.c
Labels: CLA signed, awaiting merge, skip news

#29390 [3.10] bpo-45678: Add ``functools.singledispatchmethod`` tests (GH-29328)
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Tests/2021-10-30-13-12-20.bpo-45678.bKrYeS.rst
Labels: CLA signed, type-tests, awaiting review

#29386 [3.9] bpo-45578: add tests for `dis.distb` (GH-29332)
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Tests/2021-10-30-19-00-25.bpo-45578.bvu6X2.rst
Labels: CLA signed, type-tests, awaiting core review

#29300 bpo-45506: Re-enable test_embed.
  Lib/test/test_embed.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#29393 bpo-44257: fix "assigment_expr" typo + regenerate the grammar, and remove unused imports
  Grammar/python.gram
  Parser/parser.c
  Tools/peg_generator/pegen/python_generator.py
Labels: CLA signed, awaiting review, skip news, :robot: automerge, needs backport to 3.10

#29227 bpo-45613: Set `sqlite3.threadsafety` dynamically
  Doc/library/sqlite3.rst
  Doc/whatsnew/3.11.rst
  Lib/sqlite3/dbapi2.py
  Lib/test/test_sqlite3/test_dbapi.py
  Misc/NEWS.d/next/Library/2021-10-26-14-29-54.bpo-45613.55Ie3c.rst
  Modules/_sqlite/module.c
Labels: CLA signed, awaiting merge

#29387 bpo-45680: ``typing`` docs: improve links to docs on ``GenericAlias``/``__class_getitem__``
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2021-11-03-14-51-03.bpo-45680.9_NTFU.rst
Labels: CLA signed, type-documentation, awaiting merge

#29399 [3.10] bpo-45680: ``typing`` docs: improve links to docs on ``GenericAlias``/``__class_getitem__`` (GH-29387)
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2021-11-03-14-51-03.bpo-45680.9_NTFU.rst
Labels: CLA signed, type-documentation, awaiting merge

#29400 [3.9] bpo-45680: ``typing`` docs: improve links to docs on ``GenericAlias``/``__class_getitem__`` (GH-29387)
  Doc/library/typing.rst
  Misc/NEWS.d/next/Documentation/2021-11-03-14-51-03.bpo-45680.9_NTFU.rst
Labels: CLA signed, type-documentation, awaiting merge

#29392 bpo-45697: Use PyObject_TypeCheck in type_call and binary_op1
  Objects/typeobject.c
Labels: type-enhancement, CLA signed, awaiting merge, skip news

#29401 Remove reference to ``Tuple`` at top of ``typing`` docs
  Doc/library/typing.rst
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#29402 [3.10] Remove reference to ``Tuple`` at top of ``typing`` docs (GH-29401)
  Doc/library/typing.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#29403 [3.9] Remove reference to ``Tuple`` at top of ``typing`` docs (GH-29401)
  Doc/library/typing.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#29397 bpo-43652: Actually update to Tcl/Tk 8.6.11 on Windows
  Misc/NEWS.d/next/Windows/2021-11-04-00-41-50.bpo-43652.RnqV7I.rst
  PCbuild/get_externals.bat
  PCbuild/tcltk.props
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.10

#29396 bpo-45220: Remove invalid include from resource definition files on Windows
  PC/pylauncher.rc
  PC/pyshellext.rc
  PC/python_exe.rc
  PC/python_nt.rc
  PC/pythonw_exe.rc
  PC/sqlite3.rc
  PCbuild/python.props
Labels: CLA signed, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#29405 [3.9] bpo-45220: Remove invalid include from resource definition files on Windows (GH-29396)
  PC/pylauncher.rc
  PC/pyshellext.rc
  PC/python_exe.rc
  PC/python_nt.rc
  PC/pythonw_exe.rc
  PC/sqlite3.rc
  PCbuild/python.props
Labels: CLA signed, awaiting merge, skip news

#29407 [3.10] bpo-43652: Actually update to Tcl/Tk 8.6.11 on Windows (GH-29397)
  Misc/NEWS.d/next/Windows/2021-11-04-00-41-50.bpo-43652.RnqV7I.rst
  PCbuild/get_externals.bat
  PCbuild/tcltk.props
Labels: CLA signed, awaiting core review

#29408 Add generated artifacts in Mac/ to .gitignore; update copyright
  .gitignore
  Mac/Resources/framework/Info.plist.in
Labels: CLA signed, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#29410 [3.9] Add generated artifacts in Mac/ to .gitignore; update copyright (GH-29408)
  .gitignore
  Mac/Resources/framework/Info.plist.in
Labels: CLA signed, skip issue, awaiting review, skip news

#29409 [3.10] Add generated artifacts in Mac/ to .gitignore; update copyright (GH-29408)
  .gitignore
  Mac/Resources/framework/Info.plist.in
Labels: CLA signed, skip issue, awaiting review, skip news

#29394 [3.9] bpo-45678: Fix `singledispatchmethod` `classmethod`/`staticmethod` bug
  Lib/functools.py
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Library/2021-11-03-17-28-43.bpo-45678.Zj_O8j.rst
Labels: CLA signed, awaiting review

#29406 [3.10] bpo-45220: Remove invalid include from resource definition files on Windows (GH-29396)
  PC/pylauncher.rc
  PC/pyshellext.rc
  PC/python_exe.rc
  PC/python_nt.rc
  PC/pythonw_exe.rc
  PC/sqlite3.rc
  PCbuild/python.props
Labels: CLA signed, awaiting merge, skip news

#29178 [3.9] bpo-30570: Use Py_EnterRecursiveCall() in issubclass() (GH-29048)
  Lib/test/test_isinstance.py
  Misc/NEWS.d/next/Core and Builtins/2021-10-19-01-04-08.bpo-30570._G30Ms.rst
  Objects/abstract.c
Labels: CLA signed, awaiting review

#29372 [3.8] bpo-44828: Avoid leaving a zombie Save panel.
  Mac/BuildScript/bpo-44828-filedialog-crash-monterey.patch
Labels: CLA signed, OS-mac, awaiting core review, skip news

#29414 [3.10] bpo-30570: Fix segfault on buildbots caused by stack overflow from recursion in tests (GH-29258)
  Lib/test/pickletester.py
  Lib/test/test_isinstance.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#29415 [3.9] bpo-30570: Fix segfault on buildbots caused by stack overflow from recursion in tests (GH-29258)
  Lib/test/pickletester.py
  Lib/test/test_isinstance.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#29395 [3.10] bpo-44257: fix "assigment_expr" typo + regenerate the grammar and remove unused imports (GH-29393)
  Grammar/python.gram
  Parser/parser.c
Labels: CLA signed, skip news

#29416 bpo-45160: Fix refleak in test_ttk_guionly introduced in GH-28291
  Lib/tkinter/test/test_ttk/test_extensions.py
Labels: CLA signed, type-tests, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#29411 bpo-27313: Fix ttk_guionly tests failing on Framework builds on macOS
  Lib/tkinter/test/test_ttk/test_widgets.py
Labels: CLA signed, type-tests, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#29207 bpo-45292: [PEP 654] Update traceback display code to work with exception groups
  Include/internal/pycore_traceback.h
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-26-18-18-50.bpo-45292.aX5HVr.rst
  Python/pythonrun.c
  Python/traceback.c
Labels: CLA signed, awaiting merge

#29422 [3.10] bpo-27313: Fix ttk_guionly tests failing on Framework builds on macOS (GH-29411)
  Lib/tkinter/test/test_ttk/test_widgets.py
Labels: CLA signed, type-tests, awaiting review, skip news

#29423 [3.9] bpo-27313: Fix ttk_guionly tests failing on Framework builds on macOS (GH-29411)
  Lib/tkinter/test/test_ttk/test_widgets.py
Labels: CLA signed, type-tests, awaiting review, skip news

#29420 [3.9] bpo-45160: Fix refleak in test_ttk_guionly introduced in GH-28291 (GH-29416)
  Lib/tkinter/test/test_ttk/test_extensions.py
Labels: CLA signed, type-tests, awaiting review, skip news

#29421 [3.10] bpo-45160: Fix refleak in test_ttk_guionly introduced in GH-28291 (GH-29416)
  Lib/tkinter/test/test_ttk/test_extensions.py
Labels: CLA signed, type-tests, awaiting review, skip news

#29412 bpo-45678: Add more ``singledispatchmethod`` tests
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Tests/2021-11-04-20-03-32.bpo-45678.1xNMjN.rst
Labels: CLA signed, type-tests, awaiting review, needs backport to 3.10

#29413 bpo-45716: Improve the error message when using True/False/None as keywords in a call
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-11-04-20-19-07.bpo-45716.5C0pA1.rst
  Parser/parser.c
Labels: CLA signed, awaiting core review, :robot: automerge, needs backport to 3.10

#29424 [3.10] bpo-45678: Add more ``singledispatchmethod`` tests (GH-29412)
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Tests/2021-11-04-20-03-32.bpo-45678.1xNMjN.rst
Labels: CLA signed, type-tests, awaiting review

#29426 bpo-45726: Improve docs for ``@singledispatch``/``@singledispatchmethod``
  Doc/library/functools.rst
  Misc/NEWS.d/next/Documentation/2021-11-05-12-15-24.bpo-45726.GwRr7e.rst
Labels: CLA signed, type-documentation, awaiting core review, needs backport to 3.9, needs backport to 3.10

#29431 [3.10] bpo-45726: Improve docs for ``@singledispatch``/``@singledispatchmethod`` (GH-29426)
  Doc/library/functools.rst
  Misc/NEWS.d/next/Documentation/2021-11-05-12-15-24.bpo-45726.GwRr7e.rst
Labels: CLA signed, type-documentation, awaiting review

#29430 [3.9] bpo-45726: Improve docs for ``@singledispatch``/``@singledispatchmethod`` (GH-29426)
  Doc/library/functools.rst
  Misc/NEWS.d/next/Documentation/2021-11-05-12-15-24.bpo-45726.GwRr7e.rst
Labels: CLA signed, type-documentation, awaiting review

#29356 bpo-45243: Use connection limits to simplify `sqlite3` tests
  Lib/test/test_sqlite3/test_dbapi.py
  Lib/test/test_sqlite3/test_regression.py
  Lib/test/test_sqlite3/test_userfunctions.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#29339 bpo-45679: add `tuple` tests with `lru_cache` to `test_functools`
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Tests/2021-10-31-10-58-45.bpo-45701.r0LAUL.rst
Labels: CLA signed, type-tests, awaiting merge

#29433 bpo-43158: Regenerate configure again (GH-29433)
  configure
  pyconfig.h.in
Labels: CLA signed, awaiting core review, skip news

#29417 bpo-45720: Drop references to shlwapi
  Misc/NEWS.d/next/Windows/2021-11-05-01-05-46.bpo-45720.47Nc5I.rst
  PC/getpathp.c
  PCbuild/_freeze_module.vcxproj
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, awaiting core review

#29435 [3.10] bpo-45720: Drop references to shlwapi.dll on Windows (GH-29417)
  Misc/NEWS.d/next/Windows/2021-11-05-01-05-46.bpo-45720.47Nc5I.rst
  PC/getpathp.c
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, awaiting core review, needs backport to 3.9

#29436 [3.9] bpo-45720: Drop references to shlwapi.dll on Windows (GH-29417)
  Misc/NEWS.d/next/Windows/2021-11-05-01-05-46.bpo-45720.47Nc5I.rst
  PC/getpathp.c
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, awaiting merge

#29434 bpo-45731: Handle --enable-loadable-sqlite-extensions in configure (GH-29434)
  Misc/NEWS.d/next/Build/2021-11-05-20-56-29.bpo-45731.9SDnDf.rst
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/connection.c
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed, awaiting core review, :robot: automerge

#29273 bpo-45644: Make json.tool read infile before writing to outfile
  Lib/json/tool.py
  Lib/test/test_json/test_tool.py
  Misc/NEWS.d/next/Library/2021-11-06-17-47-46.bpo-45644.ZMqHD_.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#29443 bpo-45740: [Enum] docs add version
  Doc/howto/enum.rst
  Doc/library/enum.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news

#29444 [doc] minor fixes to expressions.rst
  Doc/reference/expressions.rst
Labels: CLA signed, skip issue, skip news

#29388 [doc] bpo-45680: Improve glossary entry for generic types
  Doc/glossary.rst
Labels: CLA signed, type-documentation, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#29445 [3.10] bpo-45644: Make json.tool read infile before writing to outfile (GH-29273)
  Lib/json/tool.py
  Lib/test/test_json/test_tool.py
  Misc/NEWS.d/next/Library/2021-11-06-17-47-46.bpo-45644.ZMqHD_.rst
Labels: CLA signed, awaiting review

#29446 [3.9] bpo-45644: Make json.tool read infile before writing to outfile (GH-29273)
  Lib/json/tool.py
  Lib/test/test_json/test_tool.py
  Misc/NEWS.d/next/Library/2021-11-06-17-47-46.bpo-45644.ZMqHD_.rst
Labels: CLA signed, awaiting review

#29379 bpo-39452: [doc] Change "must" to "can", on relative import style in __main__ modules
  Doc/library/__main__.rst
Labels: CLA signed, type-documentation, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#29447 [3.10] [doc] bpo-45680: Improve glossary entry for generic types (GH-29388)
  Doc/glossary.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29449 [3.10] bpo-39452: [doc] Change "must" to "can" on relative import style in `__main__` (GH-29379)
  Doc/library/__main__.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29448 [3.9] [doc] bpo-45680: Improve glossary entry for generic types (GH-29388)
  Doc/glossary.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29425 bpo-45160: Use non-deprecated methods for tracing
  Lib/tkinter/test/test_ttk/test_extensions.py
Labels: CLA signed, type-tests, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#29439 bpo-45392: Update the docstring of the 'type' built-in.
  Misc/NEWS.d/next/Documentation/2021-11-06-10-54-17.bpo-45392.JZnVOz.rst
  Objects/typeobject.c
Labels: type-bugfix, CLA signed, type-documentation, awaiting merge, needs backport to 3.9, needs backport to 3.10

#29450 [3.10] bpo-27313: Use non-deprecated methods for tracing (GH-29425)
  Lib/tkinter/test/test_ttk/test_extensions.py
Labels: CLA signed, type-tests, awaiting review, skip news

#29451 [3.9] bpo-27313: Use non-deprecated methods for tracing (GH-29425)
  Lib/tkinter/test/test_ttk/test_extensions.py
Labels: CLA signed, type-tests, awaiting review, skip news

#29453 [3.9] bpo-45392: Update the docstring of the 'type' built-in (GH-29439)
  Misc/NEWS.d/next/Documentation/2021-11-06-10-54-17.bpo-45392.JZnVOz.rst
  Objects/typeobject.c
Labels: type-bugfix, CLA signed, type-documentation, awaiting core review

#29452 [3.10] bpo-45392: Update the docstring of the 'type' built-in (GH-29439)
  Misc/NEWS.d/next/Documentation/2021-11-06-10-54-17.bpo-45392.JZnVOz.rst
  Objects/typeobject.c
Labels: type-bugfix, CLA signed, type-documentation, awaiting review

#29442 bpo-45723: Detect missing pkg-config (GH-29442)
  Misc/NEWS.d/next/Build/2021-11-07-10-36-12.bpo-45723.JNwKSG.rst
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#29459 General cleanup of test_pydoc
  Lib/test/test_pydoc.py
Labels: CLA signed, type-tests, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#29461 bpo-45741: docs: fix plural
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#29463 [3.10] bpo-45741: docs: fix plural (GH-29461)
  Doc/whatsnew/3.10.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, :robot: automerge

#29429 bpo-45723: Add helper macros and more caching to configure.ac (GH-29429)
  Misc/NEWS.d/next/Build/2021-11-05-15-09-49.bpo-45723.gfSxur.rst
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting core review

#29455 remove the repeat 'the'
  Modules/_ctypes/libffi_osx/README
Labels: CLA signed, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#29465 [3.9] remove the repeat 'the' (GH-29455)
  Modules/_ctypes/libffi_osx/README
Labels: CLA signed, skip issue, awaiting merge, skip news, :robot: automerge

#29456 bpo-45743: Move __APPLE_USE_RFC_3542 into socketmodule.c (GH-29456)
  Modules/socketmodule.c
  setup.py
Labels: CLA signed, awaiting merge, skip news

#29470 bpo-40170: Update What's New in Python 3.9
  Doc/whatsnew/3.9.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#29460 bpo-45712: Fix typo in 'control flow' documentation
  Doc/tutorial/controlflow.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, needs backport to 3.10

#29471 [3.10] bpo-40170: Update What's New in Python 3.9 (GH-29470)
  Doc/whatsnew/3.9.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#29472 [3.9] bpo-40170: Update What's New in Python 3.9 (GH-29470)
  Doc/whatsnew/3.9.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#29473 [3.10] Closes bpo-45712: Add missing word in control flow tutorial (GH-29460)
  Doc/tutorial/controlflow.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#29466 bpo-45723: Add macro for disabling/enabling CC warnings (GH-29466)
  configure
  configure.ac
Labels: CLA signed, awaiting merge, skip news

#29441 bpo-45723: Prepare support for autoconf 2.71 (GH-29441)
  Include/pyport.h
  Misc/NEWS.d/next/Build/2021-11-07-10-45-40.bpo-45723.AreusF.rst
  Modules/_collectionsmodule.c
  Modules/arraymodule.c
  Objects/listobject.c
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting core review, skip news

#29476 Add third-party Windows build definitions
  .azure-pipelines/find-tools.yml
  .azure-pipelines/libffi-build.yml
  .azure-pipelines/openssl-build.yml
  .azure-pipelines/tcltk-build.yml
Labels: CLA signed, OS-windows, skip issue, awaiting core review, skip news

#29464 bpo-45743: -Wl,-search_paths_first is no longer needed (GH-29464)
  Misc/NEWS.d/next/Build/2021-11-08-08-58-06.bpo-45743.fZ8CTi.rst
  configure
  configure.ac
  setup.py
Labels: CLA signed, awaiting merge

#29457 bpo-45743: Remove workaround for zlib CVE from 2002 (GH-29457)
  setup.py
Labels: CLA signed, awaiting core review, skip news

#29257 bpo-45637: Remove broken fallback in gdb helpers to obtain frame variable
  Lib/test/test_gdb.py
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review, skip news

#29486 bpo-45723: Remove obsolete AC_EXEEXT from configure.ac
  configure
  configure.ac
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#29483 bpo-45763: Detect compression build deps in configure (GH-29483)
  Doc/whatsnew/3.11.rst
  Misc/NEWS.d/next/Build/2021-11-09-10-15-33.bpo-45763.gP-vrX.rst
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed, awaiting core review

#29491 Minor edit: Factor-out constant calculation.
  Lib/statistics.py
Labels: CLA signed, type-performance, skip issue, awaiting core review, skip news

#29493 [3.10] bpo-45732: Update bundled Tcl/Tk on Windows to 8.6.12 (GH-29477)
  Misc/NEWS.d/next/Windows/2021-11-08-21-53-11.bpo-45732.idl5kx.rst
  PCbuild/get_externals.bat
  PCbuild/tcltk.props
Labels: CLA signed, awaiting core review, needs backport to 3.9

#29496 [3.9] bpo-45732: Update bundled Tcl/Tk on Windows to 8.6.12 (GH-29477)
  Misc/NEWS.d/next/Windows/2021-11-08-21-53-11.bpo-45732.idl5kx.rst
  PCbuild/get_externals.bat
  PCbuild/tcltk.props
Labels: CLA signed, awaiting core review

#29480 bpo-45757: make dis reset extended_arg when op does not have an arg
  Lib/dis.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Library/2021-11-08-23-22-14.bpo-45757.MHZHt3.rst
Labels: type-bugfix, CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#29501 bpo-45220: Ensure RT_MANIFEST is defined when compiling Windows resource files
  PC/pylauncher.rc
  PC/pyshellext.rc
  PC/python_exe.rc
  PC/python_nt.rc
  PC/pythonw_exe.rc
  PC/sqlite3.rc
Labels: CLA signed, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#29504 [3.10] bpo-45220: Ensure RT_MANIFEST is defined when compiling Windows resource files (GH-29501)
  PC/pylauncher.rc
  PC/pyshellext.rc
  PC/python_exe.rc
  PC/python_nt.rc
  PC/pythonw_exe.rc
  PC/sqlite3.rc
Labels: CLA signed, awaiting merge, skip news

#29500 bpo-45723: Remove dead code for obsolete `--with-dyld` option
  configure
  configure.ac
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#29506 [3.10] bpo-45757: Fix bug where dis produced an incorrect oparg on EXTENDED_ARG before a no-arg opcode (GH-29480)
  Lib/dis.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Library/2021-11-08-23-22-14.bpo-45757.MHZHt3.rst
Labels: type-bugfix, CLA signed, awaiting core review

#29498 bpo-45701: Improve documentation for *typed* parameter
  Doc/library/functools.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, needs backport to 3.10

#29487 [bpo-45765] Fix distribution discovery on empty path.
  Lib/importlib/metadata/__init__.py
  Misc/NEWS.d/next/Library/2021-11-09-09-04-19.bpo-45765.JVobxK.rst
Labels: CLA signed, awaiting core review, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#29515 bpo-45637: Fix cframe-based fallback in the gdb helpers
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review, skip news

#29485 bpo-45723: Improve and simplify more configure.ac checks (GH-29485)
  configure
  configure.ac
Labels: CLA signed, awaiting merge, skip news

#29404 bpo-45711: Use _PyErr_ClearExcState instead of setting only exc_value…
  Modules/_asynciomodule.c
Labels: CLA signed, awaiting merge, skip news

#29495 bpo-45711: remove unnecessary DUP_TOP and POP in exception handling
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_dis.py
  Python/ceval.c
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#29489 bpo-45754: Use correct SQLite limit when checking statement length
  Lib/test/test_sqlite3/test_dbapi.py
  Lib/test/test_sqlite3/test_regression.py
  Misc/NEWS.d/next/Library/2021-11-09-15-48-38.bpo-45754.c-JDto.rst
  Modules/_sqlite/cursor.c
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting merge

#29467 bpo-45747: Detect gdbm/dbm dependencies in configure (GH-29467)
  Doc/whatsnew/3.11.rst
  Misc/NEWS.d/next/Build/2021-11-08-11-31-48.bpo-45747.AODmk_.rst
  Modules/Setup
  Modules/_dbmmodule.c
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: CLA signed, awaiting core review

#29517 bpo-45723: Add --with-pkg-config to configure (GH-29517)
  Doc/using/configure.rst
  Misc/NEWS.d/next/Build/2021-11-10-16-13-02.bpo-45723.B5gCB1.rst
  configure
  configure.ac
Labels: CLA signed, awaiting core review

#29118 bpo-45696: Deep-freeze
  .gitattributes
  .gitignore
  Doc/library/ctypes.rst
  Include/cpython/import.h
  Lib/ctypes/test/test_values.py
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2021-11-03-00-19-50.bpo-45696.eKs46f.rst
  Python/bootstrap_frozen.c
  Python/deepfreeze/README.txt
  Python/frozen.c
  Python/import.c
  Tools/freeze/test/freeze.py
  Tools/scripts/deepfreeze.py
  Tools/scripts/freeze_modules.py
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#29482 bpo-45636: `BINARY_OP` (third time's the charm)
  Doc/library/dis.rst
  Doc/whatsnew/3.11.rst
  Include/internal/pycore_code.h
  Include/opcode.h
  Lib/dis.py
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Lib/test/test_peepholer.py
  Misc/NEWS.d/next/Core and Builtins/2021-10-27-15-14-31.bpo-45636.K2X7QS.rst
  Python/ceval.c
  Python/compile.c
  Python/opcode_targets.h
  Python/specialize.c
  Tools/scripts/generate_opcode_h.py
Labels: CLA signed, awaiting core review

#29505 bpo-45773: Stop "optimizing" certain jump patterns
  Lib/test/test_peepholer.py
  Misc/NEWS.d/next/Core and Builtins/2021-11-09-13-01-35.bpo-45773.POU8A4.rst
  Python/compile.c
Labels: type-bugfix, CLA signed, awaiting changes, needs backport to 3.10

#29526 [3.10] bpo-45773: Stop "optimizing" certain jump patterns (GH-29505)
  Lib/test/test_peepholer.py
  Misc/NEWS.d/next/Core and Builtins/2021-11-09-13-01-35.bpo-45773.POU8A4.rst
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: type-bugfix, CLA signed, awaiting core review

#29525 bpo-45235: Revert an argparse bugfix that caused a regression
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2021-11-11-13-03-17.bpo-45235.8ZbkHa.rst
Labels: type-bugfix, CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#29533 bpo-45792: Fix contextvar.Token's intersphinx FQN
  Doc/library/contextvars.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10

#29535 [3.10] bpo-45792: Fix contextvar.Token's intersphinx FQN (GH-29533)
  Doc/library/contextvars.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29536 [3.9] bpo-45792: Fix contextvar.Token's intersphinx FQN (GH-29533)
  Doc/library/contextvars.rst
Labels: CLA signed, type-documentation, awaiting review, skip news

#29528 bpo-45711: Re-bump the magic number and update doc
  Doc/library/dis.rst
  Doc/whatsnew/3.11.rst
  Lib/importlib/_bootstrap_external.py
Labels: CLA signed, awaiting merge, skip news

#29514 bpo-45745: Remove regrtest --findleaks options
  Lib/test/libregrtest/cmdline.py
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/runtest.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2021-11-10-12-01-28.bpo-45745.wX5B3K.rst
Labels: CLA signed, awaiting merge

#29531 [3.9] bpo-45235: Revert an argparse bugfix that caused a regression (GH-29525)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2021-11-11-13-03-17.bpo-45235.8ZbkHa.rst
Labels: type-bugfix, CLA signed, awaiting review

#29530 [3.10] bpo-45235: Revert an argparse bugfix that caused a regression (GH-29525)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2021-11-11-13-03-17.bpo-45235.8ZbkHa.rst
Labels: type-bugfix, CLA signed, awaiting review

#29518 bpo-45711: assert that the type of exc_info is redundant
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#23960 bpo-45772: socket.socket should be a class instead of a function
  Doc/library/socket.rst
  Misc/NEWS.d/next/Documentation/2021-11-09-13-10-55.bpo-45772.EdrM3t.rst
Labels: CLA signed, type-documentation, awaiting core review, needs backport to 3.8, stale, needs backport to 3.9, needs backport to 3.10
