Repository python/cpython, pull requests merged in 2021-01, with the labels that each got.

#24031 bpo-42781: Document the mechanics of cached_property from a user viewpoint
  Doc/library/functools.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news, type-documentation

#24035 [3.9] bpo-42781: Document the mechanics of cached_property from a user viewpoint (GH-24031)
  Doc/library/functools.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24037 bpo-42794: Update test_nntplib to use offical group name for testing
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Tests/2021-01-01-08-52-36.bpo-42794.-7-XGz.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, type-tests

#24040 [3.8] bpo-42794: Update test_nntplib to use offical group name for testing (GH-24037)
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Tests/2021-01-01-08-52-36.bpo-42794.-7-XGz.rst
Labels: CLA signed, awaiting merge, type-tests

#24039 [3.9] bpo-42794: Update test_nntplib to use offical group name for testing (GH-24037)
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Tests/2021-01-01-08-52-36.bpo-42794.-7-XGz.rst
Labels: CLA signed, awaiting merge, type-tests

#24036 Bring Python into the new year.
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting merge, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#23969 bpo-42756: Configure LMTP Unix-domain socket to use global default timeout when timeout not provided
  Lib/smtplib.py
  Lib/test/mock_socket.py
  Lib/test/test_smtplib.py
  Misc/NEWS.d/next/Library/2020-12-27-21-22-01.bpo-42756.dHMPJ9.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9

#24045 [3.9] Bring Python into the new year. (GH-24036)
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#24046 [3.8] Bring Python into the new year. (GH-24036)
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news

#24026 [3.8] bpo-42759: Fix equality comparison of Variable and Font in Tkinter (GH-23968)
  Lib/tkinter/__init__.py
  Lib/tkinter/font.py
  Lib/tkinter/test/test_tkinter/test_font.py
  Lib/tkinter/test/test_tkinter/test_variables.py
  Misc/NEWS.d/next/Library/2020-12-27-22-19-26.bpo-42759.lGi_03.rst
Labels: CLA signed, awaiting core review, type-bugfix

#24025 [3.8] bpo-42425: Fix possible leak in initialization of errmap for OSError (GH-23446).
  Objects/exceptions.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#24023 [3.8] bpo-36589: Fix the error handling in curses.update_lines_cols() (GH-12766)
  Misc/NEWS.d/next/Library/2019-11-16-22-56-51.bpo-36589.0Io76D.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: CLA signed, awaiting core review, type-bugfix

#24022 [3.8] bpo-39068: Fix race condition in base64 (GH-17627)
  Lib/base64.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-12-16-17-55-31.bpo-39068.Ti3f9P.rst
Labels: CLA signed, awaiting core review, type-bugfix

#24021 [3.8] bpo-26407: Do not mask errors in csv. (GH-20536)
  Lib/test/test_csv.py
  Misc/NEWS.d/next/Library/2020-05-30-14-19-47.bpo-26407.MjWLO1.rst
  Modules/_csv.c
Labels: CLA signed, awaiting core review, type-bugfix

#24041 [3.7] bpo-42794: Update test_nntplib to use offical group name for testing (GH-24037)
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Tests/2021-01-01-08-52-36.bpo-42794.-7-XGz.rst
Labels: CLA signed, awaiting merge, type-tests

#24052 [3.7] Bring Python into the new year. (GH-24036)
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting review, skip issue, skip news

#24042 [3.6] bpo-42794: Update test_nntplib to use offical group name for testing (GH-24037)
  Lib/test/test_nntplib.py
  Misc/NEWS.d/next/Tests/2021-01-01-08-52-36.bpo-42794.-7-XGz.rst
Labels: CLA signed, awaiting merge, type-tests

#24051 [3.9] bpo-39068: Fix race condition in base64 (GH-17627)
  Lib/base64.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2019-12-16-17-55-31.bpo-39068.Ti3f9P.rst
Labels: CLA signed, awaiting merge, type-bugfix

#24000 bpo-41559: Documentation for PEP 612
  Doc/library/stdtypes.rst
  Doc/library/typing.rst
  Doc/whatsnew/3.10.rst
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip news

#24050 [3.9] bpo-42756: Configure LMTP Unix-domain socket to use global defa…
  Lib/smtplib.py
  Lib/test/mock_socket.py
  Lib/test/test_smtplib.py
  Misc/NEWS.d/next/Library/2020-12-27-21-22-01.bpo-42756.dHMPJ9.rst
Labels: CLA signed, awaiting review

#24054 [3.6] Bring Python into the new year (GH-24036)
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: CLA signed, awaiting core review, skip issue, skip news

#24057 [3.9] bpo-42425: Fix possible leak in initialization of errmap for OSError (GH-23446).
  Objects/exceptions.c
Labels: CLA signed, awaiting core review, skip news, type-bugfix

#23140 bpo-42257: handle empty string in variable executable in platform.libc_ver()
  Lib/platform.py
  Misc/NEWS.d/next/Library/2020-12-31-23-05-53.bpo-42257.ALQy7B.rst
Labels: CLA signed, awaiting review

#24059 bpo-42195: Disallow isinstance/issubclass for subclasses of genericaliases in Union
  Lib/test/test_types.py
  Objects/unionobject.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#23124 bpo-40077: Convert arraymodule to use heap types and establish module state
  Misc/NEWS.d/next/Core and Builtins/2020-11-03-13-46-10.bpo-40077.NfAIdj.rst
  Modules/arraymodule.c
  Modules/clinic/arraymodule.c.h
Labels: CLA signed, awaiting merge

#24060 bpo-42809: Improve pickle tests for recursive data.
  Lib/test/pickletester.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-tests

#24009 bpo-42789: Don't skip curses tests on non-tty.
  Lib/test/test_curses.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-tests

#24063 [3.8] bpo-42809: Improve pickle tests for recursive data. (GH-24060)
  Lib/test/pickletester.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#24062 [3.9] bpo-42809: Improve pickle tests for recursive data. (GH-24060)
  Lib/test/pickletester.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#24018 bpo-42772: Step argument ignored when stop is None.
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2020-12-30-17-16-43.bpo-42772.Xe7WFV.rst
Labels: CLA signed, awaiting core review

#24064 No need to test "istep==1" twice.
  Lib/random.py
Labels: CLA signed, awaiting core review, skip issue, skip news, type-performance

#24027 bpo-40631: Disallow single parenthesized star target
  Grammar/python.gram
  Lib/test/test_unpack_ex.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-31-20-58-22.bpo-40631.deRMCx.rst
  Parser/parser.c
Labels: CLA signed, awaiting merge, needs backport to 3.9

#24068 [3.9] bpo-40631: Disallow single parenthesized star target (GH-24027)
  Grammar/python.gram
  Lib/test/test_unpack_ex.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-31-20-58-22.bpo-40631.deRMCx.rst
  Parser/pegen/parse.c
Labels: :robot: automerge, CLA signed, awaiting merge

#24067 bpo-42806: Fix ast locations of f-strings inside parentheses
  Lib/test/test_fstring.py
  Misc/NEWS.d/next/Core and Builtins/2021-01-03-00-20-38.bpo-42806.mLAobJ.rst
  Parser/string_parser.c
Labels: CLA signed, awaiting merge, needs backport to 3.9

#24069 [3.9] bpo-42806: Fix ast locations of f-strings inside parentheses (GH-24067)
  Lib/test/test_fstring.py
  Misc/NEWS.d/next/Core and Builtins/2021-01-03-00-20-38.bpo-42806.mLAobJ.rst
  Parser/pegen/parse_string.c
Labels: :robot: automerge, CLA signed, awaiting merge

#24070 bpo-42093: Tweak the what's new message about the new LOAD_ATTR opcode cache
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24073 bpo-42814: Fix undefined behavior in Objects/genericaliasobject.c
  Misc/NEWS.d/next/Core and Builtins/2021-01-03-04-41-25.bpo-42814.sDvVbb.rst
  Objects/genericaliasobject.c
Labels: CLA signed, awaiting review

#23919 bpo-38308: Fix the "versionchanged" for the *weights* of harmonic_mean()
  Doc/library/statistics.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24066 bpo-40077: Add traverse/clear/free to arraymodule
  Modules/arraymodule.c
Labels: CLA signed, awaiting core review, skip news

#24061 bpo-41798: Allocate the expat_CAPI on the heap memory.
  Modules/pyexpat.c
Labels: CLA signed, awaiting review, skip news

#23874 bpo-42681: Fix range checks for color and pair numbers in curses
  Doc/library/curses.rst
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2020-12-20-22-50-15.bpo-42681.lDO6jb.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#24076 [3.9] bpo-42789: Don't skip curses tests on non-tty. (GH-24009)
  Lib/test/test_curses.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-tests

#24078 [3.8] [3.9] bpo-42789: Don't skip curses tests on non-tty. (GH-24009) (GH-24076)
  Lib/test/test_curses.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#24077 [3.9] bpo-42681: Fix range checks for color and pair numbers in curses (GH-23874).
  Doc/library/curses.rst
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2020-12-20-22-50-15.bpo-42681.lDO6jb.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: CLA signed, awaiting core review, needs backport to 3.8, type-bugfix

#23674 bpo-42584: Update macOS installer to use SQLite 3.34.0
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2020-12-07-11-37-35.bpo-42584.LygmqQ.rst
Labels: CLA signed, awaiting review

#24079 [3.8] [3.9] bpo-42681: Fix range checks for color and pair numbers in curses (GH-23874). (GH-24077)
  Doc/library/curses.rst
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2020-12-20-22-50-15.bpo-42681.lDO6jb.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: CLA signed, awaiting core review, type-bugfix

#24080 bpo-41837: Update macOS installer build to use OpenSSL 1.1.1i.
  Mac/BuildScript/build-installer.py
  Mac/BuildScript/openssl-mac-arm64.patch
  Misc/NEWS.d/next/macOS/2021-01-04-00-48-08.bpo-41837.dX-unJ.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9

#24081 bpo-42361: Update macOS installer build to use Tcl/Tk 8.6.11
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2021-01-04-01-17-17.bpo-42361.eolZAi.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9

#24082 Update Sphinx version for macOS installer build.
  Mac/BuildScript/build-installer.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#24086 [3.9] bpo-42361: Update macOS installer build to use Tcl/Tk 8.6.11 (GH-24081)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2021-01-04-01-17-17.bpo-42361.eolZAi.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#24088 [3.8] Update Sphinx version for macOS installer build. (GH-24082)
  Mac/BuildScript/build-installer.py
Labels: CLA signed, awaiting review, skip issue, skip news

#24087 [3.9] Update Sphinx version for macOS installer build. (GH-24082)
  Mac/BuildScript/build-installer.py
Labels: CLA signed, awaiting review, skip issue, skip news

#24084 [3.8] bpo-41837: Update macOS installer build to use OpenSSL 1.1.1i. (GH-24080)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2021-01-04-00-48-08.bpo-41837.dX-unJ.rst
Labels: CLA signed, awaiting review

#24083 [3.9] bpo-41837: Update macOS installer build to use OpenSSL 1.1.1i. (GH-24080)
  Mac/BuildScript/build-installer.py
  Mac/BuildScript/openssl-mac-arm64.patch
  Misc/NEWS.d/next/macOS/2021-01-04-00-48-08.bpo-41837.dX-unJ.rst
Labels: CLA signed, awaiting review

#24085 bpo-42789: Enable using /dev/tty in test_curses.
  Lib/test/test_curses.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#23873 bpo-42692: fix __builtin_available check on older compilers
  Misc/NEWS.d/next/Build/2021-01-04-05-07-30.bpo-42692.OO11SN.rst
  Modules/posixmodule.c
Labels: :robot: automerge, CLA signed, OS-mac, awaiting merge, needs backport to 3.9

#24090 [3.9] bpo-42692: fix __builtin_available check on older compilers (GH-23873)
  Misc/NEWS.d/next/Build/2021-01-04-05-07-30.bpo-42692.OO11SN.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting review

#24094 bpo-42246: Delete the now unused c_do_not_emit_bytecode field.
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#22222 bpo-1635741: port pyexpat to multi-phase init (PEP 489)
  Misc/NEWS.d/next/Core and Builtins/2020-09-12-19-21-52.bpo-1635741.F2kDrU.rst
  Modules/clinic/pyexpat.c.h
  Modules/pyexpat.c
Labels: CLA signed, awaiting review

#24093 [3.8] bpo-42822: Revert "[3.8] [doc] Fix erroneous backslashes in signatures and names (GH-23658)"
  Doc/library/asyncio-stream.rst
  Doc/library/base64.rst
  Doc/library/difflib.rst
  Doc/library/email.header.rst
  Doc/library/functions.rst
  Doc/library/http.cookies.rst
  Doc/library/io.rst
  Doc/library/xml.dom.minidom.rst
  Doc/requirements.txt
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#24092 [3.9] bpo-42822: Revert "[3.9] [doc] Fix erroneous backslashes in signatures and names (GH-23658)"
  Doc/library/asyncio-stream.rst
  Doc/library/base64.rst
  Doc/library/difflib.rst
  Doc/library/email.header.rst
  Doc/library/functions.rst
  Doc/library/http.cookies.rst
  Doc/library/io.rst
  Doc/library/xml.dom.minidom.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#24097 Fix 'make suspicious' for the itertools module
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting core review, skip issue, skip news

#24091 bpo-42810: Mark jumps at end of if and try statements as artificial.
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting core review, skip news

#24101 Do not remove x bit from published directories
  Tools/msi/uploadrelease.ps1
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#24103 [3.8] Do not remove x bit from published directories (GH-24101)
  Tools/msi/uploadrelease.ps1
Labels: CLA signed, awaiting merge, skip issue, skip news

#24102 [3.9] Do not remove x bit from published directories (GH-24101)
  Tools/msi/uploadrelease.ps1
Labels: CLA signed, awaiting merge, skip issue, skip news

#24095 bpo-1635741: Adapt _multibytecodec to multi-phase initialization
  Misc/NEWS.d/next/Library/2021-01-04-15-05-40.bpo-1635741.EOCfZY.rst
  Modules/cjkcodecs/multibytecodec.c
  Modules/cjkcodecs/multibytecodec.h
Labels: CLA signed, awaiting review

#20530 bpo-40810: Fix CheckTraceCallbackContent for SQLite pre 3.7.15
  Lib/sqlite3/test/hooks.py
  Misc/NEWS.d/next/Tests/2020-05-30-10-56-38.bpo-40810.LPqDLQ.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#24105 [3.8] bpo-40810: Fix CheckTraceCallbackContent for SQLite pre 3.7.15 (GH-20530)
  Lib/sqlite3/test/hooks.py
  Misc/NEWS.d/next/Tests/2020-05-30-10-56-38.bpo-40810.LPqDLQ.rst
Labels: CLA signed, awaiting merge

#24104 [3.9] bpo-40810: Fix CheckTraceCallbackContent for SQLite pre 3.7.15 (GH-20530)
  Lib/sqlite3/test/hooks.py
  Misc/NEWS.d/next/Tests/2020-05-30-10-56-38.bpo-40810.LPqDLQ.rst
Labels: CLA signed, awaiting merge

#24110 bpo-40810: Fix broken NEWS markup
  Misc/NEWS.d/next/Tests/2020-05-30-10-56-38.bpo-40810.LPqDLQ.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24109 bpo-40636: Remove overly-strict zip pickling tests
  Lib/test/test_builtin.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#24089 bpo-42681: Fix test_curses failures related to COLOR_PAIRS
  Lib/test/test_curses.py
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting core review, skip news, type-tests

#14491 bpo-32631: IDLE: Enable zzdummy extension module
  Lib/idlelib/NEWS.txt
  Lib/idlelib/configdialog.py
  Lib/idlelib/extend.txt
  Lib/idlelib/idle_test/test_zzdummy.py
  Lib/idlelib/zzdummy.py
  Misc/NEWS.d/next/IDLE/2019-06-30-20-31-09.bpo-32631.e7_4BG.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-enhancement

#23670 [3.8] bpo-42508: Keep IDLE running on macOS (GH-23577)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/runscript.py
  Misc/NEWS.d/next/IDLE/2020-11-30-19-46-05.bpo-42508.fE7w4M.rst
Labels: CLA signed, awaiting review, type-bugfix

#24111 [3.9] bpo-40810: Fix broken NEWS markup (GH-24110)
  Misc/NEWS.d/next/Tests/2020-05-30-10-56-38.bpo-40810.LPqDLQ.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24114 [3.9] bpo-32631: IDLE: Enable zzdummy example extension module (GH-14…
  Lib/idlelib/NEWS.txt
  Lib/idlelib/configdialog.py
  Lib/idlelib/extend.txt
  Lib/idlelib/idle_test/test_zzdummy.py
  Lib/idlelib/zzdummy.py
  Misc/NEWS.d/next/IDLE/2019-06-30-20-31-09.bpo-32631.e7_4BG.rst
Labels: CLA signed, awaiting core review, type-enhancement

#24115 [3.8] bpo-32631: IDLE: Enable zzdummy example extension module (GH-14491)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/configdialog.py
  Lib/idlelib/extend.txt
  Lib/idlelib/idle_test/test_zzdummy.py
  Lib/idlelib/zzdummy.py
  Misc/NEWS.d/next/IDLE/2019-06-30-20-31-09.bpo-32631.e7_4BG.rst
Labels: CLA signed, awaiting core review, type-enhancement

#24113 [3.9] bpo-42681: Fix test_curses failures related to color pairs (GH-24089)
  Lib/test/test_curses.py
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting core review, needs backport to 3.8, skip news, type-tests

#24116 [3.8] [3.9] bpo-42681: Fix test_curses failures related to color pairs (GH-24089) (GH-24113)
  Lib/test/test_curses.py
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting core review, skip news, type-tests

#24005 [3.9] bpo-40052: Fix alignment issue in PyVectorcall_Function() (GH-23999)
  Include/cpython/abstract.h
  Misc/NEWS.d/next/C API/2020-03-24-09-27-10.bpo-40052.27P2KG.rst
  Objects/call.c
Labels: CLA signed, awaiting review

#24125 bpo-41837: Updated Windows installer to include OpenSSL 1.1.1i
  Misc/NEWS.d/next/Windows/2021-01-05-20-36-40.bpo-41837.bmS7vB.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-security

#23675 bpo-42584 : Update Windows installer to use SQLite 3.34.0
  Misc/NEWS.d/next/Windows/2020-12-07-11-40-52.bpo-42584.AsYnVX.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting review

#24129 [3.8] bpo-42584: Update macOS installer to use SQLite 3.34.0 (GH-23674).
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2020-12-07-11-37-35.bpo-42584.LygmqQ.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#24127 [3.9] bpo-41837: Updated Windows installer to include OpenSSL 1.1.1i (GH-24125)
  Misc/NEWS.d/next/Windows/2021-01-05-20-36-40.bpo-41837.bmS7vB.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting core review, needs backport to 3.8, type-security

#24007 bpo-40956: Convert _sqlite3.Cursor to Argument Clinic
  Modules/_sqlite/clinic/cursor.c.h
  Modules/_sqlite/cursor.c
  Modules/_sqlite/cursor.h
Labels: CLA signed, awaiting merge, skip news

#24106 bpo-40810: Require SQLite 3.7.15
  Doc/library/sqlite3.rst
  Doc/whatsnew/3.10.rst
  Lib/sqlite3/test/dbapi.py
  Lib/sqlite3/test/hooks.py
  Misc/NEWS.d/next/Library/2021-01-05-00-52-30.bpo-40810.JxQqPe.rst
  Modules/_sqlite/connection.c
  Modules/_sqlite/module.c
  Modules/_sqlite/util.h
  setup.py
Labels: CLA signed, awaiting merge

#24131 [3.8] bpo-41837: Updated Windows installer to include OpenSSL 1.1.1i (GH-24125)
  Misc/NEWS.d/next/Windows/2021-01-05-20-36-40.bpo-41837.bmS7vB.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting core review, type-security

#24132 [3.9] bpo-42584: Update Windows installer to use SQLite 3.34.0 (GH-23675)
  Misc/NEWS.d/next/Windows/2020-12-07-11-40-52.bpo-42584.AsYnVX.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting core review

#23159 bpo-38413: Improve documentation of sqlite3 module
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24134 [3.8] bpo-38413: Remove outdated section about multithreading in sqlite3 (GH-23159)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23971 [3.8] bpo-42755: Fix sqlite3.Connection.backup docs (GH-23965)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24133 [3.8] bpo-42584: Update Windows installer to use SQLite 3.34.0 (GH-23675)
  Misc/NEWS.d/next/Windows/2020-12-07-11-40-52.bpo-42584.AsYnVX.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: CLA signed, awaiting core review

#24008 bpo-24464: Deprecate sqlite3.enable_shared_cache
  Doc/whatsnew/3.10.rst
  Lib/sqlite3/dbapi2.py
  Lib/sqlite3/test/dbapi.py
  Misc/NEWS.d/next/Library/2020-12-30-14-56-25.bpo-24464.vbNVHe.rst
Labels: CLA signed, awaiting merge

#20828 bpo-40959: Remove unused and unneeded declarations from sqlite3 headers
  Modules/_sqlite/cache.h
  Modules/_sqlite/connection.h
  Modules/_sqlite/cursor.h
  Modules/_sqlite/prepare_protocol.h
  Modules/_sqlite/statement.h
Labels: CLA signed, awaiting merge, skip news

#13716 bpo-14014: Clarify StreamWriter.reset() documentation
  Doc/library/codecs.rst
  Lib/codecs.py
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news, type-documentation

#24136 [3.9] bpo-14014: Clarify StreamWriter.reset() documentation (GH-13716)
  Doc/library/codecs.rst
  Lib/codecs.py
Labels: CLA signed, awaiting review, skip news, type-documentation

#23602 bpo-42528: Improve the docs of most Py*_Check{,Exact} API calls.
  Doc/c-api/bool.rst
  Doc/c-api/bytearray.rst
  Doc/c-api/bytes.rst
  Doc/c-api/capsule.rst
  Doc/c-api/cell.rst
  Doc/c-api/code.rst
  Doc/c-api/complex.rst
  Doc/c-api/coro.rst
  Doc/c-api/datetime.rst
  Doc/c-api/dict.rst
  Doc/c-api/float.rst
  Doc/c-api/function.rst
  Doc/c-api/gen.rst
  Doc/c-api/iter.rst
  Doc/c-api/iterator.rst
  Doc/c-api/list.rst
  Doc/c-api/long.rst
  Doc/c-api/memoryview.rst
  Doc/c-api/method.rst
  Doc/c-api/module.rst
  Doc/c-api/set.rst
  Doc/c-api/slice.rst
  Doc/c-api/tuple.rst
  Doc/c-api/type.rst
  Doc/c-api/unicode.rst
  Doc/c-api/weakref.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24117 bpo-41798: Allocate _decimal extension module CAPI on the heap
  Include/pydecimal.h
  Modules/_decimal/_decimal.c
Labels: CLA signed, awaiting review, skip news

#24139 [3.9] bpo-42528: Improve the docs of most Py*_Check{,Exact} API calls (GH-23602)
  Doc/c-api/bool.rst
  Doc/c-api/bytearray.rst
  Doc/c-api/bytes.rst
  Doc/c-api/capsule.rst
  Doc/c-api/cell.rst
  Doc/c-api/code.rst
  Doc/c-api/complex.rst
  Doc/c-api/coro.rst
  Doc/c-api/datetime.rst
  Doc/c-api/dict.rst
  Doc/c-api/float.rst
  Doc/c-api/function.rst
  Doc/c-api/gen.rst
  Doc/c-api/iter.rst
  Doc/c-api/iterator.rst
  Doc/c-api/list.rst
  Doc/c-api/long.rst
  Doc/c-api/memoryview.rst
  Doc/c-api/method.rst
  Doc/c-api/module.rst
  Doc/c-api/set.rst
  Doc/c-api/slice.rst
  Doc/c-api/tuple.rst
  Doc/c-api/type.rst
  Doc/c-api/unicode.rst
  Doc/c-api/weakref.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24100 bpo-42811: Update importlib.utils.resolve_name() docs to use __spec__.parent
  Doc/library/importlib.rst
  Misc/NEWS.d/next/Documentation/2021-01-04-22-14-22.bpo-42811.HY2beA.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-documentation

#24126 bpo-41798: Allocate socket extension module CAPI on the heap
  Modules/socketmodule.c
  Modules/socketmodule.h
Labels: CLA signed, awaiting merge, skip news

#24096 bpo-41798: Allocate the datetime.datetime_CAPI on the heap memory.
  Modules/_datetimemodule.c
Labels: CLA signed, awaiting merge, skip news

#24145 [3.9] bpo-38413: Remove outdated section about multithreading in sqlite3 (GH-23159)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#20538 bpo-40823: Use loadTestsFromTestCase() iso. makeSuite() in sqlite3 tests
  Lib/sqlite3/test/backup.py
  Lib/sqlite3/test/dbapi.py
  Lib/sqlite3/test/dump.py
  Lib/sqlite3/test/factory.py
  Lib/sqlite3/test/hooks.py
  Lib/sqlite3/test/regression.py
  Lib/sqlite3/test/transactions.py
  Lib/sqlite3/test/types.py
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Tests/2020-05-30-13-39-22.bpo-40823.yB7K5w.rst
Labels: CLA signed, awaiting merge

#24147 bpo-42847: Normalise Lib/sqlite3/test/* file encodings
  Lib/sqlite3/test/dbapi.py
  Lib/sqlite3/test/factory.py
  Lib/sqlite3/test/hooks.py
  Lib/sqlite3/test/regression.py
  Lib/sqlite3/test/transactions.py
  Lib/sqlite3/test/types.py
Labels: CLA signed, awaiting merge, skip news

#24002 bpo-42783: Documentation for asyncio.sleep(0)
  Doc/library/asyncio-task.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#24150 bpo-42823: Update frame.f_lineno before any call to the (C) tracing function.
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#24149 [3.9] bpo-42811: Update importlib.utils.resolve_name() docs to use __spec__.parent (GH-24100)
  Doc/library/importlib.rst
  Misc/NEWS.d/next/Documentation/2021-01-07-12-08-59.bpo-42811.ePF7EC.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#24144 [3.8] bpo-42811: Update importlib.utils.resolve_name() docs to use __spec__.parent (GH-24100)
  Doc/library/importlib.rst
  Misc/NEWS.d/next/Documentation/2021-01-04-22-14-22.bpo-42811.HY2beA.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#24154 bpo-42851: [Enum] remove brittle __init_subclass__ support
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-01-07-11-44-22.bpo-42851.uyQFyd.rst
Labels: CLA signed, awaiting core review

#24155 [3.9] bpo-42851: [Enum] remove brittle __init_subclass__ support (GH-24154)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-01-07-11-44-22.bpo-42851.uyQFyd.rst
Labels: CLA signed, awaiting core review

#24156 bpo-42860: Remove type error from grammar
  Grammar/python.gram
  Parser/parser.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#24157 bpo-42846: Convert CJK codec extensions to multiphase init
  Lib/test/test_multibytecodec.py
  Misc/NEWS.d/next/Library/2021-01-07-23-31-17.bpo-42846.kukDjw.rst
  Modules/cjkcodecs/cjkcodecs.h
Labels: CLA signed, awaiting core review

#24165 bpo-42866: Fix refleak in CJK getcodec()
  Misc/NEWS.d/next/Library/2021-01-08-10-57-21.bpo-42866.Y1DnrO.rst
  Modules/cjkcodecs/cjkcodecs.h
Labels: CLA signed, awaiting core review

#24166 bpo-42866: Add traverse func to _multibytecodec.MultibyteCodec
  Modules/cjkcodecs/multibytecodec.c
Labels: CLA signed, awaiting core review, skip news

#24169 Fix a typo
  Doc/library/typing.rst
Labels: CLA not signed, awaiting merge, skip issue, skip news, type-documentation

#24043 bpo-42802: Remove distutils bdist_wininst command
  Doc/distutils/apiref.rst
  Doc/distutils/builtdist.rst
  Doc/distutils/commandref.rst
  Doc/distutils/introduction.rst
  Doc/extending/building.rst
  Doc/whatsnew/3.10.rst
  Lib/distutils/command/__init__.py
  Lib/distutils/command/bdist.py
  Lib/distutils/command/bdist_msi.py
  Lib/distutils/command/bdist_wininst.py
  Lib/distutils/command/wininst-10.0-amd64.exe
  Lib/distutils/command/wininst-10.0.exe
  Lib/distutils/command/wininst-14.0-amd64.exe
  Lib/distutils/command/wininst-14.0.exe
  Lib/distutils/command/wininst-6.0.exe
  Lib/distutils/command/wininst-7.1.exe
  Lib/distutils/command/wininst-8.0.exe
  Lib/distutils/command/wininst-9.0-amd64.exe
  Lib/distutils/command/wininst-9.0.exe
  Lib/distutils/tests/test_bdist.py
  Lib/distutils/tests/test_bdist_wininst.py
  Lib/test/test_sundry.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2021-01-01-15-29-16.bpo-42802.Lw-bzl.rst
  PC/bdist_wininst/PythonPowered.bmp
  PC/bdist_wininst/README.txt
  PC/bdist_wininst/archive.h
  PC/bdist_wininst/bdist_wininst.vcxproj
  PC/bdist_wininst/bdist_wininst.vcxproj.filters
  PC/bdist_wininst/build.bat
  PC/bdist_wininst/extract.c
  PC/bdist_wininst/install.c
  PC/bdist_wininst/install.rc
  PC/bdist_wininst/resource.h
  PC/layout/main.py
  PC/layout/support/distutils.command.bdist_wininst.py
  PC/layout/support/options.py
  PCbuild/lib.pyproj
  PCbuild/pcbuild.sln
  Tools/msi/distutils.command.bdist_wininst.py
Labels: CLA signed, awaiting core review

#24170 bpo-24464: Fix sqlite3.enable_shared_cache() deprecation wrapper
  Lib/sqlite3/dbapi2.py
  Lib/sqlite3/test/dbapi.py
Labels: CLA signed, awaiting merge, skip news

#24183 bpo-33065: Fix problem debugging user classes with __repr__ method
  Lib/idlelib/NEWS.txt
  Lib/idlelib/debugger_r.py
  Lib/idlelib/idle_test/test_debugger_r.py
  Misc/NEWS.d/next/IDLE/2021-01-10-01-25-43.bpo-33065.zmyHYJ.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-bugfix

#24184 [3.9] bpo-33065: Fix problem debugging user classes with __repr__ method (GH-24183)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/debugger_r.py
  Lib/idlelib/idle_test/test_debugger_r.py
  Misc/NEWS.d/next/IDLE/2021-01-10-01-25-43.bpo-33065.zmyHYJ.rst
Labels: CLA signed, awaiting merge, type-bugfix

#24176 Fix various ParamSpec errors in typing
  Doc/library/typing.rst
  Lib/typing.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24190 bpo-42870: Document change in argparse help output.
  Doc/whatsnew/3.10.rst
  Misc/ACKS
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24193 bpo-42882: _PyRuntimeState_Init() leaves unicode next_index unchanged
  Include/internal/pycore_runtime.h
  Misc/NEWS.d/next/Core and Builtins/2021-01-11-17-58-52.bpo-42882.WfTdfg.rst
  Python/pystate.c
Labels: CLA signed, awaiting core review

#24198 bpo-42882: Add test_embed.test_unicode_id_init()
  Lib/test/test_embed.py
  Programs/_testembed.c
Labels: CLA signed, awaiting core review, skip news

#22632 bpo-41994: Fix refcount issues in Python/import.c
  Include/cpython/import.h
  Include/internal/pycore_import.h
  Misc/NEWS.d/next/Core and Builtins/2020-10-10-14-16-03.bpo-41994.Xop8sV.rst
  Python/import.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, type-bugfix

#24120 [3.8] bpo-40052: Fix alignment issue in PyVectorcall_Function() (GH-23999)
  Include/cpython/abstract.h
  Misc/NEWS.d/next/C API/2020-03-24-09-27-10.bpo-40052.27P2KG.rst
  Objects/call.c
Labels: CLA signed, awaiting core review

#24200 bpo-42874: Remove grep -qE options for Solaris 10 compatibility
  Misc/NEWS.d/next/Build/2021-01-12-10-06-50.bpo-42874.XKK61g.rst
  configure
  configure.ac
Labels: :robot: automerge, CLA signed, awaiting merge

#24158 bpo-42848: remove recursion from TracebackException
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2021-01-12-19-34-06.bpo-42848.5G8oBl.rst
Labels: CLA signed, awaiting review

#23754 bpo-37324: Remove ABC aliases from collections
  Doc/library/collections.rst
  Doc/whatsnew/3.10.rst
  Lib/collections/__init__.py
  Misc/NEWS.d/next/Core and Builtins/2020-12-12-20-09-12.bpo-37324.jB-9_U.rst
Labels: CLA signed, awaiting merge

#24196 bpo-42901: [Enum] move member creation to `__set_name__`
  Lib/enum.py
  Lib/inspect.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-01-11-17-36-59.bpo-42901.gFd-ta.rst
Labels: CLA signed, awaiting core review

#24205 bpo-1635741: Fix PyModule_AddObjectRef to use EXPORT_FUNC
  PC/python3dll.c
Labels: CLA signed, awaiting merge, skip news

#24202 bpo-42908: Mark cleanup code at end of try-except and with artificial
  Lib/test/test_dis.py
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting core review, skip news

#24209 bpo-42908: Eliminate NOPs in extended blocks.
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#24208 bpo-42924: Fix incorrect copy in bytearray_repeat
  Lib/test/test_bytes.py
  Misc/NEWS.d/next/Core and Builtins/2021-01-13-14-06-01.bpo-42924._WS1Ok.rst
  Objects/bytearrayobject.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, type-bugfix

#24214 bpo-40956: fix sqlite3.Cursor.fetchmany() default value
  Modules/_sqlite/clinic/cursor.c.h
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting merge, skip news

#17996 bpo-39273: Expose BUTTON5_* constants in the curses module if available
  Doc/library/curses.rst
  Doc/whatsnew/3.10.rst
  Misc/NEWS.d/next/Library/2020-01-13-23-37-58.bpo-39273.m5hzxV.rst
  Modules/_cursesmodule.c
Labels: CLA signed, awaiting merge

#23974 Docs: Remove stray semicolon in init.rst
  Doc/c-api/init.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news, type-documentation

#24217 [3.9] Docs: Remove stray semicolon in init.rst (GH-23974)
  Doc/c-api/init.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24140 bpo-42827: Fix crash on SyntaxError in multiline expressions
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-01-06-17-06-37.bpo-42827.jtRR0D.rst
  Parser/pegen.c
  Parser/tokenizer.c
  Parser/tokenizer.h
Labels: CLA signed, awaiting merge

#24179 bpo-42877: add the 'compact' param to TracebackException's __init__
  Doc/library/traceback.rst
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2021-01-13-12-55-41.bpo-42877.Fi1zEG.rst
Labels: CLA signed, awaiting merge

#24222 bpo-42925: Mark instructions at end of class scope as artificial.
  Lib/test/test_sys_settrace.py
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#24221 bpo-42934: use TracebackException's new compact param in unittest.Tes…
  Lib/unittest/result.py
  Misc/NEWS.d/next/Library/2021-01-15-11-48-00.bpo-42934.ILKoOI.rst
Labels: CLA signed, awaiting merge

#24219 bpo-42931: Add randbytes to random.__all__
  Lib/random.py
  Misc/NEWS.d/next/Library/2021-01-15-00-23-50.bpo-42931.QD6U2B.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, type-bugfix

#24225 [3.9] bpo-42931: randbytes missing from random.__all__ (GH-24219)
  Lib/random.py
  Misc/NEWS.d/next/Library/2021-01-15-00-23-50.bpo-42931.QD6U2B.rst
Labels: CLA signed, awaiting review, type-bugfix

#23611 [3.8] bpo-42531: Teach importlib.resources.path to handle packages without __file__
  Lib/importlib/resources.py
  Lib/test/test_importlib/test_path.py
  Misc/NEWS.d/next/Library/2020-12-02-16-28-04.bpo-42531.2sLlFW.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.7, type-bugfix

#24232 [3.9] bpo-42163, bpo-42189, bpo-42659: Support uname_tuple._replace (GH-23010)
  Lib/platform.py
  Lib/test/test_platform.py
  Misc/NEWS.d/next/Library/2020-10-29-09-22-56.bpo-42163.O4VcCY.rst
Labels: CLA signed, awaiting core review

#24240 bpo-42923: Add Py_FatalError() test in test_capi
  Lib/test/test_capi.py
  Lib/test/test_faulthandler.py
  Modules/_testcapimodule.c
  Modules/faulthandler.c
Labels: CLA signed, awaiting core review, skip news

#24242 bpo-42923: Py_FatalError() avoids fprintf()
  Include/internal/pycore_traceback.h
  Python/pylifecycle.c
  Python/traceback.c
Labels: CLA signed, awaiting core review, skip news

#24235 bpo-42944 Fix Random.sample when counts is not None
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2021-01-18-10-41-44.bpo-42944.RrONvy.rst
Labels: CLA not signed, awaiting merge, needs backport to 3.9
