Repository python/cpython, pull requests merged in 2021-03, with the labels that each got.

#24673 bpo-42128: Add documentation for the new match-based AST nodes
  Doc/library/ast.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24626 [3.8] bpo-36346: Document removal schedule of deprecate APIs (GH-20879)
  Doc/c-api/arg.rst
  Doc/c-api/unicode.rst
  Misc/NEWS.d/next/Documentation/2020-06-15-10-45-45.bpo-36346.H0sS_i.rst
Labels: CLA signed, awaiting merge, type-documentation

#24585 [3.8] closes bpo-43266: Improve array formatting. (GH-24573)
  Doc/c-api/conversion.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#23721 bpo-42603: Use pkg-config to get TCL/TK paths for tkinter.
  Misc/NEWS.d/next/Build/2020-12-08-19-25-20.bpo-42603.mXs2dB.rst
  configure
  configure.ac
  setup.py
Labels: CLA signed, awaiting merge

#24664 bpo-42128: Add documentation for pattern matching (PEP 634)
  Doc/faq/design.rst
  Doc/reference/compound_stmts.rst
  Doc/reference/datamodel.rst
  Doc/reference/lexical_analysis.rst
  Doc/tutorial/controlflow.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24675 bpo-42603: Add whatsnew and ACKS entries.
  Doc/whatsnew/3.10.rst
  Misc/ACKS
Labels: CLA signed, awaiting core review, skip news, type-documentation

#24676 bpo-43103: Fix build failure with macOS framework builds.
  configure
  configure.ac
Labels: CLA signed, awaiting core review, skip news

#24677 bpo-41837: Update macOS installer build to use OpenSSL 1.1.1j.
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2021-02-28-22-49-46.bpo-41837.9fqyXC.rst
Labels: CLA signed, awaiting core review

#24678 [3.8] bpo-41837: Update macOS installer build to use OpenSSL 1.1.1j. (GH-24677)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2021-02-28-22-49-46.bpo-41837.9fqyXC.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#24679 [3.9] bpo-41837: Update macOS installer build to use OpenSSL 1.1.1j. (GH-24677)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2021-02-28-22-49-46.bpo-41837.9fqyXC.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#24479 bpo-11717: fix ssize_t redefinition error when targeting Win32 app
  Include/pyport.h
  Objects/structseq.c
  PC/pyconfig.h
  Parser/parser.c
  Tools/peg_generator/pegen/c_generator.py
Labels: CLA signed, awaiting merge, skip news

#24680 closes bpo-43349: Fix tuning(7) manpage hyperlink
  Doc/library/resource.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24685 [3.8] closes bpo-43349: Fix tuning(7) manpage hyperlink. (GH-24680)
  Doc/library/resource.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24363 [3.8] [doc] Document VIRTUAL_ENV environment variable (GH-21970) (GH-24363)
  Doc/using/venv-create.inc
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#24682 Fix typo in Mac/README.rst
  Mac/README.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24689 Fix grammar in enum documentation.
  Doc/library/enum.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#24690 [3.9] Fix grammar in enum documentation. (GH-24689)
  Doc/library/enum.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24692 Fixed linenumber missing when audit hook has an error
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting review, skip issue, skip news

#24694 [3.9] Fixed linenumber missing when audit hook has an error (GH-24692)
  Doc/tools/extensions/pyspecific.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#24173 bpo-42840: Document providing kwargs to type.
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, stale, type-documentation

#24696 [3.8] bpo-42840: Document providing kwargs to type. (GH-24173)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24390 Doc: Improve library/json document.
  Doc/library/json.rst
Labels: CLA signed, awaiting review, needs backport to 3.9, skip issue, skip news, type-documentation

#24698 [3.9] Doc: Improve library/json document. (GH-24390)
  Doc/library/json.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24657 bpo-41282: distutils: Fix stacklevel for DeprecationWarning
  Lib/distutils/__init__.py
  Misc/NEWS.d/next/Library/2021-03-02-09-54-22.bpo-41282.xL4h94.rst
Labels: CLA signed, awaiting merge

#18305 bpo-39523: Replace while loop in pysqlite_cursor_executescript with do-while loop
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting merge, skip news

#24697 bpo-43358: Fix bad free in assemble function
  Python/compile.c
Labels: CLA signed, awaiting review, skip news

#24501 [3.9] bpo-42500: Fix recursion in or after except (GH-23568)
  Include/cpython/pystate.h
  Include/internal/pycore_ceval.h
  Lib/test/test_exceptions.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2020-11-30-14-27-29.bpo-42500.excVKU.rst
  Python/ceval.c
  Python/errors.c
  Python/pystate.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review

#24359 bpo-43049: Use io.IncrementalNewlineDecoder for doctest newline conversion
  Lib/doctest.py
Labels: CLA signed, awaiting merge, skip news

#24001 bpo-42782: Fail fast for permission errors in shutil.move()
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-12-29-13-46-57.bpo-42782.3r0HFY.rst
Labels: CLA signed, awaiting review

#24287 bpo-42994: Add MIME types for opus, AAC, 3gpp and 3gpp2
  Lib/mimetypes.py
  Misc/NEWS.d/next/Library/2021-01-21-16-58-34.bpo-42994.El0Ksp.rst
Labels: CLA signed, awaiting merge

#24687 Reorder contents of 3.10's What's New
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24715 bpo-43382: Pin test runner to Ubuntu 18 to un-break CI (for now)
  .github/workflows/build.yml
Labels: CLA signed, awaiting core review, skip news, type-tests

#24718 [3.9] Pin test runner to Ubuntu 18 to un-break CI (GH-24715)
  .github/workflows/build.yml
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-tests

#24717 [3.8] Pin test runner to Ubuntu 18 to un-break CI (GH-24715)
  .github/workflows/build.yml
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-tests

#24721 Doc: typo fix.
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#24686 missing multiply symbol in the documentation
  Modules/mathmodule.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#24706 bpo-43368: Fix fetching empty bytes on SQLite.
  Lib/sqlite3/test/regression.py
  Misc/NEWS.d/next/Library/2021-03-02-13-45-05.bpo-43368.t9XEkQ.rst
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting merge

#24724 [3.8] bpo-42782: Fail fast for permission errors in shutil.move() (GH-24001)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-12-29-13-46-57.bpo-42782.3r0HFY.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#24725 [3.9] bpo-42782: Fail fast for permission errors in shutil.move() (GH24001)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-12-29-13-46-57.bpo-42782.3r0HFY.rst
Labels: :robot: automerge, CLA signed, awaiting core review

#24627 bpo-43295: Fix error handling of datetime.strptime format string '%z'
  Lib/_strptime.py
  Lib/test/datetimetester.py
  Misc/NEWS.d/next/Library/2021-02-22-22-54-40.bpo-43295.h_ffu7.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#24716 [3.7] Pin test runner to Ubuntu 18 to un-break CI (GH-24715)
  .github/workflows/build.yml
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-tests

#24487 bpo-43162: [Enum] update docs, renable doc tests
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#24727 bpo-39199: Add attribution to the Green Tree Snakes in the AST docs
  Doc/library/ast.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#24731 [3.9] Add an attribution to the Green Tree Snakes in the AST docs (GH-24727)
  Doc/library/ast.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#20442 bpo-40701: tempfile mixes str and bytes in an inconsistent manner
  Doc/library/tempfile.rst
  Lib/tempfile.py
  Lib/test/test_tempfile.py
  Misc/NEWS.d/next/Library/2020-05-27-05-42-39.bpo-40701.PBIgW1.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, type-bugfix

#24732 bpo-42128: Add __match_args__ to structseq-based classes
  Lib/test/test_structseq.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-03-19-04-23.bpo-42128.VouZjn.rst
  Objects/structseq.c
Labels: CLA signed, awaiting merge

#24738 Improve the description of the improvements in bpo-42202
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#24739 bpo-43271: Re-enable ceval.c optimizations for Windows debug builds
  Include/pyport.h
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#24737 bpo-43394: Fix -Wstrict-prototypes warnings
  Modules/_xxtestfuzz/fuzzer.c
  Modules/_zoneinfo.c
Labels: CLA signed, awaiting core review, skip news

#24723 bpo-43369: sqlite3_column_text() and sqlite3_column_blob() failures now raise MemoryError
  Lib/sqlite3/test/types.py
  Misc/NEWS.d/next/Library/2021-03-02-15-25-28.bpo-43369.F4knlQ.rst
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting merge

#24746 bpo-43396: normalise naming in sqlite3 doc examples
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24750 [3.9] bpo-37193: Remove thread objects which finished process its request (GH-23127)
  Lib/socketserver.py
  Lib/test/test_socketserver.py
  Misc/NEWS.d/next/Library/2020-06-12-21-23-20.bpo-37193.wJximU.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#24749 [3.8] bpo-37193: Remove thread objects which finished process its request (GH-23127)
  Lib/socketserver.py
  Lib/test/test_socketserver.py
  Misc/NEWS.d/next/Library/2020-06-12-21-23-20.bpo-37193.wJximU.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23399 bpo-42405: fix C extensions build on Windows ARM64
  Lib/distutils/msvc9compiler.py
  Misc/NEWS.d/next/Windows/2020-11-23-10-14-03.bpo-42405.4vQUja.rst
Labels: :robot: automerge, CLA signed, awaiting merge, stale

#24747 [3.9] bpo-43396: Normalise naming in sqlite3 doc examples (GH-24746)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24748 [3.8] bpo-43396: Normalise naming in sqlite3 doc examples (GH-24746)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24736 bpo-43391: Remove the reference to Python 2.4 from the doc-string
  Lib/subprocess.py
Labels: CLA not signed, awaiting merge, skip news

#24753 Revert "bpo-42405: fix C extensions build on Windows ARM64"
  Lib/distutils/msvc9compiler.py
  Misc/NEWS.d/next/Windows/2020-11-23-10-14-03.bpo-42405.4vQUja.rst
Labels: :robot: automerge, CLA signed, awaiting core review

#24670 bpo-42129: Add support for resources in namespaces
  Lib/importlib/_adapters.py
  Lib/importlib/_bootstrap_external.py
  Lib/importlib/_common.py
  Lib/importlib/abc.py
  Lib/importlib/readers.py
  Lib/importlib/resources.py
  Lib/test/test_importlib/namespacedata01/binary.file
  Lib/test/test_importlib/namespacedata01/utf-16.file
  Lib/test/test_importlib/namespacedata01/utf-8.file
  Lib/test/test_importlib/test_abc.py
  Lib/test/test_importlib/test_files.py
  Lib/test/test_importlib/test_open.py
  Lib/test/test_importlib/test_path.py
  Lib/test/test_importlib/test_read.py
  Lib/test/test_importlib/test_reader.py
  Lib/test/test_importlib/test_resource.py
  Lib/test/test_importlib/update-zips.py
  Lib/test/test_importlib/zipdata01/ziptestdata.zip
  Lib/test/test_importlib/zipdata02/ziptestdata.zip
  Misc/NEWS.d/next/Library/2021-02-28-04-21-35.bpo-42129.V0KifQ.rst
  Python/importlib_external.h
Labels: CLA signed, awaiting core review

#24752 bpo-43400: Remove "easy to use" from mock docs
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#24758 [3.9] bpo-43400: Remove "easy to use" from mock docs (GH-24752)
  Doc/library/unittest.mock.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24730 bpo-43390: Set SA_ONSTACK in PyOS_setsig
  Misc/NEWS.d/next/Core and Builtins/2021-03-03-17-58-49.bpo-43390.epPpwV.rst
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, type-enhancement

#24756 bpo-43406: Fix possible race condition where ``PyErr_CheckSignals`` tries to execute a non-Python signal handler
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-04-22-53-10.bpo-43406.Na_VpA.rst
  Modules/signalmodule.c
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#24726 Make tracing info (bounds, and previous instruction offset) a bit more robust
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#24757 bpo-43407: Docs: Clarify comparisons of time.monotonic() et al results
  Doc/library/time.rst
  Misc/NEWS.d/next/Documentation/2021-03-04-22-53-03.bpo-43407.x570l5.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, type-documentation

#24768 [3.8] bpo-43407: Clarify comparisons of time.monotonic() et al results (GH-24757)
  Doc/library/time.rst
  Misc/NEWS.d/next/Documentation/2021-03-04-22-53-03.bpo-43407.x570l5.rst
Labels: CLA signed, awaiting merge, type-documentation

#24769 [3.9] bpo-43407: Clarify comparisons of time.monotonic() et al results (GH-24757)
  Doc/library/time.rst
  Misc/NEWS.d/next/Documentation/2021-03-04-22-53-03.bpo-43407.x570l5.rst
Labels: CLA signed, awaiting merge, type-documentation

#24761 [3.9] bpo-43406: Fix possible race condition where ``PyErr_CheckSignals`` tries to execute a non-Python signal handler (GH-24756)
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-04-22-53-10.bpo-43406.Na_VpA.rst
  Modules/signalmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge

#24762 [3.8] bpo-43406: Fix possible race condition where ``PyErr_CheckSignals`` tries to execute a non-Python signal handler (GH-24756)
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-04-22-53-10.bpo-43406.Na_VpA.rst
  Modules/signalmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge

#24760 Put contextvars docs into the concurrency category
  Doc/library/concurrency.rst
  Doc/library/index.rst
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#24775 [3.8] Put contextvars docs into the concurrency category (GH-24760)
  Doc/library/concurrency.rst
  Doc/library/index.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24774 [3.9] Put contextvars docs into the concurrency category (GH-24760)
  Doc/library/concurrency.rst
  Doc/library/index.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24759 bpo-43372: Use _freeze_importlib for regen-frozen.
  Lib/ctypes/test/test_values.py
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2021-03-04-17-13-57.bpo-43372.FfqDVL.rst
  Python/frozen.c
  Python/frozen_hello.h
Labels: CLA signed, awaiting core review

#24754 bpo-43405: Fix DeprecationWarnings in test_unicode
  Lib/test/test_unicode.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#24740 bpo-43319: Fixed the tutorial on venv about standard library
  Doc/tutorial/venv.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#24780 bpo-43332: Buffer proxy connection setup packets before sending.
  Lib/http/client.py
  Lib/test/test_httplib.py
  Misc/NEWS.d/next/Library/2021-03-07-11-23-20.bpo-43332.weatsh.rst
Labels: CLA signed, awaiting merge, type-bugfix, type-performance

#24783 [3.9] bpo-43332: Buffer proxy connection setup packets before sending. (GH-24780)
  Lib/http/client.py
  Lib/test/test_httplib.py
  Misc/NEWS.d/next/Library/2021-03-07-11-23-20.bpo-43332.weatsh.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix, type-performance

#24693 bpo-43353: Document that logging.getLevelName() accepts string representation of logging level.
  Doc/library/logging.rst
  Lib/logging/__init__.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#24159 bpo-14678: Update zipimport to support importlib.invalidate_caches()
  Doc/library/zipimport.rst
  Lib/test/test_zipimport.py
  Lib/zipimport.py
  Misc/NEWS.d/next/Library/2021-01-07-21-25-49.bpo-14678.1zniCH.rst
  Python/importlib_zipimport.h
Labels: :robot: automerge, CLA signed, awaiting merge

#24786 bpo-37146: Move _PyEval_DeactivateOpCache() to the internal C API
  Include/cpython/ceval.h
  Include/internal/pycore_ceval.h
Labels: awaiting merge, skip news

#24789 bpo-43415: Fix typo on dataclasses.rst
  Doc/library/dataclasses.rst
Labels: CLA not signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24790 [3.9] bpo-43415: Fix typo on dataclasses.rst (GH-24789)
  Doc/library/dataclasses.rst
Labels: CLA not signed, awaiting review, skip news, type-documentation

#24791 [3.8] bpo-43415: Fix typo on dataclasses.rst (GH-24789)
  Doc/library/dataclasses.rst
Labels: CLA not signed, awaiting review, skip news, type-documentation

#24795 bpo-3329: Fix typo in PyObjectArenaAllocator doc
  Doc/c-api/memory.rst
Labels: CLA signed, needs backport to 3.8, needs backport to 3.9, skip news

#24800 [3.8] bpo-3329: Fix typo in PyObjectArenaAllocator doc (GH-24795)
  Doc/c-api/memory.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24799 [3.9] bpo-3329: Fix typo in PyObjectArenaAllocator doc (GH-24795)
  Doc/c-api/memory.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24797 bpo-43440 : Enable SQLite R*Tree support for windows builds
  Misc/NEWS.d/next/Windows/2021-03-09-11-15-41.bpo-43440.igy2Mn.rst
  PCbuild/sqlite3.vcxproj
Labels: CLA signed, awaiting review

#24806 bpo-43446: Fix footnote in sqlite3 docs
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24808 [3.9] bpo-43446: Fix markup in sqlite3 footnote (GH-24806)
  Doc/library/sqlite3.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24810 [3.8] bpo-43439: Add audit hooks for gc functions (GH-24794).
  Doc/library/gc.rst
  Lib/test/audit-tests.py
  Lib/test/test_audit.py
  Misc/NEWS.d/next/Security/2021-03-08-23-06-07.bpo-43439.5U3lXm.rst
  Modules/gcmodule.c
Labels: :robot: automerge, CLA signed, awaiting merge

#24798 bpo-43445: Add frozen modules to sys.stdlib_module_names
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2021-03-09-11-36-19.bpo-43445.jnj-UB.rst
  Programs/_testembed.c
  Python/stdlib_module_names.h
  Tools/scripts/generate_stdlib_module_names.py
Labels: CLA signed, awaiting core review

#24814 bpo-43456: Remove _xxsubinterpreters from sys.stdlib_module_names
  Python/stdlib_module_names.h
  Tools/scripts/generate_stdlib_module_names.py
Labels: CLA signed, awaiting core review, skip news

#24815 bpo-43406: Fix test_signal.test_stress_modifying_handlers()
  Lib/test/test_signal.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#24807 Fix error in documentation for ast.match_case
  Doc/library/ast.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#24611 bpo-43287: Use PEP 590 vectorcall to speed up filter()
  Misc/NEWS.d/next/Core and Builtins/2021-02-22-03-01-02.bpo-43287.aTs6fO.rst
  Python/bltinmodule.c
Labels: CLA signed, awaiting merge

#24777 bpo-43423 Fix IndexError in subprocess _communicate function
  Lib/subprocess.py
  Misc/NEWS.d/next/Library/2021-03-11-15-44-18.bpo-43423.rRomRD.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#24755 bpo-43356: Allow passing a signal number to interrupt_main()
  Doc/c-api/exceptions.rst
  Doc/data/stable_abi.dat
  Doc/library/_thread.rst
  Doc/whatsnew/3.10.rst
  Include/internal/pycore_pylifecycle.h
  Include/pyerrors.h
  Lib/test/test_threading.py
  Misc/NEWS.d/next/Library/2021-03-04-21-51-20.bpo-43356.X7IGBM.rst
  Modules/_threadmodule.c
  Modules/signalmodule.c
  PC/python3dll.c
Labels: CLA signed, awaiting merge

#24830 [3.8] bpo-43423 Fix IndexError in subprocess _communicate function (GH-24777)
  Lib/subprocess.py
  Misc/NEWS.d/next/Library/2021-03-11-15-44-18.bpo-43423.rRomRD.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#24831 [3.9] bpo-43423 Fix IndexError in subprocess _communicate function (GH-24777)
  Lib/subprocess.py
  Misc/NEWS.d/next/Library/2021-03-11-15-44-18.bpo-43423.rRomRD.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix

#24826 [3.9] bpo-43353: Document that logging.getLevelName() accepts string representation of logging level. (GH-24693)
  Doc/library/logging.rst
  Lib/logging/__init__.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#24118 bpo-27820: Fix AUTH LOGIN logic in smtplib.SMTP
  Lib/smtplib.py
  Lib/test/test_smtplib.py
  Misc/NEWS.d/next/Library/2021-03-10-14-07-44.bpo-27820.Wwdy-r.rst
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#24832 [3.9] bpo-27820: Fix AUTH LOGIN logic in smtplib.SMTP (GH-24118)
  Lib/smtplib.py
  Lib/test/test_smtplib.py
  Misc/NEWS.d/next/Library/2021-03-10-14-07-44.bpo-27820.Wwdy-r.rst
Labels: CLA signed, awaiting merge

#24833 [3.8] bpo-27820: Fix AUTH LOGIN logic in smtplib.SMTP (GH-24118)
  Lib/smtplib.py
  Lib/test/test_smtplib.py
  Misc/NEWS.d/next/Library/2021-03-10-14-07-44.bpo-27820.Wwdy-r.rst
Labels: CLA signed, awaiting core review

#24827 bpo-43479: Remove a duplicate comment and assignment in http.client
  Lib/http/client.py
Labels: CLA signed, awaiting merge, skip news

#24805 Update link to Django's Context class.
  Doc/library/collections.rst
  Doc/library/venv.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24842 [3.8] Update link to Django's Context class. (GH-24805)
  Doc/library/collections.rst
  Doc/library/venv.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24841 [3.9] Update link to Django's Context class. (GH-24805)
  Doc/library/collections.rst
  Doc/library/venv.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24839 [3.9] bpo-43479 Update client.py (GH-24827)
  Lib/http/client.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#24840 [3.8] bpo-43479 Update client.py (GH-24827)
  Lib/http/client.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#24821 bpo-40521: [subinterpreters] Make dtoa bigint free list per-interpreter
  Include/internal/pycore_dtoa.h
  Include/internal/pycore_interp.h
  Python/dtoa.c
Labels: CLA signed, awaiting change review, skip news

#24822 bpo-43441: fix [Subinterpreters]: global variable next_version_tag cause method cache bug
  Objects/typeobject.c
Labels: CLA signed, awaiting change review, skip news

#24801 bpo-43444: Move sqlite3 MODULE_NAME from setup.py to Modules/_sqlite/module.h
  Modules/_sqlite/cache.h
  Modules/_sqlite/module.h
  Modules/_sqlite/prepare_protocol.h
  PCbuild/_sqlite3.vcxproj
  setup.py
Labels: CLA signed, awaiting merge, skip news

#24782 bpo-43428: Sync with importlib_metadata 3.7.
  Doc/library/importlib.metadata.rst
  Lib/importlib/_itertools.py
  Lib/importlib/metadata.py
  Lib/test/test_importlib/fixtures.py
  Lib/test/test_importlib/test_main.py
  Lib/test/test_importlib/test_metadata_api.py
  Lib/test/test_importlib/test_zip.py
  Misc/NEWS.d/next/Library/2021-03-07-18-54-39.bpo-43428.br0XmX.rst
Labels: :robot: automerge, CLA signed, awaiting core review

#24787 bpo-43427: Separate the method overview from static method specifics
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news, type-documentation

#24267 [3.9] Fix typos in unittest documentation (GH-24194)
  Doc/library/unittest.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, stale, type-documentation

#24834 Fix some minor errors in the docs
  Doc/library/ast.rst
  Doc/library/asyncio-api-index.rst
  Doc/library/readline.rst
  Doc/library/statistics.rst
  Doc/library/xml.sax.handler.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24849 [3.9] bpo-43427: Separte the method overview from the static method specifics. (GH-24787)
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#24836 bpo-43439: Wrapt the tuple in the audit events for the gc module
  Modules/gcmodule.c
Labels: :robot: automerge, CLA signed, needs backport to 3.8, needs backport to 3.9, skip news

#24788 bpo-43245: Add keyword argument support to ChainMap.new_child()
  Doc/library/collections.rst
  Lib/collections/__init__.py
  Lib/test/test_collections.py
  Misc/NEWS.d/next/Library/2021-03-08-22-14-37.bpo-43245.nXL-MC.rst
Labels: CLA signed, awaiting merge

#24763 bpo-43410: Fix crash in the parser when producing syntax errors when reading from stdin
  Lib/test/test_cmd_line.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-05-17-23-36.bpo-43410.lCzIg0.rst
  Parser/pegen.c
  Parser/tokenizer.c
  Parser/tokenizer.h
Labels: CLA signed, awaiting core review

#24854 [3.8] bpo-43439: Wrapt the tuple in the audit events for the gc module (GH-24836)
  Modules/gcmodule.c
Labels: CLA signed, awaiting core review, skip news

#24855 [3.9] bpo-43439: Wrapt the tuple in the audit events for the gc module (GH-24836).
  Modules/gcmodule.c
Labels: CLA signed, awaiting core review, skip news

#24856 [3.9] bpo-39943: Fix MSVC warnings in sre extension (GH-20508)
  Modules/_sre.c
  Modules/sre_lib.h
Labels: CLA signed, awaiting merge, skip news

#24859 bpo-39316: Make sure that attribute accesses and stores, including method calls, conform to PEP 626.
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-14-16-44-50.bpo-39316.Ns3a_F.rst
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
Labels: CLA signed, awaiting core review

#24793 bpo-29982: Add "ignore_cleanup_errors" param to tempfile.TemporaryDirectory()
  Doc/library/tempfile.rst
  Lib/tempfile.py
  Lib/test/test_tempfile.py
  Misc/NEWS.d/next/Library/2021-03-07-23-23-03.bpo-29982.Q9iszT.rst
Labels: CLA signed, awaiting merge

#24852 bpo-43199: Briefly explain why no goto
  Doc/faq/design.rst
  Misc/NEWS.d/next/Documentation/2021-03-13-18-43-54.bpo-43199.ZWA6KX.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-documentation

#24858 bpo-43428: Improve documentation for importlib.metadata changes.
  Doc/library/importlib.metadata.rst
  Doc/whatsnew/3.10.rst
  Lib/importlib/metadata.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#24862 [3.9] bpo-43199: Briefly explain why no goto (GH-24852)
  Doc/faq/design.rst
  Misc/NEWS.d/next/Documentation/2021-03-13-18-43-54.bpo-43199.ZWA6KX.rst
Labels: CLA signed, awaiting merge, type-documentation

#24863 [3.8] bpo-43199: Briefly explain why no goto (GH-24852)
  Doc/faq/design.rst
  Misc/NEWS.d/next/Documentation/2021-03-13-18-43-54.bpo-43199.ZWA6KX.rst
Labels: CLA signed, awaiting merge, type-documentation

#24835 [3.9] [doc] Document logging.basicConfig default format (GH-23710) (GH-24835)
  Doc/library/logging.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24847 [3.8] [doc] Document logging.basicConfig default format (GH-23710) (GH-24847)
  Doc/library/logging.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24860 bpo-42246: Mark POP_TOP at end of expression statement as artificial, to conform to PEP 626.
  Lib/test/test_compile.py
  Python/compile.c
Labels: CLA signed, awaiting core review, skip news

#24866 Fix typo in the word "spaghetti"
  Doc/faq/design.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip issue, skip news, type-documentation

#24878 [3.9] Fix typo in the word "spaghetti" (GH-24866)
  Doc/faq/design.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24879 [3.8] Fix typo in the word "spaghetti" (GH-24866)
  Doc/faq/design.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#24838 bpo-43285 Make ftplib not trust the PASV response.
  Lib/ftplib.py
  Lib/test/test_ftplib.py
  Misc/NEWS.d/next/Security/2021-03-13-03-48-14.bpo-43285.g-Hah3.rst
Labels: CLA signed, awaiting core review, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, type-bugfix, type-security

#24880 [3.9] bpo-43285 Make ftplib not trust the PASV response. (GH-24838)
  Lib/ftplib.py
  Lib/test/test_ftplib.py
  Misc/NEWS.d/next/Security/2021-03-13-03-48-14.bpo-43285.g-Hah3.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-bugfix, type-security

#22570 bpo-41933: Clarify wording for s * n in Common Sequence Operations
  Lib/pydoc_data/topics.py
  Misc/NEWS.d/next/Documentation/2020-10-05-20-04-43.bpo-41933.Pff94-.rst
Labels: CLA signed, awaiting merge, stale

#24853 Minor updates to the vector demo
  Tools/demo/vector.py
Labels: CLA signed, awaiting core review, skip issue, skip news, type-documentation

#24796 bpo-41361: Optimized argument parsing for deque_rotate
  Misc/NEWS.d/next/Library/2021-03-13-08-18-01.bpo-41361.lXDIlr.rst
  Modules/_collectionsmodule.c
Labels: CLA signed, awaiting merge

#24885 bpo-43506: Doc: Update removal schedule for Py_UNICODE encoder APIs
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#24888 [3.9] bpo-43285: Add a What's New entry for 3.9.3.
  Doc/whatsnew/3.9.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#24889 [3.8] bpo-43285: Whats New entry for 3.8.9.
  Doc/whatsnew/3.8.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#24890 [3.9] bpo-43506: Doc: Update removal schedule for Py_UNICODE encoder APIs (GH-24885)
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24891 [3.8] bpo-43506: Doc: Update removal schedule for Py_UNICODE encoder APIs (GH-24885)
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#24873 [3.9] bpo-43499: Silence compiler warnings about using legacy C API on Windows
  Modules/_ctypes/callproc.c
  Modules/_io/fileio.c
  Modules/posixmodule.c
  Objects/unicodeobject.c
  PC/_msi.c
  PC/winreg.c
  Python/dynload_win.c
  Python/fileutils.c
Labels: CLA signed, awaiting merge, skip news

#24867 bpo-43497: Emit SyntaxWarnings for assertions with tuple constants.
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-15-07-50-30.bpo-43497.Uc5ZCJ.rst
  Python/compile.c
Labels: CLA signed, awaiting review

#24892 bpo-42246: Add PEP 626 to what's new in 3.10.
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#24894 [3.9] bpo-41654: Fix compiler warning in MemoryError_dealloc() (GH-22387)
  Objects/exceptions.c
Labels: CLA signed, awaiting merge, skip news

#24882 [3.6] bpo-43285 Make ftplib not trust the PASV response. (GH-24838) (GH-24881)
  Doc/whatsnew/3.6.rst
  Lib/ftplib.py
  Lib/test/test_ftplib.py
  Misc/NEWS.d/next/Security/2021-03-13-03-48-14.bpo-43285.g-Hah3.rst
Labels: CLA signed, awaiting review, type-bugfix, type-security
