Repository python/cpython, pull requests merged in 2021-04, with the labels that each got.

#24695 [3.9] bpo-42840: Document providing kwargs to type. (GH-24173)
  Doc/library/functions.rst
Labels: CLA signed, awaiting merge, skip news, stale, type-documentation

#24691 [3.8] Fix grammar in enum documentation. (GH-24689)
  Doc/library/enum.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, stale, type-documentation

#25122 bpo-42955: Add _overlapped to sys.stdlib_module_names
  Python/stdlib_module_names.h
  Tools/scripts/generate_stdlib_module_names.py
Labels: CLA signed, awaiting core review, skip news

#25109 bpo-43651: Fix EncodingWarning in test_file and test_file_eintr
  Lib/test/test_file.py
  Lib/test/test_file_eintr.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#25097 bpo-43651: Fix EncodingWarning in test_io
  Lib/test/test_io.py
Labels: CLA signed, awaiting merge, skip news

#25125 When printing stats, move radix tree info to its own section.
  Objects/obmalloc.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#25104 Typos in 3.10 "What's new"
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#25018 [3.8] Doc: io: Remove "In-memory streams" section (GH-24927)
  Doc/library/io.rst
Labels: awaiting merge, skip issue, skip news, type-documentation

#25017 [3.9] Doc: io: Remove "In-memory streams" section (GH-24927)
  Doc/library/io.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#25134 bpo-43688: Run make regen-limited-abi
  Doc/data/stable_abi.dat
Labels: CLA signed, awaiting core review, skip news

#25136 bpo-43690: stable_abi.py no longer parses macros
  Doc/data/stable_abi.dat
  Tools/scripts/stable_abi.py
Labels: CLA signed, awaiting core review, skip news

#25135 bpo-43688: Fix Py_LIMITED_API version of xxlimited
  Include/methodobject.h
  PCbuild/xxlimited.vcxproj
  setup.py
Labels: CLA signed, awaiting core review, skip news

#25069 bpo-27129: Use instruction offsets, not byte offsets, in bytecode and internally.
  Lib/dis.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-29-16-20-29.bpo-27129.BF03A5.rst
  Objects/codeobject.c
  Objects/frameobject.c
  Objects/genobject.c
  Python/ceval.c
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
  Python/traceback.c
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review

#22033 bpo-26053: Fix args echoed by pdb run command
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2020-09-01-10-12-13.bpo-26053.hXikw_.rst
Labels: CLA signed, awaiting merge, type-bugfix

#25123 bpo-43677: Fix a minor error in Doc/howto/descriptor.rst
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#25139 bpo-26053: Correct assertion in pdb test
  Lib/test/test_pdb.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#25126 bpo-43651: Fix EncodingWarning in test_warnings
  Lib/test/test_warnings/__init__.py
Labels: CLA signed, awaiting merge, skip news

#25127 bpo-43651: Fix EncodingWarning in lib2to3/pgen2/pgen.py
  Lib/lib2to3/pgen2/pgen.py
Labels: CLA signed, awaiting merge, skip news

#25128 bpo-43651: Fix test_compileall with PEP 597
  Lib/compileall.py
  Lib/multiprocessing/util.py
  Lib/test/test_compileall.py
Labels: CLA signed, awaiting merge, skip news

#25140 [3.9] bpo-43677: Fix a minor error in Doc/howto/descriptor.rst (GH-25123)
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#25141 bpo-43700: Replace Zulip badge with Discourse badge
  README.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#25142 bpo-43651: PEP 597: Fix EncodingWarning in some tests
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_argparse.py
  Lib/test/test_baseexception.py
  Lib/test/test_bdb.py
  Lib/test/test_bool.py
  Lib/test/test_builtin.py
  Lib/test/test_doctest.py
  Lib/test/test_exceptions.py
  Lib/test/test_opcodes.py
  Lib/test/test_support.py
  Parser/asdl.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#25143 [3.9] bpo-43700: Replace Zulip badge with Discourse badge (GH-25141)
  README.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25144 [3.8] bpo-43700: Replace Zulip badge with Discourse badge (GH-25141)
  README.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25146 bpo-43510: Fix emitting EncodingWarning from _io module.
  Modules/_io/_iomodule.c
  Modules/_io/textio.c
Labels: CLA signed, awaiting merge, skip news, type-bugfix

#25149 [3.9] bpo-26053: Fix args echoed by pdb run command
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2020-09-01-10-12-13.bpo-26053.hXikw_.rst
Labels: CLA signed, awaiting review, needs backport to 3.8

#25150 [3.8] [3.9] bpo-26053: Fix args echoed by pdb run command (GH-25149)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2020-09-01-10-12-13.bpo-26053.hXikw_.rst
Labels: CLA signed, awaiting merge

#25111 Document PyCode_Addr2Line function.
  Doc/c-api/code.rst
Labels: CLA signed, awaiting merge, skip issue, skip news, type-documentation

#25147 bpo-43687: Py_Initialize() creates singletons earlier
  Include/internal/pycore_long.h
  Include/internal/pycore_pylifecycle.h
  Objects/floatobject.c
  Objects/longobject.c
  Objects/structseq.c
  Objects/unicodeobject.c
  Python/errors.c
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#25131 bpo-43688: Support the limited C API in debug mode
  Doc/whatsnew/3.10.rst
  Include/object.h
  Misc/NEWS.d/next/C API/2021-04-01-09-10-42.bpo-43688.G4gs6k.rst
  Objects/object.c
  PC/python3dll.c
  setup.py
Labels: CLA signed, awaiting core review

#25133 bpo-43688: Support "make regen-limited-abi" in debug mode
  Tools/scripts/stable_abi.py
Labels: CLA signed, awaiting core review, skip news

#25151 bpo-41111: xxlimited.c defines Py_LIMITED_API
  Modules/xxlimited.c
  Modules/xxlimited_35.c
  PCbuild/xxlimited.vcxproj
  PCbuild/xxlimited_35.vcxproj
  setup.py
Labels: CLA signed, awaiting core review, skip news

#25059 bpo-31956: Add start and stop parameters to array.index()
  Doc/library/array.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_array.py
  Misc/NEWS.d/next/Library/2021-03-28-16-53-25.bpo-31956.Lt_67U.rst
  Modules/arraymodule.c
  Modules/clinic/arraymodule.c.h
Labels: CLA signed, awaiting merge

#21989 bpo-24160: Fix breakpoints persistence across multiple pdb sessions
  Lib/bdb.py
  Lib/test/test_bdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2020-08-28-23-07-53.bpo-24160.MSGnKr.rst
Labels: CLA signed, awaiting merge

#25119 bpo-43672: raise ImportWarning when calling find_loader()
  Doc/reference/import.rst
  Doc/whatsnew/3.10.rst
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_importlib/extension/test_loader.py
  Lib/test/test_importlib/import_/test_path.py
  Lib/test/test_importlib/test_abc.py
  Lib/test/test_importlib/test_main.py
  Lib/test/test_importlib/test_metadata_api.py
  Lib/test/test_importlib/test_path.py
  Lib/test/test_importlib/test_reader.py
  Lib/test/test_importlib/test_util.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-31-09-12-54.bpo-43672.jTT5uG.rst
  Python/importlib_external.h
Labels: CLA signed, awaiting core review

#25153 bpo-43705: Document that SyntaxError's offsets are 1-indexed
  Doc/library/exceptions.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#25156 [3.8] bpo-43705: Document that SyntaxError's offsets are 1-indexed (GH-25153)
  Doc/library/exceptions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25155 [3.9] bpo-43705: Document that SyntaxError's offsets are 1-indexed (GH-25153)
  Doc/library/exceptions.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25164 Add more tests for descriptor tutorial
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news, type-documentation, type-tests

#25162 Replace broken example code with correct simpler code.
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip issue, skip news, type-documentation

#25165 [3.9] Add more tests for the descriptor tutorial (GH-25164)
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation, type-tests

#25166 [3.9] Replace broken example code with correct simpler code. (GH-25162)
  Doc/howto/descriptor.rst
Labels: CLA signed, awaiting review, skip issue, skip news, type-documentation

#25167 bpo-43720: Update import-related stdlib deprecation messages to say they will be removed in Python 3.12
  Lib/imp.py
  Lib/importlib/util.py
  Lib/pkgutil.py
  Lib/test/test_pkgutil.py
  Misc/NEWS.d/next/Library/2021-04-03-13-45-51.bpo-43720.FDZ5cZ.rst
Labels: CLA signed, awaiting core review

#25145 bpo-43651: PEP 597: Fix EncodingWarning in some tests
  Lib/ctypes/test/test_find.py
  Lib/os.py
  Lib/test/_test_multiprocessing.py
  Lib/test/multibytecodec_support.py
  Lib/test/test_asyncio/test_base_events.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_bz2.py
  Lib/test/test_cmath.py
  Lib/test/test_cmd_line.py
  Lib/test/test_cmd_line_script.py
  Lib/test/test_compile.py
  Lib/test/test_configparser.py
  Lib/test/test_contextlib.py
  Lib/test/test_csv.py
  Lib/test/test_dbm_dumb.py
  Lib/test/test_decimal.py
  Lib/test/test_difflib.py
  Lib/test/test_math.py
  Lib/test/test_profile.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#25168 bpo-43325: Add FAQ entry for identity tests
  Doc/faq/programming.rst
  Doc/tutorial/datastructures.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#25178 [3.9] bpo-43325: Add FAQ entry for identity tests (GH-25168)
  Doc/faq/programming.rst
  Doc/tutorial/datastructures.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#25171 bpo-43651: PEP 597: Fix EncodingWarning in some tests
  Lib/_osx_support.py
  Lib/test/test_float.py
  Lib/test/test_fstring.py
  Lib/test/test_gc.py
  Lib/test/test_gzip.py
  Lib/test/test_hashlib.py
Labels: CLA signed, awaiting merge, skip news

#25172 bpo-27129: Update magic numbers and bootstrapping for GH-25069
  Lib/importlib/_bootstrap_external.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-03-22-04-46.bpo-27129.u_ehHb.rst
  Python/importlib_external.h
Labels: CLA signed, awaiting merge

#25179 [3.9] bpo-43710: Rollback the 3.9 bpo-42500 fix, it broke the ABI in 3.9.3
  Include/cpython/pystate.h
  Include/internal/pycore_ceval.h
  Lib/test/test_exceptions.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-03-21-12-15.bpo-43710._Mj01v.rst
  Python/ceval.c
  Python/errors.c
  Python/pystate.c
  Python/sysmodule.c
Labels: CLA signed, awaiting merge, type-bugfix

#25182 bpo-24160: Fix test_pdb refleaks failure
  Lib/test/test_pdb.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#25183 bpo-41370: Add note about ForwardRefs and PEP585 generic types in docs
  Doc/library/typing.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#25184 [3.9] bpo-41370: Add note about ForwardRefs and PEP585 generic types in docs (GH-25183)
  Doc/library/typing.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#25158 bpo-43651: PEP 597: Fix EncodingWarning in test_email
  Lib/test/test_email/__init__.py
  Lib/test/test_email/test_email.py
Labels: CLA signed, awaiting core review, skip news

#25159 bpo-43651: PEP 597: Fix EncodingWarning in test_filecmp
  Lib/test/test_filecmp.py
Labels: awaiting core review, skip news, type-tests

#25181 bpo-43651: PEP 597: Fix EncodingWarning in some tests
  Lib/test/test_imp.py
  Lib/test/test_import/__init__.py
  Lib/test/test_importlib/fixtures.py
  Lib/test/test_importlib/source/test_file_loader.py
  Lib/test/test_importlib/source/test_finder.py
  Lib/test/test_importlib/test_api.py
  Lib/test/test_importlib/test_files.py
  Lib/test/test_importlib/test_main.py
  Lib/test/test_importlib/test_pkg_import.py
  Lib/test/test_importlib/util.py
  Lib/test/test_shutil.py
Labels: CLA signed, awaiting core review, skip news

#24398 bpo-43084: Return bool instead of int from curses.window.enclose()
  Doc/library/curses.rst
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2021-01-31-17-31-13.bpo-43084.i8nLpK.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: CLA signed, awaiting core review, stale, type-bugfix

#25193 Fix the "make suspicious" check on the pprint docs
  Doc/library/pprint.rst
Labels: CLA signed, skip issue, skip news

#25194 Fix typo in turtledemo.two_canvases.
  Lib/turtledemo/two_canvases.py
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#25196 [3.8] Fix typo in turtledemo.two_canvases. (GH-25194)
  Lib/turtledemo/two_canvases.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#25195 [3.9] Fix typo in turtledemo.two_canvases. (GH-25194)
  Lib/turtledemo/two_canvases.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#24404 bpo-43087: Fix error in ctypes "Incomplete Types" doc
  Doc/library/ctypes.rst
Labels: CLA signed, awaiting review, needs backport to 3.8, needs backport to 3.9, skip news, stale, type-documentation

#20867 bpo-36470: Allow dataclasses.replace() to handle InitVars with default values
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2020-06-13-23-33-32.bpo-36470.oi6Kdb.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#25175 bpo-20503: Show how isinstance() works with ABC registered classes.
  Doc/faq/programming.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, skip news, type-documentation

#25201 [3.8] bpo-36470: Allow dataclasses.replace() to handle InitVars with default values (GH-20867)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2020-06-13-23-33-32.bpo-36470.oi6Kdb.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#25200 [3.9] bpo-36470: Allow dataclasses.replace() to handle InitVars with default values (GH-20867)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2020-06-13-23-33-32.bpo-36470.oi6Kdb.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#25202 [3.9] bpo-20503: Show how isinstance() works with ABC registered classes. (GH-25175)
  Doc/faq/programming.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#25192 bpo-43651: Fix EncodingWarning in sysconfig
  Lib/sysconfig.py
Labels: CLA signed, awaiting core review, skip news

#25203 bpo-42128: __match_args__ can't be a list anymore
  Lib/test/test_dataclasses.py
  Lib/test/test_patma.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-05-17-38-08.bpo-42128.1uVeGK.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge

#25189 bpo-43651: PEP 597: Fix EncodingWarning in some tests
  Lib/_sitebuiltins.py
  Lib/logging/__init__.py
  Lib/logging/handlers.py
  Lib/test/test_inspect.py
  Lib/test/test_interpreters.py
  Lib/test/test_io.py
  Lib/test/test_iter.py
  Lib/test/test_json/test_tool.py
  Lib/test/test_linecache.py
  Lib/test/test_lltrace.py
  Lib/test/test_logging.py
Labels: CLA signed, awaiting core review, skip news

#25190 bpo-43651: PEP 597: Fix EncodingWarning in some tests
  Lib/test/test_lzma.py
  Lib/test/test_mailbox.py
  Lib/test/test_mimetypes.py
  Lib/test/test_posix.py
Labels: CLA signed, skip news

#24484 bpo-43176: Fix processing of empty dataclasses
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2021-02-09-07-24-29.bpo-43176.bocNQn.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, stale

#25206 [3.8] bpo-43176: Fix processing of empty dataclasses (GH-24484)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2021-02-09-07-24-29.bpo-43176.bocNQn.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#25208 bpo-17305: Link to the third-party idna package.
  Doc/library/codecs.rst
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, type-documentation

#25204 bpo-43651: PEP 597: Fix pdeps used locale encoding.
  Tools/scripts/pdeps.py
Labels: skip news

#25210 [3.9] bpo-17305: Link to the third-party idna package. (GH-25208)
  Doc/library/codecs.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#25138 bpo-43683: Handle generator entry in bytecode
  Doc/library/dis.rst
  Include/opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-01-12-30-30.bpo-43683.AjxOx2.rst
  Objects/genobject.c
  Python/ceval.c
  Python/compile.c
  Python/importlib_external.h
  Python/opcode_targets.h
Labels: CLA signed, awaiting core review

#25213 bpo-43745: Actually updates Windows release to OpenSSL 1.1.1k.
  Misc/NEWS.d/next/Windows/2021-04-06-12-27-33.bpo-43745.rdKNda.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-security

#25180 bpo-41111: Build limited C API without Py_TRACE_REFS macro.
  setup.py
Labels: CLA signed, awaiting review, skip news

#25205 [3.9] bpo-43176: Fix processing of empty dataclasses (GH-24484)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2021-02-09-07-24-29.bpo-43176.bocNQn.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#25215 bpo-43176: Fix blurb
  Misc/NEWS.d/next/Library/2021-02-09-07-24-29.bpo-43176.bocNQn.rst
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#25218 [3.8] Fix blurb for bpo-43176. (GH-25215)
  Misc/NEWS.d/next/Library/2021-02-09-07-24-29.bpo-43176.bocNQn.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip issue, skip news

#25214 [3.9] bpo-43745: Actually updates Windows release to OpenSSL 1.1.1k. (GH-25213)
  Misc/NEWS.d/next/Windows/2021-04-06-12-27-33.bpo-43745.rdKNda.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, needs backport to 3.8, type-security

#25217 [3.9] Fix blurb for bpo-43176. (GH-25215)
  Misc/NEWS.d/next/Library/2021-02-09-07-24-29.bpo-43176.bocNQn.rst
Labels: :robot: automerge, awaiting merge, skip issue, skip news

#25223 [3.8] bpo-43745: Actually updates Windows release to OpenSSL 1.1.1k. (GH-25213)
  Misc/NEWS.d/next/Windows/2021-04-06-12-27-33.bpo-43745.rdKNda.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, awaiting merge, type-security

#25219 bpo-41870: Update What's News 3.10 about vectorcall
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#25169 bpo-42135: Deprecate implementations of find_module() and find_loader()
  Doc/library/importlib.rst
  Doc/whatsnew/3.10.rst
  Lib/importlib/__init__.py
  Lib/importlib/_bootstrap.py
  Lib/importlib/_bootstrap_external.py
  Lib/importlib/abc.py
  Lib/test/test_importlib/builtin/test_finder.py
  Lib/test/test_importlib/extension/test_case_sensitivity.py
  Lib/test/test_importlib/extension/test_finder.py
  Lib/test/test_importlib/frozen/test_finder.py
  Lib/test/test_importlib/frozen/test_loader.py
  Lib/test/test_importlib/import_/test_path.py
  Lib/test/test_importlib/source/test_case_sensitivity.py
  Lib/test/test_importlib/test_abc.py
  Lib/test/test_importlib/test_api.py
  Lib/zipimport.py
  Misc/NEWS.d/next/Library/2021-04-03-15-24-59.bpo-2135.xmDAYJ.rst
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
Labels: CLA signed, awaiting core review

#25185 bpo-42128: Update pattern matching docs to match new PEP changes
  Doc/reference/compound_stmts.rst
  Doc/reference/datamodel.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25225 bpo-43683: bump the bytecode magic number
  Lib/importlib/_bootstrap_external.py
  Python/importlib_external.h
Labels: CLA signed, awaiting review, skip news

#25231 bpo-43755: Update docs to reflect that lambda is not allowed in `comp_if` since 3.9
  Doc/reference/expressions.rst
  Doc/whatsnew/3.9.rst
  Misc/NEWS.d/next/Documentation/2021-04-06-14-55-45.bpo-43755.1m0fGq.rst
Labels: CLA signed, awaiting merge, type-documentation

#25120 bpo-43567: Improved generated code refresh on Windows
  Misc/NEWS.d/next/Build/2021-03-31-19-50-01.bpo-43567.vd0a-p.rst
  PCbuild/_freeze_importlib.vcxproj
  PCbuild/build.bat
  PCbuild/pythoncore.vcxproj
  PCbuild/regen.targets
  PCbuild/regen.vcxproj
Labels: CLA signed, OS-windows, awaiting merge

#19220 bpo-39924: handle missing os functions more consistently in pathlib
  Lib/pathlib.py
Labels: CLA signed, awaiting merge, skip news

#25121 bpo-43105: Importlib now resolves relative paths when creating module spec objects from file locations
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_import/__init__.py
  Lib/test/test_importlib/test_spec.py
  Lib/test/test_importlib/test_windows.py
  Lib/test/test_site.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-31-20-35-11.bpo-43105.PBVmHm.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
  Python/importlib_external.h
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9

#18838 bpo-39895: Move `pathlib.Path.touch()` implementation into the path accessor
  Lib/pathlib.py
Labels: CLA signed, awaiting merge, skip news

#19342 bpo-40038: pathlib: remove partial support for preserving accessor when modifying a path
  Lib/pathlib.py
Labels: CLA signed, awaiting review, skip news

#25236 bpo-38605: Update "Future statements" docs since PEP 563 is always enabled
  Doc/reference/simple_stmts.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#25224 bpo-43683: Minor corrections.
  Lib/importlib/_bootstrap_external.py
  Python/compile.c
Labels: CLA signed, awaiting merge, skip news

#25243 bpo-43244: Remove Yield macro from pycore_ast.h
  Include/internal/pycore_ast.h
  Parser/asdl_c.py
  Python/Python-ast.c
  Python/ast_opt.c
  Python/bltinmodule.c
  Python/import.c
  Python/pythonrun.c
  Python/symtable.c
Labels: CLA signed, awaiting core review, skip news

#24391 bpo-43075: Fix ReDoS in request
  Lib/urllib/request.py
  Misc/NEWS.d/next/Security/2021-01-31-05-28-14.bpo-43075.DoAXqO.rst
Labels: CLA signed, awaiting review, stale

#25237 [3.9] bpo-43105: Importlib now resolves relative paths when creating module spec objects from file locations (GH-25121)
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_import/__init__.py
  Lib/test/test_importlib/test_spec.py
  Lib/test/test_importlib/test_windows.py
  Lib/test/test_site.py
  Misc/NEWS.d/next/Core and Builtins/2021-03-31-20-35-11.bpo-43105.PBVmHm.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
  Python/importlib_external.h
Labels: CLA signed, awaiting core review, needs backport to 3.8

#25248 [3.8] bpo-43075: Fix ReDoS in urllib AbstractBasicAuthHandler (GH-24391)
  Lib/urllib/request.py
  Misc/NEWS.d/next/Security/2021-01-31-05-28-14.bpo-43075.DoAXqO.rst
Labels: CLA signed, awaiting merge

#25251 Improve CDN purge script
  Tools/msi/purge.py
Labels: CLA signed, OS-windows, awaiting core review, needs backport to 3.8, needs backport to 3.9, skip issue, skip news

#25253 [3.8] Improve CDN purge script (GH-25251)
  Tools/msi/purge.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#24865 bpo-43495 : Push missing frame block in compile.c
  Python/compile.c
Labels: CLA signed, awaiting review, skip news

#18864 bpo-39906: add follow_symlinks parameter to pathlib.Path.stat() and chmod()
  Doc/library/pathlib.rst
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2020-03-30-00-13-27.bpo-39906.eaR3fN.rst
Labels: CLA signed, awaiting change review

#24294 bpo-42999: expand and clarify `pathlib.Path.link_to()` documentation.
  Doc/library/pathlib.rst
  Lib/pathlib.py
Labels: CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9, skip news, stale

#25247 [3.9] bpo-43075: Fix ReDoS in urllib AbstractBasicAuthHandler (GH-24391)
  Lib/urllib/request.py
  Misc/NEWS.d/next/Security/2021-01-31-05-28-14.bpo-43075.DoAXqO.rst
Labels: CLA signed, awaiting merge

#18834 bpo-39659: Route calls from pathlib.Path to os.getcwd() via the path accessor
  Lib/pathlib.py
Labels: CLA signed, awaiting review, skip news

#25257 [3.9] bpo-42999: Expand and clarify pathlib.Path.link_to() documentation. (GH-24294)
  Doc/library/pathlib.rst
  Lib/pathlib.py
Labels: CLA signed, needs backport to 3.8, skip news

#25233 [3.9] bpo-43755: Update docs to reflect that lambda is not allowed in `comp_if` since 3.9 (GH-25231)
  Doc/reference/expressions.rst
  Doc/whatsnew/3.9.rst
  Misc/NEWS.d/next/Documentation/2021-04-06-14-55-45.bpo-43755.1m0fGq.rst
Labels: CLA signed, awaiting merge, type-documentation

#25258 [3.8] bpo-42999: Expand and clarify pathlib.Path.link_to() documentation. (GH-24294)
  Doc/library/pathlib.rst
  Lib/pathlib.py
Labels: CLA signed, awaiting core review, skip news

#25235 bpo-36540: Improve doc of function definition regarding positional-only arguments
  Doc/reference/compound_stmts.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news, type-documentation

#25260 [3.8] bpo-36540: Improve doc of function definition regarding positional-only arguments (GH-25235)
  Doc/reference/compound_stmts.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25259 [3.9] bpo-36540: Improve doc of function definition regarding positional-only arguments (GH-25235)
  Doc/reference/compound_stmts.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25252 bpo-43244: Rename pycore_ast.h functions to _PyAST_xxx()
  Grammar/python.gram
  Include/internal/pycore_ast.h
  Lib/test/test_peg_generator/test_c_parser.py
  Parser/asdl_c.py
  Parser/parser.c
  Parser/pegen.c
  Parser/string_parser.c
  Python/Python-ast.c
  Python/ast_opt.c
Labels: CLA signed, awaiting merge, skip news

#25262 bpo-42923: Fix _Py_DumpExtensionModules() for NULL sysdict
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news

#25263 bpo-43770: Sort types in _PyTypes_Init()
  Objects/object.c
Labels: awaiting core review, skip news

#25265 bpo-43770: _PyTypes_Init() inits more static types
  Objects/object.c
Labels: CLA signed, awaiting core review, skip news

#18841 bpo-39899: Make pathlib use `os.path.expanduser()` to expand home directories
  Doc/library/os.path.rst
  Doc/library/pathlib.rst
  Lib/ntpath.py
  Lib/pathlib.py
  Lib/test/test_ntpath.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2020-03-09-20-36-07.bpo-39899.9adF3E.rst
Labels: CLA signed, awaiting review

#25209 Fix assertion of pop() result in test_issue_4920
  Lib/test/test_collections.py
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip issue, skip news, type-tests

#25269 [3.9] Fix broken test for MutableSet.pop() (GH-25209)
  Lib/test/test_collections.py
Labels: CLA signed, awaiting review, skip issue, skip news, type-tests

#25270 [3.8] Fix broken test for MutableSet.pop() (GH-25209)
  Lib/test/test_collections.py
Labels: CLA signed, awaiting review, skip issue, skip news, type-tests

#25266 bpo-43770: _PyTypes_Init() inits _PyAnextAwaitable_Type
  Include/iterobject.h
  Objects/iterobject.c
  Objects/object.c
Labels: CLA signed, awaiting core review, skip news

#25198 [3.9] bpo-43087: Fix error in ctypes "Incomplete Types" doc (GH-24404)
  Doc/library/ctypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25199 [3.8] bpo-43087: Fix error in ctypes "Incomplete Types" doc (GH-24404)
  Doc/library/ctypes.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#25244 bpo-43760: Streamline dispatch sequence for machines without computed gotos.
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#25284 bpo-43764: Fix `__match_args__` generation logic for dataclasses
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2021-04-08-09-59-20.bpo-43764.tHjO60.rst
Labels: CLA signed, awaiting merge, type-bugfix

#25286 bpo-43778: Fix Sphinx glossary_search extension
  Doc/tools/extensions/glossary_search.py
  Misc/NEWS.d/next/Documentation/2021-04-08-22-42-02.bpo-43778.MszRnY.rst
Labels: CLA signed, awaiting merge

#25234 bpo-39702: Remove dotted_name from decorator documentation
  Doc/reference/compound_stmts.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#25290 [3.9] bpo-39702: Remove dotted_name from decorator documentation (GH-25234)
  Doc/reference/compound_stmts.rst
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#25289 bpo-43779: _PyArena_AddPyObject only steals a ref on success
  Parser/pegen.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, skip news

#25281 [3.8] bpo-39674: Fix collections ABC deprecation notice
  Lib/collections/__init__.py
Labels: CLA signed, awaiting review, skip news

#25292 Break down some complex functions in pegen.c for readability
  Parser/pegen.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#25293 bpo-43774: Enhance configure documentation
  Doc/using/configure.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#25291 Sanitise macros and debug functions in pegen.c
  Parser/pegen.c
  Parser/pegen.h
  Tools/peg_generator/peg_extension/peg_extension.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#25295 Simplify _PyPegen_fill_token in pegen.c
  Parser/pegen.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#25232 [3.8] bpo-43725: Add CI step to check changes in the exported ABI
  .github/workflows/build.yml
  Doc/data/python3.8.abi
  Makefile.pre.in
Labels: CLA signed, awaiting merge, skip news

#25230 [3.9] bpo-43725: Add CI step to check changes in the exported ABI
  .github/workflows/build.yml
  Doc/data/python3.9.abi
  Makefile.pre.in
Labels: CLA signed, awaiting merge, skip news

#25296 bpo-43774: Doc job of Azure Pipelines uses Doc/requirements.txt
  .azure-pipelines/docs-steps.yml
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#25302 bpo-43774: Document the Python Build System
  Doc/using/configure.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#25303 bpo-43789: OpenSSL 3.0.0 Don't call passwd callback again in error case (GH-25303)
  Misc/NEWS.d/next/Library/2021-04-09-14-08-03.bpo-43789.eaHlAm.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9

#25304 bpo-4379: Skip TLS 1.0/1.1 tests under OpenSSL 3.0.0 (GH-25304)
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2021-04-09-15-10-38.bpo-43791.4KxiXK.rst
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9, type-tests

#25305 [3.9] bpo-43789: OpenSSL 3.0.0 Don't call passwd callback again in error case (GH-25303)
  Misc/NEWS.d/next/Library/2021-04-09-14-08-03.bpo-43789.eaHlAm.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#25308 [3.8] bpo-43791: Skip TLS 1.0/1.1 tests under OpenSSL 3.0.0 (GH-25304)
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2021-04-09-15-10-38.bpo-43791.4KxiXK.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-tests

#25307 [3.9] bpo-43791: Skip TLS 1.0/1.1 tests under OpenSSL 3.0.0 (GH-25304)
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2021-04-09-15-10-38.bpo-43791.4KxiXK.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-tests

#25306 [3.8] bpo-43789: OpenSSL 3.0.0 Don't call passwd callback again in error case (GH-25303) (GH-25306)
  Misc/NEWS.d/next/Library/2021-04-09-14-08-03.bpo-43789.eaHlAm.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#25300 bpo-43788: Generate version specific _ssl_data.h
  Misc/NEWS.d/next/Library/2021-04-09-12-08-01.bpo-43788.YsvInM.rst
  Modules/_ssl.c
  Modules/_ssl_data_111.h
  Modules/_ssl_data_300.h
  Tools/ssl/make_ssl_data.py
  Tools/ssl/multissltests.py
  setup.py
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.8, needs backport to 3.9

#25268 bpo-43682: @staticmethod inherits attributes
  Doc/library/functions.rst
  Doc/whatsnew/3.10.rst
  Lib/test/test_decorators.py
  Lib/test/test_descr.py
  Lib/test/test_pydoc.py
  Lib/test/test_reprlib.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-08-01-06-22.bpo-43682.eUn4p5.rst
  Objects/funcobject.c
Labels: CLA signed, awaiting core review

#25309 bpo-43794: OpenSSL 3.0.0: set OP_IGNORE_UNEXPECTED_EOF by default (GH-25309)
  Doc/library/ssl.rst
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2021-04-09-16-14-22.bpo-43794.-1XPDH.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting core review, needs backport to 3.8, needs backport to 3.9

#25314 [3.8] bpo-43794: OpenSSL 3.0.0: set OP_IGNORE_UNEXPECTED_EOF by default (GH-25309)
  Doc/library/ssl.rst
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2021-04-09-16-14-22.bpo-43794.-1XPDH.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge

#25313 [3.9] bpo-43794: OpenSSL 3.0.0: set OP_IGNORE_UNEXPECTED_EOF by default (GH-25309)
  Doc/library/ssl.rst
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2021-04-09-16-14-22.bpo-43794.-1XPDH.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge
