Repository python/cpython, pull requests merged in 2021-06, with the labels that each got.

#26475 bpo-42972: Track sqlite3 statement objects
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/statement.c
  Modules/_sqlite/statement.h
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news

#26477 bpo-44273: Improve syntax error message for assigning to "..."
  Lib/test/test_syntax.py
  Parser/pegen.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news

#26428 bpo-44279: [doc] reword contextlib.suppress documentation
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#26457 Fix typo in block comment in Include/internal/pycore_condvar.h
  Include/internal/pycore_condvar.h
Labels: CLA signed, awaiting merge, skip issue, skip news

#26463 bpo-44263: Py_TPFLAGS_HAVE_GC requires tp_traverse
  Doc/whatsnew/3.11.rst
  Misc/NEWS.d/next/C API/2021-05-31-11-31-13.bpo-44263.8mIOfV.rst
  Objects/typeobject.c
Labels: CLA signed, awaiting merge

#26480 [3.10] bpo-44279: [doc] reword contextlib.suppress documentation (GH-…
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#26481 [3.9] bpo-44279: [doc] reword contextlib.suppress documentation (GH-2…
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting core review, skip news, type-documentation

#26206 bpo-44165: optimise sqlite3 statement preparation by passing string size
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting merge, skip news

#26326 Remove duplicate address in CommonTestMixin_v4.test_leading_zeros().
  Lib/test/test_ipaddress.py
Labels: :robot: automerge, CLA signed, awaiting core review, skip issue, skip news, type-tests

#24976 bpo-17792: more accurate error message for UnboundLocalError
  Misc/NEWS.d/next/Core and Builtins/2021-03-22-17-50-30.bpo-17792._zssjS.rst
  Python/ceval.c
Labels: CLA signed, awaiting merge

#26484 bpo-44165: pysqlite_statement_create() returns a PyObject *, not an int
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting merge, skip news

#26486 bpo-44285: Assert that the env_file variable in getpath.c is NULL during an error check
  Modules/getpath.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news

#26489 bpo-43921: Fix test_ssl.test_pha_required_nocert()
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2021-06-02-17-41-42.bpo-43921.xP7yZ4.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, type-tests

#26494 [3.10] bpo-43921: Fix test_ssl.test_pha_required_nocert() (GH-26489)
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2021-06-02-17-41-42.bpo-43921.xP7yZ4.rst
Labels: CLA signed, awaiting merge, type-tests

#26495 [3.10] bpo-44285: getpath.c: Assert that env_file is NULL during an error check (GH-26486)
  Modules/getpath.c
Labels: CLA signed, awaiting merge, skip news

#26496 [3.9] bpo-44285: getpath.c: Assert that env_file is NULL during an error check (GH-26486)
  Modules/getpath.c
Labels: CLA signed, awaiting merge, skip news

#26491 bpo-44282: fix occasional test_incremental_editing failures on buildbots
  Lib/idlelib/idle_test/test_colorizer.py
  Lib/idlelib/idle_test/test_sidebar.py
  Lib/idlelib/idle_test/tkinter_testing_utils.py
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news, type-tests

#26499 [3.10] bpo-44282: Fix occasional test_incremental_editing failures on buildbots (GH-26491)
  Lib/idlelib/idle_test/test_colorizer.py
  Lib/idlelib/idle_test/test_sidebar.py
  Lib/idlelib/idle_test/tkinter_testing_utils.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#26001 [3.9] bpo-43568: Relax distutils MACOSX_DEPLOYMENT_TARGET check (GH-25827)
  Lib/distutils/spawn.py
  Misc/NEWS.d/next/macOS/2021-06-02-19-21-13.bpo-43568.viomLm.rst
Labels: CLA signed, awaiting merge

#26503 bpo-44022: Improve the security fix regression test.
  Lib/test/test_httplib.py
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.6, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, skip news, type-security, type-tests

#25124 Add bpo-42914 to What's New
  Doc/whatsnew/3.10.rst
  Misc/ACKS
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.10, skip news, stale, type-documentation

#26504 [3.10] bpo-44022: Improve the regression test. (GH-26503)
  Lib/test/test_httplib.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-security, type-tests

#26509 [3.10] Add bpo-42914 to What's New (GH-25124)
  Doc/whatsnew/3.10.rst
  Misc/ACKS
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-documentation

#26505 [3.9] bpo-44022: Improve the regression test. (GH-26503)
  Lib/test/test_httplib.py
Labels: :robot: automerge, CLA signed, awaiting merge, skip news, type-security, type-tests

#26510 [3.9] bpo-43776: Remove list call from args in Popen repr (GH-25338)
  Lib/subprocess.py
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Library/2021-04-12-00-00-00.bpo-43776.p14y7a.rst
Labels: CLA signed, awaiting core review, type-bugfix

#26507 [3.7] bpo-44022: Improve the regression test. (GH-26503)
  Lib/test/test_httplib.py
Labels: CLA signed, awaiting merge, skip news, type-security, type-tests

#26508 [3.6] bpo-44022: Improve the regression test. (GH-26503)
  Lib/test/test_httplib.py
Labels: CLA signed, awaiting merge, skip news, type-security, type-tests

#26459 bpo-43858: Add logging.getLevelNamesMapping()
  Doc/library/logging.rst
  Lib/logging/__init__.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2021-05-31-04-51-02.bpo-43858.r7LOu6.rst
Labels: :robot: automerge, CLA signed, awaiting merge

#23848 bpo-39560: Document PyUnicode_FromKindAndData() kind transformation
  Doc/c-api/unicode.rst
Labels: CLA signed, awaiting merge, skip news, stale, type-documentation

#26513 bpo-44298: Fix line numbers for early exits in with statements.
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
Labels: CLA signed, awaiting core review, skip news

#26512 bpo-42213: Check connection in sqlite3.Connection.__enter__
  Lib/sqlite3/test/dbapi.py
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting review, skip news

#26502 bpo-43921: Fix test_ssl.test_wrong_cert_tls13() on Windows
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2021-06-03-03-29-34.bpo-43921.nwH1FS.rst
Labels: CLA signed, needs backport to 3.10

#26388 bpo-43693: Add new internal code objects fields: co_fastlocalnames and co_fastlocalkinds.
  Doc/library/dis.rst
  Include/cpython/code.h
  Include/internal/pycore_code.h
  Lib/ctypes/test/test_values.py
  Lib/dis.py
  Lib/importlib/_bootstrap_external.py
  Misc/NEWS.d/next/Core and Builtins/2021-05-21-20-53-49.bpo-43693.-NN3J_.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Objects/frameobject.c
  Objects/typeobject.c
  Programs/test_frozenmain.h
  Python/ceval.c
  Python/compile.c
  Python/frozen_hello.h
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
  Python/marshal.c
  Python/suggestions.c
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review

#26515 [3.10] bpo-42972: Track sqlite3 statement objects (GH-26475)
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/statement.c
  Modules/_sqlite/statement.h
Labels: CLA signed, awaiting merge, skip news

#26517 bpo-42213: Remove redundant cyclic GC hack in sqlite3
  Lib/sqlite3/test/dbapi.py
  Lib/sqlite3/test/hooks.py
  Modules/_sqlite/cache.c
  Modules/_sqlite/cache.h
  Modules/_sqlite/connection.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#26493 bpo-39573: Py_TYPE becomes a static inline function
  Doc/c-api/structures.rst
  Doc/whatsnew/3.11.rst
  Include/object.h
  Misc/NEWS.d/next/C API/2021-06-03-00-59-48.bpo-39573.-elHTJ.rst
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting core review

#26516 [3.10] bpo-44298: Backport #26513 to 3.10
  Lib/test/test_sys_settrace.py
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
Labels: CLA signed, awaiting merge, skip news

#24203 bpo-42862: Use functools.lru_cache iso. _sqlite.Cache in sqlite3 module
  Doc/library/sqlite3.rst
  Misc/NEWS.d/next/Library/2021-01-13-00-02-44.bpo-42862.Z6ACLN.rst
  Modules/_sqlite/cache.c
  Modules/_sqlite/cache.h
  Modules/_sqlite/connection.c
  Modules/_sqlite/connection.h
  Modules/_sqlite/cursor.c
  Modules/_sqlite/module.c
  Modules/_sqlite/module.h
  PCbuild/_sqlite3.vcxproj
  PCbuild/_sqlite3.vcxproj.filters
  setup.py
Labels: CLA signed, awaiting merge

#20594 bpo-11105: Do not crash when compiling recursive ASTs
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Core and Builtins/2020-06-02-13-21-14.bpo-11105.wceryW.rst
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9

#26520 bpo-43921: Cleanup test_ssl.test_wrong_cert_tls13()
  Lib/test/test_ssl.py
Labels: CLA signed, awaiting core review, skip news, type-tests

#26518 [3.10] bpo-43921: Fix test_ssl.test_wrong_cert_tls13() on Windows (GH-26502)
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2021-06-03-03-29-34.bpo-43921.nwH1FS.rst
Labels: CLA signed, awaiting merge, type-tests

#26521 [3.10] bpo-11105: Do not crash when compiling recursive ASTs (GH-20594)
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Core and Builtins/2020-06-02-13-21-14.bpo-11105.wceryW.rst
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: CLA signed, awaiting merge

#26478 [3.10] bpo-44273: Improve syntax error message for assigning to "..." (GH-26477)
  Lib/test/test_syntax.py
  Parser/pegen.c
Labels: CLA signed, awaiting merge, skip news

#26522 [3.9] bpo-11105: Do not crash when compiling recursive ASTs (GH-20594)
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Core and Builtins/2020-06-02-13-21-14.bpo-11105.wceryW.rst
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: :robot: automerge, CLA signed, awaiting core review

#25908 bpo-44042: sqlite3 begin transaction optimisations
  Modules/_sqlite/connection.c
  Modules/_sqlite/connection.h
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting merge, skip news

#26523 bpo-44305: Improve syntax error for try blocks without except or finally
  Doc/whatsnew/3.10.rst
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-03-22-51-50.bpo-44305.66dVDG.rst
  Parser/parser.c
Labels: CLA signed, awaiting core review, needs backport to 3.10

#26524 [3.10] bpo-44305: Improve syntax error for try blocks without except …
  Doc/whatsnew/3.10.rst
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-03-22-51-50.bpo-44305.66dVDG.rst
  Parser/parser.c
Labels: CLA signed, awaiting core review

#4802 bpo-32280: Store `_PyRuntime` in a named section
  Python/pylifecycle.c
Labels: CLA signed, awaiting core review, skip news, type-enhancement

#25152 bpo-43693: Compute deref offsets in compiler
  Doc/library/dis.rst
  Lib/dis.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-02-15-02-16.bpo-43693.l3Ureu.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Python/ceval.c
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
Labels: CLA signed, awaiting core review

#26529 Removing myself from ssl code ownership (GH-26529)
  .github/CODEOWNERS
Labels: CLA signed, awaiting core review, skip issue, skip news

#26470 bpo-44048: Fix two hashlib test cases under FIPS mode
  Lib/test/test_hashlib.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#26530 bpo-43693: Revert commits 2c1e2583fdc4db6b43d163239ea42b0e8394171f and b2bf2bc1ece673d387341e06c8d3c2bc6e259747
  Doc/library/dis.rst
  Include/cpython/code.h
  Include/internal/pycore_code.h
  Lib/ctypes/test/test_values.py
  Lib/dis.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-02-15-02-16.bpo-43693.l3Ureu.rst
  Misc/NEWS.d/next/Core and Builtins/2021-05-21-20-53-49.bpo-43693.-NN3J_.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Objects/frameobject.c
  Objects/typeobject.c
  Programs/test_frozenmain.h
  Python/ceval.c
  Python/compile.c
  Python/frozen_hello.h
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
  Python/marshal.c
  Python/suggestions.c
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review

#25907 bpo-44041: Add test for sqlite3 column count
  Lib/sqlite3/test/dbapi.py
Labels: CLA signed, awaiting merge, skip news

#25422 bpo-43853: Handle sqlite3_value_text() errors
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-04-15-12-02-17.bpo-43853.XXCVAp.rst
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge

#26531 [3.10] bpo-44048: Fix two hashlib test cases under FIPS mode (GH-26470)
  Lib/test/test_hashlib.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#26534 [3.10] bpo-43853: Handle sqlite3_value_text() errors (GH-25422)
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Library/2021-04-15-12-02-17.bpo-43853.XXCVAp.rst
  Modules/_sqlite/connection.c
Labels: CLA signed, awaiting merge

#26535 bpo-44315: Remove unused connection argument from pysqlite_step()
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
  Modules/_sqlite/util.c
  Modules/_sqlite/util.h
Labels: CLA signed, awaiting review, skip news

#26192 Align comment for better readability.
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#26539 [3.9] bpo-44279: revert 'exceptions are raised' back to 'exceptions occur' (GH-26492)
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#26538 [3.10] bpo-44279: revert 'exceptions are raised' back to 'exceptions occur' (GH-26492)
  Doc/library/contextlib.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#26540 Update nonstandard variable names
  Lib/statistics.py
Labels: CLA signed, awaiting core review, needs backport to 3.10, skip issue, skip news

#26542 bpo-38323: Skip SubprocessMultiLoopWatcherTest as they can hang the test suite
  Lib/test/test_asyncio/test_subprocess.py
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news, type-tests

#26543 [3.9] bpo-38323: Skip SubprocessMultiLoopWatcherTest as they can hang the test suite (GH-26542)
  Lib/test/test_asyncio/test_subprocess.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#26544 [3.10] bpo-38323: Skip SubprocessMultiLoopWatcherTest as they can hang the test suite (GH-26542)
  Lib/test/test_asyncio/test_subprocess.py
Labels: CLA signed, awaiting merge, skip news, type-tests

#26151 [3.10] Improve speed and accuracy for correlation() (GH-26135)
  Lib/statistics.py
Labels: CLA signed, awaiting review, skip issue, skip news, type-performance

#26546 [3.10] Update nonstandard variable names (GH-26540)
  Lib/statistics.py
Labels: CLA signed, awaiting review, skip issue, skip news

#26545 bpo-44304: Fix crash in the sqlite3 module when the GC clears Statement objects
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-05-02-34-57.bpo-44304._MAoPc.rst
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting core review, needs backport to 3.10

#26547 [3.10] bpo-44304: Fix crash in the sqlite3 module when the GC clears Statement objects (GH-26545)
  Lib/sqlite3/test/userfunctions.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-05-02-34-57.bpo-44304._MAoPc.rst
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting merge

#26551 bpo-44304: Ensure the sqlite3 destructor callback is always called with the GIL held
  Modules/_sqlite/connection.c
  Modules/_sqlite/statement.c
Labels: :robot: automerge, CLA signed, awaiting core review, needs backport to 3.10, skip news

#26552 [3.10] bpo-44304: Ensure the sqlite3 destructor callback is always called with the GIL held (GH-26551)
  Modules/_sqlite/connection.c
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting merge, skip news

#26556 bpo-44320: Fix markup for W3C C14N test suite
  Doc/license.rst
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9, skip news, type-documentation

#26557 [3.10] bpo-44320: Fix markup for W3C C14N test suite (GH-26556)
  Doc/license.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#26558 [3.9] bpo-44320: Fix markup for W3C C14N test suite (GH-26556)
  Doc/license.rst
Labels: CLA signed, awaiting merge, skip news, type-documentation

#26548 bpo-44227: Update bisect docstrings
  Modules/_bisectmodule.c
  Modules/clinic/_bisectmodule.c.h
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip news, type-documentation

#26563 [3.10] bpo-44227: Update bisect docstrings (GH-26548)
  Modules/_bisectmodule.c
  Modules/clinic/_bisectmodule.c.h
Labels: CLA signed, awaiting review, skip news, type-documentation

#26565 bpo-44327: Remove unused members from pysqlite_Connection
  Modules/_sqlite/connection.c
  Modules/_sqlite/connection.h
Labels: CLA signed, awaiting merge, skip news

#26564 bpo-44326: Remove unused members from pysqlite_Statement
  Modules/_sqlite/statement.c
  Modules/_sqlite/statement.h
Labels: CLA signed, awaiting merge, skip news

#26562 bpo-44322: Document more SyntaxError details.
  Doc/library/exceptions.rst
  Misc/NEWS.d/next/Documentation/2021-06-06-14-12-00.bpo-44322.K0PHfE.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, type-documentation

#26569 [3.10] bpo-44322: Document more SyntaxError details. (GH-26562)
  Doc/library/exceptions.rst
  Misc/NEWS.d/next/Documentation/2021-06-06-14-12-00.bpo-44322.K0PHfE.rst
Labels: CLA signed, awaiting review, type-documentation

#22659 bpo-37449: ensurepip uses importlib.resources.files() traversable APIs
  Lib/ensurepip/__init__.py
  Lib/ensurepip/_bundled/__init__.py
  Misc/NEWS.d/next/Library/2020-10-11-20-23-48.bpo-37449.f-t3V6.rst
Labels: CLA signed, awaiting merge, stale

#26570 [3.9] bpo-44322: Document more SyntaxError details. (GH-26562)
  Doc/library/exceptions.rst
  Misc/NEWS.d/next/Documentation/2021-06-06-14-12-00.bpo-44322.K0PHfE.rst
Labels: CLA signed, awaiting core review, type-documentation

#26422 bpo-44258: support PEP 515 for Fraction's initialization from string
  Doc/library/fractions.rst
  Doc/whatsnew/3.11.rst
  Lib/fractions.py
  Lib/test/test_fractions.py
  Misc/NEWS.d/next/Library/2021-05-28-09-43-33.bpo-44258.nh5F7R.rst
Labels: CLA signed, awaiting merge

#26264 bpo-44187: Quickening infrastructure
  Include/cpython/code.h
  Include/internal/pycore_code.h
  Lib/test/libregrtest/refleak.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2021-05-20-12-43-04.bpo-44187.3lk0L1.rst
  Objects/codeobject.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/ceval.c
  Python/clinic/sysmodule.c.h
  Python/specialize.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review

#26577 bpo-43693: Un-revert commits 2c1e258 and b2bf2bc.
  Doc/library/dis.rst
  Include/cpython/code.h
  Include/internal/pycore_code.h
  Lib/ctypes/test/test_values.py
  Lib/dis.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-02-15-02-16.bpo-43693.l3Ureu.rst
  Misc/NEWS.d/next/Core and Builtins/2021-05-21-20-53-49.bpo-43693.-NN3J_.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Objects/frameobject.c
  Objects/typeobject.c
  Programs/test_frozenmain.h
  Python/ceval.c
  Python/compile.c
  Python/frozen_hello.h
  Python/importlib.h
  Python/importlib_external.h
  Python/importlib_zipimport.h
  Python/marshal.c
  Python/suggestions.c
  Tools/gdb/libpython.py
Labels: CLA signed, awaiting core review

#26568 bpo-41299: fix 16ms jitter in Windows threading timeouts
  Misc/NEWS.d/next/Windows/2021-06-06-16-36-13.bpo-41299.Rg-vb_.rst
  Python/thread_nt.h
Labels: CLA signed, awaiting review, needs backport to 3.10, needs backport to 3.9

#26581 Use absolute import in IDLE tests
  Lib/idlelib/idle_test/test_colorizer.py
Labels: CLA signed, awaiting core review, needs backport to 3.10, skip issue, skip news, type-bugfix, type-tests

#26583 [3.10] Use absolute imports in IDLE tests (GH-26581)
  Lib/idlelib/idle_test/test_colorizer.py
Labels: CLA signed, awaiting merge, skip issue, skip news, type-bugfix, type-tests

#26396 bpo-43693: Add the MAKE_CELL opcode and interleave fast locals offsets.
  Doc/library/dis.rst
  Include/cpython/code.h
  Include/internal/pycore_frame.h
  Include/opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_dis.py
  Lib/test/test_scope.py
  Misc/NEWS.d/next/Core and Builtins/2021-05-26-19-10-47.bpo-43693.1KSG9u.rst
  Objects/frameobject.c
  Objects/typeobject.c
  Python/ceval.c
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/opcode_targets.h
Labels: CLA signed, awaiting core review

#26588 bpo-43693: Silence some compiler warnings.
  Include/cpython/code.h
  Include/internal/pycore_code.h
Labels: CLA signed, awaiting core review, skip news

#26582 fix: use unambiguous punction in 'invalid escape sequence' message
  Lib/test/test_cmd_line_script.py
  Parser/string_parser.c
Labels: CLA signed, awaiting merge, needs backport to 3.10, skip issue, skip news

#26590 [3.10] fix: use unambiguous punction in 'invalid escape sequence' message (GH-26582)
  Lib/test/test_cmd_line_script.py
  Parser/string_parser.c
Labels: CLA signed, awaiting merge, skip issue, skip news

#26575 bpo-42238: Doc CI: Disable suspicious checks.
  .github/workflows/doc.yml
  .travis.yml
Labels: CLA signed, awaiting merge, skip news, type-documentation

#26594 Use from imports
  Lib/concurrent/futures/process.py
Labels: CLA signed, awaiting merge, skip issue, skip news

#26596 bpo-44348: Revert "bpo-39573: Py_TYPE becomes a static inline function (GH-26493)"
  Doc/c-api/structures.rst
  Doc/whatsnew/3.11.rst
  Include/object.h
  Misc/NEWS.d/next/C API/2021-06-03-00-59-48.bpo-39573.-elHTJ.rst
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting core review

#26589 bpo-44335: Fix a regression when identifying invalid characters in syntax errors
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-08-01-13-47.bpo-44335.GQTTkl.rst
  Parser/pegen.c
Labels: CLA signed, awaiting merge, needs backport to 3.10

#26600 [3.10] bpo-44335: Fix a regression when identifying invalid characters in syntax errors (GH-26589)
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-08-01-13-47.bpo-44335.GQTTkl.rst
  Parser/pegen.c
Labels: CLA signed, awaiting merge

#26601 Fix compiler errors for unused variables
  Modules/_sqlite/connection.c
  Python/compile.c
Labels: CLA signed, awaiting core review, skip issue, skip news

#26597 Revert "bpo-43693: Add the MAKE_CELL opcode and interleave fast locals offsets. (gh-26396)"
  Doc/library/dis.rst
  Include/cpython/code.h
  Include/internal/pycore_frame.h
  Include/opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_dis.py
  Lib/test/test_scope.py
  Misc/NEWS.d/next/Core and Builtins/2021-05-26-19-10-47.bpo-43693.1KSG9u.rst
  Objects/frameobject.c
  Objects/typeobject.c
  Python/ceval.c
  Python/compile.c
  Python/importlib.h
  Python/importlib_external.h
  Python/opcode_targets.h
Labels: CLA signed, awaiting core review

#26566 bpo-44329: Refactor sqlite3 statement creation
  Modules/_sqlite/statement.c
Labels: CLA signed, awaiting merge, skip news

#26603 [3.10] bpo-43795: Note Stable ABI PEP in What's New (GH-26479)
  Doc/whatsnew/3.10.rst
Labels: CLA signed, awaiting review, skip news, type-documentation

#26550 bpo-11105: use a lower recursion limit for infinite recursion tests
  Lib/test/support/__init__.py
  Lib/test/test_ast.py
Labels: CLA signed, awaiting core review, skip news

#26604 bpo-11105: document the new test.support.infinite_recursion context m…
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting core review, skip news

#26607 [3.10] bpo-11105: reduce the recursion limit for tests (GH-26550).
  Lib/test/support/__init__.py
  Lib/test/test_ast.py
Labels: CLA signed, awaiting core review, skip news

#26605 [3.9] bpo-11105: reduce the recursion limit for tests (GH-26550).
  Lib/test/support/__init__.py
  Lib/test/test_ast.py
Labels: CLA signed, awaiting core review, skip news

#26608 bpo-44335: Ensure the tokenizer doesn't go into Python with the error set
  Parser/pegen.c
Labels: CLA signed, awaiting core review, needs backport to 3.10, skip news

#26610 [3.10] bpo-44335: Ensure the tokenizer doesn't go into Python with the error set (GH-26608)
  Parser/pegen.c
Labels: CLA signed, awaiting merge, skip news

#26593 bpo-40468: Move help extension settings to extensions page of dialog.
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2021-06-08-03-04-51.bpo-40468.tUCGUb.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9, type-bugfix

#26612 [3.10] bpo-40468: Move IDLE helplist settings to extensions page of dialog. (GH-26593)
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2021-06-08-03-04-51.bpo-40468.tUCGUb.rst
Labels: CLA signed, awaiting merge, type-bugfix

#26613 [3.9] bpo-40468: Move IDLE helplist settings to extensions page of dialog. (GH-26593)
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2021-06-08-03-04-51.bpo-40468.tUCGUb.rst
Labels: CLA signed, awaiting merge, type-bugfix

#26614 [3.10] bpo-43833: Emit warnings for numeric literals followed by keyword (GH-25466)
  Doc/whatsnew/3.10.rst
  Lib/test/test_compile.py
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core and Builtins/2021-04-18-18-07-33.bpo-43833.oChkCi.rst
  Parser/tokenizer.c
Labels: CLA signed, awaiting merge

#26611 bpo-44349: Fix edge case when displaying text from files with encoding in syntax errors
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-08-22-49-06.bpo-44349.xgEgeA.rst
  Parser/pegen.c
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9

#26616 [3.10] bpo-44349: Fix edge case when displaying text from files with encoding in syntax errors (GH-26611)
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-08-22-49-06.bpo-44349.xgEgeA.rst
  Parser/pegen.c
Labels: CLA signed, awaiting merge

#26618 bpo-40468: Factor out class ExtPage in idlelib.configdialog
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9, skip news

#26619 [3.9] bpo-40468: Factor out class ExtPage in idlelib.configdialog (GH-26618)
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
Labels: CLA signed, awaiting merge, skip news

#26620 [3.10] bpo-40468: Factor out class ExtPage in idlelib.configdialog (GH-26618)
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
Labels: CLA signed, awaiting merge, skip news

#26615 bpo-44345: Fix comment in parser.c
  Parser/parser.c
  Tools/peg_generator/pegen/c_generator.py
Labels: CLA not signed, awaiting merge, skip news

#26624 bpo-44187: Delete line that was accidentally copied.
  Lib/test/libregrtest/refleak.py
Labels: CLA signed, awaiting core review, skip news

#26586 bpo-44242: [Enum] remove missing bits test from Flag creation
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-06-07-10-26-14.bpo-44242.MKeMCQ.rst
Labels: CLA signed, awaiting core review

#26621 bpo-40468: Split IDLE settings General tab
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2021-06-08-03-04-51.bpo-40468.tUCGUb.rst
Labels: CLA signed, awaiting core review, needs backport to 3.10, needs backport to 3.9

#26628 [3.10] bpo-40468: Split IDLE settings General tab (GH-26621)
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2021-06-08-03-04-51.bpo-40468.tUCGUb.rst
Labels: CLA signed, awaiting merge

#26629 [3.9] bpo-40468: Split IDLE settings General tab (GH-26621)
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2021-06-08-03-04-51.bpo-40468.tUCGUb.rst
Labels: CLA signed, awaiting merge

#19097 bpo-21760: fix __file__ description
  Doc/reference/import.rst
  Misc/NEWS.d/next/Documentation/2020-03-21-01-19-28.bpo-21760.CqofIc.rst
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#26630 bpo-44368: Ensure we don't raise incorrect custom syntax errors with soft keywords
  Lib/test/test_exceptions.py
  Lib/test/test_syntax.py
  Parser/pegen.c
Labels: CLA signed, awaiting core review, needs backport to 3.10, skip news

#26631 [3.10] bpo-44368: Ensure we don't raise incorrect custom syntax errors with soft keywords (GH-26630)
  Lib/test/test_exceptions.py
  Lib/test/test_syntax.py
  Parser/pegen.c
Labels: CLA signed, awaiting merge, skip news

#26617 bpo-35800: Remove smtpd.MailmanProxy since 3.11
  Doc/library/smtpd.rst
  Doc/whatsnew/3.11.rst
  Lib/smtpd.py
  Misc/NEWS.d/next/Library/2021-06-09-10-08-32.bpo-35800.3hmkWw.rst
Labels: CLA signed, awaiting merge

#26595 bpo-44337: Port LOAD_ATTR to PEP 659 adaptive interpreter
  Include/internal/pycore_code.h
  Include/internal/pycore_dict.h
  Include/opcode.h
  Lib/opcode.py
  Lib/test/test_capi.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2021-06-08-10-22-46.bpo-44337.RTjmIt.rst
  Objects/dictobject.c
  Objects/odictobject.c
  Python/ceval.c
  Python/makeopcodetargets.py
  Python/opcode_targets.h
  Python/specialize.c
  Tools/scripts/generate_opcode_h.py
Labels: CLA signed, awaiting merge

#26623 bpo-44348: Move trace-info to thread-state
  Include/cpython/pystate.h
  Lib/test/test_pdb.py
  Python/ceval.c
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news

#26639 bpo-44363: Get test_capi passing with address sanitizer
  Include/Python.h
  Misc/NEWS.d/next/Tests/2021-06-10-11-19-43.bpo-44363.-K9jD0.rst
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge

#26641 [3.9] bpo-44363: Get test_capi passing with address sanitizer (GH-26639)
  Include/Python.h
  Misc/NEWS.d/next/Tests/2021-06-10-11-19-43.bpo-44363.-K9jD0.rst
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge

#26642 [3.10] bpo-44363: Get test_capi passing with address sanitizer (GH-26639)
  Include/Python.h
  Misc/NEWS.d/next/Tests/2021-06-10-11-19-43.bpo-44363.-K9jD0.rst
  Modules/_testcapimodule.c
Labels: CLA signed, awaiting merge

#26635 [3.10] bpo-44242: [Enum] remove missing bits test from Flag creation (GH-26586)
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-06-07-10-26-14.bpo-44242.MKeMCQ.rst
Labels: CLA signed, awaiting core review

#26625 bpo-44364:Add non integral tests for `sqrt()`
  Lib/test/test_math.py
  Misc/NEWS.d/next/Tests/2021-06-09-15-32-05.bpo-44364.zu9Zee.rst
Labels: CLA signed, awaiting merge, type-tests

#26622 bpo-44357:Add `math.cbrt()` function: Cube Root
  Doc/library/math.rst
  Doc/whatsnew/3.11.rst
  Lib/test/test_math.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2021-06-09-08-32-39.bpo-44357.70Futb.rst
  Modules/mathmodule.c
Labels: CLA signed, awaiting merge

#26647 [3.10] bpo-33962: Use ttk spinbox for IDLE indent space config (GH-22954)
  Lib/idlelib/configdialog.py
  Lib/idlelib/idle_test/test_configdialog.py
  Misc/NEWS.d/next/IDLE/2021-06-10-00-50-02.bpo-33962.ikAUNg.rst
Labels: CLA signed, awaiting merge, type-enhancement

#26649 bpo-44356: [Enum] allow multiple data-type mixins if they are all the same
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-06-10-08-35-38.bpo-44356.6oDFhO.rst
Labels: CLA signed

#18180 bpo-37022: Fix bug where `pdb`'s `do_p`/`do_pp` commands swallow exceptions from `repr`
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2020-01-25-12-58-20.bpo-37022.FUZI25.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, type-bugfix

#26650 [3.10] bpo-37022: Fix bug where pdb's do_p/do_pp commands swallow exceptions from repr (GH-18180)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2020-01-25-12-58-20.bpo-37022.FUZI25.rst
Labels: CLA signed, awaiting review, type-bugfix

#26651 [3.9] bpo-37022: Fix bug where pdb's do_p/do_pp commands swallow exceptions from repr (GH-18180)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2020-01-25-12-58-20.bpo-37022.FUZI25.rst
Labels: CLA signed, awaiting review, type-bugfix

#26653 [3.10] bpo-44356: [Enum] allow multiple data-type mixins if they are all the same (GH-26649)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-06-10-08-35-38.bpo-44356.6oDFhO.rst
Labels: CLA signed, awaiting merge

#26652 [3.9] bpo-44356: [Enum] allow multiple data-type mixins if they are all the same (GH-26649)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-06-10-08-35-38.bpo-44356.6oDFhO.rst
Labels: CLA signed, awaiting merge

#26655 bpo-44385: Remove unused grammar rules
  Grammar/python.gram
  Parser/parser.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.9, skip news

#26657 [3.10] bpo-44385: Remove unused grammar rules (GH-26655)
  Grammar/python.gram
  Parser/parser.c
Labels: CLA signed, awaiting merge, skip news

#26632 bpo-44368: Improve syntax errors with invalid as pattern targets
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2021-06-09-22-56-59.bpo-44368.vgT0Cx.rst
  Parser/parser.c
Labels: :robot: automerge, CLA signed, awaiting merge, needs backport to 3.10

#26658 bpo-44342: [Enum] change pickling from by-value to by-name
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-06-10-15-06-47.bpo-44342.qqkGlj.rst
Labels: CLA signed, awaiting core review

#26659 [3.9] bpo-44385: Remove unused grammar rules (GH-26655)
  Grammar/python.gram
  Parser/pegen/parse.c
Labels: :robot: automerge, CLA signed, awaiting merge, skip news

#26660 [3.10] bpo-44342: [Enum] changed pickling from by-value to by-name (GH-26658)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2021-06-10-15-06-47.bpo-44342.qqkGlj.rst
Labels: CLA signed, awaiting merge

#26533 Doc: Prettier exception hierarchy.
  Doc/library/exceptions.rst
  Lib/test/exception_hierarchy.txt
  Lib/test/test_baseexception.py
Labels: CLA signed, awaiting core review, skip issue, skip news

#26646 bpo-44362: ssl: improve deprecation warnings and docs (GH-26646)
  Doc/library/ssl.rst
  Doc/whatsnew/3.10.rst
  Lib/ssl.py
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2021-06-10-20-07-32.bpo-44362.oVOMfd.rst
  Modules/_ssl.c
Labels: CLA signed, awaiting core review, needs backport to 3.10, type-documentation

#26665 [3.10] bpo-44362: ssl: improve deprecation warnings and docs (GH-26646)
  Doc/library/ssl.rst
  Doc/whatsnew/3.10.rst
  Lib/ssl.py
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2021-06-10-20-07-32.bpo-44362.oVOMfd.rst
  Modules/_ssl.c
Labels: :robot: automerge, CLA signed, awaiting merge, type-documentation

#26667 bpo-44342: [Enum] fix data type search
  Lib/enum.py
  Lib/test/test_enum.py
Labels: CLA signed, awaiting core review, skip news
