Repository python/cpython, pull requests merged in 2022-11, with the labels that each got.

#98898 GH-98897: fix memory leak if `math.dist` raises exception
  Lib/test/test_math.py
  Misc/NEWS.d/next/Library/2022-10-31-12-34-03.gh-issue-98897.rgNn4x.rst
  Modules/mathmodule.c
Labels: type-bug, awaiting merge, needs backport to 3.10, needs backport to 3.11

#98921 Typo in tutorial
  Doc/tutorial/controlflow.rst
Labels: docs, skip issue, awaiting review, skip news, needs backport to 3.11

#98941 [3.11] GH-98897: fix memory leak if `math.dist` raises exception (GH-98898)
  Lib/test/test_math.py
  Misc/NEWS.d/next/Library/2022-10-31-12-34-03.gh-issue-98897.rgNn4x.rst
  Modules/mathmodule.c
Labels: type-bug, awaiting merge, :robot: automerge

#98942 [3.10] GH-98897: fix memory leak if `math.dist` raises exception (GH-98898)
  Lib/test/test_math.py
  Misc/NEWS.d/next/Library/2022-10-31-12-34-03.gh-issue-98897.rgNn4x.rst
  Modules/mathmodule.c
Labels: type-bug, awaiting merge, :robot: automerge

#98939 fix wording in Functional Programming HOWTO
  Doc/howto/functional.rst
Labels: docs, skip issue, awaiting review, skip news, needs backport to 3.11

#98934 Rename JUMP_TO_INSTRUCTION to GO_TO_INSTRUCTION
  Python/ceval.c
Labels: skip issue, awaiting merge, skip news

#98945 [3.11] Fix wording in Functional Programming HOWTO (GH-98939)
  Doc/howto/functional.rst
Labels: docs, skip issue, awaiting merge, skip news, :robot: automerge

#98661 gh-98658: Add __class_getitem__ to array.array
  Doc/whatsnew/3.12.rst
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Library/2022-10-25-07-00-31.gh-issue-98658.nGABW9.rst
  Modules/arraymodule.c
Labels: awaiting merge

#98946 GH-98766: Modest speed-up from ChainMap.__iter__
  Lib/collections/__init__.py
Labels: performance, awaiting core review, skip news

#98920 gh-98852: Fix subscription of type aliases
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-31-21-01-35.gh-issue-98852.MYaRN6.rst
  Objects/genericaliasobject.c
Labels: awaiting merge, needs backport to 3.11

#98952 [3.11] gh-98852: Fix subscription of type aliases (GH-98920)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-31-21-01-35.gh-issue-98852.MYaRN6.rst
  Objects/genericaliasobject.c
Labels: awaiting merge

#98932 gh-98931: Improve error message when the user types 'import x from y' instead of 'from y import x'
  Doc/whatsnew/3.12.rst
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-31-22-55-34.gh-issue-98931.AoWZ-4.rst
  Parser/parser.c
Labels: awaiting merge

#98960 [3.10] Doc: use "unnumbered" footnotes (GH-98954)
  Doc/tutorial/datastructures.rst
Labels: docs, skip issue, awaiting merge, skip news

#98961 [3.11] Doc: use "unnumbered" footnotes (GH-98954)
  Doc/tutorial/datastructures.rst
Labels: docs, skip issue, awaiting merge, skip news

#98968 gh-98689: Update Windows builds to zlib v1.2.13
  Misc/NEWS.d/next/Windows/2022-11-01-11-07-33.gh-issue-98689.0f6e_N.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: type-bug, type-security, OS-windows, awaiting merge, needs backport to 3.10, needs backport to 3.11

#98969 [3.10] gh-98852: Fix subscription of types.GenericAlias instances (GH-98920)
  Lib/_collections_abc.py
  Lib/test/test_typing.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-31-21-01-35.gh-issue-98852.MYaRN6.rst
  Objects/genericaliasobject.c
Labels: awaiting core review

#98972 [3.10] gh-98689: Update Windows builds to zlib v1.2.13 (GH-98968)
  Misc/NEWS.d/next/Windows/2022-11-01-11-07-33.gh-issue-98689.0f6e_N.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: type-bug, type-security, awaiting merge

#98971 [3.11] gh-98689: Update Windows builds to zlib v1.2.13 (GH-98968)
  Misc/NEWS.d/next/Windows/2022-11-01-11-07-33.gh-issue-98689.0f6e_N.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: type-bug, type-security, awaiting merge

#98938 gh-98925: Lower marshal recursion depth for WASI
  .gitignore
  Lib/test/test_marshal.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-31-18-03-10.gh-issue-98925.zpdjVd.rst
  Python/marshal.c
Labels: awaiting merge, :robot: automerge, needs backport to 3.11

#98922 [doc] Update cookbook example for socket-based logging in a production sett… (GH-98922)
  Doc/howto/logging-cookbook.rst
Labels: docs, skip issue, awaiting core review, skip news

#98979 [3.11] gh-98925: Lower marshal recursion depth for WASI (GH-98938)
  .gitignore
  Lib/test/test_marshal.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-31-18-03-10.gh-issue-98925.zpdjVd.rst
  Python/marshal.c
Labels: awaiting review, :robot: automerge

#98980 [3.11] [doc] Update cookbook example for socket-based logging in a production sett… (GH-98922) (GH-98980)
  Doc/howto/logging-cookbook.rst
Labels: docs, skip issue, awaiting review, skip news

#98981 [3.10] [doc] Update cookbook example for socket-based logging in a production sett… (GH-98922) (GH-98981)
  Doc/howto/logging-cookbook.rst
Labels: docs, skip issue, awaiting review, skip news

#98958 gh-92871: Postpone the removal of typing.{io,re} to 3.13
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#98985 [3.11] gh-92871: Postpone the removal of typing.{io,re} to 3.13 (GH-98958)
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news

#92682 gh-92679: Clarify asyncio.loop.start_tls parameters
  Doc/library/asyncio-eventloop.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#98242 gh-96265: Formatting changes for faq/programming
  Doc/faq/programming.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#98990 [3.10] gh-92679: Clarify asyncio.loop.start_tls parameters (GH-92682)
  Doc/library/asyncio-eventloop.rst
Labels: docs, awaiting merge, skip news

#98991 [3.11] gh-96265: Formatting changes for faq/programming (GH-98242)
  Doc/faq/programming.rst
Labels: docs, awaiting merge, skip news

#98992 [3.11] gh-92679: Clarify asyncio.loop.start_tls parameters (GH-92682)
  Doc/library/asyncio-eventloop.rst
Labels: docs, awaiting merge, skip news

#98986 [3.10] gh-92871: Postpone the removal of typing.{io,re} to 3.13 (GH-98958)
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news

#98913 gh-87092: do not allocate PyFutureFeatures dynamically
  Include/internal/pycore_compile.h
  Python/compile.c
  Python/future.c
  Python/symtable.c
Labels: awaiting merge, skip news, interpreter-core

#98957 GH-90699: Remove `_Py_IDENTIFIER` usage from `_curses` module
  Modules/_cursesmodule.c
Labels: awaiting merge, skip news, :robot: automerge

#98914 gh-87092: remove unused SET_LOC/UNSET_LOC macros
  Python/compile.c
Labels: awaiting merge, skip news, interpreter-core

#98988 gh-98989: configure: add 3.11 to list of Pythons
  Misc/NEWS.d/next/Build/2022-11-01-21-45-58.gh-issue-98989.tMxbdB.rst
  configure
  configure.ac
Labels: awaiting merge

#99010 GH-90699: Remove `_Py_IDENTIFIER` usage from `_asyncio` module
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Modules/_asynciomodule.c
Labels: awaiting merge, skip news, :robot: automerge

#98687 GH-98686: Quicken everything
  Include/cpython/code.h
  Include/internal/pycore_code.h
  Include/internal/pycore_opcode.h
  Include/opcode.h
  Lib/opcode.py
  Lib/test/libregrtest/refleak.py
  Lib/test/test_call.py
  Lib/test/test_dis.py
  Lib/test/test_embed.py
  Lib/test/test_lltrace.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-16-13-26-46.gh-issue-98686.D9Gu_Q.rst
  Objects/codeobject.c
  Objects/frameobject.c
  Objects/genobject.c
  Python/ceval.c
  Python/clinic/sysmodule.c.h
  Python/opcode_targets.h
  Python/specialize.c
  Python/sysmodule.c
  Tools/build/deepfreeze.py
  Tools/c-analyzer/cpython/globals-to-fix.tsv
Labels: performance, awaiting merge, interpreter-core

#99017 gh-99016: Make build scripts compatible with Python 3.8
  Misc/NEWS.d/next/Build/2022-11-02-19-25-07.gh-issue-99016.R05NkD.rst
  Tools/build/generate_levenshtein_examples.py
  Tools/build/generate_opcode_h.py
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11

#98936 gh-98790: When DLLs directory is missing on Windows, assume executable_dir contains PYD files instead
  Lib/test/test_embed.py
  Lib/test/test_getpath.py
  Misc/NEWS.d/next/Windows/2022-11-01-00-37-13.gh-issue-98790.fpaPAx.rst
  Modules/getpath.py
Labels: OS-windows, awaiting merge, needs backport to 3.11

#98423 gh-98415: Fix UUID ifconfig MAC address detection
  Lib/uuid.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-19-01-01-08.gh-issue-98415.ZS2eWh.rst
Labels: awaiting changes, needs backport to 3.10, needs backport to 3.11

#99021 [3.11] gh-98415: Fix uuid.getnode() ifconfig implementation (GH-98423)
  Lib/uuid.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-19-01-01-08.gh-issue-98415.ZS2eWh.rst
Labels: awaiting merge

#99020 [3.10] gh-98415: Fix uuid.getnode() ifconfig implementation (GH-98423)
  Lib/uuid.py
  Misc/NEWS.d/next/Core and Builtins/2022-10-19-01-01-08.gh-issue-98415.ZS2eWh.rst
Labels: awaiting merge

#98982 gh-97731: Specify the full path to the docs for `make docclean`
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2022-11-02-18-45-35.gh-issue-97731.zKpTlj.rst
Labels: awaiting merge, needs backport to 3.10, build, needs backport to 3.11

#98487 gh-98393: Update test_os for bytes-like types
  Lib/test/test_os.py
Labels: tests, awaiting merge, skip news

#99024 [3.11] gh-97731: Specify the full path to the docs for `make docclean` (GH-98982)
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2022-11-02-18-45-35.gh-issue-97731.zKpTlj.rst
Labels: awaiting merge, :robot: automerge

#99019 [3.11] gh-98790: When DLLs directory is missing on Windows, assume executable_dir contains PYD files instead (GH-98936)
  Lib/test/test_embed.py
  Lib/test/test_getpath.py
  Misc/NEWS.d/next/Windows/2022-11-01-00-37-13.gh-issue-98790.fpaPAx.rst
  Modules/getpath.py
Labels: awaiting core review

#99012 GH-90699: Remove `_Py_IDENTIFIER` usage from `_elementtree` module
  Modules/_elementtree.c
Labels: awaiting merge, skip news, :robot: automerge

#99025 [3.10] gh-97731: Specify the full path to the docs for `make docclean` (GH-98982)
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2022-11-02-18-45-35.gh-issue-97731.zKpTlj.rst
Labels: awaiting review, :robot: automerge

#98977 gh-96997: Clarify the contract of PyMem_SetAllocator()
  Doc/c-api/memory.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#99028 [3.10] gh-96997: Clarify the contract of PyMem_SetAllocator() (GH-98977)
  Doc/c-api/memory.rst
Labels: docs, awaiting merge, skip news

#99027 [3.11] gh-96997: Clarify the contract of PyMem_SetAllocator() (GH-98977)
  Doc/c-api/memory.rst
Labels: docs, awaiting merge, skip news

#98994 [3.10] gh-96265: Formatting changes for faq/programming (GH-98242)
  Doc/faq/programming.rst
Labels: docs, awaiting merge, skip news

#98883 Use f-string in preference to "...".format()
  Doc/howto/argparse.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#98515 gh-98512: Add more tests for `ValuesView`
  Lib/test/test_collections.py
  Lib/test/test_dictviews.py
Labels: tests, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#99001 Docs: Add 'as, match statement' to the index
  Doc/reference/compound_stmts.rst
Labels: docs, skip issue, awaiting review, skip news, needs backport to 3.10, needs backport to 3.11

#99033 [3.10] argparse howto: Use f-string in preference to "...".format() (GH-98883)
  Doc/howto/argparse.rst
Labels: docs, skip issue, awaiting merge, skip news

#99034 [3.11] argparse howto: Use f-string in preference to "...".format() (GH-98883)
  Doc/howto/argparse.rst
Labels: docs, skip issue, awaiting merge, skip news

#99037 [3.11] Docs: Add 'as, match statement' to the index (GH-99001)
  Doc/reference/compound_stmts.rst
Labels: docs, skip issue, awaiting merge, skip news

#99038 [3.10] Docs: Add 'as, match statement' to the index (GH-99001)
  Doc/reference/compound_stmts.rst
Labels: docs, skip issue, awaiting merge, skip news

#98803 [3.10] gh-65002: Make note that null bytes are used to pad bytes (GH-98635)
  Doc/library/struct.rst
Labels: docs, awaiting merge, skip news

#98804 [3.11] gh-65002: Make note that null bytes are used to pad bytes (GH-98635)
  Doc/library/struct.rst
Labels: docs, awaiting merge, skip news

#99036 [3.10] gh-98512: Add more tests for `ValuesView` (GH-98515)
  Lib/test/test_collections.py
  Lib/test/test_dictviews.py
Labels: tests, awaiting merge, skip news

#99035 [3.11] gh-98512: Add more tests for `ValuesView` (GH-98515)
  Lib/test/test_collections.py
  Lib/test/test_dictviews.py
Labels: tests, awaiting merge, skip news

#99009 gh-98999: Raise `ValueError` in `_pyio` on closed buffers
  Lib/_pyio.py
  Lib/test/test_io.py
  Misc/NEWS.d/next/Library/2022-11-02-18-27-13.gh-issue-98999.Ai2KDh.rst
Labels: awaiting merge

#98830 GH-98831: "Generate" the interpreter
  .gitattributes
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2022-10-28-22-24-26.gh-issue-98831.IXRCRX.rst
  Python/bytecodes.c
  Python/ceval.c
  Python/generated_cases.c.h
  Tools/cases_generator/README.md
  Tools/cases_generator/bytecodes_template.c
  Tools/cases_generator/extract_cases.py
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/lexer.py
  Tools/cases_generator/parser.py
  Tools/cases_generator/plexer.py
Labels: awaiting merge, DO-NOT-MERGE

#98764 gh-98740: Fix validation of conditional expressions in RE
  Doc/library/re.rst
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2022-10-27-12-56-38.gh-issue-98740.ZoqqGM.rst
  Modules/_sre/sre.c
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#99045 [3.11] gh-98740: Fix validation of conditional expressions in RE (GH-98764)
  Doc/library/re.rst
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2022-10-27-12-56-38.gh-issue-98740.ZoqqGM.rst
  Modules/_sre/sre.c
Labels: awaiting merge

#99006 GH-96793: Implement PEP 479 in bytecode.
  Doc/library/dis.rst
  Include/internal/pycore_opcode.h
  Include/opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_dis.py
  Lib/test/test_sys.py
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2022-11-02-14-42-35.gh-issue-96793.q0Oi74.rst
  Objects/genobject.c
  Python/bytecodes.c
  Python/compile.c
  Python/generated_cases.c.h
  Python/opcode_targets.h
Labels: awaiting merge

#98949 gh-98948: Remove obsolete readelf dependency
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2022-11-02-10-56-40.gh-issue-98949.3SRD8C.rst
  Tools/wasm/config.site-wasm32-emscripten
  Tools/wasm/config.site-wasm32-wasi
  configure
  configure.ac
Labels: awaiting review

#98840 gh-83004: Clean up refleak in _io initialisation
  Misc/NEWS.d/next/Library/2022-11-02-05-52-36.gh-issue-83004.LBl79O.rst
  Modules/_io/_iomodule.c
Labels: awaiting merge

#99057 gh-97616: test_list_resize_overflow() uses sys.maxsize
  Lib/test/test_list.py
Labels: tests, awaiting core review, skip news

#99060 [3.10] gh-83004: Clean up refleak in _io initialisation (GH-98840)
  Misc/NEWS.d/next/Library/2022-11-02-05-52-36.gh-issue-83004.LBl79O.rst
  Modules/_io/_iomodule.c
Labels: awaiting merge

#99065 GH-98831: Remove redundant extract_cases.py script
  Tools/cases_generator/README.md
  Tools/cases_generator/bytecodes_template.c
  Tools/cases_generator/extract_cases.py
Labels: awaiting core review, skip news

#98810 gh-97909: PyMemberDef & PyGetSetDef members are not marked up
  Doc/c-api/structures.rst
Labels: docs, awaiting review, skip news

#99062 gh-92584: Remove references to removed _bootsubprocess
  Lib/_aix_support.py
  Tools/wasm/wasm_assets.py
Labels: awaiting core review, skip news

#98885 gh-98884: [pathlib] remove `hasattr` check for `lru_cache`
  Lib/pathlib.py
Labels: awaiting merge, skip news

#99063 gh-90716: Remove _pylong._DEBUG flag
  Lib/_pylong.py
Labels: awaiting core review, skip news

#94173 gh-94172: Remove keyfile, certfile and check_hostname parameters
  Doc/whatsnew/3.12.rst
  Lib/ftplib.py
  Lib/http/client.py
  Lib/imaplib.py
  Lib/poplib.py
  Lib/smtplib.py
  Lib/test/test_ftplib.py
  Lib/test/test_httplib.py
  Lib/test/test_imaplib.py
  Lib/test/test_poplib.py
  Misc/NEWS.d/next/Library/2022-06-23-15-31-49.gh-issue-94172.AXE2IZ.rst
  Misc/NEWS.d/next/Library/2022-06-23-15-36-49.gh-issue-94172.DzQk0s.rst
Labels: awaiting core review

#99068 [3.11] gh-98978: Fix Py_SetPythonHome(NULL) (GH-99066)
  Misc/NEWS.d/next/C API/2022-11-03-17-46-41.gh-issue-98978.KJjBvv.rst
  Python/pathconfig.c
Labels: awaiting merge

#99054 GH-90699: Remove `_Py_IDENTIFIER` usage from `_ctypes`
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/callbacks.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/stgdict.c
Labels: awaiting merge, skip news, :robot: automerge

#99070 gh-73691: Increase size limits in _xxtestfuzz
  Modules/_xxtestfuzz/fuzzer.c
Labels: awaiting merge, skip news

#99073 gh-90716: bugfixes and more tests for _pylong.
  Lib/test/test_int.py
  Objects/longobject.c
Labels: awaiting merge, skip news

#99078 Docs: add `named` to the note describing the sqlite3.paramstyle attribute
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#99081 [3.11] Docs: add `named` to the list of styles in the sqlite3.paramstyle attr docs (GH-99078)
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting merge, skip news

#99082 [3.10] Docs: add `named` to the list of styles in the sqlite3.paramstyle attr docs (GH-99078)
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting merge, skip news

#96767 gh-94808: Cover `LOAD_GLOBAL` for custom dict subtypes
  Lib/test/test_builtin.py
Labels: tests, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#98816 Support comparing two sets of pystats
  Doc/using/configure.rst
  Tools/scripts/summarize_stats.py
Labels: skip issue, awaiting review, skip news

#99091 [3.11] gh-94808: Cover `LOAD_GLOBAL` for custom dict subtypes (GH-96767)
  Lib/test/test_builtin.py
Labels: tests, awaiting review, skip news, :robot: automerge

#99096 [3.11] minor edits to locale doc (GH-98537)
  Doc/library/locale.rst
Labels: docs, skip issue, awaiting merge, skip news

#99095 [3.10] minor edits to locale doc (GH-98537)
  Doc/library/locale.rst
Labels: docs, skip issue, awaiting merge, skip news

#99094 gh-90716: Fix pylong_int_from_string() refleak
  Objects/longobject.c
Labels: awaiting core review, skip news

#99071 gh-90867: test.support.wait_process() uses LONG_TIMEOUT
  Lib/test/support/__init__.py
Labels: awaiting core review, skip news

#99098 [3.11] gh-90867: test.support.wait_process() uses LONG_TIMEOUT (#99071)
  Lib/test/support/__init__.py
Labels: awaiting core review, skip news, needs backport to 3.10

#99099 [3.10] [3.11] gh-90867: test.support.wait_process() uses LONG_TIMEOUT (GH-99071) (GH-99098)
  Lib/test/support/__init__.py
Labels: awaiting merge, skip news

#99107 GH-98831: Add `regen-cases` to `regen-all`
  Makefile.pre.in
Labels: awaiting merge, skip news, build

#99102 GH-98831: Auto-generate PREDICTED() macro calls
  Python/bytecodes.c
  Tools/cases_generator/generate_cases.py
Labels: awaiting merge, skip news

#99093 GH-98831: Add some macros definitions to bytecodes.c to reduce IDE warnings.
  Python/bytecodes.c
Labels: awaiting merge, skip news

#99106 GH-98686: Fix compiler warning for `HAS_ARG`
  Python/ceval.c
Labels: awaiting merge, skip news, interpreter-core

#99112 GH-99104: Update headers for bytecodes.c and generate_cases.py
  Python/bytecodes.c
  Python/generated_cases.c.h
  Tools/cases_generator/generate_cases.py
Labels: awaiting merge, skip news

#99085 gh-99086: Fix implicit int warning in configure check for PTHREAD_SCOPE_SYSTEM (#99085)
  Misc/NEWS.d/next/Build/2022-11-04-02-58-10.gh-issue-99086.DV_4Br.rst
  configure
  configure.ac
Labels: type-bug, awaiting merge, needs backport to 3.10, needs backport to 3.11

#99118 [3.11] gh-99086: Fix implicit int compiler warning in configure check for PTHREAD_SCOPE_SYSTEM (GH-99085)
  Misc/NEWS.d/next/Build/2022-11-04-02-58-10.gh-issue-99086.DV_4Br.rst
  configure
  configure.ac
Labels: type-bug, awaiting core review

#98300 gh-94808: Cover `PyEval_GetFuncDesc` function
  Lib/test/test_capi.py
  Modules/_testcapimodule.c
Labels: awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#99126 [3.11] gh-94808: add tests covering `PyEval_GetFuncDesc` function (GH-98300)
  Lib/test/test_capi.py
  Modules/_testcapimodule.c
Labels: awaiting merge, skip news, :robot: automerge

#98875 [3.11] gh-98706: Sync with importlib_metadata 4.13.0.
  Doc/library/importlib.metadata.rst
  Lib/importlib/metadata/__init__.py
  Lib/test/test_importlib/fixtures.py
  Lib/test/test_importlib/test_main.py
  Lib/test/test_importlib/test_metadata_api.py
  Misc/NEWS.d/next/Library/2022-10-30-12-22-24.gh-issue-98706.v1Kuy5.rst
Labels: awaiting merge, :robot: automerge

#97971 gh-98284: better error message for undefined abstractmethod
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Lib/test/test_abc.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2022-10-15-10-43-45.gh-issue-98284.SaVHTd.rst
  Objects/typeobject.c
Labels: awaiting merge

#99123 gh-94808: add tests covering `PySequence_{Set,Del}Slice`
  Lib/test/test_capi.py
  Modules/_testcapimodule.c
Labels: awaiting merge, skip news, needs backport to 3.11

#98809 gh-94808: add tests covering `PyFunction_GetKwDefaults` and `PyFunction_SetKwDefaults`
  Lib/test/test_capi.py
  Modules/_testcapimodule.c
Labels: tests, awaiting merge, skip news, needs backport to 3.11

#99133 [3.11] gh-94808: add tests covering `PySequence_{Set,Del}Slice` (GH-99123)
  Lib/test/test_capi.py
  Modules/_testcapimodule.c
Labels: awaiting merge, skip news, :robot: automerge

#99143 Fix typo "This it" -> "This is"
  Doc/tutorial/errors.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11

#99144 [3.11] [doc] fix typo (GH-99143)
  Doc/tutorial/errors.rst
Labels: docs, skip issue, awaiting merge, skip news, :robot: automerge

#99148 gh-93464: [Enum] fix auto() failure during multiple assignment
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2022-11-05-23-16-15.gh-issue-93464.ucd4vP.rst
Labels: type-bug, awaiting core review, stdlib, 3.11, 3.12

#99154 `test_typing`: use all pickle protocols
  Lib/test/test_typing.py
Labels: tests, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#99158 [3.10] `test_typing`: use all pickle protocols (GH-99154)
  Lib/test/test_typing.py
Labels: tests, skip issue, awaiting merge, skip news

#99157 [3.11] `test_typing`: use all pickle protocols (GH-99154)
  Lib/test/test_typing.py
Labels: tests, skip issue, awaiting merge, skip news

#99140 gh-99139: Improve NameError error suggestion for instances
  Doc/whatsnew/3.12.rst
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Core and Builtins/2022-11-05-18-36-27.gh-issue-99139.cI9vV1.rst
  Python/suggestions.c
Labels: awaiting merge

#99059 [3.11] gh-83004: Clean up refleak in _io initialisation (GH-98840)
  Misc/NEWS.d/next/Library/2022-11-02-05-52-36.gh-issue-83004.LBl79O.rst
  Modules/_io/_iomodule.c
Labels: awaiting merge

#98842 gh-83004: Clean up refleak in _zoneinfo initialisation
  Misc/NEWS.d/next/Library/2022-11-02-05-54-02.gh-issue-83004.0v8iyw.rst
  Modules/_zoneinfo.c
Labels: awaiting merge

#98841 gh-83004: Clean up refleak in _pickle initialisation
  Misc/NEWS.d/next/Library/2022-11-02-05-53-25.gh-issue-83004.qc_KHr.rst
  Modules/_pickle.c
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11

#99149 [3.11] gh-93464: [Enum] fix auto() failure during multiple assignment (GH-99148)
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2022-11-05-23-16-15.gh-issue-93464.ucd4vP.rst
Labels: type-bug, awaiting merge

#99163 [3.11] gh-83004: Clean up refleak in _zoneinfo initialisation (GH-98842)
  Misc/NEWS.d/next/Library/2022-11-02-05-54-02.gh-issue-83004.0v8iyw.rst
  Modules/_zoneinfo.c
Labels: awaiting merge

#99164 [3.10] gh-83004: Clean up refleak in _zoneinfo initialisation (GH-98842)
  Misc/NEWS.d/next/Library/2022-11-02-05-54-02.gh-issue-83004.0v8iyw.rst
  Modules/_zoneinfo.c
Labels: awaiting merge

#99165 [3.11] gh-83004: Clean up refleak in _pickle initialisation (GH-98841)
  Misc/NEWS.d/next/Library/2022-11-02-05-53-25.gh-issue-83004.qc_KHr.rst
  Modules/_pickle.c
Labels: awaiting merge

#99166 [3.10] gh-83004: Clean up refleak in _pickle initialisation (GH-98841)
  Misc/NEWS.d/next/Library/2022-11-02-05-53-25.gh-issue-83004.qc_KHr.rst
  Modules/_pickle.c
Labels: awaiting merge

#99160 gh-99153: set location on SyntaxError for try with both except and except*
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2022-11-06-13-25-01.gh-issue-99153.uE3CVL.rst
  Parser/parser.c
Labels: type-bug, awaiting merge, interpreter-core, needs backport to 3.11

#98194 Correct some typos in comments
  Modules/pyexpat.c
  Objects/longobject.c
Labels: skip issue, awaiting merge, skip news, :robot: automerge

#99084 GH-98831: Implement super-instruction generation
  Misc/NEWS.d/next/Build/2022-10-28-22-24-26.gh-issue-98831.IXRCRX.rst
  Python/bytecodes.c
  Python/generated_cases.c.h
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/parser.py
Labels: awaiting core review

#99052 gh-99051: remove duplicated test from `test_weakref`
  Lib/test/test_weakref.py
Labels: tests, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#99171 [3.10] gh-99051: remove duplicated test from `test_weakref` (GH-99052)
  Lib/test/test_weakref.py
Labels: tests, awaiting merge, skip news, :robot: automerge

#99170 [3.11] gh-99051: remove duplicated test from `test_weakref` (GH-99052)
  Lib/test/test_weakref.py
Labels: tests, awaiting merge, skip news, :robot: automerge

#98453 [Enum] add built-in property to test_test_simple_enum
  Lib/test/test_enum.py
Labels: tests, skip issue, awaiting core review, skip news

#7926 bpo-33964: IDLE macosx - removed unused local dict.
  Lib/idlelib/macosx.py
Labels: awaiting merge, skip news

#94297 gh-94286 Fix documentation of print default param
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#99174 [3.10] gh-94286 Fix documentation of print default param (GH-94297)
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news, :robot: automerge

#99173 [3.11] gh-94286 Fix documentation of print default param (GH-94297)
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news, :robot: automerge

#99119 [3.10] gh-99086: Fix implicit int compiler warning in configure check for PTHREAD_SCOPE_SYSTEM (GH-99085)
  Misc/NEWS.d/next/Build/2022-11-04-02-58-10.gh-issue-99086.DV_4Br.rst
  configure
  configure.ac
Labels: type-bug, awaiting core review

#98870 gh-98139: enhance namespace package repr
  Lib/importlib/_bootstrap.py
  Lib/test/test_importlib/test_namespace_pkgs.py
  Misc/NEWS.d/next/Library/2022-10-30-15-26-33.gh-issue-98139.qtm-9T.rst
Labels: awaiting merge

#99056 gh-98586: add whatsnew entry covering limited-API outgoing vector calls, related documentation fix
  Doc/c-api/call.rst
  Doc/whatsnew/3.12.rst
  Misc/NEWS.d/next/Core and Builtins/2022-10-24-10-30-30.gh-issue-98586.Tha5Iy.rst
Labels: docs, awaiting merge

#99179 [3.11] gh-96055: Update faulthandler to emit proper unexpect signal number (gh-99162)
  Misc/NEWS.d/next/Core and Builtins/2022-11-06-22-59-02.gh-issue-96055.TmQuJn.rst
  Modules/faulthandler.c
Labels: awaiting merge

#99178 [3.10] gh-96055: Update faulthandler to emit proper unexpect signal number (gh-99162)
  Misc/NEWS.d/next/Core and Builtins/2022-11-06-22-59-02.gh-issue-96055.TmQuJn.rst
  Modules/faulthandler.c
Labels: awaiting merge

#92213 gh-91803: Mock - fix error when using autospec methods with seal
  Lib/test/test_unittest/testmock/testsealable.py
  Lib/unittest/mock.py
  Misc/NEWS.d/next/Library/2022-05-03-11-32-29.gh-issue-91803.pI4Juv.rst
Labels: awaiting merge, stdlib

#31782 Remove new line in pickle error message
  Modules/_pickle.c
Labels: skip issue, awaiting merge, skip news

#99188 [3.11] GH-99155: Fix `NormalDist` pickle with `0` and `1` protocols (GH-99156).
  Lib/statistics.py
  Lib/test/test_statistics.py
  Misc/NEWS.d/next/Library/2022-11-06-12-44-51.gh-issue-99155.vLZOzi.rst
Labels: awaiting merge, :robot: automerge, needs backport to 3.10

#99168 [3.11] gh-99153: set location on SyntaxError for try with both except and except* (GH-99160)
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2022-11-06-13-25-01.gh-issue-99153.uE3CVL.rst
  Parser/parser.c
Labels: type-bug, awaiting merge

#99190 [3.10] [3.11] GH-99155: Fix `NormalDist` pickle with `0` and `1` protocols (GH-99156). (GH-99188)
  Lib/statistics.py
  Lib/test/test_statistics.py
  Misc/NEWS.d/next/Library/2022-11-06-12-44-51.gh-issue-99155.vLZOzi.rst
Labels: awaiting review

#22937 bpo-38523: ignore_dangling_symlinks does not apply recursively
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-10-23-22-20-52.bpo-38523.CrkxLh.rst
Labels: type-bug, awaiting merge, needs backport to 3.10, needs backport to 3.11

#99194 [3.10] bpo-38523: ignore_dangling_symlinks does not apply recursively (GH-22937)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-10-23-22-20-52.bpo-38523.CrkxLh.rst
Labels: type-bug, awaiting merge, :robot: automerge

#99193 [3.11] bpo-38523: ignore_dangling_symlinks does not apply recursively (GH-22937)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-10-23-22-20-52.bpo-38523.CrkxLh.rst
Labels: type-bug, awaiting merge, :robot: automerge

#99198 gh-91058: Add what's new entry for the improvement in commit 7cfbb49fcd4c85f9bab3797302eadf93df490344
  Doc/whatsnew/3.12.rst
Labels: docs, awaiting merge, skip news

#99197 gh-98254: Add what's new entry for the improvement in commit bb56dead336357153a0c3b8cc9d9d6856d2c5a03
  Doc/whatsnew/3.12.rst
Labels: docs, awaiting core review, skip news

#95390 gh-95389: socketmodule: expose popular `ETHERTYPE_*` constants
  Doc/library/socket.rst
  Misc/NEWS.d/next/Core and Builtins/2022-07-30-14-10-27.gh-issue-95389.nSGEkG.rst
  Modules/socketmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge
