Repository python/cpython, pull requests merged in 2022-02, with the labels that each got.

#30821 bpo-46482: add a test for `typing.Annotation.__new__`
  Lib/test/test_typing.py
Labels: type-tests, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#31032 bpo-46355: What's New: Note that PyFrameObject are private
  Doc/whatsnew/3.11.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news, :robot: automerge

#31045 [3.9] bpo-46482: add a test for `typing.Annotation.__new__` (GH-30821)
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, awaiting merge, skip news, :robot: automerge

#31044 [3.10] bpo-46482: add a test for `typing.Annotation.__new__` (GH-30821)
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, awaiting merge, skip news, :robot: automerge

#31014 bpo-44031: fix test_tabnanny failure in non-ascii CWD
  Lib/test/test_tabnanny.py
Labels: CLA signed, type-tests, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#31047 [3.10] bpo-44031: fix test_tabnanny failure in non-ascii CWD (GH-31014)
  Lib/test/test_tabnanny.py
Labels: CLA signed, type-tests, awaiting merge, skip news, :robot: automerge

#31048 [3.9] bpo-44031: fix test_tabnanny failure in non-ascii CWD (GH-31014)
  Lib/test/test_tabnanny.py
Labels: CLA signed, type-tests, awaiting merge, skip news, :robot: automerge

#31002 bpo-46564: do not create frame object for super object
  Misc/NEWS.d/next/Core and Builtins/2022-02-01-10-23-21.bpo-46564.6Xc2_H.rst
  Objects/typeobject.c
Labels: CLA signed, awaiting merge

#31052 bpo-46600: ./configure --with-pydebug uses -Og with clang
  Misc/NEWS.d/next/Build/2022-02-01-14-07-37.bpo-46600.NNLnfj.rst
  configure
  configure.ac
Labels: CLA signed, awaiting core review

#31024 bpo-46584: remove check for `py2.3` from `ctypes/test_python_api`
  Lib/ctypes/test/test_python_api.py
Labels: CLA signed, type-tests, awaiting merge, skip news, :robot: automerge

#31054 [3.10] bpo-46584: remove check for `py2.3` from `ctypes/test_python_api` (GH-31024)
  Lib/ctypes/test/test_python_api.py
Labels: CLA signed, type-tests, awaiting merge, skip news, :robot: automerge

#31053 [3.9] bpo-46584: remove check for `py2.3` from `ctypes/test_python_api` (GH-31024)
  Lib/ctypes/test/test_python_api.py
Labels: CLA signed, type-tests, awaiting merge, skip news, :robot: automerge

#31051 bpo-46072: Add some object layout stats
  Include/internal/pycore_code.h
  Objects/dictobject.c
  Objects/obmalloc.c
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: CLA signed, awaiting core review, skip news

#30921 bpo-45925: Update macOS installer to SQLite 3.37.2
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2022-01-26-12-04-09.bpo-45925.yBSiYO.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#30958 bpo-46487: Add `get_write_buffer_limits` to Write and _SSLProtocol transports
  Lib/asyncio/sslproto.py
  Lib/asyncio/transports.py
  Misc/NEWS.d/next/Library/2022-01-27-12-24-38.bpo-46487.UDkN2z.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#31038 bpo-45953: Preserve backward compatibility on some PyThreadState field names.
  Include/cpython/pystate.h
  Python/pystate.c
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#31058 bpo-46600: Fix test_gdb.test_pycfunction() for clang -Og
  Lib/test/test_gdb.py
  Misc/NEWS.d/next/Tests/2022-02-01-17-13-53.bpo-46600.FMCk8Z.rst
Labels: CLA signed, type-tests, awaiting core review

#31059 [3.9] bpo-45925: Update macOS installer to SQLite 3.37.2 (GH-30921) (GH-31057)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2022-01-26-12-04-09.bpo-45925.yBSiYO.rst
Labels: CLA signed, :robot: automerge

#31056 [3.9] bpo-46487: Add `get_write_buffer_limits` to Write and _SSLProtocol transports (GH-30958)
  Lib/asyncio/sslproto.py
  Lib/asyncio/transports.py
  Misc/NEWS.d/next/Library/2022-01-27-12-24-38.bpo-46487.UDkN2z.rst
Labels: CLA signed, awaiting merge

#31055 [3.10] bpo-46487: Add `get_write_buffer_limits` to Write and _SSLProtocol transports (GH-30958)
  Lib/asyncio/sslproto.py
  Lib/asyncio/transports.py
  Misc/NEWS.d/next/Library/2022-01-27-12-24-38.bpo-46487.UDkN2z.rst
Labels: CLA signed, awaiting merge

#31039 bpo-46528: Simplify `BUILD_TUPLE`/`UNPACK_SEQUENCE` folding
  Lib/test/test_peepholer.py
  Python/compile.c
Labels: CLA signed, awaiting merge, skip news

#31006 bpo-14916: use specified tokenizer fd for file input
  Misc/NEWS.d/next/C API/2020-09-11-02-50-41.bpo-14916.QN1Y03.rst
  Parser/tokenizer.c
Labels: CLA signed, awaiting merge, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#30251 bpo-46591: Make About IDLE doc link label clickable
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help_about.py
  Lib/idlelib/idle_test/htest.py
  Misc/NEWS.d/next/Library/2022-01-31-15-40-38.bpo-46591.prBD1M.rst
Labels: type-enhancement, CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#31067 [3.9] bpo-46591: Make About IDLE doc link label clickable (GH-30251)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help_about.py
  Lib/idlelib/idle_test/htest.py
  Misc/NEWS.d/next/Library/2022-01-31-15-40-38.bpo-46591.prBD1M.rst
Labels: type-enhancement, CLA signed, awaiting merge

#31069 bpo-44359: Fix test_ftplib unhandled thread exceptions
  Lib/test/test_ftplib.py
  Misc/NEWS.d/next/Tests/2022-02-02-02-24-04.bpo-44359.kPPSmN.rst
Labels: CLA signed, type-tests, awaiting core review, needs backport to 3.9, needs backport to 3.10

#31068 [3.10] bpo-46591: Make About IDLE doc link label clickable (GH-30251)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/help_about.py
  Lib/idlelib/idle_test/htest.py
  Misc/NEWS.d/next/Library/2022-01-31-15-40-38.bpo-46591.prBD1M.rst
Labels: type-enhancement, CLA signed, awaiting merge

#31070 [3.10] bpo-44359: Fix test_ftplib unhandled thread exceptions (GH-31069)
  Lib/test/test_ftplib.py
  Misc/NEWS.d/next/Tests/2022-02-02-02-24-04.bpo-44359.kPPSmN.rst
Labels: CLA signed, type-tests, awaiting merge

#31071 [3.9] bpo-44359: Fix test_ftplib unhandled thread exceptions (GH-31069)
  Lib/test/test_ftplib.py
  Misc/NEWS.d/next/Tests/2022-02-02-02-24-04.bpo-44359.kPPSmN.rst
Labels: CLA signed, type-tests, awaiting merge

#31062 bpo-46602: Do not append conftest.c
  Misc/NEWS.d/next/Build/2022-02-02-02-06-07.bpo-46602.8GaOZ2.rst
  configure
  configure.ac
Labels: CLA signed, awaiting review

#30646 bpo-46414: Add typing.reveal_type
  Doc/library/typing.rst
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-01-17-10-00-02.bpo-46414.Ld0b_y.rst
Labels: CLA signed, awaiting merge

#31029 Fix minor details in Counter docs
  Doc/library/collections.rst
  Lib/collections/__init__.py
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news, needs backport to 3.10

#31028 Add itertool recipe for subslices
  Doc/library/itertools.rst
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news, needs backport to 3.10

#31072 [3.10] Fix minor details in the Counter docs (GH-31029)
  Doc/library/collections.rst
  Lib/collections/__init__.py
Labels: CLA signed, type-documentation, skip issue, awaiting review, skip news

#31023 bpo-46583: remove unused `sys.version_info` check from `selectors`
  Lib/selectors.py
Labels: CLA signed, awaiting merge, skip news

#31049 bpo-46597: Remove Python 3.3 compatibility code from overlapped.c
  Modules/overlapped.c
Labels: CLA signed, awaiting merge, skip news

#31060 bpo-46072: Add some frame stats.
  Include/internal/pycore_code.h
  Objects/frameobject.c
  Python/ceval.c
  Python/frame.c
  Python/pystate.c
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: CLA signed, awaiting core review, skip news

#25701 bpo-43012: remove `pathlib._Accessor`
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2022-01-05-03-09-29.bpo-43012.RVhLIL.rst
Labels: CLA signed, awaiting merge, :robot: automerge, stale

#31076 [3.9] bpo-45703: Invalidate _NamespacePath cache on importlib.invalidate_cache (GH-29384) (GH-30922)
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_importlib/test_namespace_pkgs.py
  Misc/NEWS.d/next/Library/2021-11-03-13-41-49.bpo-45703.35AagL.rst
  Python/importlib_external.h
Labels: CLA signed, awaiting merge, :robot: automerge

#29991 bpo-45459: Add Py_buffer to limited API
  Doc/c-api/buffer.rst
  Doc/c-api/type.rst
  Doc/data/stable_abi.dat
  Doc/whatsnew/3.11.rst
  Include/Python.h
  Include/buffer.h
  Include/cpython/abstract.h
  Include/cpython/object.h
  Include/memoryobject.h
  Include/typeslots.h
  Lib/test/test_stable_abi_ctypes.py
  Lib/test/test_xxlimited.py
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2021-10-18-16-54-24.bpo-45459.Y1pEZs.rst
  Misc/stable_abi.txt
  Modules/xxlimited.c
  PC/python3dll.c
Labels: CLA signed, awaiting merge, :robot: automerge

#31079 bpo-46072: Add stats for FOR_ITER.
  Python/ceval.c
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: CLA signed, awaiting core review, skip news

#30696 bpo-46433: _PyType_GetModuleByDef: handle static types in MRO
  Lib/test/test_capi.py
  Misc/NEWS.d/next/C API/2022-01-19-16-51-54.bpo-46433.Er9ApS.rst
  Modules/_testmultiphase.c
  Modules/clinic/_testmultiphase.c.h
  Objects/typeobject.c
Labels: CLA signed, awaiting merge, :robot: automerge

#29724 bpo-37705: Remove orphaned PC/errmap.mak
  PC/errmap.mak
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#30952 bpo-45173: Keep configparser deprecations until Python 3.12
  Doc/library/configparser.rst
  Doc/whatsnew/3.11.rst
  Lib/configparser.py
  Lib/test/test_configparser.py
  Misc/NEWS.d/next/Library/2022-01-27-11-16-59.bpo-45173.wreRF2.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10

#31084 [3.10] bpo-45173: Note configparser deprecations will be removed in 3.12
  Lib/configparser.py
  Misc/NEWS.d/next/Library/2022-01-27-11-16-59.bpo-45173.wreRF2.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#31086 bpo-46616: Ensures test_importlib.test_windows cleans up registry keys after completion
  Lib/test/test_importlib/test_windows.py
  Misc/NEWS.d/next/Tests/2022-02-02-18-14-38.bpo-46616.URvBtE.rst
Labels: CLA signed, type-tests, OS-windows, awaiting core review, needs backport to 3.9, needs backport to 3.10

#31015 bpo-46576: bpo-46524: Disable compiler optimization within test_peg_generator.
  Misc/NEWS.d/next/Tests/2022-01-29-12-37-53.bpo-46576.-prRaV.rst
  Tools/peg_generator/pegen/build.py
Labels: CLA signed, type-tests, awaiting merge, needs backport to 3.9, needs backport to 3.10

#31088 [3.9] bpo-46616: Ensures test_importlib.test_windows cleans up registry keys after completion (GH-31086)
  Lib/test/test_importlib/test_windows.py
  Misc/NEWS.d/next/Tests/2022-02-02-18-14-38.bpo-46616.URvBtE.rst
Labels: CLA signed, type-tests, awaiting merge

#31087 [3.10] bpo-46616: Ensures test_importlib.test_windows cleans up registry keys after completion (GH-31086)
  Lib/test/test_importlib/test_windows.py
  Misc/NEWS.d/next/Tests/2022-02-02-18-14-38.bpo-46616.URvBtE.rst
Labels: CLA signed, type-tests, awaiting merge

#31083 bpo-45975: Use walrus operator for while loops in IDLE
  Lib/idlelib/idle_test/test_sidebar.py
  Lib/idlelib/pyparse.py
  Lib/idlelib/replace.py
  Lib/idlelib/run.py
  Lib/idlelib/sidebar.py
Labels: CLA signed, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#31091 [3.10] bpo-45975: Use walrus operator for some idlelib while loops (GH-31083)
  Lib/idlelib/idle_test/test_sidebar.py
  Lib/idlelib/pyparse.py
  Lib/idlelib/replace.py
  Lib/idlelib/run.py
  Lib/idlelib/sidebar.py
Labels: CLA signed, awaiting merge, skip news

#31092 [3.9] bpo-45975: Use walrus operator for some idlelib while loops [GH-31083]
  Lib/idlelib/pyparse.py
  Lib/idlelib/replace.py
  Lib/idlelib/run.py
Labels: CLA signed, awaiting core review, skip news

#31089 [3.10] bpo-46576: bpo-46524: Disable compiler optimization within test_peg_generator
  Misc/NEWS.d/next/Tests/2022-01-29-12-37-53.bpo-46576.-prRaV.rst
  Tools/peg_generator/pegen/build.py
Labels: CLA signed, type-tests, awaiting merge, needs backport to 3.9

#31093 [3.9] [3.10] bpo-46576: bpo-46524: Disable compiler optimization within test_peg_generator. (GH-31015) (GH-31089)
  Misc/NEWS.d/next/Tests/2022-01-29-12-37-53.bpo-46576.-prRaV.rst
  Tools/peg_generator/pegen/build.py
Labels: CLA signed, type-tests, awaiting merge, :robot: automerge

#31094 bpo-45629: Improve test.support.skip_if_buildbot
  Lib/test/support/__init__.py
Labels: type-bugfix, CLA signed, type-tests, awaiting core review, skip news

#31095 [3.10] Backport itertools recipe for subslices
  Doc/library/itertools.rst
Labels: CLA signed, type-documentation, skip issue, awaiting core review, skip news

#31090 bpo-43478: Restrict use of Mock objects as specs
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Lib/unittest/test/testmock/testwith.py
  Misc/NEWS.d/next/Tests/2022-02-03-00-21-32.bpo-43478.0nfcam.rst
Labels: type-bugfix, type-enhancement, CLA signed, awaiting merge

#30993 bpo-46565: `del` loop vars that are leaking into module namespaces
  Lib/_compat_pickle.py
  Lib/email/contentmanager.py
  Lib/email/quoprimime.py
  Lib/http/cookiejar.py
  Lib/inspect.py
  Lib/json/encoder.py
  Lib/lib2to3/pgen2/grammar.py
  Lib/locale.py
  Lib/multiprocessing/managers.py
  Lib/multiprocessing/process.py
  Lib/sysconfig.py
  Lib/test/test_inspect.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Library/2022-01-28-19-48-31.bpo-46565.bpZXO4.rst
Labels: CLA signed, awaiting merge

#30848 bpo-46483: remove `__class_getitem__` from `pathlib.PurePath`
  Doc/whatsnew/3.11.rst
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2022-01-23-11-17-48.bpo-46483.j7qwWb.rst
  Misc/NEWS.d/next/Library/2022-01-24-13-00-09.bpo-46483.9XnmKp.rst
Labels: CLA signed, awaiting merge

#31031 bpo-44977: Deprecate delegation of int to __trunc__
  Doc/library/functions.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.11.rst
  Lib/test/test_descr.py
  Lib/test/test_int.py
  Lib/test/test_long.py
  Misc/NEWS.d/next/Core and Builtins/2022-01-30-18-23-08.bpo-44977.BQV_zS.rst
  Objects/abstract.c
Labels: CLA signed, awaiting merge

#31066 bpo-45773: Remove invalid peephole optimizations
  Misc/NEWS.d/next/Core and Builtins/2022-02-01-14-30-56.bpo-45773.Up77LD.rst
  Python/compile.c
Labels: type-bugfix, CLA signed, awaiting core review, needs backport to 3.10

#31040 bpo-45885: Add more stats for COMPARE_OP in specialize.c
  Misc/NEWS.d/next/Core and Builtins/2022-02-01-01-17-28.bpo-45885.CjyNf_.rst
  Python/specialize.c
Labels: CLA signed, awaiting changes

#31098 bpo-46624: Revert "Remove deprecated support for non-integer values"
  Doc/library/random.rst
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2022-02-03-12-07-41.bpo-46624.f_Qqh0.rst
Labels: CLA signed, awaiting review

#31007 bpo-46569: fix typo in `StrEnum` docs
  Doc/library/enum.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#30701 bpo-46436: Fix command-line option -d/--directory in module http.server
  Lib/http/server.py
  Misc/NEWS.d/next/Library/2022-01-23-19-37-00.bpo-46436.Biz1p9.rst
Labels: CLA signed, awaiting merge, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#31100 Pass reference to func, as well as args, when pushing frame.
  Include/internal/pycore_frame.h
  Objects/frameobject.c
  Python/ceval.c
  Python/frame.c
  Python/pystate.c
Labels: CLA signed, skip issue, awaiting core review, skip news

#31105 bpo-46072: Collect stats for UNPACK_SEQUENCE.
  Python/ceval.c
  Python/specialize.c
Labels: CLA signed, awaiting core review, skip news

#31106 closes bpo-46626: Expose IP_BIND_ADDRESS_NO_PORT socket option.
  Misc/NEWS.d/next/Library/2022-02-03-10-22-42.bpo-46626.r2e-n_.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting core review

#31107 bpo-45975: IDLE - Remove extraneous parens
  Lib/idlelib/pyparse.py
  Lib/idlelib/replace.py
  Lib/idlelib/run.py
Labels: CLA signed, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#31109 [3.10] bpo-45975: IDLE - Remove extraneous parens (GH-31107)
  Lib/idlelib/pyparse.py
  Lib/idlelib/replace.py
  Lib/idlelib/run.py
Labels: CLA signed, awaiting merge, skip news

#31110 [3.9] bpo-45975: IDLE - Remove extraneous parens (GH-31107)
  Lib/idlelib/pyparse.py
  Lib/idlelib/replace.py
  Lib/idlelib/run.py
Labels: CLA signed, awaiting merge, skip news

#31112 bpo-46630: Fix initial focus of IDLE query dialogs
  Lib/idlelib/NEWS.txt
  Lib/idlelib/query.py
  Misc/NEWS.d/next/IDLE/2022-02-03-15-47-53.bpo-46630.tREOjo.rst
Labels: type-bugfix, CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#31115 [3.9] bpo-46630: Fix initial focus of IDLE query dialogs (GH-31112)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/query.py
  Misc/NEWS.d/next/IDLE/2022-02-03-15-47-53.bpo-46630.tREOjo.rst
Labels: type-bugfix, CLA signed, awaiting merge

#31114 [3.10] bpo-46630: Fix initial focus of IDLE query dialogs (GH-31112)
  Lib/idlelib/NEWS.txt
  Lib/idlelib/query.py
  Misc/NEWS.d/next/IDLE/2022-02-03-15-47-53.bpo-46630.tREOjo.rst
Labels: type-bugfix, CLA signed, awaiting merge

#31065 [3.10] bpo-14916: use specified tokenizer fd for file input (GH-31006)
  Misc/NEWS.d/next/C API/2020-09-11-02-50-41.bpo-14916.QN1Y03.rst
  Parser/tokenizer.c
Labels: CLA signed, awaiting merge

#31119 bpo-46588: fix typo in test_calltip.py
  Lib/idlelib/idle_test/test_calltip.py
Labels: CLA signed, type-tests, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#31122 [3.9] bpo-46588: fix typo in test_calltip.py (GH-31119)
  Lib/idlelib/idle_test/test_calltip.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#31121 [3.10] bpo-46588: fix typo in test_calltip.py (GH-31119)
  Lib/idlelib/idle_test/test_calltip.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#21348 Optimized Images in repo
  Doc/howto/logging_flow.png
  Doc/library/hashlib-blake2-tree.png
  Doc/library/pathlib-inheritance.svg
  Doc/library/tk_msg.png
  Doc/using/win_installer.png
  Lib/idlelib/Icons/idle_16.gif
  Lib/idlelib/Icons/idle_16.png
  Lib/idlelib/Icons/idle_256.png
  Lib/idlelib/Icons/idle_32.gif
  Lib/idlelib/Icons/idle_32.png
  Lib/idlelib/Icons/idle_48.png
  Lib/idlelib/Icons/minusnode.gif
  Lib/idlelib/Icons/plusnode.gif
  Lib/idlelib/Icons/python.gif
  Lib/idlelib/Icons/tk.gif
  Lib/test/imghdrdata/python.gif
  Lib/test/test_email/data/PyBanner048.gif
  PC/icons/logox128.png
  PC/icons/py.png
  PC/icons/pythonwx150.png
  PC/icons/pythonwx44.png
  PC/icons/pythonx150.png
  PC/icons/pythonx44.png
  PC/icons/pythonx50.png
  Tools/msi/bundle/SideBar.png
Labels: CLA not signed, skip issue, awaiting core review, skip news, needs backport to 3.9

#31123 [3.9] Optimize images by IMGbot (GH-21348)
  Doc/howto/logging_flow.png
  Doc/library/hashlib-blake2-tree.png
  Doc/library/pathlib-inheritance.svg
  Doc/library/tk_msg.png
  Doc/using/win_installer.png
  Lib/idlelib/Icons/idle_16.gif
  Lib/idlelib/Icons/idle_16.png
  Lib/idlelib/Icons/idle_256.png
  Lib/idlelib/Icons/idle_32.gif
  Lib/idlelib/Icons/idle_32.png
  Lib/idlelib/Icons/idle_48.png
  Lib/idlelib/Icons/minusnode.gif
  Lib/idlelib/Icons/plusnode.gif
  Lib/idlelib/Icons/python.gif
  Lib/idlelib/Icons/tk.gif
  Lib/test/imghdrdata/python.gif
  Lib/test/test_email/data/PyBanner048.gif
  PC/icons/logox128.png
  PC/icons/py.png
  PC/icons/pythonwx150.png
  PC/icons/pythonwx44.png
  PC/icons/pythonx150.png
  PC/icons/pythonx44.png
  PC/icons/pythonx50.png
  Tools/msi/bundle/SideBar.png
Labels: CLA signed, skip issue, awaiting merge, skip news

#31124 [3.10] Optimize images by IMGbot (GH-21348)
  Doc/howto/logging_flow.png
  Doc/library/hashlib-blake2-tree.png
  Doc/library/pathlib-inheritance.svg
  Doc/library/tk_msg.png
  Doc/using/win_installer.png
  Lib/idlelib/Icons/idle_16.gif
  Lib/idlelib/Icons/idle_16.png
  Lib/idlelib/Icons/idle_256.png
  Lib/idlelib/Icons/idle_32.gif
  Lib/idlelib/Icons/idle_32.png
  Lib/idlelib/Icons/idle_48.png
  Lib/idlelib/Icons/minusnode.gif
  Lib/idlelib/Icons/plusnode.gif
  Lib/idlelib/Icons/python.gif
  Lib/idlelib/Icons/tk.gif
  Lib/test/imghdrdata/python.gif
  Lib/test/test_email/data/PyBanner048.gif
  PC/icons/logox128.png
  PC/icons/py.png
  PC/icons/pythonwx150.png
  PC/icons/pythonwx44.png
  PC/icons/pythonx150.png
  PC/icons/pythonx44.png
  PC/icons/pythonx50.png
  Tools/msi/bundle/SideBar.png
Labels: CLA signed, skip issue, awaiting merge, skip news

#31108 bpo-46072: Add per-instruction miss stats.
  Python/ceval.c
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: CLA signed, awaiting core review, skip news

#31111 bpo-46629: Update classicAppCompat.sccd for new signing certificate
  PC/classicAppCompat.can.xml
  PC/classicAppCompat.sccd
Labels: CLA signed, OS-windows, awaiting core review, skip news, DO-NOT-MERGE, needs backport to 3.9, needs backport to 3.10

#31128 [3.10] bpo-46629: Update classicAppCompat.sccd for new signing certificate (GH-31111)
  PC/classicAppCompat.can.xml
  PC/classicAppCompat.sccd
Labels: CLA signed, awaiting merge, skip news

#31129 [3.9] bpo-46629: Update classicAppCompat.sccd for new signing certificate (GH-31111)
  PC/classicAppCompat.can.xml
  PC/classicAppCompat.sccd
Labels: CLA signed, awaiting merge, skip news

#31074 bpo-46608: exclude marshalled-frozen data if deep-freezing to save 300 KB space
  Doc/c-api/import.rst
  Doc/whatsnew/3.11.rst
  Include/cpython/import.h
  Lib/ctypes/test/test_values.py
  Misc/NEWS.d/next/Build/2022-02-02-11-26-46.bpo-46608.cXH9po.rst
  Python/frozen.c
  Python/import.c
  Tools/freeze/makefreeze.py
  Tools/scripts/freeze_modules.py
Labels: CLA signed, awaiting merge, :robot: automerge

#31132 [3.10] bpo-46609: Update asyncio-task coroutine doc
  Doc/library/asyncio-task.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news, needs backport to 3.9

#31133 [3.9] bpo-46609: Update asyncio-task coroutine doc (GH-31132)
  Doc/library/asyncio-task.rst
Labels: CLA signed, type-documentation, awaiting merge, skip news

#30279 bpo-31369: include RegexFlag in re.__all__
  Doc/library/re.rst
  Lib/re.py
  Misc/NEWS.d/next/Library/2021-12-27-18-28-44.bpo-31369.b9yM94.rst
Labels: CLA signed, awaiting merge

#31135 typing.py: Fix __init_subclass__ using self instead of class
  Lib/typing.py
Labels: CLA signed, skip issue, awaiting merge, skip news

#31131 bpo-46608: Fix argument parsing in freeze_modules.py
  Tools/scripts/freeze_modules.py
Labels: CLA signed, awaiting merge, skip news

#31050 bpo-40280: Address more test failures on Emscripten (GH-31050)
  Lib/test/support/__init__.py
  Lib/test/support/os_helper.py
  Lib/test/test_builtin.py
  Lib/test/test_capi.py
  Lib/test/test_faulthandler.py
  Lib/test/test_fileio.py
  Lib/test/test_genericalias.py
  Lib/test/test_getpass.py
  Lib/test/test_inspect.py
  Lib/test/test_interpreters.py
  Lib/test/test_io.py
  Lib/test/test_os.py
  Lib/test/test_posix.py
  Lib/test/test_pwd.py
  Lib/test/test_pyexpat.py
  Lib/test/test_resource.py
  Lib/test/test_zipfile.py
  Misc/NEWS.d/next/Build/2022-01-31-15-15-08.bpo-40280.r1AYNW.rst
  Modules/clinic/resource.c.h
  Modules/posixmodule.c
  Modules/resource.c
  Modules/timemodule.c
  Tools/wasm/README.md
  Tools/wasm/config.site-wasm32-emscripten
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting merge

#31145 Allows to specify the port on which serve documentation
  Doc/Makefile
Labels: CLA signed, skip issue, awaiting review, skip news

#31134 bpo-46640: Py_NAN now uses the C99 NAN constant
  Doc/whatsnew/3.11.rst
  Include/pymath.h
  Misc/NEWS.d/next/Build/2022-02-04-21-26-50.bpo-46640.HXUmQp.rst
Labels: CLA signed, awaiting merge

#31157 Doc: enhance readability by avoiding big blocks for small numbers.
  Doc/tutorial/floatingpoint.rst
Labels: CLA signed, type-documentation, skip issue, awaiting merge, skip news

#30338 bpo-23952: Document cgi module's maxlen variable
  Doc/library/cgi.rst
  Lib/cgi.py
Labels: CLA signed, type-documentation, awaiting merge, skip news

#31161 bpo-46648: Skip test_urllib2.test_issue16464()
  Lib/test/test_urllib2.py
Labels: CLA signed, type-tests, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#31163 [3.9] bpo-46648: Skip test_urllib2.test_issue16464() (GH-31161)
  Lib/test/test_urllib2.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#31162 [3.10] bpo-46648: Skip test_urllib2.test_issue16464() (GH-31161)
  Lib/test/test_urllib2.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#31170 Add more tests for variable substitution in generics
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, skip issue, awaiting core review, skip news, needs backport to 3.10

#31172 [3.10] Add more tests for variable substitution in generics (GH-31170)
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, skip issue, awaiting merge, skip news

#31168 bpo-46659: Update the test on the mbcs codec alias
  Lib/encodings/__init__.py
  Lib/test/test_codecs.py
  Lib/test/test_site.py
Labels: CLA signed, type-tests, awaiting core review, skip news

#31167 bpo-46659: test.support avoids locale.getdefaultlocale()
  Lib/test/support/__init__.py
Labels: CLA signed, awaiting core review, skip news

#31156 bpo-46655: allow stringized TypeAlias with get_type_hints
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-02-06-08-54-03.bpo-46655.DiLzYv.rst
Labels: CLA signed, awaiting core review

#31177 bpo-46670: Remove unused get_frame_state() function
  Objects/frameobject.c
Labels: CLA signed, skip news

#31176 bpo-46670: Define all macros for stringlib
  Objects/bytearrayobject.c
  Objects/bytesobject.c
  Objects/stringlib/asciilib.h
  Objects/stringlib/join.h
  Objects/stringlib/split.h
  Objects/stringlib/ucs1lib.h
  Objects/stringlib/ucs2lib.h
  Objects/stringlib/ucs4lib.h
  Objects/stringlib/undef.h
  Objects/stringlib/unicodedefs.h
Labels: CLA signed, awaiting core review, skip news

#31178 bpo-46670: Test if a macro is defined, not its value
  Modules/_ctypes/callbacks.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/ctypes.h
  Modules/_ctypes/malloc_closure.c
  Modules/audioop.c
  Objects/unicodeobject.c
  Python/pytime.c
Labels: CLA signed, awaiting core review, skip news

#31078 bpo-46611: add coverage to instance and class checks in `typing.py`
  Lib/test/test_types.py
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, awaiting merge, skip news, needs backport to 3.10

#31026 bpo-46589: Improve documentation for typing._GenericAlias
  Lib/typing.py
Labels: CLA signed, awaiting merge, skip news

#31183 [3.10] bpo-40479: Fix undefined behavior in Modules/_hashopenssl.c (GH-31153)
  Misc/NEWS.d/next/Core and Builtins/2022-02-06-23-08-30.bpo-40479.zED3Zu.rst
  Modules/_hashopenssl.c
Labels: CLA signed, awaiting merge, :robot: automerge

#31184 [3.9] bpo-40479: Fix undefined behavior in Modules/_hashopenssl.c (GH-31153)
  Misc/NEWS.d/next/Core and Builtins/2022-02-06-23-08-30.bpo-40479.zED3Zu.rst
  Modules/_hashopenssl.c
Labels: CLA signed, awaiting merge, :robot: automerge

#31182 [3.10] bpo-46611: add coverage to instance and class checks in `typing.py` (GH-31078)
  Lib/test/test_types.py
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#31186 bpo-46648: move `test_issue16464` to `urllib2_localnet`
  Lib/test/test_urllib2.py
  Lib/test/test_urllib2_localnet.py
Labels: CLA signed, type-tests, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#31190 [3.9] bpo-46648: Rewrite test_urllib2.test_issue16464() with a local HTTP server (GH-31186)
  Lib/test/test_urllib2.py
  Lib/test/test_urllib2_localnet.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#31188 bpo-46323: _ctypes.CFuncPtr fails if _argtypes_ is too long
  Lib/ctypes/__init__.py
  Lib/ctypes/test/test_callbacks.py
  Misc/NEWS.d/next/Library/2022-02-07-13-27-59.bpo-46323.7UENAj.rst
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/ctypes.h
Labels: CLA signed, awaiting core review

#31104 bpo-46072: Improve LOAD_METHOD stats
  Python/specialize.c
Labels: CLA signed, awaiting core review, skip news

#31196 bpo-46670: Remove unused macros in ceval.c
  Python/ceval.c
Labels: CLA signed, awaiting core review, skip news

#31195 bpo-39277: Fix PY_TIMEOUT_MAX cast in _threadmodule.c
  Modules/_threadmodule.c
Labels: CLA signed, awaiting core review, skip news

#31194 bpo-46670: Remove unused macros in the Modules directory
  Modules/_ctypes/stgdict.c
  Modules/_ssl.c
  Modules/_struct.c
  Modules/_testcapimodule.c
  Modules/_tkinter.c
  Modules/pwdmodule.c
Labels: CLA signed, awaiting core review, skip news

#31193 bpo-46670: Remove unused macros in the Objects directory
  Objects/dictobject.c
  Objects/memoryobject.c
  Objects/obmalloc.c
  Objects/unicodectype.c
Labels: CLA signed, awaiting core review, skip news

#31192 bpo-46670: Remove unused macros in the Python directory
  Python/ast_opt.c
  Python/compile.c
  Python/import.c
  Python/thread.c
Labels: CLA signed, awaiting core review, skip news

#31180 bpo-46670: Fix #ifdef in sha3module.c
  Modules/_sha3/sha3module.c
Labels: CLA signed, awaiting core review, skip news

#31175 [3.10] bpo-46655: allow stringized TypeAlias with get_type_hints (GH-…
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-02-06-08-54-03.bpo-46655.DiLzYv.rst
Labels: CLA signed, awaiting merge

#31198 bpo-46166: Fix compiler warnings in What's New in Python 3.11
  Doc/whatsnew/3.11.rst
Labels: CLA signed, type-documentation, awaiting core review, skip news

#31197 bpo-46072: Merge dxpairs into py_stats.
  Misc/NEWS.d/next/Core and Builtins/2022-02-07-14-38-54.bpo-46072.6ebLyN.rst
  Python/ceval.c
  Python/sysmodule.c
Labels: CLA signed, awaiting core review

#31200 [3.9] bpo-46638: Makes registry virtualisation setting stable when building MSIX packages (GH-31130)
  Misc/NEWS.d/next/Windows/2022-02-04-18-02-33.bpo-46638.mSJOSX.rst
  PC/layout/support/appxmanifest.py
  PC/layout/support/constants.py
Labels: CLA signed, awaiting merge

#30748 GitHub Actions: Skip cron workflow for forks
  .github/workflows/stale.yml
Labels: CLA signed, skip issue, awaiting merge, skip news

#31189 [3.10] bpo-46648: Rewrite test_urllib2.test_issue16464() with a local HTTP server (GH-31186)
  Lib/test/test_urllib2.py
  Lib/test/test_urllib2_localnet.py
Labels: CLA signed, type-tests, awaiting merge, skip news, :robot: automerge

#30924 bpo-46534: Implement PEP 673 Self in typing.py
  Doc/library/typing.rst
  Doc/whatsnew/3.11.rst
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-01-26-18-06-08.bpo-46534.vhzUM4.rst
Labels: CLA signed, awaiting merge

#31166 bpo-46659: calendar uses locale.getlocale()
  Doc/library/calendar.rst
  Doc/whatsnew/3.11.rst
  Lib/calendar.py
  Lib/test/test_calendar.py
  Misc/NEWS.d/next/Library/2022-02-06-19-13-02.bpo-46659.q-vNL9.rst
Labels: CLA signed, awaiting merge

#31204 bpo-46678: Fix Invalid cross device link in Lib/test/support/import_helper.py
  Lib/test/support/import_helper.py
  Misc/NEWS.d/next/Tests/2022-02-07-12-40-45.bpo-46678.zfOrgL.rst
Labels: CLA signed, awaiting merge, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#31209 bpo-46323 Fix ref leak if ctypes.CFuncPtr raises an error.
  Modules/_ctypes/_ctypes.c
Labels: CLA signed, skip news

#31203 bpo-46676: Make ParamSpec args and kwargs equal to themselves
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-02-07-19-20-42.bpo-46676.3Aws1o.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10

#31173 [3.8] bpo-46648: Skip test_urllib2.test_issue16464() (GH-31161)
  Lib/test/test_urllib2.py
Labels: CLA signed, type-tests, awaiting review, skip news

#31211 bpo-46072: Print summary stats for overall success of specialization.
  Tools/scripts/summarize_stats.py
Labels: CLA signed, awaiting core review, skip news

#31191 bpo-46675: Allow object value arrays and split key dictionaries larger than 16
  Include/internal/pycore_dict.h
  Lib/test/test_descr.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2022-02-07-14-33-45.bpo-46675.ZPbdMp.rst
  Objects/dictobject.c
  Python/ceval.c
Labels: CLA signed, awaiting core review

#31010 bpo-46521: Fix codeop to use a new partial-input mode of the parser
  Include/cpython/compile.h
  Include/errcode.h
  Lib/codeop.py
  Misc/NEWS.d/next/Library/2022-02-01-19-34-28.bpo-46521.IMUIrs.rst
  Parser/pegen.c
  Parser/pegen.h
  Parser/tokenizer.c
Labels: CLA signed, awaiting core review

#31213 [3.10] bpo-46521: Fix codeop to use a new partial-input mode of the parser (GH-31010)
  Include/cpython/compile.h
  Include/errcode.h
  Lib/codeop.py
  Misc/NEWS.d/next/Library/2022-02-01-19-34-28.bpo-46521.IMUIrs.rst
  Parser/pegen.c
  Parser/pegen.h
  Parser/tokenizer.c
Labels: CLA signed, awaiting core review

#31138 bpo-46323: Use PyObject_Vectorcall while calling ctypes callback function
  Misc/NEWS.d/next/Core and Builtins/2022-02-05-14-46-21.bpo-46323.FC1OJg.rst
  Modules/_ctypes/callbacks.c
Labels: CLA signed, type-performance, awaiting merge

#31219 bpo-45952: Get the C analyzer tool working again.
  Tools/c-analyzer/cpython/_parser.py
Labels: CLA signed, awaiting core review, skip news

#30842 bpo-46475: Add typing.Never and typing.assert_never
  Doc/library/typing.rst
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-01-23-15-35-07.bpo-46475.UCe18S.rst
Labels: CLA signed, awaiting merge

#31220 bpo-45952: Get the C analyzer tool working again.
  Tools/c-analyzer/cpython/_parser.py
Labels: CLA signed, awaiting core review, skip news

#30971 bpo-46556: emit `DeprecationWarning` from `pathlib.Path.__enter__()`
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2022-01-27-23-20-30.bpo-46556.tlpAgS.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#31207 [3.10] bpo-46678: Fix Invalid cross device link in Lib/test/support/import_helper.py (GH-31204)
  Lib/test/support/import_helper.py
  Misc/NEWS.d/next/Tests/2022-02-07-12-40-45.bpo-46678.zfOrgL.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#31225 bpo-36876: Update the c-analyzer whitelist.
  Tools/c-analyzer/cpython/_analyzer.py
  Tools/c-analyzer/cpython/globals-to-fix.tsv
  Tools/c-analyzer/cpython/ignored.tsv
  Tools/c-analyzer/table-file.py
Labels: CLA signed, awaiting core review, skip news

#31228 bpo-46072: Output stats as markdown with collapsible sections.
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: CLA signed, awaiting core review, skip news

#31223 bpo-46685: cover `TypeError` of `ForwardRef(1)` in `test_typing`
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#31229 [3.10] bpo-46685: cover `TypeError` of `ForwardRef(1)` in `test_typing` (GH-31223)
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#31230 [3.9] bpo-46685: cover `TypeError` of `ForwardRef(1)` in `test_typing` (GH-31223)
  Lib/test/test_typing.py
Labels: CLA signed, type-tests, awaiting merge, skip news

#26488 bpo-44289: Keep argument file object's current position in tarfile.is_tarfile
  Lib/tarfile.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Library/2021-06-02-19-47-46.bpo-44289.xC5kuV.rst
Labels: CLA signed, awaiting merge

#30683 bpo-46430: Intern strings in deep-frozen modules
  Include/internal/pycore_code.h
  Misc/NEWS.d/next/Build/2022-01-19-11-08-32.bpo-46430.k403m_.rst
  Objects/codeobject.c
  Tools/scripts/deepfreeze.py
Labels: CLA signed, awaiting merge
