Repository python/cpython, pull requests merged in 2022-04, with the labels that each got.

#32197 bpo-47167: Allow overriding a future compliance check in asyncio.Task
  Doc/library/asyncio-extending.rst
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2022-03-30-18-35-50.bpo-47167.nCNHsB.rst
  Modules/_asynciomodule.c
  Modules/clinic/_asynciomodule.c.h
Labels: CLA signed, awaiting core review

#32052 bpo-46850: Move _PyEval_EvalFrameDefault() to internal C API
  Doc/whatsnew/3.11.rst
  Include/cpython/ceval.h
  Include/internal/pycore_ceval.h
  Misc/NEWS.d/next/C API/2022-03-22-16-48-02.bpo-46850.7M5dO7.rst
Labels: CLA signed

#32216 [3.10] bpo-47182: Fix crash by named unicode characters after interpreter reinitialization (GH-32212) (GH-32216)
  Misc/NEWS.d/next/Core and Builtins/2022-03-31-15-37-02.bpo-47182.e_4SsC.rst
  Objects/unicodeobject.c
Labels: CLA signed, awaiting core review

#32054 bpo-46850: Move _PyInterpreterState_SetEvalFrameFunc() to internal C API
  Doc/c-api/init.rst
  Doc/whatsnew/3.11.rst
  Include/cpython/pystate.h
  Include/internal/pycore_interp.h
  Include/internal/pycore_pystate.h
  Misc/NEWS.d/next/C API/2022-03-22-16-59-34.bpo-46850.lmEKLy.rst
Labels: CLA signed, awaiting core review

#31864 bpo-47009: Streamline list.append for the common case
  Include/internal/pycore_list.h
  Misc/NEWS.d/next/Core and Builtins/2022-03-14-09-45-10.bpo-47009.ZI05b5.rst
  Objects/listobject.c
  Python/ceval.c
Labels: CLA signed, performance, awaiting core review

#32222 bpo-46841: Avoid unnecessary allocations in code object comparisons
  Misc/NEWS.d/next/Core and Builtins/2022-03-31-15-57-42.bpo-46841.U-25Z6.rst
  Objects/codeobject.c
Labels: CLA signed, awaiting core review

#32205 bpo-46841: Use a `bytes` object for `_co_code_adaptive`
  Objects/codeobject.c
Labels: type-bug, CLA signed, awaiting core review, skip news

#32231 bpo-47186: Replace JUMP_IF_NOT_EXC_MATCH by CHECK_EXC_MATCH + jump
  Doc/library/dis.rst
  Doc/whatsnew/3.11.rst
  Include/opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2022-04-01-11-53-59.bpo-47186.RBCPk8.rst
  Objects/frameobject.c
  Python/ceval.c
  Python/compile.c
  Python/opcode_targets.h
Labels: CLA signed, awaiting core review

#32195 bpo-47168: Mark files generated by `make regen-limited-abi` as generated
  .gitattributes
Labels: CLA signed, awaiting core review, skip news

#32234 bpo-46023: makesetup: skip all duplicate modules (GH-32234)
  Misc/NEWS.d/next/Build/2022-04-01-16-12-53.bpo-46023.1Z1OcC.rst
  Modules/makesetup
Labels: CLA signed, awaiting core review

#32233 bpo-40280: Add debug Emscripten flavors (GH-32233)
  configure
  configure.ac
Labels: CLA signed, awaiting core review, skip news

#32037 bpo-47089: Avoid test_compileall failures on Windows
  Lib/test/test_compileall.py
Labels: CLA signed, tests, awaiting review, skip news, needs backport to 3.9, needs backport to 3.10

#32224 bpo-40280: Emscripten fork_exec now fails early (GH-32224)
  Lib/subprocess.py
  Lib/test/test_subprocess.py
  configure
  configure.ac
Labels: CLA signed, awaiting merge, skip news

#32237 [3.10] bpo-47089: Avoid test_compileall failures on Windows (GH-32037)
  Lib/test/test_compileall.py
Labels: CLA signed, tests, awaiting merge, skip news

#32236 no-issue: Add assertion to PyModule_GetName for understanding
  Objects/moduleobject.c
Labels: CLA signed, skip issue, skip news

#32240 [3.9] bpo-47089: Avoid test_compileall failures on Windows (GH-32037).
  Lib/test/test_compileall.py
Labels: CLA signed, tests, awaiting review, skip news

#32132 bpo-47131: Speedup AST comparisons in test_unparse by using node traversal
  Lib/test/test_unparse.py
Labels: CLA signed, tests, awaiting changes, skip news

#32244 bpo-47196: Fix function pointer cast in test_imp
  Modules/_testmultiphase.c
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#32243 bpo-40280: Detect if WASM platform supports threading
  Lib/test/libregrtest/runtest.py
  Lib/test/support/threading_helper.py
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#32238 bpo-40280: Enable most file-at() and nanosleep APIs again (GH-32238)
  Lib/test/test_os.py
  Tools/wasm/config.site-wasm32-emscripten
Labels: CLA signed, awaiting core review, skip news

#32177 bpo-47152: Convert the re module into a package
  Doc/library/modulefinder.rst
  Doc/library/profile.rst
  Doc/whatsnew/3.11.rst
  Lib/re/__init__.py
  Lib/re/_compiler.py
  Lib/re/_constants.py
  Lib/re/_parser.py
  Lib/sre_compile.py
  Lib/sre_constants.py
  Lib/sre_parse.py
  Lib/test/test_pyclbr.py
  Lib/test/test_re.py
  Lib/test/test_site.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2022-03-29-19-14-53.bpo-47152.5rl5ZK.rst
  Modules/sre_constants.h
Labels: CLA signed, awaiting core review

#32220 [doc] fix superfluous backtick in front of role.
  Doc/whatsnew/3.11.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news, :robot: automerge

#32241 bpo-47194: Update zlib on Windows
  Misc/NEWS.d/next/Windows/2022-04-01-14-57-40.bpo-47194.IB0XL4.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, type-security, OS-windows, awaiting merge, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, dependencies, needs backport to 3.10

#32249 [3.9] bpo-47194: Update zlib to v1.2.12 on Windows to resolve CVE-2018-25032 (GH-32241)
  Misc/NEWS.d/next/Windows/2022-04-01-14-57-40.bpo-47194.IB0XL4.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, type-security, awaiting merge

#32248 [3.10] bpo-47194: Update zlib to v1.2.12 on Windows to resolve CVE-2018-25032 (GH-32241)
  Misc/NEWS.d/next/Windows/2022-04-01-14-57-40.bpo-47194.IB0XL4.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, type-security, awaiting merge

#31525 More minor fixes to C API docs
  Doc/c-api/init.rst
  Doc/c-api/iter.rst
  Doc/c-api/long.rst
  Doc/c-api/mapping.rst
  Doc/c-api/memory.rst
  Doc/c-api/method.rst
  Doc/c-api/number.rst
  Doc/c-api/object.rst
  Doc/c-api/sequence.rst
  Doc/c-api/set.rst
  Doc/c-api/structures.rst
  Doc/c-api/sys.rst
  Doc/c-api/type.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#31714 More minor fixes to C API docs
  Doc/c-api/bytearray.rst
  Doc/c-api/bytes.rst
  Doc/c-api/call.rst
  Doc/c-api/exceptions.rst
  Doc/c-api/init_config.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#18183 Document func parameter of locale.atof
  Doc/library/locale.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#32255 [3.10] More minor fixes to C API docs (GH-31714)
  Doc/c-api/bytearray.rst
  Doc/c-api/bytes.rst
  Doc/c-api/call.rst
  Doc/c-api/exceptions.rst
  Doc/c-api/init_config.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32170 bpo-47031: Improve documentation for `math.nan`
  Doc/library/math.rst
Labels: CLA signed, docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#32263 [3.10] bpo-47031: Improve documentation for `math.nan` (GH-32170)
  Doc/library/math.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32264 [3.9] bpo-47031: Improve documentation for `math.nan` (GH-32170)
  Doc/library/math.rst
Labels: CLA signed, docs, awaiting merge, skip news

#29845 bpo-45114: Update stat example
  Doc/library/stat.rst
Labels: CLA signed, docs, awaiting merge, skip news, stale, needs backport to 3.9, needs backport to 3.10

#32266 bpo-46315: Use fopencookie only on Emscripten 3.x and newer (GH-32266)
  Parser/tokenizer.c
Labels: CLA signed, awaiting core review, skip news

#29462 Fix spelling in document
  Doc/library/codecs.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, stale, needs backport to 3.9, needs backport to 3.10

#32267 [3.10] bpo-45114: Use lstat() instead of stat() in stat docs example (GH-29845)
  Doc/library/stat.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32268 [3.9] bpo-45114: Use lstat() instead of stat() in stat docs example (GH-29845)
  Doc/library/stat.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32269 [3.10] codecs docs: fix grammar mistake (GH-29462)
  Doc/library/codecs.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32270 [3.9] codecs docs: fix grammar mistake (GH-29462)
  Doc/library/codecs.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#28996 Fixing typo in the os library documentation
  Doc/library/os.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#32271 [3.10] os docs: fix typo (GH-28996)
  Doc/library/os.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#29183 bpo-45584: Clarify the meaning of `truncate` in documentation
  Doc/library/math.rst
Labels: CLA signed, docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#32273 [3.10] bpo-45584: Clarify `math.trunc` documentation (GH-29183)
  Doc/library/math.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32272 [3.9] bpo-45584: Clarify `math.trunc` documentation (GH-29183)
  Doc/library/math.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32262 [3.10] Document func parameter of locale.atof (GH-18183)
  Doc/library/locale.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news

#32261 [3.9] Document func parameter of locale.atof (GH-18183)
  Doc/library/locale.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news

#32260 [3.9] More minor fixes to C API docs (GH-31714)
  Doc/c-api/bytearray.rst
  Doc/c-api/bytes.rst
  Doc/c-api/call.rst
  Doc/c-api/exceptions.rst
  Doc/c-api/init_config.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news

#32259 [3.9] More minor fixes to C API docs (GH-31525)
  Doc/c-api/init.rst
  Doc/c-api/long.rst
  Doc/c-api/mapping.rst
  Doc/c-api/method.rst
  Doc/c-api/number.rst
  Doc/c-api/object.rst
  Doc/c-api/sequence.rst
  Doc/c-api/set.rst
  Doc/c-api/structures.rst
  Doc/c-api/sys.rst
  Doc/c-api/type.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news

#32258 [3.10] More minor fixes to C API docs (GH-31525)
  Doc/c-api/init.rst
  Doc/c-api/iter.rst
  Doc/c-api/long.rst
  Doc/c-api/mapping.rst
  Doc/c-api/memory.rst
  Doc/c-api/method.rst
  Doc/c-api/number.rst
  Doc/c-api/object.rst
  Doc/c-api/sequence.rst
  Doc/c-api/set.rst
  Doc/c-api/structures.rst
  Doc/c-api/sys.rst
  Doc/c-api/type.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news

#32274 bpo-24563: Link encoding names to encoding declarations
  Doc/reference/lexical_analysis.rst
Labels: CLA signed, docs, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#32276 [3.9] bpo-24563: Link encoding names to encoding declarations (GH-32274)
  Doc/reference/lexical_analysis.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32275 [3.10] bpo-24563: Link encoding names to encoding declarations (GH-32274)
  Doc/reference/lexical_analysis.rst
Labels: CLA signed, docs, awaiting merge, skip news

#30025 bpo-46033: Clarify for-statement execution
  Doc/reference/compound_stmts.rst
  Misc/NEWS.d/next/Documentation/2022-01-03-18-50-39.bpo-46033.7WeF0f.rst
Labels: CLA signed, docs, awaiting merge, skip news

#25212 Remove duplicated text for iterable unpacking
  Doc/reference/simple_stmts.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, stale, needs backport to 3.9, needs backport to 3.10

#32277 [3.10] Language reference: Remove duplicated text about iterable unpacking (GH-25212)
  Doc/reference/simple_stmts.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32278 [3.9] Language reference: Remove duplicated text about iterable unpacking (GH-25212)
  Doc/reference/simple_stmts.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32281 bpo-44800: Document internal frame naming conventions
  Include/internal/pycore_frame.h
Labels: CLA signed, awaiting core review, skip news

#32280 bpo-47196: Fix one more PyInit function signature
  Modules/_testmultiphase.c
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#32285 bpo-47205: Skip error check of sched_get/setaffinity on FreeBSD (GH-32285)
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Tests/2022-04-03-14-38-21.bpo-47205.hbbTnh.rst
Labels: CLA signed, tests, awaiting core review, needs backport to 3.9, needs backport to 3.10

#32287 [3.9] bpo-47205: Skip error check of sched_get/setaffinity on FreeBSD (GH-32285)
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Tests/2022-04-03-14-38-21.bpo-47205.hbbTnh.rst
Labels: CLA signed, tests, awaiting merge, :robot: automerge

#32283 bpo-23689: re module, fix memory leak when a match is terminated by a signal or memory allocation failure
  Lib/re/_compiler.py
  Lib/re/_constants.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2022-04-03-13-19-08.bpo-23689.TFSc3E.rst
  Modules/_sre.c
  Modules/clinic/_sre.c.h
  Modules/sre.h
  Modules/sre_constants.h
  Modules/sre_lib.h
Labels: CLA signed, awaiting merge

#32286 [3.10] bpo-47205: Skip error check of sched_get/setaffinity on FreeBSD (GH-32285)
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Tests/2022-04-03-14-38-21.bpo-47205.hbbTnh.rst
Labels: CLA signed, tests, awaiting merge, :robot: automerge

#32128 bpo-46126: Restore 'descriptions' when running tests internally.
  Lib/test/support/testresult.py
  Misc/NEWS.d/next/Tests/2022-03-26-11-41-19.bpo-46126.q14Ioy.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#32292 bpo-42238: [doc]: make suspicious: false positive.
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting core review, skip news

#32209 bpo-47176: Interrupt handling for wasm32-emscripten builds without pthreads
  Include/internal/pycore_emscripten_signal.h
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2022-04-02-14-32-21.bpo-47176.kTygYI.rst
  Modules/signalmodule.c
  Python/ceval.c
  Python/emscripten_signal.c
  configure
  configure.ac
Labels: CLA signed, awaiting merge

#26127 Follow PEP-8 guidelines in tutorial for standard library
  Doc/tutorial/stdlib.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, stale, needs backport to 3.9, needs backport to 3.10

#32294 [3.10] Follow PEP-8 guidelines in tutorial for standard library (GH-26127)
  Doc/tutorial/stdlib.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32295 [3.9] Follow PEP-8 guidelines in tutorial for standard library (GH-26127)
  Doc/tutorial/stdlib.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32003 bpo-47000: Make `io.text_encoding()` respects UTF-8 mode
  Doc/library/io.rst
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init.h
  Lib/_pyio.py
  Lib/test/test_io.py
  Lib/test/test_utf8_mode.py
  Misc/NEWS.d/next/Library/2022-03-20-13-00-08.bpo-47000.p8HpG0.rst
  Modules/_io/_iomodule.c
  Modules/_io/clinic/_iomodule.c.h
  Python/sysmodule.c
Labels: CLA signed, awaiting changes

#32251 [3.7] bpo-47194: Update zlib to v1.2.12 on Windows to resolve CVE-2018-25032 (GH-32241)
  Misc/NEWS.d/next/Windows/2022-04-01-14-57-40.bpo-47194.IB0XL4.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: CLA signed, type-security, awaiting merge

#32290 bpo-47152: Move sources of the _sre module into a subdirectory
  Lib/re/_constants.py
  Makefile.pre.in
  Modules/Setup.bootstrap.in
  Modules/_sre/clinic/sre.c.h
  Modules/_sre/sre.c
  Modules/_sre/sre.h
  Modules/_sre/sre_constants.h
  Modules/_sre/sre_lib.h
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Tools/c-analyzer/cpython/_parser.py
  configure
  configure.ac
Labels: CLA signed, awaiting core review, skip news

#32298 bpo-47152: Remove unused import in re
  Lib/re/__init__.py
Labels: CLA signed, awaiting core review, skip news

#32301 Revert "bpo-44800: Document internal frame naming conventions"
  Include/internal/pycore_frame.h
Labels: CLA signed, awaiting core review, skip news

#32305 [3.10] Demonstrate `py --list` in the quickstart section of the Windows doc page (GH-29383)
  Doc/using/windows.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32306 [3.9] Demonstrate `py --list` in the quickstart section of the Windows doc page (GH-29383)
  Doc/using/windows.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32297 bpo-47208: Allow vendors to override CTYPES_MAX_ARGCOUNT (GH-32297)
  Lib/ctypes/test/test_callbacks.py
  Misc/NEWS.d/next/Library/2022-04-04-08-54-31.bpo-47208.cOh9xZ.rst
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/ctypes.h
Labels: CLA signed, awaiting core review

#30825 bpo-46484:Add test for Calendar.iterweekdays
  Lib/test/test_calendar.py
  Misc/ACKS
Labels: CLA signed, tests, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#32308 [3.9] bpo-46484:Add test for Calendar.iterweekdays (GH-30825)
  Lib/test/test_calendar.py
  Misc/ACKS
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#32307 [3.10] bpo-46484:Add test for Calendar.iterweekdays (GH-30825)
  Lib/test/test_calendar.py
  Misc/ACKS
Labels: CLA signed, awaiting merge, skip news, :robot: automerge

#32103 bpo-47097: Add documentation for TypeVarTuple
  Doc/library/typing.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32299 Fix `Contributed ... in bpo-bpo-45847` typo
  Doc/whatsnew/3.11.rst
Labels: CLA signed, docs, skip issue, awaiting review, skip news

#21380 bpo-41233: Add links to errnos referenced in exceptions docs
  Doc/library/errno.rst
  Doc/library/exceptions.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2020-07-07-22-54-51.bpo-41233.lyUJ8L.rst
Labels: CLA signed, docs, awaiting merge, needs backport to 3.9, needs backport to 3.10

#32316 [3.10] bpo-41233: Add links to errnos referenced in exceptions docs (GH-21380)
  Doc/library/errno.rst
  Doc/library/exceptions.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2020-07-07-22-54-51.bpo-41233.lyUJ8L.rst
Labels: CLA signed, awaiting merge

#32317 [3.9] bpo-41233: Add links to errnos referenced in exceptions docs (GH-21380)
  Doc/library/errno.rst
  Doc/library/exceptions.rst
  Misc/ACKS
  Misc/NEWS.d/next/Documentation/2020-07-07-22-54-51.bpo-41233.lyUJ8L.rst
Labels: CLA signed, awaiting merge

#31863 bpo-47007: [doc] `str` special method lookup
  Doc/library/stdtypes.rst
Labels: CLA signed, docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#31841 bpo-46998: Allow subclassing Any at runtime
  Doc/library/typing.rst
  Lib/test/test_functools.py
  Lib/test/test_pydoc.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-03-13-08-52-58.bpo-46998.cHh-9O.rst
Labels: CLA signed, awaiting merge

#29529 bpo-45790: List macros in same order in which fields are described
  Doc/extending/newtypes_tutorial.rst
  Misc/NEWS.d/next/Documentation/2021-11-12-11-03-55.bpo-45790.6yuhe8.rst
Labels: CLA signed, docs, awaiting merge, needs backport to 3.9, needs backport to 3.10

#32230 bpo-32658: Add Metacharacter (except \) are not active inside classes Regexpr HOWTO (GH-32230)
  Doc/howto/regex.rst
Labels: CLA signed, docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#26806 Fix references to `methods` attr
  Doc/library/crypt.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#32159 bpo-43224: Add tests for pickling and copying of unpacked native tuple
  Lib/test/test_genericalias.py
Labels: CLA signed, tests, awaiting review, skip news

#32318 [3.10] bpo-47007: [doc] `str` special method lookup (GH-31863)
  Doc/library/stdtypes.rst
Labels: CLA signed, docs, awaiting merge, skip news

#24778 bpo-40982: Fix outdated copytree() "example" in the shutil docs
  Doc/library/shutil.rst
Labels: CLA signed, docs, awaiting merge, skip news, stale, needs backport to 3.9, needs backport to 3.10

#32320 [3.10] bpo-45790: List macros in same order in which fields are described (GH-29529)
  Doc/extending/newtypes_tutorial.rst
  Misc/NEWS.d/next/Documentation/2021-11-12-11-03-55.bpo-45790.6yuhe8.rst
Labels: CLA signed, docs, awaiting merge

#32319 [3.9] bpo-47007: [doc] `str` special method lookup (GH-31863)
  Doc/library/stdtypes.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32323 [3.10] bpo-32658: Regex docs: Fix metacharacter reference (GH-32230)
  Doc/howto/regex.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32324 [3.10] crypt docs: Fix references to `methods` attr (GH-26806)
  Doc/library/crypt.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32322 [3.9] bpo-32658: Regex docs: Fix metacharacter reference (GH-32230)
  Doc/howto/regex.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32325 [3.9] crypt docs: Fix references to `methods` attr (GH-26806)
  Doc/library/crypt.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32326 [3.10] bpo-40982: shutil docs: Remove outdated copytree() example (GH-24778)
  Doc/library/shutil.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32327 [3.9] bpo-40982: shutil docs: Remove outdated copytree() example (GH-24778)
  Doc/library/shutil.rst
Labels: CLA signed, docs, awaiting merge, skip news

#32328 bpo-45847: Adapt macOS installer build to use new tkinter configure vars
  Mac/BuildScript/build-installer.py
Labels: CLA signed, awaiting core review, skip news

#32321 [3.9] bpo-45790: List macros in same order in which fields are described (GH-29529)
  Doc/extending/newtypes_tutorial.rst
  Misc/NEWS.d/next/Documentation/2021-11-12-11-03-55.bpo-45790.6yuhe8.rst
Labels: CLA signed, docs, awaiting core review

#31958 bpo-46890: Fix setting of sys._base_executable with framework builds on macOS
  Lib/test/test_getpath.py
  Makefile.pre.in
  Misc/NEWS.d/next/macOS/2022-03-17-09-55-02.bpo-46890.GX-3OO.rst
  Modules/getpath.c
  Modules/getpath.py
Labels: CLA signed, OS-mac, awaiting merge

#32329 bpo-42238: [doc]: A make sucpicious false positive.
  Doc/tools/susp-ignored.csv
Labels: CLA signed, awaiting core review, skip news

#32331 chore/docs: fix rst style and typo
  Doc/library/re.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, :robot: automerge

#32284 bpo-40280: Add limited Emscripten REPL (GH-32284)
  Makefile.pre.in
  Misc/NEWS.d/next/Tools-Demos/2022-04-03-11-47-45.bpo-40280.Q_IJik.rst
  Tools/wasm/README.md
  Tools/wasm/python.html
  Tools/wasm/python.worker.js
  Tools/wasm/wasm_webserver.py
  configure
  configure.ac
Labels: CLA signed, awaiting core review

#32239 bpo-47009: Let PRECALL_NO_KW_LIST_APPEND do its own POP_TOP
  Python/ceval.c
  Python/specialize.c
Labels: CLA signed, awaiting core review, skip news

#32221 bpo-47120: make JUMP_NO_INTERRUPT relative
  Doc/library/dis.rst
  Doc/whatsnew/3.11.rst
  Include/opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2022-03-31-21-43-57.bpo-47120.NgxQbA.rst
  Objects/frameobject.c
  Python/ceval.c
  Python/compile.c
  Python/opcode_targets.h
Labels: CLA signed, awaiting merge

#32302 bpo-47212: Improve error messages for un-parenthesized generator expressions
  Grammar/python.gram
  Lib/test/test_exceptions.py
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2022-04-05-11-29-21.bpo-47212.leF4pz.rst
  Parser/action_helpers.c
  Parser/parser.c
  Parser/pegen.h
Labels: CLA signed, awaiting merge, needs backport to 3.10

#26728 bpo-41930: Add support for SQLite serialise/deserialise API
  Doc/library/sqlite3.rst
  Doc/whatsnew/3.11.rst
  Lib/test/test_sqlite3/test_dbapi.py
  Misc/NEWS.d/next/Library/2021-06-17-00-02-58.bpo-41930.JS6fsd.rst
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/connection.c
  PCbuild/_sqlite3.vcxproj
  configure
  configure.ac
  pyconfig.h.in
Labels: CLA signed, awaiting merge

#32064 bpo-47088: Add typing.LiteralString (PEP 675)
  Doc/library/typing.rst
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-03-22-19-18-31.bpo-47088.JM1kNI.rst
Labels: CLA signed, awaiting merge

#30927 bpo-46607: Add DeprecationWarning to LegacyInterpolation
  Doc/whatsnew/3.11.rst
  Lib/configparser.py
  Lib/test/test_configparser.py
  Misc/NEWS.d/next/Library/2022-01-26-18-30-34.bpo-46607.xnhT4a.rst
Labels: CLA signed, awaiting merge

#32332 bpo-47009: Fix assert on big endian (GH-32332)
  Python/ceval.c
Labels: CLA signed, awaiting merge, skip news

#32334 [3.10] Backport bpo-47212 (GH-32302) to Python 3.10
  Grammar/python.gram
  Lib/test/test_exceptions.py
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2022-04-05-11-29-21.bpo-47212.leF4pz.rst
  Parser/parser.c
  Parser/pegen.c
  Parser/pegen.h
Labels: CLA signed, awaiting merge, :robot: automerge

#32160 bpo-4833: Add ZipFile.mkdir
  Doc/library/zipfile.rst
  Lib/test/test_zipfile.py
  Lib/zipfile.py
  Misc/NEWS.d/next/Library/2022-03-28-20-16-37.bpo-4833.2vSUE5.rst
Labels: CLA signed, awaiting merge

#32337 bpo-47230: Silence new compiler warnings from updated zlib
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, awaiting review, skip news

#32134 bpo-47061: deprecate the `aifc` module
  Doc/whatsnew/3.11.rst
  Lib/aifc.py
  Lib/sndhdr.py
  Lib/test/support/warnings_helper.py
  Lib/test/test___all__.py
  Lib/test/test_aifc.py
  Lib/test/test_pyclbr.py
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2022-03-26-13-14-43.bpo-47061.QLxbC6.rst
Labels: CLA signed, awaiting merge

#32347 [3.10] bpo-47230: Silence compiler warnings on Windows from zlib 1.2.…
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, awaiting merge, skip news

#32346 [3.9] bpo-47230: Silence compiler warnings on Windows from zlib 1.2.12 (GH-32337)
  PCbuild/pythoncore.vcxproj
Labels: CLA signed, skip issue, awaiting review, skip news

#32345 Fix generation of MD5 table at end of Windows release build
  .azure-pipelines/windows-release/stage-publish-pythonorg.yml
Labels: CLA signed, OS-windows, skip issue, awaiting core review, skip news

#32083 bpo-47103: Copy pgort140.dll into output directory when building PGInstrument on Windows
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Build/2022-03-23-20-01-16.bpo-47103.b4-00F.rst
  PCbuild/python.vcxproj
Labels: CLA signed, OS-windows, awaiting core review

#32235 bpo-47189: What's New in 3.11: Faster CPython
  Doc/tutorial/modules.rst
  Doc/whatsnew/3.11.rst
  Misc/NEWS.d/next/Documentation/2022-04-01-23-56-13.bpo-47189.Nss0Y3.rst
Labels: CLA signed, docs, awaiting merge

#32355 [doc] Add missing backtick.
  Doc/whatsnew/3.11.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32361 bpo-40421: test_capi uses assertEqual(), not assertEquals()
  Lib/test/test_capi.py
Labels: CLA signed, tests, awaiting core review, skip news

#32348 bpo-47235: Note where a typo is intentional in examples
  Doc/library/unittest.mock.rst
Labels: CLA signed, docs, awaiting merge, skip news, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#32367 [3.10] bpo-47235: Note where a typo is intentional in code. (GH-32348)
  Doc/library/unittest.mock.rst
Labels: CLA signed, docs, awaiting merge, skip news, :robot: automerge

#32369 Fix whitespace/indentation format in test_sys
  Lib/test/test_sys.py
Labels: CLA signed, tests, skip issue, awaiting core review, skip news, :robot: automerge, needs backport to 3.9, needs backport to 3.10

#32371 [3.9] stdtypes docs: fix typo (GH-32349)
  Doc/library/stdtypes.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32300 bpo-47211: Remove function re.template() and flag re.TEMPLATE
  Lib/re/__init__.py
  Lib/re/_compiler.py
  Lib/re/_constants.py
  Lib/re/_parser.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2022-04-04-11-58-07.bpo-47211.W4GFkB.rst
  Modules/_sre/sre.c
  Modules/_sre/sre_constants.h
Labels: CLA signed, awaiting merge

#31316 bpo-43464: Optimize set.intersection() for non-set arguments
  Misc/NEWS.d/next/Core and Builtins/2022-02-13-21-53-29.bpo-43464.yupHjd.rst
  Objects/setobject.c
Labels: CLA signed, performance, awaiting merge

#31280 bpo-46721: Optimize set.issuperset() for non-set arguments
  Misc/NEWS.d/next/Core and Builtins/2022-02-11-17-16-30.bpo-46721.JkHaLF.rst
  Objects/setobject.c
Labels: CLA signed, performance, awaiting merge

#32362 Remove python2 support in logging cookbook example. (GH-32362)
  Doc/howto/logging-cookbook.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#2821 bpo-26579: Add object.__getstate__().
  Doc/library/pickle.rst
  Doc/whatsnew/3.11.rst
  Include/object.h
  Lib/_weakrefset.py
  Lib/collections/__init__.py
  Lib/copyreg.py
  Lib/datetime.py
  Lib/email/headerregistry.py
  Lib/test/datetimetester.py
  Lib/test/pickletester.py
  Lib/test/test_bytes.py
  Lib/test/test_deque.py
  Lib/test/test_descrtut.py
  Lib/test/test_ordered_dict.py
  Lib/test/test_set.py
  Lib/test/test_weakset.py
  Lib/test/test_xml_etree.py
  Misc/NEWS.d/next/Core and Builtins/2017-07-23-11-28-45.bpo-26579.lpCY8R.rst
  Modules/_collectionsmodule.c
  Modules/_datetimemodule.c
  Objects/bytearrayobject.c
  Objects/clinic/typeobject.c.h
  Objects/odictobject.c
  Objects/setobject.c
  Objects/typeobject.c
Labels: type-feature, CLA signed, awaiting core review, stale

#32373 [3.9] Fix whitespace/indentation issues in test_sys (GH-32369)
  Lib/test/test_sys.py
Labels: CLA signed, tests, skip issue, awaiting core review, skip news

#32374 [3.10] bpo-46769: Fix backticks in typing.rst to appease rstlint
  Doc/library/typing.rst
  Doc/tools/susp-ignored.csv
Labels: CLA signed, docs, awaiting merge, skip news

#32375 [3.9] bpo-46769: Fix backticks in typing.rst to appease rstlint
  Doc/library/typing.rst
  Doc/tools/susp-ignored.csv
Labels: CLA signed, docs, awaiting merge, skip news

#32330 Move an unrelated statement out of a try clause in Sequence.index
  Lib/_collections_abc.py
Labels: CLA signed, skip issue, awaiting review, skip news

#32377 Change parameter name from *x* for reals to *n* for integers.
  Doc/library/math.rst
  Modules/clinic/mathmodule.c.h
  Modules/mathmodule.c
Labels: CLA signed, docs, skip issue, awaiting core review, skip news, needs backport to 3.10

#32338 bpo-46576: Speed up test_peg_generator by using a static library for shared sources
  Lib/test/test_peg_generator/test_c_parser.py
  Tools/peg_generator/pegen/build.py
  Tools/peg_generator/pegen/testutil.py
Labels: CLA signed, performance, tests, awaiting merge, skip news, needs backport to 3.10

#32383 bpo-35134: Add Include/cpython/complexobject.h header
  Include/complexobject.h
  Include/cpython/complexobject.h
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: CLA signed, awaiting core review, skip news

#32364 bpo-47239: Fixes py.exe output when run in a virtual environment.
  Lib/test/test_launcher.py
  Misc/NEWS.d/next/Windows/2022-04-06-15-16-37.bpo-47239.B1HP7i.rst
  PC/launcher2.c
Labels: CLA signed, OS-windows, awaiting core review

#32384 bpo-35134: Add Include/cpython/setobject.h header
  Include/cpython/setobject.h
  Include/setobject.h
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: CLA signed, awaiting core review, skip news

#32385 bpo-35134: Remove the Include/code.h header file
  Doc/whatsnew/3.11.rst
  Include/Python.h
  Include/code.h
  Include/cpython/code.h
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2022-04-07-00-53-51.bpo-35134.zSjIzk.rst
  Objects/codeobject.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/ceval.c
  Python/marshal.c
  Python/pythonrun.c
  Python/sysmodule.c
  Python/traceback.c
Labels: CLA signed, awaiting core review

#32370 [3.10] stdtypes docs: fix typo (GH-32349)
  Doc/library/stdtypes.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32356 Link sys constants in pkgutil.rst
  Doc/library/pkgutil.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#32314 Fix typo in ssl docs
  Doc/library/ssl.rst
Labels: CLA not signed, docs, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#32391 [3.10] pkgutil docs: Link sys constants, add backticks (GH-32356)
  Doc/library/pkgutil.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32389 [3.10] ssl docs: Fix typo (GH-32314)
  Doc/library/ssl.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32390 [3.9] ssl docs: Fix typo (GH-32314)
  Doc/library/ssl.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news

#32388 [3.9] pkgutil docs: Link sys constants, add backticks (GH-32356)
  Doc/library/pkgutil.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news
