Repository python/cpython, pull requests merged in 2022-06, with the labels that each got.

#93396 📝 Make sure the phrase "constant-time compare" actually appears in the docs
  Doc/library/secrets.rst
Labels: docs, skip issue, awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#93402 [3.11] gh-93345: Fix a crash in substitution of nested TypeVar after TypeVarTuple (GH-93346)
  Lib/test/test_typing.py
  Misc/NEWS.d/next/Core and Builtins/2022-05-30-10-22-46.gh-issue-93345.gi1A4L.rst
  Objects/genericaliasobject.c
Labels: awaiting merge, type-crash

#93401 gh-93372: Fix typo in os.rename documentation
  Doc/library/os.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#93407 [3.10] Remove the execution bit to some socket-related files. (GH-93367)
  Doc/library/socket.rst
  Lib/socket.py
  Lib/test/test_socket.py
Labels: type-bug, awaiting merge, skip news

#93406 [3.11] Remove the execution bit to some socket-related files. (GH-93367)
  Doc/library/socket.rst
  Lib/socket.py
  Lib/test/test_socket.py
Labels: type-bug, awaiting merge, skip news

#30331 gh-90300: split --help output into separate options
  Doc/using/cmdline.rst
  Lib/test/test_cmd_line.py
  Misc/NEWS.d/next/Core and Builtins/2022-01-02-14-53-59.bpo-46142.WayjgT.rst
  Misc/python.man
  Python/getopt.c
  Python/initconfig.c
Labels: CLA signed, awaiting merge, needs backport to 3.11

#93398 gh-92597: Improve error message for AST nodes with invalid ranges
  Python/ast.c
Labels: awaiting merge, skip news, needs backport to 3.11

#93419 gh-93418: Fix an assert when an f-string expression is followed by an '=', but no closing brace.
  Lib/test/test_fstring.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-01-17-47-40.gh-issue-93418.24dJuc.rst
  Parser/string_parser.c
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11

#93427 gh-84461: Skip new async logging tests on Emscripten
  Lib/test/test_logging.py
Labels: tests, awaiting core review, skip news

#93436 gh-90473: Skip and document more failing tests on WASI
  Lib/test/test_compileall.py
  Lib/test/test_import/__init__.py
  Lib/test/test_os.py
  Lib/test/test_pathlib.py
  Lib/test/test_shutil.py
  Tools/wasm/README.md
  Tools/wasm/config.site-wasm32-wasi
  configure
  configure.ac
Labels: awaiting merge, skip news, needs backport to 3.11

#93285 gh-91320: Fix more old-style cast warnings in C++
  Include/boolobject.h
  Include/ceval.h
  Include/pyerrors.h
Labels: awaiting core review, skip news

#92945 gh-92932: dis._unpack_opargs should handle EXTENDED_ARG_QUICK
  Lib/dis.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Library/2022-05-19-17-49-58.gh-issue-92932.o2peTh.rst
Labels: awaiting merge, needs backport to 3.11

#93448 [3.11] gh-92932: dis._unpack_opargs should handle EXTENDED_ARG_QUICK (gh-92945)
  Lib/dis.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Library/2022-05-19-17-49-58.gh-issue-92932.o2peTh.rst
Labels: awaiting merge

#93443 [3.11] gh-90473: Skip and document more failing tests on WASI (GH-93436)
  Lib/test/test_compileall.py
  Lib/test/test_import/__init__.py
  Lib/test/test_os.py
  Lib/test/test_pathlib.py
  Lib/test/test_shutil.py
  Tools/wasm/README.md
  Tools/wasm/config.site-wasm32-wasi
  configure
  configure.ac
Labels: awaiting merge, skip news

#93440 gh-93439: remove redundant argument to loghelper
  Modules/mathmodule.c
Labels: awaiting merge, skip news, extension-modules

#91993 gh-68966: Make mailcap refuse to match unsafe filenames/types/params
  Doc/library/mailcap.rst
  Lib/mailcap.py
  Lib/test/test_mailcap.py
  Misc/NEWS.d/next/Security/2022-04-27-18-25-30.gh-issue-68966.gjS8zs.rst
Labels: awaiting core review, needs backport to 3.11

#93434 gh-93433: Fix dis doc example output
  Doc/library/dis.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.11

#93460 [3.11] gh-93433: Fix dis doc example output (GH-93434)
  Doc/library/dis.rst
Labels: docs, awaiting core review, skip news

#93470 [3.11] test.pythoninfo: Fix typo, Py_REF_DEBUG => Py_TRACE_REFS (GH-93467)
  Lib/test/pythoninfo.py
Labels: skip issue, awaiting merge, skip news

#93458 [3.11] gh-68966: Make mailcap refuse to match unsafe filenames/types/params (GH-91993)
  Doc/library/mailcap.rst
  Lib/mailcap.py
  Lib/test/test_mailcap.py
  Misc/NEWS.d/next/Security/2022-04-27-18-25-30.gh-issue-68966.gjS8zs.rst
Labels: awaiting merge, :robot: automerge

#93383 gh-93382: Cache result of `PyCode_GetCode` in codeobject
  Include/cpython/code.h
  Misc/NEWS.d/next/Core and Builtins/2022-05-31-16-36-30.gh-issue-93382.Jf6gAj.rst
  Objects/codeobject.c
  Objects/frameobject.c
  Programs/test_frozenmain.h
Labels: performance, awaiting core review, interpreter-core

#93473 gh-84461: Skip dtrace/network tests that are enabled by -u all
  Lib/test/support/__init__.py
  Lib/test/test_dtrace.py
Labels: awaiting merge, skip news, needs backport to 3.11

#93474 [3.11] gh-84461: Skip dtrace/network tests that are enabled by -u all (GH-93473)
  Lib/test/support/__init__.py
  Lib/test/test_dtrace.py
Labels: awaiting merge, skip news

#93273 gh-93156: fix negative indexing into absolute `pathlib.PurePath().parents`
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2022-05-26-23-10-55.gh-issue-93156.4XfDVN.rst
Labels: type-bug, awaiting merge, needs backport to 3.10, stdlib, needs backport to 3.11

#93445 gh-93444: remove redundant fields from basicblock: b_nofallthrough, b_exit, b_return
  Misc/NEWS.d/next/Core and Builtins/2022-06-02-23-00-08.gh-issue-93444.m63DIs.rst
  Python/compile.c
Labels: awaiting merge

#93480 [3.10] gh-93156 - fix negative indexing into absolute `pathlib.PurePath().parents` (GH-93273)
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2022-05-26-23-10-55.gh-issue-93156.4XfDVN.rst
Labels: type-bug, awaiting merge, :robot: automerge

#93479 [3.11] gh-93156 - fix negative indexing into absolute `pathlib.PurePath().parents` (GH-93273)
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2022-05-26-23-10-55.gh-issue-93156.4XfDVN.rst
Labels: type-bug, awaiting merge, :robot: automerge

#93311 netrc: Remove unused "import shlex"
  Lib/netrc.py
Labels: skip issue, awaiting merge, skip news

#93237 gh-92886: Fixing test that fails when running with optimizations (`-O`) in `test_imaplib.py`
  Lib/test/test_imaplib.py
  Misc/NEWS.d/next/Tests/2022-05-25-23-07-15.gh-issue-92886.Aki63_.rst
Labels: tests, awaiting merge, needs backport to 3.10, needs backport to 3.11

#93484 [3.11] gh-92886: Fix test that fails when running with `-O` in `test_imaplib.py` (GH-93237)
  Lib/test/test_imaplib.py
  Misc/NEWS.d/next/Tests/2022-05-25-23-07-15.gh-issue-92886.Aki63_.rst
Labels: tests, awaiting merge

#93485 [3.10] gh-92886: Fix test that fails when running with `-O` in `test_imaplib.py` (GH-93237)
  Lib/test/test_imaplib.py
  Misc/NEWS.d/next/Tests/2022-05-25-23-07-15.gh-issue-92886.Aki63_.rst
Labels: tests, awaiting merge

#93489 Fix missing word in sys.float_info docstring
  Objects/floatobject.c
Labels: type-bug, skip issue, awaiting merge, skip news, needs backport to 3.10, interpreter-core, needs backport to 3.11

#93441 Grammatical error in info docstring
  Lib/logging/__init__.py
Labels: skip issue, awaiting review, skip news

#93496 [3.10] Fix missing word in sys.float_info docstring (GH-93489)
  Objects/floatobject.c
Labels: type-bug, skip issue, awaiting review, skip news

#93495 [3.11] Fix missing word in sys.float_info docstring (GH-93489)
  Objects/floatobject.c
Labels: type-bug, skip issue, awaiting review, skip news

#93500 gh-93442: Make C++ version of _Py_CAST work with 0/NULL.
  Include/pyport.h
  Lib/test/_testcppext.cpp
  Misc/NEWS.d/next/C API/2022-06-04-13-15-41.gh-issue-93442.4M4NDb.rst
Labels: awaiting merge

#93505 Add test for _Py_CAST(nullptr).
  Lib/test/_testcppext.cpp
Labels: skip issue, awaiting merge, skip news

#93507 [3.11] gh-93442: Make C++ version of _Py_CAST work with 0/NULL. (GH-93500)
  Include/pyport.h
  Lib/test/_testcppext.cpp
  Misc/NEWS.d/next/C API/2022-06-04-13-15-41.gh-issue-93442.4M4NDb.rst
Labels: awaiting merge

#93509 [3.11] gh-93442: Add test for _Py_CAST(nullptr). (gh-93505)
  Lib/test/_testcppext.cpp
Labels: awaiting merge, skip news

#93490 gh-90473: wasmtime does not support absolute symlinks
  Lib/test/support/os_helper.py
  Lib/test/test_posixpath.py
  Lib/test/test_stat.py
  Misc/NEWS.d/next/Tests/2022-06-03-14-18-37.gh-issue-90473.7iXVRK.rst
  Misc/NEWS.d/next/Tests/2022-06-04-12-05-31.gh-issue-90473.RSpjF7.rst
Labels: awaiting core review, needs backport to 3.11

#93511 [3.11] gh-90473: wasmtime does not support absolute symlinks (GH-93490)
  Lib/test/support/os_helper.py
  Lib/test/test_posixpath.py
  Lib/test/test_stat.py
  Misc/NEWS.d/next/Tests/2022-06-03-14-18-37.gh-issue-90473.7iXVRK.rst
  Misc/NEWS.d/next/Tests/2022-06-04-12-05-31.gh-issue-90473.RSpjF7.rst
Labels: awaiting merge

#93072 gh-89973: Fix re.error in the fnmatch module.
  Lib/fnmatch.py
  Lib/test/test_fnmatch.py
  Misc/NEWS.d/next/Library/2022-05-22-16-08-01.gh-issue-89973.jc-Q4g.rst
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#93514 [3.10] gh-89973: Fix re.error in the fnmatch module. (GH-93072)
  Lib/fnmatch.py
  Lib/test/test_fnmatch.py
  Misc/NEWS.d/next/Library/2022-05-22-16-08-01.gh-issue-89973.jc-Q4g.rst
Labels: awaiting merge

#93513 [3.11] gh-89973: Fix re.error in the fnmatch module. (GH-93072)
  Lib/fnmatch.py
  Lib/test/test_fnmatch.py
  Misc/NEWS.d/next/Library/2022-05-22-16-08-01.gh-issue-89973.jc-Q4g.rst
Labels: awaiting merge

#93498 gh-93143: Document LOAD_FAST_CHECK opcode
  Doc/library/dis.rst
Labels: docs, awaiting merge, skip news

#93248 gh-93247: Fix assert function in asyncio locks test
  Lib/test/test_asyncio/test_locks.py
Labels: tests, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#93525 [3.10] gh-93247: Fix assert function in asyncio locks test (GH-93248)
  Lib/test/test_asyncio/test_locks.py
Labels: tests, awaiting merge, skip news

#93524 [3.11] gh-93247: Fix assert function in asyncio locks test (GH-93248)
  Lib/test/test_asyncio/test_locks.py
Labels: tests, awaiting merge, skip news

#93529 gh-90473: WASI requires proper open(2) flags
  Lib/test/support/os_helper.py
  Lib/test/test_os.py
  Tools/wasm/README.md
Labels: awaiting merge, skip news, needs backport to 3.11

#92562 GH-92308 What's New: list pending removals in 3.13 and future versions
  Doc/whatsnew/3.12.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11

#93530 [3.11] gh-90473: WASI requires proper open(2) flags (GH-93529)
  Lib/test/support/os_helper.py
  Lib/test/test_os.py
  Tools/wasm/README.md
Labels: awaiting merge, skip news

#93536 gh-90473: Skip POSIX tests that don't apply to WASI
  Lib/test/test_posix.py
Labels: tests, awaiting core review, skip news, needs backport to 3.11

#93371 Fix typo in asyncio documentation
  Doc/library/asyncio-sync.rst
Labels: docs, expert-asyncio, skip issue, awaiting core review, skip news, needs backport to 3.11

#93541 [3.11] asyncio.Barrier docs: Fix typo (GH-93371)
  Doc/library/asyncio-sync.rst
Labels: docs, skip issue, awaiting merge, skip news

#91939 gh-83728: Add hmac.new default parameter deprecation in 3.8 whatsnew
  Doc/whatsnew/3.8.rst
Labels: docs, awaiting review, skip news, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#93400 [3.10] 📝 Make sure the phrase "constant-time compare" actually appears in the docs (GH-93396)
  Doc/library/secrets.rst
Labels: docs, skip issue, awaiting review, skip news

#93159 [3.10] gh-93108: Bump sphinx to fix rendering issue.
  Doc/requirements.txt
Labels: awaiting core review, skip news

#93547 [3.8] gh-83728: Add hmac.new default parameter deprecation (GH-91939)
  Doc/whatsnew/3.8.rst
Labels: docs, awaiting review, skip news

#93395 [3.10] gh-93391: fix typo in `array` docs (GH-93392)
  Doc/library/array.rst
Labels: docs, awaiting review, skip news

#93540 [3.11] gh-90473: Skip POSIX tests that don't apply to WASI (GH-93536)
  Lib/test/test_posix.py
Labels: tests, awaiting core review, skip news

#93550 [3.11] gh-90473: Make chmod a dummy on WASI, skip chmod tests (GH-93534)
  Lib/test/support/os_helper.py
  Lib/test/test_argparse.py
  Lib/test/test_dbm_dumb.py
  Lib/test/test_import/__init__.py
  Lib/test/test_netrc.py
  Lib/test/test_os.py
  Lib/test/test_pathlib.py
  Lib/test/test_posix.py
  Lib/test/test_posixpath.py
  Lib/test/test_py_compile.py
  Lib/test/test_pydoc.py
  Lib/test/test_shutil.py
  Lib/test/test_stat.py
  Lib/test/test_tarfile.py
  Lib/test/test_tempfile.py
  Lib/test/test_uu.py
  Lib/test/test_zipapp.py
  Misc/NEWS.d/next/Tests/2022-06-05-10-16-45.gh-issue-90473.QMu7A8.rst
  Modules/posixmodule.c
  Tools/wasm/config.site-wasm32-wasi
Labels: awaiting review

#93552 fix some asyncio.Barrier.wait docs grammar
  Doc/library/asyncio-sync.rst
Labels: docs, skip issue, awaiting review, skip news, needs backport to 3.11

#93553 [3.11] [docs] fix some asyncio.Barrier.wait docs grammar (GH-93552)
  Doc/library/asyncio-sync.rst
Labels: docs, skip issue, awaiting review, skip news

#27645 gh-89018: Improve documentation of `sqlite3` exceptions
  Doc/library/sqlite3.rst
Labels: CLA signed, docs, awaiting core review, skip news

#32010 bpo-42658: Using LCMapStringEx in ntpath.normcase
  Lib/ntpath.py
  Lib/test/test_ntpath.py
  Misc/NEWS.d/next/Windows/2022-03-20-15-47-35.bpo-42658.16eXtb.rst
  Modules/_winapi.c
  Modules/clinic/_winapi.c.h
Labels: CLA signed, OS-windows, awaiting review

#93556 Fix contributor name
  Doc/whatsnew/3.11.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11

#93558 [3.11] Fix contributor name in WhatsNew 3.11 (GH-93556)
  Doc/whatsnew/3.11.rst
Labels: docs, skip issue, awaiting merge, skip news

#93523 Grammar fix to socket error string
  Lib/socket.py
Labels: skip issue, awaiting review, skip news, needs backport to 3.11

#93561 [3.11] gh-86986: bump min sphinx version to 3.2 (GH-93337)
  Doc/conf.py
  Misc/NEWS.d/next/Documentation/2022-05-29-21-22-54.gh-issue-86986.lFXw8j.rst
Labels: awaiting review

#93562 [3.10] gh-86986: bump min sphinx version to 3.2 (GH-93337)
  Doc/conf.py
  Misc/NEWS.d/next/Documentation/2022-05-29-21-22-54.gh-issue-86986.lFXw8j.rst
Labels: awaiting review

#93468 gh-57539: Increase calendar test coverage
  Lib/test/test_calendar.py
  Misc/ACKS
  Misc/NEWS.d/next/Tests/2022-06-03-16-26-04.gh-issue-57539.HxWgYO.rst
Labels: tests, awaiting core review, needs backport to 3.10, needs backport to 3.11

#92942 [3.10] gh-92914: Round the allocated size for lists up to the even number (GH-92915)
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2022-05-18-08-32-33.gh-issue-92914.tJUeTD.rst
  Objects/listobject.c
Labels: awaiting review

#93537 GH-93533: Shrink the LOAD_METHOD cache by one codeunit.
  Include/internal/pycore_code.h
  Include/internal/pycore_opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-06-14-28-24.gh-issue-93533.lnC0CC.rst
  Python/ceval.c
  Python/specialize.c
Labels: performance, awaiting merge

#93566 [3.11] gh-88831: In docs for asyncio.create_task, explain why strong references to tasks are needed (GH-93258)
  Doc/library/asyncio-task.rst
  Misc/NEWS.d/next/Documentation/2022-05-26-14-51-25.gh-issue-88831.5Cccr5.rst
Labels: docs, awaiting review

#93565 [3.10] gh-57539: Increase calendar test coverage (GH-93468)
  Lib/test/test_calendar.py
  Misc/ACKS
  Misc/NEWS.d/next/Tests/2022-06-03-16-26-04.gh-issue-57539.HxWgYO.rst
Labels: awaiting review

#93564 [3.11] gh-57539: Increase calendar test coverage (GH-93468)
  Lib/test/test_calendar.py
  Misc/ACKS
  Misc/NEWS.d/next/Tests/2022-06-03-16-26-04.gh-issue-57539.HxWgYO.rst
Labels: awaiting review

#93572 gh-93162: test_config_queue_handler requires threading
  Lib/test/test_logging.py
Labels: tests, awaiting merge, skip news

#92353 gh-84461: Emscripten's faccessat() does not accept flags
  Tools/wasm/config.site-wasm32-emscripten
Labels: awaiting core review, skip news, needs backport to 3.11

#93578 [3.11] gh-84461: Emscripten's faccessat() does not accept flags (GH-92353)
  Tools/wasm/config.site-wasm32-emscripten
Labels: awaiting merge, skip news

#92591 gh-92592: Allow logging filters to return a LogRecord. (GH-92591)
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.rst
  Lib/logging/__init__.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2022-05-09-22-27-11.gh-issue-92591.V7RCk2.rst
Labels: awaiting changes

#93268 Fix `Path.relative_to` links in the pathlib documentation.
  Doc/library/pathlib.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#93483 GH-93481: Suppress expected deprecation warning in test_pyclbr
  Lib/test/test_pyclbr.py
Labels: tests, awaiting merge, skip news, needs backport to 3.11

#93590 [3.10] Fix `PurePath.relative_to` links in the pathlib documentation (GH-93268)
  Doc/library/pathlib.rst
Labels: docs, skip issue, awaiting merge, skip news, :robot: automerge

#93482 gh-93370 : Deprecate sqlite3.version and sqlite3.version_info
  Doc/library/sqlite3.rst
  Lib/sqlite3/__init__.py
  Lib/sqlite3/dbapi2.py
  Lib/test/test_sqlite3/test_dbapi.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2022-06-03-22-13-28.gh-issue-93370.tjfu9L.rst
  Modules/_sqlite/module.c
Labels: awaiting merge, expert-sqlite3

#93535 GH-93521: Filter out `__weakref__` slot if present in bases
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2022-06-06-13-19-43.gh-issue-93521._vE8m9.rst
Labels: awaiting merge, needs backport to 3.11

#93594 [3.11] GH-93521: For dataclasses, filter out `__weakref__` slot if present in bases (GH-93535)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2022-06-06-13-19-43.gh-issue-93521._vE8m9.rst
Labels: awaiting merge, :robot: automerge

#93526 gh-93421: Update sqlite3 cursor.rowcount after SQLITE_DONE
  Lib/test/test_sqlite3/test_dbapi.py
  Misc/NEWS.d/next/Library/2022-06-05-22-22-42.gh-issue-93421.43UO_8.rst
  Modules/_sqlite/cursor.c
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#93598 [3.11] gh-93421: Update sqlite3 cursor.rowcount only after SQLITE_DONE (GH-93526)
  Lib/test/test_sqlite3/test_dbapi.py
  Misc/NEWS.d/next/Library/2022-06-05-22-22-42.gh-issue-93421.43UO_8.rst
  Modules/_sqlite/cursor.c
Labels: awaiting merge

#93599 [3.10] gh-93421: Update sqlite3 cursor.rowcount only after SQLITE_DONE (GH-93526)
  Lib/sqlite3/test/dbapi.py
  Misc/NEWS.d/next/Library/2022-06-05-22-22-42.gh-issue-93421.43UO_8.rst
  Modules/_sqlite/cursor.c
Labels: awaiting core review

#93581 gh-87961: Remove outdated notes from functions that aren't in the Limited API
  Doc/c-api/call.rst
  Doc/c-api/structures.rst
  Doc/c-api/typeobj.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#93603 [3.11] gh-93584: Make all install+tests targets depends on all (GH-93589)
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2022-06-08-14-28-03.gh-issue-93584.0xfHOK.rst
Labels: awaiting core review

#93602 gh-93575: Use correct way to calculate PyUnicode struct sizes
  Lib/test/test_sys.py
  Lib/test/test_unicode.py
  Misc/NEWS.d/next/Tests/2022-06-08-14-17-59.gh-issue-93575.Xb2LNB.rst
Labels: tests, awaiting core review, needs backport to 3.11

#93606 gh-90473: Define HOSTRUNNER for WASI
  configure
  configure.ac
Labels: awaiting core review, skip news, needs backport to 3.11

#93612 [3.11] gh-90473: Define HOSTRUNNER for WASI (GH-93606)
  configure
  configure.ac
Labels: awaiting core review, skip news

#93614 gh-79096: Fix/improve http cookiejar tests
  Lib/test/test_http_cookiejar.py
Labels: tests, awaiting core review, skip news

#93617 gh-93616: Fix env changed issue in test_modulefinder
  Lib/test/test_modulefinder.py
  Misc/NEWS.d/next/Tests/2022-06-08-22-32-56.gh-issue-93616.e5Kkx2.rst
Labels: tests, awaiting core review, needs backport to 3.11

#93630 [3.11] gh-93616: Fix env changed issue in test_modulefinder (GH-93617)
  Lib/test/test_modulefinder.py
  Misc/NEWS.d/next/Tests/2022-06-08-22-32-56.gh-issue-93616.e5Kkx2.rst
Labels: tests, awaiting merge

#93609 gh-90494: Reject 6th element of the __reduce__() tuple
  Lib/copy.py
  Lib/pickle.py
  Lib/test/test_copy.py
  Misc/NEWS.d/next/Library/2022-06-08-20-11-02.gh-issue-90494.LIZT85.rst
Labels: type-bug, awaiting merge, needs backport to 3.10, needs backport to 3.11

#92791 Doc: Update references and examples of old, unsupported OSes and uarches
  Doc/c-api/init_config.rst
  Doc/faq/library.rst
  Doc/howto/sockets.rst
  Doc/library/mmap.rst
  Doc/library/platform.rst
  Doc/library/posix.rst
  Doc/library/struct.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#93639 [3.10] Doc: Update references and examples of old, unsupported OSes and uarches (GH-92791)
  Doc/c-api/init_config.rst
  Doc/faq/library.rst
  Doc/howto/sockets.rst
  Doc/library/mmap.rst
  Doc/library/platform.rst
  Doc/library/posix.rst
  Doc/library/struct.rst
Labels: docs, skip issue, awaiting review, skip news

#28748 bpo-45383: Inherit MetaClass from bases in FromSpec API
  Doc/c-api/type.rst
  Misc/NEWS.d/next/C API/2021-10-05-21-59-43.bpo-45383.TVClgf.rst
  Modules/_testcapimodule.c
  Objects/typeobject.c
Labels: CLA signed, awaiting review

#93644 Improve logging documentation with example and additional cookbook re… (GH-93644)
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.rst
Labels: docs, skip issue, awaiting core review, skip news

#93633 gh-90473: disable user site packages on WASI/Emscripten
  Lib/site.py
  Lib/sysconfig.py
  Misc/NEWS.d/next/Library/2022-06-09-10-12-55.gh-issue-90473.683m_C.rst
Labels: awaiting core review, needs backport to 3.11

#93645 gh-90473: Skip get_config_h() tests on WASI (GH-93645)
  Lib/distutils/tests/test_sysconfig.py
  Lib/test/test_sysconfig.py
Labels: tests, awaiting core review, skip news, needs backport to 3.11

#93646 [3.11] gh-90473: disable user site packages on WASI/Emscripten (GH-93633)
  Lib/site.py
  Lib/sysconfig.py
  Misc/NEWS.d/next/Library/2022-06-09-10-12-55.gh-issue-90473.683m_C.rst
Labels: awaiting merge

#93647 [3.11] Improve logging documentation with example and additional cookbook re… (GH-93644) (GH-93647)
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.rst
Labels: docs, skip issue, awaiting review, skip news

#93650 [3.11] gh-90473: Skip get_config_h() tests on WASI (GH-93645)
  Lib/distutils/tests/test_sysconfig.py
  Lib/test/test_sysconfig.py
Labels: tests, awaiting merge, skip news

#30617 gh-90549: Fix leak of global named resources using multiprocessing spawn
  Lib/multiprocessing/context.py
  Lib/multiprocessing/process.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2022-06-07-14-53-46.gh-issue-90549.T4FMKY.rst
Labels: CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.11, expert-multiprocessing

#93090 gh-92434: Silence a compiler warning in _sqlite/connection.c for 32bit version
  Modules/_sqlite/connection.c
Labels: awaiting core review, skip news, 3.11, expert-sqlite3

#93672 [3.11] gh-92434: Silence compiler warning in Modules/_sqlite/connection.c on 32-bit systems (GH-93090)
  Modules/_sqlite/connection.c
Labels: awaiting merge, skip news

#93591 [3.11] bpo-42658: Use LCMapStringEx in ntpath.normcase to match OS behaviour for case-folding (GH-32010)
  Lib/ntpath.py
  Lib/test/test_ntpath.py
  Misc/NEWS.d/next/Windows/2022-03-20-15-47-35.bpo-42658.16eXtb.rst
  Modules/_winapi.c
  Modules/clinic/_winapi.c.h
Labels: awaiting core review, needs backport to 3.10

#93078 gh-90763: Modernise xx template module initialisation
  Modules/xxlimited_35.c
  Modules/xxmodule.c
Labels: awaiting merge, skip news

#93679 [3.10] gh-90763: Modernise xx template module initialisation (GH-93078)
  Modules/xxlimited_35.c
  Modules/xxmodule.c
Labels: awaiting merge, skip news

#93681 [3.11] gh-90763: Modernise xx template module initialisation (GH-93078)
  Modules/xxlimited_35.c
  Modules/xxmodule.c
Labels: awaiting core review, skip news

#93652 [3.10] gh-90549: Fix leak of global named resources using multiprocessing spawn (GH-30617)
  Lib/multiprocessing/context.py
  Lib/multiprocessing/process.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2022-06-07-14-53-46.gh-issue-90549.T4FMKY.rst
Labels: awaiting merge

#93492 gh-93491: Add support tier detection to configure (GH-93492)
  Misc/NEWS.d/next/Build/2022-06-04-12-53-53.gh-issue-93491.ehM211.rst
  PC/pyconfig.h
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge, needs backport to 3.11

#93683 [3.11] gh-93491: Add support tier detection to configure (GH-93492)
  Misc/NEWS.d/next/Build/2022-06-04-12-53-53.gh-issue-93491.ehM211.rst
  PC/pyconfig.h
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge

#93471 gh-93466: Document PyType_Spec doesn't accept repeated slot IDs; raise where this was problematic
  Doc/c-api/type.rst
  Lib/test/test_capi.py
  Misc/NEWS.d/next/C API/2022-06-03-14-54-41.gh-issue-93466.DDtH0X.rst
  Modules/_testcapimodule.c
  Objects/typeobject.c
Labels: awaiting merge

#93632 [3.10] gh-90494: Reject 6th element of the __reduce__() tuple (GH-93609)
  Lib/copy.py
  Lib/pickle.py
  Lib/test/test_copy.py
  Misc/NEWS.d/next/Library/2022-06-08-20-11-02.gh-issue-90494.LIZT85.rst
Labels: type-bug, awaiting review

#93631 [3.11] gh-90494: Reject 6th element of the __reduce__() tuple (GH-93609)
  Lib/copy.py
  Lib/pickle.py
  Lib/test/test_copy.py
  Misc/NEWS.d/next/Library/2022-06-08-20-11-02.gh-issue-90494.LIZT85.rst
Labels: type-bug, awaiting review

#93604 [3.11] gh-87961: Remove outdated notes from functions that aren't in the Limited API (GH-93581)
  Doc/c-api/call.rst
  Doc/c-api/structures.rst
  Doc/c-api/typeobj.rst
Labels: docs, awaiting review, skip news

#93403 [3.11] gh-93372: Fix typo in os.rename documentation (GH-93401)
  Doc/library/os.rst
Labels: docs, awaiting review, skip news

#93399 [3.11] 📝 Make sure the phrase "constant-time compare" actually appears in the docs (GH-93396)
  Doc/library/secrets.rst
Labels: docs, skip issue, awaiting review, skip news

#93394 [3.11] gh-93391: fix typo in `array` docs (GH-93392)
  Doc/library/array.rst
Labels: docs, awaiting review, skip news

#93648 [3.10] Improve logging documentation with example and additional cookbook re… (GH-93644)
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.rst
  Doc/tools/susp-ignored.csv
Labels: docs, skip issue, awaiting review, skip news

#93651 [3.11] gh-90549: Fix leak of global named resources using multiprocessing spawn (GH-30617)
  Lib/multiprocessing/context.py
  Lib/multiprocessing/process.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2022-06-07-14-53-46.gh-issue-90549.T4FMKY.rst
Labels: awaiting merge

#93680 gh-93671: Avoid exponential backtracking in deeply nested sequence patterns in match statements
  Grammar/python.gram
  Lib/test/test_patma.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-10-12-03-17.gh-issue-93671.idkQqG.rst
  Parser/parser.c
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#91882 gh-81790: support "UNC" device paths in `ntpath.splitdrive()`
  Doc/library/os.path.rst
  Lib/ntpath.py
  Lib/pathlib.py
  Lib/test/test_ntpath.py
  Misc/NEWS.d/next/Library/2022-04-24-22-26-45.gh-issue-81790.M5Rvpm.rst
Labels: awaiting merge

#93688 [3.11] bpo-42658: Allow _winapi.LCMapStringEx to handle embedded nulls
  Modules/_winapi.c
Labels: awaiting core review, skip news

#93689 [3.11] gh-93671: Avoid exponential backtracking in deeply nested sequence patterns in match statements (GH-93680)
  Grammar/python.gram
  Lib/test/test_patma.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-10-12-03-17.gh-issue-93671.idkQqG.rst
  Parser/parser.c
Labels: awaiting merge

#93622 GH-93621: reorder code in with/async-with exception exit path to reduce the size of the exception table
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-09-09-08-29.gh-issue-93621.-_Pn1d.rst
  Python/compile.c
Labels: awaiting merge, interpreter-core

#93690 [3.10] gh-93671: Avoid exponential backtracking in deeply nested sequence patterns in match statements (GH-93680)
  Grammar/python.gram
  Lib/test/test_patma.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-10-12-03-17.gh-issue-93671.idkQqG.rst
  Parser/parser.c
Labels: awaiting core review

#93653 gh-93461: Invalidate sys.path_importer_cache entries with relative paths
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_import/__init__.py
  Lib/test/test_importlib/import_/test_path.py
  Lib/test/test_importlib/test_api.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-09-19-19-02.gh-issue-93461.5DqP1e.rst
Labels: awaiting merge, needs backport to 3.11

#32193 gh-91317: Document that Path does not collapse initial `//`
  Doc/library/pathlib.rst
  Misc/NEWS.d/next/Documentation/2022-03-30-17-56-01.bpo-47161.gesHfS.rst
Labels: CLA signed, docs, awaiting merge, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#93236 gh-92886: Fixing tests that fail when running with optimizations (`-O`) in `test_zipimport.py`
  Lib/test/test_zipimport.py
  Misc/NEWS.d/next/Tests/2022-05-25-23-00-35.gh-issue-92886.Y-vrWj.rst
Labels: tests, awaiting merge, needs backport to 3.10, needs backport to 3.11

#93702 [3.11] gh-91317: Document that Path does not collapse initial `//` (GH-32193)
  Doc/library/pathlib.rst
  Misc/NEWS.d/next/Documentation/2022-03-30-17-56-01.bpo-47161.gesHfS.rst
Labels: docs, awaiting merge, :robot: automerge

#93703 [3.10] gh-91317: Document that Path does not collapse initial `//` (GH-32193)
  Doc/library/pathlib.rst
  Misc/NEWS.d/next/Documentation/2022-03-30-17-56-01.bpo-47161.gesHfS.rst
Labels: docs, awaiting merge, :robot: automerge

#93704 [3.11] gh-92886: Fix tests that fail when running with optimizations (`-O`) in `test_zipimport.py` (GH-93236)
  Lib/test/test_zipimport.py
  Misc/NEWS.d/next/Tests/2022-05-25-23-00-35.gh-issue-92886.Y-vrWj.rst
Labels: tests, awaiting merge, :robot: automerge

#93705 [3.10] gh-92886: Fix tests that fail when running with optimizations (`-O`) in `test_zipimport.py` (GH-93236)
  Lib/test/test_zipimport.py
  Misc/NEWS.d/next/Tests/2022-05-25-23-00-35.gh-issue-92886.Y-vrWj.rst
Labels: tests, awaiting merge, :robot: automerge

#92931 gh-92930: _pickle.c: Acquire strong references before calling save()
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Core and Builtins/2022-05-18-18-34-45.gh-issue-92930.kpYPOb.rst
  Modules/_pickle.c
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#93707 [3.11] gh-92930: _pickle.c: Acquire strong references before calling save() (GH-92931)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Core and Builtins/2022-05-18-18-34-45.gh-issue-92930.kpYPOb.rst
  Modules/_pickle.c
Labels: awaiting merge

#93708 [3.10] gh-92930: _pickle.c: Acquire strong references before calling save() (GH-92931)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Core and Builtins/2022-05-18-18-34-45.gh-issue-92930.kpYPOb.rst
  Modules/_pickle.c
Labels: awaiting merge

#93694 gh-84461: Use HOSTRUNNER to run regression tests (GH-93694)
  Misc/NEWS.d/next/Tests/2022-06-10-21-18-14.gh-issue-84461.9TAb26.rst
  Tools/scripts/run_tests.py
  configure
  configure.ac
Labels: awaiting merge, needs backport to 3.11

#93709 [3.11] gh-84461: Use HOSTRUNNER to run regression tests (GH-93694)
  Misc/NEWS.d/next/Tests/2022-06-10-21-18-14.gh-issue-84461.9TAb26.rst
  Tools/scripts/run_tests.py
  configure
  configure.ac
Labels: awaiting merge

#93712 gh-90473: Skip test_queue when threading is not available (GH-93712)
  Lib/test/test_queue.py
Labels: tests, awaiting core review, skip news, needs backport to 3.11

#93624 gh-90153: whatsnew: "z" option in format spec
  Doc/whatsnew/3.11.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11

#93717 [3.11] gh-90153: whatsnew: "z" option in format spec (GH-93624)
  Doc/whatsnew/3.11.rst
Labels: docs, awaiting merge, skip news

#93716 [3.11] gh-90473: Skip test_queue when threading is not available (GH-93712)
  Lib/test/test_queue.py
Labels: tests, awaiting merge, skip news

#93710 gh-86404: [doc] A make sucpicious false positive.
  Doc/tools/susp-ignored.csv
Labels: awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#93661 gh-93660: Change list to view object in SymbolTable docstring
  Doc/library/symtable.rst
  Lib/symtable.py
Labels: awaiting merge, skip news
