Repository python/cpython, pull requests merged in 2022-07, with the labels that each got.

#94451 gh-90005-ffi: Fix building _ctypes without pkg-config (GH-94451)
  Misc/NEWS.d/next/Build/2022-06-30-17-00-54.gh-issue-90005.iiq5qD.rst
  configure
  configure.ac
Labels: awaiting core review, needs backport to 3.11

#94447 Add a workflow to add issues/PRs to projects.
  .github/workflows/project-updater.yml
Labels: type-feature, skip issue, awaiting core review, skip news

#94371 GH-94262: Don't create frame objects for frames that aren't complete.
  Include/internal/pycore_frame.h
  Lib/test/test_generators.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-28-10-08-06.gh-issue-94262.m-HWUZ.rst
  Objects/codeobject.c
  Objects/frameobject.c
  Python/frame.c
  Python/sysmodule.c
Labels: awaiting change review, needs backport to 3.11

#94480 [3.11] gh-84461: Improve WebAssembly in-browser demo (GH-91879)
  Tools/wasm/.editorconfig
  Tools/wasm/python.html
  Tools/wasm/python.worker.js
Labels: awaiting merge, skip news

#94481 [3.11] gh-84461: Tool/wasm/python.html: Add subresource integrity hashes (GH-93953)
  Tools/wasm/python.html
Labels: awaiting merge, skip news

#94444 GH-94438: Account for NULLs on evaluation stack when jumping lines.
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-30-15-07-26.gh-issue-94438.btzHSk.rst
  Objects/frameobject.c
Labels: awaiting merge, needs backport to 3.11

#94241 gh-94216: add pseudo instructions to the dis/opcodes modules
  Doc/library/dis.rst
  Doc/whatsnew/3.12.rst
  Include/internal/pycore_opcode.h
  Include/opcode.h
  Lib/dis.py
  Lib/opcode.py
  Lib/test/test__opcode.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Library/2022-06-24-20-00-57.gh-issue-94216.hxnQPu.rst
  Modules/_opcode.c
  Python/compile.c
  Python/makeopcodetargets.py
  Tools/scripts/generate_opcode_h.py
Labels: awaiting merge

#94486 [3.11] GH-94438: Backport GH-94444
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-30-15-07-26.gh-issue-94438.btzHSk.rst
  Objects/frameobject.c
Labels: awaiting merge

#92759 gh-75372: Specify major version in README for installation
  README.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#94003 [3.11] gh-93975: Nicer error reporting in test_venv (GH-93959)
  Lib/test/test_venv.py
  Misc/NEWS.d/next/Tests/2022-06-17-13-55-11.gh-issue-93957.X4ovYV.rst
Labels: tests, awaiting core review, :robot: automerge

#94004 [3.10] gh-93975: Nicer error reporting in test_venv (GH-93959)
  Lib/test/test_venv.py
  Misc/NEWS.d/next/Tests/2022-06-17-13-55-11.gh-issue-93957.X4ovYV.rst
Labels: tests, awaiting core review, :robot: automerge

#94491 [3.10] Update code sample when importing modules in queue doc (GH-94244)
  Doc/library/queue.rst
Labels: docs, skip issue, awaiting review, skip news

#94487 [3.11] gh-75372: Specify major version in README for installation (GH-92759)
  README.rst
Labels: docs, awaiting review, skip news

#94492 [3.11] gh-81054: Document that SimpleHTTPRequestHandler follows symbolic links (GH-94416)
  Doc/library/http.server.rst
  Doc/library/security_warnings.rst
Labels: type-security, awaiting review, skip news

#94493 [3.10] gh-81054: Document that SimpleHTTPRequestHandler follows symbolic links (GH-94416)
  Doc/library/http.server.rst
  Doc/library/security_warnings.rst
Labels: type-security, awaiting review, skip news

#94494 [3.9] gh-81054: Document that SimpleHTTPRequestHandler follows symbolic links (GH-94416)
  Doc/library/http.server.rst
  Doc/library/security_warnings.rst
Labels: type-security, awaiting review, skip news

#94496 [3.7] gh-81054: Document that SimpleHTTPRequestHandler follows symbolic links (GH-94416)
  Doc/library/http.server.rst
Labels: type-security, awaiting core review, skip news

#94433 gh-90005: Port _dbm module to PY_STDLIB_MOD (GH-94433)
  Misc/NEWS.d/next/Build/2022-06-30-09-57-39.gh-issue-90005.9-pQyR.rst
  Modules/Setup.stdlib.in
  configure
  configure.ac
  pyconfig.h.in
  setup.py
Labels: awaiting merge

#94233 gh-93096: Remove `python -m codecs`
  Lib/codecs.py
  Misc/NEWS.d/next/Library/2022-06-24-19-40-40.gh-issue-93096.3RlK2d.rst
Labels: awaiting merge

#94394 gh-94393: Remove unneeded module state from _json
  Modules/_json.c
Labels: awaiting merge, skip news

#94505 Doc: fix sqlite3 blob reference anchor
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting core review, skip news

#94230 gh-93096: Remove `python -m base64 -t`
  Lib/base64.py
  Lib/test/test_base64.py
  Misc/NEWS.d/next/Library/2022-06-24-19-16-09.gh-issue-93096.r1_oIc.rst
Labels: awaiting merge

#94530 IDLE doc: Tweek RESTART and Windows console start
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: skip issue, awaiting core review, skip news, needs backport to 3.10, expert-IDLE, needs backport to 3.11

#94534 [3.11] IDLE doc: Tweek RESTART and Windows console start (GH-94530)
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: skip issue, awaiting merge, skip news

#94535 [3.10] IDLE doc: Tweek RESTART and Windows console start (GH-94530)
  Doc/library/idle.rst
  Lib/idlelib/help.html
Labels: skip issue, awaiting merge, skip news

#92870 gh-92869: ctypes: Add c_time_t
  Doc/library/ctypes.rst
  Lib/ctypes/__init__.py
  Lib/test/test_ctypes/test_sizes.py
  Misc/NEWS.d/next/Library/2022-05-17-06-27-39.gh-issue-92869.t8oBkw.rst
  Modules/_ctypes/_ctypes.c
Labels: type-feature, awaiting merge, expert-ctypes

#93965 gh-93963: Officially deprecate abcs and warn about their usage.
  Lib/importlib/abc.py
  Misc/NEWS.d/next/Library/2022-06-17-16-00-55.gh-issue-93963.8YYZ-2.rst
Labels: awaiting merge, :robot: automerge

#94540 Update logging documentation: change cross-reference and add webapp r… (GH-94540)
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.rst
Labels: docs, skip issue, awaiting core review, skip news

#94542 [3.10] Update logging documentation: change cross-reference and add webapp r… (GH-94542)
  Doc/howto/logging-cookbook.rst
  Doc/library/logging.rst
Labels: docs, skip issue, awaiting core review, skip news

#94514 gh-94512: Fix forced arg format in AC-processed msvcrtmodule
  PC/clinic/msvcrtmodule.c.h
  PC/msvcrtmodule.c
Labels: awaiting review, skip news

#94513 gh-94512: Fix forced arg format in AC-processed winreg
  PC/clinic/winreg.c.h
  PC/winreg.c
Labels: awaiting review, skip news

#94517 gh-94512: Fix forced arg format in AC-processed multiprocessing
  Modules/_multiprocessing/clinic/multiprocessing.c.h
  Modules/_multiprocessing/multiprocessing.c
Labels: awaiting review, skip news

#94353 gh-94352: shlex.split() no longer accepts None
  Doc/library/shlex.rst
  Doc/whatsnew/3.12.rst
  Lib/shlex.py
  Lib/test/test_shlex.py
  Misc/NEWS.d/next/Library/2022-06-28-00-24-48.gh-issue-94352.JY1Ayt.rst
Labels: awaiting core review

#94384 gh-94383: Remove ElementTree.Element.copy() method
  Doc/whatsnew/3.12.rst
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2022-06-28-14-41-22.gh-issue-94383.CXnquo.rst
Labels: awaiting core review

#94482 [3.11] GH-94262: Don't create frame objects for frames that aren't yet complete. (GH-94371)
  Include/internal/pycore_frame.h
  Lib/test/test_generators.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-28-10-08-06.gh-issue-94262.m-HWUZ.rst
  Objects/codeobject.c
  Objects/frameobject.c
  Python/frame.c
  Python/sysmodule.c
Labels: awaiting review

#94545 gh-93939: Add script to check extension modules
  Makefile.pre.in
  Misc/NEWS.d/next/Tools-Demos/2022-07-04-10-02-02.gh-issue-93939.U6sW6H.rst
  Tools/scripts/check_extension_modules.py
  Tools/scripts/generate_stdlib_module_names.py
Labels: awaiting core review

#93628 gh-93626: Set the release for `__future__.annotations` to `None`
  Doc/whatsnew/3.11.rst
  Lib/__future__.py
  Misc/NEWS.d/next/Library/2022-06-09-14-44-21.gh-issue-93626.sfghs46.rst
Labels: awaiting changes, needs backport to 3.11

#94553 [3.11] gh-93626: Set the release for `__future__.annotations` to `None` (GH-93628)
  Doc/whatsnew/3.11.rst
  Lib/__future__.py
  Misc/NEWS.d/next/Library/2022-06-09-14-44-21.gh-issue-93626.sfghs46.rst
Labels: awaiting review

#94380 gh-94379: Remove zipimport find_loader() and find_module() methods
  Doc/whatsnew/3.12.rst
  Lib/test/test_zipimport.py
  Lib/zipimport.py
  Misc/NEWS.d/next/Library/2022-06-28-14-29-21.gh-issue-94379.RrgKfh.rst
Labels: awaiting merge

#94554 gh-84753: Clarify change made to `inspect` functions
  Misc/NEWS.d/next/Library/2022-06-21-11-40-31.gh-issue-84753.FW1pxO.rst
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11

#94559 [3.10] gh-84753: Clarify change made to `inspect` functions (GH-94554)
  Misc/NEWS.d/next/Library/2022-06-21-11-40-31.gh-issue-84753.FW1pxO.rst
Labels: awaiting review

#94556 [3.10] gh-94538: Fix Argument Clinic output to custom file (GH-94539)
  Misc/NEWS.d/next/Tools-Demos/2022-07-04-01-37-42.gh-issue-94538.1rgy1Y.rst
  Tools/clinic/clinic.py
Labels: awaiting review

#94555 [3.11] gh-94538: Fix Argument Clinic output to custom file (GH-94539)
  Misc/NEWS.d/next/Tools-Demos/2022-07-04-01-37-42.gh-issue-94538.1rgy1Y.rst
  Tools/clinic/clinic.py
Labels: awaiting review

#94560 [3.11] gh-84753: Clarify change made to `inspect` functions (GH-94554)
  Misc/NEWS.d/next/Library/2022-06-21-11-40-31.gh-issue-84753.FW1pxO.rst
Labels: awaiting review

#94552 gh-94485: Set line number of module's RESUME instruction to 0, as specified by PEP 626
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_code.py
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-01-20-00-19.gh-issue-94485.mo5st7.rst
  Programs/test_frozenmain.h
  Python/compile.c
Labels: type-bug, awaiting merge, needs backport to 3.11

#94562 [3.11] gh-94485: Set line number of module's RESUME instruction to 0 as specified by PEP 626 (GH-94552)
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_code.py
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-01-20-00-19.gh-issue-94485.mo5st7.rst
  Programs/test_frozenmain.h
  Python/compile.c
Labels: type-bug, awaiting merge

#31355 bpo-46755: Don't log stack info twice in QueueHandler
  Doc/library/logging.handlers.rst
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2022-02-15-12-40-48.bpo-46755.zePJfx.rst
Labels: CLA signed, awaiting review

#94565 [3.10] bpo-46755: Don't log stack info twice in QueueHandler (GH-31355) (GH-94565)
  Doc/library/logging.handlers.rst
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2022-02-15-12-40-48.bpo-46755.zePJfx.rst
Labels: awaiting core review

#92857 gh-90355: Add isolated flag if currently isolated
  Lib/ensurepip/__init__.py
  Misc/NEWS.d/next/Library/2022-01-03-15-07-06.bpo-46197.Z0djv6.rst
Labels: awaiting review, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#94569 [3.10] gh-90355: Add isolated flag if currently isolated (GH-92857)
  Lib/ensurepip/__init__.py
  Misc/NEWS.d/next/Library/2022-01-03-15-07-06.bpo-46197.Z0djv6.rst
Labels: awaiting review

#94570 [3.9] gh-90355: Add isolated flag if currently isolated (GH-92857)
  Lib/ensurepip/__init__.py
  Misc/NEWS.d/next/Library/2022-01-03-15-07-06.bpo-46197.Z0djv6.rst
Labels: awaiting core review

#94571 [3.8] gh-90355: Add isolated flag if currently isolated (GH-92857)
  Lib/ensurepip/__init__.py
  Misc/NEWS.d/next/Library/2022-01-03-15-07-06.bpo-46197.Z0djv6.rst
Labels: awaiting core review

#94573 [3.11] gh-94360: Fix a tokenizer crash when reading encoded files with syntax errors from stdin (GH-94386)
  Misc/NEWS.d/next/Core and Builtins/2022-06-28-14-20-36.gh-issue-94360.DiEnen.rst
  Parser/pegen_errors.c
  Parser/tokenizer.c
Labels: awaiting merge

#94424 gh-91330: Tests and docs for dataclass descriptor-typed fields
  Doc/library/dataclasses.rst
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Tests/2022-07-05-17-53-13.gh-issue-91330.Qys5IL.rst
Labels: tests, awaiting review, needs backport to 3.10, needs backport to 3.11

#94574 [3.10] gh-94360: Fix a tokenizer crash when reading encoded files with syntax errors from stdin (GH-94386)
  Misc/NEWS.d/next/Core and Builtins/2022-06-28-14-20-36.gh-issue-94360.DiEnen.rst
  Parser/pegen.c
  Parser/tokenizer.c
Labels: awaiting core review

#94511 gh-94510: Raise on re-entrant calls to sys.setprofile and sys.settrace
  Lib/test/test_sys_setprofile.py
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Library/2022-07-02-19-46-30.gh-issue-94510.xOatDC.rst
  Modules/_lsprof.c
  Python/ceval.c
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#94576 [3.11] gh-91330: Tests and docs for dataclass descriptor-typed fields (GH-94424)
  Doc/library/dataclasses.rst
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Tests/2022-07-05-17-53-13.gh-issue-91330.Qys5IL.rst
Labels: tests, awaiting review

#94577 [3.10] gh-91330: Tests and docs for dataclass descriptor-typed fields (GH-94424)
  Doc/library/dataclasses.rst
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Tests/2022-07-05-17-53-13.gh-issue-91330.Qys5IL.rst
Labels: tests, awaiting core review

#94579 [3.10] gh-94510: Raise on re-entrant calls to sys.setprofile and syssettrace (GH-94511)
  Lib/test/test_sys_setprofile.py
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Library/2022-07-02-19-46-30.gh-issue-94510.xOatDC.rst
  Modules/_lsprof.c
  Python/ceval.c
Labels: awaiting core review

#94578 [3.11] gh-94510: Raise on re-entrant calls to sys.setprofile and sys.settrace (GH-94511)
  Lib/test/test_sys_setprofile.py
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Library/2022-07-02-19-46-30.gh-issue-94510.xOatDC.rst
  Modules/_lsprof.c
  Python/ceval.c
Labels: awaiting merge

#94582 gh-94438: in frameobject's mark_stacks switch, the PUSH_EXC_INFO and POP_EXCEPT cases are no longer reachable
  Objects/frameobject.c
Labels: awaiting merge, skip news, needs backport to 3.11

#94593 GH-93896: always set event loop in asyncio.run and IsolatedAsyncioTestCase
  Lib/asyncio/runners.py
  Lib/test/test_asyncio/test_runners.py
  Misc/NEWS.d/next/Library/2022-07-06-06-02-02.gh-issue-93896.vIgWGr.rst
Labels: awaiting merge, release-blocker, needs backport to 3.11

#94608 [3.11] GH-93896: Always set event loop in asyncio.run and IsolatedAsyncioTestCase (GH-94593)
  Lib/asyncio/runners.py
  Lib/test/test_asyncio/test_runners.py
  Misc/NEWS.d/next/Library/2022-07-06-06-02-02.gh-issue-93896.vIgWGr.rst
Labels: awaiting merge

#94320 gh-94017: Improve clarity of sqlite3 transaction handling docs
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#94618 [3.10] gh-94017: Improve clarity of sqlite3 transaction handling docs (GH-94320)
  Doc/library/sqlite3.rst
Labels: docs, awaiting merge, skip news

#94617 [3.11] gh-94017: Improve clarity of sqlite3 transaction handling docs (GH-94320)
  Doc/library/sqlite3.rst
Labels: docs, awaiting merge, skip news

#94631 gh-94630: Update sqlite3 docs with positional-only and keyword-only symbols
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#94634 [3.10] gh-94630: Update sqlite3 docs with positional-only and keyword-only symbols (GH-94631)
  Doc/library/sqlite3.rst
Labels: docs, awaiting merge, skip news

#94633 [3.11] gh-94630: Update sqlite3 docs with positional-only and keyword-only symbols (GH-94631)
  Doc/library/sqlite3.rst
Labels: docs, awaiting merge, skip news

#94592 gh-92228: disable the compiler's 'small exit block inlining' optimization for blocks that have a line number
  Lib/test/test_dis.py
  Lib/test/test_peepholer.py
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-06-14-02-26.gh-issue-92228.44Cbly.rst
  Python/compile.c
Labels: awaiting merge, :robot: automerge, interpreter-core, needs backport to 3.11

#94629 gh-94628: Add explicit parameter list to sqlite3.connect docs
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#94645 [3.11] gh-94628: Add explicit parameter list to sqlite3.connect docs (GH-94629)
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news

#94646 [3.10] gh-94628: Add explicit parameter list to sqlite3.connect docs (GH-94629)
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news

#94431 gh-94430: Allow parameters named `module` or `self` with custom C names in Argument Clinic
  Lib/test/clinic.test
  Misc/NEWS.d/next/Tools-Demos/2022-06-29-22-47-11.gh-issue-94430.hdov8L.rst
  Tools/clinic/clinic.py
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#94643 [3.11] gh-92228: disable the compiler's 'small exit block inlining' optimization for blocks that have a line number (GH-94592)
  Lib/test/test_dis.py
  Lib/test/test_peepholer.py
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-06-14-02-26.gh-issue-92228.44Cbly.rst
  Python/compile.c
Labels: awaiting merge, :robot: automerge

#94649 [3.11] gh-94430: Allow params named `module` or `self` with custom C names in AC (GH-94431)
  Lib/test/clinic.test
  Misc/NEWS.d/next/Tools-Demos/2022-06-29-22-47-11.gh-issue-94430.hdov8L.rst
  Tools/clinic/clinic.py
Labels: awaiting core review

#94650 [3.10] gh-94430: Allow params named `module` or `self` with custom C names in AC (GH-94431)
  Lib/test/clinic.test
  Misc/NEWS.d/next/Tools-Demos/2022-06-29-22-47-11.gh-issue-94430.hdov8L.rst
  Tools/clinic/clinic.py
Labels: awaiting core review

#94614 gh-93910: Fix enum performance regression
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2022-07-06-14-45-12.gh-issue-93910.iZcp67.rst
Labels: awaiting merge, :robot: automerge, stdlib, needs backport to 3.11

#94654 [3.10] GH-94644: fix test_curses ref leak (GH-94647)
  Modules/_cursesmodule.c
Labels: awaiting merge, skip news

#94653 [3.11] GH-94644: fix test_curses ref leak (GH-94647)
  Modules/_cursesmodule.c
Labels: awaiting merge, skip news

#94657 gh-94642: Remove -D_XOPEN_SOURCE from more pkg-config CFLAGS
  configure
  configure.ac
Labels: awaiting core review, skip news, build, 3.12

#94581 gh-94343: Ease initialization of reprlib.Repr attributes
  Doc/library/reprlib.rst
  Lib/reprlib.py
  Lib/test/test_reprlib.py
  Misc/NEWS.d/next/Library/2022-07-05-17-22-00.gh-issue-94343.kf4H5r.rst
Labels: awaiting merge

#94611 gh-93654: Add module docstring to pathlib
  Lib/pathlib.py
Labels: awaiting merge, skip news, :robot: automerge

#94051 GH-90699: Move generated static initializer to pycore_runtime_generated.h
  .gitattributes
  Include/internal/pycore_runtime_init.h
  Include/internal/pycore_runtime_init_generated.h
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Tools/scripts/generate_global_objects.py
Labels: awaiting merge, skip news, :robot: automerge

#94665 [3.10] gh-92743 - Fix #92743 for python 3.10 - Remove copyright sign next to "Raymond Hettinger"
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news

#94670 [3.11] gh-94321: Document sqlite3.PrepareProtocol (GH-94620)
  Doc/library/sqlite3.rst
  Misc/NEWS.d/next/Documentation/2022-07-07-08-42-05.gh-issue-94321.pmCIPb.rst
  Modules/_sqlite/prepare_protocol.c
Labels: awaiting merge

#94671 [3.10] gh-94321: Document sqlite3.PrepareProtocol (GH-94620)
  Doc/library/sqlite3.rst
  Misc/NEWS.d/next/Documentation/2022-07-07-08-42-05.gh-issue-94321.pmCIPb.rst
  Modules/_sqlite/prepare_protocol.c
Labels: awaiting core review

#94623 gh-94622: Add more references to the sqlite3 types anchor
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#94678 [3.11] gh-94622: Add more references to the sqlite3 types anchor (GH-94623)
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news

#94679 [3.10] gh-94622: Add more references to the sqlite3 types anchor (GH-94623)
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news

#94681 gh-94215: Fix error handling for line-tracing events
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-07-21-13-25.gh-issue-94215._Sv9Ms.rst
  Python/ceval.c
Labels: awaiting merge, interpreter-core, type-crash, needs backport to 3.11

#92762 Use mdash-es consistently in the library docs index
  Doc/library/2to3.rst
Labels: docs, skip issue, awaiting merge, skip news

#94689 [3.10] Use mdash-es consistently in the library docs index (GH-92762)
  Doc/library/2to3.rst
Labels: docs, skip issue, awaiting merge, skip news

#94690 [3.11] Use mdash-es consistently in the library docs index (GH-92762)
  Doc/library/2to3.rst
Labels: docs, skip issue, awaiting merge, skip news

#93597 GH-90699: Intern statically allocated strings
  Include/internal/pycore_runtime_init_generated.h
  Objects/unicodeobject.c
  Tools/scripts/generate_global_objects.py
Labels: awaiting merge, skip news, :robot: automerge

#94674 Increase test coverage of Objects/exceptions.c
  Lib/test/test_exception_group.py
  Lib/test/test_exceptions.py
Labels: tests, skip issue, awaiting core review, skip news

#94693 GH-93252: Fix error handling for failed Python calls
  Lib/test/test_call.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-08-11-44-45.gh-issue-93252.i2358c.rst
  Python/ceval.c
Labels: awaiting merge, interpreter-core, type-crash, needs backport to 3.11

#94610 gh-94607: Fix subclassing generics
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-07-06-16-01-08.gh-issue-94607.Q6RYfz.rst
  Objects/genericaliasobject.c
Labels: type-bug, awaiting merge, expert-typing, needs backport to 3.11

#94701 gh-94700: Rewrite the logging.Formatter API ref in structured form (GH-94701)
  Doc/library/logging.rst
Labels: docs, awaiting merge, skip news

#94704 [3.11] gh-94607: Fix subclassing generics (GH-94610)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-07-06-16-01-08.gh-issue-94607.Q6RYfz.rst
  Objects/genericaliasobject.c
Labels: type-bug, awaiting merge

#94695 gh-93649: Fix dependencies of _testcapi
  Makefile.pre.in
  configure
  configure.ac
Labels: awaiting core review, skip news, build

#94708 [3.11] GH-93252: Fix error handling for failed Python calls (GH-94693)
  Lib/test/test_call.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-08-11-44-45.gh-issue-93252.i2358c.rst
  Python/ceval.c
Labels: awaiting merge, :robot: automerge, type-crash

#93188 Comment nit: fix comment reference in pycore_interp.h
  Include/internal/pycore_interp.h
Labels: skip issue, awaiting core review, skip news

#94658 gh-94637: Release GIL in SSLContext.set_default_verify_paths (GH-94658)
  Misc/NEWS.d/next/Library/2022-07-07-15-46-55.gh-issue-94637.IYEiUM.rst
  Modules/_ssl.c
Labels: performance, awaiting core review, :robot: automerge, needs backport to 3.10, stdlib, needs backport to 3.11

#94711 [3.11] gh-94637: Release GIL in SSLContext.set_default_verify_paths (GH-94658)
  Misc/NEWS.d/next/Library/2022-07-07-15-46-55.gh-issue-94637.IYEiUM.rst
  Modules/_ssl.c
Labels: awaiting merge

#94712 [3.10] gh-94637: Release GIL in SSLContext.set_default_verify_paths (GH-94658)
  Misc/NEWS.d/next/Library/2022-07-07-15-46-55.gh-issue-94637.IYEiUM.rst
  Modules/_ssl.c
Labels: awaiting merge

#94686 Improve dataclass docstring
  Lib/dataclasses.py
Labels: skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#94716 [3.11] Improve dataclass docstring (gh-94686)
  Lib/dataclasses.py
Labels: skip issue, awaiting merge, skip news

#94697 GH-94694: Fix column offsets for multi-line method lookups
  Lib/test/test_compile.py
  Lib/test/test_traceback.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-08-16-44-11.gh-issue-94694.VkL2CM.rst
  Python/compile.c
Labels: awaiting core review, interpreter-core, needs backport to 3.11

#94721 [3.11] GH-94694: Fix column offsets for multi-line method lookups (GH-94697)
  Lib/test/test_compile.py
  Lib/test/test_traceback.py
  Misc/NEWS.d/next/Core and Builtins/2022-07-08-16-44-11.gh-issue-94694.VkL2CM.rst
  Python/compile.c
Labels: awaiting core review, interpreter-core

#94676 GH-77265: Document NaN handling in statistics functions that sort or count
  Doc/library/statistics.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#94726 [3.11] GH-77265: Document NaN handling in statistics functions that sort or count (GH-94676)
  Doc/library/statistics.rst
Labels: docs, awaiting review, skip news

#94725 [3.10] GH-77265: Document NaN handling in statistics functions that sort or count (GH-94676)
  Doc/library/statistics.rst
Labels: docs, awaiting review, skip news

#94626 gh-94309: Deprecate typing.Hashable/Sized
  Doc/library/typing.rst
  Misc/NEWS.d/next/Library/2022-07-06-22-41-51.gh-issue-94309._XswsX.rst
Labels: type-feature, docs, awaiting merge, expert-typing

#94730 Small speed-up for NormalDist.samples()
  Lib/statistics.py
Labels: performance, skip issue, awaiting core review, skip news

#93994 gh-93883: elide traceback indicators when possible
  Doc/library/traceback.rst
  Doc/whatsnew/3.11.rst
  Lib/idlelib/idle_test/test_run.py
  Lib/test/test_cmd_line_script.py
  Lib/test/test_doctest.py
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-24-14-06-20.gh-issue-93883.8jVQQ4.rst
  Python/traceback.c
Labels: awaiting merge

#94691 gh-87822: Make traceback module robust to exceptions from repr() of local values
  Doc/library/traceback.rst
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2022-07-08-17-49-12.gh-issue-87822.F9dzkf.rst
Labels: type-feature, awaiting merge, stdlib, 3.12

#94737 gh-93883: Fix some test involving traceback formatting
  Lib/test/test_traceback.py
Labels: tests, awaiting merge, skip news

#94740 [3.11] gh-93883: elide traceback indicators when possible (GH-93994)
  Doc/library/traceback.rst
  Doc/whatsnew/3.11.rst
  Lib/idlelib/idle_test/test_run.py
  Lib/test/test_cmd_line_script.py
  Lib/test/test_doctest.py
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Core and Builtins/2022-06-24-14-06-20.gh-issue-93883.8jVQQ4.rst
  Python/traceback.c
Labels: awaiting merge, :robot: automerge

#94738 GH-94736: Fix _multiprocessing.SemLock subclassing
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2022-07-11-10-41-48.gh-issue-94736.EbsgeK.rst
  Modules/_multiprocessing/semaphore.c
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11, expert-multiprocessing

#30274 bpo-45924: Fix asyncio incorrect traceback when future's exception is raised multiple times
  Lib/asyncio/futures.py
  Lib/test/test_asyncio/test_futures2.py
  Misc/NEWS.d/next/Library/2021-12-27-15-32-15.bpo-45924.0ZpHX2.rst
  Modules/_asynciomodule.c
Labels: type-bug, CLA signed, awaiting merge, needs backport to 3.10, needs backport to 3.11

#94743 [3.11] GH-94736: Fix _multiprocessing.SemLock subclassing (GH-94738)
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2022-07-11-10-41-48.gh-issue-94736.EbsgeK.rst
  Modules/_multiprocessing/semaphore.c
Labels: awaiting merge

#94747 [3.11] bpo-45924: Fix asyncio incorrect traceback when future's exception is raised multiple times (GH-30274)
  Lib/asyncio/futures.py
  Lib/test/test_asyncio/test_futures2.py
  Misc/NEWS.d/next/Library/2021-12-27-15-32-15.bpo-45924.0ZpHX2.rst
  Modules/_asynciomodule.c
Labels: type-bug, awaiting review

#94750 GH-94736: mark SemLock test as linux only
  Lib/test/_test_multiprocessing.py
Labels: awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#94752 [3.11] GH-94736: mark SemLock test as linux only (GH-94750)
  Lib/test/_test_multiprocessing.py
Labels: awaiting merge, skip news

#94753 [3.10] GH-94736: mark SemLock test as linux only (GH-94750)
  Lib/test/_test_multiprocessing.py
Labels: awaiting review, skip news

#94754 gh-94751: Install, import and run the test C++ extension (MVP)
  Lib/test/_testcppext.cpp
  Lib/test/setup_testcppext.py
  Lib/test/test_cppext.py
Labels: tests, awaiting core review, skip news, needs backport to 3.11

#94775 gh-94773: deepfreeze: support frozensets with unsortable types (GH-94775)
  Misc/NEWS.d/next/Build/2022-07-12-13-39-18.gh-issue-94773.koHKm5.rst
  Tools/scripts/deepfreeze.py
Labels: awaiting core review, needs backport to 3.11

#94783 [3.11] gh-94773: deepfreeze: support frozensets with unsortable types (GH-94775)
  Misc/NEWS.d/next/Build/2022-07-12-13-39-18.gh-issue-94773.koHKm5.rst
  Tools/scripts/deepfreeze.py
Labels: awaiting merge

#94771 docs: typing.Self, fix typo
  Doc/library/typing.rst
  Lib/typing.py
Labels: docs, skip issue, skip news, expert-typing, needs backport to 3.11

#94786 [3.11] docs: typing.Self, fix typo (GH-94771)
  Doc/library/typing.rst
  Lib/typing.py
Labels: skip issue, awaiting merge, skip news

#94762 Fix heading levels for "Deprecated" section in What's New for 3.12
  Doc/whatsnew/3.12.rst
Labels: docs, skip issue, awaiting merge, skip news

#94792 [3.11] Fix typo in _exact_ratio comment. (GH-94789)
  Lib/statistics.py
Labels: skip issue, awaiting merge, skip news

#94714 gh-94713 - Replacing while 1 with while True
  Lib/platform.py
Labels: skip issue, awaiting core review, skip news

#94780 [3.11] gh-94751: Install, import and run the test C++ extension (MVP) (GH-94754)
  Lib/test/_testcppext.cpp
  Lib/test/setup_testcppext.py
  Lib/test/test_cppext.py
Labels: awaiting review, skip news

#94702 gh-93649: Fix linkage of _PyTestCapi_Init_Vectorcall
  Modules/_testcapi/parts.h
Labels: awaiting core review, skip news

#94793 gh-94759: Create LCOV report with branch coverage (GH-94793)
  Makefile.pre.in
Labels: awaiting core review, skip news, build, needs backport to 3.11

#94719 GH-81620: Add random.binomialvariate()
  Doc/library/random.rst
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2022-07-09-15-17-02.gh-issue-81620.L0O_bV.rst
Labels: type-feature, awaiting core review, stdlib

#94804 [3.11] gh-94759: Create LCOV report with branch coverage (GH-94793)
  Makefile.pre.in
Labels: awaiting merge, skip news

#94790 gh-90815: Fix test_embed for Windows PGO build with mimalloc
  Programs/_testembed.c
Labels: awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#94500 gh-94499 Add test for private name mangling in class pattern matching
  Lib/test/test_patma.py
Labels: tests, awaiting merge, skip news

#94806 [3.10] gh-90815: Fix test_embed for Windows PGO build with mimalloc (GH-94790)
  Programs/_testembed.c
Labels: awaiting merge, skip news

#94805 [3.11] gh-90815: Fix test_embed for Windows PGO build with mimalloc (GH-94790)
  Programs/_testembed.c
Labels: awaiting merge, skip news

#94800 gh-90359: Update documentation to follow PEP 495.
  Doc/c-api/datetime.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#94829 [3.11] gh-90359: Update documentation to follow PEP 495. (gh-94800)
  Doc/c-api/datetime.rst
Labels: docs, awaiting merge, skip news

#94830 [3.10] gh-90359: Update documentation to follow PEP 495. (gh-94800)
  Doc/c-api/datetime.rst
Labels: docs, awaiting merge, skip news

#94836 gh-90359: Unify documentation style for datetime.rst
  Doc/c-api/datetime.rst
Labels: skip news, needs backport to 3.10, needs backport to 3.11

#94837 [3.10] gh-90359: Unify documentation style for datetime.rst (gh-94836)
  Doc/c-api/datetime.rst
Labels: docs, awaiting merge, skip news

#94838 [3.11] gh-90359: Unify documentation style for datetime.rst (gh-94836)
  Doc/c-api/datetime.rst
Labels: docs, awaiting core review, skip news

#94827 idlelib: replace 'while 1' with 'while True'
  Lib/idlelib/editor.py
  Lib/idlelib/history.py
  Lib/idlelib/hyperparser.py
  Lib/idlelib/rpc.py
  Lib/idlelib/run.py
  Lib/idlelib/searchengine.py
Labels: skip issue, awaiting core review, skip news, needs backport to 3.10, expert-IDLE, needs backport to 3.11
