Repository python/cpython, pull requests merged in 2022-05, with the labels that each got.

#92090 gh-91954: Use shell=True in test_subprocess.test_encoding_warning
  Lib/test/test_subprocess.py
Labels: tests, awaiting merge, skip news

#91982 gh-91952: Make TextIOWrapper.reconfigure() supports "locale" encoding
  Doc/library/io.rst
  Lib/_pyio.py
  Misc/NEWS.d/next/Library/2022-04-27-18-04-24.gh-issue-91952.9A4RXx.rst
  Modules/_io/textio.c
Labels: awaiting core review

#92096 [3.9] gh-91611: Use example.com for documentation, not mydomain.com (GH-91613)
  Doc/library/secrets.rst
  Doc/library/ssl.rst
Labels: docs, awaiting merge, skip news

#92095 [3.10] gh-91611: Use example.com for documentation, not mydomain.com (GH-91613)
  Doc/library/secrets.rst
  Doc/library/ssl.rst
Labels: docs, awaiting merge, skip news

#92087 gh-81488: Add recursive wording for issubclass
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#92101 [3.10] gh-81488: Add recursive wording for issubclass docs (GH-92087)
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news

#20386 Add typing example for async functions.
  Doc/library/typing.rst
Labels: CLA signed, docs, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10, expert-typing

#92103 [3.10] typing docs: Add example for async functions (GH-20386)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news

#92104 [3.9] typing docs: Add example for async functions (GH-20386)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news

#18605 bpo-39716: Raise on conflicting subparser names.
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2020-02-22-12-02-11.bpo-39716.z2WhDQ.rst
Labels: CLA signed, awaiting merge, :robot: automerge

#92102 [3.9] gh-92049: Forbid pickling constants re._constants.SUCCES…
  Lib/sre_constants.py
  Misc/NEWS.d/next/Library/2022-04-30-10-53-10.gh-issue-92049.5SEKoh.rst
Labels: type-bug, awaiting core review

#91932 [3.10] gh-91401: Conservative backport of `subprocess._USE_VFORK`
  Lib/subprocess.py
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Library/2022-04-26-00-10-06.gh-issue-91401.mddRC8.rst
  Modules/_posixsubprocess.c
Labels: type-bug, type-feature, awaiting core review, stdlib, extension-modules

#92127 [3.10] build(deps): bump actions/stale from 4 to 5 (GH-92108)
  .github/workflows/stale.yml
Labels: skip issue, awaiting core review, skip news

#92125 [3.9] build(deps): bump actions/cache from 3.0.1 to 3.0.2 (GH-92111)
  .github/workflows/build.yml
Labels: skip issue, awaiting core review, skip news

#92040 gh-91998: 'WebAssemby' to 'WebAssembly'
  Doc/using/configure.rst
Labels: docs, skip issue, awaiting merge, skip news

#92115 gh-92114: Improve error message for types with __class_getitem__ = None
  Lib/test/test_genericclass.py
  Misc/NEWS.d/next/Core and Builtins/2022-05-01-16-40-07.gh-issue-92114.5xTlLt.rst
  Objects/abstract.c
Labels: type-feature, awaiting merge, expert-typing

#92071 gh-90822: Redefined `PY_SSIZE_T_MAX` and `PY_SSIZE_T_MIN`
  Include/pyport.h
  PC/pyconfig.h
Labels: awaiting merge, skip news

#91778 gh-85679: Recommend `encoding="utf-8"` in tutorial
  Doc/tutorial/inputoutput.rst
Labels: docs, awaiting change review, skip news, needs backport to 3.9, needs backport to 3.10

#92133 [3.10] gh-85679: Recommend `encoding="utf-8"` in tutorial (GH-91778)
  Doc/tutorial/inputoutput.rst
Labels: docs, awaiting merge, skip news

#92134 [3.9] gh-85679: Recommend `encoding="utf-8"` in tutorial (GH-91778)
  Doc/tutorial/inputoutput.rst
Labels: docs, awaiting merge, skip news

#28593 bpo-36819: Fix crashes in built-in encoders with weird error handlers
  Lib/test/test_codeccallbacks.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-28-10-58-30.bpo-36819.cyV50C.rst
  Objects/stringlib/codecs.h
  Objects/unicodeobject.c
Labels: type-bug, CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#92136 [3.10] bpo-36819: Fix crashes in built-in encoders with weird error handlers (GH-28593)
  Lib/test/test_codeccallbacks.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-28-10-58-30.bpo-36819.cyV50C.rst
  Objects/stringlib/codecs.h
  Objects/unicodeobject.c
Labels: type-bug, awaiting merge

#92137 [3.9] bpo-36819: Fix crashes in built-in encoders with weird error handlers (GH-28593)
  Lib/test/test_codeccallbacks.py
  Misc/NEWS.d/next/Core and Builtins/2021-09-28-10-58-30.bpo-36819.cyV50C.rst
  Objects/stringlib/codecs.h
  Objects/unicodeobject.c
Labels: type-bug, awaiting merge

#32175 gh-91321: Add _testcppext C++ extension
  Lib/test/_testcppext.cpp
  Lib/test/test_cppext.py
Labels: CLA signed, awaiting core review, skip news

#92141 gh-88097: doc: fix link to Py_Version
  Doc/c-api/init.rst
Labels: docs, awaiting core review, skip news

#92053 gh-89301: Fix regression with bound values in traced SQLite statements
  Lib/test/test_sqlite3/test_hooks.py
  Misc/NEWS.d/next/Library/2021-09-08-16-21-03.bpo-45138.yghUrK.rst
  Modules/_sqlite/connection.c
Labels: awaiting merge, needs backport to 3.10

#91867 gh-84714: Add behavior if dst file exists
  Doc/library/shutil.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#92131 [3.9] gh-81488: Add recursive wording for issubclass docs (GH-92087).
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news

#91874 gh-85133: Add that getenv uses os.environ
  Doc/library/os.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#92144 [3.10] gh-84714: Add behavior if dst file exists (GH-91867)
  Doc/library/shutil.rst
Labels: docs, awaiting merge, skip news

#92143 [3.9] gh-84714: Add behavior if dst file exists (GH-91867)
  Doc/library/shutil.rst
Labels: docs, awaiting merge, skip news

#92145 [3.10] gh-85133: os docs: Add that getenv uses os.environ (GH-91874)
  Doc/library/os.rst
Labels: docs, awaiting merge, skip news

#92083 Fix typo in Programming FAQ
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#92030 Fix a typo in doc
  Doc/library/asyncio-subprocess.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#91995 gh-91063: Update Windows installer to SQLite 3.38.3.
  Misc/NEWS.d/next/Windows/2022-04-27-19-36-56.bpo-46907.lfurlP.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
  PCbuild/sqlite3.vcxproj
Labels: awaiting core review

#92138 gh-92135: Fix _Py_reinterpret_cast() for const
  Include/methodobject.h
  Include/objimpl.h
  Include/pyport.h
  Lib/test/_testcppext.cpp
  Lib/test/test_cppext.py
Labels: awaiting core review, skip news

#92146 [3.9] gh-85133: os docs: Add that getenv uses os.environ (GH-91874)
  Doc/library/os.rst
Labels: docs, awaiting merge, skip news

#92129 gh-92128: Add `__class_getitem__` to `logging.LoggerAdapter` and `logging.StreamHandler`
  Lib/logging/__init__.py
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Library/2022-05-01-21-45-41.gh-issue-92128.Di7VbE.rst
Labels: type-feature, awaiting merge, stdlib, expert-typing

#91614 gh-88546: Make new paragraph for emphasis and reordered sentence
  Doc/library/glob.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#92150 [3.10] asyncio.subprocess: Fix a typo in doc (GH-92030)
  Doc/library/asyncio-subprocess.rst
Labels: docs, skip issue, awaiting merge, skip news

#92149 [3.9] Fix typo in Programming FAQ (GH-92083)
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting merge, skip news

#92151 [3.9] asyncio.subprocess: Fix a typo in doc (GH-92030)
  Doc/library/asyncio-subprocess.rst
Labels: docs, skip issue, awaiting merge, skip news

#92157 [3.9] gh-88546: glob.glob docs: Make new paragraph for emphasis and reordered sentence (GH-91614)
  Doc/library/glob.rst
Labels: docs, awaiting merge, skip news

#92156 [3.10] gh-88546: glob.glob docs: Make new paragraph for emphasis and reordered sentence (GH-91614)
  Doc/library/glob.rst
Labels: docs, awaiting merge, skip news

#92152 [3.10] concurrent.futures: Fix typo in docstring (GH-92121)
  Lib/concurrent/futures/_base.py
Labels: skip issue, awaiting merge, skip news

#92147 [3.10] gh-89301: Fix regression with bound values in traced SQLite statements
  Lib/sqlite3/test/hooks.py
  Misc/NEWS.d/next/Library/2021-09-08-16-21-03.bpo-45138.yghUrK.rst
  Modules/_sqlite/connection.c
Labels: awaiting merge

#92153 [3.9] concurrent.futures: Fix typo in docstring (GH-92121)
  Lib/concurrent/futures/_base.py
Labels: skip issue, awaiting merge, skip news

#92160 gh-91215: Add weakref_slot to `@dataclass`, to allow instances with slots to be weakref-able.
  Doc/library/dataclasses.rst
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2022-05-02-09-09-47.gh-issue-91215.l1p7CJ.rst
Labels: awaiting merge

#92163 [3.10] gh-92082: contextlib docs: Change aclosing from a class to a function for consistency (GH-92155)
  Doc/library/contextlib.rst
Labels: docs, awaiting merge, skip news

#91862 Fix typo in turtle deprecation warning and use warnings._deprecated
  Lib/turtle.py
Labels: skip issue, awaiting merge, skip news

#91835 Improve efficiency of lehvenshtein_distance method
  Python/suggestions.c
Labels: skip issue, awaiting merge, skip news

#91844 gh-91783: Document security considerations for shutil.unpack_archive
  Doc/library/shutil.rst
  Misc/NEWS.d/next/Documentation/2022-04-23-00-22-54.gh-issue-91783.N09dRR.rst
Labels: docs, awaiting merge, needs backport to 3.9, needs backport to 3.10

#30277 gh-90213: Speed up right shifts of negative integers
  Lib/test/test_long.py
  Misc/NEWS.d/next/Core and Builtins/2022-04-12-09-40-57.gh-issue-46055.IPb1HA.rst
  Objects/longobject.c
Labels: CLA signed, performance, awaiting core review

#91480 gh-90765: Catch LegacyInterpolation deprecation warning
  Lib/test/test_configparser.py
Labels: tests, skip issue, awaiting merge, skip news

#92148 [3.10] Fix typo in Programming FAQ (GH-92083)
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting merge, skip news, :robot: automerge

#92165 [3.10] gh-91783: Document security considerations for shutil.unpack_archive (GH-91844)
  Doc/library/shutil.rst
  Misc/NEWS.d/next/Documentation/2022-04-23-00-22-54.gh-issue-91783.N09dRR.rst
Labels: docs, awaiting merge

#92166 [3.9] gh-91783: Document security considerations for shutil.unpack_archive (GH-91844)
  Doc/library/shutil.rst
  Misc/NEWS.d/next/Documentation/2022-04-23-00-22-54.gh-issue-91783.N09dRR.rst
Labels: docs, awaiting merge

#92161 [3.10] bpo-43504: Remove effbot urls (GH-26308)
  Doc/about.rst
  Doc/faq/library.rst
  Doc/howto/curses.rst
  Doc/library/xml.etree.elementtree.rst
  Doc/library/xmlrpc.client.rst
  Lib/xml/etree/ElementPath.py
  Objects/stringlib/fastsearch.h
Labels: awaiting merge, skip news

#92162 [3.9] bpo-43504: Remove effbot urls (GH-26308)
  Doc/about.rst
  Doc/faq/library.rst
  Doc/howto/curses.rst
  Doc/library/xml.etree.elementtree.rst
  Doc/library/xmlrpc.client.rst
  Lib/xml/etree/ElementPath.py
  Objects/stringlib/fastsearch.h
Labels: awaiting merge, skip news

#92059 gh-87390: Add __unpacked__ attribute to types.GenericAlias
  Doc/library/stdtypes.rst
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Library/2022-04-29-16-41-08.gh-issue-87390.3LNNCv.rst
  Objects/genericaliasobject.c
Labels: awaiting merge

#92182 Fix duplicate word.
  Doc/library/asyncio-runner.rst
Labels: docs, skip issue, awaiting merge, skip news

#92175 gh-92173: Fix the closure argument to PyEval_EvalCodeEx.
  Misc/NEWS.d/next/C API/2022-05-02-12-39-33.gh-issue-92173.len2Is.rst
  Objects/funcobject.c
Labels: awaiting core review

#31408 bpo-46787: Fix `ProcessPoolExecutor` exception memory leak
  Lib/concurrent/futures/process.py
  Misc/NEWS.d/next/Library/2022-02-18-20-09-29.bpo-46787.juwWc0.rst
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10

#31113 Update importlib.abc hierarchy
  Doc/library/importlib.rst
Labels: CLA signed, docs, skip issue, awaiting merge, skip news, needs backport to 3.10

#92189 [3.10] importlib docs: Update importlib.abc hierarchy (GH-31113)
  Doc/library/importlib.rst
Labels: docs, skip issue, awaiting merge, skip news

#30957 bpo-46547: remove leaking vars into `pydoc.Helper` namespace
  Lib/pydoc.py
  Misc/NEWS.d/next/Library/2022-01-27-14-41-55.bpo-46547.JMyYz9.rst
Labels: CLA signed, awaiting merge

#30612 bpo-6686: Replaced String with Bytes in xml.sax.handler documentation
  Doc/library/xml.sax.handler.rst
Labels: CLA signed, docs, awaiting merge, skip news, stale, needs backport to 3.9, needs backport to 3.10

#30999 bpo-46285: Add command-line option -p/--protocol to module http.server
  Doc/library/http.server.rst
  Lib/http/server.py
  Misc/NEWS.d/next/Library/2022-01-29-00-23-00.bpo-46285.pt84qm.rst
Labels: CLA signed, awaiting merge

#31117 Delete outdated comment in logging module
  Lib/logging/__init__.py
Labels: CLA signed, skip issue, awaiting merge, skip news

#31429 bpo-46586: Fix more erroneous doc links to builtins
  Doc/library/fileinput.rst
  Doc/library/urllib.request.rst
  Doc/library/zipfile.rst
Labels: CLA signed, docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#92029 gh-92032: Add soft keywords to rlcompleter
  Lib/rlcompleter.py
  Lib/test/test_rlcompleter.py
  Misc/NEWS.d/next/Core and Builtins/2022-04-28-20-19-49.gh-issue-92032.ef-UfM.rst
Labels: awaiting merge

#92176 gh-92106: Add test that subscription works on arbitrary TypedDicts
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news

#92027 bpo-43923: Add support of generic typing.NamedTuple
  Doc/library/typing.rst
  Doc/whatsnew/3.11.rst
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-04-28-18-45-58.gh-issue-88089.hu9kRk.rst
Labels: type-feature, awaiting merge, expert-typing

#92195 [3.10] bpo-6686: Replace String with Bytes in xml.sax.handler documentation (GH-30612)
  Doc/library/xml.sax.handler.rst
Labels: docs, awaiting merge, skip news

#92187 [3.10] bpo-46787: Fix `ProcessPoolExecutor exception` memory leak (GH-31408) (GH-31408)
  Lib/concurrent/futures/process.py
  Misc/NEWS.d/next/Library/2022-02-18-20-09-29.bpo-46787.juwWc0.rst
Labels: awaiting merge

#92196 [3.9] bpo-6686: Replace String with Bytes in xml.sax.handler documentation (GH-30612)
  Doc/library/xml.sax.handler.rst
Labels: docs, awaiting merge, skip news

#92188 [3.9] bpo-46787: Fix `ProcessPoolExecutor exception` memory leak (GH-31408) (GH-31408)
  Lib/concurrent/futures/process.py
  Misc/NEWS.d/next/Library/2022-02-18-20-09-29.bpo-46787.juwWc0.rst
Labels: awaiting merge

#92198 [3.10] bpo-46586: Fix more erroneous doc links to builtins (GH-31429)
  Doc/library/fileinput.rst
  Doc/library/urllib.request.rst
  Doc/library/zipfile.rst
Labels: docs, awaiting merge, skip news

#91930 gh-84461: Add ability for multiprocessed libregrtest to use a different Python executable
  Lib/test/libregrtest/cmdline.py
  Lib/test/libregrtest/runtest_mp.py
  Misc/NEWS.d/next/Tests/2022-05-02-20-15-54.gh-issue-84461.DhxllI.rst
Labels: awaiting merge, :robot: automerge

#91656 gh-91621: Fix typing.get_type_hints for collections.abc.Callable
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2022-04-18-18-55-21.gh-issue-91621.ACNlda.rst
Labels: type-bug, awaiting merge, stdlib, expert-typing

#92200 [3.10] gh-92106: Add test that subscription works on arbitrary TypedDicts (GH-92176)
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news

#92201 [3.9] gh-92106: Add test that subscription works on arbitrary TypedDicts (GH-92176)
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news

#92207 gh-92206: Improve scoping of sqlite3 statement step helper
  Modules/_sqlite/cursor.c
  Modules/_sqlite/util.c
  Modules/_sqlite/util.h
Labels: awaiting merge, skip news

#30416 bpo-46267: Correctly use compresslevel in gzip.compress
  Lib/test/test_gzip.py
Labels: type-bug, CLA signed, awaiting merge, skip news

#92215 Fix doc warnings in What's New in 3.11
  Doc/whatsnew/3.11.rst
Labels: docs, skip issue, awaiting core review, skip news, :robot: automerge

#92170 gh-92169: Use warnings_helper.import_deprecated() in tests
  Lib/test/test_asynchat.py
  Lib/test/test_asyncore.py
  Lib/test/test_ftplib.py
  Lib/test/test_imp.py
  Lib/test/test_logging.py
  Lib/test/test_poplib.py
  Lib/test/test_smtpd.py
  Lib/test/test_smtplib.py
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Tests/2022-05-02-20-57-04.gh-issue-92169.Xi4NGV.rst
Labels: tests, awaiting merge

#92220 The stdev calculation is more accurate computing its own mean
  Lib/statistics.py
Labels: skip issue, awaiting core review, skip news, 3.11

#92079 [3.10] gh-91583: AC: Fix regression for functions with defining_class…
  Misc/NEWS.d/next/Tools-Demos/2022-04-20-14-26-14.gh-issue-91583.200qI0.rst
  Modules/clinic/_curses_panel.c.h
  Modules/clinic/_dbmmodule.c.h
  Modules/clinic/_gdbmmodule.c.h
  Modules/clinic/_lsprof.c.h
  Modules/clinic/_queuemodule.c.h
  Modules/clinic/_sre.c.h
  Modules/clinic/_testmultiphase.c.h
  Modules/clinic/arraymodule.c.h
  Modules/clinic/md5module.c.h
  Modules/clinic/posixmodule.c.h
  Modules/clinic/pyexpat.c.h
  Modules/clinic/sha1module.c.h
  Modules/clinic/sha256module.c.h
  Modules/clinic/sha512module.c.h
  Modules/clinic/zlibmodule.c.h
  Tools/clinic/clinic.py
Labels: awaiting core review

#92080 [3.9] gh-91583: AC: Fix regression for functions with defining_class …
  Misc/NEWS.d/next/Tools-Demos/2022-04-20-14-26-14.gh-issue-91583.200qI0.rst
  Modules/clinic/_testmultiphase.c.h
  Modules/clinic/posixmodule.c.h
  Tools/clinic/clinic.py
Labels: awaiting core review

#92199 [3.9] bpo-46586: Fix more erroneous doc links to builtins (GH-31429)
  Doc/library/urllib.request.rst
  Doc/library/zipfile.rst
Labels: docs, awaiting merge, skip news

#30642 bpo-46415: Use f-string for ValueError in ipaddress.ip_{address,network,interface} helper functions
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2022-01-17-16-53-30.bpo-46415.6wSYg-.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#29560 bpo-26175: Implement `io.IOBase` interface for `SpooledTemporaryFile`
  Doc/library/tempfile.rst
  Lib/tempfile.py
  Lib/test/test_tempfile.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2021-11-14-01-35-04.bpo-26175.LNlOfI.rst
Labels: CLA signed, awaiting merge, expert-IO

#92186 Dependabot: only bump actions for major versions
  .github/dependabot.yml
  .github/workflows/build.yml
Labels: skip issue, awaiting merge, skip news

#92212 gh-92206: Improve scoping of sqlite3 register cursor helper
  Modules/_sqlite/connection.c
  Modules/_sqlite/connection.h
  Modules/_sqlite/cursor.c
Labels: awaiting merge, skip news

#92226 [3.9] bpo-46415: Use f-string for ValueError in ipaddress.ip_{address,network,interface} helper functions (GH-30642)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2022-01-17-16-53-30.bpo-46415.6wSYg-.rst
Labels: awaiting merge

#92225 [3.10] bpo-46415: Use f-string for ValueError in ipaddress.ip_{address,network,interface} helper functions (GH-30642)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2022-01-17-16-53-30.bpo-46415.6wSYg-.rst
Labels: awaiting merge

#92168 gh-92154: Expose PyCode_GetCode in the C API
  Doc/c-api/code.rst
  Doc/whatsnew/3.11.rst
  Include/cpython/code.h
  Misc/NEWS.d/next/C API/2022-05-03-20-08-35.gh-issue-92154.IqMcAJ.rst
  Modules/_testcapimodule.c
  Objects/codeobject.c
Labels: awaiting merge

#27663 bpo-44863: In TypedDict allow inherit from Generic and preserve bases
  Doc/library/typing.rst
  Doc/whatsnew/3.11.rst
  Lib/test/_typed_dict_helper.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2021-09-03-07-56-48.bpo-44863.udgz95.rst
Labels: CLA signed, awaiting review, expert-typing

#92230 gh-92135: Rename _Py_reinterpret_cast() to _Py_CAST()
  Include/cpython/abstract.h
  Include/cpython/listobject.h
  Include/cpython/methodobject.h
  Include/cpython/tupleobject.h
  Include/cpython/unicodeobject.h
  Include/methodobject.h
  Include/object.h
  Include/objimpl.h
  Include/pyport.h
Labels: skip news

#92221 Use gh link instead of bpo
  Doc/README.rst
  Doc/faq/general.rst
Labels: docs, skip issue, awaiting merge, skip news

#32247 bpo-47199: multiprocessing: micro-optimize Connection.send_bytes() method
  Lib/multiprocessing/connection.py
Labels: CLA signed, awaiting merge, skip news

#31300 gh-90887: posix._fcopyfile adding couple of more flags
  Misc/NEWS.d/next/Library/2022-05-02-18-19-46.gh-issue-90887.zQsmfp.rst
  Modules/posixmodule.c
Labels: CLA signed, awaiting merge

#92039 gh-92031: Deoptimize Static Code at Finalization
  Include/internal/pycore_opcode.h
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Core and Builtins/2022-04-29-02-50-41.gh-issue-92031.2PpaIN.rst
  Objects/codeobject.c
  Tools/scripts/generate_opcode_h.py
Labels: type-bug, awaiting core review, interpreter-core, 3.11

#31064 bpo-46604: fix function name in ssl module docstring
  Lib/ssl.py
Labels: CLA signed, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#92233 [3.10] bpo-46604: fix function name in ssl module docstring (GH-31064)
  Lib/ssl.py
Labels: awaiting merge, skip news

#92208 gh-89452: Prefer gdbm-compat over ndbm
  Misc/NEWS.d/next/Build/2022-05-03-03-36-47.gh-issue-89452.NIY0fF.rst
  Modules/_dbmmodule.c
  configure
  configure.ac
  setup.py
Labels: awaiting merge, needs backport to 3.9, needs backport to 3.10

#27808 gh-88753: Make BooleanOptionalAction's addition of default to help more similar to other actions
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2021-08-17-21-41-39.bpo-44587.57OKSz.rst
Labels: CLA signed, awaiting merge, stale

#91758 GH-91752: Skip test_freeze_simple_script when zlib is not available
  Lib/test/test_tools/test_freeze.py
  Misc/NEWS.d/next/Tests/2022-04-22-19-00-00.gh-issue-91752.Ji27dd.rst
Labels: tests, awaiting merge

#30862 bpo-29890: Test IPv*Interface construction with tuple argument
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Tests/2022-01-24-21-31-09.bpo-29890.zEG-ra.rst
Labels: CLA signed, tests, awaiting merge, needs backport to 3.9, needs backport to 3.10

#31237 bpo-46696: socketmodule SO_INCOMING_CPU constant addition
  Doc/library/socket.rst
  Misc/NEWS.d/next/Library/2022-02-09-21-40-02.bpo-46696.nPXRno.rst
  Modules/socketmodule.c
Labels: CLA signed, awaiting merge

#92241 gh-92206: Improve scoping of sqlite3 reset statement helper
  Modules/_sqlite/cursor.c
  Modules/_sqlite/statement.c
  Modules/_sqlite/statement.h
Labels: awaiting merge, skip news

#91990 gh-89653: PEP 670: Convert PyBytes macros to functions
  Doc/c-api/bytearray.rst
  Doc/c-api/bytes.rst
  Include/cpython/bytearrayobject.h
  Include/cpython/bytesobject.h
Labels: awaiting core review, skip news

#92214 gh-89289: Harden sqlite3.Connection init
  Modules/_sqlite/connection.c
Labels: awaiting merge, skip news

#92242 [3.10] bpo-29890: Test IPv*Interface construction with tuple argument (GH-30862)
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Tests/2022-01-24-21-31-09.bpo-29890.zEG-ra.rst
Labels: tests, awaiting merge

#92243 [3.9] bpo-29890: Test IPv*Interface construction with tuple argument (GH-30862)
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Tests/2022-01-24-21-31-09.bpo-29890.zEG-ra.rst
Labels: tests, awaiting merge

#92247 gh-91320: Fix more old-style cast warnings in C++
  Include/cpython/unicodeobject.h
  Include/cpython/weakrefobject.h
  Lib/test/test_cppext.py
Labels: awaiting core review, skip news

#92174 gh-90172: add test for functools.singledispatch on Union types with None type
  Lib/test/test_functools.py
Labels: tests, awaiting merge, skip news

#92246 gh-81057: Get the c-analyzer tool working again.
  Tools/c-analyzer/c_parser/info.py
  Tools/c-analyzer/c_parser/parser/_compound_decl_body.py
  Tools/c-analyzer/c_parser/parser/_regexes.py
  Tools/c-analyzer/cpython/_parser.py
Labels: awaiting core review, skip news

#92253 gh-91321: Add _Py_NULL macro
  Include/cpython/abstract.h
  Include/cpython/unicodeobject.h
  Include/object.h
  Include/pyport.h
  Lib/test/_testcppext.cpp
  Lib/test/test_cppext.py
Labels: awaiting core review, skip news

#92251 gh-91320: Use _PyCFunction_CAST()
  Modules/_asynciomodule.c
  Modules/_collectionsmodule.c
  Modules/_csv.c
  Modules/_datetimemodule.c
  Modules/_decimal/_decimal.c
  Modules/_elementtree.c
  Modules/_functoolsmodule.c
  Modules/_lsprof.c
  Modules/_operator.c
  Modules/_struct.c
  Modules/_testbuffer.c
  Modules/_testcapimodule.c
  Modules/_testmultiphase.c
  Modules/_threadmodule.c
  Modules/_xxsubinterpretersmodule.c
  Modules/atexitmodule.c
  Modules/faulthandler.c
  Modules/mathmodule.c
  Modules/nismodule.c
  Modules/signalmodule.c
  Modules/socketmodule.c
  Modules/syslogmodule.c
  Modules/xxlimited.c
  Modules/xxsubtype.c
  Objects/descrobject.c
  Objects/dictobject.c
  Objects/genobject.c
  Objects/odictobject.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Tools/peg_generator/peg_extension/peg_extension.c
Labels: awaiting core review, skip news

#92258 gh-89289: Fix GHA annotation complaint for sqlite3
  Modules/_sqlite/connection.c
Labels: awaiting merge, skip news

#92259 gh-91321: Fix PyModuleDef_HEAD_INIT on C++
  Include/moduleobject.h
Labels: awaiting core review, skip news

#92065 gh-92062: `inspect.Parameter` checks whether `name` is a keyword
  Lib/inspect.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2022-04-29-18-15-23.gh-issue-92062.X2c_Rj.rst
Labels: type-feature, awaiting merge, :robot: automerge, stdlib

#29259 bpo-45639: Add webp and avif image formats to mimetypes
  Lib/mimetypes.py
  Lib/test/test_mimetypes.py
  Misc/NEWS.d/next/Library/2022-02-02-04-51-39.bpo-45639.N8XrGO.rst
Labels: CLA signed, awaiting merge, stale

#92267 gh-81057: Fix an Indent in the c-analyzer Code
  Tools/c-analyzer/c_parser/info.py
Labels: awaiting core review, skip news

#92264 Improve the typing docs
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.9, needs backport to 3.10

#92260 gh-92206: Improve scoping of sqlite3 taint statement helper
  Modules/_sqlite/cursor.c
  Modules/_sqlite/statement.c
  Modules/_sqlite/statement.h
Labels: awaiting merge, skip news

#92164 gh-87304: Summary of the changes made: added detailed explanation for import
  Doc/reference/simple_stmts.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.9, needs backport to 3.10

#91973 gh-91928: Add `datetime.UTC` alias for `datetime.timezone.utc`
  Doc/library/datetime.rst
  Lib/datetime.py
  Lib/test/datetimetester.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2022-04-26-18-02-44.gh-issue-91928.V0YveU.rst
  Modules/_datetimemodule.c
Labels: awaiting merge, :robot: automerge

#92023 GH-91173: disable frozen modules in debug builds
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Core and Builtins/2022-05-02-12-40-18.gh-issue-91173.k_Dr6z.rst
  Python/initconfig.c
Labels: awaiting merge

#92272 [3.10] gh-87304: Improve comments in language reference for imports (GH-92164)
  Doc/reference/simple_stmts.rst
Labels: docs, awaiting merge, skip news

#92273 [3.9] gh-87304: Improve comments in language reference for imports (GH-92164)
  Doc/reference/simple_stmts.rst
Labels: docs, awaiting merge, skip news

#92211 gh-90230: Add stats for freelist use and more allocations.
  Include/internal/pycore_code.h
  Objects/dictobject.c
  Objects/floatobject.c
  Objects/genobject.c
  Objects/listobject.c
  Objects/obmalloc.c
  Objects/tupleobject.c
  Python/context.c
  Python/specialize.c
Labels: awaiting merge, skip news

#92270 [3.10] Improve the typing docs (GH-92264)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting core review, skip news

#92271 [3.9] Improve the typing docs (GH-92264)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting core review, skip news

#29054 gh-80254: Disallow recursive usage of cursors in `sqlite3` converters
  Lib/test/test_sqlite3/test_regression.py
  Misc/NEWS.d/next/Library/2019-06-22-11-01-45.bpo-36073.ED8mB9.rst
  Modules/_sqlite/cursor.c
Labels: CLA signed, awaiting merge, needs backport to 3.9, needs backport to 3.10, release-blocker

#31913 bpo-47029: Fix BrokenPipeError in multiprocessing.Queue at garbage collection and explicit close
  Lib/multiprocessing/queues.py
  Misc/NEWS.d/next/Library/2022-04-26-19-01-13.bpo-47029.qkT42X.rst
Labels: CLA signed, awaiting core review, needs backport to 3.9, needs backport to 3.10

#92276 [3.10] bpo-47029: Fix BrokenPipeError in multiprocessing.Queue at garbage collection and explicit close (GH-31913)
  Lib/multiprocessing/queues.py
  Misc/NEWS.d/next/Library/2022-04-26-19-01-13.bpo-47029.qkT42X.rst
Labels: awaiting merge

#92277 [3.9] bpo-47029: Fix BrokenPipeError in multiprocessing.Queue at garbage collection and explicit close (GH-31913)
  Lib/multiprocessing/queues.py
  Misc/NEWS.d/next/Library/2022-04-26-19-01-13.bpo-47029.qkT42X.rst
Labels: awaiting merge

#8226 gh-78214: marshal: Stabilize FLAG_REF usage
  Misc/NEWS.d/next/Core and Builtins/2018-07-14-16-58-00.bpo-34093.WaVD-f.rst
  Programs/test_frozenmain.h
  Python/marshal.c
Labels: type-feature, CLA signed, awaiting merge

#92284 Compute from_sample() in a single pass over the data
  Lib/statistics.py
Labels: performance, skip issue, awaiting core review, skip news, 3.11

#92254 gh-67248: Update cmd.py
  Lib/cmd.py
  Lib/test/test_cmd.py
  Misc/NEWS.d/next/Library/2022-05-03-19-06-38.gh-issue-67248.DK61Go.rst
Labels: awaiting merge

#92280 Fix typo in Sorting howto
  Doc/howto/sorting.rst
Labels: docs, skip issue, awaiting merge, skip news

#92287 Fix renamed "total" variable
  Lib/statistics.py
Labels: skip issue, awaiting core review, skip news, 3.11

#92037 gh-92036: Fix gc_fini_untrack()
  Misc/NEWS.d/next/Core and Builtins/2022-04-28-23-37-30.gh-issue-92036.GZJAC9.rst
  Modules/gcmodule.c
Labels: awaiting core review

#92296 [3.10] gh-92036: Fix gc_fini_untrack() (GH-92037)
  Misc/NEWS.d/next/Core and Builtins/2022-04-28-23-37-30.gh-issue-92036.GZJAC9.rst
  Modules/gcmodule.c
Labels: awaiting merge

#92297 [3.9] gh-92036: Fix gc_fini_untrack() (GH-92037)
  Misc/NEWS.d/next/Core and Builtins/2022-04-28-23-37-30.gh-issue-92036.GZJAC9.rst
  Modules/gcmodule.c
Labels: awaiting merge

#91988 Use static inline function Py_EnterRecursiveCall()
  Include/internal/pycore_ceval.h
  Modules/_ctypes/_ctypes.c
  Modules/_json.c
  Modules/_pickle.c
  Objects/abstract.c
  Objects/bytesobject.c
  Objects/call.c
  Objects/descrobject.c
  Objects/exceptions.c
  Objects/methodobject.c
  Objects/object.c
  Parser/asdl_c.py
  Python/Python-ast.c
  Python/ceval.c
  Python/pythonrun.c
Labels: skip issue, awaiting core review, skip news

#92245 GH-92239: Respect PEP 523
  Lib/test/test_capi.py
  Misc/NEWS.d/next/Core and Builtins/2022-05-03-14-55-40.gh-issue-92245.G17-5i.rst
  Modules/_testinternalcapi.c
  Python/ceval.c
  Python/specialize.c
Labels: awaiting core review

#92202 gh-92118: fix traceback of exceptions propagated from inside a contextlib.contextmanager
  Lib/contextlib.py
  Lib/test/test_contextlib.py
  Misc/NEWS.d/next/Library/2022-05-02-23-08-02.gh-issue-92118.9Mm9g4.rst
Labels: awaiting merge, stdlib
