Repository python/cpython, pull requests merged in 2023-12, with the labels that each got.

#112566 [3.12] gh-112356: LOAD_GLOBAL can only include one PUSH_NULL
  Lib/test/test_peepholer.py
  Misc/NEWS.d/next/Core and Builtins/2023-11-30-23-47-56.gh-issue-112356.g2BqyK.rst
  Python/flowgraph.c
Labels: awaiting merge

#112574 gh-66819: More IDLE htest updates
  Lib/idlelib/idle_test/htest.py
Labels: awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#112575 [3.12] gh-66819: More IDLE htest updates (GH-112574)
  Lib/idlelib/idle_test/htest.py
Labels: awaiting review, skip news

#112576 [3.11] gh-66819: More IDLE htest updates (GH-112574)
  Lib/idlelib/idle_test/htest.py
Labels: awaiting review, skip news

#112555 [3.12] gh-104231: Add more tests for str(), repr(), ascii(), and bytes() (GH-112551)
  Lib/test/test_bytes.py
  Lib/test/test_unicode.py
Labels: tests, awaiting core review, skip news

#112556 [3.11] gh-104231: Add more tests for str(), repr(), ascii(), and bytes() (GH-112551)
  Lib/test/test_bytes.py
  Lib/test/test_unicode.py
Labels: tests, awaiting core review, skip news

#112537 Add links under "generator expression" in glossary
  Doc/glossary.rst
Labels: docs, skip issue, awaiting merge, skip news

#18878 bpo-39912: Raise appropriate exceptions in filterwarnings() and simplefilter()
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2020-03-09-15-08-29.bpo-39912.xPOBBY.rst
Labels: awaiting review

#112428 gh-111058: Change coro.cr_frame/gen.gi_frame to be None for a closed coroutine/generator.
  Lib/test/test_coroutines.py
  Lib/test/test_inspect/test_inspect.py
  Misc/NEWS.d/next/Core and Builtins/2023-11-26-21-30-11.gh-issue-111058.q4DqDY.rst
  Objects/genobject.c
Labels: type-bug, awaiting merge, interpreter-core, needs backport to 3.12

#112368 gh-112367: Only free perf trampoline arenas at shutdown
  Include/internal/pycore_ceval.h
  Misc/NEWS.d/next/Core and Builtins/2023-11-24-14-10-57.gh-issue-112367.9z1IDp.rst
  Python/perf_trampoline.c
  Python/pylifecycle.c
Labels: awaiting core review

#16606 gh-82565: Fix a possible assertion failure in _pickle
  Lib/test/pickletester.py
Labels: tests, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#112588 gh-109413: regrtest: add WorkerRunTests class
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/run_workers.py
  Lib/test/libregrtest/runtests.py
  Lib/test/libregrtest/worker.py
Labels: awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#112591 [3.12] gh-82565: Add tests for pickle and unpickle with bad files (GH-16606)
  Lib/test/pickletester.py
Labels: awaiting review, skip news

#112592 [3.11] gh-82565: Add tests for pickle and unpickle with bad files (GH-16606)
  Lib/test/pickletester.py
Labels: awaiting review, skip news

#112594 [3.11] gh-109413: regrtest: add WorkerRunTests class (GH-112588)
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/run_workers.py
  Lib/test/libregrtest/runtests.py
  Lib/test/libregrtest/worker.py
Labels: awaiting review, skip news

#112586 gh-109413: libregrtest: enable mypy's `--strict-optional` check on most files
  Lib/test/libregrtest/mypy.ini
  Lib/test/libregrtest/results.py
  Lib/test/libregrtest/single.py
  Lib/test/libregrtest/utils.py
Labels: awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#13503 bpo-37013: Fix the error handling in socket.if_indextoname()
  Lib/test/test_socket.py
  Misc/NEWS.d/next/Library/2023-12-01-16-09-59.gh-issue-81194.FFad1c.rst
  Modules/socketmodule.c
Labels: awaiting merge, needs backport to 3.9, needs backport to 3.10, type-crash, needs backport to 3.11, needs backport to 3.12

#10415 [3.11] bpo-35191: Fix unexpected integer truncation in socket.setblocking()
  Lib/test/test_socket.py
  Misc/NEWS.d/next/Library/2018-11-08-18-44-04.bpo-35191.s29bWu.rst
  Modules/socketmodule.c
Labels: awaiting merge

#112595 gh-110481: Fix typo in Py_SET_REFCNT()
  Include/object.h
Labels: awaiting core review, skip news

#112590 [3.12] gh-112367: Only free perf trampoline arenas at shutdown (GH-112368)
  Include/internal/pycore_ceval.h
  Misc/NEWS.d/next/Core and Builtins/2023-11-24-14-10-57.gh-issue-112367.9z1IDp.rst
  Python/perf_trampoline.c
  Python/pylifecycle.c
Labels: awaiting core review

#112587 gh-112567: Add _Py_GetTicksPerSecond() function
  Include/internal/pycore_fileutils.h
  Include/internal/pycore_pylifecycle.h
  Include/internal/pycore_runtime.h
  Include/internal/pycore_time.h
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
  Modules/timemodule.c
  Python/fileutils.c
  Python/pylifecycle.c
Labels: awaiting core review, skip news

#112601 [3.12] Bump mypy to 1.7.1 (#112581)
  Tools/requirements-dev.txt
Labels: skip issue, awaiting core review, skip news

#112603 [3.11] [3.12] gh-109413: libregrtest: enable mypy's `--strict-optional` check on most files (GH-112586) (GH-112602)
  Lib/test/libregrtest/mypy.ini
  Lib/test/libregrtest/results.py
  Lib/test/libregrtest/single.py
  Lib/test/libregrtest/utils.py
Labels: awaiting review, skip news

#112568 gh-112567: Add _PyTimeFraction C API
  Include/internal/pycore_time.h
  Modules/timemodule.c
  Python/pytime.c
Labels: awaiting core review, skip news

#112605 [3.12] gh-109413: libregrtest: Backport `.py`-file changes from #112558 (#112558)
  Lib/test/libregrtest/cmdline.py
  Lib/test/libregrtest/refleak.py
  Lib/test/libregrtest/results.py
  Lib/test/libregrtest/run_workers.py
  Lib/test/libregrtest/runtests.py
  Lib/test/libregrtest/setup.py
  Lib/test/libregrtest/utils.py
Labels: awaiting core review, skip news, needs backport to 3.11

#112097 gh-106922: Support multi-line error locations in traceback (attempt 2)
  Doc/library/traceback.rst
  Lib/test/test_doctest.py
  Lib/test/test_exceptions.py
  Lib/test/test_repl.py
  Lib/test/test_sys.py
  Lib/test/test_traceback.py
  Lib/test/test_warnings/__init__.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2023-11-15-01-36-04.gh-issue-106922.qslOVH.rst
Labels: awaiting merge

#112317 gh-112316: Improve docs of `inspect.signature` and `Signature.from_callable`
  Doc/library/inspect.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#111084 Docs: Use sphinx-notfound-page to show a nicer 404 page
  Doc/conf.py
  Doc/requirements.txt
Labels: docs, skip issue, awaiting core review, skip news

#112629 [3.12] gh-112316: Improve docs of `inspect.signature` and `Signature.from_callable` (#112317)
  Doc/library/inspect.rst
Labels: docs, awaiting core review, skip news

#112630 [3.11] gh-112316: Improve docs of `inspect.signature` and `Signature.from_callable` (#112317)
  Doc/library/inspect.rst
Labels: docs, awaiting core review, skip news

#112143 gh-112139: Add `inspect.Signature.format` and use it in `pydoc`
  Doc/library/inspect.rst
  Lib/inspect.py
  Lib/pydoc.py
  Lib/test/test_inspect/test_inspect.py
  Lib/test/test_pydoc.py
  Misc/NEWS.d/next/Library/2023-11-16-10-42-15.gh-issue-112139.WpHosf.rst
Labels: awaiting merge

#112628 [3.12] gh-112618: Make Annotated cache typed (#112619)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2023-12-02-12-55-17.gh-issue-112618.7_FT8-.rst
Labels: awaiting merge, needs backport to 3.11

#112633 [3.11] [3.12] gh-112618: Make Annotated cache typed (GH-112619) (GH-112628)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2023-12-02-12-55-17.gh-issue-112618.7_FT8-.rst
Labels: awaiting review

#112642 gh-66819: More IDLE htest updates(2)
  Lib/idlelib/browser.py
  Lib/idlelib/debugobj.py
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/iomenu.py
  Lib/idlelib/multicall.py
  Lib/idlelib/pathbrowser.py
  Lib/idlelib/query.py
  Lib/idlelib/sidebar.py
  Lib/idlelib/statusbar.py
Labels: awaiting core review, skip news, topic-IDLE, needs backport to 3.11, needs backport to 3.12

#112612 gh-106560: Fix redundant declarations in Python/frozen.c
  Python/frozen.c
  Tools/build/freeze_modules.py
Labels: awaiting core review, skip news

#112647 gh-111545: Mention PEP 456 in PyHash_GetFuncDef() doc
  Doc/c-api/hash.rst
Labels: docs, awaiting core review, skip news

#112649 [3.12] gh-112316: improve docs for `inspect.signature` and `inspect.Signature` (#112631)
  Doc/library/inspect.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.11

#112654 Run more `inspect.rst` code snippets in CI
  Doc/library/inspect.rst
Labels: docs, skip issue, awaiting core review, skip news

#112651 [3.12] gh-106560: Fix redundant declarations in Python/frozen.c (#112612)
  Python/frozen.c
  Tools/build/freeze_modules.py
Labels: awaiting core review, skip news

#112656 [3.11] Run more `inspect.rst` code snippets in CI (#112654)
  Doc/library/inspect.rst
Labels: docs, skip issue, awaiting core review, skip news

#112621 gh-112620: Fix dis error on show_cache with labels
  Lib/dis.py
  Lib/test/test_dis.py
Labels: awaiting merge, skip news

#112659 gh-112645: remove deprecation warning for use of onerror in shutil.rmtree
  Doc/whatsnew/3.12.rst
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2023-12-03-12-41-48.gh-issue-112645.blMsKf.rst
Labels: awaiting merge, needs backport to 3.12

#112499 Fix link to 'The Perils of Floating Point', on the tutorial
  Doc/tutorial/floatingpoint.rst
Labels: docs, skip issue, awaiting merge, skip news

#112663 [3.11] Fix link to 'The Perils of Floating Point', on the tutorial (GH-112499)
  Doc/tutorial/floatingpoint.rst
Labels: docs, skip issue, awaiting review, skip news

#112665 [3.12] gh-112645: remove deprecation warning for use of onerror in shutil.rmtree (#112659)
  Doc/whatsnew/3.12.rst
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2023-12-03-12-41-48.gh-issue-112645.blMsKf.rst
Labels: awaiting merge

#112666 [3.12] gh-101100: Fix most Sphinx nitpicks in `inspect.rst` (GH-112662)
  Doc/conf.py
  Doc/library/inspect.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/2.6.rst
  Doc/whatsnew/2.7.rst
Labels: awaiting review, skip news

#112668 gh-101100: Fix Sphinx warning in `library/gettext.rst`
  Doc/library/gettext.rst
  Doc/tools/.nitignore
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#112674 [3.12] gh-101100: Fix Sphinx warning in `library/gettext.rst` (GH-112668)
  Doc/library/gettext.rst
  Doc/tools/.nitignore
Labels: awaiting merge, skip news

#112365 GH-106747: Improve `Path.glob()` expectations in pathlib tests
  Lib/test/test_pathlib.py
Labels: tests, awaiting core review, skip news, topic-pathlib

#112684 [3.12] gh-66819: More IDLE htest updates(3) (GH-112683)
  Lib/idlelib/help.py
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/percolator.py
  Lib/idlelib/scrolledlist.py
  Lib/idlelib/stackviewer.py
  Lib/idlelib/undo.py
Labels: awaiting review, skip news

#112685 [3.11] gh-66819: More IDLE htest updates(3) (GH-112683)
  Lib/idlelib/help.py
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/percolator.py
  Lib/idlelib/scrolledlist.py
  Lib/idlelib/stackviewer.py
  Lib/idlelib/undo.py
Labels: awaiting review, skip news

#112689 [3.11] gh-66819: More IDLE htest updates(4) (GH-112686)
  Lib/idlelib/browser.py
  Lib/idlelib/calltip_w.py
  Lib/idlelib/config.py
  Lib/idlelib/debugobj.py
  Lib/idlelib/delegator.py
  Lib/idlelib/dynoption.py
  Lib/idlelib/editor.py
  Lib/idlelib/filelist.py
  Lib/idlelib/grep.py
  Lib/idlelib/help.py
  Lib/idlelib/idle_test/htest.py
  Lib/idlelib/iomenu.py
  Lib/idlelib/multicall.py
  Lib/idlelib/outwin.py
  Lib/idlelib/percolator.py
  Lib/idlelib/pyshell.py
  Lib/idlelib/redirector.py
  Lib/idlelib/replace.py
  Lib/idlelib/scrolledlist.py
  Lib/idlelib/search.py
  Lib/idlelib/sidebar.py
  Lib/idlelib/statusbar.py
  Lib/idlelib/tree.py
  Lib/idlelib/undo.py
  Lib/idlelib/util.py
Labels: awaiting review, skip news

#112679 gh-112678: Declare `Tkapp_CallDeallocArgs()` as `static`
  Modules/_tkinter.c
Labels: awaiting merge, skip news

#112690 [3.12] gh-112678: Declare `Tkapp_CallDeallocArgs()` as `static` (GH-112679)
  Modules/_tkinter.c
Labels: awaiting review, skip news

#112694 [3.11] gh-112625: Protect bytearray from being freed by misbehaving iterator inside bytearray.join (GH-112626)
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2023-12-03-19-34-51.gh-issue-112625.QWTlwS.rst
  Objects/bytearrayobject.c
Labels: awaiting review

#112613 gh-106550: Fix sign conversion in pycore_code.h
  Include/internal/pycore_code.h
Labels: awaiting merge, skip news, needs backport to 3.12

#112698 [3.11] gh-101100: Fix Sphinx nitpicks in `library/functions.rst` (GH-112669)
  Doc/library/functions.rst
  Doc/tools/.nitignore
Labels: awaiting review, skip news

#112696 [3.12] gh-106550: Fix sign conversion in pycore_code.h (GH-112613)
  Include/internal/pycore_code.h
Labels: awaiting review, skip news

#105958 gh-65210: Add const qualifiers in PyArg_VaParseTupleAndKeywords()
  Doc/c-api/arg.rst
  Doc/extending/extending.rst
  Doc/whatsnew/3.13.rst
  Include/modsupport.h
  Include/pyport.h
  Misc/NEWS.d/next/C API/2023-06-21-11-53-09.gh-issue-65210.PhFRBJ.rst
  Python/getargs.c
Labels: awaiting core review, topic-C-API

#110299 gh-110275: Named tuple's __replace__() now raises TypeError for invalid arguments
  Doc/library/collections.rst
  Lib/collections/__init__.py
  Lib/test/test_collections.py
  Lib/test/test_copy.py
  Misc/NEWS.d/next/Library/2023-11-08-16-11-04.gh-issue-110275.Bm6GwR.rst
Labels: awaiting review, skip news

#109788 gh-109786: Fix leaks when re-enter itertools.pairwise.__next__()
  Lib/test/test_itertools.py
  Misc/NEWS.d/next/Library/2023-09-23-14-40-51.gh-issue-109786.UX3pKv.rst
  Modules/itertoolsmodule.c
Labels: awaiting review, needs backport to 3.11, needs backport to 3.12

#112701 [3.11] gh-101100: Fix sphinx warnings in `Doc/library/__future__.rst` (GH-109814)
  Doc/library/__future__.rst
  Doc/tools/.nitignore
Labels: awaiting review, skip news

#112702 [3.12] gh-101100: Fix sphinx warnings in `Doc/library/__future__.rst` (#109814)
  Doc/library/__future__.rst
  Doc/tools/.nitignore
Labels: awaiting core review, skip news

#112697 [3.12] gh-101100: Fix Sphinx nitpicks in `library/functions.rst` (GH-112669)
  Doc/library/functions.rst
  Doc/tools/.nitignore
Labels: awaiting review, skip news

#112704 [3.11] gh-101100: Fix Sphinx nitpicks in `library/abc.rst` (GH-112703)
  Doc/library/abc.rst
  Doc/tools/.nitignore
Labels: awaiting review, skip news

#112705 [3.12] gh-101100: Fix Sphinx nitpicks in `library/abc.rst` (#112703)
  Doc/library/abc.rst
  Doc/tools/.nitignore
Labels: awaiting core review, skip news

#112712 [3.11] gh-108927: Fix removing testing modules from sys.modules (GH-108952)
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/single.py
  Lib/test/regrtestdata/import_from_tests/test_regrtest_a.py
  Lib/test/regrtestdata/import_from_tests/test_regrtest_b/__init__.py
  Lib/test/regrtestdata/import_from_tests/test_regrtest_b/util.py
  Lib/test/regrtestdata/import_from_tests/test_regrtest_c.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2023-09-05-20-46-35.gh-issue-108927.TpwWav.rst
Labels: type-bug, awaiting review

#112711 [3.12] gh-108927: Fix removing testing modules from sys.modules (GH-108952)
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/single.py
  Lib/test/regrtestdata/import_from_tests/test_regrtest_a.py
  Lib/test/regrtestdata/import_from_tests/test_regrtest_b/__init__.py
  Lib/test/regrtestdata/import_from_tests/test_regrtest_b/util.py
  Lib/test/regrtestdata/import_from_tests/test_regrtest_c.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2023-09-05-20-46-35.gh-issue-108927.TpwWav.rst
Labels: type-bug, awaiting review

#112717 gh-74690: Avoid a costly type check where possible in `_ProtocolMeta.__subclasscheck__`
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2023-12-04-16-45-11.gh-issue-74690.pQYP5U.rst
Labels: performance, awaiting merge, topic-typing

#107962 gh-103363: Add follow_symlinks argument to `pathlib.Path.owner()` and `group()`
  Doc/library/pathlib.rst
  Doc/whatsnew/3.13.rst
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2023-08-14-21-10-52.gh-issue-103363.u64_QI.rst
Labels: awaiting merge, topic-pathlib

#112725 [3.11] gh-105967: Work around a macOS bug, limit zlib C library crc32 API calls to 1gig (GH-112615)
  Misc/NEWS.d/next/Core and Builtins/2023-12-01-19-02-21.gh-issue-105967.Puq5Cn.rst
  Modules/binascii.c
  Modules/zlibmodule.c
Labels: type-bug, awaiting review

#112724 [3.12] gh-105967: Work around a macOS bug, limit zlib C library crc32 API calls to 1gig (GH-112615)
  Misc/NEWS.d/next/Core and Builtins/2023-12-01-19-02-21.gh-issue-105967.Puq5Cn.rst
  Modules/binascii.c
  Modules/zlibmodule.c
Labels: type-bug, awaiting review

#112715 gh-112671: Fixing typo in the Macro Docs
  Doc/c-api/structures.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12

#112726 [3.12] gh-112671: Fixing typo in the Macro Docs (GH-112715)
  Doc/c-api/structures.rst
Labels: docs, awaiting review, skip news

#112709 gh-112535: Add test on _Py_ThreadId()
  Lib/test/support/__init__.py
  Lib/test/test_capi/test_misc.py
  Lib/test/test_cppext/__init__.py
  Lib/test/test_importlib/test_windows.py
  Lib/test/test_sys.py
  Modules/_testinternalcapi.c
Labels: awaiting core review, skip news, topic-free-threaded

#112617 gh-112334: Restore subprocess's use of `vfork()` & fix `extra_groups=[]` behavior
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Library/2023-12-01-21-05-46.gh-issue-112334.DmNXKh.rst
  Modules/_posixsubprocess.c
Labels: type-bug, awaiting merge, release-blocker, 3.12, needs backport to 3.12

#112728 GH-112727: Speed up `pathlib.Path.absolute()`
  Lib/pathlib.py
  Misc/NEWS.d/next/Library/2023-12-04-21-30-34.gh-issue-112727.jpgNRB.rst
Labels: performance, awaiting merge, topic-pathlib

#112731 [3.12] gh-112334: Restore subprocess's use of `vfork()` & fix `extra_groups=[]` behavior (GH-112617)
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Library/2023-12-01-21-05-46.gh-issue-112334.DmNXKh.rst
  Modules/_posixsubprocess.c
Labels: type-bug, awaiting merge, release-blocker, 3.12

#112738 gh-112736: Refactor del-safe symbol handling in subprocess
  Lib/subprocess.py
  Misc/NEWS.d/next/Library/2023-12-05-01-19-28.gh-issue-112736.rdHDrU.rst
Labels: awaiting merge

#107748 gh-102130: Support tab completion in cmd for Libedit.
  Doc/library/cmd.rst
  Lib/cmd.py
  Lib/test/test_cmd.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2023-08-07-21-11-24.gh-issue-102130._UyI5i.rst
Labels: awaiting core review

#112145 Minor refactoring of Object/abstract.c (UNARY_FUNC macro and more cases for BINARY_FUNC)
  Objects/abstract.c
Labels: skip issue, awaiting merge, skip news

#110778 gh-82300: Add track parameter to shared memory
  Doc/library/multiprocessing.shared_memory.rst
  Lib/multiprocessing/shared_memory.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2023-10-12-18-19-47.gh-issue-82300.P8-O38.rst
Labels: type-feature, awaiting merge, 3.13

#112624 gh-112535: Update _Py_ThreadId() to support PowerPC
  Include/object.h
Labels: awaiting core review, skip news, topic-free-threaded

#112744 [3.12] gh-62897: Update PyUnicode C API parameter names (GH-12680)
  Doc/c-api/unicode.rst
Labels: docs, awaiting core review, skip news

#14064 gh-81441: shutil.rmtree() FileNotFoundError race condition
  Doc/library/shutil.rst
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2019-06-14-22-37-32.bpo-37260.oecdIf.rst
Labels: awaiting merge

#112745 [3.11] gh-62897: Update PyUnicode C API parameter names (GH-12680)
  Doc/c-api/unicode.rst
Labels: docs, awaiting core review, skip news

#112737 gh-101100: Fix many easily solvable Sphinx nitpicks in the datamodel docs
  Doc/library/exceptions.rst
  Doc/reference/datamodel.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#112748 [3.12] gh-101100: Fix many easily solvable Sphinx nitpicks in the datamodel docs (GH-112737)
  Doc/library/exceptions.rst
  Doc/reference/datamodel.rst
Labels: docs, awaiting review, skip news

#112749 [3.11] gh-101100: Fix many easily solvable Sphinx nitpicks in the datamodel docs (GH-112737)
  Doc/library/exceptions.rst
  Doc/reference/datamodel.rst
Labels: docs, awaiting review, skip news

#112746 gh-112535: Add comment for ppc32/64 registers
  Include/object.h
Labels: awaiting merge, skip news

#29940 bpo-43153: Don't mask `PermissionError` with `NotADirectoryError` during tempdirectory cleanup
  Lib/tempfile.py
  Lib/test/test_tempfile.py
  Misc/NEWS.d/next/Library/2021-12-06-22-10-53.bpo-43153.J7mjSy.rst
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#112753 [3.12] bpo-43153: Don't mask `PermissionError` with `NotADirectoryError` during tempdirectory cleanup (GH-29940)
  Lib/tempfile.py
  Lib/test/test_tempfile.py
  Misc/NEWS.d/next/Library/2021-12-06-22-10-53.bpo-43153.J7mjSy.rst
Labels: awaiting review

#112513 gh-105323: Remove `WITH_APPLE_EDITLINE` to use the same declaration for all editline
  Modules/readline.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge, skip news

#112604 gh-110190: Fix ctypes structs with array on Arm
  Lib/test/test_ctypes/test_structures.py
  Misc/NEWS.d/next/Library/2023-12-01-18-05-09.gh-issue-110190.5bf-c9.rst
  Modules/_ctypes/_ctypes_test.c
  Modules/_ctypes/stgdict.c
Labels: awaiting merge

#112756 gh-94692: Only catch OSError in shutil.rmtree()
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2023-12-05-16-20-40.gh-issue-94692.-e5C3c.rst
Labels: awaiting core review

#112514 gh-112328: [Enum] Make some private attributes public.
  Doc/howto/enum.rst
  Doc/library/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2023-11-28-20-47-39.gh-issue-112328.Z2AxEY.rst
Labels: type-feature, tests, docs, awaiting review, stdlib, 3.13

#23766 bpo-35332: shutil.rmtree(ignore_errors=True) doesn't handle os.close()
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-12-14-09-31-13.bpo-35332.s22wAx.rst
Labels: awaiting review, needs backport to 3.11, needs backport to 3.12

#112763 [3.12] bpo-35332: Handle os.close() errors in shutil.rmtree() (GH-23766)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-12-14-09-31-13.bpo-35332.s22wAx.rst
Labels: awaiting review

#112759 Check argument in itertools's recipe for "grouper"
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting merge, skip news

#112764 [3.11] bpo-35332: Handle os.close() errors in shutil.rmtree() (GH-23766)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2020-12-14-09-31-13.bpo-35332.s22wAx.rst
Labels: awaiting review

#112735 gh-101100: Properly document frame object attributes
  Doc/c-api/frame.rst
  Doc/c-api/init.rst
  Doc/library/dis.rst
  Doc/library/inspect.rst
  Doc/library/sys.rst
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.11.rst
  Doc/whatsnew/3.6.rst
  Doc/whatsnew/3.7.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#112772 [3.12] gh-101100: Properly document frame object attributes (GH-112735)
  Doc/c-api/frame.rst
  Doc/c-api/init.rst
  Doc/library/dis.rst
  Doc/library/inspect.rst
  Doc/library/sys.rst
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.11.rst
  Doc/whatsnew/3.6.rst
  Doc/whatsnew/3.7.rst
Labels: docs, awaiting review, skip news

#112771 gh-112769: test_zlib: Fix comparison of ZLIB_RUNTIME_VERSION with non-int suffix
  Lib/test/test_zlib.py
  Misc/NEWS.d/next/Tests/2023-12-05-19-50-03.gh-issue-112769.kdLJmS.rst
Labels: tests, awaiting merge, needs backport to 3.11, needs backport to 3.12

#112774 [3.11] gh-112769: test_zlib: Fix comparison of ZLIB_RUNTIME_VERSION with non-int suffix (GH-112771)
  Lib/test/test_zlib.py
  Misc/NEWS.d/next/Tests/2023-12-05-19-50-03.gh-issue-112769.kdLJmS.rst
Labels: tests, awaiting review

#112773 [3.12] gh-112769: test_zlib: Fix comparison of ZLIB_RUNTIME_VERSION with non-int suffix (GH-112771)
  Lib/test/test_zlib.py
  Misc/NEWS.d/next/Tests/2023-12-05-19-50-03.gh-issue-112769.kdLJmS.rst
Labels: tests, awaiting review

#112775 [3.11] gh-101100: Properly document frame object attributes (#112735)
  Doc/c-api/frame.rst
  Doc/c-api/init.rst
  Doc/library/dis.rst
  Doc/library/inspect.rst
  Doc/library/sys.rst
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.11.rst
  Doc/whatsnew/3.6.rst
  Doc/whatsnew/3.7.rst
Labels: docs, awaiting core review, skip news

#112733 gh-112606: Use sem_clockwait with monotonic time when supported in parking_lot.c
  Python/parking_lot.c
Labels: awaiting merge, skip news

#112765 gh-108927: Include new dir test/regrtestdata in the installation
  Makefile.pre.in
Labels: awaiting merge, skip news

#112784 [3.11] gh-108927: Include new dir test/regrtestdata in the installati…
  Makefile.pre.in
Labels: awaiting core review, skip news

#112785 [3.12] gh-108927: Include new dir test/regrtestdata in the installati…
  Makefile.pre.in
Labels: awaiting core review, skip news

#112757 gh-101100: Fix most Sphinx nitpicks in the glossary and `stdtypes.rst`
  Doc/glossary.rst
  Doc/library/stdtypes.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#112790 [3.11] gh-101100: Fix most Sphinx nitpicks in the glossary and `stdtypes.rst` (GH-112757)
  Doc/glossary.rst
  Doc/library/stdtypes.rst
Labels: docs, awaiting review, skip news

#112742 gh-111178: Docs: fix `traverseproc`, `inquiry`, and `destructor` parameters in slot typedefs table
  Doc/c-api/typeobj.rst
Labels: docs, awaiting review, skip news, needs backport to 3.11, needs backport to 3.12

#112780 gh-108223: Refer to PEP 703 as Free Threading
  Doc/using/configure.rst
  Lib/test/libregrtest/utils.py
Labels: awaiting merge, skip news

#112801 [3.11] gh-75666: Tkinter: "unbind(sequence, funcid)" now only unbinds "funcid" (GH-111322)
  Lib/tkinter/__init__.py
  Lib/tkinter/test/test_tkinter/test_misc.py
  Misc/NEWS.d/next/Library/2023-10-25-16-37-13.gh-issue-75666.BpsWut.rst
Labels: awaiting review

#112802 [3.12] gh-75666: Tkinter: "unbind(sequence, funcid)" now only unbinds "funcid" (GH-111322)
  Lib/test/test_tkinter/test_misc.py
  Lib/tkinter/__init__.py
  Misc/NEWS.d/next/Library/2023-10-25-16-37-13.gh-issue-75666.BpsWut.rst
Labels: awaiting review

#112687 gh-111178: Define `visitproc` callback functions properly and remove unnecessary casts in gcmodule.c
  Modules/gcmodule.c
Labels: awaiting merge, skip news

#112767 [3.12] gh-110190: Fix ctypes structs with array on Arm (#112604)
  Lib/test/test_ctypes/test_structures.py
  Misc/NEWS.d/next/Library/2023-12-01-18-05-09.gh-issue-110190.5bf-c9.rst
  Modules/_ctypes/_ctypes_test.c
  Modules/_ctypes/stgdict.c
Labels: awaiting review

#112766 [3.11] gh-110190: Fix ctypes structs with array on Arm (#112604)
  Lib/ctypes/test/test_structures.py
  Misc/NEWS.d/next/Library/2023-12-01-18-05-09.gh-issue-110190.5bf-c9.rst
  Modules/_ctypes/_ctypes_test.c
  Modules/_ctypes/stgdict.c
Labels: awaiting review

#112811 gh-101100: Fix Sphinx nitpicks in `library/reprlib.rst`
  Doc/library/reprlib.rst
  Doc/tools/.nitignore
Labels: awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#112813 [3.12] gh-101100: Fix Sphinx nitpicks in `library/reprlib.rst` (GH-112811)
  Doc/library/reprlib.rst
  Doc/tools/.nitignore
Labels: awaiting review, skip news

#112815 [3.11] gh-101100: Fix Sphinx nitpicks in `library/reprlib.rst` (#112811)
  Doc/library/reprlib.rst
  Doc/tools/.nitignore
Labels: awaiting core review, skip news

#112816 [3.12] gh-101100: Improve documentation of code object attributes (#112781)
  Doc/c-api/function.rst
  Doc/c-api/import.rst
  Doc/library/dis.rst
  Doc/library/inspect.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.6.rst
Labels: docs, awaiting core review, skip news

#112817 [3.11] gh-101100: Improve documentation of code object attributes (#112781)
  Doc/c-api/function.rst
  Doc/c-api/import.rst
  Doc/library/dis.rst
  Doc/library/inspect.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.6.rst
Labels: docs, awaiting core review, skip news

#112732 gh-112730: Use color to highlight error locations
  Doc/using/cmdline.rst
  Doc/whatsnew/3.13.rst
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Core and Builtins/2023-12-04-23-09-07.gh-issue-112730.BXHlFa.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
  Python/initconfig.c
Labels: awaiting core review

#112164 [3.9] gh-112160: Add 'regen-configure' make target
  .github/workflows/build.yml
  Makefile.pre.in
Labels: awaiting review, skip news

#112797 gh-109981: Fix support.fd_count() on macOS 14
  Lib/test/support/os_helper.py
  Misc/NEWS.d/next/macOS/2023-12-06-12-11-13.gh-issue-109981.mOHg10.rst
Labels: OS-mac, awaiting merge, needs backport to 3.11, needs backport to 3.12

#112661 gh-112660: Do not clear arbitrary errors on import
  Misc/NEWS.d/next/Core and Builtins/2023-12-03-15-29-53.gh-issue-112660.gldBvh.rst
  Objects/moduleobject.c
  Python/ceval.c
  Python/import.c
Labels: awaiting core review

#1738 gh-74616: Raise ValueError in case of NULL in input prompt
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2023-12-07-12-00-04.gh-issue-74616.kgTGVb.rst
  Python/bltinmodule.c
Labels: awaiting merge

#112824 [3.12] gh-109981: Fix support.fd_count() on macOS 14 (GH-112797)
  Lib/test/support/os_helper.py
  Misc/NEWS.d/next/macOS/2023-12-06-12-11-13.gh-issue-109981.mOHg10.rst
Labels: awaiting review

#111194 gh-102980: Redirect pdb `interact` command, add tests and improve docs
  Doc/library/pdb.rst
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-10-23-03-49-34.gh-issue-102980.aXBd54.rst
Labels: tests, awaiting merge, stdlib

#112299 GH-111485: Separate out parsing, analysis and code-gen phases
  Include/internal/pycore_opcode_metadata.h
  Makefile.pre.in
  Python/abstract_interp_cases.c.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/cwriter.py
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/lexer.py
  Tools/cases_generator/mypy.ini
  Tools/cases_generator/parser.py
  Tools/cases_generator/parsing.py
  Tools/cases_generator/stack.py
  Tools/cases_generator/tier1_generator.py
Labels: awaiting core review, skip news

#112504 gh-112125: Fix None.__ne__(None) returning NotImplemented instead of False
  Include/internal/pycore_typeobject.h
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2023-12-07-13-19-55.gh-issue-112125.4ADN7i.rst
  Objects/object.c
  Objects/typeobject.c
Labels: awaiting review, needs backport to 3.12

#112818 gh-110190: Temporarily skip new test introduced in gh-112604 on PPC64LE
  Lib/test/test_ctypes/test_structures.py
Labels: tests, awaiting core review, skip news

#112827 [3.12] gh-112125: Fix None.__ne__(None) returning NotImplemented instead of …
  Include/internal/pycore_typeobject.h
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2023-12-07-13-19-55.gh-issue-112125.4ADN7i.rst
  Objects/object.c
  Objects/typeobject.c
Labels: awaiting core review

#112049 gh-111962: Make dtoa thread-safe in `--disable-gil` builds.
  Include/internal/pycore_dtoa.h
  Python/dtoa.c
  Python/pylifecycle.c
Labels: awaiting merge, skip news, 3.13, topic-free-threaded

#112829 [3.12] gh-110190: Temporarily skip new test introduced in gh-112604 on PPC64LE (GH-112818)
  Lib/test/test_ctypes/test_structures.py
Labels: tests, awaiting core review, skip news

#112791 gh-87319: Simplify TemporaryDirectory cleanup using os.path.isjunction()
  Lib/tempfile.py
Labels: awaiting merge, skip news, needs backport to 3.12

#112845 [3.12] gh-87319: Simplify TemporaryDirectory cleanup using os.path.isjunction() (GH-112791)
  Lib/tempfile.py
Labels: awaiting review, skip news

#112658 gh-112278: reduce time cost for platform module when no permission to WMI on Windows
  Lib/platform.py
  Misc/NEWS.d/next/Windows/2023-12-03-19-22-37.gh-issue-112278.FiloCE.rst
  PC/_wmimodule.cpp
Labels: awaiting review

#112847 [3.12] gh-79325: Fix recursion error in TemporaryDirectory cleanup on Windows (GH-112762)
  Lib/tempfile.py
  Lib/test/test_tempfile.py
  Misc/NEWS.d/next/Library/2023-12-05-18-57-53.gh-issue-79325.P2vMVK.rst
Labels: awaiting review

#112834 gh-110017: Disable test_signal.test_stress_modifying_handlers on macOS
  Lib/test/test_signal.py
  Misc/NEWS.d/next/macOS/2023-12-07-15-53-16.gh-issue-110017.UMYzMR.rst
Labels: tests, OS-mac, awaiting merge, needs backport to 3.11, needs backport to 3.12

#112560 gh-112538: Add internal-only _PyThreadStateImpl "wrapper" for PyThreadState
  Include/internal/pycore_interp.h
  Include/internal/pycore_runtime_init.h
  Include/internal/pycore_tstate.h
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/pystate.c
Labels: awaiting merge, skip news, topic-free-threaded

#112207 gh-111924: Use PyMutex for runtime global locks.
  Include/internal/pycore_atexit.h
  Include/internal/pycore_ceval.h
  Include/internal/pycore_ceval_state.h
  Include/internal/pycore_crossinterp.h
  Include/internal/pycore_import.h
  Include/internal/pycore_lock.h
  Include/internal/pycore_pymem.h
  Include/internal/pycore_pystate.h
  Include/internal/pycore_runtime.h
  Include/internal/pycore_unicodeobject.h
  Objects/obmalloc.c
  Objects/unicodeobject.c
  Python/ceval_gil.c
  Python/crossinterp.c
  Python/import.c
  Python/pylifecycle.c
  Python/pystate.c
  Python/sysmodule.c
Labels: awaiting merge, skip news, interpreter-core, 3.13, topic-free-threaded

#112850 [3.12] gh-112826: Fix the threading Module When _thread is Missing _is_main_interpreter()
  Doc/whatsnew/3.12.rst
  Lib/test/test_threading.py
  Lib/threading.py
Labels: awaiting merge, skip news

#112853 gh-112826: Add a "What's New" Entry About _thread._is_main_interpreter
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting core review, skip news

#112833 gh-101100: Silence Sphinx warnings when `ntpath` or `posixpath` are referenced
  Doc/conf.py
  Doc/library/pathlib.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.7.rst
Labels: skip news, needs backport to 3.11, needs backport to 3.12

#112857 [3.12] gh-101100: Silence Sphinx warnings when `ntpath` or `posixpath` are referenced (#112833)
  Doc/conf.py
  Doc/tools/.nitignore
  Doc/whatsnew/3.7.rst
Labels: awaiting core review, skip news

#112676 GH-112675: Move path joining tests into `test_posixpath` and `test_ntpath`
  Lib/test/test_ntpath.py
  Lib/test/test_pathlib.py
  Lib/test/test_posixpath.py
Labels: tests, awaiting core review, skip news, topic-pathlib

#112846 Add a versionchanged directive for gh-94692
  Doc/library/shutil.rst
Labels: docs, awaiting merge, skip news
