Repository python/cpython, pull requests merged in 2023-03, with the labels that each got.

#102337 gh-102336: remove windows 7 special handling
  Misc/NEWS.d/next/Core and Builtins/2023-02-28-21-17-03.gh-issue-102336.-wL3Tm.rst
  Modules/_winapi.c
  Modules/getpath.c
  Modules/mmapmodule.c
  Modules/posixmodule.c
  Modules/socketmodule.c
  Python/fileutils.c
Labels: OS-windows, awaiting review

#100614 Fix minor error in ePub
  Doc/conf.py
Labels: type-bug, docs, skip issue, awaiting core review, skip news, 3.11, 3.10, 3.12

#102348 [3.11] Doc: Fix minor error in ePub (GH-100614)
  Doc/conf.py
Labels: type-bug, docs, skip issue, awaiting core review, skip news, :robot: automerge

#102319 gh-102192: Replace PyErr_Fetch/Restore etc by more efficient alternatives in tkinter module
  Modules/_tkinter.c
Labels: awaiting merge, skip news

#102347 gh-102336: Ensure CancelIoEx result is not ignored
  Modules/_winapi.c
Labels: awaiting review, skip news

#102345 gh-102344: implement winreg QueryValue / SetValue using QueryValueEx / SetValueEx
  Misc/NEWS.d/next/Windows/2023-03-01-01-36-39.gh-issue-102344.Dgfux4.rst
  PC/winreg.c
Labels: OS-windows, awaiting review

#102163 gh-95672 skip fcntl when pipesize is smaller than pagesize
  Doc/library/test.rst
  Lib/test/support/__init__.py
  Lib/test/test_fcntl.py
  Lib/test/test_subprocess.py
Labels: tests, awaiting merge, skip news

#102360 gh-102088 Optimize iter_index itertools recipe
  Doc/library/itertools.rst
  Lib/test/test_operator.py
Labels: tests, awaiting review, skip news

#102363 [3.11] gh-102088 Optimize iter_index itertools recipe (GH-102360)
  Doc/library/itertools.rst
  Lib/test/test_operator.py
Labels: tests, awaiting review, skip news

#102321 [3.11] gh-90744: Fix erroneous doc links in the sys module (GH-101319)
  Doc/library/sys.rst
Labels: docs, awaiting core review, skip news

#102322 [3.10] gh-90744: Fix erroneous doc links in the sys module (GH-101319)
  Doc/library/sys.rst
Labels: docs, awaiting core review, skip news

#102365 gh-95672: Update memory_watchdog to use test.support.get_pagesize
  Lib/test/memory_watchdog.py
Labels: awaiting merge, skip news

#102374 Fix typos in documentation and comments
  Doc/library/sqlite3.rst
  Doc/library/typing.rst
  Lib/zoneinfo/_zoneinfo.py
  Objects/typeobject.c
Labels: skip issue, awaiting merge, skip news, :robot: automerge

#102376 [3.11] Fix typos in documentation and comments (GH-102374)
  Doc/library/sqlite3.rst
  Doc/library/typing.rst
  Lib/zoneinfo/_zoneinfo.py
Labels: skip issue, awaiting core review, skip news, needs backport to 3.10

#102377 [3.10] Fix typos in documentation and comments (GH-102374)
  Doc/library/sqlite3.rst
  Lib/zoneinfo/_zoneinfo.py
Labels: skip issue, awaiting core review, skip news

#102372 gh-102371: move _Py_Mangle from compile.c to symtable.c
  Include/internal/pycore_compile.h
  Include/internal/pycore_symtable.h
  Objects/typeobject.c
  Python/compile.c
  Python/symtable.c
Labels: awaiting merge, skip news

#102325 gh-102324: Improve tests of `typing.override`
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news

#101840 gh-101754: document that on Windows, keys in `os.environ` are converted to uppercase
  Doc/library/os.rst
Labels: docs, awaiting review, skip news

#102393 [3.10] gh-101754: Document that Windows converts keys in `os.environ` to uppercase (GH-101840)
  Doc/library/os.rst
Labels: docs, awaiting merge, skip news

#102394 [3.11] gh-101754: Document that Windows converts keys in `os.environ` to uppercase (GH-101840)
  Doc/library/os.rst
Labels: docs, awaiting merge, skip news

#102235 [3.10] GH-102126: fix deadlock at shutdown when clearing thread state…
  Misc/NEWS.d/next/Core and Builtins/2023-02-24-17-59-39.gh-issue-102126.HTT8Vc.rst
  Python/pystate.c
Labels: type-bug, awaiting core review, release-blocker

#102390 gh-102383: [docs] Arguments of `PyObject_CopyData` are `PyObject *`
  Doc/c-api/buffer.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#102346 Add import of unittest.mock.Mock in Documentation
  Doc/library/unittest.mock.rst
Labels: docs, skip issue, awaiting merge, skip news

#102401 [3.11] gh-102383: [docs] Arguments of `PyObject_CopyData` are `PyObject *` (GH-102390)
  Doc/c-api/buffer.rst
Labels: docs, awaiting merge, skip news

#102022 gh-102021 : Allow multiple input files for interpreter loop generator
  Makefile.pre.in
  Python/generated_cases.c.h
  Python/opcode_metadata.h
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/lexer.py
  Tools/cases_generator/parser.py
Labels: awaiting merge, skip news

#102415 Remove unused internal macros
  Include/internal/pycore_pymath.h
Labels: skip issue, awaiting merge, skip news

#101896 gh-101892: Fix SystemError when a callable iterator call exhausts the iterator
  Lib/test/test_iter.py
  Misc/NEWS.d/next/Library/2023-02-14-09-08-48.gh-issue-101892.FMos8l.rst
  Objects/iterobject.c
Labels: awaiting merge, needs backport to 3.10, interpreter-core, needs backport to 3.11

#102180 gh-102179: Fix os.dup2() error reporting for negative fds
  Lib/test/test_os.py
  Misc/NEWS.d/next/Library/2023-02-23-15-06-01.gh-issue-102179.P6KQ4c.rst
  Modules/posixmodule.c
Labels: awaiting merge, needs backport to 3.10, extension-modules, needs backport to 3.11

#102418 [3.11] gh-101892: Fix `SystemError` when a callable iterator call exhausts the iterator (GH-101896)
  Lib/test/test_iter.py
  Misc/NEWS.d/next/Library/2023-02-14-09-08-48.gh-issue-101892.FMos8l.rst
  Objects/iterobject.c
Labels: awaiting merge

#102420 [3.11] gh-102179: Fix `os.dup2` error reporting for negative fds (GH-102180)
  Lib/test/test_os.py
  Misc/NEWS.d/next/Library/2023-02-23-15-06-01.gh-issue-102179.P6KQ4c.rst
  Modules/posixmodule.c
Labels: awaiting merge

#102303 gh-102302 Micro-optimize `inspect.Parameter.__hash__`
  Lib/inspect.py
  Misc/NEWS.d/next/Library/2023-03-04-14-46-47.gh-issue-102302.-b_s6Z.rst
Labels: awaiting merge, stdlib

#102422 [3.10] gh-101892: Fix `SystemError` when a callable iterator call exhausts the iterator (GH-101896)
  Lib/test/test_iter.py
  Misc/NEWS.d/next/Library/2023-02-14-09-08-48.gh-issue-101892.FMos8l.rst
  Objects/iterobject.c
Labels: awaiting merge

#102419 [3.10] gh-102179: Fix `os.dup2` error reporting for negative fds (GH-102180)
  Lib/test/test_os.py
  Misc/NEWS.d/next/Library/2023-02-23-15-06-01.gh-issue-102179.P6KQ4c.rst
  Modules/posixmodule.c
Labels: awaiting merge

#102417 gh-101863: Fix wrong comments in EUC-KR codec
  Misc/ACKS
  Modules/cjkcodecs/_codecs_kr.c
Labels: awaiting merge, skip news, extension-modules

#102307 [3.8] GH-102306 Avoid GHA CI macOS test_posix failure by using the appropriate macOS SDK
  .github/workflows/build.yml
  Misc/NEWS.d/next/Build/2023-02-27-18-55-32.gh-issue-102306.bkokFL.rst
Labels: awaiting merge

#7699 gh-63301: Set exit code when tabnanny CLI exits on error
  Lib/tabnanny.py
  Lib/test/test_tabnanny.py
  Misc/NEWS.d/next/Library/2023-02-01-10-42-16.gh-issue-63301.XNxSFh.rst
Labels: awaiting merge

#102133 gh-101992: update pstlib module documentation
  Lib/plistlib.py
Labels: awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#101001 [3.11] Clarify re docs for byte pattern group names (GH-99308)
  Doc/library/re.rst
Labels: docs, awaiting merge, skip news

#96823 gh-96821: Add config option `--with-strict-overflow`
  Doc/using/configure.rst
  Misc/NEWS.d/next/Build/2022-09-14-10-38-15.gh-issue-96821.Zk2a9c.rst
  configure
  configure.ac
Labels: performance, awaiting merge, DO-NOT-MERGE, build

#102428 [3.11] gh-101992: update pstlib module documentation (GH-102133)
  Lib/plistlib.py
Labels: awaiting merge, skip news

#102429 [3.10] gh-101992: update pstlib module documentation (GH-102133)
  Lib/plistlib.py
Labels: awaiting merge, skip news

#102421 GH-97546: fix flaky asyncio `test_wait_for_race_condition` test
  Lib/test/test_asyncio/test_waitfor.py
Labels: tests, expert-asyncio, awaiting core review, skip news

#101595 Move around example in to_bytes() to avoid confusion
  Doc/library/stdtypes.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11

#102434 [3.11] Move around example in to_bytes() to avoid confusion (GH-101595)
  Doc/library/stdtypes.rst
Labels: docs, skip issue, awaiting review, skip news

#102426 gh-102356: Add thrashcan macros to filter object dealloc
  Lib/test/test_builtin.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2023-03-04-20-56-12.gh-issue-102356.07KvUd.rst
  Python/bltinmodule.c
Labels: awaiting merge, needs backport to 3.10, interpreter-core, type-crash, needs backport to 3.11

#102436 [3.10] gh-102356: Add thrashcan macros to filter object dealloc (GH-102426)
  Lib/test/test_builtin.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2023-03-04-20-56-12.gh-issue-102356.07KvUd.rst
  Python/bltinmodule.c
Labels: awaiting merge, type-crash

#102435 [3.11] gh-102356: Add thrashcan macros to filter object dealloc (GH-102426)
  Lib/test/test_builtin.py
  Misc/ACKS
  Misc/NEWS.d/next/Core and Builtins/2023-03-04-20-56-12.gh-issue-102356.07KvUd.rst
  Python/bltinmodule.c
Labels: awaiting merge, type-crash

#102318 gh-101979: fix a bug that parentheses in metavar argument of add_argument() were dropped
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2023-02-28-09-52-25.gh-issue-101979.or3hXV.rst
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11

#102437 Fix unused classes in a typing test
  Lib/test/test_typing.py
Labels: tests, skip issue, awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#102439 [3.10] gh-101979: argparse: fix a bug where parentheses in metavar argument of add_argument() were dropped (GH-102318)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2023-02-28-09-52-25.gh-issue-101979.or3hXV.rst
Labels: awaiting merge

#102438 [3.11] gh-101979: argparse: fix a bug where parentheses in metavar argument of add_argument() were dropped (GH-102318)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2023-02-28-09-52-25.gh-issue-101979.or3hXV.rst
Labels: awaiting merge

#102441 [3.11] Fix unused classes in a typing test (GH-102437)
  Lib/test/test_typing.py
Labels: tests, skip issue, awaiting merge, skip news

#102442 [3.10] Fix unused classes in a typing test (GH-102437)
  Lib/test/test_typing.py
Labels: tests, skip issue, awaiting merge, skip news

#102342 GH-102341: Improve the test function for pow
  Lib/test/test_pow.py
Labels: tests, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#102447 [3.10] GH-102341: Improve the test function for pow (GH-102342)
  Lib/test/test_pow.py
Labels: tests, awaiting merge, skip news

#102446 [3.11] GH-102341: Improve the test function for pow (GH-102342)
  Lib/test/test_pow.py
Labels: tests, awaiting merge, skip news

#102445 gh-102444: Fix minor bugs in `test_typing` highlighted by pyflakes
  Lib/test/test_typing.py
Labels: tests, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#101665 GH-101362: Call join() only when >1 argument supplied to pathlib.PurePath()
  Lib/pathlib.py
  Misc/NEWS.d/next/Library/2023-02-07-21-16-41.gh-issue-101362.KMQllM.rst
Labels: performance, awaiting merge, expert-pathlib

#102451 [3.11] gh-102444: Fix minor bugs in `test_typing` highlighted by pyflakes (GH-102445)
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news

#102452 [3.10] gh-102444: Fix minor bugs in `test_typing` highlighted by pyflakes (#102445)
  Lib/test/test_typing.py
Labels: tests, awaiting core review, skip news

#101664 GH-101362: Check pathlib.Path flavour compatibility at import time
  Lib/pathlib.py
  Misc/NEWS.d/next/Library/2023-02-07-20-46-08.gh-issue-101362.2ckZ6R.rst
Labels: performance, awaiting merge, :robot: automerge, expert-pathlib

#101667 GH-101362: Optimise PurePath(PurePath(...))
  Doc/library/pathlib.rst
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2023-02-07-22-20-32.gh-issue-101362.Jlk6mt.rst
Labels: performance, awaiting merge, :robot: automerge, expert-pathlib

#102467 gh-102416: Do not memoize incorrectly loop rules in the parser
  Misc/NEWS.d/next/Core and Builtins/2023-03-06-13-05-33.gh-issue-102416.dz6K5f.rst
  Parser/parser.c
  Tools/peg_generator/pegen/c_generator.py
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11

#102474 [3.10] gh-102416: Do not memoize incorrectly loop rules in the parser (GH-102467).
  Misc/NEWS.d/next/Core and Builtins/2023-03-06-13-05-33.gh-issue-102416.dz6K5f.rst
  Parser/parser.c
  Tools/peg_generator/pegen/c_generator.py
Labels: awaiting core review

#102472 gh-102192: Replace PyErr_Fetch/Restore etc by more efficient alternatives in sub interpreters module
  Modules/_xxsubinterpretersmodule.c
Labels: awaiting merge, skip news

#101989 Add gettext support to tools/extensions/c_annotations.py
  Doc/tools/extensions/c_annotations.py
  Doc/tools/templates/dummy.html
Labels: docs, skip issue, awaiting merge, skip news

#102480 [3.10] Add gettext support to tools/extensions/c_annotations.py (GH-101989)
  Doc/tools/extensions/c_annotations.py
  Doc/tools/templates/dummy.html
Labels: skip issue, awaiting merge, skip news

#102481 [3.11] Add gettext support to tools/extensions/c_annotations.py (GH-101989)
  Doc/tools/extensions/c_annotations.py
  Doc/tools/templates/dummy.html
Labels: skip issue, awaiting merge, skip news

#102479 Remove the unused import 'warnings' from unittest's loader module
  Lib/unittest/loader.py
Labels: skip issue, awaiting merge, skip news

#102485 gh-101759: Update macOS installer SQLite 3.40.1 checksum
  Mac/BuildScript/build-installer.py
Labels: awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#102488 [3.11] gh-101759: Update macOS installer SQLite 3.40.1 checksum (gh-102485)
  Mac/BuildScript/build-installer.py
Labels: awaiting review, skip news

#102489 [3.10] gh-101759: Update macOS installer SQLite 3.40.1 checksum (gh-102485)
  Mac/BuildScript/build-installer.py
Labels: awaiting review, skip news

#102483 gh-90110: Fix the c-analyzer Tool
  Include/internal/pycore_global_objects.h
  Include/internal/pycore_intrinsics.h
  Include/internal/pycore_runtime_init.h
  Objects/exceptions.c
  Python/intrinsics.c
  Tools/c-analyzer/c_parser/parser/_common.py
  Tools/c-analyzer/c_parser/parser/_func_body.py
  Tools/c-analyzer/c_parser/preprocessor/gcc.py
  Tools/c-analyzer/cpython/_parser.py
  Tools/c-analyzer/cpython/globals-to-fix.tsv
  Tools/c-analyzer/cpython/ignored.tsv
Labels: awaiting core review, skip news

#98429 gh-95913: Edit Faster CPython section in 3.11 WhatsNew
  Doc/whatsnew/3.11.rst
Labels: docs, awaiting merge, skip news, 3.11, needs backport to 3.11

#102490 [3.11] gh-95913: Edit Faster CPython section in 3.11 WhatsNew (GH-98429)
  Doc/whatsnew/3.11.rst
Labels: docs, awaiting review, skip news

#102398 Remove redundant `_ensure_future` in favor of `ensure_future` in `asyncio`
  Lib/asyncio/tasks.py
Labels: expert-asyncio, skip issue, awaiting merge, skip news

#102320 gh-87092: compiler's CFG construction moved to after codegen stage
  Python/compile.c
Labels: awaiting core review, skip news

#102502 gh-102493: fix normalization in PyErr_SetObject
  Lib/test/test_capi/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2023-03-07-16-56-28.gh-issue-102493.gTXrcD.rst
  Modules/_testcapi/exceptions.c
  Python/errors.c
Labels: type-bug, awaiting merge, release-blocker, 3.12

#101751 [3.9] gh-101726: Update the OpenSSL version to 1.1.1t (GH-101727)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
  .github/workflows/build.yml
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/Security/2023-02-08-22-03-04.gh-issue-101727.9P5eZz.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
  Tools/ssl/multissltests.py
Labels: awaiting merge

#101752 [3.8] gh-101726: Update the OpenSSL version to 1.1.1t (GH-101727)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
  .github/workflows/build.yml
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/Security/2023-02-08-22-03-04.gh-issue-101727.9P5eZz.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
  Tools/ssl/multissltests.py
Labels: awaiting merge

#102382 gh-102381: don't call watcher callback with dead object
  Doc/c-api/code.rst
  Doc/c-api/dict.rst
  Doc/c-api/function.rst
  Include/cpython/code.h
  Include/cpython/dictobject.h
  Include/cpython/funcobject.h
  Include/internal/pycore_dict.h
  Lib/test/test_capi/test_watchers.py
  Modules/_testcapi/watchers.c
  Objects/codeobject.c
  Objects/dictobject.c
  Objects/funcobject.c
Labels: awaiting merge, skip news

#102448 fix typo in async generator code field name `ag_code`
  Objects/genobject.c
Labels: skip issue, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#101733 Doc: fixed style in library/argparse.rst
  Doc/library/argparse.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#102399 GH-102397: Fix segfault from race condition in signal handling
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Core and Builtins/2023-03-04-06-48-34.gh-issue-102397.ACJaOf.rst
  Modules/signalmodule.c
Labels: awaiting merge, needs backport to 3.10, interpreter-core, type-crash, needs backport to 3.11

#102526 gh-101100: Fix sphinx warnings in `zipapp` and `zipfile` modules
  Doc/library/zipapp.rst
  Doc/library/zipfile.rst
Labels: docs, awaiting merge, skip news

#102527 [3.10] GH-102397: Fix segfault from race condition in signal handling (GH-102399)
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Core and Builtins/2023-03-04-06-48-34.gh-issue-102397.ACJaOf.rst
  Modules/signalmodule.c
Labels: awaiting merge, type-crash

#102528 [3.11] GH-102397: Fix segfault from race condition in signal handling (GH-102399)
  Lib/test/test_signal.py
  Misc/NEWS.d/next/Core and Builtins/2023-03-04-06-48-34.gh-issue-102397.ACJaOf.rst
  Modules/signalmodule.c
Labels: awaiting merge, type-crash

#102529 [3.10] gh-101100: Fix sphinx warnings in `zipapp` and `zipfile` modules (GH-102526)
  Doc/library/zipapp.rst
  Doc/library/zipfile.rst
Labels: docs, awaiting merge, skip news

#101963 Remove or update bitbucket links
  Doc/distributing/index.rst
  Doc/installing/index.rst
  Doc/library/venv.rst
  Lib/test/test_pathlib.py
  PC/launcher.c
  PC/launcher2.c
Labels: skip issue, awaiting merge, skip news

#102516 gh-102515: Remove unused imports in the `Lib/` directory
  Lib/_pylong.py
  Lib/concurrent/futures/process.py
  Lib/dataclasses.py
  Lib/importlib/_abc.py
  Lib/sysconfig.py
  Lib/test/_test_venv_multiprocessing.py
  Lib/test/fork_wait.py
  Lib/test/test__xxinterpchannels.py
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_asyncgen.py
  Lib/test/test_asyncio/test_ssl.py
  Lib/test/test_asyncio/test_subprocess.py
  Lib/test/test_ctypes/test_callbacks.py
  Lib/test/test_dataclasses.py
  Lib/test/test_enum.py
  Lib/test/test_grammar.py
  Lib/test/test_hashlib.py
  Lib/test/test_httplib.py
  Lib/test/test_imaplib.py
  Lib/test/test_isinstance.py
  Lib/test/test_minidom.py
  Lib/test/test_peg_generator/test_c_parser.py
  Lib/test/test_shlex.py
  Lib/test/test_sys_setprofile.py
  Lib/test/test_sys_settrace.py
  Lib/test/test_tkinter/test_widgets.py
  Lib/test/test_tools/test_sundry.py
  Lib/test/test_traceback.py
  Lib/test/test_ttk/test_widgets.py
  Lib/test/test_unicodedata.py
  Lib/test/test_unittest/test_loader.py
  Lib/test/test_wmi.py
  Lib/test/test_zipfile64.py
Labels: awaiting merge, skip news, stdlib

#102531 gh-102507 Remove invisible pagebreak characters
  Lib/email/__init__.py
  Lib/email/base64mime.py
  Lib/email/charset.py
  Lib/email/encoders.py
  Lib/email/feedparser.py
  Lib/email/generator.py
  Lib/email/header.py
  Lib/email/iterators.py
  Lib/email/mime/base.py
  Lib/email/mime/message.py
  Lib/email/mime/multipart.py
  Lib/email/mime/nonmultipart.py
  Lib/email/mime/text.py
  Lib/email/parser.py
  Modules/_io/bufferedio.c
  Tools/i18n/pygettext.py
Labels: awaiting merge, skip news

#102218 gh-102192: Replace PyErr_Fetch/Restore etc by more efficient alternatives (in Objects/)
  Objects/dictobject.c
  Objects/exceptions.c
  Objects/frameobject.c
  Objects/genobject.c
  Objects/object.c
  Objects/odictobject.c
  Objects/typeobject.c
  Objects/weakrefobject.c
Labels: awaiting merge, skip news

#102514 gh-102304: Consolidate Direct Usage of _Py_RefTotal
  Include/cpython/object.h
  Include/internal/pycore_object.h
  Include/object.h
  Modules/_testcapimodule.c
  Objects/bytesobject.c
  Objects/dictobject.c
  Objects/object.c
  Objects/structseq.c
  Objects/tupleobject.c
  Objects/unicodeobject.c
Labels: awaiting core review, skip news

#102334 gh-100227: Move func_state.next_version to PyInterpreterState
  Include/internal/pycore_function.h
  Include/internal/pycore_interp.h
  Include/internal/pycore_runtime.h
  Include/internal/pycore_runtime_init.h
  Objects/funcobject.c
Labels: awaiting core review, skip news

#102548 GH-84783: Document GH-101264 (Make the slice object hashable) in What's New.
  Doc/whatsnew/3.12.rst
Labels: docs, awaiting merge, skip news

#101941 gh-100227: Isolate the Import State to Each Interpreter
  Include/cpython/import.h
  Include/internal/pycore_import.h
  Include/internal/pycore_runtime_init.h
  Modules/posixmodule.c
  Python/import.c
Labels: awaiting core review, skip news

#102256 gh-102255: Improve build support on xbox
  Include/internal/pycore_fileutils.h
  Lib/test/test_os.py
  Misc/NEWS.d/next/Core and Builtins/2023-02-26-11-43-56.gh-issue-102255.cRnI5x.rst
  Modules/_io/_iomodule.c
  Modules/_io/_iomodule.h
  Modules/_io/clinic/winconsoleio.c.h
  Modules/_io/fileio.c
  Modules/_io/winconsoleio.c
  Modules/_localemodule.c
  Modules/_multiprocessing/multiprocessing.h
  Modules/_pickle.c
  Modules/_randommodule.c
  Modules/_ssl.c
  Modules/_winapi.c
  Modules/clinic/posixmodule.c.h
  Modules/errnomodule.c
  Modules/faulthandler.c
  Modules/getpath.c
  Modules/mmapmodule.c
  Modules/posixmodule.c
  Modules/selectmodule.c
  Modules/socketmodule.c
  Modules/timemodule.c
  Objects/obmalloc.c
  PC/clinic/msvcrtmodule.c.h
  PC/clinic/winreg.c.h
  PC/config.c
  PC/config_minimal.c
  PC/msvcrtmodule.c
  PC/pyconfig.h
  PC/winreg.c
  Parser/myreadline.c
  Python/dynload_win.c
  Python/fileutils.c
  Python/pylifecycle.c
  Python/sysmodule.c
Labels: OS-windows, awaiting review, interpreter-core, extension-modules, build

#102379 gh-102378: don't bother stripping `/` from __text_signature__
  Lib/inspect.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2023-03-03-19-53-08.gh-issue-102378.kRdOZc.rst
Labels: awaiting merge

#102477 gh-102192: Replace PyErr_Fetch/Restore etc by more efficient alternatives in types
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/callproc.c
Labels: awaiting merge, skip news, expert-ctypes, 3.12

#102544 gh-102519: Add os.listdrives, os.listvolumes and os.listmounts on Windows
  Doc/whatsnew/3.12.rst
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Include/internal/pycore_unicodeobject_generated.h
  Lib/test/test_os.py
  Misc/NEWS.d/next/Library/2023-03-08-23-08-38.gh-issue-102519.wlcsFI.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting core review

#101824 gh-86509: docs for thread-local data - add link to _threading_local.py
  Doc/library/threading.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#102575 [3.11] gh-86509: Add link to Lib/_threading_local.py in threading docs (GH-101824)
  Doc/library/threading.rst
Labels: docs, awaiting merge, skip news

#102538 GH-102537: Handle check for PYTHONTZPATH failing in zoneinfo test
  Lib/test/test_zoneinfo/test_zoneinfo.py
  Misc/NEWS.d/next/Tests/2023-03-08-13-54-20.gh-issue-102537.Vfplpb.rst
Labels: tests, awaiting merge, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#102586 [3.11] GH-102537: Handle check for PYTHONTZPATH failing in zoneinfo test (GH-102538)
  Lib/test/test_zoneinfo/test_zoneinfo.py
  Misc/NEWS.d/next/Tests/2023-03-08-13-54-20.gh-issue-102537.Vfplpb.rst
Labels: tests, awaiting merge

#102454 GH-80486: Fix handling of NTFS alternate data streams in pathlib
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2019-03-15-22-50-27.bpo-36305.Pbkv6u.rst
Labels: OS-windows, awaiting merge, expert-pathlib

#102573 gh-102578: Optimise setting and deleting mutable attributes on non-dataclass subclasses of frozen dataclasses
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2023-03-10-13-21-16.gh-issue-102578.-gujoI.rst
Labels: performance, awaiting merge, stdlib

#102104 gh-102103: add `module` argument to `dataclasses.make_dataclass`
  Doc/library/dataclasses.rst
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2023-02-21-11-56-16.gh-issue-102103.Dj0WEj.rst
Labels: awaiting merge

#101806 gh-88071: Update docstrings of dataclass' astuple and asdict
  Lib/dataclasses.py
Labels: awaiting merge, skip news, stdlib

#102569 GH-90997: Shrink the `LOAD_GLOBAL` caches
  Doc/library/dis.rst
  Include/internal/pycore_code.h
  Include/internal/pycore_opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2023-03-09-13-57-35.gh-issue-90997.J-Yhn2.rst
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
  Python/specialize.c
Labels: performance, awaiting merge, interpreter-core

#102449 gh-102433: Add tests for how classes with properties interact with `isinstance()` checks on `typing.runtime_checkable` protocols
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#102593 [3.10] gh-102433: Add tests for how classes with properties interact with `isinstance()` checks on `typing.runtime_checkable` protocols (GH-102449)
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news

#102592 [3.11] gh-102433: Add tests for how classes with properties interact with `isinstance()` checks on `typing.runtime_checkable` protocols (GH-102449)
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news

#102248 gh-102213: Optimizing the Performance of __getattr__ #102213
  Include/internal/pycore_object.h
  Misc/NEWS.d/next/Core and Builtins/2023-02-26-13-12-55.gh-issue-102213.fTH8X7.rst
  Objects/object.c
  Objects/typeobject.c
Labels: performance, awaiting review, interpreter-core

#11590 gh-79940: add introspection API for asynchronous generators
  Doc/library/inspect.rst
  Doc/whatsnew/3.12.rst
  Lib/inspect.py
  Lib/test/test_inspect.py
  Misc/NEWS.d/next/Library/2023-02-26-17-29-57.gh-issue-79940.SAfmAy.rst
  Objects/genobject.c
Labels: type-feature, expert-asyncio, awaiting merge, 3.12

#102602 [3.11] gh-102493: backport unit test for PyErr_SetObject
  Lib/test/test_capi/test_misc.py
  Modules/_testcapimodule.c
Labels: tests, awaiting core review, skip news, 3.11

#102605 gh-79940: skip `TestGetAsyncGenState` on wasm as it requires working sockets
  Lib/test/test_inspect.py
Labels: tests, awaiting merge, skip news, :robot: automerge

#101822 gh-101821: Cover `ast.main` function
  Lib/test/test_ast.py
Labels: tests, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#102623 Fixes duplicated word
  Doc/library/subprocess.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.7, needs backport to 3.10, needs backport to 3.11

#102624 [3.11] Fixes duplicated word (GH-102623)
  Doc/library/subprocess.rst
Labels: docs, skip issue, awaiting review, skip news

#102626 Optimize fmean() weighted average
  Lib/statistics.py
Labels: performance, skip issue, awaiting core review, skip news, 3.12

#102629 Fix duplicated words in the docs
  Doc/library/base64.rst
  Doc/reference/compound_stmts.rst
  Misc/NEWS.d/3.11.0a6.rst
  Misc/NEWS.d/3.12.0a1.rst
  Misc/NEWS.d/3.12.0a2.rst
Labels: docs, skip issue, awaiting merge, skip news, :robot: automerge

#101674 GH-101673: Fix pdb bug that local variable changes lost after longlist
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-02-09-19-40-41.gh-issue-101673.mX-Ppq.rst
Labels: type-bug, awaiting merge, needs backport to 3.10, stdlib, needs backport to 3.11

#102632 [3.11] GH-101673: Fix pdb bug where local variable changes are lost after longlist (GH-101674)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-02-09-19-40-41.gh-issue-101673.mX-Ppq.rst
Labels: type-bug, awaiting merge, :robot: automerge

#102340 gh-101100: Fix Sphinx warnings in `turtle` module
  Doc/library/turtle.rst
  Lib/turtle.py
Labels: docs, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#102301 GH-102300: Reuse objects with refcount == 1 in float specialized binary ops.
  Misc/NEWS.d/next/Core and Builtins/2023-02-27-15-48-31.gh-issue-102300.8o-_Mt.rst
  Python/bytecodes.c
  Python/ceval_macros.h
  Python/generated_cases.c.h
Labels: awaiting merge

#102587 [3.10] GH-102537: Handle check for PYTHONTZPATH failing in zoneinfo test (GH-102538)
  Lib/test/test_zoneinfo/test_zoneinfo.py
  Misc/NEWS.d/next/Tests/2023-03-08-13-54-20.gh-issue-102537.Vfplpb.rst
Labels: tests, awaiting merge

#102355 Fix broken link to MSDN
  Lib/socket.py
  Lib/test/support/socket_helper.py
Labels: skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#102642 [3.11] Fix broken link to MSDN (GH-102355)
  Lib/socket.py
  Lib/test/support/socket_helper.py
Labels: skip issue, awaiting merge, skip news

#102633 [3.10] GH-101673: Fix pdb bug where local variable changes are lost after longlist (#101674)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-02-09-19-40-41.gh-issue-101673.mX-Ppq.rst
Labels: type-bug, awaiting core review

#102645 [3.10] Fix duplicated words in the docs
  Doc/library/base64.rst
  Doc/reference/compound_stmts.rst
Labels: docs, skip issue, awaiting core review, skip news

#102644 [3.11] Fix duplicated words in the docs
  Doc/library/base64.rst
  Doc/reference/compound_stmts.rst
  Misc/NEWS.d/3.11.0a6.rst
Labels: docs, skip issue, awaiting core review, skip news

#102631 gh-102192: Replace PyErr_Fetch/Restore etc by more efficient alternatives
  Python/ceval.c
Labels: awaiting merge, skip news, interpreter-core

#102562 gh-87092: refactor assemble() to a number of separate functions, which do not need the compiler struct
  Lib/test/support/bytecode_helper.py
  Lib/test/test_peepholer.py
  Python/compile.c
Labels: awaiting core review, skip news, interpreter-core

#102651 gh-102650: Remove duplicate include directives from multiple source files
  Mac/Tools/pythonw.c
  Modules/_hashopenssl.c
  Modules/arraymodule.c
  Modules/signalmodule.c
  Programs/_testembed.c
Labels: awaiting review, skip news

#98170 gh-98169 dataclasses.astuple support DefaultDict
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2022-10-10-19-14-51.gh-issue-98169.DBWIxL.rst
Labels: awaiting merge

#102075 gh-102069: Fix `__weakref__` descriptor generation for custom dataclasses
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2023-02-20-16-47-56.gh-issue-102069.FS7f1j.rst
Labels: awaiting merge, needs backport to 3.11

#102659 gh-101659: Avoid Allocation for Shared Exceptions in the _xxsubinterpreters Module
  Modules/_xxsubinterpretersmodule.c
Labels: awaiting core review, skip news

#102409 gh-98831: Use DECREF_INPUTS() more
  Python/bytecodes.c
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#102662 [3.11] gh-102069: Fix `__weakref__` descriptor generation for custom dataclasses (GH-102075)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2023-02-20-16-47-56.gh-issue-102069.FS7f1j.rst
Labels: awaiting review

#102630 gh-102627: Replace address pointing toward malicious web page
  Doc/library/concurrent.futures.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#102665 [3.10] gh-102627: Replace address pointing toward malicious web page (GH-102630)
  Doc/library/concurrent.futures.rst
Labels: docs, awaiting merge, skip news

#102664 [3.11] gh-102627: Replace address pointing toward malicious web page (GH-102630)
  Doc/library/concurrent.futures.rst
Labels: docs, awaiting merge, skip news

#102668 [3.7] gh-102627: Replace address pointing toward malicious web page (GH-102630)
  Doc/library/concurrent.futures.rst
Labels: docs, awaiting merge, skip news

#102666 [3.9] gh-102627: Replace address pointing toward malicious web page (GH-102630)
  Doc/library/concurrent.futures.rst
Labels: docs, awaiting merge, skip news

#102667 [3.8] gh-102627: Replace address pointing toward malicious web page (GH-102630)
  Doc/library/concurrent.futures.rst
Labels: docs, awaiting merge, skip news

#102649 GH-102670: Use sumprod() to simplify, speed up, and improve accuracy of statistics functions
  Lib/statistics.py
  Lib/test/test_statistics.py
  Misc/NEWS.d/next/Library/2023-03-13-18-27-00.gh-issue-102670.GyoThv.rst
Labels: performance, awaiting core review, 3.12

#102014 gh-102013: Add PyUnstable_GC_VisitObjects
  Doc/c-api/gcsupport.rst
  Include/objimpl.h
  Misc/NEWS.d/next/C API/2023-02-18-00-55-14.gh-issue-102013.83mrtI.rst
  Modules/_testcapimodule.c
  Modules/gcmodule.c
Labels: awaiting merge

#102677 doc: Remove a duplicate 'versionchanged' in library/asyncio-task
  Doc/library/asyncio-task.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#102678 [3.11] doc: Remove a duplicate 'versionchanged' in library/asyncio-task (gh-102677)
  Doc/library/asyncio-task.rst
Labels: docs, skip issue, awaiting merge, skip news

#102679 [3.10] doc: Remove a duplicate 'versionchanged' in library/asyncio-task (gh-102677)
  Doc/library/asyncio-task.rst
Labels: docs, skip issue, awaiting merge, skip news
