Repository python/cpython, pull requests merged in 2023-10, with the labels that each got.

#110165 gh-109649: Use os.process_cpu_count()
  Doc/library/compileall.rst
  Doc/library/concurrent.futures.rst
  Doc/library/multiprocessing.rst
  Doc/whatsnew/3.13.rst
  Lib/concurrent/futures/process.py
  Lib/concurrent/futures/thread.py
  Lib/multiprocessing/pool.py
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/utils.py
  Lib/test/pythoninfo.py
  Lib/test/test_concurrent_futures/test_thread_pool.py
  Misc/NEWS.d/next/Library/2023-10-01-01-47-21.gh-issue-109649.BizOaD.rst
  Modules/_decimal/tests/deccheck.py
  Tools/freeze/test/freeze.py
  Tools/ssl/multissltests.py
  Tools/wasm/wasm_build.py
Labels: awaiting core review

#110151 gh-110150: Fix base case handling in quantiles()
  Doc/library/statistics.rst
  Lib/statistics.py
  Lib/test/test_statistics.py
  Misc/NEWS.d/next/Library/2023-09-30-12-50-47.gh-issue-110150.9j0Ij5.rst
Labels: type-bug, awaiting review

#110170 gh-110160: Fix flaky `test_find_periodic_pattern` in `string_tests`
  Lib/test/string_tests.py
Labels: awaiting core review, skip news, needs backport to 3.12

#107640 GH-107465: Add `pathlib.Path.from_uri()` classmethod.
  Doc/library/pathlib.rst
  Doc/whatsnew/3.13.rst
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2023-08-04-19-00-53.gh-issue-107465.Vc1Il3.rst
Labels: awaiting core review, topic-pathlib

#110181 gh-110180: Remove unused `_PickleUsingNameMixin` class from `typing`
  Lib/typing.py
Labels: awaiting core review, skip news, topic-typing

#110144 gh-101100: Fix sphinx warnings in `library/site.rst`
  Doc/library/exceptions.rst
  Doc/library/site.rst
  Doc/tools/.nitignore
Labels: docs, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#110185 [3.11] gh-101100: Fix sphinx warnings in `library/site.rst` (GH-110144)
  Doc/library/exceptions.rst
  Doc/library/site.rst
  Doc/tools/.nitignore
Labels: awaiting review, skip news

#110142 gh-110138: Improve grammar in idiomatic usage of ``__main__.py``
  Doc/library/__main__.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#110189 [3.11] gh-110138: Improve grammar in idiomatic usage of ``__main__.py`` (GH-110142)
  Doc/library/__main__.rst
Labels: docs, awaiting review, skip news

#110168 gh-110164: regrtest disables random if SOURCE_DATE_EPOCH
  Lib/test/libregrtest/main.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-01-02-58-00.gh-issue-110164.z7TMCq.rst
Labels: tests, awaiting review

#110183 [3.11] gh-110160: Fix flaky `test_find_periodic_pattern` in `string_tests` (…
  Lib/test/string_tests.py
Labels: awaiting review, skip news

#110191 fix misaligned versionchanged blocks in sqlite3 docs
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting core review, skip news

#109995 gh-109590 - Update shutil.which on win32 to only give back PATHEXT matches by default
  Doc/library/shutil.rst
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2023-09-24-06-04-14.gh-issue-109590.9EMofC.rst
Labels: awaiting review

#110056 [3.12] gh-109991: Update Windows build to use OpenSSL 3.0.11 (GH-110054)
  Misc/NEWS.d/next/Windows/2023-09-28-17-09-23.gh-issue-109991.CIMftz.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: awaiting review

#110140 [3.12] GH-101100: Fix reference warnings for ``gettext`` (GH-110115)
  Doc/library/gettext.rst
Labels: docs, awaiting core review, skip news

#110187 [3.12] gh-101100: Fix sphinx warnings in `library/site.rst` (GH-110144)
  Doc/library/exceptions.rst
  Doc/library/site.rst
  Doc/tools/.nitignore
Labels: awaiting core review, skip news

#110188 [3.12] gh-110138: Improve grammar in idiomatic usage of ``__main__.py`` (GH-110142)
  Doc/library/__main__.rst
Labels: docs, awaiting core review, skip news

#110135 [3.12] GH-101100: Fix reference warnings for ``namedtuple`` (GH-110113)
  Doc/whatsnew/2.6.rst
  Misc/NEWS.d/3.8.0a1.rst
Labels: docs, awaiting core review, skip news

#109929 [3.12] gh-107888: Fix test_mmap.test_access_parameter() on macOS 14 (GH-109928)
  Lib/test/test_mmap.py
Labels: tests, awaiting core review, skip news

#110208 Docs: bump Pygments to fix contrast ratios to meet WCAG AA guidelines
  Doc/constraints.txt
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#108018 GH-92584: Move installation schemes overview to sysconfig docs
  Doc/library/site.rst
  Doc/library/sysconfig.rst
  Doc/using/cmdline.rst
Labels: docs, awaiting review, skip news, needs backport to 3.11, needs backport to 3.12

#110211 [3.11] Docs: bump Pygments to fix contrast ratios to meet WCAG AA guidelines (GH-110208)
  Doc/constraints.txt
Labels: skip issue, awaiting core review, skip news

#110213 [3.12] GH-92584: Move installation schemes overview to sysconfig docs (GH-108018)
  Doc/library/site.rst
  Doc/library/sysconfig.rst
  Doc/using/cmdline.rst
Labels: docs, awaiting review, skip news

#110210 [3.12] Docs: bump Pygments to fix contrast ratios to meet WCAG AA guidelines (GH-110208)
  Doc/constraints.txt
Labels: skip issue, awaiting core review, skip news

#109491 gh-108963: using random to generate unique string in sys.intern test
  Lib/test/test_sys.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12

#110117 GH-109190: Announce final release in What's New in Python 3.12
  Doc/whatsnew/3.12.rst
Labels: docs, awaiting review, skip news, needs backport to 3.12

#110215 [3.12] GH-109190: Announce final release in What's New in Python 3.12 (GH-110117)
  Doc/whatsnew/3.12.rst
Labels: docs, awaiting core review, skip news

#108101 gh-83180: Made launcher treat shebang 'python' tags as low priority so that active virtual environments are preferred
  Doc/using/windows.rst
  Lib/test/test_launcher.py
  Misc/NEWS.d/next/Windows/2023-08-18-00-01-21.gh-issue-83180.DdLffv.rst
  PC/launcher2.c
Labels: OS-windows, awaiting core review

#109578 [3.12] gh-109496: Skip test_capi.test_decref_freed_object() on ASAN (GH-109573)
  Lib/test/test_capi/test_misc.py
Labels: tests, awaiting core review, skip news

#109090 [3.12] gh-88943: Improve syntax error for non-ASCII character that follows a numerical literal (GH-109081)
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core and Builtins/2023-09-07-16-05-36.gh-issue-88943.rH_X3W.rst
  Parser/tokenizer.c
Labels: type-bug, awaiting review

#109133 [3.12] gh-104690: thread_run() checks for tstate dangling pointer (#109056)
  Include/internal/pycore_pystate.h
  Modules/_threadmodule.c
  Python/ceval_gil.c
  Python/pystate.c
Labels: awaiting core review, skip news

#109153 [3.12] Check the result of PySet_Contains() for error in Python/symtable.c (GH-109146)
  Python/symtable.c
Labels: type-bug, skip issue, awaiting review, skip news

#109231 [3.12] gh-50644: Forbid pickling of codecs streams (GH-109180)
  Lib/codecs.py
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Library/2023-09-09-15-08-37.gh-issue-50644.JUAZOh.rst
Labels: type-bug, awaiting review

#109254 [3.12] gh-107219: Fix concurrent.futures terminate_broken() (GH-109244)
  Lib/concurrent/futures/process.py
  Lib/multiprocessing/connection.py
  Misc/NEWS.d/next/Library/2023-09-11-00-32-18.gh-issue-107219.3zqyFT.rst
Labels: awaiting core review

#109280 [3.12] gh-109179: Fix traceback display for SyntaxErrors with notes (#109197)
  Lib/test/test_traceback.py
  Misc/NEWS.d/next/Core and Builtins/2023-09-09-21-17-18.gh-issue-109179.ZR8qs2.rst
  Python/pythonrun.c
Labels: type-bug, awaiting core review, interpreter-core

#109327 [3.12] gh-84867: Do not load tests from TestCase and FunctionTestCase (GH-100497)
  Lib/test/test_unittest/test_loader.py
  Lib/unittest/loader.py
  Misc/NEWS.d/next/Library/2022-12-24-12-50-54.gh-issue-84867.OhaLbU.rst
Labels: awaiting review

#109379 [3.12] gh-109351: Fix crash when compiling AST with invalid NamedExpr (GH-109352)
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2023-09-12-16-00-42.gh-issue-109351.kznGeR.rst
  Python/ast.c
Labels: awaiting core review

#109429 [3.12] gh-109375: Fix bug where pdb registers an alias without an associated command (GH-109376)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2023-09-13-17-22-44.gh-issue-109375.ijJHZ9.rst
Labels: type-bug, awaiting core review

#109550 [3.12] Fix error handling in _PySys_UpdateConfig() (GH-109524)
  Python/sysmodule.c
Labels: type-bug, skip issue, awaiting review, skip news

#109557 [3.12] gh-109546: Add more tests for formatting floats and fractions (GH-109548)
  Lib/test/test_float.py
  Lib/test/test_fractions.py
Labels: tests, awaiting review, skip news

#109558 [3.12] gh-109469: Silence compiler warnings on string comparisons in _testcapi (GH-109533)
  Modules/_testcapi/util.h
Labels: awaiting review, skip news

#109585 [3.12] gh-109580: Skip test_perf_profiler on ASAN build (GH-109584)
  Lib/test/test_perf_profiler.py
  Misc/NEWS.d/next/Tests/2023-09-19-19-08-22.gh-issue-109580.G02Zam.rst
Labels: tests, awaiting core review

#110194 gh-110178: Use fewer weakrefs in test_typing.py
  Lib/test/test_typing.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12

#109614 [3.12] gh-103053: Skip test_freeze_simple_script() on PGO build (#109591)
  Lib/test/libregrtest/utils.py
  Lib/test/pythoninfo.py
  Lib/test/support/__init__.py
  Lib/test/test_tools/test_freeze.py
  Misc/NEWS.d/next/Tests/2023-09-20-02-32-17.gh-issue-103053.AoUJuK.rst
Labels: awaiting review

#109641 [3.12] gh-109613: _pystat_fromstructstat() checks for exceptions (GH-109618)
  Misc/NEWS.d/next/Library/2023-09-20-17-45-46.gh-issue-109613.P13ogN.rst
  Modules/posixmodule.c
Labels: awaiting core review

#109672 [3.12] gh-108303: Move `ann_module*.py` files to `typinganndata/` folder (GH-108354)
  Lib/test/test_grammar.py
  Lib/test/test_inspect.py
  Lib/test/test_module/__init__.py
  Lib/test/test_opcodes.py
  Lib/test/test_typing.py
  Lib/test/typinganndata/ann_module.py
  Lib/test/typinganndata/ann_module2.py
  Lib/test/typinganndata/ann_module3.py
  Lib/test/typinganndata/ann_module4.py
  Lib/test/typinganndata/ann_module5.py
  Lib/test/typinganndata/ann_module6.py
  Lib/test/typinganndata/ann_module7.py
  Lib/test/typinganndata/ann_module8.py
Labels: awaiting merge, skip news

#109674 [3.12] gh-108303: Create Lib/test/test_dataclasses/ directory (GH-108978)
  Lib/test/.ruff.toml
  Lib/test/test_dataclasses/__init__.py
  Lib/test/test_dataclasses/dataclass_module_1.py
  Lib/test/test_dataclasses/dataclass_module_1_str.py
  Lib/test/test_dataclasses/dataclass_module_2.py
  Lib/test/test_dataclasses/dataclass_module_2_str.py
  Lib/test/test_dataclasses/dataclass_textanno.py
  Makefile.pre.in
Labels: awaiting core review, skip news

#109679 [3.12] gh-108303: Move `test_future` into its own test_future_stmt subdir (#109368)
  Lib/test/libregrtest/runtest.py
  Lib/test/test_future_stmt/__init__.py
  Lib/test/test_future_stmt/badsyntax_future10.py
  Lib/test/test_future_stmt/badsyntax_future3.py
  Lib/test/test_future_stmt/badsyntax_future4.py
  Lib/test/test_future_stmt/badsyntax_future5.py
  Lib/test/test_future_stmt/badsyntax_future6.py
  Lib/test/test_future_stmt/badsyntax_future7.py
  Lib/test/test_future_stmt/badsyntax_future8.py
  Lib/test/test_future_stmt/badsyntax_future9.py
  Lib/test/test_future_stmt/future_test1.py
  Lib/test/test_future_stmt/future_test2.py
  Lib/test/test_future_stmt/test_future.py
  Lib/test/test_future_stmt/test_future_flags.py
  Lib/test/test_future_stmt/test_future_multiple_features.py
  Lib/test/test_future_stmt/test_future_multiple_imports.py
  Lib/test/test_future_stmt/test_future_single_import.py
  Makefile.pre.in
Labels: awaiting review, skip news

#109695 [3.12] gh-109582: test_fork_signal_handling should wait for event (GH-109605)
  Lib/test/test_asyncio/test_unix_events.py
Labels: tests, awaiting review, skip news

#109725 [3.12] gh-106584: Fix exit code for unittest in Python 3.12 (GH-106588)
  Lib/test/test_unittest/test_discovery.py
  Lib/test/test_unittest/test_skipping.py
  Lib/unittest/case.py
  Lib/unittest/result.py
  Misc/NEWS.d/next/Library/2023-07-11-08-56-40.gh-issue-106584.g-SBtC.rst
Labels: awaiting review

#109731 [3.12] gh-109709: Fix asyncio test_stdin_broken_pipe() (GH-109710)
  Lib/asyncio/subprocess.py
  Lib/test/test_asyncio/test_subprocess.py
Labels: awaiting review, skip news

#109752 [3.12] gh-109596: Ensure repeated rules in the grammar are not allowed and fix incorrect soft keywords (GH-109606).
  Grammar/python.gram
  Include/compile.h
  Lib/test/test_peg_generator/test_pegen.py
  Misc/NEWS.d/next/Core and Builtins/2023-09-20-13-18-08.gh-issue-109596.RG0K2G.rst
  Parser/parser.c
  Parser/pegen_errors.c
  Tools/peg_generator/pegen/grammar.py
Labels: awaiting review

#109762 [3.12] gh-109706: Fix multiprocessing test_nested_startmethod() (GH-109707)
  Lib/test/_test_multiprocessing.py
Labels: awaiting review, skip news

#109777 [3.12] gh-109521: Fix obscure cases handling in PyImport_GetImporter() (GH-109522)
  Misc/NEWS.d/next/C API/2023-09-17-21-47-31.gh-issue-109521.JDF6i9.rst
  Python/import.c
Labels: awaiting review

#109784 [3.12] gh-105829: Fix concurrent.futures.ProcessPoolExecutor deadlock (GH-108513)
  Lib/concurrent/futures/process.py
  Lib/test/test_concurrent_futures/test_deadlock.py
  Misc/NEWS.d/next/Library/2023-08-26-12-35-39.gh-issue-105829.kyYhWI.rst
Labels: awaiting core review

#109837 [3.12] gh-109833: Fix asyncio test_wait_for() (GH-109834)
  Lib/test/test_asyncio/test_waitfor.py
Labels: tests, awaiting core review, skip news

#109640 [3.12] gh-109625: Move _ready_to_import() from test_import to support.import_helper (GH-109626)
  Lib/test/support/import_helper.py
  Lib/test/test_import/__init__.py
  Lib/test/test_inspect.py
Labels: awaiting core review, skip news

#109705 [3.12] gh-109702: Increase concurrent_futures deadlock timeout (GH-109703)
  Lib/test/test_concurrent_futures/test_deadlock.py
Labels: tests, awaiting review, skip news

#109892 [3.12] gh-109832: concurrent.futures test_deadlock restores sys.stderr (GH-109887)
  Lib/test/test_concurrent_futures/test_deadlock.py
Labels: tests, awaiting core review, skip news

#109898 [3.12] gh-109593: Fix reentrancy issue in multiprocessing resource_tracker (GH-109629)
  Lib/multiprocessing/resource_tracker.py
  Lib/test/lock_tests.py
  Lib/test/test_importlib/test_locks.py
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Library/2023-09-22-20-16-44.gh-issue-109593.LboaNM.rst
  Modules/_threadmodule.c
Labels: awaiting core review

#109905 [3.12] More informative docstrings in the random module (gh-109745)
  Lib/random.py
Labels: skip issue, awaiting core review, skip news

#109919 [3.12] gh-109845: Make test_ftplib more stable under load (GH-109912)
  Lib/test/test_ftplib.py
Labels: tests, awaiting review, skip news

#109941 [3.12] Remove loop from docstring for asyncio.streams.open_connection (GH-108528)
  Lib/asyncio/streams.py
Labels: skip issue, awaiting core review, skip news

#109950 [3.12] gh-109615: Fix test_tools.test_freeze SRCDIR (#109935)
  Lib/test/libregrtest/main.py
  Lib/test/support/__init__.py
  Lib/test/test_support.py
  Lib/test/test_venv.py
  Tools/freeze/test/freeze.py
Labels: awaiting review, skip news

#109992 [3.12] gh-109955 : Update state transition comments for asyncio.Task (GH-109910)
  Lib/asyncio/tasks.py
Labels: awaiting core review, skip news

#109999 [3.12] gh-109818: `reprlib.recursive_repr` copies `__type_params__` (…
  Lib/reprlib.py
  Lib/test/test_reprlib.py
  Misc/NEWS.d/next/Library/2023-09-25-09-59-59.gh-issue-109818.dLRtT-.rst
Labels: awaiting review

#110021 [3.12] gh-109594: Fix concurrent.futures test_timeout() (GH-110018)
  Lib/test/test_concurrent_futures/test_wait.py
  Misc/NEWS.d/next/Tests/2023-09-28-14-47-14.gh-issue-109594.DB5KPP.rst
Labels: tests, awaiting core review

#110040 [3.12] gh-110033: Fix signal test_interprocess_signal() (GH-110035)
  Lib/test/signalinterproctester.py
  Misc/NEWS.d/next/Tests/2023-09-28-18-14-52.gh-issue-110033.2yHMx0.rst
Labels: awaiting core review

#110043 [3.12] gh-110038: KqueueSelector must count all read/write events (GH-110039)
  Lib/selectors.py
  Lib/test/test_selectors.py
  Misc/NEWS.d/next/Library/2023-09-28-18-50-33.gh-issue-110038.nx_gCu.rst
Labels: awaiting core review

#110060 [3.12] gh-109960: Remove test_pty timeout of 10 seconds (GH-110058)
  Lib/test/test_pty.py
Labels: tests, awaiting core review, skip news

#110064 [3.12] gh-110036: multiprocessing Popen.terminate() catches PermissionError (GH-110037)
  Lib/multiprocessing/popen_spawn_win32.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2023-09-28-18-53-11.gh-issue-110036.fECxTj.rst
Labels: awaiting core review

#110071 [3.12] gh-110052: Fix faulthandler for freed tstate (#110069)
  Modules/faulthandler.c
  Python/traceback.c
Labels: awaiting review, skip news

#110106 [3.12] gh-109592: test_eintr tolerates 20 ms when comparing timings (GH-110102)
  Lib/test/_test_eintr.py
Labels: awaiting core review, skip news

#110126 [3.12] gh-109047: concurrent.futures catches RuntimeError (#109810)
  Lib/concurrent/futures/process.py
  Lib/multiprocessing/queues.py
  Lib/test/test_concurrent_futures/test_process_pool.py
  Misc/NEWS.d/next/Library/2023-09-25-02-11-14.gh-issue-109047.b1TrqG.rst
Labels: awaiting review

#110158 [3.12] gh-110088: Fix asyncio test_prompt_cancellation() (GH-110157)
  Lib/test/test_asyncio/test_events.py
Labels: tests, awaiting core review, skip news

#110182 [3.12] gh-110160: Fix flaky `test_find_periodic_pattern` in `string_tests` (GH-110170)
  Lib/test/string_tests.py
Labels: awaiting core review, skip news

#110216 [3.12] gh-108963: using random to generate unique string in sys.intern test …
  Lib/test/test_sys.py
Labels: tests, awaiting review, skip news

#110220 [3.12] 3.12 What's New: Remove duplicate "up to" (GH-110219)
  Doc/whatsnew/3.12.rst
Labels: docs, skip issue, awaiting core review, skip news

#110217 gh-110014: Remove PY_TIMEOUT_MAX from limited C API
  Doc/data/stable_abi.dat
  Doc/whatsnew/3.13.rst
  Include/cpython/pythread.h
  Include/pythread.h
  Lib/test/test_stable_abi_ctypes.py
  Misc/NEWS.d/next/C API/2023-10-02-13-39-57.gh-issue-110014.gfQ4jU.rst
  Misc/stable_abi.toml
  PC/python3dll.c
Labels: awaiting review

#110077 gh-108494: Document how to add a project in PCbuild/readme.txt
  PCbuild/readme.txt
  Tools/msi/test/test_files.wxs
Labels: awaiting review, skip news, needs backport to 3.11, needs backport to 3.12

#110224 [3.12] gh-110178: Use fewer weakrefs in test_typing.py (GH-110194)
  Lib/test/test_typing.py
Labels: tests, awaiting core review, skip news

#108763 gh-107073: Make PyObject_VisitManagedDict() public
  Doc/c-api/object.rst
  Doc/c-api/typeobj.rst
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.13.rst
  Include/cpython/object.h
  Misc/NEWS.d/next/C API/2023-09-01-15-35-05.gh-issue-107073.zCz0iN.rst
  Modules/_asynciomodule.c
  Modules/_testcapi/heaptype.c
  Modules/_testcapimodule.c
  Objects/dictobject.c
  Objects/typeobject.c
  Objects/typevarobject.c
Labels: awaiting core review

#109621 [3.12] Fix typos in docs and comments (#109619)
  Doc/c-api/exceptions.rst
  Doc/library/typing.rst
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.5.rst
  Lib/test/test_descr.py
  Lib/test/test_dynamic.py
  Lib/test/test_frame.py
  Lib/test/test_unpack.py
  Objects/object_layout.md
Labels: skip issue, awaiting merge, skip news

#110231 [3.12] Sync factor() recipe with main branch
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting review, skip news

#110233 [3.12] gh-109782: Ensure `os.path.isdir` has the same signature on all platforms (GH-109790)
  Misc/NEWS.d/next/Library/2023-09-24-16-43-33.gh-issue-109782.gMC_7z.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting review

#110103 [3.12] gh-110031: Skip test_threading fork tests if ASAN (#110100)
  Lib/test/test_threading.py
  Misc/NEWS.d/next/Tests/2023-09-29-14-11-30.gh-issue-110031.fQnFnc.rst
Labels: tests, awaiting review

#110098 [3.12] gh-110088, gh-109878: Fix test_asyncio timeouts (#110092)
  Lib/test/test_asyncio/test_base_events.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_asyncio/test_timeouts.py
  Lib/test/test_asyncio/test_waitfor.py
  Lib/test/test_asyncio/test_windows_events.py
  Lib/test/test_asyncio/utils.py
  Misc/NEWS.d/next/Tests/2023-09-29-12-48-42.gh-issue-110088.qUhRga.rst
Labels: awaiting core review

#110232 [3.11] gh-108494: Document how to add a project in PCbuild/readme.txt (#110077)
  PCbuild/readme.txt
Labels: awaiting review, skip news

#110230 [3.12] gh-108494: Document how to add a project in PCbuild/readme.txt (GH-110077)
  PCbuild/readme.txt
Labels: awaiting review, skip news

#109994 gh-109853: Fix sys.path[0] For Subinterpreters
  Include/cpython/initconfig.h
  Lib/test/test_embed.py
  Lib/test/test_interpreters.py
  Misc/NEWS.d/next/Core and Builtins/2023-09-27-18-01-06.gh-issue-109853.coQQiL.rst
  Modules/main.c
  Python/initconfig.c
  Python/pylifecycle.c
Labels: awaiting review, needs backport to 3.12

#109921 gh-105716: Support Background Threads in Subinterpreters Consistently
  Include/cpython/pystate.h
  Include/internal/pycore_interp.h
  Include/internal/pycore_pystate.h
  Lib/test/test_interpreters.py
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Core and Builtins/2023-09-26-14-00-25.gh-issue-105716.SUJkW1.rst
  Modules/_threadmodule.c
  Modules/_xxsubinterpretersmodule.c
  Modules/main.c
  Python/pystate.c
Labels: awaiting review, needs backport to 3.12

#110179 Enable ruff on `Lib/test/test_typing.py`
  .pre-commit-config.yaml
  Lib/test/.ruff.toml
  Lib/test/test_typing.py
Labels: skip issue, awaiting core review, skip news, topic-typing

#110236 gh-76785: Module-level Fixes for test.support.interpreters
  Lib/test/support/interpreters.py
  Lib/test/test_interpreters.py
  Modules/_xxinterpchannelsmodule.c
Labels: awaiting review, skip news

#110242 gh-110241: Add missing error check to `record_eval` in `_testinternalcapi`
  Modules/_testinternalcapi.c
Labels: awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#110244 [3.12] gh-110241: Add missing error check to `record_eval` in `_testinternalcapi` (GH-110242)
  Modules/_testinternalcapi.c
Labels: awaiting review, skip news

#110221 gh-109653: Fix py312 regression in the import time of `random`
  Lib/random.py
  Misc/NEWS.d/next/Library/2023-10-02-15-40-10.gh-issue-109653.iB0peK.rst
Labels: performance, awaiting core review, stdlib, needs backport to 3.12

#110247 [3.12] gh-109653: Fix py312 regression in the import time of `random` (GH-110221)
  Lib/random.py
  Misc/NEWS.d/next/Library/2023-10-02-15-40-10.gh-issue-109653.iB0peK.rst
Labels: awaiting review

#110249 Add --inline-caches flag to dis command line
  Lib/dis.py
  Misc/NEWS.d/next/Library/2023-10-03-00-04-26.gh-issue-110249.K0mMrs.rst
Labels: skip issue, awaiting review

#110240 Remove unused Misc/requirements-test.txt
  Misc/requirements-test.txt
Labels: skip issue, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#110253 [3.12] Remove unused Misc/requirements-test.txt (GH-110240)
  Misc/requirements-test.txt
Labels: skip issue, awaiting review, skip news

#110254 [3.11] Remove unused Misc/requirements-test.txt (GH-110240)
  Misc/requirements-test.txt
Labels: skip issue, awaiting review, skip news

#110255 Fix typo in py312 whatsnew: add missing closing paren
  Doc/whatsnew/3.12.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12

#110257 [3.12] Fix typo in py312 whatsnew: add missing closing paren (GH-110255)
  Doc/whatsnew/3.12.rst
Labels: docs, skip issue, awaiting review, skip news

#109957 gh-109956: Also test `typing.NamedTuple` with `copy.replace`
  Lib/test/test_copy.py
Labels: tests, awaiting core review, skip news

#110277 gh-110276: Run `test_str`, not `test_unicode`, as part of the PGO build
  Lib/test/libregrtest/pgo.py
Labels: awaiting core review, skip news

#110281 [3.11] Bump various dependencies in `Doc/requirements-oldest-sphinx.txt` (GH-110278)
  Doc/requirements-oldest-sphinx.txt
Labels: skip issue, awaiting review, skip news

#110280 [3.12] Bump various dependencies in `Doc/requirements-oldest-sphinx.txt` (GH-110278)
  Doc/requirements-oldest-sphinx.txt
Labels: skip issue, awaiting review, skip news

#110272 gh-110267: Add tests for pickling and copying PyStructSequence objects
  Lib/test/test_structseq.py
  Misc/NEWS.d/next/Tests/2023-10-03-10-54-09.gh-issue-110267.O-c47G.rst
Labels: tests, awaiting core review

#109322 Enhanced sqlite3 connection context management documentation with contextlib.closing gh-109234
  Doc/library/sqlite3.rst
Labels: awaiting review, skip news

#110290 [3.11] Enable ruff on `Lib/test/test_typing.py` (#110179)
  .pre-commit-config.yaml
  Lib/test/.ruff.toml
  Lib/test/test_typing.py
Labels: skip issue, awaiting review, skip news

#110288 [3.12] Enable ruff on `Lib/test/test_typing.py` (#110179)
  .pre-commit-config.yaml
  Lib/test/.ruff.toml
  Lib/test/test_typing.py
Labels: skip issue, awaiting review, skip news

#110245 gh-109860: Use a New Thread State When Switching Interpreters, When Necessary
  Include/cpython/pystate.h
  Include/internal/pycore_pystate.h
  Include/internal/pycore_runtime_init.h
  Lib/threading.py
  Modules/_threadmodule.c
  Modules/_xxsubinterpretersmodule.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: awaiting review, skip news, needs backport to 3.12

#110291 gh-107073: Mention pythoncapi-compat for PyObject_VisitManagedDict()
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting review, skip news

#110293 [3.11] gh-109234: Hint to contextlib.closing in sqlite3 context manager docs (GH-109322)
  Doc/library/sqlite3.rst
Labels: docs, awaiting review, skip news

#110294 [3.12] gh-109234: Hint to contextlib.closing in sqlite3 context manager docs (GH-109322)
  Doc/library/sqlite3.rst
Labels: docs, awaiting review, skip news

#110295 gh-110276: No longer ignore PROFILE_TASK failure silently
  Doc/using/configure.rst
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2023-10-03-17-55-09.gh-issue-110276.luaKRg.rst
Labels: awaiting review

#108870 gh-108867: Add PyThreadState_GetUnchecked() function
  Doc/c-api/init.rst
  Doc/whatsnew/3.13.rst
  Include/cpython/object.h
  Include/cpython/pystate.h
  Include/internal/pycore_pystate.h
  Include/pystate.h
  Misc/NEWS.d/next/C API/2023-09-04-11-47-12.gh-issue-108867.Cr_LKd.rst
  Modules/_testcapimodule.c
  Modules/getpath.c
  Python/pystate.c
Labels: awaiting core review

#110193 gh-109979: Auto-generate the target for DEOPT_IF()
  Lib/test/test_generated_cases.py
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Tools/cases_generator/analysis.py
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/instructions.py
  Tools/cases_generator/stacking.py
Labels: awaiting review, skip news

#110292 Docs: Avoid the deprecated ``.. cmdoption::`` directive
  Doc/library/ast.rst
  Doc/library/compileall.rst
  Doc/library/gzip.rst
  Doc/library/inspect.rst
  Doc/library/json.rst
  Doc/library/pickletools.rst
  Doc/library/py_compile.rst
  Doc/library/site.rst
  Doc/library/tarfile.rst
  Doc/library/timeit.rst
  Doc/library/tokenize.rst
  Doc/library/trace.rst
  Doc/library/unittest.rst
  Doc/library/uuid.rst
  Doc/library/zipapp.rst
  Doc/library/zipfile.rst
  Doc/using/cmdline.rst
  Doc/using/configure.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#110302 [3.12] Docs: Avoid the deprecated ``.. cmdoption::`` directive (GH-110292)
  Doc/library/ast.rst
  Doc/library/compileall.rst
  Doc/library/gzip.rst
  Doc/library/inspect.rst
  Doc/library/json.rst
  Doc/library/pickletools.rst
  Doc/library/py_compile.rst
  Doc/library/site.rst
  Doc/library/tarfile.rst
  Doc/library/timeit.rst
  Doc/library/tokenize.rst
  Doc/library/trace.rst
  Doc/library/unittest.rst
  Doc/library/uuid.rst
  Doc/library/zipapp.rst
  Doc/library/zipfile.rst
  Doc/using/cmdline.rst
  Doc/using/configure.rst
Labels: docs, skip issue, awaiting core review, skip news

#110248 gh-76785: Print the Traceback from Interpreter.run()
  Modules/_xxsubinterpretersmodule.c
Labels: awaiting review, skip news

#110314 Revert "gh-76785: Print the Traceback from Interpreter.run() (gh-110248)"
  Modules/_xxsubinterpretersmodule.c
Labels: awaiting review, skip news

#110306 gh-109917: Fix test instability in test_concurrent_futures
  Lib/test/test_concurrent_futures/test_deadlock.py
Labels: tests, skip issue, awaiting review, skip news, 3.11, 3.12, 3.13

#110316 [3.11] gh-109917: Fix test instability in test_concurrent_futures (GH-110306)
  Lib/test/test_concurrent_futures/test_deadlock.py
Labels: tests, skip issue, awaiting review, skip news

#110315 [3.12] gh-109917: Fix test instability in test_concurrent_futures (GH-110306)
  Lib/test/test_concurrent_futures/test_deadlock.py
Labels: tests, skip issue, awaiting review, skip news

#110301 gh-109979: Unify _GUARD_TYPE_VERSION{,_STORE}
  Include/internal/pycore_opcode_metadata.h
  Python/abstract_interp_cases.c.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting review, skip news

#110318 gh-110300: Fix Refleaks in test_interpreters and test__xxinterpchannels
  Lib/test/support/interpreters.py
  Lib/test/test_interpreters.py
  Modules/_xxinterpchannelsmodule.c
Labels: skip news

#110028 gh-85984: Document change in return type of tty functions
  Doc/library/tty.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.12

#110286 gh-109653: Defer importing `warnings` in several modules
  Lib/argparse.py
  Lib/calendar.py
  Lib/getpass.py
  Lib/shutil.py
  Lib/tarfile.py
  Misc/NEWS.d/next/Library/2023-10-03-15-17-03.gh-issue-109653.9DYOMD.rst
Labels: performance, awaiting core review

#110274 gh-110273: dataclasses.replace() now raise TypeError for all invalid arguments
  Lib/dataclasses.py
  Lib/test/test_dataclasses/__init__.py
  Misc/NEWS.d/next/Library/2023-10-03-14-07-05.gh-issue-110273.QaDUmS.rst
Labels: awaiting core review

#110172 gh-110171: `libregrtest` always sets `random.seed` unless `--no-use-randseed` is provided
  Lib/test/libregrtest/cmdline.py
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/setup.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2023-10-01-10-27-02.gh-issue-110171.ZPlo0h.rst
Labels: awaiting review

#110331 gh-110166: Fix gdb CFunctionFullTests on ppc64le clang build
  Lib/test/test_gdb/test_cfunction_full.py
Labels: skip news, needs backport to 3.11, needs backport to 3.12

#110285 [3.12] gh-110267: Add tests for pickling and copying PyStructSequence objects (GH-110272)
  Lib/test/test_structseq.py
  Misc/NEWS.d/next/Tests/2023-10-03-10-54-09.gh-issue-110267.O-c47G.rst
Labels: tests, awaiting review

#110284 [3.11] gh-110267: Add tests for pickling and copying PyStructSequence objects (GH-110272)
  Lib/test/test_structseq.py
  Misc/NEWS.d/next/Tests/2023-10-03-10-54-09.gh-issue-110267.O-c47G.rst
Labels: tests, awaiting review

#110336 gh-110335: asyncio test_unix_events cleans multiprocessing
  Lib/test/test_asyncio/test_unix_events.py
Labels: tests, awaiting review, skip news, needs backport to 3.11, needs backport to 3.12

#110326 gh-109276: regrtest: shorter list of resources
  Lib/test/libregrtest/cmdline.py
  Lib/test/libregrtest/utils.py
  Lib/test/test_regrtest.py
Labels: awaiting core review, skip news

#110339 [3.12] gh-109972: Split test_gdb.py into test_gdb package (#109977)
  Lib/test/libregrtest/runtest.py
  Lib/test/test_gdb.py
  Lib/test/test_gdb/__init__.py
  Lib/test/test_gdb/gdb_sample.py
  Lib/test/test_gdb/test_backtrace.py
  Lib/test/test_gdb/test_cfunction.py
  Lib/test/test_gdb/test_misc.py
  Lib/test/test_gdb/test_pretty_print.py
  Lib/test/test_gdb/util.py
  Makefile.pre.in
  Misc/NEWS.d/next/Tests/2023-09-28-12-25-19.gh-issue-109972.GYnwIP.rst
Labels: tests, skip news, needs backport to 3.11

#110340 [3.12] gh-109615: Fix support test_copy_python_src_ignore() (#109958)
  Lib/shutil.py
  Lib/test/libregrtest/main.py
  Lib/test/pythoninfo.py
  Lib/test/test_support.py
  Lib/test/test_venv.py
  Tools/freeze/test/freeze.py
  Tools/patchcheck/patchcheck.py
Labels: awaiting review, skip news

#110338 [3.12] gh-110335: asyncio test_unix_events cleans multiprocessing (GH-110336)
  Lib/test/test_asyncio/test_unix_events.py
Labels: tests, awaiting review, skip news

#110334 gh-110332: Remove mentions of `random.WichmannHill` from `test_zlib`
  Lib/test/test_zlib.py
Labels: tests, awaiting core review, skip news

#110343 [3.11] gh-109972: Split test_gdb.py into test_gdb package (#109977) (…
  Lib/test/libregrtest/runtest.py
  Lib/test/test_gdb.py
  Lib/test/test_gdb/__init__.py
  Lib/test/test_gdb/gdb_sample.py
  Lib/test/test_gdb/test_backtrace.py
  Lib/test/test_gdb/test_cfunction.py
  Lib/test/test_gdb/test_misc.py
  Lib/test/test_gdb/test_pretty_print.py
  Lib/test/test_gdb/util.py
  Makefile.pre.in
  Misc/NEWS.d/next/Tests/2023-09-28-12-25-19.gh-issue-109972.GYnwIP.rst
Labels: awaiting review, skip news

#110341 [3.11] Add test.support.busy_retry() (#93770)
  Doc/library/test.rst
  Lib/test/_test_multiprocessing.py
  Lib/test/fork_wait.py
  Lib/test/support/__init__.py
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_concurrent_futures/test_init.py
  Lib/test/test_multiprocessing_main_handling.py
  Lib/test/test_signal.py
  Lib/test/test_ssl.py
  Lib/test/test_support.py
  Lib/test/test_wait3.py
  Lib/test/test_wait4.py
Labels: skip issue, awaiting review, skip news

#110347 [3.11] gh-108927: Fix test_import + test_importlib + test_unittest problem (GH-108929)
  Lib/unittest/test/test_discovery.py
Labels: tests, awaiting review, skip news

#109152 gh-109151: Enable readline in the sqlite3 CLI
  Lib/sqlite3/__main__.py
  Misc/NEWS.d/next/Library/2023-09-08-19-44-01.gh-issue-109151.GkzkQu.rst
Labels: awaiting core review, needs backport to 3.12

#110348 [3.11] gh-110332: Remove mentions of `random.WichmannHill` from `test_zlib` (GH-110334)
  Lib/test/test_zlib.py
Labels: tests, awaiting review, skip news

#110342 [3.12] gh-108987: Fix _thread.start_new_thread() race condition (#109135)
  Include/internal/pycore_pystate.h
  Misc/NEWS.d/next/Library/2023-09-08-12-09-55.gh-issue-108987.x5AIG8.rst
  Modules/_threadmodule.c
  Python/ceval_gil.c
  Python/pystate.c
Labels: awaiting review

#110349 [3.12] gh-110332: Remove mentions of `random.WichmannHill` from `test_zlib` (GH-110334)
  Lib/test/test_zlib.py
Labels: tests, awaiting review, skip news

#110346 [3.12] gh-109974: Fix threading lock_tests race conditions (#110057)
  Lib/test/lock_tests.py
  Lib/test/test_importlib/test_locks.py
  Misc/NEWS.d/next/Tests/2023-09-29-00-19-21.gh-issue-109974.Sh_g-r.rst
Labels: awaiting review, skip news, needs backport to 3.11

#110351 [3.12] gh-109972: Enhance test_gdb (#110026)
  Lib/test/support/__init__.py
  Lib/test/test_gdb/__init__.py
  Lib/test/test_gdb/test_backtrace.py
  Lib/test/test_gdb/test_cfunction.py
  Lib/test/test_gdb/test_cfunction_full.py
  Lib/test/test_gdb/test_misc.py
  Lib/test/test_gdb/test_pretty_print.py
  Lib/test/test_gdb/util.py
  Misc/NEWS.d/next/Tests/2023-09-13-05-58-09.gh-issue-104736.lA25Fu.rst
Labels: awaiting review, skip news, needs backport to 3.11

#109982 [3.12] Enhance TypedDict docs around required/optional keys (GH-109547)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting core review, skip news
