Repository python/cpython, pull requests merged in 2023-08, with the labels that each got.

#107201 gh-89013: Improve the performance of methodcaller (lazy version)
  Misc/NEWS.d/next/Library/2021-08-16-17-52-26.bpo-44850.r8jx5u.rst
  Modules/_operator.c
Labels: awaiting merge

#106875 gh-106092: Fix use-after-free crash in frame_dealloc
  Misc/NEWS.d/next/Core and Builtins/2023-07-18-16-13-51.gh-issue-106092.bObgRM.rst
  Objects/frameobject.c
Labels: awaiting merge, release-blocker

#107533 [3.11] gh-106092: Fix use-after-free crash in frame_dealloc (GH-106875)
  Misc/NEWS.d/next/Core and Builtins/2023-07-18-16-13-51.gh-issue-106092.bObgRM.rst
  Objects/frameobject.c
Labels: awaiting review

#107532 [3.12] gh-106092: Fix use-after-free crash in frame_dealloc (GH-106875)
  Misc/NEWS.d/next/Core and Builtins/2023-07-18-16-13-51.gh-issue-106092.bObgRM.rst
  Objects/frameobject.c
Labels: awaiting review

#107469 gh-107467: Restructure Argument Clinic command-line interface
  Lib/test/test_clinic.py
  Misc/NEWS.d/next/Tools-Demos/2023-07-30-23-32-16.gh-issue-107467.5O9p3G.rst
  Tools/clinic/clinic.py
Labels: awaiting merge

#107534 gh-105481: the ENABLE_SPECIALIZATION flag does not need to be generated by the build script, or exposed in opcode.py
  Doc/whatsnew/3.13.rst
  Include/internal/pycore_code.h
  Include/opcode.h
  Lib/opcode.py
  Lib/test/support/__init__.py
  Misc/NEWS.d/next/Library/2023-08-01-15-17-20.gh-issue-105481.vMbmj_.rst
  Modules/_opcode.c
  Tools/build/generate_opcode_h.py
Labels: awaiting merge

#107540 gh-105481: combine regen-opcode-targets with regen-opcode to avoid calculating the specialized opcodes in two places
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2023-08-01-17-12-53.gh-issue-105481.42nsDE.rst
  PCbuild/regen.targets
  Python/makeopcodetargets.py
  Tools/build/generate_opcode_h.py
Labels: awaiting merge

#107541 gh-104683: Argument clinic: remove the `LandMine` class
  Lib/test/test_clinic.py
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107511 Typing docs: clarify the effect in subclasses of using `Self` as a return type
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news, topic-typing, needs backport to 3.11, needs backport to 3.12

#107549 [3.11] Clarify `Self` interaction with subclasses (GH-107511)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news

#107543 gh-104683: Argument clinic: cleanup `DLSParser` `state_foo` methods
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107550 gh-104683: Argument Clinic: Refactor and simplify 'add docstring' states
  Lib/test/test_clinic.py
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107548 [3.12] Clarify `Self` interaction with subclasses (GH-107511)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news

#107555 gh-104146: Remove dead code from Argument Clinic
  Tools/clinic/clinic.py
  Tools/clinic/cpp.py
Labels: awaiting merge, skip news

#107514 gh-106368: Increase test coverage for Argument Clinic
  Lib/test/clinic.test.c
  Lib/test/test_clinic.py
Labels: awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107561 gh-105481: simplify definition of pseudo ops in Lib/opcode.py
  Doc/whatsnew/3.13.rst
  Include/opcode.h
  Lib/opcode.py
  Misc/NEWS.d/next/Library/2023-08-01-21-43-58.gh-issue-105481.cl2ajS.rst
  Tools/build/generate_opcode_h.py
Labels: awaiting merge

#107563 GH-100964: Break cycles involving exception state when returning from generator
  Misc/NEWS.d/next/Core and Builtins/2023-07-30-18-05-11.gh-issue-100964.HluhBJ.rst
  Objects/genobject.c
  Python/ceval.c
Labels: awaiting merge

#107566 Fix test_capi.test_misc when run with -R::
  Lib/test/test_capi/test_misc.py
Labels: skip issue, skip news

#107556 gh-104683: Make Argument Clinic template strings class level members
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107569 gh-107471: Fix Refleaks in test_import
  Lib/test/test_import/__init__.py
  Python/import.c
Labels: awaiting merge, skip news, needs backport to 3.12

#107571 [3.12] gh-107471: Fix Refleaks in test_import (gh-107569)
  Lib/test/test_import/__init__.py
  Python/import.c
Labels: awaiting review, skip news

#107456 gh-107455: ctypes: Improve error messages when converting to an incompatible type
  Lib/test/test_ctypes/test_functions.py
  Misc/NEWS.d/next/Core and Builtins/2023-07-30-14-18-49.gh-issue-107455.Es53l7.rst
  Modules/_ctypes/_ctypes.c
Labels: awaiting merge

#107577 GH-107458: fix test_tools refleak
  Lib/test/test_tools/test_sundry.py
Labels: tests, awaiting core review, skip news

#107582 gh-106368: Increase Argument Clinic test coverage
  Lib/test/clinic.test.c
  Lib/test/test_clinic.py
Labels: awaiting merge, skip news

#107586 gh-107077: Raise SSLCertVerificationError even if the error is set via SSL_ERROR_SYSCALL
  Misc/NEWS.d/next/Library/2023-08-03-12-52-19.gh-issue-107077.-pzHD6.rst
  Modules/_ssl.c
Labels: awaiting merge, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11, needs backport to 3.12

#107588 [3.11] gh-107077: Raise SSLCertVerificationError even if the error is set via SSL_ERROR_SYSCALL (GH-107586)
  Misc/NEWS.d/next/Library/2023-08-03-12-52-19.gh-issue-107077.-pzHD6.rst
  Modules/_ssl.c
Labels: awaiting review

#107587 [3.12] gh-107077: Raise SSLCertVerificationError even if the error is set via SSL_ERROR_SYSCALL (GH-107586)
  Misc/NEWS.d/next/Library/2023-08-03-12-52-19.gh-issue-107077.-pzHD6.rst
  Modules/_ssl.c
Labels: awaiting review

#107589 [3.10] gh-107077: Raise SSLCertVerificationError even if the error is set via SSL_ERROR_SYSCALL (GH-107586)
  Misc/NEWS.d/next/Library/2023-08-03-12-52-19.gh-issue-107077.-pzHD6.rst
  Modules/_ssl.c
Labels: awaiting review

#107584 gh-107576: Ensure `__orig_bases__` are our own in `get_original_bases`
  Lib/test/test_types.py
  Lib/types.py
  Misc/NEWS.d/next/Library/2023-08-03-11-31-11.gh-issue-107576.pO_s9I.rst
Labels: awaiting merge, needs backport to 3.12

#107451 gh-107446: Fix test_inspect.test_class_with_method_from_other_module under --forever
  Lib/test/test_inspect.py
Labels: awaiting merge, skip news

#107592 [3.12] gh-107576: Ensure `__orig_bases__` are our own in `get_original_bases` (GH-107584)
  Lib/test/test_types.py
  Lib/types.py
  Misc/NEWS.d/next/Library/2023-08-03-11-31-11.gh-issue-107576.pO_s9I.rst
Labels: awaiting merge

#107567 gh-107080: Fix Py_TRACE_REFS Crashes Under Isolated Subinterpreters
  Include/internal/pycore_object.h
  Include/internal/pycore_object_state.h
  Include/internal/pycore_runtime_init.h
  Misc/NEWS.d/next/Core and Builtins/2023-08-02-12-24-51.gh-issue-107080.PNolFU.rst
  Objects/object.c
  Python/pylifecycle.c
Labels: awaiting merge, needs backport to 3.12

#107602 [3.10] Revert "[3.10] gh-107077: Raise SSLCertVerificationError even if the error is set via SSL_ERROR_SYSCALL (GH-107586) (#107589)"
  Misc/NEWS.d/next/Library/2023-08-03-12-52-19.gh-issue-107077.-pzHD6.rst
  Modules/_ssl.c
Labels: awaiting core review

#107606 gh-106368: Argument clinic tests: improve error message when `expect_success()` fails
  Lib/test/test_clinic.py
Labels: tests, awaiting merge, skip news

#107599 [3.12] gh-107080: Fix Py_TRACE_REFS Crashes Under Isolated Subinterpreters (gh-107567)
  Include/internal/pycore_object.h
  Include/internal/pycore_object_state.h
  Include/internal/pycore_runtime_init.h
  Misc/NEWS.d/next/Core and Builtins/2023-08-02-12-24-51.gh-issue-107080.PNolFU.rst
  Objects/object.c
  Python/pylifecycle.c
Labels: awaiting review

#107608 gh-104146: Argument clinic: remove unused methods and variables
  Tools/clinic/clinic.py
  Tools/clinic/cpp.py
Labels: awaiting merge, skip news

#107598 GH-105481: Mark more files as generated
  .gitattributes
Labels: awaiting merge, skip news

#107610 gh-107609: Fix duplicate module check in Argument Clinic
  Lib/test/test_clinic.py
  Misc/NEWS.d/next/Tools-Demos/2023-08-04-00-04-40.gh-issue-107609.2DqgtL.rst
  Modules/_testcapi/vectorcall.c
  Tools/clinic/clinic.py
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#107611 gh-106368: Increase Argument Clinic test coverage
  Lib/test/test_clinic.py
Labels: tests, awaiting merge, skip news

#107535 GH-107263: Increase C stack limit for most functions, except `_PyEval_EvalFrameDefault()`
  Doc/whatsnew/3.12.rst
  Include/cpython/pystate.h
  Lib/test/list_tests.py
  Lib/test/mapping_tests.py
  Lib/test/support/__init__.py
  Lib/test/test_ast.py
  Lib/test/test_call.py
  Lib/test/test_compile.py
  Lib/test/test_dict.py
  Lib/test/test_dictviews.py
  Lib/test/test_exception_group.py
  Lib/test/test_zlib.py
  Misc/NEWS.d/next/Core and Builtins/2023-07-30-05-20-16.gh-issue-107263.q0IU2M.rst
  Parser/asdl_c.py
  Python/Python-ast.c
  Python/ast.c
  Python/ast_opt.c
  Python/bytecodes.c
  Python/ceval.c
  Python/generated_cases.c.h
  Python/symtable.c
Labels: awaiting merge

#107581 Add some GC stats to Py_STATS
  Include/internal/pycore_code.h
  Include/pystats.h
  Modules/gcmodule.c
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: skip issue, awaiting merge, skip news

#107618 [3.12] GH-107263: Increase C stack limit for most functions, except `_PyEval_EvalFrameDefault()` (GH-107535)
  Doc/whatsnew/3.12.rst
  Include/cpython/pystate.h
  Lib/test/list_tests.py
  Lib/test/mapping_tests.py
  Lib/test/support/__init__.py
  Lib/test/test_ast.py
  Lib/test/test_call.py
  Lib/test/test_compile.py
  Lib/test/test_dict.py
  Lib/test/test_dictviews.py
  Lib/test/test_exception_group.py
  Lib/test/test_zlib.py
  Misc/NEWS.d/next/Core and Builtins/2023-07-30-05-20-16.gh-issue-107263.q0IU2M.rst
  Parser/asdl_c.py
  Python/Python-ast.c
  Python/ast.c
  Python/ast_opt.c
  Python/bytecodes.c
  Python/ceval.c
  Python/generated_cases.c.h
  Python/symtable.c
Labels: awaiting review

#107615 gh-107614: Normalise Argument Clinic error messages
  Lib/test/test_clinic.py
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107626 [3.12] Update the expected bytecode magic in test_importlib.test_util
  Lib/test/test_importlib/test_util.py
Labels: tests, skip issue, awaiting core review, skip news

#107617 Docs: upgrade to python-docs-theme 2023.7
  Doc/requirements.txt
Labels: skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107601 gh-107600: docs: Update ctypes.ArgumentError error message
  Doc/library/ctypes.rst
Labels: docs, awaiting review, skip news

#107632 gh-104146: Argument clinic: remove dead code highlighted by the `vulture` tool
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107638 gh-104683: Argument Clinic: Use CConverter.length_name where possible
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107637 Docs: Only include Plausible for html, not for epub etc
  Doc/tools/templates/layout.html
Labels: skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107643 [3.11] Docs: Only include Plausible for html, not for epub etc (GH-107637)
  Doc/tools/templates/layout.html
Labels: skip issue, awaiting merge, skip news

#107641 gh-106368: Argument clinic: improve coverage for `self.valid_line()` calls
  Lib/test/test_clinic.py
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107633 [3.12] Docs: upgrade to python-docs-theme 2023.7 (GH-107617)
  Doc/requirements.txt
Labels: skip issue, awaiting core review, skip news

#107642 [3.12] Docs: Only include Plausible for html, not for epub etc (GH-107637)
  Doc/tools/templates/layout.html
Labels: skip issue, awaiting merge, skip news

#107634 [3.11] Docs: upgrade to python-docs-theme 2023.7 (GH-107617)
  Doc/requirements.txt
Labels: skip issue, awaiting core review, skip news

#105413 GH-70303: Emit FutureWarning when pathlib glob pattern ends with `**`
  Doc/library/pathlib.rst
  Lib/pathlib.py
  Lib/test/test_pathlib.py
  Misc/NEWS.d/next/Library/2023-06-07-00-13-00.gh-issue-70303.frwUKH.rst
Labels: awaiting merge, topic-pathlib

#107605 GH-84436: Skip refcounting for known immortals
  Include/internal/pycore_long.h
  Misc/NEWS.d/next/Core and Builtins/2023-08-03-13-38-14.gh-issue-84436.gl1wHx.rst
  Modules/_asynciomodule.c
  Modules/_io/textio.c
  Modules/_json.c
  Modules/_pickle.c
  Objects/boolobject.c
  Objects/bytesobject.c
  Objects/funcobject.c
  Objects/longobject.c
  Objects/rangeobject.c
  Objects/sliceobject.c
  Objects/tupleobject.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Python/ceval.c
  Python/context.c
  Python/fileutils.c
  Python/hamt.c
Labels: performance, awaiting merge, interpreter-core

#107531 gh-106608: make uop trace variable length
  Include/cpython/optimizer.h
  Include/internal/pycore_uops.h
  Misc/NEWS.d/next/Core and Builtins/2023-08-01-09-41-36.gh-issue-106608.OFZogw.rst
  Python/optimizer.c
Labels: awaiting merge

#107649 gh-106812: Fix two tiny bugs in analysis.py
  Tools/cases_generator/analysis.py
Labels: skip news

#107445 gh-107432 Fix incorrect indentation in annotations HOWTO
  Doc/howto/annotations.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107655 [3.11] gh-107432 Fix incorrect indentation in annotations HOWTO (GH-107445)
  Doc/howto/annotations.rst
Labels: docs, awaiting merge, skip news

#107648 [3.12] gh-107630: Revert "[3.12] gh-107080: Fix Py_TRACE_REFS Crashes Under Isolated Subinterpreters (gh-107567) (#107599)"
  Include/internal/pycore_object.h
  Include/internal/pycore_object_state.h
  Include/internal/pycore_runtime_init.h
  Misc/NEWS.d/next/Core and Builtins/2023-08-02-12-24-51.gh-issue-107080.PNolFU.rst
  Objects/object.c
  Python/pylifecycle.c
Labels: awaiting core review, skip news

#107654 [3.12] gh-107432 Fix incorrect indentation in annotations HOWTO (GH-107445)
  Doc/howto/annotations.rst
Labels: docs, awaiting merge, skip news

#107650 GH-106684: raise ResourceWarning when StreamWriter is not closed
  Lib/asyncio/streams.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2023-08-05-05-10-41.gh-issue-106684.P9zRXb.rst
Labels: type-bug, topic-asyncio, awaiting merge, needs backport to 3.11, needs backport to 3.12

#107663 gh-107662: Switch 'any' and 'anext' in functions.rst
  Doc/library/functions.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#107665 [3.11] gh-107662: Switch 'any' and 'anext' in functions.rst (GH-107663)
  Doc/library/functions.rst
Labels: docs, awaiting review, skip news

#107328 Docs: Argument Clinic: Improve 'How to write a custom converter'
  Doc/howto/clinic.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107670 [3.11] Docs: Argument Clinic: Improve 'How to write a custom converter' (GH-107328)
  Doc/howto/clinic.rst
Labels: docs, skip issue, awaiting merge, skip news

#107667 gh-104683: Improve consistency and test coverage of argument-clinic `__repr__` functions
  Lib/test/test_clinic.py
  Tools/clinic/clinic.py
  Tools/clinic/cpp.py
Labels: awaiting merge, skip news

#19470 GH-84435: Make pyspecific directives translatable
  Doc/tools/extensions/pyspecific.py
Labels: awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107672 Docs: Fix Sphinx annotations in Doc/library/ctypes.rst
  Doc/conf.py
  Doc/library/ctypes.rst
Labels: skip issue, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#107666 Docs: skip python-docs-theme 2023.7 to fix mobile menu
  Doc/requirements.txt
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#107691 [3.11] Docs: skip python-docs-theme 2023.7 to fix mobile menu (GH-107666)
  Doc/requirements.txt
Labels: skip issue, awaiting merge, skip news

#107148 gh-85160: improve performance of singledispatchmethod
  Lib/functools.py
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Library/2020-11-10-07-04-15.bpo-40988.5kBC-O.rst
Labels: awaiting merge

#107664 [3.12] gh-107662: Switch 'any' and 'anext' in functions.rst (GH-107663)
  Doc/library/functions.rst
Labels: docs, awaiting review, skip news

#107690 [3.12] Docs: skip python-docs-theme 2023.7 to fix mobile menu (GH-107666)
  Doc/requirements.txt
Labels: skip issue, awaiting merge, skip news

#107694 Do not use deprecated ``logger.warn()`` in pyspecific
  Doc/tools/extensions/pyspecific.py
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107696 [3.11] Do not use deprecated ``logger.warn()`` in pyspecific (GH-107694)
  Doc/tools/extensions/pyspecific.py
Labels: skip issue, awaiting core review, skip news

#107695 [3.12] Do not use deprecated ``logger.warn()`` in pyspecific (GH-107694)
  Doc/tools/extensions/pyspecific.py
Labels: skip issue, awaiting merge, skip news

#107681 [3.12] GH-84435: Make pyspecific directives translatable (GH-19470)
  Doc/tools/extensions/pyspecific.py
Labels: awaiting core review, skip news

#107693 gh-106368: Improve coverage reports for argument clinic
  .coveragerc
  Tools/clinic/clinic.py
  Tools/clinic/cpp.py
Labels: awaiting merge, skip news

#107685 [3.12] Docs: Fix Sphinx annotations in Doc/library/ctypes.rst (GH-107672)
  Doc/conf.py
  Doc/library/ctypes.rst
Labels: skip issue, awaiting merge, skip news

#107669 [3.12] Docs: Argument Clinic: Improve 'How to write a custom converter' (GH-107328)
  Doc/howto/clinic.rst
Labels: docs, skip issue, awaiting merge, skip news

#107673 Improve cross-references in `runpy` docs
  Doc/library/runpy.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107699 [3.11] Improve cross-references in `runpy` docs (GH-107673)
  Doc/library/runpy.rst
Labels: docs, skip issue, awaiting review, skip news

#107698 [3.12] Improve cross-references in `runpy` docs (GH-107673)
  Doc/library/runpy.rst
Labels: docs, skip issue, awaiting merge, skip news

#107671 Docs: Argument Clinic: Move the CConverter class to the reference
  Doc/howto/clinic.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107702 [3.11] Docs: Argument Clinic: Move the CConverter class to the reference (GH-107671)
  Doc/howto/clinic.rst
Labels: docs, skip issue, awaiting merge, skip news

#107701 [3.12] Docs: Argument Clinic: Move the CConverter class to the reference (GH-107671)
  Doc/howto/clinic.rst
Labels: docs, skip issue, awaiting merge, skip news

#107443 gh-107442: Document all valid types for ctypes `_as_parameter_`
  Doc/library/ctypes.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107688 gh-104496: Use correct Tcl or Tk version in Tkinter tests
  Lib/test/test_tcl.py
  Lib/test/test_tkinter/support.py
  Lib/test/test_tkinter/test_images.py
  Lib/test/test_tkinter/test_widgets.py
  Lib/test/test_tkinter/widget_tests.py
  Lib/test/test_ttk/test_style.py
  Lib/test/test_ttk/test_widgets.py
Labels: tests, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#95151 gh-95065: Add Argument Clinic support for deprecating positional use of parameters
  Doc/howto/clinic.rst
  Lib/test/clinic.test.c
  Lib/test/test_clinic.py
  Misc/NEWS.d/next/Tools-Demos/2022-07-23-00-33-28.gh-issue-95065.NfCCpp.rst
  Tools/clinic/clinic.py
Labels: awaiting merge, topic-argument-clinic

#107708 Docs: Fix more Sphinx annotations in ctypes.rst
  Doc/conf.py
  Doc/library/ctypes.rst
  Doc/tools/.nitignore
Labels: skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#107711 gh-107710: Speed up `logging.getHandlerNames` function
  Lib/logging/__init__.py
  Misc/NEWS.d/next/Library/2023-08-07-14-24-42.gh-issue-107710.xfOCfj.rst
Labels: awaiting merge

#107692 gh-100814: Fix exception for invalid callable value of Tkinter image option
  Lib/test/test_tkinter/test_images.py
  Lib/tkinter/__init__.py
  Misc/NEWS.d/next/Library/2023-08-06-15-29-00.gh-issue-100814.h195gW.rst
Labels: awaiting core review, needs backport to 3.11, needs backport to 3.12

#107719 [3.11] gh-104496: Use correct Tcl or Tk version in Tkinter tests (GH-107688)
  Lib/test/test_tcl.py
  Lib/tkinter/test/support.py
  Lib/tkinter/test/test_tkinter/test_images.py
  Lib/tkinter/test/test_tkinter/test_widgets.py
  Lib/tkinter/test/test_ttk/test_style.py
  Lib/tkinter/test/test_ttk/test_widgets.py
  Lib/tkinter/test/widget_tests.py
Labels: awaiting core review, skip news

#106567 gh-106566: Optimize (?!) in regular expressions
  Lib/re/_parser.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2023-07-09-13-10-54.gh-issue-106566.NN35-U.rst
Labels: awaiting core review

#107716 gh-107715: Escape class name in regular expression
  Lib/doctest.py
  Misc/NEWS.d/next/Library/2023-08-07-14-12-07.gh-issue-107715.238r2f.rst
Labels: awaiting merge

#107179 gh-107178: Add the C API tests for the Abstract Objects Layer
  Lib/test/test_bytes.py
  Lib/test/test_capi/test_abstract.py
  Lib/test/test_capi/test_dict.py
  Lib/test/test_capi/test_misc.py
  Lib/test/test_class.py
  Misc/NEWS.d/next/Tests/2023-07-24-16-56-59.gh-issue-107178.Gq1usE.rst
  Modules/Setup.stdlib.in
  Modules/_testcapi/abstract.c
  Modules/_testcapi/dict.c
  Modules/_testcapi/parts.h
  Modules/_testcapimodule.c
  PCbuild/_testcapi.vcxproj
  PCbuild/_testcapi.vcxproj.filters
Labels: tests, awaiting core review, topic-C-API

#107733 gh-107630: Initialize Each Interpreter's refchain Properly
  Include/internal/pycore_object.h
  Objects/object.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: awaiting core review, skip news

#107736 gh-107735: Add C API tests for PySys_GetObject() and PySys_SetObject()
  Lib/test/test_capi/test_misc.py
  Modules/_testcapimodule.c
Labels: tests, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#23199 gh-86457: Fix signature for code.replace().
  Misc/NEWS.d/next/Tools-Demos/2023-08-07-16-30-48.gh-issue-95065.-im4R5.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Tools/clinic/clinic.py
Labels: awaiting core review, needs backport to 3.11, needs backport to 3.12

#107741 [3.11] gh-107735: Add C API tests for PySys_GetObject() and PySys_SetObject() (GH-107736)
  Lib/test/test_capi/test_misc.py
  Modules/_testcapimodule.c
Labels: awaiting core review, skip news

#107743 gh-107735: Move just added C API tests to better place
  Lib/test/test_capi/test_misc.py
Labels: tests, awaiting core review, skip news

#107552 gh-98154: Clarify Usage of "Reference Count" In the Docs
  Doc/c-api/allocation.rst
  Doc/c-api/arg.rst
  Doc/c-api/buffer.rst
  Doc/c-api/bytes.rst
  Doc/c-api/exceptions.rst
  Doc/c-api/init_config.rst
  Doc/c-api/intro.rst
  Doc/c-api/module.rst
  Doc/c-api/object.rst
  Doc/c-api/refcounting.rst
  Doc/c-api/sys.rst
  Doc/c-api/typeobj.rst
  Doc/c-api/unicode.rst
  Doc/glossary.rst
  Doc/library/sys.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12

#107753 [3.11] gh-98154: Clarify Usage of "Reference Count" In the Docs
  Doc/c-api/allocation.rst
  Doc/c-api/arg.rst
  Doc/c-api/buffer.rst
  Doc/c-api/bytes.rst
  Doc/c-api/exceptions.rst
  Doc/c-api/intro.rst
  Doc/c-api/module.rst
  Doc/c-api/object.rst
  Doc/c-api/refcounting.rst
  Doc/c-api/sys.rst
  Doc/c-api/typeobj.rst
  Doc/c-api/unicode.rst
  Doc/glossary.rst
  Doc/library/sys.rst
Labels: docs, awaiting core review, skip news

#107750 gh-107630: Fix Remaining Subinterpreters Crashes on Py_TRACE_REFS Builds
  Lib/test/test_import/__init__.py
Labels: awaiting core review, skip news

#107759 gh-106812: Small stack effect fixes
  Tools/cases_generator/interpreter_definition.md
  Tools/cases_generator/parsing.py
  Tools/cases_generator/stacking.py
Labels: awaiting merge, skip news

#107757 gh-107758: Improvements to lltrace feature
  Misc/NEWS.d/next/Core and Builtins/2023-08-08-02-46-46.gh-issue-107758.R5kyBI.rst
  Python/ceval.c
  Python/executor.c
  Python/optimizer.c
Labels: awaiting core review

#107745 gh-95065: Make Argument Clinic append deprecation warnings to docstrings
  Lib/test/clinic.test.c
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107747 gh-86457: Add docs for Argument Clinic @text_signature directive
  Doc/howto/clinic.rst
  Misc/NEWS.d/next/Tools-Demos/2023-08-07-16-30-48.gh-issue-95065.-im4R5.rst
Labels: docs, awaiting merge, needs backport to 3.11, needs backport to 3.12

#107763 [3.11] README: remove unmaintained sections (GH-107703)
  README.rst
Labels: docs, skip issue, awaiting review, skip news

#107660 gh-107659: ctypes: Add docstrings for `ctypes.pointer` and `ctypes.POINTER`
  Misc/NEWS.d/next/Core and Builtins/2023-08-05-15-45-07.gh-issue-107659.QgtQ5M.rst
  Modules/_ctypes/callproc.c
  Modules/_ctypes/clinic/callproc.c.h
Labels: docs, awaiting merge

#107766 gh-95065: Argument Clinic: Add comment to preprocessor warning code
  Lib/test/clinic.test.c
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107682 [3.11] GH-84435: Make pyspecific directives translatable (GH-19470)
  Doc/tools/extensions/pyspecific.py
Labels: awaiting merge, skip news

#107731 gh-106368: Argument clinic: add tests for more failure paths
  Lib/test/test_clinic.py
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#91849 gh-91795: Update build optimization part of PCbuild/readme.txt
  PCbuild/readme.txt
Labels: OS-windows, awaiting review, skip news, needs backport to 3.11, needs backport to 3.12

#107752 [3.12] gh-98154: Clarify Usage of "Reference Count" In the Docs (gh-107552)
  Doc/c-api/allocation.rst
  Doc/c-api/arg.rst
  Doc/c-api/buffer.rst
  Doc/c-api/bytes.rst
  Doc/c-api/exceptions.rst
  Doc/c-api/init_config.rst
  Doc/c-api/intro.rst
  Doc/c-api/module.rst
  Doc/c-api/object.rst
  Doc/c-api/refcounting.rst
  Doc/c-api/sys.rst
  Doc/c-api/typeobj.rst
  Doc/c-api/unicode.rst
  Doc/glossary.rst
  Doc/library/sys.rst
Labels: docs, awaiting review, skip news

#107572 gh-105699: Re-enable the Multiple-Interpreters Stress Tests
  Lib/test/test_interpreters.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12

#107781 Minor accuracy improvement for statistics.correlation()
  Lib/statistics.py
Labels: skip issue, awaiting core review, skip news, 3.13

#107785 GH-100425: Note improved commutativity in sum().
  Doc/library/functions.rst
  Doc/whatsnew/3.12.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.12

#107597 GH-107596: Specialize `str[int]`
  Include/internal/pycore_opcode.h
  Include/internal/pycore_opcode_metadata.h
  Include/opcode.h
  Lib/_opcode_metadata.py
  Misc/NEWS.d/next/Core and Builtins/2023-08-03-11-13-09.gh-issue-107596.T3yPGI.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Python/specialize.c
Labels: performance, awaiting core review, interpreter-core

#107770 gh-104683: Add --exclude option to Argument Clinic CLI
  Doc/howto/clinic.rst
  Lib/test/test_clinic.py
  Makefile.pre.in
  Misc/NEWS.d/next/Tools-Demos/2023-08-08-12-21-41.gh-issue-104683.DRsAQE.rst
  Tools/clinic/clinic.py
Labels: awaiting merge

#107623 gh-104683: Argument Clinic: refactor format_docstring()
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#106515 gh-106052: Fix bug in the matching of possessive quantifiers
  Lib/re/_compiler.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2023-07-07-14-52-31.gh-issue-106052.ak8nbs.rst
Labels: awaiting core review, needs backport to 3.11, needs backport to 3.12

#107764 gh-80282: Argument Clinic: Add clarifying comment about ASCII docstring limitation
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107746 [3.11] gh-86457: Fix signature for code.replace() (GH-23199)
  Misc/NEWS.d/next/Tools-Demos/2023-08-07-16-30-48.gh-issue-95065.-im4R5.rst
  Objects/clinic/codeobject.c.h
  Objects/codeobject.c
  Tools/clinic/clinic.py
Labels: awaiting merge

#107795 [3.11] gh-106052: Fix bug in the matching of possessive quantifiers (gh-106515)
  Lib/re/_compiler.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2023-07-07-14-52-31.gh-issue-106052.ak8nbs.rst
Labels: awaiting core review

#107799 [3.11] gh-86457: Add docs for Argument Clinic @text_signature directive (#107747)
  Doc/howto/clinic.rst
  Misc/NEWS.d/next/Tools-Demos/2023-08-07-16-30-48.gh-issue-95065.-im4R5.rst
Labels: docs, awaiting core review

#107797 Docs: clean up Argument Clinic howto's
  Doc/howto/clinic.rst
  Misc/NEWS.d/next/Tools-Demos/2023-08-07-16-30-48.gh-issue-95065.-im4R5.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#107798 Future-proof helper function with zero handling.
  Lib/statistics.py
Labels: skip issue, awaiting core review, skip news

#107800 [3.11] Docs: clean up Argument Clinic howto's (#107797)
  Doc/howto/clinic.rst
Labels: docs, skip issue, awaiting core review, skip news

#107725 GH-107724: Fix the signature of `PY_THROW` callback functions.
  Include/internal/pycore_instruments.h
  Lib/test/test_monitoring.py
  Misc/NEWS.d/next/Core and Builtins/2023-08-04-21-25-26.gh-issue-107724.EbBXMr.rst
  Python/ceval.c
  Python/instrumentation.c
  Python/legacy_tracing.c
Labels: awaiting merge, needs backport to 3.12

#107771 gh-104683: Remove unused variables from `Tools/clinic` and tests for `Tools/clinic`
  Lib/test/test_clinic.py
  Tools/clinic/cpp.py
Labels: awaiting merge, skip news

#107796 [3.12] gh-106052: Fix bug in the matching of possessive quantifiers (GH-106515)
  Lib/re/_compiler.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2023-07-07-14-52-31.gh-issue-106052.ak8nbs.rst
Labels: awaiting core review

#107808 gh-95065: Produce nicer deprecation messages in Argument Clinic
  Lib/test/clinic.test.c
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#107788 GH-105848: Simplify the arrangement of `CALL`'s stack
  Doc/library/dis.rst
  Include/internal/pycore_opcode_metadata.h
  Lib/dis.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_compiler_assemble.py
  Lib/test/test_compiler_codegen.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2023-08-05-09-06-56.gh-issue-105848.Drc-1-.rst
  Objects/exception_handling_notes.txt
  Programs/test_frozenmain.h
  Python/bytecodes.c
  Python/compile.c
  Python/executor_cases.c.h
  Python/flowgraph.c
  Python/generated_cases.c.h
  Python/specialize.c
Labels: performance, awaiting merge, interpreter-core

#106539 GH-106485: Dematerialize instance dictionaries when possible
  Include/internal/pycore_dict.h
  Include/pystats.h
  Lib/test/test_opcache.py
  Misc/NEWS.d/next/Core and Builtins/2023-07-16-07-55-19.gh-issue-106485.wPb1bH.rst
  Objects/dictobject.c
  Objects/typeobject.c
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/specialize.c
Labels: performance, awaiting core review, interpreter-core

#107815 gh-107814: properly silence nuget installation in `find_python.bat`
  Misc/NEWS.d/next/Build/2023-08-09-17-05-33.gh-issue-107814.c0Oapq.rst
  PCbuild/find_python.bat
Labels: awaiting review, needs backport to 3.11, needs backport to 3.12

#107821 gh-91054: make code watcher tests resilient to other watchers
  Modules/_testcapi/watchers.c
  Tools/c-analyzer/cpython/ignored.tsv
Labels: awaiting core review, skip news

#107824 [3.11] gh-107814: Avoid output from Nuget installation in find_python.bat (GH-107815)
  Misc/NEWS.d/next/Build/2023-08-09-17-05-33.gh-issue-107814.c0Oapq.rst
  PCbuild/find_python.bat
Labels: awaiting merge

#107813 GH-107812: extend `socket`'s netlink support to FreeBSD
  Misc/NEWS.d/next/Library/2023-08-09-15-37-20.gh-issue-107812.CflAXa.rst
  Modules/socketmodule.h
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge

#107826 Update README for the cases generator
  Tools/cases_generator/README.md
Labels: skip issue, skip news

#107697 gh-107689: Add docstring to the ctypes array object
  Modules/_ctypes/_ctypes.c
Labels: awaiting merge, skip news

#107410 gh-107409: set `__wrapped__` attribute in `reprlib.recursive_repr`
  Lib/reprlib.py
  Lib/test/test_reprlib.py
  Misc/NEWS.d/next/Library/2023-07-29-02-36-50.gh-issue-107409.HG27Nu.rst
Labels: awaiting merge

#107768 gh-95065: Argument Clinic: Add functional tests of deprecated positionals
  Lib/test/clinic.test.c
  Lib/test/test_clinic.py
  Modules/_testclinic.c
  Modules/clinic/_testclinic_depr_star.c.h
  Tools/c-analyzer/cpython/globals-to-fix.tsv
Labels: awaiting merge, skip news

#107823 [3.12] gh-107814: Avoid output from Nuget installation in find_python.bat (GH-107815)
  Misc/NEWS.d/next/Build/2023-08-09-17-05-33.gh-issue-107814.c0Oapq.rst
  PCbuild/find_python.bat
Labels: awaiting merge

#107836 [3.11] [3.12] GH-106684: Close `asyncio.StreamWriter` when `asyncio.StreamWriter` is not closed by application (GH-107650) (GH-107656)
  Lib/asyncio/streams.py
  Misc/NEWS.d/next/Library/2023-08-05-05-10-41.gh-issue-106684.P9zRXb.rst
Labels: type-bug, awaiting merge

#107775 GH-107774: Add missing audit event for PEP 669
  Lib/test/audit-tests.py
  Lib/test/test_audit.py
  Misc/NEWS.d/next/Security/2023-08-05-03-51-05.gh-issue-107774.VPjaTR.rst
  Python/instrumentation.c
Labels: awaiting merge, needs backport to 3.12

#107837 GH-106485: Handle dict subclasses correctly when dematerializing `__dict__`
  Include/internal/pycore_dict.h
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Lib/test/test_opcache.py
  Modules/_testinternalcapi.c
  Objects/dictobject.c
Labels: awaiting merge, skip news, interpreter-core

#107780 GH-107674: Avoid allocating boxed ints for `sys.settrace` line events
  Misc/NEWS.d/next/Core and Builtins/2023-08-05-04-47-18.gh-issue-107674.0sYhR2.rst
  Python/instrumentation.c
Labels: awaiting merge, needs backport to 3.12
