Repository python/cpython, pull requests merged in 2023-11, with the labels that each got.

#111584 gh-110968: Py_MOD_PER_INTERPRETER_GIL_SUPPORTED was added to 3.12
  Include/moduleobject.h
  Modules/_ctypes/_ctypes_test.c
  Modules/_multiprocessing/posixshmem.c
  Modules/_scproxy.c
  Modules/_stat.c
  Modules/_testclinic_limited.c
  Modules/_uuidmodule.c
  Modules/errnomodule.c
  Modules/md5module.c
  Modules/resource.c
  Modules/xxlimited.c
  PC/winsound.c
Labels: awaiting core review, skip news

#111577 gh-110367: Make regrtest --verbose3 compatible with --huntrleaks -jN
  Lib/test/libregrtest/cmdline.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2023-10-31-22-09-25.gh-issue-110367.UhQi44.rst
Labels: tests, awaiting core review, needs backport to 3.11, needs backport to 3.12

#111589 [3.12] gh-110367: Make regrtest --verbose3 compatible with --huntrleaks -jN (GH-111577)
  Lib/test/libregrtest/cmdline.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2023-10-31-22-09-25.gh-issue-110367.UhQi44.rst
Labels: awaiting review

#111590 [3.11] gh-110367: Make regrtest --verbose3 compatible with --huntrleaks -jN (GH-111577)
  Lib/test/libregrtest/cmdline.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2023-10-31-22-09-25.gh-issue-110367.UhQi44.rst
Labels: awaiting review

#111586 gh-111495: add stub files for C API test modules
  Modules/Setup.stdlib.in
  Modules/_testcapi/bytearray.c
  Modules/_testcapi/bytes.c
  Modules/_testcapi/codec.c
  Modules/_testcapi/complex.c
  Modules/_testcapi/file.c
  Modules/_testcapi/list.c
  Modules/_testcapi/numbers.c
  Modules/_testcapi/parts.h
  Modules/_testcapi/tuple.c
  Modules/_testcapimodule.c
  PCbuild/_testcapi.vcxproj
  PCbuild/_testcapi.vcxproj.filters
Labels: tests, awaiting merge, skip news, needs backport to 3.12

#111592 [3.12] gh-111495: add stub files for C API test modules (GH-111586)
  Modules/Setup.stdlib.in
  Modules/_testcapi/bytearray.c
  Modules/_testcapi/bytes.c
  Modules/_testcapi/codec.c
  Modules/_testcapi/complex.c
  Modules/_testcapi/file.c
  Modules/_testcapi/list.c
  Modules/_testcapi/numbers.c
  Modules/_testcapi/parts.h
  Modules/_testcapi/tuple.c
  Modules/_testcapimodule.c
  PCbuild/_testcapi.vcxproj
  PCbuild/_testcapi.vcxproj.filters
Labels: awaiting merge, skip news

#111578 gh-111576: Improve documention for tkinter.messagebox
  Doc/library/tkinter.messagebox.rst
Labels: docs, awaiting merge, skip news, topic-tkinter, needs backport to 3.11, needs backport to 3.12

#111597 [3.12] gh-111576: Improve documention for tkinter.messagebox (GH-111578)
  Doc/library/tkinter.messagebox.rst
Labels: docs, awaiting review, skip news

#111598 [3.11] gh-111576: Improve documention for tkinter.messagebox (GH-111578)
  Doc/library/tkinter.messagebox.rst
Labels: docs, awaiting review, skip news

#111561 GH-111485: Use micro-ops to split specialization code from base action
  Include/internal/pycore_opcode_metadata.h
  Lib/test/test_capi/test_misc.py
  Python/abstract_interp_cases.c.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Tools/cases_generator/analysis.py
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/instructions.py
Labels: awaiting merge, skip news

#111600 GH-111537: Avoid using `this_instr` in asserts.
  Python/bytecodes.c
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#111602 Simplify _PyPegen_join_names_with_dot()
  Parser/action_helpers.c
Labels: skip issue, awaiting merge, skip news

#111496 gh-111495: Add tests for PyBytes and PyByteArray C API
  Lib/test/test_capi/test_bytearray.py
  Lib/test/test_capi/test_bytes.py
  Lib/test/test_capi/test_unicode.py
  Modules/_testcapi/bytearray.c
  Modules/_testcapi/bytes.c
Labels: tests, awaiting core review, skip news, topic-C-API, needs backport to 3.12

#111585 gh-111089: Use PyUnicode_AsUTF8() in Argument Clinic
  Modules/_io/clinic/_iomodule.c.h
  Modules/_io/clinic/fileio.c.h
  Modules/_io/clinic/textio.c.h
  Modules/_io/clinic/winconsoleio.c.h
  Modules/_multiprocessing/clinic/multiprocessing.c.h
  Modules/_multiprocessing/clinic/semaphore.c.h
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/clinic/cursor.c.h
  Modules/_sqlite/clinic/module.c.h
  Modules/_testcapi/clinic/exceptions.c.h
  Modules/cjkcodecs/clinic/multibytecodec.c.h
  Modules/clinic/_codecsmodule.c.h
  Modules/clinic/_cursesmodule.c.h
  Modules/clinic/_dbmmodule.c.h
  Modules/clinic/_elementtree.c.h
  Modules/clinic/_gdbmmodule.c.h
  Modules/clinic/_hashopenssl.c.h
  Modules/clinic/_localemodule.c.h
  Modules/clinic/_pickle.c.h
  Modules/clinic/_ssl.c.h
  Modules/clinic/_testclinic.c.h
  Modules/clinic/_tkinter.c.h
  Modules/clinic/posixmodule.c.h
  Modules/clinic/pyexpat.c.h
  Modules/clinic/symtablemodule.c.h
  Objects/clinic/bytearrayobject.c.h
  Objects/clinic/bytesobject.c.h
  Objects/clinic/floatobject.c.h
  Objects/clinic/memoryobject.c.h
  Objects/clinic/unicodeobject.c.h
  Python/clinic/Python-tokenize.c.h
  Python/clinic/bltinmodule.c.h
  Python/clinic/sysmodule.c.h
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#111588 [3.12] gh-110968: Py_MOD_PER_INTERPRETER_GIL_SUPPORTED was added to 3.12
  Include/moduleobject.h
  Modules/xxlimited.c
  Modules/xxlimited_35.c
Labels: awaiting merge, skip news

#111605 Simplify trivial calls of PyUnicode_FromFormat()
  Modules/_xxsubinterpretersmodule.c
  Modules/_zoneinfo.c
Labels: skip issue, awaiting merge, skip news

#111607 [3.12] gh-111495: Add tests for PyBytes and PyByteArray C API (GH-111496)
  Lib/test/test_capi/test_bytearray.py
  Lib/test/test_capi/test_bytes.py
  Lib/test/test_capi/test_unicode.py
  Modules/_testcapi/bytearray.c
  Modules/_testcapi/bytes.c
Labels: awaiting review, skip news

#111300 [3.12] gh-111295: Fix error checking in time extension module init (GH-111296)
  Misc/NEWS.d/next/Library/2023-10-25-08-42-05.gh-issue-111295.H2K4lf.rst
  Modules/timemodule.c
Labels: awaiting review

#111299 [3.12] gh-111253: Fix error checking in _socket module init (GH-111254)
  Misc/NEWS.d/next/Library/2023-10-24-12-20-46.gh-issue-111253.HFywSK.rst
  Modules/socketmodule.c
Labels: awaiting review

#111428 gh-111520: Integrate the Tier 2 interpreter in the Tier 1 interpreter
  Lib/test/support/__init__.py
  Lib/test/test_generated_cases.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2023-10-31-21-33-35.gh-issue-111520.vw-rxJ.rst
  PCbuild/_freeze_module.vcxproj
  PCbuild/_freeze_module.vcxproj.filters
  PCbuild/python.vcxproj
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer.c
  Python/pylifecycle.c
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/instructions.py
Labels: awaiting core review

#111411 gh-111374: Add a new PYTHON_FROZEN_MODULES env var, equivalent of `-X frozen_modules`.
  Doc/using/cmdline.rst
  Doc/whatsnew/3.13.rst
  Lib/test/test_cmd_line.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-27-11-22-09.gh-issue-111374.e9lrPZ.rst
  Python/initconfig.c
Labels: awaiting merge

#111618 gh-106168: Update PyList_SET_ITEM() What's New doc
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting core review, skip news

#108730 gh-106718: Respect PyConfig.stdlib_dir in getpath.
  Lib/test/test_getpath.py
  Misc/NEWS.d/next/Core and Builtins/2023-08-31-11-42-16.gh-issue-106718._-57DA.rst
  Modules/getpath.py
Labels: awaiting review

#111619 GH-111485: Silence warnings in Python/executor_cases.c.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting core review, skip news

#111621 High level docs for the VM state
  Python/vm-state.md
Labels: skip issue, awaiting core review, skip news

#111620 gh-111089: Use PyUnicode_AsUTF8() in getargs.c
  Python/getargs.c
Labels: awaiting core review, skip news

#111530 gh-76785: Crossinterp utils additions
  Include/internal/pycore_crossinterp.h
  Include/internal/pycore_interp.h
  Include/internal/pycore_pyerrors.h
  Include/internal/pycore_runtime.h
  Include/internal/pycore_runtime_init.h
  Lib/test/support/interpreters.py
  Modules/_xxsubinterpretersmodule.c
  Python/crossinterp.c
  Python/errors.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: awaiting core review, skip news

#111436 GH-111435 sharing of bool type in sub interpreters
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_interpreters.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-29-11-35-21.gh-issue-111435.ageUWQ.rst
  Python/crossinterp.c
Labels: awaiting merge

#111593 gh-111544: Fix mimalloc build on AIX
  Objects/mimalloc/prim/unix/prim.c
Labels: awaiting review, skip news

#111601 GH-110894: Call loop exception handler for exceptions in client_connected_cb
  Lib/asyncio/streams.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2023-11-01-14-03-24.gh-issue-110894.7-wZxC.rst
Labels: topic-asyncio, awaiting merge, needs backport to 3.11, needs backport to 3.12

#111632 [3.12] GH-110894: Call loop exception handler for exceptions in client_connected_cb (GH-111601)
  Lib/asyncio/streams.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2023-11-01-14-03-24.gh-issue-110894.7-wZxC.rst
Labels: topic-asyncio, awaiting core review, needs backport to 3.11

#111633 Remove unnecessary includes
  Python/Python-tokenize.c
  Python/traceback.c
Labels: skip issue, awaiting core review, skip news

#111580 gh-108082: Use PyErr_FormatUnraisable()
  Lib/test/test_capi/test_watchers.py
  Lib/test/test_cmd_line.py
  Modules/_ctypes/_ctypes.c
  Modules/_lsprof.c
  Modules/gcmodule.c
  Modules/getpath.c
  Modules/signalmodule.c
  Objects/codeobject.c
  Objects/dictobject.c
  Objects/funcobject.c
  Objects/moduleobject.c
  Objects/typeobject.c
  Python/ceval.c
  Python/compile.c
  Python/import.c
  Python/perf_trampoline.c
  Python/pylifecycle.c
  Python/pythonrun.c
Labels: awaiting merge, skip news

#111459 gh-111354: simplify detection of RESUME after YIELD_VALUE at except-depth 1
  Doc/library/dis.rst
  Doc/whatsnew/3.13.rst
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_opcode_utils.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-26-18-45-20.gh-issue-111354.GrT-Wf.rst
  Objects/codeobject.c
  Objects/genobject.c
  Programs/test_frozenmain.h
  Python/bytecodes.c
  Python/ceval.c
  Python/compile.c
  Python/flowgraph.c
  Python/generated_cases.c.h
  Python/opcode_targets.h
Labels: awaiting merge

#111626 gh-111625: Fix link to Info-ZIP homepage
  Doc/tools/templates/download.html
  Lib/test/ziptestdata/README.md
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#111640 [3.11] gh-111625: Fix link to Info-ZIP homepage (GH-111626)
  Doc/tools/templates/download.html
  Lib/test/ziptestdata/README.md
Labels: awaiting review, skip news

#111639 [3.12] gh-111625: Fix link to Info-ZIP homepage (GH-111626)
  Doc/tools/templates/download.html
  Lib/test/ziptestdata/README.md
Labels: awaiting review, skip news

#111641 gh-111482: Use Argument Clinic for clock_gettime()
  Misc/NEWS.d/next/Library/2023-11-02-12-15-46.gh-issue-111482.FWqZIU.rst
  Modules/clinic/timemodule.c.h
  Modules/timemodule.c
Labels: awaiting merge

#111642 GH-109369 Add vectorcall to `PyLong_Type`
  Objects/longobject.c
Labels: awaiting merge, skip news

#110909 gh-110892: Return NULL for `PyTrace_RETURN` events caused by an exception
  Lib/test/test_sys_setprofile.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-15-20-45-35.gh-issue-110892.oA6eVY.rst
  Python/legacy_tracing.c
Labels: awaiting review

#111664 gh-111663: Restore the Tier 2 uop count pystats
  Python/ceval.c
Labels: awaiting merge, skip news

#111665 Fix typo in documentation of `SysLogHandler.createSocket`
  Doc/library/logging.handlers.rst
Labels: docs, skip issue, awaiting review, skip news

#111669 [3.12] Fix typo in documentation of `SysLogHandler.createSocket` (GH-111665)
  Doc/library/logging.handlers.rst
Labels: docs, skip issue, awaiting review, skip news

#111670 [3.11] Fix typo in documentation of `SysLogHandler.createSocket` (GH-111665)
  Doc/library/logging.handlers.rst
Labels: docs, skip issue, awaiting review, skip news

#111671 gh-76785: Minor Fixes in crossinterp.c
  Python/crossinterp.c
Labels: awaiting core review, skip news

#111655 gh-111654: remove redundant decref on the eval stack value
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2023-11-03-01-04-55.gh-issue-111654.scUhDO.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: needs backport to 3.12

#111677 gh-54434: Make difflib.rst doctests pass.
  Doc/library/difflib.rst
Labels: docs, awaiting core review, skip news, stdlib, needs backport to 3.11, needs backport to 3.12

#111679 [3.11] gh-54434: Make difflib.rst doctests pass. (GH-111677)
  Doc/library/difflib.rst
Labels: docs, awaiting review, skip news

#111678 [3.12] gh-54434: Make difflib.rst doctests pass. (GH-111677)
  Doc/library/difflib.rst
Labels: docs, awaiting review, skip news

#111643 gh-108082: Remove _PyErr_WriteUnraisableMsg()
  Include/internal/pycore_pyerrors.h
  Lib/test/_test_atexit.py
  Lib/test/audit-tests.py
  Lib/test/test_ctypes/test_callbacks.py
  Lib/test/test_ctypes/test_random_things.py
  Lib/test/test_sys.py
  Lib/test/test_thread.py
  Modules/_ctypes/callbacks.c
  Modules/_testinternalcapi.c
  Modules/_threadmodule.c
  Modules/atexitmodule.c
  Modules/clinic/_testinternalcapi.c.h
  Python/errors.c
Labels: awaiting merge, skip news, topic-C-API

#111491 gh-111490: Change what exception type we expect in `test_pyexpat`
  Lib/test/test_pyexpat.py
Labels: tests, awaiting merge, skip news

#105075 gh-90026: support XATTRs on Cygwin
  Misc/NEWS.d/next/Library/2023-05-30-02-01-14.gh-issue-90026.FyCXw8.rst
  Modules/posixmodule.c
Labels: awaiting review

#111648 gh-111354: Simplify _PyGen_yf by moving some of its work to the compiler and frame state
  Doc/library/dis.rst
  Doc/whatsnew/3.13.rst
  Include/internal/pycore_frame.h
  Include/internal/pycore_opcode_metadata.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Core and Builtins/2023-11-02-14-49-19.gh-issue-111354.gIS3f-.rst
  Objects/frameobject.c
  Objects/genobject.c
  Programs/test_frozenmain.h
  Python/bytecodes.c
  Python/compile.c
  Python/generated_cases.c.h
  Python/opcode_targets.h
Labels: awaiting merge

#111683 gh-106168: Revert the "size before item" setting
  Doc/whatsnew/3.13.rst
  Include/internal/pycore_list.h
  Objects/listobject.c
Labels: awaiting merge, skip news

#111682 gh-111681: Fix doctests in `typing.rst` and remove unused imports
  Doc/library/typing.rst
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#110888 docs: specify that PyBytes_AsStringAndSize returns 0 on success
  Doc/c-api/bytes.rst
Labels: docs, skip issue, awaiting review, skip news, topic-C-API, needs backport to 3.11, needs backport to 3.12

#111674 [3.12] gh-111654: remove redundant decref in LOAD_FROM_DICT_OR_DEREF (GH-111655)
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core and Builtins/2023-11-03-01-04-55.gh-issue-111654.scUhDO.rst
  Python/bytecodes.c
  Python/generated_cases.c.h
Labels: awaiting core review

#110362 CI: Make macOS Intel required to succeed
  .github/workflows/build.yml
Labels: skip issue, skip news, needs backport to 3.11, needs backport to 3.12

#111653 gh-111652: Fix --enable-pystats build
  Include/internal/pycore_code.h
Labels: awaiting review, skip news

#109472 gh-103615: Use local events for opcode tracing
  Include/internal/pycore_ceval.h
  Include/internal/pycore_instruments.h
  Include/internal/pycore_interp.h
  Lib/test/test_sys_settrace.py
  Misc/NEWS.d/next/Core and Builtins/2023-09-15-23-39-43.gh-issue-103615.WZavly.rst
  Objects/frameobject.c
  Python/instrumentation.c
  Python/legacy_tracing.c
  Python/pystate.c
Labels: awaiting review

#111508 gh-111506: Implement Py_SET_REFCNT() as opaque function in limited C API
  Include/object.h
  Lib/test/test_stable_abi_ctypes.py
  Misc/NEWS.d/next/C API/2023-10-30-18-13-01.gh-issue-111506.EUdO22.rst
  Misc/stable_abi.toml
  Objects/object.c
  PC/python3dll.c
Labels: awaiting core review

#111706 gh-111684: Avoid a Compiler Warning
  Python/crossinterp.c
Labels: awaiting core review, skip news

#111477 Add a fuzz target for `_elementtree.XMLParser._parse_whole`
  Modules/_xxtestfuzz/dictionaries/fuzz_elementtree_parsewhole.dict
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nComment.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nPrefix.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nPrefixQname.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nPrefixQnameXpathElem.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nQname.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nQnameElem.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nQnameXpathElem.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/c14nTrim.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/expat224_utf8_bug.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inC14N1.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inC14N2.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inC14N3.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inC14N4.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inC14N5.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inC14N6.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inNsContent.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inNsDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inNsPushdown.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inNsRedecl.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inNsSort.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inNsSuperfluous.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/inNsXml.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N1_c14nComment.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N1_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N2_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N2_c14nTrim.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N3_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N3_c14nPrefix.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N3_c14nTrim.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N4_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N4_c14nTrim.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N5_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N5_c14nTrim.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inC14N6_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsContent_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsContent_c14nPrefixQnameXpathElem.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsContent_c14nQnameElem.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsContent_c14nQnameXpathElem.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsDefault_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsDefault_c14nPrefix.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsPushdown_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsPushdown_c14nPrefix.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsRedecl_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsRedecl_c14nPrefix.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsSort_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsSort_c14nPrefix.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsSuperfluous_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsSuperfluous_c14nPrefix.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsXml_c14nDefault.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsXml_c14nPrefix.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsXml_c14nPrefixQname.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/out_inNsXml_c14nQname.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/simple-ns.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/simple.xml
  Modules/_xxtestfuzz/fuzz_elementtree_parsewhole_corpus/test.xml
  Modules/_xxtestfuzz/fuzz_tests.txt
  Modules/_xxtestfuzz/fuzzer.c
  Tools/c-analyzer/cpython/ignored.tsv
Labels: skip issue, awaiting merge, skip news

#111617 [3.11] gh-111181: Fix enum doctests (GH-111180)
  Doc/howto/enum.rst
  Lib/enum.py
  Lib/test/test_enum.py
Labels: awaiting core review, skip news

#111689 gh-109649: Fix test_os.test_process_cpu_count_affinity()
  Lib/test/test_os.py
Labels: tests, awaiting merge, skip news

#111714 gh-111644: Enhance support threading_cleanup()
  Lib/test/support/threading_helper.py
Labels: awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#111717 [3.11] gh-111644: Fix support threading_cleanup() (GH-111714)
  Lib/test/support/threading_helper.py
Labels: awaiting review, skip news

#111713 gh-111644: Fix asyncio test_unhandled_exceptions()
  Lib/test/test_asyncio/test_streams.py
Labels: tests, topic-asyncio, awaiting merge, skip news, needs backport to 3.12

#111716 [3.12] gh-111644: Fix support threading_cleanup() (GH-111714)
  Lib/test/support/threading_helper.py
Labels: awaiting review, skip news

#111634 [3.11] [3.12] GH-110894: Call loop exception handler for exceptions in client_connected_cb (GH-111601) (GH-111632)
  Lib/asyncio/streams.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2023-11-01-14-03-24.gh-issue-110894.7-wZxC.rst
Labels: awaiting review

#111718 [3.12] gh-111644: Fix asyncio test_unhandled_exceptions() (GH-111713)
  Lib/test/test_asyncio/test_streams.py
Labels: tests, awaiting merge, skip news

#111725 gh-111724: Fix doctest `ResourceWarning` in `howto/descriptor.rst`
  Doc/howto/descriptor.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#111631 gh-111495: Test C API functions with extreme sizes and indices
  Lib/test/test_capi/test_abstract.py
  Lib/test/test_capi/test_bytearray.py
  Lib/test/test_capi/test_bytes.py
  Lib/test/test_capi/test_unicode.py
Labels: tests, awaiting core review, skip news, topic-C-API, needs backport to 3.12

#111541 gh-111159: Fix `SyntaxError` doctests for non-builtin exception classes
  Lib/doctest.py
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Library/2023-11-04-10-24-25.gh-issue-111541.x0RBI1.rst
Labels: type-bug, awaiting merge, stdlib, needs backport to 3.11, needs backport to 3.12

#111549 gh-108303: Move `zip` and `tar` archives to `Lib/test/archivetestdata`
  Lib/test/archivetestdata/README.md
  Lib/test/archivetestdata/exe_with_z64
  Lib/test/archivetestdata/exe_with_zip
  Lib/test/archivetestdata/header.sh
  Lib/test/archivetestdata/recursion.tar
  Lib/test/archivetestdata/testdata_module_inside_zip.py
  Lib/test/archivetestdata/testtar.tar
  Lib/test/archivetestdata/testtar.tar.xz
  Lib/test/archivetestdata/zip_cp437_header.zip
  Lib/test/archivetestdata/zipdir.zip
  Lib/test/test_contextlib.py
  Lib/test/test_tarfile.py
  Lib/test/test_zipfile/test_core.py
  Makefile.pre.in
Labels: awaiting review, skip news

#111667 gh-111666: Speed up `BaseExceptionGroup.{derive,split,subgroup}`
  Misc/NEWS.d/next/Core and Builtins/2023-11-03-01-23-48.gh-issue-111666.l8Q8G5.rst
  Objects/exceptions.c
Labels: awaiting merge

#111733 [3.11] gh-111159: Fix `SyntaxError` doctests for non-builtin exception classes (GH-111541)
  Lib/doctest.py
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Library/2023-11-04-10-24-25.gh-issue-111541.x0RBI1.rst
Labels: type-bug, awaiting merge

#111732 [3.12] gh-111159: Fix `SyntaxError` doctests for non-builtin exception classes (GH-111541)
  Lib/doctest.py
  Lib/test/test_doctest.py
  Misc/NEWS.d/next/Library/2023-11-04-10-24-25.gh-issue-111541.x0RBI1.rst
Labels: type-bug, awaiting merge

#111731 [3.12] gh-111495: Test C API functions with extreme sizes and indices (GH-111631)
  Lib/test/test_capi/test_abstract.py
  Lib/test/test_capi/test_bytearray.py
  Lib/test/test_capi/test_bytes.py
  Lib/test/test_capi/test_unicode.py
Labels: tests, awaiting core review, skip news

#110848 GH-110829: Ensure Thread.join() joins the OS thread
  Include/cpython/pthread_stubs.h
  Include/internal/pycore_pythread.h
  Lib/test/_test_multiprocessing.py
  Lib/test/audit-tests.py
  Lib/test/test_audit.py
  Lib/test/test_concurrent_futures/test_process_pool.py
  Lib/test/test_thread.py
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Core and Builtins/2023-11-04-13-36-51.gh-issue-110829.Pa0CJI.rst
  Modules/_threadmodule.c
  Python/thread_nt.h
  Python/thread_pthread.h
  Python/thread_pthread_stubs.h
Labels: type-feature, awaiting merge, interpreter-core

#97906 gh-96954: use a directed acyclic word graph for storing the unicodedata codepoint names
  Lib/test/test_tools/test_makeunicodedata.py
  Lib/test/test_unicodedata.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2022-10-05-15-01-36.gh-issue-96954.ezwkrU.rst
  Modules/unicodedata.c
  Modules/unicodename_db.h
  Tools/unicode/dawg.py
  Tools/unicode/makeunicodedata.py
Labels: awaiting merge

#111727 [3.12] gh-111724: Fix doctest `ResourceWarning` in `howto/descriptor.rst` (GH-111725)
  Doc/howto/descriptor.rst
Labels: docs, awaiting review, skip news

#111728 [3.11] gh-111724: Fix doctest `ResourceWarning` in `howto/descriptor.rst` (GH-111725)
  Doc/howto/descriptor.rst
Labels: docs, awaiting review, skip news

#110881 gh-80675: Set `f_trace_lines = True` on all frames upon `pdb.set_trace()`
  Lib/bdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-10-14-20-15-53.gh-issue-80675._M-cQC.rst
Labels: awaiting merge

#110517 gh-110395: invalidate open kqueues after fork
  Lib/test/test_kqueue.py
  Misc/NEWS.d/next/Library/2023-10-08-14-17-06.gh-issue-110395._tdCsV.rst
  Modules/selectmodule.c
Labels: awaiting merge, needs backport to 3.12

#111720 gh-111719: Add extra check for alias command
  Doc/library/pdb.rst
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-11-04-01-20-23.gh-issue-111719.fUiKBD.rst
Labels: awaiting merge

#111748 gh-111747: DOC: fix moved link to Documentation Translations
  Doc/bugs.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#111750 [3.11] gh-111747: DOC: fix moved link to Documentation Translations (GH-111748)
  Doc/bugs.rst
Labels: docs, awaiting review, skip news

#111749 [3.12] gh-111747: DOC: fix moved link to Documentation Translations (GH-111748)
  Doc/bugs.rst
Labels: docs, awaiting review, skip news

#111624 gh-111495: Add tests for PyFloat C API
  Lib/test/test_capi/test_float.py
  Modules/_testcapi/float.c
Labels: tests, awaiting merge, skip news, topic-C-API, needs backport to 3.12

#111591 gh-111495: Add tests for PyComplex C API
  Lib/test/test_capi/test_complex.py
  Modules/_testcapi/complex.c
Labels: tests, awaiting merge, skip news, topic-C-API, needs backport to 3.12

#111752 [3.12] gh-111495: Add tests for PyFloat C API (GH-111624)
  Lib/test/test_capi/test_float.py
  Modules/_testcapi/float.c
Labels: awaiting review, skip news

#111753 [3.12] gh-111495: Add tests for PyComplex C API (GH-111591)
  Lib/test/test_capi/test_complex.py
  Modules/_testcapi/complex.c
Labels: awaiting review, skip news

#109467 gh-109466: Add ipv6_mapped property to IPv4Address
  Doc/library/ipaddress.rst
  Doc/whatsnew/3.13.rst
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2023-09-15-12-30-21.gh-issue-109466.6ah-aw.rst
Labels: type-feature, awaiting merge

#111695 gh-101180: Fix a bug where iso2022_jp_3 and iso2022_jp_2004 codecs read out of bounds
  Lib/test/test_codecencodings_iso2022.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-27-19-38-33.gh-issue-102388.vd5YUZ.rst
  Modules/cjkcodecs/_codecs_iso2022.c
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#111647 GH-111646: Simplify optimizer, by compacting uops when making executor.
  Python/optimizer.c
  Python/optimizer_analysis.c
Labels: awaiting core review, skip news

#111771 [3.11] gh-101180: Fix a bug where iso2022_jp_3 and iso2022_jp_2004 co…
  Lib/test/test_codecencodings_iso2022.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-27-19-38-33.gh-issue-102388.vd5YUZ.rst
  Modules/cjkcodecs/_codecs_iso2022.c
Labels: awaiting core review

#111769 [3.12] gh-101180: Fix a bug where iso2022_jp_3 and iso2022_jp_2004 codecs read out of bounds (gh-111695)
  Lib/test/test_codecencodings_iso2022.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-27-19-38-33.gh-issue-102388.vd5YUZ.rst
  Modules/cjkcodecs/_codecs_iso2022.c
Labels: awaiting merge

#111773 GH-111772: Specialize slot loads and stores for `_Py_T_OBJECT`
  Misc/NEWS.d/next/Core and Builtins/2023-11-03-19-25-38.gh-issue-111772.aRQvOn.rst
  Python/specialize.c
Labels: awaiting merge

#111764 gh-96954: Use skip_if_missing in test_makeunicodedata
  Lib/test/test_tools/test_makeunicodedata.py
Labels: tests, awaiting core review, skip news

#111702 simplify code to pop exception in frame_setlineno
  Objects/frameobject.c
Labels: skip issue, awaiting merge, skip news

#111707 gh-111698: Restrict Py_mod_multiple_interpreters to 3.12+ under Py_LIMITED_API
  Include/moduleobject.h
Labels: awaiting merge, skip news, needs backport to 3.12

#111780 [3.9] gh-101180: Fix a bug where iso2022_jp_3 and iso2022_jp_2004 codecs read out of bounds (gh-111695)
  Lib/test/test_codecencodings_iso2022.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-27-19-38-33.gh-issue-102388.vd5YUZ.rst
  Modules/cjkcodecs/_codecs_iso2022.c
Labels: awaiting core review

#111781 [3.8] gh-101180: Fix a bug where iso2022_jp_3 and iso2022_jp_2004 codecs read out of bounds (gh-111695)
  Lib/test/test_codecencodings_iso2022.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-27-19-38-33.gh-issue-102388.vd5YUZ.rst
  Modules/cjkcodecs/_codecs_iso2022.c
Labels: awaiting core review

#111715 gh-76785: Move _Py_excinfo Functions Out of the Internal C-API
  Include/internal/pycore_crossinterp.h
  Include/internal/pycore_pyerrors.h
  Python/crossinterp.c
  Python/errors.c
Labels: awaiting core review, skip news

#111812 GH-111485: Make `BEFORE_WITH` a uop
  Include/internal/pycore_opcode_metadata.h
  Python/abstract_interp_cases.c.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: performance, awaiting merge, skip news, interpreter-core

#111734 gh-111729: update generic syntax for `typing.Concatenate` sample code in `Doc/library/typing.rst`
  Doc/library/typing.rst
Labels: docs, awaiting review, skip news, needs backport to 3.12

#111814 [3.12] gh-111729: update generic syntax for `typing.Concatenate` sample code in `Doc/library/typing.rst` (GH-111734)
  Doc/library/typing.rst
Labels: docs, awaiting review, skip news

#111805 [3.11] gh-111797: fix enum how-to
  Doc/howto/enum.rst
Labels: docs, awaiting core review, skip news, 3.11

#111816 gh-110395: test: assert after the child dies.
  Lib/test/test_kqueue.py
Labels: tests, awaiting core review, skip news

#111792 gh-79932: raise exception if frame.clear() is called on a suspended frame
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.13.rst
  Lib/test/test_frame.py
  Misc/NEWS.d/next/Core and Builtins/2023-11-06-16-44-09.gh-issue-79932.2qv7uD.rst
  Objects/frameobject.c
Labels: awaiting merge

#111697 GH-111485: Allow arbitrary annotations on instructions and micro-ops.
  Include/internal/pycore_opcode_metadata.h
  Lib/test/test_generated_cases.py
  Python/abstract_interp_cases.c.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Tools/cases_generator/analysis.py
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/instructions.py
  Tools/cases_generator/lexer.py
  Tools/cases_generator/parsing.py
Labels: awaiting merge, skip news

#111766 gh-111765: move old PyFloat_* tests to Lib/test/test_capi/test_float.py
  Lib/test/test_capi/test_float.py
  Lib/test/test_float.py
Labels: tests, awaiting merge, skip news

#106674 gh-106672: C API: Report indiscriminately ignored errors
  Doc/whatsnew/3.13.rst
  Lib/test/test_capi/test_abstract.py
  Lib/test/test_capi/test_dict.py
  Lib/test/test_capi/test_sys.py
  Misc/NEWS.d/next/C API/2023-07-12-12-14-52.gh-issue-106672.fkRjmi.rst
  Objects/abstract.c
  Objects/dictobject.c
  Objects/object.c
  Python/sysmodule.c
Labels: awaiting merge

#109112 gh-85098: Implement functional CLI of symtable
  Doc/library/symtable.rst
  Lib/symtable.py
  Lib/test/test_symtable.py
  Misc/NEWS.d/next/Library/2023-09-08-12-10-10.gh-issue-85098.DfQbeJ.rst
Labels: awaiting merge

#111628 gh-111623 Serialize tuples with sub interpreters
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_interpreters.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-29-11-35-21.gh-issue-111435.ageUWQ.rst
  Misc/NEWS.d/next/Core and Builtins/2023-10-29-12-33-33.gh-issue-111438.bHTLLl.rst
  Misc/NEWS.d/next/Core and Builtins/2023-11-02-15-00-57.gh-issue-111623.BZxYc8.rst
  Python/crossinterp.c
Labels: awaiting merge

#111823 gh-81137: deprecate assignment of code object to a function of a mismatched type
  Doc/whatsnew/3.13.rst
  Lib/test/test_funcattrs.py
  Misc/NEWS.d/next/Core and Builtins/2023-11-07-12-59-02.gh-issue-81137.qFpJCY.rst
  Objects/funcobject.c
Labels: awaiting merge

#111830 gh-111806: Fix `test_recursion` in `test_richcmp` on WASI builds
  Lib/test/test_richcmp.py
Labels: tests, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#111832 [3.11] gh-111806: Fix `test_recursion` in `test_richcmp` on WASI builds (GH-111830)
  Lib/test/test_richcmp.py
Labels: tests, awaiting merge, skip news

#111831 [3.12] gh-111806: Fix `test_recursion` in `test_richcmp` on WASI builds (GH-111830)
  Lib/test/test_richcmp.py
Labels: tests, awaiting merge, skip news

#111785 gh-61199: Remove superfluous global statements from `base64._b32{en,de}code()*`
  Lib/base64.py
Labels: awaiting merge, skip news

#111833 gh-111089: Revert PyUnicode_AsUTF8() changes
  Doc/c-api/unicode.rst
  Doc/data/stable_abi.dat
  Doc/whatsnew/3.13.rst
  Include/cpython/unicodeobject.h
  Include/unicodeobject.h
  Lib/test/test_capi/test_unicode.py
  Lib/test/test_stable_abi_ctypes.py
  Misc/NEWS.d/next/C API/2023-10-20-01-42-43.gh-issue-111089.VIrd5q.rst
  Misc/NEWS.d/next/C API/2023-10-20-18-07-24.gh-issue-111089.RxkyrQ.rst
  Misc/stable_abi.toml
  Modules/_io/clinic/_iomodule.c.h
  Modules/_io/clinic/fileio.c.h
  Modules/_io/clinic/textio.c.h
  Modules/_io/clinic/winconsoleio.c.h
  Modules/_multiprocessing/clinic/multiprocessing.c.h
  Modules/_multiprocessing/clinic/semaphore.c.h
  Modules/_multiprocessing/posixshmem.c
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/clinic/cursor.c.h
  Modules/_sqlite/clinic/module.c.h
  Modules/_sqlite/connection.c
  Modules/_testcapi/clinic/exceptions.c.h
  Modules/cjkcodecs/clinic/multibytecodec.c.h
  Modules/clinic/_codecsmodule.c.h
  Modules/clinic/_cursesmodule.c.h
  Modules/clinic/_dbmmodule.c.h
  Modules/clinic/_elementtree.c.h
  Modules/clinic/_gdbmmodule.c.h
  Modules/clinic/_hashopenssl.c.h
  Modules/clinic/_localemodule.c.h
  Modules/clinic/_pickle.c.h
  Modules/clinic/_ssl.c.h
  Modules/clinic/_testclinic.c.h
  Modules/clinic/_tkinter.c.h
  Modules/clinic/posixmodule.c.h
  Modules/clinic/pyexpat.c.h
  Modules/clinic/symtablemodule.c.h
  Objects/clinic/bytearrayobject.c.h
  Objects/clinic/bytesobject.c.h
  Objects/clinic/floatobject.c.h
  Objects/clinic/memoryobject.c.h
  Objects/clinic/unicodeobject.c.h
  Objects/typeobject.c
  Objects/unicodeobject.c
  PC/python3dll.c
  Python/clinic/Python-tokenize.c.h
  Python/clinic/bltinmodule.c.h
  Python/clinic/sysmodule.c.h
  Python/getargs.c
  Tools/clinic/clinic.py
Labels: awaiting core review

#111849 GH-111848: Tidy up tier 2 handling of FOR_ITER specialization by using DEOPT_IF instead of jumps.
  Include/internal/pycore_opcode_metadata.h
  Lib/test/test_capi/test_misc.py
  Python/abstract_interp_cases.c.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/optimizer.c
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/lexer.py
Labels: awaiting merge, skip news

#111661 gh-111662: Update socket module to use AC for optimizing performance
  Modules/clinic/socketmodule.c.h
  Modules/socketmodule.c
Labels: awaiting merge, skip news

#111825 gh-108303: Move more `typing` related files to `Lib/test/typinganndata`
  Lib/test/test_type_aliases.py
  Lib/test/test_typing.py
  Lib/test/typinganndata/_typed_dict_helper.py
  Lib/test/typinganndata/mod_generics_cache.py
Labels: awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#111837 Glossary: Add "static type checker"
  Doc/glossary.rst
  Doc/howto/pyporting.rst
  Doc/library/datetime.rst
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#111854 [3.12] Glossary: Add "static type checker" (GH-111837)
  Doc/glossary.rst
  Doc/howto/pyporting.rst
  Doc/library/datetime.rst
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting review, skip news

#111855 [3.11] Glossary: Add "static type checker" (GH-111837)
  Doc/glossary.rst
  Doc/howto/pyporting.rst
  Doc/library/datetime.rst
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting review, skip news

#111853 socket: Update generated AC code
  Modules/clinic/socketmodule.c.h
Labels: skip issue, awaiting merge, skip news

#111770 gh-111768: Add `wsgiref.util.is_hop_by_hop` to `__all__`
  Lib/wsgiref/util.py
  Misc/NEWS.d/next/Library/2023-11-08-07-42-53.gh-issue-111768.g-WpnV.rst
Labels: awaiting merge

#111483 gh-111246: Remove listening Unix socket on close
  Doc/library/asyncio-eventloop.rst
  Doc/whatsnew/3.13.rst
  Lib/asyncio/unix_events.py
  Lib/test/test_asyncio/test_server.py
  Misc/NEWS.d/next/Library/2023-10-30-14-47-23.gh-issue-111246.QJ_ehs.rst
Labels: awaiting merge

#111453 gh-68166: Tkinter: Add tests and examples for element_create()
  Doc/library/tkinter.ttk.rst
  Lib/test/test_ttk/test_style.py
  Misc/NEWS.d/next/Library/2023-10-27-12-46-56.gh-issue-68166.0EbWW4.rst
Labels: tests, docs, awaiting core review, needs backport to 3.11, needs backport to 3.12

#111859 [3.12] gh-108303: Move more typing related files to Lib/test/typinganndata (GH-111825)
  Lib/test/test_type_aliases.py
  Lib/test/test_typing.py
  Lib/test/typinganndata/_typed_dict_helper.py
  Lib/test/typinganndata/mod_generics_cache.py
Labels: awaiting merge, skip news

#111562 gh-111495: Add tests for PyList C API
  Lib/test/test_capi/test_list.py
  Modules/_testcapi/list.c
Labels: awaiting merge, skip news

#111860 [3.11] gh-108303: Move more typing related files to Lib/test/typinganndata (GH-111825)
  Lib/test/test_typing.py
  Lib/test/typinganndata/_typed_dict_helper.py
  Lib/test/typinganndata/mod_generics_cache.py
Labels: awaiting review, skip news

#111844 no-issue: Remove redundant check in dbm.open()
  Modules/_dbmmodule.c
Labels: skip issue, awaiting merge, skip news

#111861 [3.12] gh-111495: Add tests for PyList C API (GH-111562)
  Lib/test/test_capi/test_list.py
  Modules/_testcapi/list.c
Labels: awaiting review, skip news

#110586 gh-110543: Fix CodeType.replace in presence of comprehensions
  Lib/test/test_listcomps.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-09-19-54-33.gh-issue-110543.1wrxO8.rst
  Objects/codeobject.c
Labels: awaiting merge, needs backport to 3.12

#111866 [3.12] gh-110543: Fix CodeType.replace in presence of comprehensions (GH-110586)
  Lib/test/test_listcomps.py
  Misc/NEWS.d/next/Core and Builtins/2023-10-09-19-54-33.gh-issue-110543.1wrxO8.rst
  Objects/codeobject.c
Labels: awaiting review

#111571 gh-111569: Implement Python critical section API
  Include/cpython/pystate.h
  Include/internal/pycore_critical_section.h
  Include/internal/pycore_lock.h
  Include/object.h
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2023-10-31-14-58-17.gh-issue-111569._V8iu4.rst
  Modules/Setup.stdlib.in
  Modules/_testinternalcapi.c
  Modules/_testinternalcapi/parts.h
  Modules/_testinternalcapi/test_critical_sections.c
  Objects/object.c
  PCbuild/_freeze_module.vcxproj
  PCbuild/_freeze_module.vcxproj.filters
  PCbuild/_testinternalcapi.vcxproj
  PCbuild/_testinternalcapi.vcxproj.filters
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/critical_section.c
  Python/pystate.c
Labels: awaiting merge, 3.13, topic-free-threaded

#111869 GH-111804: Drop posix.fallocate() under WASI
  Misc/NEWS.d/next/Library/2023-11-08-15-58-57.gh-issue-111804.uAXTOL.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting core review, needs backport to 3.11, needs backport to 3.12

#111708 gh-111354: remove comparisons with enum values, variable reuse, unused imports in genobject.c
  Include/internal/pycore_frame.h
  Objects/genobject.c
Labels: awaiting merge, skip news

#111852 gh-111835: Add seekable method to mmap.mmap
  Doc/library/mmap.rst
  Doc/whatsnew/3.13.rst
  Lib/test/test_mmap.py
  Misc/NEWS.d/next/Library/2023-11-08-23-32-03.gh-issue-111835.ufFiuW.rst
  Modules/mmapmodule.c
Labels: awaiting merge

#111850 GH-111843: Tier 2 exponential backoff
  Include/cpython/optimizer.h
  Misc/NEWS.d/next/Core and Builtins/2023-11-05-06-40-35.gh-issue-111843.c045cB.rst
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/optimizer.c
Labels: awaiting merge

#111879 gh-108303: Move config parser data to `Lib/test/configparserdata/`
  Lib/idlelib/idle_test/test_config.py
  Lib/test/configdata/cfgparser.1
  Lib/test/configdata/cfgparser.2
  Lib/test/configdata/cfgparser.3
  Lib/test/test_configparser.py
Labels: awaiting review, skip news, needs backport to 3.11, needs backport to 3.12

#111885 gh-111881: Use lazy import in test.support
  Lib/test/support/__init__.py
  Lib/test/support/os_helper.py
Labels: tests, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#111882 [3.12] gh-108303: Move config parser data to `Lib/test/configparserdata/` (gh-111879)
  Lib/idlelib/idle_test/test_config.py
  Lib/test/configdata/cfgparser.1
  Lib/test/configdata/cfgparser.2
  Lib/test/configdata/cfgparser.3
  Lib/test/test_configparser.py
Labels: awaiting review, skip news

#111880 gh-108303: Move more files to `Lib/test/test_module`
  Lib/test/test_module/__init__.py
  Lib/test/test_module/final_a.py
  Lib/test/test_module/final_b.py
Labels: awaiting review, skip news, needs backport to 3.11, needs backport to 3.12

#111883 [3.11] gh-108303: Move config parser data to `Lib/test/configparserdata/` (gh-111879)
  Lib/idlelib/idle_test/test_config.py
  Lib/test/configdata/cfgparser.1
  Lib/test/configdata/cfgparser.2
  Lib/test/configdata/cfgparser.3
  Lib/test/test_configparser.py
Labels: awaiting review, skip news

#111868 stdlib.rst: mathematics section: random.random: add detail to comment on range of random.random()
  Doc/tutorial/stdlib.rst
Labels: docs, skip issue, awaiting merge, skip news
