Repository python/cpython, pull requests merged in 2023-01, with the labels that each got.

#100647 IDLE - fix module browser test
  Lib/idlelib/idle_test/test_browser.py
Labels: type-bug, tests, skip issue, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#100653 [3.10] IDLE - fix module browser test (GH-100647)
  Lib/idlelib/idle_test/test_browser.py
Labels: type-bug, tests, skip issue, awaiting merge, skip news

#100652 [3.11] IDLE - fix module browser test (GH-100647)
  Lib/idlelib/idle_test/test_browser.py
Labels: type-bug, tests, skip issue, awaiting merge, skip news

#100547 gh-100546: Remove incorrect positional-only marker from eval
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11

#100654 [3.11] gh-100546: Remove incorrect positional-only marker from eval (GH-100547)
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news

#100489 gh-100488: Add is_integer method to fractions.Fraction
  Doc/library/fractions.rst
  Lib/fractions.py
  Lib/test/test_fractions.py
  Misc/NEWS.d/next/Library/2022-12-24-04-13-54.gh-issue-100488.Ut8HbE.rst
Labels: awaiting merge

#100650 gh-100649: Update native_thread_id after fork
  Misc/NEWS.d/next/Core and Builtins/2022-12-31-23-32-09.gh-issue-100649.C0fY4S.rst
  Modules/posixmodule.c
Labels: awaiting merge, needs backport to 3.11

#100660 [3.11] gh-100649: Update native_thread_id after fork (gh-100650)
  Misc/NEWS.d/next/Core and Builtins/2022-12-31-23-32-09.gh-issue-100649.C0fY4S.rst
  Modules/posixmodule.c
Labels: awaiting merge

#96778 gh-96773 Fixing documentation of socket backlog
  Doc/library/socket.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#100661 [3.11] gh-96773 Fix documentation of socket backlog (GH-96778)
  Doc/library/socket.rst
Labels: docs, awaiting merge, skip news

#100662 [3.10] gh-96773 Fix documentation of socket backlog (GH-96778)
  Doc/library/socket.rst
Labels: docs, awaiting merge, skip news

#100416 gh-100201: Document behavior with a bare yield statement
  Doc/reference/expressions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#25362 gh-87980: Fix the error message for disallowed __weakref__ slots
  Objects/typeobject.c
Labels: awaiting merge, skip news

#100665 [3.10] gh-100201: Document behavior with a bare `yield` statement (GH-100416)
  Doc/reference/expressions.rst
Labels: docs, awaiting merge, skip news

#100664 [3.11] gh-100201: Document behavior with a bare `yield` statement (GH-100416)
  Doc/reference/expressions.rst
Labels: docs, awaiting merge, skip news

#100598 gh-97930: Apply changes from importlib_resources 5.10.
  Doc/library/importlib.resources.rst
  Lib/importlib/resources/_common.py
  Lib/importlib/resources/_legacy.py
  Lib/importlib/resources/abc.py
  Lib/importlib/resources/simple.py
  Lib/test/test_importlib/resources/_path.py
  Lib/test/test_importlib/resources/test_files.py
  Lib/test/test_importlib/resources/util.py
  Misc/NEWS.d/next/Library/2022-12-29-11-45-22.gh-issue-97930.hrtmJe.rst
Labels: awaiting core review

#100630 gh-99953: Purge mention of numeric param style from sqlite3 docs
  Doc/library/sqlite3.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.10, needs backport to 3.11

#100669 [3.11] gh-99953: Purge mention of numeric param style from sqlite3 docs (GH-100630)
  Doc/library/sqlite3.rst
Labels: docs, awaiting merge, skip news

#100670 [3.10] gh-99953: Purge mention of numeric param style from sqlite3 docs (GH-100630)
  Doc/library/sqlite3.rst
Labels: docs, awaiting merge, skip news

#100436 gh-100428: Make int documentation more accurate
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#100675 [3.10] gh-100428: Make int documentation more accurate (GH-100436)
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news

#100674 [3.11] gh-100428: Make int documentation more accurate (GH-100436)
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news

#100667 doc: switch from `deprecated-removed` to `deprecated`
  Doc/c-api/init.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11

#100682 [3.11] Fix deprecation doc for `PyEval_InitThreads` (GH-100667)
  Doc/c-api/init.rst
Labels: docs, skip issue, awaiting merge, skip news

#100683 fix `grammer` -> `grammar` typo in expressions.rst
  Doc/reference/expressions.rst
Labels: docs, skip issue, awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#100685 [3.10] fix `grammer` -> `grammar` typo in expressions.rst (GH-100683)
  Doc/reference/expressions.rst
Labels: docs, skip issue, awaiting merge, skip news

#100684 [3.11] fix `grammer` -> `grammar` typo in expressions.rst (GH-100683)
  Doc/reference/expressions.rst
Labels: docs, skip issue, awaiting merge, skip news

#100678 gh-100676: Improve description for venv --upgrade-deps (GH-100678)
  Lib/venv/__init__.py
Labels: awaiting merge, skip news

#100663 gh-100637: Fix int and bool __sizeof__ calculation to include the 1 element ob_digit array for 0 and False
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2023-01-01-15-59-48.gh-issue-100637.M2n6Kg.rst
  Objects/longobject.c
Labels: awaiting merge

#100671 gh-89727: Improve os.walk complexity and speed
  Lib/os.py
  Misc/NEWS.d/next/Library/2023-01-01-23-57-00.gh-issue-89727.ojedHN.rst
Labels: performance, awaiting merge

#98353 gh-81611: Improve `range` paragraph in 8.3 of language reference
  Doc/reference/compound_stmts.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#100611 gh-89419: gdb: fix printing AttributeError in py-locals when no frame is available
  Misc/NEWS.d/next/Tools-Demos/2022-12-29-19-22-11.bpo-45256.a0ee_H.rst
  Tools/gdb/libpython.py
Labels: awaiting merge

#100718 [3.11] gh-95882: fix regression in the traceback of exceptions propagated from inside a contextlib context manager (GH-95883)
  Lib/contextlib.py
  Lib/test/test_contextlib.py
  Lib/test/test_contextlib_async.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2022-08-11-10-02-19.gh-issue-95882.FsUr72.rst
Labels: type-bug, awaiting merge, :robot: automerge

#100717 [3.11] gh-100637: Fix int and bool __sizeof__ calculation to include the 1 element ob_digit array for 0 and False (GH-100663)
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2023-01-01-15-59-48.gh-issue-100637.M2n6Kg.rst
  Objects/longobject.c
Labels: awaiting review

#100147 gh-100146: Steal references from stack when building a list
  Include/internal/pycore_list.h
  Misc/NEWS.d/next/Core and Builtins/2022-12-09-13-18-42.gh-issue-100146.xLVKg0.rst
  Objects/listobject.c
  Python/bytecodes.c
  Python/generated_cases.c.h
Labels: awaiting merge

#100728 gh-100700: Remove Date and Release fields in past whatsnews
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.11.rst
  Doc/whatsnew/3.9.rst
Labels: docs, awaiting core review, skip news

#100709 Enum Documentation: replace last value by highest value for Flag auto
  Doc/library/enum.rst
Labels: docs, skip issue, awaiting merge, skip news

#100729 [3.11] gh-100700: Remove Date and Release fields in past whatsnews
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.9.rst
Labels: docs, awaiting core review, skip news

#100730 [3.10] gh-100700: Remove Date and Release fields in whatsnew/3.9
  Doc/whatsnew/3.9.rst
Labels: docs, awaiting core review, skip news

#100715 [3.10] gh-95882: Add tests for traceback from contextlib context managers (GH-95883)
  Lib/test/test_contextlib.py
  Lib/test/test_contextlib_async.py
Labels: type-bug, tests, awaiting merge, skip news, 3.10

#100732 [3.11] [Enum] docs: replace 'last value' by 'highest value' for Flag auto (GH-100709)
  Doc/library/enum.rst
Labels: docs, skip issue, awaiting merge, skip news

#100733 [3.11] Docs: Fix the Show Source link
  Doc/tools/templates/customsourcelink.html
Labels: docs, skip issue, awaiting core review, skip news, 3.11

#100738 [3.11] gh-89419: gdb: fix bug causing AttributeError in py-locals when no frame is available (GH-100611)
  Misc/NEWS.d/next/Tools-Demos/2022-12-29-19-22-11.bpo-45256.a0ee_H.rst
  Tools/gdb/libpython.py
Labels: awaiting merge

#100615 GH-86508: skip binding to local addresses of different family in `asyncio.open_connection`
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_events.py
  Misc/NEWS.d/next/Library/2022-12-30-07-49-08.gh-issue-86508.nGZDzC.rst
Labels: type-bug, expert-asyncio, awaiting merge, needs backport to 3.10, 3.11, 3.10, 3.12, needs backport to 3.11

#100742 [3.10] GH-86508: skip binding to local addresses of different family in `asyncio.open_connection` (GH-100615)
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_events.py
  Misc/NEWS.d/next/Library/2022-12-30-07-49-08.gh-issue-86508.nGZDzC.rst
Labels: type-bug, awaiting merge

#100741 [3.11] GH-86508: skip binding to local addresses of different family in `asyncio.open_connection` (GH-100615)
  Lib/asyncio/base_events.py
  Lib/test/test_asyncio/test_events.py
  Misc/NEWS.d/next/Library/2022-12-30-07-49-08.gh-issue-86508.nGZDzC.rst
Labels: type-bug, awaiting merge

#100722 gh-100720: refactor calculation of number of frame slots for a code object into the new function _PyFrame_NumSlotsForCodeObject
  Include/internal/pycore_frame.h
  Misc/NEWS.d/next/Core and Builtins/2023-01-03-16-50-42.gh-issue-100720.UhE7P-.rst
  Objects/frameobject.c
  Objects/genobject.c
  Tools/build/deepfreeze.py
Labels: awaiting merge, interpreter-core

#100744 [3.10] docs: fix `ssizeobjargproc` parameters (GH-100736)
  Doc/c-api/typeobj.rst
Labels: docs, skip issue, awaiting merge, skip news

#100743 [3.11] docs: fix `ssizeobjargproc` parameters (GH-100736)
  Doc/c-api/typeobj.rst
Labels: docs, skip issue, awaiting merge, skip news

#100721 GH-100719: Remove the `co_nplaincellvars` field from code objects.
  Include/cpython/code.h
  Misc/NEWS.d/next/Core and Builtins/2023-01-03-16-38-18.gh-issue-100719.2C--ko.rst
  Objects/codeobject.c
  Objects/frameobject.c
  Objects/typeobject.c
  Python/bytecodes.c
  Python/ceval.c
  Python/compile.c
  Python/generated_cases.c.h
  Tools/build/deepfreeze.py
Labels: awaiting merge

#100748 gh-100747: some compiler macros use c instead of C to access the compiler
  Python/compile.c
Labels: awaiting core review, skip news, interpreter-core

#100704 [3.11] gh-81611: Improve `range` paragraph in 8.3 of language reference (GH-98353)
  Doc/reference/compound_stmts.rst
Labels: docs, awaiting merge, skip news

#100705 [3.10] gh-81611: Improve `range` paragraph in 8.3 of language reference (GH-98353)
  Doc/reference/compound_stmts.rst
Labels: docs, awaiting merge, skip news

#100740 gh-100739: Respect mock spec when checking for unsafe prefixes
  Lib/test/test_unittest/testmock/testmock.py
  Lib/unittest/mock.py
  Misc/NEWS.d/next/Library/2023-01-04-09-53-38.gh-issue-100740.-j5UjI.rst
Labels: awaiting merge

#100757 Drop myself from pathlib maintenance
  .github/CODEOWNERS
Labels: skip issue, awaiting core review, skip news

#100760 [3.11] gh-100739: Respect mock spec when checking for unsafe prefixes (GH-100740)
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2023-01-04-09-53-38.gh-issue-100740.-j5UjI.rst
Labels: awaiting merge

#100761 [3.10] gh-100739: Respect mock spec when checking for unsafe prefixes (GH-100740)
  Lib/unittest/mock.py
  Lib/unittest/test/testmock/testmock.py
  Misc/NEWS.d/next/Library/2023-01-04-09-53-38.gh-issue-100740.-j5UjI.rst
Labels: awaiting merge

#100702 GH-100766: Note that locale.LC_MESSAGES is not universal (GH-100702)
  Doc/library/locale.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#100767 GH-100766: Note that locale.LC_MESSAGES is not universal (GH-100767)
  Doc/library/locale.rst
Labels: docs, awaiting review, skip news

#100768 GH-100766: Note that locale.LC_MESSAGES is not universal (GH-100768)
  Doc/library/locale.rst
Labels: docs, awaiting review, skip news

#100753 GH-100288: Remove LOAD_ATTR_METHOD_WITH_DICT instruction.
  Include/internal/pycore_opcode.h
  Include/opcode.h
  Lib/opcode.py
  Misc/NEWS.d/next/Core and Builtins/2023-01-04-16-40-55.gh-issue-100288.hRSRaT.rst
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Python/specialize.c
Labels: awaiting merge

#100771 GH-99005: Add `CALL_INTRINSIC_1` instruction
  Doc/library/dis.rst
  Include/internal/pycore_intrinsics.h
  Include/internal/pycore_opcode.h
  Include/opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_dis.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2023-01-05-13-54-00.gh-issue-99005.D7H6j4.rst
  PCbuild/_freeze_module.vcxproj
  PCbuild/_freeze_module.vcxproj.filters
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/bytecodes.c
  Python/ceval.c
  Python/compile.c
  Python/generated_cases.c.h
  Python/intrinsics.c
  Python/opcode_targets.h
Labels: awaiting merge

#100735 GH-98831: Update generate_cases.py: register inst, opcode_metadata.h
  Makefile.pre.in
  Python/bytecodes.c
  Python/compile.c
  Python/opcode_metadata.h
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/parser.py
Labels: awaiting merge, skip news

#100778 gh-98831: Regenerate Python/opcode_metadata.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news, 3.12

#100563 gh-100562: improve performance of `pathlib.Path.absolute()`
  Lib/pathlib.py
  Misc/NEWS.d/next/Library/2022-12-28-00-28-43.gh-issue-100562.Hic0Z0.rst
Labels: performance, awaiting merge, :robot: automerge, 3.12, expert-pathlib

#100779 Add hauntsaninja as tomllib CODEOWNER
  .github/CODEOWNERS
Labels: skip issue, awaiting merge, skip news, :robot: automerge

#100737 gh-87691: add an absolute path pathlib example in / operator docs
  Doc/library/pathlib.rst
Labels: docs, awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11, expert-pathlib

#100780 [3.11] gh-87691: add an absolute path pathlib example in / operator docs (GH-100737)
  Doc/library/pathlib.rst
Labels: docs, awaiting merge, skip news

#100781 [3.10] gh-87691: add an absolute path pathlib example in / operator docs (GH-100737)
  Doc/library/pathlib.rst
Labels: docs, awaiting merge, skip news

#100756 gh-90104: avoid RecursionError on recursive dataclass field repr
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2023-01-04-22-10-31.gh-issue-90104.yZk5EX.rst
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11

#100782 gh-87691: clarify use of anchor in pathlib docs
  Doc/library/pathlib.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#100787 [3.10] gh-87691: clarify use of anchor in pathlib docs (GH-100782)
  Doc/library/pathlib.rst
Labels: docs, awaiting merge, skip news

#100786 [3.11] gh-87691: clarify use of anchor in pathlib docs (GH-100782)
  Doc/library/pathlib.rst
Labels: docs, awaiting merge, skip news

#100784 [3.11] gh-90104: avoid RecursionError on recursive dataclass field repr (gh-100756)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2023-01-04-22-10-31.gh-issue-90104.yZk5EX.rst
Labels: awaiting merge, :robot: automerge

#100785 [3.10] gh-90104: avoid RecursionError on recursive dataclass field repr (gh-100756)
  Lib/dataclasses.py
  Lib/test/test_dataclasses.py
  Misc/NEWS.d/next/Library/2023-01-04-22-10-31.gh-issue-90104.yZk5EX.rst
Labels: awaiting merge, :robot: automerge

#100798 gh-99026 update dataclasses docs
  Doc/library/dataclasses.rst
Labels: docs, awaiting review, skip news, needs backport to 3.10, needs backport to 3.11

#100800 [3.10] gh-99026 update dataclasses docs for when annotations are inspected (gh-100798)
  Doc/library/dataclasses.rst
Labels: docs, awaiting merge, skip news, :robot: automerge

#100799 [3.11] gh-99026 update dataclasses docs for when annotations are inspected (gh-100798)
  Doc/library/dataclasses.rst
Labels: docs, awaiting merge, skip news, :robot: automerge

#100774 GH-99005: More intrinsics
  Doc/library/dis.rst
  Include/internal/pycore_genobject.h
  Include/internal/pycore_intrinsics.h
  Include/internal/pycore_opcode.h
  Include/opcode.h
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_lltrace.py
  Misc/NEWS.d/next/Core and Builtins/2023-01-05-17-54-29.gh-issue-99005.cmGwxv.rst
  Objects/genobject.c
  Python/bytecodes.c
  Python/compile.c
  Python/generated_cases.c.h
  Python/intrinsics.c
  Python/opcode_metadata.h
  Python/opcode_targets.h
Labels: awaiting merge

#100759 gh-100758: Refactor initialisation of frame headers into a single function (_PyFrame_Initialize)
  Include/internal/pycore_frame.h
  Objects/frameobject.c
  Python/bytecodes.c
  Python/ceval.c
  Python/generated_cases.c.h
Labels: awaiting core review, skip news

#100791 gh-91851: Trivial optimizations in Fraction
  Lib/fractions.py
  Misc/NEWS.d/next/Library/2023-01-05-23-04-15.gh-issue-91851.AuCzU5.rst
Labels: awaiting merge

#100763 GH-98831: Add some tests for generate_cases.py
  Tools/cases_generator/test_generator.py
Labels: tests, awaiting merge, skip news

#100691 gh-100690: Prevent prefix "called_" for attributes of safe mock objects
  Lib/test/test_unittest/testmock/testmock.py
  Lib/unittest/mock.py
  Misc/NEWS.d/next/Library/2023-01-02-16-59-49.gh-issue-100690.2EgWPS.rst
Labels: type-bug, awaiting merge, stdlib

#100808 Add barneygale to CODEOWNERS for pathlib
  .github/CODEOWNERS
Labels: skip issue, awaiting merge, skip news, :robot: automerge

#100819 gh-100690: [mock] hide `ATTRIB_DENY_LIST` and make it immutable
  Lib/unittest/mock.py
Labels: awaiting merge, skip news

#96335 gh-96127: Fix `inspect.signature` call on mocks
  Lib/test/test_inspect.py
  Lib/unittest/mock.py
  Misc/NEWS.d/next/Library/2022-08-27-10-35-50.gh-issue-96127.8RdLre.rst
Labels: awaiting merge

#100806 gh-88696: clean up dead argument to compiler_make_closure
  Python/compile.c
Labels: awaiting review, skip news

#100701 gh-100673: Removed erroneous note in the get_type_hints docs
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#100823 [3.11] gh-100673: Removed erroneous note in the get_type_hints docs (GH-100701)
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news

#100677 GH-100485: Add math.sumprod()
  Doc/library/itertools.rst
  Doc/library/math.rst
  Lib/test/test_math.py
  Misc/NEWS.d/next/Library/2023-01-01-21-54-46.gh-issue-100485.geNrHS.rst
  Modules/clinic/mathmodule.c.h
  Modules/mathmodule.c
Labels: type-feature, awaiting core review, 3.12

#100826 [3.10] gh-100673: Removed erroneous note in the get_type_hints docs (#100701)
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news, :robot: automerge

#100828 [3.11] Future-proof recipe by renaming dotproduct() to sumprod()
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting core review, skip news

#100793 gh-100792: Make `email.message.Message.__contains__` twice as fast
  Lib/email/message.py
  Misc/NEWS.d/next/Library/2023-01-06-14-05-15.gh-issue-100792.CEOJth.rst
Labels: performance, awaiting merge

#100816 gh-100815: Normalize `types` module usage in `copy` module
  Lib/copy.py
Labels: awaiting merge, skip news

#100836 GH-100485: Convert from Fast2Sum to 2Sum
  Modules/mathmodule.c
Labels: performance, awaiting core review, skip news

#100788 gh-100776: Fix misleading default value in help(input)
  Misc/NEWS.d/next/Core and Builtins/2023-01-06-02-02-11.gh-issue-100776.pP8xux.rst
  Python/bltinmodule.c
  Python/clinic/bltinmodule.c.h
Labels: awaiting merge

#100825 gh-100824: Fix type for the documentation of unittest.TestLoader.testNamePatterns
  Doc/library/unittest.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#100838 [3.11] gh-100824: Fix typo in the documentation of unittest.TestLoader.testNamePatterns (GH-100825)
  Doc/library/unittest.rst
Labels: docs, awaiting merge, skip news

#100839 [3.10] gh-100824: Fix typo in the documentation of unittest.TestLoader.testNamePatterns (GH-100825)
  Doc/library/unittest.rst
Labels: docs, awaiting merge, skip news

#25518 gh-91851: Micro optimizations for Fraction's arithmetic
  Lib/fractions.py
  Misc/NEWS.d/next/Library/2022-04-23-08-12-14.gh-issue-91851.Jd47V6.rst
Labels: performance, awaiting merge

#100811 gh-100783: fix os.path.join documentation
  Doc/library/os.path.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#100843 [3.11] gh-100783: fix os.path.join documentation (GH-100811)
  Doc/library/os.path.rst
Labels: docs, awaiting merge, skip news

#100844 [3.10] gh-100783: fix os.path.join documentation (GH-100811)
  Doc/library/os.path.rst
Labels: docs, awaiting merge, skip news

#100841 [3.11] gh-100776: Fix misleading default value in help(input) (GH-100788)
  Misc/NEWS.d/next/Core and Builtins/2023-01-06-02-02-11.gh-issue-100776.pP8xux.rst
  Python/bltinmodule.c
  Python/clinic/bltinmodule.c.h
Labels: awaiting core review

#100842 [3.10] gh-100776: Fix misleading default value in help(input) (GH-100788)
  Misc/NEWS.d/next/Core and Builtins/2023-01-06-02-02-11.gh-issue-100776.pP8xux.rst
  Python/bltinmodule.c
  Python/clinic/bltinmodule.c.h
Labels: awaiting core review

#100745 gh-100689: Revert "bpo-41798: pyexpat: Allocate the expat_CAPI on the…
  Misc/NEWS.d/next/Library/2023-01-04-12-58-59.gh-issue-100689.Ce0ITG.rst
  Modules/pyexpat.c
Labels: awaiting merge, needs backport to 3.10, release-blocker, type-crash, needs backport to 3.11

#100846 [3.11] gh-100689: Revert "bpo-41798: pyexpat: Allocate the expat_CAPI on the heap memory (GH-24061)" (GH-100745)
  Misc/NEWS.d/next/Library/2023-01-04-12-58-59.gh-issue-100689.Ce0ITG.rst
  Modules/pyexpat.c
Labels: awaiting merge, release-blocker, type-crash

#100847 [3.10] gh-100689: Revert "bpo-41798: pyexpat: Allocate the expat_CAPI on the heap memory (GH-24061)" (GH-100745)
  Misc/NEWS.d/next/Library/2023-01-04-12-58-59.gh-issue-100689.Ce0ITG.rst
  Modules/pyexpat.c
Labels: awaiting merge, release-blocker, type-crash

#31181 GH-90829: Fix empty iterable error message in min/max
  Lib/test/test_builtin.py
  Python/bltinmodule.c
Labels: awaiting merge, skip news

#100848 Update copyright years to 2023.
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: skip issue, awaiting core review, skip news, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#100857 GH-100485: Tweaks to sumprod()
  Doc/whatsnew/3.12.rst
  Lib/test/test_math.py
  Modules/mathmodule.c
Labels: awaiting core review, skip news

#100845 gh-100833: Remove 'volatile' qualifiers in fsum algorithm
  Misc/NEWS.d/next/Library/2023-01-08-12-10-17.gh-issue-100833.f6cT7E.rst
  Modules/mathmodule.c
Labels: type-feature, performance, awaiting merge

#100830 GH-100805: Support numpy.array() in random.choice().
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2023-01-07-15-13-47.gh-issue-100805.05rBz9.rst
Labels: type-bug, awaiting merge, needs backport to 3.11

#100858 [3.11] GH-100805: Support numpy.array() in random.choice(). (GH-100830)
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2023-01-07-15-13-47.gh-issue-100805.05rBz9.rst
Labels: type-bug, awaiting merge, :robot: automerge

#100859 Update additional copyright years to 2023.
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
Labels: OS-mac, skip issue, awaiting core review, skip news

#100581 gh-87447: Fix walrus comprehension rebind checking
  Doc/whatsnew/3.12.rst
  Lib/test/test_named_expressions.py
  Misc/NEWS.d/next/Core and Builtins/2022-12-28-15-02-53.gh-issue-87447.7-aekA.rst
  Python/symtable.c
Labels: awaiting merge

#100851 [3.9] Update copyright years to 2023. (gh-100848).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: skip issue, awaiting core review, skip news

#100850 [3.10] Update copyright years to 2023. (gh-100848).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: skip issue, awaiting core review, skip news

#100852 [3.8] Update copyright years to 2023. (gh-100848).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: skip issue, awaiting core review, skip news

#100853 [3.7] Update copyright years to 2023. (gh-100848).
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: skip issue, awaiting core review, skip news

#100849 [3.11] Update copyright years to 2023. (gh-100848)
  Doc/copyright.rst
  Doc/license.rst
  LICENSE
  Mac/IDLE/IDLE.app/Contents/Info.plist
  Mac/PythonLauncher/Info.plist.in
  Mac/Resources/app/Info.plist.in
  Mac/Resources/framework/Info.plist.in
  PC/python_ver_rc.h
  Python/getcopyright.c
  README.rst
Labels: skip issue, awaiting merge, skip news, :robot: automerge

#100863 Update copyright year in README
  README.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.7, :robot: automerge, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#100864 [3.11] Update copyright year in README (GH-100863)
  README.rst
Labels: docs, skip issue, awaiting review, skip news

#100865 [3.10] Update copyright year in README (GH-100863)
  README.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9

#100868 [3.7] Update copyright year in README (GH-100863) (GH-100865)
  README.rst
Labels: docs, skip issue, awaiting review, skip news

#100866 [3.9] Update copyright year in README (GH-100863) (GH-100865)
  README.rst
Labels: docs, skip issue, awaiting review, skip news

#100867 [3.8] Update copyright year in README (GH-100863) (GH-100865)
  README.rst
Labels: docs, skip issue, awaiting review, skip news

#10294 GH-100813: Add IPv4 socket option constant IP_PKTINFO as socket module attribute
  Doc/library/socket.rst
  Misc/NEWS.d/next/Library/2023-01-06-22-36-27.gh-issue-100813.mHRdQn.rst
  Modules/socketmodule.c
Labels: awaiting merge

#100765 gh-100764: add pycore_frame.h to PYTHON_HEADERS
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
Labels: awaiting merge, skip news

#100874 fix up mock tests coverage
  Lib/test/test_unittest/testmock/testmock.py
Labels: skip issue, awaiting core review, skip news

#13364 GH-81061: Fix refcount issue when returning `None` from a `ctypes.py_object` callback
  Lib/test/test_ctypes/test_refcounts.py
  Misc/NEWS.d/next/Library/2019-05-13-11-37-30.bpo-36880.ZgBgH0.rst
  Modules/_ctypes/callbacks.c
Labels: type-bug, tests, awaiting merge, needs backport to 3.10, needs backport to 3.11

#100881 gh-100873: Fix "‘lo’ may be used uninitialized in this function" warning in `mathmodule.c`
  Modules/mathmodule.c
Labels: awaiting merge, skip news

#100878 [3.10] GH-81061: Fix refcount issue when returning `None` from a `ctypes.py_object` callback (GH-13364)
  Lib/ctypes/test/test_refcounts.py
  Misc/NEWS.d/next/Library/2019-05-13-11-37-30.bpo-36880.ZgBgH0.rst
  Modules/_ctypes/callbacks.c
Labels: type-bug, awaiting merge

#100877 [3.11] GH-81061: Fix refcount issue when returning `None` from a `ctypes.py_object` callback (GH-13364)
  Lib/ctypes/test/test_refcounts.py
  Misc/NEWS.d/next/Library/2019-05-13-11-37-30.bpo-36880.ZgBgH0.rst
  Modules/_ctypes/callbacks.c
Labels: type-bug, awaiting merge

#100381 gh-99191: Use correct check for MSVC C++ version support in _wmimodule.cpp
  Misc/NEWS.d/next/Windows/2022-12-20-18-36-17.gh-issue-99191.0cfRja.rst
  PC/_wmimodule.cpp
Labels: OS-windows, awaiting review, build, 3.12

#100883 gh-100882: Improve `test_pickling` case in `test_ast.py`
  Lib/test/test_ast.py
Labels: tests, awaiting merge, skip news

#100613 GH-100126: Skip incomplete frames in more places
  Include/internal/pycore_frame.h
  Lib/test/test_frame.py
  Misc/NEWS.d/next/Core and Builtins/2022-12-29-04-39-38.gh-issue-100126.pfFJd-.rst
  Modules/_tracemalloc.c
  Modules/signalmodule.c
  Objects/frameobject.c
  Objects/genobject.c
  Objects/typeobject.c
  Python/ceval.c
  Python/frame.c
  Python/pystate.c
  Python/sysmodule.c
Labels: awaiting core review, interpreter-core, release-blocker, type-crash

#27376 bpo-28356: Document os.rename() behavior on Windows for differing filesystems
  Doc/library/os.rst
Labels: docs, awaiting review, skip news

#100897 [3.10] bpo-28356: Document os.rename() behavior on Windows for differing volumes (GH-27376)
  Doc/library/os.rst
Labels: docs, awaiting merge, skip news

#100896 [3.11] bpo-28356: Document os.rename() behavior on Windows for differing volumes (GH-27376)
  Doc/library/os.rst
Labels: docs, awaiting merge, skip news

#100901 gh-100180: Update Windows installer to OpenSSL 1.1.1s
  Misc/NEWS.d/next/Windows/2023-01-09-23-03-57.gh-issue-100180.b5phrg.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: OS-windows, awaiting core review, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#100895 GH-98831: Refactor instr format code and change to enum
  Python/opcode_metadata.h
  Tools/cases_generator/generate_cases.py
Labels: awaiting merge, skip news

#100902 [3.11] gh-100180: Update Windows installer to OpenSSL 1.1.1s (GH-100901)
  Misc/NEWS.d/next/Windows/2023-01-09-23-03-57.gh-issue-100180.b5phrg.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: awaiting merge

#100905 gh-100893: update bpo reference in Mac README
  Mac/README.rst
Labels: docs, OS-mac, awaiting core review, skip news

#100906 [3.11] gh-100893: update bpo reference in Mac README (GH-100905)
  Mac/README.rst
Labels: docs, awaiting merge, skip news

#100907 [3.10] gh-100893: update bpo reference in Mac README (GH-100905)
  Mac/README.rst
Labels: docs, awaiting merge, skip news

#100908 gh-100180: Update macOS installer to OpenSSL 1.1.1s
  Mac/BuildScript/build-installer.py
  Mac/BuildScript/openssl1.1.1q-pr-18719.patch
  Misc/NEWS.d/next/macOS/2023-01-09-22-04-21.gh-issue-100180.WVhCny.rst
Labels: awaiting core review

#100910 [3.10] gh-100180: Update macOS installer to OpenSSL 1.1.1s (GH-100908)
  Mac/BuildScript/build-installer.py
  Mac/BuildScript/openssl1.1.1q-pr-18719.patch
  Misc/NEWS.d/next/macOS/2023-01-09-22-04-21.gh-issue-100180.WVhCny.rst
Labels: awaiting merge

#100909 [3.11] gh-100180: Update macOS installer to OpenSSL 1.1.1s (GH-100908)
  Mac/BuildScript/build-installer.py
  Mac/BuildScript/openssl1.1.1q-pr-18719.patch
  Misc/NEWS.d/next/macOS/2023-01-09-22-04-21.gh-issue-100180.WVhCny.rst
Labels: awaiting merge

#100880 Fix typos in Doc folder
  Doc/c-api/structures.rst
  Doc/library/ctypes.rst
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11
