Repository python/cpython, pull requests merged in 2023-02, with the labels that each got.

#101483 [3.11] gh-98657: [docs] `array.typecodes` is a module-level attribute (GH-98729)
  Doc/library/array.rst
Labels: docs, awaiting merge, skip news

#101484 [3.10] gh-98657: [docs] `array.typecodes` is a module-level attribute (GH-98729)
  Doc/library/array.rst
Labels: docs, awaiting merge, skip news

#101302 gh-101277: Isolate itertools, add group and _grouper types to module state
  Lib/test/test_itertools.py
  Modules/clinic/itertoolsmodule.c.h
  Modules/itertoolsmodule.c
Labels: awaiting merge, skip news

#101455 gh-101454: fix documentation for END_ASYNC_FOR
  Doc/library/dis.rst
Labels: docs, expert-asyncio, awaiting merge, skip news, needs backport to 3.11

#101493 [3.11] gh-101454: fix documentation for END_ASYNC_FOR (#101455)
  Doc/library/dis.rst
Labels: docs, awaiting core review, skip news

#101499 gh-101498 : Updated Doc/library/asyncio-task.rst#timeout
  Doc/library/asyncio-task.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11

#101501 [3.11] gh-101498 : Fix asyncio.Timeout example in docs (GH-101499)
  Doc/library/asyncio-task.rst
Labels: docs, awaiting merge, skip news

#101488 gh-98831: Modernize the LOAD_ATTR family
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news

#101502 gh-98831: Modernize the LOAD_GLOBAL family
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news

#101504 [3.11] gh-101467: Correct py.exe handling of prefix matches and cases when only one runtime is installed (GH-101468)
  Doc/using/windows.rst
  Lib/test/test_launcher.py
  Misc/NEWS.d/next/Windows/2023-01-31-16-50-07.gh-issue-101467.ye9t-L.rst
  PC/launcher2.c
Labels: awaiting merge

#101351 Docs: improve accuracy of sqlite3 `check_same_thread` parameter
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting review, skip news, needs backport to 3.10, needs backport to 3.11

#101513 [3.10] Docs: improve accuracy of sqlite3 `check_same_thread` parameter (GH-101351)
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting merge, skip news

#101512 [3.11] Docs: improve accuracy of sqlite3 `check_same_thread` parameter (GH-101351)
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting merge, skip news

#101511 gh-98831: rewrite RERAISE and CLEANUP_THROW in the instruction definition DSL
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news, interpreter-core

#101507 docs: Fix enum reassign `str` documentation
  Doc/library/enum.rst
Labels: docs, skip issue, awaiting merge, skip news, 3.11, 3.12, needs backport to 3.11

#96429 gh-96305: Fix AIX build by avoiding subprocess during bootstrap
  Lib/_aix_support.py
  Misc/NEWS.d/next/Build/2022-08-30-10-16-31.gh-issue-96305.274i8B.rst
Labels: awaiting merge

#98768 gh-98705: Fix AIX build
  Include/pyport.h
  Misc/NEWS.d/next/Build/2022-10-27-09-57-12.gh-issue-98705.H11XmR.rst
Labels: awaiting merge

#101518 [3.11] docs: Fix enum reassign `str` documentation (GH-101507)
  Doc/library/enum.rst
Labels: docs, skip issue, awaiting merge, skip news

#100618 GH-84559: Deprecate fork being the multiprocessing default.
  Doc/library/concurrent.futures.rst
  Doc/library/multiprocessing.rst
  Doc/whatsnew/3.12.rst
  Lib/compileall.py
  Lib/concurrent/futures/process.py
  Lib/multiprocessing/context.py
  Lib/test/_test_multiprocessing.py
  Lib/test/_test_venv_multiprocessing.py
  Lib/test/test_asyncio/test_events.py
  Lib/test/test_concurrent_futures.py
  Lib/test/test_fcntl.py
  Lib/test/test_logging.py
  Lib/test/test_multiprocessing_defaults.py
  Lib/test/test_pickle.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2023-01-01-01-19-33.gh-issue-84559.zEjsEJ.rst
Labels: awaiting merge, stdlib, expert-multiprocessing

#101485 gh-100925: Move array methods under class in array doc
  Doc/library/array.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#101528 [3.10] gh-100925: Move array methods under class in array doc (GH-101485)
  Doc/library/array.rst
Labels: docs, awaiting merge, skip news

#101527 [3.11] gh-100925: Move array methods under class in array doc (GH-101485)
  Doc/library/array.rst
Labels: docs, awaiting merge, skip news

#101530 gh-84559: skip the test when no multiprocessing (wasm, etc)
  Lib/test/test_multiprocessing_defaults.py
Labels: tests, awaiting core review, skip news

#101514 gh-100920: Update documentation for asyncio wait_close
  Doc/library/asyncio-stream.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#101506 fix(tutorial,venv): replace PyPI description with link
  Doc/tutorial/venv.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#101533 [3.10] gh-100920: Update documentation for `asyncio.StreamWriter.wait_closed` (GH-101514)
  Doc/library/asyncio-stream.rst
Labels: docs, awaiting merge, skip news

#101532 [3.11] gh-100920: Update documentation for `asyncio.StreamWriter.wait_closed` (GH-101514)
  Doc/library/asyncio-stream.rst
Labels: docs, awaiting merge, skip news

#101535 [3.10] docs: replace PyPI description with link (GH-101506)
  Doc/tutorial/venv.rst
Labels: docs, skip issue, awaiting merge, skip news

#101534 [3.11] docs: replace PyPI description with link (GH-101506)
  Doc/tutorial/venv.rst
Labels: docs, skip issue, awaiting merge, skip news

#101303 gh-101277: Isolate itertools, part 2/4
  Modules/clinic/itertoolsmodule.c.h
  Modules/itertoolsmodule.c
Labels: awaiting merge, skip news

#101516 gh-98831: rewrite SEND, GET_YIELD_FROM_ITER, RETURN_GENERATOR in the instruction definition DSL
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news, interpreter-core

#101529 gh-98831: rewrite MAKE_FUNCTION and BUILD_SLICE in the instruction definition DSL
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news, interpreter-core

#101523 gh-101522: Allow overriding Windows dependencies versions and paths using MSBuild properties
  Misc/NEWS.d/next/Build/2023-02-02-23-43-46.gh-issue-101522.lnUDta.rst
  PCbuild/python.props
  PCbuild/tcltk.props
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#101546 [3.11] gh-101522: Allow overriding Windows dependencies versions and paths using MSBuild properties (GH-101523)
  Misc/NEWS.d/next/Build/2023-02-02-23-43-46.gh-issue-101522.lnUDta.rst
  PCbuild/python.props
  PCbuild/tcltk.props
Labels: awaiting core review

#101547 [3.10] gh-101522: Allow overriding Windows dependencies versions and paths using MSBuild properties (GH-101523)
  Misc/NEWS.d/next/Build/2023-02-02-23-43-46.gh-issue-101522.lnUDta.rst
  PCbuild/python.props
  PCbuild/tcltk.props
Labels: awaiting core review

#101551 gh-84559: Remove the new multiprocessing warning, too disruptive.
  Doc/library/concurrent.futures.rst
  Doc/library/multiprocessing.rst
  Doc/whatsnew/3.12.rst
  Lib/concurrent/futures/process.py
  Lib/multiprocessing/context.py
  Lib/test/_test_multiprocessing.py
  Lib/test/test_concurrent_futures.py
  Lib/test/test_logging.py
  Lib/test/test_multiprocessing_defaults.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2023-01-01-01-19-33.gh-issue-84559.zEjsEJ.rst
Labels: awaiting core review, stdlib, 3.12

#101526 gh-101524: Split Up the _xxsubinterpreters Module
  Lib/test/support/interpreters.py
  Lib/test/test__xxinterpchannels.py
  Lib/test/test__xxsubinterpreters.py
  Lib/test/test_interpreters.py
  Modules/Setup
  Modules/Setup.stdlib.in
  Modules/_testcapimodule.c
  Modules/_xxinterpchannelsmodule.c
  Modules/_xxsubinterpretersmodule.c
  PC/config.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Tools/build/generate_stdlib_module_names.py
  configure
  configure.ac
Labels: awaiting core review, skip news

#101347 code.rst: add missing versionadded comment
  Doc/c-api/code.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11

#101553 [3.11] Add missing `versionadded` directive for `PyCode_Addr2Location` (GH-101347)
  Doc/c-api/code.rst
Labels: docs, skip issue, awaiting merge, skip news

#101157 GH-56426: Add cross-reference to the documentation for faulthandler, traceback, and pdb.
  Doc/library/faulthandler.rst
  Doc/library/pdb.rst
  Doc/library/traceback.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#101554 [3.11] GH-56426: Add cross-reference to the documentation for faulthandler, traceback, and pdb. (GH-101157)
  Doc/library/faulthandler.rst
  Doc/library/pdb.rst
  Doc/library/traceback.rst
Labels: docs, awaiting merge, skip news

#101555 [3.10] GH-56426: Add cross-reference to the documentation for faulthandler, traceback, and pdb. (GH-101157)
  Doc/library/faulthandler.rst
  Doc/library/pdb.rst
  Doc/library/traceback.rst
Labels: docs, awaiting merge, skip news

#101557 gh-101282: Update BOLT --split-functions flag not to use deprecated u…
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2023-02-04-06-59-07.gh-issue-101282.7sQz5l.rst
Labels: awaiting core review

#101323 gh-101322: Ensure test_zlib.ZlibDecompressorTest runs, fix errors in ZlibDecompressor
  Lib/test/test_zlib.py
  Misc/NEWS.d/next/Library/2023-01-26-06-44-35.gh-issue-101323.h8Hk11.rst
  Modules/zlibmodule.c
Labels: awaiting merge

#101340 [3.10] [3.11] gh-99952: fix refcount issues in ctypes.Structure from_param() result (GH-101339)
  Lib/ctypes/test/test_parameters.py
  Misc/NEWS.d/next/Library/2022-12-11-14-38-59.gh-issue-99952.IYGLzr.rst
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/_ctypes_test.c
Labels: type-bug, awaiting review, :robot: automerge

#101567 GH-100485: Create an alternative code path when an accurate fma() implementation is not available
  Lib/test/test_math.py
  Modules/mathmodule.c
Labels: awaiting core review, skip news

#101540 Fix detection of presence of time.tzset (gh-101539)
  Lib/test/datetimetester.py
Labels: awaiting core review, skip news

#101548 Add missing preposition
  Doc/library/argparse.rst
Labels: docs, skip issue, awaiting merge, skip news

#101222 gh-101221: Add options in the documentation of timeit command
  Doc/library/timeit.rst
Labels: docs, awaiting merge, skip news

#101394 gh-101266: Fix __sizeof__ for subclasses of int
  Lib/test/test_long.py
  Misc/NEWS.d/next/Core and Builtins/2023-01-28-13-11-52.gh-issue-101266.AxV3OF.rst
  Objects/boolobject.c
  Objects/longobject.c
Labels: awaiting merge, needs backport to 3.11

#101579 [3.11] gh-101266: Fix __sizeof__ for subclasses of int (GH-101394)
  Lib/test/test_long.py
  Misc/NEWS.d/next/Core and Builtins/2023-01-28-13-11-52.gh-issue-101266.AxV3OF.rst
  Objects/boolobject.c
  Objects/longobject.c
Labels: awaiting core review

#101580 Revert "gh-89381: Fix invalid signatures of math/cmath.log (#101404)"
  Doc/library/cmath.rst
  Doc/library/math.rst
  Lib/test/test_math.py
  Misc/NEWS.d/next/Library/2023-01-16-10-42-58.gh-issue-89381.lM2WL0.rst
  Modules/clinic/cmathmodule.c.h
  Modules/clinic/mathmodule.c.h
  Modules/cmathmodule.c
  Modules/mathmodule.c
Labels: awaiting core review

#5561 gh-76961: Fix the PEP3118 format string for ctypes.Structure
  Doc/library/ctypes.rst
  Lib/test/test_ctypes/test_pep3118.py
  Misc/NEWS.d/next/Core and Builtins/2018-02-05-21-54-46.bpo-32780.Dtiz8z.rst
  Modules/_ctypes/stgdict.c
Labels: type-bug, awaiting merge

#7032 bpo-33591: Fix CDLL to accept PathLike objects
  Doc/library/ctypes.rst
  Lib/ctypes/__init__.py
  Lib/test/test_ctypes/test_loading.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2018-05-21-17-18-00.gh-issue-77772.Fhg84L.rst
Labels: awaiting merge, expert-ctypes, stdlib

#101572 gh-101334: Don't force USTAR format in test_tarfile.
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Tests/2023-02-04-17-24-33.gh-issue-101334._yOqwg.rst
Labels: tests, awaiting merge, needs backport to 3.10, needs backport to 3.11

#101583 [3.10] gh-101334: Don't force USTAR format in test_tarfile. (GH-101572)
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Tests/2023-02-04-17-24-33.gh-issue-101334._yOqwg.rst
Labels: tests, awaiting merge

#101584 [3.11] gh-101334: Don't force USTAR format in test_tarfile. (GH-101572)
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Tests/2023-02-04-17-24-33.gh-issue-101334._yOqwg.rst
Labels: tests, awaiting merge

#100164 Trivial Change: Remove unhelpful doc in `datetime.timedelta`
  Lib/datetime.py
Labels: skip issue, awaiting merge, skip news

#101590 gh-101541: [Enum] create flag psuedo-member without calling original __new__
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2023-02-05-14-39-49.gh-issue-101541.Mo3ppp.rst
Labels: type-bug, awaiting core review, stdlib, 3.11, 3.12, needs backport to 3.11

#101596 [3.11] gh-101541: [Enum] create flag psuedo-member without calling original __new__ (GH-101590)
  Lib/enum.py
  Lib/test/test_enum.py
  Misc/NEWS.d/next/Library/2023-02-05-14-39-49.gh-issue-101541.Mo3ppp.rst
Labels: type-bug, awaiting merge

#101388 gh-101372: Fix unicodedata.is_normalized to properly handle the UCD 3…
  Misc/NEWS.d/next/Core and Builtins/2023-01-28-20-31-42.gh-issue-101372.8BcpCC.rst
  Modules/unicodedata.c
Labels: needs backport to 3.10, needs backport to 3.11

#101597 [3.11] gh-101372: Fix unicodedata.is_normalized to properly handle the UCD 3… (gh-101388)
  Misc/NEWS.d/next/Core and Builtins/2023-01-28-20-31-42.gh-issue-101372.8BcpCC.rst
  Modules/unicodedata.c
Labels: awaiting merge

#101598 [3.10] gh-101372: Fix unicodedata.is_normalized to properly handle the UCD 3… (gh-101388)
  Misc/NEWS.d/next/Core and Builtins/2023-01-28-20-31-42.gh-issue-101372.8BcpCC.rst
  Modules/unicodedata.c
Labels: awaiting merge

#101587 gh-76961: Possible fix for buildbot failures in test_pep3118
  Lib/test/test_ctypes/test_pep3118.py
  Modules/_ctypes/stgdict.c
Labels: tests, awaiting core review, skip news

#101544 gh-101543: Ensure Windows registry path is only used when stdlib can't be found
  Misc/NEWS.d/next/Windows/2023-02-03-17-53-06.gh-issue-101543.cORAT4.rst
  Modules/getpath.py
Labels: OS-windows, awaiting core review, needs backport to 3.11

#101606 [3.11] gh-101543: Ensure Windows registry path is only used when stdlib can't be found (GH-101544)
  Misc/NEWS.d/next/Windows/2023-02-03-17-53-06.gh-issue-101543.cORAT4.rst
  Modules/getpath.py
Labels: awaiting merge

#101563 gh-101562: add tests for inheritance with NotRequired & Required in p…
  Lib/test/test_typing.py
  Misc/ACKS
Labels: tests, awaiting merge, skip news, expert-typing, needs backport to 3.11

#101611 [3.11] gh-101562: typing: add tests for inheritance with NotRequired & Required in parent fields (GH-101563)
  Lib/test/test_typing.py
  Misc/ACKS
Labels: awaiting merge, skip news

#101610 gh-101609: Fix "‘state’ may be used uninitialized" warning in `_xxinterpchannelsmodule`
  Modules/_xxinterpchannelsmodule.c
Labels: awaiting merge, skip news, :robot: automerge

#101431 gh-59956: Partial Fix for GILState API Compatibility with Subinterpreters
  Misc/NEWS.d/next/Core and Builtins/2023-01-30-11-56-09.gh-issue-59956.7xqnC_.rst
  Python/pystate.c
Labels: awaiting core review

#101617 GH-101616: Mention the Docs Discourse forum in the "reporting docs issues"
  Doc/bugs.rst
Labels: docs, awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#101621 [3.11] GH-101616: Mention the Docs Discourse forum in the "reporting docs issues" (GH-101617)
  Doc/bugs.rst
Labels: docs, awaiting merge, skip news

#101622 [3.10] GH-101616: Mention the Docs Discourse forum in the "reporting docs issues" (GH-101617)
  Doc/bugs.rst
Labels: docs, awaiting merge, skip news

#101620 gh-98831: rewrite COPY and SWAP in the instruction definition DSL
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news, interpreter-core

#101625 gh-59956: Add a Test to Verify GILState Matches the "Current" Thread State
  Lib/test/test_capi/test_misc.py
  Modules/_testcapimodule.c
Labels: awaiting core review, skip news

#99109 gh-99108: Import SHA2-224 and SHA2-256 from HACL*
  Lib/test/test_hashlib.py
  Makefile.pre.in
  Misc/NEWS.d/next/Security/2022-11-08-12-06-52.gh-issue-99108.4Wrsuh.rst
  Modules/Setup.stdlib.in
  Modules/_hacl/Hacl_Streaming_SHA2.c
  Modules/_hacl/Hacl_Streaming_SHA2.h
  Modules/_hacl/README.md
  Modules/_hacl/include/krml/FStar_UInt_8_16_32_64.h
  Modules/_hacl/include/krml/internal/target.h
  Modules/_hacl/include/krml/lowstar_endianness.h
  Modules/_hacl/include/python_hacl_namespaces.h
  Modules/_hacl/internal/Hacl_SHA2_Generic.h
  Modules/_hacl/refresh.sh
  Modules/sha256module.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  configure
  configure.ac
Labels: awaiting merge, extension-modules, 3.12

#101629 gh-98831: Move DSL documentation here from ideas repo
  Tools/cases_generator/README.md
  Tools/cases_generator/interpreter_definition.md
Labels: awaiting core review, skip news

#100270 gh-85747: Active voice & suggested edits, 'running/stopping loop' & 'callbacks' subsections of asyncio-eventloop.rst
  Doc/library/asyncio-eventloop.rst
Labels: docs, awaiting changes, skip news, needs backport to 3.10, needs backport to 3.11

#101127 gh-101072: support default and kw default in PyEval_EvalCodeEx for 3.11+
  Lib/test/test_capi/test_eval_code_ex.py
  Misc/NEWS.d/next/Core and Builtins/2023-02-06-20-13-36.gh-issue-92173.RQE0mk.rst
  Modules/_testcapimodule.c
  Objects/funcobject.c
  Python/ceval.c
Labels: awaiting merge, release-blocker

#101638 [3.11] gh-101266: Revert fix __sizeof__ for subclasses of int
  Lib/test/test_long.py
  Misc/NEWS.d/next/Core and Builtins/2023-01-28-13-11-52.gh-issue-101266.AxV3OF.rst
  Objects/boolobject.c
  Objects/longobject.c
Labels: awaiting core review

#101642 Doctest: Pin sphinxext-opengraph==0.7.5 to prevent importing NumPy
  Doc/requirements.txt
Labels: skip issue, awaiting core review, skip news

#101637 Fix nesting of 'Pending Removal in Python 3.14'
  Doc/whatsnew/3.12.rst
Labels: docs, skip issue, awaiting merge, skip news

#101626 gh-98831: Modernize the FOR_ITER family of instructions
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news

#101645 Make use of TESTFN_ASCII in test_fileio
  Lib/test/test_fileio.py
Labels: tests, skip issue, awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#101652 gh-97725: Fix documentation for the default file of `Task.print_stack`
  Doc/library/asyncio-task.rst
  Misc/NEWS.d/next/Documentation/2023-02-07-21-43-24.gh-issue-97725.cuY7Cd.rst
Labels: docs, expert-asyncio, awaiting merge, needs backport to 3.10, needs backport to 3.11

#101641 gh-98831: rewrite UNPACK_EX, UNPACK_SEQUENCE, UNPACK_SEQUENCE_TWO_TUPLE in the instruction definition DSL
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
Labels: awaiting merge, skip news, interpreter-core

#101657 gh-101656: Fix "conversion from Py_ssize_t to int" warning in `_testcapimodule`
  Modules/_testcapimodule.c
Labels: awaiting review, skip news, needs backport to 3.11

#101633 gh-101632: Add a RETURN_CONST instruction
  Doc/library/dis.rst
  Include/internal/pycore_opcode.h
  Include/opcode.h
  Lib/dis.py
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Lib/test/test_ast.py
  Lib/test/test_code.py
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Lib/test/test_peepholer.py
  Misc/NEWS.d/next/Core and Builtins/2023-02-07-14-56-43.gh-issue-101632.Fd1yxk.rst
  Objects/frameobject.c
  Programs/test_frozenmain.h
  Python/bytecodes.c
  Python/compile.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
  Python/opcode_targets.h
Labels: performance, awaiting merge, interpreter-core

#101666 gh-98831: Finish the UNPACK_SEQUENCE family
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/test_generator.py
Labels: awaiting merge, skip news

#101628 gh-98831: Modernize FORMAT_VALUE
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
  Tools/cases_generator/parser.py
  Tools/cases_generator/test_generator.py
Labels: awaiting merge, skip news

#101661 gh-101446: Change `repr` of `collections.OrderedDict`
  Lib/collections/__init__.py
  Lib/test/test_ordered_dict.py
  Misc/NEWS.d/next/Library/2023-02-07-22-21-46.gh-issue-101446.-c0FdK.rst
  Objects/odictobject.c
Labels: awaiting review

#101627 gh-98831: Modernize CALL_FUNCTION_EX
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/opcode_metadata.h
  Tools/cases_generator/generate_cases.py
  Tools/cases_generator/test_generator.py
Labels: awaiting merge, skip news

#93070 gh-47937: Note that Popen attributes are read-only
  Doc/library/subprocess.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#101607 GH-101578: Normalize the current exception
  Doc/c-api/exceptions.rst
  Doc/data/stable_abi.dat
  Include/cpython/pyerrors.h
  Include/cpython/pystate.h
  Include/internal/pycore_pyerrors.h
  Include/pyerrors.h
  Lib/test/test_capi/test_misc.py
  Lib/test/test_exceptions.py
  Lib/test/test_stable_abi_ctypes.py
  Misc/NEWS.d/next/C API/2023-02-06-16-14-30.gh-issue-101578.PW5fA9.rst
  Misc/stable_abi.toml
  Modules/_testcapi/heaptype.c
  Modules/_testcapimodule.c
  Modules/gcmodule.c
  Objects/dictobject.c
  Objects/exceptions.c
  Objects/object.c
  PC/python3dll.c
  Parser/pegen.c
  Python/bytecodes.c
  Python/ceval.c
  Python/errors.c
  Python/generated_cases.c.h
  Python/import.c
  Python/initconfig.c
  Python/pystate.c
  Python/pythonrun.c
  Python/sysmodule.c
  Python/traceback.c
Labels: awaiting merge

#101680 [3.11] gh-101656: Fix "conversion from Py_ssize_t to int" warning in …
  Modules/_testcapimodule.c
Labels: awaiting review, skip news

#101653 [3.11] gh-97725: Fix documentation for the default file of `asyncio.Task.print_stack` (#101652)
  Doc/library/asyncio-task.rst
  Misc/NEWS.d/next/Documentation/2023-02-07-21-43-24.gh-issue-97725.cuY7Cd.rst
Labels: docs, awaiting review

#101654 [3.10] gh-97725: Fix documentation for the default file of `asyncio.Task.print_stack` (#101652)
  Doc/library/asyncio-task.rst
  Misc/NEWS.d/next/Documentation/2023-02-07-21-43-24.gh-issue-97725.cuY7Cd.rst
Labels: docs, awaiting review

#101683 [3.10] gh-47937: Note that Popen attributes are read-only (GH-93070)
  Doc/library/subprocess.rst
Labels: docs, awaiting merge, skip news

#101651 [3.10] Fix MSI build PlatformToolset detection
  Tools/msi/bundle/bootstrap/pythonba.vcxproj
Labels: OS-windows, skip issue, awaiting core review, skip news

#101650 [3.11] Make use of TESTFN_ASCII in test_fileio (GH-101645)
  Lib/test/test_fileio.py
Labels: tests, skip issue, awaiting merge, skip news

#101646 [3.11] gh-96127: Fix `inspect.signature` call on mocks (#96335)
  Lib/test/test_inspect.py
  Lib/unittest/mock.py
  Misc/NEWS.d/next/Library/2022-08-27-10-35-50.gh-issue-96127.8RdLre.rst
Labels: awaiting core review

#101630 [3.8] gh-95778: add doc missing in some places (GH-100627)
  Misc/python.man
Labels: awaiting merge, skip news, :robot: automerge

#100934 gh-100933: Improve `check_element` helper in `test_xml_etree`
  Lib/test/test_xml_etree.py
Labels: tests, awaiting review, skip news, needs backport to 3.10, needs backport to 3.11

#101686 [3.11] gh-100933: Improve `check_element` helper in `test_xml_etree` (GH-100934)
  Lib/test/test_xml_etree.py
Labels: tests, awaiting review, skip news

#101687 [3.10] gh-100933: Improve `check_element` helper in `test_xml_etree` (GH-100934)
  Lib/test/test_xml_etree.py
Labels: tests, awaiting review, skip news

#101615 gh-101614: don't treat python3_d.dll as a Python dll
  Misc/NEWS.d/next/Windows/2023-02-07-18-22-54.gh-issue-101614.NjVP0n.rst
  Python/dynload_win.c
Labels: OS-windows, awaiting review, needs backport to 3.10, needs backport to 3.11

#101324 gh-101196: Make isdir/isfile/exists faster on Windows
  Include/pyport.h
  Lib/genericpath.py
  Lib/ntpath.py
  Lib/posixpath.py
  Lib/test/test_ntpath.py
  Lib/test/test_os.py
  Misc/NEWS.d/next/Windows/2023-01-25-11-33-54.gh-issue-101196.wAX_2g.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting merge, 3.12

#101691 [3.10] gh-101614: Don't treat python3_d.dll as a Python DLL when checking extension modules for incompatibility (GH-101615)
  Misc/NEWS.d/next/Windows/2023-02-07-18-22-54.gh-issue-101614.NjVP0n.rst
  Python/dynload_win.c
Labels: awaiting merge

#101690 [3.11] gh-101614: Don't treat python3_d.dll as a Python DLL when checking extension modules for incompatibility (GH-101615)
  Misc/NEWS.d/next/Windows/2023-02-07-18-22-54.gh-issue-101614.NjVP0n.rst
  Python/dynload_win.c
Labels: awaiting merge

#101672 gh-101670: typo fix in PyImport_AppendInittab()
  Python/import.c
Labels: awaiting merge, skip news, :robot: automerge, needs backport to 3.10, needs backport to 3.11

#101697 GH-101696: invalidate type version tag in `_PyStaticType_Dealloc `
  Misc/NEWS.d/next/Core and Builtins/2023-02-08-17-13-31.gh-issue-101696.seJhTt.rst
  Objects/typeobject.c
Labels: type-bug, awaiting merge, interpreter-core, needs backport to 3.11

#101508 gh-98831: Modernize CALL and family
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/generated_cases.c.h
  Python/opcode_metadata.h
  Tools/cases_generator/generate_cases.py
Labels: awaiting merge, skip news

#101304 gh-101277: Isolate itertools, part 3/4
  Modules/clinic/itertoolsmodule.c.h
  Modules/itertoolsmodule.c
Labels: awaiting merge, skip news

#101286 gh-101283: Try to load the fallback cmd.exe by an absolute path
  Doc/library/subprocess.rst
  Lib/subprocess.py
  Misc/NEWS.d/next/Security/2023-01-24-16-12-00.gh-issue-101283.9tqu39.rst
Labels: type-security, awaiting merge, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#101712 gh-101283: Fix use of unbound variable
  Lib/subprocess.py
Labels: awaiting core review, skip news

#101711 [3.11] gh-101283: Improved fallback logic for subprocess with shell=True on Windows (GH-101286)
  Doc/library/subprocess.rst
  Lib/subprocess.py
  Misc/NEWS.d/next/Security/2023-01-24-16-12-00.gh-issue-101283.9tqu39.rst
Labels: type-security, awaiting merge

#101708 [3.10] gh-101283: Improved fallback logic for subprocess with shell=True on Windows (GH-101286)
  Doc/library/subprocess.rst
  Lib/subprocess.py
  Misc/NEWS.d/next/Security/2023-01-24-16-12-00.gh-issue-101283.9tqu39.rst
Labels: type-security, awaiting merge

#101719 gh-101283: Version was just released, so should be changed in 3.11.3
  Doc/library/subprocess.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.11

#101721 [3.11] gh-101283: Version was just released, so should be changed in 3.11.3 (GH-101719)
  Doc/library/subprocess.rst
Labels: docs, awaiting merge, skip news

#101704 gh-98831: Use opcode metadata for stack_effect()
  Makefile.pre.in
  Python/compile.c
  Python/opcode_metadata.h
  Tools/cases_generator/generate_cases.py
Labels: awaiting merge, skip news

#92365 gh-85984: Remove legacy Lib/pty.py code.
  Doc/whatsnew/3.12.rst
  Lib/pty.py
  Misc/NEWS.d/next/Library/2023-02-05-21-40-15.gh-issue-85984.Kfzbb2.rst
Labels: sprint, awaiting merge, stdlib, 3.12

#101679 gh-101678: refactor the math module to use special functions from c11
  Modules/_math.h
  Modules/mathmodule.c
Labels: awaiting merge, skip news, :robot: automerge, extension-modules

#101730 gh-101678: Merge math_1_to_whatever() and math_1()
  Modules/mathmodule.c
Labels: awaiting merge, skip news

#101709 [3.9] gh-101283: Improved fallback logic for subprocess with shell=True on Windows (GH-101286)
  Doc/library/subprocess.rst
  Lib/subprocess.py
  Misc/NEWS.d/next/Security/2023-01-24-16-12-00.gh-issue-101283.9tqu39.rst
Labels: type-security, awaiting merge

#101713 [3.7] gh-101283: Improved fallback logic for subprocess with shell=True on Windows (GH-101286)
  Doc/library/subprocess.rst
  Lib/subprocess.py
  Misc/NEWS.d/next/Security/2023-01-24-16-12-00.gh-issue-101283.9tqu39.rst
Labels: type-security, awaiting core review

#101731 no-issue: Add Dong-hee Na as the cjkcodecs codeowner
  .github/CODEOWNERS
Labels: skip issue, awaiting merge, skip news

#101736 GH-99293: Document that `Py_TPFLAGS_VALID_VERSION_TAG` shouldn't be used.
  Doc/c-api/typeobj.rst
  Misc/NEWS.d/next/C API/2023-02-09-10-38-20.gh-issue-99293.mFqfpp.rst
Labels: docs, awaiting change review

#101723 gh-101670: typo fix in PyImport_ExtendInittab()
  Python/import.c
Labels: awaiting merge, skip news

#101743 LibFFI build requires x64 Cygwin, and skip the ARM build
  PCbuild/prepare_libffi.bat
Labels: skip issue, awaiting core review, skip news

#101728 gh-101283: Fix the `versionchanged` of gh-101283 (3.12 only)
  Doc/library/subprocess.rst
Labels: docs, awaiting merge, skip news

#101727 gh-101726: Update the OpenSSL version to 1.1.1t
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
  .github/workflows/build.yml
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/Security/2023-02-08-22-03-04.gh-issue-101727.9P5eZz.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
  Tools/ssl/multissltests.py
Labels: awaiting core review, needs backport to 3.7, needs backport to 3.8, needs backport to 3.9, needs backport to 3.10, needs backport to 3.11

#101600 Fix typo in test_fstring.py
  Lib/test/test_fstring.py
Labels: tests, skip issue, awaiting core review, skip news

#101227 GH-101228: Fix typo in docstring for read method of _io.TextIOWrapper class
  Modules/_io/textio.c
Labels: awaiting review, skip news

#101749 [3.11] gh-101726: Update the OpenSSL version to 1.1.1t (GH-101727)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
  .github/workflows/build.yml
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/Security/2023-02-08-22-03-04.gh-issue-101727.9P5eZz.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
  Tools/ssl/multissltests.py
Labels: awaiting merge

#101750 [3.10] gh-101726: Update the OpenSSL version to 1.1.1t (GH-101727)
  .azure-pipelines/ci.yml
  .azure-pipelines/pr.yml
  .github/workflows/build.yml
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/Security/2023-02-08-22-03-04.gh-issue-101727.9P5eZz.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
  Tools/ssl/multissltests.py
Labels: awaiting merge

#101745 gh-101430: Update tracemalloc to handle presize properly.
  Misc/NEWS.d/next/Core and Builtins/2023-02-10-01-15-57.gh-issue-101430.T3Gegb.rst
  Modules/_tracemalloc.c
  Objects/object.c
Labels: awaiting merge

#101748 gh-101747: Fix refleak in new `OrderedDict` repr
  Objects/odictobject.c
Labels: awaiting merge, skip news

#101757 Fix some typos in asdl_c.py
  Parser/asdl_c.py
Labels: skip issue, awaiting merge, skip news

#101761 gh-101759: Update macOS installer to SQLite 3.40.1
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2023-02-09-22-07-17.gh-issue-101759.B0JP2H.rst
Labels: awaiting merge, needs backport to 3.10, needs backport to 3.11

#101775 [3.11] gh-101759: Update macOS installer to SQLite 3.40.1 (GH-101761)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2023-02-09-22-07-17.gh-issue-101759.B0JP2H.rst
Labels: awaiting merge

#101776 [3.10] gh-101759: Update macOS installer to SQLite 3.40.1 (GH-101761)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2023-02-09-22-07-17.gh-issue-101759.B0JP2H.rst
Labels: awaiting merge

#101305 gh-101277: Finalise isolating itertools
  Misc/NEWS.d/next/Library/2023-01-25-00-14-52.gh-issue-101277.FceHX7.rst
  Modules/clinic/itertoolsmodule.c.h
  Modules/itertoolsmodule.c
  Tools/c-analyzer/cpython/globals-to-fix.tsv
Labels: awaiting merge, :robot: automerge

#101762 gh-101759: Update Windows installer to SQLite 3.40.1
  Misc/NEWS.d/next/Windows/2023-02-09-22-09-27.gh-issue-101759.zFlqSH.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
  PCbuild/readme.txt
Labels: awaiting core review, needs backport to 3.10, needs backport to 3.11

#101787 gh-101517: bdb should not lookup linecache with lineno=None
  Lib/bdb.py
  Lib/test/test_bdb.py
  Misc/NEWS.d/next/Library/2023-02-10-16-02-29.gh-issue-101517.r7S2u8.rst
Labels: type-bug, awaiting merge, needs backport to 3.10, stdlib, needs backport to 3.11

#101784 gh-101763: Update bundled copy of libffi to 3.4.4 on Windows
  Misc/NEWS.d/next/Windows/2023-02-10-14-26-05.gh-issue-101763.RPaj7r.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: OS-windows, awaiting core review, needs backport to 3.11

#101794 [3.10] gh-101517: make bdb avoid looking up in linecache with lineno=None (GH-101787)
  Lib/bdb.py
  Lib/test/test_bdb.py
  Misc/NEWS.d/next/Library/2023-02-10-16-02-29.gh-issue-101517.r7S2u8.rst
Labels: type-bug, awaiting merge, :robot: automerge

#101793 [3.11] gh-101517: make bdb avoid looking up in linecache with lineno=None (GH-101787)
  Lib/bdb.py
  Lib/test/test_bdb.py
  Misc/NEWS.d/next/Library/2023-02-10-16-02-29.gh-issue-101517.r7S2u8.rst
Labels: type-bug, awaiting merge, :robot: automerge

#101795 [3.11] gh-101763: Update bundled copy of libffi to 3.4.4 on Windows (GH-101784)
  Misc/NEWS.d/next/Windows/2023-02-10-14-26-05.gh-issue-101763.RPaj7r.rst
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: awaiting merge

#101782 Docs: use parameter list for sqlite3.Cursor.execute*
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11

#101803 [3.11] Docs: use parameter list for sqlite3.Cursor.execute* (GH-101782)
  Doc/library/sqlite3.rst
Labels: docs, skip issue, awaiting merge, skip news
