Repository python/cpython, pull requests merged in 2024-12, with the labels that each got.

#127199 gh-127165: Disallow embedded NULL characters in `_interpreters`
  Lib/test/test_interpreters/test_api.py
  Python/crossinterp.c
Labels: awaiting merge, skip news, needs backport to 3.13

#127462 Add the missing `f` on an f-string error message in multiprocessing.
  Lib/multiprocessing/connection.py
Labels: skip issue, awaiting merge, skip news, stdlib, needs backport to 3.12, needs backport to 3.13

#127463 [3.13] gh-127165: Disallow embedded NULL characters in `_interpreters` (GH-127199)
  Lib/test/test_interpreters/test_api.py
  Python/crossinterp.c
Labels: awaiting merge, skip news

#127464 [3.13] Add the missing `f` on an f-string error message in multiprocessing. (GH-127462)
  Lib/multiprocessing/connection.py
Labels: skip issue, awaiting review, skip news

#127465 [3.12] Add the missing `f` on an f-string error message in multiprocessing. (GH-127462)
  Lib/multiprocessing/connection.py
Labels: skip issue, awaiting review, skip news

#127460 [3.13] Docs: Fix incorrect indents in `c-api/type.rst` (GH-127449)
  Doc/c-api/type.rst
Labels: docs, skip issue, awaiting merge, skip news

#127461 [3.12] Docs: Fix incorrect indents in `c-api/type.rst` (GH-127449)
  Doc/c-api/type.rst
Labels: docs, skip issue, awaiting merge, skip news

#127357 gh-127356: Fix prepend doctrees directory for gettext target
  Doc/Makefile
Labels: awaiting review, skip news, needs backport to 3.12, needs backport to 3.13

#127470 [3.13] gh-127356: Fix prepend doctrees directory for gettext target (GH-127357)
  Doc/Makefile
Labels: awaiting review, skip news

#127471 [3.12] gh-127356: Fix prepend doctrees directory for gettext target (GH-127357)
  Doc/Makefile
Labels: awaiting review, skip news

#127457 gh-127321: Avoid stopping at an opcode without an associated line number for breakpoint()
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2024-11-30-21-46-15.gh-issue-127321.M78fBv.rst
Labels: awaiting merge

#127485 gh-119786: cleanup internal docs and fix internal links
  InternalDocs/README.md
  InternalDocs/adaptive.md
  InternalDocs/changing_grammar.md
  InternalDocs/compiler.md
  InternalDocs/exception_handling.md
  InternalDocs/frames.md
  InternalDocs/garbage_collector.md
  InternalDocs/generators.md
  InternalDocs/interpreter.md
  InternalDocs/parser.md
  InternalDocs/string_interning.md
Labels: awaiting merge, skip news

#126900 gh-126899: Add `**kw` to `tkinter.Misc.after` and `tkinter.Misc.after_idle`
  Doc/whatsnew/3.14.rst
  Lib/test/test_tkinter/test_misc.py
  Lib/tkinter/__init__.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2024-11-16-10-52-48.gh-issue-126899.GFnfBt.rst
Labels: awaiting merge

#127487 [3.13] gh-127321: Avoid stopping at an opcode without an associated line number for breakpoint() (GH-127457)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2024-11-30-21-46-15.gh-issue-127321.M78fBv.rst
Labels: type-bug, awaiting merge

#127227 gh-115999: Add partial free-thread specialization for BINARY_SUBSCR
  Include/internal/pycore_list.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_metadata.h
  Lib/test/test_dis.py
  Lib/test/test_opcache.py
  Objects/listobject.c
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/specialize.c
Labels: awaiting merge, skip news

#127430 GH-127429: fix sysconfig data generation on cross-builds
  .github/workflows/jit.yml
  Lib/sysconfig/__init__.py
  Lib/sysconfig/__main__.py
  Misc/NEWS.d/next/Library/2024-11-29-23-02-43.gh-issue-127429.dQf2w4.rst
  configure
  configure.ac
Labels: awaiting core review, needs backport to 3.12, needs backport to 3.13

#127451 gh-127443: fix some entries in `Doc/data/refcounts.dat`
  Doc/data/refcounts.dat
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#127496 [3.13] gh-127443: Fix some entries in `Doc/data/refcounts.dat` (GH-127451)
  Doc/data/refcounts.dat
Labels: awaiting merge, skip news

#127497 [3.12] gh-127443: Fix some entries in `Doc/data/refcounts.dat` (GH-127451)
  Doc/data/refcounts.dat
Labels: awaiting merge, skip news

#127110 GH-126491: GC: Mark objects reachable from roots before doing cycle collection
  Include/cpython/pystats.h
  Include/internal/pycore_frame.h
  Include/internal/pycore_gc.h
  Include/internal/pycore_object.h
  Include/internal/pycore_runtime_init.h
  InternalDocs/garbage_collector.md
  Lib/test/libregrtest/refleak.py
  Lib/test/test_gc.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-11-21-16-13-52.gh-issue-126491.0YvL94.rst
  Modules/_testinternalcapi.c
  Python/ceval.c
  Python/gc.c
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: awaiting merge

#127420 Fix Unicode encode_wstr_utf8()
  Objects/unicodeobject.c
Labels: skip issue, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#127504 [3.12] Fix Unicode encode_wstr_utf8() (#127420)
  Objects/unicodeobject.c
Labels: skip issue, awaiting review, skip news

#126975 [3.10] gh-103848: Adds checks to ensure that bracketed hosts found by urlsplit are of IPv6 or IPvFuture format (#103849)
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Library/2023-04-26-09-54-25.gh-issue-103848.aDSnpR.rst
Labels: type-bug, awaiting merge

#127048 gh-126618: fix repr(itertools.count(sys.maxsize))
  Lib/test/test_itertools.py
  Misc/NEWS.d/next/Library/2024-11-20-08-54-11.gh-issue-126618.ef_53g.rst
  Modules/itertoolsmodule.c
Labels: awaiting merge

#122933 gh-109523: Reading text from a non-blocking stream with read may now raise a BlockingIOError if the operation cannot immediately return bytes.
  Doc/library/io.rst
  Doc/whatsnew/3.14.rst
  Lib/_pyio.py
  Lib/test/test_io.py
  Misc/ACKS
  Misc/NEWS.d/next/C_API/2024-08-12-10-15-19.gh-issue-109523.S2c3fi.rst
  Modules/_io/textio.c
Labels: awaiting core review

#127054 gh-101100: Fix Sphinx warnings about list methods
  Doc/library/collections.rst
  Doc/tools/.nitignore
  Doc/tutorial/datastructures.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#126335 [3.12] gh-99880: document rounding mode for new-style formatting (GH-121481)
  Doc/library/string.rst
Labels: docs, awaiting review, skip news

#126891 [3.12] Docs: Miscellaneous corrections to simple statements in the language reference (GH-126720)
  Doc/reference/simple_stmts.rst
Labels: docs, skip issue, awaiting merge, skip news

#127501 [3.12] add missing gc_collect() calls in sqlite3 tests (GH-127446)
  Lib/test/test_sqlite3/test_regression.py
Labels: tests, skip issue, awaiting review, skip news

#127512 [3.12] gh-101100: Fix Sphinx warnings about list methods (GH-127054)
  Doc/library/collections.rst
  Doc/tools/.nitignore
  Doc/tutorial/datastructures.rst
Labels: docs, awaiting merge, skip news

#125705 [3.13] gh-125703: Correctly honour tracemalloc hooks on specialized DECREF paths (GH-125704)
  Include/internal/pycore_object.h
  Misc/NEWS.d/next/Core_and_Builtins/2024-10-18-16-00-10.gh-issue-125703.QRoqMo.rst
Labels: awaiting review

#125780 [3.13] gh-124984: Enhance `ssl` thread safety (GH-124993)
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2024-10-04-22-43-48.gh-issue-124984.xjMv9b.rst
  Modules/_ssl.c
  Modules/clinic/_ssl.c.h
Labels: awaiting review, topic-SSL, topic-free-threading

#126023 [3.13] gh-125666: Avoid PyREPL exiting when a null byte is in input (GH-125732)
  Lib/code.py
  Lib/test/test_pyrepl/test_interact.py
  Lib/test/test_pyrepl/test_pyrepl.py
  Misc/NEWS.d/next/Library/2024-10-19-16-06-52.gh-issue-125666.jGfdCP.rst
Labels: awaiting core review, topic-repl

#126334 [3.13] gh-99880: document rounding mode for new-style formatting (GH-121481)
  Doc/library/string.rst
Labels: docs, awaiting review, skip news

#126492 [3.13] gh-122838: Document missing opcodes (GH-123073)
  Doc/library/dis.rst
Labels: docs, awaiting review, skip news

#126885 [3.13] gh-126720: Docs: Miscellaneous corrections to simple statements in the language reference (GH-126720)
  Doc/reference/simple_stmts.rst
Labels: docs, skip issue, awaiting merge, skip news

#126761 [3.12] gh-126699: allow AsyncIterator to be used as a base for Protocols (GH-126702)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2024-11-11-13-24-22.gh-issue-126699.ONGbMd.rst
Labels: awaiting merge

#127500 [3.13] add missing gc_collect() calls in sqlite3 tests (GH-127446)
  Lib/test/test_sqlite3/test_regression.py
Labels: tests, skip issue, awaiting review, skip news

#127510 [3.12] gh-126618: fix repr(itertools.count(sys.maxsize)) (GH-127048)
  Lib/test/test_itertools.py
  Misc/NEWS.d/next/Library/2024-11-20-08-54-11.gh-issue-126618.ef_53g.rst
  Modules/itertoolsmodule.c
Labels: awaiting review

#127216 [3.13] gh-113841: fix possible undefined division by 0 in _Py_c_pow() (GH-127211)
  Lib/test/test_complex.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-11-24-07-01-28.gh-issue-113841.WFg-Bu.rst
  Objects/complexobject.c
Labels: awaiting review

#127513 [3.13] gh-126890: Restore stripped `ssl` docstrings (GH-127281)
  Modules/_ssl.c
  Modules/clinic/_ssl.c.h
Labels: awaiting review, skip news

#126799 [3.10] gh-126623: Update libexpat to 2.6.4, make future updates easier (GH-126792)
  Misc/NEWS.d/next/Security/2024-11-13-11-09-12.gh-issue-126623.TO7NnR.rst
  Modules/expat/expat.h
  Modules/expat/expat_external.h
  Modules/expat/refresh.sh
  Modules/expat/xmlparse.c
Labels: type-security, awaiting review

#126800 [3.9] gh-126623: Update libexpat to 2.6.4, make future updates easier (GH-126792)
  Misc/NEWS.d/next/Security/2024-11-13-11-09-12.gh-issue-126623.TO7NnR.rst
  Modules/expat/expat.h
  Modules/expat/expat_external.h
  Modules/expat/refresh.sh
  Modules/expat/xmlparse.c
Labels: type-security, awaiting review

#127514 gh-115999: Use light-weight lock for UNPACK_SEQUENCE_LIST
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge, skip news, topic-free-threading

#127517 gh-126876: Fix test_socket.testLargeTimeout() for missing _testcapi
  Lib/test/test_socket.py
Labels: tests, awaiting core review, skip news, needs backport to 3.13

#127002 [3.13] gh-126876: Fix socket internal_select() for large timeout (GH-126968)
  Lib/test/test_socket.py
  Modules/socketmodule.c
Labels: awaiting review, skip news

#127114 [3.13] gh-126914: Store the Preallocated Thread State's Pointer in a PyInterpreterState Field
  Doc/data/python3.13.abi
  Include/internal/pycore_interp.h
  Lib/test/test_interpreters/test_stress.py
  Python/pystate.c
Labels: awaiting core review, skip news

#127524 gh-127521: Mark list as "shared" before resizing if necessary
  Objects/listobject.c
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#127530 [3.12] gh-113841: fix possible undefined division by 0 in _Py_c_pow() (GH-127211) (GH-127216)
  Lib/test/test_complex.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-11-24-07-01-28.gh-issue-113841.WFg-Bu.rst
  Objects/complexobject.c
Labels: awaiting review

#127534 [3.12] gh-119826: Improved fallback for ntpath.abspath() on Windows (GH-119938)
  Lib/ntpath.py
  Lib/test/test_ntpath.py
  Misc/NEWS.d/next/Library/2024-06-02-11-48-19.gh-issue-119826.N1obGa.rst
Labels: awaiting review

#127535 [3.13] gh-119826: Improved fallback for ntpath.abspath() on Windows (GH-119938)
  Lib/ntpath.py
  Lib/test/test_ntpath.py
  Misc/NEWS.d/next/Library/2024-06-02-11-48-19.gh-issue-119826.N1obGa.rst
Labels: awaiting review

#127526 gh-127518: Fix pystats build after #127169
  Python/specialize.c
Labels: awaiting merge, skip news

#127113 gh-127111: Emscripten Make web example work again
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2024-11-30-16-36-09.gh-issue-127111.QI9mMZ.rst
  Tools/wasm/README.md
  Tools/wasm/emscripten/web_example/python.html
  Tools/wasm/emscripten/web_example/python.worker.mjs
  Tools/wasm/emscripten/web_example/server.py
  Tools/wasm/emscripten/web_example/wasm_assets.py
  configure
  configure.ac
Labels: awaiting merge, build, OS-emscripten

#127533 [3.13] gh-127521: Mark list as "shared" before resizing if necessary (GH-127524)
  Objects/listobject.c
Labels: awaiting review, skip news, topic-free-threading

#127538 Speed-up lazy heapq import in collections
  Lib/collections/__init__.py
Labels: performance, skip issue, awaiting merge, skip news

#127543 docs(logging): fix phrasing from "operation on" to "operate on"
  Doc/howto/logging.rst
Labels: docs, skip issue, awaiting merge, skip news

#127254 gh-127253: Note that Stable ABI is about ABI stability
  Doc/c-api/stable.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#126586 gh-126585: Add EHWPOISON error code
  Doc/library/errno.rst
  Doc/whatsnew/3.14.rst
  Misc/NEWS.d/next/Library/2024-11-04-22-02-30.gh-issue-85046.Y5d_ZN.rst
  Modules/errnomodule.c
Labels: awaiting merge

#127558 [3.12] gh-127253: Note that Stable ABI is about ABI stability (GH-127254)
  Doc/c-api/stable.rst
Labels: docs, awaiting review, skip news

#127003 [3.12] gh-126876: Fix socket internal_select() for large timeout (GH-126968)
  Lib/test/test_socket.py
  Modules/socketmodule.c
Labels: awaiting review, skip news

#123211 gh-117657: TSAN Fix races in `PyMember_Get` and `PyMember_Set`, for C extensions
  Include/cpython/pyatomic.h
  Include/cpython/pyatomic_gcc.h
  Include/cpython/pyatomic_msc.h
  Include/cpython/pyatomic_std.h
  Include/internal/pycore_pyatomic_ft_wrappers.h
  Lib/test/libregrtest/tsan.py
  Lib/test/test_capi/test_structmembers.py
  Lib/test/test_free_threading/test_slots.py
  Modules/_testcapi/structmember.c
  Python/structmember.c
Labels: awaiting merge, skip news

#127348 gh-127347: Document `traceback.print_list`
  Doc/library/traceback.rst
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Documentation/2024-11-27-22-56-48.gh-issue-127347.xyddWS.rst
Labels: docs, awaiting core review, needs backport to 3.12, needs backport to 3.13

#123815 [3.13] gh-122792: Make IPv4-mapped IPv6 address properties consistent with IPv4 (GH-122793)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Security/2024-08-07-10-42-13.gh-issue-122792.oiTMo9.rst
Labels: type-security, awaiting review, deferred-blocker

#123991 [3.13] gh-123935: Fix typo in `_get_slots` in `dataclasses.py` (GH-123941)
  Lib/dataclasses.py
  Lib/test/test_dataclasses/__init__.py
  Misc/NEWS.d/next/Library/2024-09-11-13-33-19.gh-issue-123935.fRZ_56.rst
Labels: awaiting merge

#126798 [3.11] gh-126623: Update libexpat to 2.6.4, make future updates easier (GH-126792)
  Misc/NEWS.d/next/Security/2024-11-13-11-09-12.gh-issue-126623.TO7NnR.rst
  Modules/expat/expat.h
  Modules/expat/expat_external.h
  Modules/expat/refresh.sh
  Modules/expat/xmlparse.c
Labels: type-security, awaiting review

#123818 [3.11] gh-122792: Make IPv4-mapped IPv6 address properties consistent with IPv4 (GH-122793)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Security/2024-08-07-10-42-13.gh-issue-122792.oiTMo9.rst
Labels: type-security, awaiting review

#127128 gh-115999: Specialize `LOAD_SUPER_ATTR` in free-threaded builds
  Lib/test/test_opcache.py
  Objects/cellobject.c
  Python/bytecodes.c
  Python/ceval.c
  Python/generated_cases.c.h
  Python/specialize.c
Labels: awaiting merge, skip news, topic-free-threading

#127571 [3.9] gh-122792: Make IPv4-mapped IPv6 address properties consistent with IPv4 (GH-122793) (GH-123819)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Security/2024-08-07-10-42-13.gh-issue-122792.oiTMo9.rst
Labels: type-security, awaiting core review

#127549 gh-127421: Fix race in test_start_new_thread_failed
  Lib/test/test_threading.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13

#127426 gh-115999: Add free-threaded specialization for `SEND`.
  Lib/test/test_opcache.py
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/specialize.c
Labels: awaiting merge, skip news, topic-free-threading

#127574 [3.13] gh-127421: Fix race in test_start_new_thread_failed (GH-127549)
  Lib/test/test_threading.py
Labels: tests, awaiting review, skip news

#127272 gh-127271: Replace use of PyCell_GET/SET
  Doc/howto/free-threading-extensions.rst
  Include/Python.h
  Include/cpython/cellobject.h
  Lib/test/test_free_threading/test_races.py
  Objects/cellobject.c
  Objects/frameobject.c
  Objects/typeobject.c
  Python/bltinmodule.c
Labels: awaiting core review, skip news, topic-free-threading

#127565 gh-127146: Resolve some minor problems in Emscripten tests
  Lib/test/test_marshal.py
  Lib/test/test_math.py
  Lib/test/test_support.py
Labels: tests, awaiting merge, skip news, OS-emscripten

#127483 Itertool recipe additions
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#127585 [3.13] Itertool recipe additions (gh-127483)
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting review, skip news

#127569 [3.13] gh-127347: Document `traceback.print_list` (GH-127348)
  Doc/library/traceback.rst
Labels: awaiting merge, skip news

#127570 [3.12] gh-127347: Document `traceback.print_list` (GH-127348)
  Doc/library/traceback.rst
Labels: awaiting merge, skip news

#127577 gh-127572: Fix `test_structmembers` initialization
  Lib/test/test_capi/test_structmembers.py
  Modules/_testcapi/structmember.c
Labels: tests, awaiting merge, skip news

#126682 gh-126524: Run `regen-unicodedata` as a part of our CI
  .github/workflows/build.yml
Labels: awaiting merge, skip news

#127482 gh-127481: Add `EPOLLWAKEUP` to the `select` module
  Doc/library/select.rst
  Misc/NEWS.d/next/Library/2024-12-01-23-18-43.gh-issue-127481.K36AoP.rst
  Modules/selectmodule.c
Labels: awaiting merge

#127590 gh-127552: Remove comment questioning 4-digit restriction for ‘Y’ in datetime.strptime patterns
  Lib/_strptime.py
Labels: awaiting merge, skip news

#127580 gh-127536: Add missing locks in listobject.c
  Misc/NEWS.d/next/Core_and_Builtins/2024-12-03-21-07-06.gh-issue-127536.3jMMrT.rst
  Objects/listobject.c
Labels: awaiting merge, topic-free-threading, needs backport to 3.13

#127584 Enable native AArch64 Ubuntu CI jobs
  .github/workflows/build.yml
  .github/workflows/jit.yml
  .github/workflows/reusable-ubuntu.yml
  Tools/jit/ignore-tests-emulated-linux.txt
Labels: skip issue, awaiting merge, skip news, infra

#127155 GH-126795: Increase the JIT side-exit threshold from 64 to 4096
  Include/internal/pycore_backoff.h
Labels: performance, awaiting core review, skip news, interpreter-core, 3.14, topic-JIT

#127551 gh-127111: Apply prettier formatter to Emscripten web example
  Tools/wasm/emscripten/web_example/python.html
  Tools/wasm/emscripten/web_example/python.worker.mjs
Labels: awaiting merge, skip news, OS-emscripten

#127151 gh-127146: Emscripten: Skip segfaults in test suite
  Lib/test/list_tests.py
  Lib/test/mapping_tests.py
  Lib/test/support/__init__.py
  Lib/test/test_ast/test_ast.py
  Lib/test/test_call.py
  Lib/test/test_capi/test_misc.py
  Lib/test/test_class.py
  Lib/test/test_compile.py
  Lib/test/test_copy.py
  Lib/test/test_descr.py
  Lib/test/test_dict.py
  Lib/test/test_dictviews.py
  Lib/test/test_exception_group.py
  Lib/test/test_functools.py
  Lib/test/test_isinstance.py
  Lib/test/test_json/test_recursion.py
  Lib/test/test_pathlib/test_pathlib_abc.py
  Lib/test/test_traceback.py
  Lib/test/test_xml_etree_c.py
  configure
  configure.ac
Labels: awaiting merge, skip news

#127506 gh-127503: Emscripten make Python.sh function as proper Python CLI
  Tools/wasm/emscripten/__main__.py
  Tools/wasm/emscripten/node_entry.mjs
  configure
  configure.ac
Labels: awaiting merge, skip news

#127575 gh-127434: Fix iOS `xcrun --sdk` clang/ar scripts to allow arguments with spaces
  Misc/NEWS.d/next/Core_and_Builtins/2024-12-04-09-52-08.gh-issue-127434.RjkGT_.rst
  iOS/Resources/bin/arm64-apple-ios-ar
  iOS/Resources/bin/arm64-apple-ios-clang
  iOS/Resources/bin/arm64-apple-ios-clang++
  iOS/Resources/bin/arm64-apple-ios-cpp
  iOS/Resources/bin/arm64-apple-ios-simulator-ar
  iOS/Resources/bin/arm64-apple-ios-simulator-clang
  iOS/Resources/bin/arm64-apple-ios-simulator-clang++
  iOS/Resources/bin/arm64-apple-ios-simulator-cpp
  iOS/Resources/bin/x86_64-apple-ios-simulator-ar
  iOS/Resources/bin/x86_64-apple-ios-simulator-clang
  iOS/Resources/bin/x86_64-apple-ios-simulator-clang++
  iOS/Resources/bin/x86_64-apple-ios-simulator-cpp
Labels: awaiting merge, needs backport to 3.13

#127624 [3.13] gh-127434: Fix iOS `xcrun --sdk` clang/ar scripts to allow arguments with spaces (GH-127575)
  Misc/NEWS.d/next/Core and Builtins/2024-12-04-09-52-08.gh-issue-127434.RjkGT_.rst
  iOS/Resources/bin/arm64-apple-ios-ar
  iOS/Resources/bin/arm64-apple-ios-clang
  iOS/Resources/bin/arm64-apple-ios-clang++
  iOS/Resources/bin/arm64-apple-ios-cpp
  iOS/Resources/bin/arm64-apple-ios-simulator-ar
  iOS/Resources/bin/arm64-apple-ios-simulator-clang
  iOS/Resources/bin/arm64-apple-ios-simulator-clang++
  iOS/Resources/bin/arm64-apple-ios-simulator-cpp
  iOS/Resources/bin/x86_64-apple-ios-simulator-ar
  iOS/Resources/bin/x86_64-apple-ios-simulator-clang
  iOS/Resources/bin/x86_64-apple-ios-simulator-clang++
  iOS/Resources/bin/x86_64-apple-ios-simulator-cpp
Labels: awaiting core review

#127607 gh-119182: Complete PyUnicodeWriter documentation
  Doc/c-api/unicode.rst
Labels: docs, awaiting merge, skip news

#127593 gh-93312: Include <sys/pidfd.h> to get PIDFD_NONBLOCK
  Misc/NEWS.d/next/Library/2024-12-04-11-01-16.gh-issue-93312.9sB-Qw.rst
  Modules/posixmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#127631 [3.12] gh-93312: Include <sys/pidfd.h> to get PIDFD_NONBLOCK (#127593)
  Misc/NEWS.d/next/Library/2024-12-04-11-01-16.gh-issue-93312.9sB-Qw.rst
  Modules/posixmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting core review

#127630 [3.13] gh-93312: Include <sys/pidfd.h> to get PIDFD_NONBLOCK (GH-127593)
  Misc/NEWS.d/next/Library/2024-12-04-11-01-16.gh-issue-93312.9sB-Qw.rst
  Modules/posixmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting review

#127414 gh-127413: allow to show specialized bytecode via `dis` CLI
  Doc/library/dis.rst
  Doc/whatsnew/3.14.rst
  Lib/dis.py
  Misc/NEWS.d/next/Library/2024-11-29-14-45-26.gh-issue-127413.z11AUc.rst
Labels: awaiting merge

#122469 gh-122431: Disallow negative values in `readline.append_history_file`
  Lib/test/test_readline.py
  Misc/NEWS.d/next/Library/2024-07-30-11-37-40.gh-issue-122431.lAzVtu.rst
  Modules/readline.c
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#127642 [3.12] gh-122431: Disallow negative values in `readline.append_history_file` (GH-122469)
  Lib/test/test_readline.py
  Misc/NEWS.d/next/Library/2024-07-30-11-37-40.gh-issue-122431.lAzVtu.rst
  Modules/readline.c
Labels: awaiting review

#127641 [3.13] gh-122431: Disallow negative values in `readline.append_history_file` (GH-122469)
  Lib/test/test_readline.py
  Misc/NEWS.d/next/Library/2024-07-30-11-37-40.gh-issue-122431.lAzVtu.rst
  Modules/readline.c
Labels: awaiting review

#127327 GH-126727: Fix test_era_nl_langinfo with Japanese ERAs on Solaris
  Lib/test/test__locale.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#127646 [3.12] GH-126727: Fix test_era_nl_langinfo with Japanese ERAs on Solaris (GH-127327)
  Lib/test/test__locale.py
Labels: tests, awaiting review, skip news

#127645 [3.13] GH-126727: Fix test_era_nl_langinfo with Japanese ERAs on Solaris (GH-127327)
  Lib/test/test__locale.py
Labels: tests, awaiting review, skip news

#127621 GDB helpers docs: fix block type of a cast example
  Doc/howto/gdb_helpers.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#127653 [3.13] [Docs] GDB howto: Fix block type of a cast example (GH-127621)
  Doc/howto/gdb_helpers.rst
Labels: docs, skip issue, awaiting review, skip news

#127654 [3.12] [Docs] GDB howto: Fix block type of a cast example (GH-127621)
  Doc/howto/gdb_helpers.rst
Labels: docs, skip issue, awaiting review, skip news

#127377 GH-125413: Revert addition of `pathlib.Path.scandir()` method
  Doc/library/pathlib.rst
  Doc/whatsnew/3.14.rst
  Lib/pathlib/_abc.py
  Lib/pathlib/_local.py
  Lib/test/test_pathlib/test_pathlib_abc.py
  Misc/NEWS.d/3.14.0a2.rst
  Misc/NEWS.d/next/Library/2024-11-29-00-15-59.gh-issue-125413.WCN0vv.rst
Labels: awaiting merge, topic-pathlib

#127659 [3.13] gh-127582: Make object resurrection thread-safe for free threading. (GH-127612)
  Include/internal/pycore_object.h
  Misc/NEWS.d/next/Core and Builtins/2024-12-05-19-25-00.gh-issue-127582.ogUY2a.rst
  Objects/codeobject.c
  Objects/dictobject.c
  Objects/funcobject.c
  Objects/object.c
Labels: awaiting core review

#127628 gh-127627: Add `posix._emscripten_debugger` function
  Misc/NEWS.d/next/Library/2024-12-05-10-14-52.gh-issue-127627.fgCHOZ.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting merge

#127656 gh-127655: Ensure `_SelectorSocketTransport.writelines` pauses the protocol if needed
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Misc/NEWS.d/next/Security/2024-12-05-21-35-19.gh-issue-127655.xpPoOf.rst
Labels: type-security, topic-asyncio, awaiting merge, needs backport to 3.12, needs backport to 3.13

#127663 [3.13] gh-127655: Ensure `_SelectorSocketTransport.writelines` pauses the protocol if needed (GH-127656)
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Misc/NEWS.d/next/Security/2024-12-05-21-35-19.gh-issue-127655.xpPoOf.rst
Labels: type-security, topic-asyncio, awaiting merge

#127664 [3.12] gh-127655: Ensure `_SelectorSocketTransport.writelines` pauses the protocol if needed (GH-127656)
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Misc/NEWS.d/next/Security/2024-12-05-21-35-19.gh-issue-127655.xpPoOf.rst
Labels: type-security, topic-asyncio, awaiting merge

#120287 gh-120010: fix invalid (nan+nanj) results in _Py_c_prod()
  Lib/test/test_complex.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-06-04-08-26-25.gh-issue-120010._z-AWz.rst
  Objects/complexobject.c
Labels: awaiting merge

#127519 GH-126491: Lower heap size limit with faster marking
  InternalDocs/garbage_collector.md
  Lib/test/test_gc.py
  Objects/dictobject.c
  Objects/genobject.c
  Objects/typeobject.c
  Python/gc.c
Labels: awaiting merge, skip news

#127692 [3.13] gh-101100: amend references starting with `!~` in gh-127054 (GH-127684)
  Doc/tutorial/datastructures.rst
Labels: docs, awaiting merge, skip news

#127693 [3.12] gh-101100: amend references starting with `!~` in gh-127054 (GH-127684)
  Doc/tutorial/datastructures.rst
Labels: docs, awaiting merge, skip news

#127566 gh-126024: fix UBSan failure in `unicodeobject.c:find_first_nonascii`
  Objects/unicodeobject.c
Labels: awaiting merge, skip news

#125612 gh-125610: Fix `STORE_ATTR_INSTANCE_VALUE` specialization check
  Python/specialize.c
Labels: awaiting merge, skip news, needs backport to 3.13

#127315 gh-127314: Don't mention the GIL when calling without a thread state on the free-threaded build
  Include/internal/pycore_pystate.h
  Lib/test/test_capi/test_mem.py
  Lib/test/test_capi/test_misc.py
  Misc/NEWS.d/next/C_API/2024-11-26-22-06-10.gh-issue-127314.SsRrIu.rst
  Objects/obmalloc.c
Labels: awaiting merge

#127698 [3.13] gh-125610: Fix `STORE_ATTR_INSTANCE_VALUE` specialization check (GH-125612)
  Python/specialize.c
Labels: awaiting review, skip news

#127338 gh-59705: Add _thread.set_name() function
  Lib/test/test_threading.py
  Lib/threading.py
  Misc/NEWS.d/next/Library/2024-11-27-17-04-38.gh-issue-59705.sAGyvs.rst
  Modules/_threadmodule.c
  Modules/clinic/_threadmodule.c.h
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge

#127175 gh-119786: Add jit.md. Move adaptive.md to a section of interpreter.md.
  InternalDocs/README.md
  InternalDocs/adaptive.md
  InternalDocs/code_objects.md
  InternalDocs/compiler.md
  InternalDocs/interpreter.md
  InternalDocs/jit.md
Labels: awaiting merge, skip news

#127650 [3.13] gh-127552: Remove comment questioning 4-digit restriction for ‘Y’ in datetime.strptime patterns (GH-127590)
  Lib/_strptime.py
Labels: awaiting merge, skip news

#127699 Fix typo in _android_support.py
  Lib/_android_support.py
Labels: skip issue, awaiting merge, skip news, needs backport to 3.13

#127703 [3.13] Fix typo in `Lib/_android_support.py` (GH-127699)
  Lib/_android_support.py
Labels: skip issue, awaiting review, skip news

#127704 GH-127652: stop using `--wasi preview2` in `wasi.py`
  Tools/wasm/wasi.py
Labels: awaiting core review, skip news, needs backport to 3.13

#127707 GH-127381: pathlib ABCs: remove `PathBase.resolve()` and `absolute()`
  Lib/pathlib/_abc.py
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: awaiting core review, skip news, topic-pathlib

#127687 gh-119786: fix typo in `InternalDocs/garbage_collector.md`
  InternalDocs/garbage_collector.md
Labels: skip issue, awaiting core review, skip news

#127370 Give RPOP proper docstring
  Lib/poplib.py
Labels: skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#127722 [3.12] Give `poplib.POP3.rpop` a proper docstring (GH-127370)
  Lib/poplib.py
Labels: skip issue, awaiting review, skip news

#127721 [3.13] Give `poplib.POP3.rpop` a proper docstring (GH-127370)
  Lib/poplib.py
Labels: skip issue, awaiting review, skip news

#127091 GH-127090: Fix `urllib.response.addinfourl.url` value for opened `file:` URIs
  Lib/test/test_urllib.py
  Lib/test/test_urllib2.py
  Lib/test/test_urllib2net.py
  Lib/urllib/request.py
  Misc/NEWS.d/next/Library/2024-11-21-06-03-46.gh-issue-127090.yUYwdh.rst
Labels: awaiting merge

#127729 GH-126789: fix some sysconfig data on late site initializations
  Lib/sysconfig/__init__.py
  Lib/test/test_sysconfig.py
  Misc/NEWS.d/next/Library/2024-12-07-23-06-44.gh-issue-126789.4dqfV1.rst
Labels: awaiting core review

#127657 gh-127610: Added validation for more than one var positional and var keyword parameters in inspect.Signature
  Lib/inspect.py
  Lib/test/test_inspect/test_inspect.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2024-12-06-17-28-55.gh-issue-127610.ctv_NP.rst
Labels: awaiting merge

#127739 gh-123378: fix post-merge typos in comments and NEWS
  Misc/NEWS.d/next/C_API/2024-08-27-09-07-56.gh-issue-123378.JJ6n_u.rst
  Objects/exceptions.c
Labels: awaiting merge

#127742 Fix typos in `interpreter_definition.md`
  Tools/cases_generator/interpreter_definition.md
Labels: skip issue, awaiting merge, skip news

#127736 GH-127381: pathlib ABCs: remove `PathBase.unlink()` and `rmdir()`
  Lib/pathlib/_abc.py
  Lib/pathlib/_local.py
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: awaiting core review, skip news, topic-pathlib

#127735 gh-127734: improve signature of `urllib.request.HTTPPasswordMgrWithPriorAuth.__init__`
  Lib/urllib/request.py
Labels: awaiting merge, skip news, 3.12

#127744 [3.13] gh-127734: improve signature of `urllib.request.HTTPPasswordMgrWithPriorAuth.__init__` (GH-127735)
  Lib/urllib/request.py
Labels: awaiting merge, skip news

#127745 [3.12] gh-127734: improve signature of `urllib.request.HTTPPasswordMgrWithPriorAuth.__init__` (GH-127735)
  Lib/urllib/request.py
Labels: awaiting merge, skip news

#127666 gh-127111: Emscripten Move link flags from `LDFLAGS_NODIST` to `LINKFORSHARED`
  configure
  configure.ac
Labels: awaiting merge, skip news, OS-emscripten

#127633 gh-127503 Don't propagate native PATH to Emscripten Python
  Tools/wasm/emscripten/node_entry.mjs
Labels: awaiting merge, skip news, OS-emscripten

#127632 gh-127503: Fix realpath handling in emscripten cli
  Tools/wasm/emscripten/__main__.py
Labels: awaiting merge, skip news, OS-emscripten

#127592 gh-126925: Modify how iOS test results are gathered
  Doc/c-api/init_config.rst
  Doc/using/ios.rst
  Doc/whatsnew/3.14.rst
  Include/cpython/initconfig.h
  Lib/_apple_support.py
  Lib/test/test_apple.py
  Lib/test/test_capi/test_config.py
  Lib/test/test_embed.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2024-12-04-15-04-12.gh-issue-126821.lKCLVV.rst
  Misc/NEWS.d/next/Tests/2024-12-04-15-03-24.gh-issue-126925.uxAMK-.rst
  Python/initconfig.c
  Python/pylifecycle.c
  Python/stdlib_module_names.h
  iOS/README.rst
  iOS/testbed/__main__.py
  iOS/testbed/iOSTestbed.xcodeproj/project.pbxproj
  iOS/testbed/iOSTestbedTests/iOSTestbedTests.m
Labels: tests, OS-mac, awaiting merge, stdlib, 3.13, OS-ios, 3.14, needs backport to 3.13

#127754 [3.13] gh-126925: Modify how iOS test results are gathered (GH-127592)
  Doc/c-api/init_config.rst
  Doc/using/ios.rst
  Include/cpython/initconfig.h
  Lib/_apple_support.py
  Lib/test/test_apple.py
  Lib/test/test_embed.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2024-12-04-15-04-12.gh-issue-126821.lKCLVV.rst
  Misc/NEWS.d/next/Tests/2024-12-04-15-03-24.gh-issue-126925.uxAMK-.rst
  Python/initconfig.c
  Python/pylifecycle.c
  Python/stdlib_module_names.h
  iOS/README.rst
  iOS/testbed/__main__.py
  iOS/testbed/iOSTestbed.xcodeproj/project.pbxproj
  iOS/testbed/iOSTestbedTests/iOSTestbedTests.m
Labels: awaiting core review

#127733 gh-127732: Add Windows Server 2025 to `platform.py` detection
  Lib/platform.py
  Misc/NEWS.d/next/Library/2024-12-08-08-36-18.gh-issue-127732.UEKxoa.rst
Labels: OS-windows, awaiting review, needs backport to 3.12, needs backport to 3.13

#127763 [3.12] gh-127732: Add Windows Server 2025 detection to platform module (GH-127733)
  Lib/platform.py
  Misc/NEWS.d/next/Library/2024-12-08-08-36-18.gh-issue-127732.UEKxoa.rst
Labels: awaiting review

#127762 [3.13] gh-127732: Add Windows Server 2025 detection to platform module (GH-127733)
  Lib/platform.py
  Misc/NEWS.d/next/Library/2024-12-08-08-36-18.gh-issue-127732.UEKxoa.rst
Labels: awaiting review

#127759 gh-127637: add tests for `dis` command-line interface
  Lib/dis.py
  Lib/test/test_dis.py
  Misc/NEWS.d/next/Tests/2024-12-09-12-35-44.gh-issue-127637.KLx-9I.rst
Labels: awaiting merge

#127494 GH-127456: pathlib ABCs: add protocol for path parser
  Lib/pathlib/_abc.py
  Lib/pathlib/_types.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: awaiting merge, skip news, topic-pathlib

#125446 gh-125420: implement `Sequence.index` API on `memoryview` objects
  Doc/library/stdtypes.rst
  Lib/test/test_memoryview.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-10-14-13-28-16.gh-issue-125420.hNKixM.rst
  Objects/clinic/memoryobject.c.h
  Objects/memoryobject.c
Labels: awaiting merge

#127660 gh-127651: Use __file__ in diagnostics if origin is missing
  Lib/test/test_import/__init__.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-12-06-01-09-40.gh-issue-127651.80cm6j.rst
  Python/ceval.c
Labels: awaiting merge, needs backport to 3.13

#127775 [3.13] gh-127651: Use __file__ in diagnostics if origin is missing (#127660)
  Lib/test/test_import/__init__.py
  Misc/NEWS.d/next/Core and Builtins/2024-12-06-01-09-40.gh-issue-127651.80cm6j.rst
  Python/ceval.c
Labels: awaiting core review
