Repository python/cpython, pull requests merged in 2024-07, with the labels that each got.

#121126 gh-87744: fix waitpid race while calling send_signal in asyncio
  Lib/asyncio/base_subprocess.py
  Lib/test/test_asyncio/test_subprocess.py
  Misc/NEWS.d/next/Library/2024-06-29-05-08-59.gh-issue-87744.rpF6Jw.rst
Labels: type-bug, topic-asyncio, awaiting core review, needs backport to 3.13

#121195 gh-121188: Escape invalid XML characters in regrtest
  Lib/test/libregrtest/testresult.py
  Lib/test/libregrtest/utils.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2024-07-01-09-04-32.gh-issue-121188.XbuTVa.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#121202 [3.13] gh-113565: Improve and harden detection of curses dependencies (GH-119816)
  Include/py_curses.h
  Misc/NEWS.d/next/Build/2024-06-02-13-23-26.gh-issue-113565.8xBlId.rst
  Modules/_curses_panel.c
  Modules/_cursesmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting review

#121205 [3.12] gh-121188: Sanitize invalid XML characters in regrtest (GH-121195)
  Lib/test/libregrtest/testresult.py
  Lib/test/libregrtest/utils.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2024-07-01-09-04-32.gh-issue-121188.XbuTVa.rst
Labels: awaiting review

#121203 gh-121199: Use _Py__has_attribute() in timemodule.c
  Modules/timemodule.c
  Python/bootstrap_hash.c
Labels: awaiting core review, skip news

#120894 gh-61103: support double complex (_Complex) type in ctypes
  Doc/library/ctypes.rst
  Lib/ctypes/__init__.py
  Lib/test/test_ctypes/test_libc.py
  Lib/test/test_ctypes/test_numbers.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2024-06-23-07-23-08.gh-issue-61103.ca_U_l.rst
  Modules/_complex.h
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/_ctypes_test.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/cfield.c
  Modules/_ctypes/ctypes.h
  PCbuild/_ctypes_test.vcxproj
  Tools/c-analyzer/c_parser/parser/_regexes.py
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge

#121204 [3.13] gh-121188: Sanitize invalid XML characters in regrtest (GH-121195)
  Lib/test/libregrtest/testresult.py
  Lib/test/libregrtest/utils.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2024-07-01-09-04-32.gh-issue-121188.XbuTVa.rst
Labels: awaiting review

#121191 gh-121084: Call _abc_registry_clear() when checking refleaks
  Lib/test/libregrtest/refleak.py
Labels: awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#121209 [3.12] gh-121084: Call _abc_registry_clear() when checking refleaks (GH-121191)
  Lib/test/libregrtest/refleak.py
Labels: awaiting review, skip news

#121208 [3.13] gh-121084: Call _abc_registry_clear() when checking refleaks (GH-121191)
  Lib/test/libregrtest/refleak.py
Labels: awaiting review, skip news

#121207 gh-121200: Log pwd entry in test_expanduser_pwd2()
  Lib/test/test_posixpath.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#121214 [3.12] gh-121200: Log pwd entry in test_expanduser_pwd2() (GH-121207)
  Lib/test/test_posixpath.py
Labels: tests, awaiting review, skip news

#121213 [3.13] gh-121200: Log pwd entry in test_expanduser_pwd2() (GH-121207)
  Lib/test/test_posixpath.py
Labels: tests, awaiting review, skip news

#117785 gh-117784: Only reference PHA functions ifndef SSL_VERIFY_POST_HANDSHAKE
  Misc/NEWS.d/next/Library/2024-06-26-17-00-39.gh-issue-117784.inCtAV.rst
  Modules/_ssl.c
Labels: awaiting merge, topic-SSL

#121221 gh-121220: Mark ``weakref.test_threaded_weak_value_dict_copy/test_threaded_weak_key_dict_copy`` as a cpu-heavy tests
  Lib/test/test_weakref.py
Labels: tests, awaiting merge, skip news

#120490 gh-117657: Using critical section to make _socket.socket.close thread safe
  Modules/clinic/socketmodule.c.h
  Modules/socketmodule.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news

#121228 gh-121200: Fix test_expanduser_pwd2() of test_posixpath
  Lib/test/test_posixpath.py
  Misc/NEWS.d/next/Tests/2024-07-01-16-15-06.gh-issue-121200.4Pc-gc.rst
Labels: tests, awaiting core review

#121232 [3.13] gh-121200: Fix test_expanduser_pwd2() of test_posixpath (GH-121228)
  Lib/test/test_posixpath.py
  Misc/NEWS.d/next/Tests/2024-07-01-16-15-06.gh-issue-121200.4Pc-gc.rst
Labels: tests, awaiting review

#121175 gh-114104: clarify asynchronous comprehension docs to match runtime behavior
  Doc/reference/expressions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#121235 [3.12] gh-114104: clarify asynchronous comprehension docs to match runtime behavior (GH-121175)
  Doc/reference/expressions.rst
Labels: docs, awaiting review, skip news

#121234 [3.13] gh-114104: clarify asynchronous comprehension docs to match runtime behavior (GH-121175)
  Doc/reference/expressions.rst
Labels: docs, awaiting review, skip news

#121236 gh-121110: Temporarily Skip test_basic_multiple_interpreters_reset_each
  Lib/test/test_import/__init__.py
Labels: awaiting core review, skip news, needs backport to 3.13

#121238 [3.13] gh-121110: Temporarily Skip test_basic_multiple_interpreters_reset_each (gh-121236)
  Lib/test/test_import/__init__.py
Labels: awaiting review, skip news

#120914 gh-117657: Fix data races reported by TSAN in some set methods
  Include/internal/pycore_object.h
  Modules/_collectionsmodule.c
  Objects/dictobject.c
  Objects/setobject.c
  Objects/typeobject.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, needs backport to 3.13

#121240 [3.13] gh-117657: Fix data races reported by TSAN in some set methods (GH-120914)
  Include/internal/pycore_object.h
  Modules/_collectionsmodule.c
  Objects/dictobject.c
  Objects/setobject.c
  Objects/typeobject.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting review, skip news

#120960 GH-116017: Get rid of `_COLD_EXIT`
  Include/internal/pycore_backoff.h
  Include/internal/pycore_code.h
  Include/internal/pycore_optimizer.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Misc/NEWS.d/next/Core and Builtins/2024-06-24-08-39-23.gh-issue-116017.-Bw2UY.rst
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor_cases.c.h
  Python/jit.c
  Python/optimizer.c
  Python/optimizer_cases.c.h
  Tools/c-analyzer/cpython/ignored.tsv
  Tools/jit/_stencils.py
  Tools/jit/template.c
Labels: performance, awaiting core review, interpreter-core

#121243 [3.12] gh-121196: Document `dict.fromkeys` params as pos-only (GH-121197)
  Doc/library/stdtypes.rst
Labels: docs, awaiting merge, skip news

#121242 [3.13] gh-121196: Document `dict.fromkeys` params as pos-only (GH-121197)
  Doc/library/stdtypes.rst
Labels: docs, awaiting merge, skip news

#121001 gh-119726: replace AArch64 trampolines with LDR
  Misc/NEWS.d/next/Core and Builtins/2024-06-25-16-26-44.gh-issue-119726.WqvHxB.rst
  Tools/jit/_stencils.py
Labels: awaiting merge

#121135 Paragraphs with leading similar
  Doc/c-api/dict.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.13

#121254 gh-121035: Improve logging flow diagram for dark/light modes.
  Doc/howto/logging.rst
  Doc/howto/logging_flow.svg
Labels: docs, awaiting core review, skip news

#121251 Move get_signal_name() to test.support
  Lib/test/libregrtest/run_workers.py
  Lib/test/libregrtest/utils.py
  Lib/test/support/__init__.py
  Lib/test/support/script_helper.py
  Lib/test/test_regrtest.py
  Lib/test/test_support.py
Labels: skip issue, awaiting core review, skip news

#121255 gh-121245: Amend d611c4c8e9 (correct import)
  Lib/site.py
  Misc/NEWS.d/next/Library/2024-07-02-11-34-06.gh-issue-121245.sSkDAr.rst
Labels: awaiting merge, needs backport to 3.13

#121211 gh-121210: handle nodes with missing attributes/fields in `ast.compare`
  Lib/ast.py
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2024-07-01-11-23-18.gh-issue-121210.cD0zfn.rst
Labels: awaiting merge

#121166 gh-121165: protect macro expansion of `ADJUST_INDICES`
  Objects/bytes_methods.c
  Objects/unicodeobject.c
Labels: awaiting merge, skip news

#121261 [3.13] gh-121245: Amend d611c4c8e9 (correct import) (GH-121255)
  Lib/site.py
  Misc/NEWS.d/next/Library/2024-07-02-11-34-06.gh-issue-121245.sSkDAr.rst
Labels: awaiting merge

#121273 gh-121272: move __future__ import validation from compiler to symtable
  Python/compile.c
  Python/symtable.c
Labels: awaiting merge, skip news

#121244 gh-117139: Add _PyTuple_FromStackRefSteal and use it
  Include/internal/pycore_stackref.h
  Include/internal/pycore_tuple.h
  Objects/tupleobject.c
  Python/bytecodes.c
  Python/ceval.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Tools/cases_generator/analyzer.py
Labels: awaiting merge, skip news, topic-free-threading

#120112 gh-115773: Add sizes to debug offset structure
  Include/internal/pycore_runtime.h
  Include/internal/pycore_runtime_init.h
Labels: awaiting merge, skip news, needs backport to 3.13

#121265 gh-121035: Further improve logging flow diagram with respect to dark/…
  Doc/howto/logging.rst
  Doc/howto/logging_flow.svg
Labels: docs, awaiting core review, skip news

#121283 [3.13] gh-115773: Add sizes to debug offset structure (GH-120112)
  Include/internal/pycore_runtime.h
  Include/internal/pycore_runtime_init.h
Labels: awaiting merge, skip news

#120807 GH-73991: Support copying directory symlinks on older Windows
  Doc/library/pathlib.rst
  Lib/pathlib/__init__.py
  Lib/pathlib/_abc.py
  Lib/pathlib/_local.py
  Lib/pathlib/_os.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: awaiting core review, skip news, topic-pathlib

#121089 gh-121027: Make the functools.partial object a method descriptor
  Doc/whatsnew/3.14.rst
  Lib/functools.py
  Lib/test/test_functools.py
  Lib/test/test_inspect/test_inspect.py
  Misc/NEWS.d/next/Library/2024-06-27-12-27-52.gh-issue-121027.D4K1OX.rst
  Modules/_functoolsmodule.c
Labels: awaiting merge

#121260 gh-116181: Remove Py_BUILD_CORE_MODULE and Py_BUILD_CORE_MODULE in rotatingtree.c
  Modules/rotatingtree.c
Labels: awaiting merge, skip news, needs backport to 3.13

#118134 gh-111872: Document the max_children attribute for socketserver.ForkingMixIn
  Doc/library/socketserver.rst
Labels: docs, awaiting merge, skip news

#120625 Code style change: updated tp_flags initialization
  Objects/typeobject.c
Labels: skip issue, awaiting merge, skip news

#121307 [3.13] gh-116181: Remove Py_BUILD_CORE_BUILTIN and Py_BUILD_CORE_MODULE in rotatingtree.c (GH-121260)
  Modules/rotatingtree.c
Labels: awaiting merge, skip news

#112237 Fix "Py_TPFLAGS_MANAGED_WEAKREF is set in tp_flags"
  Doc/c-api/typeobj.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#121310 [3.12] docs: Fix "Py_TPFLAGS_MANAGED_WEAKREF is set in tp_flags" (GH-112237)
  Doc/c-api/typeobj.rst
Labels: docs, skip issue, awaiting merge, skip news

#120855 [3.13] gh-120782: Update internal type cache when reloading datetime (GH-120829)
  Lib/test/datetimetester.py
  Misc/NEWS.d/next/Library/2024-06-21-12-00-16.gh-issue-120782.LOE8tj.rst
  Modules/_datetimemodule.c
Labels: awaiting merge

#121309 [3.13] docs: Fix "Py_TPFLAGS_MANAGED_WEAKREF is set in tp_flags" (GH-112237)
  Doc/c-api/typeobj.rst
Labels: docs, skip issue, awaiting merge, skip news

#121311 gh-106597: Add more offsets to _Py_DebugOffsets
  Include/internal/pycore_runtime.h
  Include/internal/pycore_runtime_init.h
Labels: awaiting merge, skip news, needs backport to 3.13

#121281 [3.13] gh-121279: Re-add prematurely removed import warnings to importlib.abc
  Lib/importlib/abc.py
  Lib/test/test_importlib/test_abc.py
  Misc/NEWS.d/next/Library/2024-07-02-19-36-54.gh-issue-121279.BltDo9.rst
Labels: awaiting merge

#121248 gh-61103: Support float and long double complex types in ctypes module
  Doc/library/ctypes.rst
  Lib/ctypes/__init__.py
  Lib/test/test_ctypes/test_libc.py
  Lib/test/test_ctypes/test_numbers.py
  Misc/NEWS.d/next/Library/2024-06-23-07-23-08.gh-issue-61103.ca_U_l.rst
  Modules/_complex.h
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/_ctypes_test.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/cfield.c
  Modules/_ctypes/ctypes.h
Labels: awaiting merge

#121312 [3.13] gh-106597: Add more offsets to _Py_DebugOffsets (GH-121311)
  Include/internal/pycore_runtime.h
  Include/internal/pycore_runtime_init.h
Labels: awaiting merge, skip news

#121297 gh-121272: compiler no longer modifies the symtable, ste_coroutine always set during symtable construction
  Python/compile.c
  Python/symtable.c
Labels: awaiting merge, skip news

#121270 gh-121263: Macro-ify most stackref functions for MSVC
  Include/internal/pycore_stackref.h
Labels: awaiting core review, skip news

#121317 [3.13] gh-121035: Improve logging flow diagram for dark/light modes. …
  Doc/howto/logging.rst
  Doc/howto/logging_flow.svg
Labels: docs, awaiting core review, skip news

#121321 [3.12] gh-121035: Further improve logging flow diagram with respect t…
  Doc/howto/logging.rst
  Doc/howto/logging_flow.svg
Labels: docs, awaiting core review, skip news

#121320 [3.13] gh-121035: Further improve logging flow diagram with respect t…
  Doc/howto/logging.rst
  Doc/howto/logging_flow.svg
Labels: docs, awaiting core review, skip news

#121259 gh-121245: a regression test for site.register_readline()
  Lib/test/test_pyrepl/test_pyrepl.py
Labels: awaiting merge, skip news, needs backport to 3.13

#121322 [3.13] gh-121245: a regression test for site.register_readline() (GH-121259)
  Lib/test/test_pyrepl/test_pyrepl.py
Labels: tests, awaiting merge, skip news

#121319 [3.13] gh-121279: Fix importlib DeprecatedAttrsTests
  Lib/test/test_importlib/test_abc.py
Labels: tests, awaiting core review, skip news

#121324 [3.13] gh-121035: Update PNG image for logging flow diagram. (GH-121323)
  Doc/howto/logging_flow.png
Labels: docs, awaiting core review, skip news

#121325 [3.12] gh-121035: Update PNG image for logging flow diagram. (GH-121323)
  Doc/howto/logging_flow.png
Labels: docs, awaiting core review, skip news

#121280 gh-119726: emit AArch64 trampolines in the data section
  Misc/NEWS.d/next/Core and Builtins/2024-06-28-18-34-49.gh-issue-119726.Fjv_Ab.rst
  Tools/jit/_stencils.py
Labels: performance, awaiting merge, interpreter-core, topic-JIT

#121328 gh-121201: Disable perf_trampoline on riscv64 for now
  Misc/NEWS.d/next/Core and Builtins/2024-06-05-06-26-04.gh-issue-
  Misc/NEWS.d/next/Core and Builtins/2024-06-12-12-29-45.gh-issue-120400.lZYHVS.rst
  configure
  configure.ac
Labels: awaiting merge, needs backport to 3.13

#121302 gh-121300: Add `replace` to `copy.__all__`
  Lib/copy.py
  Lib/test/test_copy.py
Labels: awaiting merge, skip news, needs backport to 3.13

#121337 [3.13] gh-121300: Add `replace` to `copy.__all__` (GH-121302)
  Lib/copy.py
  Lib/test/test_copy.py
Labels: awaiting review, skip news

#121262 gh-112136: Restore removed _PyArg_Parser
  Include/cpython/modsupport.h
  Include/internal/pycore_lock.h
  Include/internal/pycore_modsupport.h
  Include/modsupport.h
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2024-07-02-11-03-40.gh-issue-112136.f3fiY8.rst
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: awaiting core review

#121344 [3.13] gh-112136: Restore removed _PyArg_Parser (GH-121262)
  Include/cpython/modsupport.h
  Include/internal/pycore_lock.h
  Include/internal/pycore_modsupport.h
  Include/modsupport.h
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2024-07-02-11-03-40.gh-issue-112136.f3fiY8.rst
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: awaiting review

#118725 gh-118714: Make the pdb post-mortem restart/quit behavior more reasonable
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2024-05-07-17-38-53.gh-issue-118714.XXKpVZ.rst
Labels: awaiting merge, needs backport to 3.13

#121346 [3.13] gh-118714: Make the pdb post-mortem restart/quit behavior more reasonable (GH-118725)
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2024-05-07-17-38-53.gh-issue-118714.XXKpVZ.rst
Labels: awaiting review

#120233 gh-117983: Defer import of threading for lazy module loading
  Lib/importlib/util.py
  Misc/NEWS.d/next/Library/2024-06-07-10-10-32.gh-issue-117983.NeMR9n.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#121350 [3.12] gh-117983: Defer import of threading for lazy module loading (GH-120233)
  Lib/importlib/util.py
  Misc/NEWS.d/next/Library/2024-06-07-10-10-32.gh-issue-117983.NeMR9n.rst
Labels: awaiting merge

#121349 [3.13] gh-117983: Defer import of threading for lazy module loading (GH-120233)
  Lib/importlib/util.py
  Misc/NEWS.d/next/Library/2024-06-07-10-10-32.gh-issue-117983.NeMR9n.rst
Labels: awaiting merge

#121162 gh-121141: add support for `copy.replace` to AST nodes
  Doc/whatsnew/3.14.rst
  Lib/test/test_ast.py
  Misc/NEWS.d/next/Library/2024-06-29-15-21-12.gh-issue-121141.4evD6q.rst
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: awaiting merge

#120755 gh-120754: Reduce system calls in full-file readall case
  Lib/_pyio.py
  Misc/NEWS.d/next/Core and Builtins/2024-06-19-19-54-35.gh-issue-120754.uF29sj.rst
  Modules/_io/fileio.c
Labels: awaiting merge

#121336 [3.13] gh-121201: Disable perf_trampoline on riscv64 for now (GH-121328)
  Misc/NEWS.d/next/Core and Builtins/2024-06-05-06-26-04.gh-issue-
  configure
  configure.ac
Labels: awaiting merge, skip news

#121353 gh-121352: use _Py_SourceLocation in symtable
  Include/internal/pycore_symtable.h
  Python/symtable.c
Labels: awaiting merge, skip news

#121357 gh-120754: Update estimated_size in C truncate
  Modules/_io/fileio.c
Labels: awaiting merge, skip news

#121356 gh-121355: Minor typo error in simple_stmts.rst
  Doc/reference/simple_stmts.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#121363 [3.12] gh-121355: Fix incorrect word in simple_stmts.rst (GH-121356)
  Doc/reference/simple_stmts.rst
Labels: docs, awaiting review, skip news

#121361 gh-121272: move async for/with validation from compiler to symtable
  Python/compile.c
  Python/symtable.c
Labels: awaiting merge, skip news

#121362 [3.13] gh-121355: Fix incorrect word in simple_stmts.rst (GH-121356)
  Doc/reference/simple_stmts.rst
Labels: docs, awaiting review, skip news

#120817 gh-118507: Amend news entry
  Misc/NEWS.d/next/Library/2024-05-08-18-33-07.gh-issue-118507.OCQsAY.rst
Labels: docs, awaiting review, needs backport to 3.13

#121233 gh-59110: zipimport: support namespace packages when no directory entry exists
  Lib/test/test_importlib/test_namespace_pkgs.py
  Lib/test/test_zipimport.py
  Lib/zipimport.py
  Misc/NEWS.d/next/Library/2024-07-04-17-36-03.gh-issue-59110.IlI9Fz.rst
Labels: awaiting core review

#121365 [3.13] gh-118507: Amend news entry to mention ntpath.isfile bugfix (GH-120817)
  Misc/NEWS.d/3.13.0b2.rst
Labels: docs, awaiting core review, skip news

#121369 gh-106597: Remove unnecessary CFrame offsets
  Include/internal/pycore_runtime.h
Labels: awaiting merge, skip news, needs backport to 3.13

#121360 gh-121084: Fix test_typing random leaks
  Lib/test/libregrtest/utils.py
  Misc/NEWS.d/next/Tests/2024-07-04-15-10-29.gh-issue-121084.qxcd5d.rst
Labels: awaiting merge

#121370 [3.13] gh-106597: Remove unnecessary CFrame offsets (GH-121369)
  Include/internal/pycore_runtime.h
Labels: awaiting review, skip news

#121372 [3.12] gh-121084: Fix test_typing random leaks (GH-121360)
  Lib/test/libregrtest/utils.py
  Misc/NEWS.d/next/Tests/2024-07-04-15-10-29.gh-issue-121084.qxcd5d.rst
Labels: awaiting review

#121373 [3.13] gh-121084: Fix test_typing random leaks (GH-121360)
  Lib/test/libregrtest/utils.py
  Misc/NEWS.d/next/Tests/2024-07-04-15-10-29.gh-issue-121084.qxcd5d.rst
Labels: awaiting review

#116309 gh-90437: Fix __main__.py documentation wording
  Doc/library/__main__.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#121386 [3.12] gh-90437: Fix __main__.py documentation wording (GH-116309)
  Doc/library/__main__.rst
Labels: docs, awaiting merge, skip news

#121385 [3.13] gh-90437: Fix __main__.py documentation wording (GH-116309)
  Doc/library/__main__.rst
Labels: docs, awaiting merge, skip news

#121391 gh-121390: tracemalloc: Fix tracebacks memory leak
  Python/tracemalloc.c
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#121393 [3.12] gh-121390: tracemalloc: Fix tracebacks memory leak (GH-121391)
  Python/tracemalloc.c
Labels: awaiting review, skip news

#121375 gh-59110: Fix a debug output for implicit directories
  Lib/zipimport.py
Labels: awaiting merge, skip news

#121176 gh-121149: improve accuracy of builtin sum() for complex inputs
  Doc/library/functions.rst
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2024-06-30-03-48-10.gh-issue-121149.lLBMKe.rst
  Python/bltinmodule.c
Labels: awaiting merge

#121384 Fixed an issue where building inside of a clone directory with spaces would result in not being able to build at all.
  PCbuild/regen.targets
Labels: skip issue, awaiting review, skip news, needs backport to 3.12, needs backport to 3.13

#121395 gh-121288: Make error message for index() methods consistent
  Lib/multiprocessing/shared_memory.py
  Misc/NEWS.d/next/Core and Builtins/2024-07-05-11-29-27.gh-issue-121288.lYKYYP.rst
  Modules/_collectionsmodule.c
  Objects/listobject.c
  Objects/rangeobject.c
Labels: awaiting merge

#121287 Update example of str.split, bytes.split
  Doc/library/stdtypes.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#121416 [3.12] Update example of str.split, bytes.split (GH-121287)
  Doc/library/stdtypes.rst
Labels: docs, skip issue, awaiting merge, skip news

#121415 [3.13] Update example of str.split, bytes.split (GH-121287)
  Doc/library/stdtypes.rst
Labels: docs, skip issue, awaiting merge, skip news

#121414 gh-121359: Run test_pyrepl in isolated mode
  Lib/test/test_pyrepl/test_pyrepl.py
Labels: tests, awaiting core review, skip news, needs backport to 3.13

#121417 [3.13] gh-121359: Run test_pyrepl in isolated mode (GH-121414)
  Lib/test/test_pyrepl/test_pyrepl.py
Labels: tests, awaiting review, skip news

#120806 GH-73991: Support preserving metadata in `pathlib.Path.copy()`
  Doc/library/pathlib.rst
  Lib/pathlib/_abc.py
  Lib/pathlib/_local.py
  Lib/pathlib/_os.py
  Lib/test/test_pathlib/test_pathlib.py
Labels: awaiting core review, skip news, topic-pathlib

#121430 [docs] fix a Sphinx directive in `c-api/object.rst`
  Doc/c-api/object.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.13

#121437 Regen ``Doc/requirements-oldest-sphinx.txt``
  Doc/requirements-oldest-sphinx.txt
Labels: docs, skip issue, awaiting review, skip news, needs backport to 3.12, needs backport to 3.13

#121442 [3.12] Regen ``Doc/requirements-oldest-sphinx.txt`` (GH-121437)
  Doc/requirements-oldest-sphinx.txt
Labels: skip issue, awaiting review, skip news

#121440 [3.13] [docs] fix a Sphinx directive in `c-api/object.rst` (GH-121430)
  Doc/c-api/object.rst
Labels: docs, skip issue, awaiting review, skip news

#121441 [3.13] Regen ``Doc/requirements-oldest-sphinx.txt`` (GH-121437)
  Doc/requirements-oldest-sphinx.txt
Labels: skip issue, awaiting review, skip news

#121341 gh-119909: Fix ``NameError`` in ``asyncio`` REPL
  Lib/asyncio/__main__.py
Labels: awaiting review, skip news, needs backport to 3.13

#121422 gh-121351: skip test_not_wiping_history_file() if no readline
  Lib/test/test_pyrepl/test_pyrepl.py
Labels: tests, awaiting merge, skip news

#121447 [3.13] gh-119909: Fix ``NameError`` in ``asyncio`` REPL (GH-121341)
  Lib/asyncio/__main__.py
Labels: awaiting review, skip news

#121449 [3.13] gh-121351: Skip test_not_wiping_history_file() if no readline (GH-121422)
  Lib/test/test_pyrepl/test_pyrepl.py
Labels: tests, awaiting review, skip news

#121455 Add Fidget-Spinner to stackrefs CODEOWNERS
  .github/CODEOWNERS
Labels: skip issue, awaiting merge, skip news

#121444 GH-73991: Fix "Operation not supported" on Fedora buildbot.
  Lib/test/test_pathlib/test_pathlib.py
Labels: tests, skip news, topic-pathlib

#121470 Fix sphinx reference target
  Misc/NEWS.d/next/Library/2024-06-29-19-30-15.gh-issue-121163.SJKDFq.rst
Labels: docs, skip issue, awaiting core review, skip news

#121469 gh-121467: Fix makefile to include mimalloc headers
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2024-07-08-01-11-54.gh-issue-121467.3qWRQj.rst
Labels: awaiting merge, needs backport to 3.13

#121471 [3.13] gh-121467: Fix makefile to include mimalloc headers (GH-121469)
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2024-07-08-01-11-54.gh-issue-121467.3qWRQj.rst
Labels: awaiting review

#121466 gh-121461: Fix os.path.normpath documentation indentation
  Doc/library/os.path.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#121473 [3.12] gh-121461: Fix os.path.normpath documentation indentation (GH-121466)
  Doc/library/os.path.rst
Labels: docs, awaiting review, skip news

#121472 [3.13] gh-121461: Fix os.path.normpath documentation indentation (GH-121466)
  Doc/library/os.path.rst
Labels: docs, awaiting review, skip news

#121475 gh-108297: Update crashers README for test_crashers removal
  Lib/test/crashers/README
Labels: awaiting core review, skip news, needs backport to 3.13

#121476 [3.13] gh-108297: Update crashers README for test_crashers removal (GH-121475)
  Lib/test/crashers/README
Labels: awaiting review, skip news

#121411 [3.13] Fixed regenerating files in a checkout path with spaces (GH-121384)
  PCbuild/regen.targets
Labels: skip issue, awaiting review, skip news

#121483 GH-121012: Set index to -1 when list iterators become exhausted in tier 2
  Lib/test/test_list.py
  Misc/NEWS.d/next/Core and Builtins/2024-07-08-10-31-08.gh-issue-121012.M5hHk-.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
Labels: awaiting merge, needs backport to 3.13

#121492 [3.13] gh-121338: Remove GH-pragma optimize (GH-121340)
  Python/ceval.c
Labels: awaiting review, skip news

#121418 gh-121374: Correct docstrings in `_interpchannels`
  Modules/_interpchannelsmodule.c
Labels: awaiting merge, skip news, needs backport to 3.13

#121435 GH-119169: Simplify `os.walk()` exception handling
  Lib/os.py
  Misc/NEWS.d/next/Library/2024-07-06-16-08-39.gh-issue-119169.o0YymL.rst
Labels: performance, awaiting merge

#121501 [3.13] gh-121374: Correct docstrings in `_interpchannels` (gh-121418)
  Modules/_interpchannelsmodule.c
Labels: awaiting review, skip news

#121494 [3.13] GH-121012: Set index to -1 when list iterators become exhausted in tier 2 (GH-121483)
  Lib/test/test_list.py
  Misc/NEWS.d/next/Core and Builtins/2024-07-08-10-31-08.gh-issue-121012.M5hHk-.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
Labels: awaiting review

#121488 gh-121487: Fix deprecation warning for ATOMIC_VAR_INIT in mimalloc
  Include/internal/mimalloc/mimalloc/atomic.h
  Misc/NEWS.d/next/Build/2024-07-08-14-01-17.gh-issue-121487.ekHmpR.rst
Labels: awaiting merge, needs backport to 3.13

#121388 gh-121368: Fix seq lock memory ordering in _PyType_Lookup
  Include/cpython/pyatomic.h
  Include/cpython/pyatomic_gcc.h
  Include/cpython/pyatomic_msc.h
  Include/cpython/pyatomic_std.h
  Include/internal/pycore_lock.h
  Misc/NEWS.d/next/Core and Builtins/2024-07-04-23-38-30.gh-issue-121368.m3EF9E.rst
  Modules/_testcapi/pyatomic.c
  Objects/typeobject.c
  Python/lock.c
Labels: awaiting core review, topic-free-threading, needs backport to 3.13

#121504 [3.13] gh-121487: Fix deprecation warning for ATOMIC_VAR_INIT in mimalloc (gh-121488)
  Include/internal/mimalloc/mimalloc/atomic.h
  Misc/NEWS.d/next/Build/2024-07-08-14-01-17.gh-issue-121487.ekHmpR.rst
Labels: awaiting review

#121505 [3.13] gh-121368: Fix seq lock memory ordering in _PyType_Lookup (GH-121388)
  Include/cpython/pyatomic.h
  Include/cpython/pyatomic_gcc.h
  Include/cpython/pyatomic_msc.h
  Include/cpython/pyatomic_std.h
  Include/internal/pycore_lock.h
  Misc/NEWS.d/next/Core and Builtins/2024-07-04-23-38-30.gh-issue-121368.m3EF9E.rst
  Modules/_testcapi/pyatomic.c
  Objects/typeobject.c
  Python/lock.c
Labels: awaiting review, topic-free-threading

#121500 gh-121404: remove direct accesses to u_private from codegen functions
  Python/compile.c
Labels: awaiting merge, skip news

#121482 NEWS: Fix Sphinx warnings and increase threshold for new news nits
  Doc/conf.py
  Doc/library/profile.rst
  Doc/tools/check-warnings.py
  Doc/whatsnew/3.4.rst
  Doc/whatsnew/3.5.rst
  Doc/whatsnew/3.7.rst
  Misc/HISTORY
  Misc/NEWS.d/3.10.0a1.rst
  Misc/NEWS.d/3.10.0a2.rst
  Misc/NEWS.d/3.10.0a3.rst
  Misc/NEWS.d/3.10.0a4.rst
  Misc/NEWS.d/3.10.0a5.rst
  Misc/NEWS.d/3.10.0a6.rst
  Misc/NEWS.d/3.10.0a7.rst
  Misc/NEWS.d/3.10.0b1.rst
  Misc/NEWS.d/3.11.0a1.rst
  Misc/NEWS.d/3.11.0a2.rst
  Misc/NEWS.d/3.11.0a3.rst
  Misc/NEWS.d/3.11.0a4.rst
  Misc/NEWS.d/3.11.0b1.rst
  Misc/NEWS.d/3.12.0a1.rst
  Misc/NEWS.d/3.12.0a2.rst
  Misc/NEWS.d/3.12.0a3.rst
  Misc/NEWS.d/3.12.0a4.rst
  Misc/NEWS.d/3.12.0b1.rst
  Misc/NEWS.d/3.13.0a1.rst
  Misc/NEWS.d/3.13.0a2.rst
  Misc/NEWS.d/3.13.0a3.rst
  Misc/NEWS.d/3.13.0a5.rst
  Misc/NEWS.d/3.13.0a6.rst
  Misc/NEWS.d/3.13.0b1.rst
  Misc/NEWS.d/3.5.0a1.rst
  Misc/NEWS.d/3.6.0a1.rst
  Misc/NEWS.d/3.8.0a1.rst
  Misc/NEWS.d/3.8.0a4.rst
  Misc/NEWS.d/3.8.0b1.rst
  Misc/NEWS.d/3.9.0a1.rst
  Misc/NEWS.d/3.9.0a6.rst
  Misc/NEWS.d/next/Library/2023-04-24-05-34-23.gh-issue-103194.GwBwWL.rst
Labels: docs, skip issue, awaiting merge, needs backport to 3.12, needs backport to 3.13

#121510 gh-121018: Fix typo in NEWS entry
  Misc/NEWS.d/next/Library/2024-06-26-03-04-24.gh-issue-121018.clVSc4.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#121503 gh-121110: Fix Extension Module Tests Under Py_TRACE_REFS Builds
  Lib/test/test_import/__init__.py
  Python/import.c
Labels: awaiting core review, skip news, needs backport to 3.13

#121516 [3.12] gh-121018: Fix typo in NEWS entry (GH-121510)
  Misc/NEWS.d/next/Library/2024-06-26-03-04-24.gh-issue-121018.clVSc4.rst
Labels: docs, awaiting core review, skip news

#121517 [3.13] gh-121110: Fix Extension Module Tests Under Py_TRACE_REFS Builds (gh-121503)
  Lib/test/test_import/__init__.py
  Python/import.c
Labels: awaiting review, skip news

#121335 gh-121333: Clarify what is the default executor for asyncio.run_in_executor
  Doc/library/asyncio-eventloop.rst
Labels: docs, awaiting merge, skip news

#121526 [3.13] gh-121333: Clarify what is the default executor for asyncio.run_in_executor (GH-121335)
  Doc/library/asyncio-eventloop.rst
Labels: docs, awaiting merge, skip news

#121496 GH-118926: Better distinguish between pointer and arrays in interpreter generator
  Lib/test/test_generated_cases.py
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/parsing.py
  Tools/cases_generator/stack.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#121532 [3.13] Docs: fix typo and duplicate word in configure.rst (GH-121410)
  Doc/using/configure.rst
Labels: docs, skip issue, awaiting review, skip news

#121534 gh-121533: Improve `PyCell_[Get,Set]` docs: mention the exceptions
  Doc/c-api/cell.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#121540 [3.12] gh-121533: Improve `PyCell_[Get,Set]` docs: mention the exceptions (GH-121534)
  Doc/c-api/cell.rst
Labels: docs, awaiting review, skip news
