Repository python/cpython, pull requests merged in 2024-10, with the labels that each got.

#124810 gh-124309: Revert eager task factory fix to prevent breaking downstream
  Lib/asyncio/base_events.py
  Lib/asyncio/staggered.py
  Lib/test/test_asyncio/test_eager_task_factory.py
  Lib/test/test_asyncio/test_staggered.py
  Misc/NEWS.d/next/Library/2024-09-23-18-18-23.gh-issue-124309.iFcarA.rst
Labels: awaiting merge, skip news, release-blocker, needs backport to 3.12

#124812 [3.13] gh-124785: Revert "gh-116510: Fix crash due to shared immortal interned strings (gh-124646)" (gh-124807)
  Misc/NEWS.d/next/Core_and_Builtins/2024-09-26-18-21-06.gh-issue-116510.FacUWO.rst
  Objects/unicodeobject.c
Labels: awaiting review

#124738 [3.13] gh-124442: make `__static_attributes__` deterministic by sorting (GH-124492)
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-09-25-11-53-22.gh-issue-124442.EXC1Ve.rst
  Python/compile.c
Labels: awaiting core review

#124814 [3.12] gh-124785: Revert "[3.12] gh-116510: Fix a crash due to shared immortal interned strings. (gh-124541)"
  Misc/NEWS.d/next/Core_and_Builtins/2024-09-25-12-37-58.gh-issue-116510.WeBAx1.rst
  Objects/unicodeobject.c
Labels: awaiting core review, 3.12

#124817 [3.12] gh-124309: Revert eager task factory fix to prevent breaking downstream (GH-124810)
  Lib/asyncio/base_events.py
  Lib/asyncio/staggered.py
  Lib/test/test_asyncio/test_eager_task_factory.py
  Lib/test/test_asyncio/test_staggered.py
  Misc/NEWS.d/next/Library/2024-09-23-18-18-23.gh-issue-124309.iFcarA.rst
Labels: awaiting merge, skip news

#124827 GH-109975: Copyedit 3.13 What's New: Note delayed expected release date for Python 3.13.0
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13

#124831 GH-109975: Copyedit 3.13 What's New: Link to installing free-threaded binaries on macOS
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13

#124826 Doc: Fix archive filenames for standard builds
  Doc/Makefile
  Doc/tools/extensions/patchlevel.py
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#124595 gh-124594: Create and reuse one context for the entire asyncio REPL session
  Lib/asyncio/__main__.py
  Lib/test/test_repl.py
  Misc/NEWS.d/next/Library/2024-09-26-13-43-39.gh-issue-124594.peYhsP.rst
Labels: topic-asyncio, awaiting merge, needs backport to 3.12, needs backport to 3.13

#124843 gh-124842: Fix test.support.import_helper.make_legacy_pyc()
  Lib/test/support/import_helper.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#124854 [3.12] gh-124842: Fix test.support.import_helper.make_legacy_pyc() (GH-124843)
  Lib/test/support/import_helper.py
Labels: awaiting review, skip news

#124472 gh-124296: Remove private dictionary version tag (PEP 699)
  Include/cpython/dictobject.h
  Include/internal/pycore_dict.h
  Include/internal/pycore_dict_state.h
  Lib/test/test_dict_version.py
  Lib/test/test_free_threading/test_dict.py
  Misc/NEWS.d/next/C_API/2024-09-24-20-34-21.gh-issue-124296.S4QoS1.rst
  Modules/_testcapi/dict.c
  Modules/_testcapimodule.c
  Objects/dictobject.c
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_analysis.c
Labels: awaiting merge

#124844 gh-124218: Refactor per-thread reference counting
  Include/internal/pycore_interp.h
  Include/internal/pycore_object.h
  Include/internal/pycore_tstate.h
  Include/internal/pycore_typeid.h
  Include/internal/pycore_uniqueid.h
  Makefile.pre.in
  Objects/typeobject.c
  PCbuild/_freeze_module.vcxproj
  PCbuild/_freeze_module.vcxproj.filters
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/gc_free_threading.c
  Python/pylifecycle.c
  Python/pystate.c
  Python/uniqueid.c
Labels: awaiting core review, skip news, topic-free-threading

#124568 gh-116750: Add clear_tool_id function to unregister events and callbacks
  Doc/library/sys.monitoring.rst
  Include/cpython/code.h
  Include/internal/pycore_interp.h
  Lib/test/test_monitoring.py
  Misc/NEWS.d/next/Library/2024-09-26-00-35-24.gh-issue-116750.X1aMHI.rst
  Python/clinic/instrumentation.c.h
  Python/instrumentation.c
  Python/pystate.c
Labels: awaiting merge

#124811 Highlight `datetime.timedelta.seconds` vs `.total_seconds()` in docs.
  Doc/library/datetime.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#124799 gh-66436: Improved prog default value for argparse.ArgumentParser
  Doc/library/argparse.rst
  Doc/whatsnew/3.14.rst
  Lib/argparse.py
  Lib/test/test_argparse.py
  Lib/test/test_calendar.py
  Misc/NEWS.d/next/Library/2024-09-30-19-59-28.gh-issue-66436.4gYN_n.rst
Labels: awaiting merge

#124866 Minor code beautifications in statistics.py
  Lib/statistics.py
Labels: skip issue, awaiting core review, skip news

#124587 gh-124835: `tomllib.loads`: Raise TypeError not AttributeError. Improve message
  Lib/test/test_tomllib/test_error.py
  Lib/tomllib/_parser.py
  Misc/NEWS.d/next/Library/2024-10-01-12-43-42.gh-issue-124835.SVyp3K.rst
Labels: awaiting merge

#124863 [3.12] Highlight `datetime.timedelta.seconds` vs `.total_seconds()` in docs. (GH-124811)
  Doc/library/datetime.rst
Labels: docs, skip issue, awaiting review, skip news

#124782 gh-58282: Fix support of tuple metavar for positional arguments in argparse
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2018-12-04-07-36-27.bpo-14074.fMLKCu.rst
Labels: awaiting core review, needs backport to 3.12, needs backport to 3.13

#124881 [3.12] gh-58282: Fix support of tuple metavar for positional arguments in argparse (GH-124782)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2018-12-04-07-36-27.bpo-14074.fMLKCu.rst
Labels: awaiting review

#124821 GH-124820: Move `-mno-outline-atomics` flag to aarch64 Linux JIT builds only
  Tools/jit/_targets.py
Labels: awaiting merge, skip news

#124845 gh-122864: Fix a ``test_funcattrs.test___builtins__`` when executing directly
  Lib/test/test_funcattrs.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#124885 [3.12] gh-122864: Fix a ``test_funcattrs.test___builtins__`` when executing directly (GH-124845)
  Lib/test/test_funcattrs.py
Labels: tests, awaiting review, skip news

#124806 gh-111178: Fix function signatures in bytesobject.c
  Objects/bytesobject.c
Labels: awaiting core review, skip news

#124804 gh-111178: Fix function signatures in tupleobject.c
  Objects/tupleobject.c
Labels: awaiting core review, skip news

#124891 gh-85935: Improve tests for invalid arguments in test_argparse
  Lib/test/test_argparse.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#124896 gh-111178: Fix locale_free() signature
  Modules/_localemodule.c
Labels: awaiting core review, skip news

#124888 gh-111178: Fix function signatures in setobject.c
  Objects/setobject.c
Labels: awaiting core review, skip news

#124900 gh-111178: Fix function signatures in moduleobject.c
  Include/internal/pycore_moduleobject.h
  Objects/moduleobject.c
Labels: awaiting core review, skip news

#124898 [3.12] gh-85935: Improve tests for invalid arguments in test_argparse (GH-124891)
  Lib/test/test_argparse.py
Labels: tests, awaiting review, skip news

#124555 gh-120378: Fix crash caused by integer overflow in `curses`
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2024-09-25-18-07-51.gh-issue-120378.NlBSz_.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#124892 gh-124213: Fix incorrect context manager use in in_systemd_nspawn_sync_suppressed()
  Lib/test/support/__init__.py
Labels: awaiting merge, skip news

#124903 gh-111178: Fix function signatures in weakrefobject.c
  Include/cpython/weakrefobject.h
  Objects/weakrefobject.c
Labels: awaiting core review, skip news

#124902 gh-111178: Fix function signatures in methodobject.c
  Objects/methodobject.c
Labels: awaiting core review, skip news

#124895 gh-111178: Fix function signatures in longobject.c
  Include/cpython/longobject.h
  Objects/longobject.c
Labels: awaiting core review, skip news

#105805 gh-87135: Hang non-main threads that attempt to acquire the GIL during finalization
  Doc/c-api/init.rst
  Include/internal/pycore_pythread.h
  Include/pythread.h
  Lib/test/test_threading.py
  Misc/NEWS.d/next/C API/2022-08-05-19-41-20.gh-issue-87135.SCNBYj.rst
  Modules/_testcapimodule.c
  Python/ceval_gil.c
  Python/pylifecycle.c
  Python/thread_nt.h
  Python/thread_pthread.h
Labels: awaiting review

#124518 gh-120619: Optimize through `_Py_FRAME_GENERAL`
  Python/optimizer_analysis.c
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, skip news

#124908 gh-111178: Fix function signatures in funcobject.c
  Objects/funcobject.c
Labels: awaiting core review, skip news

#124427 [3.12] gh-123978: Remove broken time.thread_time() on NetBSD (GH-124116)
  Misc/NEWS.d/next/Library/2024-09-16-12-31-48.gh-issue-123978.z3smEu.rst
  Modules/timemodule.c
Labels: type-bug, awaiting merge

#123872 gh-119726: generate and patch AArch64 trampolines
  Misc/NEWS.d/next/Core_and_Builtins/2024-09-19-16-57-34.gh-issue-119726.DseseK.rst
  Python/jit.c
  Tools/jit/_stencils.py
  Tools/jit/_targets.py
  Tools/jit/_writer.py
Labels: performance, awaiting review, interpreter-core, topic-JIT

#124859 gh-124858: fix happy eyeballs refcyles
  Lib/asyncio/base_events.py
  Lib/asyncio/staggered.py
  Lib/test/test_asyncio/test_streams.py
  Misc/NEWS.d/next/Library/2024-10-01-17-12-20.gh-issue-124858.Zy0tvT.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#121983 gh-121982: csv module: Test invalid quoting constant
  Lib/test/test_csv.py
Labels: tests, awaiting merge, skip news

#124925 [3.12] gh-121982: ``csv``: Add a test case for invalid ``quoting`` constant. (GH-121983)
  Lib/test/test_csv.py
Labels: tests, awaiting review, skip news

#124920 gh-115145: Update documentation about ``PyThreadState_DeleteCurrent``
  Doc/c-api/init.rst
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#124931 [3.12] gh-115145: Update documentation about ``PyThreadState_DeleteCurrent`` (gh-124920)
  Doc/c-api/init.rst
Labels: docs, skip news

#124907 gh-123961: Improve curses C API cleanup
  Modules/_cursesmodule.c
Labels: awaiting merge, skip news

#124893 gh-124889: Remove redundant artificial rules in PEG parser
  Parser/parser.c
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/parser_generator.py
Labels: awaiting merge, skip news

#124930 [3.13] gh-115145: Update documentation about ``PyThreadState_DeleteCurrent`` (gh-124920)
  Doc/c-api/init.rst
Labels: docs, awaiting review, skip news

#124836 [3.13] Doc: Fix archive filenames for standard builds (GH-124826)
  Doc/Makefile
  Doc/tools/extensions/patchlevel.py
Labels: skip issue, awaiting merge, skip news

#124828 [3.13] GH-109975: Copyedit 3.13 What's New: Note delayed expected release date for Python 3.13.0 (GH-124827)
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting merge, skip news

#124833 [3.13] GH-109975: Copyedit 3.13 What's New: Link to installing free-threaded binaries on macOS (GH-124831)
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting merge, skip news

#124860 [3.13] gh-124370: Add "howto" for free-threaded Python (GH-124371)
  Doc/howto/free-threading-python.rst
  Doc/howto/index.rst
  Doc/reference/datamodel.rst
Labels: docs, awaiting merge, skip news, topic-free-threading

#124862 [3.13] Highlight `datetime.timedelta.seconds` vs `.total_seconds()` in docs. (GH-124811)
  Doc/library/datetime.rst
Labels: docs, skip issue, awaiting merge, skip news

#124884 [3.13] gh-122864: Fix a ``test_funcattrs.test___builtins__`` when executing directly (GH-124845)
  Lib/test/test_funcattrs.py
Labels: tests, awaiting merge, skip news

#124926 [3.13] gh-121982: ``csv``: Add a test case for invalid ``quoting`` constant. (GH-121983)
  Lib/test/test_csv.py
Labels: tests, awaiting merge, skip news

#124941 Simplify partial() rough equivalent code
  Doc/library/functools.rst
Labels: docs, skip issue, awaiting merge, skip news, 3.14

#124947 GH-109975: Copyedit 3.13 What's New: Remove references to the incremental GC
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting core review, skip news

#124794 gh-124613: Deactivate perf support in tests if the jit is set
  Lib/test/test_perf_profiler.py
Labels: awaiting merge, skip news

#124934 gh-123961: convert `curses.window` static type into a heap type
  Misc/NEWS.d/next/C_API/2024-10-03-14-06-08.gh-issue-123961.uwJQTY.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: awaiting merge

#124942 gh-111178: Fix function signatures in Python-ast.c
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: awaiting merge, skip news

#124940 gh-111178: Fix function signatures in bytearrayobject.c
  Objects/bytearrayobject.c
Labels: awaiting core review, skip news

#124943 gh-111178: Fix function signatures in classobject.c
  Objects/classobject.c
Labels: awaiting core review, skip news

#124830 gh-109975: nntplib is not on PyPI so propose pynntp
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13

#124964 gh-111178: Fix function signatures in _threadmodule.c
  Modules/_threadmodule.c
Labels: awaiting core review, skip news

#124598 gh-118658: Modify cert generation script to extract cert3.pem
  Lib/test/certdata/cert3.pem
  Lib/test/certdata/make_ssl_certs.py
Labels: awaiting merge, skip news, topic-SSL, needs backport to 3.13

#124968 Fix console prompt syntax in What's New in Python 3.8
  Doc/whatsnew/3.8.rst
Labels: docs, skip issue, awaiting merge, skip news

#124971 gh-124962: Convert leftover rst to markup in `InternalDocs/compiler.md`
  InternalDocs/compiler.md
Labels: awaiting merge, skip news

#124938 [3.12] gh-113993: For string interning, do not rely on (or assert) _Py_IsImmortal (GH-121358) (GH-121851)
  Misc/NEWS.d/next/C API/2024-07-04-13-23-27.gh-issue-113601.K3RLqp.rst
  Objects/unicodeobject.c
Labels: awaiting core review

#124952 gh-124871: fix 'visited' tracking in compiler's reachability analysis
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2024-10-03-22-26-39.gh-issue-124871.tAMF47.rst
  Python/flowgraph.c
Labels: type-bug, awaiting merge, needs backport to 3.13

#124966 [3.13] gh-109975: Suggest ``pynntp`` instead of ``nntplib`` (GH-124830)
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting merge, skip news

#124977 [3.13] gh-124871: fix 'visited' tracking in compiler's reachability analysis (GH-124952)
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2024-10-03-22-26-39.gh-issue-124871.tAMF47.rst
  Python/flowgraph.c
Labels: type-bug, awaiting merge, release-blocker

#124989 gh-119786: move a few more details on exception handling from devguide to InternalDocs
  InternalDocs/exception_handling.md
Labels: docs, awaiting merge, skip news

#119783 gh-117151: increase default buffer size of shutil.copyfileobj() to 256k.
  Lib/shutil.py
  Misc/NEWS.d/next/Library/2024-10-03-05-00-25.gh-issue-117151.Prdw_W.rst
Labels: awaiting merge

#124990 gh-119786: Replace a Sphinx role with literal syntax
  InternalDocs/exception_handling.md
Labels: docs, awaiting merge, skip news

#124553 gh-124552 : Improve the accuracy of possible breakpoint check in bdb
  Lib/bdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2024-09-25-22-06-52.gh-issue-124552.1nQKNM.rst
Labels: awaiting merge

#124914 gh-112804: Clamping timeout value for _PySemaphore_PlatformWait
  Python/parking_lot.c
Labels: awaiting merge, skip news, needs backport to 3.13

#124970 gh-111178: Fix function signatures in genobject.c
  Objects/genobject.c
Labels: awaiting merge, skip news

#124998 gh-122951: Simplify the grammar of the assignment rule
  Grammar/python.gram
  Parser/parser.c
Labels: awaiting merge, skip news

#125013 gh-125008: Fix `tokenize.untokenize` roundtrip for `\n{{`
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-10-05-23-53-06.gh-issue-125008.ETANpd.rst
Labels: awaiting review, needs backport to 3.12, needs backport to 3.13

#125021 [3.12] gh-125008: Fix `tokenize.untokenize` roundtrip for `\n{{` (GH-125013)
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-10-05-23-53-06.gh-issue-125008.ETANpd.rst
Labels: awaiting merge

#125020 [3.13] gh-125008: Fix `tokenize.untokenize` roundtrip for `\n{{` (GH-125013)
  Lib/test/test_tokenize.py
  Lib/tokenize.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-10-05-23-53-06.gh-issue-125008.ETANpd.rst
Labels: awaiting merge

#119536 gh-119535: python𝜋
  Lib/venv/__init__.py
Labels: awaiting merge, skip news

#125015 gh-125010: Fix `use-after-free` in AST `repr()`
  Lib/test/test_ast/test_ast.py
  Parser/asdl_c.py
  Python/Python-ast.c
Labels: awaiting merge, skip news

#124988 Doc: Simplify the definition of 'soft deprecated'
  Doc/glossary.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#125030 [3.12] Doc: Simplify the definition of 'soft deprecated' (GH-124988)
  Doc/glossary.rst
Labels: docs, skip issue, awaiting core review, skip news

#125026 gh-125025: `_thread` docs: fix/update the *caveats* list
  Doc/library/_thread.rst
Labels: docs, awaiting merge, skip news

#125031 [3.12] gh-125025: `_thread` docs: fix/update the *caveats* list (GH-125026)
  Doc/library/_thread.rst
Labels: docs, awaiting review, skip news

#125029 [3.13] Doc: Simplify the definition of 'soft deprecated' (GH-124988)
  Doc/glossary.rst
Labels: docs, skip issue, awaiting merge, skip news

#125007 GH-109975: Announce final release in What's New in Python 3.13
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#125032 [3.13] gh-125025: `_thread` docs: fix/update the *caveats* list (GH-125026)
  Doc/library/_thread.rst
Labels: docs, awaiting review, skip news

#125033 [3.13] GH-109975: Announce final release in What's New in Python 3.13 (GH-125007)
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting review, skip news

#124469 GH-116968: Remove branch from advance_backoff_counter
  Include/internal/pycore_backoff.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/instrumentation.c
Labels: awaiting merge, skip news

#121613 gh-121249: Support _Complex types in the struct module
  Doc/library/struct.rst
  Lib/ctypes/__init__.py
  Lib/test/test_struct.py
  Misc/NEWS.d/next/Library/2024-07-10-08-13-34.gh-issue-121249.W9Gd09.rst
  Modules/_struct.c
Labels: awaiting merge

#125043 gh-111178: Fix function signatures in fileio.c
  Modules/_io/fileio.c
Labels: awaiting core review, skip news

#125027 gh-125018: Add importlib.metadata semantic link targets
  Doc/library/importlib.metadata.rst
  Misc/NEWS.d/next/Documentation/2024-10-07-00-31-17.gh-issue-125018.yKnymn.rst
Labels: docs, awaiting core review, needs backport to 3.12, needs backport to 3.13

#124392 GH-119866: Spill before escaping calls in all cases.
  Include/internal/pycore_ceval.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/test/test_asyncio/test_streams.py
  Lib/test/test_generated_cases.py
  Lib/test/test_monitoring.py
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/cwriter.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/lexer.py
  Tools/cases_generator/optimizer_generator.py
  Tools/cases_generator/stack.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#125048 [3.12] gh-125018: Add importlib.metadata semantic link targets (GH-125027)
  Doc/library/importlib.metadata.rst
  Misc/NEWS.d/next/Documentation/2024-10-07-00-31-17.gh-issue-125018.yKnymn.rst
Labels: docs, awaiting core review

#125045 gh-120762: make_ssl_certs: Don't set extensions for the temporary CSR
  Lib/test/certdata/make_ssl_certs.py
Labels: awaiting merge, skip news

#125050 gh-125018: Fix role syntax
  Doc/library/importlib.metadata.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#124991 [3.13] gh-112804: Clamping timeout value for _PySemaphore_PlatformWait (gh-124914)
  Python/parking_lot.c
Labels: awaiting merge, skip news

#125055 [3.12] gh-125018: Fix role syntax (GH-125050)
  Doc/library/importlib.metadata.rst
Labels: docs, awaiting review, skip news

#124894 GH-121459: Streamline PyObject* to PyStackRef conversions by disallowing NULL pointers.
  Include/internal/pycore_stackref.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#124957 gh-124956: Use `#undef` for temp macros in `_csv.c`
  Modules/_csv.c
Labels: awaiting merge, skip news

#124335 gh-124182: Explain naming rules for struct sequence types
  Doc/c-api/tuple.rst
Labels: docs, awaiting merge, skip news

#125044 Use _PyLong_GetOne() and _PyLong_GetZero() in long_invmod()
  Objects/longobject.c
Labels: skip issue, awaiting merge, skip news

#125056 [3.12] gh-124182: Explain naming rules for struct sequence types (GH-124335)
  Doc/c-api/tuple.rst
Labels: docs, awaiting review, skip news

#124897 gh-124653: relax (again) detection of queue API for logging handlers
  Doc/library/logging.config.rst
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-10-02-15-05-45.gh-issue-124653.tqsTu9.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#125034 [3.12] GH-109975: Announce final release in What's New in Python 3.13 (GH-125007)
  Doc/whatsnew/3.12.rst
Labels: docs, awaiting merge, skip news

#124975 gh-122392: Fix the wrong size of the Path Browser vertical spacing for IDLE (#122392)
  Lib/idlelib/tree.py
  Misc/NEWS.d/next/IDLE/2024-10-04-15-34-34.gh-issue-122392.V8K3w2.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#125062 [3.12] gh-122392: IDLE - Fix overlapping lines in browsers (GH-122392) (GH-124975)
  Lib/idlelib/tree.py
  Misc/NEWS.d/next/IDLE/2024-10-04-15-34-34.gh-issue-122392.V8K3w2.rst
Labels: awaiting review

#125061 [3.13] gh-122392: IDLE - Fix overlapping lines in browsers (GH-122392) (GH-124975)
  Lib/idlelib/tree.py
  Misc/NEWS.d/next/IDLE/2024-10-04-15-34-34.gh-issue-122392.V8K3w2.rst
Labels: awaiting review

#124418 [3.13] gh-63143: Fix parsing mutually exclusive arguments in argparse (GH-124307)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-21-23-56-41.gh-issue-63143.YKu-LQ.rst
Labels: awaiting merge

#124423 [3.13] gh-124188: Fix PyErr_ProgramTextObject() (GH-124189)
  Lib/test/support/script_helper.py
  Lib/test/test_compiler_codegen.py
  Lib/test/test_eof.py
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-09-17-22-06-01.gh-issue-124188.aFqNAB.rst
  Python/errors.c
Labels: awaiting review

#124436 [3.13] gh-59317: Improve parsing optional positional arguments in argparse (GH-124303)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-21-19-02-37.gh-issue-59317.OAhNZZ.rst
Labels: awaiting merge

#124504 gh-124502: Add PyUnicode_Equal() function
  Doc/c-api/unicode.rst
  Doc/data/stable_abi.dat
  Doc/whatsnew/3.14.rst
  Include/unicodeobject.h
  Lib/test/test_capi/test_unicode.py
  Lib/test/test_stable_abi_ctypes.py
  Misc/NEWS.d/next/C_API/2024-09-25-11-44-02.gh-issue-124502.qWuDjT.rst
  Misc/stable_abi.toml
  Modules/_testlimitedcapi/unicode.c
  Objects/unicodeobject.c
  PC/python3dll.c
Labels: awaiting core review

#124749 [3.13] gh-104860: Fix allow_abbrev=False for single-dash long options (GH-124340)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-23-17-33-47.gh-issue-104860.O86OSc.rst
Labels: awaiting merge

#124751 [3.13] gh-80259: Fix conflict between type and default=SUPPRESS in argparse (GH-124519)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-25-18-08-29.gh-issue-80259.kO5Tw7.rst
Labels: awaiting merge

#124753 [3.13] gh-124345: Support abbreviated single-dash long options with = in argparse (GH-124428)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-24-12-34-48.gh-issue-124345.s3vKql.rst
Labels: awaiting merge

#124757 [3.13] gh-116850: Fix argparse for namespaces with not directly writable dict (GH-124667)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-27-15-16-04.gh-issue-116850.dBkR0-.rst
Labels: awaiting merge

#124755 [3.13] gh-61181: Fix support of choices with string value in argparse (GH-124578)
  Doc/library/argparse.rst
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-26-09-18-09.gh-issue-61181.dwjmch.rst
Labels: awaiting merge

#124853 [3.13] gh-124842: Fix test.support.import_helper.make_legacy_pyc() (GH-124843)
  Lib/test/support/import_helper.py
Labels: awaiting review, skip news

#125068 [3.13] gh-95468: Add more tests for "--" (double dash) in test_argparse (GH-124274)
  Lib/test/test_argparse.py
Labels: tests, awaiting review, skip news

#123866 [3.13] Fix typos (#123775)
  Android/testbed/app/src/main/c/main_activity.c
  Lib/enum.py
  Lib/test/decimaltestdata/ddFMA.decTest
  Lib/test/decimaltestdata/ddQuantize.decTest
  Lib/test/decimaltestdata/ddRemainder.decTest
  Lib/test/decimaltestdata/ddRemainderNear.decTest
  Lib/test/decimaltestdata/dqRemainder.decTest
  Lib/test/decimaltestdata/dqRemainderNear.decTest
  Lib/test/decimaltestdata/exp.decTest
  Lib/test/decimaltestdata/remainder.decTest
  Lib/test/decimaltestdata/remainderNear.decTest
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/utils.py
  Lib/test/mathdata/ieee754.txt
  Lib/test/pickletester.py
  Lib/test/test_class.py
  Lib/test/test_concurrent_futures/test_deadlock.py
  Lib/test/test_enum.py
  Lib/test/test_fractions.py
  Lib/test/test_free_threading/test_monitoring.py
  Lib/test/test_fstring.py
  Lib/test/test_getpath.py
  Lib/test/test_logging.py
  Lib/test/test_math.py
  Lib/test/test_msvcrt.py
  Lib/test/test_posix.py
  Lib/test/test_property.py
  Lib/test/test_queue.py
  Lib/test/test_socket.py
  Lib/test/test_string_literals.py
  Lib/test/test_zipfile/test_core.py
  Lib/test/test_zipimport.py
  Lib/turtledemo/sorting_animate.py
  Makefile.pre.in
  Misc/coverity_model.c
  Modules/_threadmodule.c
  Objects/mimalloc/bitmap.h
  Objects/mimalloc/init.c
  Objects/mimalloc/segment-map.c
  Tools/c-analyzer/c_parser/preprocessor/gcc.py
  configure
  configure.ac
Labels: skip issue, awaiting merge, skip news

#124242 [3.13] Support the "pager" binary in _pyrepl (GH-122878)
  Lib/_pyrepl/pager.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-09-19-13-17-31.gh-issue-122878.4iFpsB.rst
Labels: skip issue, awaiting merge

#124282 [3.13] gh-124217, ipaddress: Add RFC 9637 reserved IPv6 block `3fff::/20` (GH-124240)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2024-09-19-20-15-00.gh-issue-124217.j0KlQB.rst
Labels: awaiting merge

#124800 [3.13] gh-116810: fix memory leak in ssl module (GH-123249)
  Misc/NEWS.d/next/Library/2024-08-23-15-49-10.gh-issue-116810.QLBUU8.rst
  Modules/_ssl.c
Labels: awaiting merge, topic-SSL

#124905 [3.13] gh-120378: Fix crash caused by integer overflow in `curses` (GH-124555)
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2024-09-25-18-07-51.gh-issue-120378.NlBSz_.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: awaiting merge

#125057 [3.13] gh-124182: Explain naming rules for struct sequence types (GH-124335)
  Doc/c-api/tuple.rst
Labels: docs, awaiting merge, skip news

#125074 gh-125072: Add label for assignment expressions; update tracked section for assignment expression topic
  Doc/reference/expressions.rst
  Doc/tools/extensions/pyspecific.py
  Lib/pydoc_data/topics.py
Labels: awaiting core review, skip news, 3.13, needs backport to 3.13

#124421 [3.13] gh-72795: Make positional arguments with nargs='*' or REMAINDER non-required (GH-124306)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-21-22-32-21.gh-issue-72795.naLmkX.rst
Labels: awaiting merge

#124760 [3.13] gh-58573: Fix conflicts between abbreviated long options in the parent parser and subparsers in argparse (GH-124631)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-09-26-22-14-12.gh-issue-58573.hozbm9.rst
Labels: awaiting core review

#125075 [3.13] Small improvements to the itertools docs (GH-123885)
  Doc/library/itertools.rst
  Lib/test/test_itertools.py
Labels: tests, docs, skip issue, skip news, 3.13

#125066 Docs: make a tutorial example more precise
  Doc/tutorial/introduction.rst
Labels: skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#125077 [3.13] gh-125072: Add label for assignment expressions; update tracked section for assignment expression topic (GH-125074)
  Doc/reference/expressions.rst
  Doc/tools/extensions/pyspecific.py
Labels: awaiting core review, skip news

#125078 [3.13] Docs: make a tutorial example more precise (GH-125066)
  Doc/tutorial/introduction.rst
Labels: docs, skip issue, awaiting review, skip news

#125047 [3.13] gh-125018: Add importlib.metadata semantic link targets (GH-125027)
  Doc/library/importlib.metadata.rst
  Misc/NEWS.d/next/Documentation/2024-10-07-00-31-17.gh-issue-125018.yKnymn.rst
Labels: docs, awaiting merge

#125080 [3.13] gh-125018: Fix role syntax (GH-125050)
  Doc/library/importlib.metadata.rst
Labels: docs, awaiting merge, skip news

#124919 [3.13] gh-102511: Change the `os.path.splitroot` param name from `path` back to `p` (GH-124097)
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting merge, skip news

#125059 [3.13] gh-124653: Relax (again) detection of queue API for logging handlers (GH-124897)
  Doc/library/logging.config.rst
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-10-02-15-05-45.gh-issue-124653.tqsTu9.rst
Labels: awaiting review

#125060 [3.12] gh-124653: Relax (again) detection of queue API for logging handlers (GH-124897)
  Doc/library/logging.config.rst
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-10-02-15-05-45.gh-issue-124653.tqsTu9.rst
Labels: awaiting review

#124882 [3.13] gh-58282: Fix support of tuple metavar for positional arguments in argparse (GH-124782)
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2018-12-04-07-36-27.bpo-14074.fMLKCu.rst
Labels: awaiting core review

#124922 gh-90102: Remove isatty call during regular open
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Include/internal/pycore_unicodeobject_generated.h
  Lib/_pyio.py
  Misc/NEWS.d/next/Library/2024-10-02-22-53-48.gh-issue-90102.4qX52R.rst
  Modules/_io/_iomodule.c
  Modules/_io/fileio.c
  Modules/_io/winconsoleio.c
Labels: awaiting merge

#122545 gh-70870: Clarify dual usage of 'free variable'
  Doc/c-api/code.rst
  Doc/glossary.rst
  Doc/library/dis.rst
  Doc/library/functions.rst
  Doc/library/symtable.rst
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/reference/executionmodel.rst
  Misc/NEWS.d/next/Documentation/2024-08-01-17-18-21.gh-issue-70870.fZnBM9.rst
Labels: docs, awaiting merge, triaged, 3.13, 3.14, needs backport to 3.13

#125088 [3.13] gh-70870: Clarify dual usage of 'free variable' (GH-122545)
  Doc/c-api/code.rst
  Doc/glossary.rst
  Doc/library/dis.rst
  Doc/library/functions.rst
  Doc/library/symtable.rst
  Doc/library/types.rst
  Doc/reference/datamodel.rst
  Doc/reference/executionmodel.rst
  Misc/NEWS.d/next/Documentation/2024-08-01-17-18-21.gh-issue-70870.fZnBM9.rst
Labels: docs, awaiting review

#124901 [3.13] gh-85935: Improve tests for invalid arguments in test_argparse (GH-124891)
  Lib/test/test_argparse.py
Labels: tests, awaiting core review, skip news

#124963 gh-69998: Fix decoding error in locale.nl_langinfo()
  Doc/library/locale.rst
  Doc/whatsnew/3.14.rst
  Lib/test/test__locale.py
  Misc/NEWS.d/next/Library/2024-10-04-12-43-03.gh-issue-69998.DVqOXX.rst
  Modules/_localemodule.c
Labels: awaiting merge

#8023 bpo-34206: Improve docs and test coverage for pre-init functions
  Doc/c-api/init.rst
  Doc/c-api/init_config.rst
  Doc/c-api/veryhigh.rst
  Lib/test/test_embed.py
  Misc/NEWS.d/next/C API/2018-06-30-21-48-16.bpo-34008.2Wjtm0.rst
  Misc/NEWS.d/next/Documentation/2018-07-04-20-35-25.bpo-34008.bqecIb.rst
  Programs/_testembed.c
Labels: awaiting merge, needs backport to 3.13

#125090 gh-53203: Improve tests for strptime()
  Lib/test/pickletester.py
  Lib/test/support/__init__.py
  Lib/test/test_codecs.py
  Lib/test/test_decimal.py
  Lib/test/test_float.py
  Lib/test/test_imaplib.py
  Lib/test/test_str.py
  Lib/test/test_strptime.py
  Lib/test/test_time.py
  Lib/test/test_types.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#125091 [3.13] gh-53203: Improve tests for strptime() (GH-125090)
  Lib/test/pickletester.py
  Lib/test/support/__init__.py
  Lib/test/test_codecs.py
  Lib/test/test_decimal.py
  Lib/test/test_float.py
  Lib/test/test_imaplib.py
  Lib/test/test_str.py
  Lib/test/test_strptime.py
  Lib/test/test_time.py
  Lib/test/test_types.py
Labels: awaiting review, skip news
