Repository python/cpython, pull requests merged in 2024-03, with the labels that each got.

#116157 [3.11] gh-116026: Try disabling rebuilds of dependents in Homebrew (GH-116027)
  .github/workflows/reusable-macos.yml
Labels: awaiting review, skip news

#116153 gh-115491: Fix Clang compiler warning
  Objects/mimalloc/alloc.c
Labels: awaiting core review, skip news

#116158 [3.12] gh-116026: Try disabling rebuilds of dependents in Homebrew (GH-116027)
  .github/workflows/reusable-macos.yml
Labels: awaiting review, skip news

#116164 gh-116099: Fix refcounting bug in `_queueobj_shared()`
  Modules/_xxinterpqueuesmodule.c
Labels: awaiting merge, skip news

#116173 [3.12] gh-115881: Document feature_version limitations (#115980)
  Doc/library/ast.rst
Labels: docs, awaiting core review, skip news

#116174 [3.11] gh-115881: Document feature_version limitations (#115980)
  Doc/library/ast.rst
Labels: docs, awaiting core review, skip news

#116013 gh-115999: Disable the specializing adaptive interpreter in free-threaded builds
  Include/internal/pycore_code.h
  Lib/test/test_capi/test_opt.py
  Lib/test/test_generated_cases.py
  Lib/test/test_monitoring.py
  Lib/test/test_opcache.py
  Lib/test/test_type_cache.py
  Python/ceval_macros.h
  Python/generated_cases.c.h
  Tools/cases_generator/tier1_generator.py
Labels: awaiting merge, skip news, topic-free-threading

#116178 gh-116098: Revert "gh-107674: Improve performance of `sys.settrace` (GH-114986)"
  Misc/NEWS.d/next/Core and Builtins/2024-02-04-07-45-29.gh-issue-107674.q8mCmi.rst
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/instrumentation.c
Labels: awaiting review

#116185 [3.12] gh-115811: Update documentation to add some Logger attributes. (GH-116109)
  Doc/library/logging.rst
Labels: docs, awaiting review, skip news

#116186 [3.11] gh-115811: Update documentation to add some Logger attributes. (GH-116109)
  Doc/library/logging.rst
Labels: docs, awaiting review, skip news

#116162 gh-116159: argparse: performance improvement parsing large number of options
  Lib/argparse.py
Labels: awaiting merge, skip news

#115530 gh-101293: Fix support of custom callables and types in inspect.Signature.from_callable()
  Lib/inspect.py
  Lib/test/test_inspect/test_inspect.py
  Misc/NEWS.d/next/Library/2024-02-15-19-11-49.gh-issue-101293.898b8l.rst
Labels: awaiting core review

#116197 [3.11] gh-101293: Fix support of custom callables and types in inspect.Signature.from_callable() (GH-115530)
  Lib/inspect.py
  Lib/test/test_inspect/test_inspect.py
  Misc/NEWS.d/next/Library/2024-02-15-19-11-49.gh-issue-101293.898b8l.rst
Labels: awaiting review

#116198 [3.12] gh-101293: Fix support of custom callables and types in inspect.Signature.from_callable() (GH-115530)
  Lib/inspect.py
  Lib/test/test_inspect/test_inspect.py
  Misc/NEWS.d/next/Library/2024-02-15-19-11-49.gh-issue-101293.898b8l.rst
Labels: awaiting review

#116201 [3.11] gh-115554: Improved logic for handling multiple existing py.exe launcher installs (GH-115793)
  Misc/NEWS.d/next/Windows/2024-02-21-23-48-59.gh-issue-115554.02mpQC.rst
  Tools/msi/bundle/Default.wxl
  Tools/msi/bundle/bootstrap/PythonBootstrapperApplication.cpp
  Tools/msi/bundle/bundle.wxs
Labels: awaiting core review

#116191 gh-88352: Fix logging.TimedRotatingFileHandler
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-03-01-11-57-32.gh-issue-88352.bZ68rw.rst
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#104220 gh-104219: Document that idunders can return NotImplemented
  Doc/reference/datamodel.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116210 [3.12] gh-104219: Document that idunders can return NotImplemented (GH-104220)
  Doc/reference/datamodel.rst
Labels: docs, awaiting review, skip news

#116211 [3.11] gh-104219: Document that idunders can return NotImplemented (GH-104220)
  Doc/reference/datamodel.rst
Labels: docs, awaiting review, skip news

#112283 gh-112281: Allow `Union` with unhashable `Annotated` metadata
  Lib/test/test_types.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2023-11-20-16-15-44.gh-issue-112281.gH4EVk.rst
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#116166 gh-76785: Fix interpreters.Queue.get_nowait()
  Lib/test/support/interpreters/queues.py
  Lib/test/test_interpreters/test_queues.py
Labels: awaiting core review, skip news

#116208 [3.12] gh-88352: Fix logging.TimedRotatingFileHandler (GH-116191)
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-03-01-11-57-32.gh-issue-88352.bZ68rw.rst
Labels: awaiting review

#116209 [3.11] gh-88352: Fix logging.TimedRotatingFileHandler (GH-116191)
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-03-01-11-57-32.gh-issue-88352.bZ68rw.rst
Labels: awaiting review

#116187 gh-116035: Document that both tzinfo and fold are ignored in comparisons if tzinfo is the same
  Doc/library/datetime.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#115915 gh-104711: Add security warning to the CGIHTTPRequestHandler document
  Doc/library/http.server.rst
Labels: docs, awaiting review, skip news, needs backport to 3.11, needs backport to 3.12

#116216 [3.12] gh-116035: Document that both tzinfo and fold are ignored in comparisons if tzinfo is the same (GH-116187)
  Doc/library/datetime.rst
Labels: docs, awaiting review, skip news

#116217 [3.11] gh-116035: Document that both tzinfo and fold are ignored in comparisons if tzinfo is the same (GH-116187)
  Doc/library/datetime.rst
Labels: docs, awaiting review, skip news

#116165 gh-115806: Don't mangle output of configure 'ipv6 stack type' check
  configure
  configure.ac
Labels: awaiting core review, skip news

#116212 gh-115773: Add missing preprocessor guard in _testexternalinspection
  Modules/_testexternalinspection.c
Labels: tests, awaiting merge, skip news

#20517 gh-84995: Run sys.__interactivehook__() on asyncio REPL startup
  Lib/asyncio/__main__.py
  Lib/site.py
  Misc/NEWS.d/next/Library/2020-05-29-18-08-54.bpo-40818.Ij8ffq.rst
Labels: topic-asyncio, awaiting merge

#115710 gh-115480: Type propagate _BINARY_OP_ADD_UNICODE
  Lib/test/test_capi/test_opt.py
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, skip news

#116196 gh-115941: Documentation: dictobjects.c: changing the doc block section of the file
  Objects/dictobject.c
Labels: awaiting review, skip news

#115190 gh-114271: Make `_thread.ThreadHandle` thread-safe in free-threaded builds
  Include/internal/pycore_lock.h
  Lib/test/test_thread.py
  Lib/threading.py
  Modules/_threadmodule.c
  Python/lock.c
Labels: awaiting merge, skip news, topic-free-threading

#116227 GH-116226: include `pthread_stubs.h` in `pycore_pythreads.h`
  Include/internal/pycore_pythread.h
Labels: awaiting core review, skip news

#115875 gh-112087: Use QSBR technique for list_new/clear for free-thread build
  Objects/listobject.c
Labels: awaiting merge, skip news, topic-free-threading

#116230 gh-116102: Silence a Compiler Warning in _xxinterpqueues
  Modules/_xxinterpqueuesmodule.c
Labels: awaiting core review, skip news

#116228 GH-115978: Disable `*readv()` and `*writev()` on WASI
  Misc/NEWS.d/next/Library/2024-03-01-14-22-08.gh-issue-115978.r2ePTo.rst
  Tools/wasm/config.site-wasm32-wasi
Labels: awaiting core review, needs backport to 3.11, needs backport to 3.12

#116231 [3.12] GH-115978: Disable `*readv()` and `*writev()` on WASI (GH-116228)
  Misc/NEWS.d/next/Library/2024-03-01-14-22-08.gh-issue-115978.r2ePTo.rst
  Tools/wasm/config.site-wasm32-wasi
Labels: awaiting merge

#116232 [3.11] GH-115978: Disable `*readv()` and `*writev()` on WASI (GH-116228)
  Misc/NEWS.d/next/Library/2024-03-01-14-22-08.gh-issue-115978.r2ePTo.rst
  Tools/wasm/config.site-wasm32-wasi
Labels: awaiting merge

#114624 [3.12] gh-114494: Change logging docstring to bool for exec_info (GH=114558)
  Lib/logging/__init__.py
Labels: awaiting review, skip news

#21731 gh-85644: webbrowser: Use $XDG_CURRENT_DESKTOP to check desktop
  Lib/webbrowser.py
  Misc/NEWS.d/next/Library/2024-02-27-20-11-29.gh-issue-85644.3rgcBm.rst
Labels: awaiting merge

#116242 [3.11] gh-114494: Change logging docstring to bool for exec_info (GH-114558)
  Lib/logging/__init__.py
Labels: awaiting core review, skip news

#116238 gh-115103: Update refleak checker to trigger _PyMem_ProcessDelayed
  Python/gc_free_threading.c
Labels: awaiting merge, skip news, topic-free-threading

#110729 gh-72971: Clarify the special no-TypeError behavior for equality
  Doc/reference/datamodel.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116254 [3.12] gh-72971: Clarify the special no-TypeError behavior for equality (GH-110729)
  Doc/reference/datamodel.rst
Labels: docs, awaiting review, skip news

#116255 [3.11] gh-72971: Clarify the special no-TypeError behavior for equality (GH-110729)
  Doc/reference/datamodel.rst
Labels: docs, awaiting review, skip news

#114751 gh-108562: fix compiler warnings for bundled libmpdec in the main
  Makefile.pre.in
  Misc/sbom.spdx.json
  Modules/_decimal/libmpdec/io.c
  configure
  configure.ac
Labels: awaiting merge, skip news

#115812 gh-115809: Improve TimedRotatingFileHandler.getFilesToDelete()
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-02-22-11-29-27.gh-issue-115809.9H1DhB.rst
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#116261 [3.12] gh-115809: Improve TimedRotatingFileHandler.getFilesToDelete() (GH-115812)
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-02-22-11-29-27.gh-issue-115809.9H1DhB.rst
Labels: awaiting review

#116274 Docs: update using/configure.rst
  Doc/using/configure.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116282 gh-116281: Remove wrong '\' from '\*' in some doc signatures
  Doc/library/asyncio-stream.rst
  Doc/library/enum.rst
  Doc/library/hashlib.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#116285 [3.12] gh-116281: Remove wrong '\' from '\*' in some doc signatures (GH-116282)
  Doc/library/asyncio-stream.rst
  Doc/library/enum.rst
  Doc/library/hashlib.rst
Labels: docs, awaiting review, skip news

#116287 [3.11] gh-116010: Remove link to deprecated PEP 6 in FAQ guide (GH-116246)
  Doc/faq/general.rst
Labels: docs, awaiting review, skip news

#116286 [3.12] gh-116010: Remove link to deprecated PEP 6 in FAQ guide (GH-116246)
  Doc/faq/general.rst
Labels: docs, awaiting review, skip news

#116288 [3.11] gh-112281: Allow `Union` with unhashable `Annotated` metadata (GH-112283)
  Lib/test/test_types.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2023-11-20-16-15-44.gh-issue-112281.gH4EVk.rst
Labels: awaiting merge

#116289 [3.11] gh-116281: Remove wrong '\' from '\*' in some doc signatures (#116282)
  Doc/library/asyncio-stream.rst
  Doc/library/hashlib.rst
Labels: docs, awaiting core review, skip news

#116293 pathlib ABCs: follow all symlinks in `PathBase.glob()`
  Lib/pathlib/_abc.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: skip issue, awaiting core review, skip news, topic-pathlib

#116297 gh-116296: Fix refleak in reduce_newobj() corner case
  Misc/NEWS.d/next/Core and Builtins/2024-03-04-10-19-51.gh-issue-116296.gvtxyU.rst
  Objects/typeobject.c
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#116300 [3.11] gh-116296: Fix refleak in reduce_newobj() corner case (GH-116297)
  Misc/NEWS.d/next/Core and Builtins/2024-03-04-10-19-51.gh-issue-116296.gvtxyU.rst
  Objects/typeobject.c
Labels: awaiting review

#116299 [3.12] gh-116296: Fix refleak in reduce_newobj() corner case (GH-116297)
  Misc/NEWS.d/next/Core and Builtins/2024-03-04-10-19-51.gh-issue-116296.gvtxyU.rst
  Objects/typeobject.c
Labels: awaiting review

#116301 gh-115398: Increment PyExpat_CAPI_MAGIC for SetReparseDeferralEnabled addition
  Include/pyexpat.h
  Misc/NEWS.d/next/Security/2024-02-18-03-14-40.gh-issue-115398.tzvxH8.rst
Labels: awaiting core review

#116235 [3.12] gh-104711: Add security warning to the CGIHTTPRequestHandler document (GH-115915)
  Doc/library/http.server.rst
Labels: docs, awaiting core review, skip news

#116236 [3.11] gh-104711: Add security warning to the CGIHTTPRequestHandler document (GH-115915)
  Doc/library/http.server.rst
Labels: docs, awaiting core review, skip news

#116283 GH-116271 Docs: provide clarification for object assignments in the Tutorial section
  Doc/tutorial/introduction.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116306 [3.11] GH-116271 Docs: provide clarification for object assignments in the Tutorial section (GH-116283)
  Doc/tutorial/introduction.rst
Labels: docs, awaiting review, skip news

#116305 [3.12] GH-116271 Docs: provide clarification for object assignments in the Tutorial section (GH-116283)
  Doc/tutorial/introduction.rst
Labels: docs, awaiting review, skip news

#116170 gh-114258: Argument Clinic: refactor getset implementation
  Lib/test/clinic.test.c
  Lib/test/test_clinic.py
  Tools/clinic/clinic.py
Labels: awaiting merge, skip news

#115257 gh-115256: Remove refcycles from tarfile writing
  Doc/whatsnew/3.13.rst
  Lib/tarfile.py
  Misc/NEWS.d/next/Library/2024-02-10-17-18-49.gh-issue-115256.41Fy9P.rst
Labels: awaiting merge

#116308 Consistently spell out *predicate* instead of *pred*.
  Doc/library/itertools.rst
  Modules/itertoolsmodule.c
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12

#116312 [3.12] Consistently spell out *predicate* instead of *pred*. (gh-116308)
  Doc/library/itertools.rst
  Modules/itertoolsmodule.c
Labels: skip issue, awaiting merge, skip news

#115856 gh-115832: Fix instrumentation version mismatch during interpreter shutdown
  Lib/test/_test_monitoring_shutdown.py
  Lib/test/test_monitoring.py
  Python/instrumentation.c
  Python/pystate.c
Labels: awaiting merge, skip news

#116302 gh-108562: Revert enabling -fstrict-overflow for libmpdec
  Makefile.pre.in
  configure
  configure.ac
Labels: awaiting review, skip news

#116315 [3.12] gh-116116: Backport blake2 change to fix building with clang-cl on windows-i686 (GH-116117)
  Misc/NEWS.d/next/Build/2024-02-29-15-12-31.gh-issue-116117.eENkQK.rst
  Misc/sbom.spdx.json
  Modules/_blake2/impl/blake2b.c
  Modules/_blake2/impl/blake2s.c
Labels: awaiting review

#109499 gh-57141: Add dircmp shallow option.
  Doc/library/filecmp.rst
  Lib/filecmp.py
  Lib/test/test_filecmp.py
  Misc/NEWS.d/next/Library/2023-07-12-14-52-04.gh-issue-57141.L2k8Xb.rst
Labels: awaiting review

#116317 gh-116316: Fix typo in `UNARY_FUNC(PyNumber_Positive)` macros
  Objects/abstract.c
Labels: awaiting merge, skip news

#116177 GH-115802: Don't JIT zero-length jumps
  Tools/jit/_stencils.py
Labels: performance, awaiting merge, skip news, interpreter-core

#116130 GH-116134: JIT `aarch64-pc-windows-msvc`
  .github/workflows/jit.yml
  Python/jit.c
  Tools/jit/_schema.py
  Tools/jit/_targets.py
Labels: type-feature, performance, OS-windows, awaiting core review, skip news, interpreter-core

#116318 gh-76785: Simplify Channels XID Types
  Modules/_xxinterpchannelsmodule.c
Labels: awaiting core review, skip news

#115321 gh-115320: Refactor `get_hash_info` in `sysmodule.c` not to swallow errors
  Python/sysmodule.c
Labels: awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116276 [3.12] Docs: update using/configure.rst (GH-116274)
  Doc/using/configure.rst
Labels: docs, skip issue, awaiting core review, skip news

#116277 [3.11] Docs: update using/configure.rst (GH-116274)
  Doc/using/configure.rst
Labels: docs, skip issue, awaiting core review, skip news

#115493 gh-115490: Make the interpreter.channels and interpreter.queues Modules Handle Reloading Properly
  Lib/test/libregrtest/main.py
  Lib/test/test__xxinterpchannels.py
  Lib/test/test_interpreters/test_channels.py
  Lib/test/test_interpreters/test_queues.py
  Modules/_xxinterpchannelsmodule.c
  Modules/_xxinterpqueuesmodule.c
Labels: awaiting merge, skip news

#116324 [3.11] gh-115320: Refactor `get_hash_info` in `sysmodule.c` not to swallow errors (GH-115321)
  Python/sysmodule.c
Labels: awaiting merge, skip news

#116323 [3.12] gh-115320: Refactor `get_hash_info` in `sysmodule.c` not to swallow errors (GH-115321)
  Python/sysmodule.c
Labels: awaiting merge, skip news

#116284 gh-116265: Remove obsolete sentence.
  Tools/c-analyzer/README
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116331 [3.12] gh-116265: Remove obsolete sentence. (GH-116284)
  Tools/c-analyzer/README
Labels: awaiting core review, skip news

#116332 [3.11] gh-116265: Remove obsolete sentence. (GH-116284)
  Tools/c-analyzer/README
Labels: awaiting core review, skip news

#116340 gh-116029: Fix unused function warning on macOS
  Objects/dictobject.c
Labels: awaiting merge, skip news, topic-free-threading

#116233 gh-112087: Make list_{slice, ass_slice, subscript} to be threadsafe
  Lib/test/test_list.py
  Objects/listobject.c
Labels: awaiting merge, skip news, topic-free-threading

#116336 gh-112075: Enable freeing with qsbr and fallback to lock on key changed
  Objects/dictobject.c
Labels: awaiting core review, skip news, topic-free-threading

#116341 gh-116325: Raise `SyntaxError` on ForwardRef with empty string arg
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2024-03-05-02-09-18.gh-issue-116325.FmlBYv.rst
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#116347 [3.12] gh-116325: Raise `SyntaxError` rather than `IndexError` on ForwardRef with empty string arg (GH-116341)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2024-03-05-02-09-18.gh-issue-116325.FmlBYv.rst
Labels: awaiting review

#116348 [3.11] gh-116325: Raise `SyntaxError` rather than `IndexError` on ForwardRef with empty string arg (GH-116341)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2024-03-05-02-09-18.gh-issue-116325.FmlBYv.rst
Labels: awaiting review

#116311 GH-115685: Optimize `TO_BOOL` and variants based on truthiness of input.
  Include/internal/pycore_optimizer.h
  Python/optimizer_analysis.c
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Python/optimizer_symbols.c
Labels: awaiting merge, skip news

#116339 gh-116326: Handler errors correctly in `getwindowsversion` in `sysmodule`
  Python/sysmodule.c
Labels: awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116355 GH-115819: Eliminate Boolean guards when value is known
  Include/internal/pycore_optimizer.h
  Lib/test/test_capi/test_opt.py
  Python/optimizer_analysis.c
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Python/optimizer_symbols.c
Labels: awaiting merge, skip news

#116352 GH-115685: Split `_TO_BOOL_ALWAYS_TRUE` into micro-ops
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_analysis.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, skip news

#116269 gh-115777: Fix double versionadded directives
  Doc/library/asyncio-eventloop.rst
  Doc/library/audit_events.rst
  Doc/library/decimal.rst
  Doc/library/ipaddress.rst
  Doc/library/ssl.rst
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116056 Fix the PyGetSetDef documentation
  Doc/c-api/structures.rst
Labels: docs, skip issue, awaiting core review, skip news, topic-C-API, needs backport to 3.11, needs backport to 3.12

#116125 gh-76511: Fix email.Message.as_string() for non-ASCII message with ASCII charset
  Lib/email/generator.py
  Lib/email/message.py
  Lib/test/test_email/test_email.py
  Misc/NEWS.d/next/Library/2024-02-29-17-06-54.gh-issue-76511.WqjRLP.rst
Labels: awaiting core review, needs backport to 3.11, needs backport to 3.12

#115771 gh-74668: Fix support of bytes in urllib.parse.parse_qsl()
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Library/2024-02-21-17-54-59.gh-issue-74668.JT-Q8W.rst
Labels: awaiting core review, needs backport to 3.11, needs backport to 3.12

#116328 gh-76785: Minor Improvements to "interpreters" Module
  Lib/test/support/interpreters/__init__.py
  Lib/test/support/interpreters/channels.py
  Lib/test/support/interpreters/queues.py
  Lib/test/test_interpreters/test_api.py
  Lib/test/test_interpreters/test_channels.py
  Lib/test/test_interpreters/test_queues.py
  Modules/_interpreters_common.h
  Modules/_xxinterpchannelsmodule.c
  Modules/_xxinterpqueuesmodule.c
Labels: awaiting core review, skip news

#116361 [3.12] gh-115777: Fix double versionadded directives (GH-116269)
  Doc/library/asyncio-eventloop.rst
  Doc/library/audit_events.rst
  Doc/library/decimal.rst
  Doc/library/ipaddress.rst
  Doc/library/ssl.rst
  Doc/library/typing.rst
Labels: docs, awaiting review, skip news

#116345 chore: fix typos
  Doc/library/idle.rst
  Include/cpython/code.h
  Include/internal/pycore_compile.h
  Include/internal/pycore_gc.h
  Include/internal/pycore_instruments.h
  Include/internal/pycore_interp.h
  Include/internal/pycore_lock.h
  Lib/asyncio/tasks.py
  Lib/importlib/util.py
  Lib/test/libregrtest/run_workers.py
  Lib/test/libregrtest/utils.py
  Lib/test/test_asyncio/test_waitfor.py
  Lib/test/test_baseexception.py
  Objects/mimalloc/prim/windows/etw.h
  Tools/build/stable_abi.py
Labels: skip issue, awaiting merge, skip news

#116362 [3.11] gh-115777: Fix double versionadded directives (GH-116269)
  Doc/library/asyncio-eventloop.rst
  Doc/library/audit_events.rst
  Doc/library/decimal.rst
  Doc/library/ipaddress.rst
  Doc/library/ssl.rst
  Doc/library/typing.rst
Labels: docs, awaiting review, skip news

#116368 [3.11] Fix the PyGetSetDef documentation (GH-116056)
  Doc/c-api/structures.rst
Labels: docs, skip issue, awaiting core review, skip news

#116200 [3.12] gh-115554: Improved logic for handling multiple existing py.exe launcher installs (GH-115793)
  Misc/NEWS.d/next/Windows/2024-02-21-23-48-59.gh-issue-115554.02mpQC.rst
  Tools/msi/bundle/Default.wxl
  Tools/msi/bundle/bootstrap/PythonBootstrapperApplication.cpp
  Tools/msi/bundle/bundle.wxs
Labels: awaiting review

#116364 [3.12] gh-76511: Fix email.Message.as_string() for non-ASCII message with ASCII charset (GH-116125)
  Lib/email/generator.py
  Lib/email/message.py
  Lib/test/test_email/test_email.py
  Misc/NEWS.d/next/Library/2024-02-29-17-06-54.gh-issue-76511.WqjRLP.rst
Labels: awaiting review

#116365 [3.11] gh-76511: Fix email.Message.as_string() for non-ASCII message with ASCII charset (GH-116125)
  Lib/email/generator.py
  Lib/email/message.py
  Lib/test/test_email/test_email.py
  Misc/NEWS.d/next/Library/2024-02-29-17-06-54.gh-issue-76511.WqjRLP.rst
Labels: awaiting review

#116366 [3.12] gh-74668: Fix support of bytes in urllib.parse.parse_qsl() (GH-115771)
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Library/2024-02-21-17-54-59.gh-issue-74668.JT-Q8W.rst
Labels: awaiting review

#116367 [3.11] gh-74668: Fix support of bytes in urllib.parse.parse_qsl() (GH-115771)
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Library/2024-02-21-17-54-59.gh-issue-74668.JT-Q8W.rst
Labels: awaiting review

#116337 Fix debug output for optimized executor
  Python/optimizer.c
Labels: skip issue, awaiting merge, skip news

#109822 gh-109653: Just import `recursive_repr` in `dataclasses`
  Lib/dataclasses.py
Labels: awaiting merge, skip news

#116369 gh-76785: Use PRId64 to Fix a Compiler Warning on Windows
  Modules/_xxinterpqueuesmodule.c
Labels: awaiting core review, skip news

#116370 [3.12] chore: fix typos (#116345)
  Doc/library/idle.rst
  Include/cpython/code.h
  Include/internal/pycore_instruments.h
  Lib/asyncio/tasks.py
  Lib/importlib/util.py
  Lib/test/libregrtest/run_workers.py
  Lib/test/libregrtest/utils.py
  Lib/test/test_asyncio/test_waitfor.py
  Lib/test/test_baseexception.py
  Tools/build/stable_abi.py
Labels: skip issue, awaiting core review, skip news, needs backport to 3.11

#116343 gh-115103: Enable internal mimalloc assertions in debug builds
  Include/internal/pycore_mimalloc.h
  Objects/mimalloc/alloc.c
Labels: awaiting merge, skip news, topic-free-threading

#116375 [3.11] chore: fix typos (GH-116345)
  Doc/library/idle.rst
  Lib/test/libregrtest/run_workers.py
  Lib/test/libregrtest/utils.py
  Lib/test/test_baseexception.py
  Tools/scripts/stable_abi.py
Labels: skip issue, awaiting core review, skip news

#116104 gh-115986: Fix inaccuracies in pprint docs
  Doc/library/pprint.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#116383 [3.11] gh-115986: Fix inaccuracies in pprint docs (GH-116104)
  Doc/library/pprint.rst
Labels: docs, awaiting review, skip news

#116373 [3.12] GH-116313: get WASI builds to run under wasmtime 18 w/ WASI 0.2/preview2 primitives (GH-116327)
  .devcontainer/Dockerfile
  Misc/NEWS.d/next/Build/2024-03-04-12-43-42.gh-issue-116313.cLLb8S.rst
  Tools/wasm/wasm_build.py
  configure
  configure.ac
Labels: awaiting core review, needs backport to 3.11

#116384 [3.11] GH-116313: get WASI builds to run under wasmtime 18 w/ WASI 0.2/preview2 primitives (GH-116327) (GH-116373)
  Misc/NEWS.d/next/Build/2024-03-04-12-43-42.gh-issue-116313.cLLb8S.rst
  Tools/wasm/wasm_build.py
  configure
  configure.ac
Labels: awaiting core review

#116371 gh-116112: Fix `ResourceWarning` in `test_asyncio.test_stream`
  Lib/test/test_asyncio/test_streams.py
Labels: tests, awaiting merge, skip news

#116353 gh-112087: Update list_get_item_ref to optimistically avoid locking
  Objects/listobject.c
Labels: awaiting merge, skip news, topic-free-threading

#116388 [3.11] gh-116326: Handler errors correctly in `getwindowsversion` in `sysmodule` (GH-116339)
  Python/sysmodule.c
Labels: awaiting merge, skip news

#116406 [3.12] gh-116404: Handle errors correctly in `wait_helper` in `posixmodule` (GH-116405)
  Modules/posixmodule.c
Labels: awaiting merge, skip news

#116407 [3.11] gh-116404: Handle errors correctly in `wait_helper` in `posixmodule` (GH-116405)
  Modules/posixmodule.c
Labels: awaiting merge, skip news

#116359 gh-107954: Add PyConfig_MEMBER_BOOL type to PyConfigSpec
  Lib/test/_test_embed_set_config.py
  Lib/test/test_cmd_line.py
  Lib/test/test_embed.py
  Python/initconfig.c
Labels: awaiting core review, skip news

#116360 GH-115687: Most comparisons create Booleans, so propagate that information
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, skip news

#116410 GH-113710: Tier 2 optimizer: check the function instead of checking globals.
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/optimizer_analysis.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, skip news

#107651 gh-107625: configparser: Raise ParsingError if a key contains empty value
  Doc/library/configparser.rst
  Lib/configparser.py
  Lib/test/test_configparser.py
  Misc/NEWS.d/next/Library/2023-08-05-08-41-58.gh-issue-107625.cVSHCT.rst
Labels: awaiting merge

#116144 gh-116143: Fix race condition in pydoc _start_server
  Lib/pydoc.py
  Misc/NEWS.d/next/Library/2024-03-05-20-53-34.gh-issue-116143.sww6Zl.rst
Labels: awaiting merge, needs backport to 3.11, needs backport to 3.12

#115435 gh-115103: Delay reuse of mimalloc pages that store PyObjects
  Include/internal/mimalloc/mimalloc/types.h
  Include/internal/pycore_mimalloc.h
  Include/internal/pycore_qsbr.h
  Objects/mimalloc/heap.c
  Objects/mimalloc/page.c
  Objects/mimalloc/segment.c
  Objects/obmalloc.c
  Python/pystate.c
  Python/qsbr.c
Labels: awaiting merge, skip news, topic-free-threading

#116416 [3.11] gh-116143: Fix race condition in pydoc _start_server (GH-116144)
  Lib/pydoc.py
  Misc/NEWS.d/next/Library/2024-03-05-20-53-34.gh-issue-116143.sww6Zl.rst
Labels: awaiting review

#116418 [3.11] gh-90300: Reformat the Python CLI help output (GH-93415) (GH-115847)
  Python/initconfig.c
Labels: awaiting core review, skip news

#116278 gh-115398: Suggest use of `hasattr` with checking for 3.13 Expat API availability
  Doc/library/pyexpat.rst
  Doc/library/xml.etree.elementtree.rst
Labels: docs, awaiting merge, skip news

#116385 gh-116381: Specialize CONTAINS_OP
  Include/internal/pycore_code.h
  Include/internal/pycore_list.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_setobject.h
  Include/internal/pycore_tuple.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/importlib/_bootstrap_external.py
  Lib/opcode.py
  Misc/NEWS.d/next/Core and Builtins/2024-03-05-22-00-58.gh-issue-116381.0Nq9iO.rst
  Objects/listobject.c
  Objects/setobject.c
  Objects/tupleobject.c
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Python/optimizer_cases.c.h
  Python/specialize.c
Labels: awaiting merge

#116009 gh-115957: Close coroutine if the TaskGroup is inactive
  Doc/library/asyncio-task.rst
  Doc/whatsnew/3.13.rst
  Lib/asyncio/taskgroups.py
  Lib/test/test_asyncio/test_taskgroups.py
  Misc/NEWS.d/next/Library/2024-03-02-11-31-49.gh-issue-115957.C-3Z_U.rst
Labels: awaiting merge, interpreter-core

#116433 gh-114271: Make `_thread.lock` thread-safe in free-threaded builds
  Modules/_threadmodule.c
Labels: awaiting merge, skip news, topic-free-threading

#116434 gh-88118: Fix some test_multiprocessing flakiness.
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#112389 gh-107361: strengthen default SSL context flags
  .gitattributes
  Doc/library/ssl.rst
  Doc/whatsnew/3.13.rst
  Lib/ssl.py
  Lib/test/certdata/allsans.pem
  Lib/test/certdata/capath/b1930218.0
  Lib/test/certdata/capath/ceff1710.0
  Lib/test/certdata/idnsans.pem
  Lib/test/certdata/keycert.passwd.pem
  Lib/test/certdata/keycert.pem
  Lib/test/certdata/keycert2.pem
  Lib/test/certdata/keycert3.pem
  Lib/test/certdata/keycert4.pem
  Lib/test/certdata/keycertecc.pem
  Lib/test/certdata/leaf-missing-aki.ca.pem
  Lib/test/certdata/leaf-missing-aki.keycert.pem
  Lib/test/certdata/make_ssl_certs.py
  Lib/test/certdata/nosan.pem
  Lib/test/certdata/pycacert.pem
  Lib/test/certdata/pycakey.pem
  Lib/test/certdata/revocation.crl
  Lib/test/certdata/ssl_cert.pem
  Lib/test/certdata/ssl_key.passwd.pem
  Lib/test/certdata/ssl_key.pem
  Lib/test/test_ssl.py
  Misc/NEWS.d/next/Library/2023-11-24-23-40-00.gh-issue-107361.v54gh46.rst
Labels: type-security, awaiting merge

#116248 [3.12] gh-115398: Expose Expat >=2.6.0 reparse deferral API (CVE-2023-52425) (GH-115623)
  Doc/library/pyexpat.rst
  Doc/library/xml.etree.elementtree.rst
  Include/pyexpat.h
  Lib/test/test_pyexpat.py
  Lib/test/test_sax.py
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Lib/xml/sax/expatreader.py
  Misc/NEWS.d/next/Security/2024-02-18-03-14-40.gh-issue-115398.tzvxH8.rst
  Misc/sbom.spdx.json
  Modules/_elementtree.c
  Modules/clinic/_elementtree.c.h
  Modules/clinic/pyexpat.c.h
  Modules/expat/pyexpatns.h
  Modules/pyexpat.c
Labels: type-feature, type-security, awaiting review

#116268 [3.11] gh-115398: Expose Expat >=2.6.0 reparse deferral API (CVE-2023-52425) (GH-115623)
  Doc/library/pyexpat.rst
  Doc/library/xml.etree.elementtree.rst
  Include/pyexpat.h
  Lib/test/test_pyexpat.py
  Lib/test/test_sax.py
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Lib/xml/sax/expatreader.py
  Misc/NEWS.d/next/Security/2024-02-18-03-14-40.gh-issue-115398.tzvxH8.rst
  Modules/_elementtree.c
  Modules/clinic/_elementtree.c.h
  Modules/clinic/pyexpat.c.h
  Modules/expat/pyexpatns.h
  Modules/pyexpat.c
Labels: type-feature, type-security, awaiting merge

#116441 [3.11] gh-88118: Fix some test_multiprocessing flakiness. (GH-116434)
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting review, skip news

#115160 gh-109653: Reduce import overhead of uuid module on Linux
  Lib/uuid.py
  Misc/NEWS.d/next/Documentation/2024-02-08-08-51-37.gh-issue-109653.QHLW4w.rst
Labels: awaiting core review

#116270 [3.10] gh-115398: Expose Expat >=2.6.0 reparse deferral API (CVE-2023-52425) (GH-115623)
  Doc/library/pyexpat.rst
  Doc/library/xml.etree.elementtree.rst
  Include/pyexpat.h
  Lib/test/test_pyexpat.py
  Lib/test/test_sax.py
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Lib/xml/sax/expatreader.py
  Misc/NEWS.d/next/Security/2024-02-18-03-14-40.gh-issue-115398.tzvxH8.rst
  Modules/_elementtree.c
  Modules/clinic/_elementtree.c.h
  Modules/clinic/pyexpat.c.h
  Modules/expat/pyexpatns.h
  Modules/pyexpat.c
Labels: type-feature, type-security, awaiting review

#116272 [3.9] gh-115398: Expose Expat >=2.6.0 reparse deferral API (CVE-2023-52425) (GH-115623)
  Doc/library/pyexpat.rst
  Doc/library/xml.etree.elementtree.rst
  Include/pyexpat.h
  Lib/test/test_pyexpat.py
  Lib/test/test_sax.py
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Lib/xml/sax/expatreader.py
  Misc/NEWS.d/next/Security/2024-02-18-03-14-40.gh-issue-115398.tzvxH8.rst
  Modules/_elementtree.c
  Modules/clinic/_elementtree.c.h
  Modules/clinic/pyexpat.c.h
  Modules/expat/pyexpatns.h
  Modules/pyexpat.c
Labels: type-feature, type-security, awaiting review

#116275 [3.8] gh-115398: Expose Expat >=2.6.0 reparse deferral API (CVE-2023-52425) (GH-115623)
  Doc/library/pyexpat.rst
  Doc/library/xml.etree.elementtree.rst
  Include/pyexpat.h
  Lib/test/test_pyexpat.py
  Lib/test/test_sax.py
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Lib/xml/sax/expatreader.py
  Misc/NEWS.d/next/Security/2024-02-18-03-14-40.gh-issue-115398.tzvxH8.rst
  Modules/_elementtree.c
  Modules/clinic/_elementtree.c.h
  Modules/clinic/pyexpat.c.h
  Modules/expat/pyexpatns.h
  Modules/pyexpat.c
Labels: type-feature, type-security, awaiting review

#116414 gh-116397: Move the _PyGC_ClearAllFreeLists to the safe point
  Python/gc_free_threading.c
Labels: awaiting merge, skip news, topic-free-threading

#116445 GH-116314: Update `Tools/wasm/README.md` to point to the devguide for building for WASI
  Tools/wasm/README.md
Labels: awaiting core review, skip news

#115930 gh-114099 - Add iOS testbed, plus Makefile target to invoke it.
  .gitignore
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2024-02-26-13-13-53.gh-issue-114099.8lpX-7.rst
  Modules/_testexternalinspection.c
  configure
  configure.ac
  iOS/README.rst
  iOS/testbed/Python.xcframework/Info.plist
  iOS/testbed/Python.xcframework/ios-arm64/README
  iOS/testbed/Python.xcframework/ios-arm64_x86_64-simulator/README
  iOS/testbed/iOSTestbed.xcodeproj/project.pbxproj
  iOS/testbed/iOSTestbed/AppDelegate.h
  iOS/testbed/iOSTestbed/AppDelegate.m
  iOS/testbed/iOSTestbed/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/testbed/iOSTestbed/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/testbed/iOSTestbed/Assets.xcassets/Contents.json
  iOS/testbed/iOSTestbed/Base.lproj/LaunchScreen.storyboard
  iOS/testbed/iOSTestbed/dylib-Info-template.plist
  iOS/testbed/iOSTestbed/iOSTestbed-Info.plist
  iOS/testbed/iOSTestbed/main.m
  iOS/testbed/iOSTestbedTests/iOSTestbedTests.m
Labels: awaiting merge
