Repository python/cpython, pull requests merged in 2024-05, with the labels that each got.

#118339 gh-118335: Configure Tier 2 interpreter at build time
  Doc/whatsnew/3.13.rst
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_metadata.h
  Lib/dis.py
  Lib/test/support/__init__.py
  Lib/test/test_capi/test_opt.py
  Lib/test/test_monitoring.py
  Lib/test/test_opcache.py
  Lib/test/test_optimizer.py
  Lib/test/test_weakref.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-26-14-06-18.gh-issue-118335.SRFsxO.rst
  Modules/_opcode.c
  Modules/_testinternalcapi.c
  Objects/codeobject.c
  Objects/object.c
  PCbuild/_testinternalcapi.vcxproj
  PCbuild/build.bat
  PCbuild/pythoncore.vcxproj
  Python/bytecodes.c
  Python/ceval.c
  Python/generated_cases.c.h
  Python/instrumentation.c
  Python/optimizer.c
  Python/optimizer_analysis.c
  Python/optimizer_symbols.c
  Python/pylifecycle.c
  Python/pystate.c
  Python/sysmodule.c
  Tools/cases_generator/analyzer.py
  Tools/jit/README.md
  configure
  configure.ac
Labels: awaiting merge

#118453 gh-118201: Accomodate flaky behavior of `os.sysconf` on iOS
  Lib/test/support/os_helper.py
  Lib/test/test_os.py
Labels: awaiting merge, skip news, OS-ios

#117878 gh-116622: Add Android testbed
  .github/CODEOWNERS
  Android/README.md
  Android/android.py
  Android/testbed/.gitignore
  Android/testbed/app/.gitignore
  Android/testbed/app/build.gradle.kts
  Android/testbed/app/src/main/AndroidManifest.xml
  Android/testbed/app/src/main/c/CMakeLists.txt
  Android/testbed/app/src/main/c/main_activity.c
  Android/testbed/app/src/main/java/org/python/testbed/MainActivity.kt
  Android/testbed/app/src/main/python/main.py
  Android/testbed/app/src/main/res/drawable-xxhdpi/ic_launcher.png
  Android/testbed/app/src/main/res/layout/activity_main.xml
  Android/testbed/app/src/main/res/values/strings.xml
  Android/testbed/build.gradle.kts
  Android/testbed/gradle.properties
  Android/testbed/gradle/wrapper/gradle-wrapper.properties
  Android/testbed/settings.gradle.kts
  Misc/NEWS.d/next/Build/2024-04-14-19-35-35.gh-issue-116622.8lpX-7.rst
Labels: awaiting merge

#117882 GH-117881: fix athrow().throw()/asend().throw() concurrent access
  Lib/test/test_asyncgen.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-15-07-37-09.gh-issue-117881.07H0wI.rst
  Objects/genobject.c
Labels: awaiting merge

#115485 Test syntax error on comma-less tuple-style sequence patterns
  Lib/test/test_patma.py
Labels: tests, skip issue, awaiting merge, skip news

#118459 GH-118095: Make invalidating and clearing executors memory safe
  Include/cpython/optimizer.h
  Objects/codeobject.c
  Python/bytecodes.c
  Python/generated_cases.c.h
  Python/optimizer.c
Labels: awaiting merge, skip news

#118348 gh-116767: fix crash on 'async with' with many context managers
  Include/cpython/code.h
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-27-16-23-29.gh-issue-116767.z9UFpr.rst
  Python/compile.c
Labels: awaiting merge, interpreter-core, type-crash, needs backport to 3.12

#112670 gh-99180: Remove traceback anchors in return and assign statements that cover all the displayed range
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Core and Builtins/2023-12-03-18-21-59.gh-issue-99180.5m0V0q.rst
Labels: awaiting merge

#117959 gh-117958: Expose JIT code via access method in experimental UOpExecutor
  Misc/NEWS.d/next/Core and Builtins/2024-04-18-03-49-41.gh-issue-117958.-EsfUs.rst
  Python/optimizer.c
Labels: awaiting merge

#118435 [3.12] gh-116122: Add SBOM generation to PCbuild/build.bat (GH-116138)
  PCbuild/regen.targets
  Tools/build/generate_sbom.py
Labels: awaiting review, skip news

#118287 GH-115802: Use the GHC calling convention in JIT code
  Include/cpython/optimizer.h
  Lib/test/test_perf_profiler.py
  Python/jit.c
  Python/optimizer.c
  Tools/jit/_targets.py
  Tools/jit/_writer.py
  Tools/jit/template.c
  Tools/jit/trampoline.c
Labels: performance, awaiting merge, skip news, interpreter-core

#118352 gh-116622: Android sysconfig updates
  Android/android-env.sh
  Lib/sysconfig/__init__.py
  Lib/test/test_sysconfig.py
  Misc/NEWS.d/next/Library/2024-04-27-20-34-56.gh-issue-116622.YlQgXv.rst
  configure
  configure.ac
Labels: awaiting merge

#113187 Expand the 'Extending' docs with an example.
  Doc/library/importlib.metadata.rst
Labels: docs, skip issue, awaiting merge, skip news

#118477 [3.12] gh-116767: fix crash on 'async with' with many context managers (GH-118348)
  Include/cpython/code.h
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-27-16-23-29.gh-issue-116767.z9UFpr.rst
  Python/compile.c
Labels: awaiting core review, type-crash

#118394 gh-110850: Add PyTime_TimeRaw() function
  Doc/c-api/time.rst
  Doc/whatsnew/3.13.rst
  Include/cpython/pytime.h
  Lib/test/test_capi/test_time.py
  Misc/NEWS.d/next/C API/2024-04-29-17-19-07.gh-issue-110850.vcpLn1.rst
  Modules/_testcapi/time.c
  Python/pytime.c
Labels: awaiting merge

#118478 gh-118272: set stacktop to 0 before freeing contents, to avoid access to invalid objects during GC
  Python/frame.c
Labels: awaiting merge, skip news

#118484 GH-118095: Make sure that progress is made if there are pending calls being handled.
  Include/internal/pycore_ceval_state.h
  Python/ceval_gil.c
Labels: awaiting merge, skip news

#118481 GH-113464: Add a warning when building the JIT
  Tools/jit/_llvm.py
  Tools/jit/_schema.py
  Tools/jit/_stencils.py
  Tools/jit/_targets.py
  Tools/jit/_writer.py
  Tools/jit/build.py
Labels: awaiting core review, skip news, build

#117608 gh-117607: Speedup `os.path.relpath()`
  Lib/ntpath.py
  Lib/posixpath.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-07-18-42-09.gh-issue-117607.C978BD.rst
Labels: awaiting review

#118491 gh-118413: Temporarily skip `test_release_task_refs` in free-threaded builds
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting merge, skip news, topic-free-threading

#118175 GH-118174: specify the type for the path argument of shutil.which
  Doc/library/shutil.rst
Labels: docs, awaiting core review, skip news

#118493 gh-118335: Make REGEN_JIT_COMMAND empty if tier2 interpreter enabled
  Misc/NEWS.d/next/Core and Builtins/2024-04-26-14-06-18.gh-issue-118335.SRFsxO.rst
  configure
  configure.ac
Labels: awaiting merge, skip news

#118205 gh-117953: Work Relative to Specific Extension Kinds in the Import Machinery
  Include/internal/pycore_importdl.h
  Python/import.c
  Python/importdl.c
Labels: awaiting core review, skip news

#118497 gh-118335: Rename --experimental-interpreter on Windows to --experimental-jit-interpreter
  Doc/whatsnew/3.13.rst
  PCbuild/build.bat
Labels: awaiting merge, skip news

#118411 docs: typo: tiny grammar change: "pointed by" -> "pointed to by"
  Doc/library/os.rst
  Doc/library/shutil.rst
  Lib/pathlib/__init__.py
  Lib/pathlib/_abc.py
  Lib/shutil.py
Labels: skip issue, awaiting merge, skip news, needs backport to 3.12

#118504 [3.12] docs: typo: tiny grammar change: "pointed by" -> "pointed to by" (GH-118411)
  Doc/library/os.rst
  Doc/library/shutil.rst
  Lib/pathlib.py
  Lib/shutil.py
Labels: skip issue, awaiting core review, skip news

#118385 [3.12] Uncomment one grammar test (GH-118361)
  Lib/test/test_grammar.py
Labels: tests, skip issue, awaiting merge, skip news

#118458 [3.12] GH-117881: fix athrow().throw()/asend().throw() concurrent access (GH-117882)
  Lib/test/test_asyncgen.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-15-07-37-09.gh-issue-117881.07H0wI.rst
  Objects/genobject.c
Labels: awaiting review

#118438 Small fix for gdb/libpython.py docs
  Tools/gdb/libpython.py
Labels: skip issue, awaiting core review, skip news

#118482 GH-117442: Check eval-breaker at start (rather than end) of tier 2 loops
  Include/cpython/optimizer.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer.c
  Python/optimizer_cases.c.h
  Tools/jit/template.c
Labels: awaiting merge, skip news

#118267 gh-118216: Don't consider dotted `__future__` imports
  Doc/whatsnew/3.13.rst
  Lib/test/test_future_stmt/test_future.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-25-11-48-28.gh-issue-118216.SVg700.rst
  Python/compile.c
  Python/future.c
Labels: awaiting merge

#116637 gh-116180: check if globals is NULL and set error in run_eval_code_obj()
  Lib/test/test_capi/test_run.py
  Python/pythonrun.c
Labels: awaiting merge, skip news, needs backport to 3.12

#117925 gh-117903: Clarify that the staticmethod descriptor is callable
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12

#118509 [3.12] gh-117903: Clarify that the staticmethod descriptor is callable (GH-117925)
  Doc/library/functions.rst
Labels: docs, awaiting review, skip news

#118488 gh-118486: Support mkdir(mode=0o700) on Windows
  Doc/library/os.rst
  Lib/test/test_os.py
  Lib/test/test_tempfile.py
  Misc/NEWS.d/next/Windows/2024-05-01-20-57-09.gh-issue-118486.K44KJG.rst
  Modules/posixmodule.c
Labels: awaiting core review

#115270 gh-82062: correctly set module for built-in instance methods in inspect.signature()
  Lib/inspect.py
  Lib/test/test_inspect/test_inspect.py
  Misc/NEWS.d/next/Library/2024-02-11-07-31-43.gh-issue-82062.eeS6w7.rst
  Modules/_testcapi/docstring.c
Labels: awaiting merge

#118420 GH-118095: Unify the behavior of tier 2 `FOR_ITER` branch micro-ops
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/optimizer.c
  Python/optimizer_symbols.c
  Python/specialize.c
Labels: awaiting core review, skip news

#118451 [3.12] gh-118272: Clear generator frame's locals when the generator is closed
  Include/internal/pycore_frame.h
  Lib/test/test_generators.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-30-23-06-10.gh-issue-118272.5ptjk_.rst
  Objects/genobject.c
  Python/frame.c
Labels: type-bug, awaiting merge, interpreter-core

#105885 gh-105879: Add support for keyword arguments to eval and exec
  Doc/library/functions.rst
  Lib/test/test_builtin.py
  Misc/NEWS.d/next/Core and Builtins/2023-06-18-00-27-57.gh-issue-105879.dPw78k.rst
  Python/bltinmodule.c
  Python/clinic/bltinmodule.c.h
Labels: awaiting merge

#115945 gh-93502: Add new C-API functions to trace object creation and destruction
  Doc/c-api/init.rst
  Doc/whatsnew/3.13.rst
  Include/cpython/object.h
  Include/internal/pycore_object.h
  Include/internal/pycore_runtime.h
  Include/internal/pycore_runtime_init.h
  Misc/NEWS.d/next/Core and Builtins/2024-02-26-13-14-52.gh-issue-93502.JMWRvA.rst
  Modules/_testcapimodule.c
  Objects/object.c
  Python/tracemalloc.c
Labels: awaiting merge

#118163 gh-90848: Fixed create_autospec ignoring configure_mock style kwargs
  Lib/test/test_unittest/testmock/testmock.py
  Lib/unittest/mock.py
  Misc/NEWS.d/next/Library/2024-04-22-21-54-12.gh-issue-90848.5jHEEc.rst
Labels: awaiting merge

#118494 gh-118413: Fix test_release_task_refs on free-threaded build
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting merge, skip news, topic-free-threading

#118511 Remove stray `__cplusplus` guard in sysmodule.c
  Python/sysmodule.c
Labels: skip issue, awaiting merge, skip news

#118517 [3.12] gh-90848: Fixed create_autospec ignoring configure_mock style kwargs (GH-118163)
  Lib/test/test_unittest/testmock/testmock.py
  Lib/unittest/mock.py
  Misc/NEWS.d/next/Library/2024-04-22-21-54-12.gh-issue-90848.5jHEEc.rst
Labels: awaiting merge

#118515 gh-118486: Switch mkdir(mode=0o700) on Windows to use OWNER RIGHTS instead of CURRENT_USER
  Modules/posixmodule.c
Labels: awaiting core review, skip news

#118260 gh-117657: Fix TSAN list set failure
  Include/internal/pycore_list.h
  Lib/test/test_free_threading/test_list.py
  Objects/listobject.c
Labels: awaiting merge, skip news, topic-free-threading

#118520 gh-118519: Fix empty weakref list check
  Objects/weakrefobject.c
Labels: awaiting merge, skip news, topic-free-threading

#118501 gh-118500: Add pdb support for zipapp
  Doc/whatsnew/3.13.rst
  Lib/pdb.py
  Lib/test/test_pdb.py
  Lib/test/test_pyclbr.py
  Misc/NEWS.d/next/Library/2024-05-02-04-27-12.gh-issue-118500.pBGGtQ.rst
Labels: awaiting merge

#117530 gh-116738: Make `_codecs` module thread-safe
  Include/internal/pycore_codecs.h
  Include/internal/pycore_interp.h
  Objects/unicodeobject.c
  Python/codecs.c
  Python/pystate.c
  Tools/c-analyzer/cpython/ignored.tsv
Labels: awaiting merge, skip news, interpreter-core, topic-free-threading

#118206 gh-117953: Other Cleanups in the Extensions Machinery
  Lib/test/test_import/__init__.py
  Modules/_testsinglephase.c
  Python/import.c
Labels: awaiting core review, skip news

#117678 gh-117492: Clarify documentation of `typing.Never`
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news

#118547 [3.12] gh-117492: Clarify documentation of `typing.Never` (GH-117678)
  Doc/library/typing.rst
Labels: docs, skip news

#116129 gh-116126: Implement PEP 696
  Doc/library/ast.rst
  Doc/library/typing.rst
  Doc/reference/compound_stmts.rst
  Doc/reference/executionmodel.rst
  Doc/whatsnew/3.13.rst
  Grammar/python.gram
  Include/internal/pycore_ast.h
  Include/internal/pycore_ast_state.h
  Include/internal/pycore_intrinsics.h
  Include/internal/pycore_typevarobject.h
  Lib/ast.py
  Lib/test/test_ast.py
  Lib/test/test_type_params.py
  Lib/test/test_typing.py
  Lib/test/test_unparse.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2024-02-29-18-55-45.gh-issue-116129.wsFnIq.rst
  Modules/_typingmodule.c
  Objects/clinic/typevarobject.c.h
  Objects/typevarobject.c
  Parser/Python.asdl
  Parser/parser.c
  Python/Python-ast.c
  Python/ast.c
  Python/compile.c
  Python/intrinsics.c
  Python/symtable.c
  Tools/c-analyzer/cpython/globals-to-fix.tsv
Labels: awaiting merge

#118425 gh-101732: Modules/_ssl.c: use Y2038 compatible openssl function when available
  Misc/NEWS.d/next/Library/2024-04-30-12-59-04.gh-issue-101732.29zUDu.rst
  Modules/_ssl.c
Labels: awaiting merge

#118526 gh-118513: Fix sibling comprehensions with a name bound in one and global in the other
  Lib/test/test_listcomps.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-02-21-19-35.gh-issue-118513.qHODjb.rst
  Python/compile.c
Labels: awaiting merge, needs backport to 3.12

#118548 [3.12] gh-118513: Fix sibling comprehensions with a name bound in one and global in the other (GH-118526)
  Lib/test/test_listcomps.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-02-21-19-35.gh-issue-118513.qHODjb.rst
  Python/compile.c
Labels: awaiting review

#118528 gh-118527: Use `_Py_ID(__main__)` for main module name
  Python/pylifecycle.c
Labels: awaiting merge, skip news, topic-free-threading

#118514 gh-117514: Add `sys._is_gil_enabled()` function
  Doc/library/sys.rst
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-02-16-04-51.gh-issue-117514.CJiuC0.rst
  Python/clinic/sysmodule.c.h
  Python/sysmodule.c
Labels: awaiting merge, topic-free-threading

#118530 gh-118495: Skip test using threads after forking when running with TSAN
  Lib/test/test_threading.py
Labels: tests, awaiting merge, skip news

#118529 gh-118527: Use deferred reference counting for C functions on modules
  Objects/moduleobject.c
Labels: awaiting merge, skip news, topic-free-threading

#118549 docs: clarify DictReader's treatment of the first data row.
  Doc/library/csv.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12

#118555 [3.12] docs: clarify csv.DictReader's treatment of the first data row (GH-118549)
  Doc/library/csv.rst
Labels: docs, skip issue, awaiting review, skip news

#118506 gh-115119: Update Windows installer to mpdecimal 4.0.0
  Misc/NEWS.d/next/Windows/2024-05-02-09-28-04.gh-issue-115119.cUKMXo.rst
  Misc/externals.spdx.json
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: awaiting merge

#118382 gh-115119: Update macOS installer to build with libmpdec 4.0.0
  Mac/BuildScript/README.rst
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2024-05-03-12-13-27.gh-issue-115119.ltDtoR.rst
Labels: awaiting core review, skip news

#118537 gh-118487: Add Black to `.pre-commit-config.yaml` for JIT files
  .pre-commit-config.yaml
  Tools/jit/_targets.py
Labels: awaiting merge, skip news

#114279 gh-83856: Honor atexit for all multiprocessing start methods
  Lib/multiprocessing/forkserver.py
  Lib/multiprocessing/popen_fork.py
  Lib/multiprocessing/process.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2024-01-19-05-40-46.gh-issue-83856.jN5M80.rst
Labels: awaiting review, topic-multiprocessing

#117133 gh-107674: Improve performance of `sys.settrace`
  Misc/NEWS.d/next/Core and Builtins/2024-02-04-07-45-29.gh-issue-107674.q8mCmi.rst
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/instrumentation.c
Labels: awaiting review

#118536 gh-118251: Skip tests not files in JIT CI
  .github/workflows/jit.yml
  Tools/jit/ignore-tests-emulated-linux.txt
Labels: tests, awaiting merge, skip news

#118301 gh-117657: Disable the function/code cache in free-threaded builds
  Include/internal/pycore_function.h
  Objects/codeobject.c
  Objects/funcobject.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, topic-free-threading

#118562 GH-116380: Move pathlib globbing implementation into `pathlib._glob`
  Lib/glob.py
  Lib/pathlib/__init__.py
  Lib/pathlib/_abc.py
  Lib/pathlib/_glob.py
Labels: awaiting core review, skip news

#118563 Minor improvements to the itertools recipes
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12

#118553 gh-118534: Fix load of `gil->locked`
  Python/ceval_gil.c
Labels: awaiting merge, skip news

#118558 gh-118527: Intern filename, name, and qualname in code objects.
  Objects/codeobject.c
Labels: awaiting merge, skip news, topic-free-threading

#118565 [3.12] Minor improvements to the itertools recipes (GH-118563)
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting review, skip news

#118564 GH-118251: Fix incomplete ternary expression in JIT workflow
  .github/workflows/jit.yml
Labels: type-bug, tests, awaiting core review, skip news

#118512 GH-113464: Generate a more efficient JIT
  Python/jit.c
  Tools/jit/_stencils.py
  Tools/jit/_writer.py
Labels: performance, awaiting core review, skip news, interpreter-core, build

#118210 gh-115532 Add kde_random() to the statistic module
  Doc/library/statistics.rst
  Doc/whatsnew/3.13.rst
  Lib/statistics.py
  Lib/test/test_statistics.py
Labels: type-feature, awaiting core review, skip news

#118556 gh-110850: Use _PyDeadline_Get() in EnterNonRecursiveMutex()
  Python/thread_nt.h
Labels: awaiting merge, skip news

#118545 GH-113464: Remove the extra jump via `_SIDE_EXIT` in `_EXIT_TRACE`
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/optimizer.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, skip news

#116413 gh-111997: C-API for signalling monitoring events
  Doc/c-api/index.rst
  Doc/c-api/monitoring.rst
  Doc/conf.py
  Doc/library/sys.monitoring.rst
  Include/Python.h
  Include/cpython/monitoring.h
  Include/internal/pycore_instruments.h
  Include/monitoring.h
  Lib/test/test_monitoring.py
  Makefile.pre.in
  Misc/NEWS.d/next/C API/2024-03-13-17-48-24.gh-issue-111997.8ZbHlA.rst
  Modules/Setup.stdlib.in
  Modules/_testcapi/monitoring.c
  Modules/_testcapi/parts.h
  Modules/_testcapimodule.c
  PCbuild/_testcapi.vcxproj
  PCbuild/_testcapi.vcxproj.filters
  PCbuild/_testinternalcapi.vcxproj.filters
  Python/instrumentation.c
  Tools/c-analyzer/cpython/globals-to-fix.tsv
Labels: awaiting merge

#113082 gh-113081: Print colorized exception just like built-in traceback in pdb
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-12-14-02-51-38.gh-issue-113081.S-9Qyn.rst
Labels: awaiting merge

#118322 GH-118095: Use broader specializations in tier 1, for better tier 2 support of calls.
  Include/internal/pycore_frame.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/test/test_call.py
  Lib/test/test_dis.py
  Lib/test/test_dynamic.py
  Lib/test/test_glob.py
  Python/bytecodes.c
  Python/ceval.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Python/optimizer.c
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Python/specialize.c
Labels: awaiting merge, skip news

#115153 gh-74929: Implement PEP 667
  Doc/data/stable_abi.dat
  Include/ceval.h
  Include/cpython/frameobject.h
  Include/cpython/pyframe.h
  Include/internal/pycore_frame.h
  Lib/test/test_frame.py
  Lib/test/test_listcomps.py
  Lib/test/test_peepholer.py
  Lib/test/test_stable_abi_ctypes.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core and Builtins/2024-04-27-21-44-40.gh-issue-74929.C2nESp.rst
  Misc/stable_abi.toml
  Objects/frameobject.c
  Objects/object.c
  PC/python3dll.c
  Python/ceval.c
  Python/intrinsics.c
  Python/sysmodule.c
  Tools/c-analyzer/cpython/globals-to-fix.tsv
Labels: awaiting merge

#111834 gh-111744: Support opcode events in bdb
  Lib/bdb.py
  Lib/test/test_bdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-11-07-22-41-42.gh-issue-111744.TbLxF0.rst
Labels: awaiting merge

#118570 gh-118569: Add a test for dynamic PEP695 classes
  Lib/test/test_type_params.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12

#118574 [3.12] gh-118569: Add a test for dynamic PEP695 classes (GH-118570)
  Lib/test/test_type_params.py
Labels: tests, awaiting merge, skip news

#118573 gh-117139: Fix missing semicolon
  Include/internal/pycore_stackref.h
Labels: awaiting merge, skip news

#118532 gh-117953: Track Extra Details in Global Extensions Cache
  Include/internal/pycore_importdl.h
  Python/import.c
  Python/importdl.c
Labels: awaiting core review, skip news

#111258 gh-109617: fix ncurses incompatibility on macOS with Xcode 15
  Include/py_curses.h
  Misc/NEWS.d/next/Library/2023-10-24-12-39-04.gh-issue-109617.YoI8TV.rst
  Modules/_cursesmodule.c
  configure
  configure.ac
Labels: awaiting review

#118503 gh-118164: str(10**10000) hangs if the C _decimal module is missing
  Lib/_pydecimal.py
  Lib/test/test_decimal.py
  Misc/NEWS.d/next/Library/2024-05-04-20-22-59.gh-issue-118164.9D02MQ.rst
Labels: awaiting merge

#112254 gh-118518: Allow perf to work without frame pointers
  Doc/c-api/init_config.rst
  Doc/howto/perf_profiling.rst
  Doc/using/cmdline.rst
  Doc/whatsnew/3.13.rst
  Include/internal/pycore_ceval.h
  Include/internal/pycore_ceval_state.h
  Lib/test/test_perf_profiler.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2024-05-02-20-32-42.gh-issue-118518.m-JbTi.rst
  PCbuild/_freeze_module.vcxproj
  PCbuild/_freeze_module.vcxproj.filters
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/initconfig.c
  Python/perf_jit_trampoline.c
  Python/perf_trampoline.c
  Python/pylifecycle.c
  Python/sysmodule.c
  Tools/c-analyzer/cpython/ignored.tsv
Labels: awaiting core review

#118583 gh-74929: Fix an extra DECREF for PEP 667 implementation
  Lib/test/test_frame.py
  Objects/frameobject.c
Labels: awaiting merge, skip news

#118483 gh-118164: Break a loop between _pydecimal and _pylong and optimize int to str conversion
  Lib/_pylong.py
  Lib/test/test_int.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-02-15-57-07.gh-issue-118164.AF6kwI.rst
Labels: awaiting merge

#118456 gh-118455: Fix mangle_from_ default value in email.policy.Policy.__doc__
  Lib/email/_policybase.py
Labels: awaiting merge, skip news

#118132 gh-118131: Command-line interface for the `random` module
  Doc/library/cmdline.rst
  Doc/library/random.rst
  Doc/whatsnew/3.13.rst
  Lib/random.py
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2024-04-21-18-55-42.gh-issue-118131.eAT0is.rst
Labels: awaiting merge, stdlib

#118584 [3.12] gh-118164: str(10**10000) hangs if the C _decimal module is missing (GH-118503)
  Lib/_pydecimal.py
  Lib/test/test_decimal.py
  Misc/NEWS.d/next/Library/2024-05-04-20-22-59.gh-issue-118164.9D02MQ.rst
Labels: awaiting review

#118585 Minor edit: Simplify and tighten the distribution test
  Lib/test/test_statistics.py
Labels: tests, skip issue, awaiting core review, skip news

#118586 [3.12] gh-118455: Fix mangle_from_ default value in email.policy.Policy.__doc__ (GH-118456)
  Lib/email/_policybase.py
Labels: awaiting merge, skip news

#118559 gh-118476: Fix corner cases in islice() rough equivalent.
  Doc/library/itertools.rst
Labels: type-bug, docs, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12

#118587 [3.12] gh-118476: Fix corner cases in islice() rough equivalent. (Gh-118559)
  Doc/library/itertools.rst
Labels: type-bug, docs, awaiting merge, skip news

#118552 gh-110850: Remove _PyTime_TimeUnchecked() function
  Include/internal/pycore_time.h
  Modules/_lsprof.c
  Modules/_testinternalcapi/test_lock.c
  Python/gc.c
  Python/gc_free_threading.c
  Python/import.c
  Python/lock.c
  Python/parking_lot.c
  Python/pytime.c
  Python/thread_pthread.h
Labels: awaiting core review, skip news

#118592 gh-118518: Use the raw syscall directly for gettid
  Python/perf_jit_trampoline.c
Labels: awaiting core review, skip news

#17995 bpo-39324: Add markdown mimetype mapping
  Lib/mimetypes.py
  Misc/NEWS.d/next/Library/2020-01-14-09-46-51.bpo-39324.qUcDrM.rst
Labels: awaiting merge, needs backport to 3.12

#118593 gh-101137: Add `text/x-rst` to `mimetypes`
  Lib/mimetypes.py
  Lib/test/test_mimetypes.py
  Misc/NEWS.d/next/Library/2024-05-05-16-08-03.gh-issue-101137.71ECXu.rst
Labels: awaiting merge

#118579 gh-111744: Make `breakpoint()` enter the debugger immediately
  Doc/library/bdb.rst
  Doc/library/pdb.rst
  Doc/whatsnew/3.13.rst
  Lib/bdb.py
  Lib/pdb.py
  Lib/test/test_doctest/test_doctest.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2024-05-04-18-40-43.gh-issue-111744.nuCtwN.rst
Labels: awaiting merge

#118581 gh-74929: Rudimentary docs for PEP 667
  Doc/c-api/frame.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.13.rst
  Misc/NEWS.d/next/Core and Builtins/2024-04-27-21-44-40.gh-issue-74929.C2nESp.rst
Labels: docs, awaiting merge

#118600 Fix negative bandwidth test and add online code path test.
  Lib/statistics.py
  Lib/test/test_statistics.py
Labels: tests, skip issue, awaiting core review, skip news

#117390 gh-117389: Fix `test_compileall.EncodingTest`
  Lib/test/test_compileall.py
Labels: tests, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12

#118603 [3.12] gh-117389: Fix `test_compileall.EncodingTest` (GH-117390)
  Lib/test/test_compileall.py
Labels: tests, awaiting merge, skip news

#118580 gh-117549: Don't use designated initializers in headers
  Include/internal/pycore_backoff.h
  Misc/NEWS.d/next/Core and Builtins/2024-05-05-12-04-02.gh-issue-117549.kITawD.rst
Labels: awaiting merge

#111567 gh-111201: A new Python REPL
  .github/workflows/mypy.yml
  .github/workflows/reusable-macos.yml
  .github/workflows/reusable-ubuntu.yml
  Doc/glossary.rst
  Doc/tutorial/appendix.rst
  Doc/using/cmdline.rst
  Doc/whatsnew/3.13.rst
  Lib/_pyrepl/__init__.py
  Lib/_pyrepl/__main__.py
  Lib/_pyrepl/_minimal_curses.py
  Lib/_pyrepl/commands.py
  Lib/_pyrepl/completing_reader.py
  Lib/_pyrepl/console.py
  Lib/_pyrepl/curses.py
  Lib/_pyrepl/fancy_termios.py
  Lib/_pyrepl/historical_reader.py
  Lib/_pyrepl/input.py
  Lib/_pyrepl/keymap.py
  Lib/_pyrepl/mypy.ini
  Lib/_pyrepl/pager.py
  Lib/_pyrepl/reader.py
  Lib/_pyrepl/readline.py
  Lib/_pyrepl/simple_interact.py
  Lib/_pyrepl/trace.py
  Lib/_pyrepl/types.py
  Lib/_pyrepl/unix_console.py
  Lib/_pyrepl/unix_eventqueue.py
  Lib/_pyrepl/utils.py
  Lib/code.py
  Lib/pydoc.py
  Lib/site.py
  Lib/test/test_pyrepl.py
  Lib/test/test_traceback.py
  Lib/traceback.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core and Builtins/2024-04-28-00-41-17.gh-issue-111201.cQsh5U.rst
  Modules/main.c
  Python/clinic/sysmodule.c.h
  Python/pythonrun.c
  Python/stdlib_module_names.h
  Python/sysmodule.c
Labels: awaiting merge

#118582 Move pathlib implementation out of `__init__.py`
  Lib/pathlib/__init__.py
  Lib/pathlib/_abc.py
  Lib/pathlib/_glob.py
  Lib/pathlib/_local.py
Labels: skip issue, awaiting core review, skip news, topic-pathlib

#118607 gh-118605: Fix reference leak in FrameLocalsProxy
  Objects/frameobject.c
Labels: awaiting merge, skip news

#118612 gh-111140: minor docs typos cleanup in the C example API calls.
  Doc/c-api/long.rst
Labels: docs, awaiting core review, skip news

#118616 Add Lysandros Nikolaou to the News entry of gh-111201
  Misc/NEWS.d/next/Core and Builtins/2024-04-28-00-41-17.gh-issue-111201.cQsh5U.rst
Labels: docs, awaiting merge

#118620 Correct timing sensitivity in iOS testing Makefile target.
  Makefile.pre.in
Labels: skip issue, awaiting review, skip news

#118621 Set a DerivedData path for iOS test builds.
  Makefile.pre.in
Labels: skip issue, awaiting merge, skip news

#118614 gh-118613: Fix error handling of `_PyEval_GetFrameLocals` in `ceval.c`
  Python/ceval.c
Labels: awaiting merge, skip news

#9502 gh-78955: Use user-selected color theme for Help => IDLE Doc
  Lib/idlelib/News3.txt
  Lib/idlelib/help.py
  Misc/NEWS.d/next/IDLE/2018-09-23-01-36-39.bpo-34774.VeM-X-.rst
Labels: type-feature, awaiting merge, needs backport to 3.12

#118105 gh-95382: Improve performance of json encoder with indent
  Lib/json/encoder.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-03-18-01-26.gh-issue-95382.73FSEv.rst
  Modules/_json.c
Labels: awaiting review

#118632 [3.12] gh-78955: Use user-selected color theme for Help => IDLE Doc (GH-9502)
  Lib/idlelib/News3.txt
  Lib/idlelib/help.py
  Misc/NEWS.d/next/IDLE/2018-09-23-01-36-39.bpo-34774.VeM-X-.rst
Labels: type-feature, awaiting review

#118631 gh-115119: Bump CI to use Ubuntu 22.04
  .github/workflows/build.yml
  .github/workflows/reusable-ubuntu.yml
  .github/workflows/reusable-wasi.yml
Labels: awaiting merge, skip news, needs backport to 3.12

#118475 gh-118465: Add __firstlineno__ attribute to class
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.13.rst
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Include/internal/pycore_unicodeobject_generated.h
  Lib/enum.py
  Lib/importlib/_bootstrap_external.py
  Lib/inspect.py
  Lib/pydoc.py
  Lib/test/test_compile.py
  Lib/test/test_descr.py
  Lib/test/test_inspect/test_inspect.py
  Lib/test/test_metaclass.py
  Lib/typing.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-01-17-12-36.gh-issue-118465.g3Q8iE.rst
  Python/compile.c
Labels: awaiting merge

#118634 [3.12] gh-115119: Bump CI to use Ubuntu 22.04 (#118631)
  .github/workflows/build.yml
  .github/workflows/reusable-ubuntu.yml
Labels: awaiting merge, skip news

#118590 [3.12] gh-118164: Break a loop between _pydecimal and _pylong and optimize int to str conversion (GH-118483)
  Lib/_pylong.py
  Lib/test/test_int.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-02-15-57-07.gh-issue-118164.AF6kwI.rst
Labels: awaiting review

#118635 gh-111201: Fix event queue tests for pyrepl
  Lib/test/test_pyrepl.py
Labels: tests, awaiting merge, skip news

#118265 gh-74929: locals() documentation update for PEP 667
  Doc/library/functions.rst
Labels: docs, awaiting core review, skip news

#118624 gh-74929: Make containment checks more efficient in `FrameLocalsProxy`
  Objects/frameobject.c
Labels: awaiting merge, skip news

#118638 gh-111201: Use a more common constant in completion tests in test_pyrepl
  Lib/test/test_pyrepl.py
Labels: tests, awaiting merge, skip news

#117258 gh-66543: Add mimetypes.guess_file_type()
  Doc/includes/email-dir.py
  Doc/library/mimetypes.rst
  Doc/library/wsgiref.rst
  Doc/whatsnew/3.13.rst
  Lib/http/server.py
  Lib/mimetypes.py
  Lib/test/test_mimetypes.py
  Misc/NEWS.d/next/Library/2024-03-26-15-29-39.gh-issue-66543.OZBhU5.rst
Labels: awaiting merge

#116930 gh-116871: Improve name suggestions in tracebacks
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2024-03-17-18-24-23.gh-issue-116871.9uSl8M.rst
Labels: awaiting merge

#118622 Fix typo in Lib/zipfile/_path/__init__.py
  Lib/zipfile/_path/__init__.py
Labels: skip issue, awaiting merge, skip news

#118646 gh-118518: Correct type of perf_profiling in config
  Python/initconfig.c
Labels: awaiting core review, skip news

#118228 gh-118225: Support more options for copying images in Tkinter
  Doc/library/tkinter.rst
  Doc/whatsnew/3.13.rst
  Lib/test/test_tkinter/test_images.py
  Lib/tkinter/__init__.py
  Misc/NEWS.d/next/Library/2024-04-24-16-07-26.gh-issue-118225.KdrcgL.rst
Labels: awaiting core review

#118627 Fix typo in Doc/library/asyncio-task.rst
  Doc/library/asyncio-task.rst
Labels: docs, skip issue, awaiting merge, skip news

#118273 gh-118271: Support more options for reading/writing images in Tkinter
  Doc/whatsnew/3.13.rst
  Lib/test/test_tkinter/test_images.py
  Lib/tkinter/__init__.py
  Misc/NEWS.d/next/Library/2024-04-25-11-49-11.gh-issue-118271.5N2Xcy.rst
Labels: awaiting core review

#118615 gh-118609: Add proper error check for framelocalsproxy
  Objects/frameobject.c
Labels: awaiting merge, skip news

#117632 GH-115577 Clarify netloc term usage in urllib.parse docs
  Doc/library/urllib.parse.rst
Labels: docs, awaiting merge, skip news

#118645 gh-116322: Rename PyModule_ExperimentalSetGIL to PyUnstable_Module_SetGIL
  Doc/c-api/module.rst
  Include/moduleobject.h
  Misc/NEWS.d/next/Core and Builtins/2024-03-12-13-51-09.gh-issue-116322.q8TcDQ.rst
  Modules/_cursesmodule.c
  Modules/_datetimemodule.c
  Modules/_testbuffer.c
  Modules/_testcapimodule.c
  Modules/_testclinic.c
  Modules/_testclinic_limited.c
  Modules/_testexternalinspection.c
  Modules/_testlimitedcapi.c
  Modules/_testmultiphase.c
  Modules/_testsinglephase.c
  Modules/_tkinter.c
  Modules/_tracemalloc.c
  Modules/readline.c
  Objects/moduleobject.c
  Python/bltinmodule.c
  Python/sysmodule.c
Labels: awaiting merge

#118656 [3.12] GH-115577 Clarify netloc term usage in urllib.parse docs (GH-117632)
  Doc/library/urllib.parse.rst
Labels: docs, awaiting review, skip news

#118291 gh-71592: Add ability to trace Tcl commands executed by Tkinter
  Lib/tkinter/__init__.py
  Modules/_tkinter.c
  Modules/clinic/_tkinter.c.h
Labels: awaiting core review, skip news, needs backport to 3.12

#117906 GH-117714: implement athrow().close() and asend().close() using throw
  Lib/test/test_asyncgen.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-01-07-06-48.gh-issue-117714.Ip_dm5.rst
  Objects/genobject.c
Labels: awaiting merge

#118654 gh-118518: Ensure that the code padding it's applied
  Python/perf_jit_trampoline.c
Labels: awaiting core review, skip news

#118454 gh-118362: Fix thread safety around lookups from the type cache in the face of concurrent mutators
  Include/cpython/object.h
  Include/cpython/pyatomic.h
  Include/cpython/pyatomic_gcc.h
  Include/cpython/pyatomic_msc.h
  Include/cpython/pyatomic_std.h
  Include/internal/pycore_dict.h
  Include/internal/pycore_object.h
  Lib/test/test_class.py
  Lib/test/test_free_threading/test_type.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-01-14-20-28.gh-issue-118492.VUsSfn.rst
  Modules/_collectionsmodule.c
  Modules/_ctypes/_ctypes.c
  Modules/_lsprof.c
  Modules/_testcapi/gc.c
  Objects/classobject.c
  Objects/dictobject.c
  Objects/object.c
  Objects/typeobject.c
Labels: awaiting merge, skip news, topic-free-threading

#111094 gh-83151: Make closure work on pdb
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2023-10-20-03-50-17.gh-issue-83151.bcsD40.rst
Labels: awaiting merge

#118539 gh-115119: Default to --with-system-libmpdec=yes
  .github/workflows/posix-deps-apt.sh
  Doc/using/configure.rst
  Doc/whatsnew/3.13.rst
  Misc/NEWS.d/next/Build/2024-05-06-00-39-06.gh-issue-115119.LT27pF.rst
  configure
  configure.ac
Labels: awaiting merge

#118664 gh-71592: Fix a leak in tkinter.Tk destructor when _debug is true
  Modules/_tkinter.c
Labels: awaiting core review, skip news

#118662 [3.12] gh-71592: Add ability to trace Tcl commands executed by Tkinter (GH-118291)
  Lib/tkinter/__init__.py
  Modules/_tkinter.c
  Modules/clinic/_tkinter.c.h
Labels: awaiting core review, skip news

#118665 gh-118628: Don't display pyrepl warning on Windows
  Lib/_pyrepl/__main__.py
Labels: awaiting merge, skip news

#118496 gh-118415: Fix issues with local tracing being enabled/disabled on a function
  Lib/test/test_free_threading/test_monitoring.py
  Python/instrumentation.c
Labels: awaiting merge, skip news, topic-free-threading
