Repository python/cpython, pull requests merged in 2024-06, with the labels that each got.

#119379 gh-74929: PEP 667 C API documentation
  Doc/c-api/reflection.rst
  Doc/data/refcounts.dat
  Doc/whatsnew/3.13.rst
  Lib/test/test_sys.py
  Objects/frameobject.c
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/sysmodule.c
Labels: docs, awaiting core review, skip news, 3.13, 3.14, needs backport to 3.13

#119892 [3.13] gh-74929: PEP 667 C API documentation (gh-119379)
  Doc/c-api/reflection.rst
  Doc/data/refcounts.dat
  Doc/whatsnew/3.13.rst
  Lib/test/test_sys.py
  Objects/frameobject.c
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/sysmodule.c
Labels: awaiting review, skip news

#119889 [3.13] gh-119821: Support non-dict globals in LOAD_FROM_DICT_OR_GLOBALS (#119822)
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_metadata.h
  Lib/test/test_type_aliases.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-30-23-01-00.gh-issue-119821.jPGfvt.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_cases.c.h
Labels: awaiting core review

#119890 [3.12] gh-119821: Support non-dict globals in LOAD_FROM_DICT_OR_GLOBALS (#119822)
  Lib/test/test_type_aliases.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-30-23-01-00.gh-issue-119821.jPGfvt.rst
  Python/bytecodes.c
  Python/generated_cases.c.h
Labels: awaiting core review

#119893 gh-118888: Further PEP 667 docs updates
  Doc/c-api/reflection.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting core review, skip news, 3.13, 3.14, needs backport to 3.13

#119883 gh-117657: Fix TSAN race in free-threaded GC
  Python/gc_free_threading.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#119887 gh-117657: Fix TSAN race in QSBR assertion
  Python/qsbr.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#119903 [3.13] gh-117657: Fix TSAN race in free-threaded GC (GH-119883)
  Python/gc_free_threading.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting review, skip news

#119904 [3.13] gh-117657: Fix TSAN race in QSBR assertion (GH-119887)
  Python/qsbr.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting review, skip news

#119905 [3.12] Revert "[3.12] gh-69214: Fix fcntl.ioctl() request type (#119498) (#1…
  Misc/NEWS.d/next/Library/2024-05-24-11-47-08.gh-issue-69214.Grl6zF.rst
  Modules/clinic/fcntlmodule.c.h
  Modules/fcntlmodule.c
Labels: awaiting core review

#119906 [3.13] Revert "[3.13] gh-69214: Fix fcntl.ioctl() request type (GH-119498) (…
  Misc/NEWS.d/next/Library/2024-05-24-11-47-08.gh-issue-69214.Grl6zF.rst
  Modules/clinic/fcntlmodule.c.h
  Modules/fcntlmodule.c
Labels: awaiting core review

#119519 gh-113892: Add a extra check to `ProactorEventLoop.sock_connect` to ensure that the given socket is in non-blocking mode
  Lib/asyncio/proactor_events.py
  Lib/test/test_asyncio/test_proactor_events.py
  Misc/NEWS.d/next/Library/2024-05-24-21-54-55.gh-issue-113892.JKDFqq.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#119908 gh-117657: Add TSAN suppression for `set_discard_entry`
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#119912 [3.13] gh-113892: Add a extra check to `ProactorEventLoop.sock_connect` to ensure that the given socket is in non-blocking mode (GH-119519)
  Lib/asyncio/proactor_events.py
  Lib/test/test_asyncio/test_proactor_events.py
  Misc/NEWS.d/next/Library/2024-05-24-21-54-55.gh-issue-113892.JKDFqq.rst
Labels: awaiting merge

#119913 [3.12] gh-113892: Add a extra check to `ProactorEventLoop.sock_connect` to ensure that the given socket is in non-blocking mode (GH-119519)
  Lib/asyncio/proactor_events.py
  Lib/test/test_asyncio/test_proactor_events.py
  Misc/NEWS.d/next/Library/2024-05-24-21-54-55.gh-issue-113892.JKDFqq.rst
Labels: awaiting merge

#119911 Add unique() recipe to itertools docs
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#119914 [3.13] gh-117657: Add TSAN suppression for `set_discard_entry` (GH-119908)
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting review, skip news

#119916 [3.13] Add unique() recipe to itertools docs (gh-119911)
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting review, skip news

#119917 [3.12] Add unique() recipe to itertools docs (gh-119911)
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting review, skip news

#119808 GH-89727: Fix `shutil.rmtree()` recursion error on deep trees
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2024-05-30-21-37-05.gh-issue-89727.D6S9ig.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#119918 [3.13] GH-89727: Fix `shutil.rmtree()` recursion error on deep trees (GH-119808)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2024-05-30-21-37-05.gh-issue-89727.D6S9ig.rst
Labels: awaiting merge

#119919 [3.12] GH-89727: Fix `shutil.rmtree()` recursion error on deep trees (GH-119808)
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/NEWS.d/next/Library/2024-05-30-21-37-05.gh-issue-89727.D6S9ig.rst
Labels: awaiting core review

#119922 [3.12] gh-116145: Update macOS installer to Tcl/Tk 8.6.14 (GH-116151)
  Mac/BuildScript/backport_gh92603_fix.patch
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2024-02-29-20-52-23.gh-issue-116145.ygafim.rst
Labels: awaiting merge

#119130 gh-119016: Remove outdated sentences from the "classes" tutorial
  Doc/tutorial/classes.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#119924 [3.13] gh-111201: Skip pyrepl Windows tests earlier (#119848)
  Lib/test/test_pyrepl/test_windows_console.py
Labels: tests, awaiting core review, skip news

#119926 [3.12] gh-119016: Remove outdated sentences from the "classes" tutorial (GH-119130)
  Doc/tutorial/classes.rst
Labels: docs, awaiting review, skip news

#119925 [3.13] gh-119016: Remove outdated sentences from the "classes" tutorial (GH-119130)
  Doc/tutorial/classes.rst
Labels: docs, awaiting review, skip news

#119930 Refactor (mostly rearrange) the statistics module
  Lib/statistics.py
  Lib/test/test_statistics.py
Labels: skip issue, awaiting core review, skip news

#119932 gh-118934: Fix PyEval_GetLocals docs (PEP 667)
  Doc/c-api/reflection.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting core review, skip news, 3.13, 3.14, needs backport to 3.13

#119894 [3.13] gh-118888: Further PEP 667 docs updates (gh-119893)
  Doc/c-api/reflection.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting review, skip news

#119934 [3.13] gh-118934: Fix PyEval_GetLocals docs (PEP 667) (GH-119932)
  Doc/c-api/reflection.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting review, skip news

#119776 gh-119775: Remove ability to create immutable types with mutable bases
  Doc/whatsnew/3.14.rst
  Lib/test/test_capi/test_misc.py
  Misc/NEWS.d/next/C API/2024-05-30-12-51-21.gh-issue-119775.CBq9IG.rst
  Objects/typeobject.c
Labels: awaiting merge

#119743 gh-119740: Remove deprecated trunc delegation
  Doc/library/functions.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.14.rst
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Include/internal/pycore_unicodeobject_generated.h
  Lib/test/test_int.py
  Lib/test/test_long.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-29-18-53-43.gh-issue-119740.zP2JNM.rst
  Objects/abstract.c
Labels: awaiting merge

#119921 gh-117657: Fix TSAN reported race in `_PyEval_IsGILEnabled`.
  Include/internal/pycore_ceval.h
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#119939 [3.13] gh-117657: Fix TSAN reported race in `_PyEval_IsGILEnabled`. (GH-119921)
  Include/internal/pycore_ceval.h
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting review, skip news

#119928 Improve documentation for typing.get_type_hints
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news, topic-typing, needs backport to 3.12, needs backport to 3.13

#119944 [3.12] Improve documentation for typing.get_type_hints (GH-119928)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting review, skip news

#119943 [3.13] Improve documentation for typing.get_type_hints (GH-119928)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting review, skip news

#119951 [3.13] GH-119054: Add "Querying file type and status" section to pathlib docs (GH-119055)
  Doc/library/pathlib.rst
Labels: docs, awaiting core review, skip news, topic-pathlib

#119952 [3.12] GH-119054: Add "Querying file type and status" section to pathlib docs (GH-119055)
  Doc/library/pathlib.rst
Labels: docs, awaiting core review, skip news, topic-pathlib

#119524 GH-119054: Add "Reading and writing files" section to pathlib docs
  Doc/library/pathlib.rst
Labels: docs, awaiting merge, skip news, topic-pathlib, needs backport to 3.12, needs backport to 3.13

#119954 [3.13] GH-119054: Add "Reading and writing files" section to pathlib docs (GH-119524)
  Doc/library/pathlib.rst
Labels: docs, awaiting review, skip news

#119955 [3.12] GH-119054: Add "Reading and writing files" section to pathlib docs (GH-119524)
  Doc/library/pathlib.rst
Labels: docs, awaiting core review, skip news, topic-pathlib

#119958 gh-109975: What's New in Python 3.13: `telnetlib` projects not found
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting review, skip news, needs backport to 3.13

#119959 [3.13] gh-109975: What's New in Python 3.13: fix broken link for `telnetlib` alternative (GH-119958)
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting review, skip news

#119907 gh-117657: Fix data races report by TSAN unicode-hash
  Objects/unicodeobject.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, needs backport to 3.13

#119963 [3.13] gh-117657: Fix data races report by TSAN unicode-hash (gh-119907)
  Objects/unicodeobject.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news

#119962 gh-119961: Fix test workflow status badge in README
  README.rst
Labels: docs, awaiting merge, skip news

#119957 gh-119396: Optimize unicode_decode_utf8_writer()
  Objects/unicodeobject.c
Labels: awaiting core review, skip news

#118828 gh-118827: Remove `Quoter` from `urllib.parse`
  Doc/whatsnew/3.14.rst
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Library/2024-05-09-12-33-25.gh-issue-118827.JrzHz1.rst
Labels: awaiting merge

#116992 gh-116991: Improve `pygen --help` for `python` subparser
  Tools/peg_generator/pegen/__main__.py
Labels: awaiting merge, skip news

#119858 gh-119856: Support exiting help() with just "exit"
  Lib/pydoc.py
Labels: awaiting core review, skip news, needs backport to 3.13

#119855 gh-112026: Deprecate _PyDict_GetItemStringWithError() function
  Include/cpython/dictobject.h
Labels: awaiting merge, skip news, topic-C-API

#119967 [3.13] gh-119856: Support exiting help() with just "exit" (GH-119858)
  Lib/pydoc.py
Labels: awaiting review, skip news

#119839 gh-119838: Treat Fraction as a real value in mixed arithmetic operations with complex
  Lib/fractions.py
  Lib/test/test_fractions.py
  Misc/NEWS.d/next/Library/2024-05-31-13-56-21.gh-issue-119838.H6XHlE.rst
Labels: awaiting core review

#119970 [3.13] gh-119336: Restore removed _PyLong_NumBits() function (GH-119418)
  Include/cpython/longobject.h
  Include/internal/pycore_long.h
  Misc/NEWS.d/next/C API/2024-05-22-17-50-48.gh-issue-119336.ff3qnS.rst
Labels: awaiting review

#119969 gh-119968: Improved monitoring c-api docs
  Doc/c-api/monitoring.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13

#119815 gh-119786: move exception handling doc to InternalDocs
  InternalDocs/README.md
  InternalDocs/exception_handling.md
  Objects/exception_handling_notes.txt
Labels: docs, awaiting merge, skip news

#119971 [3.13] gh-119968: Improved monitoring c-api docs (GH-119969)
  Doc/c-api/monitoring.rst
Labels: docs, awaiting merge, skip news

#116561 gh-116560: Add PyLong_GetSign() public function
  Doc/c-api/long.rst
  Doc/whatsnew/3.14.rst
  Include/cpython/longobject.h
  Lib/test/test_capi/test_long.py
  Misc/NEWS.d/next/C API/2024-03-10-14-55-51.gh-issue-116560.x2mZaO.rst
  Modules/_testcapi/long.c
  Objects/longobject.c
Labels: awaiting merge

#119895 gh-102511: Amend 3.13.0b1.rst
  Misc/NEWS.d/3.13.0b1.rst
Labels: docs, awaiting review, skip news, needs backport to 3.13

#119980 [3.13] gh-102511: Amend 3.13.0b1.rst (GH-119895)
  Misc/NEWS.d/3.13.0b1.rst
Labels: docs, awaiting review, skip news

#119790 gh-119679: Ensures correct import libraries are included in Windows installs
  Misc/NEWS.d/next/Windows/2024-05-30-17-39-25.gh-issue-119679.mZC87w.rst
  PC/layout/main.py
  Tools/msi/freethreaded/freethreaded_files.wxs
Labels: OS-windows, awaiting core review, needs backport to 3.13

#119983 [3.13] gh-119679: Ensures correct import libraries are included in Windows install packages (GH-119790)
  Misc/NEWS.d/next/Windows/2024-05-30-17-39-25.gh-issue-119679.mZC87w.rst
  PC/layout/main.py
  Tools/msi/freethreaded/freethreaded_files.wxs
Labels: awaiting review

#119591 gh-119588: Implement zipfile.Path.is_symlink (zipp 3.19.0).
  Doc/library/zipfile.rst
  Lib/test/test_zipfile/_path/test_path.py
  Lib/zipfile/_path/__init__.py
  Misc/NEWS.d/next/Library/2024-05-26-21-28-11.gh-issue-119588.wlLBK5.rst
Labels: awaiting core review, needs backport to 3.12, needs backport to 3.13

#119979 Use Cirrus M1 macOS runners for CI
  .github/workflows/build.yml
  Lib/test/test_pyrepl/test_unix_console.py
  Lib/test/test_pyrepl/test_windows_console.py
Labels: skip issue, awaiting merge, skip news, needs backport to 3.13

#119982 gh-119981: use do { ... } while(0) in some multi-line macros
  Python/symtable.c
Labels: awaiting review, skip news

#119066 gh-119057: Use better error messages for zero division
  Doc/howto/logging-cookbook.rst
  Lib/_pylong.py
  Lib/test/mathdata/ieee754.txt
  Lib/test/test_builtin.py
  Lib/test/test_doctest/test_doctest.py
  Lib/test/test_generators.py
  Lib/test/test_genexps.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-15-12-15-58.gh-issue-119057.P3G9G2.rst
  Objects/complexobject.c
  Objects/floatobject.c
  Objects/longobject.c
Labels: awaiting merge

#119986 [3.13] Use Cirrus M1 macOS runners for CI (GH-119979)
  .github/workflows/build.yml
  Lib/test/test_pyrepl/test_unix_console.py
  Lib/test/test_pyrepl/test_windows_console.py
Labels: skip issue, awaiting review, skip news

#119987 [3.12] Use Cirrus M1 macOS runners for CI (GH-119979)
  .github/workflows/build.yml
  .github/workflows/reusable-macos.yml
  Lib/asyncio/__main__.py
Labels: skip issue, awaiting merge, skip news

#119728 gh-119727: Add --sequentially option to regrtest
  Lib/test/libregrtest/cmdline.py
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/worker.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2024-05-29-15-28-08.gh-issue-119727.dVkaZM.rst
Labels: awaiting merge

#119942 gh-118835: pyrepl: Fix prompt length computation for custom prompts containing ANSI escape codes
  Lib/_pyrepl/reader.py
  Lib/test/test_pyrepl/test_reader.py
  Misc/NEWS.d/next/Library/2024-06-02-15-09-17.gh-issue-118835.KUAuz6.rst
Labels: awaiting merge, needs backport to 3.13, topic-repl

#119990 [3.13] gh-118835: pyrepl: Fix prompt length computation for custom prompts containing ANSI escape codes (GH-119942)
  Lib/_pyrepl/reader.py
  Lib/test/test_pyrepl/test_reader.py
  Misc/NEWS.d/next/Library/2024-06-02-15-09-17.gh-issue-118835.KUAuz6.rst
Labels: awaiting merge

#119915 gh-117657: Avoid `sem_clockwait` in TSAN
  Python/parking_lot.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting core review, skip news, topic-free-threading, needs backport to 3.13

#119992 [3.13] gh-117657: Avoid `sem_clockwait` in TSAN (GH-119915)
  Python/parking_lot.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting review, skip news

#119975 [3.12] gh-119821: Fix refleak in LOAD_FROM_DICT_OR_GLOBALS
  Python/bytecodes.c
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#119927 gh-117657: Fix race involving immortalizing objects
  Include/internal/pycore_gc.h
  Lib/test/support/__init__.py
  Modules/_testinternalcapi.c
  Objects/codeobject.c
  Objects/object.c
  Python/bltinmodule.c
  Python/gc_free_threading.c
  Python/pystate.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#119810 gh-117398: Add datetime Module State
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Include/internal/pycore_unicodeobject_generated.h
  Modules/_datetimemodule.c
Labels: awaiting core review, skip news, needs backport to 3.13

#120005 [3.13] gh-117657: Fix race involving immortalizing objects (GH-119927)
  Include/internal/pycore_gc.h
  Lib/test/support/__init__.py
  Modules/_testinternalcapi.c
  Objects/codeobject.c
  Objects/object.c
  Python/bltinmodule.c
  Python/gc_free_threading.c
  Python/pystate.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting core review, skip news

#119991 gh-117142: Support Importing ctypes in Isolated Interpreters
  Misc/NEWS.d/next/Library/2024-06-03-11-18-16.gh-issue-117142.kWTXQo.rst
  Modules/_ctypes/_ctypes.c
Labels: awaiting core review, needs backport to 3.13

#120007 [3.13] gh-117657: Fix itertools.count thread safety (GH-119268)
  Lib/test/test_itertools.py
  Modules/itertoolsmodule.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting core review, skip news, topic-free-threading

#120004 [3.13] gh-117398: Add datetime Module State (gh-119810)
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Include/internal/pycore_unicodeobject_generated.h
  Modules/_datetimemodule.c
Labels: awaiting review, skip news

#120008 [3.13] gh-117142: Support Importing ctypes in Isolated Interpreters (gh-119991)
  Misc/NEWS.d/next/Library/2024-06-03-11-18-16.gh-issue-117142.kWTXQo.rst
  Modules/_ctypes/_ctypes.c
Labels: awaiting review

#119929 gh-117398: Use Per-Interpreter State for the _datetime Static Types
  Include/internal/pycore_object.h
  Include/internal/pycore_typeobject.h
  Misc/NEWS.d/next/Library/2024-06-01-16-58-43.gh-issue-117398.kR0RW7.rst
  Modules/_datetimemodule.c
  Objects/exceptions.c
  Objects/object.c
  Objects/structseq.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Objects/weakrefobject.c
  Python/crossinterp_exceptions.h
  Tools/c-analyzer/cpython/globals-to-fix.tsv
  Tools/c-analyzer/cpython/ignored.tsv
Labels: awaiting merge, needs backport to 3.13

#120009 [3.13] gh-117398: Use Per-Interpreter State for the _datetime Static Types (gh-119929)
  Include/internal/pycore_object.h
  Include/internal/pycore_typeobject.h
  Misc/NEWS.d/next/Library/2024-06-01-16-58-43.gh-issue-117398.kR0RW7.rst
  Modules/_datetimemodule.c
  Objects/exceptions.c
  Objects/object.c
  Objects/structseq.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Objects/weakrefobject.c
  Python/crossinterp_exceptions.h
  Tools/c-analyzer/cpython/globals-to-fix.tsv
  Tools/c-analyzer/cpython/ignored.tsv
Labels: awaiting review

#119974 gh-119724: Revert "bpo-45759: Better error messages for non-matching 'elif'/'else' statements (#29513)"
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core and Builtins/2024-06-03-13-25-04.gh-issue-119724.EH1dkA.rst
  Parser/parser.c
Labels: awaiting merge, needs backport to 3.13

#117054 gh-106531: Apply changes from importlib_resources 6.3.2
  Lib/importlib/resources/_common.py
  Lib/importlib/resources/readers.py
  Lib/test/test_importlib/resources/data01/subdirectory/binary.file
  Lib/test/test_importlib/resources/namespacedata01/subdirectory/binary.file
  Lib/test/test_importlib/resources/test_contents.py
  Lib/test/test_importlib/resources/test_custom.py
  Lib/test/test_importlib/resources/test_files.py
  Lib/test/test_importlib/resources/test_open.py
  Lib/test/test_importlib/resources/test_path.py
  Lib/test/test_importlib/resources/test_read.py
  Lib/test/test_importlib/resources/test_reader.py
  Lib/test/test_importlib/resources/test_resource.py
  Lib/test/test_importlib/resources/util.py
  Lib/test/test_importlib/resources/zip.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2024-03-19-21-41-31.gh-issue-106531.Mgd--6.rst
Labels: awaiting merge, needs backport to 3.13

#119334 [3.13] gh-111389: Add PyHASH_MULTIPLIER constant (GH-119214)
  Doc/c-api/hash.rst
  Include/cpython/pyhash.h
  Misc/NEWS.d/next/C API/2024-05-20-10-35-22.gh-issue-111389.a6axBk.rst
  Objects/codeobject.c
  Python/optimizer.c
  Python/pyhash.c
  Python/tracemalloc.c
Labels: awaiting merge

#119880 gh-119879: Utilize last character gap for two-way periodic needles
  Misc/NEWS.d/next/Core and Builtins/2024-06-02-06-12-35.gh-issue-119879.Jit951.rst
  Objects/stringlib/fastsearch.h
Labels: performance, awaiting review

#119846 gh-119070: Update test_shebang_executable_extension to always use non-installed version
  Lib/test/test_launcher.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#120020 gh-119613: Soft deprecate the Py_MEMCPY() macro
  Include/pyport.h
  Misc/NEWS.d/next/C API/2024-06-04-10-58-20.gh-issue-119613.qOr9GF.rst
Labels: awaiting merge

#120021 gh-111499: Fix PYTHONMALLOCSTATS at Python exit
  Python/pylifecycle.c
Labels: awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#120023 [3.12] gh-111499: Fix PYTHONMALLOCSTATS at Python exit (#120021)
  Python/pylifecycle.c
Labels: awaiting core review, skip news

#119763 Fix typos in documentation and comments in Python/
  Python/brc.c
  Python/ceval.c
  Python/flowgraph.c
  Python/gc.c
  Python/import.c
  Python/optimizer.c
  Python/vm-state.md
Labels: skip issue, awaiting merge, skip news

#120015 [3.13] gh-119070: Update test_shebang_executable_extension to always use non-installed version (GH-119846)
  Lib/test/test_launcher.py
Labels: tests, awaiting review, skip news

#120016 [3.12] gh-119070: Update test_shebang_executable_extension to always use non-installed version (GH-119846)
  Lib/test/test_launcher.py
Labels: tests, awaiting review, skip news

#118869 gh-118868: logging QueueHandler fix passing of kwargs
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-05-09-21-36-11.gh-issue-118868.uckxxP.rst
Labels: awaiting merge

#120031 [3.12] gh-118868: logging QueueHandler fix passing of kwargs (GH-118869)
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-05-09-21-36-11.gh-issue-118868.uckxxP.rst
Labels: awaiting review

#120032 [3.13] gh-118868: logging QueueHandler fix passing of kwargs (GH-118869)
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-05-09-21-36-11.gh-issue-118868.uckxxP.rst
Labels: awaiting review

#120030 gh-119819: Fix regression to allow logging configuration with multipr…
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-06-04-12-23-01.gh-issue-119819.WKKrYh.rst
Labels: awaiting core review

#120034 [3.12] gh-119819: Fix regression to allow logging configuration with multipr… (GH-120030)
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-06-04-12-23-01.gh-issue-119819.WKKrYh.rst
Labels: awaiting review

#120035 [3.13] gh-119819: Fix regression to allow logging configuration with multipr… (GH-120030)
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-06-04-12-23-01.gh-issue-119819.WKKrYh.rst
Labels: awaiting review

#119227 gh-94808: Remove unused code in _make_posargs
  Parser/action_helpers.c
Labels: awaiting review, skip news

#119923 gh-117657: Fix race involving GC and heap initialization
  Include/internal/pycore_mimalloc.h
  Python/gc_free_threading.c
  Python/pystate.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#120038 [3.13] gh-117657: Fix race involving GC and heap initialization (GH-119923)
  Include/internal/pycore_mimalloc.h
  Python/gc_free_threading.c
  Python/pystate.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting review, skip news

#120028 gh-120029: export `DEF_TYPE_PARAM` compiler flag
  Doc/library/symtable.rst
  Lib/symtable.py
  Lib/test/test_symtable.py
  Misc/NEWS.d/next/Library/2024-06-04-14-54-46.gh-issue-120029._1YdTf.rst
  Modules/symtablemodule.c
Labels: awaiting merge

#120014 [3.13] gh-106531: Apply changes from importlib_resources 6.3.2 (GH-117054)
  Lib/importlib/resources/_common.py
  Lib/importlib/resources/readers.py
  Lib/test/test_importlib/resources/data01/subdirectory/binary.file
  Lib/test/test_importlib/resources/namespacedata01/subdirectory/binary.file
  Lib/test/test_importlib/resources/test_contents.py
  Lib/test/test_importlib/resources/test_custom.py
  Lib/test/test_importlib/resources/test_files.py
  Lib/test/test_importlib/resources/test_open.py
  Lib/test/test_importlib/resources/test_path.py
  Lib/test/test_importlib/resources/test_read.py
  Lib/test/test_importlib/resources/test_reader.py
  Lib/test/test_importlib/resources/test_resource.py
  Lib/test/test_importlib/resources/util.py
  Lib/test/test_importlib/resources/zip.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2024-03-19-21-41-31.gh-issue-106531.Mgd--6.rst
Labels: awaiting review

#119985 [3.13] gh-119588: Implement zipfile.Path.is_symlink (zipp 3.19.0). (GH-119591)
  Doc/library/zipfile.rst
  Lib/test/test_zipfile/_path/test_path.py
  Lib/zipfile/_path/__init__.py
  Misc/NEWS.d/next/Library/2024-05-26-21-28-11.gh-issue-119588.wlLBK5.rst
Labels: awaiting merge

#120043 gh-119588: Update docs to reflect decision to include the change with Python 3.13 and not 3.12.
  Doc/library/zipfile.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.13

#120046 [3.13] gh-119588: Update docs to reflect decision to include the change with Python 3.13 and not 3.12. (GH-120043)
  Doc/library/zipfile.rst
Labels: docs, awaiting review, skip news

#120042 gh-120041: Do not use append_to_screen when completions are visible
  Lib/_pyrepl/commands.py
  Lib/_pyrepl/completing_reader.py
  Lib/test/test_pyrepl/support.py
  Lib/test/test_pyrepl/test_reader.py
Labels: awaiting core review, skip news, needs backport to 3.13, topic-repl

#120045 Fix incorrect pull GitHub link in What's New
  Doc/whatsnew/3.13.rst
Labels: docs, skip issue, awaiting review, skip news, needs backport to 3.13

#31794 gh-89928: Fix integer conversion of device numbers.
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Library/2022-03-10-16-47-57.bpo-45767.ywmyo1.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: type-bug, awaiting merge, needs backport to 3.12, needs backport to 3.13

#112681 gh-112672: use `Tcl_Size` to avoid incompatible pointer type warnings
  Misc/NEWS.d/next/Library/2024-06-04-19-03-25.gh-issue-112672.K2XfZH.rst
  Modules/_tkinter.c
Labels: awaiting review, topic-tkinter

#120052 [3.13] Fix incorrect pull GitHub link in What's New (GH-120045)
  Doc/whatsnew/3.13.rst
Labels: docs, skip issue, awaiting review, skip news

#120054 [3.12] gh-89928: Fix integer conversion of device numbers (GH-31794)
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Library/2022-03-10-16-47-57.bpo-45767.ywmyo1.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: type-bug, awaiting core review

#120053 [3.13] gh-89928: Fix integer conversion of device numbers (GH-31794)
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Library/2022-03-10-16-47-57.bpo-45767.ywmyo1.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: type-bug, awaiting review

#120055 gh-120041: Refactor check for visible completion menu in completing_reader
  Lib/_pyrepl/commands.py
  Lib/_pyrepl/completing_reader.py
Labels: awaiting core review, skip news, topic-repl

#120047 gh-120039: Reduce expected timeout in test_siginterrupt_off
  Lib/test/test_signal.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#119801 gh-119553: Clear reader on Ctrl-C command
  Lib/_pyrepl/commands.py
  Lib/test/test_pyrepl/support.py
  Lib/test/test_pyrepl/test_reader.py
Labels: awaiting core review, skip news, needs backport to 3.13, topic-repl

#119931 doc: Mention the missing reflected operations
  Doc/reference/expressions.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#120051 [3.13] gh-120041: Do not use append_to_screen when completions are visible (GH-120042)
  Lib/_pyrepl/completing_reader.py
  Lib/test/test_pyrepl/support.py
  Lib/test/test_pyrepl/test_reader.py
Labels: awaiting merge, skip news

#120061 [3.12] gh-120039: Reduce expected timeout in test_siginterrupt_off (GH-120047)
  Lib/test/test_signal.py
Labels: tests, awaiting review, skip news

#120060 [3.13] gh-120039: Reduce expected timeout in test_siginterrupt_off (GH-120047)
  Lib/test/test_signal.py
Labels: tests, awaiting review, skip news

#120062 [3.13] gh-119553: Clear reader on Ctrl-C command (GH-119801)
  Lib/_pyrepl/commands.py
  Lib/test/test_pyrepl/support.py
  Lib/test/test_pyrepl/test_reader.py
Labels: awaiting merge, skip news, topic-repl

#120050 gh-120048: Make `test_imaplib` faster
  Lib/test/test_imaplib.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#120070 [3.12] gh-120048: Make `test_imaplib` faster (GH-120050)
  Lib/test/test_imaplib.py
Labels: tests, awaiting review, skip news

#120066 [3.13] gh-119842: Honor PyOS_InputHook in the new REPL (GH-119843)
  Lib/_pyrepl/console.py
  Lib/_pyrepl/reader.py
  Lib/_pyrepl/unix_console.py
  Lib/_pyrepl/windows_console.py
  Lib/test/test_pyrepl/test_reader.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-31-12-06-11.gh-issue-119842.tCGVsv.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting core review, topic-repl

#120000 gh-119999: Fix potential race condition in `_Py_ExplicitMergeRefcount`
  Objects/object.c
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#120071 [3.12] gh-119819: Update test to skip if _multiprocessing is unavailable. (GH-120067)
  Lib/test/test_logging.py
Labels: tests, awaiting review, skip news

#120072 [3.13] gh-119819: Update test to skip if _multiprocessing is unavailable. (GH-120067)
  Lib/test/test_logging.py
Labels: tests, awaiting review, skip news

#119644 [3.12] gh-119311: Fix name mangling with PEP 695 generic classes (#119464)
  Doc/data/python3.12.abi
  Include/internal/pycore_symtable.h
  Lib/test/test_type_params.py
  Misc/NEWS.d/next/Core and Builtins/2024-05-23-06-34-14.gh-issue-119395.z-Hsqb.rst
  Misc/NEWS.d/next/Core and Builtins/2024-05-23-06-34-45.gh-issue-119311.2DBwKR.rst
  Python/compile.c
  Python/symtable.c
Labels: awaiting merge

#120073 [3.13] gh-119999: Fix potential race condition in `_Py_ExplicitMergeRefcount` (GH-120000)
  Objects/object.c
Labels: awaiting review, skip news

#120069 [3.13] gh-120048: Make `test_imaplib` faster (GH-120050)
  Lib/test/test_imaplib.py
Labels: tests, awaiting merge, skip news

#120075 gh-119553: Fix console when pressing Ctrl-C within a multiline block
  Lib/_pyrepl/commands.py
  Lib/_pyrepl/simple_interact.py
Labels: awaiting merge, skip news, needs backport to 3.13, topic-repl

#120076 [3.13] gh-119553: Fix console when pressing Ctrl-C within a multiline block (GH-120075)
  Lib/_pyrepl/commands.py
  Lib/_pyrepl/simple_interact.py
Labels: awaiting merge, skip news

#120033 gh-114616: Improve docs regarding changes to caches representation in dis
  Doc/library/dis.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.13

#120079 [3.13] gh-114616: Improve docs regarding changes to caches representation in dis (GH-120033)
  Doc/library/dis.rst
  Doc/whatsnew/3.13.rst
Labels: docs, awaiting merge, skip news

#120081 gh-120078: Fixed a typo in the documentation for the time module. Specifically t…
  Doc/library/time.rst
Labels: docs, awaiting merge, skip news

#120084 [3.12] gh-120078: Fix struct_time attr typo tm_day -> tm_mday in Doc/library/time.rst (GH-120081)
  Doc/library/time.rst
Labels: docs, awaiting review, skip news

#120085 [3.13] gh-120078: Fix struct_time attr typo tm_day -> tm_mday in Doc/library/time.rst (GH-120081)
  Doc/library/time.rst
Labels: docs, awaiting review, skip news

#120090 gh-119819: Update logging configuration to support joinable multiproc…
  Lib/logging/config.py
  Lib/test/test_logging.py
Labels: awaiting core review, skip news

#120092 [3.12] gh-119819: Update logging configuration to support joinable multiproc… (GH-120090)
  Lib/logging/config.py
  Lib/test/test_logging.py
Labels: awaiting review, skip news

#120093 [3.13] gh-119819: Update logging configuration to support joinable multiproc… (GH-120090)
  Lib/logging/config.py
  Lib/test/test_logging.py
Labels: awaiting review, skip news

#119657 gh-119287: clarify doc on BaseExceptionGroup.derive and link to it from contextlib.suppress
  Doc/library/contextlib.rst
  Doc/library/exceptions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.11, needs backport to 3.12, needs backport to 3.13

#120106 [3.12] gh-119287: clarify doc on BaseExceptionGroup.derive and link to it from contextlib.suppress (GH-119657)
  Doc/library/contextlib.rst
  Doc/library/exceptions.rst
Labels: docs, awaiting merge, skip news

#120068 gh-120065: Increase `collect_in_thread` period to 5 ms.
  Lib/test/test_weakref.py
Labels: tests, awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#120110 [3.13] gh-120065: Increase `collect_in_thread` period to 5 ms. (GH-120068)
  Lib/test/test_weakref.py
Labels: tests, awaiting review, skip news

#120077 gh-119786: add links to code in exception handling doc
  InternalDocs/exception_handling.md
Labels: docs, awaiting core review, skip news

#119339 gh-115225: Raise error on unsupported ISO 8601 time strings
  Lib/test/datetimetester.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2024-05-21-19-10-30.gh-issue-115225.eRmfJH.rst
  Modules/_datetimemodule.c
Labels: awaiting merge
