Repository python/cpython, pull requests merged in 2024-08, with the labels that each got.

#122522 gh-116622: Don't expose `FICLONE` ioctl on Android
  Misc/NEWS.d/next/Library/2024-07-31-15-08-42.gh-issue-116622.aKxIQA.rst
  Modules/fcntlmodule.c
Labels: awaiting merge, needs backport to 3.13

#122502 Fix typos in docs, error messages and comments
  Doc/howto/isolating-extensions.rst
  Doc/library/threading.rst
  Doc/using/configure.rst
  Include/internal/pycore_freelist_state.h
  Lib/test/test_webbrowser.py
  Python/crossinterp.c
Labels: skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122538 [3.12] Move change detection to separate workflow in CI (GH-122336).
  .github/workflows/build.yml
  .github/workflows/reusable-change-detection.yml
Labels: skip issue, awaiting review, skip news

#122286 GH-122155: Track local variables between pops and pushes in cases generator
  Include/internal/pycore_opcode_metadata.h
  Lib/test/test_generated_cases.py
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/optimizer_generator.py
  Tools/cases_generator/parsing.py
  Tools/cases_generator/stack.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#122385 gh-122384: Mark strings from Download page for translation
  Doc/tools/templates/download.html
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122554 [3.12] gh-122384: Mark strings from Download page for translation (GH-122385)
  Doc/tools/templates/download.html
Labels: awaiting review, skip news

#122553 [3.13] gh-122384: Mark strings from Download page for translation (GH-122385)
  Doc/tools/templates/download.html
Labels: awaiting review, skip news

#122556 gh-122555: Remove removed functions from `Doc/data/refcounts.dat`
  Doc/data/refcounts.dat
  Lib/importlib/_bootstrap.py
Labels: awaiting merge, skip news

#122453 Replace PyObject_Del with PyObject_Free
  Doc/c-api/typeobj.rst
  Modules/_testcapi/gc.c
  Modules/_testcapimodule.c
  Objects/bytearrayobject.c
  Objects/bytesobject.c
  Objects/codeobject.c
  Objects/complexobject.c
  Objects/fileobject.c
  Objects/odictobject.c
  Objects/rangeobject.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Python/optimizer.c
Labels: skip issue, awaiting core review, skip news

#120793 GH-118095: Make BINARY_SUBSCR_GETITEM suitable for tier 2
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_optimizer.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer.c
  Python/optimizer_analysis.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, skip news

#122563 gh-122562: Remove ste_free and ste_child_free from symtable
  Include/internal/pycore_symtable.h
  Python/symtable.c
Labels: awaiting merge, skip news

#122520 Fixes typo in idlelib/idle_test/example_stub.pyi
  Lib/idlelib/idle_test/example_stub.pyi
Labels: skip issue, awaiting review, skip news, needs backport to 3.12

#122591 [3.12] Fixes typo in idlelib/idle_test/example_stub.pyi (GH-122520)
  Lib/idlelib/idle_test/example_stub.pyi
Labels: skip issue, awaiting review, skip news

#120605 gh-120083: Add IDLE Hovertip foreground color needed for recent macOS
  Lib/idlelib/News3.txt
  Lib/idlelib/tooltip.py
  Misc/NEWS.d/next/IDLE/2024-06-16-21-42-45.gh-issue-120083.nczuyv.rst
Labels: awaiting review, needs backport to 3.12

#122568 gh-122544: Change OS image in readthedocs.yml to ubuntu-24.04
  .readthedocs.yml
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122593 [3.13] gh-122544: Change OS image in readthedocs.yml to ubuntu-24.04 (GH-122568)
  .readthedocs.yml
Labels: awaiting merge, skip news

#122594 [3.12] gh-122544: Change OS image in readthedocs.yml to ubuntu-24.04 (GH-122568)
  .readthedocs.yml
Labels: awaiting merge, skip news

#122503 gh-122188: Remove _imp.pyc_magic_number
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_import/__init__.py
  Python/import.c
Labels: awaiting merge, skip news

#122597 Update PyObject_Del() documentation
  Doc/c-api/allocation.rst
  Doc/c-api/memory.rst
  Modules/_sre/sre.c
  Modules/_testcapi/heaptype.c
Labels: skip issue, awaiting core review, skip news

#122154 gh-121723: Relax constraints on queue objects for `logging.handlers.QueueHandler`.
  Doc/library/logging.config.rst
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-07-23-10-59-38.gh-issue-121723.iJEf7e.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#122583 [3.13] Add the Python 3.13 abidump, and enable the ABI check.
  .github/workflows/build.yml
  .gitignore
  Doc/data/python3.13.abi
Labels: skip issue, awaiting merge, skip news

#122604 [3.12] gh-121723: Relax constraints on queue objects for `logging.handlers.QueueHandler`. (GH-122154)
  Doc/library/logging.config.rst
  Lib/logging/config.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-07-23-10-59-38.gh-issue-121723.iJEf7e.rst
Labels: awaiting review

#122605 [3.12] Fix typos in docs (#122502)
  Doc/howto/isolating-extensions.rst
  Doc/library/threading.rst
Labels: docs, skip issue, awaiting core review, skip news

#122506 [3.11] gh-122133: Rework pure Python socketpair tests to avoid use of importlib.reload. (GH-122493)
  Lib/socket.py
  Lib/test/test_socket.py
Labels: awaiting review, skip news

#122507 [3.10] gh-122133: Rework pure Python socketpair tests to avoid use of importlib.reload. (GH-122493)
  Lib/socket.py
  Lib/test/test_socket.py
Labels: awaiting review, skip news

#122508 [3.9] gh-122133: Rework pure Python socketpair tests to avoid use of importlib.reload. (GH-122493)
  Lib/socket.py
  Lib/test/test_socket.py
Labels: awaiting review, skip news

#122317 gh-120974: Make asyncio `swap_current_task` safe in free-threaded build
  Include/internal/pycore_dict.h
  Modules/_asynciomodule.c
  Objects/dictobject.c
Labels: awaiting merge, skip news, needs backport to 3.13

#122481 gh-122334: Fix crash when importing ssl after re-initialization
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Library/2024-07-30-21-29-30.gh-issue-122334.LeoE1x.rst
  Python/getargs.c
Labels: awaiting merge

#122495 [3.12] gh-122334: Fix crash when importing ssl after re-initialization (GH-122481)
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Library/2024-07-30-21-29-30.gh-issue-122334.LeoE1x.rst
  Python/getargs.c
Labels: awaiting merge

#122612 [3.13] gh-120974: Make asyncio `swap_current_task` safe in free-threaded build (GH-122317)
  Include/internal/pycore_dict.h
  Modules/_asynciomodule.c
  Objects/dictobject.c
Labels: awaiting merge, skip news

#122614 [3.13] gh-122334: Fix crash when importing ssl after re-initialization (GH-122481)
  Lib/test/test_embed.py
  Misc/NEWS.d/next/Library/2024-07-30-21-29-30.gh-issue-122334.LeoE1x.rst
  Python/getargs.c
Labels: awaiting merge

#122446 gh-122445: populate only modified fields in __static_attributes__
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.13.rst
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2024-07-30-11-41-35.gh-issue-122445.Rq0bjS.rst
  Python/compile.c
Labels: awaiting merge, needs backport to 3.13

#122601 GH-117224: Move the body of a few large-ish micro-ops into helper functions
  Include/internal/pycore_ceval.h
  Python/bytecodes.c
  Python/ceval.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#122577 gh-122527: Fix a crash on deallocation of `PyStructSequence`
  Lib/test/test_structseq.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-08-01-19-13-58.gh-issue-122527.eztso6.rst
  Objects/structseq.c
Labels: awaiting merge

#122621 [3.13] gh-122445: populate only modified fields in __static_attributes__ (#122446)
  Doc/reference/datamodel.rst
  Doc/whatsnew/3.13.rst
  Lib/test/test_compile.py
  Misc/NEWS.d/next/Core and Builtins/2024-07-30-11-41-35.gh-issue-122445.Rq0bjS.rst
  Python/compile.c
Labels: awaiting merge

#122582 gh-122560: add test that comprehension loop var appears only in one scope of the symtable
  Lib/test/test_symtable.py
Labels: tests, awaiting merge, skip news

#122640 gh-122313: Clean up deep recursion guarding code in the compiler
  Python/ast.c
  Python/ast_opt.c
  Python/symtable.c
Labels: awaiting merge, skip news

#122627 Doc: Improve wording of ``os.path.commonpath()``
  Doc/library/os.path.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122280 gh-122613: Document PyLong_GetInfo() (part of Limited API)
  Doc/c-api/long.rst
Labels: docs, awaiting review, skip news

#122642 [3.12] Doc: Improve wording of ``os.path.commonpath()`` (GH-122627)
  Doc/library/os.path.rst
Labels: docs, skip issue, awaiting review, skip news

#109895 gh-109408: Stop running patchcheck in CI
  .azure-pipelines/posix-steps.yml
  .azure-pipelines/pr.yml
  Tools/patchcheck/patchcheck.py
Labels: awaiting core review, skip news

#122630 gh-122334: Fix test_embed failure when missing _ssl module
  Lib/test/test_embed.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122646 Doc: Grammar fix in `library/ssl.rst`, 'Verifying certificates'
  Doc/library/ssl.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122641 [3.13] Doc: Improve wording of ``os.path.commonpath()`` (GH-122627)
  Doc/library/os.path.rst
Labels: docs, skip issue, awaiting merge, skip news

#122650 [3.12] Doc: Grammar fix in ``library/ssl.rst``, 'Verifying certificates' (GH-122646)
  Doc/library/ssl.rst
Labels: docs, skip issue, awaiting review, skip news

#122649 [3.13] Doc: Grammar fix in ``library/ssl.rst``, 'Verifying certificates' (GH-122646)
  Doc/library/ssl.rst
Labels: docs, skip issue, awaiting review, skip news

#122643 GH-109408: Remove ``.azure-pipelines/pr.yml``
  .azure-pipelines/posix-deps-apt.sh
  .azure-pipelines/posix-steps.yml
  .azure-pipelines/pr.yml
Labels: awaiting merge, skip news

#122651 GH-121970: Fix ``gettext`` for audit events
  Doc/tools/extensions/audit_events.py
Labels: docs, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#122654 [3.12] GH-121970: Fix ``gettext`` for audit events (GH-122651)
  Doc/tools/extensions/audit_events.py
Labels: awaiting merge, skip news

#122624 gh-122623: Improve `c-api/bytearray.rst` with error handling info
  Doc/c-api/bytearray.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122659 [3.12] gh-122623: Improve `c-api/bytearray.rst` with error handling info (GH-122624)
  Doc/c-api/bytearray.rst
Labels: docs, awaiting merge, skip news

#121892 gh-121889: cmath.acosh(0+nanj) returns nan+pi/2j
  Lib/test/mathdata/cmath_testcases.txt
  Misc/NEWS.d/next/Library/2024-07-17-09-23-03.gh-issue-121889.6se9jS.rst
  Modules/cmathmodule.c
Labels: awaiting merge

#122638 gh-122637: fix tanh(±0+infj) and tanh(±0+nanj) to return ±0+nanj
  Lib/test/mathdata/cmath_testcases.txt
  Misc/NEWS.d/next/Library/2024-08-03-06-51-08.gh-issue-122637.gpas8J.rst
  Modules/cmathmodule.c
Labels: awaiting merge

#122658 [3.13] gh-122623: Improve `c-api/bytearray.rst` with error handling info (GH-122624)
  Doc/c-api/bytearray.rst
Labels: docs, awaiting merge, skip news

#122662 gh-122661: Remove GNU make-specific directive from Doc/Makefile
  Doc/Makefile
Labels: awaiting merge, skip news, build, needs backport to 3.12, needs backport to 3.13

#122669 [3.12] gh-122661: Remove GNU make-specific directive from Doc/Makefile (GH-122662)
  Doc/Makefile
Labels: awaiting merge, skip news

#122670 Add `3.13` and remove `3.7` in Azure Pipelines
  .azure-pipelines/ci.yml
Labels: skip issue, awaiting review, skip news, needs backport to 3.12, needs backport to 3.13

#122672 [3.12] Add `3.13` and remove `3.7` in Azure Pipelines (GH-122670)
  .azure-pipelines/ci.yml
Labels: skip issue, awaiting merge, skip news

#122671 [3.13] Add `3.13` and remove `3.7` in Azure Pipelines (GH-122670)
  .azure-pipelines/ci.yml
Labels: skip issue, awaiting merge, skip news

#122574 gh-122573: Require Python 3.10 or newer for Windows builds
  Misc/NEWS.d/next/Windows/2024-08-01-10-55-15.gh-issue-122573.4-UCFY.rst
  PCbuild/find_python.bat
Labels: type-bug, OS-windows, awaiting merge, build, needs backport to 3.12, needs backport to 3.13

#122663 gh-121367: [doc] BUILD_TUPLE arg can be 0
  Doc/library/dis.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#122684 [3.12] gh-121367: [doc] BUILD_TUPLE arg can be 0 (GH-122663)
  Doc/library/dis.rst
Labels: docs, awaiting merge, skip news

#122683 [3.13] gh-121367: [doc] BUILD_TUPLE arg can be 0 (GH-122663)
  Doc/library/dis.rst
Labels: docs, awaiting merge, skip news

#122460 gh-122459: Optimize pickling by name objects without __module__
  Lib/pickle.py
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2024-07-30-15-57-07.gh-issue-122459.AYIoeN.rst
  Modules/_pickle.c
Labels: awaiting core review

#122620 GH-122616: Simplify LOAD_ATTR_WITH_HINT and STORE_ATTR_WITH_HINT
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#122644 [3.12] gh-122613: Document PyLong_GetInfo() (part of Limited API) (GH-122280)
  Doc/c-api/long.rst
Labels: docs, awaiting merge, skip news

#120690 GH-118943: Fix another race condition when generating jit_stencils.h
  Misc/NEWS.d/next/Build/2024-06-18-15-28-25.gh-issue-118943.aie7nn.rst
  Tools/jit/_targets.py
Labels: awaiting merge, build, needs backport to 3.13, topic-JIT

#122687 gh-122686: pin attrs package (for hypothesis workflow)
  Tools/requirements-hypothesis.txt
Labels: awaiting merge, skip news

#122698 gh-116622: Android logging fixes
  Lib/_android_support.py
  Lib/test/test_android.py
  Misc/NEWS.d/next/Core and Builtins/2024-08-05-19-04-06.gh-issue-116622.3LWUzE.rst
Labels: awaiting merge, needs backport to 3.13

#122705 gh-122704: Fix reference leak in `Modules/_pickle.c`
  Modules/_pickle.c
Labels: awaiting merge, skip news

#122596 gh-122595: Add more error checks in the compiler
  Python/compile.c
  Python/symtable.c
Labels: awaiting merge, skip news

#122699 Fix syntax in generate_re_casefix.py
  Lib/re/_casefix.py
  Tools/build/generate_re_casefix.py
Labels: skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122721 [3.13] Fix syntax in generate_re_casefix.py (GH-122699)
  Lib/re/_casefix.py
  Tools/build/generate_re_casefix.py
Labels: skip issue, awaiting review, skip news

#122693 GH-120024: Refactor code a bit so that escaping calls can be wrapped in spill code in code generator
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#122694 gh-122581: Avoid data races when collecting parser statistics
  Include/internal/pycore_parser.h
  Parser/pegen.c
Labels: awaiting merge, skip news, needs backport to 3.13

#122730 GH-120024: Refactor code generators to uses classes for emitting code.
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/optimizer_generator.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#122729 gh-122686: bump hypothesis from 6.104.2 to 6.108.10 in Tools
  Tools/requirements-hypothesis.txt
Labels: awaiting merge, skip news

#122682 gh-122681: merge m_atan2() and c_atan2() helper functions
  Modules/_math.h
  Modules/cmathmodule.c
  Modules/mathmodule.c
Labels: awaiting merge, skip news

#122059 gh-122058: `Lib/inspect`: Update docstrings for `isfunction`, `isgenerator`, `isframe`, `iscode`.
  Doc/library/inspect.rst
  Lib/inspect.py
  Objects/frameobject.c
Labels: awaiting merge, skip news

#122734 GH-120024: Move three more escaping calls out of conditional statements
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#118594 [3.12] gh-83505: Add markdown mimetype mapping (GH-17995)
  Lib/mimetypes.py
  Misc/NEWS.d/next/Library/2020-01-14-09-46-51.bpo-39324.qUcDrM.rst
Labels: awaiting review

#120107 gh-120104: IDLE: Fix padding in config and search dialogs
  Lib/idlelib/configdialog.py
  Lib/idlelib/searchbase.py
  Misc/NEWS.d/next/IDLE/2024-06-05-14-54-24.gh-issue-120104.j_thj4.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#122674 [3.13] gh-122573: Require Python 3.10 or newer for Windows builds (GH-122574)
  Misc/NEWS.d/next/Windows/2024-08-01-10-55-15.gh-issue-122573.4-UCFY.rst
  PCbuild/find_python.bat
Labels: type-bug, awaiting review

#122677 [3.12] gh-122573: Require Python 3.10 or newer for Windows builds (GH-122574)
  Misc/NEWS.d/next/Windows/2024-08-01-10-55-15.gh-issue-122573.4-UCFY.rst
  PCbuild/find_python.bat
Labels: type-bug, awaiting core review

#122484 [3.13] gh-121650: Encode newlines in headers, and verify headers are sound (GH-122233)
  Doc/library/email.errors.rst
  Doc/library/email.policy.rst
  Doc/whatsnew/3.13.rst
  Lib/email/_header_value_parser.py
  Lib/email/_policybase.py
  Lib/email/errors.py
  Lib/email/generator.py
  Lib/test/test_email/test_generator.py
  Lib/test/test_email/test_policy.py
  Misc/NEWS.d/next/Library/2024-07-27-16-10-41.gh-issue-121650.nf6oc9.rst
Labels: awaiting review

#122599 [3.12] gh-121650: Encode newlines in headers, and verify headers are sound (GH-122233)
  Doc/library/email.errors.rst
  Doc/library/email.policy.rst
  Doc/whatsnew/3.12.rst
  Lib/email/_header_value_parser.py
  Lib/email/_policybase.py
  Lib/email/errors.py
  Lib/email/generator.py
  Lib/test/test_email/test_generator.py
  Lib/test/test_email/test_policy.py
  Misc/NEWS.d/next/Library/2024-07-27-16-10-41.gh-issue-121650.nf6oc9.rst
Labels: awaiting core review, release-blocker

#122741 [3.12] gh-120104: IDLE: Fix padding in config and search dialogs (GH-120107)
  Lib/idlelib/configdialog.py
  Lib/idlelib/searchbase.py
  Misc/NEWS.d/next/IDLE/2024-06-05-14-54-24.gh-issue-120104.j_thj4.rst
Labels: awaiting review

#117274 [3.12] gh-117270: Add missed change to COMPARE_OP from 3.12 to dis documentation (GH-117272)
  Doc/library/dis.rst
Labels: docs, awaiting review, skip news

#122211 gh-112301: Add macOS warning tracking tooling
  .github/workflows/reusable-macos.yml
  .github/workflows/reusable-ubuntu.yml
  Misc/NEWS.d/next/Security/2024-07-24-05-18-25.gh-issue-112301.lfINgZ.rst
  Tools/build/.warningignore_macos
  Tools/build/check_warnings.py
Labels: awaiting merge

#122732 Fix duplicated words 'begins with a'
  Lib/pathlib/_abc.py
Labels: skip issue, awaiting core review, skip news, topic-pathlib

#122737 gh-121103: Update site module docs for free-threaded installs
  Doc/library/site.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13

#122418 gh-122417: Implement per-thread heap type refcounts
  Include/cpython/object.h
  Include/internal/pycore_gc.h
  Include/internal/pycore_interp.h
  Include/internal/pycore_object.h
  Include/internal/pycore_tstate.h
  Include/internal/pycore_typeid.h
  Lib/test/test_sys.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core_and_Builtins/2024-07-29-19-20-25.gh-issue-122417.NVgs0a.rst
  Objects/object.c
  Objects/typeobject.c
  PCbuild/_freeze_module.vcxproj
  PCbuild/_freeze_module.vcxproj.filters
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/gc_free_threading.c
  Python/pystate.c
  Python/typeid.c
Labels: awaiting merge, topic-free-threading

#122747 [3.12] gh-122744: Bump bundled pip to 24.2
  Lib/ensurepip/__init__.py
  Lib/ensurepip/_bundled/pip-24.0-py3-none-any.whl
  Lib/ensurepip/_bundled/pip-24.2-py3-none-any.whl
  Misc/NEWS.d/next/Library/2024-08-06-18-07-19.gh-issue-122744.kCzNDI.rst
Labels: awaiting merge, topic-ensurepip

#122750 [3.13] gh-121103: Update site module docs for free-threaded installs (GH-122737)
  Doc/library/site.rst
Labels: docs, awaiting review, skip news

#122648 [3.12] gh-122334: Fix test_embed failure when missing _ssl module (GH-122630)
  Lib/test/test_embed.py
Labels: tests, awaiting review, skip news

#122647 [3.13] gh-122334: Fix test_embed failure when missing _ssl module (GH-122630)
  Lib/test/test_embed.py
Labels: tests, awaiting review, skip news

#122735 gh-122728: Fix SystemError in PyEval_GetLocals()
  Lib/test/test_capi/test_misc.py
  Misc/NEWS.d/next/C_API/2024-08-06-14-23-11.gh-issue-122728.l-fQ-v.rst
  Modules/_testcapimodule.c
  Python/ceval.c
Labels: awaiting merge, needs backport to 3.13

#122757 [3.13] gh-122728: Fix SystemError in PyEval_GetLocals() (GH-122735)
  Lib/test/test_capi/test_misc.py
  Misc/NEWS.d/next/C_API/2024-08-06-14-23-11.gh-issue-122728.l-fQ-v.rst
  Modules/_testcapimodule.c
  Python/ceval.c
Labels: awaiting merge

#122572 gh-122571: Remove duplicated definitions of `PY_BUILTIN_HASHLIB_HASHES` in `configure.ac`
  configure
  configure.ac
Labels: awaiting merge, skip news, needs backport to 3.13

#122368 GH-73991: Rework `pathlib.Path.rmtree()` into `delete()`
  Doc/library/pathlib.rst
  Doc/whatsnew/3.14.rst
  Lib/pathlib/_abc.py
  Lib/pathlib/_local.py
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_pathlib/test_pathlib_abc.py
  Misc/NEWS.d/next/Library/2024-05-15-01-21-44.gh-issue-73991.bNDqQN.rst
Labels: awaiting merge, topic-pathlib

#122720 Fix typos in comments and docstring
  Lib/enum.py
  Lib/mimetypes.py
  Lib/pdb.py
  Lib/shutil.py
  Lib/test/datetimetester.py
  Lib/test/test__interpreters.py
  Lib/test/test_array.py
  Lib/typing.py
  Lib/uuid.py
Labels: skip issue, awaiting review, skip news

#91740 gh-79846: Make `ssl.create_default_context()` ignore invalid certificates
  Lib/ssl.py
  Misc/NEWS.d/next/Windows/2022-04-20-18-32-30.gh-issue-79846.Vggv3f.rst
Labels: awaiting review

#122774 [3.12] Workaround 3.12.5 bundled pip 24.2 issue on macOS 10.9 to 10.12.
  Mac/BuildScript/resources/ReadMe.rtf
  Mac/BuildScript/resources/Welcome.rtf
  Mac/BuildScript/resources/install_certificates.command
Labels: OS-mac, skip issue, awaiting core review, skip news, topic-installation

#122733 [3.13] gh-122581: Avoid data races when collecting parser statistics (GH-122694)
  Include/internal/pycore_parser.h
  Parser/pegen.c
Labels: awaiting merge, skip news

#121159 gh-121151: Fix wrapping of long usage text of arguments inside a mutually exclusive groups in argparse
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2024-06-29-15-23-26.gh-issue-121151.HeLEvq.rst
Labels: awaiting core review

#122318 gh-117139: Fix an incorrect borrow in bytecodes.c
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#122512 gh-122511: improve documentation for mutable/immutable types behaviours
  Doc/reference/datamodel.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122779 [3.12] gh-122511: Improve documentation for object identity of mutable/immutable types (GH-122512)
  Doc/reference/datamodel.rst
Labels: docs, awaiting review, skip news

#122760 gh-122759: Remove `assert` from `RERAISE` error handling
  Python/bytecodes.c
  Python/generated_cases.c.h
Labels: awaiting merge, skip news

#122590 docs: Include -P and -R in cmdline.rst usage (trivial)
  Doc/using/cmdline.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#122047 gh-100256: Skip inaccessible registry keys in the WinAPI mimetype implementation
  Misc/ACKS
  Misc/NEWS.d/next/Windows/2024-07-19-21-50-54.gh-issue-100256.GDrKba.rst
  Modules/_winapi.c
Labels: awaiting core review, needs backport to 3.12, needs backport to 3.13

#122784 [3.12] Doc: cmdline.rst: Include -P and -R in usage (GH-122590)
  Doc/using/cmdline.rst
Labels: docs, skip issue, awaiting merge, skip news

#121072 docs: Change `remove` to `removes` for consistency
  Doc/library/stdtypes.rst
Labels: docs, skip issue, awaiting merge, skip news

#122778 [3.13] gh-122511: Improve documentation for object identity of mutable/immutable types (GH-122512)
  Doc/reference/datamodel.rst
Labels: docs, awaiting merge, skip news

#122791 [3.12] Docs: Change `remove` to `removes` for consistency (GH-121072)
  Doc/library/stdtypes.rst
Labels: docs, skip issue, awaiting merge, skip news

#122790 [3.13] Docs: Change `remove` to `removes` for consistency (GH-121072)
  Doc/library/stdtypes.rst
Labels: docs, skip issue, awaiting merge, skip news

#122748 gh-118926: Spill deferred references to stack in cases generator
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/lexer.py
  Tools/cases_generator/stack.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news, topic-free-threading

#122787 [3.12] gh-100256: Skip inaccessible registry keys in the WinAPI mimetype implementation (GH-122047)
  Misc/ACKS
  Misc/NEWS.d/next/Windows/2024-07-19-21-50-54.gh-issue-100256.GDrKba.rst
  Modules/_winapi.c
Labels: awaiting review

#122799 gh-122798: Make tests for warnings in the re module more strict
  Lib/test/test_re.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#122725 gh-118761: Improve import time of `pprint`
  Lib/pprint.py
  Misc/NEWS.d/next/Library/2024-08-06-10-36-55.gh-issue-118761.q_x_1A.rst
Labels: awaiting merge

#122528 gh-122478: Remove internal frames from tracebacks in REPL
  Lib/code.py
  Lib/test/test_code_module.py
  Misc/NEWS.d/next/Library/2024-07-31-20-43-21.gh-issue-122478.sCU2Le.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#122664 gh-118814: Fix the TypeVar constructor when name is passed by keyword
  Lib/test/test_clinic.py
  Lib/test/test_typing.py
  Misc/NEWS.d/next/Library/2024-08-04-14-07-18.gh-issue-118814.uiyks1.rst
  Modules/_testclinic.c
  Modules/clinic/_testclinic.c.h
  Python/getargs.c
Labels: type-bug, awaiting core review, needs backport to 3.12, needs backport to 3.13

#122331 gh-105201: Add PyIter_NextItem()
  Doc/c-api/iter.rst
  Doc/data/refcounts.dat
  Doc/data/stable_abi.dat
  Doc/whatsnew/3.14.rst
  Include/abstract.h
  Lib/test/test_capi/test_abstract.py
  Lib/test/test_stable_abi_ctypes.py
  Misc/NEWS.d/next/C_API/2024-07-27-00-28-35.gh-issue-105201.0-xUWq.rst
  Misc/stable_abi.toml
  Modules/_testcapi/abstract.c
  Objects/abstract.c
  PC/python3dll.c
Labels: awaiting merge

#122251 gh-122247: Move instruction instrumentation sanity check after tracing check
  Lib/test/test_monitoring.py
  Python/instrumentation.c
Labels: awaiting merge, skip news, needs backport to 3.13

#122800 gh-120782: Update datetime test for static type immutability
  Lib/test/datetimetester.py
Labels: awaiting merge, skip news

#122788 gh-116263: Do not rollover empty files in RotatingFileHandler
  Lib/logging/handlers.py
  Lib/test/test_logging.py
  Misc/NEWS.d/next/Library/2024-08-07-17-41-16.gh-issue-116263.EcXir0.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#122806 [3.13] gh-118814: Fix the TypeVar constructor when name is passed by keyword (GH-122664)
  Lib/test/test_clinic.py
  Lib/test/test_typing.py
  Misc/NEWS.d/next/Library/2024-08-04-14-07-18.gh-issue-118814.uiyks1.rst
  Modules/_testclinic.c
  Modules/clinic/_testclinic.c.h
  Python/getargs.c
Labels: type-bug, awaiting merge

#122807 [3.12] gh-118814: Fix the TypeVar constructor when name is passed by keyword (GH-122664)
  Lib/test/test_clinic.py
  Lib/test/test_typing.py
  Misc/NEWS.d/next/Library/2024-08-04-14-07-18.gh-issue-118814.uiyks1.rst
  Modules/_testclinic.c
  Modules/clinic/_testclinic.c.h
  Python/getargs.c
Labels: type-bug, awaiting core review

#122514 [3.13] gh-87320: In the code module, handle exceptions raised in sys.excepthook (GH-122456)
  Lib/code.py
  Lib/test/test_code_module.py
  Lib/test/test_pyrepl/test_pyrepl.py
  Misc/NEWS.d/next/Library/2024-07-30-14-46-16.gh-issue-87320.-Yk1wb.rst
Labels: awaiting merge

#122227 gh-122255: Add black box tests in test_warnings
  Lib/test/test_warnings/__init__.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#122809 InternalDocs: Fix typo in link to instruction_sequence.c inside compiler docs
  InternalDocs/compiler.md
Labels: skip issue, awaiting merge, skip news

#122776 gh-122744: test_venv: ignore pip's complaint about missing ssl
  Lib/test/test_venv.py
Labels: tests, awaiting merge, skip news

#122780 GH-120024: Tidy up case generator code a bit.
  Python/generated_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/opcode_metadata_generator.py
  Tools/cases_generator/optimizer_generator.py
  Tools/cases_generator/parsing.py
  Tools/cases_generator/py_metadata_generator.py
  Tools/cases_generator/stack.py
  Tools/cases_generator/target_generator.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#122789 gh-111495: Add more tests on PyEval C APIs
  Lib/test/test_capi/test_eval.py
  Lib/test/test_capi/test_misc.py
  Modules/Setup.stdlib.in
  Modules/_testcapimodule.c
  Modules/_testlimitedcapi.c
  Modules/_testlimitedcapi/eval.c
  Modules/_testlimitedcapi/parts.h
  PCbuild/_testlimitedcapi.vcxproj
  PCbuild/_testlimitedcapi.vcxproj.filters
Labels: awaiting merge, skip news

#122825 gh-122562: fix dump_symtable for ste_free and ste_child_free removal
  Python/symtable.c
Labels: awaiting merge, skip news

#122703 gh-122697: Fix free-threading memory leaks at shutdown
  Misc/NEWS.d/next/Core_and_Builtins/2024-08-05-19-28-12.gh-issue-122697.17MvYl.rst
  Objects/obmalloc.c
  Python/gc_free_threading.c
  Python/pylifecycle.c
  Python/pystate.c
Labels: awaiting merge, topic-free-threading

#122836 gh-122835: Fix module name in ``test_typing``
  Lib/test/test_typing.py
Labels: tests, awaiting merge, skip news

#122758 gh-112301: Update disable safety and enable slow safety configure options documentation
  Doc/using/configure.rst
Labels: docs, awaiting merge, skip news

#122602 gh-118943: Remove 'regen-jit' from the 'regen-all' make target
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2024-08-02-12-59-15.gh-issue-118943.vZQtET.rst
Labels: awaiting merge, build, needs backport to 3.13, topic-JIT

#122709 [3.13] GH-118943: Handle races when moving jit_stencils.h (GH-120690)
  Misc/NEWS.d/next/Build/2024-06-18-15-28-25.gh-issue-118943.aie7nn.rst
  Tools/jit/_targets.py
Labels: awaiting merge, topic-JIT

#122840 [3.13] GH-118943: Remove regen-jit from the regen-all make target (GH-122602)
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2024-08-02-12-59-15.gh-issue-118943.vZQtET.rst
Labels: awaiting merge, topic-JIT

#122764 gh-116622: Rename build variable MODULE_LDFLAGS back to LIBPYTHON
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2024-08-07-00-20-18.gh-issue-116622.U9cxHM.rst
  Misc/python-config.sh.in
  Misc/python.pc.in
  Modules/makesetup
  configure
  configure.ac
Labels: awaiting merge, needs backport to 3.13

#122823 [3.13] gh-122744: test_venv: ignore pip's complaint about missing ssl (GH-122776)
  Lib/test/test_venv.py
Labels: tests, awaiting review, skip news

#122822 [3.12] gh-122744: test_venv: ignore pip's complaint about missing ssl (GH-122776)
  Lib/test/test_venv.py
Labels: tests, awaiting review, skip news

#122716 gh-121268: remove workarounds for non-IEEE 754 systems in cmath
  Misc/NEWS.d/next/Library/2024-07-17-12-55-22.gh-issue-121268.41RmjR.rst
  Modules/cmathmodule.c
Labels: awaiting merge

#122689 gh-122688: Fix support of var-positional parameter in Argument Clinic
  Lib/test/clinic.test.c
  Lib/test/test_clinic.py
  Modules/_testclinic.c
  Modules/clinic/_testclinic.c.h
  Objects/setobject.c
  Tools/clinic/libclinic/dsl_parser.py
  Tools/clinic/libclinic/parse_args.py
Labels: awaiting merge, skip news, topic-argument-clinic

#122851 gh-111495: Fix refleaks in test_capi.test_eval tests
  Modules/_testlimitedcapi/eval.c
Labels: awaiting merge, skip news

#122668 [3.13] gh-122661: Remove GNU make-specific directive from Doc/Makefile (GH-122662)
  Doc/Makefile
Labels: awaiting merge, skip news

#122775 gh-105376: Restore deprecated logging warn() method
  Doc/deprecations/pending-removal-in-future.rst
  Doc/library/logging.rst
  Doc/whatsnew/3.13.rst
  Lib/logging/__init__.py
  Misc/NEWS.d/next/Library/2024-08-07-14-12-19.gh-issue-105376.QbGPdE.rst
Labels: awaiting merge, needs backport to 3.13

#118003 [3.11] gh-114539: Clarify implicit launching of shells by subprocess (GH-117996)
  Doc/library/subprocess.rst
Labels: docs, type-security, awaiting merge, skip news
