Repository python/cpython, pull requests merged in 2025-02, with the labels that each got.

#129426 gh-126835: Move optimization of constant sequence creation from codegen to CFG
  Lib/test/test_dis.py
  Python/codegen.c
  Python/flowgraph.c
Labels: awaiting merge, skip news

#129544 gh-93649: Move _testcapi tests to specific files
  Lib/test/test_capi/test_misc.py
  Lib/test/test_capi/test_object.py
  Modules/_testcapi/dict.c
  Modules/_testcapi/float.c
  Modules/_testcapi/list.c
  Modules/_testcapi/mem.c
  Modules/_testcapi/object.c
  Modules/_testcapi/set.c
  Modules/_testcapimodule.c
Labels: awaiting core review, skip news

#129535 gh-126022: Replace TeX quotation marks with ``"`` in Doc/license.rst
  Doc/license.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129551 [3.13] gh-126022: Replace TeX quotation marks with ``"`` in Doc/license.rst (GH-129535)
  Doc/license.rst
Labels: docs, awaiting merge, skip news

#129554 [3.12] gh-126022: Replace TeX quotation marks with ``"`` in Doc/license.rst (GH-129535)
  Doc/license.rst
Labels: docs, awaiting core review, skip news

#129561 gh-119461: Restore the testSocket VSOCK skipUnless removed by PR #119465
  Lib/test/test_socket.py
Labels: tests, awaiting core review, skip news, needs backport to 3.11, needs backport to 3.12, needs backport to 3.13

#129565 [3.12] gh-119461: Restore the testSocket VSOCK skipUnless removed by PR GH-119465 (GH-129561)
  Lib/test/test_socket.py
Labels: tests, awaiting review, skip news

#129564 [3.13] gh-119461: Restore the testSocket VSOCK skipUnless removed by PR GH-119465 (GH-129561)
  Lib/test/test_socket.py
Labels: tests, awaiting review, skip news

#129526 [3.13] gh-105704: Disallow square brackets (`[` and `]`) in domain names for parsed URLs (GH-129418)
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2025-01-28-14-08-03.gh-issue-105704.EnhHxu.rst
Labels: type-security, awaiting core review, release-blocker

#129527 [3.12] gh-105704: Disallow square brackets (`[` and `]`) in domain names for parsed URLs (GH-129418)
  Lib/test/test_urlparse.py
  Lib/urllib/parse.py
  Misc/NEWS.d/next/Security/2025-01-28-14-08-03.gh-issue-105704.EnhHxu.rst
Labels: type-security, awaiting core review

#129558 gh-129539: Reorganize posixmodule.c header
  Modules/posixmodule.c
Labels: awaiting core review, skip news

#129580 gh-104400: Remove ``fintl.gettext`` from pygettext
  Tools/i18n/pygettext.py
Labels: awaiting core review, skip news

#128037 gh-115514: Fix incomplete writes after close in asyncio._SelectorSocketTransport
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Lib/test/test_asyncio/test_ssl.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2024-12-17-16-48-02.gh-issue-115514.1yOJ7T.rst
Labels: topic-asyncio, awaiting merge, needs backport to 3.12, needs backport to 3.13

#129582 [3.12] gh-115514: Fix incomplete writes after close while using ssl in asyncio(GH-128037)
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Lib/test/test_asyncio/test_ssl.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2024-12-17-16-48-02.gh-issue-115514.1yOJ7T.rst
Labels: topic-asyncio, awaiting merge

#129549 gh-126609: Allow translating the ``availability`` directive
  Doc/tools/extensions/availability.py
  Doc/tools/templates/dummy.html
Labels: docs, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#129581 [3.13] gh-115514: Fix incomplete writes after close while using ssl in asyncio(GH-128037)
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Lib/test/test_asyncio/test_ssl.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2024-12-17-16-48-02.gh-issue-115514.1yOJ7T.rst
Labels: topic-asyncio, awaiting merge

#129577 GH-121970: Extract ``misc_news`` into a new extension
  Doc/conf.py
  Doc/make.bat
  Doc/tools/extensions/misc_news.py
  Doc/tools/extensions/pyspecific.py
  Doc/whatsnew/changelog.rst
  Misc/NEWS.d/3.5.3rc1.rst
  Misc/NEWS.d/3.6.0a4.rst
  Misc/NEWS.d/3.6.0b1.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129585 [3.12] gh-126609: Allow translating the ``availability`` directive (GH-129549)
  Doc/tools/extensions/availability.py
  Doc/tools/templates/dummy.html
Labels: awaiting merge, skip news

#129586 [3.13] GH-121970: Extract ``misc_news`` into a new extension (GH-129577)
  Doc/conf.py
  Doc/make.bat
  Doc/tools/extensions/misc_news.py
  Doc/tools/extensions/pyspecific.py
  Doc/whatsnew/changelog.rst
  Misc/NEWS.d/3.5.3rc1.rst
  Misc/NEWS.d/3.6.0a4.rst
  Misc/NEWS.d/3.6.0b1.rst
Labels: awaiting core review, skip news

#129587 [3.12] GH-121970: Extract ``misc_news`` into a new extension (GH-129577)
  Doc/conf.py
  Doc/make.bat
  Doc/tools/extensions/misc_news.py
  Doc/tools/extensions/pyspecific.py
  Doc/whatsnew/changelog.rst
  Misc/NEWS.d/3.5.3rc1.rst
  Misc/NEWS.d/3.6.0a4.rst
  Misc/NEWS.d/3.6.0b1.rst
Labels: awaiting core review, skip news

#129590 [3.13] gh-129539: Include sysexits.h before checking EX_OK
  Misc/NEWS.d/next/Build/2025-02-02-09-11-45.gh-issue-129539.SYXXCg.rst
  Modules/posixmodule.c
Labels: awaiting review

#129593 [3.13] gh-127096: Do not recreate unnamed section on every read in ConfigParser (GH-127228)
  Lib/configparser.py
  Lib/test/test_configparser.py
  Misc/NEWS.d/next/Library/2024-11-24-22-06-42.gh-issue-127096.R7LLpQ.rst
Labels: awaiting core review

#129398 gh-91417: Remove PySequence_Fast() from the limited C API
  Doc/data/stable_abi.dat
  Doc/whatsnew/3.14.rst
  Include/abstract.h
  Include/cpython/abstract.h
  Misc/NEWS.d/next/C_API/2025-01-28-13-21-17.gh-issue-91417.AfiR0t.rst
  Misc/stable_abi.toml
Labels: awaiting merge

#129601 [3.12] gh-127975: Avoid reusing quote types in ast.unparse if not needed (GH-127980)
  Lib/ast.py
  Lib/test/test_unparse.py
  Misc/NEWS.d/next/Library/2024-12-20-08-44-12.gh-issue-127975.8HJwu9.rst
Labels: awaiting merge

#129599 gh-105875: amend sqlite3 docstring wrt. SQLite requirement
  Lib/sqlite3/__init__.py
Labels: awaiting core review, skip news, needs backport to 3.13

#128873 gh-128872: Remove unused `consts` argument
  Objects/codeobject.c
  Python/specialize.c
Labels: awaiting merge, skip news

#128941 gh-128842: collect JIT memory stats via pystats
  Include/cpython/pystats.h
  Include/internal/pycore_code.h
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-17-13-16-14.gh-issue-128842.OMs5X6.rst
  Python/jit.c
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: awaiting merge, topic-JIT

#129232 gh-129231: group executable JIT code in memory
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-24-11-37-22.gh-issue-129231.ZsAP9v.rst
  Python/jit.c
Labels: awaiting merge, topic-JIT

#129602 [3.13] gh-105875: amend sqlite3 docstring wrt. SQLite requirement (GH-129599)
  Lib/sqlite3/__init__.py
Labels: awaiting review, skip news

#129600 [3.13] gh-127975: Avoid reusing quote types in ast.unparse if not needed (GH-127980)
  Lib/ast.py
  Lib/test/test_unparse.py
  Misc/NEWS.d/next/Library/2024-12-20-08-44-12.gh-issue-127975.8HJwu9.rst
Labels: awaiting merge

#129584 [3.13] gh-126609: Allow translating the ``availability`` directive (GH-129549)
  Doc/tools/extensions/availability.py
  Doc/tools/templates/dummy.html
Labels: awaiting merge, skip news

#93152 gh-81340: Use `copy_file_range` in `shutil.copyfile` copy functions
  Doc/library/shutil.rst
  Lib/shutil.py
  Lib/test/test_shutil.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2022-05-23-21-23-29.gh-issue-81340.D11RkZ.rst
Labels: awaiting merge

#129361 gh-129342: Explain how to replace Py_GetProgramName() in C
  Doc/c-api/init.rst
  Doc/deprecations/c-api-pending-removal-in-3.15.rst
Labels: docs, awaiting merge, skip news

#129410 gh-129407: Clarify that a `SystemError` isn't always CPython's fault
  Doc/library/exceptions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129610 [3.13] gh-129407: Clarify that a `SystemError` isn't always CPython's fault (GH-129410)
  Doc/library/exceptions.rst
Labels: docs, awaiting review, skip news

#129611 [3.12] gh-129407: Clarify that a `SystemError` isn't always CPython's fault (GH-129410)
  Doc/library/exceptions.rst
Labels: docs, awaiting review, skip news

#129433 gh-101944: Clarify PyModule_AddObjectRef() documentation
  Doc/c-api/module.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#129609 [3.12] gh-129539: Include sysexits.h before checking EX_OK (#129590)
  Misc/NEWS.d/next/Build/2025-02-02-09-11-45.gh-issue-129539.SYXXCg.rst
  Modules/posixmodule.c
Labels: awaiting core review

#129612 [3.13] gh-101944: Clarify PyModule_AddObjectRef() documentation (GH-129433)
  Doc/c-api/module.rst
Labels: docs, awaiting review, skip news

#129613 [3.12] gh-101944: Clarify PyModule_AddObjectRef() documentation (GH-129433)
  Doc/c-api/module.rst
Labels: docs, awaiting review, skip news

#129404 GH-128682: Make `PyStackRef_CLOSE` escaping.
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_metadata.h
  Lib/test/test_generated_cases.py
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer.c
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#129608 GH-128563: Generate `opcode = ...` in instructions that need `opcode`
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Python/optimizer_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/tier1_generator.py
Labels: awaiting merge, skip news

#129546 gh-111637: Clarify MIME type recognition behavior in mimetypes documentation
  Doc/library/mimetypes.rst
Labels: docs, awaiting review, skip news

#129443 [3.12] gh-129345: null check for indent syslogmodule (GH-129348)
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-28-06-23-59.gh-issue-129345.uOjkML.rst
  Modules/syslogmodule.c
Labels: awaiting review

#128790 [3.12] gh-128078: Use `PyErr_SetRaisedException` in `_PyGen_SetStopIterationValue` (GH-128287)
  Lib/test/test_asyncgen.py
  Objects/genobject.c
Labels: awaiting review, skip news

#128773 [3.12] gh-128696: Add arm64 to the get_platform return val description (GH-128701)
  Doc/library/sysconfig.rst
  Lib/sysconfig.py
Labels: awaiting review, skip news

#128655 [3.12] gh-97850: Remove the mention of removal from `ResourceReader` docs (GH-128602)
  Doc/library/importlib.resources.abc.rst
Labels: docs, awaiting core review, skip news

#128789 [3.13] gh-128078: Use `PyErr_SetRaisedException` in `_PyGen_SetStopIterationValue` (GH-128287)
  Lib/test/test_asyncgen.py
  Objects/genobject.c
Labels: awaiting review, skip news

#129442 [3.13] gh-129345: null check for indent syslogmodule (GH-129348)
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-28-06-23-59.gh-issue-129345.uOjkML.rst
  Modules/syslogmodule.c
Labels: awaiting review

#128774 [3.13] gh-128696: Add arm64 to the get_platform return val description (GH-128701)
  Doc/library/sysconfig.rst
  Lib/sysconfig/__init__.py
Labels: awaiting review, skip news

#129517 [3.13] gh-129502: Fix handling errors in ctypes callbacks (GH-129504)
  Misc/NEWS.d/next/Library/2025-01-31-11-14-05.gh-issue-129502.j_ArNo.rst
  Modules/_ctypes/callbacks.c
Labels: awaiting review

#129568 gh-126835: Move constant subscript folding to CFG
  Include/internal/pycore_long.h
  Lib/test/test_ast/test_ast.py
  Lib/test/test_peepholer.py
  Python/ast_opt.c
  Python/codegen.c
  Python/flowgraph.c
Labels: awaiting merge, skip news

#129634 gh-126835: Fix `optimize_if_const_subscr` refleaks
  Python/flowgraph.c
Labels: awaiting merge, skip news

#129618 GH-128682: Spill the stack pointer in labels, as well as instructions
  Include/internal/pycore_optimizer.h
  Lib/test/test_generated_cases.py
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer.c
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/lexer.py
  Tools/cases_generator/optimizer_generator.py
  Tools/cases_generator/parser.py
  Tools/cases_generator/parsing.py
  Tools/cases_generator/stack.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#129645 GH-128682: Mark two more macros as escaping.
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Tools/cases_generator/analyzer.py
Labels: awaiting merge, skip news

#129639 [3.12] gh-129502: Fix handling errors in ctypes callbacks (GH-129504)
  Misc/NEWS.d/next/Library/2025-01-31-11-14-05.gh-issue-129502.j_ArNo.rst
  Modules/_ctypes/callbacks.c
Labels: awaiting core review

#129507 Use roles :data: and :const: for referencing module variables
  Doc/howto/free-threading-python.rst
  Doc/library/datetime.rst
  Doc/library/decimal.rst
  Doc/library/filecmp.rst
  Doc/library/importlib.metadata.rst
  Doc/library/importlib.rst
  Doc/library/logging.rst
  Doc/library/plistlib.rst
  Doc/library/select.rst
  Doc/library/site.rst
  Doc/library/ssl.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.13.rst
  Doc/whatsnew/3.4.rst
  Misc/NEWS.d/3.11.0a4.rst
  Misc/NEWS.d/3.14.0a1.rst
  Misc/NEWS.d/next/Library/2024-12-16-22-20-38.gh-issue-121604.m3Xn4G.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129485 [3.13] gh-127349: Add check for correct resizing in REPL (GH-127387)
  Lib/_pyrepl/reader.py
  Lib/test/test_pyrepl/test_reader.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-11-30-16-13-31.gh-issue-127349.ssYd6n.rst
Labels: awaiting core review, topic-repl

#129376 gh-129350: Make tests for glob with trailing slash more strict
  Lib/test/test_glob.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129649 [3.13] Use roles :data: and :const: for referencing module variables (GH-129507)
  Doc/howto/free-threading-python.rst
  Doc/library/datetime.rst
  Doc/library/decimal.rst
  Doc/library/filecmp.rst
  Doc/library/importlib.metadata.rst
  Doc/library/importlib.rst
  Doc/library/logging.rst
  Doc/library/plistlib.rst
  Doc/library/select.rst
  Doc/library/site.rst
  Doc/library/ssl.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.13.rst
  Doc/whatsnew/3.4.rst
  Misc/NEWS.d/3.11.0a4.rst
Labels: docs, skip issue, awaiting core review, skip news

#129177 gh-128772: Fix pydoc for methods with __module__ is None
  Lib/pydoc.py
  Lib/test/test_pydoc/module_none.py
  Lib/test/test_pydoc/test_pydoc.py
  Misc/NEWS.d/next/Library/2025-01-22-13-29-06.gh-issue-128772.6YrxYM.rst
Labels: awaiting core review, needs backport to 3.12, needs backport to 3.13

#129650 [3.12] Use roles :data: and :const: for referencing module variables (GH-129507)
  Doc/library/datetime.rst
  Doc/library/decimal.rst
  Doc/library/filecmp.rst
  Doc/library/importlib.metadata.rst
  Doc/library/importlib.rst
  Doc/library/logging.rst
  Doc/library/select.rst
  Doc/library/ssl.rst
  Doc/whatsnew/2.3.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.4.rst
  Misc/NEWS.d/3.11.0a4.rst
Labels: docs, skip issue, awaiting core review, skip news

#129654 [3.12] gh-128772: Fix pydoc for methods with __module__ is None (GH-129177)
  Lib/pydoc.py
  Lib/test/test_pydoc/module_none.py
  Lib/test/test_pydoc/test_pydoc.py
  Misc/NEWS.d/next/Library/2025-01-22-13-29-06.gh-issue-128772.6YrxYM.rst
Labels: awaiting review

#129656 gh-129354: Use PyErr_FormatUnraisable() function
  Modules/_io/fileio.c
  Modules/_io/iobase.c
  Modules/socketmodule.c
Labels: awaiting merge, skip news

#129647 gh-129646: Update the locale alias mapping
  Lib/locale.py
  Misc/NEWS.d/next/Library/2025-02-04-15-16-33.gh-issue-129646.sapk1F.rst
Labels: awaiting merge, needs backport to 3.13

#129658 [3.13] gh-129646: Update the locale alias mapping (GH-129647)
  Lib/locale.py
  Misc/NEWS.d/next/Library/2025-02-04-15-16-33.gh-issue-129646.sapk1F.rst
Labels: awaiting review

#129661 gh-129660: Do not use test_embed in PGO profile builds
  Misc/NEWS.d/next/Build/2025-02-04-12-30-43.gh-issue-129660.SitXa7.rst
Labels: docs, awaiting merge

#128003 gh-127933: Add option to run regression tests in parallel
  Doc/library/test.rst
  Lib/test/libregrtest/cmdline.py
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/parallel_case.py
  Lib/test/libregrtest/runtests.py
  Lib/test/libregrtest/single.py
  Lib/test/support/__init__.py
  Lib/test/test_class.py
  Lib/test/test_descr.py
  Lib/test/test_operator.py
  Lib/test/test_tokenize.py
  Misc/NEWS.d/next/Tests/2024-12-16-19-15-10.gh-issue-128003.GVBrfa.rst
Labels: tests, awaiting merge, topic-free-threading

#129672 gh-104400: pygettext: Prepare to replace TokenEater with a NodeVisitor
  Tools/i18n/pygettext.py
Labels: awaiting merge, skip news

#129644 gh-129643: fix thread safety of `PyList_SetItem`
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-04-12-42-40.gh-issue-129643.K24Zow.rst
  Objects/listobject.c
Labels: awaiting merge, topic-free-threading, needs backport to 3.13

#129677 [3.13] gh-129643: fix thread safety of `PyList_SetItem` (#129644)
  Misc/NEWS.d/next/Core and Builtins/2025-02-04-12-42-40.gh-issue-129643.K24Zow.rst
  Objects/listobject.c
Labels: awaiting core review, topic-free-threading

#129657 gh-128911: Use PyImport_ImportModuleAttr() function
  Modules/_ctypes/callbacks.c
  Modules/_ctypes/stgdict.c
  Modules/_testcapi/code.c
  Modules/_testcapimodule.c
  Modules/main.c
  Python/crossinterp.c
  Python/pythonrun.c
Labels: awaiting core review, skip news

#129523 gh-129354: Use PyErr_FormatUnraisable() function
  Lib/test/test_coroutines.py
  Lib/test/test_exceptions.py
  Lib/test/test_generators.py
  Lib/test/test_struct.py
  Objects/genobject.c
  Objects/typeobject.c
  Python/_warnings.c
Labels: awaiting merge, skip news

#129662 [3.13] gh-129660: Do not use test_embed in PGO profile builds
  Lib/test/libregrtest/pgo.py
  Misc/NEWS.d/next/Build/2025-02-04-12-30-43.gh-issue-129660.SitXa7.rst
Labels: awaiting merge, needs backport to 3.12

#129685 [3.12] gh-129660: Do not use test_embed in PGO profile builds (GH-129662)
  Lib/test/libregrtest/pgo.py
  Misc/NEWS.d/next/Build/2025-02-04-12-30-43.gh-issue-129660.SitXa7.rst
Labels: awaiting review

#129653 [3.13] gh-128772: Fix pydoc for methods with __module__ is None (GH-129177)
  Lib/pydoc.py
  Lib/test/test_pydoc/module_none.py
  Lib/test/test_pydoc/test_pydoc.py
  Misc/NEWS.d/next/Library/2025-01-22-13-29-06.gh-issue-128772.6YrxYM.rst
Labels: awaiting review

#127835 gh-127833: Docs: Add a `grammar-snippet` directive & replace `productionlist`
  Doc/conf.py
  Doc/reference/toplevel_components.rst
  Doc/tools/extensions/grammar_snippet.py
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129627 Convert change detection to a Python script
  .github/workflows/build.yml
  .github/workflows/reusable-change-detection.yml
  .github/workflows/reusable-context.yml
  Tools/build/compute-changes.py
Labels: skip issue, awaiting core review, skip news

#129560 gh-129559: Add `bytearray.resize()`
  Doc/c-api/bytearray.rst
  Doc/library/stdtypes.rst
  Lib/test/test_bytes.py
  Lib/test/test_capi/test_bytearray.py
  Misc/NEWS.d/next/Library/2025-02-01-14-55-33.gh-issue-129559.hQCeAz.rst
  Objects/bytearrayobject.c
  Objects/clinic/bytearrayobject.c.h
Labels: awaiting merge

#129203 gh-129201: Use prefetch in GC mark alive phase.
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-22-14-22-34.gh-issue-129201.wiZzEb.rst
  Python/gc_free_threading.c
Labels: type-feature, performance, awaiting merge, topic-free-threading

#129588 gh-69001: Replace maintainer email in IDLE credits
  Lib/idlelib/CREDITS.txt
Labels: awaiting merge, skip news, topic-IDLE, needs backport to 3.12, needs backport to 3.13

#129714 [3.12] gh-69001: Replace maintainer email in IDLE credits (GH-129588)
  Lib/idlelib/CREDITS.txt
Labels: awaiting review, skip news, topic-IDLE

#129713 [3.13] gh-69001: Replace maintainer email in IDLE credits (GH-129588)
  Lib/idlelib/CREDITS.txt
Labels: awaiting review, skip news, topic-IDLE

#129698 gh-86206: Change IDLE splash line
  Lib/idlelib/pyshell.py
Labels: awaiting review, skip news, needs backport to 3.12, needs backport to 3.13

#129717 [3.13] gh-86206: Change IDLE splash line (GH-129698)
  Lib/idlelib/pyshell.py
Labels: awaiting review, skip news

#129718 [3.12] gh-86206: Change IDLE splash line (GH-129698)
  Lib/idlelib/pyshell.py
Labels: awaiting review, skip news

#129702 gh-129005: Update _pyio.BytesIO to use bytearray.resize on write
  Lib/_pyio.py
Labels: awaiting merge, skip news

#129017 Use a permalink for the analysis of MS-Word extensions
  Lib/_markupbase.py
Labels: skip issue, awaiting core review, skip news

#129691 gh-118915: Fix bad link in documentation
  Doc/c-api/init.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.13

#129723 [3.13] gh-118915: Fix bad link in documentation (GH-129691)
  Doc/c-api/init.rst
Labels: docs, awaiting core review, skip news

#129680 gh-129643: Fix `PyList_Insert` in free-threading builds
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-05-11-29-52.gh-issue-129643.4mGzvg.rst
  Objects/listobject.c
Labels: awaiting merge, needs backport to 3.13

#129725 [3.13] gh-129643: Fix `PyList_Insert` in free-threading builds (GH-129680)
  Misc/NEWS.d/next/Core and Builtins/2025-02-05-11-29-52.gh-issue-129643.4mGzvg.rst
  Objects/listobject.c
Labels: awaiting core review

#129673 [3.13] Merge TSAN test matrices in CI (#123278)
  .github/workflows/build.yml
  .github/workflows/reusable-tsan.yml
  Tools/tsan/suppressions.txt
Labels: skip issue, awaiting review, skip news

#129016 gh-128714: Fix function object races in FT build
  Lib/test/test_free_threading/test_func_annotations.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-19-09-07-44.gh-issue-128714.m1fyCB.rst
  Objects/clinic/funcobject.c.h
  Objects/funcobject.c
Labels: awaiting merge, topic-free-threading, needs backport to 3.13

#128718 gh-128563: A new tail-calling interpreter
  .github/workflows/tail-call.yml
  Lib/test/test_generated_cases.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-10-18-56-20.gh-issue-128563.baDvls.rst
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/target_generator.py
  Tools/cases_generator/tier1_generator.py
  Tools/jit/template.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge

#129708 gh-129707: Check `Tools/build/compute-changes.py` with `mypy`
  Tools/build/mypy.ini
Labels: awaiting merge, skip news

#129399 gh-91048: fix thread safety for asyncio stack introspection APIs
  Modules/_asynciomodule.c
  Modules/clinic/_asynciomodule.c.h
Labels: topic-asyncio, awaiting core review, skip news

#129731 gh-91048: fix `_asyncio.future_discard_from_awaited_by`
  Modules/_asynciomodule.c
Labels: topic-asyncio, awaiting core review, skip news

#129733 Remove an inaccurate note from `socket.recv`
  Doc/library/socket.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#129674 [3.12] Merge TSAN test matrices in CI (#123278)
  .github/workflows/build.yml
  .github/workflows/reusable-tsan.yml
  Tools/tsan/suppressions.txt
Labels: skip issue, skip news

#129663 GH-121970: Extract ``implementation_detail`` into a new extension
  Doc/conf.py
  Doc/tools/extensions/implementation_detail.py
  Doc/tools/extensions/pyspecific.py
  Doc/tools/templates/dummy.html
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129739 [3.13] GH-121970: Extract ``implementation_detail`` into a new extension (GH-129663)
  Doc/conf.py
  Doc/tools/extensions/implementation_detail.py
  Doc/tools/extensions/pyspecific.py
  Doc/tools/templates/dummy.html
Labels: skip issue, awaiting core review, skip news

#129740 [3.12] GH-121970: Extract ``implementation_detail`` into a new extension (GH-129663)
  Doc/conf.py
  Doc/tools/extensions/implementation_detail.py
  Doc/tools/extensions/pyspecific.py
  Doc/tools/templates/dummy.html
Labels: skip issue, awaiting core review, skip news

#129704 gh-129668: Fix thread-safety of MemoryError freelist in free threaded build
  Include/internal/pycore_exceptions.h
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-04-21-26-05.gh-issue-129668.zDanyM.rst
  Objects/exceptions.c
Labels: awaiting merge, needs backport to 3.13

#129741 gh-112020: Rework socketserver examples to be correct
  Doc/library/socketserver.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#129734 [3.13] Remove an inaccurate note from `socket.recv` (GH-129733)
  Doc/library/socket.rst
Labels: docs, skip issue, awaiting review, skip news

#129735 [3.12] Remove an inaccurate note from `socket.recv` (GH-129733)
  Doc/library/socket.rst
Labels: docs, skip issue, awaiting review, skip news

#129743 [3.13] gh-112020: Rework socketserver examples to be correct (GH-129741)
  Doc/library/socketserver.rst
Labels: docs, awaiting review, skip news

#129744 [3.12] gh-112020: Rework socketserver examples to be correct (GH-129741)
  Doc/library/socketserver.rst
Labels: docs, awaiting review, skip news

#129742 [3.13] gh-129668: Fix thread-safety of MemoryError freelist in free threaded build (gh-129704)
  Include/internal/pycore_exceptions.h
  Misc/NEWS.d/next/Core and Builtins/2025-02-04-21-26-05.gh-issue-129668.zDanyM.rst
  Objects/exceptions.c
Labels: awaiting core review

#129738 gh-129732: Fix race in on shared->array in qsbr code under free-threa…
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-06-17-57-33.gh-issue-129732.yl97oq.rst
  Python/qsbr.c
Labels: awaiting merge, needs backport to 3.13

#128869 gh-128002: use per threads tasks linked list in asyncio
  Include/internal/pycore_interp.h
  Include/internal/pycore_lock.h
  Include/internal/pycore_pystate.h
  Include/internal/pycore_tstate.h
  Lib/test/test_asyncio/test_free_threading.py
  Modules/_asynciomodule.c
  Python/pystate.c
Labels: topic-asyncio, awaiting review, skip news, topic-free-threading

#129747 [3.13] gh-129732: Fix race on `shared->array` in qsbr code under free-threading (gh-129738)
  Misc/NEWS.d/next/Core and Builtins/2025-02-06-17-57-33.gh-issue-129732.yl97oq.rst
  Python/qsbr.c
Labels: awaiting core review

#129665 gh-117657: Fix data race in new_reference for free-threaded build
  Objects/object.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news

#129751 gh-117657: Skip tests that may cause stack overflows under TSan
  Lib/test/test_call.py
  Lib/test/test_functools.py
Labels: tests, awaiting merge, skip news, topic-free-threading

#129563 gh-129533: Update PyGC_Enable/Disable/IsEnabled to use atomic operation
  Misc/NEWS.d/next/C_API/2025-02-02-12-58-21.gh-issue-129533.dFfqkT.rst
  Python/gc_free_threading.c
Labels: awaiting merge, topic-free-threading, needs backport to 3.13

#129756 [3.13] gh-129533: Update PyGC_Enable/Disable/IsEnabled to use atomic operat…
  Misc/NEWS.d/next/C API/2025-02-02-12-58-21.gh-issue-129533.dFfqkT.rst
  Python/gc_free_threading.c
Labels: awaiting merge, topic-free-threading

#129749 gh-117657: Include all of test_free_threading in TSAN tests
  Lib/test/libregrtest/tsan.py
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge, skip news

#129760 Add multinomial to the itertools recipes docs
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#129762 [3.13] Add multinomial to the itertools recipes docs (gh-129760)
  Doc/library/itertools.rst
Labels: docs, skip issue, awaiting review, skip news

#129754 gh-129737: Fix help message for tail calling interpreter configuration
  configure
  configure.ac
Labels: awaiting merge, skip news

#122542 gh-55454: Add IMAP4 IDLE support to imaplib
  Doc/library/imaplib.rst
  Doc/whatsnew/3.14.rst
  Lib/imaplib.py
  Lib/test/test_imaplib.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2024-08-01-01-00-00.gh-issue-55454.wy0vGw.rst
Labels: awaiting merge

#129757 Emscripten: use better `_Py_Version` computation for worker module
  Tools/wasm/emscripten/web_example/python.worker.mjs
Labels: skip issue, awaiting merge, skip news

#129771 gh-129766: Fix crash on calling `warnings._release_lock` with no lock
  Lib/test/test_warnings/__init__.py
  Misc/NEWS.d/next/Library/2025-02-07-10-34-09.gh-issue-129766.6n5fQZ.rst
  Python/_warnings.c
Labels: awaiting merge

#129705 gh-129005: Align FileIO.readall between _pyio and _io
  Lib/_pyio.py
  Misc/NEWS.d/next/Library/2025-02-05-13-19-15.gh-issue-129005.Sb69L_.rst
Labels: awaiting merge

#129728 gh-128563: Document the tail-calling interpreter
  Doc/using/configure.rst
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#129803 gh-128563: Move assignment of opcode into ifdef
  Lib/test/test_generated_cases.py
  Python/generated_cases.c.h
  Tools/cases_generator/tier1_generator.py
Labels: awaiting merge, skip news

#129755 gh-117657: Fix data race in `dict_dict_merge`
  Objects/dictobject.c
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#129809 gh-128563: Clarify tail calling interpreter is not TCO
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#129812 gh-128563: Clarify clarificatory tail calling wording in What's New
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#129808 [3.13] gh-117657: Fix data race in `dict_dict_merge` (gh-129755)
  Objects/dictobject.c
Labels: awaiting review, skip news, topic-free-threading

#129815 fix tests in `test_asyncio.test_tasks` to use correct `all_tasks`
  Lib/test/test_asyncio/test_tasks.py
Labels: tests, topic-asyncio, skip issue, awaiting core review, skip news

#129764 GH-129763: Remove the `LLTRACE` macro
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-06-17-05-09.gh-issue-129763.6ZxQ8W.rst
  Misc/SpecialBuilds.txt
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/generated_cases.c.h
  Tools/c-analyzer/TODO
  Tools/cases_generator/analyzer.py
  Tools/jit/template.c
Labels: awaiting merge, interpreter-core

#129710 GH-129709: Clean up tier two
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/jit/jit.h
  Tools/jit/shim.c
  Tools/jit/template.c
Labels: awaiting merge, skip news, interpreter-core, topic-JIT

#129822 Fix Garrett Gu name misspelling in 3.14 whatsnew
  Doc/whatsnew/3.14.rst
Labels: docs, skip issue, awaiting merge, skip news

#129821 improve `test_log_destroyed_pending_task` in asyncio
  Lib/test/test_asyncio/test_tasks.py
Labels: tests, topic-asyncio, skip issue, awaiting core review, skip news

#129823 Remove tail-calling wording as it is confusing
  Doc/whatsnew/3.14.rst
Labels: docs, skip issue, awaiting core review, skip news

#129828 Fix link in 3.14 whatsnew
  Doc/whatsnew/3.14.rst
Labels: docs, skip issue, awaiting core review, skip news

#129716 GH-129715: Remove `_DYNAMIC_EXIT`
  Include/cpython/pystats.h
  Include/internal/pycore_optimizer.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-05-22-58-18.gh-issue-129715.mLlpIO.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/optimizer.c
  Python/optimizer_analysis.c
  Python/optimizer_cases.c.h
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: performance, awaiting merge, interpreter-core, topic-JIT

#129827 gh-129825: Skip test_faulthandler.test_register_chain under TSAN
  Lib/test/test_faulthandler.py
Labels: tests, awaiting merge, skip news

#129700 gh-100239: replace BINARY_SUBSCR & family by BINARY_OP with oparg NB_SUBSCR
  Doc/library/dis.rst
  Doc/whatsnew/3.14.rst
  Include/internal/pycore_code.h
  Include/internal/pycore_magic_number.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Include/opcode.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/test/test__opcode.py
  Lib/test/test_compile.py
  Lib/test/test_dis.py
  Lib/test/test_opcache.py
  Lib/test/test_peepholer.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-07-17-06-39.gh-issue-100239.WvBTPL.rst
  Modules/_opcode.c
  Programs/test_frozenmain.h
  Python/bytecodes.c
  Python/ceval.c
  Python/codegen.c
  Python/executor_cases.c.h
  Python/flowgraph.c
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Python/optimizer.c
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Python/specialize.c
  Tools/c-analyzer/cpython/ignored.tsv
Labels: awaiting merge

#127730 GH-125413: Add `pathlib.Path.info` attribute
  Doc/library/pathlib.rst
  Doc/whatsnew/3.14.rst
  Lib/glob.py
  Lib/pathlib/_abc.py
  Lib/pathlib/_local.py
  Lib/pathlib/_os.py
  Lib/pathlib/types.py
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_pathlib/test_pathlib_abc.py
  Misc/NEWS.d/next/Library/2024-12-10-19-39-35.gh-issue-125413.wOb4yr.rst
Labels: type-feature, awaiting merge, topic-pathlib

#129818 gh-124703: Add documentation and whatsnew entry for pdb exit change
  Doc/library/pdb.rst
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#128886 gh-128657: fix _hashopenssl ref/data race
  Misc/NEWS.d/next/Library/2025-01-15-15-45-21.gh-issue-128657.P5LNQA.rst
  Modules/_hashopenssl.c
Labels: awaiting merge, topic-free-threading, needs backport to 3.13

#129836 GH-129835: Yield path with trailing slash from `ReadablePath.glob('')`
  Lib/glob.py
  Lib/pathlib/_abc.py
  Lib/pathlib/_local.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: awaiting core review, skip news, topic-pathlib

#129834 Use ubuntu-22.04-arm image for Arm runners.
  .github/workflows/build.yml
  .github/workflows/jit.yml
  .github/workflows/tail-call.yml
Labels: skip issue, awaiting merge, skip news, infra

#129845 gh-129842: Remove obsolete requirement reference
  Lib/warnings.py
Labels: awaiting review, skip news

#122946 gh-119349: Add ctypes.util function to list loaded shared libraries
  Doc/library/ctypes.rst
  Doc/whatsnew/3.14.rst
  Lib/ctypes/util.py
  Lib/test/test_ctypes/test_dllist.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2024-08-12-11-58-15.gh-issue-119349.-xTnHl.rst
Labels: awaiting core review, topic-ctypes

#129083 gh-111178: fix UBSan failures in `Modules/_io/*.c`
  Modules/_io/bufferedio.c
  Modules/_io/bytesio.c
  Modules/_io/fileio.c
  Modules/_io/iobase.c
  Modules/_io/stringio.c
  Modules/_io/textio.c
  Modules/_io/winconsoleio.c
Labels: awaiting core review, skip news

#129772 gh-111178: fix UBSan failures in `Modules/arraymodule.c`
  Modules/arraymodule.c
Labels: awaiting core review, skip news
