Repository python/cpython, pull requests merged in 2025-06, with the labels that each got.

#134971 gh-134970: Fix exception message in `argparse` module
  Lib/argparse.py
  Misc/NEWS.d/next/Library/2025-05-31-12-08-12.gh-issue-134970.lgSaxq.rst
Labels: awaiting merge, needs backport to 3.13, needs backport to 3.14

#134756 gh-133503: Update `compileall.rst`'s documentation of `-s` and `-p` for clarity,
  Doc/library/compileall.rst
Labels: docs, awaiting merge, skip news

#134930 gh-132983: Minor fixes and clean up for the _zstd module
  Lib/test/test_zstd.py
  Modules/_zstd/_zstdmodule.c
  Modules/_zstd/_zstdmodule.h
  Modules/_zstd/compressor.c
  Modules/_zstd/decompressor.c
  Modules/_zstd/zstddict.c
Labels: awaiting core review, skip news, needs backport to 3.14

#134997 [3.14] gh-133503: clarify `compileall -s/-p` docs (GH-134756)
  Doc/library/compileall.rst
Labels: docs, awaiting merge, skip news

#134962 [3.13] gh-134696: align OpenSSL and HACL*-based hash functions constructors AC signatures (GH-134713)
  Lib/hashlib.py
  Lib/test/test_hashlib.py
  Misc/NEWS.d/next/Library/2025-05-26-14-04-39.gh-issue-134696.P04xUa.rst
  Modules/_blake2/blake2b_impl.c
  Modules/_blake2/blake2s_impl.c
  Modules/_blake2/clinic/blake2b_impl.c.h
  Modules/_blake2/clinic/blake2s_impl.c.h
  Modules/_hashopenssl.c
  Modules/clinic/_hashopenssl.c.h
  Modules/clinic/md5module.c.h
  Modules/clinic/sha1module.c.h
  Modules/clinic/sha2module.c.h
  Modules/clinic/sha3module.c.h
  Modules/hashlib.h
  Modules/md5module.c
  Modules/sha1module.c
  Modules/sha2module.c
  Modules/sha3module.c
Labels: awaiting core review

#134996 [3.13] gh-133503: clarify `compileall -s/-p` docs (GH-134756)
  Doc/library/compileall.rst
Labels: docs, awaiting merge, skip news

#134998 [3.14] gh-132983: Minor fixes and clean up for the _zstd module (GH-134930)
  Lib/test/test_zstd.py
  Modules/_zstd/_zstdmodule.c
  Modules/_zstd/_zstdmodule.h
  Modules/_zstd/compressor.c
  Modules/_zstd/decompressor.c
  Modules/_zstd/zstddict.c
Labels: awaiting review, skip news

#134188 gh-130478: Fixed HACL compilation failure on macOS Silicon
  configure
  configure.ac
Labels: awaiting merge, skip news, needs backport to 3.14

#134608 gh-134449: fix grammar for precision_with_grouping in format description
  Doc/library/string.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.14

#134960 gh-122153: fix docs: Windows doesn't support `{send,recv}_fds`
  Doc/library/socket.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#132935 gh-132908: Add math.isnormal/issubnormal() functions
  Doc/library/math.rst
  Doc/whatsnew/3.14.rst
  Doc/whatsnew/3.15.rst
  Lib/test/test_math.py
  Misc/NEWS.d/next/Library/2025-04-25-16-06-53.gh-issue-132908.wV5rja.rst
  Modules/clinic/mathmodule.c.h
  Modules/mathmodule.c
Labels: awaiting merge

#135018 [3.14] gh-122153: indicate that Windows does not support `socket.{send,recv}_fds` (GH-134960)
  Doc/library/socket.rst
Labels: docs, skip news

#131001 gh-130999: Avoid exiting the new REPL when there are non-string candidates for suggestions
  Lib/test/test_pyrepl/test_pyrepl.py
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2025-03-09-03-13-41.gh-issue-130999.tBRBVB.rst
Labels: awaiting review, needs backport to 3.13, topic-repl, needs backport to 3.14

#130663 gh-130662: accept leading zeros in precision/width for Fraction's formatting
  Lib/fractions.py
  Lib/test/test_fractions.py
  Misc/NEWS.d/next/Library/2025-06-02-14-28-30.gh-issue-130662.EIgIR8.rst
Labels: awaiting merge, skip news, needs backport to 3.14

#131212 gh-123471: Make concurrent iteration over itertools.cycle safe under free-threading
  Lib/test/test_free_threading/test_itertools.py
  Misc/NEWS.d/next/Library/2025-03-13-20-48-58.gh-issue-123471.cM4w4f.rst
  Modules/itertoolsmodule.c
Labels: awaiting merge, topic-free-threading

#134341 [3.11] gh-133767: Fix use-after-free in the unicode-escape decoder with an error handler (GH-129648) (GH-133944)
  Include/cpython/bytesobject.h
  Include/cpython/unicodeobject.h
  Lib/test/test_codeccallbacks.py
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Security/2025-05-09-20-22-54.gh-issue-133767.kN2i3Q.rst
  Objects/bytesobject.c
  Objects/unicodeobject.c
  Parser/string_parser.c
Labels: type-security, awaiting core review

#134345 [3.10] gh-133767: Fix use-after-free in the unicode-escape decoder with an error handler (GH-129648) (GH-133944)
  Include/cpython/bytesobject.h
  Include/cpython/unicodeobject.h
  Lib/test/test_codeccallbacks.py
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Security/2025-05-09-20-22-54.gh-issue-133767.kN2i3Q.rst
  Objects/bytesobject.c
  Objects/unicodeobject.c
  Parser/string_parser.c
Labels: type-security, awaiting core review

#132371 [3.9] gh-80222: Fix email address header folding with long quoted-string (GH-122753) (GH-129111)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Security/2024-08-06-11-43-08.gh-issue-80222.wfR4BU.rst
Labels: type-security, awaiting merge, topic-email

#134346 [3.9] gh-133767: Fix use-after-free in the unicode-escape decoder with an error handler (GH-129648) (GH-133944)
  Include/cpython/bytesobject.h
  Include/cpython/unicodeobject.h
  Lib/test/test_codeccallbacks.py
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Security/2025-05-09-20-22-54.gh-issue-133767.kN2i3Q.rst
  Objects/bytesobject.c
  Objects/unicodeobject.c
  Parser/pegen/parse_string.c
Labels: type-security, awaiting core review

#135035 [3.9] bpo-43757: Make pathlib use os.path.realpath() to resolve symlinks in a path (GH-25264)
  Doc/library/os.path.rst
  Lib/ntpath.py
  Lib/pathlib.py
  Lib/posixpath.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Misc/NEWS.d/next/Library/2021-04-08-22-11-27.bpo-25264.b33fa0.rst
Labels: awaiting core review

#134910 gh-134908: protect ``textiowrapper_iternext`` with critical section
  Lib/test/test_io.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-30-15-56-19.gh-issue-134908.3a7PxM.rst
  Modules/_io/textio.c
Labels: awaiting merge, topic-free-threading, needs backport to 3.13, needs backport to 3.14

#135039 [3.14] gh-134908: Protect `textiowrapper_iternext` with critical section (gh-134910)
  Lib/test/test_io.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-30-15-56-19.gh-issue-134908.3a7PxM.rst
  Modules/_io/textio.c
Labels: awaiting review, topic-free-threading

#135040 [3.13] gh-134908: Protect `textiowrapper_iternext` with critical section (gh-134910)
  Lib/test/test_io.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-30-15-56-19.gh-issue-134908.3a7PxM.rst
  Modules/_io/textio.c
Labels: awaiting core review, topic-free-threading

#134965 [3.13] gh-133489: Remove size restrictions on getrandbits() and randbytes() (GH-133658)
  Lib/test/test_random.py
  Misc/NEWS.d/next/Library/2025-05-08-13-43-19.gh-issue-133489.9eGS1Z.rst
  Modules/_randommodule.c
  Modules/clinic/_randommodule.c.h
  Objects/longobject.c
Labels: awaiting merge

#134575 gh-133454: Mark test_queue tests with many threads as bigmem
  Lib/test/test_queue.py
Labels: tests, awaiting core review, skip news, needs backport to 3.13, needs backport to 3.14

#133241 gh-132813: Improve error messages for incorrect types and values of csv.Dialog attributes
  Lib/test/test_csv.py
  Misc/NEWS.d/next/Library/2025-05-01-10-56-44.gh-issue-132813.rKurvp.rst
  Modules/_csv.c
Labels: awaiting core review, needs backport to 3.14

#135049 [3.13] gh-74232: Add a note about roundtrip of non-float numerics in CSV (GH-134963)
  Doc/library/csv.rst
Labels: docs, awaiting review, skip news

#135048 [3.14] gh-74232: Add a note about roundtrip of non-float numerics in CSV (GH-134963)
  Doc/library/csv.rst
Labels: docs, awaiting review, skip news

#135046 [3.14] gh-133454: Mark test_queue tests with many threads as bigmem (gh-134575)
  Lib/test/test_queue.py
Labels: tests, awaiting review, skip news

#135050 [3.14] gh-132813: Improve error messages for incorrect types and values of csv.Dialog attributes (GH-133241)
  Lib/test/test_csv.py
  Misc/NEWS.d/next/Library/2025-05-01-10-56-44.gh-issue-132813.rKurvp.rst
  Modules/_csv.c
Labels: awaiting review

#134831 gh-134830: Fix reference in `Doc/extending/windows.rst`
  Doc/c-api/stable.rst
  Doc/extending/windows.rst
Labels: docs, awaiting core review, skip news

#134994 gh-134875: Fix mimallc build error for the old compilers
  Include/internal/mimalloc/mimalloc/internal.h
Labels: awaiting merge, skip news, needs backport to 3.14

#128606 gh-128605: Add branch protections for x86_64 in asm_trampoline.S
  Python/asm_trampoline.S
  Python/perf_jit_trampoline.c
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13, needs backport to 3.14

#132200 gh-131884: Fix incorrect formatting in `json.dumps()` when using `indent` and `skipkeys=True`
  Lib/json/encoder.py
  Lib/test/test_json/test_dump.py
  Misc/NEWS.d/next/Library/2025-04-07-06-41-54.gh-issue-131884.ym9BJN.rst
  Modules/_json.c
Labels: awaiting merge, needs backport to 3.13, needs backport to 3.14

#135054 [3.13] gh-134875: Fix mimallc build error for the old compilers (gh-134994)
  Include/internal/mimalloc/mimalloc/internal.h
Labels: awaiting merge, skip news

#135037 gh-135034: Normalize link targets in tarfile, add `os.path.realpath(strict='allow_missing')`
  Doc/library/os.path.rst
  Doc/library/tarfile.rst
  Doc/whatsnew/3.15.rst
  Lib/genericpath.py
  Lib/ntpath.py
  Lib/posixpath.py
  Lib/tarfile.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Security/2025-06-02-11-32-23.gh-issue-135034.RLGjbp.rst
Labels: awaiting core review

#135065 [3.14] gh-135034: Normalize link targets in tarfile, add `os.path.realpath(strict='allow_missing')` (gh-135037)
  Doc/library/os.path.rst
  Doc/library/tarfile.rst
  Doc/whatsnew/3.14.rst
  Lib/genericpath.py
  Lib/ntpath.py
  Lib/posixpath.py
  Lib/tarfile.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Security/2025-06-02-11-32-23.gh-issue-135034.RLGjbp.rst
Labels: awaiting core review

#135077 [3.14] gh-128605: Add branch protections for x86_64 in asm_trampoline.S (#128606)
  Python/asm_trampoline.S
  Python/perf_jit_trampoline.c
Labels: awaiting review, skip news

#135080 [3.11] gh-87799: Improve the textual representation of IPv4-mapped IPv6 addresses (GH-29345)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2021-10-31-16-06-28.bpo-43633.vflwXv.rst
Labels: awaiting review

#135081 [3.12] gh-87799: Improve the textual representation of IPv4-mapped IPv6 addresses (GH-29345)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2021-10-31-16-06-28.bpo-43633.vflwXv.rst
Labels: awaiting review

#135078 [3.9] gh-87799: Improve the textual representation of IPv4-mapped IPv6 addresses (GH-29345)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2021-10-31-16-06-28.bpo-43633.vflwXv.rst
Labels: awaiting review

#135079 [3.10] gh-87799: Improve the textual representation of IPv4-mapped IPv6 addresses (GH-29345)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2021-10-31-16-06-28.bpo-43633.vflwXv.rst
Labels: awaiting review

#134615 [3.9] gh-128840: Limit the number of parts in IPv6 address parsing (GH-128841)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Security/2025-01-14-11-19-07.gh-issue-128840.M1doZW.rst
Labels: type-security, awaiting review

#135064 [3.13] gh-135034: Normalize link targets in tarfile, add `os.path.realpath(strict='allow_missing')` (GH-135037)
  Doc/library/os.path.rst
  Doc/library/tarfile.rst
  Doc/whatsnew/3.13.rst
  Lib/genericpath.py
  Lib/ntpath.py
  Lib/posixpath.py
  Lib/tarfile.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Security/2025-06-02-11-32-23.gh-issue-135034.RLGjbp.rst
Labels: awaiting core review

#135066 [3.12] gh-135034: Normalize link targets in tarfile, add `os.path.realpath(strict='allow_missing')` (GH-135037)
  Doc/library/os.path.rst
  Doc/library/tarfile.rst
  Doc/whatsnew/3.12.rst
  Lib/genericpath.py
  Lib/ntpath.py
  Lib/posixpath.py
  Lib/tarfile.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Security/2025-06-02-11-32-23.gh-issue-135034.RLGjbp.rst
Labels: awaiting core review

#135087 [3.11] gh-123409: fix `IPv6Address.reverse_pointer` for IPv4-mapped addresses (GH-123419)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2024-08-28-13-03-36.gh-issue-123409.lW0YF-.rst
Labels: awaiting review

#134847 [3.12] gh-128840: Fix parsing long IPv6 addresses with embedded IPv4 address (GH-134836)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2025-05-28-15-53-27.gh-issue-128840.Nur2pB.rst
Labels: release-blocker

#135090 [3.9] gh-128840: Fix parsing long IPv6 addresses with embedded IPv4 address (GH-134836)
  Lib/ipaddress.py
  Lib/test/test_ipaddress.py
  Misc/NEWS.d/next/Library/2025-05-28-15-53-27.gh-issue-128840.Nur2pB.rst
Labels: awaiting review

#135093 [3.12] gh-135034: Remove test_realpath_permission
  Lib/test/test_ntpath.py
Labels: tests, skip news

#135068 [3.11] gh-135034: Normalize link targets in tarfile, add `os.path.realpath(strict='allow_missing')` (GH-135037)
  Doc/library/os.path.rst
  Doc/library/tarfile.rst
  Doc/whatsnew/3.11.rst
  Lib/genericpath.py
  Lib/ntpath.py
  Lib/posixpath.py
  Lib/tarfile.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Security/2025-06-02-11-32-23.gh-issue-135034.RLGjbp.rst
Labels: awaiting merge

#134871 gh-134248 test_getallocatedblocks pre-check to ignore immortalized strings
  Lib/test/test_sys.py
Labels: tests, skip news, needs backport to 3.14

#135095 [3.14] gh-134248 test_getallocatedblocks pre-check to ignore immortalized strings (GH-134871)
  Lib/test/test_sys.py
Labels: tests, awaiting review, skip news

#135070 [3.10] gh-135034: Normalize link targets in tarfile, add `os.path.realpath(strict='allow_missing')` (GH-135037)
  Doc/library/os.path.rst
  Doc/library/tarfile.rst
  Doc/whatsnew/3.10.rst
  Lib/genericpath.py
  Lib/ntpath.py
  Lib/posixpath.py
  Lib/tarfile.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Security/2025-06-02-11-32-23.gh-issue-135034.RLGjbp.rst
Labels: awaiting merge

#135084 [3.9] gh-135034: Normalize link targets in tarfile, add `os.path.realpath(strict='allow_missing')` (GH-135037)
  Doc/library/os.path.rst
  Doc/library/tarfile.rst
  Doc/whatsnew/3.9.rst
  Lib/genericpath.py
  Lib/ntpath.py
  Lib/posixpath.py
  Lib/tarfile.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Security/2025-06-02-11-32-23.gh-issue-135034.RLGjbp.rst
Labels: awaiting merge

#132751 gh-127081: use `getlogin_r` if available
  Misc/NEWS.d/next/Library/2025-04-21-01-03-15.gh-issue-127081.WXRliX.rst
  Modules/posixmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge

#135097 [3.14] gh-127081: use `getlogin_r` if available (gh-132751)
  Misc/NEWS.d/next/Library/2025-04-21-01-03-15.gh-issue-127081.WXRliX.rst
  Modules/posixmodule.c
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting review

#135096 [3.13] Backport PyManager support to PC/layout script
  PC/layout/__main__.py
  PC/layout/main.py
  PC/layout/support/options.py
  PC/layout/support/pymanager.py
Labels: skip issue, awaiting core review, skip news

#135102 gh-135101: When choosing the default simulator device, don't use `simctl --set testing`
  iOS/testbed/__main__.py
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#135104 gh-135103: Remove an unused local variable in Lib/code.py
  Lib/code.py
Labels: awaiting review, skip news, stdlib, type-refactor

#135118 Use a more clear example for the PEP 758 what's new section
  Doc/whatsnew/3.14.rst
Labels: docs, skip issue, skip news, needs backport to 3.14

#135116 [3.14] gh-135099: Only wait on `_PyOS_SigintEvent()` in main thread (GH-135100)
  Misc/NEWS.d/next/Windows/2025-06-03-18-26-54.gh-issue-135099.Q9usKm.rst
  Python/parking_lot.c
Labels: awaiting review

#132694 gh-126483: disable warnings filters mutation in concurrent test_check…
  Lib/test/test_ssl.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#135021 gh-134989: Implement PyObject_DelAttr() as a macro in the limited C API
  Include/abstract.h
  Misc/NEWS.d/next/C_API/2025-06-02-13-19-22.gh-issue-134989.sDDyBN.rst
Labels: awaiting merge, topic-C-API, needs backport to 3.13, needs backport to 3.14

#135127 [3.14] gh-135108: Fix utmp.h inclusion in posixmodule.c on NetBSD (GH-135109)
  Modules/posixmodule.c
Labels: awaiting review, skip news

#135135 [3.13] gh-133256: Add _Py_NONSTRING macro (#133257)
  Include/internal/pycore_runtime.h
  Include/pyport.h
Labels: skip news

#135134 [3.13] gh-134989: Implement PyObject_DelAttr() as a macro in the limited C API (GH-135021)
  Include/abstract.h
  Misc/NEWS.d/next/C API/2025-06-02-13-19-22.gh-issue-134989.sDDyBN.rst
Labels: awaiting core review, topic-C-API

#135139 gh-129876: Update IDLE News3.txt to May 2025
  Lib/idlelib/News3.txt
Labels: awaiting core review, skip news, topic-IDLE, needs backport to 3.13, needs backport to 3.14

#135143 Update the devcontainer image to the latest version
  .devcontainer/devcontainer.json
Labels: skip issue, awaiting core review, skip news

#134958 gh-134889: Fix handling of a few opcodes when optimizing `LOAD_FAST`
  Include/internal/pycore_magic_number.h
  Lib/test/test_dis.py
  Lib/test/test_peepholer.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-30-18-09-54.gh-issue-134889.Ic9UM-.rst
  Python/flowgraph.c
Labels: awaiting merge

#132870 gh-131531: android.py enhancements to support cibuildwheel
  Android/README.md
  Android/android-env.sh
  Android/android.py
  Android/testbed/app/build.gradle.kts
  Android/testbed/app/src/androidTest/java/org/python/testbed/PythonSuite.kt
  Android/testbed/app/src/main/java/org/python/testbed/MainActivity.kt
  Android/testbed/app/src/main/python/android_testbed_main.py
  Android/testbed/build.gradle.kts
  Android/testbed/gradle/wrapper/gradle-wrapper.properties
  Doc/using/android.rst
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#135158 [3.14] gh-131531: android.py enhancements to support cibuildwheel (GH-132870)
  Android/README.md
  Android/android-env.sh
  Android/android.py
  Android/testbed/app/build.gradle.kts
  Android/testbed/app/src/androidTest/java/org/python/testbed/PythonSuite.kt
  Android/testbed/app/src/main/java/org/python/testbed/MainActivity.kt
  Android/testbed/app/src/main/python/android_testbed_main.py
  Android/testbed/build.gradle.kts
  Android/testbed/gradle/wrapper/gradle-wrapper.properties
  Doc/using/android.rst
Labels: awaiting merge, skip news

#135164 [3.13] gh-131531: android.py enhancements to support cibuildwheel (GH-132870)
  .github/CODEOWNERS
  Android/README.md
  Android/android-env.sh
  Android/android.py
  Android/testbed/app/build.gradle.kts
  Android/testbed/app/src/androidTest/java/org/python/testbed/PythonSuite.kt
  Android/testbed/app/src/main/java/org/python/testbed/MainActivity.kt
  Android/testbed/app/src/main/python/android_testbed_main.py
  Android/testbed/build.gradle.kts
  Android/testbed/gradle/wrapper/gradle-wrapper.properties
  Doc/using/android.rst
Labels: awaiting merge, skip news

#135169 [3.13] gh-135124: Change stdout errors in regrtest worker process (GH-135138)
  Lib/test/libregrtest/main.py
  Lib/test/libregrtest/setup.py
  Lib/test/test_regrtest.py
Labels: awaiting review, skip news

#135165 gh-134989: Fix Py_RETURN_NONE in the limited C API
  Include/boolobject.h
  Include/object.h
  Misc/NEWS.d/next/C_API/2025-06-05-11-06-07.gh-issue-134989.74p4ud.rst
Labels: awaiting merge

#135060 [3.14] gh-131884: Fix incorrect formatting in json.dumps() when using indent and skipkeys=True (GH-132200)
  Lib/json/encoder.py
  Lib/test/test_json/test_dump.py
  Misc/NEWS.d/next/Library/2025-04-07-06-41-54.gh-issue-131884.ym9BJN.rst
  Modules/_json.c
Labels: awaiting review

#135173 [3.14] gh-134938: Add set_pledged_input_size() to ZstdCompressor (GH-135010)
  Doc/library/compression.zstd.rst
  Lib/test/test_zstd.py
  Modules/_zstd/_zstdmodule.c
  Modules/_zstd/_zstdmodule.h
  Modules/_zstd/clinic/compressor.c.h
  Modules/_zstd/compressor.c
Labels: awaiting review, skip news

#135182 [3.13] gh-134989: Fix Py_RETURN_NONE in the limited C API (GH-135165)
  Include/boolobject.h
  Include/object.h
  Misc/NEWS.d/next/C API/2025-06-05-11-06-07.gh-issue-134989.74p4ud.rst
Labels: awaiting core review

#135162 gh-135161: Remove redundant NULL check for 'exc' after dereference in ceval.c
  Python/ceval.c
Labels: awaiting core review, skip news

#134194 gh-134155: fix AttributeError in email._header_value_parser.get_address
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Library/2025-05-18-23-46-21.gh-issue-134152.30HwbX.rst
Labels: awaiting merge, needs backport to 3.13, needs backport to 3.14

#135187 [3.14] gh-134889: Fix handling of a few opcodes when optimizing `LOAD_FAST` (#134958)
  Include/internal/pycore_magic_number.h
  Lib/test/test_dis.py
  Lib/test/test_peepholer.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-30-18-09-54.gh-issue-134889.Ic9UM-.rst
  Python/flowgraph.c
Labels: awaiting merge

#135180 [3.13] gh-135151: Fix incorrect packaging of pyconfig.h in Windows installer
  Doc/howto/free-threading-extensions.rst
  Misc/NEWS.d/next/Windows/2025-06-05-13-52-36.gh-issue-135151.4PfNZQ.rst
  Tools/msi/dev/dev_files.wxs
Labels: awaiting core review

#135121 gh-135120: Add test.support.subTests()
  Lib/test/support/__init__.py
  Lib/test/test_http_cookiejar.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_urlparse.py
  Misc/NEWS.d/next/Tests/2025-06-04-13-07-44.gh-issue-135120.NapnZT.rst
Labels: tests, awaiting core review, needs backport to 3.13, needs backport to 3.14

#135175 [3.14] gh-128605: Revert "Add branch protections for x86_64 in asm_tr…ampoline.S (#128606) (#135077)"
  Python/asm_trampoline.S
  Python/perf_jit_trampoline.c
Labels: awaiting core review, skip news, needs backport to 3.13

#135188 gh-134993: Add os.lstat() to os.supports_dir_fd
  Lib/os.py
Labels: awaiting core review, skip news, needs backport to 3.13, needs backport to 3.14

#135205 [3.14] gh-134993: Add os.lstat() to os.supports_dir_fd (GH-135188)
  Lib/os.py
Labels: awaiting review, skip news

#135208 [3.14] gh-135120: Add test.support.subTests() (GH-135121)
  Lib/test/support/__init__.py
  Lib/test/test_http_cookiejar.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_urlparse.py
  Misc/NEWS.d/next/Tests/2025-06-04-13-07-44.gh-issue-135120.NapnZT.rst
Labels: awaiting core review

#135181 feat(docs): type fix - apply pep8 by using docstring instead of comment in the doc.
  Doc/tutorial/modules.rst
Labels: docs, skip issue, awaiting core review, skip news

#135210 [3.13] gh-135120: Add test.support.subTests() (GH-135121)
  Lib/test/support/__init__.py
  Lib/test/test_http_cookiejar.py
  Lib/test/test_ntpath.py
  Lib/test/test_posixpath.py
  Lib/test/test_urlparse.py
  Misc/NEWS.d/next/Tests/2025-06-04-13-07-44.gh-issue-135120.NapnZT.rst
Labels: awaiting core review

#134892 gh-134891: Add PyUnstable_Unicode_GET_CACHED_HASH
  Doc/c-api/unicode.rst
  Doc/whatsnew/3.15.rst
  Include/cpython/unicodeobject.h
  Lib/test/test_capi/test_unicode.py
  Misc/NEWS.d/next/C_API/2025-05-29-16-56-23.gh-issue-134891.7eKO8U.rst
  Modules/_testcapi/unicode.c
  Objects/unicodeobject.c
Labels: awaiting core review

#135203 [3.13] gh-128605: Revert "Add branch protections for x86_64 in asm_tr…ampoline.S (GH-128606) (GH-135077)" (GH-135175)
  Python/asm_trampoline.S
  Python/perf_jit_trampoline.c
Labels: awaiting review, skip news

#133393 gh-133390: Support SQL keyword completion for sqlite3 CLI
  Doc/whatsnew/3.15.rst
  Lib/sqlite3/__main__.py
  Lib/sqlite3/_completer.py
  Lib/test/test_sqlite3/test_cli.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2025-05-05-03-14-08.gh-issue-133390.AuTggn.rst
  Modules/_sqlite/module.c
Labels: awaiting merge, topic-sqlite3

#135213 [3.14] gh-134160: Use PyModuleDef.m_free in the example module xxlimited (GH-135174)
  Modules/xxlimited.c
Labels: awaiting review, skip news

#135220 [3.14] Docs: Update `PyExc_*` tables in the c-api documentation (GH-131640)
  Doc/c-api/exceptions.rst
  Doc/conf.py
Labels: skip issue, awaiting review, skip news, topic-C-API

#135221 [3.13] Docs: Update `PyExc_*` tables in the c-api documentation (GH-131640)
  Doc/c-api/exceptions.rst
  Doc/conf.py
Labels: skip issue, awaiting review, skip news, topic-C-API

#135192 [3.13] gh-134155: fix AttributeError in email._header_value_parser.get_address (GH-134194)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Library/2025-05-18-23-46-21.gh-issue-134152.30HwbX.rst
Labels: awaiting review

#135191 [3.14] gh-134155: fix AttributeError in email._header_value_parser.get_address (GH-134194)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Library/2025-05-18-23-46-21.gh-issue-134152.30HwbX.rst
Labels: awaiting review

#135194 gh-131798: JIT: Optimize `_CALL_TYPE_1` when the result is known
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-06-05-21-58-30.gh-issue-131798.nt5Ab7.rst
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge

#135232 Revert "gh-133390: Support SQL keyword completion for sqlite3 CLI (#133393)" temporarily
  Doc/whatsnew/3.15.rst
  Lib/sqlite3/__main__.py
  Lib/sqlite3/_completer.py
  Lib/test/test_sqlite3/test_cli.py
  Misc/ACKS
  Misc/NEWS.d/next/Library/2025-05-05-03-14-08.gh-issue-133390.AuTggn.rst
  Modules/_sqlite/module.c
Labels: awaiting core review

#135214 [3.13] gh-134160: Use PyModuleDef.m_free in the example module xxlimited (GH-135174)
  Modules/xxlimited.c
Labels: awaiting review, skip news

#135240 [3.14] gh-134876: Add fallback for when process_vm_readv fails with ENOSYS (GH-134878)
  Misc/ACKS
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-31-10-26-46.gh-issue-134876.8mBGJI.rst
  Python/remote_debug.h
  Python/remote_debugging.c
Labels: awaiting merge

#134671 gh-131798: JIT: Assign type to sliced string/list/tuple
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-25-19-32-15.gh-issue-131798.f5h8aI.rst
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge

#134629 gh-133579: correctly report C curses errors in `_curses_panel`
  Modules/_curses_panel.c
  Modules/clinic/_curses_panel.c.h
Labels: awaiting merge, skip news

#134687 gh-134151 Fix TypeError in email.utils.decode_params() when sorting RFC 2231 continuations
  Lib/email/utils.py
  Lib/test/test_email/test_email.py
  Misc/NEWS.d/next/Library/2025-05-25-23-23-05.gh-issue-134151.13Wwsb.rst
Labels: awaiting merge, needs backport to 3.13, needs backport to 3.14

#135254 gh-134531: refactor `_hashlib` logic for mapping NIDs to EVP_MD objects
  Modules/_hashopenssl.c
Labels: awaiting core review, skip news, type-refactor

#135258 [3.14] gh-134976: document the exception type that can be raised by `s[i]` (GH-134977)
  Doc/library/stdtypes.rst
Labels: docs, awaiting merge, skip news

#135270 [3.14] Update tutorial for new "Copy" button (GH-135007)
  Doc/tutorial/introduction.rst
Labels: docs, skip issue, awaiting review, skip news

#135111 Add compile_commands.json to .gitignore
  .gitignore
Labels: skip issue, awaiting review, skip news

#135271 [3.13] Update tutorial for new "Copy" button (GH-135007)
  Doc/tutorial/introduction.rst
Labels: docs, skip issue, awaiting review, skip news

#135277 gh-135276: Refresh `zipfile.Path` from zipp 3.23
  Lib/test/test_zipfile/_path/_test_params.py
  Lib/test/test_zipfile/_path/test_complexity.py
  Lib/test/test_zipfile/_path/test_path.py
  Lib/test/test_zipfile/_path/write-alpharep.py
  Lib/zipfile/_path/__init__.py
  Lib/zipfile/_path/_functools.py
  Lib/zipfile/_path/glob.py
  Misc/NEWS.d/next/Library/2025-06-08-14-50-34.gh-issue-135276.ZLUhV1.rst
Labels: awaiting core review, needs backport to 3.13, needs backport to 3.14

#135275 gh-135263: Fix typo in token.NAME documentation
  Doc/library/token.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#135280 [3.14] gh-135263: Fix typo in token.NAME documentation (GH-135275)
  Doc/library/token.rst
Labels: docs, awaiting review, skip news

#135281 [3.13] gh-135263: Fix typo in token.NAME documentation (GH-135275)
  Doc/library/token.rst
Labels: docs, awaiting review, skip news

#135279 [3.13] gh-135276: Refresh `zipfile.Path` from zipp 3.23 (GH-135277)
  Lib/test/test_zipfile/_path/_test_params.py
  Lib/test/test_zipfile/_path/test_complexity.py
  Lib/test/test_zipfile/_path/test_path.py
  Lib/test/test_zipfile/_path/write-alpharep.py
  Lib/zipfile/_path/__init__.py
  Lib/zipfile/_path/glob.py
  Misc/NEWS.d/next/Library/2025-06-08-14-50-34.gh-issue-135276.ZLUhV1.rst
Labels: awaiting review

#135245 Use f-strings in csv docs example
  Doc/library/csv.rst
Labels: docs, skip issue, awaiting merge, skip news, 3.13, 3.14, 3.15

#135285 [3.14] Use f-strings in csv docs example (GH-135245)
  Doc/library/csv.rst
Labels: docs, skip issue, awaiting merge, skip news

#28358 gh-89373: Document that error indicator may be set in tp_dealloc
  Doc/c-api/typeobj.rst
  Misc/NEWS.d/next/Documentation/2021-09-15-13-07-25.bpo-45210.RtGk7i.rst
Labels: docs, awaiting merge

#135222 gh-131798: Optimize `_UNARY_INVERT`
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-06-06-01-09-44.gh-issue-131798.1SuxO9.rst
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge

#135289 GH-135287: clangcl PGO builds on Windows fail with `could not open '/GENPROFILE'`
  PCbuild/pyproject.props
Labels: awaiting review, skip news, needs backport to 3.14

#135296 [3.14] GH-135287: clang-cl PGO builds on Windows fail with `could not open '/GENPROFILE'` (GH-135289)
  PCbuild/pyproject.props
Labels: awaiting review, skip news

#134974 [3.14] gh-133968: Add PyUnicodeWriter_WriteASCII() function (#133973)
  Doc/c-api/unicode.rst
  Doc/whatsnew/3.14.rst
  Include/cpython/unicodeobject.h
  Lib/test/test_capi/test_unicode.py
  Misc/NEWS.d/next/C_API/2025-05-13-16-06-46.gh-issue-133968.6alWst.rst
  Modules/_json.c
  Modules/_ssl.c
  Modules/_testcapi/unicode.c
  Objects/genericaliasobject.c
  Objects/typevarobject.c
  Objects/unicodeobject.c
  Objects/unionobject.c
  Parser/asdl_c.py
  Python/Python-ast.c
  Python/context.c
  Python/hamt.c
Labels: awaiting core review

#135002 gh-135001: Explicitly specify the encoding parameter value of `calendar.HTMLCalendar` as 'utf-8'
  Doc/library/calendar.rst
  Lib/calendar.py
  Lib/test/test_calendar.py
Labels: awaiting merge, skip news

#131821 GH-131296: fix clang-cl warning on Windows in socketmodule.c
  Modules/socketmodule.c
Labels: awaiting review, skip news

#135036 gh-116738: Make _heapq module thread-safe
  Lib/test/test_free_threading/test_heapq.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-06-02-13-57-40.gh-issue-116738.ycJsL8.rst
  Modules/_heapqmodule.c
  Modules/clinic/_heapqmodule.c.h
Labels: awaiting merge, topic-free-threading, needs backport to 3.14

#134048 gh-133157: remove usage of `_Py_NO_SANITIZE_UNDEFINED` in `Parser/pegen.c`
  Parser/parser.c
  Parser/pegen.c
  Parser/pegen.h
  Tools/peg_generator/pegen/c_generator.py
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#135318 [3.14] Fix definition of `_Py_RemoteDebug_` symbols for static linking (GH-135146)
  Python/remote_debug.h
Labels: skip issue, awaiting merge, skip news

#135319 [3.14] Fix warnings `set but not used [-Wunused-but-set-variable]` in remote_debug.h (GH-135290)
  Python/remote_debug.h
Labels: skip issue, awaiting merge, skip news

#135334 [3.13] gh-133157: fix UBSan failures in `Parser/pegen.c` (GH-134048)
  Parser/parser.c
  Parser/pegen.c
  Parser/pegen.h
  Tools/peg_generator/pegen/c_generator.py
Labels: awaiting merge, skip news

#135339 [3.14] Docs: fix docstring of `email.message.Message.add_header` (GH-134355)
  Lib/email/message.py
Labels: skip issue, awaiting merge, skip news

#133222 gh-132969: Fix error/hang when shutdown(wait=False) and task exited abnormally
  Lib/concurrent/futures/process.py
  Lib/test/test_concurrent_futures/test_shutdown.py
  Misc/NEWS.d/next/Library/2025-04-30-19-32-18.gh-issue-132969.EagQ3G.rst
Labels: awaiting merge, topic-multiprocessing

#135342 [3.14] gh-118928: Amend sqlite3 execute*() deprecation notes (GH-135163)
  Doc/library/sqlite3.rst
Labels: docs, awaiting review, skip news

#135317 gh-130077: Properly match full soft keywords in the parser
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-06-09-23-57-37.gh-issue-130077.MHknDB.rst
  Parser/pegen.c
Labels: needs backport to 3.12, needs backport to 3.13

#135345 [3.14] gh-128605: Add branch protections for x86_64 in asm_trampoline.S (#128606)
  Python/asm_trampoline.S
  Python/perf_jit_trampoline.c
Labels: skip news

#135348 [3.14] gh-130077: Properly match full soft keywords in the parser (GH-135317)
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-06-09-23-57-37.gh-issue-130077.MHknDB.rst
  Parser/pegen.c
Labels: awaiting review

#134956 [3.14] gh-91048: Reorder result tuple of parse_code_object (GH-134898)
  Lib/test/test_external_inspection.py
  Modules/_remote_debugging_module.c
Labels: awaiting merge, skip news

#135356 gh-135326: Test support of __index__ in random.getrandbits()
  Lib/test/test_random.py
Labels: tests, awaiting merge, skip news, needs backport to 3.14

#135353 [3.13] gh-128605: Add branch protections for x86_64 in asm_trampoline.S (#128606)
  Python/asm_trampoline.S
  Python/perf_jit_trampoline.c
Labels: awaiting merge, skip news

#135322 gh-135321: Changing data type of `size` variable for `BINSTRING` in `_pickle`
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2025-06-10-00-42-30.gh-issue-135321.UHh9jT.rst
  Modules/_pickle.c
Labels: awaiting merge, needs backport to 3.13, needs backport to 3.14

#135209 gh-127545: Replace _Py_ALIGN_AS(V) by _Py_ALIGNED_DEF(N, T)
  Include/Python.h
  Include/cpython/unicodeobject.h
  Include/internal/pycore_interp_structs.h
  Include/object.h
  Include/pymacro.h
  Misc/NEWS.d/next/Build/2024-12-04-10-00-35.gh-issue-127545.t0THjE.rst
Labels: awaiting merge

#135383 [3.13] gh-135321: Always raise a correct exception for BINSTRING argument > 0x7fffffff in pickle (GH-135322)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2025-06-10-00-42-30.gh-issue-135321.UHh9jT.rst
  Modules/_pickle.c
Labels: awaiting review

#135382 [3.14] gh-135321: Always raise a correct exception for BINSTRING argument > 0x7fffffff in pickle (GH-135322)
  Lib/test/pickletester.py
  Misc/NEWS.d/next/Library/2025-06-10-00-42-30.gh-issue-135321.UHh9jT.rst
  Modules/_pickle.c
Labels: awaiting review

#135390 [3.13] GH-135171: Roll back all fixes for GH-127682 as they are not suitable for 3.13
  Lib/test/test_coroutines.py
  Lib/test/test_dis.py
  Lib/test/test_generators.py
  Lib/test/test_genexps.py
  Lib/test/test_listcomps.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-06-11-14-09-12.gh-issue-135171.VUdivl.rst
  Python/compile.c
Labels: awaiting core review

#135392 [3.12] gh-132415: Use shutil.which() in missing_compiler_executable() (GH-132906)
  Lib/test/support/__init__.py
Labels: awaiting review, skip news

#135393 [3.12] gh-132415: Update vendored setuptools in ``Lib/test/wheeldata` (GH-132887)
  Lib/test/support/__init__.py
  Lib/test/wheeldata/setuptools-67.6.1-py3-none-any.whl
  Lib/test/wheeldata/setuptools-79.0.1-py3-none-any.whl
Labels: awaiting core review, skip news

#135396 [3.11] gh-135374: Update the bundled copy of setuptools to 79.0.1
  Lib/ensurepip/__init__.py
  Lib/ensurepip/_bundled/setuptools-65.5.0-py3-none-any.whl
  Lib/ensurepip/_bundled/setuptools-79.0.1-py3-none-any.whl
  Misc/NEWS.d/next/Library/2025-06-11-17-38-16.gh-issue-135374.eqRcTc.rst
Labels: awaiting core review

#135398 [3.10] gh-135374: Update the bundled copy of setuptools to 79.0.1
  Lib/ensurepip/__init__.py
  Lib/ensurepip/_bundled/setuptools-65.5.0-py3-none-any.whl
  Lib/ensurepip/_bundled/setuptools-79.0.1-py3-none-any.whl
  Misc/NEWS.d/next/Library/2025-06-11-17-38-16.gh-issue-135374.eqRcTc.rst
Labels: awaiting core review

#135397 [3.9] gh-135374: Update the bundled copy of setuptools to 79.0.1
  Lib/ensurepip/__init__.py
  Lib/ensurepip/_bundled/setuptools-58.1.0-py3-none-any.whl
  Lib/ensurepip/_bundled/setuptools-79.0.1-py3-none-any.whl
  Misc/NEWS.d/next/Library/2025-06-11-17-47-19.gh-issue-135374.eqRcTc.rst
Labels: awaiting core review

#133958 gh-134939: Add the interpreters Module
  .github/CODEOWNERS
  Doc/library/concurrency.rst
  Doc/library/concurrent.interpreters.rst
  Doc/library/concurrent.rst
  Doc/library/python.rst
  Doc/whatsnew/3.14.rst
  Lib/concurrent/futures/interpreter.py
  Lib/concurrent/interpreters/__init__.py
  Lib/concurrent/interpreters/_crossinterp.py
  Lib/concurrent/interpreters/_queues.py
  Lib/test/support/channels.py
  Lib/test/test__interpchannels.py
  Lib/test/test_concurrent_futures/test_interpreter_pool.py
  Lib/test/test_interpreters/test_api.py
  Lib/test/test_interpreters/test_channels.py
  Lib/test/test_interpreters/test_lifecycle.py
  Lib/test/test_interpreters/test_queues.py
  Lib/test/test_interpreters/test_stress.py
  Lib/test/test_interpreters/utils.py
  Lib/test/test_sys.py
  Lib/test/test_threading.py
  Lib/test/test_types.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2025-05-30-09-46-21.gh-issue-134939.Pu3nnm.rst
  Modules/_interpchannelsmodule.c
  Modules/_interpqueuesmodule.c
  Modules/_testinternalcapi.c
  Python/crossinterp_exceptions.h
Labels: awaiting core review, needs backport to 3.14

#116532 Fix format of dataclasses' `unsafe_hash` default value
  Doc/library/dataclasses.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#135416 [3.14] Fix presentation of dataclasses' `unsafe_hash` default value (GH-116532)
  Doc/library/dataclasses.rst
Labels: docs, skip issue, awaiting review, skip news

#135419 [3.14] gh-128627: Fix iPad detection in wasm-gc (GH-135388)
  Python/emscripten_trampoline.c
Labels: awaiting merge, skip news
