Repository python/cpython, pull requests merged in 2025-10, with the labels that each got.

#139411 gh-92266: Update pre-commit
  .pre-commit-config.yaml
  Tools/build/.ruff.toml
  Tools/clinic/.ruff.toml
  Tools/peg_generator/.ruff.toml
Labels: awaiting core review, skip news, needs backport to 3.13, needs backport to 3.14

#139450 Fix typo in tracemalloc.c
  Python/tracemalloc.c
Labels: skip issue, awaiting merge, skip news

#139454 gh-138013: Split BufferedIO tests from test_io.test_general
  Lib/test/test_io/test_bufferedio.py
  Lib/test/test_io/test_general.py
Labels: tests, awaiting merge, skip news

#139073 gh-116946: Remove gc-support from some immutable types
  Modules/_bz2module.c
  Modules/_lzmamodule.c
  Modules/_ssl.c
  Modules/_threadmodule.c
  Modules/hmacmodule.c
Labels: awaiting merge, skip news

#139469 gh-139210: Move gh-139210 patch NEWS file to correct section
  Misc/NEWS.d/next/Library/2025-09-21-15-58-57.gh-issue-139210.HGbMvz.rst
Labels: docs, awaiting core review, skip news

#124107 gh-123828: fix data raceing for _waiting_release method in _interpchannelsmodule.c
  Lib/test/test__interpchannels.py
  Modules/_interpchannelsmodule.c
Labels: awaiting merge, skip news

#139488 gh-139487: doc(enum): add missing imports for standalone doctest examples
  Doc/library/enum.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#139494 [3.13] gh-139487: add missing imports for standalone doctest `Enum` examples (GH-139488)
  Doc/library/enum.rst
Labels: docs, awaiting review, skip news

#139493 [3.14] gh-139487: add missing imports for standalone doctest `Enum` examples (GH-139488)
  Doc/library/enum.rst
Labels: docs, awaiting merge, skip news

#139507 [3.13] gh-135329: Use longer timeout in pyrepl test_repl_eio() (#139503)
  Lib/test/test_pyrepl/test_unix_console.py
Labels: tests, awaiting core review, skip news

#135945 gh-135944: Add a "Runtime Components" Section to the Execution Model Docs
  Doc/reference/executionmodel.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#139502 gh-77476: Remove urllib HTTP test
  Lib/test/test_urllib2net.py
Labels: tests, awaiting merge, skip news

#139513 Remove @tiran from CODEOWNERS
  .github/CODEOWNERS
Labels: skip issue, awaiting merge, skip news

#139505 gh-139504: Catch BrokenPipeError in ssl test_client_sigalgs_mismatch()
  Lib/test/test_ssl.py
Labels: tests, awaiting merge, skip news, topic-SSL

#139499 gh-55258: Reenable support test_get_original_stdout()
  Lib/test/test_support.py
Labels: tests, awaiting core review, skip news

#139477 gh-139322: Remove redundant `test_os.Win32ErrorTests`
  Lib/test/test_os/test_os.py
  Lib/test/test_os/test_windows.py
Labels: tests, awaiting merge, skip news

#139498 gh-139322: Reenable test_os.test_getlogin()
  Lib/test/test_os/test_os.py
  Misc/NEWS.d/next/Library/2025-10-02-15-45-08.gh-issue-139322.rouPGj.rst
  Modules/posixmodule.c
Labels: tests, awaiting core review, skip news

#139522 [3.14] gh-139495: Fix `hashlib.file_digest()` versionchanged description of `BlockingIOError` (GH-139496)
  Doc/library/hashlib.rst
Labels: docs, awaiting merge, skip news

#139528 [3.13] gh-139495: Fix `hashlib.file_digest()` versionchanged description of `BlockingIOError` (GH-139496)
  Doc/library/hashlib.rst
Labels: docs, awaiting merge, skip news

#137933 gh-137840: Implement PEP 728 (closed and extra_items in typing.TypedDict)
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2025-08-18-07-10-55.gh-issue-137840.9b7AnG.rst
Labels: awaiting merge

#139538 gh-105987: unskip `test_issue105987` from `test_asyncio.test_eager_task_factory`
  Lib/test/test_asyncio/test_eager_task_factory.py
Labels: tests, topic-asyncio, awaiting core review, skip news, needs backport to 3.14

#139524 gh-139525: Don't specialize functions which have a modified vectorcall
  Lib/test/test_opcache.py
  Modules/_testinternalcapi.c
  Python/specialize.c
Labels: awaiting merge, skip news

#139154 gh-137638: Use macos-15-intel in GitHub Actions
  .github/actionlint.yaml
  .github/workflows/build.yml
  .github/workflows/jit.yml
  .github/workflows/reusable-macos.yml
  .github/workflows/tail-call.yml
Labels: awaiting merge, skip news, needs backport to 3.10, needs backport to 3.11, needs backport to 3.12, needs backport to 3.13, needs backport to 3.14

#139118 [3.14] Document `Py_AddPendingCall()` change with subinterpreters in 3.12 (GH-139117)
  Doc/c-api/init.rst
Labels: docs, sprint, skip issue, awaiting review, skip news, topic-subinterpreters, topic-C-API

#139539 [3.14] gh-105987: unskip `test_issue105987` from `test_asyncio.test_eager_task_factory` (GH-139538)
  Lib/test/test_asyncio/test_eager_task_factory.py
Labels: tests, topic-asyncio, awaiting merge, skip news

#139508 [3.14] GH-123299: Copyedit 3.14 What's New: Other Language Changes (GH-139425)
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#139548 gh-133210: Fix `test_types` with `--without-doc-strings`
  Lib/test/test_types.py
Labels: tests, awaiting merge, skip news

#136831 Replace workflow with project automations
  .github/workflows/project-updater.yml
Labels: skip issue, awaiting merge, skip news, infra

#139302 gh-138489: Add missing `build-details.json` step for building wasm
  Makefile.pre.in
  Misc/NEWS.d/next/Build/2025-09-24-13-59-26.gh-issue-138489.1AcuZM.rst
Labels: awaiting merge

#139555 [3.14] GH-123299: Copyedit 3.14 What's New: New and Improved Modules (GH-139530)
  Doc/library/compression.rst
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#139341 gh-139308: Skip test_special_chars_csh on NetBSD due to csh variable expansion issue
  Lib/test/test_venv.py
Labels: type-bug, tests, awaiting merge, skip news, needs backport to 3.13, OS-netbsd, needs backport to 3.14

#139236 gh-101100: Fix some Sphinx reference warnings in whatsnew/2.6.rst
  Doc/whatsnew/2.6.rst
Labels: docs, sprint, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#139564 gh-138703: clarify data buffer requirement of `asyncio.StreamWriter.write`
  Doc/library/asyncio-stream.rst
  Lib/asyncio/selector_events.py
Labels: docs, topic-asyncio, awaiting core review, skip news, needs backport to 3.13, needs backport to 3.14

#139571 [3.13] gh-138703: clarify data buffer requirement of `asyncio.StreamWriter.write` (GH-139564)
  Doc/library/asyncio-stream.rst
  Lib/asyncio/selector_events.py
Labels: topic-asyncio, awaiting merge, skip news

#139187 gh-138558: Improve description of `Interpolation.expression` in library docs
  Doc/library/string.templatelib.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.14

#139562 gh-139573: Update Android to OpenSSL 3.0.18
  Android/android.py
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#139584 [3.13] gh-139573: Update Android to OpenSSL 3.0.18 (GH-139562)
  Android/android.py
Labels: awaiting core review, skip news

#139585 [3.13] gh-139573: Update OpenSSL in CI (GH-139577)
  .github/workflows/build.yml
  .github/workflows/reusable-ubuntu.yml
  Doc/using/configure.rst
  Tools/ssl/multissltests.py
Labels: awaiting merge, skip news, topic-SSL

#139241 GH-137218: Fix unnecessary recompile of `Programs/_freeze_module`
  Makefile.pre.in
  configure
  configure.ac
Labels: awaiting merge, skip news

#139579 [3.14] gh-138558: Improve description of ``Interpolation.expression`` (GH-139187)
  Doc/library/string.templatelib.rst
Labels: docs, awaiting merge, skip news

#139581 [3.14] gh-139573: Update Android to OpenSSL 3.0.18 (GH-139562)
  Android/android.py
Labels: awaiting merge, skip news

#139583 [3.14] gh-139573: Update OpenSSL in CI (GH-139577)
  .github/workflows/build.yml
  .github/workflows/reusable-ubuntu.yml
  Doc/using/configure.rst
  Modules/_ssl_data_35.h
  Tools/ssl/multissltests.py
Labels: awaiting review, skip news, topic-SSL

#139586 [3.14] gh-139573: Update Windows builds to use OpenSSL 3.0.18 (GH-139574)
  Misc/NEWS.d/next/Windows/2025-10-04-12-18-45.gh-issue-139573.EO9kVB.rst
  Misc/externals.spdx.json
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: awaiting merge, topic-SSL

#139582 gh-139573: Update OpenSSL version used in iOS builds
  Apple/__main__.py
Labels: awaiting core review, skip news, needs backport to 3.14

#139589 [3.14] gh-139573: Update OpenSSL version used in iOS builds (GH-139582)
  Apple/__main__.py
Labels: awaiting review, skip news

#139552 gh-139310: skip `test_aead_aes_gcm` for Linux kernel between 6.16.0 and 6.17.x
  Lib/test/support/__init__.py
  Lib/test/test_socket.py
Labels: awaiting merge, skip news

#139593 [3.13] gh-139310: skip `test_aead_aes_gcm` for Linux kernel between 6.16.0 and 6.17.x (GH-139552)
  Lib/test/support/__init__.py
  Lib/test/test_socket.py
Labels: awaiting merge, skip news

#139594 [3.14] gh-139310: skip `test_aead_aes_gcm` for Linux kernel between 6.16.0 and 6.17.x (GH-139552)
  Lib/test/support/__init__.py
  Lib/test/test_socket.py
Labels: awaiting merge, skip news

#139526 gh-118767: remove bool(NotImplemented) from pending-removal document
  Doc/deprecations/pending-removal-in-future.rst
Labels: docs, awaiting merge, skip news

#139599 [3.14] gh-118767: Remove ``bool(NotImplemented)`` from pending-removal document (GH-139526)
  Doc/deprecations/pending-removal-in-future.rst
Labels: docs, awaiting merge, skip news

#138312 [3.14] gh-138130: Fix return value of libc_ver() on Emscripten (GH-138132)
  Lib/platform.py
  Lib/test/test_platform.py
Labels: awaiting merge, skip news

#139606 [3.14] gh-139400: Make sure that parent parsers outlive their subparsers in `pyexpat` (GH-139403)
  Lib/test/test_pyexpat.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-29-00-01-28.gh-issue-139400.X2T-jO.rst
  Modules/pyexpat.c
Labels: awaiting merge

#139610 gh-70765: fix an HTTP/0.9 flaky test post GH-139514
  Lib/test/test_httpservers.py
Labels: tests, awaiting core review, skip news

#139601 Replace ambiguous word "pound" by "hash" in `difflib` docs
  Doc/library/difflib.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#139617 [3.13] Replace ambiguous word "pound" by "hash" in `difflib` docs (GH-139601)
  Doc/library/difflib.rst
Labels: docs, skip issue, awaiting merge, skip news

#139615 [3.14] GH-123299: Copyedit 3.14 What's New: New Features (GH-139543)
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#139618 GH-123299: Copyedit 3.14 What's New: Trivia
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.14

#139619 gh-105812: Use the ``:deco:`` role in place of manual decorator markup
  Doc/library/collections.abc.rst
  Doc/library/dataclasses.rst
  Doc/library/functools.rst
  Doc/library/typing.rst
  Doc/library/warnings.rst
  Doc/reference/datamodel.rst
  Doc/whatsnew/2.7.rst
  Doc/whatsnew/3.10.rst
  Misc/NEWS.d/3.10.0b1.rst
  Misc/NEWS.d/3.11.0a1.rst
  Misc/NEWS.d/3.11.0b1.rst
  Misc/NEWS.d/3.14.0a1.rst
  Misc/NEWS.d/next/Library/2025-08-27-17-05-36.gh-issue-138010.ZZJmPL.rst
Labels: docs, awaiting merge, needs backport to 3.13, needs backport to 3.14

#139626 [3.14] GH-123299: Copyedit 3.14 What's New: Trivia (GH-139618)
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#139645 [3.13] gh-139624: Skip problematic locales on AIX in test_date_locale2 (GH-139625)
  Lib/test/test_strptime.py
Labels: tests, awaiting review, skip news

#139647 gh-139646: fix typo in pickletools error message
  Lib/pickletools.py
  Lib/test/test_pickletools.py
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#139643 gh-116488: Mention dict.get usage in data structures tutorial
  Doc/tutorial/datastructures.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#139608 [3.13] gh-139400: Make sure that parent parsers outlive their subparsers in `pyexpat` (GH-139403)
  Lib/test/test_pyexpat.py
  Misc/NEWS.d/next/Security/2025-09-29-00-01-28.gh-issue-139400.X2T-jO.rst
  Modules/pyexpat.c
Labels: awaiting merge

#139654 gh-133210: Fix `test_pydoc` without docstrings
  Lib/test/test_pydoc/test_pydoc.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#139664 gh-139400: Move news item from section "Core and Builtins" to section "Security" (GH-139606)
  Misc/NEWS.d/next/Security/2025-09-29-00-01-28.gh-issue-139400.X2T-jO.rst
Labels: docs, skip news

#139663 [3.14] gh-139400: Move NEWS item from section "Core and Builtins" to section "Security" (GH-139606)
  Misc/NEWS.d/next/Security/2025-09-29-00-01-28.gh-issue-139400.X2T-jO.rst
Labels: docs, awaiting merge, skip news

#139651 gh-133210: Fix `test_inspect` without docstrings
  Lib/test/test_inspect/test_inspect.py
Labels: tests, awaiting merge, skip news

#138855 gh-138854: Skip test_script_shadowing_stdlib_cwd_failure on AIX
  Lib/test/test_import/__init__.py
Labels: type-bug, tests, awaiting merge, skip news, topic-importlib, OS-unsupported, needs backport to 3.13, needs backport to 3.14

#139675 [3.13] gh-138854: Skip test_script_shadowing_stdlib_cwd_failure on AIX (GH-138855)
  Lib/test/test_import/__init__.py
Labels: type-bug, awaiting merge, skip news, topic-importlib

#139658 PEP 765: What's New warnings filter suggestions
  Doc/whatsnew/3.14.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.14

#139676 [3.14] Add warnings filter suggestions to PEP 765 entry in What's New (GH-139658)
  Doc/whatsnew/3.14.rst
Labels: docs, skip issue, awaiting merge, skip news

#139612 [3.11] gh-139400: Make sure that parent parsers outlive their subparsers in `pyexpat` (GH-139403)
  Lib/test/test_pyexpat.py
  Misc/NEWS.d/next/Security/2025-09-29-00-01-28.gh-issue-139400.X2T-jO.rst
  Modules/pyexpat.c
Labels: awaiting merge

#139613 [3.10] gh-139400: Make sure that parent parsers outlive their subparsers in `pyexpat` (GH-139403)
  Lib/test/test_pyexpat.py
  Misc/NEWS.d/next/Security/2025-09-29-00-01-28.gh-issue-139400.X2T-jO.rst
  Modules/pyexpat.c
Labels: awaiting merge

#139681 [3.13] gh-139573: Update macOS installer to use OpenSSL 3.0.18 (GH-139575)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-10-04-12-29-31.gh-issue-139573.vVpHaP.rst
Labels: awaiting merge, topic-SSL

#139684 [3.13] gh-124111: Update macOS installer to use Tcl/Tk 8.6.17. (GH-139682)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-10-06-23-56-36.gh-issue-124111.KOlBvs.rst
Labels: awaiting merge

#139683 [3.14] gh-124111: Update macOS installer to use Tcl/Tk 8.6.17. (GH-139682)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-10-06-23-56-36.gh-issue-124111.KOlBvs.rst
Labels: awaiting merge

#139631 GH-123299: Announce final release in What's New in Python 3.14
  Doc/whatsnew/3.13.rst
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.14

#139662 [3.12] gh-139312: Update bundled libexpat to 2.7.3 (GH-139319)
  Misc/NEWS.d/next/Library/2025-09-25-07-33-43.gh-issue-139312.ygE8AC.rst
  Misc/sbom.spdx.json
  Modules/expat/expat.h
  Modules/expat/internal.h
  Modules/expat/refresh.sh
  Modules/expat/xmlparse.c
  Modules/expat/xmlrole.h
Labels: awaiting core review

#139614 [3.9] gh-139400: Make sure that parent parsers outlive their subparsers in `pyexpat` (GH-139403)
  Lib/test/test_pyexpat.py
  Misc/NEWS.d/next/Security/2025-09-29-00-01-28.gh-issue-139400.X2T-jO.rst
  Modules/pyexpat.c
Labels: awaiting merge

#139437 gh-139436: Remove ``dist-pdf`` from the docsbuild-scripts rebuild target
  Doc/Makefile
Labels: docs, skip news, needs backport to 3.10, needs backport to 3.11, needs backport to 3.12, needs backport to 3.13, needs backport to 3.14

#139055 [3.9] gh-138998: Upgrade vendored expat to 2.7.2 (GH-138999)
  Misc/NEWS.d/next/Library/2025-09-16-19-05-29.gh-issue-138998.URl0Y_.rst
  Modules/expat/expat.h
  Modules/expat/expat_external.h
  Modules/expat/internal.h
  Modules/expat/refresh.sh
  Modules/expat/xmlparse.c
  Modules/expat/xmlrole.h
  Modules/expat/xmltok.c
  Modules/expat/xmltok.h
Labels: awaiting merge, release-blocker

#139050 [3.14] gh-128639: Don't assume one thread in subinterpreter finalization with fixed daemon thread support (GH-134606)
  Lib/test/test_interpreters/test_api.py
  Lib/test/test_interpreters/test_lifecycle.py
  Lib/test/test_threading.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-08-12-52-47.gh-issue-128640.9nbh9z.rst
  Programs/_testembed.c
  Python/pylifecycle.c
Labels: awaiting merge, topic-subinterpreters

#139701 [3.14] gh-139516: Fix lambda colon start format spec in f-string in tokenizer (GH-139657)
  Lib/test/test_fstring.py
  Lib/test/test_tokenize.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-10-06-13-15-26.gh-issue-139516.d9Pkur.rst
  Parser/lexer/lexer.c
  Parser/lexer/state.h
Labels: awaiting review

#138702 [3.14] gh-136234: Fix `SelectorSocketTransport.writelines` to be robust to connection loss (GH-136743)
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Misc/NEWS.d/next/Library/2025-07-17-16-12-23.gh-issue-136234.VmTxtj.rst
Labels: type-bug, topic-asyncio, awaiting core review, needs backport to 3.13

#137416 [3.14] gh-137238: Fix data race in `_Py_slot_tp_getattr_hook` (gh-137240)
  Objects/typeobject.c
  Python/specialize.c
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting core review, skip news, topic-free-threading

#138916 [3.14] gh-137017: Ensure `Thread.is_alive()` only returns False after the underlying OS thread exits (gh-137315)
  Misc/NEWS.d/next/Library/2025-08-01-23-11-25.gh-issue-137017.0yGcNc.rst
  Modules/_threadmodule.c
Labels: awaiting merge

#139260 [3.14] gh-139208: Fix regrtest --fast-ci --verbose (GH-139240)
  Lib/test/libregrtest/cmdline.py
  Lib/test/test_regrtest.py
  Misc/NEWS.d/next/Tests/2025-09-22-15-40-09.gh-issue-139208.Tc13dl.rst
Labels: awaiting merge

#137460 [3.14] gh-58124: Avoid CP_UTF8 in UnicodeDecodeError (GH-137415)
  Lib/test/test_codecs.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-08-05-17-22-24.gh-issue-58124.q1__53.rst
  Objects/unicodeobject.c
  Python/codecs.c
Labels: awaiting merge

#137149 [3.14] gh-136278: Document codecs.escape_encode() and codecs.escape_decode() (GH-136314)
  Doc/library/codecs.rst
Labels: docs, awaiting review, skip news

#137080 [3.14] Fix docs for Queue.shutdown (gh-137028)
  Doc/library/asyncio-queue.rst
  Doc/library/queue.rst
  Lib/asyncio/queues.py
  Lib/queue.py
Labels: skip issue, awaiting review, skip news

#137730 [3.14] gh-137400: Fix thread-safety issues when profiling all threads (gh-137518)
  Include/internal/pycore_ceval.h
  Include/internal/pycore_interp_structs.h
  Lib/test/test_free_threading/test_monitoring.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-08-07-09-52-19.gh-issue-137400.AK1dy-.rst
  Python/bytecodes.c
  Python/ceval.c
  Python/generated_cases.c.h
  Python/instrumentation.c
  Python/legacy_tracing.c
  Python/pystate.c
  Python/sysmodule.c
Labels: awaiting core review

#139711 [3.14] gh-139698: Fix typo in What's New 3.14 (GH-139699)
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#137256 [3.14] gh-137239: Add *_max functions to heapq.__all__ (gh-137241)
  Lib/heapq.py
  Misc/NEWS.d/next/Library/2025-07-30-17-42-36.gh-issue-137239.qSpj32.rst
Labels: awaiting merge

#137437 [3.14] gh-136823: Update documentation on excluded headers in Python.h (GH-136824)
  Doc/extending/extending.rst
  Include/Python.h
Labels: sprint, awaiting merge, skip news

#138914 [3.14] gh-138902: Fix generator send arg name (GH-138905)
  Objects/genobject.c
Labels: awaiting merge, skip news

#138742 [3.14] gh-138008: Fix segfaults in _ctypes due to invalid argtypes (GH-138285)
  Lib/test/test_ctypes/test_prototypes.py
  Misc/NEWS.d/next/Library/2025-08-31-09-06-49.gh-issue-138008.heOvsU.rst
  Modules/_ctypes/_ctypes.c
Labels: awaiting review

#139644 [3.14] gh-139624: Skip problematic locales on AIX in test_date_locale2 (GH-139625)
  Lib/test/test_strptime.py
Labels: tests, awaiting review, skip news

#138834 [3.14] gh-138661: fix data race in `PyCode_Addr2Line` (GH-138664)
  Include/internal/pycore_code.h
  Objects/codeobject.c
  Python/traceback.c
Labels: awaiting merge, skip news, topic-free-threading

#137245 [3.14] gh-135444: fix `asyncio.DatagramTransport.sendto` to account for datagram header size when data cannot be sent (GH-135445)
  Lib/asyncio/proactor_events.py
  Lib/asyncio/selector_events.py
  Lib/test/test_asyncio/test_proactor_events.py
  Lib/test/test_asyncio/test_selector_events.py
  Misc/NEWS.d/next/Library/2025-06-16-12-37-02.gh-issue-135444.An2eeA.rst
Labels: type-bug, topic-asyncio, awaiting merge

#139693 [3.13] gh-139436: Remove ``dist-pdf`` from the docs archives rebuild target (GH-139437)
  Doc/Makefile
Labels: awaiting review, skip news

#137656 [3.14] gh-131885: Use positional-only markers for ``max()`` and ``min()`` (GH-131868)
  Doc/library/functions.rst
Labels: docs, awaiting merge, skip news

#137394 [3.14] gh-137390: Add missing line continuation character in configure.ac (GH-137391)
  configure.ac
Labels: awaiting merge, skip news

#137363 [3.14] gh-122450: Expand documentation for ``Rational`` and ``Fraction`` (GH-136800)
  Doc/library/fractions.rst
  Doc/library/numbers.rst
  Lib/numbers.py
Labels: awaiting merge, skip news

#137272 [3.14] gh-137025: Include ``python.worker.mjs`` in the Emscripten Web Example (GH-137236)
  Makefile.pre.in
Labels: awaiting merge, skip news

#139705 [3.14] gh-75989: TarFile.extractall and TarFile.extract now overwrite symlinks when extracting hardlinks (GH-137316)
  Lib/tarfile.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Library/2025-08-01-23-52-49.gh-issue-75989.5aYXNJ.rst
Labels: awaiting review

#139112 [3.14] gh-135729: Store reference to globals in `Interpreter._decref` (GH-139104)
  Lib/concurrent/interpreters/__init__.py
  Lib/test/test_interpreters/test_api.py
  Misc/NEWS.d/next/Library/2025-09-18-05-32-18.gh-issue-135729.8AmMza.rst
Labels: sprint, awaiting review

#139649 [3.14] gh-139646: fix typo in `pickletools` error message (GH-139647)
  Lib/pickletools.py
  Lib/test/test_pickletools.py
Labels: awaiting review, skip news

#139650 [3.13] gh-139646: fix typo in `pickletools` error message (GH-139647)
  Lib/pickletools.py
  Lib/test/test_pickletools.py
Labels: awaiting review, skip news

#139471 [3.14] gh-139327: fix some reference leaks in `sqlite3` error branches (GH-139328)
  Modules/_sqlite/connection.c
  Modules/_sqlite/cursor.c
Labels: awaiting merge, skip news

#139347 [3.14] gh-115119: Defer `--with-system-libmpdec` removal to 3.16 (GH-139318)
  Doc/using/configure.rst
Labels: docs, awaiting core review, skip news

#139229 [3.14] `Doc/library/zoneinfo.rst`: Fix typo (GH-139190)
  Doc/library/zoneinfo.rst
Labels: docs, skip issue, awaiting review, skip news

#139099 [3.14] Remove unmatched closing parenthesis (GH-139082)
  Doc/c-api/unicode.rst
Labels: docs, skip issue, awaiting review, skip news

#137536 [3.14] gh-130102: drop "require numeric arguments" from pow() docs (GH-137456)
  Doc/library/functions.rst
Labels: docs, awaiting review, skip news

#137962 [3.14] Update the dbm documentation (GH-137919)
  Doc/library/dbm.rst
  Doc/whatsnew/3.13.rst
Labels: docs, skip issue, awaiting merge, skip news

#139042 [3.14] gh-129368: In PyRun C API docs, clarify what a "start token" is (GH-129935)
  Doc/c-api/veryhigh.rst
Labels: docs, awaiting merge, skip news

#137543 [3.14] Bump mypy to 1.17.1 (GH-137542)
  Tools/requirements-dev.txt
Labels: skip issue, awaiting review, skip news

#138926 [3.14] gh-138779: Use the dev_t converter for st_rdev (GH-138780)
  Misc/NEWS.d/next/Library/2025-09-11-11-09-28.gh-issue-138779.TNZnLr.rst
  Modules/posixmodule.c
Labels: awaiting review

#139062 [3.14] gh-138736: Fix sqlite3.Connection.blobopen 'row' parameter type and naming (#138738)
  Doc/library/sqlite3.rst
  Modules/_sqlite/clinic/connection.c.h
  Modules/_sqlite/connection.c
Labels: awaiting core review, skip news

#137305 [3.14] gh-137273: Fix debug assertion failure in locale.setlocale() on Windows (GH-137300)
  Lib/test/test_locale.py
  Misc/NEWS.d/next/Library/2025-08-01-15-07-59.gh-issue-137273.4V8Xmv.rst
  Modules/_localemodule.c
Labels: awaiting merge

#137381 [3.14] gh-136520: Clarify docs for _pack_ & _align_ (GH-137036)
  Doc/library/ctypes.rst
Labels: docs, awaiting review, skip news

#137365 [3.14] gh-81325: Support path-like objects with streaming TarFile (GH-137188)
  Lib/tarfile.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Library/2025-07-28-23-11-29.gh-issue-81325.jMJFBe.rst
Labels: awaiting merge

#137506 [3.14] gh-137044: Support large limit values in getrlimit() and setrlimit() (GH-137338)
  Lib/test/test_resource.py
  Misc/NEWS.d/next/Library/2025-08-03-13-16-39.gh-issue-137044.0hPVL_.rst
  Modules/clinic/resource.c.h
  Modules/resource.c
Labels: awaiting review

#139718 [3.14] GH-92266: Remove embedded tabs from ``c-analyzer/cpython/_parser.py`` (GH-137622)
  Tools/c-analyzer/cpython/_parser.py
Labels: awaiting merge, skip news

#138575 [3.14] gh-116738: make `cProfile` module thread-safe (GH-138229)
  Lib/test/test_free_threading/test_cprofile.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-08-28-09-29-46.gh-issue-116738.yLZJpV.rst
  Modules/_lsprof.c
  Modules/clinic/_lsprof.c.h
Labels: awaiting merge, topic-free-threading

#139221 Doc: Improve clarity for subinterpreters in What's New in 3.14
  Doc/whatsnew/3.14.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.14

#137832 [3.14] gh-131178: Add tests for `site` command-line interface (GH-133582)
  Lib/test/test_site.py
Labels: tests, awaiting merge, skip news

#139661 [3.9] gh-135661: Fix CDATA section parsing in HTMLParser (GH-135665) (GH-137774)
  Lib/html/parser.py
  Lib/test/test_htmlparser.py
  Misc/NEWS.d/next/Security/2025-06-18-13-34-55.gh-issue-135661.NZlpWf.rst
Labels: type-security, awaiting merge

#139714 [3.10] gh-139700: Check consistency of the zip64 end of central directory record (GH-139702) (GH-139708)
  Lib/test/test_zipfile.py
  Lib/zipfile.py
  Misc/NEWS.d/next/Security/2025-10-07-19-31-34.gh-issue-139700.vNHU1O.rst
Labels: type-security, awaiting review

#139441 [3.14] gh-139283: correctly handle `size` limit in `cursor.fetchmany()` (GH-139296)
  Doc/library/sqlite3.rst
  Lib/test/test_sqlite3/test_dbapi.py
  Misc/NEWS.d/next/Security/2025-09-24-13-39-56.gh-issue-139283.jODz_q.rst
  Modules/_sqlite/clinic/cursor.c.h
  Modules/_sqlite/cursor.c
  Modules/_sqlite/cursor.h
Labels: awaiting merge

#139722 [3.14] Doc: Improve clarity for subinterpreters in What's New in 3.14 (GH-139221)
  Doc/whatsnew/3.14.rst
Labels: docs, skip issue, awaiting review, skip news

#139406 [3.14] gh-78319: Fix implementation of IMAP APPEND UTF8 (GH-9436)
  Lib/imaplib.py
  Lib/test/test_imaplib.py
  Misc/NEWS.d/next/Library/2023-02-13-20-34-52.gh-issue-78319.V1zzed.rst
Labels: awaiting review, topic-email

#139029 [3.14] gh-134466: Don't run when termios is inaccessible (GH-138911)
  Lib/_pyrepl/fancy_termios.py
  Lib/_pyrepl/unix_console.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-15-14-04-56.gh-issue-134466.yR4fYW.rst
Labels: awaiting merge, topic-repl

#138506 [3.14] gh-137920: Fix semantically relevant typo in curses.window.attron (#137940)
  Doc/library/curses.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: awaiting merge, skip news

#137660 [3.14] gh-126008: Improve docstrings for Tkinter cget and configure methods (GH-133303)
  Lib/tkinter/__init__.py
  Lib/tkinter/ttk.py
Labels: awaiting merge, skip news

#137419 [3.14] gh-123441: Correct the supported languages of the iso-8859-4 codec (GH-137034)
  Doc/library/codecs.rst
Labels: docs, awaiting review, skip news

#139442 [3.14] gh-63161: Add more tests for source encoding (GH-139440)
  Lib/test/test_source_encoding.py
  Lib/test/test_tokenize.py
Labels: tests, awaiting review, skip news

#137053 [3.14] Touch up `Setup.local` handling in `Tools/wasm/wasi` (GH-137051)
  Tools/wasm/wasi/__main__.py
Labels: skip issue, awaiting merge, skip news, OS-wasi

#138777 [3.14] gh-138432: Improved invalid path checking in zoneinfo.reset_tzpath() (GH-138433)
  Lib/test/test_zoneinfo/test_zoneinfo.py
  Lib/zoneinfo/_tzpath.py
  Misc/NEWS.d/next/Library/2025-09-03-15-20-10.gh-issue-138432.RMc7UX.rst
Labels: awaiting review

#138629 [3.14] gh-105487: Fix `__dir__` entries of `GenericAlias` (GH-138578)
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-06-13-53-33.gh-issue-105487.a43YaY.rst
  Objects/genericaliasobject.c
Labels: awaiting merge

#139706 [3.14] gh-139700: Check consistency of the zip64 end of central directory record (GH-139702)
  Lib/test/test_zipfile/test_core.py
  Lib/zipfile/__init__.py
  Misc/NEWS.d/next/Security/2025-10-07-19-31-34.gh-issue-139700.vNHU1O.rst
Labels: type-security, awaiting review

#138212 [3.14] Drop explicit tool installation in the dev container (GH-138211)
  .devcontainer/devcontainer.json
Labels: skip issue, skip news

#139725 gh-79315: Add Include/cpython/marshal.h header
  Include/cpython/marshal.h
  Include/marshal.h
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
Labels: awaiting core review, skip news

#139726 [3.13] gh-139516: Fix lambda colon start format spec in f-string in t…
  Lib/test/test_fstring.py
  Lib/test/test_tokenize.py
  Misc/NEWS.d/next/Core and Builtins/2025-10-06-13-15-26.gh-issue-139516.d9Pkur.rst
  Parser/lexer/lexer.c
  Parser/lexer/state.h
Labels: awaiting review

#139731 gh-79315: Remove Include/pylock.h and Include/monitoring.h
  Include/Python.h
  Include/cpython/monitoring.h
  Include/cpython/pylock.h
  Include/monitoring.h
  Include/pylock.h
  Makefile.pre.in
  Modules/_testcapi/monitoring.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: awaiting core review, skip news

#137250 [3.14] GH-137243: Have `Tools/wasm/wasi` detect WASI SDK installs in `/opt` when the release tarball is extracted (GH-137244)
  Misc/NEWS.d/next/Tools-Demos/2025-07-30-10-28-35.gh-issue-137243.NkdUqH.rst
  Tools/wasm/wasi/__main__.py
Labels: awaiting merge, OS-wasi

#139730 gh-79315: Add Include/cpython/structseq.h header
  Include/cpython/structseq.h
  Include/structseq.h
  Makefile.pre.in
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
Labels: awaiting core review, skip news

#139739 Remove long-obsolete PCbuild/field3.py script
  PCbuild/field3.py
Labels: OS-windows, skip issue, skip news, build

#139084 [3.14] gh-138813: Fix mutable default kwargs={} in multiprocessing BaseProcess and DummyProcess to use None (GH-138814)
  Lib/multiprocessing/dummy/__init__.py
  Lib/multiprocessing/process.py
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Library/2025-09-17-08-32-43.gh-issue-138813.LHkHjX.rst
Labels: awaiting review

#139272 [3.14] gh-138558: Improve handling of Template annotations in annotationlib (GH-139072)
  Lib/annotationlib.py
  Lib/test/test_annotationlib.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-17-17-17-21.gh-issue-138558.0VbzCH.rst
Labels: awaiting merge

#139602 [3.13] gh-70765: avoid waiting for HTTP headers when parsing HTTP/0.9 requests (GH-139514)
  Lib/http/server.py
  Lib/test/test_httpservers.py
  Misc/NEWS.d/next/Library/2025-10-02-17-40-10.gh-issue-70765.zVlLZn.rst
Labels: awaiting core review
