Repository python/cpython, pull requests merged in 2025-03, with the labels that each got.

#128975 gh-128974: Fix `UnicodeError.__str__` when custom attributes have side-effects
  Lib/test/test_exceptions.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-18-10-50-04.gh-issue-128974.KltI-A.rst
  Objects/exceptions.c
Labels: awaiting merge

#130724 gh-128364: Fix flaky `test_timeout` test
  Lib/test/test_concurrent_futures/test_wait.py
  Lib/test/test_concurrent_futures/util.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130729 [3.12] gh-128364: Fix flaky `test_timeout` test (gh-130724)
  Lib/test/test_concurrent_futures/test_wait.py
  Lib/test/test_concurrent_futures/util.py
Labels: awaiting review, skip news

#130728 [3.13] gh-128364: Fix flaky `test_timeout` test (gh-130724)
  Lib/test/test_concurrent_futures/test_wait.py
  Lib/test/test_concurrent_futures/util.py
Labels: awaiting review, skip news

#130732 Revert "gh-128364: Fix flaky `test_timeout` test (gh-130724)"
  Lib/test/test_concurrent_futures/test_wait.py
  Lib/test/test_concurrent_futures/util.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#130735 [3.12] Revert "gh-128364: Fix flaky `test_timeout` test (gh-130724)" (gh-130732)
  Lib/test/test_concurrent_futures/test_wait.py
  Lib/test/test_concurrent_futures/util.py
Labels: awaiting review, skip news

#130734 [3.13] Revert "gh-128364: Fix flaky `test_timeout` test (gh-130724)" (gh-130732)
  Lib/test/test_concurrent_futures/test_wait.py
  Lib/test/test_concurrent_futures/util.py
Labels: awaiting review, skip news

#130642 [3.13] gh-130618: Fix parser error when using lambdas inside f-strings (GH-130638)
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-27-15-07-06.gh-issue-130618.JTcsRB.rst
  Parser/lexer/lexer.c
Labels: awaiting core review

#130644 [3.12] gh-130618: Fix parser error when using lambdas inside f-strings (GH-130638)
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-27-15-07-06.gh-issue-130618.JTcsRB.rst
  Parser/tokenizer.c
Labels: awaiting core review

#130743 Revert "GH-116380: Speed up `glob.[i]glob()` by making fewer system calls. (#116392)"
  Doc/library/glob.rst
  Doc/whatsnew/3.14.rst
  Lib/glob.py
  Lib/pathlib/_abc.py
  Lib/pathlib/_local.py
  Lib/test/test_glob.py
  Misc/NEWS.d/next/Library/2024-03-05-23-08-11.gh-issue-116380.56HU7I.rst
Labels: awaiting merge, skip news

#129959 gh-129401: Test repr rlock failing randomly
  Lib/test/_test_multiprocessing.py
  Misc/NEWS.d/next/Tests/2025-02-10-14-34-29.gh-issue-129401.Cq6Ruy.rst
Labels: tests, awaiting merge

#130314 gh-130160: use `.. program::` directive for documenting `cProfile` CLI
  Doc/library/profile.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130745 [3.13] gh-130160: use `.. program::` directive for documenting `cProfile` CLI (GH-130314)
  Doc/library/profile.rst
Labels: docs, awaiting merge, skip news

#130746 [3.12] gh-130160: use `.. program::` directive for documenting `cProfile` CLI (GH-130314)
  Doc/library/profile.rst
Labels: docs, awaiting merge, skip news

#130520 GH-127381: pathlib ABCs: remove `ReadablePath.exists()` and `is_*()`
  Lib/pathlib/_abc.py
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: awaiting core review, skip news, topic-pathlib

#130611 GH-127381: pathlib ABCs: remove `WritablePath.mkdir()` arguments
  Lib/pathlib/_abc.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: awaiting core review, skip news, topic-pathlib

#130739 Add link in importlib.metadata.version() docs
  Doc/library/importlib.metadata.rst
Labels: docs, skip issue, awaiting merge, skip news

#130741 Fix grammar typo in `Doc/c-api/arg.rst`
  Doc/c-api/arg.rst
Labels: docs, skip issue, awaiting merge, skip news

#128484 gh-128481: Add missing documentation for `traceback.FrameSummary`
  Doc/library/traceback.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130753 [3.13] gh-128481: Improve documentation for `traceback.FrameSummary` (GH-128484)
  Doc/library/traceback.rst
Labels: docs, awaiting review, skip news

#130754 [3.12] gh-128481: Improve documentation for `traceback.FrameSummary` (GH-128484)
  Doc/library/traceback.rst
Labels: docs, awaiting review, skip news

#130738 gh-130740: Move some `stdbool.h` includes after `Python.h`
  Misc/NEWS.d/next/Build/2025-03-01-18-27-42.gh-issue-130740.nDFSHR.rst
  Modules/_hashopenssl.c
  Parser/string_parser.c
  Python/codegen.c
  Python/flowgraph.c
  Python/index_pool.c
  Python/instruction_sequence.c
Labels: awaiting merge

#130761 [3.13] Add link in the `importlib.metadata.version()` docs (GH-130739)
  Doc/library/importlib.metadata.rst
Labels: docs, skip issue, awaiting merge, skip news

#130760 [3.12] Add link in the `importlib.metadata.version()` docs (GH-130739)
  Doc/library/importlib.metadata.rst
Labels: docs, skip issue, awaiting merge, skip news

#130759 [3.13] Fix grammar typo in `Doc/c-api/arg.rst` (GH-130741)
  Doc/c-api/arg.rst
Labels: docs, skip issue, awaiting review, skip news

#120650 gh-89083: add support for UUID version 6 (RFC 9562)
  Doc/library/uuid.rst
  Doc/whatsnew/3.14.rst
  Lib/test/test_uuid.py
  Lib/uuid.py
  Misc/NEWS.d/next/Library/2024-06-17-17-31-27.gh-issue-89083.nW00Yq.rst
Labels: type-feature, awaiting merge

#130646 gh-130637: Add validation for numeric response data in `stat()` method
  Lib/poplib.py
  Lib/test/test_poplib.py
  Misc/NEWS.d/next/Library/2025-03-01-02-19-28.gh-issue-130637.swet54w4rs.rst
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#130755 gh-128481: indicate that the default value for `FrameSummary.end_lineno` changed in 3.13
  Doc/library/traceback.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.13

#130767 [3.13] gh-128481: indicate that the default value for `FrameSummary.end_lineno` changed in 3.13 (GH-130755)
  Doc/library/traceback.rst
Labels: docs, awaiting merge, skip news

#130764 [3.12] gh-130637: Add validation for numeric response data in `stat()` method (GH-130646)
  Lib/poplib.py
  Lib/test/test_poplib.py
  Misc/NEWS.d/next/Library/2025-03-01-02-19-28.gh-issue-130637.swet54w4rs.rst
Labels: awaiting review

#130763 [3.13] gh-130637: Add validation for numeric response data in `stat()` method (GH-130646)
  Lib/poplib.py
  Lib/test/test_poplib.py
  Misc/NEWS.d/next/Library/2025-03-01-02-19-28.gh-issue-130637.swet54w4rs.rst
Labels: awaiting review

#130659 GH-130415: Use boolean guards to narrow types to values in the JIT
  Include/internal/pycore_optimizer.h
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-27-17-05-05.gh-issue-130415.iijvfW.rst
  Python/optimizer_analysis.c
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Python/optimizer_symbols.c
Labels: performance, awaiting core review, interpreter-core, topic-JIT

#128043 gh-128041: Add a terminate_workers method to ProcessPoolExecutor
  Doc/library/concurrent.futures.rst
  Doc/whatsnew/3.14.rst
  Lib/concurrent/futures/process.py
  Lib/test/test_concurrent_futures/test_process_pool.py
  Misc/NEWS.d/next/Library/2024-12-17-18-53-21.gh-issue-128041.W96kAr.rst
Labels: awaiting merge

#127668 gh-127667: fix more reference leaks in `hashlib`
  Modules/_hashopenssl.c
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129562 gh-129015: Move link supression around in a Note for exceptions.rst
  Doc/library/constants.rst
  Doc/library/exceptions.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130776 [3.13] gh-129015: Improve disambiguation between `NotImplemented` and `NotImplementedError` (GH-129562)
  Doc/library/constants.rst
  Doc/library/exceptions.rst
Labels: docs, awaiting review, skip news

#130629 gh-101100: Fix Sphinx documentation warnings in `collections.rst`
  Doc/library/collections.rst
  Doc/tools/.nitignore
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130774 gh-101100: Fix sphinx warnings in `library/email.errors.rst`
  Doc/library/email.errors.rst
  Doc/tools/.nitignore
Labels: docs, awaiting core review, skip news

#130779 [3.13] gh-101100: Fix Sphinx documentation warnings in `collections.rst` (GH-130629)
  Doc/library/collections.rst
  Doc/tools/.nitignore
Labels: docs, awaiting merge, skip news

#130781 [3.13] gh-101100: Fix sphinx warnings in `library/email.errors.rst` (GH-130774)
  Doc/library/email.errors.rst
  Doc/tools/.nitignore
Labels: docs, awaiting merge, skip news

#130780 [3.12] gh-101100: Fix sphinx warnings in `library/email.errors.rst` (GH-130774)
  Doc/library/email.errors.rst
  Doc/tools/.nitignore
Labels: docs, awaiting merge, skip news

#130782 [3.12] gh-101100: Fix Sphinx documentation warnings in `collections.rst` (GH-130629)
  Doc/library/collections.rst
  Doc/tools/.nitignore
Labels: docs, awaiting core review, skip news

#130150 gh-130149: refactor tests for HMAC
  Lib/test/support/hashlib_helper.py
  Lib/test/test_hmac.py
Labels: awaiting merge, skip news

#130783 [3.12] gh-127667: fix memory leaks in `hashlib` (GH-127668)
  Modules/_hashopenssl.c
Labels: awaiting core review, skip news

#130762 docs: internal notes have moved, correct references
  Include/internal/pycore_code.h
  Python/assemble.c
Labels: skip issue, awaiting merge, skip news

#129894 gh-129173: simplify `PyCodec_XMLCharRefReplaceErrors` logic
  Python/codecs.c
Labels: awaiting merge, skip news

#130787 `unittest.mock` test and coverage fixup
  Lib/test/test_unittest/testmock/testhelpers.py
  Lib/test/test_unittest/testmock/testmock.py
  Lib/test/test_unittest/testmock/testpatch.py
Labels: skip issue, awaiting core review, skip news

#130756 [3.13] gh-130740: Move some `stdbool.h` includes after `Python.h` (#130738)
  Misc/NEWS.d/next/Build/2025-03-01-18-27-42.gh-issue-130740.nDFSHR.rst
  Modules/_blake2/blake2b_impl.c
  Modules/_blake2/blake2s_impl.c
  Modules/_hashopenssl.c
  Parser/string_parser.c
  Python/flowgraph.c
  Python/instruction_sequence.c
Labels: awaiting core review

#129895 gh-129173: refactor `PyCodec_BackslashReplaceErrors` into separate functions
  Python/codecs.c
Labels: awaiting merge, skip news

#100389 gh-100388: Change undefined __DATE__ to the Unix epoch
  Misc/NEWS.d/next/Core_and_Builtins/2022-12-21-14-28-01.gh-issue-100388.vne8ky.rst
  Modules/getbuildinfo.c
Labels: awaiting merge

#130712 gh-130711: Document `PyBaseObject_Type`
  Doc/c-api/structures.rst
Labels: docs, awaiting core review, skip news, topic-C-API, needs backport to 3.12, needs backport to 3.13

#130639 [3.12] Docs: Fix a misplaced statement in the document for `ServerProxy` (GH-130616)
  Doc/library/xmlrpc.client.rst
Labels: docs, skip issue, awaiting review, skip news

#130791 [3.13] gh-130379: Fix incorrect zipapp logic to avoid including the target in itself (gh-130509)
  Lib/test/test_zipapp.py
  Lib/zipapp.py
  Misc/NEWS.d/next/Library/2025-02-24-14-46-20.gh-issue-130379.lsef7A.rst
Labels: awaiting merge

#130500 [3.13] gh-128388: pyrepl on Windows: add meta and ctrl+arrow keybindings (GH-128389)
  Lib/_pyrepl/windows_console.py
  Misc/NEWS.d/next/Library/2025-01-01-19-24-43.gh-issue-128388.8UdMz_.rst
Labels: awaiting merge, topic-repl

#130709 gh-130453: pygettext: Allow overriding default keywords when using `--keyword`
  Lib/test/test_tools/i18n_data/custom_keywords.pot
  Lib/test/test_tools/i18n_data/custom_keywords.py
  Lib/test/test_tools/test_i18n.py
  Misc/NEWS.d/next/Tools-Demos/2025-02-28-23-24-03.gh-issue-130453.EK0Vk_.rst
  Tools/i18n/pygettext.py
Labels: awaiting merge

#130747 GH-128520: Merge `pathlib._abc` into `pathlib.types`
  Lib/pathlib/_abc.py
  Lib/pathlib/types.py
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_pathlib/test_pathlib_abc.py
Labels: awaiting core review, skip news, topic-pathlib

#130797 gh-130737: Fix multiprocessing test_notify()
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting merge, skip news, topic-multiprocessing, needs backport to 3.12, needs backport to 3.13

#130803 [3.12] gh-130737: Fix multiprocessing test_notify() (GH-130797)
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting review, skip news, topic-multiprocessing

#130802 [3.13] gh-130737: Fix multiprocessing test_notify() (GH-130797)
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting review, skip news, topic-multiprocessing

#130801 gh-130790: Remove references about unicode's readiness from comments
  Include/cpython/unicodeobject.h
  Include/internal/pycore_traceback.h
  Modules/_io/textio.c
  Modules/unicodedata.c
  Objects/typeobject.c
  Objects/unicodeobject.c
  Parser/lexer/lexer.c
  Parser/pegen.c
  Python/codecs.c
  Python/formatter_unicode.c
  Python/tracemalloc.c
Labels: awaiting merge, skip news

#124512 gh-124445: Allow specializing generic ParamSpec aliases
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-09-25-13-45-01.gh-issue-124445.zfsD7q.rst
  Objects/genericaliasobject.c
Labels: awaiting merge

#130714 gh-130599: precompute conversion constants for ``long()``
  Objects/longobject.c
  Tools/c-analyzer/cpython/ignored.tsv
  Tools/scripts/long_conv_tables.py
Labels: awaiting merge, skip news, topic-free-threading

#130487 gh-130486: Fix test_venv fails from within venv
  Lib/test/test_venv.py
Labels: tests, awaiting merge, skip news

#130788 gh-130149: fix HMAC tests for some FIPS-only build bots
  Lib/test/test_hmac.py
Labels: tests, awaiting core review, skip news

#130757 [3.12] gh-130740: Move some `stdbool.h` includes after `Python.h` (#130738)
  Misc/NEWS.d/next/Build/2025-03-01-18-27-42.gh-issue-130740.nDFSHR.rst
  Objects/codeobject.c
  Parser/string_parser.c
  Python/assemble.c
  Python/compile.c
  Python/flowgraph.c
  Python/opcode_metadata.h
  Python/pythonrun.c
  Tools/cases_generator/generate_cases.py
Labels: awaiting merge

#121119 gh-89083: add support for UUID version 7 (RFC 9562)
  Doc/library/uuid.rst
  Doc/whatsnew/3.14.rst
  Lib/test/test_uuid.py
  Lib/uuid.py
  Misc/NEWS.d/next/Library/2024-06-28-11-27-25.gh-issue-89083.DKL_Sk.rst
Labels: type-feature, awaiting merge

#130800 gh-130736: Fix asyncio test_shutdown_default_executor_timeout()
  Lib/test/test_asyncio/test_base_events.py
Labels: tests, topic-asyncio, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130826 [3.12] gh-130736: Fix asyncio test_shutdown_default_executor_timeout() (GH-130800)
  Lib/test/test_asyncio/test_base_events.py
Labels: tests, topic-asyncio, awaiting review, skip news

#130825 [3.13] gh-130736: Fix asyncio test_shutdown_default_executor_timeout() (GH-130800)
  Lib/test/test_asyncio/test_base_events.py
Labels: tests, topic-asyncio, awaiting review, skip news

#130692 gh-129666: Add C11/C++11 to docs and -pedantic-errors to GCC/clang test_c[pp]ext tests
  Doc/c-api/intro.rst
  Include/object.h
  Lib/test/test_cext/__init__.py
  Lib/test/test_cext/extension.c
  Lib/test/test_cext/setup.py
  Lib/test/test_cppext/__init__.py
  Lib/test/test_cppext/extension.cpp
  Lib/test/test_cppext/setup.py
Labels: awaiting merge, skip news

#130778 gh-130547: Fix race between dict_dealloc and split_keys_entry_added
  Objects/dictobject.c
Labels: awaiting merge, skip news, topic-free-threading, needs backport to 3.13

#130815 gh-128184: Fix display of signatures with ForwardRefs
  Lib/dataclasses.py
  Lib/inspect.py
  Lib/test/test_dataclasses/__init__.py
  Lib/test/test_inspect/test_inspect.py
  Misc/NEWS.d/next/Library/2024-12-23-17-00-35.gh-issue-128184.cRQvgM.rst
Labels: awaiting merge

#130832 gh-130727: Retry test_wmi on TimeoutError
  Lib/test/test_wmi.py
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#130233 gh-129567: Add a note to `typing.TypedDict` docs about name mangling
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130841 [3.13] gh-129567: Add a note to `typing.TypedDict` docs about name mangling (GH-130233)
  Doc/library/typing.rst
Labels: docs, awaiting merge, skip news

#130839 [3.13] gh-130727: Retry test_wmi on TimeoutError (GH-130832)
  Lib/test/test_wmi.py
Labels: tests, awaiting review, skip news

#130842 [3.12] gh-129567: Add a note to typing.TypedDict docs about name mangling (GH-130233)
  Doc/library/typing.rst
Labels: docs, awaiting core review, skip news

#130838 Revert "gh-128041: Add `terminate_workers` and `kill_workers` methods to ProcessPoolExecutor (GH-128043)"
  Doc/library/concurrent.futures.rst
  Doc/whatsnew/3.14.rst
  Lib/concurrent/futures/process.py
  Lib/test/test_concurrent_futures/test_process_pool.py
  Misc/NEWS.d/next/Library/2024-12-17-18-53-21.gh-issue-128041.W96kAr.rst
Labels: awaiting merge

#130493 gh-82987: Stop on calling frame unconditionally for inline breakpoints
  Doc/library/pdb.rst
  Doc/whatsnew/3.14.rst
  Lib/bdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2025-02-24-01-49-11.gh-issue-82987.vHfQlG.rst
Labels: awaiting merge

#130643 GH-90916: Add helper function to dis.Instruction and use it to reduce churn in test_dis
  Lib/dis.py
  Lib/test/test_dis.py
Labels: awaiting merge, skip news

#130837 gh-130730: Fix multiprocessing test_active_children()
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130845 [3.13] gh-130730: Fix multiprocessing test_active_children() (GH-130837)
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting review, skip news

#129907 gh-130090: Support PGO for clang-cl
  Misc/ACKS
  Misc/NEWS.d/next/Build/2025-02-13-19-21-41.gh-issue-130090.3ngJaV.rst
  PCbuild/_freeze_module.vcxproj
  PCbuild/pyproject-clangcl.props
  PCbuild/pyproject.props
  PCbuild/pythoncore.vcxproj
  PCbuild/readme.txt
Labels: awaiting review

#127981 gh-126085: Add `tp_iter` to TypeAliasType to allow star unpacking
  Doc/library/typing.rst
  Doc/whatsnew/3.14.rst
  Lib/test/test_type_aliases.py
  Misc/NEWS.d/next/Core_and_Builtins/2024-12-15-16-56-26.gh-issue-126085.BvyEXk.rst
  Objects/typevarobject.c
Labels: awaiting merge

#105511 gh-105499: Merge typing.Union and types.UnionType
  Doc/deprecations/pending-removal-in-future.rst
  Doc/library/functools.rst
  Doc/library/stdtypes.rst
  Doc/library/types.rst
  Doc/library/typing.rst
  Doc/whatsnew/3.10.rst
  Doc/whatsnew/3.11.rst
  Include/internal/pycore_unionobject.h
  Lib/functools.py
  Lib/test/test_dataclasses/__init__.py
  Lib/test/test_functools.py
  Lib/test/test_inspect/test_inspect.py
  Lib/test/test_pydoc/test_pydoc.py
  Lib/test/test_types.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2023-06-08-07-56-05.gh-issue-105499.7jV6cP.rst
  Modules/_typingmodule.c
  Objects/typevarobject.c
  Objects/unionobject.c
Labels: awaiting merge

#130852 gh-130660: Add a test for pdb when user quits after interact command
  Lib/test/test_pdb.py
Labels: tests, awaiting core review, skip news

#130772 GH-130415: Narrow `int` to `0` based on boolean tests
  Lib/test/test_capi/test_opt.py
  Misc/ACKS
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-03-01-21-04.gh-issue-130415.ibOV6B.rst
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Python/optimizer_symbols.c
Labels: awaiting merge, topic-JIT

#130476 GH-130415: Narrow `str` to `""` based on boolean tests
  Lib/test/test_capi/test_opt.py
  Misc/ACKS
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-22-22-49-00.gh-issue-130415.WyxBYS.rst
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Python/optimizer_symbols.c
Labels: performance, awaiting merge, interpreter-core, topic-JIT

#127372 gh-127371 Avoid unbounded growth SpooledTempfile.writelines
  Lib/tempfile.py
  Lib/test/test_tempfile.py
  Misc/NEWS.d/next/Security/2024-11-28-20-29-21.gh-issue-127371.PeEhUd.rst
Labels: awaiting merge

#130808 gh-130794: Process interpreter QSBR queue in _PyMem_AbandonDelayed.
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-03-20-33-44.gh-issue-130794.LwtGQc.rst
  Objects/obmalloc.c
  Python/qsbr.c
Labels: awaiting merge, topic-free-threading, needs backport to 3.13

#130857 [3.13] gh-130794: Process interpreter QSBR queue in _PyMem_AbandonDelayed. (gh-130808)
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-03-20-33-44.gh-issue-130794.LwtGQc.rst
  Objects/obmalloc.c
  Python/qsbr.c
Labels: awaiting core review, topic-free-threading

#130444 GH-125722: Increase minimum supported Sphinx to 8.2.0
  Doc/conf.py
  Misc/NEWS.d/next/Documentation/2025-02-22-02-24-39.gh-issue-125722.zDIUFV.rst
Labels: docs, awaiting merge, needs backport to 3.12, needs backport to 3.13

#130858 [3.13] GH-125722: Increase minimum supported Sphinx to 8.2.0 (GH-130444)
  Doc/conf.py
  Misc/NEWS.d/next/Documentation/2025-02-22-02-24-39.gh-issue-125722.zDIUFV.rst
Labels: awaiting merge

#130833 [3.13] gh-130547: Fix race between dict_dealloc and split_keys_entry_added (gh-130778)
  Objects/dictobject.c
Labels: awaiting review, skip news, topic-free-threading

#130828 gh-130824: Add tests for `NULL` in `PyLong_*AndOverflow` functions
  Lib/test/test_capi/test_long.py
  Modules/_testlimitedcapi/long.c
Labels: tests, awaiting merge, skip news

#130871 gh-130824: Clean up test wrappers for PyLong_*AndOverflow functions
  Modules/_testlimitedcapi/long.c
Labels: tests, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#130220 gh-127750: Improve repr of functools.singledispatchmethod
  Lib/functools.py
  Lib/test/test_functools.py
  Misc/NEWS.d/next/Library/2025-02-17-12-36-39.gh-issue-127750.ZC-hBq.rst
Labels: awaiting core review

#130869 [3.13] gh-130824: Add tests for `NULL` in `PyLong_*AndOverflow` functions (GH-130828)
  Lib/test/test_capi/test_long.py
  Modules/_testlimitedcapi/long.c
Labels: awaiting review, skip news

#130876 [3.12] gh-130824: Add tests for NULL in PyLong_*AndOverflow functions (GH-130828)
  Lib/test/test_capi/test_long.py
  Modules/_testcapi/long.c
Labels: awaiting core review, skip news

#130874 [3.12] gh-116742: Fix subprocess test_check_output_timeout() (GH-130836)
  Lib/test/test_subprocess.py
Labels: tests, awaiting review, skip news

#130873 [3.13] gh-116742: Fix subprocess test_check_output_timeout() (GH-130836)
  Lib/test/test_subprocess.py
Labels: tests, awaiting review, skip news

#130785 GH-127705: better double free message.
  Include/internal/pycore_interp.h
  Include/internal/pycore_stackref.h
  Objects/object.c
  Python/pystate.c
  Python/stackrefs.c
Labels: awaiting merge, skip news

#130853 gh-130851: Don't crash when deduping unusual code constants.
  Lib/test/test_code.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-04-20-33-28.gh-issue-130851.MT9j7n.rst
  Objects/codeobject.c
Labels: awaiting merge, topic-free-threading, needs backport to 3.13

#130877 Update links from typing.readthedocs.io to typing.python.org
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130883 [3.13] Update links from typing.readthedocs.io to typing.python.org (GH-130877)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news

#130884 [3.12] Update links from typing.readthedocs.io to typing.python.org (GH-130877)
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting review, skip news

#130879 gh-130878: Got back check for prepare_ssl.py
  PCbuild/prepare_ssl.py
Labels: OS-windows, awaiting review, skip news

#130885 [3.12] gh-127371 Avoid unbounded growth SpooledTempfile.writelines (GH-127372)
  Lib/tempfile.py
  Lib/test/test_tempfile.py
  Misc/NEWS.d/next/Security/2024-11-28-20-29-21.gh-issue-127371.PeEhUd.rst
Labels: awaiting review

#130811 gh-118331: Fix a couple of issues when list allocation fails
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_metadata.h
  Lib/test/test_list.py
  Objects/listobject.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Tools/cases_generator/analyzer.py
Labels: awaiting merge, skip news

#130097 GH-115802: JIT using the "medium" code model on `x86_64-unknown-linux-gnu`
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-13-12-31-53.gh-issue-115802.0kN4xM.rst
  Tools/jit/_stencils.py
  Tools/jit/_targets.py
Labels: performance, awaiting merge, interpreter-core, topic-JIT

#130880 [3.13] gh-130851: Don't crash when deduping unusual code constants (GH-130853)
  Lib/test/test_code.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-04-20-33-28.gh-issue-130851.MT9j7n.rst
  Objects/codeobject.c
Labels: awaiting review, topic-free-threading

#130882 gh-129964: Fix JIT crash on Windows on Arm
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-05-15-19-21.gh-issue-129964.jqu89w.rst
  Tools/jit/_targets.py
Labels: awaiting merge, interpreter-core, type-crash, topic-JIT

#130849 gh-128041: Add `terminate_workers` and `kill_workers` methods to ProcessPoolExecutor
  Doc/library/concurrent.futures.rst
  Doc/whatsnew/3.14.rst
  Lib/concurrent/futures/process.py
  Lib/test/test_concurrent_futures/test_process_pool.py
  Misc/NEWS.d/next/Library/2024-12-17-18-53-21.gh-issue-128041.W96kAr.rst
Labels: awaiting merge

#129954 gh-130153: reword `match` paragraph in `Doc/tutorial/controlflow.rst`
  Doc/tutorial/controlflow.rst
Labels: docs, awaiting merge, skip news

#130900 gh-128041: Fix incorrect bullet placement
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#130082 gh-85795: Raise a clear error when `super()` is used in `typing.NamedTuple` subclasses
  Doc/library/typing.rst
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2025-02-13-15-10-56.gh-issue-85795.jeXXI9.rst
Labels: awaiting merge

#130908 gh-128563: Add correction note to tail call in whats new
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting core review, skip news

#130685 gh-130574: renumber RESUME opcode from 149 to 128
  Include/internal/pycore_magic_number.h
  Include/internal/pycore_opcode_metadata.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/test/test_code.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-28-13-34-51.gh-issue-130574.ujr3Vx.rst
  Programs/test_frozenmain.h
  Python/opcode_targets.h
  Tools/build/deepfreeze.py
  Tools/cases_generator/analyzer.py
Labels: awaiting review

#130904 GH-130903: typo in optimizer DSL for _GUARD_BOTH_UNICODE
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, skip news

#130865 gh-130860: fix width calculation, when separators in fractional part
  Lib/test/test_float.py
  Python/formatter_unicode.c
Labels: awaiting merge, skip news

#127648 gh-127647: Add typing.Reader and Writer protocols
  Doc/library/io.rst
  Doc/library/typing.rst
  Doc/whatsnew/3.14.rst
  Lib/_pyio.py
  Lib/io.py
  Lib/test/test_io.py
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2024-12-05-19-54-16.gh-issue-127647.Xd78Vs.rst
Labels: awaiting merge

#130649 gh-124878: Fix race conditions during interpreter finalization
  Include/cpython/pystate.h
  Include/internal/pycore_pystate.h
  Include/internal/pycore_runtime_init.h
  Include/internal/pycore_tstate.h
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-27-18-48-42.gh-issue-124878.DS0MIL.rst
  Modules/_threadmodule.c
  Modules/posixmodule.c
  Python/ceval_gil.c
  Python/pylifecycle.c
  Python/pystate.c
  Python/qsbr.c
  Tools/tsan/suppressions.txt
  Tools/tsan/suppressions_free_threading.txt
Labels: awaiting merge

#130742 gh-128364: Fix flaky `test_concurrent_futures.test_wait` tests
  Lib/test/test_concurrent_futures/test_wait.py
  Lib/test/test_concurrent_futures/util.py
Labels: awaiting merge, skip news, needs backport to 3.13

#130922 [3.13] gh-128364: Fix flaky `test_concurrent_futures.test_wait` tests (gh-130742)
  Lib/test/test_concurrent_futures/test_wait.py
  Lib/test/test_concurrent_futures/util.py
Labels: awaiting merge, skip news

#130921 gh-118331: Fix `test_list.ListTest.test_no_memory` under trace refs build
  Lib/test/test_list.py
Labels: tests, awaiting merge, skip news

#130923 gh-130920: Fix data race in STORE_SUBSCR_LIST_INT
  Lib/test/test_free_threading/test_list.py
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge, skip news, topic-free-threading

#130890 gettext: Remove outdated "TODO" comment
  Lib/gettext.py
Labels: skip issue, awaiting merge, skip news

#129012 gh-129011: Update comments in FileIO to match current code
  Lib/_pyio.py
  Modules/_io/clinic/fileio.c.h
  Modules/_io/fileio.c
Labels: awaiting merge, skip news

#130894 gh-130893: Fix sqlite3 docs typo
  Lib/sqlite3/__main__.py
Labels: docs, awaiting core review, skip news

#130934 gh-130932: Fix incorrect exception handling in _PyModule_IsPossiblyShadowing
  Lib/test/test_import/__init__.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-06-22-56-02.gh-issue-130932.QVHaKT.rst
  Objects/moduleobject.c
Labels: awaiting merge, needs backport to 3.13

#130939 [3.13] gh-130932: Fix incorrect exception handling in _PyModule_IsPossiblyShadowing (GH-130934)
  Lib/test/test_import/__init__.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-06-22-56-02.gh-issue-130932.QVHaKT.rst
  Objects/moduleobject.c
Labels: awaiting merge

#127539 Correct function name in `Doc/extending/embedding.rst`
  Doc/extending/embedding.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130945 [3.13] Correct function name in `Doc/extending/embedding.rst` (GH-127539)
  Doc/extending/embedding.rst
Labels: docs, skip issue, awaiting review, skip news

#130946 [3.12] Correct function name in `Doc/extending/embedding.rst` (GH-127539)
  Doc/extending/embedding.rst
Labels: docs, skip issue, awaiting review, skip news

#130847 GH-128534: Fix behavior of branch monitoring for `async for`
  Include/internal/pycore_magic_number.h
  Include/internal/pycore_opcode_metadata.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/dis.py
  Lib/test/test_code.py
  Lib/test/test_dis.py
  Lib/test/test_monitoring.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-04-15-12-32.gh-issue-128534.3A0K3D.rst
  Programs/test_frozenmain.h
  Python/assemble.c
  Python/bytecodes.c
  Python/codegen.c
  Python/flowgraph.c
  Python/generated_cases.c.h
  Python/instrumentation.c
  Python/opcode_targets.h
Labels: awaiting merge

#130933 gh-110206: Fix multiprocessing test_notify_all
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130901 gh-130851: Only intern constants of types generated by the compiler
  Objects/codeobject.c
Labels: awaiting merge, skip news, needs backport to 3.13

#130951 [3.12] gh-110206: Fix multiprocessing test_notify_all (GH-130933)
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting review, skip news

#130748 GH-128520: Merge `pathlib._local` into `pathlib`
  Lib/pathlib/__init__.py
  Lib/pathlib/_local.py
Labels: awaiting core review, skip news, topic-pathlib

#130969 [3.13] gh-130917: update timer and workload in test_signal (GH-130918)
  Lib/test/test_signal.py
Labels: tests, awaiting review, skip news

#128647 gh-128646: Implement GzipFile.readinto() functions
  Lib/gzip.py
  Lib/test/test_gzip.py
  Misc/NEWS.d/next/Library/2025-01-08-15-14-17.gh-issue-128647.GabglU.rst
Labels: awaiting core review

#130955 gh-130954: Fix multiprocessing test_notify_n
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#130953 [3.13] gh-130851: Only intern constants of types generated by the compiler (GH-130901)
  Objects/codeobject.c
Labels: awaiting core review, skip news

#130982 [3.12] gh-130954: Fix multiprocessing test_notify_n (GH-130955)
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting review, skip news

#130968 [3.12] gh-130917: update timer and workload in test_signal (GH-130918)
  Lib/test/test_signal.py
Labels: tests, awaiting review, skip news

#130981 [3.13] gh-130954: Fix multiprocessing test_notify_n (GH-130955)
  Lib/test/_test_multiprocessing.py
Labels: tests, awaiting review, skip news

#130537 gh-123726: Document caveats of zipfile.Path around name sanitization
  Doc/library/zipfile.rst
Labels: docs, awaiting review, skip news, needs backport to 3.12, needs backport to 3.13

#130986 [3.13] gh-123726: Document caveats of zipfile.Path around name sanitization (GH-130537)
  Doc/library/zipfile.rst
Labels: docs, awaiting review, skip news

#130987 [3.12] gh-123726: Document caveats of zipfile.Path around name sanitization (GH-130537)
  Doc/library/zipfile.rst
Labels: docs, awaiting review, skip news

#130995 gh-130160: use `.. program::` directive for documenting `webbrowser` CLI
  Doc/library/webbrowser.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13
