Repository python/cpython, pull requests merged in 2025-09, with the labels that each got.

#138289 gh-116946: fully implement GC protocol for `_hashlib` objects
  Modules/_hashopenssl.c
Labels: awaiting merge, skip news, needs backport to 3.14

#138290 gh-116946: fully implement GC protocol for `zlib` objects
  Modules/zlibmodule.c
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138323 [3.13] gh-116946: fully implement GC protocol for `lzma` objects (GH-138288)
  Modules/_lzmamodule.c
Labels: awaiting core review, skip news

#138326 [3.13] gh-116946: fully implement GC protocol for `_hashlib` objects (GH-138289)
  Modules/_hashopenssl.c
Labels: awaiting core review, skip news

#138328 [3.13] gh-116946: fully implement GC protocol for `zlib` objects (GH-138290)
  Modules/zlibmodule.c
Labels: awaiting core review, skip news

#137930 Reapply "gh-132947: Apply changes from importlib_metadata 8.7 (#137885)" (#137924)
  Lib/importlib/metadata/__init__.py
  Lib/importlib/metadata/_adapters.py
  Lib/importlib/metadata/_collections.py
  Lib/importlib/metadata/_functools.py
  Lib/importlib/metadata/_meta.py
  Lib/importlib/metadata/_typing.py
  Lib/test/test_importlib/metadata/_issue138313.py
  Lib/test/test_importlib/metadata/_path.py
  Lib/test/test_importlib/metadata/fixtures.py
  Lib/test/test_importlib/metadata/test_api.py
  Lib/test/test_importlib/metadata/test_main.py
  Lib/test/test_importlib/metadata/test_zip.py
  Misc/NEWS.d/next/Library/2025-08-17-10-22-31.gh-issue-132947.XR4MJ8.rst
Labels: awaiting core review

#138337 [3.13] gh-116946: Revert GC protocol for immutable empty heap types (GH-138322, GH-138323, GH-138326)
  Modules/_bz2module.c
  Modules/_hashopenssl.c
  Modules/_lzmamodule.c
Labels: awaiting merge, skip news

#138301 gh-54874: Expand unicodedata module documentation
  Doc/library/unicodedata.rst
Labels: docs, awaiting merge, skip news

#138347 gh-138302: Specialize int ops only if ints are compact
  Lib/test/test_opcache.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-01-21-52-54.gh-issue-138302.-ez47B.rst
  Python/specialize.c
Labels: awaiting merge

#138354 [3.13] gh-89905: Correct `-R` option doc (GH-137608)
  Doc/using/cmdline.rst
Labels: docs, awaiting review, skip news

#138359 gh-138360: Fix `test_free_threading` for IO objects
  Lib/test/test_free_threading/test_io.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138150 gh-135763: Argument Clinic: Implement allow_negative for ssize_t
  Include/internal/pycore_abstract.h
  Lib/test/clinic.test.c
  Lib/test/test_clinic.py
  Modules/_testclinic.c
  Modules/clinic/_testclinic.c.h
  Python/modsupport.c
  Tools/clinic/libclinic/converters.py
Labels: awaiting merge, skip news, topic-argument-clinic

#138254 gh-61206: Support zstandard compression in the zipimport module
  Doc/library/zipimport.rst
  Lib/test/test_zipimport.py
  Lib/zipimport.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-08-30-00-55-35.gh-issue-61206.HeFLvl.rst
Labels: awaiting merge

#138256 gh-138253: Fix compatibility of sub-interpreters queues with queue.Queue
  Lib/concurrent/interpreters/_queues.py
  Lib/test/test_interpreters/test_queues.py
  Misc/NEWS.d/next/Library/2025-08-30-10-58-15.gh-issue-138253.9Ehj-N.rst
Labels: awaiting merge, needs backport to 3.14

#138063 gh-110936: Improve string literal definition in Lexical Analysis
  Doc/reference/lexical_analysis.rst
Labels: docs, awaiting review, skip news

#138369 gh-127647: Fix and enable I/O protocol tests
  Lib/test/test_io/test_general.py
Labels: tests, awaiting merge, skip news, needs backport to 3.14

#138298 gh-138297 Point link in docs for `finally` to try/else, instead of if/else
  Doc/reference/compound_stmts.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138017 gh-138004: Encode thread names on Solaris-based platforms as ASCII and fix main/worker threading test
  Lib/test/test_threading.py
  Misc/ACKS
  Misc/NEWS.d/next/Core_and_Builtins/2025-08-21-06-31-42.gh-issue-138004.FH2Hre.rst
  Modules/_threadmodule.c
Labels: awaiting merge

#138220 gh-138204: Forbid expansion of a shared anonymous mmap on Linux
  Lib/test/test_mmap.py
  Misc/NEWS.d/next/Library/2025-08-28-13-20-09.gh-issue-138204.8oLOud.rst
  Modules/mmapmodule.c
Labels: awaiting core review, needs backport to 3.13, needs backport to 3.14

#138375 gh-138372: Fix SyntaxWarning for erroneous t-string subscription
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-02-09-10-06.gh-issue-138372.h1Xk4-.rst
  Python/codegen.c
Labels: awaiting merge, needs backport to 3.14

#138392 [3.14] gh-138372: Fix SyntaxWarning for erroneous t-string subscription (GH-138375)
  Lib/test/test_grammar.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-02-09-10-06.gh-issue-138372.h1Xk4-.rst
  Python/codegen.c
Labels: awaiting merge

#138393 Doc: Track file downloads via plausible
  Doc/tools/templates/layout.html
Labels: skip issue, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138397 [3.13] Doc: Track file downloads via plausible (GH-138393)
  Doc/tools/templates/layout.html
Labels: skip issue, awaiting merge, skip news

#138394 GH-135763: AC: Use ``Py_ssize_t(allow_negative=False)``
  Modules/_bisectmodule.c
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/clinic/_ctypes.c.h
  Modules/_hashopenssl.c
  Modules/arraymodule.c
  Modules/clinic/_bisectmodule.c.h
  Modules/clinic/_hashopenssl.c.h
  Modules/clinic/arraymodule.c.h
  Modules/clinic/itertoolsmodule.c.h
  Modules/clinic/posixmodule.c.h
  Modules/clinic/sha3module.c.h
  Modules/clinic/zlibmodule.c.h
  Modules/itertoolsmodule.c
  Modules/posixmodule.c
  Modules/sha3module.c
  Modules/zlibmodule.c
  Objects/clinic/longobject.c.h
  Objects/longobject.c
Labels: awaiting merge, skip news, topic-argument-clinic

#138424 [3.13] GH-101100: Resolve reference warnings in whatsnew/3.7.rst (GH-138410)
  Doc/howto/instrumentation.rst
  Doc/library/hmac.rst
  Doc/reference/datamodel.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.7.rst
Labels: docs, awaiting merge, skip news

#138341 gh-116946: add `Py_TPFLAGS_IMMUTABLETYPE` to `_random.Random`
  Misc/NEWS.d/next/Library/2025-09-02-10-23-09.gh-issue-116946.U6RpwK.rst
  Modules/_randommodule.c
Labels: awaiting merge

#138333 gh-116946: fully implement GC protocol for `_curses_panel.panel`
  Modules/_curses_panel.c
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138265 gh-138264: Fix gcc 14 compiler warnings
  Include/internal/pycore_stats.h
  Lib/test/test_generated_cases.py
  Modules/_sre/sre.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Tools/cases_generator/generators_common.py
Labels: awaiting merge, skip news, needs backport to 3.14

#138365 gh-138013: Move I/O tests to test_io
  Lib/test/libregrtest/findtests.py
  Lib/test/test_io/__init__.py
  Lib/test/test_io/test_bufferedio.py
  Lib/test/test_io/test_file.py
  Lib/test/test_io/test_fileio.py
  Lib/test/test_io/test_general.py
  Lib/test/test_io/test_largefile.py
  Lib/test/test_io/test_memoryio.py
  Lib/test/test_io/test_univnewlines.py
Labels: tests, awaiting merge, skip news

#138366 gh-138013: Remove `test_io` load_tests namespace manipulation
  Lib/test/test_io/test_general.py
Labels: tests, awaiting merge, skip news

#138434 [3.14] GH-123299: Copyedit 3.14 What's New: Move and consolidate Porting (GH-138400)
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#138409 GH-101100: Resolve reference warnings in whatsnew/3.8.rst
  Doc/library/unittest.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.8.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138306 gh-138307: Update the Ellipsis documentation
  Doc/glossary.rst
  Doc/library/constants.rst
  Doc/library/stdtypes.rst
  Doc/library/typing.rst
  Doc/tutorial/controlflow.rst
Labels: docs, awaiting merge, skip news

#138436 [3.13] GH-101100: Resolve reference warnings in whatsnew/3.3.rst (GH-138414)
  Doc/library/curses.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.3.rst
Labels: docs, awaiting review, skip news

#138437 [3.14] GH-101100: Resolve reference warnings in whatsnew/3.8.rst (GH-138409)
  Doc/library/unittest.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.8.rst
Labels: docs, awaiting review, skip news

#138438 [3.13] GH-101100: Resolve reference warnings in whatsnew/3.8.rst (GH-138409)
  Doc/library/unittest.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.8.rst
Labels: docs, awaiting review, skip news

#138441 [3.14] GH-101100: Resolve reference warnings in whatsnew/2.7.rst (GH-138415)
  Doc/library/shutil.rst
  Doc/tools/.nitignore
  Doc/whatsnew/2.7.rst
Labels: docs, awaiting merge, skip news

#138442 [3.13] GH-101100: Resolve reference warnings in whatsnew/2.7.rst (GH-138415)
  Doc/library/shutil.rst
  Doc/tools/.nitignore
  Doc/whatsnew/2.7.rst
Labels: docs, awaiting merge, skip news

#121431 GH-119169: Slightly speed up `os.walk(topdown=True)`
  Lib/os.py
  Misc/NEWS.d/next/Library/2024-07-06-14-32-30.gh-issue-119186.E5B1HQ.rst
Labels: performance, awaiting core review

#138413 GH-101100: Resolve reference warnings in whatsnew/3.4.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.4.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138443 [3.14] GH-101100: Resolve reference warnings in whatsnew/3.4.rst (GH-138413)
  Doc/tools/.nitignore
  Doc/whatsnew/3.4.rst
Labels: docs, awaiting review, skip news

#138406 Docs: Fix typo in test.support.linked_to_musl function name
  Doc/library/test.rst
Labels: docs, skip issue, awaiting review, skip news, needs backport to 3.14

#138417 GH-101100: Resolve reference warnings in extending/extending.rst
  Doc/extending/extending.rst
  Doc/tools/.nitignore
  Misc/NEWS.d/3.11.0a1.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138446 [3.14] GH-101100: Resolve reference warnings in extending/extending.rst (GH-138417)
  Doc/extending/extending.rst
  Doc/tools/.nitignore
  Misc/NEWS.d/3.11.0a1.rst
Labels: docs, awaiting review, skip news

#31978 gh-91214: Skip tests failing on Solaris
  Lib/test/test_re.py
  Lib/test/test_socket.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#137713 gh-135676: Reword the Operators & Delimiters section(s)
  Doc/reference/lexical_analysis.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.14

#138412 GH-101100: Resolve reference warnings in whatsnew/3.5.rst
  Doc/library/collections.abc.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.5.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138444 [3.13] GH-101100: Resolve reference warnings in whatsnew/3.4.rst (GH-138413)
  Doc/library/dis.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.4.rst
Labels: docs, awaiting merge, skip news

#138282 gh-138281: Run `ruff` on `Tools/peg_generator`
  .pre-commit-config.yaml
  Tools/peg_generator/.ruff.toml
  Tools/peg_generator/pegen/__main__.py
  Tools/peg_generator/pegen/ast_dump.py
  Tools/peg_generator/pegen/build.py
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/first_sets.py
  Tools/peg_generator/pegen/grammar.py
  Tools/peg_generator/pegen/grammar_visualizer.py
  Tools/peg_generator/pegen/parser.py
  Tools/peg_generator/pegen/parser_generator.py
  Tools/peg_generator/pegen/python_generator.py
  Tools/peg_generator/pegen/sccutils.py
  Tools/peg_generator/pegen/testutil.py
  Tools/peg_generator/pegen/tokenizer.py
  Tools/peg_generator/pegen/validator.py
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138458 gh-138431: JIT Optimizer --- Fix round-tripping references for str and tuple
  Include/internal/pycore_optimizer.h
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-03-15-35-34.gh-issue-138431.EUsrtA.rst
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge, needs backport to 3.14

#138468 gh-72249: Correct wording of GH-101910 blurb
  Misc/NEWS.d/3.13.0a5.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138472 [3.13] gh-138281: Run `ruff` on `Tools/peg_generator` (GH-138282)
  .pre-commit-config.yaml
  Tools/peg_generator/.ruff.toml
  Tools/peg_generator/pegen/__main__.py
  Tools/peg_generator/pegen/ast_dump.py
  Tools/peg_generator/pegen/build.py
  Tools/peg_generator/pegen/c_generator.py
  Tools/peg_generator/pegen/first_sets.py
  Tools/peg_generator/pegen/grammar.py
  Tools/peg_generator/pegen/grammar_visualizer.py
  Tools/peg_generator/pegen/parser.py
  Tools/peg_generator/pegen/parser_generator.py
  Tools/peg_generator/pegen/python_generator.py
  Tools/peg_generator/pegen/sccutils.py
  Tools/peg_generator/pegen/testutil.py
  Tools/peg_generator/pegen/tokenizer.py
  Tools/peg_generator/pegen/validator.py
Labels: awaiting merge, skip news

#138476 Fix Windows path in `venv` docs
  Doc/library/venv.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.13, needs backport to 3.14

#138408 GH-101100: Resolve reference warnings in whatsnew/3.10.rst
  Doc/tools/.nitignore
  Doc/whatsnew/3.10.rst
Labels: docs, awaiting core review, skip news, needs backport to 3.13, needs backport to 3.14

#138481 [3.13] GH-101100: Resolve reference warnings in whatsnew/3.10.rst (GH-138408)
  Doc/tools/.nitignore
  Doc/whatsnew/3.10.rst
Labels: docs, awaiting merge, skip news

#129971 gh-95844: Move help_url code to a help module function
  Lib/idlelib/editor.py
  Lib/idlelib/help.py
Labels: skip news, needs backport to 3.13, needs backport to 3.14

#138485 [3.13] gh-95844: Move help_url code to a help module function (GH-129971)
  Lib/idlelib/editor.py
  Lib/idlelib/help.py
Labels: awaiting review, skip news

#138429 gh-132657: Make deepcopy and copy scale with free-threading
  Lib/copy.py
  Misc/NEWS.d/next/Library/2025-09-03-09-03-11.gh-issue-132657.cbAIDh.rst
Labels: performance, awaiting merge, stdlib, topic-free-threading

#138501 [3.13] Docs: Fix typo in `os.fwalk()` example (GH-138486)
  Doc/library/os.rst
Labels: docs, skip issue, awaiting merge, skip news

#138461 [3.14] GH-101100: Resolve reference warnings in using/windows.rst (GH-138416)
  Doc/tools/.nitignore
  Doc/using/windows.rst
Labels: docs, awaiting merge, skip news

#138377 Add random_derangement recipe
  Doc/library/random.rst
Labels: docs, skip issue, awaiting core review, skip news

#138494 gh-87595: Fix the docs for mmap.size()
  Doc/library/mmap.rst
  Misc/NEWS.d/next/Library/2021-03-07-16-31-36.bpo-43429.Koa0mf.rst
Labels: docs, awaiting merge

#138522 [3.13] gh-138516: fix typo in OrderedDict exception msg (GH-138517)
  Objects/odictobject.c
Labels: awaiting merge, skip news

#138524 [3.13] gh-138286: Run ``ruff`` on ``Tools/i18n`` (GH-138287)
  .pre-commit-config.yaml
  Tools/i18n/.ruff.toml
  Tools/i18n/makelocalealias.py
  Tools/i18n/msgfmt.py
  Tools/i18n/pygettext.py
Labels: awaiting merge, skip news

#138523 [3.14] gh-138516: fix typo in OrderedDict exception msg (GH-138517)
  Objects/odictobject.c
Labels: awaiting merge, skip news

#138403 gh-138401: Check arg `count>=0` in `os.sendfile`
  Lib/test/test_os.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-02-22-17-55.gh-issue-138401.uTRvue.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting merge

#137816 gh-131178: Fix `test_unknown_flag` for platform CLI
  Lib/test/test_platform.py
Labels: tests, awaiting merge, skip news

#138309 gh-57911: Sanitize symlink targets in tarfile on win32
  Doc/whatsnew/3.15.rst
  Lib/tarfile.py
  Lib/test/test_tarfile.py
  Misc/NEWS.d/next/Library/2025-08-31-22-10-22.gh-issue-57911.N_Ixtv.rst
Labels: awaiting review

#138508 annotationlib: add note on security to docs
  Doc/library/annotationlib.rst
  Doc/library/inspect.rst
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news

#136878 gh-83424: Allow empty name if handle is non-null when create ctypes.CDLL
  Lib/ctypes/__init__.py
  Lib/test/test_ctypes/test_loading.py
  Misc/NEWS.d/next/Library/2025-07-21-01-16-32.gh-issue-83424.Y3tEV4.rst
Labels: awaiting merge, needs backport to 3.13, needs backport to 3.14

#138540 gh-138191: Document ``frame.f_generator`` in the data model
  Doc/reference/datamodel.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.14

#138549 [3.13] gh-88375, gh-111788: Fix parsing errors and normalization in robotparser (GH-138502)
  Lib/test/test_robotparser.py
  Lib/urllib/robotparser.py
  Misc/NEWS.d/next/Library/2025-09-04-15-18-11.gh-issue-111788.tuTEM5.rst
  Misc/NEWS.d/next/Library/2025-09-05-15-35-59.gh-issue-88375.dC491a.rst
Labels: awaiting review

#138210 gh-138010: Fix `__init_subclass__` forwarding by `warnings.deprecated`
  Lib/_py_warnings.py
  Lib/test/test_warnings/__init__.py
  Misc/NEWS.d/next/Library/2025-08-27-17-05-36.gh-issue-138010.ZZJmPL.rst
Labels: awaiting merge, needs backport to 3.13, needs backport to 3.14

#138530 gh-137985: correct description of Formatter's datefmt param in logging doc
  Doc/library/logging.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138564 [3.13] gh-138010: Fix `__init_subclass__` forwarding by `warnings.deprecated` (GH-138210)
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2025-08-27-17-05-36.gh-issue-138010.ZZJmPL.rst
Labels: awaiting merge

#138566 [3.13] gh-137985: Correct description of Formatter's datefmt param in logging documentation (GH-138530)
  Doc/library/logging.rst
Labels: docs, awaiting review, skip news

#138567 [3.13] GH-138465: Improve documentation for common sequence methods (GH-138474)
  Doc/conf.py
  Doc/faq/design.rst
  Doc/faq/programming.rst
  Doc/glossary.rst
  Doc/library/bisect.rst
  Doc/library/collections.abc.rst
  Doc/library/collections.rst
  Doc/library/pickle.rst
  Doc/library/stdtypes.rst
  Doc/reference/datamodel.rst
  Doc/tutorial/controlflow.rst
  Doc/tutorial/datastructures.rst
  Doc/tutorial/introduction.rst
  Doc/whatsnew/2.0.rst
  Doc/whatsnew/2.6.rst
  Doc/whatsnew/3.11.rst
  Doc/whatsnew/3.13.rst
  Doc/whatsnew/3.3.rst
Labels: awaiting core review, skip news

#98100 gh-93334: Fix homonym edge case in PathFinder.find_spec()
  Lib/importlib/_bootstrap_external.py
  Lib/test/test_importlib/namespace_pkgs/foo/README.md
  Lib/test/test_importlib/test_namespace_pkgs.py
  Makefile.pre.in
  Misc/NEWS.d/next/Library/2022-10-08-14-56-07.gh-issue-93334.0KUm8d.rst
Labels: awaiting merge

#138203 GH-95952: Require setting `HOSTRUNNER` when cross compiling for WASI
  Misc/NEWS.d/next/Build/2025-08-27-11-32-02.gh-issue-95952.KSymc7.rst
  configure
  configure.ac
Labels: awaiting core review, build, 3.15

#137712 gh-137706: make typing._is_unpacked_typevartuple check for `True` instead of truthy
  Lib/test/test_typing.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2025-09-05-21-10-24.gh-issue-137706.0EztiJ.rst
Labels: awaiting merge, needs backport to 3.14

#138229 gh-116738: Make cProfile module thread-safe
  Lib/test/test_free_threading/test_cprofile.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-08-28-09-29-46.gh-issue-116738.yLZJpV.rst
  Modules/_lsprof.c
  Modules/clinic/_lsprof.c.h
Labels: awaiting merge, topic-free-threading, needs backport to 3.14

#138276 gh-138205: Remove the resize method on mmap object on platforms don't support it
  Doc/library/mmap.rst
  Doc/whatsnew/3.15.rst
  Lib/test/test_mmap.py
  Misc/NEWS.d/next/Library/2025-08-31-12-34-02.gh-issue-138205.iHXb1z.rst
  Modules/mmapmodule.c
Labels: awaiting merge

#138428 [3.13] gh-116946: fully implement GC protocol for `_curses_panel.panel` (GH-138333)
  Modules/_curses_panel.c
Labels: awaiting merge, skip news

#138553 [3.14] gh-138191: Document ``frame.f_generator`` in the data model (GH-138540)
  Doc/reference/datamodel.rst
Labels: docs, awaiting merge, skip news

#138427 [3.14] gh-116946: fully implement GC protocol for `_curses_panel.panel` (GH-138333)
  Modules/_curses_panel.c
Labels: awaiting merge, skip news

#138554 fix comment reference from man 7 signal to man 7 signal-safety
  Modules/_posixsubprocess.c
  Modules/signalmodule.c
  Python/pylifecycle.c
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#134454 gh-90548: Allow Alpine/MUSL to pass test_c_locale_coercion.
  Lib/test/test_c_locale_coercion.py
Labels: tests, awaiting merge, skip news

#138592 gh-90548: Skip ctypes test_null_dlsym when linked to musl
  Lib/test/test_ctypes/test_dlerror.py
Labels: tests, awaiting core review, skip news, topic-ctypes

#138595 [3.13] fix comment reference from man 7 signal to man 7 signal-safety (GH-138554)
  Modules/_posixsubprocess.c
  Modules/signalmodule.c
  Python/pylifecycle.c
Labels: skip issue, awaiting merge, skip news

#138599 Fix typo in `random_derangement` recipe
  Doc/library/random.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138602 [3.14] gh-90548: Skip NODEV portion of test_makedev when linked to musl (GH-138593)
  Lib/test/test_posix.py
Labels: tests, awaiting merge, skip news

#138601 [3.14] gh-90548: Skip ctypes test_null_dlsym when linked to musl (GH-138592)
  Lib/test/test_ctypes/test_dlerror.py
Labels: tests, awaiting merge, skip news, topic-ctypes

#138600 [3.14] gh-90548: Allow Alpine/MUSL to pass test_c_locale_coercion. (GH-134454)
  Lib/test/test_c_locale_coercion.py
Labels: tests, awaiting merge, skip news

#135295 gh-126631: fix pre-loading of __main__
  Lib/multiprocessing/forkserver.py
  Lib/test/_test_multiprocessing.py
  Lib/test/mp_preload_main.py
  Misc/NEWS.d/next/Library/2025-06-10-21-00-48.gh-issue-126631.eITVJd.rst
Labels: type-bug, awaiting merge, needs backport to 3.13, needs backport to 3.14

#138596 [3.13] gh-138556: Fixed the links in documentation
  Doc/library/gc.rst
Labels: docs, awaiting merge, skip news

#138588 Add Emma Smith to CODEOWNERS
  .github/CODEOWNERS
Labels: skip issue, awaiting merge, skip news

#138590 gh-138584: Fix missing type2test in Lib/tests/list_tests.py
  Lib/test/list_tests.py
Labels: awaiting merge, skip news

#138611 [3.13] gh-138584: Increase test coverage for `collections.UserList` (GH-138590)
  Lib/test/list_tests.py
Labels: awaiting merge, skip news

#138612 [3.14] gh-138584: Increase test coverage for `collections.UserList` (GH-138590)
  Lib/test/list_tests.py
Labels: awaiting merge, skip news

#138578 gh-105487: Fix `__dir__` entries of `GenericAlias`
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-06-13-53-33.gh-issue-105487.a43YaY.rst
  Objects/genericaliasobject.c
Labels: awaiting merge, needs backport to 3.13, needs backport to 3.14

#138488 GH-123299: Copyedit 3.14 What's New: Build Changes
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.14

#138632 [3.14] GH-123299: Copyedit 3.14 What's New: Build Changes (GH-138488)
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting review, skip news

#136406 [3.12] gh-136155: Use ``sphinxext-opengraph`` v0.12.0
  Doc/conf.py
  Doc/requirements.txt
Labels: awaiting core review, skip news

#138545 gh-137210: Move PYTHON_API_VERSION & PYTHON_ABI_VERSION to patchlevel.h
  Include/modsupport.h
  Include/patchlevel.h
  PC/python_ver_rc.h
Labels: awaiting merge, skip news

#138643 [3.14] Use `test.support.is_wasm32` flag for `is_emscripten` or `is_wasi` for generic checks (GH-136815)
  Lib/test/pythoninfo.py
  Lib/test/support/__init__.py
  Lib/test/test_build_details.py
  Lib/test/test_import/__init__.py
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_pty.py
  Lib/test/test_pydoc/test_pydoc.py
  Lib/test/test_support.py
  Lib/test/test_venv.py
Labels: skip issue, awaiting merge, skip news, type-refactor

#138626 gh-57911: Fix failing symlink test
  Lib/test/test_tarfile.py
Labels: tests, awaiting review, skip news

#137406 [3.14] gh-137397: Skip test_os_open on NetBSD due to indefinite hang (GH-137398)
  Lib/test/_test_eintr.py
Labels: type-bug, tests, awaiting merge, skip news

#138381 [3.14] gh-138297 Point link in docs for `finally` to try/else, instead of if/else (GH-138298)
  Doc/reference/compound_stmts.rst
Labels: docs, awaiting merge, skip news

#138667 gh-138665: Move `platform.invalidate_caches` docs
  Doc/library/platform.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.14

#138367 [3.14] gh-138253: Fix compatibility of sub-interpreters queues with queue.Queue (GH-138256)
  Lib/concurrent/interpreters/_queues.py
  Lib/test/test_interpreters/test_queues.py
  Misc/NEWS.d/next/Library/2025-08-30-10-58-15.gh-issue-138253.9Ehj-N.rst
Labels: awaiting merge

#138177 gh-137838: Fix JIT trace buffer overrun by increasing possible exit stubs
  Include/internal/pycore_optimizer.h
  Lib/test/test_sys_settrace.py
  Lib/test/test_trace.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-08-27-17-51-38.gh-issue-137838.lK6T0j.rst
  Python/optimizer.c
Labels: awaiting merge

#138684 [3.14] gh-137242: Add a --no-randomize option, and use it in Android CI (GH-138649)
  Android/android.py
  Lib/test/libregrtest/cmdline.py
  Lib/test/test_regrtest.py
Labels: awaiting merge, skip news

#138537 gh-138535: Optimize fill_time for typical timestamps
  Lib/test/test_os.py
  Misc/NEWS.d/next/Library/2025-09-06-20-09-32.gh-issue-138535.mlntEe.rst
  Modules/posixmodule.c
Labels: performance, awaiting review

#138677 gh-138577: Mention limitations of `getpass.getpass(echo_char=...)`
  Doc/library/getpass.rst
Labels: docs, awaiting review, skip news, needs backport to 3.14

#138696 [3.14] gh-138577: Mention Unix-specific limitations of `getpass.getpass(echo_char=...)` (GH-138677)
  Doc/library/getpass.rst
Labels: docs, awaiting merge, skip news

#138698 gh-133143: Use _Py_ID for the other literals in sys
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Include/internal/pycore_unicodeobject_generated.h
  Python/sysmodule.c
Labels: awaiting merge, skip news

#138693 gh-138535: Pass directly state to posix fill_time()
  Modules/posixmodule.c
Labels: awaiting core review, skip news

#138683 [3.14] GH-101100: Remove some entries from ``nitpick_ignore`` (GH-138464)
  Doc/conf.py
  Doc/library/collections.rst
  Doc/library/dataclasses.rst
  Doc/library/dis.rst
  Doc/library/inspect.rst
  Doc/library/os.path.rst
  Doc/library/pathlib.rst
  Doc/library/stdtypes.rst
  Doc/reference/compound_stmts.rst
  Doc/tools/check-warnings.py
  Doc/tutorial/controlflow.rst
  Doc/whatsnew/3.2.rst
  Doc/whatsnew/3.4.rst
  Doc/whatsnew/3.5.rst
  Doc/whatsnew/3.6.rst
  Misc/NEWS.d/3.12.0a1.rst
  Misc/NEWS.d/3.13.0a6.rst
  Misc/NEWS.d/3.14.0a7.rst
Labels: awaiting review, skip news

#94662 gh-85076: Document exceptions that can be raised by importlib.import_module
  Doc/library/importlib.rst
Labels: docs, awaiting merge, skip news, topic-importlib

#138713 [3.13] gh-90548: Skip NODEV portion of test_makedev when linked to musl (GH-138593)
  Lib/test/test_posix.py
Labels: tests, awaiting review, skip news

#136653 gh-136616: Improve `assert` syntax error messages
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-07-14-17-01-23.gh-issue-136616.FQjXE_.rst
  Parser/parser.c
Labels: awaiting merge

#138715 gh-135953: Add flamegraph reporter to sampling profiler
  .gitattributes
  Doc/license.rst
  Lib/profiling/sampling/_assets/python-logo-only.png
  Lib/profiling/sampling/_vendor/d3-flame-graph/4.1.3/d3-flamegraph-tooltip.min.js
  Lib/profiling/sampling/_vendor/d3-flame-graph/4.1.3/d3-flamegraph.css
  Lib/profiling/sampling/_vendor/d3-flame-graph/4.1.3/d3-flamegraph.min.js
  Lib/profiling/sampling/_vendor/d3/7.8.5/d3.min.js
  Lib/profiling/sampling/flamegraph.css
  Lib/profiling/sampling/flamegraph.js
  Lib/profiling/sampling/flamegraph_template.html
  Lib/profiling/sampling/sample.py
  Lib/profiling/sampling/stack_collector.py
  Lib/test/test_profiling/test_sampling_profiler.py
  Makefile.pre.in
Labels: awaiting merge, skip news

#138228 gh-138230: Remove dead code in code gen - codegen_check_annotation is only calle…
  Python/codegen.c
Labels: awaiting merge, skip news, type-refactor

#138718 gh-138716: Fix `assert a := b` syntax error message
  Grammar/python.gram
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-09-23-59-13.gh-issue-138716.UawDY0.rst
  Parser/parser.c
Labels: awaiting merge

#138390 [3.14] gh-136599: Add tests for long_hash (GH-138335)
  Lib/test/test_long.py
Labels: tests, awaiting merge, skip news

#138838 gh-129813, PEP 782: Use PyBytesWriter in _PyBytes_DecodeEscape2()
  Objects/bytesobject.c
Labels: awaiting core review, skip news

#138830 gh-129813, PEP 782: Use Py_GetConstant(Py_CONSTANT_EMPTY_BYTES)
  Modules/_bz2module.c
  Modules/_dbmmodule.c
  Modules/_lzmamodule.c
  Modules/zlibmodule.c
  Objects/bytesobject.c
  Objects/unicodeobject.c
Labels: awaiting core review, skip news

#138836 gh-129813, PEP 782: Use PyBytesWriter in memoryview
  Objects/memoryobject.c
Labels: awaiting core review, skip news

#138837 gh-129813, PEP 782: Use PyBytesWriter in _PyBytes_FromList()
  Objects/bytesobject.c
Labels: awaiting core review, skip news

#138758 [3.9] gh-138744: GitHub Actions: pin to `windows-2022` (GH-138743)
  .github/workflows/build.yml
  .github/workflows/build_msi.yml
Labels: awaiting core review, skip news

#137782 [3.11] gh-118350: Fix support of elements "textarea" and "title" in HTMLParser (GH-135310)
  Lib/html/parser.py
  Lib/test/test_htmlparser.py
  Misc/NEWS.d/next/Security/2025-06-09-20-38-25.gh-issue-118350.KgWCcP.rst
Labels: type-security, awaiting merge

#138002 [3.11] gh-137638: Remove macos-13 from GitHub Actions
  .github/workflows/reusable-macos.yml
Labels: awaiting merge, skip news, infra

#137783 [3.10] gh-118350: Fix support of elements "textarea" and "title" in HTMLParser (GH-135310)
  Lib/html/parser.py
  Lib/test/test_htmlparser.py
  Misc/NEWS.d/next/Security/2025-06-09-20-38-25.gh-issue-118350.KgWCcP.rst
Labels: type-security, awaiting merge

#138757 [3.10] gh-138744: GitHub Actions: pin to `windows-2022` (GH-138743)
  .github/workflows/build.yml
  .github/workflows/build_msi.yml
Labels: awaiting core review, skip news

#138873 gh-71810: Fix _PyLong_AsByteArray() undefined behavior
  Objects/longobject.c
Labels: awaiting merge, skip news, needs backport to 3.13, needs backport to 3.14

#138818 [3.13] gh-138669: Increase test coverage for difflib (GH-138670)
  Lib/test/test_difflib.py
Labels: tests, awaiting merge, skip news

#138880 gh-135953: Prevent overflow in the profiler flamegraph hover boxes
  Lib/profiling/sampling/flamegraph.css
  Lib/profiling/sampling/flamegraph.js
Labels: awaiting merge, skip news

#138797 gh-138794: Communicate to PyRefTracer when they are being replaced
  Doc/c-api/init.rst
  Include/cpython/object.h
  Misc/NEWS.d/next/Core_and_Builtins/2025-09-11-15-56-18.gh-issue-138794.nrOn1K.rst
  Modules/_testcapimodule.c
  Objects/object.c
Labels: awaiting core review

#137994 gh-137992: Stop the world when calling PyRefTracer_SetTracer
  Misc/NEWS.d/next/Core_and_Builtins/2025-08-20-14-17-47.gh-issue-137992.fcL3SK.rst
  Objects/object.c
Labels: awaiting merge

#138905 gh-138902: Fix generator send arg name
  Objects/genobject.c
Labels: awaiting merge, skip news

#138927 [3.13] gh-138779: Use the dev_t converter for st_rdev (GH-138780)
  Misc/NEWS.d/next/Library/2025-09-11-11-09-28.gh-issue-138779.TNZnLr.rst
  Modules/posixmodule.c
Labels: awaiting review

#135000 gh-134953: Expand theming for `True`/`False`/`None`
  Lib/_colorize.py
  Lib/_pyrepl/utils.py
  Misc/NEWS.d/next/Library/2025-06-01-11-14-00.gh-issue-134953.ashdfs.rst
Labels: awaiting review, needs backport to 3.14

#138933 GH-132732: Remove textwrap import
  Tools/cases_generator/optimizer_generator.py
Labels: awaiting merge, skip news

#136048 gh-132732: Clear errors in JIT optimizer on error
  Python/optimizer_analysis.c
Labels: awaiting merge, skip news

#138089 gh-128636: Fix crash in PyREPL when os.environ is overwritten with an invalid value for mac
  Lib/_colorize.py
  Lib/_pyrepl/unix_console.py
  Lib/test/support/__init__.py
  Lib/test/test_pyrepl/test_unix_console.py
  Misc/NEWS.d/next/Library/2025-09-10-10-02-59.gh-issue-128636.ldRKGZ.rst
Labels: awaiting review

#138934 [3.13] gh-131189: Fix "msvcrt" import warning on Linux when "_ctypes" is not available. (GH-131201)
  Lib/_pyrepl/readline.py
Labels: awaiting review, skip news

#138922 gh-129813, PEP 782: Use PyBytesWriter in _hashopenssl
  Modules/_hashopenssl.c
Labels: awaiting merge, skip news

#138955 gh-129813, PEP 782: Use PyBytesWriter in FileIO.read()
  Modules/_io/fileio.c
Labels: awaiting core review, skip news

#138942 [3.13] gh-128636: Fix crash in PyREPL when os.environ is overwritten with an invalid value for macOS (GH-138089)
  Lib/_colorize.py
  Lib/_pyrepl/unix_console.py
  Lib/test/support/__init__.py
  Lib/test/test_pyrepl/test_unix_console.py
  Misc/NEWS.d/next/Library/2025-09-10-10-02-59.gh-issue-128636.ldRKGZ.rst
Labels: awaiting core review

#138628 Re-order Modules/makesetup in CODEOWNERS and add Adam Turner
  .github/CODEOWNERS
Labels: skip issue, awaiting merge, skip news
