Repository python/cpython, pull requests merged in 2025-04, with the labels that each got.

#131532 gh-131531: Add `android.py package` command
  Android/README.md
  Android/android.py
  Android/testbed/.gitignore
  Android/testbed/.idea/inspectionProfiles/Project_Default.xml
  Android/testbed/app/build.gradle.kts
  Android/testbed/app/src/main/c/CMakeLists.txt
  Doc/using/android.rst
Labels: awaiting merge, skip news, needs backport to 3.13

#131960 [3.13] gh-131531: Add `android.py package` command (GH-131532)
  Android/README.md
  Android/android.py
  Android/testbed/.gitignore
  Android/testbed/.idea/inspectionProfiles/Project_Default.xml
  Android/testbed/app/build.gradle.kts
  Android/testbed/app/src/main/c/CMakeLists.txt
  Doc/using/android.rst
Labels: awaiting merge, skip news

#125958 gh-125957: sync argument naming in sphinx docs of the cmath and help()
  Doc/library/cmath.rst
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#131867 gh-121249: Note struct module changes in What's New
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#127261 Minor improvements to faq/programming.rst
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting core review, skip news, needs backport to 3.12, needs backport to 3.13

#131962 [3.13] gh-125957: sync argument naming in sphinx docs of the cmath and help() (GH-125958)
  Doc/library/cmath.rst
Labels: docs, awaiting merge, skip news

#131963 [3.12] gh-125957: sync argument naming in sphinx docs of the cmath and help() (GH-125958)
  Doc/library/cmath.rst
Labels: docs, awaiting merge, skip news

#131964 [3.13] Minor improvements to the programming FAQ (GH-127261)
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting merge, skip news

#131965 [3.12] Minor improvements to the programming FAQ (GH-127261)
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting merge, skip news

#131739 gh-131736: Only do seclevel workaround if seclevel greater than 1
  Lib/test/test_ssl.py
Labels: tests, awaiting merge, skip news

#131966 [3.12] gh-131736: only apply `security_level` workaround in `test_ssl` for security levels greater than 1 (GH-131739)
  Lib/test/test_ssl.py
Labels: tests, awaiting merge, skip news

#131363 [3.10] gh-131261: Update libexpat to 2.7.0 (CVE-2024-8176) (GH-131272)
  Misc/NEWS.d/next/Security/2025-03-14-23-28-39.gh-issue-131261.0aB6nM.rst
  Modules/expat/expat.h
  Modules/expat/refresh.sh
  Modules/expat/xmlparse.c
Labels: type-security, awaiting merge, release-blocker

#131668 gh-111178: Fix getsockaddrarg() undefined behavior
  Misc/NEWS.d/next/Library/2025-03-28-11-26-31.gh-issue-131668.tcS4xS.rst
  Modules/socketmodule.c
Labels: skip news, needs backport to 3.12, needs backport to 3.13

#131977 [3.13] gh-111178: Fix getsockaddrarg() undefined behavior (#131668)
  Misc/NEWS.d/next/Library/2025-03-28-11-26-31.gh-issue-131668.tcS4xS.rst
  Modules/socketmodule.c
Labels: skip news

#131673 gh-111178: remove redundant casts for functions with correct signatures
  Modules/_asynciomodule.c
  Modules/_cursesmodule.c
  Modules/_functoolsmodule.c
  Modules/_interpchannelsmodule.c
  Modules/_io/textio.c
  Modules/_io/winconsoleio.c
  Modules/_lzmamodule.c
  Modules/_testcapi/docstring.c
  Modules/_testcapi/exceptions.c
  Modules/_testcapi/gc.c
  Modules/_testcapi/mem.c
  Modules/_testcapi/watchers.c
  Modules/_testinternalcapi.c
  Modules/_xxtestfuzz/_xxtestfuzz.c
  Modules/_zoneinfo.c
  Modules/atexitmodule.c
  Modules/cjkcodecs/cjkcodecs.h
  Modules/faulthandler.c
  Objects/boolobject.c
  Objects/bytearrayobject.c
  Objects/dictobject.c
  Objects/genericaliasobject.c
  Objects/listobject.c
  Objects/longobject.c
  Objects/object.c
  Objects/rangeobject.c
  Objects/stringlib/unicode_format.h
  Objects/unicodeobject.c
  Objects/unionobject.c
  Python/hamt.c
Labels: skip news

#131593 GH-131296: fix clang-cl warning on Windows in sre.c
  Modules/_sre/sre.c
Labels: awaiting review, skip news

#130708 gh-130704: Strength reduce `LOAD_FAST{_LOAD_FAST}`
  Doc/library/dis.rst
  Include/internal/pycore_frame.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_stackref.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Include/opcode_ids.h
  Lib/_opcode_metadata.py
  Lib/dis.py
  Lib/test/test_capi/test_opt.py
  Lib/test/test_ctypes/test_memfunctions.py
  Lib/test/test_ctypes/test_refcounts.py
  Lib/test/test_ctypes/test_stringptr.py
  Lib/test/test_dis.py
  Lib/test/test_frame.py
  Lib/test/test_generators.py
  Lib/test/test_importlib/test_abc.py
  Lib/test/test_peepholer.py
  Lib/test/test_sys.py
  Lib/test/test_traceback.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-28-11-29-35.gh-issue-130704.7RDVLE.rst
  Objects/floatobject.c
  Objects/frameobject.c
  Programs/test_frozenmain.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/flowgraph.c
  Python/gc.c
  Python/generated_cases.c.h
  Python/opcode_targets.h
  Python/optimizer_analysis.c
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/opcode_metadata_generator.py
Labels: awaiting merge

#131833 gh-131831: Implement PEP 758 – Allow except and except* expressions without parentheses
  Doc/reference/compound_stmts.rst
  Doc/whatsnew/3.14.rst
  Grammar/python.gram
  Lib/test/test_grammar.py
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-28-18-59-24.gh-issue-131833.v4WvWT.rst
  Parser/parser.c
Labels: awaiting merge

#131991 gh-131987: Bump the magic number
  Include/internal/pycore_magic_number.h
Labels: awaiting merge, skip news

#131800 GH-131798: Allow the JIT to remove more `int`/`float`/`str` guards
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-27-12-40-21.gh-issue-131800.Xq3n54.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: performance, awaiting core review, interpreter-core, topic-JIT

#131810 GH-131726: Split up `_CHECK_VALIDITY_AND_SET_IP`
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/optimizer.c
  Python/optimizer_analysis.c
  Python/optimizer_cases.c.h
Labels: awaiting core review, skip news, interpreter-core, topic-JIT

#131985 [3.13] Backport miscellaneous Android testbed changes
  Android/README.md
  Android/testbed/app/build.gradle.kts
  Android/testbed/app/src/main/c/main_activity.c
Labels: skip issue, awaiting merge, skip news

#128070 GH-128055: fix test_sysconfigdata_json outside the builddir
  Lib/test/test_sysconfig.py
  Misc/NEWS.d/next/Library/2024-12-18-15-51-09.gh-issue-128055.0c_Noq.rst
Labels: tests, awaiting core review

#131902 gh-130197: pygettext: Test the `--escape` option
  Lib/test/test_tools/i18n_data/ascii-escapes.pot
  Lib/test/test_tools/i18n_data/escapes.pot
  Lib/test/test_tools/i18n_data/escapes.py
  Lib/test/test_tools/test_i18n.py
  Tools/i18n/pygettext.py
Labels: awaiting merge, skip news

#132003 gh-132002: Fix crash of `ContextVar` on unhashable `str` subtype
  Lib/test/test_context.py
  Misc/NEWS.d/next/Library/2025-04-02-11-31-15.gh-issue-132002.TMsYvE.rst
  Python/context.c
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#132008 [3.12] gh-132002: Fix crash of `ContextVar` on unhashable `str` subtype (GH-132003)
  Lib/test/test_context.py
  Misc/NEWS.d/next/Library/2025-04-02-11-31-15.gh-issue-132002.TMsYvE.rst
  Python/context.c
Labels: awaiting merge

#132007 [3.13] gh-132002: Fix crash of `ContextVar` on unhashable `str` subtype (GH-132003)
  Lib/test/test_context.py
  Misc/NEWS.d/next/Library/2025-04-02-11-31-15.gh-issue-132002.TMsYvE.rst
  Python/context.c
Labels: awaiting merge

#131889 gh-131888: fix ResourceWarning in test_ftplib
  Lib/test/test_ftplib.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#132010 [3.12] gh-131888: fix ResourceWarning in test_ftplib (GH-131889)
  Lib/test/test_ftplib.py
Labels: tests, awaiting review, skip news

#132009 [3.13] gh-131888: fix ResourceWarning in test_ftplib (GH-131889)
  Lib/test/test_ftplib.py
Labels: tests, awaiting review, skip news

#132012 gh-59705: Fix solaris detection in test_set_name
  Lib/test/test_threading.py
Labels: tests, awaiting merge, skip news

#132015 gh-131544: Update docs for PyType_AddWatcher
  Doc/c-api/type.rst
Labels: awaiting merge, skip news, needs backport to 3.13

#131975 gh-131974: Fix usages of `locked_deref` in `ctypes`
  Misc/NEWS.d/next/Library/2025-04-01-09-20-32.gh-issue-131974.AIzshA.rst
  Modules/_ctypes/_ctypes.c
Labels: awaiting merge, topic-ctypes, topic-free-threading

#131948 GH-131498: Cases generator: Parse down to C statement level.
  Lib/test/test_generated_cases.py
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Tools/cases_generator/analyzer.py
  Tools/cases_generator/cwriter.py
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/lexer.py
  Tools/cases_generator/optimizer_generator.py
  Tools/cases_generator/parser.py
  Tools/cases_generator/parsing.py
  Tools/cases_generator/plexer.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#131953 gh-118761: Optimise import time for ast
  .github/CODEOWNERS
  Lib/_ast_unparse.py
  Lib/ast.py
  Lib/test/test_ast/test_ast.py
  Misc/NEWS.d/next/Library/2025-03-31-19-19-36.gh-issue-118761.M0yFiZ.rst
  Python/stdlib_module_names.h
Labels: awaiting merge

#132019 [3.13] gh-131544: Update docs for PyType_AddWatcher (gh-132015)
  Doc/c-api/type.rst
Labels: docs, awaiting merge, skip news

#132020 gh-111178: Skip test_perf_profiler on function sanitizer
  Lib/test/support/__init__.py
  Lib/test/test_perf_profiler.py
Labels: awaiting core review, skip news

#131239 [3.12] gh-89039: Call subclass constructors in datetime.*.replace (GH-114780)
  Lib/test/datetimetester.py
  Misc/NEWS.d/next/Library/2023-12-18-20-10-50.gh-issue-89039.gqFdtU.rst
  Modules/_datetimemodule.c
Labels: awaiting core review

#132025 gh-118761: Fix star-import of ast (alternative)
  Lib/_ast_unparse.py
  Lib/ast.py
Labels: awaiting merge, skip news

#132033 [3.12] gh-130197: pygettext: Test the --escape option (GH-131902)
  Lib/test/test_tools/i18n_data/ascii-escapes.pot
  Lib/test/test_tools/i18n_data/escapes.pot
  Lib/test/test_tools/i18n_data/escapes.py
  Lib/test/test_tools/test_i18n.py
  Tools/i18n/pygettext.py
Labels: awaiting review, skip news

#132032 [3.13] gh-130197: pygettext: Test the --escape option (GH-131902)
  Lib/test/test_tools/i18n_data/ascii-escapes.pot
  Lib/test/test_tools/i18n_data/escapes.pot
  Lib/test/test_tools/i18n_data/escapes.py
  Lib/test/test_tools/test_i18n.py
  Tools/i18n/pygettext.py
Labels: awaiting review, skip news

#131638 gh-60115: Support frozen modules for linecache.getline()
  Doc/library/linecache.rst
  Doc/whatsnew/3.14.rst
  Lib/linecache.py
  Lib/test/test_linecache.py
  Misc/NEWS.d/next/Library/2025-03-23-18-39-07.gh-issue-60115.AWdcmq.rst
Labels: awaiting merge

#132034 Remove deferred ``typing`` import in ``annotationlib``
  Lib/annotationlib.py
Labels: skip issue, awaiting merge, skip news

#132022 GH-131904: Fix Py_STACKREF_DEBUG build
  Include/internal/pycore_stackref.h
  Python/stackrefs.c
Labels: awaiting merge, skip news

#131971 [3.10] gh-127257: ssl: Raise OSError for ERR_LIB_SYS (GH-127361) (GH-127905)
  Misc/NEWS.d/next/Library/2024-11-28-14-14-46.gh-issue-127257.n6-jU9.rst
  Modules/_ssl.c
Labels: awaiting core review

#131405 [3.11] gh-121284: Fix email address header folding with parsed encoded-word (GH-122754)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Security/2024-08-06-12-27-34.gh-issue-121284.8rwPxe.rst
Labels: type-security, awaiting merge, topic-email

#131411 [3.10] gh-121284: Fix email address header folding with parsed encoded-word (GH-122754)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Security/2024-08-06-12-27-34.gh-issue-121284.8rwPxe.rst
Labels: type-security, awaiting merge, topic-email

#131412 [3.9] gh-121284: Fix email address header folding with parsed encoded-word (GH-122754)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Security/2024-08-06-12-27-34.gh-issue-121284.8rwPxe.rst
Labels: type-security, awaiting merge, topic-email

#131362 [3.11] gh-131261: Update libexpat to 2.7.0 (CVE-2024-8176) (GH-131272)
  Misc/NEWS.d/next/Security/2025-03-14-23-28-39.gh-issue-131261.0aB6nM.rst
  Modules/expat/expat.h
  Modules/expat/refresh.sh
  Modules/expat/xmlparse.c
Labels: type-security, awaiting merge, release-blocker

#132051 gh-131423: Update OpenSSL build tag to 3.0.16.2 to fix ARM64 crash
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: OS-windows, skip news, needs backport to 3.12, needs backport to 3.13

#128930 gh-128661: Remove DeprecationWarning in evaluate_forward_ref
  Doc/library/annotationlib.rst
  Doc/library/typing.rst
  Lib/test/test_typing.py
  Lib/typing.py
Labels: awaiting core review, skip news

#129111 [3.10] gh-80222: Fix email address header folding with long quoted-string (GH-122753)
  Lib/email/_header_value_parser.py
  Lib/test/test_email/test__header_value_parser.py
  Misc/NEWS.d/next/Security/2024-08-06-11-43-08.gh-issue-80222.wfR4BU.rst
Labels: type-security, awaiting core review, release-blocker, topic-email

#132039 gh-132038: Make perf version check in test_perf_profiler more robust
  Lib/test/test_perf_profiler.py
Labels: tests, awaiting merge, skip news

#132053 [3.12] gh-131423: Update OpenSSL build tag to 3.0.16.2 to fix ARM64 crash. (GH-132051)
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: awaiting core review, skip news

#132052 [3.13] gh-131423: Update OpenSSL build tag to 3.0.16.2 to fix ARM64 crash (GH-132051)
  PCbuild/get_externals.bat
  PCbuild/python.props
Labels: awaiting review, skip news

#131994 Enable Windows on Arm GitHub runners
  .github/workflows/build.yml
  .github/workflows/jit.yml
  .github/workflows/reusable-windows-msi.yml
  .github/workflows/reusable-windows.yml
Labels: skip issue, awaiting review, skip news

#132023 Add tests for Bluetooth RFCOMM, HCI and SCO
  Lib/test/test_socket.py
Labels: tests, skip issue, awaiting merge, skip news

#132016 gh-125434: Display thread name in faulthandler
  Lib/test/test_faulthandler.py
  Misc/NEWS.d/next/Library/2025-04-02-16-01-12.gh-issue-125434.EjPc7g.rst
  Python/traceback.c
Labels: awaiting merge

#131289 GH-131288: use _AddressOfReturnAddress in _Py_get_machine_stack_pointer to silence MSVC warning in pycore_ceval.h for release builds
  Include/internal/pycore_ceval.h
Labels: awaiting merge, skip news

#132061 gh-105499: Defer "import warnings" in typing
  Lib/typing.py
Labels: awaiting merge, skip news

#128744 gh-128632: fix segfault on nested __classdict__ type param
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-11-20-11-28.gh-issue-128632.ryhnKs.rst
  Python/assemble.c
  Python/symtable.c
Labels: awaiting merge, needs backport to 3.12, needs backport to 3.13

#131909 gh-130655: Add a test for bad magic numbers when parsing gettext MO files
  Lib/test/test_gettext.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#131911 gh-130655: Add a test for corrupt MO files in gettext
  Lib/test/test_gettext.py
Labels: tests, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#132059 gh-118761: Defer import of functools in annotationlib
  Lib/annotationlib.py
Labels: awaiting merge, skip news

#132076 gh-132075: Fix possible use of sockaddr structures with uninitialized members
  Misc/NEWS.d/next/Library/2025-04-04-16-22-03.gh-issue-132075.qMM5np.rst
  Modules/socketmodule.c
Labels: awaiting core review, needs backport to 3.12, needs backport to 3.13

#132087 [3.12] gh-132075: Fix possible use of sockaddr structures with uninitialized members (GH-132076)
  Misc/NEWS.d/next/Library/2025-04-04-16-22-03.gh-issue-132075.qMM5np.rst
  Modules/socketmodule.c
Labels: awaiting review

#130391 gh-130115: fix thread identifiers for 32-bit musl
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-21-00-12-24.gh-issue-130115.mF-rP6.rst
  Python/thread_pthread.h
Labels: awaiting merge

#132068 gh-100239: more refined specialisation stats for BINARY_OP/SUBSCR
  Include/cpython/pystats.h
  Python/specialize.c
  Tools/scripts/summarize_stats.py
Labels: awaiting merge, skip news

#132086 [3.13] gh-132075: Fix possible use of sockaddr structures with uninitialized members (GH-132076)
  Misc/NEWS.d/next/Library/2025-04-04-16-22-03.gh-issue-132075.qMM5np.rst
  Modules/socketmodule.c
Labels: awaiting review

#132083 [3.12] gh-130655: Add tests for `gettext.find()` (GH-130691)
  Lib/test/test_gettext.py
Labels: tests, awaiting review, skip news

#132084 [3.13] gh-130655: Add tests for `gettext.find()` (GH-130691)
  Lib/test/test_gettext.py
Labels: tests, awaiting review, skip news

#132077 [3.13] gh-130655: Add a test for bad magic numbers in `.mo` files parsed by `gettext` (GH-131909)
  Lib/test/test_gettext.py
Labels: tests, awaiting review, skip news

#132078 [3.12] gh-130655: Add a test for bad magic numbers in `.mo` files parsed by `gettext` (GH-131909)
  Lib/test/test_gettext.py
Labels: tests, awaiting review, skip news

#132079 [3.13] gh-130655: Add a test for corrupt `.mo` files in `gettext` (GH-131911)
  Lib/test/test_gettext.py
Labels: tests, awaiting review, skip news

#132080 [3.12] gh-130655: Add a test for corrupt `.mo` files in `gettext` (GH-131911)
  Lib/test/test_gettext.py
Labels: tests, awaiting review, skip news

#131972 gh-131938: Update error message for `Element.remove()` when an element is not found
  Lib/test/test_xml_etree.py
  Lib/xml/etree/ElementTree.py
  Misc/NEWS.d/next/Library/2025-04-01-13-44-26.gh-issue-131938.dm4Suq.rst
  Modules/_elementtree.c
Labels: awaiting merge, topic-XML

#132085 [3.13] gh-128632: fix segfault on nested __classdict__ type param (GH-128744)
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-11-20-11-28.gh-issue-128632.ryhnKs.rst
  Python/assemble.c
  Python/symtable.c
Labels: awaiting merge

#132090 [3.12] gh-128632: fix segfault on nested __classdict__ type param (GH…
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-11-20-11-28.gh-issue-128632.ryhnKs.rst
  Python/symtable.c
Labels: awaiting merge

#132060 gh-118761: Lazily import annotationlib in typing
  Lib/typing.py
Labels: awaiting merge, skip news

#132074 GH-131498: manage stacks automatically
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_stackref.h
  Include/internal/pycore_structs.h
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_cases.c.h
  Python/stackrefs.c
  Tools/cases_generator/generators_common.py
  Tools/cases_generator/optimizer_generator.py
  Tools/cases_generator/stack.py
  Tools/cases_generator/tier1_generator.py
  Tools/cases_generator/tier2_generator.py
Labels: awaiting merge, skip news

#130157 gh-99108: Implement HACL* HMAC
  Doc/whatsnew/3.14.rst
  Lib/hmac.py
  Lib/test/support/hashlib_helper.py
  Lib/test/test_hmac.py
  Makefile.pre.in
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-15-14-36-32.gh-issue-99108.u6CfmK.rst
  Misc/sbom.spdx.json
  Modules/Setup
  Modules/Setup.stdlib.in
  Modules/_hacl/Hacl_HMAC.c
  Modules/_hacl/Hacl_HMAC.h
  Modules/_hacl/Hacl_Streaming_HMAC.c
  Modules/_hacl/Hacl_Streaming_HMAC.h
  Modules/_hacl/README.md
  Modules/_hacl/internal/Hacl_HMAC.h
  Modules/_hacl/internal/Hacl_Streaming_HMAC.h
  Modules/_hacl/libintvector-shim.h
  Modules/_hacl/python_hacl_namespaces.h
  Modules/_hacl/refresh.sh
  Modules/clinic/hmacmodule.c.h
  Modules/hmacmodule.c
  PC/config.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/stdlib_module_names.h
  Tools/c-analyzer/cpython/_parser.py
  Tools/c-analyzer/cpython/ignored.tsv
  configure
  configure.ac
Labels: awaiting merge

#132093 gh-100239: fix bug in comparison
  Python/specialize.c
Labels: awaiting merge, skip news

#132094 Fix typo in `template_replace()` test helper docstring
  Lib/test/test_typing.py
Labels: tests, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#132096 [3.12] Fix typo in `template_replace()` test helper docstring (GH-132094)
  Lib/test/test_typing.py
Labels: tests, skip issue, awaiting review, skip news

#131941 gh-131933: Document UnionType/Union merger in What's New
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#132089 [3.13] gh-130115: fix thread identifiers for 32-bit musl (GH-130391)
  Misc/NEWS.d/next/Core_and_Builtins/2025-02-21-00-12-24.gh-issue-130115.mF-rP6.rst
  Python/thread_pthread.h
Labels: awaiting merge

#131969 gh-109599: Expose `CapsuleType` via the `_types` module
  Lib/types.py
  Modules/Setup
  Modules/Setup.bootstrap.in
  Modules/_typesmodule.c
  PC/config.c
  PCbuild/pythoncore.vcxproj
  PCbuild/pythoncore.vcxproj.filters
  Python/stdlib_module_names.h
  configure
  configure.ac
Labels: awaiting merge, skip news

#129465 gh-129463, gh-128593: Simplify ForwardRef
  Doc/library/annotationlib.rst
  Doc/library/typing.rst
  Doc/whatsnew/3.14.rst
  Lib/annotationlib.py
  Lib/test/support/__init__.py
  Lib/test/test_annotationlib.py
  Lib/test/test_inspect/test_inspect.py
  Lib/test/test_types.py
  Lib/test/test_typing.py
  Misc/NEWS.d/next/Library/2025-01-29-21-27-45.gh-issue-128593.r3j4l-.rst
  Misc/NEWS.d/next/Library/2025-01-29-21-29-46.gh-issue-129463.qePexX.rst
Labels: awaiting merge

#132030 gh-131912: Refactored description of grouping options in format specification docs
  Doc/library/string.rst
Labels: docs, awaiting merge, skip news

#131881 gh-131015: Add test for bytes formatting errors
  Lib/test/test_bytes.py
Labels: tests, awaiting merge, skip news

#132069 Docs: Fix document for `plistlib.load`
  Doc/library/plistlib.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#129607 gh-85162: Add HTTPSServer to http.server
  Doc/library/http.server.rst
  Doc/whatsnew/3.14.rst
  Lib/http/server.py
  Lib/test/test_httpservers.py
  Misc/NEWS.d/next/Library/2025-02-02-00-30-09.gh-issue-85162.BNF_aJ.rst
Labels: awaiting merge

#132116 [3.13] Docs: document `plistlib.InvalidFileException` (GH-132069)
  Doc/library/plistlib.rst
Labels: docs, skip issue, awaiting merge, skip news

#132115 [3.13] gh-131015: Add test for bytes formatting errors (#131881)
  Lib/test/test_bytes.py
Labels: tests, awaiting core review, skip news

#132114 [3.12] gh-131015: Add test for bytes formatting errors (#131881)
  Lib/test/test_bytes.py
Labels: tests, awaiting core review, skip news

#132082 gh-128182: add critical section to `_ctypes.PyCData` getters and setters
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/clinic/_ctypes.c.h
Labels: awaiting core review, skip news, topic-free-threading

#132081 gh-128182: add critical section to _ctypes.Simple getters and setters
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/clinic/_ctypes.c.h
Labels: awaiting core review, skip news, topic-ctypes, topic-free-threading

#132119 Docs: Fix typo in `InternalDocs/jit.md`
  InternalDocs/jit.md
Labels: docs, skip issue, awaiting core review, skip news

#132071 [3.13] Add tests for Bluetooth RFCOMM, HCI and SCO (GH-132023)
  Lib/test/test_socket.py
Labels: tests, skip issue, awaiting merge, skip news

#132072 Skip a test for Bluetooth HCI socket (added in GH-132023) if it fails
  Lib/test/test_socket.py
Labels: tests, skip issue, awaiting core review, skip news

#132125 [3.13] Skip a test for Bluetooth HCI socket (added in GH-132023) if it fails (GH-132072)
  Lib/test/test_socket.py
Labels: tests, skip issue, awaiting review, skip news

#132101 Generate social media preview cards for the documentation
  Doc/Makefile
  Doc/conf.py
  Doc/requirements.txt
Labels: docs, skip issue, awaiting merge, skip news

#128692 gh-126703: Add PyCFunction freelist
  Include/internal/pycore_freelist_state.h
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-09-22-12-03.gh-issue-126703.6rAxZ7.rst
  Objects/methodobject.c
  Objects/object.c
Labels: awaiting merge

#132112 gh-131591: Fix GENERATE_DEBUG_SECTION for clangcl on Windows
  Include/internal/pycore_debug_offsets.h
  Modules/_asynciomodule.c
  Tools/c-analyzer/cpython/ignored.tsv
Labels: awaiting merge, skip news

#132098 gh-132132: Upgrade LLVM on tail calling CI
  .github/workflows/tail-call.yml
Labels: skip issue, awaiting core review, skip news

#132103 GH-118761: Expose more core interpreter types in ``_types``
  Lib/test/test_types.py
  Lib/types.py
  Modules/_typesmodule.c
Labels: performance, awaiting merge, skip news

#130158 Fix numbered list syntax in programming.rst
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#132140 [3.13] Fix numbered list syntax in programming.rst (GH-130158)
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting merge, skip news

#132141 [3.12] Fix numbered list syntax in programming.rst (GH-130158)
  Doc/faq/programming.rst
Labels: docs, skip issue, awaiting merge, skip news

#131880 gh-131852: Filter out POT-Creation-Date in ``msgfmt``
  Lib/test/test_tools/msgfmt_data/general.json
  Lib/test/test_tools/msgfmt_data/general.mo
  Misc/NEWS.d/next/Tools-Demos/2025-03-29-16-20-00.gh-issue-131852.afuefb.rst
  Tools/i18n/msgfmt.py
Labels: awaiting merge

#132057 gh-131798: JIT: Narrow the return type of `_CONTAINS_OP_SET` to bool
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-04-03-20-11-02.gh-issue-131798.yhdUKW.rst
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
Labels: awaiting merge

#132135 gh-132134: Add to `.cache` directory .gitignore file
  .gitignore
Labels: awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#132145 [3.12] gh-132134: Add the clangd ``.cache`` directory to ``.gitignore`` (GH-132135)
  .gitignore
Labels: awaiting merge, skip news

#132144 [3.13] gh-132134: Add the clangd ``.cache`` directory to ``.gitignore`` (GH-132135)
  .gitignore
Labels: awaiting merge, skip news

#132137 Replace dead hyperlink for CGI environment variables
  Lib/http/server.py
Labels: skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#132151 [3.12] Docs: Replace dead hyperlink for CGI environment variables (GH-132137)
  Lib/http/server.py
Labels: skip issue, awaiting review, skip news

#132150 [3.13] Docs: Replace dead hyperlink for CGI environment variables (GH-132137)
  Lib/http/server.py
Labels: skip issue, awaiting review, skip news

#132058 [3.13] gh-132038: Make perf version check in test_perf_profiler more robust (GH-132039)
  Lib/test/test_perf_profiler.py
Labels: tests, awaiting core review, skip news

#132152 gh-128182: add critical sections to ctypes arrays getters and setters
  Modules/_ctypes/_ctypes.c
  Modules/_ctypes/clinic/_ctypes.c.h
Labels: awaiting core review, skip news, topic-ctypes

#132146 gh-132139: Document that you can no longer set attributes on unions
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#131275 gh-131178: Add tests for `pickle` command-line interface
  Lib/pickle.py
  Lib/test/test_pickle.py
Labels: awaiting merge, skip news

#132157 gh-132139: 3.14 what's new: elaborate on why you can no longer set `Union` attributes
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news, topic-typing

#132018 gh-132011: Fix crash on invalid `CALL_LIST_APPEND` deoptimization
  Lib/test/test_list.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-04-02-17-47-14.gh-issue-132011.dNh64H.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
Labels: awaiting merge

#132160 gh-132159: Do not shadow user arguments in generated `__new__` by `@warnings.deprecated`
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2025-04-06-16-12-49.gh-issue-132159.WvBfBm.rst
Labels: awaiting merge, needs backport to 3.13

#132163 [3.13] gh-132159: Do not shadow user arguments in generated `__new__` by `@warnings.deprecated` (GH-132160)
  Lib/test/test_warnings/__init__.py
  Lib/warnings.py
  Misc/NEWS.d/next/Library/2025-04-06-16-12-49.gh-issue-132159.WvBfBm.rst
Labels: awaiting review

#132161 [3.13] gh-132011: Fix crash on invalid `CALL_LIST_APPEND` deoptimization (GH-132018)
  Lib/test/test_list.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-04-02-17-47-14.gh-issue-132011.dNh64H.rst
  Python/bytecodes.c
  Python/generated_cases.c.h
Labels: awaiting core review

#107841 [3.12] GH-107674: Avoid allocating boxed ints for `sys.settrace` line events (GH-107780)
  Misc/NEWS.d/next/Core and Builtins/2023-08-05-04-47-18.gh-issue-107674.0sYhR2.rst
  Python/instrumentation.c
Labels: awaiting merge

#132050 gh-131591: Handle includes for iOS in remote_debugging.c
  Include/internal/pycore_ceval.h
  Python/remote_debugging.c
Labels: awaiting merge, skip news

#128619 gh-126703: Add freelist for range and range_iter objects
  Include/internal/pycore_freelist_state.h
  Misc/NEWS.d/next/Core_and_Builtins/2025-01-08-09-41-25.gh-issue-126703.djs9e_.rst
  Objects/object.c
  Objects/rangeobject.c
Labels: awaiting merge

#132165 gh-84481: Add ZipFile.data_offset attribute
  Doc/library/zipfile.rst
  Lib/test/test_zipfile/test_core.py
  Lib/zipfile/__init__.py
  Misc/NEWS.d/next/Library/2025-04-06-09-55-43.gh-issue-84481.cX4yTn.rst
Labels: awaiting merge

#132169 gh-132168: Add `__class_getitem__` to `ctypes.py_object`
  Doc/library/ctypes.rst
  Doc/whatsnew/3.14.rst
  Lib/ctypes/__init__.py
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Library/2025-04-06-13-23-41.gh-issue-132168.6UMEpo.rst
Labels: awaiting merge

#131887 Add a single table as summary to cmath documentation
  Doc/library/cmath.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.12, needs backport to 3.13

#132179 [3.13] Docs: Add a single table summary for ``cmath`` (GH-131887)
  Doc/library/cmath.rst
Labels: docs, skip issue, awaiting merge, skip news

#132180 [3.12] Docs: Add a single table summary for ``cmath`` (GH-131887)
  Doc/library/cmath.rst
Labels: docs, skip issue, awaiting merge, skip news

#132187 [3.13] gh-91132: Update macOS installer to use ncurses 6.5. (GH-129990)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-02-10-22-08-37.gh-issue-91132.00x1MI.rst
Labels: awaiting merge

#132188 [3.12] gh-91132: Update macOS installer to use ncurses 6.5. (GH-129990)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-02-10-22-08-37.gh-issue-91132.00x1MI.rst
Labels: awaiting merge

#132184 gh-129204: Add _PYTHON_SUBPROCESS_USE_POSIX_SPAWN environment knob
  Lib/subprocess.py
  Misc/NEWS.d/next/Library/2025-04-06-19-25-12.gh-issue-129204.sAVFO6.rst
Labels: awaiting merge

#132189 gh-131423: Update macOS installer to use OpenSSL 3.0.16.
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-04-06-23-24-00.gh-issue-131423.4UcBKy.rst
Labels: OS-mac, awaiting core review, needs backport to 3.12, needs backport to 3.13

#132196 [3.13] gh-131423: Update macOS installer to use OpenSSL 3.0.16. (GH-132189)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-04-06-23-24-00.gh-issue-131423.4UcBKy.rst
Labels: awaiting merge

#132197 [3.12] gh-131423: Update macOS installer to use OpenSSL 3.0.16. (GH-132189)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-04-06-23-24-00.gh-issue-131423.4UcBKy.rst
Labels: awaiting merge

#132190 gh-124111: Update macOS installer to use Tcl/Tk 8.6.16.
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-04-06-23-39-47.gh-issue-124111.2JI7iE.rst
Labels: OS-mac, awaiting core review, needs backport to 3.12, needs backport to 3.13

#132198 [3.13] gh-124111: Update macOS installer to use Tcl/Tk 8.6.16. (GH-132190)
  Mac/BuildScript/build-installer.py
  Misc/NEWS.d/next/macOS/2025-04-06-23-39-47.gh-issue-124111.2JI7iE.rst
Labels: awaiting merge

#132191 [3.13] gh-129204: Add _PYTHON_SUBPROCESS_USE_POSIX_SPAWN environment knob (GH-132184)
  Lib/subprocess.py
  Misc/NEWS.d/next/Library/2025-04-06-19-25-12.gh-issue-129204.sAVFO6.rst
Labels: awaiting review

#132203 [3.12] gh-131912: Refactor description of grouping options in format specification docs (GH-132030)
  Doc/library/string.rst
Labels: docs, awaiting core review, skip news

#132120 gh-99108: add support for SIMD-accelerated HMAC-BLAKE2
  Modules/hmacmodule.c
Labels: awaiting merge, skip news

#132208 [3.12] gh-122040: reword `Modules/xxmodule.c` module-level comment (GH-132201)
  Modules/xxmodule.c
Labels: awaiting merge, skip news

#132175 gh-132174: Fix function name in error message of `_interpreters.run_string`
  Misc/NEWS.d/next/Library/2025-04-06-23-16-08.gh-issue-132174.dN4b-X.rst
  Modules/_interpretersmodule.c
Labels: awaiting merge, topic-subinterpreters, needs backport to 3.13

#132207 [3.13] gh-122040: reword `Modules/xxmodule.c` module-level comment (GH-132201)
  Modules/xxmodule.c
Labels: awaiting merge, skip news

#15079 gh-61456: Add Thai language codec aliases
  Lib/encodings/aliases.py
  Misc/NEWS.d/next/Library/2019-08-05-13-58-10.bpo-17254.11xglZ.rst
Labels: awaiting review

#132216 [3.12] gh-131852: Filter out POT-Creation-Date in msgfmt (GH-131880)
  Lib/test/test_tools/msgfmt_data/general.json
  Lib/test/test_tools/msgfmt_data/general.mo
  Misc/NEWS.d/next/Tools-Demos/2025-03-29-16-20-00.gh-issue-131852.afuefb.rst
  Tools/i18n/msgfmt.py
Labels: awaiting review
