Repository python/cpython, pull requests merged in 2025-05, with the labels that each got.

#133184 gh-133183: Include IPHONEOS_DEPLOYMENT_TARGET in iOS shim targets.
  Misc/NEWS.d/next/Build/2025-04-30-11-07-53.gh-issue-133183.zCKUeQ.rst
  iOS/Resources/bin/arm64-apple-ios-clang
  iOS/Resources/bin/arm64-apple-ios-clang++
  iOS/Resources/bin/arm64-apple-ios-cpp
  iOS/Resources/bin/arm64-apple-ios-simulator-clang
  iOS/Resources/bin/arm64-apple-ios-simulator-clang++
  iOS/Resources/bin/arm64-apple-ios-simulator-cpp
  iOS/Resources/bin/x86_64-apple-ios-simulator-clang
  iOS/Resources/bin/x86_64-apple-ios-simulator-clang++
  iOS/Resources/bin/x86_64-apple-ios-simulator-cpp
Labels: awaiting merge, needs backport to 3.13

#133226 Bump the HACL* revision.
  Misc/sbom.spdx.json
  Modules/_hacl/Lib_Memzero0.c
  Modules/_hacl/refresh.sh
Labels: skip issue, awaiting core review, skip news

#133234 [3.13] gh-133183: Include IPHONEOS_DEPLOYMENT_TARGET in iOS shim targets. (GH-133184)
  Misc/NEWS.d/next/Build/2025-04-30-11-07-53.gh-issue-133183.zCKUeQ.rst
  iOS/Resources/bin/arm64-apple-ios-clang
  iOS/Resources/bin/arm64-apple-ios-clang++
  iOS/Resources/bin/arm64-apple-ios-cpp
  iOS/Resources/bin/arm64-apple-ios-simulator-clang
  iOS/Resources/bin/arm64-apple-ios-simulator-clang++
  iOS/Resources/bin/arm64-apple-ios-simulator-cpp
  iOS/Resources/bin/x86_64-apple-ios-simulator-clang
  iOS/Resources/bin/x86_64-apple-ios-simulator-clang++
  iOS/Resources/bin/x86_64-apple-ios-simulator-cpp
Labels: awaiting merge

#133174 Fix typo at _interpretersmodule.c file
  Modules/_interpretersmodule.c
Labels: skip issue, awaiting merge, skip news

#130170 gh-130167: Improve speed of `difflib.IS_LINE_JUNK` by replacing `re`
  Lib/difflib.py
  Misc/NEWS.d/next/Library/2025-02-16-06-25-01.gh-issue-130167.kUg7Rc.rst
Labels: awaiting merge

#133193 gh-131531: Make Android build retry after network failures
  Android/README.md
  Android/android.py
Labels: awaiting merge, skip news, needs backport to 3.13

#133236 [3.13] gh-131531: Make Android build retry after network failures (GH-133193)
  Android/README.md
  Android/android.py
Labels: awaiting merge, skip news

#133225 gh-133196: Guard PEP 750 grammar with `CHECK_VERSION`
  Grammar/python.gram
  Lib/test/test_ast/test_ast.py
  Parser/parser.c
Labels: awaiting merge, skip news

#133124 Lint: Create a project-wide ``.ruff.toml`` settings file
  .ruff.toml
  Doc/.ruff.toml
  Lib/test/.ruff.toml
  Tools/build/.ruff.toml
  Tools/clinic/.ruff.toml
Labels: skip issue, awaiting merge, skip news

#133245 PyStats: Make sure that the `failure_kinds` array is big enough.
  Include/cpython/pystats.h
  Python/specialize.c
Labels: skip issue, awaiting merge, skip news

#132622 Remove duplicate includes: Python/{bytecodes,ceval,optimizer_analysis}.c
  Python/bytecodes.c
  Python/ceval.c
  Python/optimizer_analysis.c
Labels: skip issue, awaiting core review, skip news

#132282 [3.13] gh-132246: Add PEP 688 to C Buffer Protocol docs (GH-132249)
  Doc/c-api/buffer.rst
Labels: docs, awaiting review, skip news

#132469 gh-130655: Add a test for big-endian MO files in `gettext`
  Lib/test/test_gettext.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13

#133248 [3.13] gh-130655: Add a test for big-endian MO files in gettext (GH-132469)
  Lib/test/test_gettext.py
Labels: tests, awaiting review, skip news

#133199 gh-124715: Fix method_dealloc(): use PyObject_GC_UnTrack()
  Objects/classobject.c
Labels: awaiting core review, skip news

#133240 gh-133166: Fix missing error emission of PyType_GetModuleByDef
  Lib/test/test_capi/test_type.py
  Misc/NEWS.d/next/C_API/2025-05-01-01-02-11.gh-issue-133166.Ly9Ae2.rst
  Modules/_testcapi/heaptype.c
  Objects/typeobject.c
Labels: awaiting review

#133048 gh-130197: Improve test coverage of `msgfmt.py`
  Lib/test/test_tools/test_msgfmt.py
Labels: tests, awaiting merge, skip news

#133246 gh-132930: Include IDLE path in registry for PyManager packages
  PC/layout/support/pymanager.py
Labels: OS-windows, awaiting core review, skip news

#133204 gh-130317: fix test_pack_unpack_roundtrip() and add docs
  Doc/c-api/float.rst
  Lib/test/test_capi/test_float.py
  Modules/_testcapi/clinic/float.c.h
  Modules/_testcapi/float.c
  Objects/floatobject.c
Labels: awaiting review, skip news

#133257 gh-133256: Add _Py_NONSTRING macro
  Include/internal/pycore_debug_offsets.h
  Include/pyport.h
  Modules/fcntlmodule.c
Labels: awaiting merge, skip news

#133250 gh-133210: Fix `test_inspect` in `--without-doc-strings` mode
  Lib/test/test_inspect/test_inspect.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13

#133041 gh-130197: Test `pygettext` output option
  Lib/test/test_tools/test_i18n.py
Labels: tests, awaiting merge, skip news

#133263 [3.13] gh-133210: Fix `test_inspect` in `--without-doc-strings` mode (GH-133250)
  Lib/test/test_inspect/test_inspect.py
Labels: tests, awaiting merge, skip news

#133269 gh-133261: Use __builtin_frame_address() on GCC 9 and older
  Include/internal/pycore_pystate.h
Labels: awaiting core review, skip news

#133268 gh-133259: Show path to python.sh script on successful build
  Tools/wasm/wasi.py
Labels: awaiting merge, skip news

#132055 gh-119605: Respect `follow_wrapped` for `__init__` and `__new__` when getting class signature with `inspect.signature`
  Lib/inspect.py
  Lib/test/test_inspect/test_inspect.py
  Lib/test/test_warnings/__init__.py
  Misc/NEWS.d/next/Library/2025-04-03-17-19-42.gh-issue-119605.c7QXAA.rst
Labels: awaiting merge, needs backport to 3.13

#133277 [3.13] gh-119605: Respect `follow_wrapped` for `__init__` and `__new__` when getting class signature with `inspect.signature` (GH-132055)
  Lib/inspect.py
  Lib/test/test_inspect/test_inspect.py
  Lib/test/test_warnings/__init__.py
  Misc/NEWS.d/next/Library/2025-04-03-17-19-42.gh-issue-119605.c7QXAA.rst
Labels: awaiting merge

#133255 [3.13] gh-130197: Improve test coverage of msgfmt.py (GH-133048)
  Lib/test/test_tools/test_msgfmt.py
Labels: tests, awaiting merge, skip news

#133082 gh-123299: Add missing pending removals
  Doc/deprecations/index.rst
  Doc/deprecations/pending-removal-in-3.16.rst
  Doc/deprecations/pending-removal-in-3.17.rst
  Doc/whatsnew/3.12.rst
  Doc/whatsnew/3.13.rst
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#133271 gh-133210: Fix `test_pydoc` in `--without-doc-strings` mode
  Lib/test/test_pydoc/test_pydoc.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13

#133288 [3.13] gh-133210: Fix `test_pydoc` in `--without-doc-strings` mode (GH-133271)
  Lib/test/test_pydoc/test_pydoc.py
Labels: tests, awaiting review, skip news

#133242 gh-133197: Improve error message for incompatible string / bytes prefixes
  Lib/test/test_fstring.py
  Lib/test/test_grammar.py
  Lib/test/test_syntax.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-01-11-06-29.gh-issue-133197.BHjfh4.rst
  Parser/lexer/lexer.c
Labels: awaiting merge

#130502 gh-130482: Add ability to specify name for `tkinter.OptionMenu` and `tkinter.ttk.OptionMenu`
  Doc/whatsnew/3.14.rst
  Lib/test/test_tkinter/test_widgets.py
  Lib/test/test_ttk/test_extensions.py
  Lib/tkinter/__init__.py
  Lib/tkinter/ttk.py
  Misc/NEWS.d/next/Library/2025-02-24-12-22-51.gh-issue-130482.p2DrrL.rst
Labels: awaiting merge

#133283 Docs: delete title links in `turtle.rst` and `typing.rst`
  Doc/library/turtle.rst
  Doc/library/typing.rst
Labels: docs, skip issue, awaiting merge, skip news, needs backport to 3.13

#133292 gh-133290: Use PyObject_SetAttr to set _type_
  Lib/test/test_ctypes/test_pointers.py
  Misc/NEWS.d/next/Library/2025-05-02-13-16-44.gh-issue-133290.R5WrLM.rst
  Modules/_ctypes/_ctypes.c
Labels: awaiting core review, needs backport to 3.13

#133280 gh-133279: Assert with HAS_TARGET in the codegen_addop_j function
  Python/codegen.c
Labels: awaiting merge, skip news

#132387 gh-132385: Fix instance error suggestions potential exceptions in `traceback`
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2025-04-11-12-41-47.gh-issue-132385.86HoA7.rst
Labels: awaiting merge, needs backport to 3.13

#133294 gh-133210: Fix `test_descr` in `--without-doc-strings` mode
  Lib/test/test_descr.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13

#132323 gh-130645: Add colour to `argparse` help
  Doc/library/argparse.rst
  Lib/_colorize.py
  Lib/argparse.py
  Lib/test/test_argparse.py
  Misc/NEWS.d/next/Library/2025-04-09-19-07-22.gh-issue-130645.cVfE1X.rst
Labels: type-feature, awaiting merge, stdlib

#133170 gh-133164: Add `PyUnstable_Object_IsUniqueReferencedTemporary` C API
  Doc/c-api/object.rst
  Doc/c-api/refcounting.rst
  Doc/whatsnew/3.14.rst
  Include/cpython/object.h
  Lib/test/test_capi/test_object.py
  Misc/NEWS.d/next/C_API/2025-04-29-19-39-16.gh-issue-133164.W-XTU7.rst
  Modules/_testcapi/object.c
  Objects/object.c
Labels: awaiting merge

#133298 [3.13] gh-133210: Fix `test_descr` in `--without-doc-strings` mode (GH-133294)
  Lib/test/test_descr.py
Labels: tests, awaiting review, skip news

#133297 [3.13] gh-132385: Fix instance error suggestions trigger potential exceptions in `traceback` (GH-132387)
  Lib/test/test_traceback.py
  Lib/traceback.py
  Misc/NEWS.d/next/Library/2025-04-11-12-41-47.gh-issue-132385.86HoA7.rst
Labels: awaiting review

#133302 gh-133300: argparse: make `suggest_on_error` a keyword-only parameter
  Doc/library/argparse.rst
  Lib/argparse.py
  Misc/NEWS.d/next/Library/2025-05-02-17-23-41.gh-issue-133300.oAh1P2.rst
Labels: type-feature, awaiting merge

#133295 [3.13] gh-133290: Use PyObject_SetAttr to set _type_ (GH-133292)
  Lib/test/test_ctypes/test_pointers.py
  Misc/NEWS.d/next/Library/2025-05-02-13-16-44.gh-issue-133290.R5WrLM.rst
  Modules/_ctypes/_ctypes.c
Labels: awaiting review

#132864 gh-121249: unconditionally support `complex` types in `struct`
  Doc/library/struct.rst
  Doc/whatsnew/3.14.rst
  Lib/test/test_struct.py
  Misc/NEWS.d/next/Library/2025-04-25-16-20-49.gh-issue-121249.uue2nK.rst
  Modules/_struct.c
Labels: awaiting merge, skip news

#133179 GH-133171: Prevent combinations of `--disable-gil` and `--enable-experimental-jit` (for now)
  .github/workflows/jit.yml
  Misc/NEWS.d/next/Build/2025-04-29-15-29-11.gh-issue-133171.YbwbwP.rst
  PCbuild/build.bat
  configure
  configure.ac
Labels: awaiting core review, build, topic-free-threading, topic-JIT

#132746 gh-132744: Check recursion limit in _PY_FRAME_GENERAL
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Lib/test/test_opcache.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-04-20-10-37-39.gh-issue-132744.ArrCp8.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_cases.c.h
Labels: awaiting merge

#126598 gh-112936: Fix IDLE: no Shell menu item in single-process mode
  Lib/idlelib/pyshell.py
  Misc/NEWS.d/next/IDLE/2024-11-08-18-07-13.gh-issue-112936.1Q2RcP.rst
Labels: awaiting merge, needs backport to 3.13

#133310 [3.13] gh-112936: Fix IDLE: no Shell menu item in single-process mode (GH-126598)
  Lib/idlelib/pyshell.py
  Misc/NEWS.d/next/IDLE/2024-11-08-18-07-13.gh-issue-112936.1Q2RcP.rst
Labels: awaiting review

#133247 gh-131507: Add support for syntax highlighting in PyREPL
  Doc/whatsnew/3.14.rst
  Lib/_colorize.py
  Lib/_pyrepl/_module_completer.py
  Lib/_pyrepl/commands.py
  Lib/_pyrepl/mypy.ini
  Lib/_pyrepl/reader.py
  Lib/_pyrepl/readline.py
  Lib/_pyrepl/simple_interact.py
  Lib/_pyrepl/unix_console.py
  Lib/_pyrepl/utils.py
  Lib/_pyrepl/windows_console.py
  Lib/test/test_pyrepl/test_pyrepl.py
  Lib/test/test_pyrepl/test_reader.py
  Lib/test/test_pyrepl/test_unix_console.py
  Lib/test/test_pyrepl/test_utils.py
  Lib/test/test_pyrepl/test_windows_console.py
  Lib/token.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-21-19-03-42.gh-issue-131507.q9fvyM.rst
  Misc/mypy/token.py
  Misc/mypy/typed-stdlib.txt
  Tools/build/generate_token.py
Labels: awaiting merge, topic-repl

#133317 Lint: Use Ruff to format ``Tools/build/check_warnings.py``
  .pre-commit-config.yaml
  Tools/build/.ruff.toml
  Tools/build/check_warnings.py
Labels: skip issue, awaiting merge, skip news

#132970 gh-91048: Chain some exceptions in _testexternalinspection.c
  Modules/_testexternalinspection.c
  Python/remote_debug.h
Labels: awaiting merge, skip news

#132885 gh-91156: Document how TextIOWrapper interacts with UTF-8 mode
  Doc/library/io.rst
Labels: docs, awaiting merge, skip news, needs backport to 3.13

#133323 [3.13] gh-91156: Document how TextIOWrapper interacts with UTF-8 mode (GH-132885)
  Doc/library/io.rst
Labels: docs, awaiting merge, skip news

#133084 gh-133037: Add test for shadowing __annotate__
  Lib/test/test_type_annotations.py
Labels: tests, awaiting core review, skip news

#133289 gh-133194: Fix regression with PEP 758 parsing on older `feature_version`
  Grammar/python.gram
  Lib/test/test_ast/test_ast.py
  Parser/parser.c
Labels: awaiting merge, skip news

#133330 gh-114713: Revert gh-114731
  Lib/test/test_zoneinfo/test_zoneinfo.py
  Lib/zoneinfo/_tzpath.py
  Misc/NEWS.d/next/Library/2025-03-09-01-09-12.gh-issue-114713.lkq9vZ.rst
Labels: awaiting core review, skip news, needs backport to 3.13

#133314 gh-133306: Support \z as a synonym for \Z in regular expressions
  Doc/howto/regex.rst
  Doc/library/re.rst
  Doc/whatsnew/3.14.rst
  Lib/re/__init__.py
  Lib/re/_parser.py
  Lib/test/re_tests.py
  Lib/test/test_re.py
  Misc/NEWS.d/next/Library/2025-05-02-21-35-03.gh-issue-133306.-vBye5.rst
Labels: awaiting merge

#133331 [3.13] gh-114713: Revert gh-114731 (GH-133330)
  Lib/test/test_zoneinfo/test_zoneinfo.py
  Lib/zoneinfo/_tzpath.py
  Misc/NEWS.d/next/Library/2025-03-09-01-09-12.gh-issue-114713.lkq9vZ.rst
Labels: awaiting review, skip news

#131542 gh-131524: Update platform CLI to use argparse
  Lib/platform.py
  Lib/test/test_platform.py
  Misc/NEWS.d/next/Library/2025-03-21-17-34-27.gh-issue-131524.Vj1pO_.rst
Labels: awaiting merge

#133335 gh-130160: use `.. program::` directive for documenting `platform` CLI
  Doc/library/cmdline.rst
  Doc/library/platform.rst
Labels: docs, awaiting merge, skip news

#133206 gh-133117: Enable stricter mypy checks for `tomllib`
  Lib/tomllib/_parser.py
  Lib/tomllib/_re.py
  Lib/tomllib/mypy.ini
Labels: awaiting core review, skip news, needs backport to 3.13

#133343 [3.13] gh-133117: Enable stricter mypy checks for `tomllib` (GH-133206)
  Lib/tomllib/_parser.py
  Lib/tomllib/_re.py
  Lib/tomllib/mypy.ini
Labels: awaiting merge, skip news

#133338 gh-133306: Use \z instead of \Z in fnmatch.translate() and glob.translate()
  Doc/library/fnmatch.rst
  Doc/library/glob.rst
  Lib/fnmatch.py
  Lib/glob.py
  Lib/test/test_fnmatch.py
  Lib/test/test_glob.py
  Misc/NEWS.d/next/Library/2025-05-03-13-19-22.gh-issue-133306.ustKV3.rst
Labels: awaiting merge

#133337 gh-133306: Use \z instead of \Z in regular expressions in the stdlib
  Lib/_py_warnings.py
  Lib/_pydecimal.py
  Lib/email/feedparser.py
  Lib/fractions.py
  Lib/idlelib/pyshell.py
  Lib/test/test_asyncio/test_locks.py
  Lib/test/test_gc.py
  Lib/test/test_import/__init__.py
  Lib/test/test_logging.py
  Lib/test/test_strtod.py
  Lib/test/test_tkinter/widget_tests.py
  Lib/test/test_ttk/test_widgets.py
  Lib/textwrap.py
  Lib/tokenize.py
  Lib/urllib/parse.py
  Lib/zipfile/_path/glob.py
Labels: awaiting merge, skip news

#133328 gh-133304: workaround for RISC-V in PyFloat_Pack4/Unpack4()
  Lib/test/test_capi/test_float.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-03-07-41-21.gh-issue-133304.YMuSne.rst
  Objects/floatobject.c
Labels: awaiting merge, 3.14

#133321 gh-123299: Add PyREPL syntax highlighting to release highlights
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting core review, skip news

#133332 gh-133210: Fix `test_rlcompleter` in `--without-doc-strings` mode
  Lib/test/test_rlcompleter.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13

#133348 [3.13] gh-133210: Fix `test_rlcompleter` in `--without-doc-strings` mode (GH-133332)
  Lib/test/test_rlcompleter.py
Labels: tests, awaiting review, skip news

#133344 gh-123539: Add new error message changes to "Whats New"
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#133145 gh-133139: Add curses.assume_default_colors()
  Doc/library/curses.rst
  Doc/whatsnew/3.14.rst
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2025-04-29-13-40-05.gh-issue-133139.9yCcC2.rst
  Modules/_cursesmodule.c
  Modules/clinic/_cursesmodule.c.h
Labels: awaiting merge

#133284 GH-91048: Add utils for printing the call stack for asyncio tasks
  Doc/whatsnew/3.14.rst
  Lib/asyncio/__main__.py
  Lib/asyncio/tools.py
  Lib/test/test_asyncio/test_tools.py
  Lib/test/test_external_inspection.py
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-03-19-04-03.gh-issue-91048.S8QWSw.rst
  Modules/Setup
  Modules/Setup.stdlib.in
  Modules/_remotedebuggingmodule.c
  PCbuild/_remotedebugging.vcxproj
  PCbuild/_remotedebugging.vcxproj.filters
  PCbuild/pcbuild.proj
  PCbuild/pcbuild.sln
  Tools/build/generate_stdlib_module_names.py
  configure
  configure.ac
Labels: awaiting merge

#133027 gh-132983: Introduce `_zstd` bindings module
  Doc/license.rst
  Include/internal/pycore_global_objects_fini_generated.h
  Include/internal/pycore_global_strings.h
  Include/internal/pycore_runtime_init_generated.h
  Include/internal/pycore_unicodeobject_generated.h
  Makefile.pre.in
  Modules/Setup
  Modules/Setup.stdlib.in
  Modules/_zstd/_zstdmodule.c
  Modules/_zstd/_zstdmodule.h
  Modules/_zstd/buffer.h
  Modules/_zstd/clinic/_zstdmodule.c.h
  Modules/_zstd/clinic/compressor.c.h
  Modules/_zstd/clinic/decompressor.c.h
  Modules/_zstd/clinic/zdict.c.h
  Modules/_zstd/compressor.c
  Modules/_zstd/decompressor.c
  Modules/_zstd/zdict.c
  Python/stdlib_module_names.h
  Tools/c-analyzer/cpython/ignored.tsv
  configure
  configure.ac
  pyconfig.h.in
Labels: awaiting merge, skip news

#133364 gh-133363: Fix Cmd completion for lines beginning with `! `
  Lib/cmd.py
  Lib/test/test_cmd.py
  Misc/NEWS.d/next/Library/2025-05-03-21-55-33.gh-issue-133363.PTLnRP.rst
Labels: awaiting merge

#133287 GH-133231: Changes to executor management to support proposed `sys._jit` module
  Include/cpython/pystate.h
  Include/internal/pycore_interp_structs.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_optimizer.h
  Include/internal/pycore_uop_metadata.h
  Python/bytecodes.c
  Python/ceval.c
  Python/ceval_macros.h
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer.c
  Python/pystate.c
  Tools/jit/template.c
Labels: awaiting merge, skip news

#26226 bpo-44172: Keep reference to original window in curses subwindow objects
  Include/py_curses.h
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2021-05-18-19-12-58.bpo-44172.rJ_-CI.rst
  Modules/_cursesmodule.c
Labels: awaiting review, OS-netbsd

#133370 [3.13] bpo-44172: Keep reference to original window in curses subwindow objects (GH-26226)
  Include/py_curses.h
  Lib/test/test_curses.py
  Misc/NEWS.d/next/Library/2021-05-18-19-12-58.bpo-44172.rJ_-CI.rst
  Modules/_cursesmodule.c
Labels: awaiting core review

#133358 gh-69605: Add PyREPL import autocomplete feature to 'What's New'
  Doc/whatsnew/3.14.rst
Labels: docs, awaiting merge, skip news

#122628 gh-122559: Synchronize C and Python implementation of the io module about pickling
  Lib/test/test_io.py
  Misc/NEWS.d/next/Library/2024-08-02-20-01-36.gh-issue-122559.2JlJr3.rst
  Modules/_io/bufferedio.c
  Modules/_io/fileio.c
  Modules/_io/textio.c
Labels: awaiting core review, needs backport to 3.12, needs backport to 3.13

#132517 gh-81793: Always call linkat() from os.link(), if available
  Doc/library/os.rst
  Lib/test/test_inspect/test_inspect.py
  Lib/test/test_posix.py
  Misc/NEWS.d/next/Library/2025-04-14-17-24-50.gh-issue-81793.OhRTTT.rst
  Modules/clinic/posixmodule.c.h
  Modules/posixmodule.c
Labels: awaiting core review

#132490 gh-132426: Add get_annotate_from_class_namespace replacing get_annotate_function
  Doc/library/annotationlib.rst
  Doc/reference/datamodel.rst
  Lib/annotationlib.py
  Lib/test/test_annotationlib.py
  Lib/typing.py
  Misc/NEWS.d/next/Library/2025-04-13-21-11-11.gh-issue-132426.SZno1d.rst
Labels: awaiting core review

#132812 gh-132805: annotationlib: Fix handling of non-constant values in FORWARDREF
  Lib/annotationlib.py
  Lib/test/test_annotationlib.py
  Misc/NEWS.d/next/Library/2025-04-22-13-42-12.gh-issue-132805.r-dhmJ.rst
Labels: awaiting core review

#133381 [3.13] gh-122559: Synchronize C and Python implementation of the io module about pickling (GH-122628)
  Lib/test/test_io.py
  Misc/NEWS.d/next/Library/2024-08-02-20-01-36.gh-issue-122559.2JlJr3.rst
  Modules/_io/bufferedio.c
  Modules/_io/fileio.c
  Modules/_io/textio.c
Labels: awaiting core review

#132460 gh-132457: make staticmethod and classmethod generic
  Lib/test/test_genericalias.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-04-13-01-50-40.gh-issue-132457.1q-1xz.rst
  Objects/funcobject.c
Labels: awaiting merge

#133368 gh-133141: Relax test_async_global_awaited_by to fix flakyness
  Lib/test/test_external_inspection.py
Labels: awaiting core review, skip news

#133388 gh-81793: Skip tests for os.link() to symlink on Android
  Lib/test/test_posix.py
Labels: tests, awaiting core review, skip news

#109946 gh-109700: Improve stress tests for interpreter creation
  Lib/test/test_interpreters/test_stress.py
Labels: tests, awaiting core review, skip news, needs backport to 3.13

#133391 [3.13] gh-109700: Improve stress tests for interpreter creation (GH-109946)
  Lib/test/test_interpreters/test_stress.py
Labels: tests, awaiting review, skip news

#133387 gh-133351: Fix remote PDB's multi-line block tab completion
  Lib/pdb.py
  Lib/test/test_remote_pdb.py
  Misc/NEWS.d/next/Library/2025-05-04-13-46-20.gh-issue-133351.YsZls1.rst
Labels: awaiting merge

#133064 gh-133042: disable HACL* HMAC on Emscripten
  configure
  configure.ac
Labels: awaiting merge, skip news

#133394 Regenerate pcbuild.sln in Visual Studio 2022
  PCbuild/pcbuild.sln
Labels: OS-windows, skip issue, awaiting core review, skip news, build

#133329 gh-131178: Add tests for `ast` command-line interface
  Lib/ast.py
  Lib/test/test_ast/test_ast.py
Labels: awaiting merge, skip news

#133385 gh-91048: Add filename and line number to external inspection routines
  Lib/asyncio/tools.py
  Lib/test/test_external_inspection.py
  Modules/_remotedebuggingmodule.c
Labels: awaiting core review, skip news

#132818 gh-125618: Make FORWARDREF format succeed more often
  Doc/library/annotationlib.rst
  Lib/annotationlib.py
  Lib/test/test_annotationlib.py
  Misc/NEWS.d/next/Library/2025-04-22-16-35-37.gh-issue-125618.PEocn3.rst
Labels: awaiting core review

#133408 gh-131421: Fix ASDL tests
  Lib/test/test_asdl_parser.py
  Parser/asdl.py
Labels: awaiting merge, skip news

#133398 GH-91048: Minor fixes for ``_remotedebugging`` & rename to ``_remote_debugging``
  Lib/asyncio/tools.py
  Lib/test/test_external_inspection.py
  Lib/test/test_sys.py
  Modules/Setup
  Modules/Setup.stdlib.in
  Modules/_remote_debugging_module.c
  PCbuild/_remote_debugging.vcxproj
  PCbuild/_remote_debugging.vcxproj.filters
  PCbuild/pcbuild.proj
  PCbuild/pcbuild.sln
  Python/stdlib_module_names.h
  Tools/build/generate_stdlib_module_names.py
  configure
  configure.ac
Labels: awaiting merge, skip news

#133378 gh-133376: build: allow parser.c to be created if missing
  Makefile.pre.in
Labels: awaiting merge, skip news

#133103 gh-133089: Use original timeout value for `TimeoutExpired` when the func `subprocess.run` is called with a timeout
  Doc/library/subprocess.rst
  Lib/subprocess.py
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Library/2025-04-29-02-23-04.gh-issue-133089.8Jy1ZS.rst
Labels: awaiting merge, needs backport to 3.13

#133418 [3.13] gh-133089: Use original timeout value for `TimeoutExpired` when the func `subprocess.run` is called with a timeout (GH-133103)
  Doc/library/subprocess.rst
  Lib/subprocess.py
  Lib/test/test_subprocess.py
  Misc/NEWS.d/next/Library/2025-04-29-02-23-04.gh-issue-133089.8Jy1ZS.rst
Labels: awaiting review

#133383 gh-133371: Don't optimize `LOAD_FAST` instructions whose local is killed by `DELETE_FAST`
  Include/internal/pycore_magic_number.h
  Lib/test/test_peepholer.py
  Python/flowgraph.c
Labels: awaiting merge, skip news

#133420 [tests] test_subprocess maybe avoid a timeout race condition?
  Lib/test/test_subprocess.py
Labels: tests, skip issue, awaiting core review, skip news, needs backport to 3.13

#133421 [3.13] [tests] test_subprocess maybe avoid a timeout race condition? (GH-133420)
  Lib/test/test_subprocess.py
Labels: tests, skip issue, awaiting review, skip news

#133422 [GH-133419] fix test_external_inspection race assert
  Lib/test/test_external_inspection.py
Labels: tests, awaiting core review, skip news

#128306 gh-128307: support eager_start kwarg in create_eager_task_factory, and pass kwargs from asyncio.create_task and TaskGroup.create_task
  Doc/library/asyncio-eventloop.rst
  Lib/asyncio/base_events.py
  Lib/asyncio/taskgroups.py
  Lib/asyncio/tasks.py
  Lib/test/test_asyncio/test_eager_task_factory.py
  Lib/test/test_asyncio/test_tasks.py
  Misc/NEWS.d/next/Library/2024-12-28-11-01-36.gh-issue-128307.BRCYTA.rst
Labels: awaiting merge

#133355 gh-113081: Highlight source code in pdb
  Doc/library/pdb.rst
  Doc/whatsnew/3.14.rst
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2025-05-03-18-48-54.gh-issue-113081.JsLJ1X.rst
Labels: awaiting core review

#133416 GH-133410: Use commit hashes for change detection
  .github/workflows/reusable-context.yml
  Tools/build/compute-changes.py
Labels: awaiting merge, skip news, infra

#133237 gh-61103: don't use native complex types in ctypes
  Makefile.pre.in
  Modules/_complex.h
  Modules/_ctypes/_ctypes_test.c
  Modules/_ctypes/callproc.c
  Modules/_ctypes/cfield.c
  Modules/_ctypes/ctypes.h
  Modules/_struct.c
Labels: awaiting merge, skip news

#133405 Bump mypy to 1.15
  Lib/_pyrepl/commands.py
  Lib/test/libregrtest/setup.py
  Tools/requirements-dev.txt
Labels: skip issue, awaiting merge, skip news

#133429 [3.13] Bump mypy to 1.15 (GH-133405)
  Lib/_pyrepl/commands.py
  Lib/test/libregrtest/setup.py
  Tools/requirements-dev.txt
Labels: skip issue, awaiting review, skip news

#133433 gh-133419: fix test_external_inspection race assert
  Lib/test/test_external_inspection.py
Labels: tests, awaiting merge, skip news

#133431 GH-133261: Make sure that the GC doesn't untrack objects in trashcan
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-05-12-03-46.gh-issue-133261.bL1gqz.rst
  Objects/object.c
  Python/gc.c
Labels: awaiting merge

#133432 [3.13] gh-107006: Move `threading.local` docstring to docs (GH-131840)
  Doc/library/threading.rst
  Lib/_threading_local.py
  Misc/NEWS.d/next/Documentation/2025-03-28-18-25-43.gh-issue-107006.BxFijD.rst
Labels: awaiting merge

#131910 gh-131878: Handle top level exceptions in new pyrepl and prevent of closing it
  Lib/_pyrepl/simple_interact.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-30-19-58-14.gh-issue-131878.uxM26H.rst
Labels: awaiting review, needs backport to 3.13

#133434 Revert "gh-124715: Fix method_dealloc(): use PyObject_GC_UnTrack() (#133199)"
  Objects/classobject.c
Labels: awaiting core review, skip news

#133444 GH-133336: Remove reserved ``-J`` flag for Jython
  Doc/using/cmdline.rst
  Doc/whatsnew/2.6.rst
  Doc/whatsnew/3.14.rst
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-05-15-33-35.gh-issue-133336.miffFi.rst
  Python/getopt.c
Labels: awaiting merge

#133445 [3.13] gh-131878: Handle top level exceptions in new pyrepl and prevent of closing it (GH-131910)
  Lib/_pyrepl/simple_interact.py
  Misc/NEWS.d/next/Core and Builtins/2025-03-30-19-58-14.gh-issue-131878.uxM26H.rst
Labels: awaiting core review

#133407 gh-119180: Make the FORWARDREF format work with more kinds of runtime errors
  Lib/annotationlib.py
  Lib/test/test_annotationlib.py
  Misc/NEWS.d/next/Library/2025-05-04-15-39-25.gh-issue-119180.avZ3Hm.rst
Labels: awaiting core review

#130725 gh-110067: Make max heap methods public and add missing ones
  Doc/library/heapq.rst
  Doc/whatsnew/3.14.rst
  Lib/heapq.py
  Lib/test/test_heapq.py
  Misc/NEWS.d/next/Library/2025-03-01-15-00-00.gh-issue-110067.1ad3as.rst
  Modules/_heapqmodule.c
  Modules/clinic/_heapqmodule.c.h
Labels: awaiting merge

#133026 gh-63882: Break down `and` tests in `test_minidom`
  Lib/test/test_minidom.py
Labels: tests, awaiting merge, skip news, needs backport to 3.13

#131901 gh-131878: Fix input of unicode characters with two or more code points in new pyrepl on Windows
  Lib/_pyrepl/base_eventqueue.py
  Lib/_pyrepl/windows_console.py
  Lib/test/test_pyrepl/test_eventqueue.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-03-30-19-49-00.gh-issue-131878.J8_cHB.rst
Labels: awaiting merge

#133451 [3.13] gh-63882: Break down `and` tests in `test_minidom` (GH-133026)
  Lib/test/test_minidom.py
Labels: tests, awaiting review, skip news

#133142 gh-131296: Fix clang-cl warning on Windows in `posixmodule.c`
  Modules/posixmodule.c
Labels: awaiting core review, skip news

#132440 GH-132439: Fix REPL swallowing characters entered with AltGr
  Lib/_pyrepl/windows_console.py
  Lib/test/test_pyrepl/test_windows_console.py
  Misc/NEWS.d/next/Library/2025-04-12-16-29-42.gh-issue-132439.3twrU6.rst
Labels: OS-windows, awaiting merge, needs backport to 3.13, topic-repl

#133396 gh-133395: add option for extension modules to specialize BINARY_OP/SUBSCR, apply to arrays
  Include/cpython/object.h
  Include/internal/pycore_code.h
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_metadata.h
  Include/typeslots.h
  Lib/test/test_sys.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-04-19-32-47.gh-issue-133395.VhWWEP.rst
  Modules/arraymodule.c
  Objects/typeslots.inc
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_cases.c.h
  Python/specialize.c
Labels: awaiting merge

#132610 GH-123599: `url2pathname()`: don't call `gethostbyname()` by default
  Doc/library/pathlib.rst
  Doc/library/urllib.request.rst
  Doc/whatsnew/3.14.rst
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_urllib.py
  Lib/urllib/request.py
  Misc/NEWS.d/next/Library/2024-11-14-21-17-48.gh-issue-126838.Yr5vKF.rst
Labels: awaiting merge

#133399 gh-132917: Check resident set size (RSS) before GC trigger.
  Doc/library/gc.rst
  Include/internal/pycore_interp_structs.h
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-04-14-47-26.gh-issue-132917.DrEU1y.rst
  Python/gc_free_threading.c
Labels: performance, awaiting merge, topic-free-threading

#133369 gh-133367: Add missing options to `ast` CLI
  Doc/library/ast.rst
  Doc/whatsnew/3.14.rst
  Lib/ast.py
  Lib/test/test_ast/test_ast.py
  Misc/NEWS.d/next/Library/2025-05-04-13-40-05.gh-issue-133367.E5nl2u.rst
Labels: awaiting merge

#133427 [3.13] GH-133410: Use commit hashes for change detection (gh-133416)
  .github/workflows/reusable-context.yml
  Tools/build/compute-changes.py
Labels: awaiting review, skip news

#133380 gh-130645: Add color to stdlib argparse CLIs
  Lib/ast.py
  Lib/calendar.py
  Lib/code.py
  Lib/compileall.py
  Lib/dis.py
  Lib/doctest.py
  Lib/ensurepip/__init__.py
  Lib/gzip.py
  Lib/http/server.py
  Lib/inspect.py
  Lib/json/tool.py
  Lib/mimetypes.py
  Lib/pdb.py
  Lib/pickle.py
  Lib/pickletools.py
  Lib/platform.py
  Lib/py_compile.py
  Lib/random.py
  Lib/sqlite3/__main__.py
  Lib/tarfile.py
  Lib/test/test_ast/test_ast.py
  Lib/test/test_calendar.py
  Lib/test/test_mimetypes.py
  Lib/test/test_pickle.py
  Lib/test/test_platform.py
  Lib/test/test_random.py
  Lib/test/test_sqlite3/test_cli.py
  Lib/tokenize.py
  Lib/trace.py
  Lib/unittest/main.py
  Lib/uuid.py
  Lib/venv/__init__.py
  Lib/webbrowser.py
  Lib/zipapp.py
  Lib/zipfile/__init__.py
  Misc/NEWS.d/next/Library/2025-05-04-16-00-01.gh-issue-130645.yNwKue.rst
Labels: awaiting merge

#133350 gh-133349: Enable auto-indent for pdb's multi-line mode
  Doc/whatsnew/3.14.rst
  Lib/pdb.py
  Lib/test/test_pdb.py
  Misc/NEWS.d/next/Library/2025-05-03-16-04-04.gh-issue-133349.kAhJDY.rst
Labels: awaiting merge

#133144 gh-133140: Add `PyUnstable_Object_IsUniquelyReferenced` for free-threading
  Doc/c-api/object.rst
  Doc/c-api/refcounting.rst
  Doc/whatsnew/3.14.rst
  Include/cpython/object.h
  Lib/test/test_capi/test_object.py
  Misc/NEWS.d/next/C_API/2025-04-29-06-27-46.gh-issue-133140.IPGGc3.rst
  Modules/_testcapi/object.c
  Objects/object.c
Labels: awaiting merge, topic-C-API, topic-free-threading

#133223 gh-132975: Improve Remote PDB interrupt handling
  Lib/pdb.py
  Lib/test/test_remote_pdb.py
  Misc/NEWS.d/next/Library/2025-05-01-18-32-44.gh-issue-133223.KE_T5f.rst
Labels: awaiting merge

#133462 [3.13] gh-130804: Fix support of typing unicode chars in pyrepl (GH-130805)
  Lib/_pyrepl/base_eventqueue.py
  Lib/test/test_pyrepl/test_eventqueue.py
  Misc/NEWS.d/next/Core and Builtins/2025-03-10-21-46-37.gh-issue-130804.0PpcTx.rst
Labels: awaiting core review

#133450 GH-133261: Make sure trashcan pointers look mortal -- 32 bit
  Objects/object.c
Labels: awaiting merge, skip news

#132918 gh-132017: Handle SIGCONT in `pyrepl`
  Lib/_pyrepl/unix_console.py
  Misc/NEWS.d/next/Library/2025-04-25-10-51-00.gh-issue-132017.SIGCONT1.rst
Labels: awaiting merge, needs backport to 3.13, topic-repl

#133468 [3.13] gh-131878: Fix input of unicode characters with two or more code points in new pyrepl on Windows (gh-131901)
  Lib/_pyrepl/base_eventqueue.py
  Lib/_pyrepl/windows_console.py
  Lib/test/test_pyrepl/test_eventqueue.py
  Misc/NEWS.d/next/Core and Builtins/2025-03-30-19-49-00.gh-issue-131878.J8_cHB.rst
Labels: awaiting core review

#133470 [3.13] gh-132017: Handle SIGCONT in `pyrepl` (#132918)
  Lib/_pyrepl/unix_console.py
  Misc/NEWS.d/next/Library/2025-04-25-10-51-00.gh-issue-132017.SIGCONT1.rst
Labels: awaiting review, topic-repl

#133464 gh-132917: Use RSS + swap for estimate of process memory usage
  Doc/library/gc.rst
  Include/internal/pycore_interp_structs.h
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-04-14-47-26.gh-issue-132917.DrEU1y.rst
  Python/gc_free_threading.c
Labels: awaiting merge, skip news, topic-free-threading

#133180 gh-131798: Split CALL_LEN into several uops
  Include/internal/pycore_opcode_metadata.h
  Include/internal/pycore_uop_ids.h
  Include/internal/pycore_uop_metadata.h
  Lib/test/test_capi/test_opt.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-04-30-00-21-54.gh-issue-131798.D6T5_u.rst
  Python/bytecodes.c
  Python/executor_cases.c.h
  Python/generated_cases.c.h
  Python/optimizer_bytecodes.c
  Python/optimizer_cases.c.h
  Python/specialize.c
Labels: awaiting merge

#133347 gh-133346: Make theming support in _colorize extensible
  Doc/whatsnew/3.14.rst
  Lib/_colorize.py
  Lib/_pyrepl/reader.py
  Lib/_pyrepl/utils.py
  Lib/argparse.py
  Lib/asyncio/__main__.py
  Lib/json/tool.py
  Lib/pdb.py
  Lib/test/support/__init__.py
  Lib/test/test_argparse.py
  Lib/test/test_json/test_tool.py
  Lib/test/test_pdb.py
  Lib/test/test_pyrepl/support.py
  Lib/test/test_pyrepl/test_reader.py
  Lib/test/test_pyrepl/test_unix_console.py
  Lib/test/test_pyrepl/test_windows_console.py
  Lib/test/test_traceback.py
  Lib/traceback.py
  Lib/unittest/runner.py
  Misc/NEWS.d/next/Core_and_Builtins/2025-05-04-19-46-14.gh-issue-133346.nRXi4f.rst
Labels: awaiting merge

#133221 gh-132775: Add _PyCode_VerifyStateless()
  Include/internal/pycore_code.h
  Include/internal/pycore_function.h
  Include/internal/pycore_opcode_utils.h
  Lib/test/_code_definitions.py
  Lib/test/test_code.py
  Modules/_testinternalcapi.c
  Objects/codeobject.c
  Objects/funcobject.c
Labels: awaiting core review, skip news

#133471 gh-133469: Adds to advanced section on installing PyManager
  Doc/using/windows.rst
Labels: docs, awaiting core review, skip news

#133057 gh-118761: Add test_lazy_import for more modules
  Lib/test/test_ast/test_ast.py
  Lib/test/test_base64.py
  Lib/test/test_cmd.py
  Lib/test/test_csv.py
  Lib/test/test_email/test_utils.py
  Lib/test/test_enum.py
  Lib/test/test_functools.py
  Lib/test/test_gettext.py
  Lib/test/test_locale.py
  Lib/test/test_mimetypes.py
  Lib/test/test_optparse.py
  Lib/test/test_pathlib/test_pathlib.py
  Lib/test/test_pickle.py
  Lib/test/test_pprint.py
  Lib/test/test_pstats.py
  Lib/test/test_shlex.py
  Lib/test/test_socket.py
  Lib/test/test_string/test_string.py
  Lib/test/test_threading.py
  Lib/test/test_zipfile/test_core.py
Labels: tests, awaiting merge, skip news

#133478 gh-91048: Add filename:line_no information to `asyncio pstree`
  Lib/asyncio/__main__.py
  Lib/asyncio/tools.py
  Lib/test/test_asyncio/test_tools.py
Labels: awaiting merge, skip news

#133472 gh-132775: Do Not Set __name__ to __main__ With _PyPickle_GetXIData()
  Python/crossinterp.c
Labels: awaiting core review, skip news

#133475 gh-132775: Add _PyCode_GetXIData()
  Include/internal/pycore_crossinterp.h
  Lib/test/_code_definitions.py
  Lib/test/test_code.py
  Lib/test/test_crossinterp.py
  Modules/_testinternalcapi.c
  Python/crossinterp_data_lookup.h
Labels: awaiting core review, skip news

#133426 [3.12] GH-133410: Use commit hashes for change detection (gh-133416)
  .github/workflows/reusable-context.yml
  Tools/build/compute-changes.py
Labels: awaiting review, skip news

#133366 GH-132983: Build ``_zstd`` on Windows
  Misc/externals.spdx.json
  Modules/Setup
  Modules/Setup.stdlib.in
  Modules/_zstd/clinic/zstddict.c.h
  Modules/_zstd/zstddict.c
  PCbuild/_zstd.vcxproj
  PCbuild/_zstd.vcxproj.filters
  PCbuild/get_externals.bat
  PCbuild/pcbuild.proj
  PCbuild/pcbuild.sln
  PCbuild/python.props
  PCbuild/readme.txt
  PCbuild/regen.targets
  Tools/msi/freethreaded/freethreaded_files.wxs
  Tools/msi/lib/lib_files.wxs
  configure
  configure.ac
Labels: awaiting merge, skip news

#118655 gh-102567: Add -X importtime=2 for logging an importtime message for already-loaded modules
  Doc/c-api/init_config.rst
  Doc/using/cmdline.rst
  Doc/whatsnew/3.14.rst
  Lib/_pyrepl/unix_console.py
  Lib/_pyrepl/windows_console.py
  Lib/test/test_capi/test_config.py
  Lib/test/test_cmd_line.py
  Lib/test/test_embed.py
  Lib/test/test_support.py
  Misc/ACKS
  Misc/NEWS.d/next/Core_and_Builtins/2024-07-11-12-31-29.gh-issue-102567.weRqDn.rst
  Misc/python.man
  Programs/_testembed.c
  Python/import.c
  Python/initconfig.c
Labels: awaiting merge

#133479 GH-132983: Use a standard autoconf version check for zstd
  configure
  configure.ac
Labels: awaiting core review, skip news
